INSERT INTO words (word, phonetic, pos, level, def_en, ex_en, synonyms) VALUES
('Doggerel', '/ˈdɒɡəɹəl/', 'adjective', 'C1', 'Of a crude or irregular construction. (Originally applied to humorous verse, but now to verse lacking artistry or meaning.)', '', ARRAY[]::TEXT[]),
('Dogma', '/ˈdɒɡ.mə/', 'noun', 'C1', 'An authoritative principle, belief or statement of opinion, especially one considered to be absolutely true and indisputable, regardless of evidence or without evidence to support it.', 'In the Catholic Church, new dogmas can only be declared by the pope after the extremely rare procedure ex cathedra to make them part of the official faith.', ARRAY[]::TEXT[]),
('Doldrums', '/ˈdɒldɹəmz/', 'noun', 'C1', 'A slothful or stupid person.', '', ARRAY['dullard','dullard']::TEXT[]),
('Dolorous', '/ˈdoʊləɹəs/', 'adjective', 'C2', 'Solemnly or ponderously sad.', '', ARRAY[]::TEXT[]),
('Dolt', '/dɒlt/', 'verb', 'C1', 'To behave foolishly.', '', ARRAY[]::TEXT[]),
('Domicile', '/ˈdɑmɪsaɪl/', 'verb', 'C1', 'To have a domicile in a particular place.', 'The answer depends on which state he was domiciled in at his death.', ARRAY[]::TEXT[]),
('Domination', '/ˌdɒməˈneɪʃən/', 'noun', 'C1', 'Area or situation which screens a person or thing from view.', 'The soldiers took cover behind a ruined building.', ARRAY[]::TEXT[]),
('Don', '/dɒn/', 'noun', 'C1', 'A university professor, particularly one at Oxford or Cambridge.', '', ARRAY[]::TEXT[]),
('Doodle', '/ˈduː.dəl/', 'verb', 'C1', 'To draw or scribble aimlessly.', 'The bored student doodled a submarine in his notebook.', ARRAY[]::TEXT[]),
('Dormant', '/ˈdɔːmənt/', 'adjective', 'C1', 'Inactive, sleeping, asleep, suspended.', 'Grass goes dormant during the winter, waiting for spring before it grows again.', ARRAY['quiescent']::TEXT[]),
('Dour', '/ˈdaʊə/', 'adjective', 'C1', 'Stern, harsh and forbidding.', '', ARRAY['dejected','gloomy','melancholic','sullen','forbidding']::TEXT[]),
('Douse', '/daʊs/', 'verb', 'C1', 'To plunge suddenly into water; to duck; to immerse.', '', ARRAY[]::TEXT[]),
('Downplay', '', 'verb', 'C1', 'To de-emphasize; to present or portray as less important or consequential.', 'He would sometimes downplay his Princeton education by saying simply that he went to school in New Jersey.', ARRAY['trivialize','understate']::TEXT[]),
('Downpour', '/ˈdaʊn.pɔː(ɹ)/', 'verb', 'C1', 'To pour down; rain heavily.', '', ARRAY[]::TEXT[]),
('Doyen', '/dwɑˈjæ̃/', 'noun', 'C1', 'A commander in charge of ten men.', '', ARRAY[]::TEXT[]),
('Doze', '/doʊz/', 'verb', 'C1', 'To sleep lightly or briefly; to nap, snooze.', 'I didn’t sleep very well, but I think I may have dozed a bit.', ARRAY['slumber']::TEXT[]),
('Draconian', '/dɹækˈəʊ.ni.ən/', 'adjective', 'C1', 'Very severe or strict.', 'The Soviet regime was draconian.', ARRAY['Orwellian','cruel','hard','harsh','rigid']::TEXT[]),
('Drawl', '/dɹɔːl/', 'verb', 'C1', 'To drag on slowly and heavily; to while or dawdle away time indolently.', '', ARRAY[]::TEXT[]),
('Dreary', '/ˈdɹɪəɹi/', 'adjective', 'C1', 'Drab; dark, colorless, or cheerless.', 'It had rained for three days straight, and the dreary weather dragged the townspeople''''s spirits down.', ARRAY[]::TEXT[]),
('Drench', '/dɹɛntʃ/', 'verb', 'C1', 'To soak, to make very wet.', '', ARRAY[]::TEXT[]),
('Drivel', '/dɹɪv.əl/', 'verb', 'C1', 'To have saliva drip from the mouth; to drool.', '', ARRAY['drool']::TEXT[]),
('Drizzle', '/ˈdɹɪz.l/', 'verb', 'C1', 'To rain lightly.', 'We had planned a picnic for Joe''''s birthday, but it ended up drizzling all day.', ARRAY[]::TEXT[]),
('Effluvium', '/ɪˈfluːvi.əm/', 'noun', 'C1', 'A gaseous or vaporous emission, especially a foul-smelling one.', '', ARRAY[]::TEXT[]),
('Effrontery', '/ɛˈfɹʌntəɹi/', 'noun', 'C2', 'Insolent and shameless audacity.', 'We even had the effrontery to suggest that he should leave the country.', ARRAY[]::TEXT[]),
('Effusive', '/ɪˈfjuːsɪv/', 'adjective', 'C1', 'Gushy; unrestrained, extravagant or excessive (in emotional expression).', '', ARRAY[]::TEXT[]),
('Egalitarian', '/ɪˌɡæl.ɪˈtɛə.ɹi.ən/', 'adjective', 'C1', 'Characterized by social equality and equal rights for all people.', '', ARRAY['equalitarian']::TEXT[]),
('Egoism', '', 'noun', 'C1', 'The tendency to think selfishly with exclusive self-interest in mind.', '', ARRAY['selfishness']::TEXT[]),
('Elastic', '/iˈlæstɪk/', 'adjective', 'C1', 'Capable of stretching; particularly, capable of stretching so as to return to an original shape or size when force is released.', 'The rope is somewhat elastic, so expect it to give when you pull on it.', ARRAY['stretchable','stretchy']::TEXT[]),
('Elate', '/ɪˈleɪt/', 'adjective', 'C1', 'Elated; exultant', '', ARRAY[]::TEXT[]),
('Eleemosynary', '/ˌɛl.ɪ.iːˈmɒ.sɪ.nə.ɹi/', 'adjective', 'C1', 'Relating to charity, alms, or almsgiving.', '', ARRAY['charitable']::TEXT[]),
('Elegy', '/ˈɛlɪdʒi/', 'noun', 'C1', 'A mournful or plaintive poem; a funeral song; a poem of lamentation.', '', ARRAY['dirge','threnody']::TEXT[]),
('Elephantine', '/ɛl.ə.ˈfæn.taɪn/', 'adjective', 'C1', 'Of, pertaining to, or characteristic of elephants.', '', ARRAY['elephantic','elephantlike']::TEXT[]),
('Ellipsis', '/ɪˈlɪpsɪs/', 'noun', 'C1', 'A mark consisting of (in English) three periods, historically or more formally with spaces in between, before, and after them “ . . . ”, or more recently a single character “…” Ellipses are used to indicate that words have been omitted in a text or that they are missing or illegible.', '', ARRAY['dot dot dot','suspension dots','suspension points','dot dot dot','suspension dots']::TEXT[]),
('Elliptical', '/ɪˈlɪp.tɪk.əl/', 'adjective', 'C1', 'In a shape of, or reminding of, an ellipse; oval.', '', ARRAY['elliptic']::TEXT[]),
('Emancipate', '/ɪˈmænsɪpeɪt/', 'adjective', 'C1', 'Freed; set at liberty.', '', ARRAY[]::TEXT[]),
('Embargo', '/ɪmˈbɑːɡəʊ/', 'verb', 'C1', 'To impose an embargo on trading certain goods with another country.', '', ARRAY[]::TEXT[]),
('Embarrass', '/ɪmˈbæ.ɹəs/', 'verb', 'C1', 'To humiliate; to disrupt somebody''''s composure or comfort with acting publicly or freely; to disconcert; to abash', 'The crowd''''s laughter and jeers embarrassed him.', ARRAY['abash','discomfit','disconcert','humiliate','shame']::TEXT[]),
('Embezzle', '/əmˈbɛzəl/', 'verb', 'C1', 'To steal or misappropriate money that one has been trusted with, especially to steal money from the organisation for which one works.', '', ARRAY['defalcate','have one''''s hand in the till','misappropriate','peculate']::TEXT[]),
('Embolden', '/ɛmˈbəʊldən/', 'verb', 'C1', 'To render (someone) bolder or more courageous.', '', ARRAY['boldface','boldface']::TEXT[]),
('Emboss', '/ɪmˈbɒs/', 'verb', 'C1', 'To mark or decorate with a raised design or symbol.', 'The papers weren''''t official until the seal had been embossed on them.', ARRAY[]::TEXT[]),
('Embroider', '/ɪmˈbɹɔɪdə/', 'verb', 'C1', 'To stitch a decorative design on fabric with needle and thread of various colours.', '', ARRAY[]::TEXT[]),
('Emigrate', '/ˈɛmɪɡɹeɪt/', 'verb', 'C1', 'To leave the country in which one lives, especially one''''s native country, in order to reside elsewhere.', '', ARRAY[]::TEXT[]),
('Eminence', '/ˈɛmɪnəns/', 'noun', 'C1', 'Someone of high rank, reputation or social status.', '', ARRAY['celebrity','distinction','prominence','renown']::TEXT[]),
('Emollient', '/ɪˈmɒl.ɪ.ənt/', 'adjective', 'C1', 'Moisturizing.', '', ARRAY[]::TEXT[]),
('Enamel', '/ɪˈnæməl/', 'noun', 'C1', 'An opaque, glassy coating baked onto metal or ceramic objects.', '', ARRAY[]::TEXT[]),
('Encomium', '/ɛŋˈkəʊ.mɪ.əm/', 'noun', 'C1', 'Warm praise, especially a formal expression of such praise; a tribute.', '', ARRAY[]::TEXT[]),
('Encumber', '/ɛnˈkʌmbə(ɹ)/', 'verb', 'C2', 'To load down something with a burden', '', ARRAY[]::TEXT[]),
('Enfranchise', '/ɛnˈfɹænt͡ʃaɪz/', 'verb', 'C1', 'To grant the franchise to an entity, specifically:', '', ARRAY[]::TEXT[]),
('Engross', '/ɛnˈɡɹəʊs/', 'verb', 'C1', 'To write (a document) in large, aesthetic, and legible lettering; to make a finalized copy of.', 'She seems to be completely engrossed in that book.', ARRAY['amound','hoard','corner the market','inspissate','corner the market']::TEXT[]),
('Enigma', '/əˈnɪɡmə/', 'noun', 'C1', 'Something or someone puzzling, mysterious or inexplicable.', '', ARRAY[]::TEXT[]),
('Enlighten', '/ənˈlaɪtn̩/', 'verb', 'C1', 'To supply with light.', 'The sun enlightens the Earth.', ARRAY['apprise','inform','notify','illuminate','illumine']::TEXT[]),
('Ennoble', '', 'verb', 'C1', 'To bestow with nobility, honour or grace.', '', ARRAY['elevate','invest','knight','lord','elevate']::TEXT[]),
('Ennui', '/ɒnˈwiː/', 'verb', 'C1', 'To make bored or listless; to weary.', '', ARRAY[]::TEXT[]),
('Everlasting', '/ˌɛvəˈlɑːstɪŋ/', 'adjective', 'C1', 'Lasting or enduring forever; existing or continuing without end', 'this everlasting nonsense', ARRAY['continual','endless','eternal','immortal','incessant']::TEXT[]),
('Evict', '', 'verb', 'C1', 'To expel (one or more people) from their property; to force (one or more people) to move out.', '', ARRAY[]::TEXT[]),
('Evince', '/iˈvɪns/', 'verb', 'C1', 'To show or demonstrate clearly; to manifest.', '', ARRAY[]::TEXT[]),
('Ewe', '/joː/', 'noun', 'C1', 'A female sheep, as opposed to a ram.', '', ARRAY['yoe','yow','yowe']::TEXT[]),
('Excavate', '/ˈɛk.skə.veɪt/', 'verb', 'C1', 'To make a hole in (something); to hollow.', '', ARRAY[]::TEXT[]),
('Excerpt', '/ɛkˈsɜ(ɹ)(p)t/', 'verb', 'C1', 'To select or copy sample material (excerpts) from a work.', '', ARRAY[]::TEXT[]),
('Excoriate', '/ɪkˈskoʊɹ.iˌeɪt/', 'verb', 'C2', 'To wear off the skin of; to chafe or flay.', '', ARRAY['abrade','chafe','flay','condemn','disparage']::TEXT[]),
('Excrete', '/ɛkˈskɹiːt/', 'verb', 'C1', 'To discharge material (including waste products) from a cell, body or system.', '', ARRAY[]::TEXT[]),
('Excruciate', '/ɛk.ˈskɹu.si.eɪ̯t/', 'adjective', 'C1', 'Excruciated; tortured.', '', ARRAY[]::TEXT[]),
('Exculpate', '/ˈɛkskəlpeɪt/', 'verb', 'C1', 'To clear of or to free from guilt; exonerate.', '', ARRAY['absolve','acquit','disculpate','exonerate','pardon']::TEXT[]),
('Excursive', '', 'adjective', 'C1', 'Tending to digress.', '', ARRAY[]::TEXT[]),
('Execrate', '', 'verb', 'C2', 'To feel loathing for; to abhor', '', ARRAY['anathematize','comminate','curse','damn','imprecate']::TEXT[]),
('Exemplary', '/ɛɡˈzɛmpləɹi/', 'adjective', 'C1', 'Deserving honour, respect and admiration.', 'Her behaviour was always exemplary.', ARRAY['exemplar','admonitory']::TEXT[]),
('Exempt', '/ɛɡˈzɛm(p)t/', 'adjective', 'C1', 'Free from a duty or obligation.', 'His income is so small that it is exempt from tax.', ARRAY[]::TEXT[]),
('Exhaust', '/ɪɡˈzɔːst/', 'adjective', 'C1', 'Exhausted; used up.', '', ARRAY[]::TEXT[]),
('Exhilarate', '/ɛɡ-/', 'verb', 'C1', 'To cheer, to cheer up, to gladden, to make happy.', 'Good news exhilarates the mind; wine exhilarates the drinker.', ARRAY['enliven','stimulate']::TEXT[]),
('Exigent', '/ˈɛk.sɪ.dʒənt/', 'adjective', 'C1', 'Urgent; needing immediate action.', '', ARRAY[]::TEXT[]),
('Exodus', '/ˈɛksədəs/', 'verb', 'C1', 'To depart from a place in a large group.', '', ARRAY[]::TEXT[]),
('Exorbitant', '/ɛɡˈzɔːbɪtənt/', 'adjective', 'C2', 'Exceeding proper limits; extravagant; excessive or unduly high.', 'It''''s a nice car, but they are charging an exorbitant price for it.', ARRAY[]::TEXT[]),
('Expansive', '/ɪkˈspænsɪv/', 'adjective', 'C2', 'Comprehensive in scope or extent.', 'an expansive research work', ARRAY[]::TEXT[]),
('Expedite', '/ˈɛk.spəˌdaɪt/', 'adjective', 'C1', 'Free of impediment; unimpeded.', '', ARRAY[]::TEXT[]),
('Expiate', '/ˈɛk.spi.eɪt/', 'verb', 'C1', 'To atone or make reparation for.', '', ARRAY[]::TEXT[]),
('Exponent', '/ɛkˈspəʊnənt/', 'noun', 'C1', 'One who expounds, represents or advocates.', '', ARRAY['degree','power','power','power','degree']::TEXT[]),
('Expurgate', '/ˈɛks.pɚ.ɡeɪt/', 'verb', 'C2', 'To edit out (incorrect, offensive, or otherwise undesirable information) from a book or other publication; to cleanse; to purge.', 'The publisher decided to expurgate the love scene from the book, to make it more child-friendly.', ARRAY[]::TEXT[]),
('Exquisite', '/ɪkˈskwɪzɪt/', 'adjective', 'C1', 'Especially fine or pleasing; exceptional.', 'Sourav Ganguly scored an exquisite century in his debut Test match.', ARRAY['beautiful','delicate','discriminating','perfect']::TEXT[]),
('Extemporize', '', 'verb', 'C1', 'To do something, particularly to perform or speak, without prior planning or thought; to act in an impromptu manner; to improvise.', '', ARRAY['improvise','think on one''''s feet','devise','improvise']::TEXT[]),
('Extenuate', '/ɪkˈstɛnjueɪt/', 'verb', 'C1', 'To lessen; to palliate; to lessen or weaken the force of; to diminish the conception of, as crime, guilt, faults, ills, accusations, etc.', '', ARRAY['mitigate']::TEXT[]),
('Extinct', '/ɛkˈstɪŋkt/', 'adjective', 'C1', 'Extinguished, no longer alight (of fire, candles etc.)', 'Poor Edward''''s cigarillo was already extinct.', ARRAY['dead']::TEXT[]),
('Extinguish', '/ɪkˈstɪŋ.ɡwɪʃ/', 'verb', 'C1', 'To put out, as in fire; to end burning; to quench', 'She extinguished all my hopes.', ARRAY['douse','put out','quench']::TEXT[]),
('Extol', '/ɪkˈstəʊl/', 'verb', 'C1', 'To praise; to make high.', '', ARRAY['belaud','flatter','belaud','flatter']::TEXT[]),
('Extort', '/ɪkˈstɔː(ɹ)t/', 'adjective', 'C1', 'Wrongfully obtained.', '', ARRAY[]::TEXT[]),
('Extraction', '/ɪkˈstɹækʃən/', 'noun', 'C1', 'An act of extracting or the condition of being extracted.', '', ARRAY['descent','lineage','extract','reduction']::TEXT[]),
('Extraneous', '/ekˈstɹæɪ.ni.əs/', 'adjective', 'C1', 'Not belonging to, or dependent upon, a thing; without or beyond a thing; foreign', 'Extraneous substances were found on my cup of water.', ARRAY['additional','alien','foreign','intrusive','extra']::TEXT[]),
('Extravagant', '/ɪkˈstɹævəɡənt/', 'adjective', 'C1', 'Exceeding the bounds of something; roving; hence, foreign.', 'extravagant acts, praise, or abuse', ARRAY[]::TEXT[]),
('Extricate', '/ˈɛks.tɹɪ.keɪt/', 'verb', 'C1', 'To free, disengage, loosen, or untangle.', 'I finally managed to extricate myself from the tight jacket.', ARRAY[]::TEXT[]),
('Exuberant', '/ɪɡˈzuːbəɹənt/', 'adjective', 'C1', '(of people) Very high-spirited; extremely energetic and enthusiastic.', 'exuberant feeling', ARRAY['buoyant','cheerful','high-spirited','profuse','superabundant']::TEXT[]),
('Exude', '/ɪkˈsud/', 'verb', 'C1', 'To discharge through pores or incisions, as moisture or other liquid matter; to give out.', '', ARRAY[]::TEXT[]),
('Exult', '/ɪɡˈzʌlt/', 'verb', 'C1', 'To rejoice; to be very happy, especially in triumph.', '', ARRAY[]::TEXT[]),
('Fable', '/ˈfeɪbəl/', 'verb', 'C1', 'To compose fables; hence, to write or speak fiction; to write or utter what is not true.', '', ARRAY['devise','feign','invent','make up','devise']::TEXT[]),
('Fabricate', '/ˈfæb.ɹɪ.keɪt/', 'verb', 'C1', 'To form into a whole by uniting its parts; to construct; to build.', 'to fabricate a bridge or ship', ARRAY['cook up','invent','make up','manufacture','trump up']::TEXT[]),
('Facile', '/ˈfa.sʌɪl/', 'adjective', 'C2', 'Easy, now especially in a disparaging sense; contemptibly easy.', 'His facile disposition made him many friends.', ARRAY[]::TEXT[]),
('Fallacy', '/ˈfæləsi/', 'noun', 'C1', 'Deceptive or false appearance; that which misleads the eye or the mind.', '', ARRAY['deceitfulness','deception','deceitfulness','deception']::TEXT[]),
('Fallow', '/ˈfæləʊ/', 'adjective', 'C1', '(of agricultural land) Ploughed but left unseeded for more than one planting season.', 'a fallow period in one''''s career', ARRAY['abeyant','dormant','latent']::TEXT[]),
('Fail-safe', '/ˈfeɪlˌseɪf/', 'adjective', 'C1', 'That does not cause undue damage in the event of failure.', 'The system is failsafe, because everything is backed up automatically.', ARRAY[]::TEXT[]),
('Falsehood', '/ˈfɒlsˌhʊd/', 'noun', 'C1', 'The property of being false.', 'Don''''t tell falsehoods.', ARRAY['falseness','mendacity','lie','falsity']::TEXT[]),
('Falter', '/ˈfɒltə(r)/', 'verb', 'C1', 'To waver or be unsteady; to weaken or trail off.', '', ARRAY[]::TEXT[]),
('Fanatic', '/fəˈnæt.ɪk/', 'adjective', 'C1', 'Showing evidence of possession by a god or demon; frenzied, overzealous.', '', ARRAY[]::TEXT[]),
('Farce', '/fɑːs/', 'noun', 'C1', 'A style of humor marked by broad improbabilities with little regard to regularity or method.', 'The farce that we saw last night had us laughing and shaking our heads at the same time.', ARRAY[]::TEXT[]),
('Fascinate', '/ˈfæsɪneɪt/', 'verb', 'C1', 'To evoke an intense interest or attraction in someone.', 'The flickering TV fascinated the cat.', ARRAY[]::TEXT[]),
('Fateful', '/ˈfeɪtfəl/', 'adjective', 'C1', 'Momentous, significant, setting or sealing one’s fate.', 'It started with that fateful trip, history was never the same afterwards.', ARRAY[]::TEXT[]),
('Fathom', '/ˈfæðəm/', 'verb', 'C1', 'To encircle with outstretched arms, especially to take a measurement; to embrace.', 'I can''''t for the life of me fathom what this means.', ARRAY['fathom out','figure out','puzzle out','work out','fathom out']::TEXT[]),
('Fatigue', '/fəˈtiːɡ/', 'verb', 'C1', 'To tire or make weary by physical or mental exertion', '', ARRAY[]::TEXT[]),
('Fatuous', '/ˈfæt.ju.əs/', 'adjective', 'C1', 'Obnoxiously stupid, vacantly silly, content in one''''s foolishness.', '', ARRAY['childish','imbecilic','inane','insipid','puerile']::TEXT[]),
('Favorable', '', 'adjective', 'C1', 'Pleasing, encouraging or approving.', 'The candidate wearing the business suite made a favourable impression.', ARRAY['advantageous','helpful','useful','approving','encouraging']::TEXT[]),
('Faze', '/feɪz/', 'verb', 'C1', 'To frighten or cause hesitation; to daunt, put off (usually used in the negative); to disconcert, to perturb.', 'Jumping out of an airplane does not faze him, yet he is afraid to ride a roller coaster.', ARRAY[]::TEXT[]),
('Feckless', '/ˈfɛkləs/', 'adjective', 'C2', 'Lacking purpose.', '', ARRAY['feeble','futile','hopeless','ineffective','ineffectual']::TEXT[]),
('Fecund', '/ˈfɛ.kənd/', 'adjective', 'C2', 'Highly fertile; able to produce offspring.', '', ARRAY['fertile','fertile','productive','prolific']::TEXT[]),
('Feeble', '/ˈfiːbəl/', 'adjective', 'C1', 'Deficient in physical strength', 'Though she appeared old and feeble, she could still throw a ball.', ARRAY['debilitated','infirm','weak','faint']::TEXT[]),
('Feign', '/feɪn/', 'verb', 'C1', 'To make a false show or pretence of; to counterfeit or simulate.', 'The pupil feigned sickness on the day of his exam.', ARRAY['front','put on airs']::TEXT[]),
('Fender', '/ˈfɛnd.ə(ɹ)/', 'verb', 'C1', 'To use fenders to protect the side of a boat', '', ARRAY[]::TEXT[]),
('Feral', '/ˈfɛɹəl/', 'adjective', 'C1', 'Wild, untamed, especially of domesticated animals having returned to the wild.', '', ARRAY[]::TEXT[]),
('Ferrous', '/ˈfɛɹəs/', 'adjective', 'C1', 'Of or containing iron.', '', ARRAY[]::TEXT[]),
('Fertilize', '/ˈfɜː(ɹ)tɪlaɪz/', 'verb', 'C1', 'To make (the soil) more fertile by adding nutrients to it.', 'to fertilize one''''s imagination', ARRAY[]::TEXT[]),
('Fervid', '/ˈfɜː.vɪd/', 'adjective', 'C1', 'Intensely hot, emotional, or zealous.', '', ARRAY['ardent','fervent','zealous']::TEXT[]),
('Fervor', '/ˈfɝvɚ/', 'noun', 'C1', 'An intense, heated emotion; passion, ardor.', 'The coach trains his water polo team with fervor.', ARRAY['fire in the belly','zeal']::TEXT[]),
('Fester', '/ˈfɛstə(ɹ)/', 'verb', 'C1', 'To become septic; to become rotten.', 'Deal with the problem immediately; do not let it fester.', ARRAY[]::TEXT[]),
('Fetid', '/ˈfɛtɪd/', 'adjective', 'C1', 'Foul-smelling, stinking.', 'I caught the fetid odor of dirty socks.', ARRAY[]::TEXT[]),
('Fetter', '/ˈfet.ə/', 'verb', 'C1', 'To shackle or bind up with fetters.', '', ARRAY[]::TEXT[]),
('Fiasco', '/fɪˈæs.kəʊ/', 'noun', 'C1', 'A sudden or unexpected failure.', '', ARRAY['debacle','debacle']::TEXT[]),
('Fictitious', '/fɪkˈtɪʃəs/', 'adjective', 'C1', 'Invented; contrived.', '', ARRAY['contrived','fictive','imaginary','invented','contrived']::TEXT[]),
('Fidelity', '/faɪˈdɛl.ɪ.ti/', 'noun', 'C1', 'Faithfulness to one''''s duties.', 'the fidelity of the civil servants', ARRAY[]::TEXT[]),
('Fidget', '/ˈfɪdʒ.ɪt/', 'verb', 'C1', 'To wiggle or twitch; to move around nervously or idly.', '', ARRAY[]::TEXT[]),
('Figurative', '/ˈfɪɡəɹətɪv/', 'adjective', 'C1', 'Of use as a metaphor, simile, or metonym, as opposed to literal; using figures; as when saying that someone who eats more than they should is a pig or like a pig.', '', ARRAY[]::TEXT[]),
('Figurehead', '/ˈfɪɡjəɹˌhɛd/', 'noun', 'C1', 'A carved figure on the prow of a sailing ship.', '', ARRAY[]::TEXT[]),
('Figurine', '/fɪɡəˈɹin/', 'noun', 'C1', 'A small carved or molded figure; a statuette.', '', ARRAY[]::TEXT[]),
('Filibuster', '/ˈfɪlɪbʌstə(ɹ)/', 'verb', 'C1', 'To take part in a private military action in a foreign country.', '', ARRAY[]::TEXT[]),
('Filigree', '/ˈfɪl.ɪ.ɡɹiː/', 'verb', 'C1', 'To decorate something with intricate ornamentation made from gold or silver twisted wire.', '', ARRAY[]::TEXT[]),
('Filing', '/faɪ.lɪŋ/', 'verb', 'C1', 'To commit (official papers) to some office.', 'She filed for divorce the next day.', ARRAY[]::TEXT[]),
('Filly', '/ˈfɪli/', 'noun', 'C1', 'A young female horse.', 'Hey, Homer, get a load of the gams on that filly!', ARRAY[]::TEXT[]),
('Finale', '', 'noun', 'C1', 'The grand end of something, especially a show or piece of music.', '', ARRAY[]::TEXT[]),
('Finch', '/fɪntʃ/', 'verb', 'C1', 'To hunt for finches, to go finching.', '', ARRAY[]::TEXT[]),
('Finesse', '/fɨ-/', 'verb', 'C1', 'To evade (a problem, situation, etc.) by using some clever argument or strategem.', '', ARRAY['zhoosh','zhoosh']::TEXT[]),
('Finicky', '/ˈfɪnɪki/', 'adjective', 'C1', '(of a person) Fastidious and fussy; difficult to please; exacting, especially about details.', 'My editor is very finicky about punctuation. Every dot and comma has to be just right.', ARRAY['fastidious','fussy','fastidious','fussy']::TEXT[]),
('Flaccid', '/ˈflæksɪd/', 'adjective', 'C1', 'Soft; floppy.', '', ARRAY[]::TEXT[]),
('Flamboyant', '/flamˈbɔɪənt/', 'adjective', 'C1', 'Showy, bold or audacious in behaviour, appearance, etc.', '', ARRAY[]::TEXT[]),
('Flatter', '/ˈflætə/', 'adjective', 'C1', 'Having no variations in height.', 'The land around here is flat.', ARRAY['deflate','punctured','even','planar','plane']::TEXT[]),
('Flax', '/flæks/', 'noun', 'C1', 'A plant of the genus Linum, especially Linum usitatissimum, which has a single, slender stalk, about a foot and a half high, with blue flowers. Also known as linseed, especially when referring to the seeds.', '', ARRAY[]::TEXT[]),
('Fledge', '/flɛdʒ/', 'adjective', 'C1', 'Feathered; furnished with feathers or wings; able to fly.', '', ARRAY[]::TEXT[]),
('Flinch', '/flɪntʃ/', 'verb', 'C1', 'To make a sudden, involuntary movement in response to a (usually negative) stimulus; to cringe.', '', ARRAY[]::TEXT[]),
('Flippancy', '/ˈflɪ.pən.si/', 'noun', 'C1', 'A disrespectful levity or pertness especially in respect to grave or sacred matters.', '', ARRAY[]::TEXT[]),
('Flirt', '/flɜːt/', 'adjective', 'C1', 'Pert; wanton', '', ARRAY[]::TEXT[]),
('Flit', '/flɪt/', 'adjective', 'C1', 'Fast, nimble.', '', ARRAY[]::TEXT[]),
('Flock', '/flɒk/', 'verb', 'C1', 'To congregate in or head towards a place in large numbers.', 'People flocked to the cinema to see the new film.', ARRAY[]::TEXT[]),
('Florid', '/ˈflɒɹɪd/', 'adjective', 'C1', 'Having a rosy or pale red colour; ruddy.', '', ARRAY[]::TEXT[]),
('Flout', '/flʌʊt/', 'verb', 'C1', 'To express contempt for (laws, rules, etc.) by word or action.', '', ARRAY[]::TEXT[]),
('Fluctuate', '', 'verb', 'C1', 'To vary irregularly; to swing.', 'I fluctuated between wishing he was back home and wishing I''''d never met him.', ARRAY[]::TEXT[]),
('Fluent', '/ˈfluːənt/', 'adjective', 'C1', 'That flows; flowing, liquid.', 'fluent handwriting', ARRAY['fluent']::TEXT[]),
('Fluke', '/fluːk/', 'verb', 'C1', 'To obtain a successful outcome by pure chance.', 'I fluked a pass in the multiple-choice exam.', ARRAY['glitch']::TEXT[]),
('Fluster', '/ˈflʌstə/', 'verb', 'C1', 'To make hot and rosy, as with drinking.', 'He seemed to get flustered when speaking in front of too many people.', ARRAY[]::TEXT[]),
('Fluvial', '', 'adjective', 'C1', 'Of, pertaining to, inhabiting, or produced by the action of a river or stream', '', ARRAY['fluviatile','riverine']::TEXT[]),
('Foil', '/fɔɪl/', 'verb', 'C1', 'To cover or wrap with foil.', '', ARRAY[]::TEXT[]),
('Foliage', '/ˈfəʊliɪdʒ/', 'noun', 'C1', 'The leaves of plants.', '', ARRAY[]::TEXT[]),
('Foolproof', '/ˈfuːl ˌpɹuːf/', 'adjective', 'C1', 'For a device: protected, or designed to be proof against misuse or error.', '', ARRAY[]::TEXT[]),
('Footloose', '', 'adjective', 'C1', 'Tending to travel or do as one pleases; readily without many commitments or responsibility.', 'He was footloose in his youth.', ARRAY[]::TEXT[]),
('Forebear', '', 'verb', 'C1', 'To keep away from; to avoid; to abstain from.', '', ARRAY[]::TEXT[]),
('Forbearance', '/foːˈbiəɹɘn(t)s/', 'noun', 'C1', 'Patient self-control; restraint and tolerance under provocation.', '', ARRAY['patience','restraint','thole']::TEXT[]),
('Ford', '/fɔːd/', 'verb', 'C1', 'To cross a stream using a ford.', '', ARRAY[]::TEXT[]),
('Forestall', '/fɔː(ɹ)ˈstɔːl/', 'verb', 'C1', 'To prevent, delay or hinder something by taking precautionary or anticipatory measures; to avert.', 'Fred forestalled disaster by his prompt action.', ARRAY[]::TEXT[]),
('Foreword', '/ˈfɔɹwɚd/', 'noun', 'C1', 'An introductory section preceding the main text of a book or other document; a preface or introduction.', '', ARRAY['forespeech','foretalk','introduction','preamble','preface']::TEXT[]),
('Forger', '', 'noun', 'C1', 'A person who creates forgeries, falsifies documents with intent to defraud, e.g. to create a false will or illicit copies of currency; counterfeiter.', '', ARRAY[]::TEXT[]),
('Formidable', '/fɔːˈmɪdəbəl/', 'adjective', 'C1', 'Causing fear, dread, awe, or discouragement as a result of size, strength, or some other impressive feature; commanding respect; causing wonder or astonishment.', 'a formidable opponent', ARRAY[]::TEXT[]),
('Fortify', '/ˈfɔːtɪfaɪ/', 'verb', 'C1', 'To increase the defenses of; to strengthen and secure by military works; to render defensible against an attack by hostile forces.', 'Sherry is made by fortifying wine.', ARRAY['castellate','incastellate','incastle','secure','strengthen']::TEXT[]),
('Fracas', '/fɹəˈkɑː/', 'noun', 'C1', 'A noisy disorderly quarrel, fight, brawl, disturbance or scrap.', '', ARRAY['brouhaha','kerfuffle','melee']::TEXT[]),
('Fracture', '/ˈfɹæk.tjə/', 'verb', 'C1', 'To break, or cause something to break.', '', ARRAY[]::TEXT[]),
('Frail', '/fɹeɪl/', 'adjective', 'C1', 'Easily broken physically; not firm or durable; liable to fail and perish', '', ARRAY[]::TEXT[]),
('Fraudulent', '/ˈfɹɔː.djə.lənt/', 'adjective', 'C1', 'Dishonest; based on fraud or deception.', 'He tried to pass a fraudulent check.', ARRAY[]::TEXT[]),
('Fraught', '/fɹɔːt/', 'noun', 'C1', 'The hire of a ship or boat to transport cargo.', 'fraught money.', ARRAY[]::TEXT[]),
('Freelancer', '', 'noun', 'C1', 'One who freelances', '', ARRAY[]::TEXT[]),
('Frenzy', '/ˈfɹɛnzi/', 'adjective', 'C1', 'Mad; frantic.', '', ARRAY[]::TEXT[]),
('Fresco', '/ˈfɹɛskəʊ/', 'verb', 'C1', 'To paint using fresco.', '', ARRAY[]::TEXT[]),
('Fret', '/fɹɛt/', 'verb', 'C1', 'Especially when describing animals: to consume, devour, or eat.', 'to fret the surface of water', ARRAY[]::TEXT[]),
('Friable', '/ˈfɹaɪəbl̩/', 'adjective', 'C1', 'Easily broken into small fragments, crumbled, or reduced to powder.', '', ARRAY['crumbly']::TEXT[]),
('Friction', '/ˈfɹɪkʃən̩/', 'noun', 'C1', 'The rubbing of one object or surface against another.', '', ARRAY[]::TEXT[]),
('Frieze', '/ˈfɹiːz/', 'verb', 'C1', 'To make a nap on (cloth); to friz.', '', ARRAY[]::TEXT[]),
('Frigid', '/ˈfɹɪdʒɪd/', 'adjective', 'C1', 'Very cold; lacking warmth; icy.', '', ARRAY[]::TEXT[]),
('Fringe', '/fɹɪndʒ/', 'adjective', 'C1', 'Outside the mainstream.', '', ARRAY['alternative','nonmainstream']::TEXT[]),
('Frond', '/fɹɒnd/', 'noun', 'C1', 'The leaf of a fern, especially a compound leaf.', '', ARRAY[]::TEXT[]),
('Frothy', '', 'adjective', 'C1', 'Foamy or churned to the point of becoming infused with bubbles.', 'I like my milkshakes frothy, not flat like this!', ARRAY['foamy','spumescent']::TEXT[]),
('Frowsy', '/ˈfɹaʊzi/', 'adjective', 'C1', 'Having a dingy, neglected, and scruffy appearance.', '', ARRAY[]::TEXT[]),
('Full-bodied', '', 'adjective', 'C1', 'Of a comestible, especially a beverage, having a rich flavor.', 'a full-bodied coffee', ARRAY['bold']::TEXT[]),
('Fulminate', '/ˈfʌlmɪneɪt/', 'verb', 'C1', 'To make a verbal attack.', '', ARRAY['berate','condemn','criticize','denounce','denunciate']::TEXT[]),
('Fumble', '/ˈfʌmbəl/', 'verb', 'C1', 'To handle nervously or awkwardly.', 'He fumbled the key into the lock.', ARRAY[]::TEXT[]),
('Fungi', '/ˈfʌn.dʒaɪ/', 'noun', 'C1', 'Any member of the kingdom Fungi; a eukaryotic organism typically having chitin cell walls but no chlorophyll or plastids. Fungi may be unicellular or multicellular.', '', ARRAY[]::TEXT[]),
('Furnace', '/ˈfɜːnɪs/', 'verb', 'C1', 'To heat in a furnace.', '', ARRAY[]::TEXT[]),
('Furor', '/ˈfjɜɹə/', 'noun', 'C1', 'A general uproar or commotion', '', ARRAY[]::TEXT[]),
('Fury', '/ˈfjʊəɹi/', 'noun', 'C1', 'Extreme anger.', '', ARRAY[]::TEXT[]),
('Fussy', '/ˈfʌ.si/', 'adjective', 'C1', 'Anxious or particular about petty details.', '', ARRAY[]::TEXT[]),
('Fusty', '', 'adjective', 'C1', 'Moldy or musty.', '', ARRAY[]::TEXT[]),
('Gadfly', '/ˈɡædflaɪ/', 'noun', 'C1', 'Any dipterous insect of the family Oestridae, commonly known as botflies.', 'He''''s a regular gadfly and takes advantage of his friend''''s generosity.', ARRAY['bloodsucker','botfly','horsefly','stoat-fly','stout']::TEXT[]),
('Gadget', '/ɡædʒɪt/', 'noun', 'C1', 'A thing whose name cannot be remembered; thingamajig, doohickey.', 'He bought a neat new gadget for shredding potatoes.', ARRAY['contraption','contrivance','doohickey','gizmo','widget']::TEXT[]),
('Gaffe', '/ɡæf/', 'noun', 'C2', 'A foolish and embarrassing error, especially one made in public.', '', ARRAY['blooper','blunder','error','mistake','slip']::TEXT[]),
('Gait', '/ɡeɪt/', 'verb', 'C1', 'To teach a specific gait to a horse.', '', ARRAY[]::TEXT[]),
('Galaxy', '/ˈɡaləksi/', 'noun', 'C1', 'The Milky Way; the apparent band of concentrated stars which appears in the night sky over earth.', '', ARRAY['G','star city','trichiliocosm']::TEXT[]),
('Gallant', '/ˈɡælənt/', 'adjective', 'C1', 'Brave, valiant.', '', ARRAY[]::TEXT[]),
('Galley', '/ˈɡæli/', 'noun', 'C1', 'A long, slender ship propelled primarily by oars, whether having masts and sails or not; usually referring to rowed warships used in the Mediterranean from the 16th century until the modern era.', '', ARRAY['lymphad']::TEXT[]),
('Gamble', '/ˈɡæm.bəl/', 'verb', 'C1', 'To take a risk, with the potential of a positive outcome.', 'He gambled his reputation on the outcome.', ARRAY[]::TEXT[]),
('Gambol', '/ˈɡæm.bəl/', 'verb', 'C1', 'To move about playfully; to frolic.', '', ARRAY[]::TEXT[]),
('Gangly', '/ˈɡæŋ.ɡli/', 'adjective', 'C1', 'Tall and thin, especially so as to cause physical awkwardness.', '', ARRAY['lanky']::TEXT[]),
('Gangway', '', 'verb', 'C1', 'To serve as, furnish with, or conduct oneself as though proceeding on a gangway.', '', ARRAY[]::TEXT[]),
('Garble', '/ˈɡɑː(ɹ)bəl/', 'verb', 'C1', 'To pick out such parts (of a text) as may serve a purpose; to mutilate; to pervert', 'to garble a quotation', ARRAY[]::TEXT[]),
('Gargantuan', '/ɡɑɹˈɡæn.tʃu.ən/', 'adjective', 'C1', 'Of the giant Gargantua or his appetite.', '', ARRAY['colossal','enormous','giant','huge','humongous']::TEXT[]),
('Garish', '/ˈɡɛəɹɪʃ/', 'adjective', 'C1', 'Overly ostentatious; so colourful as to be in bad taste.', 'The dress fits her well, but the pattern is rather garish.', ARRAY[]::TEXT[]),
('Garment', '/ˈɡɑː.mənt/', 'verb', 'C1', 'To clothe in a garment.', '', ARRAY[]::TEXT[]),
('Gash', '/ɡæʃ/', 'adjective', 'C1', 'Of poor quality; makeshift; improvised; temporary; substituted.', '', ARRAY[]::TEXT[]),
('Gaudy', '/ˈɡɔː.di/', 'adjective', 'C1', 'Very showy or ornamented, now especially when excessive, or in a tasteless or vulgar manner', '', ARRAY['flashy','garish','kitschy','tawdry','gaudy']::TEXT[]),
('Gauge', '/ˈɡeɪdʒ/', 'verb', 'C1', 'To measure or determine with a gauge; to measure the capacity of.', '', ARRAY[]::TEXT[]),
('Gerrymander', '', 'verb', 'C2', 'To divide a geographic area into voting districts in such a way as to give an unfair advantage to one party in an election.', 'The superintendent helped gerrymander the school district lines in order to keep the children of the wealthy gated community in the better school all the way across town.', ARRAY[]::TEXT[]),
('Geyser', '/ˈɡaɪzə/', 'verb', 'C1', 'To (cause to) rush or burst upward like water from a geyser.', '', ARRAY[]::TEXT[]),
('Gratuitous', '/ɡɹəˈtjuː.ɪt.əs/', 'adjective', 'C1', 'Given freely; unearned.', 'gratuitous violence', ARRAY['baseless','free','gratis','groundless','uncalled-for']::TEXT[]),
('Gravel', '/ˈɡɹævəl/', 'verb', 'C1', 'To apply a layer of gravel to the surface of a road, etc.', '', ARRAY[]::TEXT[]),
('Grieve', '/ɡɹiːv/', 'verb', 'C1', 'To cause sorrow or distress to.', 'to grieve one''''s fate', ARRAY[]::TEXT[]),
('Grimace', '/ˈɡɹɪm.əs/', 'verb', 'C1', 'To make grimaces; to distort one''''s face; to make faces.', '', ARRAY[]::TEXT[]),
('Gripe', '/ɡɹʌɪp/', 'verb', 'C1', 'To complain; to whine.', 'What''''s griping you?', ARRAY['bitch','complain','whine','whinge']::TEXT[]),
('Grisly', '/ˈɡɹɪzli/', 'adjective', 'C1', 'Horrifyingly repellent; gruesome, terrifying.', 'The photographs of the killings depict a grisly scene.', ARRAY['gristly','grisy','grizzly','gristly','grisy']::TEXT[]),
('Groove', '/ɡɹuːv/', 'verb', 'C1', 'To cut a groove or channel in; to form into channels or grooves; to furrow.', 'I was just starting to groove to the band when we had to leave.', ARRAY[]::TEXT[]),
('Grotesque', '/ɡɹəʊˈtɛsk/', 'adjective', 'C1', 'Distorted and unnatural in shape or size; abnormal and hideous.', '', ARRAY[]::TEXT[]),
('Grotto', '/ˈɡɹɒt.əʊ/', 'noun', 'C1', 'A small cave.', '', ARRAY[]::TEXT[]),
('Grove', '/ɡɹəʊv/', 'verb', 'C1', 'To cultivate in groves; to grow naturally so as to form groves.', '', ARRAY['groove']::TEXT[]),
('Grueling', '', 'adjective', 'C1', 'So difficult or taxing as to make one exhausted; backbreaking.', '', ARRAY['backbreaking','exhausting']::TEXT[]),
('Guile', '/ɡaɪl/', 'verb', 'C1', 'To deceive, beguile, bewile.', '', ARRAY[]::TEXT[]),
('Gullible', '/ˈɡʌlɪbl̩/', 'adjective', 'C1', 'Easily deceived or duped; naive, easily cheated or fooled.', 'Andrew is so gullible, the way he still believes in Santa Claus, the Easter Bunny, the Tooth Fairy, and the Sandman at the age of fourteen.', ARRAY['fleeceable','green','naif','naive']::TEXT[]),
('Gully', '/ˈɡʌli/', 'verb', 'C1', 'To flow noisily.', '', ARRAY[]::TEXT[]),
('Gum', '/ɡʌm/', 'verb', 'C1', 'To chew, especially of a toothless person or animal.', '', ARRAY[]::TEXT[]),
('Gush', '/ˈɡʌʃ/', 'verb', 'C1', 'To flow forth suddenly, in great volume.', '', ARRAY[]::TEXT[]),
('Gust', '/ɡʌst/', 'verb', 'C1', 'To blow in gusts.', '', ARRAY[]::TEXT[]),
('Guzzle', '/ˈɡʌzəl/', 'verb', 'C1', 'To drink or eat quickly, voraciously, or to excess; to gulp down; to swallow greedily, continually, or with gusto.', 'This car just guzzles petrol.', ARRAY['swig','swill']::TEXT[]),
('Habitable', '/ˈhæbɪtəbəl/', 'adjective', 'C1', 'Safe and comfortable, where humans, or other animals, can live; fit for habitation.', 'After we found the freshwater spring we were more confident that the place was habitable.', ARRAY['inhabitable']::TEXT[]),
('Hack', '/hæk/', 'verb', 'C1', 'To chop or cut down in a rough manner.', 'They hacked the brush down and made their way through the jungle.', ARRAY['crack','frob','tweak','frob','tweak']::TEXT[]),
('Halcyon', '/ˈhælsiːən/', 'adjective', 'C2', 'Pertaining to the halcyon or kingfisher.', '', ARRAY['at peace','blissful','calm','peaceful','prelapsarian']::TEXT[]),
('Hale', '/heɪl/', 'noun', 'C1', 'Health, welfare.', '', ARRAY[]::TEXT[]),
('Half-baked', '', 'adjective', 'C1', '(frequently derisive) incomplete; (of an idea or scheme) not fully planned or carefully considered, ill-conceived, unsound or badly thought-out; (of a person) foolish or having no common sense.', 'The guy had some half-baked idea for getting rich in the stock market.', ARRAY[]::TEXT[]),
('Hallmark', '/ˈhɔːlmɑːk/', 'verb', 'C1', 'To provide or stamp with a hallmark.', '', ARRAY[]::TEXT[]),
('Hallow', '', 'noun', 'C1', '(obsolete outside set phrases) A saint; a holy person; an apostle.', '', ARRAY[]::TEXT[]),
('Hallucination', '/həˌluːsɪˈneɪʃən/', 'noun', 'C1', 'A sensory perception of something that does not exist, often arising from disorder of the nervous system, as in delirium tremens; a delusion.', '', ARRAY[]::TEXT[]),
('Ham-handed', '', 'adjective', 'C1', 'Clumsy, heavy, or inept; not delicate, light or gentle.', 'Some of the dishes arrived damaged after their ham-handed moving efforts.', ARRAY[]::TEXT[]),
('Hammer', '/ˈhæm.ə(ɹ)/', 'verb', 'C1', 'To strike repeatedly with a hammer, some other implement, the fist, etc.', 'Tony hammered on the door to try to get him to open.', ARRAY['pound','pound']::TEXT[]),
('Hamstring', '/ˈhæmstɹɪŋ/', 'verb', 'C1', 'To lame or disable by cutting the tendons of the ham or knee; to hough.', '', ARRAY['cripple','disable','incapacitate','hock','hough']::TEXT[]),
('Hangdog', '', 'adjective', 'C1', 'Low; sneaking; ashamed.', '', ARRAY[]::TEXT[]),
('Hankering', '', 'verb', 'C1', 'To crave, want or desire.', 'If you hanker for chocolate, you''''ll like this fudge recipe.', ARRAY[]::TEXT[]),
('Harass', '/həˈɹæs/', 'verb', 'C1', 'To fatigue or to tire with repeated and exhausting efforts.', 'To harass good people is no different than speaking ill of them.', ARRAY['beset','chevvy','chevy','chivvy','chivy']::TEXT[]),
('Harbinger', '/ˈhɑːbɪndʒə/', 'verb', 'C1', 'To announce or precede; to be a harbinger of.', '', ARRAY['herald']::TEXT[]),
('Harbor', '/ˈhɑːbə/', 'noun', 'C1', 'Any place of shelter.', 'The neighborhood is a well-known harbor for petty thieves.', ARRAY[]::TEXT[]),
('Hard-bitten', '', 'adjective', 'C1', 'Callous and toughened by experience', '', ARRAY[]::TEXT[]),
('Hardy', '/ˈhɑːdi/', 'adjective', 'C1', 'Having rugged physical strength; inured to fatigue or hardships.', 'A hardy plant is one that can withstand the extremes of climate, such as frost.', ARRAY['robust','rugged','strong']::TEXT[]),
('Harmonious', '/hɑːˈməʊnɪəs/', 'adjective', 'C1', 'Showing accord in feeling or action.', '', ARRAY[]::TEXT[]),
('Harness', '/ˈhɑː(ɹ).nəs/', 'verb', 'C1', 'To place a harness on something; to tie up or restrain.', 'They harnessed the horse to the post.', ARRAY[]::TEXT[]),
('Harp', '/hɑːp/', 'verb', 'C1', '(usually with on) To repeatedly mention a subject.', 'Why do you harp on a single small mistake?', ARRAY['keep on','perseverate']::TEXT[]),
('Harrow', '/ˈhæɹəʊ/', 'verb', 'C1', 'To drag a harrow over; to break up with a harrow.', '', ARRAY[]::TEXT[]),
('Harry', '/hæɹi/', 'verb', 'C1', 'To plunder, pillage, assault.', '', ARRAY[]::TEXT[]),
('Hasten', '/ˈheɪ.sən/', 'verb', 'C1', 'To move or act in a quick fashion.', '', ARRAY['hurry','rush','zoom','dart','race']::TEXT[]),
('Hasty', '/ˈheɪsti/', 'adjective', 'C1', 'Acting in haste; being too hurried or quick', 'Without much thinking about it they made a hasty decision to buy it.', ARRAY[]::TEXT[]),
('Hatch', '/hætʃ/', 'verb', 'C1', 'To close with a hatch or hatches.', '', ARRAY[]::TEXT[]),
('Hauteur', '/ɔːˈtɜː/', 'noun', 'C2', 'Haughtiness or arrogance; loftiness.', '', ARRAY[]::TEXT[]),
('Haven', '/ˈheɪvən/', 'verb', 'C1', 'To put into, or provide with a haven.', '', ARRAY[]::TEXT[]),
('Havoc', '/ˈhæv.ək/', 'verb', 'C1', 'To pillage.', '', ARRAY[]::TEXT[]),
('Headlong', '/ˈhɛdlɑŋ/', 'adjective', 'C1', 'Precipitous.', '', ARRAY[]::TEXT[]),
('Hearken', '/ˈhɑːk(ə)n/', 'verb', 'C1', '(obsolete except poetic) To hear (something) with attention; to have regard to (something).', '', ARRAY[]::TEXT[]),
('Hearten', '/ˈhɑːtən/', 'verb', 'C1', 'To give heart to; to encourage, urge on, cheer, give confidence to.', '', ARRAY[]::TEXT[]),
('Heartrending', '', 'adjective', 'C1', 'That causes great grief, anguish or distress.', '', ARRAY['heart-breaking','heart-breaking']::TEXT[]),
('Hedonism', '/ˈhiːdənɪzəm/', 'noun', 'C1', 'The belief that pleasure or happiness is the highest good in life. Some hedonists, such as the Epicureans, have insisted that pleasure of the entire mind, not just pleasure of the senses, is the highest good.', '', ARRAY[]::TEXT[]),
('Heinous', '/ˈheɪnəs/', 'adjective', 'C1', 'Totally reprehensible.', 'I hope they catch the person responsible for that heinous crime.', ARRAY['abominable','horrible','odious']::TEXT[]),
('Heirloom', '/ˈɛə.luːm/', 'noun', 'C1', 'A valued possession that has been passed down through the generations.', '', ARRAY['patrimony','patrimony']::TEXT[]),
('Hem', '/hɛm/', 'verb', 'C1', 'To make the sound expressed by the word hem; to hesitate in speaking.', '', ARRAY[]::TEXT[]),
('Hew', '/hjuː/', 'verb', 'C1', 'To chop away at; to whittle down; to mow down.', 'One of the most widely used typefaces in the world was hewn by the English printer and typographer John Baskerville.', ARRAY[]::TEXT[]),
('Herald', '/ˈhɛɹəld/', 'verb', 'C1', 'To proclaim or announce an event.', 'Daffodils herald the Spring.', ARRAY['disclose','make known']::TEXT[]),
('Herbicide', '', 'noun', 'C1', 'A substance used to kill plants.', '', ARRAY[]::TEXT[]),
('Heresy', '/ˈhɛɹəsi/', 'noun', 'C1', 'A doctrine held by a member of a religion at variance with established religious beliefs, especially dissension from Roman Catholic dogma.', '', ARRAY[]::TEXT[]),
('Heretical', '/həˈɹɛtɪkəl/', 'adjective', 'C1', 'Of or pertaining to heresy or heretics.', '', ARRAY['unorthodox','unorthodox']::TEXT[]),
('Hermetic', '/hə(ɹ)ˈmɛtɪk/', 'adjective', 'C1', '(chiefly with capital initial) Pertaining to Hermes Trismegistus or the writings attributed to him.', '', ARRAY[]::TEXT[]),
('Hermit', '/ˈhɜːmɪt/', 'noun', 'C1', 'A religious recluse; someone who lives alone for religious reasons; an eremite.', '', ARRAY['anchorite','eremite','recluse']::TEXT[]),
('Hesitance', '', 'noun', 'C1', 'The act or state of hesitating.', 'His hesitance was caused by bad past experiences.', ARRAY[]::TEXT[]),
('Heterodox', '/ˈhɛtɛɹədɒks/', 'adjective', 'C1', 'Of or pertaining to creeds, beliefs, or teachings, especially religious ones, that are different from orthodoxy, or the norm, but not sufficiently different to be called heretical.', 'The Church of Alexandria in Egypt is considered heterodox, not heretical.', ARRAY[]::TEXT[]),
('Hidebound', '/ˈhaɪd.baʊnd/', 'adjective', 'C1', 'Bound with the hide of an animal.', '', ARRAY[]::TEXT[]),
('Hideous', '/ˈhɪd.iː.ʌs/', 'adjective', 'C1', 'Extremely or shockingly ugly.', 'A piteous and hideous spectacle.', ARRAY['dreadful','frightful','ghastly','grim','grisly']::TEXT[]),
('Hie', '/haɪ/', 'verb', 'C1', 'To hasten; to go quickly, to hurry.', '', ARRAY[]::TEXT[]),
('Hieroglyph', '/ˈhaɪɹəˌɡlɪf/', 'verb', 'C1', 'To represent by hieroglyphs.', '', ARRAY[]::TEXT[]),
('Hike', '/haɪk/', 'verb', 'C1', 'To take a long walk for pleasure or exercise.', 'Don''''t forget to bring the map when we go hiking tomorrow.', ARRAY['lean out','sit out','tramp']::TEXT[]),
('Histrionic', '/hɪstɹiːˈɒnɪk/', 'adjective', 'C2', 'Of or relating to actors or acting.', '', ARRAY['actorish','actressy','dramatic','theatrical','melodramatic']::TEXT[]),
('Hive', '/haɪv/', 'verb', 'C1', 'To enter or possess a hive.', 'to hive a swarm of bees', ARRAY[]::TEXT[]),
('Hoard', '/hɔːd/', 'verb', 'C1', 'To amass, usually for one''''s own private collection.', '', ARRAY['engross','uphoard']::TEXT[]),
('Hoary', '/hɔː.ɹi/', 'adjective', 'C2', 'White, whitish, or greyish-white.', 'The old man bowed his hoary head in acquiescence.', ARRAY['canescent','aged','ancient','olden','bygone']::TEXT[]),
('Hoax', '/həʊks/', 'verb', 'C1', 'To deceive (someone) by making them believe something that has been maliciously or mischievously fabricated.', '', ARRAY[]::TEXT[]),
('Homage', '/ˈhɒmɪdʒ/', 'verb', 'C1', 'To pay reverence to by external action.', '', ARRAY[]::TEXT[]),
('Homely', '/ˈhəʊmli/', 'adjective', 'C1', 'Lacking in beauty or elegance, plain in appearance, physically unattractive.', 'I am seeking a beautiful homely girl for marriage.', ARRAY[]::TEXT[]),
('Homily', '/ˈhɑmɪli/', 'noun', 'C1', 'A sermon, especially concerning a practical matter.', '', ARRAY[]::TEXT[]),
('Homogenize', '/həˈmɒdʒənaɪz/', 'verb', 'C1', 'To make homogeneous, to blend or puree.', '', ARRAY[]::TEXT[]),
('Hone', '/həʊn/', 'verb', 'C1', 'To sharpen with a hone; to whet.', '', ARRAY[]::TEXT[]),
('Honorarium', '/ˌɑ.nəˈɹɛɹ.i.əm/', 'noun', 'C1', 'Compensation for services that do not have a predetermined value.', '', ARRAY[]::TEXT[]),
('Hoodwink', '/ˈhʊd.wɪŋk/', 'verb', 'C2', 'To deceive by disguise; to dupe, bewile, mislead.', '', ARRAY[]::TEXT[]),
('Horticulture', '/ˈhɔː.tɪˌkʌl.tʃə(ɹ)/', 'noun', 'C1', 'The art or science of cultivating gardens; gardening.', '', ARRAY[]::TEXT[]),
('Hovel', '/ˈhɒvəl/', 'verb', 'C1', 'To put in a hovel; to shelter.', '', ARRAY[]::TEXT[]),
('Hub', '/hʌb/', 'noun', 'C1', 'The central part, usually cylindrical, of a wheel; the nave.', 'Hong Kong International Airport is one of the most important air traffic hubs in Asia.', ARRAY['hub world']::TEXT[]),
('Hubris', '/ˈhjuːbɹɪs/', 'noun', 'C2', 'Excessive pride, presumption or arrogance (originally toward the gods).', '', ARRAY[]::TEXT[]),
('Humility', '/hjuːˈmɪlɪti/', 'noun', 'C1', 'The characteristic of being humble; humbleness in character and behavior.', '', ARRAY['egolessness','humilitude','meekness','modesty','self-effacement']::TEXT[]),
('Humor', '/hjuː.mə(ɹ)/', 'verb', 'C1', 'To pacify by indulging.', 'I know you don''''t believe my story, but humour me for a minute and imagine it to be true.', ARRAY[]::TEXT[]),
('Husbandry', '/ˈhʌzb(ə)ndɹi/', 'noun', 'C1', 'The occupation or work of a husbandman or farmer; the cultivation of crops and the raising of livestock; agriculture.', '', ARRAY['agronomy','economy','frugality','thrift','agronomy']::TEXT[]),
('Husk', '/hʌsk/', 'verb', 'C1', 'To remove husks from.', '', ARRAY[]::TEXT[]),
('Husky', '/ˈhʌs.ki/', 'adjective', 'C1', '(of a voice) Hoarse and rough-sounding.', '', ARRAY[]::TEXT[]),
('Hybrid', '/ˈhaɪ.bɹɪd/', 'adjective', 'C1', 'Consisting of diverse ''''hybridized'''' components.', '', ARRAY[]::TEXT[]),
('Hymn', '/hɪm/', 'verb', 'C1', 'To sing a hymn.', '', ARRAY[]::TEXT[]),
('Hyperbole', '/haɪˈpɝːbəli/', 'noun', 'C1', 'Deliberate or unintentional overstatement, particularly extreme overstatement.', '', ARRAY['auxesis','exaggeration','overstatement']::TEXT[]),
('Hypnotic', '/hɪpˈnɒtɪk/', 'adjective', 'C1', 'Of, or relating to hypnosis or hypnotism.', '', ARRAY['captivating','mesmeric']::TEXT[]),
('Hypocritical', '/hɪpəˈkɹɪtɪkəl/', 'adjective', 'C1', 'Characterized by hypocrisy or being a hypocrite.', '', ARRAY['two-faced']::TEXT[]),
('Idyll', '/ˈɪdəl/', 'noun', 'C1', 'Any poem or short written piece composed in the style of Theocritus'''' short pastoral poems, the Idylls.', '', ARRAY[]::TEXT[]),
('Ignite', '/ɪɡˈnaɪt/', 'verb', 'C1', 'To set fire to (something), to light (something)', 'to ignite iron or platinum', ARRAY[]::TEXT[]),
('Ignominy', '/ˈɪɡnəˌmɪni/', 'noun', 'C1', 'Great dishonor, shame, or humiliation.', '', ARRAY[]::TEXT[]),
('Illiteracy', '/ɪˈlɪt(ʃ)ɹəsi/', 'noun', 'C1', 'The inability to read and write.', 'Illiteracy is widespread in certain areas of the country.', ARRAY['analphabetism']::TEXT[]),
('Illumination', '', 'noun', 'C1', 'The act of illuminating, or supplying with light; the state of being illuminated.', '', ARRAY['lumination']::TEXT[]),
('Illusory', '/ɪˈluːs(ə)ɹi/', 'adjective', 'C1', 'Resulting from an illusion; deceptive, imaginary, unreal', 'Enron''''s profits were all illusory.', ARRAY[]::TEXT[]),
('Imbibe', '/ɪmˈbaɪb/', 'verb', 'C2', 'To drink (used frequently of alcoholic beverages).', 'to imbibe knowledge', ARRAY[]::TEXT[]),
('Imbroglio', '/ɪmˈbɹəʊljəʊ/', 'noun', 'C2', 'A complicated situation; an entanglement.', '', ARRAY['snarl']::TEXT[]),
('Imitation', '/ɪmɪˈteɪʃən/', 'noun', 'C1', 'The act of imitating.', 'imitation leather', ARRAY[]::TEXT[]),
('Immaculate', '/ɪˈmækjəlɪt/', 'adjective', 'C1', 'Having no stain or blemish; spotless, undefiled, clear, clean, pure.', 'Thou sheer, immaculate and silver fountain. — Shakespeare, Richard II, V-iii.', ARRAY[]::TEXT[]),
('Immanent', '/ˈɪmənənt/', 'adjective', 'C1', 'Naturally part of something; existing throughout and within something; intrinsic.', '', ARRAY[]::TEXT[]),
('Immature', '/ɪməˈtjʊə(ɹ)/', 'adjective', 'C1', 'Occurring before the proper time; untimely, premature (especially of death).', 'The man was immature for throwing a tantrum.', ARRAY['infantile','milky']::TEXT[]),
('Immemorial', '/ɪ.məˈmɔːɹi.əl/', 'adjective', 'C1', 'That is beyond memory; ancient.', 'The rocks had stood overlooking the valley since time immemorial.', ARRAY[]::TEXT[]),
('Immure', '/ɪˈmjʊə(r)/', 'verb', 'C2', 'To cloister, confine, imprison: to lock up behind walls.', 'John''''s body was immured Thursday in the mausoleum.', ARRAY['inter','cloister','confine','imprison','incarcerate']::TEXT[]),
('Imp', '/ɪmp/', 'verb', 'C1', 'To plant or engraft.', '', ARRAY[]::TEXT[]),
('Impassive', '/ɪmˈpæsɪv/', 'adjective', 'C1', 'Having, or revealing, no emotion.', '', ARRAY['apathetic','phlegmatic']::TEXT[]),
('Impecunious', '/ˌɪm.pəˈkjuː.ni.əs/', 'adjective', 'C2', 'Lacking money', '', ARRAY['penniless','poor']::TEXT[]),
('Impend', '/ɪmˈpɛnd/', 'verb', 'C1', 'To hang or be suspended over (something); to overhang.', '', ARRAY[]::TEXT[]),
('Impenetrable', '/ɪmˈpɛnətɹəbəl/', 'adjective', 'C1', 'Not penetrable.', 'The fortress is impenetrable, so it cannot be taken.', ARRAY['impregnable','unfathomable']::TEXT[]),
('Impenitent', '/ɪmˈpɛnɪtənt/', 'adjective', 'C1', 'Not penitent; not repent one''''s sins', '', ARRAY[]::TEXT[]),
('Imperative', '/ɪmˈpɛɹ.ə.tɪv/', 'adjective', 'C1', 'Essential; crucial; extremely important.', 'It is imperative that you come here right now.', ARRAY[]::TEXT[]),
('Imperial', '/ɪmˈpɪ.ɹi.əl/', 'adjective', 'C1', 'Related to an empire, emperor, or empress.', '', ARRAY['old money']::TEXT[]),
('Imperious', '/ɪmˈpɪəɹi.əs/', 'adjective', 'C2', 'Domineering, arrogant, or overbearing.', '', ARRAY['authoritarian','bossy','dictatorial','domineering','overbearing']::TEXT[]),
('Impertinence', '/ɪm.ˈpɜː.tɪ.nəns/', 'noun', 'C1', 'Lack of pertinence; irrelevance.', '', ARRAY[]::TEXT[]),
('Imperturbable', '/ˌɪmpəˈtɜːbəbəl/', 'adjective', 'C1', 'Not easily perturbed, upset or excited.', '', ARRAY[]::TEXT[]),
('Impervious', '/ɪmˈpɜːvi.əs/', 'adjective', 'C2', 'Unaffected or unable to be affected by something.', 'The man was completely impervious to the deception we were trying.', ARRAY[]::TEXT[]),
('Impetuous', '/imˈpɛtʃuəs/', 'adjective', 'C2', 'Making arbitrary decisions, especially in an impulsive and forceful manner.', '', ARRAY['hasty','hotheaded','impulsive','rash']::TEXT[]),
('Impiety', '', 'noun', 'C1', 'The state of being impious.', '', ARRAY['afgodness','ungodliness','disregard','disrespect','afgodness']::TEXT[]),
('Implode', '', 'verb', 'C1', 'To collapse or burst inward violently.', '', ARRAY[]::TEXT[]),
('Imposing', '/ɪmˈpəʊzɪŋ/', 'adjective', 'C1', 'Magnificent and impressive because of appearance, size, stateliness or dignity.', '', ARRAY[]::TEXT[]),
('Importune', '/ɪmpɔːˈtjuːn/', 'adjective', 'C1', 'Grievous, severe, exacting.', '', ARRAY[]::TEXT[]),
('Impostor', '/ɪmˈpɒstə/', 'noun', 'C1', 'Someone who attempts to deceive by using an assumed name or identity.', '', ARRAY['impersonator']::TEXT[]),
('Impotent', '/ˈɪm.pə.tənt/', 'adjective', 'C1', 'Lacking physical strength or vigor; weak', '', ARRAY['feeble','puny','weak','helpless','powerless']::TEXT[]),
('Imprecise', '/ɪmpɹɪˈsaɪs/', 'adjective', 'C1', 'Not precise or exact; containing some error or uncertainty', '', ARRAY[]::TEXT[]),
('Impresario', '', 'noun', 'C1', 'A manager or producer in the entertainment industry, especially music or theatre.', '', ARRAY[]::TEXT[]),
('Impromptu', '/ɪmˈpɹɒmptju/', 'adjective', 'C1', 'Improvised; without prior preparation, planning or rehearsal.', 'The party began with an impromptu rendition of ''''Happy Birthday''''.', ARRAY['extemporaneous','unplanned','extemporaneous','unplanned']::TEXT[]),
('Improvise', '/ˈɪmpɹəvaɪz/', 'verb', 'C1', 'To make something up or invent it as one goes on; to proceed guided only by imagination, instinct, and guesswork rather than by a careful plan.', 'He had no speech prepared, so he improvised.', ARRAY['fly by the seat of one''''s pants','play by ear','punt','think on one''''s feet','wing it']::TEXT[]),
('Impugn', '/ɪmˈpjuːn/', 'verb', 'C2', 'To assault, attack.', '', ARRAY['call into question','challenge','contest','contradict','deny']::TEXT[]),
('Inalienable', '/ɪˈneɪ.lɪ.ə.nə.bəl/', 'adjective', 'C1', 'Incapable of being alienated, surrendered, or transferred to another; not alienable.', 'inalienable right a right that cannot be given away', ARRAY['unalienable']::TEXT[]),
('Inane', '/ɪˈneɪn/', 'adjective', 'C1', 'Lacking sense or meaning (often to the point of boredom or annoyance)', 'This supremely gifted kid told me that in the early elementary grades, the songs sung in music class were so inane that he wanted to skip grades already! Eventually he did, so better late than never.', ARRAY['fatuous','silly','vapid','fatuous','silly']::TEXT[]),
('Inanimate', '/ɪnˈænɪmət/', 'adjective', 'C1', 'Lacking the quality or ability of motion; as an inanimate object.', '', ARRAY['insensate','insentient','lifeless','non-animate','immobile']::TEXT[]),
('Inaugurate', '/ɪˈnɔːɡjʊɹət/', 'adjective', 'C1', 'Invested with office; inaugurated.', '', ARRAY[]::TEXT[]),
('Incandescent', '/ˌɪn.kænˈdɛs.ənt/', 'adjective', 'C1', 'Emitting light as a result of being heated', '', ARRAY[]::TEXT[]),
('Incantation', '/inkænˈteɪʃən/', 'noun', 'C1', 'The act or process of using formulas and/or usually rhyming words, sung or spoken, with occult ceremonies, for the purpose of raising spirits, producing enchantment, or creating other magical results.', '', ARRAY[]::TEXT[]),
('Incarnate', '/ɪnˈkɑːneɪt/', 'adjective', 'C1', 'Embodied in flesh; given a bodily, especially a human, form; personified.', '', ARRAY[]::TEXT[]),
('Incendiary', '/ɪnˈsɛn.djəɹ.i/', 'adjective', 'C1', 'Capable of, or used for, or actually causing fire.', 'Politics is an incendiary topic; it tends to cause fights to break out.', ARRAY[]::TEXT[]),
('Inception', '/ɪnˈsɛpʃn/', 'noun', 'C1', 'The creation or beginning of something; the establishment.', 'From its inception, the agency has been helping people obtain and properly install car seats for children.', ARRAY[]::TEXT[]),
('Inchoate', '/ɪnˈkəʊeɪt/', 'adjective', 'C2', 'Recently started but not fully formed yet; just begun; only elementary or immature.', '', ARRAY['chaotic','confused','elementary','embryonic','immature']::TEXT[]),
('Incinerate', '', 'adjective', 'C1', 'Reduced to ashes by burning; thoroughly consumed.', '', ARRAY[]::TEXT[]),
('Incipient', '/ɪnˈsɪp.i.ənt/', 'adjective', 'C1', 'In an initial stage; beginning, starting, coming into existence.', 'After 500 years, incipient towns appeared.', ARRAY['beginning','commencing','emerging','inchoate','nascent']::TEXT[]),
('Incite', '/ɪnˈsaɪt/', 'verb', 'C1', 'To stir up or excite; to rouse or goad into action.', 'The judge was told by the accused that his friends had incited him to commit the crime.', ARRAY[]::TEXT[]),
('Incongruent', '', 'adjective', 'C1', 'Out of place, incompatible, inharmonious, not congruent', 'Her knowledge of world politics was incongruent in someone so young.', ARRAY['absurd','inappropriate','incongruous']::TEXT[]),
('Inconsequential', '/ɪnˌkɑnsəˈkwɛnʃəl/', 'adjective', 'C1', 'Having no consequence; not consequential; of little importance.', 'You will never know the exact atomic time when you started reading this phrase; of course, that''''s inconsequential.', ARRAY['negligible','trifling','trivial','unimportant']::TEXT[]),
('Incontrovertible', '/ˌɪŋ.kɒn.tɹəˈvɜː.təbl̩/', 'adjective', 'C2', 'Not capable of being denied, challenged, or disputed; closed to questioning.', 'Her statement that Hitler was evil is incontrovertible.', ARRAY['indisputable','undeniable','unquestionable','indisputable','undeniable']::TEXT[]),
('Incriminate', '/ɪŋˈkɹɪmɪneɪt/', 'verb', 'C1', 'To accuse or bring criminal charges against.', 'The newspapers incriminated the innocent man unjustly.', ARRAY[]::TEXT[]),
('Incubator', '/ɪn.kjuːˈbeɪ.tə(ɹ)/', 'noun', 'C1', 'Any apparatus used to maintain environmental conditions suitable for a reaction.', '', ARRAY['brooder','brooder']::TEXT[]),
('Inculpate', '', 'verb', 'C1', 'To imply the guilt of; to blame or incriminate.', '', ARRAY[]::TEXT[]),
('Incursion', '', 'noun', 'C1', 'An aggressive movement into somewhere; an invasion.', '', ARRAY['attack','movement']::TEXT[]),
('Indelible', '/ɪnˈdɛləbl/', 'adjective', 'C1', 'Having the quality of being difficult to delete, remove, wash away, blot out, or efface.', 'This ink spot on the contract is indelible.', ARRAY['unerasable','unerasable','unforgettable','unerasable','unerasable']::TEXT[]),
('Indemnity', '/ɪnˈdɛmnɪti/', 'noun', 'C1', 'Security from damage, loss, or penalty.', '', ARRAY[]::TEXT[]),
('Indifferent', '/ɪnˈdɪf.ə.ɹənt/', 'adjective', 'C1', 'Not caring or concerned; uninterested, apathetic.', 'He was indifferent to the proposal, since it didn’t affect him, either way.', ARRAY[]::TEXT[]),
('Indigent', '/ˈɪndɪd͡ʒənt/', 'adjective', 'C2', 'Poor; destitute; in need.', '', ARRAY[]::TEXT[]),
('Indispensable', '/ɪndɪˈspɛnsəbəl/', 'adjective', 'C1', 'Not admitting ecclesiastical dispensation; not subject to release or exemption; that cannot be allowed by bending the canonical rules.', 'The law was moral and indispensable. -Bp. Burnet', ARRAY[]::TEXT[]),
('Indoctrinate', '', 'verb', 'C1', 'To teach with a biased, one-sided or uncritical ideology; to brainwash.', '', ARRAY[]::TEXT[]),
('Indolent', '/ˈɪn.dəl.ənt/', 'adjective', 'C1', 'Habitually lazy, procrastinating, or resistant to physical labor', 'The indolent girl resisted doing her homework.', ARRAY['idle','work-shy']::TEXT[]),
('Inducement', '', 'noun', 'C1', 'An incentive that helps bring about a desired state. In some contexts, this can imply bribery.', '', ARRAY[]::TEXT[]),
('Indulgent', '/ɪnˈdʌldʒənt/', 'adjective', 'C1', 'Disposed or prone to indulge, humor, gratify, or yield to one''''s own or another''''s desires, etc., or to be compliant, lenient, or forbearing;', 'an indulgent parent', ARRAY['forbearing','gentle','lenient','tolerant']::TEXT[]),
('Indurate', '', 'adjective', 'C1', 'Hardened, obstinate, unfeeling, callous.', 'The doctor removed a lot of indurate skin from his wound.', ARRAY[]::TEXT[]),
('Ineffable', '/ɪˈnɛf.ə.bəl/', 'adjective', 'C2', 'Beyond expression in words; unspeakable.', '', ARRAY['indescribable','inexpressible','unspeakable','taboo','unspeakable']::TEXT[]),
('Ineluctable', '/ɪn.ɪˈlʌk.tə.bəl/', 'adjective', 'C2', 'Impossible to avoid or escape; inescapable, irresistible.', '', ARRAY[]::TEXT[]),
('Inept', '/ɪnˈɛpt/', 'adjective', 'C1', 'Not able to do something; not proficient; displaying incompetence.', '', ARRAY[]::TEXT[]),
('Inert', '/ɪnˈɝt/', 'adjective', 'C1', 'Unable to move or act; inanimate.', '', ARRAY['unreactive','dormant','motionless']::TEXT[]),
('Inexorable', '/ɪnˈɛksɔɹəbəl/', 'adjective', 'C1', 'Impossible to prevent or stop; inevitable.', '', ARRAY['implacable','ineluctable','inescapable','unpreventable','unrelenting']::TEXT[]),
('Infamy', '/ˈɪnfəmi/', 'noun', 'C1', 'The state of being infamous.', '', ARRAY[]::TEXT[]),
('Infatuate', '/ɪnˈfætju(w)ət/', 'adjective', 'C1', 'Infatuated, foolishly attracted to (someone).', '', ARRAY[]::TEXT[]),
('Inferno', '/ɪnˈfɝnoʊ/', 'noun', 'C1', 'A place or situation resembling Hell.', '', ARRAY[]::TEXT[]),
('Infiltrate', '/ˈɪnfɪltɹeɪt/', 'verb', 'C1', 'To surreptitiously penetrate, enter or gain access to.', 'High-grade tumors often infiltrate surrounding structures.', ARRAY[]::TEXT[]),
('Infinite', '/ˈɪnfɪnɪt/', 'adjective', 'C1', 'Indefinably large, countlessly great; immense.', '', ARRAY['immeasurable','inestimable','vast','countless','amaranthine']::TEXT[]),
('Infirm', '/ɪnˈfɝm/', 'adjective', 'C1', 'Weak or ill, not in good health.', 'He was infirm of body but still keen of mind, and though it looked like he couldn''''t walk across the room, he crushed me in debate.', ARRAY[]::TEXT[]),
('Inflame', '/ɪnˈfleɪm/', 'verb', 'C1', 'To set on fire; to kindle; to cause to burn, flame, or glow.', 'to inflame desire', ARRAY['anger','arouse','enrage','exasperate','excite']::TEXT[]),
('Infelicitous', '/ˌɪn.fəˈlɪs.ɪ.təs/', 'adjective', 'C2', 'Unhappy or unfortunate.', '', ARRAY[]::TEXT[]),
('Influx', '/ˈɪnˌflʌks/', 'noun', 'C1', 'A flow inward or into something; a coming in.', 'I''''ll buy a new computer when I get an influx of cash.', ARRAY['importation','infusion','introduction','intromission','instreaming']::TEXT[]),
('Infuse', '/ɪnˈfjuz/', 'verb', 'C1', 'To cause to become an element of something; to insert or fill.', 'Let it infuse for five minutes.', ARRAY[]::TEXT[]),
('Infuriate', '/ɪnˈfjʊəɹieɪt/', 'adjective', 'C1', 'Filled with, characterized by or expressing fury.', '', ARRAY['enraged','furious','raging','enraged','furious']::TEXT[]),
('Ingenious', '/ɪnˈdʒiːniəs/', 'adjective', 'C1', 'Displaying genius or brilliance; tending to invent.', 'This fellow is ingenious; he fixed a problem I didn''''t even know I had.', ARRAY[]::TEXT[]),
('Ingest', '/ɪnˈdʒɛst/', 'verb', 'C1', 'To take a substance (e.g. food) into the body of an organism, especially through the mouth and into the gastrointestinal tract.', '', ARRAY[]::TEXT[]),
('Ingrained', '', 'adjective', 'C1', 'Being an element; present in the essence of a thing', '', ARRAY['bred-in-the-bone','radicated','inherent']::TEXT[]),
('Ingrate', '/ˈɪnɡɹeɪt/', 'adjective', 'C1', 'Unpleasant, unfriendly', '', ARRAY[]::TEXT[]),
('Ingratiating', '', 'adjective', 'C1', 'Which ingratiates; which attempts to bring oneself into the favour of another, often with flattery or insincerity.', 'That was an ingratiating smile.', ARRAY[]::TEXT[]),
('Inimitable', '/ɪnˈɪmɪtəbl̩/', 'adjective', 'C2', 'Beyond imitation, surpassing all others, matchless.', '', ARRAY[]::TEXT[]),
('Iniquity', '/ɪnˈɪkwɪti/', 'noun', 'C1', 'Deviation from what is right; gross injustice, sin, wickedness.', '', ARRAY[]::TEXT[]),
('Inquisitive', '/ɪŋˈkwɪzətɪv/', 'adjective', 'C1', 'Eager to acquire knowledge.', '', ARRAY[]::TEXT[]),
('Insensible', '/ɪnˈsɛn.sɪ.bl̩/', 'adjective', 'C1', 'Unable to be perceived by the senses.', '', ARRAY['insensitive']::TEXT[]),
('Insensitive', '/ɪnˈsɛnsɪtɪv/', 'adjective', 'C1', 'Not expressing normal physical feeling', '', ARRAY['unaffected','unsensitive']::TEXT[]),
('Insentient', '', 'adjective', 'C1', 'Having no consciousness or animation; not sentient', '', ARRAY[]::TEXT[]),
('Insouciant', '/ɪnˈsuːsɪənt/', 'adjective', 'C1', 'Casually unconcerned; carefree, indifferent, nonchalant.', 'an insouciant gesture', ARRAY[]::TEXT[]),
('Instate', '/ɪnˈsteɪt/', 'verb', 'C1', 'To install (someone) in office; to establish.', '', ARRAY[]::TEXT[]),
('Instigate', '/ˈɪnstəɡeɪt/', 'verb', 'C1', 'To incite; to bring about by urging or encouraging', 'to instigate a riot', ARRAY['animate','encourage','impel','incite','provoke']::TEXT[]),
('Instill', '/ɪnˈstɪl/', 'verb', 'C1', 'To cause a quality to become part of someone''''s nature.', 'It is important to instill discipline in a child at an early age.', ARRAY[]::TEXT[]),
('Instrumentalist', '', 'noun', 'C1', 'One who plays a musical instrument, as distinguished from a vocalist', '', ARRAY[]::TEXT[]),
('Insubordinate', '', 'adjective', 'C1', 'Rebellious or defiant to authority.', '', ARRAY[]::TEXT[]),
('Insular', '/ˈɪnsjələ/', 'adjective', 'C1', 'Of, pertaining to, being, or resembling an island or islands.', '', ARRAY[]::TEXT[]),
('Insulate', '', 'verb', 'C1', 'To separate, detach, or isolate.', 'Ceramic can be used to insulate power lines.', ARRAY['isolate']::TEXT[]),
('Insurgent', '/ɪnˈsəːdʒ(ə)nt/', 'adjective', 'C1', 'Rebellious, opposing authority.', '', ARRAY[]::TEXT[]),
('Intangible', '/ɪnˈtandʒɪbl/', 'adjective', 'C1', 'Incapable of being perceived by the senses; incorporeal', '', ARRAY[]::TEXT[]),
('Intelligible', '/ɪnˈtɛlədʒəbl̩/', 'adjective', 'C1', 'Capable of being understood; clear to the mind.', '', ARRAY['understandable']::TEXT[]),
('Intemperate', '', 'adjective', 'C1', 'Lacking moderation, temper or control.', 'Bad week for: Jeremy Clarkson, who has become a hate figure in Malaysia after launching an intemperate attack on a Malaysian built car - The Week, 14 April 2007, 609, 4.', ARRAY[]::TEXT[]),
('Inter', '/ɪnˈtɜː(ɹ)/', 'verb', 'C1', 'To bury in a grave.', '', ARRAY['bury','entomb','inearth','inhume','bury']::TEXT[]),
('Intercessor', '/ˈɪntə(ɹ)ˌsɛsə(ɹ)/', 'noun', 'C1', 'A person who intercedes; a mediator; one who reconciles enemies, or pleads for another.', '', ARRAY[]::TEXT[]),
('Interdict', '/ɪntəˈdɪkt/', 'verb', 'C1', 'To exclude (someone or somewhere) from participation in church services; to place under a religious interdict.', '', ARRAY[]::TEXT[]),
('Interlock', '', 'verb', 'C1', 'To fit or clasp together securely.', '', ARRAY[]::TEXT[]),
('Interminable', '/ɪnˈtɜː(ɹ).mɪn.ə.bəl/', 'adjective', 'C1', 'Existing or occurring without interruption or end; ceaseless, unending.', '', ARRAY[]::TEXT[]),
('Interregnum', '/ˌɪntəɹˈɹɛɡnəm/', 'noun', 'C1', 'The period of time between the end of a sovereign''''s reign and the accession of another sovereign.', 'The Sasanian Interregnum of 628-632', ARRAY['hiatus','moratorium','recess']::TEXT[]),
('Interrogate', '', 'verb', 'C1', 'To question or quiz, especially in a thorough and/or aggressive manner', 'The police interrogated the suspect at some length before they let him go.', ARRAY[]::TEXT[]),
('Intimidate', '/ɪnˈtɪmɪdeɪt/', 'verb', 'C1', 'To make timid or afraid; to cause to feel fear or nervousness; to deter, especially by threats of violence', 'He''''s trying to intimidate you. If you ignore him, hopefully he''''ll stop.', ARRAY['abash','abash']::TEXT[]),
('Intoxicant', '', 'adjective', 'C1', 'Intoxicating.', '', ARRAY[]::TEXT[]),
('Intrigue', '', 'verb', 'C1', 'To conceive or carry out a secret plan intended to harm; to form a plot or scheme.', '', ARRAY[]::TEXT[]),
('Intrinsic', '/ɪn.ˈtɹɪn.zɪk/', 'adjective', 'C1', 'Innate, inherent, inseparable from the thing itself, essential.', 'the intrinsic merit of an action', ARRAY['essential','inherent','innate','proper to','essential']::TEXT[]),
('Intuitive', '/ɪnˈtjuːɪtɪv/', 'adjective', 'C1', 'Spontaneous, without requiring conscious thought.', 'The intuitive response turned out to be correct.', ARRAY[]::TEXT[]),
('Inure', '/ɪˈnjɔː/', 'verb', 'C2', 'To cause someone to become accustomed to something (usually) unpleasant.', 'Jim buys a beach house that includes the right to travel across the neighbor''''s property to get to the water. That right of way is said, cryptically, "to inure to the benefit of Jim".', ARRAY['habituate','harden','toughen','habituate','harden']::TEXT[]),
('Invective', '/ɪnˈvɛktɪv/', 'adjective', 'C2', 'Characterized by invection or railing.', 'Tom''''s speeches became diatribes — each more invective than the last.', ARRAY['abusive','critical','denunciatory','satirical','vitriolic']::TEXT[]),
('Inveigh', '/ɪnˈveɪ/', 'verb', 'C1', '(with against or occasionally about, formerly also with on, at, upon) To complain loudly, to give voice to one''''s censure or criticism', '', ARRAY[]::TEXT[]),
('Inveigle', '/ɪnˈveɪ.ɡəl/', 'verb', 'C1', 'To convert, convince, or win over with flattery or wiles.', 'He inveigled an introduction to her.', ARRAY['entice','induce','put someone up to something','entice','induce']::TEXT[]),
('Inventory', '/ɪnˈvɛn.tə.ɹi/', 'verb', 'C1', '(operations) To take stock of the resources or items on hand; to produce an inventory.', 'The main job of the night shift was to inventory the store, and restock when necessary.', ARRAY['index','inventorize','take inventory','take stock']::TEXT[]),
('Invidious', '/ɪnˈvɪdi.əs/', 'adjective', 'C2', 'Causing ill will, envy, or offense.', '', ARRAY[]::TEXT[]),
('Invigorate', '/ɪnˈvɪɡəɹeɪt/', 'verb', 'C1', 'To impart vigor, strength, or vitality to.', 'Exercise is invigorating.', ARRAY[]::TEXT[]),
('Invincible', '/ɪnˈvɪns.ɪbl̩/', 'adjective', 'C1', 'Impossible to defeat, destroy or kill; too powerful to be defeated or overcome.', '', ARRAY['unconquerable','undefeatable','unconquerable','undefeatable']::TEXT[]),
('Irate', '/aɪˈɹeɪt/', 'adjective', 'C1', 'Extremely angry; wrathful; enraged.', '', ARRAY['furious','infuriated','sore','furious','infuriated']::TEXT[]),
('Ironclad', '', 'adjective', 'C1', 'Covered with iron, steel, or some metal, armor-plated.', 'The suspect had an ironclad alibi for his whereabouts on the night of the crime.', ARRAY[]::TEXT[]),
('Irreducible', '/ˌɪɹɪˈdjuːsɪbəl/', 'adjective', 'C1', 'Not able to be reduced or lessened.', '', ARRAY[]::TEXT[]),
('Irrigate', '/ˈɪɹəˌɡeɪt/', 'verb', 'C1', 'To supply (farmland) with water, by building ditches, pipes, etc.', 'We need to irrigate the land before we plant the crops.', ARRAY[]::TEXT[]),
('Irritate', '/ˈɪɹɪteɪt/', 'verb', 'C1', 'To provoke impatience, anger, or displeasure in.', '', ARRAY['provoke','rile']::TEXT[]),
('Isthmus', '/ˈɪs.məs/', 'noun', 'C1', 'A narrow strip of land, bordered on both sides by water, and connecting two larger landmasses.', '', ARRAY[]::TEXT[]),
('Itinerary', '/aɪˈtɪnəɹi/', 'adjective', 'C1', 'Itinerant; travelling from place to place; done on a journey', '', ARRAY[]::TEXT[]),
('Jabber', '/ˈdʒæbə(ɹ)/', 'verb', 'C1', 'To talk rapidly, indistinctly, or unintelligibly; to utter gibberish or nonsense.', '', ARRAY[]::TEXT[]),
('Jaded', '/ˈdʒeɪdɪd/', 'adjective', 'C1', 'Bored or lacking enthusiasm, typically after having been over exposed to, or having consumed too much of something.', '', ARRAY['blasé','cloyed','glutted','gorged','sated']::TEXT[]),
('Jape', '/d͡ʒeɪp/', 'verb', 'C1', 'To jest; play tricks.', '', ARRAY['befool','gibe','make fun of','razz','trick']::TEXT[]),
('Jarring', '', 'adjective', 'C1', 'That jars (clashes or disagrees); incongruous, conflictful.', '', ARRAY[]::TEXT[]),
('Jaundice', '/ˈdʒɔːndɪs/', 'verb', 'C2', 'To affect with jaundice; to color by prejudice or envy; to prejudice.', '', ARRAY[]::TEXT[]),
('Jaunty', '/ˈdʒɑːn.ti/', 'adjective', 'C1', 'Airy; showy; finical.', 'He wore a jaunty outfit that was all the rage.', ARRAY[]::TEXT[]),
('Jejune', '/dʒiˈdʒuːn/', 'adjective', 'C2', '(now rare) Not nutritious.', '', ARRAY['dry','insipid','poor','dry','insipid']::TEXT[]),
('Jest', '/dʒɛst/', 'verb', 'C1', 'To tell a joke; to talk in a playful manner; to make fun of something or someone.', 'Surely you jest!', ARRAY['banter','kid','mock','tease']::TEXT[]),
('Jeopardy', '/ˈd͡ʒɛpədi/', 'verb', 'C1', 'To jeopardize; to endanger.', '', ARRAY[]::TEXT[]),
('Jettison', '/ˈdʒɛtɪsən/', 'verb', 'C1', 'To eject from a boat, submarine, aircraft, spaceship or hot-air balloon, so as to lighten the load.', 'The ballooners had to jettison all of their sand bags to make it over the final hill.', ARRAY['chuck','discard','ditch','dump','junk']::TEXT[]),
('Jibe', '/dʒaɪb/', 'verb', 'C1', 'To reproach with contemptuous words; to deride, to mock, to taunt.', '', ARRAY['flout','flout']::TEXT[]),
('Jitter', '/ˈdʒɪt.ə(ɹ)/', 'verb', 'C1', 'To be nervous.', '', ARRAY['fidget']::TEXT[]),
('Jocund', '/ˈdʒɒkənd/', 'adjective', 'C1', 'Jovial; exuberant; lighthearted; merry and in high spirits; exhibiting happiness.', '', ARRAY[]::TEXT[]),
('Jog', '/dʒɒɡ/', 'verb', 'C1', 'To push slightly; to move or shake with a push or jerk, as to gain the attention of; to jolt.', 'jog one''''s elbow', ARRAY[]::TEXT[]),
('Jolt', '/dʒɒlt/', 'verb', 'C1', 'To push or shake abruptly and roughly.', 'The bus jolted its passengers at every turn.', ARRAY[]::TEXT[]),
('Jot', '/dʒɒt/', 'verb', 'C1', '(usually with "down") To write quickly.', 'Tell me your order, so I can jot it down.', ARRAY[]::TEXT[]),
('Judicious', '/dʒuˈdɪʃ.əs/', 'adjective', 'C1', 'Having, characterized by, or done with good judgment or sound thinking.', '', ARRAY['sagacious']::TEXT[]),
('Juggernaut', '/ˈdʒʌ.ɡə.nɔːt/', 'noun', 'C2', 'A literal or metaphorical force or object regarded as unstoppable, that will crush all in its path.', '', ARRAY[]::TEXT[]),
('Kangaroo', '/kaŋ.ɡə.ˈɹuː/', 'adjective', 'C1', 'Of or relating to Australia.', '', ARRAY[]::TEXT[]),
('Ken', '/kɛn/', 'verb', 'C1', 'To give birth, conceive, beget, be born; to develop (as a fetus); to nourish, sustain (as life).', '', ARRAY[]::TEXT[]),
('Kindle', '/ˈkɪndl/', 'verb', 'C1', 'To start (a fire) or light (a torch, a match, coals, etc.).', 'He kindled an enthusiasm for the project in his fellow workers.', ARRAY['arouse','inspire','ignite']::TEXT[]),
('Kindred', '/ˈkɪndɹəd/', 'adjective', 'C1', 'Of the same nature, or of similar character.', 'kindred tongues', ARRAY[]::TEXT[]),
('Knack', '/næk/', 'verb', 'C1', 'To crack; to make a sharp, abrupt noise; to chink.', '', ARRAY[]::TEXT[]),
('Knave', '/neɪv/', 'noun', 'C1', 'A boy; especially, a boy servant.', '', ARRAY['rogue','villain','rogue','villain']::TEXT[]),
('Knead', '/niːd/', 'verb', 'C1', 'To work and press into a mass, usually with the hands; especially, to work, as by repeated pressure with the knuckles, into a well mixed mass, the materials of bread, cake, etc.', '', ARRAY['amalgamate']::TEXT[]),
('Knit', '/ˈnɪt/', 'verb', 'C1', 'To turn thread or yarn into a piece of fabric by forming loops that are pulled through each other. This can be done by hand with needles or by machine.', 'The first generation knitted to order; the second still knits for its own use; the next leaves knitting to industrial manufacturers.', ARRAY[]::TEXT[]),
('Knotty', '', 'adjective', 'C1', 'Full of knots.', 'knotty pine', ARRAY['intricate','thorny','intricate','thorny']::TEXT[]),
('Kudos', '/ˈkjuːdɒs/', 'noun', 'C1', 'Praise; accolades.', 'The talented, young playwright received much kudos for his new drama.', ARRAY[]::TEXT[]),
('Labile', '/ˈleɪbaɪl/', 'adjective', 'C1', 'Liable to slip, err, fall, or apostatize.', 'Certain drugs can be conjugated to polymer molecules with a linkage that is labile at low pH to effect controlled release in a cellular endosome.', ARRAY['unstable','unstable']::TEXT[]),
('Labored', '', 'adjective', 'C1', 'Expressive of strenuous effort.', 'At the end of the marathon, her laboured breathing told us she was exhausted.', ARRAY[]::TEXT[]),
('Labyrinth', '/ˈlab.(ə)ɹ.ɪnθ/', 'verb', 'C1', 'To enclose in a labyrinth, or as though in a labyrinth.', '', ARRAY[]::TEXT[]),
('Lacerate', '', 'adjective', 'C2', 'Jagged, as if torn or lacerated.', 'The bract at the base is dry and papery, often lacerate near its apex.', ARRAY[]::TEXT[]),
('Lackluster', '', 'adjective', 'C1', 'Lacking brilliance or intelligence.', 'The actor gave a lackluster performance in his latest film.', ARRAY[]::TEXT[]),
('Lachrymose', '/ˈlæk.ɹɪ.moʊs/', 'adjective', 'C2', 'Tearful, sorrowful, sad, pertaining to tears, weeping, causing tears or crying.', '', ARRAY[]::TEXT[]),
('Lambaste', '/læmˈbeɪst/', 'verb', 'C1', 'To scold, reprimand or criticize harshly.', 'Her first novel was well and truly lambasted by the critics.', ARRAY['beat','hit','thrash','berate','scold']::TEXT[]),
('Lament', '/ləˈmɛnt/', 'verb', 'C1', 'To express grief; to weep or wail; to mourn.', '', ARRAY['bewail']::TEXT[]),
('Lamentable', '/ləˈmɛn.tə.bəl/', 'adjective', 'C1', 'Causing sorrow, distress or regret; deplorable, pitiful or distressing.', '', ARRAY[]::TEXT[]),
('Laminate', '/ˈlæmɪneɪt/', 'adjective', 'C1', 'Consisting of, or covered with, laminae, or thin plates, scales, or layers, one over another; laminated.', '', ARRAY[]::TEXT[]),
('Lampoon', '/læmˈpuːn/', 'verb', 'C2', 'To satirize or poke fun at.', '', ARRAY[]::TEXT[]),
('Landfill', '/ˈlænd.fɪl/', 'verb', 'C1', 'To dispose of (garbage) by burying it at a landfill site.', '', ARRAY[]::TEXT[]),
('Languish', '/ˈlæŋ.ɡwɪʃ/', 'verb', 'C2', 'To lose strength and become weak; to be in a state of weakness or sickness.', 'He languished without his girlfriend', ARRAY[]::TEXT[]),
('Languor', '/ˈlæŋɡə/', 'noun', 'C1', 'A state of the body or mind caused by exhaustion or disease and characterized by a languid or weary feeling; lassitude; an instance of this.', 'languor of convalescence', ARRAY['torpor','torpor']::TEXT[]),
('Lank', '/læŋk/', 'adjective', 'C1', 'Slender or thin; not well filled out; not plump; shrunken; lean.', '', ARRAY['lax','loose','nutant','insufficient','scarce']::TEXT[]),
('Lapse', '/læps/', 'verb', 'C1', 'To fall away gradually; to subside.', '', ARRAY[]::TEXT[]),
('Larder', '/ˈlɑː.də/', 'noun', 'C1', 'A cool room in a domestic house where food is stored, but larger than a pantry.', '', ARRAY[]::TEXT[]),
('Largesse', '/lɑːˈdʒɛs/', 'noun', 'C1', 'Generosity in the giving of gifts or money.', '', ARRAY['benevolence','generosity','graciousness','boon']::TEXT[]),
('Lariat', '/ˈlæɹɪət/', 'noun', 'C1', 'An attack where the wrestler runs towards an opponent, wraps his arm around their upper chest and neck and then forces them to the ground.', '', ARRAY[]::TEXT[]),
('Lash', '/læʃ/', 'verb', 'C1', 'To strike with a lash; to whip or scourge with a lash, or with something like one.', '', ARRAY['berate','berate']::TEXT[]),
('Lassitude', '/ˈlæsɪˌtjuːd/', 'noun', 'C1', 'Lethargy or lack of energy; fatigue.', '', ARRAY[]::TEXT[]),
('Latent', '/ˈleɪ.tənt/', 'adjective', 'C1', 'Existing or present but concealed or inactive.', '', ARRAY['hidden','invisible','dormant']::TEXT[]),
('Lathe', '/leɪð/', 'verb', 'C1', 'To invite; bid; ask.', '', ARRAY[]::TEXT[]),
('Latitude', '/ˈlæt.ɪ.tjuːd/', 'noun', 'C1', 'The angular distance north or south from a planet''''s equator, measured along the meridian of that particular point.', 'His parents gave him a great deal of latitude.', ARRAY[]::TEXT[]),
('Laudatory', '/ˈlɔːdətɹi/', 'adjective', 'C1', 'Of or pertaining to praise, or the expression of praise.', 'laudatory verses', ARRAY[]::TEXT[]),
('Lavish', '/ˈlævɪʃ/', 'adjective', 'C1', 'Expending or bestowing profusely; profuse; prodigal.', 'lavish of money; lavish of praise', ARRAY['extravagant','exuberant','immoderate','prodigal','profuse']::TEXT[]),
('Leaven', '/ˈlɛv.ən/', 'verb', 'C1', 'To add a leavening agent.', '', ARRAY[]::TEXT[]),
('Leer', '/lɪə/', 'verb', 'C1', 'To look sideways or obliquely; now especially with sexual desire or malicious intent.', '', ARRAY[]::TEXT[]),
('Legion', '/ˈliːdʒən/', 'adjective', 'C1', 'Numerous; vast; very great in number', 'Russia’s labor and capital resources are woefully inadequate to overcome the state’s needs and vulnerabilities, which are legion.', ARRAY['multitudinous','numerous','multitudinous','numerous']::TEXT[]),
('Loutish', '', 'adjective', 'C1', 'Resembling a lout.', '', ARRAY['hoonish','yobbish']::TEXT[]),
('Lubricate', '', 'verb', 'C1', 'To make slippery or smooth (normally to minimize friction) by applying a lubricant.', '', ARRAY['lube']::TEXT[]),
('Lucubration', '', 'noun', 'C1', 'Intense and prolonged study or meditation; especially, late at night.', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
