INSERT INTO words (word, phonetic, pos, level, def_en, ex_en, synonyms) VALUES
('Advert', '/ˈædvɜː(ɹ)t/', 'noun', 'C1', 'An advertisement, an ad.', '', ARRAY[]::TEXT[]),
('Affidavit', '/ˌæfɪˈdeɪvɪt/', 'noun', 'C1', 'A signed document wherein an affiant makes a sworn statement.', 'He submitted his affidavit rather than appearing to testify in court.', ARRAY[]::TEXT[]),
('Affinity', '/əˈfɪnɪti/', 'noun', 'C1', 'A natural attraction or feeling of kinship to a person or thing.', '', ARRAY[]::TEXT[]),
('Aggrandize', '/əˈɡɹændaɪ̯z/', 'verb', 'C1', 'To make great; to enlarge; to increase.', 'to aggrandize one''''s authority, distress', ARRAY[]::TEXT[]),
('Aggravate', '/ˈæɡ.ɹə.veɪ̯t/', 'verb', 'C1', 'To make (an offence) worse or more severe; to increase in offensiveness or heinousness.', 'He aggravated the story.', ARRAY['exasperate','irritate','provoke','exacerbate','exaggerate']::TEXT[]),
('Aggregate', '', 'adjective', 'C1', 'Formed by a collection of particulars into a whole mass or sum; collective; combined; added up.', 'aggregate glands', ARRAY[]::TEXT[]),
('Agitate', '/ˈæ.dʒɪ.teɪt/', 'verb', 'C1', 'To disturb or excite; to perturb or stir up (a person).', 'He was greatly agitated by the news.', ARRAY['canvass','debate','discuss','distract','disturb']::TEXT[]),
('Agog', '/əˈɡɒɡ/', 'adjective', 'C1', 'In eager desire, eager, astir.', '', ARRAY['all a-gog','all agog']::TEXT[]),
('Agonize', '/ˈæ.ɡən.aɪz/', 'verb', 'C1', 'To writhe with agony; to suffer violent anguish.', '', ARRAY[]::TEXT[]),
('Agrarian', '/əˈɡɹɛ(ə)ɹi.ən/', 'adjective', 'C1', 'Of, or relating to, the ownership, tenure and cultivation of land.', '', ARRAY[]::TEXT[]),
('Airtight', '', 'adjective', 'C1', 'Impermeable to air or other gases.', 'We have an airtight argument they won’t be able to punch holes in.', ARRAY['hermetic']::TEXT[]),
('Alacrity', '[əˈlækɹɨti]', 'noun', 'C2', 'Eagerness; liveliness; enthusiasm.', '', ARRAY['avidity','eagerness','enthusiasm','willingness','briskness']::TEXT[]),
('Albino', '/alˈbiːnoː/', 'adjective', 'C1', 'Congenitally lacking melanin pigmentation in the skin, eyes, and hair or feathers (or more rarely only in the eyes); born with albinism.', '', ARRAY['albinal','albinic','albinistic','albinoid','amelanistic']::TEXT[]),
('Alchemy', '/ˈælkəmi/', 'noun', 'C1', 'The ancient search for a universal panacea, and of the philosopher''''s stone, that eventually developed into chemistry.', '', ARRAY[]::TEXT[]),
('Alibi', '/ˈæl.ə.baɪ/', 'verb', 'C1', 'To provide an alibi for.', '', ARRAY[]::TEXT[]),
('Alienate', '/ˈeɪ.li.ə.neɪt/', 'adjective', 'C1', '(followed by "from") Estranged; withdrawn in affection; foreign', '', ARRAY[]::TEXT[]),
('Allay', '/əˈleɪ/', 'verb', 'C1', 'To make quiet or put at rest; to pacify or appease; to quell; to calm.', 'to allay popular excitement', ARRAY['abate','alleviate','appease','assuage','calm']::TEXT[]),
('Allegiance', '/əˈliː.dʒəns/', 'noun', 'C1', 'Loyalty to some cause, nation or ruler.', '', ARRAY['adherence','fidelity','loyalty']::TEXT[]),
('Alleviate', '/əˈli.vi.eɪt/', 'verb', 'C1', 'To make less severe, as a pain or difficulty.', 'Alcohol is often a cheap tool to alleviate the stress of a hard day.', ARRAY['address','allay','ameliorate','assuage','ease']::TEXT[]),
('Alliterate', '/əˈlɪ.tə.ɹeɪt/', 'verb', 'C1', 'To exhibit alliteration.', '', ARRAY['alliterize']::TEXT[]),
('Allude', '/əˈluːd/', 'verb', 'C1', 'To refer to something indirectly or by suggestion.', '', ARRAY[]::TEXT[]),
('Allure', '/əˈl(j)ʊɚ/', 'verb', 'C1', 'To entice; to attract.', '', ARRAY['attract','decoy','entice','seduce','tempt']::TEXT[]),
('Aloft', '/əˈlɑft/', 'adverb', 'C1', 'At, to, or in the air or sky.', 'high winds aloft', ARRAY[]::TEXT[]),
('Aloof', '/əˈluːf/', 'adjective', 'C1', 'Reserved and remote; either physically or emotionally distant; standoffish.', '', ARRAY[]::TEXT[]),
('Alphabetical', '/ˌæl.fəˈbɛt.ɪ.kəl/', 'adjective', 'C1', 'Pertaining to, furnished with, or expressed by letters of the alphabet.', 'All names were placed into an alphabetical list.', ARRAY[]::TEXT[]),
('Amalgamate', '/əˈmælɡəˌmeɪt/', 'adjective', 'C1', 'Coalesced; united; combined.', '', ARRAY[]::TEXT[]),
('Amble', '/ˈæm.bəl/', 'verb', 'C1', 'To stroll or walk slowly and leisurely.', '', ARRAY['saunter']::TEXT[]),
('Amenity', '/əˈmiːnəti/', 'noun', 'C1', 'Pleasantness.', 'We especially enjoyed the amenity of the climate on our last holiday.', ARRAY['facility','infrastructure','facility','infrastructure']::TEXT[]),
('Amicable', '/ˈæ.mɨ.kə.bəl/', 'adjective', 'C1', 'Showing friendliness or goodwill.', 'He was an amicable fellow with an easy smile.', ARRAY[]::TEXT[]),
('Amity', '/ˈæ.mɪ.ti/', 'noun', 'C1', 'Friendship. The cooperative and supportive relationship between people, or animals. In this sense, the term connotes a relationship which involves mutual knowledge, esteem, affection, and respect along with a degree of rendering service to friends in times of need or crisis.', '', ARRAY['friendliness','friendship']::TEXT[]),
('Amulet', '/ˈæm.jə.lɪt/', 'noun', 'C1', 'A kind of protective charm or ornament, often bearing magical symbols, worn for protection against ill will, negative influences or evil spirits.', '', ARRAY[]::TEXT[]),
('Analgesic', '/ˌæn.l̩ˈdʒiː.sɪk/', 'adjective', 'C1', '(pharmaceutical effect) Of or relating to analgesia; anodyne.', '', ARRAY[]::TEXT[]),
('Anarchist', '/ˈæn.ə.kɪst/', 'adjective', 'C1', '(somewhat rare) Relating to anarchism or to anarchists, anarchistic.', '', ARRAY[]::TEXT[]),
('Anathema', '/əˈnæθəmə/', 'noun', 'C2', 'A ban or curse pronounced with religious solemnity by ecclesiastical authority, often accompanied by excommunication; something denounced as accursed.', '', ARRAY['ban','curse','bête noire','ban','curse']::TEXT[]),
('Ancillary', '/ˈænsəˌleɹiː/', 'adjective', 'C1', 'Subordinate; secondary; auxiliary', '', ARRAY['accessory','accessory']::TEXT[]),
('Anecdote', '/ˈæ.nɪk.doʊt/', 'verb', 'C1', 'To tell anecdotes (about).', '', ARRAY[]::TEXT[]),
('Anemic', '/ʌˈni.mɪk/', 'adjective', 'C2', 'Of, pertaining to, or suffering from anemia.', '', ARRAY[]::TEXT[]),
('Anesthetic', '/ˌænəsˈtɛtɪk/', 'adjective', 'C1', 'Causing anesthesia; reducing pain sensitivity.', '', ARRAY[]::TEXT[]),
('Animate', '/ˈæ.nə.meɪt/', 'adjective', 'C1', 'That which lives.', 'She is an engaging and animate speaker.', ARRAY['active','dynamic','energetic','lively','perky']::TEXT[]),
('Animus', '/ˈæ.nɪ.məs/', 'noun', 'C1', 'The basic impulses and instincts which govern one''''s actions.', '', ARRAY['bad blood']::TEXT[]),
('Annals', '/ˈæn.əlz/', 'noun', 'C1', 'The record of a single event or item.', '', ARRAY[]::TEXT[]),
('Annul', '/əˈnʌl/', 'verb', 'C1', 'To formally revoke the validity of.', '', ARRAY[]::TEXT[]),
('Antagonize', '', 'verb', 'C1', 'To work against; to oppose (especially to incite reaction)', 'The other children constantly antagonized Joe to the point of tears.', ARRAY['harass','oppose','pester','harass','oppose']::TEXT[]),
('Antediluvian', '/ˌantɪdɪˈluːvɪən/', 'adjective', 'C1', 'Ancient or antiquated.', 'Those ideas are antediluvian.', ARRAY['antediluvial','antediluvial','old','prehistoric','dated']::TEXT[]),
('Anterior', '/ænˈtɪəriə(r)/', 'adjective', 'C1', 'Before in place.', '', ARRAY[]::TEXT[]),
('Anthology', '/ænˈθɒlədʒɪ/', 'noun', 'C1', 'A collection of literary works, such as poems or short stories, especially a collection from various authors.', '', ARRAY[]::TEXT[]),
('Antic', '/ˈæn.tɪk/', 'adjective', 'C2', 'Playful, funny, absurd', '', ARRAY[]::TEXT[]),
('Antidote', '/ˈæn.tə.dot/', 'verb', 'C1', 'To counteract as an antidote.', '', ARRAY[]::TEXT[]),
('Apocalyptic', '/əˈpɒ.kə.lɪp.tɪk/', 'adjective', 'C1', 'Of or relating to an apocalypse:', 'He was apocalyptically furious.', ARRAY[]::TEXT[]),
('Apoplectic', '/ˌæpəˈplɛktɪk/', 'adjective', 'C1', 'Of, or relating to apoplexy.', '', ARRAY[]::TEXT[]),
('Apostasy', '/əˈpɒstəsi/', 'noun', 'C1', 'The renunciation of a belief or set of beliefs.', '', ARRAY['backsliding','conversion','deconversion','defection','disaffection']::TEXT[]),
('Apostrophe', '/əˈpɒs.tɹə.fi/', 'noun', 'C1', 'The text character ’, which serves as a punctuation mark in various languages and as a diacritical mark in certain rare contexts.', '', ARRAY[]::TEXT[]),
('Apothecary', '/əˈpɒθəkəɹi/', 'noun', 'C1', 'A person who makes and provides/sells drugs and/or medicines.', '', ARRAY['chemist','druggist','pharmacist','apothecary''''s','apothecary''''s shop']::TEXT[]),
('Appall', '/əˈpɔːl/', 'verb', 'C1', 'To fill with horror; to dismay.', 'The evidence put forth at the court appalled most of the jury.', ARRAY['affright','daunt','depress','dismay','frighten']::TEXT[]),
('Apparel', '/əˈpæ.ɹəl/', 'verb', 'C1', 'To dress or clothe; to attire.', 'ships appareled to fight', ARRAY['dight','don','put on','adorn','ornament']::TEXT[]),
('Appellation', '/ˌæpəˈleɪʃən/', 'noun', 'C1', 'A name, title or designation.', '', ARRAY[]::TEXT[]),
('Applause', '/əˈplɔːz/', 'noun', 'C1', 'The act of applauding; approbation and praise publicly expressed by the clapping of hands, stamping or tapping of the feet, acclamation, huzzas, or other means; marked commendation.', '', ARRAY['acclaim','acclamation','approbation','approval','commendation']::TEXT[]),
('Apposite', '/ˈa.pə.zɪt/', 'adjective', 'C1', 'Strikingly appropriate or relevant; well suited to the circumstance or in relation to something.', '', ARRAY['to the point']::TEXT[]),
('Apprise', '/əˈpɹaɪ̯z/', 'verb', 'C1', 'To notify, or to make aware; to inform.', '', ARRAY['abreast','up to date','up-to-date']::TEXT[]),
('Approbation', '/ˌæp.ɹəʊˈbeɪ.ʃən/', 'noun', 'C1', 'The act of approving; an assenting to the propriety of a thing with some degree of pleasure or satisfaction; approval, sanction, commendation or official recognition.', '', ARRAY['approval','concurrence','consent','liking','sanction']::TEXT[]),
('Apron', '/ˈeɪ.pɹən/', 'verb', 'C1', 'To cover with, or as if with, an apron.', '', ARRAY[]::TEXT[]),
('Apropos', '/ˌæp.ɹəˈpəʊ/', 'adjective', 'C1', 'Of an appropriate or pertinent nature.', '', ARRAY['by the way','incidental','incidentally']::TEXT[]),
('Apt', '/æpt/', 'adjective', 'C1', 'Suitable; appropriate; fit or fitted; suited.', 'an apt metaphor', ARRAY['appropriate','meet','suitable','disposed','inclined']::TEXT[]),
('Aquatic', '/ɘˈkwɔ.tɘk/', 'adjective', 'C1', 'Relating to water; living in or near water, taking place in water.', '', ARRAY['waterly']::TEXT[]),
('Arbor', '', 'noun', 'C1', 'A shady sitting place or pergola usually in a park or garden, surrounded by climbing shrubs, vines or other vegetation.', '', ARRAY[]::TEXT[]),
('Arboreal', '/ɑɹˈbɔɹi.əl/', 'adjective', 'C1', 'Of, relating to, or resembling a tree.', '', ARRAY[]::TEXT[]),
('Archetype', '/ˈɑːkɪtaɪp/', 'verb', 'C1', 'To depict as, model using, or otherwise associate an object or subject with an archetype.', '', ARRAY[]::TEXT[]),
('Archipelago', '/ɑːkɪˈpɛləɡəʊ/', 'noun', 'C1', '(collective) A group of islands.', 'The Gulag Archipelago', ARRAY[]::TEXT[]),
('Ardor', '/ˈɑː(ɹ)də(ɹ)/', 'noun', 'C1', 'Great warmth of feeling; fervor; passion.', '', ARRAY['elan','fire in the belly','passion','zeal','intensity']::TEXT[]),
('Argot', '/ˈɑːɡəʊ/', 'noun', 'C1', 'A secret language or conventional slang peculiar to thieves, tramps and vagabonds.', 'The conversation was in the argot of the trade, full of acronyms and abbreviations that made no sense to the uninitiate.', ARRAY['cant','jargon','slang','jargon','cant']::TEXT[]),
('Arresting', '', 'adjective', 'C1', 'Striking, gripping', '', ARRAY[]::TEXT[]),
('Arrhythmic', '', 'adjective', 'C1', 'Without rhythm.', '', ARRAY['arhythmic','irrhythmic','nonrhythmic','unrhythmic']::TEXT[]),
('Arrogance', '/ˈæɹ.oʊ.ɡəns/', 'noun', 'C1', 'The state of being arrogant; a type of extreme or foolish pride in which someone feels much superior to another', '', ARRAY[]::TEXT[]),
('Artifacts', '', 'noun', 'C1', 'An object made or shaped by human hand or labor.', 'The spot on his lung turned out to be an artifact of the X-ray process.', ARRAY[]::TEXT[]),
('Ascendant', '/əˈsɛndənt/', 'adjective', 'C1', 'Rising, moving upward.', '', ARRAY[]::TEXT[]),
('Askew', '/əˈskjuː/', 'adjective', 'C1', 'Turned or twisted to one side.', '', ARRAY[]::TEXT[]),
('Asperity', '/əˈspɛɹɪti/', 'noun', 'C2', 'Roughness as of stone or weather.', 'the asperity of Maine''''s winter', ARRAY[]::TEXT[]),
('Aspersion', '', 'noun', 'C1', 'An attack on somebody''''s reputation or good name, often in the phrase to cast aspersions upon….', '', ARRAY['calumny','slander','calumny','slander']::TEXT[]),
('Aspirant', '/ˈæspəɹənt/', 'adjective', 'C1', 'Seeking advancement.', '', ARRAY[]::TEXT[]),
('Assent', '/əˈsɛnt/', 'verb', 'C1', 'To agree; to give approval.', '', ARRAY['affirm','allow','astipulate','aver','soothe']::TEXT[]),
('Assertive', '/əˈsɝtɪv/', 'adjective', 'C1', 'Boldly self-assured; confident without being aggressive.', '', ARRAY[]::TEXT[]),
('Assiduous', '/əˈsɪdjuːəs/', 'adjective', 'C1', 'Hard-working, diligent or regular (in attendance or work); industrious.', '', ARRAY['diligent','meticulous','sedulous','diligent','meticulous']::TEXT[]),
('Astounding', '', 'adjective', 'C1', 'That astounds or astound.', 'astounding success; an astounding spectacle', ARRAY['amazing','extraordinary','fantastic','incredible','marvelous']::TEXT[]),
('Astringent', '/əˈstɹɪn.dʒənt/', 'adjective', 'C1', 'Extremely sour, bitter.', '', ARRAY['smectic']::TEXT[]),
('Astrology', '/əˈstɹɒlədʒi/', 'noun', 'C1', 'Divination about human affairs or natural phenomena from the relative positions of celestial bodies.', '', ARRAY['astromancy','astrosophy','starcraft']::TEXT[]),
('Astute', '/əsˈtjuːt/', 'adjective', 'C1', 'Quickly and critically discerning.', '', ARRAY['crafty','shrewd','wily']::TEXT[]),
('Asunder', '/əˈsʌndə/', 'adverb', 'C1', 'Into separate parts or pieces.', 'Lest anyone find her treasure, she tore the map asunder and cast its pieces into the wind.', ARRAY['apart','in twain','apart','in twain']::TEXT[]),
('Barbarous', '/ˈbɑː(ɹ)bəɹəs/', 'adjective', 'C1', '(said of language) Not classical or pure.', 'By the known rules of antient libertie,', ARRAY[]::TEXT[]),
('Barefaced', '/ˈbeə(ɹ)feɪst/', 'adjective', 'C1', 'Undisguisedly offensive and bold; crude; coarse; brazen', '', ARRAY['bareface']::TEXT[]),
('Baroque', '/bæˈɹɒk/', 'adjective', 'C1', 'Ornate, intricate, decorated, laden with detail.', '', ARRAY[]::TEXT[]),
('Barrage', '/ˈbæɹɑːʒ/', 'verb', 'C1', 'To direct a barrage at.', '', ARRAY['bombard','bombard']::TEXT[]),
('Barren', '/ˈbæɹən/', 'adjective', 'C1', 'Unable to bear children; sterile.', 'I silently wept as my daughter''''s husband rejected her. What would she do now that she was no longer a maiden but also barren?', ARRAY['sterile']::TEXT[]),
('Barricade', '/ˌbæɹɪˈkeɪd/', 'verb', 'C1', 'To close or block a road etc., using a barricade', '', ARRAY[]::TEXT[]),
('Barter', '/ˈbɑːtə(ɹ)/', 'verb', 'C1', 'To exchange goods or services without involving money.', 'She bartered a bonsai for one of the rare books in my library.', ARRAY['swap','swop','trade']::TEXT[]),
('Baseboard', '', 'noun', 'C1', '(finish carpentry, interior decorating) A panel or molding between the floor and the interior wall of a structure', '', ARRAY['skirting board']::TEXT[]),
('Batch', '/bæt͡ʃ/', 'adjective', 'C1', 'Of a process, operating for a defined set of conditions, and then halting.', 'The plant had two batch assembly lines for packaging, as well as a continuous feed production line.', ARRAY[]::TEXT[]),
('Bathetic', '/bəˈθetɪk/', 'adjective', 'C1', 'Characterized by or pertaining to bathos.', '', ARRAY[]::TEXT[]),
('Bawdy', '/ˈbɔːdi/', 'adjective', 'C1', 'Soiled, dirty.', '', ARRAY[]::TEXT[]),
('Bedeck', '/bɪˈdɛk/', 'verb', 'C1', 'To deck, ornament, or adorn; to grace.', 'She bedecked her wedding gown with seed pearls.', ARRAY[]::TEXT[]),
('Belabor', '', 'verb', 'C1', 'To labour about; labour over; work hard upon; ply diligently.', '', ARRAY[]::TEXT[]),
('Beleaguer', '/bəˈliː.ɡə/', 'verb', 'C1', 'To besiege; to surround with troops.', '', ARRAY[]::TEXT[]),
('Bellwether', '/ˈbɛlwɛðɚ/', 'noun', 'C1', 'The leading sheep of a flock, having a bell hung round its neck.', '', ARRAY['gauge','indicator','sign']::TEXT[]),
('Beneficent', '/bəˈnɛf.ə.sənt/', 'adjective', 'C1', 'Given to acts that are kind, charitable, philanthropic or beneficial.', '', ARRAY['beneficient','generous']::TEXT[]),
('Berate', '/bɪˈɹeɪt/', 'verb', 'C1', 'To chide or scold vehemently', 'What society tells people, that they could "do whatever they want" to dissidents, and yet berates anyone for treating them well?', ARRAY[]::TEXT[]),
('Beseech', '/bɪˈsiːt͡ʃ/', 'verb', 'C1', 'To beg or implore (a person)', '', ARRAY[]::TEXT[]),
('Bibliography', '/bɪbliɒɡɹəfi/', 'noun', 'C1', 'A section of a written work containing citations, not quotations, to all the books referred to in the work.', '', ARRAY[]::TEXT[]),
('Bifurcate', '/ˈbʌɪ.fək.eɪt/', 'adjective', 'C1', 'Divided or forked into two; bifurcated.', '', ARRAY[]::TEXT[]),
('Bigot', '/ˈbɪɡət/', 'noun', 'C1', 'One who is narrow-mindedly devoted to one''''s own ideas and groups, and intolerant of (people of) differing ideas, races, genders, religions, politics, etc.', '', ARRAY[]::TEXT[]),
('Bland', '/blænd/', 'adjective', 'C1', 'Having a soothing effect; not irritating or stimulating.', 'a bland diet', ARRAY[]::TEXT[]),
('Blandishment', '/ˈblændɪʃmn̩t/', 'noun', 'C1', 'Flattering speech or actions designed to persuade or influence.', '', ARRAY[]::TEXT[]),
('Blasé', '/ˈblɑːzeɪ/', 'adjective', 'C1', 'Unimpressed with something because of over-familiarity.', '', ARRAY['casual','indifferent','jaded','nonchalant','unimpressed']::TEXT[]),
('Blazon', '/ˈbleɪzən/', 'verb', 'C1', 'To describe a coat of arms.', '', ARRAY[]::TEXT[]),
('Blemish', '/ˈblɛmɪʃ/', 'verb', 'C1', 'To spoil the appearance of.', '', ARRAY[]::TEXT[]),
('Blight', '/blaɪt/', 'verb', 'C1', 'To affect with blight; to blast; to prevent the growth and fertility of.', 'This vine never blights.', ARRAY[]::TEXT[]),
('Bliss', '/blɪs/', 'noun', 'C1', 'Perfect happiness', '', ARRAY[]::TEXT[]),
('Blithe', '/blaɪð/', 'adjective', 'C1', '(dated or literary) Happy, cheerful.', 'She had a blithe disregard of cultures outside the United States.', ARRAY[]::TEXT[]),
('Blueprint', '/ˈbluːˌpɹɪnt/', 'verb', 'C1', 'To make a blueprint for.', 'The architect blueprinted the renovation plan once the client had signed off.', ARRAY[]::TEXT[]),
('Blunder', '/ˈblʌn.də(ɹ)/', 'verb', 'C1', 'To make a clumsy or stupid mistake.', 'to blunder in preparing a medical prescription', ARRAY[]::TEXT[]),
('Blunt', '/blʌnt/', 'adjective', 'C1', 'Having a thick edge or point; not sharp.', 'the blunt admission that he had never liked my company', ARRAY['brusque','curt','harsh','impolite','rude']::TEXT[]),
('Blur', '/blɜ(ɹ)/', 'adjective', 'C1', 'In a state of doubt or confusion.', '', ARRAY[]::TEXT[]),
('Blurb', '/blɝ(ː)b/', 'verb', 'C1', 'To write or quote in a blurb.', '', ARRAY[]::TEXT[]),
('Blurt', '/ˈblɜːt/', 'verb', 'C1', 'To utter suddenly and unadvisedly; to speak quickly or without thought; to divulge inconsiderately — commonly with out.', 'Please think about your reply and don''''t just blurt out the first thing that comes to mind.', ARRAY[]::TEXT[]),
('Bluster', '/ˈblʌs.tə/', 'verb', 'C1', 'To speak or protest loudly.', 'When confronted by opposition his reaction was to bluster, which often cowed the meek.', ARRAY[]::TEXT[]),
('Bodyguard', '/ˈbɒdiɡɑːd/', 'verb', 'C1', 'To act as bodyguard for (someone); figuratively, to protect.', '', ARRAY[]::TEXT[]),
('Boggle', '/ˈbɒɡ.əl/', 'verb', 'C1', 'Either literally or figuratively to stop or hesitate as if suddenly seeing a bogle.', 'The dogs went on, but the horse boggled at the sudden appearance of the strange beast.', ARRAY[]::TEXT[]),
('Boisterous', '/ˈbɔɪstəɹəs/', 'adjective', 'C1', 'Full of energy; exuberant; noisy.', '', ARRAY[]::TEXT[]),
('Bombast', '/ˈbɒmbæst/', 'adjective', 'C1', 'Big without meaning, or high-sounding; bombastic, inflated; magniloquent.', '', ARRAY['aureate','highfalutin']::TEXT[]),
('Bonhomie', '/boʊnəˈmiː/', 'noun', 'C1', 'A pleasant, friendly, good-natured manner; an affable and approachable disposition; good-heartedness.', '', ARRAY['affability','friendliness','geniality','conviviality','warmth']::TEXT[]),
('Boo', '/buː/', 'verb', 'C1', 'To shout extended boos derisively.', 'When he took the podium, the crowd booed.', ARRAY[]::TEXT[]),
('Boor', '/bʊə/', 'noun', 'C1', 'A Boer, white South African of Dutch or Huguenot descent.', '', ARRAY[]::TEXT[]),
('Bootless', '', 'adjective', 'C1', 'Without boots.', '', ARRAY[]::TEXT[]),
('Bouquet', '/boʊˈkeɪ/', 'noun', 'C1', 'A bunch of cut flowers.', 'For my birthday I received two bouquets.', ARRAY[]::TEXT[]),
('Boycott', '/ˈbɔɪkɒt/', 'verb', 'C1', 'To abstain, either as an individual or a group, from using, buying, or dealing with someone or some organization as an expression of protest.', '', ARRAY['blackball','blacklist','embargo','withhold patronage']::TEXT[]),
('Bracing', '/ˈbɹeɪsɪŋ/', 'adjective', 'C1', 'Invigorating or stimulating.', '', ARRAY[]::TEXT[]),
('Bracket', '/ˈbɹækɪt/', 'verb', 'C1', 'To support by means of mechanical brackets.', 'I tried to hit the bullseye by first bracketing it with two shots and then splitting the difference with my third, but I missed.', ARRAY[]::TEXT[]),
('Braid', '/bɹeɪd/', 'verb', 'C1', 'To make a sudden movement with, to jerk.', '', ARRAY[]::TEXT[]),
('Brake', '/bɹeɪk/', 'noun', 'C1', 'A fern; bracken.', '', ARRAY[]::TEXT[]),
('Brash', '/bɹæʃ/', 'adjective', 'C1', '(of people or behaviour) Overly bold or self-assertive to the point of being insensitive, tactless or impudent; shameless.', 'a brash young businessman; a brash tabloid; a brash sense of humour', ARRAY['audacious','brassy','brazen','cocky','undiplomatic']::TEXT[]),
('Brassy', '/ˈbɹæs.i/', 'adjective', 'C1', 'Resembling brass.', 'The cup had a brassy color.', ARRAY[]::TEXT[]),
('Brattish', '', 'adjective', 'C1', 'Characteristic of a brat; childishly rude and annoying.', '', ARRAY['bratty']::TEXT[]),
('Bravado', '/brəˈvɑːdoʊ/', 'verb', 'C1', 'To swagger; to brag.', '', ARRAY[]::TEXT[]),
('Bravura', '/bɹəˈvjʊəɹə/', 'adjective', 'C1', 'Overly showy; ostentatious.', '', ARRAY[]::TEXT[]),
('Breezeway', '/ˈbɹiːzˌweɪ/', 'noun', 'C1', 'A covered walkway, with open sides, that connects two buildings.', 'One of his favorite pastimes was strolling through the breezeway on warm spring afternoons.', ARRAY[]::TEXT[]),
('Brevity', '/ˈbɹɛvəti/', 'noun', 'C1', 'The quality of being brief in duration.', '', ARRAY['ephemerality','fleetingness','transiency','concision','laconicism']::TEXT[]),
('Bribe', '/bɹaɪb/', 'verb', 'C1', 'To give a bribe to; specifically, to ask a person to do something, usually against his/her will, in exchange for some type of reward or relief from potential trouble.', 'She was accused of trying to bribe the jury into making false statements.', ARRAY[]::TEXT[]),
('Bridle', '/ˈbɹaɪdəl/', 'verb', 'C2', 'To put a bridle on.', '', ARRAY['restrain']::TEXT[]),
('Brisk', '/bɹɪsk/', 'adjective', 'C1', 'Full of liveliness and activity; characterized by quickness of motion or action', 'We took a brisk walk yesterday.', ARRAY['lively','quick','spirited','lively','quick']::TEXT[]),
('Bristle', '/ˈbɹɪs.l̩/', 'verb', 'C2', 'To rise or stand erect, like bristles.', 'The employees bristled at the prospect of working through the holidays.', ARRAY[]::TEXT[]),
('Brittle', '/ˈbɹɪtl̩/', 'adjective', 'C1', 'Inflexible, liable to break or snap easily under stress or pressure.', 'A diamond is hard but brittle.', ARRAY[]::TEXT[]),
('Broach', '/bɹəʊtʃ/', 'verb', 'C1', 'To make a hole in, especially a cask of liquor, and put in a tap in order to draw the liquid.', 'French knights at Agincourt were unable to broach the English line.', ARRAY[]::TEXT[]),
('Bromide', '/ˈbɹəʊ.maɪd/', 'noun', 'C2', 'A binary compound of bromine and some other element or radical.', 'My adviser at college was a bromide who had not had an original thought in years.', ARRAY['platitude','platitude']::TEXT[]),
('Brook', '/bɹʊk/', 'verb', 'C2', 'To use; enjoy; have the full employment of.', 'I will not brook any disobedience. I will brook no refusal. I will brook no impertinence.', ARRAY['apply','employ','utilize']::TEXT[]),
('Browbeat', '/ˈbɹaʊ.biːt/', 'verb', 'C2', 'To bully in an intimidating, bossy, or supercilious way.', 'Though the teacher browbeat all the children, they still acted out during the lesson.', ARRAY['bully','cow','domineer','intimidate']::TEXT[]),
('Bruit', '/bɹuːt/', 'verb', 'C1', 'To disseminate, promulgate, or spread news, a rumour, etc.', '', ARRAY[]::TEXT[]),
('Budge', '/bʌdʒ/', 'adjective', 'C1', 'Brisk; stirring; jocund.', '', ARRAY[]::TEXT[]),
('Buffoon', '/bəˈfuːn/', 'verb', 'C1', 'To behave like a buffoon', '', ARRAY[]::TEXT[]),
('Bulge', '/bʌldʒ/', 'verb', 'C1', 'To stick out from (a surface).', 'He stood six feet tall, with muscular arms bulging out of his black T-shirt.', ARRAY[]::TEXT[]),
('Bully', '/ˈbʊli/', 'adjective', 'C1', 'Jovial and blustering.', 'a bully horse', ARRAY['dashing','excellent','excellent','dashing']::TEXT[]),
('Bumptious', '/ˈbʌmpʃəs/', 'adjective', 'C1', 'Obtrusively pushy; self-assertive to a pretentious extreme.', '', ARRAY[]::TEXT[]),
('Bungle', '/ˈbʌŋ.ɡ(ə)l/', 'verb', 'C1', 'To botch up, bumble or incompetently perform a task; to make or mend clumsily; to manage awkwardly.', '', ARRAY[]::TEXT[]),
('Buoy', '/ˈbɔɪ/', 'verb', 'C1', 'To keep afloat or aloft; used with up.', 'to buoy an anchor; to buoy or buoy off a channel', ARRAY[]::TEXT[]),
('Buoyant', '/ˈbɔɪ.ənt/', 'adjective', 'C1', 'Having buoyancy; able to float.', 'I’m in a buoyant mood.', ARRAY[]::TEXT[]),
('Burlesque', '/bə(ɹ)ˈlɛsk/', 'adjective', 'C1', 'Parodical; parodic', '', ARRAY[]::TEXT[]),
('Burnish', '/ˈbɜː(ɹ)nɪʃ/', 'verb', 'C1', 'To make smooth or shiny by rubbing; to polish; to shine.', 'In pottery, a stone is sometimes used to burnish a pot before firing, giving it a smooth, shiny look.', ARRAY['buff','furbish','polish','shine','wax']::TEXT[]),
('Byline', '/ˈbaɪlaɪn/', 'verb', 'C1', 'To provide (an article) with a byline.', '', ARRAY[]::TEXT[]),
('Byzantine', '', 'adjective', 'C2', 'Of or pertaining to Byzantium.', 'a Byzantine system of regulations', ARRAY[]::TEXT[]),
('Cache', '/kæɪʃ/', 'verb', 'C1', 'To place in a cache.', '', ARRAY[]::TEXT[]),
('Cacophony', '/kəˈkɒfəni/', 'noun', 'C1', 'A mix of discordant sounds; dissonance.', '', ARRAY[]::TEXT[]),
('Cadge', '/kædʒ/', 'verb', 'C1', 'To obtain something by wit or guile; to convince people to do something they might not normally do.', '"Are ye gannin te cadge a lift of yoer fatha?"', ARRAY['bum','scrounge']::TEXT[]),
('Cajole', '/kəˈdʒəʊl/', 'verb', 'C1', 'To persuade someone to do something which they are reluctant to do, especially by flattery or promises; to coax.', '', ARRAY['butter up','coax','entice','inveigle','sweet-talk']::TEXT[]),
('Calcify', '/ˈkælsɪfaɪ/', 'verb', 'C1', 'To make something hard and stony by impregnating with calcium salts.', '', ARRAY[]::TEXT[]),
('Calibrate', '', 'verb', 'C1', 'To check or adjust by comparison with a standard.', '', ARRAY['tune']::TEXT[]),
('Calligraphy', '/kəˈlɪɡɹəfi/', 'noun', 'C1', 'The art or practice of writing letters and words in a decorative style; the letters and words so written.', '', ARRAY['chirography','penmanship']::TEXT[]),
('Callous', '/ˈkæləs/', 'adjective', 'C1', 'Emotionally hardened; unfeeling and indifferent to the suffering/feelings of others.', 'She was so callous that she could criticise a cancer patient for wearing a wig.', ARRAY['heartless','insensitive']::TEXT[]),
('Callow', '/ˈkaləʊ/', 'adjective', 'C2', 'Unfledged (of a young bird).', 'Those three young men are particularly callow youths.', ARRAY[]::TEXT[]),
('Callus', '/ˈkæləs/', 'verb', 'C1', 'To form such hardened tissue.', '', ARRAY[]::TEXT[]),
('Calorie', '/ˈkæləɹi/', 'noun', 'C1', '(nutrition) Kilogram calorie or large calorie. A unit of energy 1000 times larger than the gram calorie. It is equivalent to the gram kilocalorie, approximately 4.2 kilojoules.', '', ARRAY[]::TEXT[]),
('Calumniate', '/kəˈlʌmni.eɪt/', 'verb', 'C1', 'To make hurtful untrue comments about.', '', ARRAY['slander']::TEXT[]),
('Camaraderie', '/ˌkæməˈɹɑːdəɹi/', 'noun', 'C1', 'Close friendship in a group of friends or teammates.', '', ARRAY['chumminess','comradeliness','comradery','comradeship','team spirit']::TEXT[]),
('Cameo', '/ˈkæm.iː.əʊ/', 'verb', 'C1', 'To appear in a cameo role.', '', ARRAY[]::TEXT[]),
('Camouflage', '/ˈkæ.məˌflɑːʒ/', 'verb', 'C1', 'To hide or disguise something by covering it up or changing the way it looks.', '', ARRAY[]::TEXT[]),
('Canard', '/kəˈnɑːd/', 'noun', 'C2', 'A false or misleading report or story, especially if deliberately so.', '', ARRAY['hoax']::TEXT[]),
('Candor', '/ˈkæn.də(ɹ)/', 'noun', 'C1', 'Whiteness; brilliance; purity.', '', ARRAY['equity','fairness','frankness','honesty','parrhesia']::TEXT[]),
('Canon', '/ˈkæn.ən/', 'noun', 'C1', 'A generally accepted principle; a rule.', 'The trial must proceed according to the canons of law.', ARRAY['French canon']::TEXT[]),
('Canopy', '/ˈkæ.nə.pi/', 'verb', 'C1', 'To cover with or as if with a canopy.', '', ARRAY[]::TEXT[]),
('Canyon', '/ˈkænjən/', 'noun', 'C1', 'A valley, especially a long, narrow, steep valley, cut in rock by a river.', '', ARRAY['dale','dalles','gorge','gulch','ravine']::TEXT[]),
('Capitulate', '/kəˈpɪ.tjʊ.leɪt/', 'verb', 'C2', 'To surrender; to end all resistance, to give up; to go along with or comply.', 'He argued and hollered for so long that I finally capitulated just to make him stop.', ARRAY['wave the white flag']::TEXT[]),
('Caprice', '/kəˈpɹis/', 'noun', 'C1', 'An impulsive, seemingly unmotivated action, change of mind, or notion.', '', ARRAY[]::TEXT[]),
('Captivate', '/ˈkæptɪveɪt/', 'verb', 'C1', 'To attract and hold interest and attention of; charm.', '', ARRAY[]::TEXT[]),
('Caret', '/ˈkæɹ.ət/', 'noun', 'C1', 'A mark ⟨ ‸ ⟩ used by writers and proofreaders to indicate that something is to be inserted at that point.', '', ARRAY[]::TEXT[]),
('Careworn', '/ˈkɛːwɔːn/', 'adjective', 'C1', 'Worn down by cares: showing the signs of long-term stress, tired and haggard due to prolonged worry.', 'The weeks of working hard to look after his sick family left him looking careworn.', ARRAY[]::TEXT[]),
('Caricature', '/ˈkæɹɪkətʃʊə/', 'verb', 'C1', 'To represent someone in an exaggerated or distorted manner.', '', ARRAY[]::TEXT[]),
('Carnal', '/ˈkɑɹnəl/', 'adjective', 'C1', 'Relating to the physical and especially sexual appetites.', '', ARRAY[]::TEXT[]),
('Carouse', '/kəˈɹaʊz/', 'verb', 'C1', 'To engage in a noisy or drunken social gathering.', 'We are all going to carouse at Brian''''s tonight.', ARRAY[]::TEXT[]),
('Carp', '/ˈkɑːp/', 'noun', 'C1', 'Any of various freshwater fish of the family Cyprinidae, especially the common carp, Cyprinus carpio.', '', ARRAY[]::TEXT[]),
('Cartographer', '', 'noun', 'C1', 'One who makes maps or charts.', '', ARRAY['cartographist','mapmaker']::TEXT[]),
('Catalyze', '/ˈkætəˌlaɪz/', 'verb', 'C1', 'To bring about the catalysis of a chemical reaction.', '', ARRAY[]::TEXT[]),
('Catastrophe', '/kəˈtæstɹəfi/', 'noun', 'C1', 'Any large and disastrous event of great significance', '', ARRAY[]::TEXT[]),
('Categorical', '/ˌkætəˈɡɔɹɪk(ə)l/', 'adjective', 'C1', 'Absolute; having no exception.', '', ARRAY['absolute','categoric','unconditional']::TEXT[]),
('Catholic', '/ˈkaθ(ə)lɪk/', 'adjective', 'C2', 'Of the Western Christian church, as differentiated from e.g. the Orthodox church.', 'Christmas is celebrated at different dates in the Catholic and Orthodox calendars.', ARRAY[]::TEXT[]),
('Caustic', '/ˈkɒstɪk/', 'adjective', 'C1', 'Capable of burning, corroding or destroying organic tissue.', '', ARRAY['acidic','biting','burning','corrosive','searing']::TEXT[]),
('Caveat', '/ˈkeɪ-/', 'verb', 'C1', 'To qualify a statement with a caveat or proviso.', '', ARRAY[]::TEXT[]),
('Cavern', '/ˈkæv.ən/', 'verb', 'C1', 'To form a cavern or deep depression in.', 'catacombs caverning the hillsides', ARRAY[]::TEXT[]),
('Cavil', '/ˈkæv.əl/', 'verb', 'C1', 'To criticise for petty or frivolous reasons.', '', ARRAY['be hypercritical','nitpick','pettifog','split hairs','be hypercritical']::TEXT[]),
('Cavort', '/kəˈvɔːt/', 'verb', 'C1', '(originally intransitive) To prance, said of mounts', '', ARRAY['caper','frolic','prance','romp']::TEXT[]),
('Cede', '/siːd/', 'verb', 'C2', 'To give up; yield to another.', 'Edward decided to cede the province.', ARRAY[]::TEXT[]),
('Cement', '/səˈmɛnt/', 'verb', 'C1', 'To affix with cement.', 'to cement a cellar floor', ARRAY[]::TEXT[]),
('Censorious', '', 'adjective', 'C1', 'Addicted to censure and scolding; apt to blame or condemn; severe in making remarks on others, or on their writings or manners.', 'censorious remarks', ARRAY[]::TEXT[]),
('Census', '/ˈsɛnsəs/', 'verb', 'C1', 'To conduct a census on.', '', ARRAY[]::TEXT[]),
('Cessation', '/sɛˈseɪʃən/', 'noun', 'C1', 'A ceasing or discontinuance, for example of an action, whether temporary or final.', '', ARRAY['close','endpoint','terminus','hiatus','moratorium']::TEXT[]),
('Chaff', '/tʃæf/', 'verb', 'C1', 'To use light, idle language by way of fun or ridicule; to banter.', '', ARRAY[]::TEXT[]),
('Chagrin', '/ˈʃæɡ.ɹɪn/', 'adjective', 'C2', 'Feeling chagrin; annoyed; vexed, fretful.', '', ARRAY['chagrined']::TEXT[]),
('Chameleon', '/kəˈmiːljən/', 'adjective', 'C1', 'Describing something that changes color.', 'The wall was covered with a chameleon paint.', ARRAY[]::TEXT[]),
('Charade', '/ʃəˈɹeɪd/', 'verb', 'C1', 'To act out a charade (of); to gesture; to pretend.', '', ARRAY[]::TEXT[]),
('Charlatan', '/ˈʃɑːlətən/', 'noun', 'C2', 'A mountebank, someone who addresses crowds in the street; (especially), an itinerant seller of medicines or drugs.', '', ARRAY['swindler','trickster','swindler','trickster']::TEXT[]),
('Chary', '/ˈtʃɛəɹi/', 'adjective', 'C2', 'Careful, cautious, shy, wary.', '', ARRAY[]::TEXT[]),
('Chasm', '/ˈkæz(ə)m/', 'noun', 'C1', 'A deep, steep-sided rift, gap or fissure; a gorge or abyss.', '', ARRAY[]::TEXT[]),
('Chauvinistic', '', 'adjective', 'C1', 'Of or pertaining to chauvinism or chauvinists.', '', ARRAY[]::TEXT[]),
('Cherubic', '', 'adjective', 'C1', 'Of, or relating to a cherub; angelic.', '', ARRAY['cherubical','cherublike','cherubical','cherublike']::TEXT[]),
('Chevron', '/ˈʃɛvɹən/', 'verb', 'C1', 'To form or be formed into chevrons', '', ARRAY[]::TEXT[]),
('Chiaroscuro', '/ˌkjɒɹəˈskuɹoʊ/', 'adjective', 'C1', 'Possessing the qualities of a work of chiaroscuro.', '', ARRAY[]::TEXT[]),
('Chicanery', '/ʃɪˈkeɪn(ə)ɹi/', 'noun', 'C1', 'Deception by use of trickery, quibbling, or subterfuge.', '', ARRAY['dishonesty','fraud','subterfuge','trickery']::TEXT[]),
('Chide', '/tʃaɪd/', 'verb', 'C1', 'To admonish in blame; to reproach angrily.', '', ARRAY[]::TEXT[]),
('Choleric', '/kɘˈliɘɹɘk/', 'adjective', 'C2', '(according to theories of the four humours or temperaments) Having a temperament characterized by an excess of choler; easily becoming angry.', '', ARRAY['ill-tempered','irascible','angry','indignant','irate']::TEXT[]),
('Chord', '/kɔː(ɹ)d/', 'verb', 'C1', 'To write chords for.', 'This note chords with that one.', ARRAY[]::TEXT[]),
('Choreography', '/ˌkɔɹ.iˈɒɡ.ɹə.fi/', 'noun', 'C1', 'The art of creating, arranging and recording the dance movements of a work, such as a ballet.', 'She has staged many successful ballets, so her choreography skills must be excellent.', ARRAY[]::TEXT[]),
('Chorus', '/ˈkɔːɹəs/', 'verb', 'C1', 'To sing or recite in chorus.', '', ARRAY['duet']::TEXT[]),
('Chromatic', '', 'adjective', 'C1', 'Relating to or characterised by hue.', '', ARRAY[]::TEXT[]),
('Chuckle', '/ˈt͡ʃʌkəl/', 'verb', 'C1', 'To laugh quietly or inwardly.', 'She chuckled her assent to my offer as she got in the car.', ARRAY['grope','pet','touch up','coddle','posset']::TEXT[]),
('Churl', '/tʃəːl/', 'noun', 'C1', 'A rustic; a countryman or labourer; a free peasant (as opposed to a serf).', '', ARRAY[]::TEXT[]),
('Cineast', '', 'noun', 'C1', 'An enthusiast of film and the cinema.', '', ARRAY[]::TEXT[]),
('Cipher', '/ˈsaɪfɚ/', 'verb', 'C1', 'To calculate.', 'I never learned much more than how to read and cipher.', ARRAY[]::TEXT[]),
('Circuitous', '/sɜːˈkjuːɪtəs/', 'adjective', 'C1', 'Not direct or to the point.', '', ARRAY['indirect','roundabout','roundabout','tortuous']::TEXT[]),
('Circular', '/ˈsɜːk.jə.lə(ɹ)/', 'adjective', 'C1', 'Of or relating to a circle.', 'Your dictionary defines "brave" as "courageous", and "courageous" as "brave". That''''s a circular definition.', ARRAY[]::TEXT[]),
('Circumference', '/sɜːˈkʌm.fɹəns/', 'verb', 'C1', 'To include in a circular space; to bound.', '', ARRAY[]::TEXT[]),
('Circumlocution', '/ˌsɜːkəmləˈkjuːʃən/', 'noun', 'C1', 'A roundabout or indirect way of speaking; the use of more words than necessary to express an idea.', '', ARRAY['ambages','periphrasis']::TEXT[]),
('Circumspect', '/ˈsɜː.kəm.spɛkt/', 'adjective', 'C1', 'Carefully aware of all circumstances; considerate of all that is pertinent.', 'Being aware of the danger of upsetting her audience, she was somewhat circumspect in her comments.', ARRAY['cautious','chary','prudent','thoughtful','vigilant']::TEXT[]),
('Cistern', '/ˈsɪs.tən/', 'noun', 'C1', 'A reservoir or tank for holding water, especially for catching and holding rainwater for later use.', '', ARRAY[]::TEXT[]),
('Civility', '/sɪˈvɪl.ɪ.ti/', 'noun', 'C1', 'Speech or behaviour that is fit for civil interactions; politeness, courtesy.', '', ARRAY[]::TEXT[]),
('Clandestine', '/klænˈdɛstɪn/', 'adjective', 'C1', 'Done or kept in secret, sometimes to conceal an illicit or improper purpose.', 'clandestine military operations', ARRAY['covert','furtive','hush-hush','secret','secretive']::TEXT[]),
('Clarion', '/ˈklæɹiən/', 'verb', 'C1', 'To sound a clarion (trumpet-like instrument).', '', ARRAY[]::TEXT[]),
('Clasp', '/klɑːsp/', 'verb', 'C1', 'To take hold of; to grasp; to grab tightly.', 'They clasped hands and parted as friends.', ARRAY['begrip','grasp','grip','attach','join']::TEXT[]),
('Cleft', '/klɛft/', 'verb', 'C1', 'To syntactically separate a prominent constituent from the rest of the clause that concerns it, such as threat in "The threat which I saw but which he didn''''t see, was his downfall."', '', ARRAY[]::TEXT[]),
('Clement', '', 'adjective', 'C1', 'Lenient or merciful; charitable.', '', ARRAY[]::TEXT[]),
('Cliche', '/kliˈʃeɪ/', 'verb', 'C1', 'To use a cliché; to make up a word or a name that sounds like a cliché.', '', ARRAY[]::TEXT[]),
('Clique', '/kliːk/', 'verb', 'C1', 'To associate together in a clannish way; to act with others secretly to gain a desired end; to plot.', '', ARRAY[]::TEXT[]),
('Clog', '/klɒɡ/', 'verb', 'C1', 'To block or slow passage through (often with ''''up'''').', 'Hair is clogging the drainpipe.', ARRAY[]::TEXT[]),
('Clot', '/klɒt/', 'verb', 'C1', 'To form a clot or mass.', '', ARRAY[]::TEXT[]),
('Cloture', '/ˈkloʊ.tjʊə(ɹ)/', 'verb', 'C1', 'To end legislative debate by this means.', '', ARRAY[]::TEXT[]),
('Cloudburst', '/ˈklaʊdˌbɜːst/', 'noun', 'C1', 'A sudden heavy rainstorm.', '', ARRAY['cloudbust']::TEXT[]),
('Clout', '/klʌʊt/', 'verb', 'C1', 'To hit, especially with the fist.', '', ARRAY[]::TEXT[]),
('Cloying', '/ˈklɔɪ.ɪŋ/', 'adjective', 'C1', 'Unpleasantly excessive.', 'The cloying fondness she displayed was what, in the end, drove me away.', ARRAY['oversweet','saccharine','syrupy','treacly','exaggerated']::TEXT[]),
('Clumsy', '/ˈklʌmzi/', 'adjective', 'C1', 'Awkward, lacking coordination, not graceful, not dextrous.', 'He''''s very clumsy. I wouldn''''t trust him with carrying the dishes.', ARRAY[]::TEXT[]),
('Coagulant', '', 'adjective', 'C1', 'That causes coagulation or that coagulates', '', ARRAY[]::TEXT[]),
('Coax', '/kəʊks/', 'verb', 'C1', 'To fondle, kid, pet, tease.', 'He coaxed the horse gently into the trailer.', ARRAY['ease','cajole','canoodle','persuade','wheedle']::TEXT[]),
('Coda', '/ˈkəʊ.də/', 'noun', 'C1', 'A person born hearing to deaf parents.', '', ARRAY[]::TEXT[]),
('Coerce', '/kəʊˈɜːs/', 'verb', 'C1', 'To restrain by force, especially by law or authority; to repress; to curb.', '', ARRAY['bully','compel','dragoon']::TEXT[]),
('Coeval', '/kəʊˈiːvəl/', 'adjective', 'C1', 'Of the same age; contemporary.', 'Anything coeval with that clock will fetch a hefty price!', ARRAY['contemporaneous','contemporaneous']::TEXT[]),
('Cognizant', '/ˈkɒnɪzənt/', 'adjective', 'C1', 'Aware; fully informed; having understanding of a fact', 'The defendant is cognizant that this is a serious charge.', ARRAY[]::TEXT[]),
('Colander', '/ˈkɑləndəɹ/', 'noun', 'C1', 'A bowl-shaped kitchen utensil with holes in it used for draining food such as pasta.', '', ARRAY[]::TEXT[]),
('Collude', '', 'verb', 'C1', 'To act in concert with; to conspire', '', ARRAY['cahoots','conspire','plot','scheme']::TEXT[]),
('Colonnade', '/ˌkɒləˈneɪd/', 'noun', 'C1', 'A series of columns at regular intervals.', '', ARRAY[]::TEXT[]),
('Coltish', '', 'adjective', 'C1', 'Resembling a colt, especially:', '', ARRAY[]::TEXT[]),
('Coma', '/ˈkəʊmə/', 'noun', 'C1', 'A state of unconsciousness from which one may not wake up, usually induced by some form of trauma.', '', ARRAY[]::TEXT[]),
('Combustible', '/kəmˈbʌstɪbəl/', 'adjective', 'C1', 'Capable of burning', 'Dumping fertilizer on top of whatever mysterious goop was in the storage tank created a combustible mix which caught fire.', ARRAY[]::TEXT[]),
('Comely', '/ˈkʌmli/', 'adjective', 'C1', '(of a person) Pleasing or attractive to the eye.', 'a comely woman', ARRAY['pulchritudinous','pulchritudinous']::TEXT[]),
('Comity', '/ˈkɒmɪti/', 'noun', 'C1', 'Courtesy and considerate behaviour towards others; social harmony.', '', ARRAY['frith']::TEXT[]),
('Commencement', '/kəˈmɛnsmənt/', 'noun', 'C1', 'The first existence of anything; act or fact of commencing', 'The time of Henry VII nearly coincides with the commencement of what is termed modern history.', ARRAY['beginning','dawn','origin','rise','start']::TEXT[]),
('Commend', '/kəˈmɛnd/', 'verb', 'C1', 'To congratulate or reward.', 'The schoolboy was commended for raising the alarm about the burning building.', ARRAY[]::TEXT[]),
('Commingle', '', 'verb', 'C1', 'To mix, to blend.', '', ARRAY[]::TEXT[]),
('Committed', '/kəˈmɪtɪd/', 'adjective', 'C1', 'Obligated by a pledge to some course of action.', '', ARRAY[]::TEXT[]),
('Commodious', '/kəˈməʊdɪəs/', 'adjective', 'C1', 'Advantageous; profitable.', 'Our house is much more commodious than our old apartment.', ARRAY['advantageous','fit','proper','serviceable','suitable']::TEXT[]),
('Commotion', '/kəˈməʊ.ʃən/', 'noun', 'C1', 'A state of turbulent motion.', '', ARRAY[]::TEXT[]),
('Compendium', '', 'noun', 'C1', 'A short, complete summary; an abstract.', '', ARRAY[]::TEXT[]),
('Complacency', '', 'noun', 'C1', 'A feeling of contented self-satisfaction, especially when unaware of upcoming trouble.', '', ARRAY[]::TEXT[]),
('Compliant', '/kəmˈplʌɪənt/', 'adjective', 'C1', 'Willing to comply; submissive; willing to do what someone wants.', 'Tendon is compliant compared to bone.', ARRAY['bending','pliant','yielding','conformant','bending']::TEXT[]),
('Compliment', '/ˈkɒmplɪmənt/', 'verb', 'C1', 'To pay a compliment (to); to express a favorable opinion (of).', '', ARRAY[]::TEXT[]),
('Composed', '/kəmˈpəʊzd/', 'adjective', 'C1', 'Showing composure.', '', ARRAY[]::TEXT[]),
('Compress', '/kəmˈpɹɛs/', 'verb', 'C1', 'To make smaller; to press or squeeze together, or to make something occupy a smaller space or volume.', 'The force required to compress a spring varies linearly with the displacement.', ARRAY['contract','abridge','condense','shorten','truncate']::TEXT[]),
('Compunction', '/kəmˈpʌŋk.ʃən/', 'noun', 'C1', 'A pricking of conscience or a feeling of regret, especially one which is slight or fleeting.', '', ARRAY['qualm','regret','remorse','qualm','regret']::TEXT[]),
('Concatenate', '/kənˈkæt.ə.neɪt/', 'adjective', 'C1', 'Joined together as if in a chain.', '', ARRAY[]::TEXT[]),
('Concave', '/ˈkɒŋkeɪv/', 'adjective', 'C1', 'Curved like the inner surface of a sphere or bowl', '', ARRAY[]::TEXT[]),
('Concerted', '', 'adjective', 'C1', 'Performed through a concert of effort; done by agreement or in combination.', '', ARRAY[]::TEXT[]),
('Conciliate', '/ˌkənˈsɪlieɪt/', 'verb', 'C2', 'To make calm and content, or regain the goodwill of; to placate.', '', ARRAY[]::TEXT[]),
('Concise', '/kənˈsaɪs/', 'adjective', 'C1', 'Brief, yet including all important information', '', ARRAY['succinct','terse']::TEXT[]),
('Concord', '/ˈkɒn.kɔɹd/', 'noun', 'C1', 'A state of agreement; harmony; union.', '', ARRAY[]::TEXT[]),
('Concur', '/kənˈkɜː/', 'verb', 'C1', 'To unite or agree (in action or opinion); to have a common opinion; to coincide; to correspond.', '', ARRAY['cooperate','unite','assemble','congregate','crowd']::TEXT[]),
('Condescending', '/ˈkɔn.dɪ.sɛnd.ɪŋ/', 'adjective', 'C1', 'Assuming a tone of superiority, or a patronizing attitude.', 'Quit talking to me in that condescending tone! You always treat me like a child!', ARRAY['patronizing']::TEXT[]),
('Condign', '/kənˈdaɪn/', 'adjective', 'C1', 'Fitting, appropriate, deserved, especially denoting punishment', '', ARRAY[]::TEXT[]),
('Condole', '', 'verb', 'C1', 'To express sympathetic sorrow; to lament in sympathy (with someone on something).', '', ARRAY[]::TEXT[]),
('Condone', '/kənˈdəʊn/', 'verb', 'C1', 'To forgive, excuse or overlook (something that is considered morally wrong, offensive, or generally disliked).', '', ARRAY[]::TEXT[]),
('Conductor', '/kənˈdʌktɚ/', 'noun', 'C1', 'One who conducts or leads; a guide; a director.', 'train conductor; tram conductor', ARRAY[]::TEXT[]),
('Confluence', '/ˈkɒnfluəns/', 'noun', 'C1', 'The place where two rivers, streams, or other continuously flowing bodies of water meet and become one, especially where a tributary joins a river.', 'We encountered an abandoned boat at the confluence of the Mississippi and Ohio Rivers.', ARRAY['conflux']::TEXT[]),
('Congeal', '/kənˈdʒiːl/', 'verb', 'C1', 'To change from a liquid to solid state perhaps by cold', 'We must act before opposition to our plans congeals.', ARRAY[]::TEXT[]),
('Congenial', '', 'adjective', 'C1', 'Having the same or very similar nature, personality, tastes, habits or interests.', 'The congenial bartender makes the Hog’s Head an inviting place to hang out during the weekends.', ARRAY[]::TEXT[]),
('Congruent', '/ˈkɒŋ.ɡɹuː.ənt/', 'adjective', 'C1', 'Corresponding in character; congruous', '', ARRAY['congruous']::TEXT[]),
('Conjecture', '/kənˈd͡ʒɛk.t͡ʃə(ɹ)/', 'verb', 'C1', 'To guess; to venture an unproven idea.', 'I do not know if it is true; I am simply conjecturing here.', ARRAY[]::TEXT[]),
('Connive', '/kəˈnaɪv/', 'verb', 'C1', 'Often followed by with: to secretly cooperate with another person or persons in order to commit a crime or other wrongdoing; to collude, to conspire.', '', ARRAY['dissimulate','look the other way','shut one''''s eyes','turn a blind eye','wink']::TEXT[]),
('Connoisseur', '/ˌkɒnəˈsɜɹ/', 'noun', 'C1', 'A specialist in a given field whose opinion is highly valued, especially in one of the fine arts or in matters of taste', '', ARRAY['cognoscente']::TEXT[]),
('Conscientious', '/ˌkɒnʃiˈɛnʃəs/', 'adjective', 'C1', 'Thorough, careful, or vigilant in one’s task performance.', 'He was a thoughtful and conscientious worker.', ARRAY[]::TEXT[]),
('Conservatory', '/kənˈsɜː.və.tɹi/', 'adjective', 'C1', 'Having the quality of preserving from loss, decay, or injury.', '', ARRAY[]::TEXT[]),
('Console', '/ˈkɒn.səʊl/', 'noun', 'C1', 'A stand-alone cabinet designed to stand on the floor; especially, one that houses home entertainment equipment, such as a TV or stereo system.', '', ARRAY[]::TEXT[]),
('Consonant', '/ˈkɒn.sə.nənt/', 'adjective', 'C1', 'Characterized by harmony or agreement.', 'consonant tones; consonant chords', ARRAY[]::TEXT[]),
('Constrain', '/kənˈstɹeɪn/', 'verb', 'C1', 'To force physically, by strong persuasion or pressuring; to compel; to oblige.', '', ARRAY[]::TEXT[]),
('Contagious', '/kənˈteɪdʒəs/', 'adjective', 'C1', '(of a disease) Easily transmitted to others.', 'The flu was so contagious that everybody in town got sick!', ARRAY['catching','infectious','infectious','catching','infectious']::TEXT[]),
('Contaminate', '/kənˈtæmɪneɪt/', 'verb', 'C1', 'To make something dangerous or toxic by introducing impurities or foreign matter.', 'This water is contaminated. It isn''''t safe to drink.', ARRAY[]::TEXT[]),
('Contentious', '/kənˈtɛn.ʃəs/', 'adjective', 'C2', 'Marked by heated arguments or controversy.', '', ARRAY[]::TEXT[]),
('Contiguous', '/kənˈtɪɡjuəs/', 'adjective', 'C1', 'Connected; touching; abutting.', 'the forty-eight contiguous states', ARRAY[]::TEXT[]),
('Contort', '', 'verb', 'C1', 'To twist in a violent manner.', 'features contorted with fury.', ARRAY['deform','detort','twist']::TEXT[]),
('Contravene', '/ˌkɒn.tɹəˈviːn/', 'verb', 'C1', 'To act contrary to an order; to fail to conform to a regulation or obligation.', '', ARRAY['breach','break','infringe','violate','contradict']::TEXT[]),
('Contumacious', '/ˌkɒn.tjʊˈmeɪ.ʃəs/', 'adjective', 'C1', 'Contemptuous of authority; willfully disobedient; rebellious.', '', ARRAY['disobedient','insubordinate','obstinate','perverse','rebellious']::TEXT[]),
('Convalesce', '/ˌkɒn.vəˈlɛs/', 'verb', 'C1', 'To recover health and strength gradually after sickness or weakness.', 'The patient convalesced for six months after his stroke.', ARRAY[]::TEXT[]),
('Convergent', '', 'adjective', 'C1', 'That converges or focuses.', '', ARRAY[]::TEXT[]),
('Conversant', '/kənˈvɝsənt/', 'adjective', 'C1', 'Closely familiar; current; having frequent interaction', 'She is equally conversant with Shakespeare and the laws of physics.', ARRAY[]::TEXT[]),
('Convex', '/ˈkɒnvɛks/', 'adjective', 'C1', 'Curved or bowed outward like the outside of a bowl or sphere or circle', '', ARRAY[]::TEXT[]),
('Convoke', '/kənˈvoʊk/', 'verb', 'C1', 'To convene, to cause to assemble for a meeting.', '', ARRAY[]::TEXT[]),
('Convulsion', '/kənˈvʌlʃən/', 'noun', 'C1', 'An intense, paroxysmal, involuntary muscular contraction.', 'Earthquakes and convulsions of nature shake Earth on a regular basis.', ARRAY[]::TEXT[]),
('Coop', '/kuːp/', 'verb', 'C1', 'To keep in a coop.', '', ARRAY[]::TEXT[]),
('Coquette', '/kɒˈkɛt/', 'verb', 'C1', 'To act as a flirt or coquet.', '', ARRAY[]::TEXT[]),
('Cord', '/kɔːd/', 'verb', 'C1', 'To furnish with cords', '', ARRAY[]::TEXT[]),
('Cordon', '/kɔː(ɹ)dən/', 'noun', 'C1', 'A ribbon normally worn diagonally across the chest as a decoration or insignia of rank etc.', '', ARRAY[]::TEXT[]),
('Corona', '/kəˈɹoʊnə/', 'verb', 'C1', 'To surround with a luminous or crownlike ring as if by the solar corona.', '', ARRAY[]::TEXT[]),
('Coronation', '/ˌkɒɹəˈneɪʃən/', 'noun', 'C1', 'The act or solemnity of crowning a sovereign; the act of investing a prince with the insignia of royalty, on his succeeding to the sovereignty.', '', ARRAY[]::TEXT[]),
('Corporeal', '/kɔːˈpɔːɹiəl/', 'adjective', 'C1', 'Material; tangible; physical.', '', ARRAY['bodily','corporal']::TEXT[]),
('Corrosive', '', 'adjective', 'C1', 'Eating away; having the power of gradually wearing, hanging, or destroying the texture or substance of a body; as the corrosive action of an acid.', '', ARRAY[]::TEXT[]),
('Corrugated', '', 'adjective', 'C1', 'Marked with parallel folds, ridges or furrows.', '', ARRAY[]::TEXT[]),
('Cosset', '', 'verb', 'C1', 'To treat like a pet; to overly indulge.', 'The car cossets its occupants in comfort.', ARRAY['grope','touch up','coddle','posset']::TEXT[]),
('Countenance', '[kʲʰæũ̯.ʔɪ̆.nəns]', 'verb', 'C1', 'To tolerate, support, sanction, patronise or approve of something.', 'The cruel punishment was countenanced by the government, although it was not officially legal.', ARRAY['approve','sanction','support','tolerate']::TEXT[]),
('Counterfeit', '/ˈkaʊn.tɚˌfɪt/', 'adjective', 'C1', 'False, especially of money; intended to deceive or carry appearance of being genuine.', 'This counterfeit watch looks like the real thing, but it broke a week after I bought it.', ARRAY[]::TEXT[]),
('Countermand', '/ˌkaʊntəˈmɑːnd/', 'verb', 'C2', 'To revoke (a former command); to cancel or rescind by giving an order contrary to one previously given.', 'to countermand an order for goods', ARRAY['cancel','rescind','forbid','prohibit','cancel']::TEXT[]),
('Coven', '/ˈkʌ.vən/', 'noun', 'C1', 'A formal group or assembly of witches.', '', ARRAY[]::TEXT[]),
('Covert', '/ˈkəʊvəːt/', 'adjective', 'C1', 'Hidden, covered over; overgrown, sheltered.', '', ARRAY['feme covert']::TEXT[]),
('Covetous', '/ˈkʌvətəs/', 'adjective', 'C1', 'Extremely keen or desirous, especially to obtain and possess something belonging to someone else; avaricious.', '', ARRAY[]::TEXT[]),
('Cowardice', '/ˈkaʊədɪs/', 'noun', 'C1', 'Lack of courage.', '', ARRAY['cowardliness','cowardness','cowardship']::TEXT[]),
('Cower', '/ˈkaʊə/', 'verb', 'C1', 'To crouch or cringe, or to avoid or shy away from something, in fear.', 'He''''d be useless in war. He''''d just cower in his bunker until the enemy came in and shot him, or until the war was over.', ARRAY[]::TEXT[]),
('Cozen', '/ˈkəʊzən/', 'verb', 'C1', 'To become cozy; (by extension) to become acquainted, comfortable, or familiar with.', '', ARRAY[]::TEXT[]),
('Cramped', '/kɹæmpt/', 'adjective', 'C1', 'Uncomfortably restricted in size, or financially.', '', ARRAY[]::TEXT[]),
('Crass', '/kɹæs/', 'adjective', 'C1', 'Coarse; crude; unrefined or insensitive; lacking discrimination', '', ARRAY[]::TEXT[]),
('Crave', '/kɹeɪv/', 'verb', 'C1', 'To desire strongly, so as to satisfy an appetite; to long or yearn for.', 'to crave after wealth', ARRAY[]::TEXT[]),
('Crease', '/kɹiːs/', 'verb', 'C1', 'To make a crease in; to wrinkle.', 'The bullet just creased his shoulder.', ARRAY[]::TEXT[]),
('Credulous', '/kɹɛdjələs/', 'adjective', 'C1', 'Excessively ready to believe things; gullible.', '', ARRAY['naive','unworldly']::TEXT[]),
('Creek', '/kɹiːk/', 'noun', 'C1', 'A small inlet or bay, often saltwater, narrower and extending farther into the land than a cove; a recess in the shore of the sea, or of a river; the inner part of a port that is used as a dock for small boats.', '', ARRAY['bayou','branch','brook','run','beck']::TEXT[]),
('Crescendo', '/kɹəˈʃɛn.dəʊ/', 'verb', 'C1', 'To increase in intensity; to reach or head for a crescendo.', 'The band crescendoed and then suddenly went silent.', ARRAY[]::TEXT[]),
('Crest', '/kɹɛst/', 'verb', 'C1', 'Particularly with reference to waves, to reach a peak.', '', ARRAY[]::TEXT[]),
('Crestfallen', '/ˈkɹɛstfɔːlən/', 'adjective', 'C2', 'Sad because of a recent disappointment.', '', ARRAY['blue','dejected','depressed','despondent','down in the dumps']::TEXT[]),
('Cronyism', '/ˈkɹəʊ.ni.ɪ.zəm/', 'noun', 'C1', 'Favoritism to friends without regard for their qualifications, especially by appointing them to political positions.', '', ARRAY[]::TEXT[]),
('Crook', '/kɹʊk/', 'verb', 'C1', 'To bend, or form into a hook.', 'He crooked his finger toward me.', ARRAY[]::TEXT[]),
('Croon', '/ˈkɹuːn/', 'verb', 'C1', 'To hum or sing softly or in a sentimental manner.', '', ARRAY[]::TEXT[]),
('Crouch', '/kɹaʊt͡ʃ/', 'verb', 'C1', 'To bend down; to stoop low; to stand close to the ground with legs bent, like an animal when waiting for prey, or someone in fear.', 'We crouched behind the low wall until the squad of soldiers had passed by.', ARRAY[]::TEXT[]),
('Crumple', '/ˈkɹʌmpəl/', 'verb', 'C1', 'To rumple; to press into wrinkles by crushing together.', '', ARRAY[]::TEXT[]),
('Crutch', '/kɹʌtʃ/', 'verb', 'C1', 'To support on crutches; to prop up.', '', ARRAY[]::TEXT[]),
('Crux', '/kɹʌks/', 'noun', 'C1', 'The basic, central, or essential point or feature.', 'The crux of her argument was that the roadways needed repair before anything else could be accomplished.', ARRAY['core','gist','core','gist']::TEXT[]),
('Cuisine', '/kwɪˈziːn/', 'noun', 'C1', 'A characteristic style of preparing food, often associated with a place of origin.', 'French cuisine is considered to be one of the world''''s most refined and elegant styles of cooking.', ARRAY['culinary art','kitchen']::TEXT[]),
('Culpable', '/ˈkʌlpəbəl/', 'adjective', 'C1', 'Meriting condemnation, censure or blame, especially as something wrong, harmful or injurious; blameworthy.', 'I am culpable for stealing your money.', ARRAY[]::TEXT[]),
('Cunning', '/ˈkʌnɪŋ/', 'adjective', 'C1', 'Sly; crafty; clever in surreptitious behaviour.', 'cunning work', ARRAY[]::TEXT[]),
('Curator', '', 'noun', 'C1', 'A person who manages, administers or organizes a collection, either independently or employed by a museum, library, archive or zoo.', '', ARRAY[]::TEXT[]),
('Curmudgeon', '/kɜː(ɹ)ˈmʌdʒ.ən/', 'noun', 'C2', 'An ill-tempered person full of stubborn ideas or opinions.', 'John Doe''''s old age and stubborn aversion to new ideas make him a curmudgeon of a candidate.', ARRAY['crank','crank']::TEXT[]),
('Cursory', '/ˈkɵː.sɘ.ɹi/', 'adjective', 'C1', 'Hasty; superficial; careless', 'Most junk mail requires only a cursory glance.', ARRAY[]::TEXT[]),
('Curt', '/kɜːt/', 'adjective', 'C1', 'Brief or terse, especially to the point of being rude.', '', ARRAY['brusque','brusque']::TEXT[]),
('Curtail', '/kɜːˈteɪl/', 'verb', 'C1', 'To cut short the tail of an animal', 'Curtailing horses procured long horse-hair.', ARRAY['crop','dock','behedge','control','limit']::TEXT[]),
('Cynic', '/ˈsɪnɪk/', 'adjective', 'C1', 'Cynical (in all senses)', 'the cynic, or Sothic, year; cynic cycle', ARRAY[]::TEXT[]),
('Dabble', '/ˈdæb(ə)l/', 'verb', 'C1', 'To make slightly wet or soiled by spattering or sprinkling a liquid (such as water, mud, or paint) on it; to bedabble.', 'The children sat on the dock and dabbled their feet in the water.', ARRAY['bespatter','besprinkle','spatter']::TEXT[]),
('Daft', '/dæft/', 'adjective', 'C1', 'Foolish, silly, stupid.', 'a daft idea', ARRAY[]::TEXT[]),
('Daguerreotype', '/dəˈɡɛɹ.əʊ.taɪp/', 'verb', 'C1', 'To make a photograph using this process, to make a daguerreotype (of).', '', ARRAY[]::TEXT[]),
('Dais', '/ˈdeɪ.əs/', 'noun', 'C1', 'A raised platform in a room for a high table, a seat of honour, a throne, or other dignified occupancy; a similar platform supporting a lectern, pulpit, etc., which may be used to speak from.', '', ARRAY['podium']::TEXT[]),
('Dally', '/ˈdæli/', 'verb', 'C1', 'To waste time in trivial activities, or in idleness; to trifle.', '', ARRAY['kill time','feel up','grope','touch up','dawdle']::TEXT[]),
('Damper', '/ˈdæmpɚ/', 'adjective', 'C1', 'In a state between dry and wet; moderately wet; moist.', 'The lawn was still damp so we decided not to sit down.', ARRAY['glum','melancholy','sorrowful','moist','thoan']::TEXT[]),
('Dandy', '/ˈdændi/', 'adjective', 'C1', 'Like a dandy, foppish.', 'That''''s all fine and dandy, but how much does it cost?', ARRAY['all very well','well and good']::TEXT[]),
('Dank', '/deəŋk/', 'adjective', 'C1', 'Dark, damp and humid.', 'The dank cave was chilly and spooky.', ARRAY[]::TEXT[]),
('Dapper', '/ˈdæpə(ɹ)/', 'adjective', 'C1', 'Neat, trim.', '', ARRAY[]::TEXT[]),
('Dappled', '[ˈdæpəɫd]', 'adjective', 'C1', 'Having a mottled or spotted skin or coat, dapple.', '', ARRAY[]::TEXT[]),
('Daredevil', '/ˈdɛədɛvəl/', 'adjective', 'C1', 'Recklessly bold; adventurous.', 'The climatic scene of “Rebel without a Cause” is the group of very daredevil teens playing chicken.', ARRAY[]::TEXT[]),
('Dart', '/dɑːt/', 'noun', 'C1', 'A pointed missile weapon, intended to be thrown by the hand, for example a short lance or javelin', '', ARRAY[]::TEXT[]),
('Daunt', '/dɔːnt/', 'verb', 'C1', 'To discourage, intimidate.', '', ARRAY[]::TEXT[]),
('Dawdle', '/ˈdɔːdəl/', 'verb', 'C1', 'To spend time idly and unfruitfully, to waste time.', 'to dawdle away the whole morning', ARRAY[]::TEXT[]),
('Deadpan', '/ˈdɛdpæn/', 'adjective', 'C1', 'Deliberately impassive or expressionless.', 'The comedian remained deadpan.', ARRAY['poker-faced']::TEXT[]),
('Debacle', '/deɪˈbɑː.kəl/', 'noun', 'C1', 'An event or enterprise that ends suddenly and disastrously, often with humiliating consequences.', '', ARRAY['fiasco']::TEXT[]),
('Debark', '/dɪˈbɑːk/', 'verb', 'C1', 'To unload goods from an aircraft or ship.', '', ARRAY[]::TEXT[]),
('Debilitate', '/dɪˈbɪlɪteɪt/', 'verb', 'C1', 'To make feeble; to weaken.', 'The American Dream suffered a debilitating effect after the subprime crisis.', ARRAY['enervate','enfeeble','weaken','enervate','enfeeble']::TEXT[]),
('Decant', '/dəˈkænt/', 'verb', 'C1', 'To pour off (a liquid) gently, so as not to disturb the sediment.', 'to decant wine', ARRAY[]::TEXT[]),
('Decibel', '/ˈdɛsɪbəl/', 'noun', 'C1', 'A common measure of sound intensity ratio that is one tenth of a bel on the logarithmic intensity scale. It is defined as dB = 10 log10(P1 / P2), where P1 and P2 are the relative powers of the sound.', '', ARRAY[]::TEXT[]),
('Decipher', '/dɪˈsaɪfə(ɹ)/', 'verb', 'C1', 'To decode or decrypt a code or cipher to plain text.', '', ARRAY[]::TEXT[]),
('Decode', '/diːˈkəʊd/', 'verb', 'C1', 'To convert from an encrypted form to plain text.', '', ARRAY['decipher']::TEXT[]),
('Decrepit', '/dɪˈkɹɛp.ɪt/', 'adjective', 'C1', 'Weakened or worn out from age or wear.', '', ARRAY['aged','timeworn','withered']::TEXT[]),
('Defer', '/dɪˈfɜː(ɹ)/', 'verb', 'C1', 'To delay or postpone', 'We''''re going to defer the decision until we have all the facts.', ARRAY[]::TEXT[]),
('Deference', '/ˈdɛfəɹəns/', 'noun', 'C1', 'Great respect.', 'The children treated their elders with deference.', ARRAY['honor','respect']::TEXT[]),
('Defile', '/dɪˈfaɪl/', 'verb', 'C1', 'To make unclean, dirty, or impure; soil; befoul.', 'To urinate on someone''''s grave is an example of a way to defile it.', ARRAY['contaminate','pollute','spoil','sully','desecrate']::TEXT[]),
('Defoliant', '/diːˈfəʊlɪənt/', 'noun', 'C1', 'An agent used to defoliate plants.', '', ARRAY[]::TEXT[]),
('Deforest', '/dɪˈfɒɹɪst/', 'verb', 'C1', 'To clear (an area) of forest.', '', ARRAY[]::TEXT[]),
('Deft', '/dɛft/', 'adjective', 'C1', 'Quick and neat in action; skillful.', 'He assembled it in one fluid, deft motion.', ARRAY[]::TEXT[]),
('Defuse', '/diːˈfjuːz/', 'verb', 'C1', 'To remove the fuse from (a bomb, etc.).', 'to defuse a hostage situation', ARRAY[]::TEXT[]),
('Dehydrate', '/diːhaɪdˈɹeɪt/', 'verb', 'C1', 'To lose or remove water; to dry', '', ARRAY[]::TEXT[]),
('Deify', '/ˈdeɪ.ɪ.faɪ/', 'verb', 'C1', 'To make a god of (something or someone).', '', ARRAY['apotheosize','exalt','idealize']::TEXT[]),
('Deject', '/dɪˈdʒɛkt/', 'verb', 'C1', 'Make sad or dispirited.', '', ARRAY[]::TEXT[]),
('Delicacy', '/ˈdɛlɪkəsi/', 'noun', 'C1', 'The quality of being delicate.', '', ARRAY[]::TEXT[]),
('Delirium', '/dɪˈlɪɹɪəm/', 'noun', 'C1', 'A temporary mental state with a sudden onset, usually reversible, including symptoms of confusion, inability to concentrate, disorientation, anxiety, and sometimes hallucinations. Causes can include dehydration, drug intoxication, and severe infection.', '', ARRAY[]::TEXT[]),
('Delusion', '/dɪˈl(j)uːzjən/', 'noun', 'C1', 'A false belief that is resistant to confrontation with actual facts.', 'It is far better to grasp the universe as it really is than to persist in delusion, however satisfying and reassuring.', ARRAY[]::TEXT[]),
('Deluge', '/ˈdɛl.juːdʒ/', 'verb', 'C1', 'To flood with water.', 'Some areas were deluged with a month''''s worth of rain in 24 hours.', ARRAY[]::TEXT[]),
('Delve', '/dɛlv/', 'verb', 'C1', 'To dig the ground, especially with a shovel.', '', ARRAY['dig','investigate','research']::TEXT[]),
('Demagogue', '/ˈdɛməɡɒɡ/', 'verb', 'C1', 'To speak or act in the manner of a demagogue; to speak about (an issue) in the manner of a demagogue.', '', ARRAY[]::TEXT[]),
('Demanding', '/dɪˈmɑːndɪŋ/', 'adjective', 'C1', 'Requiring much endurance, strength, or patience.', '', ARRAY[]::TEXT[]),
('Demolition', '/ˌdɛm.əˈlɪʃən/', 'noun', 'C1', 'The process of demolishing or destroying buildings or other structures.', '', ARRAY[]::TEXT[]),
('Demoralize', '/dɪˈmɒɹəlaɪz/', 'verb', 'C1', 'To destroy the morale of; to dishearten.', '', ARRAY[]::TEXT[]),
('Demotic', '/dɪ.ˈmɒ.tɪk/', 'adjective', 'C1', 'Of or for the common people.', 'demotic writing style', ARRAY['colloquial','informal','popular','vernacular','enchorial']::TEXT[]),
('Denouement', '/ˌdeɪnuˈmɑ̃/', 'noun', 'C2', '(authorship, often used metaphorically) The conclusion or resolution of a plot.', '', ARRAY[]::TEXT[]),
('Dent', '/dɛnt/', 'verb', 'C1', 'To impact something, producing a dent.', 'Copper is soft and dents easily.', ARRAY[]::TEXT[]),
('Denude', '/dɪˈnjuːd/', 'verb', 'C1', 'To divest of all covering; to make bare or naked; to strip.', 'He denuded himself of his clothes.', ARRAY[]::TEXT[]),
('Deplete', '/dɪˈpliːt/', 'verb', 'C1', 'To empty or unload, as the vessels of the human system, by bloodletting or by medicine.', 'Certain medications can deplete vitamin D.', ARRAY[]::TEXT[]),
('Deplore', '/dɪˈplɔː/', 'verb', 'C1', 'To bewail; to weep bitterly over; to feel sorrow for.', 'I deplore my neighbour for having lost his job.', ARRAY['bewail','condemn']::TEXT[]),
('Deportation', '/diːˌpɔːˈteɪʃən/', 'noun', 'C1', 'The act of deporting or exiling, or the state of being deported; banishment; transportation.', '', ARRAY[]::TEXT[]),
('Depose', '/dɪˈpəʊz/', 'verb', 'C1', 'To put down; to lay down; to deposit; to lay aside; to put away.', 'A deposed monarch may go into exile as pretender to the lost throne, hoping to be restored in a subsequent revolution.', ARRAY['declare']::TEXT[]),
('Depravity', '/dəˈpɹævɪti/', 'noun', 'C1', 'The state or condition of being depraved; moral debasement.', '', ARRAY['wickedness']::TEXT[]),
('Deprecate', '/ˈdɛpɹəkeɪt/', 'verb', 'C1', 'To belittle or express disapproval of.', 'He deprecates any praise of his own merits.', ARRAY[]::TEXT[]),
('Depreciate', '/dɪˈpɹiːʃɪeɪt/', 'verb', 'C1', 'To lessen in price or estimated value; to lower the worth of.', '', ARRAY['do down']::TEXT[]),
('Depressant', '/dɪˈpɹɛsənt/', 'adjective', 'C1', '(pharmaceutical effect) reducing functional or nervous activity.', '', ARRAY[]::TEXT[]),
('Deprivation', '/dɛp.ɹɪ.veɪʃən/', 'noun', 'C1', 'The act of depriving, dispossessing, or bereaving; the act of deposing or divesting of some dignity.', 'He was suffering from deprivation of sleep.', ARRAY['bereavement','loss','privation','want','bereavement']::TEXT[]),
('Deracinate', '/dɪˈɹæsəneɪt/', 'verb', 'C1', 'To pull up by the roots; to uproot; to extirpate.', '', ARRAY[]::TEXT[]),
('Derelict', '/ˈdɛɹəlɪkt/', 'adjective', 'C2', 'Abandoned, forsaken; given up by the natural owner or guardian; (of a ship) abandoned at sea, dilapidated, neglected; (of a spacecraft) abandoned in outer space.', 'There was a derelict ship on the island.', ARRAY['abandoned']::TEXT[]),
('Descendant', '/dɪˈsɛndənt/', 'adjective', 'C1', 'Descending from a biological ancestor.', '', ARRAY[]::TEXT[]),
('Desiccate', '/dɪˈsɪkeɪt/', 'adjective', 'C1', 'Having had moisture removed; dehydrated, dessicated.', '', ARRAY['dried','dried']::TEXT[]),
('Despicable', '/dɪˈspɪkəbəl/', 'adjective', 'C1', 'Fit or deserving to be despised; contemptible; mean', '', ARRAY['contemptible','evil','mean','vile','contemptible']::TEXT[]),
('Despise', '/dɪˈspaɪz/', 'verb', 'C1', 'To regard with contempt or scorn.', '', ARRAY['contemn','disdain','scorn']::TEXT[]),
('Despotic', '/disˈpɒt.ɪk/', 'adjective', 'C1', 'Of or pertaining to a despot or tyrant.', 'This despotic age of the empire ended in a revolt.', ARRAY['domineering','tyrannical']::TEXT[]),
('Dessert', '/dɪˈzɜːt/', 'noun', 'C1', 'A sweet confection served as the last course of a meal', '', ARRAY['afters','pudding','sweet']::TEXT[]),
('Desultory', '/ˈdɛs.əl.t(ə).ɹi/', 'adjective', 'C1', 'Jumping, or passing, from one thing or subject to another, without order, planning, or rational connection; lacking logical sequence.', 'He wandered round, cleaning up in a desultory way.', ARRAY['aimless','disconnected','quodlibetic','quodlibetical','unmethodical']::TEXT[]),
('Detach', '/dəˈtætʃ/', 'verb', 'C1', 'To take apart from; to take off.', 'to detach the tag from a newly purchased garment', ARRAY['fall off','allocate','earmark','disengage','unfasten']::TEXT[]),
('Deterioration', '/dɪˌtɪəɹɪəˈɹeɪʃən/', 'noun', 'C1', 'The process of making or growing worse, or the state of having grown worse.', '', ARRAY['retrogression','retrogression']::TEXT[]),
('Detour', '/ˈdiː.tɔː(ɹ)/', 'verb', 'C1', 'To make a detour.', '', ARRAY[]::TEXT[]),
('Detoxification', '', 'noun', 'C1', 'The process of removing toxins.', '', ARRAY[]::TEXT[]),
('Detract', '/dɪˈtɹækt/', 'verb', 'C1', 'To take away; to withdraw or remove.', '', ARRAY['decry','defame']::TEXT[]),
('Detritus', '/dɪˈtɹaɪtəs/', 'noun', 'C1', '(chiefly geological) Pieces of rock broken off by ice, glacier, or erosion.', '', ARRAY[]::TEXT[]),
('Devoted', '/dɪˈvəʊtəd/', 'adjective', 'C1', 'Vowed; dedicated; consecrated.', 'Bob and Sara are devoted to their children.', ARRAY[]::TEXT[]),
('Devout', '/dəˈvʌʊt/', 'adjective', 'C1', 'Devoted to religion or to religious feelings and duties; pious; extremely religious.', 'devout sighs; devout eyes; a devout posture', ARRAY[]::TEXT[]),
('Dew', '/djuː/', 'noun', 'C1', 'Any moisture from the atmosphere condensed by cool bodies upon their surfaces.', 'There was a heavy dew this morning.', ARRAY['rore','rore']::TEXT[]),
('Dexterous', '/ˈdɛkstɹəs/', 'adjective', 'C1', 'Skillful with one''''s hands.', '', ARRAY[]::TEXT[]),
('Diabolic', '/ˌdaɪəˈbɒlɪk/', 'adjective', 'C1', 'Showing wickedness typical of a devil.', 'a cunning and diabolic plot', ARRAY['demonic','fiendish','hellish','infernal','satanic']::TEXT[]),
('Diaphanous', '/daɪˈæf.ən.əs/', 'adjective', 'C1', 'Transparent or translucent; allowing light to pass through; capable of being seen through.', '', ARRAY['translucent','transparent','delicate','insubstantial']::TEXT[]),
('Diatribe', '/ˈdaɪ.əˌtɹaɪb/', 'noun', 'C2', 'An abusive, bitter, attack or criticism: denunciation.', 'The senator was prone to diatribes which could go on for more than an hour.', ARRAY[]::TEXT[]),
('Diehard', '', 'adjective', 'C1', 'Unreasonably or stubbornly resisting change.', 'For a Roman Catholic teacher, he sure is a diehard fundamentalist.', ARRAY[]::TEXT[]),
('Diffuse', '/dɪˈfjuːz/', 'verb', 'C1', 'To spread over or through as in air, water, or other matter, especially by fluid motion or passive means.', 'Food coloring diffuses in water.', ARRAY['forspread']::TEXT[]),
('Digit', '/ˈdɪdʒɪt/', 'verb', 'C1', 'To point at or point out with the finger.', '', ARRAY[]::TEXT[]),
('Digress', '/daɪˈɡɹɛs/', 'verb', 'C1', 'To step or turn aside; to deviate; to swerve; especially, to turn aside from the main subject of attention, or course of argument, in writing or speaking.', '', ARRAY['sidetrack']::TEXT[]),
('Dilapidate', '/dəˈlæp.ə.deɪt/', 'verb', 'C1', 'To fall into ruin or disuse.', '', ARRAY[]::TEXT[]),
('Dilate', '/daɪˈleɪt/', 'verb', 'C1', 'To enlarge; to make bigger.', 'The eye doctor put drops in my eye to dilate the pupil so he could see the nerve better.', ARRAY[]::TEXT[]),
('Dilute', '/daɪˈljuːt/', 'adjective', 'C1', 'Having a low concentration.', 'Clean the panel with a dilute, neutral cleaner.', ARRAY[]::TEXT[]),
('Din', '/dɪn/', 'noun', 'C1', 'A loud noise; a cacophony or loud commotion.', '', ARRAY[]::TEXT[]),
('Dingy', '/ˈdɪn.dʒi/', 'adjective', 'C1', 'Drab; shabby; dirty; squalid', '', ARRAY['dismal','drab','dreary','gloomy','grimy']::TEXT[]),
('Diocesan', '/dʌɪˈɒsɪsən/', 'adjective', 'C1', 'Pertaining to a diocese.', '', ARRAY[]::TEXT[]),
('Dire', '/ˈdaɪ̯ə(ɹ)/', 'adjective', 'C1', 'Warning of bad consequences: ill-boding; portentous.', 'dire omens', ARRAY['horrible','lamentable','terrible','horrible','lamentable']::TEXT[]),
('Dirge', '/dɜːdʒ/', 'verb', 'C1', 'To sing dirges', '', ARRAY[]::TEXT[]),
('Disabuse', '/dɪsəˈbjuːz/', 'verb', 'C2', 'To free (someone) of a misconception or misapprehension; to unveil a falsehood held by (somebody).', '', ARRAY['undeceive']::TEXT[]),
('Disarm', '/dɪsˈɑː(ɹ)m/', 'verb', 'C1', 'To deprive of weapons; to deprive of the means of attack or defense; to render defenseless.', 'to disarm a man''''s wrath', ARRAY[]::TEXT[]),
('Disarray', '/dɪsəˈɹeɪ/', 'verb', 'C1', 'To throw into disorder; to break the array of.', '', ARRAY[]::TEXT[]),
('Disavow', '/dɪsəˈvaʊ/', 'verb', 'C1', 'To strongly and solemnly refuse to own or acknowledge; to deny responsibility for, approbation of, and the like.', 'He was charged with embezzlement, but he disavows the crime.', ARRAY['abjure','deny','disclaim','disown','reject']::TEXT[]),
('Discern', '', 'verb', 'C1', 'To detect with the senses, especially with the eyes.', 'He was too young to discern right from wrong.', ARRAY['discriminate','distinguish','ken','spy']::TEXT[]),
('Disciple', '/dɪˈsaɪpl̩/', 'verb', 'C1', 'To convert (a person) into a disciple.', '', ARRAY[]::TEXT[]),
('Discombobulate', '/ˌdɪs.kəmˈbɒb.jəˌleɪt/', 'verb', 'C1', 'To throw into a state of confusion; to befuddle or perplex.', '', ARRAY[]::TEXT[]),
('Discomfit', '/dɪsˈkʌmfɪt/', 'adjective', 'C1', 'Discomfited; overthrown.', '', ARRAY[]::TEXT[]),
('Discommode', '/ˌdɪskəˈməʊd/', 'verb', 'C1', 'To cause inconvenience to (someone).', '', ARRAY['incommode','inconvenience']::TEXT[]),
('Discompose', '', 'verb', 'C1', 'To destroy the composure of; to disturb or agitate.', '', ARRAY['agitate','perturb','unsettle']::TEXT[]),
('Disconcert', '/ˌdɪskənˈsɜːt/', 'verb', 'C1', 'To upset the composure of.', 'The emperor disconcerted the plans of his enemy.', ARRAY['agitate','upset']::TEXT[]),
('Discredit', '', 'verb', 'C1', 'To harm the good reputation of a person; to cause an idea or piece of evidence to seem false or unreliable.', 'The candidate tried to discredit his opponent.', ARRAY['demean','disgrace','dishonour','disprove','invalidate']::TEXT[]),
('Discrepancy', '/dɪsˈkɹɛpənsi/', 'noun', 'C1', 'An inconsistency between facts or sentiments.', 'They found a discrepancy between the first set of test results and the second, and they''''re still trying to figure out why.', ARRAY['anomalous','discordance','anomaly','conflict','contrariety']::TEXT[]),
('Discretionary', '/dɪˈskɹɛʃən(ə)ɹi/', 'adjective', 'C1', 'Available at one''''s discretion; able to be used as one chooses; left to or regulated by one''''s own discretion or judgment.', 'discretionary income', ARRAY['elective','optional']::TEXT[]),
('Discursive', '/dɪsˈkɜː(ɹ)sɪv/', 'adjective', 'C2', '(of speech or writing) Tending to digress from the main point; rambling.', '', ARRAY[]::TEXT[]),
('Disdain', '/dɪsˈdeɪn/', 'verb', 'C1', 'To regard (someone or something) with strong contempt.', '', ARRAY['abominate','contemn']::TEXT[]),
('Disengage', '/ˌdɪsɪŋˈɡeɪdʒ/', 'verb', 'C1', 'To release or loosen from something that binds, entangles, holds, or interlocks.', '', ARRAY['detach','disentangle','free','unfasten','detach']::TEXT[]),
('Disgorge', '/dɪsˈɡɔːdʒ/', 'verb', 'C1', 'To vomit or spew, to discharge.', '', ARRAY[]::TEXT[]),
('Disgruntle', '/dɪsˈɡɹʌnt(ə)l/', 'verb', 'C1', 'To make discontent or cross; to put in a bad temper.', '', ARRAY[]::TEXT[]),
('Disguise', '/dɪsˈɡaɪz/', 'verb', 'C1', 'To change the appearance of (a person or thing) so as to hide, or to assume an identity.', 'Spies often disguise themselves.', ARRAY['camouflage','cloak','hide','mask']::TEXT[]),
('Disinclination', '', 'noun', 'C1', 'The state of being disinclined; want of propensity, desire, or affection; slight aversion or dislike', '', ARRAY['indisposition','indisposition']::TEXT[]),
('Disinfect', '/dɪs.ɪnˈfɛkt/', 'verb', 'C1', 'To sterilize by the use of cleaning agent.', '', ARRAY[]::TEXT[]),
('Disjointed', '/dɪsˈdʒɔɪn.tɪd/', 'adjective', 'C1', 'Not connected, coherent, or continuous.', 'The hours of his illness were disjointed and confusing as he drifted in and out of consciousness.', ARRAY[]::TEXT[]),
('Disinter', '/ˌdɪsɪnˈtɜː(ɹ)/', 'verb', 'C1', 'To take out of the grave or tomb.', '', ARRAY['dig up','exhume','unbury','dig up','exhume']::TEXT[]),
('Disjunctive', '/dɪsˈdʒʊŋktɪv/', 'adjective', 'C1', 'Not connected; separated.', '', ARRAY[]::TEXT[]),
('Dismantle', '[dɪsˈmæntʰəɫ]', 'verb', 'C1', 'To divest, strip of dress or covering.', '', ARRAY[]::TEXT[]),
('Dismay', '/dɪsˈmeɪ/', 'verb', 'C1', 'To cause to feel apprehension; great sadness, or fear; to deprive of energy', '', ARRAY['appall','daunt','terrify','appall','daunt']::TEXT[]),
('Disparage', '/dɪsˈpæɹɪd͡ʒ/', 'verb', 'C1', 'To match unequally; to degrade or dishonor.', '', ARRAY[]::TEXT[]),
('Disregard', '/dɪsɹɪˈɡɑːd/', 'verb', 'C1', 'To ignore; pay no attention to.', '', ARRAY['misregard','unheed','unmind']::TEXT[]),
('Dissect', '/dɪˈsɛkt/', 'verb', 'C1', 'To study an animal''''s anatomy by cutting it apart; to perform a necropsy or an autopsy.', '', ARRAY[]::TEXT[]),
('Dissemble', '[dɪˈsɛmbəɫ]', 'verb', 'C2', 'To disguise or conceal something.', '', ARRAY['disregard','take no notice of']::TEXT[]),
('Dissension', '/dɪˈsɛnʃən/', 'noun', 'C1', 'An act of expressing dissent, especially spoken.', '', ARRAY[]::TEXT[]),
('Dissent', '/dɪˈsɛnt/', 'verb', 'C1', 'To disagree; to withhold assent. Construed with from (or, formerly, to).', '', ARRAY['disagree','refute','reject','take exception']::TEXT[]),
('Dissipate', '/ˈdɪsɪpeɪt/', 'verb', 'C2', 'To drive away, disperse.', '', ARRAY[]::TEXT[]),
('Dissolute', '/ˈdɪsəljuːt/', 'adjective', 'C1', 'Unrestrained by morality.', '', ARRAY['debauched','dissipated','hedonic','lascivious','lewd']::TEXT[]),
('Dissonance', '/ˈdɪsənəns/', 'noun', 'C1', 'A harsh, discordant combination of sounds.', '', ARRAY[]::TEXT[]),
('Dissuade', '/dɪˈsweɪd/', 'verb', 'C1', 'To convince not to try or do.', 'Jane dissuaded Martha from committing suicide.', ARRAY[]::TEXT[]),
('Distal', '/ˈdɪs.təl/', 'adjective', 'C1', 'Remote from the point of attachment or origin.', 'the distal end of a bone or muscle', ARRAY[]::TEXT[]),
('Distend', '/dɪsˈtɛnd/', 'verb', 'C1', 'To extend or expand, as from internal pressure; to swell', '', ARRAY[]::TEXT[]),
('Distill', '[dɪˈstɪɫ]', 'verb', 'C1', 'To subject a substance to distillation.', 'Firs distill resin.', ARRAY[]::TEXT[]),
('Distraught', '/dɪsˈtɹɔːt/', 'adjective', 'C1', 'Deeply hurt, saddened, or worried; distressed.', 'His distraught widow cried for days, feeling very alone.', ARRAY['distressed','pained']::TEXT[]),
('Ditty', '/ˈdɪti/', 'verb', 'C1', 'To sing; to warble a little tune.', '', ARRAY[]::TEXT[]),
('Diurnal', '/daɪˈɜːnəɫ/', 'adjective', 'C1', 'Happening or occurring during daylight, or primarily active during that time.', 'Most birds are diurnal.', ARRAY['circadian']::TEXT[]),
('Diverge', '/daɪˈvɜːdʒ/', 'verb', 'C1', '(of lines or paths) To run apart; to separate; to tend into different directions.', 'Both stories start out the same way, but they diverge halfway through.', ARRAY[]::TEXT[]),
('Divestiture', '', 'noun', 'C1', 'The act of divesting, or something divested.', '', ARRAY[]::TEXT[]),
('Divulge', '/daɪˈvʌldʒ/', 'verb', 'C1', 'To make public or known; to communicate to the public; to tell (information, especially a secret) so that it may become generally known', 'I will never divulge that secret to anyone.', ARRAY['bewray','bring out','disclose','discover','expose']::TEXT[]),
('Dodder', '', 'verb', 'C1', 'To shake or tremble as one moves, especially as of old age or childhood; to totter.', '', ARRAY[]::TEXT[]),
('Dodge', '/dɒdʒ/', 'verb', 'C1', 'To avoid (something) by moving suddenly out of the way.', 'He dodged traffic crossing the street.', ARRAY['duck','evade','fudge','shun','skirt']::TEXT[]),
('Doff', '/dɒf/', 'verb', 'C1', '(clothing) To remove or take off, especially of clothing.', 'The rustics doffed their hats at the clergy.', ARRAY['take off','take off']::TEXT[]),
('Dogged', '/dɒɡd/', 'verb', 'C1', 'To pursue with the intent to catch.', 'The woman cursed him so that trouble would dog his every step.', ARRAY['chase','chase after','go after','pursue','tag']::TEXT[])
ON CONFLICT (word) DO NOTHING;
