INSERT INTO words (word, phonetic, pos, level, def_en, ex_en, synonyms) VALUES
('Rookie', '/ˈɹʊki/', 'adjective', 'C1', 'Non-professional; amateur', 'The game was going well until I made that rookie mistake.', ARRAY[]::TEXT[]),
('Roster', '/ˈɹɒstə/', 'verb', 'C1', 'To place the name of (a person) on a roster.', 'I have rostered you for cleaning duties on the first Monday of each month.', ARRAY[]::TEXT[]),
('Rostrum', '/ˈɹɒstɹəm/', 'noun', 'C1', 'A dais, pulpit, or similar platform for a speaker, conductor, or other performer.', '', ARRAY['dais','pulpit','dais','pulpit']::TEXT[]),
('Rouse', '/ˈɹaʊz/', 'verb', 'C1', 'To wake (someone) or be awoken from sleep, or from apathy.', 'to rouse the faculties, passions, or emotions', ARRAY[]::TEXT[]),
('Royalty', '/ˈɹɔɪəlti/', 'noun', 'C1', 'The rank, status, power or authority of a monarch.', '', ARRAY[]::TEXT[]),
('Rubicund', '', 'adjective', 'C1', 'Ruddy; possessing a red complexion.', '', ARRAY[]::TEXT[]),
('Rue', '/ɹuː/', 'noun', 'C1', 'Sorrow; repentance; regret.', '', ARRAY[]::TEXT[]),
('Ruffle', '/ˈɹʌfəl/', 'verb', 'C1', 'To make a ruffle in; to curl or flute, as an edge of fabric.', 'Ruffle the end of the cuff.', ARRAY[]::TEXT[]),
('Ruminate', '/ˈɹumɪneɪt/', 'adjective', 'C1', 'Having a hard albumen penetrated by irregular channels filled with softer matter, as the nutmeg and the seeds of the North American papaw.', 'a ruminate endosperm', ARRAY[]::TEXT[]),
('Rumple', '/ˈɹʌmpəl/', 'verb', 'C1', 'To make wrinkled, particularly fabric.', 'I''''ll rumple my bedsheets so it looks like I was here last night.', ARRAY[]::TEXT[]),
('Rupture', '/ˈɹʌptʃə/', 'verb', 'C1', 'To burst, break through, or split, as under pressure.', '', ARRAY[]::TEXT[]),
('Ruse', '/ɹuːz/', 'verb', 'C1', 'To deceive or trick using a ruse.', '', ARRAY[]::TEXT[]),
('Rustle', '/ˈɹʌsəl/', 'verb', 'C1', 'To move (something) with a soft crackling sound.', '', ARRAY['rustle up','rustle up']::TEXT[]),
('Savory', '/ˈseɪvəɹi/', 'adjective', 'C1', 'Tasty, attractive to the palate.', 'The fine restaurant presented an array of savory dishes; each was delicious.', ARRAY[]::TEXT[]),
('Sawdust', '/ˈsɔːˌdʌst/', 'verb', 'C1', 'To sprinkle with sawdust.', '', ARRAY[]::TEXT[]),
('Scabbard', '/ˈskæb.əd/', 'verb', 'C1', 'To put an object (especially a sword) into its scabbard.', 'Suddenly he scabbarded his sabre.', ARRAY[]::TEXT[]),
('Scads', '', 'noun', 'C1', 'Any of several fish, of the family Carangidae, from the western Atlantic.', '', ARRAY[]::TEXT[]),
('Scalpel', '/ˈskælpəl/', 'noun', 'C1', 'A small straight knife with a very sharp blade used for surgery, dissection and craftwork.', '', ARRAY[]::TEXT[]),
('Scant', '/skænt/', 'adjective', 'C1', 'Very little, very few.', 'After his previous escapades, Mary had scant reason to believe John.', ARRAY['geason','few','little','slight']::TEXT[]),
('Scathing', '', 'adjective', 'C1', 'Harshly or bitterly critical; vitriolic', '', ARRAY[]::TEXT[]),
('Schism', '/ˈskɪzəm/', 'noun', 'C1', 'A split or separation within a group or organization, typically caused by discord.', 'The schism between Sunnis and Shias happened quite early in Islamic history.', ARRAY['division','separation','split']::TEXT[]),
('Scintillate', '/ˈsɪntɪleɪt/', 'verb', 'C1', 'To give off sparks; to shine as if emanating sparks; to twinkle or glow.', '', ARRAY[]::TEXT[]),
('Scion', '/ˈsaɪən/', 'noun', 'C1', 'A descendant, especially a first-generation descendant of a distinguished family.', '', ARRAY[]::TEXT[]),
('Scission', '/ˈsɪ.ʒən/', 'noun', 'C1', 'The act of division, separation, cutting or severing', '', ARRAY[]::TEXT[]),
('Scissor', '/ˈsɪzə/', 'verb', 'C1', 'To cut using, or as if using, scissors.', 'The erroneous testimony was scissored from the record.', ARRAY[]::TEXT[]),
('Scoff', '/skɒf/', 'verb', 'C1', 'To jeer; to laugh with contempt and derision.', '', ARRAY['sneer','contemn','deride']::TEXT[]),
('Scooter', '/ˈskuːtə(ɹ)/', 'verb', 'C1', 'To ride on a scooter.', '', ARRAY[]::TEXT[]),
('Scorch', '/skɔːtʃ/', 'verb', 'C1', 'To burn the surface of something so as to discolour it', '', ARRAY[]::TEXT[]),
('Scorn', '/skɔːn/', 'verb', 'C1', 'To feel or display contempt or disdain for something or somebody; to despise.', 'He scorned her romantic advances.', ARRAY['deride','mock','ridicule','scoff','sneer']::TEXT[]),
('Scotch', '/skɒtʃ/', 'verb', 'C1', 'To cut or score; to wound superficially.', 'The rain scotched his plans of going to the beach.', ARRAY['block','chock','foil','put the kibosh on','thwart']::TEXT[]),
('Scour', '/ˈskaʊə/', 'verb', 'C1', 'To clean, polish, or wash something by rubbing and scrubbing it vigorously, frequently with an abrasive or cleaning agent.', 'He scoured the burnt food from the pan.', ARRAY[]::TEXT[]),
('Scowl', '/skaʊl/', 'verb', 'C1', 'To wrinkle the brows, as in frowning or displeasure; to put on a frowning look; to look sour, sullen, severe, or angry.', 'to scowl a rival into submission', ARRAY[]::TEXT[]),
('Scrappy', '/ˈskɹæpi/', 'adjective', 'C1', 'Consisting of scraps; fragmentary; lacking unity or consistency.', 'That was a scrappy lecture.', ARRAY['feisty','pugnacious','disconnected']::TEXT[]),
('Scrap', '/skɹæp/', 'verb', 'C1', 'To discard.', '', ARRAY[]::TEXT[]),
('Scrawl', '/skɹɔːl/', 'verb', 'C1', 'To write something hastily or illegibly.', '', ARRAY[]::TEXT[]),
('Scribble', '/ˈskɹɪbəl/', 'verb', 'C1', 'To write or draw carelessly and in a hurry', '', ARRAY['scrawl']::TEXT[]),
('Scrutinize', '/ˈskɹuːtɨnaɪz/', 'verb', 'C1', 'To examine something with great care or detail, as to look for hidden or obscure flaws.', 'to scrutinize the conduct or motives of individuals', ARRAY[]::TEXT[]),
('Scuff', '/skʌf/', 'verb', 'C1', 'To scrape the feet while walking.', '', ARRAY[]::TEXT[]),
('Sculpt', '', 'verb', 'C1', 'To form by sculpture.', 'They sculpted a statue out of clay.', ARRAY[]::TEXT[]),
('Scurrilous', '/ˈskʌ.ɹə.ləs/', 'adjective', 'C1', '(of a person) Given to vulgar verbal abuse; foul-mouthed.', 'We have had our address used by scurrilous crooks in the past to gain assets by fraud.', ARRAY[]::TEXT[]),
('Scurvy', '', 'adjective', 'C1', 'Covered or affected with scurf or scabs; scabby; scurfy; specifically, diseased with the scurvy.', 'a scurvy trick; a scurvy knave', ARRAY['roynish','scabrous','miserable','paltry','shabby']::TEXT[]),
('Scythe', '/ˈsaɪð/', 'verb', 'C1', 'To use a scythe.', '', ARRAY[]::TEXT[]),
('Seascape', '', 'noun', 'C1', 'A piece of art that depicts the sea or shoreline.', '', ARRAY['marinescape','seapiece']::TEXT[]),
('Seamy', '/ˈsiːmi/', 'adjective', 'C1', 'Sordid, squalid or corrupt.', '', ARRAY[]::TEXT[]),
('Secluded', '', 'adjective', 'C1', 'Hidden, isolated, remote.', '', ARRAY['isolated','off the grid']::TEXT[]),
('Sedate', '/sɪˈdeɪt/', 'adjective', 'C1', '(of a person or their behaviour) Remaining composed and dignified, and avoiding too much activity or excitement.', '', ARRAY['placid','staid','unruffled','placid','staid']::TEXT[]),
('Sedentary', '/ˈsɛd(ə)ntɛɹi/', 'adjective', 'C1', 'Not moving; relatively still; staying in the vicinity.', 'The oyster is a sedentary mollusk; the barnacles are sedentary crustaceans.', ARRAY['abeyant','cessant','dormant','non-migratory','settled']::TEXT[]),
('Seduce', '/sɪˈdjuːs/', 'verb', 'C1', 'To beguile or lure (someone) away from duty, accepted principles, or proper conduct; to lead astray.', 'He had repeatedly seduced the girl in his car, hotels and his home.', ARRAY['coitize','go to bed with','sleep with','debauch','forlead']::TEXT[]),
('Sedulous', '/ˈsɛdjʊ-/', 'adjective', 'C2', 'Of a person: diligent in application or pursuit; constant and persevering in business or in endeavours to effect a goal; steadily industrious.', '', ARRAY['assiduous','assiduous']::TEXT[]),
('Seemly', '/ˈsiːmli/', 'adjective', 'C1', '(of behavior) Appropriate; suited to the occasion or purpose; becoming.', 'His behavior was seemly, as befits a gentleman.', ARRAY['apposite']::TEXT[]),
('Self-abasement', '', 'noun', 'C1', 'The debasement of oneself', '', ARRAY[]::TEXT[]),
('Self-absorbed', '', 'adjective', 'C1', 'Overly concerned about oneself, to the point of ignoring the feelings of others.', 'I don''''t want to call him self-absorbed but he was more concerned with the scratch on his car than the people in the car he hit.', ARRAY['inconsiderate']::TEXT[]),
('Seine', '/seɪn/', 'verb', 'C1', 'To use a seine, to fish with a seine.', '', ARRAY[]::TEXT[]),
('Seminal', '/ˈsɛmɪnəl/', 'adjective', 'C1', 'Of or relating to seed or semen.', '"The Structure of Scientific Revolutions" was a seminal work in the modern philosophy of science.', ARRAY['innovative','primary','formative','influential','innovative']::TEXT[]),
('Seminary', '', 'adjective', 'C1', 'Of or relating to seed; seminal.', '', ARRAY[]::TEXT[]),
('Sentinel', '/ˈsɛntɪnəl/', 'verb', 'C1', 'To watch over as a guard.', 'He sentineled the north wall.', ARRAY[]::TEXT[]),
('Sepulchral', '/səˈpʊlkɹəl/', 'adjective', 'C1', 'Relating to a grave or to death; funereal.', '', ARRAY[]::TEXT[]),
('Septic', '', 'adjective', 'C1', 'Of or pertaining to sepsis.', '', ARRAY[]::TEXT[]),
('Sequela', '/sɪˈkwiːlə/', 'noun', 'C1', 'A disease or condition which is caused by an earlier disease or problem.', '', ARRAY[]::TEXT[]),
('Sequester', '/səˈkwɛs.tə/', 'verb', 'C1', 'To separate from all external influence; to seclude; to withdraw.', 'The jury was sequestered from the press by the judge''''s order.', ARRAY['segregate']::TEXT[]),
('Seraph', '/ˈsɛɹəf/', 'noun', 'C1', 'A six-winged angel; the highest choir or order of angels in Christian angelology, ranked above cherubim, and below God. They are the 5th highest order of angels in Jewish angelology. A detailed description can be found at the beginning of Isaiah chapter 6', '', ARRAY[]::TEXT[]),
('Sere', '/sɪə/', 'adjective', 'C1', 'Without moisture; dry.', '', ARRAY['sare','sear','sare','sear']::TEXT[]),
('Serfdom', '', 'noun', 'C1', 'The state of being a serf.', '', ARRAY['serfage','serfhood']::TEXT[]),
('Sermon', '/ˈsɜː.mən/', 'noun', 'C1', 'Religious discourse; a written or spoken address on a religious or moral matter.', '', ARRAY[]::TEXT[]),
('Serpentine', '/ˈsəːpəntaɪn/', 'adjective', 'C1', 'Of, pertaining to, or characteristic of snakes.', 'The wily criminal was known for his serpentine behavior.', ARRAY['ophidian','sinuous','tortuous','winding','ophidian']::TEXT[]),
('Serrate', '', 'adjective', 'C1', 'Having tooth-like projections on one side, as in a saw.', 'Many click beetles have serrate antennae.', ARRAY['jagged','saw-toothed']::TEXT[]),
('Serried', '', 'adjective', 'C1', 'Crowded together in rows.', '', ARRAY[]::TEXT[]),
('Servile', '/ˈsɜː(ɹ).ˌvaɪl/', 'adjective', 'C1', 'Of or pertaining to a slave.', 'servile flattery; servile obedience', ARRAY[]::TEXT[]),
('Shackle', '/ˈʃækəl/', 'noun', 'C1', '(usually in the plural) A restraint fit over a human or animal appendage, such as a wrist, ankle or finger; normally used in pairs joined by a chain.', 'The prisoner lay in shackles in his gloomy cell.', ARRAY['hobble','hobble']::TEXT[]),
('Shale', '/ʃeɪl/', 'verb', 'C1', 'To take off the shell or coat of.', '', ARRAY['shell']::TEXT[]),
('Sham', '/ʃæm/', 'adjective', 'C1', 'Intended to deceive; false.', 'It was only a sham wedding: they didn''''t care much for one another, but wanted their parents to stop hassling them.', ARRAY['mock']::TEXT[]),
('Shard', '/ʃaːd/', 'verb', 'C1', 'To fall apart into shards, usually as the result of impact or explosion.', '', ARRAY[]::TEXT[]),
('Shiftless', '', 'adjective', 'C1', 'Lazy, unmotivated', '', ARRAY[]::TEXT[]),
('Shipshape', '/ˈʃɪpʃeɪp/', 'adjective', 'C1', '(originally nautical) Meticulously neat and tidy.', '', ARRAY['shipshape and Bristol fashion','tight','shipshape and Bristol fashion','tight']::TEXT[]),
('Shirk', '/ʃɜːk/', 'verb', 'C1', 'To avoid, especially a duty, responsibility, etc.; to stay away from.', 'If you have a job, don''''t shirk from it by staying off work.', ARRAY[]::TEXT[]),
('Shoal', '/ʃɒʊl/', 'verb', 'C1', 'To arrive at a shallow (or less deep) area.', 'The colour of the water shows where it shoals.', ARRAY[]::TEXT[]),
('Shopworn', '', 'adjective', 'C1', 'Having been used, as a sample item in a retail store.', 'The handbag looks nice, but shopworn.', ARRAY[]::TEXT[]),
('Shred', '/ʃɹɛd/', 'noun', 'C1', 'A long, narrow piece cut or torn off; a strip.', 'There isn''''t a shred of evidence to support his claims.', ARRAY[]::TEXT[]),
('Shrewd', '/ʃɹuːd/', 'adjective', 'C1', 'Showing clever resourcefulness in practical matters.', 'a shrewd guess', ARRAY[]::TEXT[]),
('Shrine', '/ʃɹaɪ̯n/', 'verb', 'C1', 'To enshrine; to place reverently, as if in a shrine.', '', ARRAY[]::TEXT[]),
('Shun', '/ʃʌn/', 'verb', 'C1', 'To avoid, especially persistently.', 'Acrophobes shun mountaineering.', ARRAY[]::TEXT[]),
('Sidereal', '/saɪˈdɪəɹi.əl/', 'adjective', 'C1', 'Of or relating to the stars.', '', ARRAY[]::TEXT[]),
('Sidestep', '', 'verb', 'C1', 'To step to the side.', 'They sidestepped the issue.', ARRAY[]::TEXT[]),
('Simper', '/ˈsɪmpə/', 'verb', 'C1', 'To smile in a foolish, frivolous, self-conscious, coy, or smug manner.', '', ARRAY[]::TEXT[]),
('Simpleton', '/ˈsɪmpəltən/', 'noun', 'C1', 'A simple-minded person lacking common sense.', '', ARRAY[]::TEXT[]),
('Sinecure', '/ˈsaɪ.nɪ.kjʊə/', 'verb', 'C2', 'To put or place in a sinecure.', '', ARRAY[]::TEXT[]),
('Sinew', '/ˈsɪnjuː/', 'verb', 'C1', 'To knit together or make strong with, or as if with, sinews.', '', ARRAY[]::TEXT[]),
('Singe', '/sɪnd͡ʒ/', 'verb', 'C1', 'To burn slightly.', '', ARRAY['scorch']::TEXT[]),
('Sinuous', '/ˈsɪn.ju.əs/', 'adjective', 'C1', 'Having curves in alternate directions; meandering.', 'We followed every bend of the sinuous river.', ARRAY['anfractuous','flexuous','serpentine','winding','windy']::TEXT[]),
('Sip', '/sɪp/', 'verb', 'C1', 'To ooze or pass slowly through pores or other small openings, and in overly small quantities; said of liquids, etc.', 'The water steadily seeped in through the thirl.', ARRAY['leak']::TEXT[]),
('Siren', '/ˈsaɪəɹən/', 'adjective', 'C1', 'Relating to or like a siren.', '', ARRAY['bewitching','enchanting','enticing','sirenic','bewitching']::TEXT[]),
('Skeleton', '/ˈskɛlətən/', 'verb', 'C1', 'To reduce to a skeleton; to skin; to skeletonize', '', ARRAY[]::TEXT[]),
('Skeptic', '/ˈskɛp.tɪk/', 'noun', 'C1', 'Someone who habitually doubts beliefs and claims presented as accepted by others, requiring strong evidence before accepting any belief or claim.', '', ARRAY[]::TEXT[]),
('Skimp', '/skɪmp/', 'verb', 'C1', 'To mock, deride, scorn, scold, make fun of.', 'I thought Adie was only skimpin'''' me.', ARRAY[]::TEXT[]),
('Skirmish', '/ˈskɜːmɪʃ/', 'verb', 'C1', 'To engage in a minor battle or dispute', '', ARRAY[]::TEXT[]),
('Skit', '', 'verb', 'C1', '(Merseyside) To make fun of.', '', ARRAY[]::TEXT[]),
('Slack', '/slæk/', 'adjective', 'C1', '(normally said of a rope) Lax; not tense; not firmly extended.', 'a slack rope', ARRAY['easy','moderate','slow']::TEXT[]),
('Slab', '/slæb/', 'verb', 'C1', 'To make something into a slab.', '', ARRAY[]::TEXT[]),
('Slake', '/sleɪk/', 'verb', 'C1', 'To satisfy (thirst, or other desires).', 'The lime slakes.', ARRAY['extinguish','quench','extinguish','quench']::TEXT[]),
('Slant', '/ˈslænt/', 'adjective', 'C1', 'Sloping; oblique; slanted.', '', ARRAY[]::TEXT[]),
('Slate', '/sleɪt/', 'adjective', 'C1', 'Having the bluish-grey/gray colour of slate.', '', ARRAY[]::TEXT[]),
('Slew', '/sluː/', 'verb', 'C1', 'To rotate or turn something about its axis.', 'The single line was slewed onto the disused up formation to make way for the future redoubling.', ARRAY[]::TEXT[]),
('Sling', '/ˈslɪŋ/', 'verb', 'C1', 'To throw with a circular or arcing motion.', '', ARRAY[]::TEXT[]),
('Slippery', '/ˈslɪpəɹi/', 'adjective', 'C1', 'Of a surface, having low friction, often due to being covered in a non-viscous liquid, and therefore hard to grip, hard to stand on without falling, etc.', 'Oily substances render things slippery.', ARRAY['greasy','slick','slimy','slippy','wet']::TEXT[]),
('Slipshod', '/ˈslɪp.ʃɒd/', 'adjective', 'C1', 'Done poorly or too quickly; slapdash.', '', ARRAY[]::TEXT[]),
('Sloppy', '', 'adjective', 'C1', 'Very wet; covered in or composed of slop.', 'The dog tracked sloppy mud through the kitchen!', ARRAY[]::TEXT[]),
('Sloth', '/slɑθ/', 'verb', 'C1', 'To be idle; to idle (away time).', '', ARRAY[]::TEXT[]),
('Slouch', '/slaʊt͡ʃ/', 'verb', 'C1', 'To hang or droop; to adopt a limp posture', 'Do not slouch when playing a flute.', ARRAY[]::TEXT[]),
('Slovenly', '/ˈslɒv.ən.li/', 'adjective', 'C1', 'Having an untidy appearance; unkempt.', '', ARRAY[]::TEXT[]),
('Sluggard', '', 'noun', 'C1', 'A person who is lazy, stupid, or idle by habit.', '', ARRAY[]::TEXT[]),
('Sluggish', '/ˈslʌɡɪʃ/', 'adjective', 'C1', 'Habitually idle and lazy; slothful; dull; inactive', 'a sluggish man', ARRAY[]::TEXT[]),
('Slumber', '/slʌmbə/', 'verb', 'C1', 'To be in a very light state of sleep, almost awake.', '', ARRAY[]::TEXT[]),
('Slur', '/slɜː(ɹ)/', 'verb', 'C1', 'To insult or slight.', 'to slur syllables; He slurs his speech when he is drunk.', ARRAY[]::TEXT[]),
('Sly', '/slaɪ/', 'adjective', 'C1', 'Artfully cunning; secretly mischievous; wily.', 'a sly trick', ARRAY['artful','cautious','nimble','shrewd','skillful']::TEXT[]),
('Smarmy', '/ˈsmɑː.mi/', 'adjective', 'C1', 'Falsely earnest, smug, or ingratiating.', 'a smarmy salesman with a big smile', ARRAY['flattering','gushing','ingratiating','oily','smug']::TEXT[]),
('Smirk', '/smɜːk/', 'adjective', 'C1', 'Smart; spruce; affected; simpering', '', ARRAY[]::TEXT[]),
('Smother', '/ˈsmʌðɚ/', 'verb', 'C1', 'To suffocate; stifle; obstruct, more or less completely, the respiration of something or someone.', 'to smother a fire with ashes', ARRAY['conceal','cover up','hide','stifle','conceal']::TEXT[]),
('Smuggle', '/ˈsmʌɡəl/', 'verb', 'C1', 'To import or export, illicitly or by stealth, without paying lawful customs charges or duties', '', ARRAY[]::TEXT[]),
('Snare', '/snɛə/', 'verb', 'C1', 'To catch or hold, especially with a loop.', '', ARRAY[]::TEXT[]),
('Snarl', '/ˈsnɑː(ɹ)l/', 'verb', 'C1', 'To entangle; to complicate; to involve in knots.', 'to snarl a skein of thread', ARRAY[]::TEXT[]),
('Sneer', '/snɪə̯/', 'verb', 'C1', 'To raise a corner of the upper lip slightly, especially in scorn', '"Now here''''s someone who should attend privilege workshops," sneered she.', ARRAY[]::TEXT[]),
('Snobbish', '', 'adjective', 'C1', 'Having the property of being a snob; arrogant and pretentious; smugly superior or dismissive of perceived inferiors.', '', ARRAY['cliquish']::TEXT[]),
('Sober', '/ˈsəʊ.bə(ɹ)/', 'adjective', 'C1', 'Not drunk; not intoxicated', '1890, John Charles, The Godly, Righteous, And Sober Life', ARRAY[]::TEXT[]),
('Sodden', '/ˈsɒ.dən/', 'adjective', 'C1', 'Soaked or drenched with liquid; soggy, saturated.', '', ARRAY['blank','stonefaced','dopping','waterlogged']::TEXT[]),
('Solace', '/ˈsɒ.lɪs/', 'verb', 'C1', 'To give solace to; comfort; cheer; console.', '', ARRAY[]::TEXT[]),
('Solder', '/ˈsɑdɚ/', 'verb', 'C1', 'To join items together, or to coat them with solder', '', ARRAY[]::TEXT[]),
('Solemnity', '/səˈlɛmnɪti/', 'noun', 'C1', 'The quality of being deeply serious and sober or solemn.', 'the solemnity of a funeral', ARRAY[]::TEXT[]),
('Solicitous', '/səˈlɪsɪtəs/', 'adjective', 'C2', 'Disposed to solicit; eager to obtain something desirable, or to avoid anything evil.', '', ARRAY[]::TEXT[]),
('Sprightly', '/ˈspɹaɪtli/', 'adjective', 'C1', 'Animated, gay or vivacious; lively, spirited.', '', ARRAY['active','dynamic','mettlesome','vivacious','energetic']::TEXT[]),
('Spur', '/spɜː/', 'verb', 'C1', 'To prod (especially a horse) on the side or flank, with the intent to urge motion or haste, to gig.', 'to spur boots', ARRAY['drive','impel','incite','instigate','stimulate']::TEXT[]),
('Squabble', '/ˈskwɒbl/', 'verb', 'C1', 'To participate in a minor fight or argument.', 'The brothers were always squabbling with each other.', ARRAY[]::TEXT[]),
('Squalid', '/ˈskwɒlɪd/', 'adjective', 'C1', 'Extremely dirty and unpleasant.', 'A squalid attempt to buy votes.', ARRAY[]::TEXT[]),
('Squall', '/ˈskwɔːl/', 'verb', 'C1', 'To cry or wail loudly.', '', ARRAY[]::TEXT[]),
('Squat', '/skwɒt/', 'adjective', 'C1', 'Relatively short or low, and thick or broad.', '', ARRAY[]::TEXT[]),
('Squint', '/skwɪnt/', 'adjective', 'C1', 'Looking obliquely; having the vision distorted.', '', ARRAY[]::TEXT[]),
('Squelch', '/ˈskwɛltʃ/', 'verb', 'C2', 'To halt, stop, eliminate, stamp out, or put down, often suddenly or by force', 'Even the king’s announcement could not squelch the rumors.', ARRAY['quash']::TEXT[]),
('Stalwart', '/ˈstɒl-/', 'adjective', 'C2', 'Firmly or solidly built.', '', ARRAY['bold','brave','courageous','daring','valiant']::TEXT[]),
('Stamina', '/ˈstæmɪnə/', 'noun', 'C1', 'The energy and strength for continuing to do something over a long period of time; power of sustained exertion, or resistance to hardship, illness etc.', 'He has a lot of stamina. I suppose that''''s why he can run for a long time.', ARRAY[]::TEXT[]),
('Stammer', '/ˈstæmə/', 'verb', 'C1', 'To keep repeating a particular sound involuntarily during speech.', 'He blushed, and stammered a few words of apology.', ARRAY['stutter']::TEXT[]),
('Stanza', '/ˈstænzə/', 'noun', 'C1', 'A unit of a poem, written or printed as a paragraph; equivalent to a verse.', '', ARRAY[]::TEXT[]),
('Startle', '/ˈstɑːt(ə)l/', 'verb', 'C1', 'To move suddenly, or be excited, on feeling alarm; to start.', 'a horse that startles easily', ARRAY['deter','alarm','frighten','scare','surprise']::TEXT[]),
('Static', '/ˈstæt.ɪk/', 'adjective', 'C1', 'Unchanging; that cannot or does not change.', '', ARRAY['stable','stable','still','stable','stable']::TEXT[]),
('Stature', '/ˈstætʃ.ə/', 'noun', 'C1', 'A person or animal''''s natural height when standing upright.', '', ARRAY[]::TEXT[]),
('Stealth', '/stɛlθ/', 'adjective', 'C1', 'Of a transgender person, hiding their transgender status from society after transition.', 'He has been/lived stealth for 10 years.', ARRAY[]::TEXT[]),
('Stench', '/stɛntʃ/', 'verb', 'C1', 'To cause to emit a disagreeable odour; to cause to stink.', '', ARRAY[]::TEXT[]),
('Stencil', '/ˈstɛnsɪl/', 'verb', 'C1', 'To print with a stencil.', '', ARRAY[]::TEXT[]),
('Stentorian', '/stɛnˈtɔː.ɹi.ən/', 'adjective', 'C1', '(of a voice) Loud, powerful, booming, suitable for giving speeches to large crowds.', '', ARRAY[]::TEXT[]),
('Sterile', '/ˈstɛɹaɪl/', 'adjective', 'C1', 'Unable to reproduce (or procreate).', 'a sterile kitchen table', ARRAY['barren','infertile']::TEXT[]),
('Stickler', '/ˈstɪk.lə/', 'noun', 'C1', 'A referee or adjudicator at a fight, wrestling match, duel, etc. who ensures fair play.', 'Lexicographers are sticklers for correct language.', ARRAY['dogmatist','formalist','pedant','traditionalist','dogmatist']::TEXT[]),
('Stifle', '/ˈstaɪfəl/', 'verb', 'C1', 'To interrupt or cut off.', 'The army stifled the rebellion.', ARRAY['hinder','restrain','suppress','throttle']::TEXT[]),
('Stigma', '/ˈstɪɡmə/', 'noun', 'C1', 'A mark of infamy or disgrace.', '', ARRAY[]::TEXT[]),
('Stint', '/stɪnt/', 'verb', 'C1', 'To stop (an action); cease, desist.', 'The next party you throw, don''''t stint on the beer.', ARRAY[]::TEXT[]),
('Stingy', '/ˈstɪndʒi/', 'adjective', 'C1', 'Unwilling to spend, give, or share; ungenerous; mean', '', ARRAY[]::TEXT[]),
('Subordinate', '', 'adjective', 'C1', 'Placed in a lower class, rank, or position.', 'In the sentence “The barbecue finished before John arrived”, the subordinate clause “before John arrived” specifies the time of the main clause, “The barbecue finished”.', ARRAY['dependent','lesser','lesser','dependent']::TEXT[]),
('Subpoena', '/səˈpiːnə/', 'verb', 'C1', 'To summon with a subpoena.', '', ARRAY[]::TEXT[]),
('Subservient', '', 'adjective', 'C1', 'Useful in an inferior capacity.', '', ARRAY[]::TEXT[]),
('Subside', '', 'verb', 'C1', 'To sink or fall to the bottom; to settle, as lees.', 'The fever has subsided.', ARRAY[]::TEXT[]),
('Subsidiary', '/sʌbˈsɪ.di.əɹ.i/', 'adjective', 'C1', 'Auxiliary or supplemental.', 'a subsidiary stream', ARRAY[]::TEXT[]),
('Substantiate', '/səbˈstanʃɪeɪt/', 'verb', 'C1', 'To verify something by supplying evidence; to authenticate or corroborate', '', ARRAY[]::TEXT[]),
('Substantive', '/səbˈstæntɪv/', 'adjective', 'C1', 'Of the essence or essential element of a thing; as, "substantive information"', '', ARRAY['essential','in essence','meaty','substantial','substantival']::TEXT[]),
('Subterfuge', '/ˈsʌbtəɹˌfjuː(d)ʒ/', 'noun', 'C2', 'An indirect or deceptive device or stratagem; a blind. Refers especially to war and diplomatics.', 'Overt subterfuge in a region nearly caused a minor accident.', ARRAY[]::TEXT[]),
('Subtlety', '/ˈsʌt(ə)lti/', 'noun', 'C1', 'The quality of being subtle.', 'The subtleties of this overture are often overlooked.', ARRAY['artifice','craftiness','cunning','deceitfulness','slyness']::TEXT[]),
('Succinct', '/sə(k)ˈsɪŋkt/', 'adjective', 'C1', 'Brief and to the point', 'Unlike general lossless data compression algorithms, succinct data structures retain the ability to use them in-place, without decompressing them first.', ARRAY['concise','laconic']::TEXT[]),
('Succor', '', 'verb', 'C1', 'To give aid, assistance, or help.', '', ARRAY[]::TEXT[]),
('Suffocate', '/ˈsʌfəkeɪt/', 'adjective', 'C1', 'Suffocated; choked.', '', ARRAY[]::TEXT[]),
('Suffuse', '/səˈfjuːz/', 'adjective', 'C1', 'Suffused; diffuse.', '', ARRAY[]::TEXT[]),
('Sulk', '/sʌlk/', 'verb', 'C1', 'To express ill humor or offence by remaining sullenly silent or withdrawn.', '', ARRAY[]::TEXT[]),
('Summon', '/ˈsʌmən/', 'verb', 'C1', 'To call people together; to convene.', '', ARRAY['muster','muster up','summon up','muster','muster up']::TEXT[]),
('Sumptuous', '/ˈsʌmpt͡ʃuəs/', 'adjective', 'C1', 'Magnificent, luxurious, splendid.', '', ARRAY['lavish']::TEXT[]),
('Sunder', '/ˈsʌndɚ/', 'adjective', 'C1', 'Sundry; separate; different.', '', ARRAY[]::TEXT[]),
('Supercilious', '/ˌsjuː.pə(ɹ)ˈsɪ.li.əs/', 'adjective', 'C2', 'Arrogantly superior; showing contemptuous indifference; haughty.', '', ARRAY[]::TEXT[]),
('Superficial', '/ˌs(j)uːpəˈfɪʃəl/', 'adjective', 'C1', 'Of or pertaining to the surface.', '', ARRAY['surficial']::TEXT[]),
('Superimpose', '', 'verb', 'C1', 'To place an object over another object, usually in such a way that both will be visible.', 'He superimposed the company logo over the image.', ARRAY[]::TEXT[]),
('Supine', '/ˈs(j)uːpaɪn/', 'adjective', 'C1', 'Lying on its back.', '', ARRAY['inclined','sloping','lazy','lethargic','listless']::TEXT[]),
('Supple', '/ˈsʌpəl/', 'adjective', 'C1', 'Pliant, flexible, easy to bend', 'supple joints; supple fingers', ARRAY[]::TEXT[]),
('Supplicate', '/ˈsʌplɪkeɪt/', 'verb', 'C1', 'To humble oneself before (another) in making a request; to beg or beseech.', 'to supplicate blessings on Christian efforts to spread the gospel', ARRAY[]::TEXT[]),
('Supposition', '/ˌsʌpəˈzɪʃən/', 'noun', 'C1', 'Something that is supposed; an assumption made to account for known facts, conjecture.', '', ARRAY[]::TEXT[]),
('Surcharge', '/ˈsɜː(ɹ)t͡ʃɑː(ɹ)d͡ʒ/', 'verb', 'C1', 'To apply a surcharge.', 'to surcharge an animal or a ship; to surcharge a cannon', ARRAY[]::TEXT[]),
('Tangy', '/ˈtæŋiː/', 'adjective', 'C1', 'Having a sharp, pungent flavor', '', ARRAY[]::TEXT[]),
('Tantalize', '/ˈtæntəlaɪz/', 'verb', 'C1', 'To tease (someone) by offering something desirable but keeping it out of reach', '', ARRAY[]::TEXT[]),
('Tantrum', '/ˈtæntɹəm/', 'verb', 'C1', 'To throw a tantrum.', '', ARRAY[]::TEXT[]),
('Taper', '/ˈteɪpə/', 'adjective', 'C1', 'Tapered; narrowing to a point.', '', ARRAY[]::TEXT[]),
('Tardy', '/ˈtɑːdi/', 'adjective', 'C1', 'Late; overdue or delayed.', 'He yawned, then raised a tardy hand over his mouth.', ARRAY['belated','delayed']::TEXT[]),
('Tarpaulin', '/tɑˈpɔː.lɪn/', 'noun', 'C1', 'A tarp, a heavy, waterproof sheet of material, often cloth, used as a cover or blanket.', 'Throw a tarpaulin over that woodpile before it gets wet.', ARRAY[]::TEXT[]),
('Tasty', '/ˈteɪsti/', 'adjective', 'C1', 'Having a pleasant or satisfying flavor; delicious.', 'You could make this tasty meal for breakfast.', ARRAY[]::TEXT[]),
('Taunt', '/tɔːnt/', 'verb', 'C1', 'To make fun of (someone); to goad (a person) into responding, often in an aggressive manner.', '', ARRAY[]::TEXT[]),
('Taut', '/tɔːt/', 'adjective', 'C1', 'Under tension, like a stretched bowstring, rope, or sail; tight.', '', ARRAY['concise','crisp','terse','tight','nonrelaxed']::TEXT[]),
('Taxonomy', '/tækˈsɒnəmi/', 'noun', 'C1', 'The science or the technique used to make a classification.', '', ARRAY['alpha taxonomy','taxonomics']::TEXT[]),
('Tedious', '/ˈtiː.dɪəs/', 'adjective', 'C1', 'Boring, monotonous, time-consuming, wearisome.', '', ARRAY[]::TEXT[]),
('Teeter', '/ˈtiːtə/', 'verb', 'C1', 'To tilt back and forth on an edge.', 'He teetered on the brink of the precipice.', ARRAY[]::TEXT[]),
('Temerity', '/tɛˈmɛɹəti/', 'noun', 'C2', 'Reckless boldness; foolish bravery.', '', ARRAY['audacity','foolhardiness','rashness','recklessness','brashness']::TEXT[]),
('Temporize', '/ˈtɛmpəɹaɪz/', 'verb', 'C1', 'To deliberately act evasively or prolong a discussion in order to gain time or postpone a decision, sometimes in order to reach a compromise or simply to make a conversation more temperate; to stall for time.', '', ARRAY[]::TEXT[]),
('Temperate', '/ˈtɛmpəɹət/', 'adjective', 'C1', 'Moderate; not excessive', 'a temperate climate.', ARRAY[]::TEXT[]),
('Tempestuous', '', 'adjective', 'C2', 'Of, or resembling a tempest; stormy, tumultuous.', '', ARRAY['blustery','stormy','tumultuous','windy']::TEXT[]),
('Tenable', '/ˈtɛn.ə.bəl/', 'adjective', 'C1', '(of a theory, argument, etc.) capable of being maintained or justified; well-founded', 'Back in the 1800s, many did not consider Darwin''''s theory of evolution to be tenable at all.', ARRAY[]::TEXT[]),
('Tendentious', '/tɛnˈdɛnʃəs/', 'adjective', 'C2', 'Having a tendency; written or spoken with a partisan, biased or prejudiced purpose, especially a controversial one.', 'As a supporter of the cause, his reports were tendentious in the extreme.', ARRAY[]::TEXT[]),
('Tenuous', '/ˈtɛn.ju.əs/', 'adjective', 'C1', 'Thin in substance or consistency.', 'Far from being amicable, the numbers seemed to turn their backs on each other, and I couldn''''t find a pair with even the most tenuous connection.', ARRAY['delicate','gossamer','ethereal','delicate','gossamer']::TEXT[]),
('Tepid', '/ˈtɛpɪd/', 'adjective', 'C1', 'Lukewarm; neither warm nor cool.', 'I''''m drinking a cup of tepid water.', ARRAY['lukewarm','lukewarm','uninterested','lukewarm','lukewarm']::TEXT[]),
('Terminology', '/ˌtɜːməˈnɒləd͡ʒi/', 'noun', 'C1', 'The doctrine of terms; a theory of terms or appellations; a treatise on terms, a system of specialized terms.', '', ARRAY['-ese','jargon','language','lingo','nomenclature']::TEXT[]),
('Terminus', '', 'noun', 'C1', 'The end or final point of something.', '', ARRAY[]::TEXT[]),
('Terse', '/tɝːs/', 'adjective', 'C1', '(by extension) Of speech or style: brief, concise, to the point.', '', ARRAY['abrupt','brusque','mardy','short-spoken','concise']::TEXT[]),
('Testator', '/tɛsˈteɪ.tɚ/', 'noun', 'C1', 'One who dies having made a legally valid will.', '', ARRAY[]::TEXT[]),
('Testy', '/ˈtɛsti/', 'adjective', 'C1', 'Easily annoyed, irritable.', 'He made testy remarks.', ARRAY['tetchy','touchy']::TEXT[]),
('Tether', '', 'verb', 'C1', 'To restrict something with a tether.', '', ARRAY[]::TEXT[]),
('Theocracy', '/θiːˈɒkɹəsɪ/', 'noun', 'C1', 'Government under the control of a state-sponsored religion.', 'Tibet was a Buddhist theocracy ruled by the Dalai Lama.', ARRAY[]::TEXT[]),
('Therapeutic', '/θɛɹəˈpjuːtɪk/', 'adjective', 'C1', 'Of, or relating to therapy.', '', ARRAY['curative','remedial','therapeutical']::TEXT[]),
('Thorny', '/ˈθɔːni/', 'adjective', 'C1', 'Having thorns or spines', '', ARRAY[]::TEXT[]),
('Threadbare', '/ˈθɹɛdbɛə(ɹ)/', 'adjective', 'C1', '(of cloth) shabby, frayed and worn to an extent that warp threads show', '', ARRAY[]::TEXT[]),
('Throng', '/θɹɒŋ/', 'adjective', 'C1', 'Filled with persons or objects; crowded.', '', ARRAY[]::TEXT[]),
('Ticklish', '/ˈtɪk(ə)lɪʃ/', 'adjective', 'C1', 'Sensitive or susceptible to being tickled.', 'She is ticklish only on her tummy and the bottoms of her feet.', ARRAY[]::TEXT[]),
('Tiff', '/tɪf/', 'verb', 'C1', 'To quarrel.', '', ARRAY[]::TEXT[]),
('Tightfisted', '', 'adjective', 'C1', 'Reluctant to spend money; miserly or stingy', '', ARRAY['pinchfist']::TEXT[]),
('Timeworn', '/ˈtaɪm.wɔɹn/', 'adjective', 'C1', 'Showing the effects of wear due to long use.', '', ARRAY['shopworn','threadbare','timeworn','well-worn','banal']::TEXT[]),
('Timid', '/ˈtɪmɪd/', 'adjective', 'C1', 'Lacking in courage or confidence.', 'John''''s a very timid person. I''''ll doubt he''''ll be brave enough to face his brother.', ARRAY['fearful','shy','timorous','fearful','shy']::TEXT[]),
('Tinge', '/tɪn(d)ʒ/', 'verb', 'C1', 'To add a small amount of colour; to tint; (by extension) to add a small amount of some other thing.', '', ARRAY['tinct','tinct']::TEXT[]),
('Tinker', '/ˈtɪŋkə(ɹ)/', 'verb', 'C1', 'To fiddle with something in an attempt to fix, mend or improve it, especially in an experimental or unskilled manner.', '', ARRAY[]::TEXT[]),
('Tint', '/tɪnt/', 'verb', 'C1', 'To shade, to color.', '', ARRAY[]::TEXT[]),
('Toady', '', 'verb', 'C1', '(construed with to) To behave like a toady (to someone).', '', ARRAY[]::TEXT[]),
('Tonic', '/ˈtɒnɪk/', 'adjective', 'C1', 'Pertaining to tension, especially of muscles.', 'The arrival of the new members had a tonic effect on the team.', ARRAY[]::TEXT[]),
('Tong', '/tɒŋ/', 'verb', 'C1', 'To use tongs.', '', ARRAY[]::TEXT[]),
('Tonsorial', '', 'adjective', 'C1', 'Relating to barbers or to shaving.', '', ARRAY[]::TEXT[]),
('Topsy-turvy', '', 'adjective', 'C1', 'Backwards or upside-down.', '', ARRAY[]::TEXT[]),
('Topsoil', '', 'noun', 'C1', 'The most fertile soil, easiest to start new plants in.', 'Little grew on the farm, after the floods from the hurricane washed away the topsoil.', ARRAY[]::TEXT[]),
('Tornado', '/tɔː(ɹ)ˈneɪ.dəʊ/', 'noun', 'C1', 'A violent windstorm characterized by a mobile, twisting, funnel-shaped cloud.', 'A tornado is a rotating column of air.', ARRAY['twister','twister','whirling void','twister']::TEXT[]),
('Torque', '/tɔːk/', 'verb', 'C1', 'To twist or turn something.', '', ARRAY[]::TEXT[]),
('Torpid', '', 'adjective', 'C1', 'Dormant or hibernating', '', ARRAY['latent','quiescent','lethargic','motionless','stock-still']::TEXT[]),
('Torrid', '/ˈtɒɹɪd/', 'adjective', 'C1', 'Very hot and dry.', 'a torrid love scene in a film or novel', ARRAY[]::TEXT[]),
('Torrential', '/tɒɹˈɛn.tʃəl/', 'adjective', 'C1', 'Coming or characterized by torrents; flowing heavily or in large quantities.', 'There was a torrential downpour and we were all soaked.', ARRAY[]::TEXT[]),
('Tourniquet', '/ˈtɔː.nɪ.keɪ/', 'noun', 'C1', 'A tightly-compressed bandage used to stop bleeding by stopping the flow of blood through a large artery in a limb.', '', ARRAY[]::TEXT[]),
('Tranquility', '', 'noun', 'C1', 'The state of being tranquil', '', ARRAY[]::TEXT[]),
('Transcend', '/tɹæn(t)ˈsɛnd/', 'verb', 'C1', 'To pass beyond the limits of something.', 'lights in the heavens transcending the region of the clouds', ARRAY['ascend','exceed','overgo','surpass','better']::TEXT[]),
('Transfigure', '', 'verb', 'C1', 'To transform the outward appearance of; to convert into a different form, state or substance.', '', ARRAY[]::TEXT[]),
('Transgress', '/tɹænzˈɡɹɛs/', 'verb', 'C1', 'To exceed or overstep some limit or boundary.', '', ARRAY['forpass','surpass','transcend']::TEXT[]),
('Translucent', '/tɹænzˈluː.sənt/', 'adjective', 'C1', 'Allowing light to pass through, but diffusing it.', '', ARRAY[]::TEXT[]),
('Traverse', '/tɹəˈvɜːs/', 'adjective', 'C1', 'Lying across; being in a direction across something else.', 'paths cut with traverse trenches', ARRAY[]::TEXT[]),
('Treasurer', '/ˈtɹɛʒəɹə(ɹ)/', 'noun', 'C1', 'The government official in charge of the Treasury.', '', ARRAY[]::TEXT[]),
('Trenchant', '/ˈtɹɛnʃənt/', 'adjective', 'C2', 'Fitted to trench or cut; gutting; sharp.', 'trenchant wit', ARRAY[]::TEXT[]),
('Understate', '', 'verb', 'C1', 'To state (something) with less completeness than needed; to minimise or downplay.', '', ARRAY['trivialize']::TEXT[]),
('Understated', '', 'adjective', 'C1', 'Restrained and unpretentious.', '', ARRAY[]::TEXT[]),
('Unexceptionable', '', 'adjective', 'C1', 'Beyond reproach; unimpeachable', '', ARRAY[]::TEXT[]),
('Unflappable', '/ʌnˈflæpəbəl/', 'adjective', 'C2', 'Remaining composed and level-headed at all times; impossible to fluster; not becoming frustrated or irritated easily.', '', ARRAY['collected','cool','even-keeled','collected','cool']::TEXT[]),
('Ungainly', '/ʌnˈɡeɪnli/', 'adjective', 'C1', 'Clumsy; lacking grace.', '', ARRAY[]::TEXT[]),
('Unimpeachable', '', 'adjective', 'C2', 'Not able to be impeached or reproached.', 'a gentleman of unimpeachable integrity', ARRAY[]::TEXT[]),
('Unkempt', '/ˌʌnˈkɛmpt/', 'adjective', 'C1', '(of hair) Uncombed; dishevelled.', '', ARRAY['dishevelled','slovenly']::TEXT[]),
('Unlettered', '', 'adjective', 'C1', 'Not instructed in letters; not well educated; unable to read', '', ARRAY[]::TEXT[]),
('Unpretentious', '/ˌʌnpɹəˈtɛnʃəs/', 'adjective', 'C1', 'Simple, humble, not pretentious, plain.', '', ARRAY[]::TEXT[]),
('Unproductive', '', 'adjective', 'C1', 'Not productive; useless; fruitless.', 'Juggling is an amusing pastime, but generally unproductive.', ARRAY['nonproductive','unyieldly']::TEXT[]),
('Unrequited', '', 'adjective', 'C1', 'Unanswered; not returned; not reciprocated; not repaid.', '', ARRAY[]::TEXT[]),
('Untenable', '', 'adjective', 'C2', 'Not able to be held, as of an opinion or position; unholdable, indefensible.', 'The theory of cold fusion was untenable.', ARRAY[]::TEXT[]),
('Untold', '/ʌnˈtoʊld/', 'adjective', 'C1', 'Not told; not related; not revealed; secret.', '', ARRAY[]::TEXT[]),
('Untoward', '/ˌʌn.tʊˈwɔːd/', 'adjective', 'C2', 'Unfavourable, adverse, or disadvantageous.', '', ARRAY['adverse','disadvantageous','inconvenient','unfavorable','unfortunate']::TEXT[]),
('Unwitting', '', 'adjective', 'C1', 'Unaware or uninformed; oblivious', '', ARRAY['clueless','ignorant','inadvertent','unintended','clueless']::TEXT[]),
('Unwonted', '', 'adjective', 'C1', 'Not customary or habitual; unusual; infrequent; strange.', '', ARRAY[]::TEXT[]),
('Usurp', '/juːˈzɜːp/', 'verb', 'C1', 'To seize power from another, usually by illegitimate means.', '', ARRAY[]::TEXT[]),
('Usury', '/ˈjuːʒəɹi/', 'noun', 'C1', 'An exorbitant rate of interest, in excess of any legal rates or at least immorally.', '', ARRAY['oker']::TEXT[]),
('Utter', '/ˈʌtə/', 'adjective', 'C1', 'Outer; furthest out, most remote.', 'utter ruin; utter darkness', ARRAY[]::TEXT[]),
('Vaccinate', '/ˈvæksɪneɪt/', 'verb', 'C1', 'Treat with a vaccine to produce immunity against a disease.', '', ARRAY[]::TEXT[]),
('Vagary', '/vəˈɡɛɹi/', 'noun', 'C1', 'An erratic, unpredictable occurrence or action.', '', ARRAY[]::TEXT[]),
('Valediction', '/ˌvæl.əˈdɪk.ʃən/', 'noun', 'C1', 'A speech made when leaving or parting company.', '', ARRAY[]::TEXT[]),
('Valiant', '/ˈvæljənt/', 'adjective', 'C1', 'Showing courage or determination; brave, heroic.', '', ARRAY['orped','valorous']::TEXT[]),
('Vapid', '/ˈveɪp.ɪd/', 'adjective', 'C1', 'Offering nothing that is stimulating or challenging.', '', ARRAY[]::TEXT[]),
('Vaporize', '', 'verb', 'C1', 'To turn into vapor.', '', ARRAY[]::TEXT[]),
('Varnish', '/ˈvɑː(ɹ)nɪʃ/', 'verb', 'C1', 'To apply varnish.', '', ARRAY[]::TEXT[]),
('Vault', '/vɒlt/', 'verb', 'C1', 'To build as, or cover with a vault.', '', ARRAY[]::TEXT[]),
('Vaunt', '/vɑːnt/', 'verb', 'C1', 'To speak boastfully.', '', ARRAY['boast','brag']::TEXT[]),
('Veer', '/vɪə/', 'verb', 'C1', 'To let out (a sail-line), to allow (a sheet) to run out.', '', ARRAY[]::TEXT[]),
('Venal', '/ˈviːnəl/', 'adjective', 'C1', 'Venous; pertaining to veins.', '', ARRAY[]::TEXT[]),
('Vendor', '/ˈvɛn.də/', 'verb', 'C1', 'To bundle third-party dependencies with the source code for one''''s own program.', 'I distributed my application with a vendored copy of Perl so that it wouldn''''t use the system copies of Perl where it is installed.', ARRAY[]::TEXT[]),
('Venial', '/ˈviːni.əl/', 'adjective', 'C2', 'Pardonable; able to be forgiven.', 'a venial sin', ARRAY[]::TEXT[]),
('Venom', '/ˈvɛnəm/', 'adjective', 'C1', 'Poisonous, poisoned; (figuratively) pernicious.', '', ARRAY[]::TEXT[]),
('Verbatim', '/vɜːˈbeɪ.tɪm/', 'adjective', 'C1', '(of a document) Corresponding with the original word for word.', 'Date unknown: Joint Committee on Printing Congress of the United States, General Statement of Procedure for Verbatim Reporting of Proceedings in Senate Chamber, page five:', ARRAY['to the letter','word for word']::TEXT[]),
('Verbose', '/vəˈbəʊs/', 'adjective', 'C1', 'Abounding in words, containing more words than necessary; long-winded.', '', ARRAY[]::TEXT[]),
('Verdant', '/ˈvɝ.dənt/', 'adjective', 'C1', 'Green in colour.', 'a verdant youth from the interior of Connecticut', ARRAY[]::TEXT[]),
('Veritable', '/ˈvɛ.ɹɪ.tə.bl/', 'adjective', 'C2', 'True; genuine.', 'He is a veritable genius.', ARRAY[]::TEXT[]),
('Vernacular', '/vəˈnækjələ/', 'adjective', 'C1', 'Of or pertaining to everyday language, as opposed to standard, literary, liturgical, or scientific idiom.', 'a vernacular disease', ARRAY['folk','colloquial','common','everyday','indigenous']::TEXT[]),
('Versatile', '/ˈvɝsətl̩/', 'adjective', 'C1', 'Capable of doing many things competently.', '2004, "queenchaser1158", Horny Versatile TV/TS Wanted in Phoenix (on newsgroup alt.personals.gay)', ARRAY[]::TEXT[]),
('Vertigo', '/ˈvɜːtɪɡəʊ/', 'noun', 'C1', 'A sensation of whirling and loss of balance, caused by looking down from a great height or by disease affecting the inner ear.', '', ARRAY['dizziness','giddiness']::TEXT[]),
('Verve', '/vɜː(r)v/', 'noun', 'C1', 'Excitement of imagination such as that which animates a poet, artist, or musician, in composing or performing', '', ARRAY[]::TEXT[]),
('Vestige', '/ˈvɛ.stɪd͡ʒ/', 'noun', 'C1', 'The mark of the foot left on the earth.', 'the vestiges of ancient magnificence in Palmyra', ARRAY['footstep','sign','trace','track','remains']::TEXT[]),
('Vestigial', '/vɛˈstɪdʒəl/', 'adjective', 'C1', 'Of or pertaining to a vestige or remnant; like a trace from the past.', '', ARRAY[]::TEXT[]),
('Veto', '/ˈviːtəʊ/', 'verb', 'C1', 'To use a veto against.', '', ARRAY[]::TEXT[]),
('Vex', '/vɛks/', 'verb', 'C1', 'To trouble aggressively, to harass.', '', ARRAY['agitate','irk','irritate','afflict','grame']::TEXT[]),
('Vicissitude', '[vaɪˈsɪs.ɨˌt(j)u(ː)d]', 'noun', 'C2', 'Regular change or succession from one thing to another, or one part of a cycle to the next; alternation; mutual succession; interchange.', '', ARRAY['ups and downs','ups and downs']::TEXT[]),
('Victimize', '/ˈvɪktɪmaɪz/', 'verb', 'C1', 'To make someone a victim or sacrifice.', '', ARRAY[]::TEXT[]),
('Vigilant', '/ˈvɪdʒɪlənt/', 'adjective', 'C1', 'Watchful, especially for danger or disorder; alert; wary', 'Be vigilant for signs of disease in your garden.', ARRAY['alert','aware','circumspect','observant','on the qui vive']::TEXT[]),
('Vignette', '/vɪnˈjɛt/', 'verb', 'C1', 'To make, as an engraving or a photograph, with a border or edge gradually fading away.', '', ARRAY[]::TEXT[]),
('Vigorous', '/ˈvɪɡəɹəs/', 'adjective', 'C1', 'Physically strong and active.', 'a vigorous shrub', ARRAY[]::TEXT[]),
('Vim', '/vɪm/', 'noun', 'C1', 'Ready vitality and vigour.', '', ARRAY['energy','go','pep','pizzazz','verve']::TEXT[]),
('Virtuoso', '/ˌvɜ.tʃuˈəʊ.səʊ/', 'adjective', 'C1', 'Exhibiting the ability of a virtuoso.', '', ARRAY[]::TEXT[]),
('Virtuous', '/ˈvɜːt͡ʃʊəs/', 'adjective', 'C1', 'Full of virtue, having excellent moral character.', 'Successful communities need strong, selfless leaders and a virtuous people.', ARRAY['good','righteous']::TEXT[]),
('Virulent', '/ˈvɪɹjʊlənt/', 'adjective', 'C1', '(of a disease or disease-causing agent) Highly infectious, malignant or deadly.', 'The politicians were virulent in their hatred of the president.', ARRAY[]::TEXT[]),
('Viscid', '', 'adjective', 'C1', 'Viscous; having a high viscosity.', '', ARRAY['viscous']::TEXT[]),
('Viscous', '/ˈvɪs.kəs/', 'adjective', 'C1', 'Having a thick, sticky consistency between solid and liquid.', '', ARRAY['syrupy','thickflowing','viscid','viscose']::TEXT[]),
('Visionary', '/ˈvɪʒn̩(ə)ɹi/', 'adjective', 'C1', 'Having vision or foresight', 'a visionary scheme or project', ARRAY[]::TEXT[]),
('Vitality', '/vaɪˈtæləti/', 'noun', 'C1', 'The capacity to live and develop.', '', ARRAY[]::TEXT[]),
('Vitiate', '/ˈvɪʃ.i.eɪt/', 'verb', 'C1', 'To spoil, make faulty; to reduce the value, quality, or effectiveness of something', '', ARRAY[]::TEXT[]),
('Vitrify', '/ˈvɪ.tɹɪ.faɪ/', 'verb', 'C1', 'To convert into, or cause to resemble, glass or a glassy substance, by heat and fusion.', '', ARRAY['glassify']::TEXT[]),
('Vitriolic', '/vɪtɹɪˈɒlɪk/', 'adjective', 'C2', 'Of or pertaining to vitriol; derived from or resembling vitriol.', 'a vitriolic taste', ARRAY['vitriolous','vitriolous']::TEXT[]),
('Vituperate', '/vaɪˈtjuːpəɹeɪt/', 'verb', 'C2', 'To criticize in a harsh or abusive manner.', '', ARRAY['berate','rile','scold','rail']::TEXT[]),
('Vivacious', '/vaɪˈveɪʃəs/', 'adjective', 'C1', 'Lively and animated; full of life and energy.', '', ARRAY['animated','bubbly','ebullient','exciting','high-spirited']::TEXT[]),
('Volatile', '/ˈvɒl.əˌtaɪ.(ə)l/', 'adjective', 'C1', 'Evaporating or vaporizing readily under normal conditions.', '', ARRAY[]::TEXT[]),
('Volition', '/vəˈlɪʃ(ə)n/', 'noun', 'C1', 'A conscious choice or decision.', 'Out of all the factors that can influence a person’s decision, none can match the power of his or her own volition.', ARRAY[]::TEXT[]),
('Voluble', '/ˈvɒl.jʊ.bəl/', 'adjective', 'C1', '(of a person or a manner of speaking) Fluent or having a ready flow of speech; garrulous or loquacious; tonguey.', '', ARRAY['steady']::TEXT[]),
('Voluminous', '/vəˈl(j)uː.mɪ.nəs/', 'adjective', 'C1', 'Of or pertaining to volume or volumes.', 'a voluminous writer', ARRAY['copious','diffuse','copious','diffuse']::TEXT[]),
('Voluptuous', '/vəˈlʌp.tʃu.əs/', 'adjective', 'C1', 'Suggestive of or characterized by full, generous, pleasurable sensation.', 'The plentiful blankets and the voluptuous pillows of the bed called out to my tired body.', ARRAY['luxurious']::TEXT[]),
('Votary', '', 'adjective', 'C1', 'Consecrated by a vow or promise; consequent on a vow; devoted; promised.', '', ARRAY[]::TEXT[]),
('Vouch', '/ˈvaʊtʃ/', 'verb', 'C1', 'To take responsibility for; to express confidence in; to witness; to obtest.', 'I can vouch that the match took place.', ARRAY['affirm','attest','avouch','affirm','attest']::TEXT[]),
('Vulgar', '/ˈvʌl.ɡə/', 'adjective', 'C1', 'Debased, uncouth, distasteful, obscene.', 'The construction worker made a vulgar suggestion to the girls walking down the street.', ARRAY['debased','ignoble','inappropriate','mean','obscene']::TEXT[]),
('Waddle', '/ˈwɒd.əl/', 'verb', 'C1', 'To walk with short steps, tilting the body from side to side.', '', ARRAY[]::TEXT[]),
('Waffle', '/ˈwɒ.fl/', 'noun', 'C1', 'A flat pastry pressed with a grid pattern.', 'The brunch was waffles with strawberries and whipped cream.', ARRAY[]::TEXT[]),
('Waft', '/wæft/', 'verb', 'C1', 'To (cause to) float easily or gently through the air.', 'A breeze came in through the open window and wafted her sensuous perfume into my eager nostrils.', ARRAY[]::TEXT[]),
('Wag', '/wæɡ/', 'verb', 'C1', 'To swing from side to side, such as of an animal''''s tail, or someone''''s head, to express disagreement or disbelief.', '', ARRAY[]::TEXT[]),
('Wan', '/wɒn/', 'adjective', 'C1', 'Pale, sickly-looking.', 'A wan expression', ARRAY[]::TEXT[]),
('Wanderlust', '/ˈvændəˌlʊst/', 'verb', 'C1', 'To feel a strong impulse or longing to travel.', '', ARRAY[]::TEXT[]),
('Wane', '/weɪn/', 'verb', 'C1', 'To progressively lose its splendor, value, ardor, power, intensity etc.; to decline.', '', ARRAY[]::TEXT[]),
('Wardrobe', '/ ˈwɔːdɹəʊb/', 'verb', 'C1', 'To act as a wardrobe department, to provide clothing or sets of clothes.', '', ARRAY[]::TEXT[]),
('Warmonger', '/ˈwɔː.mʌŋ.ɡə(ɹ)/', 'verb', 'C1', 'To advocate war.', '', ARRAY[]::TEXT[]),
('Warp', '/woːp/', 'noun', 'C1', 'The state, quality, or condition of being twisted, physically or mentally:', 'a warp of fish', ARRAY[]::TEXT[]),
('Wary', '/ˈwɛəɹ.i/', 'adjective', 'C1', 'Cautious of danger; carefully watching and guarding against deception, trickery, and dangers; suspiciously prudent', 'He is wary of dogs.', ARRAY['careful','cautious','chary','guarded','careful']::TEXT[]),
('Wastrel', '', 'noun', 'C1', 'One who is profligate, who wastes time or resources extravagantly.', '', ARRAY[]::TEXT[]),
('Watershed', '/ˈwɔːtəʃɛd/', 'adjective', 'C1', 'Serving to mark a significant development, change in direction, etc.', '', ARRAY[]::TEXT[]),
('Waylay', '/ˈweɪleɪ/', 'verb', 'C1', 'To lie in wait for and attack from ambush.', '', ARRAY['ambush','lurk','buttonhole','ambush','lurk']::TEXT[]),
('Welter', '/ˈwɛltə/', 'verb', 'C1', 'To roll around; to wallow.', '', ARRAY[]::TEXT[]),
('Wheedle', '/ˈwiː.dəl/', 'verb', 'C1', 'To cajole or attempt to persuade by flattery.', 'I''''d like one of those, too, if you can wheedle him into telling you where he got it.', ARRAY[]::TEXT[]),
('Whet', '/ˈwɛt/', 'verb', 'C1', 'To hone or rub on with some substance, as a piece of stone, for the purpose of sharpening – see whetstone.', 'to whet one''''s appetite or one''''s courage', ARRAY[]::TEXT[]),
('Whiff', '', 'adjective', 'C1', 'Having a strong or unpleasant odor.', '', ARRAY[]::TEXT[]),
('Wholesome', '/ˈhoʊlsəm/', 'adjective', 'C1', 'Promoting good physical health and well-being.', '', ARRAY['healthful','healthy','salubrious']::TEXT[]),
('Wickedness', '/ˈwɪkɪdnəs/', 'noun', 'C1', 'The state of being wicked; evil disposition; immorality.', '', ARRAY[]::TEXT[]),
('Wince', '/wɪns/', 'verb', 'C1', 'To flinch as if in pain or distress.', 'A horse winces.', ARRAY[]::TEXT[]),
('Windbag', '/ˈwɪndˌbæɡ/', 'noun', 'C1', 'Bellows for an organ.', '', ARRAY['bag of wind','bloviator','gasbag']::TEXT[]),
('Windy', '/ˈwɪndi/', 'adjective', 'C1', 'Accompanied by wind.', 'It was a long and windy night.', ARRAY['blowy','blustery','breezy']::TEXT[]),
('Wither', '/ˈwɪðə/', 'verb', 'C1', 'To shrivel, droop or dry up, especially from lack of water.', '', ARRAY[]::TEXT[]),
('Withhold', '/wɪðˈhəʊld/', 'verb', 'C1', 'To keep (a physical object that one has obtained) to oneself rather than giving it back to its owner.', '', ARRAY['retain']::TEXT[]),
('Wizen', '/ˈwɪzən/', 'adjective', 'C1', 'Wizened; withered; lean and wrinkled by shrinkage as from age or illness.', '', ARRAY[]::TEXT[]),
('Wobble', '/ˈwɒbl̩/', 'verb', 'C1', 'To move with an uneven or rocking motion, or unsteadily to and fro.', 'the Earth wobbles slowly on its axis; the jelly wobbled on the plate', ARRAY['falter','vacillate','waffle','waver','jiggle']::TEXT[]),
('Worldly', '/ˈwɜː(ɹ)ldli/', 'adjective', 'C1', 'Concerned with human or earthly matters, physical as opposed to spiritual.', '', ARRAY['lay','profane','material','mundane','sublunar']::TEXT[]),
('Wrangler', '', 'noun', 'C1', 'Someone who wrangles or corrals.', '', ARRAY[]::TEXT[]),
('Wretched', '/ˈɹɛtʃɪd/', 'adjective', 'C1', 'Very miserable; feeling deep affliction or distress.', 'I felt wretched after my wife died.', ARRAY[]::TEXT[]),
('Benighted', '/bɪˈnaɪtɪd/', 'adjective', 'C2', 'Overtaken by night; especially of a traveller, etc.: caught out by oncoming night before reaching one''''s destination.', '', ARRAY[]::TEXT[]),
('Bereft', '/bəˈɹɛft/', 'adjective', 'C2', '(of a person) Pained by the loss of someone.', '', ARRAY[]::TEXT[]),
('Besotted', '', 'adjective', 'C2', 'Intellectually or morally blinded', '', ARRAY['smitten']::TEXT[]),
('Bilious', '/ˈbɪl.i.əs/', 'adjective', 'C2', 'Of or pertaining to something containing or consisting of bile.', '', ARRAY[]::TEXT[]),
('Blinkered', '', 'adjective', 'C2', 'Wearing blinkers or blinders.', '', ARRAY[]::TEXT[]),
('Bowdlerize', '/ˈbaʊd.lə.ˌɹaɪz/', 'verb', 'C2', 'To remove or alter those parts of a text considered offensive, vulgar, or otherwise unseemly.', 'The bowdlerized version of the novel, while free of vulgarity, was also free of flavor.', ARRAY[]::TEXT[]),
('Broadside', '', 'verb', 'C2', 'To collide with something sideways on', '', ARRAY[]::TEXT[]),
('Cataclysm', '/ˈkætəˌklɪzm̩/', 'noun', 'C2', 'A sudden, violent event.', '', ARRAY[]::TEXT[]),
('Celerity', '/sɪˈlɛɹɪti/', 'noun', 'C2', 'Speed, swiftness.', '', ARRAY[]::TEXT[]),
('Chauvinism', '/ˈʃəʊ.və.nɪ.zəm/', 'noun', 'C2', 'Excessive patriotism, eagerness for national superiority; jingoism.', 'Feminists say that male chauvinism is still prevalent in cultures worldwide.', ARRAY['jingoism']::TEXT[]),
('Chimera', '/kɪ-/', 'noun', 'C2', 'Alternative letter-case form of Chimera (a flame-spewing monster often represented as having two heads, one of a goat and the other of a lion; the body of a goat; and a serpent as a tail).', 'The car which he built himself was a real chimera: half Volkswagen and half Porsche.', ARRAY['motley crew','ghost shark','rabbitfish','ratfish']::TEXT[]),
('Churlish', '/ˈtʃɜːlɪʃ/', 'adjective', 'C2', 'Of or pertaining to a serf, peasant, or rustic.', '', ARRAY['cross-grained','rude','surly','ungracious','grudging']::TEXT[]),
('Complaisant', '/kəmˈpleɪsənt/', 'adjective', 'C2', 'Willing to do what pleases others; obliging.', '', ARRAY[]::TEXT[]),
('Complicit', '/kəmˈplɪs.ɪt/', 'adjective', 'C2', 'Associated with or participating in an activity, especially one of a questionable nature.', '', ARRAY['complicitous']::TEXT[]),
('Concomitant', '/kənˈkɒmɪtənt/', 'adjective', 'C2', 'Accompanying; conjoining; attending; concurrent.', '', ARRAY['accompanying','adjoining','attendant','incidental','accompanying']::TEXT[]),
('Conflagration', '/ˌkɒnfləˈɡɹeɪʃən/', 'noun', 'C2', 'A large fire extending to many objects, or over a large space; a general burning.', 'It took sixty firefighters to put out the conflagration.', ARRAY['firestorm','inferno','firestorm','inferno']::TEXT[]),
('Conflate', '/kɒnˈfleɪt/', 'adjective', 'C2', '(biblical criticism) Combining elements from multiple versions of the same text.', '', ARRAY[]::TEXT[]),
('Corollary', '/kɔˈɹoʊˌlɛɹi/', 'adjective', 'C2', 'Occurring as a natural consequence or result; attendant; consequential.', '', ARRAY[]::TEXT[]),
('Cosseted', '', 'verb', 'C2', 'To treat like a pet; to overly indulge.', 'The car cossets its occupants in comfort.', ARRAY['grope','touch up','coddle','posset']::TEXT[]),
('Coterminous', '/kɒnˈtəː.mɪ.nəs/', 'adjective', 'C2', 'Meeting end to end or at the ends.', 'New York''''s borough of Brooklyn and Kings County are conterminous.', ARRAY[]::TEXT[]),
('Crystallize', '/ˈkɹɪstəlaɪz/', 'verb', 'C2', 'To make something form into crystals', 'I crystallized the copper sulphate by slowly cooling a saturated solution.', ARRAY[]::TEXT[]),
('Cupidity', '/kjuːˈpɪdəti/', 'noun', 'C2', 'Extreme greed, especially for wealth.', '', ARRAY['avarice','covetousness']::TEXT[]),
('Debonair', '/dɛbəˈneə(ɹ)/', 'adjective', 'C2', 'Gracious, courteous.', '', ARRAY[]::TEXT[]),
('Decry', '/dɪˈkɹaɪ/', 'verb', 'C2', 'To denounce as harmful.', '', ARRAY[]::TEXT[]),
('Defray', '/dɪˈfɹeɪ/', 'verb', 'C2', 'To spend (money).', '', ARRAY[]::TEXT[]),
('Deign', '/deɪn/', 'verb', 'C2', 'To condescend; to do despite a perceived affront to one''''s dignity.', 'He didn''''t even deign to give us a nod of the head; he thought us that far beneath him.', ARRAY[]::TEXT[]),
('Demonstrative', '/dɪˈmɒnstɹətɪv/', 'adjective', 'C2', 'That serves to demonstrate, show or prove', '', ARRAY[]::TEXT[]),
('Desiccated', '/ˈdɛsɪkeɪtəd/', 'verb', 'C2', 'To remove moisture from; to dry.', '', ARRAY['dehydrate','exiccate','exsiccate','parch','dehydrate']::TEXT[]),
('Desideratum', '/-ˈɹeɪ-/', 'noun', 'C2', 'Something that is wished for, or considered desirable.', '', ARRAY[]::TEXT[]),
('Despot', '/ˈdɛs.pɒt/', 'noun', 'C2', 'A ruler with absolute power; a tyrant.', '', ARRAY[]::TEXT[]),
('Diminutive', '/dəˈmɪn.jə.tɪv/', 'adjective', 'C2', 'Very small.', '', ARRAY['lilliputian','tiny','lilliputian','tiny']::TEXT[]),
('Disingenuous', '/ˌdɪs.ɪn.ˈdʒɛn.ju.əs/', 'adjective', 'C2', 'Not honourable; unworthy of honour', '', ARRAY['uncandid','uncandid']::TEXT[]),
('Dispensation', '/dɪsˌpɛnˈseɪʃən/', 'noun', 'C2', 'The act of dispensing or dealing out; distribution; often used of the distribution of good and evil by God to man, or more generically, of the acts and modes of his administration.', '', ARRAY[]::TEXT[]),
('Dissolution', '/ˌdɪsəˈl(j)uːʃən/', 'noun', 'C2', 'The termination of an organized body or legislative assembly, especially a formal dismissal.', 'He led a life of dissolution, drinking and gambling almost daily.', ARRAY['abolition','dissipation','abolition','dissipation']::TEXT[]),
('Doleful', '/ˈdoʊlfəl/', 'adjective', 'C2', 'Filled with grief, mournful, bringing feelings of sadness.', 'The doleful peal of the bell indicated another funeral was being held.', ARRAY[]::TEXT[]),
('Doughty', '[ˈdʌʊ̯ɾi]', 'adjective', 'C2', 'Bold; brave, courageous.', '', ARRAY['dauntless','fearless','intrepid','resolute','stouthearted']::TEXT[]),
('Effervescent', '/ˌɛfəˈvɛsənt/', 'adjective', 'C2', '(of a liquid) Giving off bubbles; fizzy.', '', ARRAY['bubbly','ebullient','sparkling']::TEXT[]),
('Elegiac', '/ˌɛləˈdʒaɪæk/', 'adjective', 'C2', 'Of or relating to an elegy.', 'the elegiac distich or couplet, consisting of a dactylic hexameter and pentameter', ARRAY[]::TEXT[]),
('Embryonic', '/ˈɛm.bɹi.ɒn.ɪk/', 'adjective', 'C2', 'Of or relating to an embryo.', '', ARRAY['embryonal']::TEXT[]),
('Empiricism', '', 'noun', 'C2', 'A pursuit of knowledge purely through experience, especially by means of observation and sometimes by experimentation.', '', ARRAY['charlatanry','quackery']::TEXT[]),
('Enamor', '/ɪˈnæmə(ɹ)/', 'verb', 'C2', '(mostly in the passive, followed by "of" or "with") To cause to be in love.', '', ARRAY[]::TEXT[]),
('Enjoin', '/ənˈdʒɔɪn/', 'verb', 'C2', 'To lay upon, as an order or command; to give an injunction to; to direct with authority; to order; to charge.', '', ARRAY[]::TEXT[]),
('Enormity', '/ɪˈnɔːmɪti/', 'noun', 'C2', 'Deviation from what is normal or standard; irregularity, abnormality.', 'Not until the war ended and journalists were able to enter Cambodia did the world really become aware of the enormity of Pol Pot’s oppression.', ARRAY['desecration','violation','atrociousness','depravity','immorality']::TEXT[]),
('Enthrall', '', 'verb', 'C2', 'To hold spellbound; to bewitch, charm or captivate.', '', ARRAY['awe','bewitch','captivate','charm','transfix']::TEXT[]),
('Epiphany', '/ɛˈpɪf.ə.ni/', 'noun', 'C2', 'The appearance of Jesus Christ to the Magi on the twelfth day after Christmas.', '', ARRAY['Twelfth Day','Twelfthtide','Twelvetide']::TEXT[]),
('Eponym', '/ˈɛpənɪm/', 'noun', 'C2', 'A real or fictitious person''''s name that has given rise to the name of a particular item.', 'Romulus is the eponym of Rome.', ARRAY['namesake','toponym','namesake','toponym']::TEXT[]),
('Equitable', '/ˈɛk.wɪ.tə.bəl/', 'adjective', 'C2', 'Marked by or having equity.', '', ARRAY[]::TEXT[]),
('Ersatz', '/ˈɛəzæts/', 'adjective', 'C2', 'Made in imitation; artificial, especially of a poor quality', 'Back then, we could only get ersatz coffee.', ARRAY['artificial','faux','gingerbread','imitation','knock off']::TEXT[]),
('Exegesis', '/ɛksɪˈdʒiːsɪs/', 'noun', 'C2', 'An exposition or explanation of a text, especially a religious one.', '', ARRAY[]::TEXT[]),
('Exemplar', '/ɛɡˈzɛm.plə/', 'noun', 'C2', 'Something fit to be imitated; an ideal, a model.', '', ARRAY[]::TEXT[]),
('Expunge', '/ɛks.ˈpʌndʒ/', 'verb', 'C2', 'To erase or strike out.', '', ARRAY[]::TEXT[]),
('Extrapolate', '/ɛkˈstɹæp.əˌleɪt/', 'verb', 'C2', 'To infer by extending known information.', '', ARRAY[]::TEXT[]),
('Factious', '/ˈfækʃəs/', 'adjective', 'C2', 'Of, pertaining to, or caused by factions.', '', ARRAY[]::TEXT[]),
('Factitious', '/fækˈtɪʃəs/', 'adjective', 'C2', 'Created by humans; artificial.', '', ARRAY[]::TEXT[]),
('Fell', '/fɛl/', 'verb', 'C2', 'To make something fall; especially to chop down a tree.', '', ARRAY[]::TEXT[]),
('Firebrand', '/ˈfaɪə.bɹænd/', 'noun', 'C2', 'An argumentative troublemaker or revolutionary; one who agitates against the current situation.', 'The member of the college''''s Communist League was a firebrand who would launch a sit-in or protest march at a moment''''s notice.', ARRAY['radical','revolutionary','troublemaker','radical','revolutionary']::TEXT[]),
('Flippant', '/ˈflɪ.pənt/', 'adjective', 'C2', 'Glib; speaking with ease and rapidity', '', ARRAY[]::TEXT[]),
('Flummox', '/ˈflʌməks/', 'verb', 'C2', 'To confuse; to fluster; to flabbergast.', '', ARRAY[]::TEXT[]),
('Fractious', '/ˈfɹæk.ʃəs/', 'adjective', 'C2', 'Given to troublemaking.', '', ARRAY[]::TEXT[]),
('Gambit', '/ˈɡæmbɪt/', 'verb', 'C2', 'To sacrifice (a pawn or minor piece) to gain an advantage.', '', ARRAY[]::TEXT[]),
('Graft', '/ɡɹæft/', 'verb', 'C2', 'To insert (a graft) in a branch or stem of another tree; to propagate by insertion in another stock; also, to insert a graft upon.', '', ARRAY['affix','attach','put together','unite']::TEXT[]),
('Gumption', '/ˈɡʌmpʃən/', 'noun', 'C2', 'Common sense, initiative, resourcefulness.', '', ARRAY['chutzpah','gumph','guts','spunk','gumph']::TEXT[]),
('Hector', '/ˈhɛktə/', 'verb', 'C2', 'To dominate or intimidate in a blustering way; to bully, to domineer.', '', ARRAY['huff','terrorise','terrorize','terrorise','terrorize']::TEXT[]),
('Hedge', '/hɛdʒ/', 'noun', 'C2', 'A thicket of bushes or other shrubbery, especially one planted as a fence between two portions of land, or to separate the parts of a garden.', 'He trims the hedge once a week.', ARRAY[]::TEXT[]),
('Hobble', '/ˈhɒbəl/', 'verb', 'C2', 'To fetter by tying the legs; to restrict (a horse) with hobbles.', '', ARRAY[]::TEXT[]),
('Illustrious', '/ɪˈlʌs.tɹɪ.əs/', 'adjective', 'C2', 'Admired, distinguished, respected, or well-known, especially due to past achievements or noble qualities.', '', ARRAY[]::TEXT[]),
('Importuned', '', 'verb', 'C2', 'To bother, trouble, irritate.', '', ARRAY[]::TEXT[]),
('Improvident', '/ɪmˈpɹɒvɪdənt/', 'adjective', 'C2', 'Failing to provide for the future; reckless', '', ARRAY['imprudent','myopic','short','thriftless','wasteful']::TEXT[]),
('Impute', '/ɪmˈpjuːt/', 'verb', 'C2', 'To attribute or ascribe (responsibility or fault) to a cause or source.', 'The teacher imputed the student''''s failure to his nervousness.', ARRAY['ascribe','assign','attribute','attribute','charge']::TEXT[]),
('Inanity', '/ɪˈnænɪti/', 'noun', 'C2', 'The property of being inane, of lacking material of interest or satisfaction, emptiness.', 'Working in any bureaucracy means being bedeviled by inanities daily.', ARRAY[]::TEXT[]),
('Inequity', '/ɪnˈɛk.wɨ.ti/', 'noun', 'C2', 'A lack of justice; injustice.', '', ARRAY[]::TEXT[]),
('Insouciance', '/ɪnˈsuːsi.əns/', 'noun', 'C2', 'Carelessness, heedlessness, indifference, or casual unconcern', '', ARRAY[]::TEXT[]),
('Insufferable', '[ɪnˈsʌfɹəbl̩]', 'adjective', 'C2', 'Not sufferable; very difficult or impossible to endure.', '', ARRAY['intolerable','unbearable']::TEXT[]),
('Internecine', '/-sɪn/', 'adjective', 'C2', 'Mutually destructive; most often applied to warfare.', 'Internecine strife in Gaza claimed its most senior victim yesterday.', ARRAY[]::TEXT[]),
('Intimation', '/ˌɪntəˈmeɪʃən/', 'noun', 'C2', 'The act of intimating.', '', ARRAY[]::TEXT[]),
('Inviolable', '/ɪnˈvaɪələbl̩/', 'adjective', 'C2', 'Not violable; not to be infringed.', '', ARRAY['holy','sacred','sacrosanct','invincible','unassailable']::TEXT[]),
('Inviolate', '/ɪnˈvaɪ.ə.lət/', 'adjective', 'C2', 'Not violated; free from violation or hurt of any kind; secure against violation or impairment.', '', ARRAY[]::TEXT[]),
('Irrefutable', '/ˌɪɹɪˈfjuːtəbl/', 'adjective', 'C2', 'Undeniable; unable to be disproved or refuted', '', ARRAY[]::TEXT[]),
('Kowtow', '/ˈkaʊˌtaʊ/', 'verb', 'C2', 'To grovel, act in a very submissive manner.', '', ARRAY[]::TEXT[]),
('Lascivious', '/ləˈsɪvɪəs/', 'adjective', 'C2', 'Wanton; lewd, driven by lust, lustful.', '', ARRAY['lewd','lustful','wanton']::TEXT[]),
('Litany', '/ˈlɪtəni/', 'noun', 'C2', 'A ritual liturgical prayer in which a series of prayers recited by a leader are alternated with responses from the congregation.', '', ARRAY[]::TEXT[]),
('Machinate', '/ˈmækɪneɪt/', 'verb', 'C2', 'To devise a plot or secret plan; to conspire.', '', ARRAY[]::TEXT[]),
('Magisterial', '/madʒɪˈstɪəɹɪəl/', 'adjective', 'C2', 'Befitting the status or skill of a magister or master; authoritative, masterly.', '', ARRAY[]::TEXT[]),
('Malapropism', '/ˈmæləpɹɒpɪzəm/', 'noun', 'C2', 'The blundering use of an absurdly inappropriate word or expression in place of a similar-sounding one.', 'The script employed malapropism to great effect.', ARRAY['catachresis','malaprop']::TEXT[]),
('Malfeasance', '/ˌmælˈfiːzənts/', 'noun', 'C2', 'Wrongdoing.', '', ARRAY['misconduct','wrongdoing']::TEXT[]),
('Malingerer', '/məˈlɪŋɡəɹə/', 'noun', 'C2', 'A person who malingers.', '', ARRAY['goldbrick','one of his majesty''''s bad bargains','pseudopatient','goldbrick','one of his majesty''''s bad bargains']::TEXT[]),
('Maunder', '/ˈmɔːndə/', 'verb', 'C2', 'To speak in a disorganized or desultory manner; to babble or prattle.', '', ARRAY['babble','prattle','ramble','ramble','wander']::TEXT[]),
('Mendicant', '/ˈmɛn.dɪ.kənt/', 'adjective', 'C2', 'Depending on alms for a living.', '', ARRAY[]::TEXT[]),
('Mettlesome', '', 'adjective', 'C2', 'Marked by mettle or bravery; courageous.', '', ARRAY[]::TEXT[]),
('Misattribute', '', 'verb', 'C2', 'To erroneously attribute; to falsely ascribe; used especially of authorship.', '', ARRAY[]::TEXT[]),
('Mulct', '/mʌlkt/', 'verb', 'C2', 'To impose such a fine or penalty.', '', ARRAY[]::TEXT[]),
('Nettlesome', '', 'adjective', 'C2', '(of a person, thing, situation, etc.) Causing irritation, annoyance, or discomfort; bothersome, irksome.', 'My poison ivy rash is very nettlesome.', ARRAY[]::TEXT[]),
('Objurgate', '', 'verb', 'C2', 'To rebuke or scold strongly.', '', ARRAY[]::TEXT[]),
('Overweening', '/əʊvəˈwiːnɪŋ/', 'adjective', 'C2', 'Unduly confident; arrogant', 'She wins one modeling contest in Montana and suddenly she’s overweening.', ARRAY['conceited','presumptuous','conceited','presumptuous']::TEXT[]),
('Palaver', '/pəˈlɑː.və(ɹ)/', 'verb', 'C2', 'To discuss with much talk.', '', ARRAY['jabber','rabbit','yak']::TEXT[]),
('Palimpsest', '/ˈpælɪmpsɛst/', 'verb', 'C2', 'To scrape clean, as in parchment, for reuse.', 'Typically refers to a multi-layered work, e.g.: new ads covering old on a roadside sign.', ARRAY[]::TEXT[]),
('Panacea', '/ˌpæn.əˈsiː.ə/', 'noun', 'C2', 'A remedy believed to cure all disease and prolong life that was originally sought by alchemists; a cure-all.', 'A monorail will be a panacea for our traffic woes.', ARRAY['allheal','woundwort','catholicon','cure-all','elixir']::TEXT[]),
('Parvenu', '/ˈpɑː.və.njuː/', 'adjective', 'C2', 'Being a parvenu; also, like, having the characteristics of, or associated with a parvenu.', '', ARRAY[]::TEXT[]),
('Pecuniary', '/pɪˈkjuːn(jə)ɹi/', 'adjective', 'C2', 'Of, or relating to, money; monetary, financial.', '', ARRAY[]::TEXT[]),
('Penurious', '', 'adjective', 'C2', 'Miserly; excessively cheap.', 'The old man died a penurious wretch; eighty-thousand dollars in the mattress and as many holes in the roof.', ARRAY[]::TEXT[]),
('Percipient', '', 'adjective', 'C2', 'Having the ability to perceive, especially to perceive quickly.', 'Over time children advance from the percipient stage to the perceptive stage, in which they begin to reflect on the significance of events.', ARRAY[]::TEXT[]),
('Picayune', '/ˌpɪ.kəˈjuːn/', 'adjective', 'C2', 'Petty, trivial; of little consequence; small and of little importance.', '', ARRAY['malicious','peevish','petty','petty','picayunish']::TEXT[]),
('Pith', '/pɪθ/', 'verb', 'C2', 'To extract the pith from (a plant stem or tree).', '', ARRAY[]::TEXT[]),
('Plucky', '/ˈplʌki/', 'adjective', 'C2', 'Having or showing pluck, courage or spirit in trying circumstances.', '', ARRAY['brave','feisty','spunky','brave','feisty']::TEXT[]),
('Presentiment', '/prɪˈzen.tɪ.mənt/', 'noun', 'C2', 'A premonition; a feeling that something, often of undesirable nature, is going to happen.', '', ARRAY['boding','foreboding','forefeeling','premonition']::TEXT[]),
('Primacy', '/ˈpɹaɪ.mə.si/', 'noun', 'C2', 'The state or condition of being prime or first, as in time, place, rank, etc.', 'December 25 2016, Amruta Patil writing in The Hindu, The book in my hand', ARRAY[]::TEXT[]),
('Prognostication', '', 'noun', 'C2', 'A statement about or prior knowledge of the future.', '', ARRAY[]::TEXT[]),
('Puissant', '/ˈpjuːɪs(ə)nt/', 'adjective', 'C2', 'Powerful, mighty, having authority.', '', ARRAY[]::TEXT[]),
('Pyrrhic', '/ˈpɪɹ.ɪk/', 'adjective', 'C2', 'Of or relating to Pyrrhus (319/318–272 BC), Greek general and statesman.', 'The Pyrrhic army lost the Pyrrhic war.', ARRAY[]::TEXT[]),
('Quisling', '/ˈkwɪz.lɪŋ/', 'noun', 'C2', 'A traitor who collaborates with the enemy.', '', ARRAY['collaborator','rat','traitor']::TEXT[]),
('Raillery', '/ˈɹeɪləɹi/', 'noun', 'C2', 'Good-natured ridicule, jest or banter.', '', ARRAY[]::TEXT[]),
('Rarefied', '', 'adjective', 'C2', 'Distant from the lives and everyday concerns of ordinary people; esoteric, exclusive, select.', 'Philosophical debates can be quite rarefied.', ARRAY[]::TEXT[]),
('Recapitulation', '/ˌɹiːkəˌpɪtjʊˈleɪʃ(ə)n/', 'noun', 'C2', 'A subsequent brief recitement or enumeration of the major points in a narrative, article, or book.', '', ARRAY['summary']::TEXT[]),
('Recrimination', '/ɹiˌkɹɪməˈneɪʃən/', 'noun', 'C2', 'The act of recriminating.', '', ARRAY[]::TEXT[]),
('Recrudesce', '', 'verb', 'C2', 'To recur, or break out anew after a dormant period.', '', ARRAY['repeat']::TEXT[]),
('Remonstrate', '/ˈɹɛ.mən.stɹeɪt/', 'verb', 'C2', 'To object; to express disapproval (with, against).', '', ARRAY['demur','expostulate']::TEXT[]),
('Reprisal', '/ɹɪˈpɹaɪzəl/', 'noun', 'C2', 'An act of retaliation.', '', ARRAY[]::TEXT[]),
('Sagacious', '/səˈɡeɪʃəs/', 'adjective', 'C2', 'Having or showing keen discernment, sound judgment, and farsightedness; mentally shrewd.', '', ARRAY['frood']::TEXT[]),
('Sangfroid', '/sɑŋˈfɹɑ/', 'noun', 'C2', 'Composure, self-possession or imperturbability especially when in a dangerous situation.', 'He handled the stressful situation with great sangfroid.', ARRAY['aplomb','poise','unflappability','aplomb','poise']::TEXT[]),
('Sardonic', '/saːˈdɔnɪk/', 'adjective', 'C2', 'Scornfully mocking or cynical.', 'He distances himself from people with his nasty, sardonic laughter.', ARRAY[]::TEXT[]),
('Schadenfreude', '/ˈʃɑːdənfɹɔɪdə/', 'noun', 'C2', 'Malicious enjoyment derived from observing someone else''''s misfortune.', '', ARRAY['epicaricacy']::TEXT[]),
('Effacing', '', 'verb', 'C2', 'To erase (as anything impressed or inscribed upon a surface); to render illegible or indiscernible.', 'Do not efface what I''''ve written on the chalkboard.', ARRAY[]::TEXT[]),
('Semblance', '/ˈsɛm.bləns/', 'noun', 'C2', 'Likeness, similarity; the quality of being similar.', '', ARRAY['veneer']::TEXT[]),
('Sententious', '/sɛnˈtɛn.ʃəs/', 'adjective', 'C2', 'Full of meaning.', '', ARRAY['aphoristic','concise','pithy']::TEXT[]),
('Simulacrum', '/ˌsimjəˈleɪkɹəm/', 'noun', 'C2', 'An image or representation.', 'a simulacrum of a New York studio apartment', ARRAY[]::TEXT[]),
('Solecism', '/ˈsɒlɪsɪzəm/', 'noun', 'C2', 'An erroneous or improper usage.', '', ARRAY[]::TEXT[]),
('Solicitude', '/səˈlɪsɪˌt(j)uːd/', 'noun', 'C2', 'The state of being solicitous; uneasiness of mind occasioned by fear of evil or desire for good; anxiety.', '', ARRAY[]::TEXT[]),
('Splenetic', '/spləˈnɛtɪk/', 'adjective', 'C2', 'Bad-tempered, irritable, peevish, spiteful, habitually angry.', '', ARRAY[]::TEXT[]),
('Transmute', '', 'verb', 'C2', 'To change, transform or convert one thing to another, or from one state or form to another.', 'Did the base metals transmute to gold?', ARRAY[]::TEXT[]),
('Umbrage', '/ˈʌm.bɹɪdʒ/', 'verb', 'C2', 'To displease or cause offense.', '', ARRAY[]::TEXT[]),
('Unforthcoming', '', 'adjective', 'C2', 'Not forthcoming; laconic or uncooperative', 'The coach''''s manner was dour and unforthcoming.', ARRAY[]::TEXT[]),
('Unprepossessing', '', 'adjective', 'C2', 'Unimpressive or unremarkable; dull and ordinary; nondescript.', '', ARRAY[]::TEXT[]),
('Unpropitious', '', 'adjective', 'C2', 'Not propitious; unfavourable, untimely', '', ARRAY[]::TEXT[]),
('Unstinting', '/ʌnˈstɪntɪŋ/', 'adjective', 'C2', 'Generous and tireless with one''''s contributions of time, money, etc.', 'We thank her for her unstinting support of our new hospital.', ARRAY[]::TEXT[]),
('Untrammeled', '', 'adjective', 'C2', 'Not limited or restricted; unrestrained; limitless.', '', ARRAY[]::TEXT[]),
('Unviable', '', 'adjective', 'C2', 'Unable to sustain its own life', '', ARRAY[]::TEXT[]),
('Vaunted', '', 'adjective', 'C2', 'Highly or widely praised or boasted about.', '', ARRAY[]::TEXT[]),
('Verisimilitude', '/vɛɹɪsɪˈmɪlɪtjuːd/', 'noun', 'C2', 'The property of seeming true, of resembling reality; resemblance to reality, realism.', '', ARRAY[]::TEXT[]),
('Vitriol', '/ˈvɪ.tɹi.əl/', 'verb', 'C2', 'To subject to bitter verbal abuse.', '', ARRAY[]::TEXT[]),
('Zeitgeist', '/ˈtsaɪtɡaɪst/', 'noun', 'C2', 'The spirit of the age; the taste, outlook, and spirit characteristic of a period.', '', ARRAY['spiritus mundi','temper of the times','tenor of the times','spiritus mundi','temper of the times']::TEXT[])
ON CONFLICT (word) DO NOTHING;
