INSERT INTO words (word, phonetic, pos, level, def_en, ex_en, synonyms) VALUES
('Lug', '/lʌɡ/', 'verb', 'C1', '(sometimes figurative) To haul or drag along (especially something heavy); to carry; to pull.', 'Why do you always lug around so many books?', ARRAY[]::TEXT[]),
('Lugubrious', '/ləˈɡ(j)uːbɹi.əs/', 'adjective', 'C2', 'Gloomy, mournful or dismal, especially to an exaggerated degree.', 'His client’s lugubrious expression tipped off the detective that something lurked beneath her optimistic words.', ARRAY[]::TEXT[]),
('Lull', '/lʌl/', 'verb', 'C1', 'To cause to rest by soothing influences; to compose; to calm', 'The storm lulled.', ARRAY['appease','quiet','soothe','quiet','soothe']::TEXT[]),
('Lullaby', '/ˈlʌləbaɪ/', 'verb', 'C1', 'To sing a lullaby to.', '', ARRAY[]::TEXT[]),
('Lumber', '/ˈlʌm.bə/', 'verb', 'C1', 'To move clumsily and heavily; to move slowly.', 'I got lumbered with that boring woman all afternoon.', ARRAY[]::TEXT[]),
('Lumen', '/ˈluːmən/', 'noun', 'C1', 'In the International System of Units, the derived unit of luminous flux; the light that is emitted in a solid angle of one steradian from a source of one candela. Symbol: lm.', '', ARRAY[]::TEXT[]),
('Luminary', '/ˈluːmɪn(ə)ɹi/', 'noun', 'C1', 'One who is an inspiration to others; one who has achieved success in their chosen field; a leading light.', '', ARRAY['guiding light']::TEXT[]),
('Lurch', '/lɝt͡ʃ/', 'verb', 'C1', 'To make such a sudden, unsteady movement.', '', ARRAY[]::TEXT[]),
('Lurk', '/lɜːk/', 'verb', 'C1', 'To remain concealed in order to ambush.', '', ARRAY[]::TEXT[]),
('Lush', '/lʌʃ/', 'adjective', 'C1', 'Juicy, succulent.', 'That meal was lush! We have to go that restaurant again sometime!', ARRAY['sapful','sappy','sapful','sappy']::TEXT[]),
('Lustrous', '', 'adjective', 'C1', 'Having a glow or lustre.', '', ARRAY[]::TEXT[]),
('Macerate', '', 'verb', 'C1', 'To soften (something) or separate it into pieces by soaking it in a heated or unheated liquid.', '', ARRAY[]::TEXT[]),
('Maculate', '', 'adjective', 'C1', 'Marked with spots or maculae; blotched.', '', ARRAY[]::TEXT[]),
('Maelstrom', '/ˈmeɪlstɹəm/', 'noun', 'C1', 'A large and violent whirlpool.', '', ARRAY[]::TEXT[]),
('Malaise', '/mæˈleɪz/', 'noun', 'C1', 'A feeling of general bodily discomfort, fatigue or unpleasantness, often at the onset of illness.', '', ARRAY['angst','melancholy','weltschmerz','doldrums','ill at ease']::TEXT[]),
('Malcontent', '/ˈmal.kən.tɛnt/', 'adjective', 'C1', 'Dissatisfied with current conditions; disaffected, discontented, rebellious.', '', ARRAY[]::TEXT[]),
('Malicious', '/məˈlɪʃəs/', 'adjective', 'C1', 'Of, pertaining to, or as a result of malice or spite', 'He was sent off for a malicious tackle on Jones.', ARRAY['evil','malevolent']::TEXT[]),
('Malign', '/məˈlaɪn/', 'adjective', 'C1', 'Evil or malignant in disposition, nature, intent or influence.', 'a malign ulcer', ARRAY[]::TEXT[]),
('Malinger', '/məˈlɪŋɡə/', 'verb', 'C1', 'To feign illness, injury, or incapacitation in order to avoid work, obligation, or perilous risk.', 'It is not uncommon on exam days for several students to malinger rather than prepare themselves.', ARRAY[]::TEXT[]),
('Malodor', '/ˌmælˈəʊ.də(ɹ)/', 'noun', 'C1', 'An offensive odor.', '', ARRAY[]::TEXT[]),
('Mangle', '/ˈmæŋ.ɡəl/', 'verb', 'C1', 'To change, mutilate or disfigure by cutting, tearing, rearranging etc.', '', ARRAY[]::TEXT[]),
('Mangy', '/ˈmeɪndʒi/', 'adjective', 'C1', 'Afflicted with mange.', 'We stayed in a really mangy hotel in New York.', ARRAY['decrepit','scruffy','shabby','decrepit','scruffy']::TEXT[]),
('Mania', '/ˈmeɪ.ni.ə/', 'noun', 'C1', 'Violent derangement of mind; madness; insanity.', '', ARRAY[]::TEXT[]),
('Mannered', '', 'adjective', 'C1', '(often in combination) Having manners or (often excessive) mannerisms.', 'His upbringing had led him to act in an overly mannered way.', ARRAY[]::TEXT[]),
('Manumit', '/mænjʊˈmɪt/', 'verb', 'C1', 'To release from slavery, to free.', '', ARRAY['emancipate','liberate']::TEXT[]),
('Mar', '/mɑː(ɹ)/', 'verb', 'C1', 'To spoil; to ruin; to scathe; to damage.', '', ARRAY[]::TEXT[]),
('Marsh', '/mɑː(ɹ)ʃ/', 'noun', 'C1', 'An area of low, wet land, often with tall grass.', '', ARRAY[]::TEXT[]),
('Marsupial', '/mɑː.ˈsuː.pi.əl/', 'adjective', 'C1', 'Of or pertaining to a marsupial.', 'the marsupial bones', ARRAY[]::TEXT[]),
('Martinet', '/mæɹtˈnɛt/', 'noun', 'C2', 'A strict disciplinarian.', '', ARRAY[]::TEXT[]),
('Marvel', '/ˈmɑːvl̩/', 'verb', 'C1', 'To become filled with wonderment or admiration; to be amazed at something.', '', ARRAY[]::TEXT[]),
('Masquerade', '/ˈmæskəˌɹeɪd/', 'verb', 'C1', 'To take part in a masquerade; to assemble in masks and costumes; to wear a disguise.', 'I’m going to masquerade as the wikipede. What are you going to dress up as?', ARRAY[]::TEXT[]),
('Mash', '/mæʃ/', 'noun', 'C1', 'A mass of mixed ingredients reduced to a soft pulpy state by beating or pressure; a mass of anything in a soft pulpy state.', '', ARRAY[]::TEXT[]),
('Masticate', '/ˈmæstɪkeɪt/', 'verb', 'C1', 'To chew (food).', 'The cow stood, quietly masticating its cud.', ARRAY[]::TEXT[]),
('Mastery', '/ˈmɑːst(ə)ɹi/', 'noun', 'C1', 'The position or authority of a master; dominion; command; supremacy; superiority.', '', ARRAY[]::TEXT[]),
('Matriculate', '', 'verb', 'C1', 'To enroll as a member of a body, especially of a college or university', '', ARRAY[]::TEXT[]),
('Mattress', '/ˈmætɹɪs/', 'verb', 'C1', 'To cover with a thick layer, like a mattress; to blanket.', '', ARRAY[]::TEXT[]),
('Maudlin', '/ˈmɔːd.lɪn/', 'adjective', 'C2', 'Affectionate or sentimental in an effusive, tearful, or foolish manner, especially because of drunkenness.', '', ARRAY['mushy','sappy','schmaltzy','slushy','soupy']::TEXT[]),
('Maven', '/ˈmeɪvən/', 'noun', 'C1', 'An expert in a given field.', '', ARRAY[]::TEXT[]),
('Meager', '/ˈmiːɡə/', 'adjective', 'C1', 'Having little flesh; lean; thin.', 'A meager piece of cake in one bite.', ARRAY['inadequate','measly','paltry','scanty','inadequate']::TEXT[]),
('Measly', '/ˈmiːzli/', 'adjective', 'C1', 'Particularly of pigs or pork: infected with larval tapeworms or trichinae (parasitic roundworms).', '', ARRAY['miserable','paltry','trifling','miserable','paltry']::TEXT[]),
('Measured', '/ˈmɛʒəd/', 'adjective', 'C1', 'That has been determined by measurement.', 'He ran over a measured mile.', ARRAY[]::TEXT[]),
('Meddle', '/ˈmɛd.əl/', 'verb', 'C1', 'To interfere in or with; to concern oneself with unduly.', '', ARRAY['do it','get it on','ming','dabble','stick one''''s nose into']::TEXT[]),
('Mediate', '/ˈmidi.ət/', 'adjective', 'C1', 'Acting through a mediating agency, indirect.', '', ARRAY[]::TEXT[]),
('Mediocre', '/ˈmiːdɪˌəʊkə/', 'adjective', 'C1', 'Having no peculiar or outstanding features; not extraordinary, special, exceptional, or great; of medium quality, almost always with a negative connotation.', 'I''''m pretty good at tennis but only mediocre at racquetball.', ARRAY['common','commonplace','ordinary','common','commonplace']::TEXT[]),
('Medley', '/ˈmɛdli/', 'verb', 'C1', 'To combine, to form a medley.', '', ARRAY[]::TEXT[]),
('Meek', '/miːk/', 'adjective', 'C1', 'Humble, non-boastful, modest, meager, or self-effacing.', '', ARRAY[]::TEXT[]),
('Meliorism', '/ˈmiːlɪəɹɪz(ə)m/', 'noun', 'C1', 'The view or doctrine that the world can be improved through human effort (often understood as an intermediate outlook between optimism and pessimism).', '', ARRAY[]::TEXT[]),
('Mellifluous', '/məˈlɪflu.əs/', 'adjective', 'C2', 'Flowing like honey.', '', ARRAY['birdsweet','dulcet','euphonious','sweet-flowing']::TEXT[]),
('Melodrama', '/ˈmɛləˌdɹɑːmə/', 'noun', 'C1', 'A kind of drama having a musical accompaniment to intensify the effect of certain scenes.', 'the melodrama in the grave digging scene of Beethoven''''s "Fidelio".', ARRAY[]::TEXT[]),
('Membrane', '/ˈmembɹeɪn/', 'noun', 'C1', 'A flexible enclosing or separating tissue forming a plane or film and separating two environments (usually in a plant or animal).', '', ARRAY[]::TEXT[]),
('Menace', '/ˈmɛnɪs/', 'noun', 'C1', 'A perceived threat or danger.', '', ARRAY[]::TEXT[]),
('Mendacious', '/mɛnˈdeɪʃəs/', 'adjective', 'C1', '(of a person) Lying, untruthful or dishonest.', '', ARRAY[]::TEXT[]),
('Mercenary', '/ˈmɜː.sə.nə.ɹi/', 'adjective', 'C1', 'Motivated by private gain.', '', ARRAY['hired gun','greedy','venal']::TEXT[]),
('Merited', '', 'verb', 'C1', 'To deserve, to earn.', 'Her performance merited wild applause.', ARRAY[]::TEXT[]),
('Mesh', '/mɛʃ/', 'verb', 'C1', 'To connect together by interlocking, as gears do.', 'The music meshed well with the visuals in that film.', ARRAY[]::TEXT[]),
('Mesmerism', '/ˈmɛzməˌɹɪzəm/', 'noun', 'C1', 'The method or power of gaining control over someone''''s personality or actions, as in hypnosis or suggestion.', '', ARRAY[]::TEXT[]),
('Metaphysics', '/mɛtəˈfɪzɪks/', 'noun', 'C1', 'The field of study of metaphysics.', '', ARRAY[]::TEXT[]),
('Metamorphose', '/ˌmɛtəˈmɔːˌfəʊz/', 'verb', 'C1', '(of a moth or insect) To undergo metamorphosis.', '', ARRAY['metamorphosize']::TEXT[]),
('Meteoric', '', 'adjective', 'C2', 'Of, pertaining to, or originating from a meteor.', 'meteoric iron', ARRAY[]::TEXT[]),
('Meteorology', '/ˌmiːtɪəˈɹɒlədʒi/', 'noun', 'C1', 'The science that deals with the study of the atmosphere and its phenomena, especially with weather and weather forecasting.', '', ARRAY[]::TEXT[]),
('Methodical', '', 'adjective', 'C1', 'In an organized manner; proceeding with regard to method; systematic.', 'the methodical arrangement of arguments; a methodical treatise', ARRAY['systematic']::TEXT[]),
('Metrical', '', 'adjective', 'C1', 'Relating to poetic meter', '', ARRAY[]::TEXT[]),
('Mettle', '/ˈmɛ.təl/', 'noun', 'C1', 'A quality of endurance and courage.', '', ARRAY['courage','heart','spirit']::TEXT[]),
('Miff', '/mɪf/', 'verb', 'C1', '(usually used in the passive) To offend slightly.', '', ARRAY[]::TEXT[]),
('Migratory', '/ˈmaɪ.ɡɹəˌtɔ.ɹi/', 'adjective', 'C1', '(of birds, etc) Migrating.', 'migratory habits; a migratory life', ARRAY[]::TEXT[]),
('Mime', '/maɪm/', 'verb', 'C1', 'To act without words.', '', ARRAY[]::TEXT[]),
('Mimicry', '/ˈmɪm.ɪk.ɹi/', 'noun', 'C1', 'The act or ability to simulate the appearance of someone or something else.', 'They say that mimicry is the sincerest form of flattery, but I still think I''''m being mocked when he acts just like me.', ARRAY[]::TEXT[]),
('Minaret', '/ˈmɪnəɹɛt/', 'noun', 'C1', 'The tall slender tower of an Islamic mosque, from which the muezzin recites the adhan (call to prayer).', '', ARRAY[]::TEXT[]),
('Minatory', '', 'adjective', 'C1', 'Threatening, menacing.', '', ARRAY['minacious','ominous','sinister']::TEXT[]),
('Mince', '/mɪns/', 'verb', 'C1', 'To make less; make small.', 'Butchers often use machines to mince meat.', ARRAY['extenuate','palliate','weaken','extenuate','palliate']::TEXT[]),
('Mingle', '/ˈmɪŋ.ɡəl/', 'verb', 'C1', 'To intermix; to combine or join, as an individual or part, with other parts, but commonly so as to be distinguishable in the product', '', ARRAY['confound','confuse','confound','confuse']::TEXT[]),
('Minion', '/ˈmɪnjən/', 'adjective', 'C1', 'Favoured, beloved; "pet".', '', ARRAY[]::TEXT[]),
('Mint', '/mɪnt/', 'adjective', 'C1', '(with condition) Like new.', 'in mint condition.', ARRAY[]::TEXT[]),
('Minuscule', '/ˈmɪ.nəˌskjuːl/', 'adjective', 'C1', 'Written in minuscules, lowercase.', 'a minuscule dot', ARRAY['microscopic','minute','tiny','lower-case','small']::TEXT[]),
('Minutia', '/maɪˈn(j)uːʃ(iː)ə/', 'noun', 'C1', 'A minor detail, often of negligible importance.', 'They spent all their time on minutiae, never making real progress.', ARRAY[]::TEXT[]),
('Mirage', '/mɪˈɹɑːdʒ/', 'verb', 'C1', 'To cause to appear as or like a mirage.', '', ARRAY[]::TEXT[]),
('Mire', '/ˈmaɪə/', 'verb', 'C1', 'To cause or permit to become stuck in mud; to plunge or fix in mud.', 'to mire a horse or wagon', ARRAY['bemire','bemire','enmire','bemire','enmire']::TEXT[]),
('Mirth', '/mɜːθ/', 'noun', 'C1', 'The emotion usually following humour and accompanied by laughter; merriment; jollity; gaiety.', '', ARRAY['delight','glee','hilarity','jollity']::TEXT[]),
('Misbehave', '', 'verb', 'C1', 'To act or behave in an inappropriate, improper, incorrect, or unexpected manner.', 'He doesn''''t mean to misbehave; he just doesn''''t know better.', ARRAY['carry on','go it']::TEXT[]),
('Mischievous', '/ˈmɪs.t͡ʃə.vəs/', 'adjective', 'C1', 'Causing mischief; injurious.', 'Matthew had a twin brother called Edward, who was always mischievous and badly behaved.', ARRAY['badly-behaved','naughty','destructive','detrimental','harmful']::TEXT[]),
('Misdemeanor', '/ˌmɪsdɪˈmiːnə(ɹ)/', 'noun', 'C1', 'A crime usually punishable upon conviction by a small fine or by a short term of imprisonment. In the USA, misdemeanants usually are incarcerated in county jail for less than one year, but felons usually are incarcerated in state or federal prison for more than one year. Crimes which are punishable by large fines or by longer imprisonment are sometimes called felonies.', '', ARRAY['petty crime']::TEXT[]),
('Misfortune', '/mɪsˈfɔːtʃuːn/', 'noun', 'C1', 'An undesirable event such as an accident', 'It was my fortune, or misfortune, to be called to the office of Chief Executive without any previous political training. - Ulysses S. Grant', ARRAY[]::TEXT[]),
('Misgiving', '', 'noun', 'C1', 'Doubt, apprehension, a feeling of dread', '', ARRAY['doubt']::TEXT[]),
('Mishap', '/ˈmɪs.hæp/', 'verb', 'C1', 'To happen through misfortune; to mishappen.', '', ARRAY[]::TEXT[]),
('Misrepresent', '', 'verb', 'C1', 'To represent falsely; to inaccurately portray something.', 'The fraudster misrepresented himself as a lawyer.', ARRAY[]::TEXT[]),
('Mite', '/maɪt/', 'noun', 'C1', 'Any of many minute arachnids which, along with the ticks, comprise subclass Acarina (aka Acari).', '', ARRAY[]::TEXT[]),
('Mnemonics', '/nəˈmɒn.ɪks/', 'noun', 'C1', 'Anything (especially something in verbal form) used to help remember something.', 'To remember the colours of the rainbow, use the mnemonic "Richard of York gave battle in vain" (red, orange, yellow, green, blue, indigo, violet).', ARRAY['aide-mémoire']::TEXT[]),
('Mockery', '/ˈmɒkəɹi/', 'noun', 'C1', 'The action of mocking; ridicule, derision.', 'The defendant wasn''''t allowed to speak at his own trial - it was a mockery of justice.', ARRAY[]::TEXT[]),
('Modicum', '/ˈmɒdɪkəm/', 'noun', 'C2', 'A modest, small, or trifling amount.', 'Unable to garner even a modicum of support for his plan, he conceded to follow the others.', ARRAY['iota','jot','tittle','iota','jot']::TEXT[]),
('Molar', '/ˈmoʊlɚ/', 'adjective', 'C1', 'Of or relating to the molar teeth, or to grinding.', '', ARRAY[]::TEXT[]),
('Molding', '/ˈməʊl.dɪŋ/', 'verb', 'C1', 'To shape in or on a mold; to form into a particular shape; to give shape to.', 'These shoes gradually molded to my feet.', ARRAY[]::TEXT[]),
('Mollycoddle', '/ˈmɒl.ɪˌkɒd.əl/', 'verb', 'C1', 'To be overprotective and indulgent toward; to pamper.', '', ARRAY[]::TEXT[]),
('Molt', '', 'verb', 'C1', 'To shed or lose a covering of hair or fur, feathers, skin, horns, etc, and replace it with a fresh one.', '', ARRAY['shed','slough','shed','slough']::TEXT[]),
('Momentous', '/məʊˈmɛn.təs/', 'adjective', 'C1', 'Outstanding in importance, of great consequence.', '', ARRAY[]::TEXT[]),
('Mongrel', '/ˈmɒŋ.ɡɹəl/', 'noun', 'C1', 'Someone or something of mixed kind or uncertain origin, especially a dog.', 'That dog is a mongrel; who knows what breed it could be!', ARRAY['Heinz 57','bitsa','bitser','bitzer','cur']::TEXT[]),
('Monochromatic', '', 'adjective', 'C1', 'Having only one color, represented by differing hues and tints. For example shades in a black and white television.', '', ARRAY[]::TEXT[]),
('Monocle', '/ˈmɑnəkəl/', 'noun', 'C1', 'A single lens, usually in a wire frame, and used to correct vision for only one eye.', '', ARRAY[]::TEXT[]),
('Monologue', '', 'verb', 'C1', 'To deliver a monologue.', '', ARRAY['monologize']::TEXT[]),
('Monotonous', '/məˈnɒtənəs/', 'adjective', 'C1', 'Having an unvarying tone or pitch.', '', ARRAY['level','monotone','monotonic','samely']::TEXT[]),
('Montage', '/mɒnˈtɑːʒ/', 'verb', 'C1', 'To combine into, or depict as, a montage.', '', ARRAY[]::TEXT[]),
('Moratorium', '/ˌmɒ.ɹəˈtɔː.ɹɪəm/', 'noun', 'C1', 'An authorization to a debtor, permitting temporary suspension of payments.', 'Canada may put a moratorium on cloning for research.', ARRAY['hiatus','interruption','recess']::TEXT[]),
('Morbid', '/ˈmɔː.bɪd/', 'adjective', 'C1', 'Of, or relating to disease.', '', ARRAY['bloody','disgusting','gory','grisly','gruesome']::TEXT[]),
('Mordant', '/mɔː(ɹ)dənt/', 'adjective', 'C2', 'Having or showing a sharp or critical quality', '', ARRAY['biting','caustic','keen','sarcastic','severe']::TEXT[]),
('Moribund', '/ˈmɔːɹɪbʌnd/', 'adjective', 'C2', 'Approaching death; about to die; dying; expiring.', '', ARRAY[]::TEXT[]),
('Mortar', '/ˈmɔːtə(ɹ)/', 'verb', 'C1', 'To use mortar or plaster to join two things together.', '', ARRAY[]::TEXT[]),
('Mosaic', '/məʊˈzeɪ.ɪk/', 'adjective', 'C1', '(of an individual) Containing cells of varying genetic constitution.', '', ARRAY[]::TEXT[]),
('Moth-eaten', '', 'adjective', 'C1', 'Containing holes by having been eaten by moth larvae.', '', ARRAY[]::TEXT[]),
('Motile', '/ˈməʊtaɪl/', 'adjective', 'C1', 'Having the power to move spontaneously.', 'motile powers', ARRAY[]::TEXT[]),
('Motley', '/ˈmɒtli/', 'adjective', 'C1', 'Comprising greatly varied elements, to the point of incongruity; heterogeneous.', '', ARRAY['diverse','manifold','colorful','prismatic','variegated']::TEXT[]),
('Mottle', '/ˈmɑt əl/', 'verb', 'C1', 'To mark with blotches of different color, or shades of color, as if stained; to spot; to maculate.', '', ARRAY[]::TEXT[]),
('Motto', '/ˈmɒtəʊ/', 'noun', 'C1', 'A sentence, phrase, or word, forming part of an heraldic achievement.', '', ARRAY[]::TEXT[]),
('Mournful', '/ˈmɔːnfəl/', 'adjective', 'C1', 'Filled with grief or sadness; being in a state in which one mourns.', '', ARRAY[]::TEXT[]),
('Muddy', '[ˈmʌdi]', 'adjective', 'C1', 'Covered with or full of mud or wet soil.', 'He slogged across the muddy field.', ARRAY[]::TEXT[]),
('Muffler', '/ˈmʌflɚ/', 'noun', 'C1', 'Part of the exhaust pipe of a car that dampens the noise the engine produces.', '', ARRAY['silencer']::TEXT[]),
('Mulish', '', 'adjective', 'C1', 'Characteristic of a mule; stubborn, obstinate, or intractable', '', ARRAY['stubborn as a mule']::TEXT[]),
('Mumble', '/ˈmʌmbəl/', 'verb', 'C1', 'To speak unintelligibly or inaudibly; to fail to articulate.', 'Please try not to mumble so I can hear you better.', ARRAY[]::TEXT[]),
('Mural', '/ˈmjʊəɹəl/', 'adjective', 'C1', 'Of or relating to a wall; on, or in, or against a wall.', 'a mural quadrant', ARRAY[]::TEXT[]),
('Murky', '', 'adjective', 'C1', 'Hard to see through, as a fog or mist.', '', ARRAY['dark']::TEXT[]),
('Murmur', '/ˈmɜː.mə(ɹ)/', 'verb', 'C1', 'To grumble; to complain in a low, muttering voice, or express discontent at or against someone or something.', 'I couldn''''t hear the words; he just murmured a lot.', ARRAY[]::TEXT[]),
('Musket', '/ˈmʌskət/', 'noun', 'C1', 'A kind of firearm formerly carried by the infantry of an army, originally fired by means of a match, or matchlock, for which several mechanical appliances (including the flintlock, and finally the percussion lock) were successively substituted; ultimately superseded by the rifle.', 'Sam, Sam, pick up thy musket.', ARRAY[]::TEXT[]),
('Mutate', '/mjuːˈteɪt/', 'verb', 'C1', 'To undergo mutation.', '', ARRAY[]::TEXT[]),
('Mute', '/mjuːt/', 'adjective', 'C1', 'Not having the power of speech; dumb.', '', ARRAY[]::TEXT[]),
('Mutter', '/ˈmʌtə/', 'verb', 'C1', 'To utter words, especially complaints or angry expressions, indistinctly or with a low voice and lips partly closed; to say under one''''s breath.', 'The beggar muttered words of thanks, as passersby dropped coins in his cup.', ARRAY['growl','putter','rumble','babble','mumble']::TEXT[]),
('Nadir', '/neɪˈdɪə(ɹ)/', 'verb', 'C2', 'To extend (a beehive) by adding an empty box at the base.', '', ARRAY[]::TEXT[]),
('Naive', '/naɪˈiːv/', 'adjective', 'C1', 'Lacking worldly experience, wisdom, or judgement; unsophisticated.', '', ARRAY[]::TEXT[]),
('Narcissism', '/ˈnɑːsəˌsɪzm/', 'noun', 'C1', 'Excessive love of oneself.', '', ARRAY[]::TEXT[]),
('Nascent', '/ˈneɪ.sənt/', 'adjective', 'C1', 'Emerging; just coming into existence.', '', ARRAY['emergent','emerging','immature','in statu nascendi','inchoate']::TEXT[]),
('Natty', '/ˈnæti/', 'adjective', 'C1', 'Smart and fashionable.', '', ARRAY[]::TEXT[]),
('Nauseate', '', 'verb', 'C1', 'To cause nausea in.', '', ARRAY['disgust','make','sick','offend','repel']::TEXT[]),
('Nautical', '/ˈnɔːtɪkl̩/', 'adjective', 'C1', 'Relating to or involving ships or shipping or navigation or seamen.', 'nautical charts', ARRAY[]::TEXT[]),
('Naysaying', '', 'verb', 'C1', 'To speak negatively of something.', '', ARRAY[]::TEXT[]),
('Nebulous', '/ˈnɛbjʊləs/', 'adjective', 'C1', 'In the form of a cloud or haze; hazy.', '', ARRAY[]::TEXT[]),
('Needy', '/ˈniːdi/', 'adjective', 'C1', 'In need; poor.', 'Needy people want to give too, but have few material goods to offer.', ARRAY[]::TEXT[]),
('Nefarious', '/nɛˈfɛəɹi.əs/', 'adjective', 'C1', 'Sinful, villainous, criminal, or wicked, especially when noteworthy or notorious for such characteristics.', 'Aliens have a nefarious connotation in many science fiction books.', ARRAY['evil','good-for-nothing','iniquitous','sinister','underhanded']::TEXT[]),
('Negation', '/nəˈɡeɪʃən/', 'noun', 'C1', 'The act of negating something.', '', ARRAY[]::TEXT[]),
('Negligence', '', 'noun', 'C1', 'The state of being negligent.', '', ARRAY[]::TEXT[]),
('Neologism', '/niːˈɒlədʒɪzəm/', 'noun', 'C1', 'A word or phrase which has recently been coined; a new word or phrase.', '', ARRAY['coinage','coinage']::TEXT[]),
('Neophyte', '/ˈni.əˌfaɪt/', 'noun', 'C1', 'A beginner; a person who is new to a subject, skill, or belief.', '', ARRAY['beginner','newbie','newcomer','starter','catechumen']::TEXT[]),
('Nepotism', '/ˈnɛp.ə.tɪ.zəm/', 'noun', 'C1', 'The favoring of relatives or personal friends because of their relationship rather than because of their abilities.', 'Nepotism can get you very far in the world if you''''ve got the right connections.', ARRAY[]::TEXT[]),
('Nettle', '/ˈnɛt(ə)l/', 'verb', 'C1', 'Of the nettle plant and similar physical causes, to sting, causing a rash in someone.', 'The children were badly nettled after playing in the field.', ARRAY[]::TEXT[]),
('Neutralize', '', 'verb', 'C1', 'To make even, inactive or ineffective.', 'The antidote neutralised the toxin.', ARRAY['counteract','counterweigh']::TEXT[]),
('Nicety', '/ˈnaɪsɪti/', 'noun', 'C1', 'A small detail or distinction.', 'We met the new captain while we were taking enemy fire and were unable to observe the niceties of formal introductions.', ARRAY[]::TEXT[]),
('Nexus', '/ˈnɛk.suːs/', 'noun', 'C1', 'A form of connection.', '', ARRAY['bond','link','tie','hub','junction']::TEXT[]),
('Nibble', '/ˈnɪbəl/', 'verb', 'C1', 'To eat with small, quick bites.', 'The rabbit nibbled at the lettuce.', ARRAY['piddle']::TEXT[]),
('Nil', '/nɪl/', 'noun', 'C1', 'Nothing; zero.', '', ARRAY[]::TEXT[]),
('Nip', '/nɪp/', 'noun', 'C1', 'A small quantity of something edible or a potable liquor.', 'He had a nip of whiskey.', ARRAY['a little of the creature','nibble','a little of the creature','nibble']::TEXT[]),
('Nitpick', '/ˈnɪt.pɪk/', 'verb', 'C1', 'To correct minutiae or find fault in unimportant details.', 'Someone will invariably nitpick about any spelling error posted to the forums.', ARRAY['cavil','flyspeck','cavil','flyspeck']::TEXT[]),
('Nocturnal', '/nɒkˈtɜː(ɹ)nəl/', 'adjective', 'C1', '(of a person, creature, group, or species) Primarily active during the night.', 'nocturnal birds', ARRAY[]::TEXT[]),
('Noisome', '/ˈnɔɪ.səm/', 'adjective', 'C2', 'Morally hurtful or noxious.', '', ARRAY['fetid','foul','nauseating','sickening','fetid']::TEXT[]),
('Nomad', '/ˈnəʊmæd/', 'adjective', 'C1', 'Of or relating to nomads, whether', '', ARRAY['nomad','ambling','ambulant','ambulatory','discursive']::TEXT[]),
('Nominal', '/ˈnɑm.ɪnl̩/', 'adjective', 'C1', 'Of, resembling, relating to, or consisting of a name or names.', 'a nominal difference', ARRAY['normal','trifling','trifling','normal']::TEXT[]),
('Nonchalant', '/ˈnɒn.ʃəl.ənt/', 'adjective', 'C2', 'Casually calm and relaxed.', 'We handled the whole frenetic situation with a nonchalant attitude.', ARRAY['carefree','cool','easygoing','mellow','blasé']::TEXT[]),
('Nondescript', '/ˈnɒndɪskɹɪpt/', 'adjective', 'C1', 'Not described (in the academic literature).', 'He drove a nondescript silver sedan.', ARRAY['undescribed','unidentified','unexceptional','undescribed','unidentified']::TEXT[]),
('Nonentity', '', 'noun', 'C1', 'An unimportant or insignificant person', '', ARRAY[]::TEXT[]),
('Nonplus', '/nɒnˈplʌs/', 'verb', 'C1', 'To perplex or bewilder someone; to confound or flummox', '', ARRAY[]::TEXT[]),
('Notch', '/nɒtʃ/', 'verb', 'C1', 'To cut a notch in (something).', 'The tribe''''s hunters notch their kills by notches on each''''s axe''''s handle.', ARRAY['notch up','notch up']::TEXT[]),
('Noxious', '/ˈnɒkʃəs/', 'adjective', 'C1', 'Harmful; injurious.', '', ARRAY['harmful','injurious','scathel']::TEXT[]),
('Nucleate', '', 'adjective', 'C1', 'Having a nucleus; nucleated', '', ARRAY[]::TEXT[]),
('Nudge', '/nʌdʒ/', 'verb', 'C1', 'To push against gently, especially in order to gain attention or give a signal.', '', ARRAY[]::TEXT[]),
('Nugatory', '/ˈnjuːɡətɔɹi/', 'adjective', 'C1', 'Trivial, trifling or of little importance.', '', ARRAY[]::TEXT[]),
('Nurture', '/ˈnɜːɹ.tʃəɹ/', 'verb', 'C1', 'To nourish or nurse.', '', ARRAY[]::TEXT[]),
('Oasis', '/əʊˈeɪsəs/', 'noun', 'C1', 'A spring of fresh water, surrounded by a fertile region of vegetation, in a desert.', 'The park was an oasis in the middle of the busy city.', ARRAY['island','refuge']::TEXT[]),
('Oath', '/ˈəʊθ/', 'noun', 'C1', 'A solemn pledge or promise, appealing to a deity, a ruler, or another entity (not necessarily present) to attest to the truth of a statement or sincerity of one''''s desire to fulfill a contract or promise.', 'After taking the oath of office, she became the country''''s forty-third premier.', ARRAY['avowal','pledge','vow']::TEXT[]),
('Obedient', '/əʊˈbiːdɪənt/', 'adjective', 'C1', 'Willing to comply with the commands, orders, or instructions of those in authority.', 'Jessica was so intensely obedient of her parents that her brother sometimes thought she was a robot.', ARRAY['dutiful','hearsome']::TEXT[]),
('Obeisance', '/oʊˈbeɪsəns/', 'noun', 'C1', 'Demonstration of an obedient attitude, especially by bowing deeply; a deep bow which demonstrates such an attitude.', '', ARRAY[]::TEXT[]),
('Obfuscate', '/ˈɒbfəskeɪt/', 'adjective', 'C1', 'Obfuscated; darkened; obscured.', '', ARRAY[]::TEXT[]),
('Obituary', '/əʊ̯ˈbɪtjʊəɹiː/', 'adjective', 'C1', 'Relating to the death of a person.', '', ARRAY[]::TEXT[]),
('Obligatory', '/əˈblɪɡət(ə)ɹi/', 'adjective', 'C1', 'Imposing obligation, legally, morally, or otherwise; binding; mandatory.', 'an obligatory promise', ARRAY['bounden','mandatory']::TEXT[]),
('Oblique', '/əˈbliːk/', 'adjective', 'C2', 'Not erect or perpendicular; neither parallel to, nor at right angles from, the base; slanting; inclined.', '', ARRAY[]::TEXT[]),
('Obliterate', '/əbˈlɪtəɹeɪt/', 'verb', 'C1', 'To remove completely, leaving no trace; to wipe out; to destroy.', '', ARRAY[]::TEXT[]),
('Oblivious', '/əˈblɪ.vi.əs/', 'adjective', 'C1', '(usually followed by to or of) Lacking awareness; unmindful; unaware, unconscious of.', '', ARRAY[]::TEXT[]),
('Obloquy', '/ˈɒbləˌkwi/', 'noun', 'C1', 'Abusive language.', '', ARRAY['defamation','insult','opprobrium']::TEXT[]),
('Observatory', '/əbˈzəːvət(ə)ɹi/', 'noun', 'C1', 'A place where stars, planets and other celestial bodies are observed, usually through a telescope; also place for observing meteorological or other natural phenomena.', '', ARRAY[]::TEXT[]),
('Obstreperous', '/ɒbˈstɹɛp.əɹ.əs/', 'adjective', 'C2', 'Attended by, or making, a loud and tumultuous noise; boisterous.', '', ARRAY['clamorous','loud','noisy','vociferous','recalcitrant']::TEXT[]),
('Obstruct', '/əbˈstɹʌkt/', 'verb', 'C1', 'To block or fill (a passage) with obstacles or an obstacle.', 'They obstructed my progress.', ARRAY[]::TEXT[]),
('Obtuse', '/-ˈtʃuːs/', 'adjective', 'C2', 'Blunt; not sharp, pointed, or acute in form.', '', ARRAY['dense','dim','dim-witted','thick','blunt']::TEXT[]),
('Obviate', '/ˈɒbviˌeɪt/', 'verb', 'C1', 'To anticipate and prevent or bypass (something which would otherwise have been necessary or required).', '', ARRAY[]::TEXT[]),
('Occult', '/əˈkʌlt/', 'adjective', 'C1', 'Secret; hidden from general knowledge; undetected.', 'occult blood loss; occult cancer', ARRAY[]::TEXT[]),
('Ode', '/əʊd/', 'noun', 'C1', 'A short poetical composition proper to be set to music or sung; a lyric poem; especially, now, a poem characterized by sustained noble sentiment and appropriate dignity of style.', '', ARRAY[]::TEXT[]),
('Odium', '/ˈəʊ.di.əm/', 'noun', 'C1', 'Hatred; dislike.', 'His conduct brought him into odium, or, brought odium upon him.', ARRAY[]::TEXT[]),
('Offbeat', '', 'adjective', 'C1', 'Unusual; unconventional; not ordinary.', 'He has such an offbeat sense of humor that hardly anyone finds his jokes amusing.', ARRAY['odd','peculiar','weird']::TEXT[]),
('Offhand', '/ˌɔfˈhænd/', 'adjective', 'C1', 'Without planning or thinking ahead.', 'She gave an offhand speech.', ARRAY['extemporaneous','impromptu','off-the-cuff']::TEXT[]),
('Officious', '', 'adjective', 'C2', 'Obliging, attentive, eager to please.', '', ARRAY[]::TEXT[]),
('Off-key', '', 'adjective', 'C1', 'Pitched inaccurately either above or below the correct note', '', ARRAY[]::TEXT[]),
('Olfaction', '', 'noun', 'C1', 'The sense of smell; the detection of airborne molecules.', '', ARRAY[]::TEXT[]),
('Ominous', '/ˈɒmɪnəs/', 'adjective', 'C1', 'Of or pertaining to an omen or to omens; being or exhibiting an omen; significant.', 'California poll support for Jerry Brown''''s tax increases has ominous implications for U.S. taxpayers too Los Angeles Times Headline April 25, 2011', ARRAY['inauspicious','portentous','threatening','portentous','sinister']::TEXT[]),
('Omniscient', '/ɒmˈnɪsɪənt/', 'adjective', 'C1', 'Having total knowledge.', 'The Abrahamic God is omniscient.', ARRAY['all-knowing']::TEXT[]),
('Onerous', '/ˈɒnəɹəs/', 'adjective', 'C1', 'Imposing or constituting a physical, mental, or figurative load which can be borne only with effort; burdensome.', '', ARRAY['demanding','difficult','taxing','wearing']::TEXT[]),
('Opine', '/ə(ʊ)ˈpaɪn/', 'verb', 'C1', 'To have or express an opinion; to state as an opinion; to suppose, consider (that).', '"Your decisions," she opined, "have been unfailingly disastrous for this company."', ARRAY[]::TEXT[]),
('Opportune', '', 'adjective', 'C1', 'Suitable for some particular purpose.', 'This would be an opportune spot for a picnic.', ARRAY['seasonable','timesome','appropriate','proper']::TEXT[]),
('Opprobrious', '', 'adjective', 'C1', 'Of or relating to opprobrium or disgrace.', '', ARRAY[]::TEXT[]),
('Oracle', '/ˈɒɹəkəl/', 'verb', 'C1', 'To utter oracles or prophecies.', '', ARRAY[]::TEXT[]),
('Oration', '/ɔɹˈeɪʃən/', 'verb', 'C1', 'To deliver an oration; to speak.', '', ARRAY['hold forth','orate','sermonize','speechify']::TEXT[]),
('Orient', '/ˈɔː.ɹɪ.ənt/', 'adjective', 'C1', 'Rising, like the morning sun.', '', ARRAY['Orient red','Orient red']::TEXT[]),
('Ornithology', '', 'noun', 'C1', 'The branch of zoology that deals with the scientific study of birds.', '', ARRAY['birdlore','fowl-lore','birdlore','fowl-lore']::TEXT[]),
('Orthodox', '/ˈɔːθədɒks/', 'adjective', 'C1', 'Conforming to the accepted, established, or traditional doctrines of a given faith, religion, or ideology.', '', ARRAY['conservative','conventional','conservative','conventional']::TEXT[]),
('Oscillate', '/ˈɑsɪleɪt/', 'verb', 'C1', 'To swing back and forth, especially if with a regular rhythm.', 'A pendulum oscillates slower as it gets longer.', ARRAY['vacillate']::TEXT[]),
('Ossify', '/ˈɒs.ɪ.faɪ/', 'verb', 'C2', 'To transform (or cause to transform) from a softer animal substance into bone; particularly the processes of growth in humans and animals.', '', ARRAY['harden']::TEXT[]),
('Oust', '/ʌʊst/', 'verb', 'C1', 'To expel; to remove.', 'The protesters became so noisy that they were finally ousted from the meeting.', ARRAY['banish','dismiss','eject','exclude']::TEXT[]),
('Outgoing', '', 'adjective', 'C1', 'Extraverted: talkative, friendly, and social, especially with respect to meeting new people easily and comfortably.', 'Tom is very outgoing and enjoys meeting people; his brother, on the other hand, is painfully shy.', ARRAY[]::TEXT[]),
('Outlandish', '/aʊ̯tˈlændɪʃ/', 'adjective', 'C1', 'Bizarre, strange', 'The rock star wore black with outlandish pink and green spiked hair.', ARRAY[]::TEXT[]),
('Outmaneuver', '', 'verb', 'C1', 'To perform movements more adroitly or successfully than.', '', ARRAY[]::TEXT[]),
('Outset', '/ˈaʊtsɛt/', 'noun', 'C1', 'The beginning or initial stage of something.', 'He agreed and understood from the outset, so don''''t bother explaining again.', ARRAY[]::TEXT[]),
('Outwit', '/aʊtˈwɪt/', 'verb', 'C1', 'To get the better of; to outsmart, to beat in a competition of wits.', '', ARRAY['outfox','outguess','outsmart','overreach']::TEXT[]),
('Overbearing', '', 'adjective', 'C1', 'Overly bossy, domineering, or arrogant.', '', ARRAY['demanding','dictatorial','dominant','haughty','high-handed']::TEXT[]),
('Overlap', '/ˈəʊvəˌlæp/', 'verb', 'C1', 'To extend over and partly cover something.', 'The mouse-mat overlapped the edge of the desk.', ARRAY['intersect']::TEXT[]),
('Overt', '/ə(ʊ)ˈvɜːt/', 'adjective', 'C1', 'Open and not concealed or secret.', '', ARRAY['manifest','open','patent','plain','unconcealed']::TEXT[]),
('Overture', '/ˈəʊvətjʊə/', 'verb', 'C1', 'To make overtures; to approach with a proposal.', '', ARRAY[]::TEXT[]),
('Oxymoron', '/ɒksɪˈmɔːɹɒn/', 'noun', 'C1', 'A figure of speech in which two words or phrases with opposing meanings are used together intentionally for effect.', '', ARRAY[]::TEXT[]),
('Pachyderm', '/ˈpæk.ɪˌdɜː(ɹ)m/', 'noun', 'C1', 'A member of the obsolete taxonomic order Pachydermata, grouping of thick-skinned, hoofed animals such as the rhinoceros, hippopotamus, elephant, pig and horse.', '', ARRAY[]::TEXT[]),
('Pacify', '/ˈpæsəfaɪ/', 'verb', 'C1', 'To bring peace to (a place or situation), by ending war, fighting, violence, anger or agitation.', '', ARRAY['allay','locarnize']::TEXT[]),
('Padding', '/ˈpædɪŋ/', 'verb', 'C1', 'To furnish with a pad or padding.', 'May 21, 2008, Austin American-Statesman', ARRAY[]::TEXT[]),
('Paean', '/ˈpiː.ən/', 'verb', 'C1', 'To sing a paean; to praise.', '', ARRAY[]::TEXT[]),
('Painstaking', '/ˈpeɪnzˌteɪkɪŋ/', 'adjective', 'C1', 'Carefully attentive to details; diligent in performing a process or procedure.', '', ARRAY[]::TEXT[]),
('Palatable', '/ˈpæl.ə.tə.bəl/', 'adjective', 'C2', 'Pleasing to the taste, tasty.', 'For some instant noodles make a palatable, if not especially nutritious, meal.', ARRAY[]::TEXT[]),
('Palatial', '', 'adjective', 'C1', 'Of or relating to a palace.', 'The home where he lived was palatial.', ARRAY[]::TEXT[]),
('Palette', '/ˈpælət/', 'noun', 'C1', 'A thin board on which a painter lays and mixes colours.', '', ARRAY[]::TEXT[]),
('Pall', '/pɔːl/', 'noun', 'C1', 'Senses relating to cloth.', '', ARRAY[]::TEXT[]),
('Palliate', '/ˈpalɪeɪt/', 'adjective', 'C1', 'Cloaked; hidden, concealed.', '', ARRAY[]::TEXT[]),
('Pallid', '/ˈpælɪd/', 'adjective', 'C1', 'Appearing weak, pale or wan.', '', ARRAY['ashen','ghastly','pale','pasty']::TEXT[]),
('Palmy', '/ˈpɑːmi/', 'adjective', 'C1', 'Made out of palm leaves or palm sap.', '', ARRAY[]::TEXT[]),
('Palpable', '/ˈpalpəbəl/', 'adjective', 'C1', 'Capable of being touched, felt or handled; touchable, tangible.', '', ARRAY['manifest','noticeable','patent','tangible','touchable']::TEXT[]),
('Palter', '/ˈpɒltə/', 'verb', 'C1', 'To talk insincerely; to prevaricate or equivocate in speech or actions.', '', ARRAY[]::TEXT[]),
('Paltry', '/ˈpɑltɹi/', 'adjective', 'C1', 'Trashy, trivial, of little value.', 'She made some paltry excuse and left.', ARRAY['insignificant','petty','trivial','unimportant','meager']::TEXT[]),
('Pancreas', '/ˈpæŋkɹɪəs/', 'noun', 'C1', 'A gland near the stomach which secretes a fluid into the duodenum to help with food digestion. The fluid contains protease, carbohydrase and lipase, which breaks down larger molecules into smaller pieces. The pancreas also produces the hormones insulin and glucagon which regulate blood sugar. These hormones are released into the cardiovascular system.', '', ARRAY['belly sweetbread','gutbread','stomach sweetbread']::TEXT[]),
('Pandemic', '/pænˈdɛmɪk/', 'adjective', 'C1', 'Of a disease: epidemic over a wide geographical area and affecting a large proportion of the population; also, of or pertaining to a disease of this nature.', 'World War I might have continued indefinitely if not for a pandemic outbreak of influenza.', ARRAY['common','ubiquitous','universal','pandemial','pandemical']::TEXT[]),
('Pandemonium', '/ˌpændɪˈməʊnɪəm/', 'noun', 'C1', 'A place where all demons live; Hell.', '', ARRAY['bedlam','chaos','outburst','uproar']::TEXT[]),
('Panegyric', '/ˌpænəˈd͡ʒaɪɹɪk/', 'adjective', 'C2', 'Panegyrical', '', ARRAY[]::TEXT[]),
('Panoramic', '', 'adjective', 'C1', 'With a wide view', '', ARRAY[]::TEXT[]),
('Pantry', '/ˈpantɹi/', 'noun', 'C1', 'A small room, closet, or cabinet usually located in or near the kitchen, dedicated to shelf-stable food storage and/or storing kitchenware, like a larder, but smaller.', '', ARRAY['cabinet','cupboard','kitchen','closet','cupboard']::TEXT[]),
('Parable', '/ˈpaɹəbəl/', 'verb', 'C1', 'To represent by parable.', '', ARRAY[]::TEXT[]),
('Paradigm', '/ˈpæ.ɹə.daɪm/', 'noun', 'C1', 'A pattern, a way of doing something, especially a pattern of thought, a system of beliefs, a conceptual framework.', 'Thomas Kuhn''''s landmark “The Structure of Scientific Revolutions” got people talking about paradigm shifts, to the point the word itself now suggests an incomplete or biased perspective.', ARRAY['exemplar','posterboy','template','model','worldview']::TEXT[]),
('Paradise', '/ˈpæ.ɹə.daɪs/', 'verb', 'C1', 'To place (as) in paradise.', '', ARRAY['bewitch','entrance','imparadise','imparadise','bewitch']::TEXT[]),
('Paradox', '/ˈpaɹədɒks/', 'noun', 'C1', 'An apparently self-contradictory statement, which can only be true if it is false, and vice versa.', '"This sentence is false" is a paradox.', ARRAY['shocker','contradiction','juxtaposition','reverse psychology','enigma']::TEXT[]),
('Paragon', '/ˈpæɹəɡən/', 'verb', 'C2', 'To compare; to parallel; to put in rivalry or emulation with.', '', ARRAY[]::TEXT[]),
('Paramount', '/ˈpa.ɹə.maʊnt/', 'adjective', 'C1', 'Supreme; highest; chief.', 'Getting those credit cards paid off is paramount.', ARRAY['highest','utmost']::TEXT[]),
('Paranoia', '/ˌpæɹ.əˈnɔɪ.ə/', 'noun', 'C1', 'A psychotic disorder characterized by delusions of persecution, conspiracy and perceived threat against the person, often associated with false accusations and general mistrust of others', '', ARRAY[]::TEXT[]),
('Paraphrase', '', 'verb', 'C1', 'To restate something as, or to compose a paraphrase.', '', ARRAY[]::TEXT[]),
('Parasite', '/ˈpæɹəˌsaɪt/', 'noun', 'C1', 'A person who lives on other people''''s efforts or expense and gives little or nothing back.', 'Lice, fleas, ticks and mites are widely spread parasites.', ARRAY[]::TEXT[]),
('Parch', '/pɑːtʃ/', 'verb', 'C1', 'To burn the surface of, to scorch.', 'The sun today could parch cement.', ARRAY[]::TEXT[]),
('Parenthesis', '/pəˈɹɛnθəsɪs/', 'noun', 'C1', 'A clause, phrase or word which is inserted (usually for explanation or amplification) into a passage which is already grammatically complete, and usually marked off with brackets, commas or dashes.', '', ARRAY['parenthesis-point','round bracket','paren']::TEXT[]),
('Pariah', '/pəˈɹaɪə/', 'noun', 'C2', 'A person who is rejected from society or home; an outcast.', '', ARRAY[]::TEXT[]),
('Parity', '/ˈpæɹɪti/', 'noun', 'C1', 'Equality; comparability of strength or intensity.', '', ARRAY[]::TEXT[]),
('Parlance', '/ˈpɑː.ləns/', 'noun', 'C1', 'A certain way of speaking, of using words, especially when it comes to those with a particular job or interest.', '', ARRAY['jargon']::TEXT[]),
('Parody', '/ˈpæɹədi/', 'verb', 'C1', 'To make a parody of something.', 'The comedy movie parodied the entire Western genre.', ARRAY[]::TEXT[]),
('Paroxysm', '/ˈpæɹ.əkˌsɪz.əm/', 'noun', 'C1', 'A random or sudden outburst (of activity).', '', ARRAY[]::TEXT[]),
('Parquetry', '/ˈpɑɹkɪtɹi/', 'noun', 'C1', 'The technique of applying wooden tiles or veneers to create a decorative geometrical pattern on floors, furniture etc.', 'The new ballroom floor is a marvellous example of parquetry.', ARRAY[]::TEXT[]),
('Parrot', '/ˈpæɹət/', 'verb', 'C1', 'To repeat (exactly what has just been said) without necessarily showing understanding, in the manner of a parrot.', 'The interviewee merely parroted the views of her tabloid.', ARRAY['ape','copycat']::TEXT[]),
('Parry', '/ˈpæɹi/', 'verb', 'C1', 'To avoid, deflect, or ward off (an attack, a blow, an argument, etc.).', '', ARRAY[]::TEXT[]),
('Parse', '/pɑːz/', 'verb', 'C1', 'To resolve (a sentence, etc.) into its elements, pointing out the several parts of speech, and their relation to each other by agreement or government; to analyze and describe grammatically.', 'This sentence doesn''''t parse.', ARRAY['construe','construe']::TEXT[]),
('Parsimony', '/ˈpɑɹ.sə.ˌmoʊ.ni/', 'noun', 'C1', 'Great reluctance to spend money unnecessarily.', '', ARRAY['economy','frugality','stinginess','economy','frugality']::TEXT[]),
('Particularize', '/pəˈtɪkjʊləɹʌɪz/', 'verb', 'C1', 'To make particular, as opposed to general; to restrict to a specific or individual case, class etc.; to single out.', '', ARRAY['clarify','explicitize','distinguish','severalize','set apart']::TEXT[]),
('Partisan', '/ˈpɑː.tɪˌzæn/', 'adjective', 'C1', 'Serving as commander or member of a body of detached light troops.', 'partisan officer, partisan corps', ARRAY[]::TEXT[]),
('Pastiche', '/pæsˈtiːʃ/', 'verb', 'C1', 'To create or compose in a mixture of styles.', '', ARRAY[]::TEXT[]),
('Partition', '/pɑɹˈtɪʃən/', 'verb', 'C1', 'To divide something into parts, sections or shares', '', ARRAY['dismember']::TEXT[]),
('Pathology', '/pəˈθɒlədʒi/', 'noun', 'C1', 'The branch of medicine concerned with the study of the nature of disease and its causes, processes, development, and consequences.', 'The surgeon sent a specimen of the cyst to the pathology department for staining and analysis to determine its histologic subtype.', ARRAY['abnormality','disease','illness','pathosis','abnormality']::TEXT[]),
('Patina', '/ˈpætɪnə/', 'adjective', 'C1', 'Of a green colour, tinted with grey, like that of bronze patina.', '', ARRAY[]::TEXT[]),
('Patrician', '/pətɹˈɪʃən/', 'adjective', 'C1', 'Of or pertaining to the Roman patres ("fathers") or senators, or patricians.', '', ARRAY[]::TEXT[]),
('Patriot', '/ˈpeɪ.tɹi.ət/', 'noun', 'C1', 'A person who loves and zealously supports and defends their country.', '', ARRAY[]::TEXT[]),
('Paunchy', '', 'adjective', 'C1', 'Having a paunch; having a prominent stomach; potbellied.', 'He exercised every day to avoid becoming paunchy in his old age.', ARRAY[]::TEXT[]),
('Pebble', '/ˈpɛb.əl/', 'verb', 'C1', 'To pave with pebbles.', 'to pebble the ice between games', ARRAY[]::TEXT[]),
('Peccadillo', '/ˌpɛ.kəˈdɪ.ləʊ/', 'noun', 'C1', 'A small flaw or sin.', '', ARRAY['veniality','veniality']::TEXT[]),
('Peck', '/pɛk/', 'verb', 'C1', 'To strike or pierce with the beak or bill (of a bird).', 'The birds pecked at their food.', ARRAY[]::TEXT[]),
('Pedagogue', '', 'noun', 'C1', 'A teacher or instructor of children; one whose occupation is to teach the young.', '', ARRAY[]::TEXT[]),
('Pedant', '/ˈpɛdənt/', 'noun', 'C1', 'A teacher or schoolmaster.', '', ARRAY[]::TEXT[]),
('Pedestal', '/ˈpɛdɪstəl/', 'verb', 'C1', 'To set or support on (or as if on) a pedestal.', '', ARRAY[]::TEXT[]),
('Predestine', '/pɹeˈdɛstɪn/', 'verb', 'C1', 'To determine the future or the fate of something in advance; to preordain.', '', ARRAY[]::TEXT[]),
('Pediatrics', '', 'noun', 'C1', 'The branch of medicine that deals with the treatment of children.', '', ARRAY['pediatry']::TEXT[]),
('Peep', '/piːp/', 'verb', 'C1', 'To make a soft, shrill noise like a baby bird.', '', ARRAY[]::TEXT[]),
('Peeve', '/piːv/', 'verb', 'C1', 'To annoy; vex.', 'He was peeved to note that his hard work had been undone.', ARRAY[]::TEXT[]),
('Pelf', '/pɛlf/', 'noun', 'C1', 'Money; riches; gain, especially when dishonestly acquired (compare lucre).', '', ARRAY[]::TEXT[]),
('Pellucid', '/pəˈluːsɪd/', 'adjective', 'C2', 'Allowing the passage of light; transparent.', '', ARRAY['clear','limpid','lucid','translucent','clear']::TEXT[]),
('Penchant', '/ˈpɒnʃɒn/', 'noun', 'C1', 'Taste, liking, or inclination (for).', 'He has a penchant for fine wine.', ARRAY['desire']::TEXT[]),
('Penitent', '/ˈpɛnɪtənt/', 'adjective', 'C1', 'Feeling pain or sorrow on account of one''''s sins or offenses; feeling sincere guilt.', '', ARRAY['contrite','repentant','contrite','repentant']::TEXT[]),
('Pensive', '/ˈpɛn.sɪv/', 'adjective', 'C1', 'Having the appearance of deep, often melancholic, thinking.', '', ARRAY[]::TEXT[]),
('Penury', '/ˈpɛnjəɹi/', 'noun', 'C1', 'Extreme want; poverty; destitution.', '', ARRAY['barrenness','insufficiency','barrenness','insufficiency']::TEXT[]),
('Perambulate', '/pəɹˈæmbjəˌleɪt/', 'verb', 'C1', 'To walk about, roam or stroll.', '', ARRAY[]::TEXT[]),
('Perceptible', '/pəˈsɛptɪbl̩/', 'adjective', 'C1', 'Able to be perceived, sensed, or discerned.', 'Her voice was barely perceptible over the noise, but her gestures made her meaning clear.', ARRAY[]::TEXT[]),
('Peremptory', '/pəˈɹɛmptəɹi/', 'adjective', 'C2', 'Precluding debate or expostulation; not admitting of question or appeal', '', ARRAY['absolute','conclusive','decisive','final','positive']::TEXT[]),
('Perfervid', '/pəːˈfəːvɪd/', 'adjective', 'C1', 'Extremely, excessively, or feverishly passionate; zealous.', '', ARRAY['ardent','eager','enthusiastic','fervid']::TEXT[]),
('Perforate', '', 'verb', 'C1', 'To pierce; to penetrate.', 'to perforate a sheet of postage stamps', ARRAY[]::TEXT[]),
('Perfunctory', '/pəˈfʌŋk.t(ə)ɹɪ/', 'adjective', 'C2', 'Done only to fulfil a duty, or in a careless or indifferent manner; performed mechanically and as a thing of rote.', 'He did a perfunctory job cleaning his dad''''s car, finishing quickly but leaving a few spots still dirty.', ARRAY['automatic','cursory','dutiful','mechanical','obligatory']::TEXT[]),
('Perimeter', '/pəˈɹɪmɪtə(ɹ)/', 'noun', 'C1', 'The sum of the distance of all the lengths of the sides of an object.', '', ARRAY['premises','circumference']::TEXT[]),
('Periodical', '', 'adjective', 'C1', 'Published at regular intervals of more than one day, especially weekly, monthly, or quarterly.', '', ARRAY['cyclic','cyclic']::TEXT[]),
('Peripatetic', '/ˌpɛɹ.ə.pəˈtɛt.ɪk/', 'adjective', 'C2', 'Tending to walk about.', '', ARRAY[]::TEXT[]),
('Peripheral', '/pəˈɹɪf(ə)ɹ(ə)l/', 'adjective', 'C1', 'On the periphery or boundary.', '', ARRAY[]::TEXT[]),
('Perish', '/ˈpɛɹɪʃ/', 'verb', 'C1', 'To decay and disappear; to waste away to nothing.', '', ARRAY['decease','pass away']::TEXT[]),
('Perjury', '/ˈpɜː(ɹ)dʒəɹi/', 'noun', 'C1', 'The deliberate giving of false or misleading testimony under oath.', 'We declare under penalty of perjury that the foregoing is true and correct.', ARRAY['false','testimony','oathbreach']::TEXT[]),
('Permanence', '/ˈpɜmənəns/', 'noun', 'C1', 'The state of being permanent.', '', ARRAY['perdurance','remanence']::TEXT[]),
('Permeable', '', 'adjective', 'C1', 'That absorbs or allows the passage of fluids', 'Rainwater sinks through permeable rock to form an underground reservoir.', ARRAY['water-permeable','water-permeable']::TEXT[]),
('Peroration', '/pɛɹɒˈɹeɪʃən/', 'noun', 'C1', 'The concluding section of a discourse, either written or oral, in which the orator or writer sums up and commends his topic to his audience, particularly as used in the technical sense of a component of ancient Roman oratorical delivery.', '', ARRAY[]::TEXT[]),
('Perpetual', '/pəˈpɛtjʊəl/', 'adjective', 'C1', 'Lasting forever, or for an indefinitely long time', 'By means of artificial hybridization, practised for a series of years, he has succeeded in producing a race of carnations which are perpetual bloomers.', ARRAY['continuant','persistent','continuous','nonstop','continuant']::TEXT[]),
('Persecute', '/ˈpəːsɪkjuːt/', 'verb', 'C1', 'To pursue in a manner to injure, grieve, or afflict; to beset with cruelty or malignity; to harass; especially, to afflict, harass, punish, or put to death for one''''s race, sexual identity, adherence to a particular religious creed, or mode of worship.', 'He who persecutes one will persecute all.', ARRAY['annoy','distress','harass','oppress','worry']::TEXT[]),
('Persevere', '', 'verb', 'C1', 'To persist steadfastly in pursuit of an undertaking, task, journey, or goal, even if hindered by distraction, difficulty, obstacles, or discouragement.', '', ARRAY[]::TEXT[]),
('Persiflage', '/ˈpɜː.sɪ.flɑːʒ/', 'noun', 'C1', 'Good-natured banter; raillery.', '', ARRAY['banter','raillery']::TEXT[]),
('Persistence', '/pəˈsɪst(ə)ns/', 'noun', 'C1', 'The property of being persistent.', 'You''''ve got to admire his persistence. He''''s asked her out every day for a month even though she keeps turning him down.', ARRAY['persistency']::TEXT[]),
('Personable', '/ˈpɜː(ɹ)sənəbəl/', 'adjective', 'C1', '(of a person) Having a pleasing appearance or manner; attractive; handsome; friendly; amiable.', '', ARRAY['affable']::TEXT[]),
('Plasticity', '', 'noun', 'C1', 'The quality or state of being plastic.', '', ARRAY[]::TEXT[]),
('Plateau', '/ˈplætəʊ/', 'verb', 'C1', 'To reach a stable level; to level off.', '', ARRAY[]::TEXT[]),
('Plausible', '/ˈplɔːz.ə.bəl/', 'adjective', 'C1', 'Seemingly or apparently valid, likely, or acceptable; conceivably true or likely', 'a plausible excuse', ARRAY[]::TEXT[]),
('Pleat', '/pliːt/', 'verb', 'C1', 'To form one or more pleats in a piece of fabric or a garment.', '', ARRAY[]::TEXT[]),
('Plentitude', '', 'noun', 'C1', 'Abundance, fullness, completeness; an instance of this.', 'Of quotations in the OED there are indeed a plentitude.', ARRAY['plenitude']::TEXT[]),
('Plethora', '/plɪˈθɔːɹə/', 'noun', 'C1', '(usually followed by of) An excessive amount or number; an abundance.', 'The menu offers a plethora of cuisines from around the world.', ARRAY['glut','myriad','slew','superfluity','surfeit']::TEXT[]),
('Pliable', '/ˈplaɪəbəl/', 'adjective', 'C1', 'Soft, flexible, easily bent, formed, shaped, or molded.', 'You will find the clay perfectly pliable as long as it stays moist.', ARRAY['lithy']::TEXT[]),
('Pliant', '/ˈplaɪənt/', 'adjective', 'C1', 'Capable of plying or bending; readily yielding to force or pressure without breaking', 'a pliant thread pliant wax', ARRAY['flexible','limber','lithe','plastic','pliable']::TEXT[]),
('Plight', '/plaɪt/', 'noun', 'C1', 'A dire or unfortunate situation.', '', ARRAY[]::TEXT[]),
('Pluck', '/plʌk/', 'verb', 'C1', 'To pull something sharply; to pull something out', 'She plucked the phone from her bag and dialled.', ARRAY[]::TEXT[]),
('Plumb', '/plʌm/', 'adjective', 'C1', 'Truly vertical, as indicated by a plumb line.', '', ARRAY['perpendicular']::TEXT[]),
('Plummet', '/ˈplʌm.ət/', 'verb', 'C1', 'To drop swiftly, in a direct manner; to fall quickly.', 'After its ascent, the arrow plummeted to earth.', ARRAY['dive','drop','fall']::TEXT[]),
('Plump', '/plʌmp/', 'adjective', 'C1', 'Having a full and rounded shape; chubby, somewhat overweight.', 'a plump baby; plump cheeks', ARRAY[]::TEXT[]),
('Plutocracy', '/pluːˈtɒkɹəsi/', 'noun', 'C1', 'Government by the wealthy.', '', ARRAY['argentocracy','tycoonocracy']::TEXT[]),
('Podiatrist', '/pəˈdaɪətɹɪst/', 'noun', 'C1', 'A health care practitioner who specializes in the diagnosis and treatment of foot ailments.', 'I visited my podiatrist to get a new pair of orthopedic inserts for my sneakers.', ARRAY['chiropodist']::TEXT[]),
('Polarize', '/ˈpoʊləɹaɪz/', 'verb', 'C1', 'To cause to have a polarization.', '', ARRAY[]::TEXT[]),
('Polished', '/ˈpɒlɪʃt/', 'adjective', 'C1', 'Made smooth or shiny by polishing.', 'polished shoes', ARRAY[]::TEXT[]),
('Politic', '/ˈpɒlətɪk/', 'adjective', 'C1', 'Of or relating to polity, or civil government; political.', 'the body politic', ARRAY[]::TEXT[]),
('Pollster', '', 'noun', 'C1', 'A professional who conducts or analyzes opinion polls.', 'Trump didn''''t like the results of the polls, so he fired the pollsters.', ARRAY[]::TEXT[]),
('Pompous', '/ˈpɒmpəs/', 'adjective', 'C1', 'Affectedly grand, solemn or self-important.', '', ARRAY['conceited','smug']::TEXT[]),
('Ponderable', '', 'adjective', 'C1', 'Having a detectable amount of matter; having a measurable mass.', '', ARRAY['massive','hefty','massive','weighty','eminent']::TEXT[]),
('Ponderous', '/ˈpɒn.dəɹ.əs/', 'adjective', 'C2', 'Heavy, massive, weighty.', '', ARRAY['heavy','massive','oppressive','serious']::TEXT[]),
('Pontificate', '/pɒnˈtɪfɪkət/', 'noun', 'C2', 'The status or term of office of a pontiff or pontifex.', '', ARRAY[]::TEXT[]),
('Porcelain', '/ˈpoːslɘn/', 'noun', 'C1', 'The plant Smilax china, a liana of much of eastern Asia.', '', ARRAY['china']::TEXT[]),
('Pore', '/pɔː/', 'noun', 'C1', 'A tiny opening in the skin.', '', ARRAY[]::TEXT[]),
('Porous', '/ˈpɔːɹəs/', 'adjective', 'C1', 'Full of tiny pores that allow fluids or gasses to pass through.', 'Concrete is porous, so water will slowly filter through it.', ARRAY['permeable']::TEXT[]),
('Portentous', '/pɔː(ɹ)ˈtɛntəs/', 'adjective', 'C2', 'Of momentous or ominous significance.', '', ARRAY['foreshadowing','predictive','premonitory','prognosticatory','momentous']::TEXT[]),
('Poseur', '/poʊˈzʊəɹ/', 'noun', 'C1', 'One who affects some behaviour, style, attitude or other condition, often to impress or influence others.', 'He pretends he''''s an artist, but he''''s just a poseur.', ARRAY['attitudinizer','poser','attitudinizer','poser']::TEXT[]),
('Postulate', '', 'adjective', 'C1', 'Postulated.', '', ARRAY[]::TEXT[]),
('Posture', '/ˈpɒstʃə/', 'verb', 'C1', 'To put one''''s body into a posture or series of postures, especially hoping that one will be noticed and admired', 'If you''''re finished posturing in front of the mirror, can I use the bathroom now?', ARRAY[]::TEXT[]),
('Potable', '/ˈpɒt-/', 'adjective', 'C1', 'Good for drinking without fear of disease or poisoning.', '', ARRAY['drinkable','drinkworthy','drinkable','drinkworthy']::TEXT[]),
('Potboiler', '', 'noun', 'C1', '(mildly) A creative work of low quality (book, art, etc), produced merely to earn a living or for profit, as opposed to serious creative expression.', '', ARRAY[]::TEXT[]),
('Potentate', '/ˈpəʊ.tən.teɪt/', 'adjective', 'C1', 'Regnant, powerful, dominant.', '', ARRAY[]::TEXT[]),
('Potentiate', '', 'verb', 'C1', 'To endow with power.', 'These antidepressants potentiate the analgesic action of opiates.', ARRAY[]::TEXT[]),
('Pout', '/pʌʊt/', 'verb', 'C1', 'To push out one''''s lips.', '"Don''''t you love me any more?" she pouted.', ARRAY['moue']::TEXT[]),
('Prairie', '/ˈpɹɛəɹi/', 'noun', 'C1', 'An extensive area of relatively flat grassland with few, if any, trees, especially in North America.', '', ARRAY[]::TEXT[]),
('Prate', '/pɹeɪt/', 'verb', 'C1', 'To talk much and to little purpose; to be loquacious; to speak foolishly.', '', ARRAY['blabber','blabber']::TEXT[]),
('Precipice', '/ˈpɹɛs.ə.pɪs/', 'noun', 'C1', 'A very steep cliff.', 'to stand on a precipice', ARRAY['cliff','cliffdrop']::TEXT[]),
('Precipitate', '/pɹəˈsɪpɪteɪt/', 'adjective', 'C2', 'Headlong; falling steeply or vertically.', 'The king was too precipitate in declaring war.', ARRAY['abrupt','precipitous','subitaneous','brant','headlong']::TEXT[]),
('Precipitation', '/pɹɪˌsɪpɪˈteɪʃən/', 'noun', 'C1', 'Any or all of the forms of water particles, whether liquid or solid, that fall from the atmosphere (e.g., rain, hail, snow or sleet). It is a major class of hydrometeor, but it is distinguished from cloud, fog, dew, rime, frost, etc., in that it must fall. It is distinguished from cloud and virga in that it must reach the ground.', '', ARRAY[]::TEXT[]),
('Precursor', '/pɹɨˈkɜɹ.səɹ/', 'adjective', 'C1', '(of intersymbol interference) Caused by the following symbol.', '', ARRAY[]::TEXT[]),
('Preeminent', '/pɹiːˈɛmɪnənt/', 'adjective', 'C1', 'Exceeding others in quality or rank; of outstanding excellence, extremely notable or important.', '', ARRAY[]::TEXT[]),
('Preen', '/pɹiːn/', 'verb', 'C1', 'To pin; fasten.', '', ARRAY[]::TEXT[]),
('Preface', '/ˈpɹɛfəs/', 'verb', 'C1', 'To introduce or make a comment before (the main point).', 'Let me preface this by saying that I don''''t know him that well.', ARRAY[]::TEXT[]),
('Premeditate', '', 'verb', 'C1', 'To meditate, consider, or plan beforehand; to think about and revolve in the mind beforehand.', '', ARRAY[]::TEXT[]),
('Preoccupation', '', 'noun', 'C1', 'The state of being preoccupied or an idea that preoccupies the mind; enthrallment.', '', ARRAY['preoccupancy']::TEXT[]),
('Preponderant', '', 'adjective', 'C1', 'Having greater or the greatest weight, quantity, importance or force.', 'The judge gave preponderant weight to the physical evidence.', ARRAY['dominant','overriding','predominant','dominant','overriding']::TEXT[]),
('Prepossessing', '', 'adjective', 'C1', 'Tending to invite favor; attracting confidence, favor, esteem, or love; attractive', 'a prepossessing manner', ARRAY[]::TEXT[]),
('Preposterous', '', 'adjective', 'C1', 'Absurd, or contrary to common sense.', '', ARRAY['absurd','foolish','irrational','nonsensical']::TEXT[]),
('Presage', '/pɹɪˈseɪdʒ/', 'verb', 'C1', 'To predict or foretell something.', '', ARRAY['foreshadow','forespell','portend']::TEXT[]),
('Preservative', '', 'adjective', 'C1', 'Tending to preserve.', 'The curators took preservative actions to maintain the ancient collection.', ARRAY[]::TEXT[]),
('Prestige', '/pɹəˈsti(d)ʒ/', 'adjective', 'C1', '(of a linguistic form) Regarded as relatively prestigious; often, considered the standard language or language variety, or a part of such a variety.', '', ARRAY[]::TEXT[]),
('Pretense', '/ˈpɹiːtɛns/', 'noun', 'C1', 'A false or hypocritical profession', 'under pretense of friendliness', ARRAY['affectation','deception','escape','false pretense','fiction']::TEXT[]),
('Preternatural', '/ˌpɹiː.təˈnæt͡ʃ.(ə)ɹ.əl/', 'adjective', 'C1', 'Beyond or not conforming to what is natural or according to the regular course of things; strange.', '', ARRAY['abnormal','exceptional','extraordinary','inexplicable','uncanny']::TEXT[]),
('Prevalent', '/ˈpɹɛvələnt/', 'adjective', 'C1', 'Widespread or preferred.', '', ARRAY['common','rife']::TEXT[]),
('Primordial', '/pɹaɪˈmɔː.di.əl/', 'adjective', 'C1', 'First, earliest or original', 'a primordial leaf; a primordial cell', ARRAY[]::TEXT[]),
('Primp', '/pɹɪmp/', 'verb', 'C1', 'To spend time improving one''''s appearance, often in front of a mirror.', '', ARRAY[]::TEXT[]),
('Privation', '/pɹaɪˈveɪʃən/', 'noun', 'C1', 'The state of being deprived of or lacking an attribute formerly or properly possessed; the loss or absence of such an attribute.', '', ARRAY[]::TEXT[]),
('Probity', '/ˈpɹəʊbɪti/', 'noun', 'C2', 'Integrity, especially of the quality of having strong moral principles; honesty and decency.', '', ARRAY['decency','godliness','goodness','honesty','honor']::TEXT[]),
('Proclivity', '/pɹoʊˈklɪvəti/', 'noun', 'C1', 'A predisposition or natural inclination, propensity, or a predilection; especially, a strong disposition or bent.', 'The child has a proclivity for exaggeration.', ARRAY['penchant','propensity']::TEXT[]),
('Procrastinate', '/pɹəʊˈkɹæstɪneɪt/', 'verb', 'C1', 'To delay taking action; to wait until later.', 'He procrastinated until the last minute and had to stay up all night to finish.', ARRAY['delay','penelopize','stall','delay','postpone']::TEXT[]),
('Procure', '/pɹəˈkjɔː/', 'verb', 'C1', 'To acquire or obtain.', '', ARRAY['obtain','buy','purchase']::TEXT[]),
('Prod', '/pɹɒd/', 'verb', 'C1', 'To poke, to push, to touch.', '', ARRAY[]::TEXT[]),
('Profane', '/pɹəˈfeɪn/', 'adjective', 'C1', 'Unclean; ritually impure; unholy, desecrating a holy place or thing.', 'profane authors', ARRAY['debased','ignoble','inappropriate','lewd','mean']::TEXT[]),
('Proffer', '/ˈpɹɒfə(ɹ)/', 'verb', 'C1', 'To offer for acceptance; to propose to give; to make a tender of.', 'to proffer friendship, a gift, or services', ARRAY[]::TEXT[]),
('Proficient', '/pɹəˈfɪʃ.ənt/', 'adjective', 'C1', 'Good at something; skilled; fluent; practiced, especially in relation to a task or skill.', 'He was a proficient writer with an interest in human nature.', ARRAY['fluent','practiced','skilled']::TEXT[]),
('Profundity', '/pɹəˈfʌndɪti/', 'noun', 'C1', 'The state of being profound or abstruse.', '', ARRAY['profoundness']::TEXT[]),
('Prohibitive', '', 'adjective', 'C1', 'Tending to prohibit, preclude, or disallow.', 'Some countries are more prohibitive than others when it comes to hot topics like euthanasia and cloning.', ARRAY[]::TEXT[]),
('Proliferate', '/pɹəˈlɪf.əɹ.eɪt/', 'verb', 'C1', 'To increase in number or spread rapidly; to multiply.', 'The flowers proliferated rapidly all spring.', ARRAY[]::TEXT[]),
('Prolix', '/ˈpɹəʊ.lɪks/', 'adjective', 'C1', 'Tediously lengthy; dwelling on trivial details.', '', ARRAY['verbose','verbose']::TEXT[]),
('Prologue', '/ˈpɹəʊlɒɡ/', 'verb', 'C1', 'To introduce with a formal preface, or prologue.', '', ARRAY[]::TEXT[]),
('Prolong', '/pɹoʊˈlɑŋ/', 'verb', 'C1', 'To extend in space or length.', 'The government shouldn''''t prolong deciding on this issue any further.', ARRAY['draw out','draw out']::TEXT[]),
('Proofread', '/ˈpɹuːfɹiːd/', 'verb', 'C1', 'To check a written text for errors in spelling and grammar.', '', ARRAY[]::TEXT[]),
('Promulgate', '/ˈpɹɒml̩.ɡeɪt/', 'verb', 'C2', 'To make known or public.', '', ARRAY['carry out','execute','implement','put into effect','declare']::TEXT[]),
('Propagate', '/ˈpɹɒpəˌɡeɪt/', 'verb', 'C1', '(of animals or plants) To cause to continue or multiply by generation, or successive production', 'to propagate sound or light', ARRAY[]::TEXT[]),
('Propensity', '/pɹəˈpɛnsɪti/', 'noun', 'C1', 'An inclination, disposition, tendency, preference, or attraction.', 'He has a propensity for lengthy discussions of certain favorite topics.', ARRAY['predilection','proclivity','propension']::TEXT[]),
('Prophetic', '/pɹəˈfɛtɪk/', 'adjective', 'C1', 'Of, or relating to a prophecy or a prophet', '', ARRAY[]::TEXT[]),
('Propitiate', '/ˌpɹəˈpɪʃieɪt/', 'verb', 'C2', 'To conciliate, appease, or make peace with someone, particularly a god or spirit.', '', ARRAY['appease','atone','appease','atone']::TEXT[]),
('Propriety', '/pɹəˈpɹaɪəti/', 'noun', 'C1', 'The particular character or essence of someone or something; individuality.', '', ARRAY[]::TEXT[]),
('Prosaic', '/pɹəʊˈzeɪ.ɪk/', 'adjective', 'C2', 'Pertaining to or having the characteristics of prose.', 'The tenor of Eliot''''s prosaic work differs greatly from that of his poetry.', ARRAY['dull','humdrum','unimaginative','dull','humdrum']::TEXT[]),
('Proscribe', '/ˈpɹəʊˌskɹaɪb/', 'verb', 'C2', 'To forbid or prohibit.', 'The law proscribes driving a car while intoxicated.', ARRAY[]::TEXT[]),
('Proselytize', '/ˈpɹɑ.zə.lə.taɪz/', 'verb', 'C2', 'To advertise one’s religious beliefs; to convert (someone) to one’s own faith or religious movement or encourage them to do so.', 'It is illegal to proselytize [children] in some countries', ARRAY['advocate','back','endorse','peddle','recruit']::TEXT[]),
('Prosperous', '/ˈpɹɒs.p(ə.)ɹəs/', 'adjective', 'C1', 'Characterized by success', 'Trading Babe Ruth was far more prosperous for the Yankees than for the Red Sox.', ARRAY['successful','favorable','lucky','affluent','rich']::TEXT[]),
('Prostrate', '/ˈpɹɒstɹeɪt/', 'adjective', 'C1', 'Lying flat, face-down.', 'He was prostrate from the extreme heat.', ARRAY['prone','prone']::TEXT[]),
('Protean', '/pɹəʊˈtiː.ən/', 'adjective', 'C2', 'Of or relating to Proteus', '', ARRAY['protean']::TEXT[]),
('Protract', '/pɹəˈtɹakt/', 'verb', 'C1', 'To draw out; to extend, especially in duration.', 'to protract a decision or duty', ARRAY['prolong']::TEXT[]),
('Protrude', '', 'verb', 'C1', 'To extend from, above or beyond a surface or boundary; to bulge outward; to stick out.', '', ARRAY['jut','project','protuberate']::TEXT[]),
('Protuberant', '', 'adjective', 'C1', 'Swelling or bulging outward.', '', ARRAY[]::TEXT[]),
('Provident', '/ˈpɹɒvɪdənt/', 'adjective', 'C2', 'Possessing, exercising, or demonstrating great care and consideration for the future.', '', ARRAY['cautious','foresightful','prudent','economical','frugal']::TEXT[]),
('Providential', '/pɹɒvɪˈdɛnʃl̩/', 'adjective', 'C1', 'Pertaining to divine providence.', '', ARRAY['fortunate','heaven-sent','lucky','serendipitous','fortunate']::TEXT[]),
('Provisory', '/pɹəˈvaɪzəɹi/', 'adjective', 'C1', 'Containing a proviso.', 'The provisory clause effectively excluded his otherwise logical heirs from his main inheritance.', ARRAY['conditional','provisional','temporary','transitory']::TEXT[]),
('Prowess', '/ˈpɹaʊɪs/', 'noun', 'C1', 'Skillfulness and manual ability; adroitness or dexterity.', '', ARRAY[]::TEXT[]),
('Prowl', '/pɹaʊl/', 'verb', 'C1', 'To rove over, through, or about in a stealthy manner; especially, to search in, as for prey or booty.', 'It''''s tough to sneak vandalism into Wikipedia as there are plenty of other users prowling the Recent Changes page.', ARRAY[]::TEXT[]),
('Prude', '/pɹuːd/', 'noun', 'C1', 'A person who is or tries to be excessively proper, especially one who is easily offended by matters of a sexual nature.', '', ARRAY['antisexualist','celibacist','erotophobe','goody-goody','prig']::TEXT[]),
('Prudent', '/ˈpɹuːdənt/', 'adjective', 'C1', 'Sagacious in adapting means to ends; circumspect in action, or in determining any line of conduct; careful, discreet, sensible; — opposed to rash; directed by prudence or wise forethought; evincing prudence', 'His prudent career moves reliably brought him to the top', ARRAY['considerate','provident']::TEXT[]),
('Prudish', '', 'adjective', 'C1', 'Of excessive propriety; easily offended or shocked, especially by sexual matters', '', ARRAY[]::TEXT[]),
('Prune', '/pɹuːn/', 'verb', 'C1', 'To become wrinkled like a dried plum, as the fingers and toes do when kept submerged in water.', '', ARRAY[]::TEXT[]),
('Pry', '/pɹaɪ/', 'verb', 'C1', 'To look where one is not welcome; to be nosy.', '', ARRAY[]::TEXT[]),
('Pseudonym', '/ˈs(j)uː.dəʊ.nɪm/', 'noun', 'C1', 'A fictitious name, as those used by writers and movie stars.', 'The Reverend Charles Lutwidge Dodgson wrote "Alice''''s Adventures in Wonderland" under the pseudonym Lewis Carroll.', ARRAY[]::TEXT[]),
('Pucker', '', 'verb', 'C1', 'To pinch or wrinkle; to squeeze inwardly, to dimple or fold.', '', ARRAY[]::TEXT[]),
('Puckish', '/ˈpʌkɪʃ/', 'adjective', 'C1', 'Mischievous; excessively playful.', '', ARRAY['impish','mischievous','playful']::TEXT[]),
('Puerile', '/ˈpjʊə.ɹaɪl/', 'adjective', 'C2', 'Childish; trifling; silly.', '', ARRAY['juvenile','silly','trifling','juvenile','silly']::TEXT[]),
('Puissance', '/ˈpjuːɪ.s(ə)ns/', 'noun', 'C1', 'Power, might or potency.', '', ARRAY[]::TEXT[]),
('Pulchritude', '[ˈpʰʌɫkɹəˌtjuːd]', 'noun', 'C1', 'Physical beauty.', '', ARRAY['comeliness','comeliness']::TEXT[]),
('Pulverize', '', 'verb', 'C1', 'To render into dust or powder.', 'the stone pulverises easily', ARRAY[]::TEXT[]),
('Pun', '/pʌn/', 'verb', 'C1', 'To beat; strike with force; to ram; to pound, as in a mortar; reduce to powder, to pulverize.', 'We punned about the topic until all around us groaned.', ARRAY[]::TEXT[]),
('Punctilious', '/pʌŋkˈtɪli.əs/', 'adjective', 'C2', 'Strictly attentive to detail; meticulous or fastidious, particularly to codes or conventions.', 'With a punctilious slap of the gloves, the duel was now inevitable.', ARRAY['finicky','nitpicky','precise','finicky','nitpicky']::TEXT[]),
('Pungent', '/ˈpʌndʒənt/', 'adjective', 'C1', 'Having a strong odor that stings the nose, said especially of acidic or spicy substances.', 'I accidentally dropped the bottle of ammonia and after few seconds, a very pungent stench could be detected.', ARRAY[]::TEXT[]),
('Puny', '/pjuːni/', 'adjective', 'C1', 'Of inferior size, strength or significance; small, weak, ineffective.', 'You puny earthlings are no match for Ming the Merciless!', ARRAY[]::TEXT[]),
('Purity', '/ˈpjɔːɹɪti/', 'noun', 'C1', 'The state or degree of being pure.', '', ARRAY[]::TEXT[]),
('Purlieu', '/ˈpɜːljuː/', 'noun', 'C1', 'The ground on the edges of a forest, especially when partly subject to the same forest laws concerning game hunting etc.', '', ARRAY[]::TEXT[]),
('Purloin', '/pɜːˈlɔɪn/', 'verb', 'C1', 'To take the property of another, often in breach of trust; to appropriate wrongfully; to steal.', '', ARRAY[]::TEXT[]),
('Purvey', '/pəˈveɪ/', 'verb', 'C1', 'To prepare in advance (for or to do something); to plan, make provision.', '', ARRAY[]::TEXT[]),
('Pusillanimous', '/pjuːsəlˈænəməs/', 'adjective', 'C1', 'Showing ignoble cowardice, or contemptible timidity.', '', ARRAY[]::TEXT[]),
('Quack', '/kwæk/', 'verb', 'C1', 'To make a noise like a duck.', 'Do you hear the ducks quack?', ARRAY[]::TEXT[]),
('Quaff', '/kwɒf/', 'verb', 'C1', 'To drink or imbibe with vigour or relish; to drink copiously; to swallow in large draughts.', '', ARRAY[]::TEXT[]),
('Quail', '/ˈkweɪl/', 'verb', 'C2', 'To waste away; to fade, to wither', '', ARRAY[]::TEXT[]),
('Quarantine', '/ˈkwɒɹ.ən.taɪn/', 'noun', 'C1', 'The desert in which Christ fasted for 40 days according to the Bible.', '', ARRAY[]::TEXT[]),
('Quarry', '/ˈkwɒɹi/', 'verb', 'C1', 'To obtain (or mine) stone by extraction from a quarry.', 'They quarried out new, interesting facts about ancient Egypt from old papyri.', ARRAY['dig','dig up','unearth','mine']::TEXT[]),
('Quash', '/kwɒʃ/', 'verb', 'C1', 'To defeat decisively.', 'The army quashed the rebellion.', ARRAY[]::TEXT[]),
('Quaver', '/ˈkweɪvə(ɹ)/', 'verb', 'C1', 'To shake in a trembling manner.', '', ARRAY[]::TEXT[]),
('Quell', '/kwɛl/', 'verb', 'C1', 'To subdue, to put down; to silence or force (someone) to submit.', 'to quell grief', ARRAY[]::TEXT[]),
('Quench', '/kwɛnt͡ʃ/', 'verb', 'C1', 'To satisfy, especially an actual or figurative thirst.', 'The library quenched her thirst for knowledge.', ARRAY['appease','slake','appease','slake']::TEXT[]),
('Quibble', '/ˈkwɪbəl/', 'verb', 'C1', 'To complain or argue in a trivial or petty manner.', 'They are constantly quibbling over insignificant details.', ARRAY[]::TEXT[]),
('Quiescent', '/ˈkwaɪ̯.ɛsn̩t/', 'adjective', 'C1', 'Inactive, quiet, at rest.', 'The bats were quiescent at that time of day, so we slowly entered the cave.', ARRAY['dormant','servile','calm','still','tranquil']::TEXT[]),
('Quixotic', '/kwɪkˈsɒtɪk/', 'adjective', 'C2', 'Possessing or acting with the desire to do noble and romantic deeds, without thought of realism and practicality; exceedingly idealistic.', '', ARRAY[]::TEXT[]),
('Rabble', '/ˈɹæbəl/', 'verb', 'C1', 'To speak in a confused manner; talk incoherently; utter nonsense', '', ARRAY[]::TEXT[]),
('Rabid', '/ˈɹeɪbɪd/', 'adjective', 'C1', 'Affected with rabies.', 'a rabid socialist', ARRAY[]::TEXT[]),
('Raconteur', '/ˌɹæk.ɒnˈtəː/', 'verb', 'C2', 'To make witty remarks or stories.', '', ARRAY[]::TEXT[]),
('Ream', '/ɹiːm/', 'verb', 'C1', 'To cream; mantle; foam; froth.', '', ARRAY[]::TEXT[]),
('Reap', '/ɹiːp/', 'verb', 'C1', 'To cut (for example a grain) with a sickle, scythe, or reaping machine', 'to reap a benefit from exertions', ARRAY[]::TEXT[]),
('Rebuff', '/ɹɪˈbʌf/', 'verb', 'C1', 'To refuse; to offer sudden or harsh resistance; to turn down or shut out.', '', ARRAY[]::TEXT[]),
('Recalcitrant', '/ɹɪ.ˈkæl.sɪ.tɹənt/', 'adjective', 'C1', 'Marked by a stubborn unwillingness to obey authority.', '', ARRAY['adversarial','intransigent','obstreperous','stubborn','unruly']::TEXT[]),
('Recant', '/ɹəˈkænt/', 'verb', 'C1', 'To withdraw or repudiate a statement or opinion formerly expressed, especially formally and publicly.', 'Convince me that I am wrong, and I will recant.', ARRAY['abjure','disavow','disown','recall','retract']::TEXT[]),
('Recessive', '', 'adjective', 'C1', 'Going back; receding.', '', ARRAY[]::TEXT[]),
('Recidivism', '', 'noun', 'C1', 'Committing new offenses after a crime committed in the past.', 'alcohol(ic) recidivism', ARRAY[]::TEXT[]),
('Reciprocate', '/ɹɪˈsɪpɹəˌkeɪt/', 'verb', 'C1', 'To exchange two things, with both parties giving one thing and taking another thing.', 'I gave them apples from my tree; they reciprocated with a pie and some apple jelly.', ARRAY[]::TEXT[]),
('Reckless', '/ˈɹɛkləs/', 'adjective', 'C1', 'Careless or heedless; headstrong or rash.', '', ARRAY[]::TEXT[]),
('Recluse', '/ɹɪˈkluːs/', 'adjective', 'C1', 'Sequestered; secluded, isolated', 'a recluse monk or hermit', ARRAY['reclusive']::TEXT[]),
('Recoil', '/ˈɹiːkɔɪl/', 'verb', 'C1', 'To pull back, especially in disgust, horror or astonishment.', 'He recoiled in disgust when he saw the mess.', ARRAY[]::TEXT[]),
('Reconnoiter', '/ˌɹɛkəˈnɔɪtə/', 'verb', 'C1', 'To perform a reconnaissance (of an area; an enemy position); to scout with the aim of acquiring information.', 'Our scout will reconnoiter the path ahead of our troops.', ARRAY['scout','survey']::TEXT[]),
('Reconstitute', '/ɹiːˈkɒnstɪtjuːt/', 'verb', 'C1', 'To construct something anew, or in a different manner', '', ARRAY[]::TEXT[]),
('Reconvene', '', 'verb', 'C1', 'To resume something that has been convened and then paused.', 'We will reconvene after lunch to discuss the outstanding points on the agenda.', ARRAY[]::TEXT[]),
('Rectitude', '/ˈɹɛk.tə.tjuːd/', 'noun', 'C1', 'Straightness; the state or quality of having a constant direction and not being crooked or bent.', '', ARRAY['honesty','integrity','morality']::TEXT[]),
('Recumbent', '', 'adjective', 'C1', 'Lying down.', '', ARRAY[]::TEXT[]),
('Recuperate', '/ɹɪˈk(j)uːpəˌɹeɪt/', 'verb', 'C1', 'To recover, especially from an illness; to get better from an illness.', '', ARRAY[]::TEXT[]),
('Redistribution', '/ˌɹiːdɪstɹəˈbjuːʃən/', 'noun', 'C1', 'The act of changing the distribution of resources.', 'The redistribution of wealth between the rich and poor has been tried many times.', ARRAY[]::TEXT[]),
('Redolent', '/ˈɹɛd.əl.ənt/', 'adjective', 'C1', 'Fragrant or aromatic; having a sweet scent.', '', ARRAY['aromatic','fragrant','reeking','smelling','reminiscent']::TEXT[]),
('Redoubtable', '', 'adjective', 'C2', 'Eliciting respect or fear; imposing; awe-inspiring.', 'The redoubtable New York Times has been called the "newspaper of record" of the United States.', ARRAY[]::TEXT[]),
('Redundant', '/ɹɪˈdʌn.dənt/', 'adjective', 'C1', 'Superfluous; exceeding what is necessary.', 'Four employees were made redundant.', ARRAY['surplus to requirements']::TEXT[]),
('Reel', '/ɹiːl/', 'verb', 'C1', 'To wind on a reel.', 'He reeled off some tape from the roll and sealed the package.', ARRAY[]::TEXT[]),
('Refine', '/ɹɪˈfaɪn/', 'verb', 'C1', 'To purify; reduce to a fine, unmixed, or pure state; to free from impurities.', 'to refine gold', ARRAY[]::TEXT[]),
('Refulgent', '/ɹəˈfʌldʒənt/', 'adjective', 'C1', 'Resplendent, or shining brightly and radiantly.', 'She had a refulgent smile.', ARRAY[]::TEXT[]),
('Regenerate', '', 'adjective', 'C1', 'Spiritually reborn.', '', ARRAY[]::TEXT[]),
('Regimen', '/ˈɹɛdʒ.ɪ.mən/', 'noun', 'C1', 'Orderly government; system of order; administration.', '', ARRAY[]::TEXT[]),
('Regress', '', 'verb', 'C1', 'To move backwards to an earlier stage; to devolve.', 'When we regress Y on X, we use the values of variable X to predict those of Y.', ARRAY['backslide']::TEXT[]),
('Rehabilitate', '/ɹiː(h)əˈbɪlɪteɪt/', 'verb', 'C1', 'To restore (someone) to their former state, reputation, possessions, status etc.', '', ARRAY[]::TEXT[]),
('Rehearsal', '/ɹɪˈhɜː(ɹ)səl/', 'noun', 'C1', 'The practicing of something which is to be performed before an audience, usually to test or improve the interaction between several participating people, or to allow technical adjustments with respect to staging to be done.', '', ARRAY[]::TEXT[]),
('Rein', '/ɹeɪn/', 'verb', 'C1', 'To direct or stop a horse by using reins.', '', ARRAY[]::TEXT[]),
('Reiterate', '/ɹiˈɪt.əɹ.eɪt/', 'adjective', 'C1', 'Reiterated; repeated.', '', ARRAY['iterate','iterate']::TEXT[]),
('Rejoice', '/ɹɪˈd͡ʒɔɪs/', 'verb', 'C1', 'To be very happy, be delighted, exult; to feel joy.', '', ARRAY[]::TEXT[]),
('Relapse', '/ɹɪˈlæps/', 'verb', 'C1', 'To fall back again; to slide or turn back into a former state or practice.', 'He has improved recently but keeps relapsing into states of utter confusion.', ARRAY[]::TEXT[]),
('Relent', '/ɹɪˈlɛnt/', 'adjective', 'C1', 'Softhearted; yielding', '', ARRAY[]::TEXT[]),
('Relinquish', '[ɹɪˈlɪŋkwɪʃ]', 'verb', 'C1', 'To give up, abandon or retire from something. To trade away.', 'to relinquish a title', ARRAY[]::TEXT[]),
('Relish', '/ˈɹɛ.lɪʃ/', 'verb', 'C1', 'To taste or eat with pleasure, to like the flavor of', 'He relishes their time together.', ARRAY[]::TEXT[]),
('Remodel', '', 'verb', 'C1', 'To change the appearance, layout, or furnishings of.', '', ARRAY[]::TEXT[]),
('Remonstrance', '', 'noun', 'C1', 'A remonstration; disapproval; a formal, usually written, objection or protest.', '', ARRAY[]::TEXT[]),
('Remorse', '/ɹɪˈmɔː(ɹ)s/', 'noun', 'C1', 'A feeling of regret or sadness for doing wrong or sinning.', '', ARRAY['agenbite','compunction','contrition','penitence','repentance']::TEXT[]),
('Remunerate', '/ɹɪˈmjuːnəɹeɪt/', 'verb', 'C1', 'To compensate; to pay.', 'The workers were generously remunerated for their time.', ARRAY[]::TEXT[]),
('Rend', '', 'verb', 'C1', 'To separate into parts with force or sudden violence; to split; to burst', 'Lightning rends an oak.', ARRAY[]::TEXT[]),
('Renegade', '/ˈɹɛnəˌɡeɪd/', 'verb', 'C1', 'To desert one''''s cause, or change one''''s loyalties; to commit betrayal.', '', ARRAY[]::TEXT[]),
('Renounce', '/ɹɪˈnaʊns/', 'verb', 'C1', 'To give up, resign, surrender, atsake.', 'to renounce a title to land or to a throne', ARRAY['forsay','forswear']::TEXT[]),
('Renovate', '/ˈɹenəʊveɪt/', 'verb', 'C1', 'To renew; to revamp something to make it look new again.', '', ARRAY[]::TEXT[]),
('Repartee', '/ˌɹɛpɑːˈtiː/', 'verb', 'C1', 'To reply with a repartee', '', ARRAY[]::TEXT[]),
('Repatriate', '/ɹiːˈpeɪ.tɹi.eɪt/', 'verb', 'C1', 'To restore (a person) to his or her own country.', '', ARRAY[]::TEXT[]),
('Repeal', '/ɹəˈpiːl/', 'verb', 'C1', 'To cancel, invalidate, annul.', 'to repeal a law', ARRAY['annul','cancel','invalidate','revoke','veto']::TEXT[]),
('Repel', '/ɹɪˈpɛl/', 'verb', 'C1', 'To turn (someone) away from a privilege, right, job, etc.', '', ARRAY['withdrive']::TEXT[]),
('Repertoire', '/ˈɹɛp.ə.twɑː/', 'noun', 'C1', 'A list of dramas, operas, pieces, parts, etc., which a company or a person has rehearsed and is prepared to perform or display.', 'The conjurer expanded his repertoire with some new tricks.', ARRAY[]::TEXT[]),
('Retinue', '/ˈɹɛt.ɪ.njuː/', 'noun', 'C1', 'A group of servants or attendants, especially of someone considered important.', 'the queen’s retinues', ARRAY[]::TEXT[]),
('Retort', '/ɹɪˈtɔːt/', 'verb', 'C1', 'To say something sharp or witty in answer to a remark or accusation.', 'to retort the charge of vanity', ARRAY['back answer','comeback','rejoinder']::TEXT[]),
('Retouch', '/ɹɪˈtʌt͡ʃ/', 'verb', 'C1', 'To improve something (especially a photograph), by adding or correcting details, or by removing flaws.', '', ARRAY[]::TEXT[]),
('Retrench', '', 'verb', 'C1', 'To dig or redig a trench where one already exists.', '', ARRAY[]::TEXT[]),
('Retribution', '/ˌɹɛtɹɪˈbjuʃən/', 'noun', 'C1', 'Punishment inflicted in the spirit of moral outrage or personal vengeance.', '', ARRAY[]::TEXT[]),
('Retrograde', '/ˈɹɛtɹəˌɡɹeɪd/', 'adjective', 'C1', 'Directed backwards, retreating; reverting, especially to an inferior state, declining; inverse, reverse; movement opposite to normal or intended motion, often circular motion.', 'retrograde ideas, morals, etc.', ARRAY['reactionary','traditionalist']::TEXT[]),
('Retrospective', '/ˌɹɛtɹə(ʊ)ˈspɛktɪv/', 'adjective', 'C1', 'Of, relating to, or contemplating the past.', '', ARRAY['hindsightly']::TEXT[]),
('Revelry', '[ˈɹɛv.əɫ.ɹi]', 'noun', 'C1', 'Joyful or riotous merry-making.', '', ARRAY['celebration','festivity','revelment']::TEXT[]),
('Revere', '/ɹə.viːɹ/', 'verb', 'C1', 'To regard someone or something with great awe or devotion.', '', ARRAY['respect','venerate']::TEXT[]),
('Revoke', '', 'verb', 'C1', 'To cancel or invalidate by withdrawing or reversing.', 'I hereby revoke all former wills.', ARRAY['draw back','withdraw','recall','recollect','remember']::TEXT[]),
('Revolt', '/ɹɪˈvɒlt/', 'verb', 'C1', 'To rebel, particularly against authority.', 'The farmers had to revolt against the government to get what they deserved.', ARRAY[]::TEXT[]),
('Ribald', '/ˈɹɪb.əld/', 'adjective', 'C2', 'Coarsely, vulgarly, or lewdly amusing; referring to sexual matters in a rude or irreverent way.', '', ARRAY[]::TEXT[]),
('Rickety', '/ˈɹɪk.e.ti/', 'adjective', 'C1', 'Of an object: not strong or sturdy, as because of poor construction or upkeep; not safe or secure.', 'He hesitated about climbing such a small, rickety ladder.', ARRAY['giddy','precarious','shaky','tottering','unsafe']::TEXT[]),
('Rider', '/ˈɹaɪ.də(ɹ)/', 'noun', 'C1', 'One who rides, often on a horse or a motorcycle.', '', ARRAY[]::TEXT[]),
('Ridicule', '/ˈɹɪdɪkjuːl/', 'verb', 'C1', 'To criticize or disapprove of someone or something through scornful jocularity; to make fun of', 'His older sibling constantly ridiculed him with sarcastic remarks.', ARRAY['outlaugh']::TEXT[]),
('Rife', '/ɹaɪf/', 'adjective', 'C1', 'Widespread, common, prevalent, current (mainly of unpleasant or harmful things).', 'Smallpox was rife after the siege had been lifted.', ARRAY['filled','pandemic','ubiquitous']::TEXT[]),
('Rift', '/ɹɪft/', 'verb', 'C1', 'To form a rift; to split open.', 'to rift an oak', ARRAY[]::TEXT[]),
('Ripen', '/ˈɹaɪpən/', 'verb', 'C1', 'To grow ripe; to become mature (said of grain, fruit, flowers etc.)', 'Grapes ripen in the sun.', ARRAY[]::TEXT[]),
('Rite', '/ɹaɪt/', 'noun', 'C1', 'A religious custom.', '', ARRAY[]::TEXT[]),
('Rive', '/ɹaɪv/', 'verb', 'C1', 'To tear apart by force; to rend; to split; to cleave.', '', ARRAY['cleave','rend','split']::TEXT[]),
('Riveting', '', 'adjective', 'C1', 'Commanding the attention of spectators.', '', ARRAY[]::TEXT[]),
('Rivulet', '/ˈɹɪv.jə.lət/', 'noun', 'C1', 'A small brook or stream; a streamlet.', 'A rivulet of tears ran down his face.', ARRAY[]::TEXT[]),
('Rodent', '/ˈɹəʊdənt/', 'adjective', 'C1', 'Gnawing; biting; corroding; applied to a destructive variety of cancer or ulcer.', '', ARRAY[]::TEXT[]),
('Roil', '/ɹɔɪl/', 'verb', 'C1', 'To render turbid by stirring up the dregs or sediment of.', 'To roil a spring.', ARRAY['agitate','irritate','rile','agitate','irritate']::TEXT[]),
('Roister', '/ˈɹɔɪstə(ɹ)/', 'verb', 'C1', 'To engage in noisy, drunken, or riotous behavior.', '', ARRAY['carouse','revel','riot','swagger']::TEXT[])
ON CONFLICT (word) DO NOTHING;
