INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Highly', 'highly_us.mp3', 'adverb', 'B1', 'very', '', 'It is highly unlikely that she''ll be late.', '', ARRAY[]::TEXT[]),
('Highway', 'highway_us.mp3', 'noun', 'B1', 'a main road for travelling long distances, especially one connecting and going through cities and towns', '', 'Plans were being made for the construction of a new interstate highway system.', '', ARRAY[]::TEXT[]),
('Hilarious', 'hilarious_us.mp3', 'adjective', 'B1', 'extremely funny', '', 'a hilarious joke/story', '', ARRAY[]::TEXT[]),
('Hill', 'hill_us.mp3', 'noun', 'B1', 'an area of land that is higher than the land around it, but not as high as a mountain', '', 'a region of gently rolling hills', '', ARRAY[]::TEXT[]),
('Him', 'him_us.mp3', 'pronoun', 'B1', 'used as the object of a verb, after the verb be or after a preposition to refer to a male person or animal that has already been mentioned or is easily identified', '', 'When did you see him?', '', ARRAY[]::TEXT[]),
('Himself', 'himself_us.mp3', 'pronoun', 'B1', 'used when the man or boy who performs an action is also affected by it', '', 'He introduced himself.', '', ARRAY[]::TEXT[]),
('Hint', 'hint_us.mp3', 'noun', 'B1', 'something that you say or do in an indirect way in order to show somebody what you are thinking', '', 'He gave a broad hint (= one that was obvious) that he was thinking of retiring.', '', ARRAY[]::TEXT[]),
('Hint', 'hint_us.mp3', 'verb', 'B1', 'to suggest something in an indirect way', '', 'hint at something, What are you hinting at?', '', ARRAY[]::TEXT[]),
('Hip', 'hip_us.mp3', 'noun', 'B1', 'the area at either side of the body between the top of the leg and the middle part of the body; the joint at the top of the leg that connects it with the top part of the body', '', 'She stood with her hands on her hips.', '', ARRAY[]::TEXT[]),
('Hire', 'hire_us.mp3', 'noun', 'B1', 'the act of paying to use something for a short time', '', 'a hire car', '', ARRAY[]::TEXT[]),
('Hire', 'hire_us.mp3', 'verb', 'B1', 'to give somebody a job', '', 'She was hired three years ago.', '', ARRAY[]::TEXT[]),
('His', 'his_us.mp3', 'determiner', 'B1', 'of or belonging to a man or boy who has already been mentioned or is easily identified', '', 'James has sold his car.', '', ARRAY[]::TEXT[]),
('His', 'his_us.mp3', 'pronoun', 'B1', 'of or belonging to him', '', 'He took my hand in his.', '', ARRAY[]::TEXT[]),
('Historian', 'historian_us.mp3', 'noun', 'B1', 'a person who studies or writes about history; an expert in history', '', 'No serious historian today accepts this theory.', '', ARRAY[]::TEXT[]),
('Historic', 'historic_us.mp3', 'adjective', 'B1', 'important in history; likely to be thought of as important at some time in the future', '', 'the restoration of historic buildings', '', ARRAY[]::TEXT[]),
('Historical', 'historical_us.mp3', 'adjective', 'B1', 'connected with the past', '', 'You must place these events in their historical context.', '', ARRAY[]::TEXT[]),
('History', 'history_us.mp3', 'noun', 'B1', 'all the events that happened in the past', '', 'in history, The battle was a turning point in human history.', '', ARRAY[]::TEXT[]),
('Hit', 'hit_us.mp3', 'noun', 'B1', 'an act of hitting somebody/something with your hand or with an object held in your hand', '', 'Give it a good hit.', '', ARRAY[]::TEXT[]),
('Hit', 'hit_us.mp3', 'verb', 'B1', 'to bring your hand, or an object you are holding, against somebody/something quickly and with force', '', 'hit somebody/something, I was afraid he was going to hit me.', '', ARRAY[]::TEXT[]),
('Hobby', 'hobby_us.mp3', 'noun', 'B1', 'an activity that you do for pleasure when you are not working', '', 'Do you have any hobbies?', '', ARRAY[]::TEXT[]),
('Hockey', 'hockey_us.mp3', 'noun', 'B1', 'a game played on a field by two teams of 11 players, with curved sticks and a small hard ball. Teams try to hit the ball into the other team’s goal.', '', 'to play hockey', '', ARRAY[]::TEXT[]),
('Hold', 'hold_us.mp3', 'noun', 'B1', 'the action of holding somebody/something; the way you are holding somebody/something', '', 'hold on somebody/something, His hold on her arm tightened.', '', ARRAY[]::TEXT[]),
('Hold', 'hold_us.mp3', 'verb', 'B1', 'to have somebody/something in your hand, arms, etc.', '', 'hold somebody/something, She was holding a large box.', '', ARRAY[]::TEXT[]),
('Hole', 'hole_us.mp3', 'noun', 'B1', 'a hollow space in something solid or in the surface of something', '', 'He dug a deep hole in the garden.', '', ARRAY[]::TEXT[]),
('Holiday', 'holiday_us.mp3', 'noun', 'B1', 'a period of time when you are not at work or school', '', 'the school/summer/Christmas holidays', '', ARRAY[]::TEXT[]),
('Hollow', 'hollow_us.mp3', 'adjective', 'B1', 'having a hole or empty space inside', '', 'a hollow ball/centre/tube/tree', '', ARRAY[]::TEXT[]),
('Holy', 'holy_us.mp3', 'adjective', 'B1', 'connected with God or a particular religion', '', 'the Holy Bible', '', ARRAY[]::TEXT[]),
('Home', 'home_us.mp3', 'adjective', 'B1', 'connected with the place where you live', '', 'home life (= with your family)', '', ARRAY[]::TEXT[]),
('Home', 'home_us.mp3', 'adverb', 'B1', 'to or at the place where you live', '', 'Come on, it''s time to go home.', '', ARRAY[]::TEXT[]),
('Home', 'home_us.mp3', 'noun', 'B1', 'the house or flat that you live in, especially with your family', '', 'Old people prefer to stay in their own homes.', '', ARRAY[]::TEXT[]),
('Homeland', 'homeland_us.mp3', 'noun', 'B1', 'the country where a person was born', '', 'Many refugees have been forced to flee their homeland.', '', ARRAY[]::TEXT[]),
('Homeless', 'homeless_us.mp3', 'adjective', 'B1', 'having no home, and therefore typically living on the streets', '', 'The scheme has been set up to help homeless people.', '', ARRAY[]::TEXT[]),
('Homework', 'homework_us.mp3', 'noun', 'B1', 'work that is given by teachers for students to do at home', '', 'I always do my homework on the bus.', '', ARRAY[]::TEXT[]),
('Honest', 'honest_us.mp3', 'adjective', 'B1', 'always telling the truth, and never stealing or cheating', '', 'an honest man/woman', '', ARRAY[]::TEXT[]),
('Honesty', 'honesty_us.mp3', 'noun', 'B1', 'the quality of being honest', '', 'She answered all my questions with her usual honesty.', '', ARRAY[]::TEXT[]),
('Honour', 'honour_us.mp3', 'noun', 'B1', 'great respect for somebody', '', 'the guest of honour (= the most important one)', '', ARRAY[]::TEXT[]),
('Honour', 'honour_us.mp3', 'verb', 'B1', 'to do something that shows great respect for somebody/something', '', 'honour somebody/something, our honoured guests', '', ARRAY[]::TEXT[]),
('Hook', 'hook_us.mp3', 'noun', 'B1', 'a curved piece of metal, plastic or wire for hanging things on, catching fish with, etc.', '', 'a picture/curtain/coat hook', '', ARRAY[]::TEXT[]),
('Hook', 'hook_us.mp3', 'verb', 'B1', 'to fasten or hang something on something else using a hook; to be fastened or hanging in this way', '', 'hook something + adv./prep., We hooked the trailer to the back of the car.', '', ARRAY[]::TEXT[]),
('Hope', 'hope_us.mp3', 'noun', 'B1', 'a feeling of wanting and expecting a particular thing to happen; something that you wish for', '', 'Don''t lose hope—we''ll find her.', '', ARRAY[]::TEXT[]),
('Hope', 'hope_us.mp3', 'verb', 'B1', 'to want something to happen and think that it is possible', '', 'All we can do now is wait and hope.', '', ARRAY[]::TEXT[]),
('Hopeful', 'hopeful_us.mp3', 'adjective', 'B1', 'believing that something you want will happen', '', 'hopeful (that…), I feel hopeful that we''ll find a suitable house very soon.', '', ARRAY[]::TEXT[]),
('Hopefully', 'hopefully_us.mp3', 'adverb', 'B1', 'used to express what you hope will happen', '', 'Hopefully, we''ll arrive before dark.', '', ARRAY[]::TEXT[]),
('Horizon', 'horizon_us.mp3', 'noun', 'B1', 'the furthest that you can see, where the sky seems to meet the land or the sea', '', 'The sun sank below the horizon.', '', ARRAY[]::TEXT[]),
('Horn', 'horn_us.mp3', 'noun', 'B1', 'a hard pointed part that grows, usually in pairs, on the heads of some animals, such as sheep and cows. Horns are often curved.', '', 'a large bull with curved horns', '', ARRAY[]::TEXT[]),
('Horrible', 'horrible_us.mp3', 'adjective', 'B1', 'very bad or unpleasant; used to describe something that you do not like', '', 'What horrible weather!', '', ARRAY[]::TEXT[]),
('Horror', 'horror_us.mp3', 'noun', 'B1', 'a feeling of great shock or fear', '', 'The thought of being left alone filled her with horror.', '', ARRAY[]::TEXT[]),
('Horse', 'horse_us.mp3', 'noun', 'B1', 'a large animal with four legs, a mane (= long thick hair on its neck) and a tail. Horses are used for riding on, pulling carriages, etc.', '', 'to ride a horse', '', ARRAY[]::TEXT[]),
('Hospital', 'hospital_us.mp3', 'noun', 'B1', 'a large building where people who are ill or injured are given medical treatment and care', '', 'to/into (the) hospital, (British English), He had to go to/into hospital for treatment.', '', ARRAY[]::TEXT[]),
('Host', 'host_us.mp3', 'noun', 'B1', 'a person who invites guests to a meal, a party, etc. or who has people staying at their house', '', 'Ian, our host, introduced us to the other guests.', '', ARRAY[]::TEXT[]),
('Host', 'host_us.mp3', 'verb', 'B1', 'to organize an event to which others are invited and make all the arrangements for them', '', 'to host an event/a conference/a meeting', '', ARRAY[]::TEXT[]),
('Hostage', 'hostage_us.mp3', 'noun', 'B1', 'a person who is captured and held prisoner by a person or group, and who may be injured or killed if people do not do what the person or group is asking', '', 'Three children were taken hostage during the bank robbery.', '', ARRAY[]::TEXT[]),
('Hostile', 'hostile_us.mp3', 'adjective', 'B1', 'aggressive or unfriendly and ready to argue or fight', '', 'The speaker got a hostile reception from the audience.', '', ARRAY[]::TEXT[]),
('Hostility', 'hostility_us.mp3', 'noun', 'B1', 'aggressive or unfriendly feelings or behaviour', '', 'There was a barely veiled hostility in her tone.', '', ARRAY[]::TEXT[]),
('Hot', 'hot_us.mp3', 'adjective', 'B1', 'having a high temperature; producing heat', '', 'It''s hot today, isn''t it?', '', ARRAY[]::TEXT[]),
('Hotel', 'hotel_us.mp3', 'noun', 'B1', 'a building where people stay, usually for a short time, paying for their rooms and meals', '', 'a two-star/five-star, etc. hotel', '', ARRAY[]::TEXT[]),
('Hour', 'hour_us.mp3', 'noun', 'B1', '60 minutes; one of the 24 parts that a day is divided into', '', 'I spent an hour on the phone.', '', ARRAY[]::TEXT[]),
('House', 'house_us.mp3', 'noun', 'B1', 'a building for people to live in, usually for one family', '', 'in a house, We live in a two-bedroom house.', '', ARRAY[]::TEXT[]),
('House', 'house_us.mp3', 'verb', 'B1', 'to provide a place for a person or an animal to live', '', 'The government is committed to housing the refugees.', '', ARRAY[]::TEXT[]),
('Household', 'household_us.mp3', 'noun', 'B1', 'all the people living together in a house or flat', '', 'Most households now own at least one car.', '', ARRAY[]::TEXT[]),
('Housing', 'housing_us.mp3', 'noun', 'B1', 'houses, flats, etc. that people live in, especially when referring to their type, price or condition', '', 'rental/student housing', '', ARRAY[]::TEXT[]),
('How', 'how_us.mp3', 'adverb', 'B1', 'in what way or manner', '', 'How does it work?', '', ARRAY[]::TEXT[]),
('However', 'however_us.mp3', 'adverb', 'B1', 'used to introduce a statement that contrasts with something that has just been said', '', 'He was feeling bad. He went to work, however, and tried to concentrate.', '', ARRAY[]::TEXT[]),
('Huge', 'huge_us.mp3', 'adjective', 'B1', 'extremely large in size or amount; great in degree', '', 'The sums of money involved are potentially huge.', '', ARRAY[]::TEXT[]),
('Human', 'human_us.mp3', 'adjective', 'B1', 'of or connected with people rather than animals, machines or gods', '', 'the human body/brain', '', ARRAY[]::TEXT[]),
('Human', 'human_us.mp3', 'noun', 'B1', 'a person rather than an animal or a machine', '', 'Dogs can hear much better than humans.', '', ARRAY[]::TEXT[]),
('Humanitarian', 'humanitarian_us.mp3', 'adjective', 'B1', 'connected with helping people who are suffering and improving the conditions that they are living in', '', 'to provide humanitarian aid to the war zone', '', ARRAY[]::TEXT[]),
('Humanity', 'humanity_us.mp3', 'noun', 'B1', 'people in general', '', 'He was found guilty of crimes against humanity.', '', ARRAY[]::TEXT[]),
('Humble', 'humble_us.mp3', 'adjective', 'B1', 'showing you do not think that you are as important as other people', '', 'Be humble enough to learn from your mistakes.', '', ARRAY[]::TEXT[]),
('Humorous', 'humorous_us.mp3', 'adjective', 'B1', 'funny; showing a sense of humour', '', 'He gave a humorous account of their trip to Spain.', '', ARRAY[]::TEXT[]),
('Humour', 'humour_us.mp3', 'noun', 'B1', 'the quality in something that makes it funny; the ability to laugh at things that are funny', '', 'It was a story full of gentle humour.', '', ARRAY[]::TEXT[]),
('Hundred', 'hundred_us.mp3', 'number', 'B1', '100', '', 'One hundred (of the children) have already been placed with foster families.', '', ARRAY[]::TEXT[]),
('Hunger', 'hunger_us.mp3', 'noun', 'B1', 'the state of not having enough food to eat, especially when this causes illness or death', '', 'Around fifty people die of hunger every day in the camp.', '', ARRAY[]::TEXT[]),
('Hungry', 'hungry_us.mp3', 'adjective', 'B1', 'feeling that you want to eat something', '', 'I''m really hungry.', '', ARRAY[]::TEXT[]),
('Hunt', 'hunt_us.mp3', 'noun', 'B1', 'an act of looking for somebody/something that is difficult to find', '', 'The hunt is on for a suitable candidate.', '', ARRAY[]::TEXT[]),
('Hunt', 'hunt_us.mp3', 'verb', 'B1', 'to go after wild animals in order to catch or kill them for food, sport or to make money', '', 'Lions sometimes hunt alone.', '', ARRAY[]::TEXT[]),
('Hunting', 'hunting_us.mp3', 'noun', 'B1', 'going after and killing wild animals as a sport or for food', '', 'He goes hunting every weekend.', '', ARRAY[]::TEXT[]),
('Hurricane', 'hurricane_us.mp3', 'noun', 'B1', 'a violent storm with very strong winds, especially in the western Atlantic Ocean', '', 'A powerful hurricane hit the Florida coast.', '', ARRAY[]::TEXT[]),
('Hurry', 'hurry_us.mp3', 'noun', 'B1', 'the need or wish to get something done quickly', '', 'Take your time—there''s no hurry.', '', ARRAY[]::TEXT[]),
('Hurry', 'hurry_us.mp3', 'verb', 'B1', 'to move or act quickly because there is not much time', '', 'You''ll have to hurry if you want to catch that train.', '', ARRAY[]::TEXT[]),
('Hurt', 'hurt_us.mp3', 'adjective', 'B1', 'injured physically', '', 'None of the passengers were badly hurt.', '', ARRAY[]::TEXT[]),
('Hurt', 'hurt_us.mp3', 'noun', 'B1', 'a feeling of unhappiness because somebody has been unkind or unfair to you', '', 'There was hurt and real anger in her voice.', '', ARRAY[]::TEXT[]),
('Hurt', 'hurt_us.mp3', 'verb', 'B1', 'to cause physical pain to somebody/yourself; to injure somebody/yourself', '', 'hurt something, He hurt his back playing squash.', '', ARRAY[]::TEXT[]),
('Husband', 'husband_us.mp3', 'noun', 'B1', 'the man that somebody is married to; a married man', '', 'This is my husband, Steve.', '', ARRAY[]::TEXT[]),
('Hypothesis', 'hypothesis_us.mp3', 'noun', 'B1', 'an idea or explanation of something that is based on a few known facts but that has not yet been proved to be true or correct', '', 'to formulate/confirm a hypothesis', '', ARRAY[]::TEXT[]),
('I', 'I_us.mp3', 'pronoun', 'B1', 'used as the subject of a verb when the speaker or writer is referring to himself/herself', '', 'I think I''d better go now.', '', ARRAY[]::TEXT[]),
('Ice', 'ice_us.mp3', 'noun', 'B1', 'water that has frozen and become solid', '', 'There was ice on the windows.', '', ARRAY[]::TEXT[]),
('Ice cream', 'ice cream_us.mp3', 'noun', 'B1', 'a type of sweet frozen food made from milk fat, tasting of fruit, chocolate, etc. and often eaten as a dessert; a small amount of this food intended for one person, often served in a container made of biscuit that is like a cone in shape', '', 'Desserts are served with cream or ice cream.', '', ARRAY[]::TEXT[]),
('Icon', 'icon_us.mp3', 'noun', 'B1', 'a small symbol on a computer or smartphone screen that represents a program or a file', '', 'Click on the printer icon with the mouse.', '', ARRAY[]::TEXT[]),
('ID', 'ID_us.mp3', 'noun', 'B1', 'an official way of showing who you are, for example a document with your name, date of birth and often a photograph on it (the abbreviation for ‘identity’ or ‘identification’)', '', 'You must carry ID at all times.', '', ARRAY[]::TEXT[]),
('Idea', 'idea_us.mp3', 'noun', 'B1', 'a plan, thought or suggestion, especially about what to do in a particular situation', '', 'It would be a good idea to call before we leave.', '', ARRAY[]::TEXT[]),
('Ideal', 'ideal_us.mp3', 'adjective', 'B1', 'perfect; most suitable', '', 'an ideal location/place', '', ARRAY[]::TEXT[]),
('Ideal', 'ideal_us.mp3', 'noun', 'B1', 'an idea or standard that seems perfect, and worth trying to achieve or obtain', '', 'He was accused of betraying his political ideals.', '', ARRAY[]::TEXT[]),
('Identical', 'identical_us.mp3', 'adjective', 'B1', 'similar in every detail', '', 'a row of identical houses', '', ARRAY[]::TEXT[]),
('Identification', 'identification_us.mp3', 'noun', 'B1', 'the process of showing, proving or recognizing who or what somebody/something is', '', 'The identification of the crash victims was a long and difficult task.', '', ARRAY[]::TEXT[]),
('Identify', 'identify_us.mp3', 'verb', 'B1', 'to recognize somebody/something and be able to say who or what they are', '', 'identify somebody/something, She was able to identify her attacker.', '', ARRAY[]::TEXT[]),
('Identity', 'identity_us.mp3', 'noun', 'B1', 'who or what somebody/something is', '', 'The police are trying to discover the identity of the killer.', '', ARRAY[]::TEXT[]),
('Ideological', 'ideological_us.mp3', 'adjective', 'B1', 'based on or connected with an ideology', '', 'ideological differences', '', ARRAY[]::TEXT[]),
('Ideology', 'ideology_us.mp3', 'noun', 'B1', 'a set of ideas that an economic or political system is based on', '', 'Marxist/capitalist ideology', '', ARRAY[]::TEXT[]),
('Idiot', 'idiot_us.mp3', 'noun', 'B1', 'a rude way to refer to somebody who you think is very stupid', '', 'When I lost my passport, I felt such an idiot.', '', ARRAY[]::TEXT[]),
('If', 'if_us.mp3', 'conjunction', 'B1', 'used to say that one thing can, will or might happen or be true, depending on another thing happening or being true', '', 'If you see him, give him this note.', '', ARRAY[]::TEXT[]),
('Ignorance', 'ignorance_us.mp3', 'noun', 'B1', 'a lack of knowledge or information about something', '', 'They fought a long battle against prejudice and ignorance.', '', ARRAY[]::TEXT[]),
('Ignore', 'ignore_us.mp3', 'verb', 'B1', 'to pay no attention to something', '', 'He ignored all the ‘No Smoking’ signs and lit up a cigarette.', '', ARRAY[]::TEXT[]),
('Ill', 'ill_us.mp3', 'adjective', 'B1', 'suffering from an illness or disease; not feeling well', '', 'Her father is seriously ill in St Luke''s hospital.', '', ARRAY[]::TEXT[]),
('Illegal', 'illegal_us.mp3', 'adjective', 'B1', 'not allowed by the law', '', 'illegal drugs/firearms/substances', '', ARRAY[]::TEXT[]),
('Illness', 'illness_us.mp3', 'noun', 'B1', 'the state of being physically or mentally ill', '', 'The virus can cause illness in humans.', '', ARRAY[]::TEXT[]),
('Illusion', 'illusion_us.mp3', 'noun', 'B1', 'a false idea or belief, especially about somebody or about a situation', '', 'under the illusion that…, She''s under the illusion that (= believes wrongly that) she''ll get the job.', '', ARRAY[]::TEXT[]),
('Illustrate', 'illustrate_us.mp3', 'verb', 'B1', 'to use pictures, photographs, diagrams, etc. in a book, etc.', '', 'illustrate something, She illustrated her own books.', '', ARRAY[]::TEXT[]),
('Illustration', 'illustration_us.mp3', 'noun', 'B1', 'a drawing or picture in a book, magazine, for decoration or to explain something', '', '50 full-colour illustrations', '', ARRAY[]::TEXT[]),
('Image', 'image_us.mp3', 'noun', 'B1', 'a picture, photograph or statue that represents somebody/something', '', 'Most simple leaflets will include text and images.', '', ARRAY[]::TEXT[]),
('Imagery', 'imagery_us.mp3', 'noun', 'B1', 'language that produces pictures in the minds of people reading or listening', '', 'poetic imagery', '', ARRAY[]::TEXT[]),
('Imaginary', 'imaginary_us.mp3', 'adjective', 'B1', 'existing only in your mind or imagination', '', 'The equator is an imaginary line around the middle of the earth.', '', ARRAY[]::TEXT[]),
('Imagination', 'imagination_us.mp3', 'noun', 'B1', 'the ability to create pictures in your mind; the part of your mind that does this', '', 'a vivid/fertile imagination', '', ARRAY[]::TEXT[]),
('Imagine', 'imagine_us.mp3', 'verb', 'B1', 'to form a picture in your mind of what something might be like', '', 'imagine something, The house was just as she had imagined it.', '', ARRAY[]::TEXT[]),
('Immediate', 'immediate_us.mp3', 'adjective', 'B1', 'happening or done without delay', '', 'an immediate reaction/response', '', ARRAY[]::TEXT[]),
('Immediately', 'immediately_us.mp3', 'adverb', 'B1', 'without delay', '', 'She answered almost immediately.', '', ARRAY[]::TEXT[]),
('Immense', 'immense_us.mp3', 'adjective', 'B1', 'extremely large or great', '', 'There is still an immense amount of work to be done.', '', ARRAY[]::TEXT[]),
('Immigrant', 'immigrant_us.mp3', 'noun', 'B1', 'a person who has come to live permanently in a different country from the one they were born in', '', 'immigrant from…, immigrants from other European countries', '', ARRAY[]::TEXT[]),
('Immigration', 'immigration_us.mp3', 'noun', 'B1', 'the process of coming to live permanently in a different country from the one you were born in; the number of people who do this', '', 'legal/illegal immigration', '', ARRAY[]::TEXT[]),
('Imminent', 'imminent_us.mp3', 'adjective', 'B1', 'likely to happen very soon', '', 'the imminent threat of invasion', '', ARRAY[]::TEXT[]),
('Immune', 'immune_us.mp3', 'adjective', 'B1', 'that cannot catch or be affected by a particular disease or illness', '', 'Adults are often immune to German measles.', '', ARRAY[]::TEXT[]),
('Impact', 'impact_us.mp3', 'noun', 'B1', 'the powerful effect that something has on somebody/something', '', 'a positive/a negative/an adverse impact', '', ARRAY[]::TEXT[]),
('Impact', 'impact_us.mp3', 'verb', 'B1', 'to have an effect on somebody/something', '', 'impact on/upon somebody/something, Her father''s death impacted greatly on her childhood years.', '', ARRAY[]::TEXT[]),
('Impatient', 'impatient_us.mp3', 'adjective', 'B1', 'annoyed by somebody/something, especially because you have to wait for a long time', '', 'I''d been waiting for twenty minutes and I was getting impatient.', '', ARRAY[]::TEXT[]),
('Implement', 'implement_us.mp3', 'verb', 'B1', 'to make something that has been officially decided start to happen or be used', '', 'to implement changes/decisions/policies/reforms', '', ARRAY[]::TEXT[]),
('Implementation', 'implementation_us.mp3', 'noun', 'B1', 'the act of making something that has been officially decided start to happen or be used', '', 'the implementation of the new system', '', ARRAY[]::TEXT[]),
('Implication', 'implication_us.mp3', 'noun', 'B1', 'a possible effect or result of an action or a decision', '', 'They failed to consider the wider implications of their actions.', '', ARRAY[]::TEXT[]),
('Imply', 'imply_us.mp3', 'verb', 'B1', 'to suggest that something is true or that you feel or think something, without saying so directly', '', 'imply (that)…, Are you implying (that) I am wrong?', '', ARRAY[]::TEXT[]),
('Import', 'import_us.mp3', 'noun', 'B1', 'a product or service that is brought into one country from another', '', 'import from…, food imports from abroad', '', ARRAY[]::TEXT[]),
('Import', 'import_us.mp3', 'verb', 'B1', 'to bring a product, a service, an idea, etc. into one country from another', '', 'import something, The country has to import most of its raw materials.', '', ARRAY[]::TEXT[]),
('Importance', 'importance_us.mp3', 'noun', 'B1', 'the quality of being important', '', 'She stressed the importance of careful preparation.', '', ARRAY[]::TEXT[]),
('Important', 'important_us.mp3', 'adjective', 'B1', 'having a great effect on people or things; of great value', '', 'an important issue/question/point/factor', '', ARRAY[]::TEXT[]),
('Impose', 'impose_us.mp3', 'verb', 'B1', 'to introduce a new law, rule, tax, etc.; to order that a rule, punishment, etc. be used', '', 'impose something, The UN Security Council imposed sanctions in 1992.', '', ARRAY[]::TEXT[]),
('Impossible', 'impossible_us.mp3', 'adjective', 'B1', 'that cannot exist or be done; not possible', '', 'almost/virtually/nearly impossible', '', ARRAY[]::TEXT[]),
('Impress', 'impress_us.mp3', 'verb', 'B1', 'if a person or thing impresses you, you admire them or it', '', 'impress (somebody), We interviewed a number of candidates but none of them impressed us.', '', ARRAY[]::TEXT[]),
('Impressed', 'impressed_us.mp3', 'adjective', 'B1', 'admiring somebody/something because you think they are particularly good, interesting, etc.', '', 'I must admit I am impressed.', '', ARRAY[]::TEXT[]),
('Impression', 'impression_us.mp3', 'noun', 'B1', 'an idea, a feeling or an opinion that you get about somebody/something, or that somebody/something gives you', '', 'My first impression of him was favourable.', '', ARRAY[]::TEXT[]),
('Impressive', 'impressive_us.mp3', 'adjective', 'B1', 'making you admire them, because they are very large, good, skilful, etc.', '', 'an impressive performance', '', ARRAY[]::TEXT[]),
('Imprison', 'imprison_us.mp3', 'verb', 'B1', 'to put somebody in a prison or another place from which they cannot escape', '', 'be imprisoned (for something), They were imprisoned for possession of drugs.', '', ARRAY[]::TEXT[]),
('Imprisonment', 'imprisonment_us.mp3', 'noun', 'B1', 'the act of putting somebody in a prison or another place from which they cannot escape; the state of being there', '', 'to be sentenced to life imprisonment for murder', '', ARRAY[]::TEXT[]),
('Improve', 'improve_us.mp3', 'verb', 'B1', 'to become better than before; to make something/somebody better than before', '', 'Overall the situation has improved dramatically.', '', ARRAY[]::TEXT[]),
('Improvement', 'improvement_us.mp3', 'noun', 'B1', 'the act of making something better; the process of something becoming better', '', 'The economy has shown significant improvement over the past 9 months.', '', ARRAY[]::TEXT[]),
('In', 'in_us.mp3', 'adverb', 'B1', 'into an object, an area or a substance', '', 'She opened the door and went in.', '', ARRAY[]::TEXT[]),
('In', 'in_us.mp3', 'preposition', 'B1', 'at a point within an area or a space', '', 'a country in Africa', '', ARRAY[]::TEXT[]),
('Inability', 'inability_us.mp3', 'noun', 'B1', 'the fact of not being able to do something', '', 'the government’s inability to provide basic services', '', ARRAY[]::TEXT[]),
('Inadequate', 'inadequate_us.mp3', 'adjective', 'B1', 'not enough; not good enough', '', 'inadequate supplies', '', ARRAY[]::TEXT[]),
('Inappropriate', 'inappropriate_us.mp3', 'adjective', 'B1', 'not suitable or appropriate in a particular situation', '', 'inappropriate behaviour/language', '', ARRAY[]::TEXT[]),
('Incentive', 'incentive_us.mp3', 'noun', 'B1', 'something that encourages you to do something', '', 'There is no incentive for people to save fuel.', '', ARRAY[]::TEXT[]),
('Inch', 'inch_us.mp3', 'noun', 'B1', 'a unit for measuring length or height, equal to 2.54 centimetres. There are 12 inches in a foot.', '', 'She''s a few inches taller than me.', '', ARRAY[]::TEXT[]),
('Incidence', 'incidence_us.mp3', 'noun', 'B1', 'the extent to which something happens or has an effect', '', 'an area with a high incidence of crime', '', ARRAY[]::TEXT[]),
('Incident', 'incident_us.mp3', 'noun', 'B1', 'something that happens, especially something unusual or unpleasant', '', 'His bad behaviour was just an isolated incident.', '', ARRAY[]::TEXT[]),
('Inclined', 'inclined_us.mp3', 'adjective', 'B1', 'wanting to do something', '', 'She was inclined to trust him.', '', ARRAY[]::TEXT[]),
('Include', 'include_us.mp3', 'verb', 'B1', 'if one thing includes another, it has the second thing as one of its parts', '', 'include something, The tour included a visit to the Science Museum.', '', ARRAY[]::TEXT[]),
('Included', 'included_us.mp3', 'adjective', 'B1', 'contained as part of something', '', 'all of Europe (Britain included)', '', ARRAY[]::TEXT[]),
('Including', 'including_us.mp3', 'preposition', 'B1', 'having something as part of a group or set', '', 'I''ve got three days'' holiday including New Year''s Day.', '', ARRAY[]::TEXT[]),
('Inclusion', 'inclusion_us.mp3', 'noun', 'B1', 'the fact of including somebody/something; the fact of being included', '', 'His inclusion in the team is in doubt.', '', ARRAY[]::TEXT[]),
('Income', 'income_us.mp3', 'noun', 'B1', 'the money that a person, a region, a country, etc. earns from work, from investing money, from business, etc.', '', 'Average household income fell slightly.', '', ARRAY[]::TEXT[]),
('Incorporate', 'incorporate_us.mp3', 'verb', 'B1', 'to include something so that it forms a part of something', '', 'incorporate something, The new car design incorporates all the latest safety features.', '', ARRAY[]::TEXT[]),
('Incorrect', 'incorrect_us.mp3', 'adjective', 'B1', 'not accurate or true', '', 'incorrect information/spelling', '', ARRAY[]::TEXT[]),
('Increase', 'increase_us.mp3', 'noun', 'B1', 'a rise in the amount, number or value of something', '', 'price/tax/wage increases', '', ARRAY[]::TEXT[]),
('Increase', 'increase_us.mp3', 'verb', 'B1', 'to become greater in amount, number, value, etc.; to make something greater in amount, number, value, etc.', '', 'Costs have increased significantly.', '', ARRAY[]::TEXT[]),
('Increasingly', 'increasingly_us.mp3', 'adverb', 'B1', 'more and more all the time', '', 'Tourism is playing an increasingly important role in the region''s economy', '', ARRAY[]::TEXT[]),
('Incredible', 'incredible_us.mp3', 'adjective', 'B1', 'impossible or very difficult to believe', '', 'an incredible story', '', ARRAY[]::TEXT[]),
('Incredibly', 'incredibly_us.mp3', 'adverb', 'B1', 'extremely', '', 'It was all incredibly difficult.', '', ARRAY[]::TEXT[]),
('Incur', 'incur_us.mp3', 'verb', 'B1', 'if you incur something unpleasant, you are in a situation in which you have to deal with it', '', 'She had incurred the wrath of her father by marrying without his consent.', '', ARRAY[]::TEXT[]),
('Indeed', 'indeed_us.mp3', 'adverb', 'B1', 'used after very and an adjective or adverb to emphasize a statement, description, etc.', '', 'Thank you very much indeed!', '', ARRAY[]::TEXT[]),
('Independence', 'independence_us.mp3', 'noun', 'B1', 'freedom from political control by other countries', '', 'Cuba gained independence from Spain in 1898.', '', ARRAY[]::TEXT[]),
('Independent', 'independent_us.mp3', 'adjective', 'B1', 'having its own government', '', 'an independent state/nation/country', '', ARRAY[]::TEXT[]),
('Index', 'index_us.mp3', 'noun', 'B1', 'a list of names or topics that are referred to in a book, etc., usually arranged at the end of a book in alphabetical order or listed in a separate file or book', '', 'Look it up in the index.', '', ARRAY[]::TEXT[]),
('Indicate', 'indicate_us.mp3', 'verb', 'B1', 'to show that something is true or exists', '', 'indicate something, Initial tests indicate the presence of oxygen.', '', ARRAY[]::TEXT[]),
('Indication', 'indication_us.mp3', 'noun', 'B1', 'a remark or sign that shows that something is happening or what somebody is thinking or feeling', '', 'indication of something, They gave no indication of how the work should be done.', '', ARRAY[]::TEXT[]),
('Indicator', 'indicator_us.mp3', 'noun', 'B1', 'a sign that shows you what something is like or how a situation is changing', '', 'The economic indicators are better than expected.', '', ARRAY[]::TEXT[]),
('Indictment', 'indictment_us.mp3', 'noun', 'B1', 'a sign that a system, society, etc. is very bad or very wrong', '', 'The poverty in our cities is a damning indictment of modern society.', '', ARRAY[]::TEXT[]),
('Indigenous', 'indigenous_us.mp3', 'adjective', 'B1', 'coming from a particular place and having lived there for a long time before other people came there; relating to, belonging to or developed by these people', '', 'the indigenous peoples/languages of an area', '', ARRAY[]::TEXT[]),
('Indirect', 'indirect_us.mp3', 'adjective', 'B1', 'happening not as the main aim, cause or result of a particular action, but in addition to it', '', 'the indirect effects of the war', '', ARRAY[]::TEXT[]),
('Individual', 'individual_us.mp3', 'adjective', 'B1', 'considered separately rather than as part of a group', '', 'We interviewed each individual member of the community.', '', ARRAY[]::TEXT[]),
('Individual', 'individual_us.mp3', 'noun', 'B1', 'a person considered separately rather than as part of a group', '', 'The competition is open to both teams and individuals.', '', ARRAY[]::TEXT[]),
('Indoor', 'indoor_us.mp3', 'adjective', 'B1', 'located, done or used inside a building', '', 'an indoor swimming pool', '', ARRAY[]::TEXT[]),
('Indoors', 'indoors_us.mp3', 'adverb', 'B1', 'inside or into a building', '', 'I prefer to stay indoors in this really hot weather.', '', ARRAY[]::TEXT[]),
('Induce', 'induce_us.mp3', 'verb', 'B1', 'to persuade or influence somebody to do something', '', 'Nothing would induce me to take the job.', '', ARRAY[]::TEXT[]),
('Indulge', 'indulge_us.mp3', 'verb', 'B1', 'to allow yourself to have or do something that you like, especially something that is considered bad for you', '', 'indulge in something, They went into town to indulge in some serious shopping.', '', ARRAY[]::TEXT[]),
('Industrial', 'industrial_us.mp3', 'adjective', 'B1', 'connected with industry', '', 'an industrial dispute', '', ARRAY[]::TEXT[]),
('Industry', 'industry_us.mp3', 'noun', 'B1', 'the production of goods from raw materials, especially in factories', '', 'the needs of British industry', '', ARRAY[]::TEXT[]),
('Inequality', 'inequality_us.mp3', 'noun', 'B1', 'the unfair difference between groups of people in society, when some have more wealth, status or opportunities than others', '', 'We need to tackle inequality of opportunity wherever we find it.', '', ARRAY[]::TEXT[]),
('Inevitable', 'inevitable_us.mp3', 'adjective', 'B1', 'that you cannot avoid or prevent', '', 'It was an inevitable consequence of the decision.', '', ARRAY[]::TEXT[]),
('Inevitably', 'inevitably_us.mp3', 'adverb', 'B1', 'as is certain to happen', '', 'Inevitably, the press exaggerated the story.', '', ARRAY[]::TEXT[]),
('Infamous', 'infamous_us.mp3', 'adjective', 'B1', 'well known for being bad or evil', '', 'a general who was infamous for his brutality', '', ARRAY[]::TEXT[]),
('Infant', 'infant_us.mp3', 'noun', 'B1', 'a baby or very young child', '', 'a nursery for infants under two', '', ARRAY[]::TEXT[]),
('Infect', 'infect_us.mp3', 'verb', 'B1', 'to make a disease or an illness spread to a person, an animal or a plant', '', 'infect somebody/something (with something), It is not possible to infect another person through kissing.', '', ARRAY[]::TEXT[]),
('Infection', 'infection_us.mp3', 'noun', 'B1', 'the act or process of causing or getting a disease', '', 'to cause/prevent infection', '', ARRAY[]::TEXT[]),
('Infer', 'infer_us.mp3', 'verb', 'B1', 'to reach an opinion or decide that something is true on the basis of information that is available', '', 'infer something (from something), Much of the meaning must be inferred from the context.', '', ARRAY[]::TEXT[]),
('Inflation', 'inflation_us.mp3', 'noun', 'B1', 'a general rise in the prices of services and goods in a particular country, resulting in a fall in the value of money; the rate at which this happens', '', 'the fight against rising inflation', '', ARRAY[]::TEXT[]),
('Inflict', 'inflict_us.mp3', 'verb', 'B1', 'to make somebody/something suffer something unpleasant', '', 'inflict something on/upon somebody/something, They inflicted a humiliating defeat on the home team.', '', ARRAY[]::TEXT[]),
('Influence', 'influence_us.mp3', 'noun', 'B1', 'the effect that somebody/something has on the way a person thinks or behaves or on the way that something works or develops', '', 'His early work shows the influence of Cézanne and Matisse.', '', ARRAY[]::TEXT[]),
('Influence', 'influence_us.mp3', 'verb', 'B1', 'to have an effect on the way that somebody behaves or thinks, especially by giving them an example to follow', '', 'influence somebody/something, His writings have influenced the lives of millions.', '', ARRAY[]::TEXT[]),
('Influential', 'influential_us.mp3', 'adjective', 'B1', 'having a lot of influence on somebody/something', '', 'a highly influential book', '', ARRAY[]::TEXT[]),
('Info', 'info_us.mp3', 'noun', 'B1', 'information', '', 'For more info, click here.', '', ARRAY[]::TEXT[]),
('Inform', 'inform_us.mp3', 'verb', 'B1', 'to tell somebody about something, especially in an official way', '', 'inform somebody, The government took this decision without consulting Parliament or informing the public.', '', ARRAY[]::TEXT[]),
('Informal', 'informal_us.mp3', 'adjective', 'B1', 'relaxed and friendly; not following strict rules of how to behave or do something', '', 'an informal atmosphere', '', ARRAY[]::TEXT[]),
('Information', 'information_us.mp3', 'noun', 'B1', 'facts or details about somebody/something', '', 'a piece of information', '', ARRAY[]::TEXT[]),
('Ingredient', 'ingredient_us.mp3', 'noun', 'B1', 'one of the things from which something is made, especially one of the foods that are used together to make a particular dish', '', 'Mix all the ingredients in a bowl.', '', ARRAY[]::TEXT[]),
('Inhabitant', 'inhabitant_us.mp3', 'noun', 'B1', 'a person or an animal that lives in a particular place', '', 'the oldest inhabitant of the village', '', ARRAY[]::TEXT[]),
('Inherent', 'inherent_us.mp3', 'adjective', 'B1', 'that is a basic or permanent part of somebody/something and that cannot be removed', '', 'the difficulties inherent in a study of this type', '', ARRAY[]::TEXT[]),
('Inherit', 'inherit_us.mp3', 'verb', 'B1', 'to receive money, property, etc. from somebody when they die', '', 'inherit something from somebody, She inherited a fortune from her father.', '', ARRAY[]::TEXT[]),
('Inhibit', 'inhibit_us.mp3', 'verb', 'B1', 'to prevent something from happening or make it happen more slowly or less frequently than normal', '', 'A lack of oxygen may inhibit brain development in the unborn child.', '', ARRAY[]::TEXT[]),
('Initial', 'initial_us.mp3', 'adjective', 'B1', 'happening at the beginning; first', '', 'There is an initial payment of £60 followed by ten instalments of £25.', '', ARRAY[]::TEXT[]),
('Initially', 'initially_us.mp3', 'adverb', 'B1', 'at the beginning', '', 'Initially, the system worked well.', '', ARRAY[]::TEXT[]),
('Initiate', 'initiate_us.mp3', 'verb', 'B1', 'to make something begin', '', 'to initiate legal proceedings against somebody', '', ARRAY[]::TEXT[]),
('Initiative', 'initiative_us.mp3', 'noun', 'B1', 'a new plan for dealing with a particular problem or for achieving a particular purpose', '', 'a United Nations peace initiative', '', ARRAY[]::TEXT[]),
('Inject', 'inject_us.mp3', 'verb', 'B1', 'to put a drug or other substance into a person’s or an animal’s body using a syringe', '', 'inject something (into yourself/somebody/something), Adrenaline was injected into the muscle.', '', ARRAY[]::TEXT[]),
('Injection', 'injection_us.mp3', 'noun', 'B1', 'an act of injecting somebody with a drug or other substance', '', 'to give somebody an injection', '', ARRAY[]::TEXT[]),
('Injure', 'injure_us.mp3', 'verb', 'B1', 'to harm yourself or somebody else physically, especially in an accident', '', 'He injured his knee playing hockey.', '', ARRAY[]::TEXT[]),
('Injured', 'injured_us.mp3', 'adjective', 'B1', 'physically hurt; having an injury', '', 'His injured leg prevented him from walking.', '', ARRAY[]::TEXT[]),
('Injury', 'injury_us.mp3', 'noun', 'B1', 'harm done to a person’s or an animal’s body, for example in an accident', '', 'Two people sustained minor injuries.', '', ARRAY[]::TEXT[]),
('Injustice', 'injustice_us.mp3', 'noun', 'B1', 'the fact of a situation being unfair and of people not being treated equally; an unfair act or an example of unfair treatment', '', 'We are committed to fighting against poverty and injustice.', '', ARRAY[]::TEXT[]),
('Ink', 'ink_us.mp3', 'noun', 'B1', 'coloured liquid for writing, drawing and printing', '', 'in ink, written in ink', '', ARRAY[]::TEXT[]),
('Inmate', 'inmate_us.mp3', 'noun', 'B1', 'one of the people living in an institution such as a prison or a psychiatric hospital', '', 'The jail has 500 inmates.', '', ARRAY[]::TEXT[]),
('Inner', 'inner_us.mp3', 'adjective', 'B1', 'inside; towards or close to the centre of a place', '', 'an inner courtyard', '', ARRAY[]::TEXT[]),
('Innocent', 'innocent_us.mp3', 'adjective', 'B1', 'not guilty of a crime, etc.; not having done something wrong', '', 'They have imprisoned an innocent man.', '', ARRAY[]::TEXT[]),
('Innovation', 'innovation_us.mp3', 'noun', 'B1', 'the introduction of new things, ideas or ways of doing something', '', 'an age of technological innovation', '', ARRAY[]::TEXT[]),
('Innovative', 'innovative_us.mp3', 'adjective', 'B1', 'introducing or using new ideas, ways of doing something, etc.', '', 'There will be a prize for the most innovative design.', '', ARRAY[]::TEXT[]),
('Input', 'input_us.mp3', 'noun', 'B1', 'time, knowledge, ideas, etc. that you put into work, a project, etc. in order to make it succeed; the act of putting something in', '', 'I''d appreciate your input on this.', '', ARRAY[]::TEXT[]),
('Inquiry', 'inquiry_us.mp3', 'noun', 'B1', 'an official process to find out the cause of something or to find out information about something', '', 'a murder inquiry', '', ARRAY[]::TEXT[]),
('Insect', 'insect_us.mp3', 'noun', 'B1', 'any small creature with six legs and a body divided into three parts. Insects usually also have wings. Ants, bees and flies are all insects.', '', 'Most birds spend most of the day eating insects.', '', ARRAY[]::TEXT[]),
('Insert', 'insert_us.mp3', 'verb', 'B1', 'to put something into something else or between two things', '', 'insert something (in/into something), Insert coins into the slot and press for a ticket.', '', ARRAY[]::TEXT[]),
('Insertion', 'insertion_us.mp3', 'noun', 'B1', 'the act of putting something inside something else; a thing that is put inside something else', '', 'An examination is carried out before the insertion of the tube.', '', ARRAY[]::TEXT[]),
('Inside', 'inside_us.mp3', 'adjective', 'B1', 'forming the inner part of something; not on the outside', '', 'the inside pages of a newspaper', '', ARRAY[]::TEXT[]),
('Inside', 'inside_us.mp3', 'adverb', 'B1', 'on or to the inside', '', 'She shook it to make sure there was nothing inside.', '', ARRAY[]::TEXT[]),
('Inside', 'inside_us.mp3', 'noun', 'B1', 'the inner part, side or surface of something', '', 'The inside of the box was blue.', '', ARRAY[]::TEXT[]),
('Inside', 'inside_us.mp3', 'preposition', 'B1', 'on or to the inner part of something/somebody; within something/somebody', '', 'Go inside the house.', '', ARRAY[]::TEXT[]),
('Insider', 'insider_us.mp3', 'noun', 'B1', 'a person who knows a lot about a group or an organization, because they are part of it', '', 'The situation was described by one insider as ‘absolute chaos’.', '', ARRAY[]::TEXT[]),
('Insight', 'insight_us.mp3', 'noun', 'B1', 'an understanding of what something is like', '', 'There are many valuable insights in her book.', '', ARRAY[]::TEXT[]),
('Insist', 'insist_us.mp3', 'verb', 'B1', 'to demand that something happen or that somebody agree to do something', '', 'I didn''t really want to go but he insisted.', '', ARRAY[]::TEXT[]),
('Inspect', 'inspect_us.mp3', 'verb', 'B1', 'to look closely at something/somebody, especially to check that everything is as it should be', '', 'inspect something/somebody, The teacher walked around inspecting their work.', '', ARRAY[]::TEXT[]),
('Inspection', 'inspection_us.mp3', 'noun', 'B1', 'an official visit to a school, factory, etc. in order to check that rules are being obeyed and that standards are acceptable', '', 'Regular inspections are carried out at the prison.', '', ARRAY[]::TEXT[]),
('Inspector', 'inspector_us.mp3', 'noun', 'B1', 'an officer of middle rank in the police force', '', 'Inspector Maggie Forbes', '', ARRAY[]::TEXT[]),
('Inspiration', 'inspiration_us.mp3', 'noun', 'B1', 'the process that takes place when somebody sees or hears something that causes them to have exciting new ideas or makes them want to create something, especially in art, music or literature', '', 'Dreams can be a rich source of inspiration for an artist.', '', ARRAY[]::TEXT[]),
('Inspire', 'inspire_us.mp3', 'verb', 'B1', 'to give somebody the desire, confidence or enthusiasm to do something well', '', 'inspire somebody, The actors'' enthusiasm inspired the kids.', '', ARRAY[]::TEXT[]),
('Install', 'install_us.mp3', 'verb', 'B1', 'to fix equipment or furniture into position so that it can be used', '', 'They''re planning to install a new drainage system.', '', ARRAY[]::TEXT[]),
('Installation', 'installation_us.mp3', 'noun', 'B1', 'the act of fixing equipment or furniture in position so that it can be used', '', 'installation costs', '', ARRAY[]::TEXT[]),
('Instance', 'instance_us.mp3', 'noun', 'B1', 'a particular example or case of something', '', 'instance of somebody/something, The report highlights a number of instances of injustice.', '', ARRAY[]::TEXT[]),
('Instant', 'instant_us.mp3', 'adjective', 'B1', 'happening immediately', '', 'This account gives you instant access to your money.', '', ARRAY[]::TEXT[]),
('Instantly', 'instantly_us.mp3', 'adverb', 'B1', 'immediately', '', 'Her voice is instantly recognizable.', '', ARRAY[]::TEXT[]),
('Instead', 'instead_us.mp3', 'adverb', 'B1', 'in the place of somebody/something', '', 'Lee was ill so I went instead.', '', ARRAY[]::TEXT[]),
('Instinct', 'instinct_us.mp3', 'noun', 'B1', 'a natural quality that makes people and animals tend to behave in a particular way using the knowledge and abilities that they were born with rather than thought or training', '', 'She did not seem to have any of the usual maternal instincts.', '', ARRAY[]::TEXT[]),
('Institute', 'institute_us.mp3', 'noun', 'B1', 'an organization that has a particular purpose, especially one that is connected with education or a particular profession; the building used by this organization', '', 'The report was compiled by Germany''s five leading economic research institutes.', '', ARRAY[]::TEXT[]),
('Institution', 'institution_us.mp3', 'noun', 'B1', 'a large important organization that has a particular purpose, for example a university or bank', '', 'The deal is backed by one of the country''s largest financial institutions.', '', ARRAY[]::TEXT[]),
('Institutional', 'institutional_us.mp3', 'adjective', 'B1', 'connected with a large important organization, for example a university or bank', '', 'institutional investors', '', ARRAY[]::TEXT[]),
('Instruct', 'instruct_us.mp3', 'verb', 'B1', 'to tell somebody to do something, especially in a formal or official way', '', 'instruct somebody to do something, The letter instructed him to report to headquarters immediately.', '', ARRAY[]::TEXT[]),
('Instruction', 'instruction_us.mp3', 'noun', 'B1', 'detailed information on how to do or use something', '', 'Follow the instructions on the packet carefully.', '', ARRAY[]::TEXT[]),
('Instructor', 'instructor_us.mp3', 'noun', 'B1', 'a person whose job is to teach somebody a practical skill or sport', '', 'a fitness/driving/ski instructor', '', ARRAY[]::TEXT[]),
('Instrument', 'instrument_us.mp3', 'noun', 'B1', 'an object used for producing musical sounds, for example a piano or a drum', '', 'to play an instrument', '', ARRAY[]::TEXT[]),
('Instrumental', 'instrumental_us.mp3', 'adjective', 'B1', 'important in making something happen', '', 'The Conservation Trust performs an instrumental role in the protection of rural environments.', '', ARRAY[]::TEXT[]),
('Insufficient', 'insufficient_us.mp3', 'adjective', 'B1', 'not large, strong or important enough for a particular purpose', '', 'insufficient time', '', ARRAY[]::TEXT[]),
('Insult', 'insult_us.mp3', 'noun', 'B1', 'a remark or an action that is said or done in order to offend somebody', '', 'The crowd were shouting insults at the police.', '', ARRAY[]::TEXT[]),
('Insult', 'insult_us.mp3', 'verb', 'B1', 'to say or do something that offends somebody', '', 'I have never been so insulted in my life!', '', ARRAY[]::TEXT[]),
('Insurance', 'insurance_us.mp3', 'noun', 'B1', 'an arrangement with a company in which you pay them regular amounts of money and they agree to pay the costs, for example, if you die or are ill, or if you lose or damage something', '', 'health/medical insurance', '', ARRAY[]::TEXT[]),
('Intact', 'intact_us.mp3', 'adjective', 'B1', 'complete and not damaged', '', 'Most of the house remains intact even after two hundred years.', '', ARRAY[]::TEXT[]),
('Intake', 'intake_us.mp3', 'noun', 'B1', 'the amount of food, drink, etc. that you take into your body', '', 'high fluid intake', '', ARRAY[]::TEXT[]),
('Integral', 'integral_us.mp3', 'adjective', 'B1', 'being an essential part of something', '', 'Music is an integral part of the school''s curriculum.', '', ARRAY[]::TEXT[]),
('Integrate', 'integrate_us.mp3', 'verb', 'B1', 'to combine two or more things so that they work together; to combine with something else in this way', '', 'integrate into/with something, These programs will integrate with your existing software.', '', ARRAY[]::TEXT[]),
('Integrated', 'integrated_us.mp3', 'adjective', 'B1', 'in which many different parts are closely connected and work successfully together', '', 'an integrated programme of patient care', '', ARRAY[]::TEXT[]),
('Integration', 'integration_us.mp3', 'noun', 'B1', 'the act or process of combining two or more things so that they work together', '', 'The aim is to promote closer economic integration.', '', ARRAY[]::TEXT[]),
('Integrity', 'integrity_us.mp3', 'noun', 'B1', 'the quality of being honest and having strong moral principles', '', 'personal/professional/artistic integrity', '', ARRAY[]::TEXT[]),
('Intellectual', 'intellectual_us.mp3', 'adjective', 'B1', 'connected with or using a person’s ability to think in a logical way and understand things', '', 'Gifted children typically show great intellectual curiosity and a wide range of interests.', '', ARRAY[]::TEXT[]),
('Intellectual', 'intellectual_us.mp3', 'noun', 'B1', 'a person who is well educated and enjoys activities in which they have to think seriously about things', '', 'He was a leading intellectual of his day.', '', ARRAY[]::TEXT[]),
('Intelligence', 'intelligence_us.mp3', 'noun', 'B1', 'the ability to learn, understand and think in a logical way about things; the ability to do this well', '', 'a person of high/average/low intelligence', '', ARRAY[]::TEXT[]),
('Intelligent', 'intelligent_us.mp3', 'adjective', 'B1', 'good at learning, understanding and thinking in a logical way about things; showing this ability', '', 'a highly intelligent child', '', ARRAY[]::TEXT[]),
('Intend', 'intend_us.mp3', 'verb', 'B1', 'to have a plan, result or purpose in your mind when you do something', '', 'We finished later than we had intended.', '', ARRAY[]::TEXT[]),
('Intended', 'intended_us.mp3', 'adjective', 'B1', 'that you are trying to achieve or reach', '', 'the intended purpose', '', ARRAY[]::TEXT[]),
('Intense', 'intense_us.mp3', 'adjective', 'B1', 'very great; very strong', '', 'We were all suffering in the intense heat.', '', ARRAY[]::TEXT[]),
('Intensify', 'intensify_us.mp3', 'verb', 'B1', 'to increase in degree or strength; to make something increase in degree or strength', '', 'Violence intensified during the night.', '', ARRAY[]::TEXT[]),
('Intensity', 'intensity_us.mp3', 'noun', 'B1', 'the state or quality of being intense', '', 'intensity of light/sound/colour', '', ARRAY[]::TEXT[]),
('Intensive', 'intensive_us.mp3', 'adjective', 'B1', 'involving a lot of work or activity done in a short time', '', 'an intensive language course', '', ARRAY[]::TEXT[]),
('Intent', 'intent_us.mp3', 'noun', 'B1', 'what you intend to do', '', 'She denies possessing the drug with intent to supply.', '', ARRAY[]::TEXT[]),
('Intention', 'intention_us.mp3', 'noun', 'B1', 'what you intend or plan to do; your aim', '', 'intention of doing something, I have no intention of going to the wedding.', '', ARRAY[]::TEXT[]),
('Interact', 'interact_us.mp3', 'verb', 'B1', 'to communicate with somebody, especially while you work, play or spend time with them', '', 'Teachers have a limited amount of time to interact with each child.', '', ARRAY[]::TEXT[]),
('Interaction', 'interaction_us.mp3', 'noun', 'B1', 'the act of communicating with somebody, especially while you work, play or spend time with them', '', 'the interaction between performers and their audience', '', ARRAY[]::TEXT[]),
('Interactive', 'interactive_us.mp3', 'adjective', 'B1', 'that allows information to be passed continuously and in both directions between a computer or other device and the person who uses it', '', 'interactive displays/video', '', ARRAY[]::TEXT[]),
('Interest', 'interest_us.mp3', 'noun', 'B1', 'the feeling that you have when you want to know or learn more about somebody/something', '', 'Her research has generated interest around the world.', '', ARRAY[]::TEXT[]),
('Interest', 'interest_us.mp3', 'verb', 'B1', 'to attract your attention and make you feel interested; to make yourself give your attention to something', '', 'interest somebody, Politics doesn''t interest me.', '', ARRAY[]::TEXT[]),
('Interested', 'interested_us.mp3', 'adjective', 'B1', 'giving your attention to something because you enjoy finding out about it or doing it; showing interest in something and finding it exciting', '', 'He sounded genuinely interested.', '', ARRAY[]::TEXT[]),
('Interesting', 'interesting_us.mp3', 'adjective', 'B1', 'attracting your attention because it is/they are special, exciting or unusual', '', 'The article raises several interesting questions.', '', ARRAY[]::TEXT[]),
('Interface', 'interface_us.mp3', 'noun', 'B1', 'the way a computer program presents information to a user or receives information from a user, in particular the layout of the screen and the menus', '', 'the user interface', '', ARRAY[]::TEXT[]),
('Interfere', 'interfere_us.mp3', 'verb', 'B1', 'to get involved in and try to influence a situation that should not really involve you, in a way that annoys other people', '', 'I wish my mother would stop interfering and let me make my own decisions.', '', ARRAY[]::TEXT[]),
('Interference', 'interference_us.mp3', 'noun', 'B1', 'the act of getting involved in and trying to influence a situation that should not really involve you, in a way that annoys other people', '', 'interference (in something), They resent foreign interference in the internal affairs of their country.', '', ARRAY[]::TEXT[]),
('Interim', 'interim_us.mp3', 'adjective', 'B1', 'intended to last for only a short time until somebody/something more permanent is found', '', 'an interim government/measure/report', '', ARRAY[]::TEXT[]),
('Interior', 'interior_us.mp3', 'adjective', 'B1', 'connected with the inside part of something', '', 'interior walls', '', ARRAY[]::TEXT[]),
('Interior', 'interior_us.mp3', 'noun', 'B1', 'the inside part of something', '', 'the interior of a building/a car', '', ARRAY[]::TEXT[]),
('Intermediate', 'intermediate_us.mp3', 'adjective', 'B1', 'located between two places, things, states, etc.', '', 'an intermediate stage/step in a process', '', ARRAY[]::TEXT[]),
('Internal', 'internal_us.mp3', 'adjective', 'B1', 'connected with the inside of something', '', 'the internal structure of a building', '', ARRAY[]::TEXT[]),
('International', 'international_us.mp3', 'adjective', 'B1', 'connected with or involving two or more countries', '', 'international trade/law', '', ARRAY[]::TEXT[]),
('Internet', 'internet_us.mp3', 'noun', 'B1', 'an international computer network connecting other networks and computers that allows people to share information around the world', '', 'to surf/browse/access the internet', '', ARRAY[]::TEXT[]),
('Interpret', 'interpret_us.mp3', 'verb', 'B1', 'to explain the meaning of something', '', 'The students were asked to interpret the poem.', '', ARRAY[]::TEXT[]),
('Interpretation', 'interpretation_us.mp3', 'noun', 'B1', 'the particular way in which something is understood or explained', '', 'Her evidence suggests a different interpretation of the events.', '', ARRAY[]::TEXT[]),
('Interrupt', 'interrupt_us.mp3', 'verb', 'B1', 'to say or do something that makes somebody stop what they are saying or doing', '', 'Sorry to interrupt, but there''s someone to see you.', '', ARRAY[]::TEXT[]),
('Interval', 'interval_us.mp3', 'noun', 'B1', 'a period of time between two events', '', 'The interval between major earthquakes might be 200 years.', '', ARRAY[]::TEXT[]),
('Intervene', 'intervene_us.mp3', 'verb', 'B1', 'to become involved in a situation in order to improve or help it', '', 'She might have been killed if the neighbours hadn''t intervened.', '', ARRAY[]::TEXT[]),
('Intervention', 'intervention_us.mp3', 'noun', 'B1', 'action taken to improve or help a situation', '', 'calls for government intervention to save the steel industry', '', ARRAY[]::TEXT[]),
('Interview', 'interview_us.mp3', 'noun', 'B1', 'a formal meeting at which somebody is asked questions to see if they are suitable for a particular job, or for a course of study at a college, university, etc.', '', 'a job interview', '', ARRAY[]::TEXT[]),
('Interview', 'interview_us.mp3', 'verb', 'B1', 'to talk to somebody and ask them questions at a formal meeting to find out if they are suitable for a job, course of study, etc.', '', 'interview somebody, The university interviews all potential candidates.', '', ARRAY[]::TEXT[]),
('Intimate', 'intimate_us.mp3', 'adjective', 'B1', 'having a close and friendly relationship', '', 'intimate friends', '', ARRAY[]::TEXT[]),
('Into', 'into_us.mp3', 'preposition', 'B1', 'to a position in or inside something', '', 'Come into the house.', '', ARRAY[]::TEXT[]),
('Intriguing', 'intriguing_us.mp3', 'adjective', 'B1', 'very interesting because of being unusual or not having an obvious answer', '', 'These discoveries raise intriguing questions.', '', ARRAY[]::TEXT[]),
('Introduce', 'introduce_us.mp3', 'verb', 'B1', 'to tell two or more people who have not met before what each other’s names are; to tell somebody what your name is', '', 'introduce somebody, Allow me to introduce my mother.', '', ARRAY[]::TEXT[]),
('Introduction', 'introduction_us.mp3', 'noun', 'B1', 'the first part of a book or speech that gives a general idea of what is to follow', '', 'a book with an excellent introduction and notes', '', ARRAY[]::TEXT[]),
('Invade', 'invade_us.mp3', 'verb', 'B1', 'to enter a country, town, etc. using military force in order to take control of it', '', 'Troops invaded on August 9th that year.', '', ARRAY[]::TEXT[]),
('Invasion', 'invasion_us.mp3', 'noun', 'B1', 'the act of an army entering another country by force in order to take control of it', '', 'the German invasion of Poland in 1939', '', ARRAY[]::TEXT[]),
('Invent', 'invent_us.mp3', 'verb', 'B1', 'to produce or design something that has not existed before', '', 'Who invented the steam engine?', '', ARRAY[]::TEXT[]),
('Invention', 'invention_us.mp3', 'noun', 'B1', 'a thing or an idea that has been invented', '', 'Fax machines were a wonderful invention at the time.', '', ARRAY[]::TEXT[]),
('Invest', 'invest_us.mp3', 'verb', 'B1', 'to buy property, shares in a company, etc. in the hope of making a profit', '', 'Now is a good time to invest.', '', ARRAY[]::TEXT[]),
('Investigate', 'investigate_us.mp3', 'verb', 'B1', 'to carefully examine the facts of a situation, an event, a crime, etc. to find out the truth about it or how it happened', '', 'The FBI has been called in to investigate.', '', ARRAY[]::TEXT[]),
('Investigation', 'investigation_us.mp3', 'noun', 'B1', 'an official examination of the facts about a situation, crime, etc.', '', 'a criminal/murder/police investigation', '', ARRAY[]::TEXT[]),
('Investigator', 'investigator_us.mp3', 'noun', 'B1', 'a person who examines a situation such as an accident or a crime to find out the truth', '', 'air safety investigators', '', ARRAY[]::TEXT[]),
('Investment', 'investment_us.mp3', 'noun', 'B1', 'the act of investing money in something', '', 'foreign/private investment', '', ARRAY[]::TEXT[]),
('Investor', 'investor_us.mp3', 'noun', 'B1', 'a person or an organization that invests money in something', '', 'small investors (= private people)', '', ARRAY[]::TEXT[]),
('Invisible', 'invisible_us.mp3', 'adjective', 'B1', 'that cannot be seen', '', 'a wizard who could make himself invisible', '', ARRAY[]::TEXT[]),
('Invitation', 'invitation_us.mp3', 'noun', 'B1', 'a spoken or written request to somebody to do something or to go somewhere', '', 'to issue/extend an invitation', '', ARRAY[]::TEXT[]),
('Invite', 'invite_us.mp3', 'verb', 'B1', 'to ask somebody to come to a social event', '', 'invite somebody to something, Have you been invited to their party?', '', ARRAY[]::TEXT[]),
('Invoke', 'invoke_us.mp3', 'verb', 'B1', 'to mention or use a law, rule, etc. as a reason for doing something', '', 'It is unlikely that libel laws will be invoked.', '', ARRAY[]::TEXT[]),
('Involve', 'involve_us.mp3', 'verb', 'B1', 'if a situation, an event or an activity involves something, that thing is an important or necessary part or result of it', '', 'involve something, Any investment involves an element of risk.', '', ARRAY[]::TEXT[]),
('Involved', 'involved_us.mp3', 'adjective', 'B1', 'taking part in something; being part of something or connected with something', '', 'Some people tried to stop the fight but I didn''t want to get involved.', '', ARRAY[]::TEXT[]),
('Involvement', 'involvement_us.mp3', 'noun', 'B1', 'the act of taking part in something or dealing with somebody', '', 'involvement in something, US involvement in European wars', '', ARRAY[]::TEXT[]),
('Iron', 'iron_us.mp3', 'noun', 'B1', 'a chemical element. Iron is a hard strong metal that is used to make steel and is also found in small quantities in blood and food.', '', 'iron gates/bars/railings', '', ARRAY[]::TEXT[]),
('Iron', 'iron_us.mp3', 'verb', 'B1', 'to make clothes, etc. smooth by using an iron', '', 'He was ironing when I arrived.', '', ARRAY[]::TEXT[]),
('Ironic', 'ironic_us.mp3', 'adjective', 'B1', 'showing that you really mean the opposite of what you are saying; expressing irony', '', 'an ironic comment', '', ARRAY[]::TEXT[]),
('Ironically', 'ironically_us.mp3', 'adverb', 'B1', 'in a way that shows that you really mean the opposite of what you are saying; in a way that expresses irony', '', 'He smiled ironically.', '', ARRAY[]::TEXT[]),
('Irony', 'irony_us.mp3', 'noun', 'B1', 'the funny or strange aspect of a situation that is very different from what you expect; a situation like this', '', 'It was one of life''s little ironies.', '', ARRAY[]::TEXT[]),
('Irrelevant', 'irrelevant_us.mp3', 'adjective', 'B1', 'not important to or connected with a situation', '', 'totally/completely/largely irrelevant', '', ARRAY[]::TEXT[]),
('Island', 'island_us.mp3', 'noun', 'B1', 'a piece of land that is completely surrounded by water', '', 'a small/tiny island', '', ARRAY[]::TEXT[]),
('Isolate', 'isolate_us.mp3', 'verb', 'B1', 'to separate somebody/something physically or socially from other people or things', '', 'isolate somebody/yourself/something, Patients with the disease should be isolated.', '', ARRAY[]::TEXT[]),
('Isolated', 'isolated_us.mp3', 'adjective', 'B1', 'far away from any others', '', 'isolated rural areas', '', ARRAY[]::TEXT[]),
('Isolation', 'isolation_us.mp3', 'noun', 'B1', 'the act of separating somebody/something; the state of being separate', '', 'geographical isolation', '', ARRAY[]::TEXT[]),
('Issue', 'issue_us.mp3', 'noun', 'B1', 'an important topic that people are discussing or arguing about', '', 'a key/major issue', '', ARRAY[]::TEXT[]),
('Issue', 'issue_us.mp3', 'verb', 'B1', 'to make something known formally', '', 'issue something, They issued a joint statement denying the charges.', '', ARRAY[]::TEXT[]),
('IT', 'IT_us.mp3', 'noun', 'B1', 'the study and use of electronic processes and equipment to store and send information of all kinds, including words, pictures and numbers (the abbreviation for ‘information technology’)', '', 'the increasing use of IT in all aspects of today''s society', '', ARRAY[]::TEXT[]),
('It', 'it_us.mp3', 'pronoun', 'B1', 'used to refer to an animal or a thing that has already been mentioned or that is being talked about now', '', '‘Where''s your car?’ ‘It''s in the garage.’', '', ARRAY[]::TEXT[]),
('Item', 'item_us.mp3', 'noun', 'B1', 'one thing on a list of things to buy, do, talk about, etc.', '', 'What''s the next item on the agenda?', '', ARRAY[]::TEXT[]),
('Its', 'its_us.mp3', 'determiner', 'B1', 'belonging to or connected with a thing, an animal or a baby', '', 'Turn the box on its side.', '', ARRAY[]::TEXT[]),
('Itself', 'itself_us.mp3', 'pronoun', 'B1', 'used when the animal or thing that does an action is also affected by it', '', 'The cat was washing itself.', '', ARRAY[]::TEXT[]),
('Jacket', 'jacket_us.mp3', 'noun', 'B1', 'a piece of clothing worn on the top half of the body over a shirt, etc. that has arms and fastens down the front; a short, light coat', '', 'a leather/denim/tweed jacket', '', ARRAY[]::TEXT[]),
('Jail', 'jail_us.mp3', 'noun', 'B1', 'a prison', '', 'She spent a year in jail.', '', ARRAY[]::TEXT[]),
('Jail', 'jail_us.mp3', 'verb', 'B1', 'to put somebody in prison', '', 'be jailed (for something), He was jailed for life for murder.', '', ARRAY[]::TEXT[]),
('Jam', 'jam_us.mp3', 'noun', 'B1', 'a thick sweet substance made by boiling fruit with sugar, often sold in jars and spread on bread', '', 'strawberry jam', '', ARRAY[]::TEXT[]),
('January', 'January_us.mp3', 'noun', 'B1', 'the 1st month of the year, between December and February', '', 'She was born in January.', '', ARRAY[]::TEXT[]),
('Jazz', 'jazz_us.mp3', 'noun', 'B1', 'a type of music with strong rhythms, in which the players often improvise (= make up the music as they are playing), originally created by African American musicians at the beginning of the 20th century', '', 'traditional/modern jazz', '', ARRAY[]::TEXT[]),
('Jeans', 'jeans_us.mp3', 'noun', 'B1', 'trousers made of denim (= a type of strong cotton)', '', 'I always wear jeans.', '', ARRAY[]::TEXT[]),
('Jet', 'jet_us.mp3', 'noun', 'B1', 'a plane driven by jet engines', '', 'a jet aircraft/fighter/airliner', '', ARRAY[]::TEXT[]),
('Jewellery', 'jewellery_us.mp3', 'noun', 'B1', 'objects such as rings and necklaces that people wear as decoration', '', 'silver/gold jewellery', '', ARRAY[]::TEXT[]),
('Job', 'job_us.mp3', 'noun', 'B1', 'work for which you receive regular payment', '', 'I don''t have a job at present.', '', ARRAY[]::TEXT[]),
('Join', 'join_us.mp3', 'verb', 'B1', 'to fix or connect two or more things together', '', 'join A to/onto B, Join one section of pipe to the next.', '', ARRAY[]::TEXT[]),
('Joint', 'joint_us.mp3', 'adjective', 'B1', 'involving two or more people together', '', 'a joint account (= a bank account in the name of more than one person, for example shared by a couple)', '', ARRAY[]::TEXT[]),
('Joint', 'joint_us.mp3', 'noun', 'B1', 'a place where two bones are joined together in the body in a way that enables them to bend and move', '', 'inflammation of the knee joint', '', ARRAY[]::TEXT[]),
('Joke', 'joke_us.mp3', 'noun', 'B1', 'something that you say or do to make people laugh, for example a funny story that you tell', '', 'I can''t tell jokes.', '', ARRAY[]::TEXT[]),
('Joke', 'joke_us.mp3', 'verb', 'B1', 'to say something to make people laugh; to tell a funny story', '', 'She was laughing and joking with the children.', '', ARRAY[]::TEXT[]),
('Journal', 'journal_us.mp3', 'noun', 'B1', 'a newspaper or magazine that deals with a particular subject or profession', '', 'a scientific/an academic journal', '', ARRAY[]::TEXT[]),
('Journalism', 'journalism_us.mp3', 'noun', 'B1', 'the work of collecting and writing news stories for newspapers, magazines, radio, television or online news sites; the news stories that are written', '', 'I''d like a career in journalism.', '', ARRAY[]::TEXT[]),
('Journalist', 'journalist_us.mp3', 'noun', 'B1', 'a person whose job is to collect and write news stories for newspapers, magazines, radio, television or online news sites', '', 'a freelance journalist', '', ARRAY[]::TEXT[]),
('Journey', 'journey_us.mp3', 'noun', 'B1', 'an act of travelling from one place to another, especially when they are far apart', '', 'They went on a long train journey across India.', '', ARRAY[]::TEXT[]),
('Joy', 'joy_us.mp3', 'noun', 'B1', 'a feeling of great happiness', '', 'Her books have brought joy to millions.', '', ARRAY[]::TEXT[]),
('Judge', 'judge_us.mp3', 'noun', 'B1', 'a person in a court who has the authority to decide how criminals should be punished or to make legal decisions', '', 'a High Court judge', '', ARRAY[]::TEXT[]),
('Judge', 'judge_us.mp3', 'verb', 'B1', 'to form an opinion about somebody/something, based on the information you have', '', 'As far as I can judge, all of them are to blame.', '', ARRAY[]::TEXT[]),
('Judgement', 'judgement_us.mp3', 'noun', 'B1', 'the ability to make sensible decisions after carefully considering the best thing to do', '', 'good/poor/sound judgement', '', ARRAY[]::TEXT[]),
('Judicial', 'judicial_us.mp3', 'adjective', 'B1', 'connected with a court, a judge or legal judgement', '', 'judicial powers', '', ARRAY[]::TEXT[]),
('Juice', 'juice_us.mp3', 'noun', 'B1', 'the liquid that comes from fruit or vegetables; a drink made from this', '', 'a glass of fruit juice', '', ARRAY[]::TEXT[]),
('July', 'July_us.mp3', 'noun', 'B1', 'the 7th month of the year, between June and August', '', 'in July, She was born in July.', '', ARRAY[]::TEXT[]),
('Jump', 'jump_us.mp3', 'noun', 'B1', 'an act of jumping', '', 'to do a parachute jump', '', ARRAY[]::TEXT[]),
('Jump', 'jump_us.mp3', 'verb', 'B1', 'to move quickly off the ground or away from a surface by pushing yourself with your legs and feet', '', '‘Quick, jump!’ he shouted.', '', ARRAY[]::TEXT[]),
('Junction', 'junction_us.mp3', 'noun', 'B1', 'the place where two or more roads or railway lines meet', '', 'It was near the junction of City Road and Old Street.', '', ARRAY[]::TEXT[]),
('June', 'June_us.mp3', 'noun', 'B1', 'the 6th month of the year, between May and July', '', 'She was born in June.', '', ARRAY[]::TEXT[]),
('Junior', 'junior_us.mp3', 'adjective', 'B1', 'having a low rank in an organization or a profession', '', 'a junior partner/minister/officer', '', ARRAY[]::TEXT[]),
('Jurisdiction', 'jurisdiction_us.mp3', 'noun', 'B1', 'the authority that an official organization has to make legal decisions about somebody/something', '', 'jurisdiction over somebody/something, The English court had no jurisdiction over the defendants.', '', ARRAY[]::TEXT[]),
('Jury', 'jury_us.mp3', 'noun', 'B1', 'a group of members of the public who listen to the facts of a case in a court and decide whether or not somebody is guilty of a crime, or whether a claim has been proved', '', 'members of the jury', '', ARRAY[]::TEXT[]),
('Just', 'just_us.mp3', 'adjective', 'B1', 'that most people consider to be morally fair and reasonable', '', 'a just decision/law/society', '', ARRAY[]::TEXT[]),
('Just', 'just_us.mp3', 'adverb', 'B1', 'only', '', 'There is just one method that might work.', '', ARRAY[]::TEXT[]),
('Justice', 'justice_us.mp3', 'noun', 'B1', 'the fair treatment of people', '', 'She spent her life fighting for social justice and equality for women.', '', ARRAY[]::TEXT[]),
('Justification', 'justification_us.mp3', 'noun', 'B1', 'a good reason why something exists or is done', '', 'justification for doing something, I can see no possible justification for any further tax increases.', '', ARRAY[]::TEXT[]),
('Justify', 'justify_us.mp3', 'verb', 'B1', 'to show that somebody/something is right or reasonable', '', 'justify doing something, How can they justify paying such huge salaries?', '', ARRAY[]::TEXT[]),
('Keen', 'keen_us.mp3', 'adjective', 'B1', 'wanting to do something or wanting something to happen very much', '', 'keen to do something, John was very keen to help.', '', ARRAY[]::TEXT[]),
('Keep', 'keep_us.mp3', 'verb', 'B1', 'to continue to have something and not give it back or throw it away', '', 'He kept all her letters.', '', ARRAY[]::TEXT[]),
('Key', 'key_us.mp3', 'adjective', 'B1', 'most important; essential', '', 'the key issue/factor/point', '', ARRAY[]::TEXT[]),
('Key', 'key_us.mp3', 'noun', 'B1', 'a piece of metal with a special shape used for locking a door, starting a car, etc.', '', 'to put/turn the key in the lock', '', ARRAY[]::TEXT[]),
('Key', 'key_us.mp3', 'verb', 'B1', 'to put information into a computer using a keyboard', '', 'key something, I was busy keying data.', '', ARRAY[]::TEXT[]),
('Keyboard', 'keyboard_us.mp3', 'noun', 'B1', 'the set of keys for operating a computer or typewriter, or the set of letters that you can touch to write on a smartphone or tablet', '', 'The program locks the keyboard until a password is given.', '', ARRAY[]::TEXT[]),
('Kick', 'kick_us.mp3', 'noun', 'B1', 'a movement with the foot or the leg, usually to hit something with the foot', '', 'the first kick of the game', '', ARRAY[]::TEXT[]),
('Kick', 'kick_us.mp3', 'verb', 'B1', 'to hit somebody/something with your foot', '', 'Stop kicking—it hurts!', '', ARRAY[]::TEXT[]),
('Kid', 'kid_us.mp3', 'noun', 'B1', 'a child or young person', '', 'Do you have any kids?', '', ARRAY[]::TEXT[]),
('Kidnap', 'kidnap_us.mp3', 'verb', 'B1', 'to take somebody away illegally and keep them as a prisoner, especially in order to get money or something else for returning them', '', 'Two businessmen have been kidnapped by terrorists.', '', ARRAY[]::TEXT[]),
('Kidney', 'kidney_us.mp3', 'noun', 'B1', 'either of the two organs in the body that remove waste products from the blood and produce urine', '', 'a kidney infection', '', ARRAY[]::TEXT[]),
('Kill', 'kill_us.mp3', 'verb', 'B1', 'to make somebody/something die', '', 'kill (somebody/something), Cancer kills thousands of people every year.', '', ARRAY[]::TEXT[]),
('Killing', 'killing_us.mp3', 'noun', 'B1', 'an act of killing somebody deliberately', '', 'Their leader condemned the torture and killing of innocent civilians.', '', ARRAY[]::TEXT[]),
('Kilometre', 'kilometre_us.mp3', 'noun', 'B1', 'a unit for measuring distance; 1 000 metres', '', 'The industrial estate is 6 kilometres from the city centre.', '', ARRAY[]::TEXT[]),
('Kind', 'kind_us.mp3', 'adjective', 'B1', 'caring about others; gentle, friendly and generous', '', 'a very kind and helpful person', '', ARRAY[]::TEXT[]),
('Kind', 'kind_us.mp3', 'noun', 'B1', 'a group of people or things that are the same in some way; a particular variety or type', '', 'kind of somebody/something, three kinds of cakes/cake', '', ARRAY[]::TEXT[]),
('King', 'king_us.mp3', 'noun', 'B1', 'the male ruler of an independent state that has a royal family', '', 'the kings and queens of England', '', ARRAY[]::TEXT[]),
('Kingdom', 'kingdom_us.mp3', 'noun', 'B1', 'a country that has a king or queen as head of state (= official leader of the country)', '', 'the United Kingdom', '', ARRAY[]::TEXT[]),
('Kiss', 'kiss_us.mp3', 'noun', 'B1', 'the act of kissing somebody/something', '', 'Come here and give me a kiss!', '', ARRAY[]::TEXT[]),
('Kiss', 'kiss_us.mp3', 'verb', 'B1', 'to touch somebody with your lips as a sign of love or sexual desire or when saying hello or goodbye', '', 'They stood in a doorway kissing (= kissing each other).', '', ARRAY[]::TEXT[]),
('Kit', 'kit_us.mp3', 'noun', 'B1', 'a set of tools or equipment that you use for a particular purpose', '', 'a first-aid kit', '', ARRAY[]::TEXT[]),
('Kitchen', 'kitchen_us.mp3', 'noun', 'B1', 'a room in which meals are cooked or prepared', '', 'We ate at the kitchen table.', '', ARRAY[]::TEXT[]),
('Knee', 'knee_us.mp3', 'noun', 'B1', 'the joint between the top and bottom parts of the leg where it bends in the middle', '', 'a knee injury', '', ARRAY[]::TEXT[]),
('Knife', 'knife_us.mp3', 'noun', 'B1', 'a sharp blade (= metal edge) with a handle, used for cutting or as a weapon', '', 'knives and forks', '', ARRAY[]::TEXT[]),
('Knock', 'knock_us.mp3', 'noun', 'B1', 'the sound of somebody hitting a door, window, etc. with their hand or with something hard to attract attention', '', 'knock on/at something, There was a knock at the door.', '', ARRAY[]::TEXT[]),
('Knock', 'knock_us.mp3', 'verb', 'B1', 'to hit a door, etc. in order to attract attention', '', 'He knocked three times and waited.', '', ARRAY[]::TEXT[]),
('Know', 'know_us.mp3', 'verb', 'B1', 'to have information in your mind as a result of experience or because you have learned or been told it', '', 'know something, No one knows the answer.', '', ARRAY[]::TEXT[]),
('Knowledge', 'knowledge_us.mp3', 'noun', 'B1', 'the information, understanding and skills that you gain through education or experience', '', 'scientific/technical knowledge and skills', '', ARRAY[]::TEXT[]),
('Lab', 'lab_us.mp3', 'noun', 'B1', 'a laboratory', '', 'a computer/research lab', '', ARRAY[]::TEXT[]),
('Label', 'label_us.mp3', 'noun', 'B1', 'a piece of paper, etc. that is attached to something and that gives information about it', '', 'Always read the label carefully.', '', ARRAY[]::TEXT[]),
('Label', 'label_us.mp3', 'verb', 'B1', 'to fix a label on something or write information on something', '', 'label something, Make sure that your luggage is clearly labelled.', '', ARRAY[]::TEXT[]),
('Laboratory', 'laboratory_us.mp3', 'noun', 'B1', 'a room or building used for scientific research, experiments, testing, etc.', '', 'a clinical/research laboratory', '', ARRAY[]::TEXT[]),
('Labour', 'labour_us.mp3', 'noun', 'B1', 'work, especially physical work', '', 'manual labour (= work using your hands)', '', ARRAY[]::TEXT[]),
('Lack', 'lack_us.mp3', 'noun', 'B1', 'the state of not having something or not having enough of something', '', 'lack of something, a lack of understanding/knowledge', '', ARRAY[]::TEXT[]),
('Lack', 'lack_us.mp3', 'verb', 'B1', 'to have none or not enough of something', '', 'to lack confidence/experience/resources/power', '', ARRAY[]::TEXT[]),
('Lad', 'lad_us.mp3', 'noun', 'B1', 'a boy or young man', '', 'Things have changed since I was a lad.', '', ARRAY[]::TEXT[]),
('Ladder', 'ladder_us.mp3', 'noun', 'B1', 'a piece of equipment for climbing up and down a wall, the side of a building, etc., consisting of two lengths of wood or metal that are joined together by steps or rungs', '', 'to climb up/fall off a ladder', '', ARRAY[]::TEXT[]),
('Lady', 'lady_us.mp3', 'noun', 'B1', 'a word used to mean ‘woman’ that some people, especially older people, consider is more polite', '', 'There''s a lady waiting to see you.', '', ARRAY[]::TEXT[]),
('Lake', 'lake_us.mp3', 'noun', 'B1', 'a large area of water that is surrounded by land', '', 'in a lake, We swam in the lake.', '', ARRAY[]::TEXT[]),
('Lamp', 'lamp_us.mp3', 'noun', 'B1', 'a device that uses electricity, oil or gas to produce light', '', 'a desk/bedside lamp', '', ARRAY[]::TEXT[]),
('Land', 'land_us.mp3', 'noun', 'B1', 'the surface of the earth that is not sea', '', 'The new project will reclaim the land from the sea.', '', ARRAY[]::TEXT[]),
('Land', 'land_us.mp3', 'verb', 'B1', 'to come down through the air onto the ground or another surface', '', 'The plane landed safely.', '', ARRAY[]::TEXT[]),
('Landing', 'landing_us.mp3', 'noun', 'B1', 'an act of bringing an aircraft or a spacecraft down to the ground after a journey', '', 'a perfect/smooth/safe landing', '', ARRAY[]::TEXT[]),
('Landlord', 'landlord_us.mp3', 'noun', 'B1', 'a person or company from whom you rent a room, a house, an office, etc.', '', 'a buy-to-let landlord (= who buys houses and flats in order to rent them out)', '', ARRAY[]::TEXT[]),
('Landmark', 'landmark_us.mp3', 'noun', 'B1', 'something, such as a large building, that you can see clearly from a distance and that will help you to know where you are', '', 'The Empire State Building is a familiar landmark on the New York skyline.', '', ARRAY[]::TEXT[]),
('Landscape', 'landscape_us.mp3', 'noun', 'B1', 'everything you can see when you look across a large area of land, especially in the country', '', 'the woods and fields that are typical features of the English landscape', '', ARRAY[]::TEXT[]),
('Lane', 'lane_us.mp3', 'noun', 'B1', 'a narrow road in the country', '', 'winding country lanes', '', ARRAY[]::TEXT[]),
('Language', 'language_us.mp3', 'noun', 'B1', 'the system of communication in speech and writing that is used by people of a particular country or area', '', 'the English language', '', ARRAY[]::TEXT[]),
('Lap', 'lap_us.mp3', 'noun', 'B1', 'the top part of your legs that forms a flat surface when you are sitting down', '', 'on somebody''s lap, There''s only one seat so you''ll have to sit on my lap.', '', ARRAY[]::TEXT[]),
('Laptop', 'laptop_us.mp3', 'noun', 'B1', 'a small computer that can work with a battery and be easily carried', '', 'I opened my laptop and started typing.', '', ARRAY[]::TEXT[]),
('Large', 'large_us.mp3', 'adjective', 'B1', 'big in size or quantity', '', 'a large group/city/area/crowd/family', '', ARRAY[]::TEXT[]),
('Large-scale', 'large-scale_us.mp3', 'adjective', 'B1', 'involving many people or things, especially over a wide area', '', 'Large areas of the forest will be cleared for ranching as part of a large-scale development plan.', '', ARRAY[]::TEXT[]),
('Largely', 'largely_us.mp3', 'adverb', 'B1', 'to a great extent; mostly or mainly', '', 'The manager was largely responsible for the team’s victory.', '', ARRAY[]::TEXT[]),
('Laser', 'laser_us.mp3', 'noun', 'B1', 'a device that gives out light in which all the waves oscillate (= change direction and strength) together, typically producing a powerful beam of light that can be used for cutting metal, in medical operations, etc.', '', 'a laser beam', '', ARRAY[]::TEXT[]),
('Last', 'last_us.mp3', 'adverb', 'B1', 'after anyone or anything else; at the end', '', 'He came last in the race.', '', ARRAY[]::TEXT[]),
('Last', 'last_us.mp3', 'determiner', 'B1', 'happening or coming after all other similar things or people', '', 'We caught the last bus home.', '', ARRAY[]::TEXT[]),
('Last', 'last_us.mp3', 'noun', 'B1', 'the person or thing that comes or happens after all other similar people or things', '', 'Sorry I''m late—am I the last?', '', ARRAY[]::TEXT[]),
('Last', 'last_us.mp3', 'verb', 'B1', 'to continue for a particular period of time', '', 'Each game lasts about an hour.', '', ARRAY[]::TEXT[]),
('Late', 'late_us.mp3', 'adjective', 'B1', 'arriving, happening or done after the expected, arranged or usual time', '', 'I''m sorry I''m late.', '', ARRAY[]::TEXT[]),
('Late', 'late_us.mp3', 'adverb', 'B1', 'after the expected, arranged or usual time', '', 'I got up late.', '', ARRAY[]::TEXT[]),
('Lately', 'lately_us.mp3', 'adverb', 'B1', 'recently; in the recent past', '', 'Have you seen her lately?', '', ARRAY[]::TEXT[]),
('Later', 'later_us.mp3', 'adjective', 'B1', 'coming after something else or at a time in the future', '', 'Rembrandt''s later works', '', ARRAY[]::TEXT[]),
('Later', 'later_us.mp3', 'adverb', 'B1', 'at a time in the future; after the time you are talking about', '', 'See you later.', '', ARRAY[]::TEXT[]),
('Latest', 'latest_us.mp3', 'adjective', 'B1', 'the most recent or newest', '', 'the latest craze/fashion/trend', '', ARRAY[]::TEXT[]),
('Latest', 'latest_us.mp3', 'noun', 'B1', 'the most recent or the newest thing or piece of news', '', 'the latest (in something), This is the latest in robot technology.', '', ARRAY[]::TEXT[]),
('Latter', 'latter_us.mp3', 'adjective', 'B1', 'used to refer to the second of two things or people mentioned', '', 'He chose the latter option.', '', ARRAY[]::TEXT[]),
('Latter', 'latter_us.mp3', 'noun', 'B1', 'the second of two things or people mentioned', '', 'He presented two solutions. The latter seems much better.', '', ARRAY[]::TEXT[]),
('Laugh', 'laugh_us.mp3', 'noun', 'B1', 'the sound you make when you think that something is funny or silly', '', 'to give a laugh', '', ARRAY[]::TEXT[]),
('Laugh', 'laugh_us.mp3', 'verb', 'B1', 'to make the sounds and movements of your face that show you think something is funny or silly', '', 'to laugh out loud', '', ARRAY[]::TEXT[]),
('Laughter', 'laughter_us.mp3', 'noun', 'B1', 'the act or sound of laughing', '', 'to roar/howl with laughter', '', ARRAY[]::TEXT[]),
('Launch', 'launch_us.mp3', 'noun', 'B1', 'the action of launching something', '', 'a missile/rocket launch', '', ARRAY[]::TEXT[]),
('Launch', 'launch_us.mp3', 'verb', 'B1', 'to start an activity, especially an organized one', '', 'The government recently launched a national road safety campaign.', '', ARRAY[]::TEXT[]),
('Law', 'law_us.mp3', 'noun', 'B1', 'a rule that deals with a particular crime, agreement, etc.', '', 'to pass a law (= officially make it part of the system of laws)', '', ARRAY[]::TEXT[]),
('Lawn', 'lawn_us.mp3', 'noun', 'B1', 'an area of ground covered in short grass in a garden or park, or used for playing a game on', '', 'In summer we have to mow the lawn twice a week.', '', ARRAY[]::TEXT[]),
('Lawsuit', 'lawsuit_us.mp3', 'noun', 'B1', 'a claim or complaint against somebody that a person or an organization can make in court', '', 'He filed a lawsuit against his record label.', '', ARRAY[]::TEXT[]),
('Lawyer', 'lawyer_us.mp3', 'noun', 'B1', 'a person who is trained and qualified to advise people about the law and to represent them in court, and to write legal documents', '', 'to hire a lawyer', '', ARRAY[]::TEXT[]),
('Lay', 'lay_us.mp3', 'verb', 'B1', 'to put somebody/something in a particular position, especially when it is done gently or carefully', '', 'lay somebody/something + adv./prep., He laid a hand on my arm.', '', ARRAY[]::TEXT[]),
('Layer', 'layer_us.mp3', 'noun', 'B1', 'a quantity or sheet of something that lies over a surface or between surfaces', '', 'layer (of something), A thin layer of dust covered everything.', '', ARRAY[]::TEXT[]),
('Layout', 'layout_us.mp3', 'noun', 'B1', 'the way in which the parts of something such as the page of a book, a website, a garden or a building are arranged', '', 'the layout of streets', '', ARRAY[]::TEXT[]),
('Lazy', 'lazy_us.mp3', 'adjective', 'B1', 'unwilling to work or be active; doing as little as possible', '', 'He was not stupid, just lazy.', '', ARRAY[]::TEXT[]),
('Lead', 'lead_us.mp3', 'verb', 'B1', 'to go with or in front of a person or an animal to show the way or to make them go in the right direction', '', 'If you lead, I''ll follow.', '', ARRAY[]::TEXT[]),
('Leader', 'leader_us.mp3', 'noun', 'B1', 'a person who leads a group of people, especially the head of a country, an organization, etc.', '', 'party/world leaders', '', ARRAY[]::TEXT[]),
('Leadership', 'leadership_us.mp3', 'noun', 'B1', 'the state or position of being a leader', '', 'a leadership role/position', '', ARRAY[]::TEXT[]),
('Leading', 'leading_us.mp3', 'adjective', 'B1', 'most important or most successful', '', 'a leading expert/authority/figure/member', '', ARRAY[]::TEXT[]),
('Leaf', 'leaf_us.mp3', 'noun', 'B1', 'a flat green part of a plant, growing from a stem or branch or from the root', '', 'lettuce/cabbage/oak leaves', '', ARRAY[]::TEXT[]),
('Leaflet', 'leaflet_us.mp3', 'noun', 'B1', 'a printed sheet of paper or a few printed pages that are given free to advertise or give information about something', '', 'We picked up a few leaflets on local places of interest.', '', ARRAY[]::TEXT[]),
('League', 'league_us.mp3', 'noun', 'B1', 'a group of sports teams who all play each other to earn points and find which team is best', '', 'Castleford have led the league for most of the season.', '', ARRAY[]::TEXT[]),
('Leak', 'leak_us.mp3', 'noun', 'B1', 'a small hole that lets liquid or gas flow in or out of something by accident', '', 'a leak in the roof', '', ARRAY[]::TEXT[]),
('Leak', 'leak_us.mp3', 'verb', 'B1', 'to allow liquid or gas to get in or out through a small hole', '', 'a leaking pipe', '', ARRAY[]::TEXT[]),
('Lean', 'lean_us.mp3', 'verb', 'B1', 'to bend or move from a straight position to a sloping position', '', 'I leaned back in my chair.', '', ARRAY[]::TEXT[]),
('Leap', 'leap_us.mp3', 'noun', 'B1', 'a long or high jump', '', 'a leap of six metres', '', ARRAY[]::TEXT[]),
('Leap', 'leap_us.mp3', 'verb', 'B1', 'to jump high or a long way', '', '+ adv./prep., A dolphin leapt out of the water.', '', ARRAY[]::TEXT[]),
('Learn', 'learn_us.mp3', 'verb', 'B1', 'to gain knowledge or skill by studying, from experience, from being taught, etc.', '', 'learn something, to learn a language/skill/trade', '', ARRAY[]::TEXT[]),
('Learning', 'learning_us.mp3', 'noun', 'B1', 'the process of learning something', '', 'lifelong/adult learning', '', ARRAY[]::TEXT[]),
('Least', 'least_us.mp3', 'adverb', 'B1', 'to the smallest degree', '', 'He always turns up just when you least expect him.', '', ARRAY[]::TEXT[]),
('Least', 'least_us.mp3', 'determiner', 'B1', 'smallest in size, amount, degree, etc.', '', 'He''s the best teacher, even though he has the least experience.', '', ARRAY[]::TEXT[]),
('Least', 'least_us.mp3', 'pronoun', 'B1', 'smallest in size, amount, degree, etc.', '', 'He''s the best teacher, even though he has the least experience.', '', ARRAY[]::TEXT[]),
('Leather', 'leather_us.mp3', 'noun', 'B1', 'material made by removing the hair or fur from animal skins and preserving the skins using special processes', '', 'a leather jacket', '', ARRAY[]::TEXT[]),
('Leave', 'leave_us.mp3', 'noun', 'B1', 'a period of time when you are allowed to be away from work for a holiday or for a special reason', '', 'to take a month’s paid/unpaid leave', '', ARRAY[]::TEXT[]),
('Leave', 'leave_us.mp3', 'verb', 'B1', 'to go away from a person or a place', '', 'Come on, it''s time we left (= time for us to leave).', '', ARRAY[]::TEXT[]),
('Lecture', 'lecture_us.mp3', 'noun', 'B1', 'a talk that is given to a group of people to teach them about a particular subject, often as part of a university or college course', '', 'to go to/attend a lecture', '', ARRAY[]::TEXT[]),
('Lecture', 'lecture_us.mp3', 'verb', 'B1', 'to give a talk or a series of talks to a group of people on a subject, especially as a way of teaching in a university or college', '', 'He has taught and lectured at the University of Pretoria.', '', ARRAY[]::TEXT[]),
('Left', 'left_us.mp3', 'adjective', 'B1', 'on the side of your body that is towards the west when you are facing north', '', 'Fewer people write with their left hand than with their right.', '', ARRAY[]::TEXT[]),
('Left', 'left_us.mp3', 'adverb', 'B1', 'on or to the left side', '', 'Turn left at the intersection.', '', ARRAY[]::TEXT[]),
('Left', 'left_us.mp3', 'noun', 'B1', 'the left side or direction', '', 'on the left, Take the next road on the left.', '', ARRAY[]::TEXT[]),
('Leg', 'leg_us.mp3', 'noun', 'B1', 'one of the long parts that connect the feet to the rest of the body', '', 'Sit on the floor, stretching your legs out in front of you.', '', ARRAY[]::TEXT[]),
('Legacy', 'legacy_us.mp3', 'noun', 'B1', 'money or property that is given to you by somebody when they die', '', 'They each received a legacy of $5 000.', '', ARRAY[]::TEXT[]),
('Legal', 'legal_us.mp3', 'adjective', 'B1', 'connected with the law', '', 'the legal profession/system', '', ARRAY[]::TEXT[]),
('Legend', 'legend_us.mp3', 'noun', 'B1', 'a story from ancient times about people and events, that may or may not be true; this type of story', '', 'The film is based on the legend of Robin Hood.', '', ARRAY[]::TEXT[]),
('Legendary', 'legendary_us.mp3', 'adjective', 'B1', 'very famous and talked about a lot by people', '', 'a legendary figure', '', ARRAY[]::TEXT[]),
('Legislation', 'legislation_us.mp3', 'noun', 'B1', 'a law or a set of laws passed by a parliament', '', 'an important piece of legislation', '', ARRAY[]::TEXT[]),
('Legislative', 'legislative_us.mp3', 'adjective', 'B1', 'connected with the act of making and passing laws', '', 'a legislative assembly/body/council', '', ARRAY[]::TEXT[]),
('Legislature', 'legislature_us.mp3', 'noun', 'B1', 'a group of people who have the power to make and change laws', '', 'a democratically elected legislature', '', ARRAY[]::TEXT[]),
('Legitimate', 'legitimate_us.mp3', 'adjective', 'B1', 'for which there is a fair and acceptable reason', '', 'a legitimate grievance', '', ARRAY[]::TEXT[]),
('Leisure', 'leisure_us.mp3', 'noun', 'B1', 'time when you are not working or studying; free time', '', 'These days we have more money and more leisure to enjoy it.', '', ARRAY[]::TEXT[]),
('Lemon', 'lemon_us.mp3', 'noun', 'B1', 'a yellow citrus fruit with juice that has a bitter, sharp taste. Slices of lemon and lemon juice are used in cooking and drinks.', '', 'Add a squeeze of lemon juice.', '', ARRAY[]::TEXT[]),
('Lend', 'lend_us.mp3', 'verb', 'B1', 'to give something to somebody or allow them to use something that belongs to you, which they have to return to you later', '', 'lend something, They will lend equipment free of charge.', '', ARRAY[]::TEXT[]),
('Length', 'length_us.mp3', 'noun', 'B1', 'the size or measurement of something from one end to the other', '', 'Measure the length of the line from A to B.', '', ARRAY[]::TEXT[]),
('Lengthy', 'lengthy_us.mp3', 'adjective', 'B1', 'very long, and often too long, in time or size', '', 'lengthy delays', '', ARRAY[]::TEXT[]),
('Lens', 'lens_us.mp3', 'noun', 'B1', 'a curved piece of glass or plastic that makes things look larger, smaller or clearer when you look through it', '', 'a pair of glasses with tinted lenses', '', ARRAY[]::TEXT[]),
('Lesbian', 'lesbian_us.mp3', 'adjective', 'B1', 'sexually attracted to other women; connected with lesbians', '', 'the lesbian and gay community', '', ARRAY[]::TEXT[]),
('Less', 'less_us.mp3', 'adverb', 'B1', 'to a smaller degree; not so much', '', 'less expensive/likely/intelligent', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
