INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Stay', 'stay_us.mp3', 'verb', 'B1', 'to continue to be in a particular place for a period of time without moving away', '', '+ adv./prep., Stay there and don''t move!', '', ARRAY[]::TEXT[]),
('Steadily', 'steadily_us.mp3', 'adverb', 'B1', 'gradually and in an even and regular way', '', 'The company''s exports have been increasing steadily.', '', ARRAY[]::TEXT[]),
('Steady', 'steady_us.mp3', 'adjective', 'B1', 'developing, growing, etc. gradually and in an even and regular way', '', 'We''ve had five years of steady economic growth.', '', ARRAY[]::TEXT[]),
('Steal', 'steal_us.mp3', 'verb', 'B1', 'to take something from a person, shop, etc. without permission and without intending to return it or pay for it', '', 'I''ll report you to the police if I catch you stealing again.', '', ARRAY[]::TEXT[]),
('Steam', 'steam_us.mp3', 'noun', 'B1', 'the hot gas that water changes into when it boils', '', 'Steam rose from the boiling kettle.', '', ARRAY[]::TEXT[]),
('Steel', 'steel_us.mp3', 'noun', 'B1', 'a strong, hard metal that is made of a mixture of iron and carbon', '', 'the iron and steel industry', '', ARRAY[]::TEXT[]),
('Steep', 'steep_us.mp3', 'adjective', 'B1', 'rising or falling quickly, not gradually', '', 'a steep hill/slope', '', ARRAY[]::TEXT[]),
('Steer', 'steer_us.mp3', 'verb', 'B1', 'to control the direction in which a boat, car, etc. moves', '', 'He steered the boat into the harbour.', '', ARRAY[]::TEXT[]),
('Stem', 'stem_us.mp3', 'noun', 'B1', 'the main long, thin part of a plant above the ground from which the leaves or flowers grow; a smaller part that grows from this and supports flowers or leaves', '', 'long, trailing stems of ivy', '', ARRAY[]::TEXT[]),
('Stem', 'stem_us.mp3', 'verb', 'B1', 'to stop something that is flowing from spreading or increasing', '', 'The cut was bandaged to stem the bleeding.', '', ARRAY[]::TEXT[]),
('Step', 'step_us.mp3', 'noun', 'B1', 'one of a series of things that you do in order to achieve something', '', 'We are taking steps to prevent pollution.', '', ARRAY[]::TEXT[]),
('Step', 'step_us.mp3', 'verb', 'B1', 'to lift your foot and move it in a particular direction or put it on or in something; to move a short distance', '', 'to step onto/off a bus', '', ARRAY[]::TEXT[]),
('Stereotype', 'stereotype_us.mp3', 'noun', 'B1', 'a fixed idea or image that many people have of a particular type of person or thing, but which is often not true in reality and may cause hurt and offence', '', 'cultural/gender/racial stereotypes', '', ARRAY[]::TEXT[]),
('Stick', 'stick_us.mp3', 'noun', 'B1', 'a thin piece of wood that has fallen or been broken from a tree', '', 'We collected dry sticks to start a fire.', '', ARRAY[]::TEXT[]),
('Stick', 'stick_us.mp3', 'verb', 'B1', 'to fix something to something else, usually with a sticky substance; to become fixed to something in this way', '', 'stick something + adv./prep., He stuck a stamp on the envelope.', '', ARRAY[]::TEXT[]),
('Sticky', 'sticky_us.mp3', 'adjective', 'B1', 'made of or covered in a substance that sticks to things that touch it', '', 'sticky fingers covered in jam', '', ARRAY[]::TEXT[]),
('Stiff', 'stiff_us.mp3', 'adjective', 'B1', 'difficult to bend or move', '', 'a sheet of stiff black cardboard', '', ARRAY[]::TEXT[]),
('Still', 'still_us.mp3', 'adjective', 'B1', 'not moving; calm and quiet', '', 'A fallen tree floated in the still water.', '', ARRAY[]::TEXT[]),
('Still', 'still_us.mp3', 'adverb', 'B1', 'continuing until a particular point in time and not finishing', '', 'I am very happy that you all are still alive and well.', '', ARRAY[]::TEXT[]),
('Stimulate', 'stimulate_us.mp3', 'verb', 'B1', 'to make something develop or become more active; to encourage something', '', 'The exhibition has stimulated interest in her work.', '', ARRAY[]::TEXT[]),
('Stimulus', 'stimulus_us.mp3', 'noun', 'B1', 'something that helps somebody/something to develop better or more quickly', '', 'stimulus for something, Books provide children with ideas and a stimulus for play.', '', ARRAY[]::TEXT[]),
('Stir', 'stir_us.mp3', 'verb', 'B1', 'to move a liquid or substance around, using a spoon or something similar, in order to mix it completely', '', 'stir something, She stirred her tea.', '', ARRAY[]::TEXT[]),
('Stock', 'stock_us.mp3', 'noun', 'B1', 'a supply of goods that is available for sale in a shop', '', 'We have a fast turnover of stock.', '', ARRAY[]::TEXT[]),
('Stomach', 'stomach_us.mp3', 'noun', 'B1', 'the organ inside the body where food goes when you eat it', '', 'stomach pains/cramps', '', ARRAY[]::TEXT[]),
('Stone', 'stone_us.mp3', 'noun', 'B1', 'a hard solid mineral substance that is found in the ground, often used for building', '', 'Most of the houses are built of stone.', '', ARRAY[]::TEXT[]),
('Stop', 'stop_us.mp3', 'noun', 'B1', 'a place where a bus or train stops regularly for passengers to get on or off', '', 'I get off at the next stop.', '', ARRAY[]::TEXT[]),
('Stop', 'stop_us.mp3', 'verb', 'B1', 'to no longer move; to make somebody/something no longer move', '', 'The car stopped at the traffic lights.', '', ARRAY[]::TEXT[]),
('Storage', 'storage_us.mp3', 'noun', 'B1', 'the process of keeping something in a particular place until it is needed; the space where things can be kept', '', 'tables that fold flat for storage', '', ARRAY[]::TEXT[]),
('Store', 'store_us.mp3', 'noun', 'B1', 'a large shop that sells many different types of goods', '', 'It''s available at London''s three biggest stores.', '', ARRAY[]::TEXT[]),
('Store', 'store_us.mp3', 'verb', 'B1', 'to put something somewhere and keep it there to use later', '', 'store something, We do not have adequate space to store these documents.', '', ARRAY[]::TEXT[]),
('Storm', 'storm_us.mp3', 'noun', 'B1', 'very bad weather with strong winds and rain, and often thunder and lightning', '', 'fierce/heavy/severe/violent storms', '', ARRAY[]::TEXT[]),
('Story', 'story_us.mp3', 'noun', 'B1', 'a description of events and people that the writer or speaker has invented in order to entertain people', '', 'a tragic love story', '', ARRAY[]::TEXT[]),
('Straight', 'straight_us.mp3', 'adjective', 'B1', 'without a bend or curve; going in one direction only', '', 'a straight road', '', ARRAY[]::TEXT[]),
('Straight', 'straight_us.mp3', 'adverb', 'B1', 'not in a curve or at an angle; in a straight line', '', 'Keep straight on for two miles.', '', ARRAY[]::TEXT[]),
('Straightforward', 'straightforward_us.mp3', 'adjective', 'B1', 'easy to do or to understand; not complicated', '', 'It''s a relatively straightforward process.', '', ARRAY[]::TEXT[]),
('Strain', 'strain_us.mp3', 'noun', 'B1', 'pressure on a system or relationship because great demands are being placed on it', '', 'The transport service cannot cope with the strain of so many additional passengers.', '', ARRAY[]::TEXT[]),
('Strand', 'strand_us.mp3', 'noun', 'B1', 'a single thin piece of thread, wire, hair, etc.', '', 'He pulled at a loose strand of wool in his sweater.', '', ARRAY[]::TEXT[]),
('Strange', 'strange_us.mp3', 'adjective', 'B1', 'unusual or surprising, especially in a way that is difficult to understand', '', 'A strange thing happened this morning.', '', ARRAY[]::TEXT[]),
('Stranger', 'stranger_us.mp3', 'noun', 'B1', 'a person that you do not know', '', 'There was a complete stranger sitting at my desk.', '', ARRAY[]::TEXT[]),
('Strategic', 'strategic_us.mp3', 'adjective', 'B1', 'done as part of a plan that is meant to achieve a particular purpose or to gain an advantage', '', 'strategic planning', '', ARRAY[]::TEXT[]),
('Strategy', 'strategy_us.mp3', 'noun', 'B1', 'a plan that is intended to achieve a particular purpose', '', 'the government’s economic strategy', '', ARRAY[]::TEXT[]),
('Stream', 'stream_us.mp3', 'noun', 'B1', 'a small, narrow river', '', 'a mountain stream', '', ARRAY[]::TEXT[]),
('Street', 'street_us.mp3', 'noun', 'B1', 'a public road in a city or town that has houses and buildings on one side or both sides', '', 'along/down/up the street, I was just walking along the street when it happened.', '', ARRAY[]::TEXT[]),
('Strength', 'strength_us.mp3', 'noun', 'B1', 'the quality of being physically strong', '', 'He pushed against the rock with all his strength.', '', ARRAY[]::TEXT[]),
('Strengthen', 'strengthen_us.mp3', 'verb', 'B1', 'to become more powerful or effective; to make somebody/something more powerful or effective', '', 'Her position in the party has strengthened in recent weeks.', '', ARRAY[]::TEXT[]),
('Stress', 'stress_us.mp3', 'noun', 'B1', 'pressure or worry caused by problems in somebody’s life or by having too much to do', '', 'emotional/mental stress', '', ARRAY[]::TEXT[]),
('Stress', 'stress_us.mp3', 'verb', 'B1', 'to give extra force to a word or syllable when saying it', '', 'You stress the first syllable in ‘happiness’.', '', ARRAY[]::TEXT[]),
('Stretch', 'stretch_us.mp3', 'noun', 'B1', 'an area of land or water, especially a long one', '', 'a particularly dangerous stretch of road', '', ARRAY[]::TEXT[]),
('Stretch', 'stretch_us.mp3', 'verb', 'B1', 'to make something longer, wider or looser, for example by pulling it; to become longer, etc. in this way', '', 'Is there any way of stretching shoes?', '', ARRAY[]::TEXT[]),
('Strict', 'strict_us.mp3', 'adjective', 'B1', 'that must be obeyed exactly', '', 'strict rules/regulations', '', ARRAY[]::TEXT[]),
('Strictly', 'strictly_us.mp3', 'adverb', 'B1', 'with a lot of control and rules that must be obeyed', '', 'She was brought up very strictly.', '', ARRAY[]::TEXT[]),
('Strike', 'strike_us.mp3', 'noun', 'B1', 'a period of time when an organized group of employees of a company stops working because of an argument over pay or conditions', '', 'the miners''/firefighters''/teachers'' strike', '', ARRAY[]::TEXT[]),
('Strike', 'strike_us.mp3', 'verb', 'B1', 'to hit somebody/something hard or with force', '', 'strike somebody/something, The ship struck a rock.', '', ARRAY[]::TEXT[]),
('Striking', 'striking_us.mp3', 'adjective', 'B1', 'interesting and unusual enough to attract attention', '', 'a striking feature', '', ARRAY[]::TEXT[]),
('String', 'string_us.mp3', 'noun', 'B1', 'long, thin material used for tying things together, made of several threads that have been twisted together; a piece of string used to fasten or pull something or keep something in place', '', 'a piece/length/ball of string', '', ARRAY[]::TEXT[]),
('Strip', 'strip_us.mp3', 'noun', 'B1', 'a long narrow piece of paper, metal, cloth, etc.', '', 'a strip of material', '', ARRAY[]::TEXT[]),
('Strip', 'strip_us.mp3', 'verb', 'B1', 'to take off all or most of your clothes or another person’s clothes', '', 'I stripped and washed myself all over.', '', ARRAY[]::TEXT[]),
('Strive', 'strive_us.mp3', 'verb', 'B1', 'to try very hard to achieve something', '', 'strive for something, We encourage all members to strive for the highest standards.', '', ARRAY[]::TEXT[]),
('Stroke', 'stroke_us.mp3', 'noun', 'B1', 'an act of hitting a ball, for example with a bat or racket', '', 'What a beautiful stroke!', '', ARRAY[]::TEXT[]),
('Strong', 'strong_us.mp3', 'adjective', 'B1', 'having a lot of physical power so that you can lift heavy weights, do hard physical work, etc.', '', 'He''s strong enough to lift a car!', '', ARRAY[]::TEXT[]),
('Strongly', 'strongly_us.mp3', 'adverb', 'B1', 'in a way that shows definite and serious opinions or beliefs', '', 'a strongly worded protest', '', ARRAY[]::TEXT[]),
('Structural', 'structural_us.mp3', 'adjective', 'B1', 'connected with the way in which something is built or organized', '', 'Storms have caused structural damage to hundreds of homes.', '', ARRAY[]::TEXT[]),
('Structure', 'structure_us.mp3', 'noun', 'B1', 'the way in which the parts of something are connected together, arranged or organized; a particular arrangement of parts', '', 'the structure of the building', '', ARRAY[]::TEXT[]),
('Structure', 'structure_us.mp3', 'verb', 'B1', 'to arrange or organize something into a system or pattern', '', 'structure something, How well does the teacher structure the lessons?', '', ARRAY[]::TEXT[]),
('Struggle', 'struggle_us.mp3', 'noun', 'B1', 'a hard fight in which people try to obtain or achieve something, especially something that somebody else does not want them to have', '', 'Marx wrote about the class struggle.', '', ARRAY[]::TEXT[]),
('Struggle', 'struggle_us.mp3', 'verb', 'B1', 'to try very hard to do something when it is difficult or when there are a lot of problems', '', 'life as a struggling artist (= one who is very poor)', '', ARRAY[]::TEXT[]),
('Student', 'student_us.mp3', 'noun', 'B1', 'a person who is studying at a university or college', '', 'a college/university student', '', ARRAY[]::TEXT[]),
('Studio', 'studio_us.mp3', 'noun', 'B1', 'a room where radio or television programmes are recorded and broadcast from, or where music is recorded', '', 'a television/recording studio', '', ARRAY[]::TEXT[]),
('Study', 'study_us.mp3', 'noun', 'B1', 'the activity of learning or gaining knowledge, either from books or by examining things in the world', '', 'a room set aside for private study', '', ARRAY[]::TEXT[]),
('Study', 'study_us.mp3', 'verb', 'B1', 'to spend time learning about a subject by reading, going to college, etc.', '', 'He sat up very late that night, studying.', '', ARRAY[]::TEXT[]),
('Stuff', 'stuff_us.mp3', 'noun', 'B1', 'used to refer to a substance, material, group of objects, etc. when you do not know the name, when the name is not important or when it is obvious what you are talking about', '', 'What''s all that sticky stuff on the carpet?', '', ARRAY[]::TEXT[]),
('Stuff', 'stuff_us.mp3', 'verb', 'B1', 'to fill a space or container tightly with something', '', 'stuff A with B, She had 500 envelopes to stuff with leaflets.', '', ARRAY[]::TEXT[]),
('Stumble', 'stumble_us.mp3', 'verb', 'B1', 'to hit your foot against something while you are walking or running and almost fall', '', 'The child stumbled and fell.', '', ARRAY[]::TEXT[]),
('Stun', 'stun_us.mp3', 'verb', 'B1', 'to make a person or an animal unconscious for a short time, especially by hitting them on the head', '', 'The fall stunned me for a moment.', '', ARRAY[]::TEXT[]),
('Stunning', 'stunning_us.mp3', 'adjective', 'B1', 'extremely attractive or impressive', '', 'You look absolutely stunning!', '', ARRAY[]::TEXT[]),
('Stupid', 'stupid_us.mp3', 'adjective', 'B1', 'showing a lack of thought or good judgement', '', 'a stupid mistake/question/idea', '', ARRAY[]::TEXT[]),
('Style', 'style_us.mp3', 'noun', 'B1', 'the particular way in which something is done', '', 'a wide range of musical styles', '', ARRAY[]::TEXT[]),
('Subject', 'subject_us.mp3', 'adjective', 'B1', 'likely to be affected by something, especially something bad', '', 'At this stage these are proposals and are still subject to change.', '', ARRAY[]::TEXT[]),
('Subject', 'subject_us.mp3', 'noun', 'B1', 'a thing or person that is being discussed, described or dealt with', '', 'subject of something, Walker''s work has been the subject of much debate.', '', ARRAY[]::TEXT[]),
('Submission', 'submission_us.mp3', 'noun', 'B1', 'the act of accepting that somebody has defeated you and that you must obey them', '', 'a gesture of submission', '', ARRAY[]::TEXT[]),
('Submit', 'submit_us.mp3', 'verb', 'B1', 'to give a document, proposal, etc. to somebody in authority so that they can study or consider it', '', 'submit something, to submit an application/a claim/a proposal', '', ARRAY[]::TEXT[]),
('Subscriber', 'subscriber_us.mp3', 'noun', 'B1', 'a person who pays money, usually once a year, to receive regular copies of a magazine or newspaper or have access to it online', '', 'subscribers to ‘New Scientist’', '', ARRAY[]::TEXT[]),
('Subscription', 'subscription_us.mp3', 'noun', 'B1', 'an amount of money that you pay regularly to receive a service, be a member of a club, support a charity or receive regular copies of a newspaper or magazine; the act of paying this money', '', 'an annual subscription', '', ARRAY[]::TEXT[]),
('Subsequent', 'subsequent_us.mp3', 'adjective', 'B1', 'happening or coming after something else', '', 'subsequent generations', '', ARRAY[]::TEXT[]),
('Subsequently', 'subsequently_us.mp3', 'adverb', 'B1', 'afterwards; later; after something else has happened', '', 'The original interview notes were subsequently lost.', '', ARRAY[]::TEXT[]),
('Subsidy', 'subsidy_us.mp3', 'noun', 'B1', 'money that is paid by a government or an organization to reduce the costs of services or of producing goods so that their prices can be kept low', '', 'agricultural subsidies', '', ARRAY[]::TEXT[]),
('Substance', 'substance_us.mp3', 'noun', 'B1', 'a type of solid, liquid or gas that has particular qualities', '', 'a sticky substance', '', ARRAY[]::TEXT[]),
('Substantial', 'substantial_us.mp3', 'adjective', 'B1', 'large in amount, value or importance', '', 'substantial sums of money', '', ARRAY[]::TEXT[]),
('Substantially', 'substantially_us.mp3', 'adverb', 'B1', 'very much; a lot', '', 'The costs have increased substantially.', '', ARRAY[]::TEXT[]),
('Substitute', 'substitute_us.mp3', 'noun', 'B1', 'a person or thing that you use or have instead of the one you normally use or have', '', 'a meat substitute', '', ARRAY[]::TEXT[]),
('Substitute', 'substitute_us.mp3', 'verb', 'B1', 'to take the place of somebody/something else; to use somebody/something instead of somebody/something else', '', 'substitute for somebody/something, Nothing can substitute for the advice your doctor is able to give you.', '', ARRAY[]::TEXT[]),
('Substitution', 'substitution_us.mp3', 'noun', 'B1', 'an act of using one person or thing in the place of another', '', 'Two substitutions were made during the game.', '', ARRAY[]::TEXT[]),
('Subtle', 'subtle_us.mp3', 'adjective', 'B1', 'not very obvious or easy to notice', '', 'subtle colours/flavours/smells, etc.', '', ARRAY[]::TEXT[]),
('Suburb', 'suburb_us.mp3', 'noun', 'B1', 'an area where people live that is outside the centre of a city', '', 'a suburb of London', '', ARRAY[]::TEXT[]),
('Suburban', 'suburban_us.mp3', 'adjective', 'B1', 'in or connected with a suburb', '', 'suburban areas', '', ARRAY[]::TEXT[]),
('Succeed', 'succeed_us.mp3', 'verb', 'B1', 'to achieve something that you have been trying to do or get; to have the result or effect that was intended', '', 'Our plan succeeded.', '', ARRAY[]::TEXT[]),
('Success', 'success_us.mp3', 'noun', 'B1', 'the fact that you have achieved something that you want and have been trying to do or get', '', 'The company has achieved considerable success in this market.', '', ARRAY[]::TEXT[]),
('Successful', 'successful_us.mp3', 'adjective', 'B1', 'achieving your aims or what was intended', '', 'The experiment was entirely successful.', '', ARRAY[]::TEXT[]),
('Successfully', 'successfully_us.mp3', 'adverb', 'B1', 'in a way that achieves your aims or what was intended', '', 'She had already successfully completed these courses.', '', ARRAY[]::TEXT[]),
('Succession', 'succession_us.mp3', 'noun', 'B1', 'a number of people or things that follow each other in time or order', '', 'a succession of visitors', '', ARRAY[]::TEXT[]),
('Successive', 'successive_us.mp3', 'adjective', 'B1', 'following immediately one after the other', '', 'This was their fourth successive win.', '', ARRAY[]::TEXT[]),
('Successor', 'successor_us.mp3', 'noun', 'B1', 'a person or thing that comes after somebody/something else and takes their/its place', '', 'Who''s the likely successor to him as party leader?', '', ARRAY[]::TEXT[]),
('Such', 'such_us.mp3', 'determiner', 'B1', 'used to emphasize the great degree of something', '', 'This issue was of such importance that we could not afford to ignore it.', '', ARRAY[]::TEXT[]),
('Such', 'such_us.mp3', 'pronoun', 'B1', 'used to emphasize the great degree of something', '', 'This issue was of such importance that we could not afford to ignore it.', '', ARRAY[]::TEXT[]),
('Suck', 'suck_us.mp3', 'verb', 'B1', 'to take liquid, air, etc. into your mouth by using the muscles of your lips', '', 'to suck the juice from an orange', '', ARRAY[]::TEXT[]),
('Sudden', 'sudden_us.mp3', 'adjective', 'B1', 'happening or done quickly and unexpectedly', '', 'News of his sudden and unexpected death came as a great shock.', '', ARRAY[]::TEXT[]),
('Suddenly', 'suddenly_us.mp3', 'adverb', 'B1', 'quickly and unexpectedly', '', 'I suddenly realized what I had to do.', '', ARRAY[]::TEXT[]),
('Sue', 'sue_us.mp3', 'verb', 'B1', 'to make a claim against a person or an organization in court about something that they have said or done to harm you', '', 'They threatened to sue if the work was not completed.', '', ARRAY[]::TEXT[]),
('Suffer', 'suffer_us.mp3', 'verb', 'B1', 'to be badly affected by a disease, pain, sad feelings, a lack of something, etc.', '', 'I hate to see animals suffering.', '', ARRAY[]::TEXT[]),
('Suffering', 'suffering_us.mp3', 'noun', 'B1', 'physical or mental pain', '', 'Death finally brought an end to her suffering.', '', ARRAY[]::TEXT[]),
('Sufficient', 'sufficient_us.mp3', 'adjective', 'B1', 'enough for a particular purpose; as much as you need', '', 'Allow sufficient time to get there.', '', ARRAY[]::TEXT[]),
('Sufficiently', 'sufficiently_us.mp3', 'adverb', 'B1', 'enough for a particular purpose; as much as you need', '', 'The following day she felt sufficiently well to go to work.', '', ARRAY[]::TEXT[]),
('Sugar', 'sugar_us.mp3', 'noun', 'B1', 'a sweet substance, often in the form of white or brown crystals, made from the juices of various plants, used in cooking or to make tea, coffee, etc. sweeter', '', 'Do you take sugar (= have it in your tea, coffee, etc.)?', '', ARRAY[]::TEXT[]),
('Suggest', 'suggest_us.mp3', 'verb', 'B1', 'to put forward an idea or a plan for other people to think about', '', 'suggest something, I''d like to suggest a different explanation for the company''s decline.', '', ARRAY[]::TEXT[]),
('Suggestion', 'suggestion_us.mp3', 'noun', 'B1', 'an idea or a plan that you mention for somebody else to think about', '', 'Can I make a suggestion?', '', ARRAY[]::TEXT[]),
('Suicide', 'suicide_us.mp3', 'noun', 'B1', 'the act of killing yourself deliberately', '', 'to commit suicide', '', ARRAY[]::TEXT[]),
('Suit', 'suit_us.mp3', 'noun', 'B1', 'a set of clothes made of the same cloth, including a jacket and trousers or a skirt', '', 'She was wearing a grey business suit.', '', ARRAY[]::TEXT[]),
('Suit', 'suit_us.mp3', 'verb', 'B1', 'to be convenient or useful for somebody', '', 'suit somebody/something, If we met at two, would that suit you?', '', ARRAY[]::TEXT[]),
('Suitable', 'suitable_us.mp3', 'adjective', 'B1', 'right or appropriate for a particular purpose or occasion', '', 'a suitable candidate', '', ARRAY[]::TEXT[]),
('Suite', 'suite_us.mp3', 'noun', 'B1', 'a set of rooms, especially in a hotel', '', 'a hotel/private/honeymoon suite', '', ARRAY[]::TEXT[]),
('Sum', 'sum_us.mp3', 'noun', 'B1', 'an amount of money', '', 'You will be fined the sum of £200.', '', ARRAY[]::TEXT[]),
('Summarize', 'summarize_us.mp3', 'verb', 'B1', 'to give a summary of something', '', 'This essay briefly summarizes some of our approaches.', '', ARRAY[]::TEXT[]),
('Summary', 'summary_us.mp3', 'noun', 'B1', 'a short statement that gives only the main points of something, not the details', '', 'a news summary', '', ARRAY[]::TEXT[]),
('Summer', 'summer_us.mp3', 'noun', 'B1', 'the warmest season of the year, coming between spring and autumn', '', 'in the summer, We''re going away in the summer.', '', ARRAY[]::TEXT[]),
('Summit', 'summit_us.mp3', 'noun', 'B1', 'the highest point of something, especially the top of a mountain', '', 'We reached the summit at noon.', '', ARRAY[]::TEXT[]),
('Sun', 'sun_us.mp3', 'noun', 'B1', 'the star that shines in the sky during the day and gives the earth heat and light', '', 'The sun was shining and birds were singing.', '', ARRAY[]::TEXT[]),
('Sunday', 'Sunday_us.mp3', 'noun', 'B1', 'the day of the week after Saturday and before Monday, thought of as either the first or the last day of the week', '', 'It''s Sunday today, isn''t it?', '', ARRAY[]::TEXT[]),
('Super', 'super_us.mp3', 'adjective', 'B1', 'extremely good', '', 'a super meal', '', ARRAY[]::TEXT[]),
('Superb', 'superb_us.mp3', 'adjective', 'B1', 'excellent; of very good quality', '', 'a superb player', '', ARRAY[]::TEXT[]),
('Superior', 'superior_us.mp3', 'adjective', 'B1', 'better in quality than somebody/something else; greater than somebody/something else', '', 'vastly superior', '', ARRAY[]::TEXT[]),
('Supermarket', 'supermarket_us.mp3', 'noun', 'B1', 'a large shop that sells food, drinks and goods used in the home. People choose what they want from the shelves and pay for it as they leave.', '', 'I only shop at this supermarket.', '', ARRAY[]::TEXT[]),
('Supervise', 'supervise_us.mp3', 'verb', 'B1', 'to be in charge of somebody/something and make sure that everything is done correctly, safely, etc.', '', 'supervise (somebody/something), to supervise building work', '', ARRAY[]::TEXT[]),
('Supervision', 'supervision_us.mp3', 'noun', 'B1', 'the work or activity involved in being in charge of somebody/something and making sure that everything is done correctly, safely, etc.', '', 'Very young children should not be left to play without supervision.', '', ARRAY[]::TEXT[]),
('Supervisor', 'supervisor_us.mp3', 'noun', 'B1', 'a person who supervises somebody/something', '', 'I have a meeting with my supervisor about my research topic.', '', ARRAY[]::TEXT[]),
('Supplement', 'supplement_us.mp3', 'noun', 'B1', 'a thing that is added to something else to improve or complete it', '', 'vitamin/dietary supplements (= vitamins and other foods eaten in addition to what you usually eat)', '', ARRAY[]::TEXT[]),
('Supplement', 'supplement_us.mp3', 'verb', 'B1', 'to add something to something in order to improve it or make it more complete', '', 'supplement something with something, a diet supplemented with vitamin pills', '', ARRAY[]::TEXT[]),
('Supply', 'supply_us.mp3', 'noun', 'B1', 'an amount of something that is provided or available to be used', '', 'Advances in agriculture increased the food supply.', '', ARRAY[]::TEXT[]),
('Supply', 'supply_us.mp3', 'verb', 'B1', 'to provide somebody/something with something that they need or want, especially in large quantities', '', 'supply something to somebody/something, The company supplied sports equipment to schools.', '', ARRAY[]::TEXT[]),
('Support', 'support_us.mp3', 'noun', 'B1', 'approval that you give to somebody/something because you want them to be successful', '', 'support for something, There is strong public support for the policy.', '', ARRAY[]::TEXT[]),
('Support', 'support_us.mp3', 'verb', 'B1', 'to help or encourage somebody/something by saying or showing that you agree with them/it', '', 'support somebody/something, to support an idea/a view', '', ARRAY[]::TEXT[]),
('Supporter', 'supporter_us.mp3', 'noun', 'B1', 'a person who supports a political party, an idea, etc.', '', 'a strong/loyal/staunch/ardent supporter', '', ARRAY[]::TEXT[]),
('Supportive', 'supportive_us.mp3', 'adjective', 'B1', 'encouraging somebody or giving them help or sympathy', '', 'a supportive family', '', ARRAY[]::TEXT[]),
('Suppose', 'suppose_us.mp3', 'verb', 'B1', 'to think or believe that something is true or possible (based on the knowledge that you have)', '', 'Getting a visa isn''t as simple as you might suppose.', '', ARRAY[]::TEXT[]),
('Supposedly', 'supposedly_us.mp3', 'adverb', 'B1', 'according to what is generally thought or believed but not known for certain', '', 'The novel is supposedly based on a true story.', '', ARRAY[]::TEXT[]),
('Suppress', 'suppress_us.mp3', 'verb', 'B1', 'to put an end, often by force, to a group or an activity that is believed to threaten authority', '', 'The rebellion was brutally suppressed.', '', ARRAY[]::TEXT[]),
('Supreme', 'supreme_us.mp3', 'adjective', 'B1', 'highest in rank or position', '', 'the Supreme Commander of the armed forces', '', ARRAY[]::TEXT[]),
('Sure', 'sure_us.mp3', 'adjective', 'B1', 'confident that you know something or that you are right', '', '‘Is that John over there?’ ‘I''m not sure’.', '', ARRAY[]::TEXT[]),
('Sure', 'sure_us.mp3', 'adverb', 'B1', 'used to say ‘yes’ to somebody', '', '‘Will you get me my coat?’ ‘Sure, where is it?’', '', ARRAY[]::TEXT[]),
('Surely', 'surely_us.mp3', 'adverb', 'B1', 'used to show that you are almost certain of what you are saying and want other people to agree with you', '', 'Surely we should do something about it?', '', ARRAY[]::TEXT[]),
('Surface', 'surface_us.mp3', 'noun', 'B1', 'the outside or top layer of something', '', 'We need a flat, smooth surface to play the game on.', '', ARRAY[]::TEXT[]),
('Surge', 'surge_us.mp3', 'noun', 'B1', 'a sudden increase of a strong feeling', '', 'She felt a sudden surge of anger.', '', ARRAY[]::TEXT[]),
('Surge', 'surge_us.mp3', 'verb', 'B1', 'to move quickly and with force in a particular direction', '', 'The gates opened and the crowd surged forward.', '', ARRAY[]::TEXT[]),
('Surgeon', 'surgeon_us.mp3', 'noun', 'B1', 'a doctor who is trained to perform surgery (= medical operations that involve cutting open a person’s body)', '', 'a brain/heart surgeon', '', ARRAY[]::TEXT[]),
('Surgery', 'surgery_us.mp3', 'noun', 'B1', 'medical treatment of injuries or diseases that involves cutting open a person’s body and often removing or replacing some parts; the branch of medicine connected with this treatment', '', 'major/minor surgery', '', ARRAY[]::TEXT[]),
('Surgical', 'surgical_us.mp3', 'adjective', 'B1', 'used in or connected with surgery', '', 'surgical procedures', '', ARRAY[]::TEXT[]),
('Surplus', 'surplus_us.mp3', 'noun', 'B1', 'an amount that is extra or more than you need', '', 'food surpluses', '', ARRAY[]::TEXT[]),
('Surprise', 'surprise_us.mp3', 'noun', 'B1', 'an event, a piece of news, etc. that is unexpected or that happens suddenly', '', 'What a nice surprise!', '', ARRAY[]::TEXT[]),
('Surprise', 'surprise_us.mp3', 'verb', 'B1', 'to make somebody feel surprised', '', 'surprise somebody, It wouldn''t surprise me if they got married soon.', '', ARRAY[]::TEXT[]),
('Surprised', 'surprised_us.mp3', 'adjective', 'B1', 'feeling or showing surprise', '', 'a surprised look', '', ARRAY[]::TEXT[]),
('Surprising', 'surprising_us.mp3', 'adjective', 'B1', 'causing surprise', '', 'It’s not surprising (that) they lost.', '', ARRAY[]::TEXT[]),
('Surrender', 'surrender_us.mp3', 'verb', 'B1', 'to admit that you have been defeated and want to stop fighting; to allow yourself to be caught, taken prisoner, etc.', '', 'The rebel soldiers were forced to surrender.', '', ARRAY[]::TEXT[]),
('Surround', 'surround_us.mp3', 'verb', 'B1', 'to be all around something/somebody', '', 'surround something/somebody, Tall trees surround the lake.', '', ARRAY[]::TEXT[]),
('Surrounding', 'surrounding_us.mp3', 'adjective', 'B1', 'that is near or around something', '', 'Oxford and the surrounding area', '', ARRAY[]::TEXT[]),
('Surveillance', 'surveillance_us.mp3', 'noun', 'B1', 'the act of carefully watching a person suspected of a crime or a place where a crime may be committed', '', 'The police are keeping the suspects under constant surveillance.', '', ARRAY[]::TEXT[]),
('Survey', 'survey_us.mp3', 'noun', 'B1', 'an investigation of the opinions, behaviour, etc. of a particular group of people, which is usually done by asking them questions', '', 'A recent survey showed 75 per cent of those questioned were in favour of the plan.', '', ARRAY[]::TEXT[]),
('Survey', 'survey_us.mp3', 'verb', 'B1', 'to look carefully at the whole of something, especially in order to get a general impression of it', '', 'The next morning we surveyed the damage caused by the fire.', '', ARRAY[]::TEXT[]),
('Survival', 'survival_us.mp3', 'noun', 'B1', 'the state of continuing to live or exist, often despite difficulty or danger', '', 'the struggle/battle/fight for survival', '', ARRAY[]::TEXT[]),
('Survive', 'survive_us.mp3', 'verb', 'B1', 'to continue to live or exist', '', 'She was the last surviving member of the family.', '', ARRAY[]::TEXT[]),
('Survivor', 'survivor_us.mp3', 'noun', 'B1', 'a person who continues to live, especially despite being nearly killed or experiencing great danger or difficulty', '', 'the sole/only survivor of the massacre', '', ARRAY[]::TEXT[]),
('Suspect', 'suspect_us.mp3', 'noun', 'B1', 'a person who is suspected of a crime or of having done something wrong', '', 'a murder suspect', '', ARRAY[]::TEXT[]),
('Suspect', 'suspect_us.mp3', 'verb', 'B1', 'to have an idea that something is probably true or likely to happen, especially something bad, but without having definite proof', '', 'As I had suspected all along, he was not a real policeman.', '', ARRAY[]::TEXT[]),
('Suspend', 'suspend_us.mp3', 'verb', 'B1', 'to hang something from something else', '', 'be suspended from something, A lamp was suspended from the ceiling.', '', ARRAY[]::TEXT[]),
('Suspension', 'suspension_us.mp3', 'noun', 'B1', 'the act of officially removing somebody from their job, school, team, etc. for a period of time, usually as a punishment', '', 'suspension from school', '', ARRAY[]::TEXT[]),
('Suspicion', 'suspicion_us.mp3', 'noun', 'B1', 'a feeling that somebody has done something wrong, illegal or dishonest, even though you have no proof', '', 'They drove away slowly to avoid arousing suspicion.', '', ARRAY[]::TEXT[]),
('Suspicious', 'suspicious_us.mp3', 'adjective', 'B1', 'feeling that somebody has done something wrong, illegal or dishonest, without having any proof', '', 'They became suspicious of his behaviour and contacted the police.', '', ARRAY[]::TEXT[]),
('Sustain', 'sustain_us.mp3', 'verb', 'B1', 'to provide enough of what somebody/something needs in order to live or exist', '', 'Which planets can sustain life?', '', ARRAY[]::TEXT[]),
('Sustainable', 'sustainable_us.mp3', 'adjective', 'B1', 'involving the use of natural products and energy in a way that does not harm the environment', '', 'sustainable forest management', '', ARRAY[]::TEXT[]),
('Swallow', 'swallow_us.mp3', 'verb', 'B1', 'to make food, drink, etc. go down your throat into your stomach', '', 'swallow (something), Always chew food well before swallowing it.', '', ARRAY[]::TEXT[]),
('Swear', 'swear_us.mp3', 'verb', 'B1', 'to use rude or offensive language, usually because you are angry', '', 'She fell over and swore loudly.', '', ARRAY[]::TEXT[]),
('Sweater', 'sweater_us.mp3', 'noun', 'B1', 'a piece of clothing for the upper part of the body, made of wool or cotton, with long sleeves', '', 'She wore jeans and a sweater.', '', ARRAY[]::TEXT[]),
('Sweep', 'sweep_us.mp3', 'verb', 'B1', 'to clean a room, surface, etc. using a broom (= a type of brush on a long handle)', '', 'sweep (something), to sweep the floor', '', ARRAY[]::TEXT[]),
('Sweet', 'sweet_us.mp3', 'adjective', 'B1', 'containing, or tasting as if it contains, a lot of sugar', '', 'a cup of hot sweet tea', '', ARRAY[]::TEXT[]),
('Sweet', 'sweet_us.mp3', 'noun', 'B1', 'a small piece of sweet food, usually made with sugar and/or chocolate and eaten between meals', '', 'a packet of sweets', '', ARRAY[]::TEXT[]),
('Swim', 'swim_us.mp3', 'noun', 'B1', 'a period of time during which you swim', '', 'Let''s go for a swim.', '', ARRAY[]::TEXT[]),
('Swim', 'swim_us.mp3', 'verb', 'B1', 'to move through water by moving your arms and legs, without touching the bottom', '', 'I can''t swim.', '', ARRAY[]::TEXT[]),
('Swimming', 'swimming_us.mp3', 'noun', 'B1', 'the sport or activity of swimming', '', 'Swimming is a good form of exercise.', '', ARRAY[]::TEXT[]),
('Swing', 'swing_us.mp3', 'noun', 'B1', 'a swinging movement or rhythm', '', 'He took a wild swing at the ball.', '', ARRAY[]::TEXT[]),
('Swing', 'swing_us.mp3', 'verb', 'B1', 'to move backwards or forwards or from side to side while hanging from a fixed point; to make something do this', '', 'His arms swung as he walked.', '', ARRAY[]::TEXT[]),
('Switch', 'switch_us.mp3', 'noun', 'B1', 'a small device that you press or move up and down in order to turn a light or piece of electrical equipment on and off', '', 'a light switch', '', ARRAY[]::TEXT[]),
('Switch', 'switch_us.mp3', 'verb', 'B1', 'to change or make something change from one thing to another', '', 'switch (over) to something, We''re in the process of switching over to a new system of invoicing.', '', ARRAY[]::TEXT[]),
('Sword', 'sword_us.mp3', 'noun', 'B1', 'a weapon with a long metal blade (= sharp cutting part) and a handle', '', 'to draw/sheathe a sword (= to take it out of/put it into its cover)', '', ARRAY[]::TEXT[]),
('Symbol', 'symbol_us.mp3', 'noun', 'B1', 'a person, an object, an event, etc. that represents a more general quality or situation', '', 'The vase is decorated with religious symbols.', '', ARRAY[]::TEXT[]),
('Symbolic', 'symbolic_us.mp3', 'adjective', 'B1', 'containing symbols, or being used as a symbol', '', 'He shook his fist in a symbolic gesture of defiance.', '', ARRAY[]::TEXT[]),
('Sympathetic', 'sympathetic_us.mp3', 'adjective', 'B1', 'kind to somebody who is hurt or sad; showing that you understand and care about their problems', '', 'a sympathetic listener', '', ARRAY[]::TEXT[]),
('Sympathy', 'sympathy_us.mp3', 'noun', 'B1', 'the feeling of being sorry for somebody; showing that you understand and care about somebody’s problems', '', 'sympathy for somebody, to express/feel sympathy for somebody', '', ARRAY[]::TEXT[]),
('Symptom', 'symptom_us.mp3', 'noun', 'B1', 'a change in your body or mind that shows that you are not healthy', '', 'Symptoms include a headache and sore throat.', '', ARRAY[]::TEXT[]),
('Syndrome', 'syndrome_us.mp3', 'noun', 'B1', 'a set of physical conditions that show you have a particular disease or medical problem', '', 'PMS or premenstrual syndrome', '', ARRAY[]::TEXT[]),
('Synthesis', 'synthesis_us.mp3', 'noun', 'B1', 'the act of combining separate ideas, beliefs, styles, etc.; a mixture or combination of ideas, beliefs, styles, etc.', '', 'synthesis of A with B, the synthesis of art with everyday life', '', ARRAY[]::TEXT[]),
('System', 'system_us.mp3', 'noun', 'B1', 'an organized set of ideas or theories or a particular way of doing something', '', 'reform of the country''s education system', '', ARRAY[]::TEXT[]),
('Systematic', 'systematic_us.mp3', 'adjective', 'B1', 'done according to a system or plan, in a complete, efficient or determined way', '', 'a systematic approach to solving the problem', '', ARRAY[]::TEXT[]),
('T-shirt', 'T-shirt_us.mp3', 'noun', 'B1', 'an informal shirt, usually with short sleeves (= arms) no collar or buttons, or just a few buttons at the top', '', 'He was wearing a faded pair of blue jeans and an old T-shirt.', '', ARRAY[]::TEXT[]),
('Table', 'table_us.mp3', 'noun', 'B1', 'a piece of furniture that consists of a flat top supported by legs', '', 'at a/the table, We sat at a round table in the corner.', '', ARRAY[]::TEXT[]),
('Tablet', 'tablet_us.mp3', 'noun', 'B1', 'a small computer that is easy to carry, with a large touch screen and usually without a physical keyboard', '', 'The company has launched its latest 10-inch tablet.', '', ARRAY[]::TEXT[]),
('Tackle', 'tackle_us.mp3', 'noun', 'B1', 'an act of trying to take the ball from an opponent in football (soccer), hockey, etc.; an act of knocking somebody to the ground, for example in rugby or American football', '', 'He was booked for a late tackle on Torres.', '', ARRAY[]::TEXT[]),
('Tackle', 'tackle_us.mp3', 'verb', 'B1', 'to make a determined effort to deal with a difficult problem or situation', '', 'The government is determined to tackle inflation.', '', ARRAY[]::TEXT[]),
('Tactic', 'tactic_us.mp3', 'noun', 'B1', 'the particular method you use to achieve something', '', 'They tried all kinds of tactics to get us to go.', '', ARRAY[]::TEXT[]),
('Tactical', 'tactical_us.mp3', 'adjective', 'B1', 'connected with the particular method you use to achieve something', '', 'tactical planning', '', ARRAY[]::TEXT[]),
('Tag', 'tag_us.mp3', 'noun', 'B1', 'a small piece of paper, cloth, plastic, etc. attached to something to identify it or give information about it', '', 'He put name tags on all his shirts.', '', ARRAY[]::TEXT[]),
('Tag', 'tag_us.mp3', 'verb', 'B1', 'to fasten a tag onto something/somebody', '', 'Each animal was tagged with a number for identification.', '', ARRAY[]::TEXT[]),
('Tail', 'tail_us.mp3', 'noun', 'B1', 'the part that sticks out at the back of the body of a bird, an animal or a fish, which the animal can move from side to side or up and down', '', 'The dog ran up, wagging its tail.', '', ARRAY[]::TEXT[]),
('Take', 'take_us.mp3', 'verb', 'B1', 'to carry or move something from one place to another', '', 'take something, Remember to take your coat when you leave.', '', ARRAY[]::TEXT[]),
('Tale', 'tale_us.mp3', 'noun', 'B1', 'a story created using the imagination, especially one that is full of action and adventure', '', 'a coming-of-age/morality tale', '', ARRAY[]::TEXT[]),
('Talent', 'talent_us.mp3', 'noun', 'B1', 'a natural ability to do something well', '', 'The festival showcases the talent of young musicians.', '', ARRAY[]::TEXT[]),
('Talented', 'talented_us.mp3', 'adjective', 'B1', 'having a natural ability to do something well', '', 'a talented player/musician/artist', '', ARRAY[]::TEXT[]),
('Talk', 'talk_us.mp3', 'noun', 'B1', 'a speech or lecture on a particular subject', '', 'I went to several interesting talks at the conference.', '', ARRAY[]::TEXT[]),
('Talk', 'talk_us.mp3', 'verb', 'B1', 'to say things; to speak in order to give information or to express feelings, ideas, etc.', '', 'Stop talking and listen!', '', ARRAY[]::TEXT[]),
('Tall', 'tall_us.mp3', 'adjective', 'B1', 'having a greater than average height', '', 'She''s tall and thin.', '', ARRAY[]::TEXT[]),
('Tank', 'tank_us.mp3', 'noun', 'B1', 'a large container for holding liquid or gas', '', 'a fuel/water/storage tank', '', ARRAY[]::TEXT[]),
('Tap', 'tap_us.mp3', 'noun', 'B1', 'a device for controlling the flow of water from a pipe into a bath or sink', '', 'bath taps', '', ARRAY[]::TEXT[]),
('Tap', 'tap_us.mp3', 'verb', 'B1', 'to hit somebody/something quickly and lightly', '', 'tap (away) (at something), Someone tapped at the door.', '', ARRAY[]::TEXT[]),
('Tape', 'tape_us.mp3', 'noun', 'B1', 'a long, narrow piece of material with a sticky substance on one side that is used for sticking things together', '', 'adhesive/sticky tape', '', ARRAY[]::TEXT[]),
('Target', 'target_us.mp3', 'noun', 'B1', 'a result that you try to achieve', '', 'to meet/hit a target', '', ARRAY[]::TEXT[]),
('Target', 'target_us.mp3', 'verb', 'B1', 'to aim an attack or a criticism at somebody/something', '', 'target somebody/something, He accused the group of deliberately targeting civilians.', '', ARRAY[]::TEXT[]),
('Task', 'task_us.mp3', 'noun', 'B1', 'a piece of work that somebody has to do, especially a hard or unpleasant one', '', 'to accomplish/perform/undertake/complete a task', '', ARRAY[]::TEXT[]),
('Taste', 'taste_us.mp3', 'noun', 'B1', 'the particular quality that different foods and drinks have that allows you to recognize them when you put them in your mouth', '', 'a sweet/salty/bitter/sour taste', '', ARRAY[]::TEXT[]),
('Taste', 'taste_us.mp3', 'verb', 'B1', 'to have a particular taste', '', '+ adj., to taste good/delicious/sweet', '', ARRAY[]::TEXT[]),
('Tax', 'tax_us.mp3', 'noun', 'B1', 'money that you have to pay to the government so that it can pay for public services. People pay tax according to their income and businesses pay tax according to their profits. Tax is also often paid on goods and services.', '', 'to pay your taxes', '', ARRAY[]::TEXT[]),
('Tax', 'tax_us.mp3', 'verb', 'B1', 'to put a tax on somebody/something; to make somebody pay tax', '', 'tax somebody/something, His declared aim was to tax the rich.', '', ARRAY[]::TEXT[]),
('Taxi', 'taxi_us.mp3', 'noun', 'B1', 'a car with a driver that you pay to take you somewhere. Taxis usually have meters that show how much money you have to pay.', '', 'We took a taxi to the airport.', '', ARRAY[]::TEXT[]),
('Taxpayer', 'taxpayer_us.mp3', 'noun', 'B1', 'a person who pays tax to the government, especially on the money that they earn', '', 'Hundreds of thousands of pounds of taxpayers'' money (= money paid in taxes) have been spent on the project.', '', ARRAY[]::TEXT[]),
('Tea', 'tea_us.mp3', 'noun', 'B1', 'the dried leaves (called tea leaves) of the tea bush', '', 'a packet of tea', '', ARRAY[]::TEXT[]),
('Teach', 'teach_us.mp3', 'verb', 'B1', 'to give lessons to students in a school, college, university, etc.; to help somebody learn something by giving information about it', '', 'She teaches at our local school.', '', ARRAY[]::TEXT[]),
('Teacher', 'teacher_us.mp3', 'noun', 'B1', 'a person whose job is teaching, especially in a school', '', 'an English/a science teacher', '', ARRAY[]::TEXT[]),
('Teaching', 'teaching_us.mp3', 'noun', 'B1', 'the work of a teacher', '', 'She wants to go into teaching (= make it a career).', '', ARRAY[]::TEXT[]),
('Team', 'team_us.mp3', 'noun', 'B1', 'a group of people who play a particular game or sport against another group of people', '', 'a football/basketball/soccer team', '', ARRAY[]::TEXT[]),
('Tear', 'tear_us.mp3', 'noun', 'B1', 'a hole that has been made in something by tearing', '', 'This sheet has a tear in it.', '', ARRAY[]::TEXT[]),
('Tear', 'tear_us.mp3', 'verb', 'B1', 'to damage something by pulling it apart or into pieces or by cutting it on something sharp; to become damaged in this way', '', 'tear something + adv./prep., I tore my jeans on the fence.', '', ARRAY[]::TEXT[]),
('Technical', 'technical_us.mp3', 'adjective', 'B1', 'connected with the practical use of machines, methods, etc. in science and industry', '', 'We offer free technical support for those buying our software.', '', ARRAY[]::TEXT[]),
('Technique', 'technique_us.mp3', 'noun', 'B1', 'a particular way of doing something, especially one in which you have to learn special skills', '', 'management techniques', '', ARRAY[]::TEXT[]),
('Technological', 'technological_us.mp3', 'adjective', 'B1', 'connected with technology', '', 'technological advances', '', ARRAY[]::TEXT[]),
('Technology', 'technology_us.mp3', 'noun', 'B1', 'scientific knowledge used in practical ways in industry, for example in designing new machines', '', 'science and technology', '', ARRAY[]::TEXT[]),
('Teenage', 'teenage_us.mp3', 'adjective', 'B1', 'between 13 and 19 years old; connected with people of this age', '', 'a teenage girl/boy', '', ARRAY[]::TEXT[]),
('Teenager', 'teenager_us.mp3', 'noun', 'B1', 'a person who is between 13 and 19 years old', '', 'a magazine aimed at teenagers', '', ARRAY[]::TEXT[]),
('Teens', 'teens_us.mp3', 'noun', 'B1', 'the years of a person’s life when they are between 13 and 19 years old', '', 'in your teens, She began writing poetry in her teens.', '', ARRAY[]::TEXT[]),
('Telephone', 'telephone_us.mp3', 'noun', 'B1', 'a system for talking to somebody else over long distances, using wires or radio; a machine used for this', '', 'The telephone rang and Pat answered it.', '', ARRAY[]::TEXT[]),
('Telephone', 'telephone_us.mp3', 'verb', 'B1', 'to speak to somebody by phone', '', 'Please write or telephone for details.', '', ARRAY[]::TEXT[]),
('Television', 'television_us.mp3', 'noun', 'B1', 'a piece of electrical equipment with a screen on which you can watch programmes with moving pictures and sounds', '', 'a widescreen/flat-screen/plasma television', '', ARRAY[]::TEXT[]),
('Tell', 'tell_us.mp3', 'verb', 'B1', 'to give information to somebody by speaking or writing', '', 'tell something to somebody, He told the news to everybody he saw.', '', ARRAY[]::TEXT[]),
('Temperature', 'temperature_us.mp3', 'noun', 'B1', 'the measurement in degrees of how hot or cold a thing or place is', '', 'high/low temperatures', '', ARRAY[]::TEXT[]),
('Temple', 'temple_us.mp3', 'noun', 'B1', 'a building used for religious worship, especially in religions other than Christianity', '', 'the Temple of Diana at Ephesus', '', ARRAY[]::TEXT[]),
('Temporarily', 'temporarily_us.mp3', 'adverb', 'B1', 'in a way that lasts or is intended to last or be used only for a short time; in a way that is not permanent', '', 'We regret this service is temporarily unavailable.', '', ARRAY[]::TEXT[]),
('Temporary', 'temporary_us.mp3', 'adjective', 'B1', 'lasting or intended to last or be used only for a short time; not permanent', '', 'to hire temporary workers', '', ARRAY[]::TEXT[]),
('Tempt', 'tempt_us.mp3', 'verb', 'B1', 'to attract somebody or make somebody want to do or have something, even if they know it is wrong', '', 'tempt somebody, I was tempted by the dessert menu.', '', ARRAY[]::TEXT[]),
('Ten', 'ten_us.mp3', 'number', 'B1', '10', '', 'There are only ten of these rare animals left.', '', ARRAY[]::TEXT[]),
('Tenant', 'tenant_us.mp3', 'noun', 'B1', 'a person who pays rent for the use of a room, building, land, etc. to the person who owns it', '', 'They had evicted their tenants for non-payment of rent.', '', ARRAY[]::TEXT[]),
('Tend', 'tend_us.mp3', 'verb', 'B1', 'to be likely to do something or to happen in a particular way because this is what often or usually happens', '', 'Women tend to live longer than men.', '', ARRAY[]::TEXT[]),
('Tendency', 'tendency_us.mp3', 'noun', 'B1', 'if somebody/something has a particular tendency, they are likely to behave or act in a particular way', '', 'to display artistic tendencies', '', ARRAY[]::TEXT[]),
('Tender', 'tender_us.mp3', 'adjective', 'B1', 'kind, gentle and loving', '', 'tender words', '', ARRAY[]::TEXT[]),
('Tennis', 'tennis_us.mp3', 'noun', 'B1', 'a game in which two or four players use rackets to hit a ball backwards and forwards across a net on a specially marked court', '', 'to play tennis', '', ARRAY[]::TEXT[]),
('Tension', 'tension_us.mp3', 'noun', 'B1', 'a situation in which people do not trust each other, or feel unfriendly towards each other, and that may cause them to attack each other', '', 'There is mounting tension along the border.', '', ARRAY[]::TEXT[]),
('Tent', 'tent_us.mp3', 'noun', 'B1', 'a shelter made of a large sheet of canvas, nylon, etc. that is supported by poles and ropes fixed to the ground, and is used especially for camping', '', 'to put up/take down a tent', '', ARRAY[]::TEXT[]),
('Tenure', 'tenure_us.mp3', 'noun', 'B1', 'the period of time when somebody holds an important job, especially a political one; the act of holding an important job', '', 'his four-year tenure as president', '', ARRAY[]::TEXT[]),
('Term', 'term_us.mp3', 'noun', 'B1', 'a word or phrase used as the name of something, especially one connected with a particular type of language', '', 'a technical/legal/generic term', '', ARRAY[]::TEXT[]),
('Term', 'term_us.mp3', 'verb', 'B1', 'to use a particular name or word to describe somebody/something', '', 'term somebody/something + adj., At his age, he can hardly be termed young.', '', ARRAY[]::TEXT[]),
('Terminal', 'terminal_us.mp3', 'adjective', 'B1', 'that cannot be cured and will lead to death, often slowly', '', 'He has terminal lung cancer.', '', ARRAY[]::TEXT[]),
('Terminal', 'terminal_us.mp3', 'noun', 'B1', 'a building or set of buildings at an airport where passengers arrive and leave', '', 'A second terminal was opened last year.', '', ARRAY[]::TEXT[]),
('Terminate', 'terminate_us.mp3', 'verb', 'B1', 'to end; to make something end', '', 'Your contract of employment terminates in December.', '', ARRAY[]::TEXT[]),
('Terms', 'terms_us.mp3', 'noun', 'B1', 'the conditions that people offer, demand or accept when they make an agreement, an arrangement or a contract', '', 'peace terms', '', ARRAY[]::TEXT[]),
('Terrain', 'terrain_us.mp3', 'noun', 'B1', 'used to refer to an area of land when you are mentioning its natural features, for example, if it is rough, flat, etc.', '', 'difficult/rough/mountainous terrain', '', ARRAY[]::TEXT[]),
('Terrible', 'terrible_us.mp3', 'adjective', 'B1', 'very unpleasant; making you feel very unhappy, upset or frightened', '', 'a terrible experience', '', ARRAY[]::TEXT[]),
('Terribly', 'terribly_us.mp3', 'adverb', 'B1', 'very', '', 'I''m terribly sorry—did I hurt you?', '', ARRAY[]::TEXT[]),
('Terrific', 'terrific_us.mp3', 'adjective', 'B1', 'excellent; wonderful', '', 'I feel absolutely terrific today!', '', ARRAY[]::TEXT[]),
('Terrify', 'terrify_us.mp3', 'verb', 'B1', 'to make somebody feel extremely frightened', '', 'terrify somebody, Flying terrifies her.', '', ARRAY[]::TEXT[]),
('Territory', 'territory_us.mp3', 'noun', 'B1', 'land that is under the control of a particular country or political leader', '', 'enemy/disputed/foreign territory', '', ARRAY[]::TEXT[]),
('Terror', 'terror_us.mp3', 'noun', 'B1', 'a feeling of extreme fear', '', 'a feeling of sheer/pure terror', '', ARRAY[]::TEXT[]),
('Terrorism', 'terrorism_us.mp3', 'noun', 'B1', 'the use of violent action in order to achieve political aims or to force a government to act', '', 'an act of terrorism', '', ARRAY[]::TEXT[]),
('Terrorist', 'terrorist_us.mp3', 'noun', 'B1', 'a person who takes part in terrorism', '', 'The terrorists are threatening to blow up the plane.', '', ARRAY[]::TEXT[]),
('Test', 'test_us.mp3', 'noun', 'B1', 'an examination of somebody’s knowledge or ability, consisting of questions for them to answer or activities for them to perform', '', 'an IQ/a fitness test', '', ARRAY[]::TEXT[]),
('Test', 'test_us.mp3', 'verb', 'B1', 'to find out how much somebody knows, or what they can do by asking them questions or giving them activities to perform', '', 'test somebody, Students will be tested at the end of each module.', '', ARRAY[]::TEXT[]),
('Testify', 'testify_us.mp3', 'verb', 'B1', 'to make a statement that something happened or that something is true, especially as a witness in court', '', 'testify against somebody/something, She refused to testify against her husband.', '', ARRAY[]::TEXT[]),
('Testimony', 'testimony_us.mp3', 'noun', 'B1', 'a thing that shows that something else exists or is true', '', 'This increase in exports bears testimony to the successes of industry.', '', ARRAY[]::TEXT[]),
('Testing', 'testing_us.mp3', 'noun', 'B1', 'the activity of testing somebody/something in order to find something out, see if it works, etc.', '', 'nuclear testing', '', ARRAY[]::TEXT[]),
('Text', 'text_us.mp3', 'noun', 'B1', 'any form of written material', '', 'a computer that can process text', '', ARRAY[]::TEXT[]),
('Textbook', 'textbook_us.mp3', 'noun', 'B1', 'a book that teaches a particular subject and that is used especially in schools and colleges', '', 'a school/medical/history textbook', '', ARRAY[]::TEXT[]),
('Texture', 'texture_us.mp3', 'noun', 'B1', 'the way a surface, substance or piece of cloth feels when you touch it, for example how rough, smooth, hard or soft it is', '', 'the soft texture of velvet', '', ARRAY[]::TEXT[]),
('Than', 'than_us.mp3', 'conjunction', 'B1', 'used to introduce the second part of a comparison', '', 'I''m older than her.', '', ARRAY[]::TEXT[]),
('Than', 'than_us.mp3', 'preposition', 'B1', 'used to introduce the second part of a comparison', '', 'I''m older than her.', '', ARRAY[]::TEXT[]),
('Thank', 'thank_us.mp3', 'verb', 'B1', 'to tell somebody that you are grateful for something', '', 'thank somebody for something, I must write and thank Mary for the present.', '', ARRAY[]::TEXT[]),
('Thankfully', 'thankfully_us.mp3', 'adverb', 'B1', 'used to show that you are pleased that something good has happened or that something bad has been avoided', '', 'There was a fire in the building, but thankfully no one was hurt.', '', ARRAY[]::TEXT[]),
('Thanks', 'thanks_us.mp3', 'exclamation', 'B1', 'used to show that you are grateful to somebody for something they have done', '', '‘How are you?’ ‘Fine, thanks (= thanks for asking).’', '', ARRAY[]::TEXT[]),
('Thanks', 'thanks_us.mp3', 'noun', 'B1', 'words or actions that show that you are grateful to somebody for something', '', 'thanks to somebody for something, How can I ever express my thanks to you for all you''ve done?', '', ARRAY[]::TEXT[]),
('That', 'that_us.mp3', 'adverb', 'B1', 'to such a degree; so', '', 'I can''t walk that far (= as far as that).', '', ARRAY[]::TEXT[]),
('That', 'that_us.mp3', 'conjunction', 'B1', 'used after some verbs, adjectives and nouns to introduce a new part of the sentence', '', 'She said (that) the story was true.', '', ARRAY[]::TEXT[]),
('That', 'that_us.mp3', 'determiner', 'B1', 'used for referring to a person or thing that is not near the speaker or as near to the speaker as another', '', 'Look at that man over there.', '', ARRAY[]::TEXT[]),
('That', 'that_us.mp3', 'pronoun', 'B1', 'used for referring to a person or thing that is not near the speaker, or not as near to the speaker as another', '', 'Who''s that?', '', ARRAY[]::TEXT[]),
('The', 'the_us.mp3', 'definite article', 'B1', 'used to refer to somebody/something that has already been mentioned or is easily understood', '', 'There were three questions. The first two were relatively easy but the third one was hard.', '', ARRAY[]::TEXT[]),
('Theatre', 'theatre_us.mp3', 'noun', 'B1', 'a building or an outdoor area where plays and similar types of entertainment are performed', '', 'Broadway theatres', '', ARRAY[]::TEXT[]),
('Theatrical', 'theatrical_us.mp3', 'adjective', 'B1', 'connected with the theatre', '', 'a theatrical agent', '', ARRAY[]::TEXT[]),
('Theft', 'theft_us.mp3', 'noun', 'B1', 'the crime of stealing something from a person or place', '', 'car theft', '', ARRAY[]::TEXT[]),
('Their', 'their_us.mp3', 'determiner', 'B1', 'of or belonging to people, animals or things that have already been mentioned or are easily identified', '', 'Their parties are always fun.', '', ARRAY[]::TEXT[]),
('Theirs', 'theirs_us.mp3', 'pronoun', 'B1', 'of or belonging to them', '', 'Theirs are the children with very fair hair.', '', ARRAY[]::TEXT[]),
('Them', 'them_us.mp3', 'pronoun', 'B1', 'used when referring to people, animals or things as the object of a verb or preposition, or after the verb be', '', 'Tell them the news.', '', ARRAY[]::TEXT[]),
('Theme', 'theme_us.mp3', 'noun', 'B1', 'the subject or main idea in a talk, piece of writing or work of art', '', 'the central/main/key/major theme', '', ARRAY[]::TEXT[]),
('Themselves', 'themselves_us.mp3', 'pronoun', 'B1', 'used when people or animals performing an action are also affected by it', '', 'They seemed to be enjoying themselves.', '', ARRAY[]::TEXT[]),
('Then', 'then_us.mp3', 'adverb', 'B1', 'used to refer to a particular time in the past or future', '', 'Life was harder then because neither of us had a job.', '', ARRAY[]::TEXT[]),
('Theology', 'theology_us.mp3', 'noun', 'B1', 'the study of religion and beliefs', '', 'a degree in theology', '', ARRAY[]::TEXT[]),
('Theoretical', 'theoretical_us.mp3', 'adjective', 'B1', 'connected with the ideas and principles on which a particular subject is based, rather than with practice and experiment', '', 'a theoretical approach', '', ARRAY[]::TEXT[]),
('Theory', 'theory_us.mp3', 'noun', 'B1', 'a formal set of ideas that is intended to explain why something happens or exists', '', 'theory of something, the theory of evolution/relativity', '', ARRAY[]::TEXT[]),
('Therapist', 'therapist_us.mp3', 'noun', 'B1', 'a specialist who treats a particular type of illness or problem, or who uses a particular type of treatment', '', 'a speech therapist', '', ARRAY[]::TEXT[]),
('Therapy', 'therapy_us.mp3', 'noun', 'B1', 'the treatment of a physical problem or an illness', '', 'He is receiving therapy for cancer.', '', ARRAY[]::TEXT[]),
('There', 'there_us.mp3', 'adverb', 'B1', 'used to show that something exists or happens', '', 'There''s a restaurant around the corner.', '', ARRAY[]::TEXT[]),
('Thereafter', 'thereafter_us.mp3', 'adverb', 'B1', 'after the time or event mentioned', '', 'She married at 17 and gave birth to her first child shortly thereafter.', '', ARRAY[]::TEXT[]),
('Thereby', 'thereby_us.mp3', 'adverb', 'B1', 'used to introduce the result of the action or situation mentioned', '', 'Regular exercise strengthens the heart, thereby reducing the risk of heart attack.', '', ARRAY[]::TEXT[]),
('Therefore', 'therefore_us.mp3', 'adverb', 'B1', 'used to introduce the logical result of something that has just been mentioned', '', 'He''s only 17 and therefore not eligible to vote.', '', ARRAY[]::TEXT[]),
('Thesis', 'thesis_us.mp3', 'noun', 'B1', 'a long piece of writing completed by a student as part of a university degree, based on their own research', '', 'Students must submit a thesis on an agreed subject within four years.', '', ARRAY[]::TEXT[]),
('They', 'they_us.mp3', 'pronoun', 'B1', 'people, animals or things that have already been mentioned or are easily identified', '', '‘Where are John and Liz?’ ‘They went for a walk.’', '', ARRAY[]::TEXT[]),
('Thick', 'thick_us.mp3', 'adjective', 'B1', 'having a larger distance between opposite sides or surfaces than other similar objects or than normal', '', 'a thick slice of bread', '', ARRAY[]::TEXT[]),
('Thief', 'thief_us.mp3', 'noun', 'B1', 'a person who steals something from another person or place', '', 'a car/jewel thief', '', ARRAY[]::TEXT[]),
('Thin', 'thin_us.mp3', 'adjective', 'B1', 'having a smaller distance between opposite sides or surfaces than other similar objects or than normal', '', 'Cut the vegetables into thin strips.', '', ARRAY[]::TEXT[]),
('Thing', 'thing_us.mp3', 'noun', 'B1', 'an object whose name you do not use because you do not need to or want to, or because you do not know it', '', 'Can you pass me that thing over there?', '', ARRAY[]::TEXT[]),
('Think', 'think_us.mp3', 'verb', 'B1', 'to have a particular idea or opinion about something/somebody; to believe something', '', 'think (that)…, Do you really think (that) he''ll win?', '', ARRAY[]::TEXT[]),
('Thinking', 'thinking_us.mp3', 'noun', 'B1', 'the process of thinking about something', '', 'I had to do some quick thinking.', '', ARRAY[]::TEXT[]),
('Third', 'third_us.mp3', 'noun', 'B1', 'each of three equal parts of something', '', 'He divided the money into thirds.', '', ARRAY[]::TEXT[]),
('Third', 'third_us.mp3', 'ordinal number', 'B1', '3rd', '', 'Today is the third (of May).', '', ARRAY[]::TEXT[]),
('Thirsty', 'thirsty_us.mp3', 'adjective', 'B1', 'needing or wanting to drink', '', 'We were hungry and thirsty.', '', ARRAY[]::TEXT[]),
('This', 'this_us.mp3', 'adverb', 'B1', 'to this degree; so', '', 'It''s about this high (= as high as I am showing you with my hands).', '', ARRAY[]::TEXT[]),
('This', 'this_us.mp3', 'determiner', 'B1', 'used to refer to a particular person, thing or event that is close to you, especially compared with another', '', 'How long have you been living in this country?', '', ARRAY[]::TEXT[]),
('Thorough', 'thorough_us.mp3', 'adjective', 'B1', 'done completely; with great attention to detail', '', 'a thorough knowledge of the subject', '', ARRAY[]::TEXT[]),
('Thoroughly', 'thoroughly_us.mp3', 'adverb', 'B1', 'very much; completely', '', 'We thoroughly enjoyed ourselves.', '', ARRAY[]::TEXT[]),
('Though', 'though_us.mp3', 'adverb', 'B1', 'used especially at the end of a sentence or clause to add a fact or an opinion that makes the previous statement less strong or less important', '', 'Our team lost. It was a good game though.', '', ARRAY[]::TEXT[]),
('Though', 'though_us.mp3', 'conjunction', 'B1', 'despite the fact that', '', 'Anne was fond of Tim, though he often annoyed her.', '', ARRAY[]::TEXT[]),
('Thought', 'thought_us.mp3', 'noun', 'B1', 'something that you think of or remember', '', 'thought of doing something, I couldn''t bear the thought of waiting any longer.', '', ARRAY[]::TEXT[]),
('Thought-provoking', 'thought-provoking_us.mp3', 'adjective', 'B1', 'making people think seriously about a particular subject or issue', '', 'a brilliant and thought-provoking play', '', ARRAY[]::TEXT[]),
('Thoughtful', 'thoughtful_us.mp3', 'adjective', 'B1', 'quiet, because you are thinking', '', 'He looked thoughtful.', '', ARRAY[]::TEXT[]),
('Thousand', 'thousand_us.mp3', 'number', 'B1', '1 000', '', 'There were thousands of people there.', '', ARRAY[]::TEXT[]),
('Thread', 'thread_us.mp3', 'noun', 'B1', 'a thin string of cotton, wool, silk, etc. used for sewing or making cloth', '', 'a needle and thread', '', ARRAY[]::TEXT[]),
('Threat', 'threat_us.mp3', 'noun', 'B1', 'a statement in which you tell somebody that you will punish or harm them, especially if they do not do what you want', '', 'threat against somebody/something, to make threats against somebody', '', ARRAY[]::TEXT[]),
('Threaten', 'threaten_us.mp3', 'verb', 'B1', 'to say that you will cause trouble, hurt somebody, etc. if you do not get what you want', '', 'threaten somebody/something, They broke my windows and threatened me.', '', ARRAY[]::TEXT[]),
('Three', 'three_us.mp3', 'number', 'B1', '3', '', 'There are only three cookies left.', '', ARRAY[]::TEXT[]),
('Threshold', 'threshold_us.mp3', 'noun', 'B1', 'the floor or ground at the bottom of a doorway, considered as the entrance to a building or room', '', 'He stepped across the threshold.', '', ARRAY[]::TEXT[]),
('Thrilled', 'thrilled_us.mp3', 'adjective', 'B1', 'very excited and pleased', '', '‘Are you pleased?’ ‘I''m thrilled.’', '', ARRAY[]::TEXT[]),
('Thrive', 'thrive_us.mp3', 'verb', 'B1', 'to become, and continue to be, successful, strong, healthy, etc.', '', 'New businesses thrive in this area.', '', ARRAY[]::TEXT[]),
('Throat', 'throat_us.mp3', 'noun', 'B1', 'a passage in the neck through which food and air pass on their way into the body; the front part of the neck', '', 'a sore throat', '', ARRAY[]::TEXT[]),
('Through', 'through_us.mp3', 'adverb', 'B1', 'from one end or side of something to the other', '', 'Put the coffee in the filter and let the water run through.', '', ARRAY[]::TEXT[]),
('Through', 'through_us.mp3', 'preposition', 'B1', 'from one end or side of something/somebody to the other', '', 'The burglar got in through the window.', '', ARRAY[]::TEXT[]),
('Throughout', 'throughout_us.mp3', 'adverb', 'B1', 'in or into every part of something', '', 'They export their products to markets throughout the world.', '', ARRAY[]::TEXT[]),
('Throughout', 'throughout_us.mp3', 'preposition', 'B1', 'in or into every part of something', '', 'They export their products to markets throughout the world.', '', ARRAY[]::TEXT[]),
('Throw', 'throw_us.mp3', 'verb', 'B1', 'to send something from your hand through the air by moving your hand or arm quickly', '', 'Practise throwing and catching.', '', ARRAY[]::TEXT[]),
('Thumb', 'thumb_us.mp3', 'noun', 'B1', 'the short, thick finger at the side of the hand, slightly apart from the other four', '', 'She still sucks her thumb when she''s worried.', '', ARRAY[]::TEXT[]),
('Thursday', 'Thursday_us.mp3', 'noun', 'B1', 'the day of the week after Wednesday and before Friday', '', 'It''s Thursday today, isn''t it?', '', ARRAY[]::TEXT[]),
('Thus', 'thus_us.mp3', 'adverb', 'B1', 'in this way; like this', '', 'Many scholars have argued thus.', '', ARRAY[]::TEXT[]),
('Ticket', 'ticket_us.mp3', 'noun', 'B1', 'a printed piece of paper, or a message or image received on your phone or computer, that gives you the right to travel on a particular bus, train, etc. or to go into a theatre, etc.', '', 'a plane/bus/train ticket', '', ARRAY[]::TEXT[]),
('Tide', 'tide_us.mp3', 'noun', 'B1', 'a regular rise and fall in the level of the sea, caused by the pull of the moon and sun; the flow of water that happens as the sea rises and falls', '', 'the ebb and flow of the tide', '', ARRAY[]::TEXT[]),
('Tidy', 'tidy_us.mp3', 'adjective', 'B1', 'arranged neatly and with everything in order', '', 'a tidy desk', '', ARRAY[]::TEXT[]),
('Tidy', 'tidy_us.mp3', 'verb', 'B1', 'to make something look neat by putting things in the place where they belong', '', 'I spent all morning cleaning and tidying.', '', ARRAY[]::TEXT[]),
('Tie', 'tie_us.mp3', 'noun', 'B1', 'a long, narrow piece of cloth worn around the neck, especially by men, with a knot in front', '', 'He was dressed impeccably in a suit and tie.', '', ARRAY[]::TEXT[]),
('Tie', 'tie_us.mp3', 'verb', 'B1', 'to attach or hold two or more things together using string, rope, etc.; to fasten somebody/something with string, rope, etc.', '', 'tie something + adv./prep., She tied the newspapers in a bundle.', '', ARRAY[]::TEXT[]),
('Tight', 'tight_us.mp3', 'adjective', 'B1', 'held or fixed in position securely; difficult to move, open or separate', '', 'He kept a tight grip on her arm.', '', ARRAY[]::TEXT[]),
('Tighten', 'tighten_us.mp3', 'verb', 'B1', 'to hold or fix something more securely in position; to make something or become more difficult to move, open or separate', '', 'tighten something, to tighten a lid/screw/rope/knot', '', ARRAY[]::TEXT[]),
('Till', 'till_us.mp3', 'conjunction', 'B1', 'until', '', 'We''re open till 6 o''clock.', '', ARRAY[]::TEXT[]),
('Till', 'till_us.mp3', 'preposition', 'B1', 'until', '', 'We''re open till 6 o''clock.', '', ARRAY[]::TEXT[]),
('Timber', 'timber_us.mp3', 'noun', 'B1', 'trees that are grown to be used in building or for making things', '', 'the timber industry', '', ARRAY[]::TEXT[]),
('Time', 'time_us.mp3', 'noun', 'B1', 'what is measured in minutes, hours, days, etc.', '', 'The world exists in time and space.', '', ARRAY[]::TEXT[]),
('Time', 'time_us.mp3', 'verb', 'B1', 'to measure how long it takes for something to happen or for somebody to do something', '', 'time something, ‘How long does it take to get to Leeds from here?’ ‘I don’t know, I’ve never timed it.’', '', ARRAY[]::TEXT[]),
('Timely', 'timely_us.mp3', 'adjective', 'B1', 'happening at exactly the right time', '', 'A nasty incident was prevented by the timely arrival of the police.', '', ARRAY[]::TEXT[]),
('Timing', 'timing_us.mp3', 'noun', 'B1', 'the act of choosing when something happens; a particular point or period of time when something happens or is planned', '', 'The timing of the decision was a complete surprise.', '', ARRAY[]::TEXT[]),
('Tin', 'tin_us.mp3', 'noun', 'B1', 'a metal container in which food is sold; the contents of one of these containers', '', 'Open the tin and drain the tuna.', '', ARRAY[]::TEXT[]),
('Tiny', 'tiny_us.mp3', 'adjective', 'B1', 'very small in size or amount', '', 'a tiny baby', '', ARRAY[]::TEXT[]),
('Tip', 'tip_us.mp3', 'noun', 'B1', 'a small piece of advice about something practical', '', 'tip on/for doing something, handy tips for buying a computer', '', ARRAY[]::TEXT[]),
('Tip', 'tip_us.mp3', 'verb', 'B1', 'to give somebody an extra amount of money to thank them for something they have done for you as part of their job', '', 'Americans were always welcome because they tended to tip heavily.', '', ARRAY[]::TEXT[]),
('Tired', 'tired_us.mp3', 'adjective', 'B1', 'feeling that you would like to sleep or rest; needing rest', '', 'to be/look/feel tired', '', ARRAY[]::TEXT[]),
('Tissue', 'tissue_us.mp3', 'noun', 'B1', 'a piece of soft paper, used especially as a handkerchief', '', 'a box of tissues', '', ARRAY[]::TEXT[]),
('Title', 'title_us.mp3', 'noun', 'B1', 'the name of a book, poem, painting, piece of music, etc.', '', 'What''s title of her new book?', '', ARRAY[]::TEXT[]),
('Title', 'title_us.mp3', 'verb', 'B1', 'to give a book, piece of music, etc. a particular name', '', 'be titled…, Their first album was titled ‘Made in Valmez’.', '', ARRAY[]::TEXT[]),
('To', 'to_us.mp3', 'infinitive marker', 'B1', 'used to show purpose or intention', '', 'I set out to buy food.', '', ARRAY[]::TEXT[]),
('To', 'to_us.mp3', 'preposition', 'B1', 'in the direction of something; towards something', '', 'I walked to the office.', '', ARRAY[]::TEXT[]),
('Tobacco', 'tobacco_us.mp3', 'noun', 'B1', 'the dried leaves of the tobacco plant that are used for making cigarettes, smoking in a pipe, etc.', '', 'tobacco smoke', '', ARRAY[]::TEXT[]),
('Today', 'today_us.mp3', 'adverb', 'B1', 'on this day', '', 'I''ve got a piano lesson later today.', '', ARRAY[]::TEXT[]),
('Today', 'today_us.mp3', 'noun', 'B1', 'this day', '', 'Today is her tenth birthday.', '', ARRAY[]::TEXT[]),
('Toe', 'toe_us.mp3', 'noun', 'B1', 'one of the five small parts that stick out from the foot; any similar part on the foot of an animal or bird', '', 'the big/little toe (= the largest/smallest toe)', '', ARRAY[]::TEXT[]),
('Together', 'together_us.mp3', 'adverb', 'B1', 'with or near to somebody/something else; with each other', '', 'We grew up together.', '', ARRAY[]::TEXT[]),
('Toilet', 'toilet_us.mp3', 'noun', 'B1', 'a large bowl attached to a pipe that you sit on or stand over when you get rid of waste matter from your body', '', 'Have you flushed the toilet?', '', ARRAY[]::TEXT[]),
('Tolerance', 'tolerance_us.mp3', 'noun', 'B1', 'the quality of being willing to accept or tolerate somebody/something, especially opinions or behaviour that you may not agree with, or people who are not like you', '', 'She had no tolerance for jokes of any kind.', '', ARRAY[]::TEXT[]),
('Tolerate', 'tolerate_us.mp3', 'verb', 'B1', 'to allow somebody to do something that you do not agree with or like', '', 'tolerate something, Their relationship was tolerated but not encouraged.', '', ARRAY[]::TEXT[]),
('Toll', 'toll_us.mp3', 'noun', 'B1', 'money that you pay to use a particular road or bridge', '', 'motorway tolls', '', ARRAY[]::TEXT[]),
('Tomato', 'tomato_us.mp3', 'noun', 'B1', 'a soft fruit with a lot of juice and shiny red skin that is eaten as a vegetable either raw or cooked', '', 'a bacon, lettuce, and tomato sandwich', '', ARRAY[]::TEXT[]),
('Tomorrow', 'tomorrow_us.mp3', 'adverb', 'B1', 'on or during the day after today', '', 'I''m off now. See you tomorrow.', '', ARRAY[]::TEXT[]),
('Tomorrow', 'tomorrow_us.mp3', 'noun', 'B1', 'the day after today', '', 'Today is Tuesday, so tomorrow is Wednesday.', '', ARRAY[]::TEXT[]),
('Ton', 'ton_us.mp3', 'noun', 'B1', 'a unit for measuring weight, in the UK 2 240 pounds (long ton) and in the US 2 000 pounds (short ton)', '', '(informal), What have you got in this bag? It weighs a ton (= is very heavy).', '', ARRAY[]::TEXT[]),
('Tone', 'tone_us.mp3', 'noun', 'B1', 'the quality of somebody’s voice, especially expressing a particular emotion', '', 'speaking in hushed/low/clipped/measured, etc. tones', '', ARRAY[]::TEXT[]),
('Tongue', 'tongue_us.mp3', 'noun', 'B1', 'the soft part in the mouth that moves around, used for tasting, swallowing, speaking, etc.', '', 'He clicked his tongue to attract their attention.', '', ARRAY[]::TEXT[]),
('Tonight', 'tonight_us.mp3', 'adverb', 'B1', 'on or during the evening or night of today', '', 'Will you have dinner with me tonight?', '', ARRAY[]::TEXT[]),
('Tonight', 'tonight_us.mp3', 'noun', 'B1', 'the evening or night of today', '', 'Here are tonight''s football results.', '', ARRAY[]::TEXT[]),
('Tonne', 'tonne_us.mp3', 'noun', 'B1', 'a unit for measuring weight, equal to 1 000 kilograms', '', 'a record grain harvest of 236m tonnes', '', ARRAY[]::TEXT[]),
('Too', 'too_us.mp3', 'adverb', 'B1', 'used before adjectives and adverbs to say that something is more than is good, necessary, possible, etc.', '', 'He''s far too young to go on his own.', '', ARRAY[]::TEXT[]),
('Tool', 'tool_us.mp3', 'noun', 'B1', 'an instrument such as a hammer, screwdriver, saw, etc. that you hold in your hand and use for making things, repairing things, etc.', '', 'garden tools', '', ARRAY[]::TEXT[]),
('Tooth', 'tooth_us.mp3', 'noun', 'B1', 'any of the hard white structures in the mouth used for biting food', '', 'I''ve just had a tooth out at the dentist''s.', '', ARRAY[]::TEXT[]),
('Top', 'top_us.mp3', 'adjective', 'B1', 'highest in position', '', 'He lives on the top floor.', '', ARRAY[]::TEXT[]),
('Top', 'top_us.mp3', 'noun', 'B1', 'the highest part or point of something', '', 'at the top of something, She was standing at the top of the stairs.', '', ARRAY[]::TEXT[]),
('Top', 'top_us.mp3', 'verb', 'B1', 'to be higher than a particular amount', '', 'Worldwide sales look set to top $1 billion.', '', ARRAY[]::TEXT[]),
('Topic', 'topic_us.mp3', 'noun', 'B1', 'a subject that you talk, write or learn about', '', 'The main topic of conversation was Tom''s new girlfriend.', '', ARRAY[]::TEXT[]),
('Torture', 'torture_us.mp3', 'noun', 'B1', 'the act of causing somebody severe pain in order to punish them or make them say or do something', '', 'Many of the refugees have suffered torture.', '', ARRAY[]::TEXT[]),
('Torture', 'torture_us.mp3', 'verb', 'B1', 'to hurt somebody physically or mentally in order to punish them or make them tell you something', '', 'torture somebody, Many of the rebels were captured and tortured by secret police.', '', ARRAY[]::TEXT[]),
('Toss', 'toss_us.mp3', 'verb', 'B1', 'to throw something lightly or carelessly', '', 'toss something + adv./prep., I tossed the book aside and got up.', '', ARRAY[]::TEXT[]),
('Total', 'total_us.mp3', 'adjective', 'B1', 'being the amount or number after everyone or everything is counted or added together', '', 'Their total cost was $18 000.', '', ARRAY[]::TEXT[]),
('Total', 'total_us.mp3', 'noun', 'B1', 'the amount you get when you add several numbers or amounts together; the final number of people or things when they have all been counted', '', 'a total of something, You got 47 points on the written examination and 18 on the oral, making a total of 65.', '', ARRAY[]::TEXT[]),
('Total', 'total_us.mp3', 'verb', 'B1', 'to reach a particular total', '', 'Imports totalled $1.5 billion last year.', '', ARRAY[]::TEXT[]),
('Totally', 'totally_us.mp3', 'adverb', 'B1', 'completely', '', 'They come from totally different cultures.', '', ARRAY[]::TEXT[]),
('Touch', 'touch_us.mp3', 'noun', 'B1', 'the sense that enables you to be aware of things and what they are like when you put your hands and fingers on them', '', 'the sense of touch', '', ARRAY[]::TEXT[]),
('Touch', 'touch_us.mp3', 'verb', 'B1', 'to put your hand or another part of your body onto somebody/something', '', 'Don''t touch that plate—it''s hot!', '', ARRAY[]::TEXT[]),
('Tough', 'tough_us.mp3', 'adjective', 'B1', 'having or causing problems or difficulties', '', 'a tough childhood', '', ARRAY[]::TEXT[]),
('Tour', 'tour_us.mp3', 'noun', 'B1', 'a journey made for pleasure during which several different towns, countries, etc. are visited', '', 'a walking/sightseeing/bus tour', '', ARRAY[]::TEXT[]),
('Tour', 'tour_us.mp3', 'verb', 'B1', 'to travel around a place, for example on holiday, or to perform, to advertise something, etc.', '', 'tour something, He toured America with his one-man show.', '', ARRAY[]::TEXT[]),
('Tourism', 'tourism_us.mp3', 'noun', 'B1', 'the business activity connected with providing accommodation, services and entertainment for people who are visiting a place for pleasure', '', 'The area is heavily dependent on tourism.', '', ARRAY[]::TEXT[]),
('Tourist', 'tourist_us.mp3', 'noun', 'B1', 'a person who is travelling or visiting a place for pleasure', '', 'busloads of foreign tourists', '', ARRAY[]::TEXT[]),
('Tournament', 'tournament_us.mp3', 'noun', 'B1', 'a sports competition involving a number of teams or players who take part in different games and must leave the competition if they lose. The competition continues until there is only the winner left.', '', 'a golf/tennis/soccer/chess tournament', '', ARRAY[]::TEXT[]),
('Towards', 'towards_us.mp3', 'preposition', 'B1', 'in the direction of somebody/something', '', 'They were heading towards the German border.', '', ARRAY[]::TEXT[]),
('Towel', 'towel_us.mp3', 'noun', 'B1', 'a piece of cloth or paper used for drying things, especially your body', '', 'Help yourself to a clean towel.', '', ARRAY[]::TEXT[]),
('Tower', 'tower_us.mp3', 'noun', 'B1', 'a tall narrow building or part of a building, especially of a church or castle', '', 'a bell tower', '', ARRAY[]::TEXT[]),
('Town', 'town_us.mp3', 'noun', 'B1', 'a place with many houses, shops, etc. where people live and work. It is larger than a village but smaller than a city.', '', 'The nearest town is ten miles away.', '', ARRAY[]::TEXT[]),
('Toxic', 'toxic_us.mp3', 'adjective', 'B1', 'containing poison; poisonous', '', 'toxic chemicals/fumes/gases/substances', '', ARRAY[]::TEXT[]),
('Toy', 'toy_us.mp3', 'adjective', 'B1', 'made as a copy of a particular thing and used for playing with', '', 'a toy car', '', ARRAY[]::TEXT[]),
('Toy', 'toy_us.mp3', 'noun', 'B1', 'an object for children to play with', '', 'cuddly/stuffed toys', '', ARRAY[]::TEXT[]),
('Trace', 'trace_us.mp3', 'noun', 'B1', 'a mark, an object or a sign that shows that somebody/something existed or was present', '', 'It''s exciting to discover traces of earlier civilizations.', '', ARRAY[]::TEXT[]),
('Trace', 'trace_us.mp3', 'verb', 'B1', 'to find or discover somebody/something by looking carefully for them/it', '', 'We finally traced him to an address in Chicago.', '', ARRAY[]::TEXT[]),
('Track', 'track_us.mp3', 'noun', 'B1', 'rails (= metal bars) that a train moves along', '', 'railway/railroad tracks', '', ARRAY[]::TEXT[]),
('Track', 'track_us.mp3', 'verb', 'B1', 'to find somebody/something by following the marks, signs, information, etc., that they have left behind them', '', 'track somebody/something, hunters tracking and shooting bears', '', ARRAY[]::TEXT[]),
('Trade', 'trade_us.mp3', 'noun', 'B1', 'the activity of buying and selling or of exchanging goods or services between people or countries', '', 'international/foreign/global/world trade', '', ARRAY[]::TEXT[]),
('Trade', 'trade_us.mp3', 'verb', 'B1', 'to buy and sell things', '', 'trade in something, The firm openly traded in arms.', '', ARRAY[]::TEXT[]),
('Trademark', 'trademark_us.mp3', 'noun', 'B1', 'a name, symbol or design that a company uses for its products and that cannot be used by anyone else', '', '‘Big Mac’ is McDonald''s best-known trademark.', '', ARRAY[]::TEXT[]),
('Trading', 'trading_us.mp3', 'noun', 'B1', 'the activity of buying and selling things', '', 'new laws on Sunday trading (= shops being open on Sundays)', '', ARRAY[]::TEXT[]),
('Tradition', 'tradition_us.mp3', 'noun', 'B1', 'a belief, custom or way of doing something that has existed for a long time among a particular group of people; a set of these beliefs or customs', '', 'religious/cultural/ancient traditions', '', ARRAY[]::TEXT[]),
('Traditional', 'traditional_us.mp3', 'adjective', 'B1', 'being part of the beliefs, customs or way of life of a particular group of people, that have not changed for a long time', '', 'traditional dress/music/art/culture/dance', '', ARRAY[]::TEXT[]),
('Traffic', 'traffic_us.mp3', 'noun', 'B1', 'the vehicles that are on a road at a particular time', '', 'There''s always a lot of traffic at this time of day.', '', ARRAY[]::TEXT[]),
('Tragedy', 'tragedy_us.mp3', 'noun', 'B1', 'a very sad event or situation, especially one that involves death', '', 'It''s a tragedy that she died so young.', '', ARRAY[]::TEXT[]),
('Tragic', 'tragic_us.mp3', 'adjective', 'B1', 'making you feel very sad, usually because somebody has died or suffered a lot', '', 'He was killed in a tragic accident at the age of 24.', '', ARRAY[]::TEXT[]),
('Trail', 'trail_us.mp3', 'noun', 'B1', 'a long line or series of marks that is left by somebody/something', '', 'a trail of blood', '', ARRAY[]::TEXT[]),
('Trail', 'trail_us.mp3', 'verb', 'B1', 'to pull something behind somebody/something, usually along the ground; to be pulled along in this way', '', 'trail something, A jeep trailing a cloud of dust was speeding in my direction.', '', ARRAY[]::TEXT[]),
('Trailer', 'trailer_us.mp3', 'noun', 'B1', 'a truck, or a container with wheels, that is pulled by another vehicle', '', 'a car towing a trailer with a boat on it', '', ARRAY[]::TEXT[]),
('Train', 'train_us.mp3', 'noun', 'B1', 'a number of connected coaches or trucks, pulled by an engine or powered by a motor in each one, taking people and goods from one place to another', '', 'to get on/off a train', '', ARRAY[]::TEXT[]),
('Train', 'train_us.mp3', 'verb', 'B1', 'to teach a person or an animal the skills for a particular job or activity; to be taught in this way', '', 'train somebody/something, highly trained professionals', '', ARRAY[]::TEXT[]),
('Trainer', 'trainer_us.mp3', 'noun', 'B1', 'a shoe that you wear for sports or as informal clothing', '', 'a pair of trainers', '', ARRAY[]::TEXT[]),
('Training', 'training_us.mp3', 'noun', 'B1', 'the process of learning the skills that you need to do a job', '', 'staff training', '', ARRAY[]::TEXT[]),
('Trait', 'trait_us.mp3', 'noun', 'B1', 'a particular quality in your personality', '', 'personality traits', '', ARRAY[]::TEXT[]),
('Transaction', 'transaction_us.mp3', 'noun', 'B1', 'a piece of business that is done between people, especially an act of buying or selling', '', 'financial transactions between companies', '', ARRAY[]::TEXT[]),
('Transcript', 'transcript_us.mp3', 'noun', 'B1', 'a written or printed copy of words that have been spoken', '', 'a transcript of the interview', '', ARRAY[]::TEXT[]),
('Transfer', 'transfer_us.mp3', 'noun', 'B1', 'the act of moving somebody/something from one place, group or job to another; an occasion when this happens', '', 'electronic data transfer', '', ARRAY[]::TEXT[]),
('Transfer', 'transfer_us.mp3', 'verb', 'B1', 'to move from one place to another; to move something/somebody from one place to another', '', 'transfer (to something), The film studio is transferring to Hollywood.', '', ARRAY[]::TEXT[]),
('Transform', 'transform_us.mp3', 'verb', 'B1', 'to change the form of something; to change in form', '', 'transform something/somebody (into something), The photochemical reactions transform the light into electrical impulses.', '', ARRAY[]::TEXT[]),
('Transformation', 'transformation_us.mp3', 'noun', 'B1', 'a complete change in somebody/something', '', 'The way in which we work has undergone a complete transformation in the past decade.', '', ARRAY[]::TEXT[]),
('Transit', 'transit_us.mp3', 'noun', 'B1', 'the process of being moved or carried from one place to another', '', 'The cost includes transit.', '', ARRAY[]::TEXT[]),
('Transition', 'transition_us.mp3', 'noun', 'B1', 'the process or a period of changing from one state or condition to another', '', 'transition from something to something, the transition from school to full-time work', '', ARRAY[]::TEXT[]),
('Translate', 'translate_us.mp3', 'verb', 'B1', 'to express the meaning of speech or writing in a different language', '', 'translate something into something, He translated the letter into English.', '', ARRAY[]::TEXT[]),
('Translation', 'translation_us.mp3', 'noun', 'B1', 'the process of changing something that is written or spoken into another language', '', 'an error in translation', '', ARRAY[]::TEXT[]),
('Transmission', 'transmission_us.mp3', 'noun', 'B1', 'the act or process of passing something from one person, place or thing to another', '', 'the transmission of the disease', '', ARRAY[]::TEXT[]),
('Transmit', 'transmit_us.mp3', 'verb', 'B1', 'to send an electronic signal, radio or television broadcast, etc.', '', 'signals transmitted from a satellite', '', ARRAY[]::TEXT[]),
('Transparency', 'transparency_us.mp3', 'noun', 'B1', 'the quality of something, such as a situation or an argument, that makes it easy to understand', '', 'a need for greater transparency in legal documents', '', ARRAY[]::TEXT[]),
('Transparent', 'transparent_us.mp3', 'adjective', 'B1', 'allowing you to see through it', '', 'The insect''s wings are almost transparent.', '', ARRAY[]::TEXT[]),
('Transport', 'transport_us.mp3', 'noun', 'B1', 'a system for carrying people or goods from one place to another using vehicles, roads, etc.', '', 'air/freight/road transport', '', ARRAY[]::TEXT[]),
('Transport', 'transport_us.mp3', 'verb', 'B1', 'to take something/somebody from one place to another in a vehicle', '', 'to transport goods/passengers', '', ARRAY[]::TEXT[]),
('Transportation', 'transportation_us.mp3', 'noun', 'B1', 'a system for carrying people or goods from one place to another using vehicles, roads, etc.', '', 'public transportation (= the system of buses, trains, etc. provided for people to travel from one place to another)', '', ARRAY[]::TEXT[]),
('Trap', 'trap_us.mp3', 'noun', 'B1', 'a piece of equipment for catching animals', '', 'a fox with its leg in a trap', '', ARRAY[]::TEXT[]),
('Trap', 'trap_us.mp3', 'verb', 'B1', 'to put somebody in a dangerous place that they cannot get out of', '', 'be trapped, Help! I''m trapped!', '', ARRAY[]::TEXT[]),
('Trauma', 'trauma_us.mp3', 'noun', 'B1', 'a mental condition caused by severe shock, stress or fear, especially when the harmful effects last for a long time', '', 'the effects of trauma and stress on the body', '', ARRAY[]::TEXT[]),
('Travel', 'travel_us.mp3', 'noun', 'B1', 'the act or activity of travelling', '', 'air/rail/space travel', '', ARRAY[]::TEXT[]),
('Travel', 'travel_us.mp3', 'verb', 'B1', 'to go from one place to another, especially over a long distance', '', 'I go to bed early if I''m travelling the next day.', '', ARRAY[]::TEXT[]),
('Traveller', 'traveller_us.mp3', 'noun', 'B1', 'a person who is travelling or who often travels', '', 'She is a frequent traveller to Belgium.', '', ARRAY[]::TEXT[]),
('Treasure', 'treasure_us.mp3', 'noun', 'B1', 'a collection of valuable things such as gold, silver and jewellery', '', 'buried treasure', '', ARRAY[]::TEXT[]),
('Treat', 'treat_us.mp3', 'verb', 'B1', 'to behave in a particular way towards somebody/something', '', 'treat somebody/something with something, to treat people with respect', '', ARRAY[]::TEXT[]),
('Treatment', 'treatment_us.mp3', 'noun', 'B1', 'something that is done to cure an illness or injury, or to make somebody look and feel good', '', 'The drug is used in the treatment of depression.', '', ARRAY[]::TEXT[]),
('Treaty', 'treaty_us.mp3', 'noun', 'B1', 'a formal agreement between two or more countries', '', 'the Treaty of Rome', '', ARRAY[]::TEXT[]),
('Tree', 'tree_us.mp3', 'noun', 'B1', 'a tall plant that can live a long time. Trees have a thick central wooden trunk from which branches grow, usually with leaves on them', '', 'an oak/olive/apple tree', '', ARRAY[]::TEXT[]),
('Tremendous', 'tremendous_us.mp3', 'adjective', 'B1', 'very great', '', 'a tremendous explosion', '', ARRAY[]::TEXT[]),
('Trend', 'trend_us.mp3', 'noun', 'B1', 'a general direction in which a situation is changing or developing', '', 'social/economic/political/demographic trends', '', ARRAY[]::TEXT[]),
('Trial', 'trial_us.mp3', 'noun', 'B1', 'a formal examination of evidence in court by a judge and often a jury, to decide if somebody accused of a crime is guilty or not', '', 'a murder/criminal trial', '', ARRAY[]::TEXT[]),
('Tribal', 'tribal_us.mp3', 'adjective', 'B1', 'connected with a tribe or tribes', '', 'tribal art', '', ARRAY[]::TEXT[]),
('Tribe', 'tribe_us.mp3', 'noun', 'B1', 'a social group in a traditional society consisting of people with the same language, culture, religion, etc., living in a particular area and often having one leader known as a chief', '', 'They were a nomadic horse-riding tribe.', '', ARRAY[]::TEXT[]),
('Tribunal', 'tribunal_us.mp3', 'noun', 'B1', 'a type of court with the authority to deal with a particular problem or disagreement', '', 'an international war crimes tribunal', '', ARRAY[]::TEXT[]),
('Tribute', 'tribute_us.mp3', 'noun', 'B1', 'an act, a statement or a gift that is intended to show your love or respect, especially for a dead person', '', 'At her funeral her oldest friend paid tribute to her life and work.', '', ARRAY[]::TEXT[]),
('Trick', 'trick_us.mp3', 'noun', 'B1', 'something that you do to make somebody believe something that is not true, or to annoy somebody as a joke', '', 'They had to think of a trick to get past the guards.', '', ARRAY[]::TEXT[]),
('Trick', 'trick_us.mp3', 'verb', 'B1', 'to make somebody believe something which is not true, especially in order to cheat them', '', 'trick somebody, I''d been tricked and I felt stupid.', '', ARRAY[]::TEXT[]),
('Trigger', 'trigger_us.mp3', 'noun', 'B1', 'the part of a gun that you press in order to fire it', '', 'to pull/squeeze the trigger', '', ARRAY[]::TEXT[]),
('Trigger', 'trigger_us.mp3', 'verb', 'B1', 'to make something happen suddenly', '', 'Nuts can trigger off a violent allergic reaction.', '', ARRAY[]::TEXT[]),
('Trio', 'trio_us.mp3', 'noun', 'B1', 'a group of three people or things', '', 'A trio of English runners featured in the women’s 1 500 metres.', '', ARRAY[]::TEXT[]),
('Trip', 'trip_us.mp3', 'noun', 'B1', 'a journey to a place and back again, especially a short one for pleasure or a particular purpose', '', 'Did you have a good trip?', '', ARRAY[]::TEXT[]),
('Trip', 'trip_us.mp3', 'verb', 'B1', 'to catch your foot on something and fall or almost fall', '', 'She tripped and fell.', '', ARRAY[]::TEXT[]),
('Triumph', 'triumph_us.mp3', 'noun', 'B1', 'a great success, achievement or victory', '', 'one of the greatest triumphs of modern science', '', ARRAY[]::TEXT[]),
('Troop', 'troop_us.mp3', 'noun', 'B1', 'soldiers, especially in large groups', '', 'They announced the withdrawal of 12 000 troops from the area.', '', ARRAY[]::TEXT[]),
('Trophy', 'trophy_us.mp3', 'noun', 'B1', 'an object such as a silver cup that is given as a prize for winning a competition', '', 'a trophy cabinet', '', ARRAY[]::TEXT[]),
('Tropical', 'tropical_us.mp3', 'adjective', 'B1', 'coming from, found in or typical of the tropics', '', 'tropical fish/birds/fruit', '', ARRAY[]::TEXT[]),
('Trouble', 'trouble_us.mp3', 'noun', 'B1', 'a problem, worry, difficulty, etc. or a situation causing this', '', 'We have trouble getting staff.', '', ARRAY[]::TEXT[]),
('Trouble', 'trouble_us.mp3', 'verb', 'B1', 'to make somebody worried or upset', '', 'What is it that''s troubling you?', '', ARRAY[]::TEXT[]),
('Troubled', 'troubled_us.mp3', 'adjective', 'B1', 'worried and anxious', '', 'She looked into his troubled face.', '', ARRAY[]::TEXT[]),
('Trousers', 'trousers_us.mp3', 'noun', 'B1', 'a piece of clothing that covers the lower body and is divided into two parts to cover each leg separately', '', 'a pair of grey trousers', '', ARRAY[]::TEXT[]),
('Truck', 'truck_us.mp3', 'noun', 'B1', 'a large vehicle for carrying heavy loads by road', '', 'a truck driver', '', ARRAY[]::TEXT[]),
('True', 'true_us.mp3', 'adjective', 'B1', 'connected with facts rather than things that have been invented or guessed', '', 'Indicate whether the following statements are true or false.', '', ARRAY[]::TEXT[]),
('Truly', 'truly_us.mp3', 'adverb', 'B1', 'used to emphasize that a particular statement, feeling, etc. is sincere or real', '', 'She truly believes that none of this is her fault.', '', ARRAY[]::TEXT[]),
('Trust', 'trust_us.mp3', 'noun', 'B1', 'the belief that somebody/something is good, sincere, honest, etc. and will not try to harm or trick you', '', 'Our partnership is based on trust.', '', ARRAY[]::TEXT[]),
('Trust', 'trust_us.mp3', 'verb', 'B1', 'to have confidence in somebody; to believe that somebody is good, sincere, honest, etc.', '', 'trust somebody, She trusts Alan implicitly.', '', ARRAY[]::TEXT[]),
('Trustee', 'trustee_us.mp3', 'noun', 'B1', 'a person or an organization that has control of money or property that has been put into a trust for somebody', '', 'The bank will act as trustees for the estate until the child is 18.', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
