INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Being', 'being_us.mp3', 'noun', 'B1', 'existence', '', 'The Irish Free State came into being in 1922.', '', ARRAY[]::TEXT[]),
('Belief', 'belief_us.mp3', 'noun', 'B1', 'a strong feeling that something/somebody exists or is true; confidence that something/somebody is good or right', '', 'belief in something/somebody, I admire his passionate belief in what he is doing.', '', ARRAY[]::TEXT[]),
('Believe', 'believe_us.mp3', 'verb', 'B1', 'to feel certain that something is true or that somebody is telling you the truth', '', 'believe somebody, I don''t believe you!', '', ARRAY[]::TEXT[]),
('Bell', 'bell_us.mp3', 'noun', 'B1', 'a hollow metal object, often like a cup in shape, that makes a ringing sound when hit by a small piece of metal inside it; the sound that it makes', '', 'A peal of church bells rang out in the distance.', '', ARRAY[]::TEXT[]),
('Belong', 'belong_us.mp3', 'verb', 'B1', 'to be in the right or suitable place', '', 'Where do these plates belong (= where are they kept)?', '', ARRAY[]::TEXT[]),
('Beloved', 'beloved_us.mp3', 'adjective', 'B1', 'loved very much', '', 'in memory of our dearly beloved son, John', '', ARRAY[]::TEXT[]),
('Below', 'below_us.mp3', 'adverb', 'B1', 'at or to a lower level, position or place', '', 'They live on the floor below.', '', ARRAY[]::TEXT[]),
('Below', 'below_us.mp3', 'preposition', 'B1', 'at or to a lower level or position than somebody/something', '', 'He dived below the surface of the water.', '', ARRAY[]::TEXT[]),
('Belt', 'belt_us.mp3', 'noun', 'B1', 'a long narrow piece of leather, cloth, etc. that you wear around the middle part of your body', '', 'to do up/fasten/tighten a belt', '', ARRAY[]::TEXT[]),
('Bench', 'bench_us.mp3', 'noun', 'B1', 'a long seat for two or more people, usually made of wood', '', 'a park bench', '', ARRAY[]::TEXT[]),
('Benchmark', 'benchmark_us.mp3', 'noun', 'B1', 'something that can be measured and used as a standard that other things can be compared with', '', 'Tests at the age of seven provide a benchmark against which the child''s progress at school can be measured.', '', ARRAY[]::TEXT[]),
('Bend', 'bend_us.mp3', 'noun', 'B1', 'a curve or turn, especially in a road or river', '', 'a sharp bend in the road', '', ARRAY[]::TEXT[]),
('Bend', 'bend_us.mp3', 'verb', 'B1', 'to lean, or make something lean, in a particular direction', '', 'He bent and kissed her.', '', ARRAY[]::TEXT[]),
('Beneath', 'beneath_us.mp3', 'preposition', 'B1', 'in or to a lower position than somebody/something; under somebody/something', '', 'They found the body buried beneath a pile of leaves.', '', ARRAY[]::TEXT[]),
('Beneficial', 'beneficial_us.mp3', 'adjective', 'B1', 'improving a situation; having a helpful or useful effect', '', 'A good diet is beneficial to health.', '', ARRAY[]::TEXT[]),
('Beneficiary', 'beneficiary_us.mp3', 'noun', 'B1', 'a person who gains as a result of something', '', 'Who will be the main beneficiary of the cuts in income tax?', '', ARRAY[]::TEXT[]),
('Benefit', 'benefit_us.mp3', 'noun', 'B1', 'an advantage that something gives you; a helpful and useful effect that something has', '', 'Freedom of information brings great benefits.', '', ARRAY[]::TEXT[]),
('Benefit', 'benefit_us.mp3', 'verb', 'B1', 'to be useful to somebody or improve their life in some way', '', 'We should spend the money on something that will benefit everyone.', '', ARRAY[]::TEXT[]),
('Bent', 'bent_us.mp3', 'adjective', 'B1', 'not straight', '', 'a piece of bent wire', '', ARRAY[]::TEXT[]),
('Beside', 'beside_us.mp3', 'preposition', 'B1', 'next to or at the side of somebody/something', '', 'He sat beside her all night.', '', ARRAY[]::TEXT[]),
('Besides', 'besides_us.mp3', 'adverb', 'B1', 'used for making an extra comment that adds to what you have just said', '', 'I don''t really want to go. Besides, it''s too late now.', '', ARRAY[]::TEXT[]),
('Besides', 'besides_us.mp3', 'preposition', 'B1', 'in addition to somebody/something; apart from somebody/something', '', 'We have lots of things in common besides music.', '', ARRAY[]::TEXT[]),
('Best', 'best_us.mp3', 'adjective', 'B1', 'of the most excellent type or quality', '', 'That''s the best movie I''ve ever seen!', '', ARRAY[]::TEXT[]),
('Best', 'best_us.mp3', 'adverb', 'B1', 'most; to the greatest extent', '', 'Which one do you like best?', '', ARRAY[]::TEXT[]),
('Best', 'best_us.mp3', 'noun', 'B1', 'the most excellent thing or person', '', 'We all want the best for our children.', '', ARRAY[]::TEXT[]),
('Bet', 'bet_us.mp3', 'noun', 'B1', 'an arrangement to risk money, etc. on the result of a particular event; the money that you risk in this way', '', 'to win/lose a bet', '', ARRAY[]::TEXT[]),
('Bet', 'bet_us.mp3', 'verb', 'B1', 'to risk money on a race or an event by trying to predict the result', '', 'You have to be over 16 to bet.', '', ARRAY[]::TEXT[]),
('Betray', 'betray_us.mp3', 'verb', 'B1', 'to give information about somebody/something to an enemy', '', 'betray somebody/something, He was offered money to betray his colleagues.', '', ARRAY[]::TEXT[]),
('Better', 'better_us.mp3', 'adjective', 'B1', 'of a higher standard or less poor quality; not as bad as something else', '', 'We''re hoping for better weather tomorrow.', '', ARRAY[]::TEXT[]),
('Better', 'better_us.mp3', 'adverb', 'B1', 'in a more excellent or pleasant way; not as badly', '', 'She sings much better than I do.', '', ARRAY[]::TEXT[]),
('Better', 'better_us.mp3', 'noun', 'B1', 'something that is better', '', 'the better of the two books', '', ARRAY[]::TEXT[]),
('Between', 'between_us.mp3', 'adverb', 'B1', 'in the space or period of time separating two or more points, objects, etc. or two dates, events, etc.', '', 'The house was near a park but there was a road in between.', '', ARRAY[]::TEXT[]),
('Between', 'between_us.mp3', 'preposition', 'B1', 'in or into the space separating two or more points, objects, people, etc.', '', 'Q comes between P and R in the English alphabet.', '', ARRAY[]::TEXT[]),
('Beyond', 'beyond_us.mp3', 'adverb', 'B1', 'on the other side; further on', '', 'Snowdon and the mountains beyond were covered in snow.', '', ARRAY[]::TEXT[]),
('Beyond', 'beyond_us.mp3', 'preposition', 'B1', 'on or to the further side of something', '', 'The road continues beyond the village up into the hills.', '', ARRAY[]::TEXT[]),
('Bias', 'bias_us.mp3', 'noun', 'B1', 'a strong feeling in favour of or against one group of people, or one side in an argument, often not based on fair judgement', '', 'accusations of political bias in news programmes (= that reports are unfair and show favour to one political party)', '', ARRAY[]::TEXT[]),
('Bicycle', 'bicycle_us.mp3', 'noun', 'B1', 'a road vehicle with two wheels that you ride by pushing the pedals with your feet', '', 'He got on his bicycle and rode off.', '', ARRAY[]::TEXT[]),
('Bid', 'bid_us.mp3', 'noun', 'B1', 'an offer by a person or a company to pay a particular amount of money for something', '', 'bid for something, A German firm launched a takeover bid for the company.', '', ARRAY[]::TEXT[]),
('Bid', 'bid_us.mp3', 'verb', 'B1', 'to offer to pay a particular price for something, especially at an auction', '', 'bid (something) (for something), I bid £2 000 for the painting.', '', ARRAY[]::TEXT[]),
('Big', 'big_us.mp3', 'adjective', 'B1', 'large in size, degree, amount, etc.', '', 'a big man/house/increase', '', ARRAY[]::TEXT[]),
('Bike', 'bike_us.mp3', 'noun', 'B1', 'a bicycle', '', 'I used to ride my bike around the neighbourhood for hours.', '', ARRAY[]::TEXT[]),
('Bill', 'bill_us.mp3', 'noun', 'B1', 'a document that shows how much you owe somebody for goods or services', '', 'the phone/electricity/gas bill', '', ARRAY[]::TEXT[]),
('Bill', 'bill_us.mp3', 'verb', 'B1', 'to send somebody a bill for something', '', 'bill somebody for something, Please bill me for the books.', '', ARRAY[]::TEXT[]),
('Billion', 'billion_us.mp3', 'number', 'B1', '1 000 000 000; one thousand million', '', 'Worldwide sales reached 2.5 billion.', '', ARRAY[]::TEXT[]),
('Bin', 'bin_us.mp3', 'noun', 'B1', 'a container that you put waste in', '', 'a rubbish bin', '', ARRAY[]::TEXT[]),
('Bind', 'bind_us.mp3', 'verb', 'B1', 'to tie somebody/something with rope, string, etc. so that they/it cannot move or are held together strongly', '', 'bind somebody/something to something, She was bound to a chair.', '', ARRAY[]::TEXT[]),
('Biography', 'biography_us.mp3', 'noun', 'B1', 'the story of a person’s life written by somebody else; this type of writing', '', 'Boswell’s biography of Johnson', '', ARRAY[]::TEXT[]),
('Biological', 'biological_us.mp3', 'adjective', 'B1', 'connected with the science of biology', '', 'the biological sciences', '', ARRAY[]::TEXT[]),
('Biology', 'biology_us.mp3', 'noun', 'B1', 'the scientific study of the life and structure of plants and animals', '', 'a degree in biology', '', ARRAY[]::TEXT[]),
('Bird', 'bird_us.mp3', 'noun', 'B1', 'a creature that is covered with feathers and has two wings and two legs. Most birds can fly.', '', 'a bird’s nest with two eggs in it', '', ARRAY[]::TEXT[]),
('Birth', 'birth_us.mp3', 'noun', 'B1', 'the time when a baby is born; the process of being born', '', 'at birth, The baby weighed three kilos at birth.', '', ARRAY[]::TEXT[]),
('Birthday', 'birthday_us.mp3', 'noun', 'B1', 'the day in each year which is the same date as the one on which you were born', '', 'Happy Birthday!', '', ARRAY[]::TEXT[]),
('Biscuit', 'biscuit_us.mp3', 'noun', 'B1', 'a small flat dry cake for one person, usually sweet, and baked until hard', '', 'a packet/tin of chocolate biscuits', '', ARRAY[]::TEXT[]),
('Bishop', 'bishop_us.mp3', 'noun', 'B1', 'a senior priest in charge of the work of the Church in a city or district', '', 'the Bishop of Oxford', '', ARRAY[]::TEXT[]),
('Bit', 'bit_us.mp3', 'noun', 'B1', 'rather; to some extent', '', 'These trousers are a bit tight.', '', ARRAY[]::TEXT[]),
('Bite', 'bite_us.mp3', 'noun', 'B1', 'an act of biting', '', 'The dog gave me a playful bite.', '', ARRAY[]::TEXT[]),
('Bite', 'bite_us.mp3', 'verb', 'B1', 'to use your teeth to cut into or through something', '', 'Does your dog bite?', '', ARRAY[]::TEXT[]),
('Bitter', 'bitter_us.mp3', 'adjective', 'B1', 'having a strong, unpleasant taste; not sweet', '', 'Black coffee leaves a bitter taste in the mouth.', '', ARRAY[]::TEXT[]),
('Bizarre', 'bizarre_us.mp3', 'adjective', 'B1', 'very strange or unusual', '', 'a bizarre situation/incident/story', '', ARRAY[]::TEXT[]),
('Black', 'black_us.mp3', 'adjective', 'B1', 'having the very darkest colour, like coal or the sky at night', '', 'a shiny black car', '', ARRAY[]::TEXT[]),
('Black', 'black_us.mp3', 'noun', 'B1', 'the very darkest colour, like night or coal', '', 'the black of the night sky', '', ARRAY[]::TEXT[]),
('Blade', 'blade_us.mp3', 'noun', 'B1', 'the flat part of a knife, tool or machine, which has a sharp edge or edges for cutting', '', 'The machine comes with a plastic guard over the blade to protect the operator.', '', ARRAY[]::TEXT[]),
('Blame', 'blame_us.mp3', 'noun', 'B1', 'responsibility for doing something badly or wrongly; saying that somebody is responsible for something', '', 'Why do I always get the blame for everything that goes wrong?', '', ARRAY[]::TEXT[]),
('Blame', 'blame_us.mp3', 'verb', 'B1', 'to think or say that somebody/something is responsible for something bad', '', 'blame somebody/something for something, She doesn''t blame anyone for her father''s death.', '', ARRAY[]::TEXT[]),
('Blank', 'blank_us.mp3', 'adjective', 'B1', 'empty, with nothing written, printed or recorded on it', '', 'Sign your name in the blank space below.', '', ARRAY[]::TEXT[]),
('Blank', 'blank_us.mp3', 'noun', 'B1', 'an empty space on a printed form or document for you to write answers, information, etc. in', '', 'Please fill in the blanks.', '', ARRAY[]::TEXT[]),
('Blanket', 'blanket_us.mp3', 'noun', 'B1', 'a large cover, often made of wool, used especially on beds to keep people warm', '', 'It’s cold tonight—can I have another blanket?', '', ARRAY[]::TEXT[]),
('Blast', 'blast_us.mp3', 'noun', 'B1', 'an explosion or a powerful movement of air caused by an explosion', '', 'a bomb blast', '', ARRAY[]::TEXT[]),
('Blast', 'blast_us.mp3', 'verb', 'B1', 'to violently destroy or break something into pieces, using explosives', '', 'They blasted a huge crater in the runway.', '', ARRAY[]::TEXT[]),
('Bleed', 'bleed_us.mp3', 'verb', 'B1', 'to lose blood, especially from a wound or an injury', '', 'My finger''s bleeding.', '', ARRAY[]::TEXT[]),
('Blend', 'blend_us.mp3', 'noun', 'B1', 'a mixture of different types of the same thing', '', 'a blend of tea', '', ARRAY[]::TEXT[]),
('Blend', 'blend_us.mp3', 'verb', 'B1', 'to mix two or more substances together', '', 'blend A with B, Blend the flour with the milk to make a smooth paste.', '', ARRAY[]::TEXT[]),
('Bless', 'bless_us.mp3', 'verb', 'B1', 'to ask God to protect somebody/something', '', 'They brought the children to Jesus and he blessed them.', '', ARRAY[]::TEXT[]),
('Blessing', 'blessing_us.mp3', 'noun', 'B1', 'God’s help and protection, or a prayer asking for this', '', 'to pray for God’s blessing', '', ARRAY[]::TEXT[]),
('Blind', 'blind_us.mp3', 'adjective', 'B1', 'not able to see', '', 'Doctors think he will go blind.', '', ARRAY[]::TEXT[]),
('Block', 'block_us.mp3', 'noun', 'B1', 'a large piece of a solid material that is square or rectangular in shape and usually has flat sides', '', 'The houses are made of concrete blocks with tin roofs.', '', ARRAY[]::TEXT[]),
('Block', 'block_us.mp3', 'verb', 'B1', 'to stop something from moving or flowing through a pipe, a passage, a road, etc. by putting something in it or across it', '', 'After today''s heavy snow, many roads are still blocked.', '', ARRAY[]::TEXT[]),
('Blog', 'blog_us.mp3', 'noun', 'B1', 'a website where an individual person, or people representing an organization, write regularly about recent events or topics that interest them, usually with photos and links to other websites that they find interesting', '', 'This is a link to the museum''s blog.', '', ARRAY[]::TEXT[]),
('Blonde', 'blonde_us.mp3', 'adjective', 'B1', 'pale gold in colour', '', 'She had long blonde hair.', '', ARRAY[]::TEXT[]),
('Blood', 'blood_us.mp3', 'noun', 'B1', 'the red liquid that flows through the bodies of humans and animals', '', 'He lost a lot of blood in the accident.', '', ARRAY[]::TEXT[]),
('Blow', 'blow_us.mp3', 'noun', 'B1', 'a hard hit with the hand, a weapon, etc.', '', 'She received a severe blow on the head.', '', ARRAY[]::TEXT[]),
('Blow', 'blow_us.mp3', 'verb', 'B1', 'to send out air from the mouth', '', '+ adv./prep., You''re not blowing hard enough!', '', ARRAY[]::TEXT[]),
('Blue', 'blue_us.mp3', 'adjective', 'B1', 'having the colour of a clear sky or the sea on a clear day', '', 'piercing blue eyes', '', ARRAY[]::TEXT[]),
('Blue', 'blue_us.mp3', 'noun', 'B1', 'the colour of a clear sky or the sea on a clear day', '', 'bright/dark/light/pale/deep blue', '', ARRAY[]::TEXT[]),
('Board', 'board_us.mp3', 'noun', 'B1', 'a long thin piece of strong hard material, especially wood, used, for example, for making floors, building walls and roofs and making boats', '', 'He had ripped up the carpet, leaving only the bare boards.', '', ARRAY[]::TEXT[]),
('Board', 'board_us.mp3', 'verb', 'B1', 'to get on a ship, train, plane, bus, etc.', '', 'Passengers are waiting to board.', '', ARRAY[]::TEXT[]),
('Boast', 'boast_us.mp3', 'verb', 'B1', 'to talk in a way that shows you are too proud of something that you have or can do', '', 'I don''t want to boast, but I can actually speak six languages.', '', ARRAY[]::TEXT[]),
('Boat', 'boat_us.mp3', 'noun', 'B1', 'a vehicle (smaller than a ship) that travels on water, moved by oars, sails or a motor', '', 'a rowing/sailing boat', '', ARRAY[]::TEXT[]),
('Body', 'body_us.mp3', 'noun', 'B1', 'the whole physical structure of a human or an animal', '', 'The human body is a complex structure.', '', ARRAY[]::TEXT[]),
('Boil', 'boil_us.mp3', 'verb', 'B1', 'when a liquid boils or when you boil it, it is heated to the point where it forms bubbles and turns to steam or vapour', '', 'The water was bubbling and boiling away.', '', ARRAY[]::TEXT[]),
('Bold', 'bold_us.mp3', 'adjective', 'B1', 'brave and confident; not afraid to say what you feel or to take risks', '', 'It was a bold move on their part to open a business in France.', '', ARRAY[]::TEXT[]),
('Bomb', 'bomb_us.mp3', 'noun', 'B1', 'a weapon designed to explode at a particular time or when it is dropped or thrown', '', 'a bomb goes off/explodes', '', ARRAY[]::TEXT[]),
('Bomb', 'bomb_us.mp3', 'verb', 'B1', 'to attack something/somebody by leaving a bomb in a place or by dropping bombs from a plane', '', 'Warplanes bombed targets in and around the capital.', '', ARRAY[]::TEXT[]),
('Bombing', 'bombing_us.mp3', 'noun', 'B1', 'an occasion when a bomb is dropped or left somewhere; the act of doing this', '', 'recent bombings in major cities', '', ARRAY[]::TEXT[]),
('Bond', 'bond_us.mp3', 'noun', 'B1', 'something that forms a connection between people or groups, such as a feeling of friendship or shared ideas and experiences', '', 'the bond that links us', '', ARRAY[]::TEXT[]),
('Bone', 'bone_us.mp3', 'noun', 'B1', 'any of the hard parts that form the skeleton of the body of a human or an animal', '', 'He survived the accident with no broken bones.', '', ARRAY[]::TEXT[]),
('Bonus', 'bonus_us.mp3', 'noun', 'B1', 'an extra amount of money that is added to a payment, especially to somebody’s wages or salary as a reward', '', 'a £100 Christmas bonus', '', ARRAY[]::TEXT[]),
('Book', 'book_us.mp3', 'noun', 'B1', 'a set of printed pages that are fastened inside a cover so that you can turn them and read them', '', 'His desk was covered with piles of books.', '', ARRAY[]::TEXT[]),
('Book', 'book_us.mp3', 'verb', 'B1', 'to arrange to have or use something on a particular date in the future; to buy a ticket in advance', '', 'Book early to avoid disappointment.', '', ARRAY[]::TEXT[]),
('Booking', 'booking_us.mp3', 'noun', 'B1', 'an arrangement that you make in advance to buy a ticket to travel somewhere, go to the theatre, etc.', '', 'a booking form/hall/clerk', '', ARRAY[]::TEXT[]),
('Boom', 'boom_us.mp3', 'noun', 'B1', 'a sudden increase in trade and economic activity; a period of wealth and success', '', 'Living standards improved rapidly during the post-war boom.', '', ARRAY[]::TEXT[]),
('Boost', 'boost_us.mp3', 'noun', 'B1', 'something that helps or encourages somebody/something', '', 'a great/tremendous/welcome boost', '', ARRAY[]::TEXT[]),
('Boost', 'boost_us.mp3', 'verb', 'B1', 'to make something increase, or become better or more successful', '', 'to boost exports/profits', '', ARRAY[]::TEXT[]),
('Boot', 'boot_us.mp3', 'noun', 'B1', 'a strong shoe that covers the foot and ankle and often the lower part of the leg', '', '(British English), walking boots', '', ARRAY[]::TEXT[]),
('Border', 'border_us.mp3', 'noun', 'B1', 'the line that divides two countries or areas; the land near this line', '', 'I live in a small town in the US, near the Canadian border.', '', ARRAY[]::TEXT[]),
('Border', 'border_us.mp3', 'verb', 'B1', 'to share a border with another country or area', '', 'the countries bordering the Baltic', '', ARRAY[]::TEXT[]),
('Bored', 'bored_us.mp3', 'adjective', 'B1', 'feeling tired and impatient because you have lost interest in somebody/something or because you have nothing to do', '', 'There was a bored expression on her face.', '', ARRAY[]::TEXT[]),
('Boring', 'boring_us.mp3', 'adjective', 'B1', 'not interesting; making you feel tired and impatient', '', 'He''s such a boring man!', '', ARRAY[]::TEXT[]),
('Born', 'born_us.mp3', 'verb', 'B1', 'to come out of your mother’s body at the beginning of your life', '', 'I was born in 1976.', '', ARRAY[]::TEXT[]),
('Borrow', 'borrow_us.mp3', 'verb', 'B1', 'to take and use something that belongs to somebody else, and return it to them at a later time', '', 'borrow something, Can I borrow your umbrella?', '', ARRAY[]::TEXT[]),
('Boss', 'boss_us.mp3', 'noun', 'B1', 'a person who is in charge of other people at work and tells them what to do', '', 'I''ll ask my boss if I can have the day off.', '', ARRAY[]::TEXT[]),
('Both', 'both_us.mp3', 'determiner', 'B1', 'used with plural nouns to mean ‘the two’ or ‘the one as well as the other’', '', 'Both women were French.', '', ARRAY[]::TEXT[]),
('Both', 'both_us.mp3', 'pronoun', 'B1', 'used with plural nouns to mean ‘the two’ or ‘the one as well as the other’', '', 'Both women were French.', '', ARRAY[]::TEXT[]),
('Bother', 'bother_us.mp3', 'verb', 'B1', 'to spend time and/or energy doing something', '', '‘Shall I wait?’ ‘No, don''t bother’.', '', ARRAY[]::TEXT[]),
('Bottle', 'bottle_us.mp3', 'noun', 'B1', 'a glass or plastic container, usually round with straight sides and a narrow neck, used especially for storing liquids', '', 'a wine/beer/milk/water bottle', '', ARRAY[]::TEXT[]),
('Bottom', 'bottom_us.mp3', 'adjective', 'B1', 'in the lowest, last or furthest place or position', '', 'your bottom lip', '', ARRAY[]::TEXT[]),
('Bottom', 'bottom_us.mp3', 'noun', 'B1', 'the lowest part of something', '', 'the bottom of the screen/stairs/hill', '', ARRAY[]::TEXT[]),
('Bounce', 'bounce_us.mp3', 'verb', 'B1', 'if something bounces or you bounce it, it moves quickly away from a surface it has just hit or you make it do this', '', 'The ball bounced twice before he could reach it.', '', ARRAY[]::TEXT[]),
('Bound', 'bound_us.mp3', 'adjective', 'B1', 'certain or likely to happen, or to do or be something', '', 'There are bound to be changes when the new system is introduced.', '', ARRAY[]::TEXT[]),
('Boundary', 'boundary_us.mp3', 'noun', 'B1', 'a real or imagined line that marks the limits or edges of something and separates it from other things or places; a dividing line', '', 'After the war the national boundaries were redrawn.', '', ARRAY[]::TEXT[]),
('Bow', 'bow_us.mp3', 'noun', 'B1', 'the act of bending your head or the upper part of your body forward in order to say hello or goodbye to somebody or to show respect', '', 'She gave a slight bow of her head in greeting.', '', ARRAY[]::TEXT[]),
('Bow', 'bow_us.mp3', 'verb', 'B1', 'to move your head or the top half of your body forwards and downwards as a sign of respect or to say hello or goodbye', '', 'bow (to/before somebody/something), He bowed low to the assembled crowd.', '', ARRAY[]::TEXT[]),
('Bowl', 'bowl_us.mp3', 'noun', 'B1', 'a deep round dish with a wide open top, used especially for holding food or liquid', '', 'a salad/fruit/sugar bowl', '', ARRAY[]::TEXT[]),
('Box', 'box_us.mp3', 'noun', 'B1', 'a container made of wood, thick card, metal, etc. with a flat stiff base and sides and often a lid (= cover), used especially for holding solid things', '', 'in a box, Everything we owned was neatly packed in cardboard boxes.', '', ARRAY[]::TEXT[]),
('Boy', 'boy_us.mp3', 'noun', 'B1', 'a male child or a young male person', '', 'a little/small/young boy', '', ARRAY[]::TEXT[]),
('Boyfriend', 'boyfriend_us.mp3', 'noun', 'B1', 'a man or boy that somebody has a romantic or sexual relationship with', '', 'She''s got a new boyfriend.', '', ARRAY[]::TEXT[]),
('Brain', 'brain_us.mp3', 'noun', 'B1', 'the organ inside the head that controls movement, thought, memory and feeling', '', 'The human brain is a complex organ.', '', ARRAY[]::TEXT[]),
('Branch', 'branch_us.mp3', 'noun', 'B1', 'a part of a tree that grows out from the main stem and on which leaves, flowers and fruit grow', '', 'She climbed the tree and hid in the branches.', '', ARRAY[]::TEXT[]),
('Brand', 'brand_us.mp3', 'noun', 'B1', 'a type of product, service, etc. made or offered by a particular company under a particular name', '', 'a well-known brand of toothpaste', '', ARRAY[]::TEXT[]),
('Brand', 'brand_us.mp3', 'verb', 'B1', 'to apply a brand name, image or identity to something', '', 'brand something, The website was not doing a very good job of branding the company.', '', ARRAY[]::TEXT[]),
('Brave', 'brave_us.mp3', 'adjective', 'B1', 'willing to do things that are difficult, dangerous or painful; not afraid', '', 'brave men and women', '', ARRAY[]::TEXT[]),
('Breach', 'breach_us.mp3', 'noun', 'B1', 'a failure to do something that must be done by law', '', 'a breach of contract/copyright/warranty', '', ARRAY[]::TEXT[]),
('Breach', 'breach_us.mp3', 'verb', 'B1', 'to not keep to an agreement or not keep a promise', '', 'The government is accused of breaching the terms of the treaty.', '', ARRAY[]::TEXT[]),
('Bread', 'bread_us.mp3', 'noun', 'B1', 'a type of food made from flour, water and usually yeast mixed together and baked', '', 'a loaf/slice/piece of bread', '', ARRAY[]::TEXT[]),
('Break', 'break_us.mp3', 'noun', 'B1', 'a short period of time when you stop what you are doing and rest, eat, etc.', '', 'She was on her lunch break.', '', ARRAY[]::TEXT[]),
('Break', 'break_us.mp3', 'verb', 'B1', 'to be damaged and separated into two or more parts, as a result of force; to damage something in this way', '', 'All the windows broke with the force of the blast.', '', ARRAY[]::TEXT[]),
('Breakdown', 'breakdown_us.mp3', 'noun', 'B1', 'an occasion when a vehicle or machine stops working', '', 'a breakdown on the motorway', '', ARRAY[]::TEXT[]),
('Breakfast', 'breakfast_us.mp3', 'noun', 'B1', 'the first meal of the day', '', 'They were having breakfast when I arrived.', '', ARRAY[]::TEXT[]),
('Breakthrough', 'breakthrough_us.mp3', 'noun', 'B1', 'an important development that may lead to an agreement or achievement', '', 'to make/achieve a breakthrough', '', ARRAY[]::TEXT[]),
('Breast', 'breast_us.mp3', 'noun', 'B1', 'either of the two round soft parts at the front of a woman’s body that produce milk when she has had a baby', '', 'She put the baby to her breast.', '', ARRAY[]::TEXT[]),
('Breath', 'breath_us.mp3', 'noun', 'B1', 'the air that you take into your lungs and send out again', '', 'His breath smelt of garlic.', '', ARRAY[]::TEXT[]),
('Breathe', 'breathe_us.mp3', 'verb', 'B1', 'to take air into your lungs and send it out again through your nose or mouth', '', 'He breathed deeply before speaking again.', '', ARRAY[]::TEXT[]),
('Breathing', 'breathing_us.mp3', 'noun', 'B1', 'the action of taking air into the lungs and sending it out again', '', 'Her breathing became steady and she fell asleep.', '', ARRAY[]::TEXT[]),
('Breed', 'breed_us.mp3', 'noun', 'B1', 'a particular type of animal that has been developed by people in a certain way, especially a type of dog, cat or farm animal', '', 'Labradors and other large breeds of dog', '', ARRAY[]::TEXT[]),
('Breed', 'breed_us.mp3', 'verb', 'B1', 'to have sex and produce young', '', 'Many animals breed only at certain times of the year.', '', ARRAY[]::TEXT[]),
('Brick', 'brick_us.mp3', 'noun', 'B1', 'baked clay used for building walls, houses and other buildings; an individual block of this', '', 'The school is built of brick.', '', ARRAY[]::TEXT[]),
('Bride', 'bride_us.mp3', 'noun', 'B1', 'a woman on her wedding day, or just before or just after it', '', 'a toast to the bride and groom', '', ARRAY[]::TEXT[]),
('Bridge', 'bridge_us.mp3', 'noun', 'B1', 'a structure that is built over a road, railway, river, etc. so that people, vehicles, etc. can cross from one side to the other', '', 'We crossed the bridge over the River Windrush.', '', ARRAY[]::TEXT[]),
('Brief', 'brief_us.mp3', 'adjective', 'B1', 'lasting only a short time; short', '', 'a brief visit/meeting/conversation', '', ARRAY[]::TEXT[]),
('Briefly', 'briefly_us.mp3', 'adverb', 'B1', 'for a short time', '', 'He had spoken to Emma only briefly.', '', ARRAY[]::TEXT[]),
('Bright', 'bright_us.mp3', 'adjective', 'B1', 'full of light; shining strongly', '', 'bright light/sunshine', '', ARRAY[]::TEXT[]),
('Brilliant', 'brilliant_us.mp3', 'adjective', 'B1', 'extremely clever or impressive', '', 'What a brilliant idea!', '', ARRAY[]::TEXT[]),
('Bring', 'bring_us.mp3', 'verb', 'B1', 'to come to a place with somebody/something', '', 'bring somebody/something (with you), Don''t forget to bring your books with you.', '', ARRAY[]::TEXT[]),
('Broad', 'broad_us.mp3', 'adjective', 'B1', 'wide', '', 'a broad street/avenue/river', '', ARRAY[]::TEXT[]),
('Broadband', 'broadband_us.mp3', 'noun', 'B1', 'a way of connecting to the internet that allows you to receive information, including pictures, etc., very quickly and that is always active (so that the user does not have to connect each time)', '', 'plans to provide rural areas with fast broadband', '', ARRAY[]::TEXT[]),
('Broadcast', 'broadcast_us.mp3', 'noun', 'B1', 'a radio or television programme', '', '(British English), a party political broadcast (= for example, before an election)', '', ARRAY[]::TEXT[]),
('Broadcast', 'broadcast_us.mp3', 'verb', 'B1', 'to send out programmes on television or radio', '', 'The concert will be broadcast live (= at the same time as it takes place) tomorrow evening.', '', ARRAY[]::TEXT[]),
('Broadcaster', 'broadcaster_us.mp3', 'noun', 'B1', 'a person whose job is presenting or talking on television or radio programmes', '', 'She is a writer and broadcaster on environmental matters.', '', ARRAY[]::TEXT[]),
('Broadly', 'broadly_us.mp3', 'adverb', 'B1', 'generally, without considering details', '', 'Broadly speaking, I agree with you.', '', ARRAY[]::TEXT[]),
('Broken', 'broken_us.mp3', 'adjective', 'B1', 'that has been damaged or injured; no longer whole or working correctly', '', 'a broken window/plate', '', ARRAY[]::TEXT[]),
('Brother', 'brother_us.mp3', 'noun', 'B1', 'a boy or man who has the same parents as another person', '', 'We''re brothers.', '', ARRAY[]::TEXT[]),
('Brown', 'brown_us.mp3', 'adjective', 'B1', 'having the colour of earth or coffee', '', 'brown eyes/hair', '', ARRAY[]::TEXT[]),
('Brown', 'brown_us.mp3', 'noun', 'B1', 'the colour of earth or coffee', '', 'leaves of various shades of brown', '', ARRAY[]::TEXT[]),
('Browser', 'browser_us.mp3', 'noun', 'B1', 'a computer program that lets you look at or read documents on the World Wide Web', '', 'What do you use as your default browser?', '', ARRAY[]::TEXT[]),
('Brush', 'brush_us.mp3', 'noun', 'B1', 'an object made of short stiff hairs (called bristles) or wires set in a block of wood or plastic, usually attached to a handle. Brushes are used for many different jobs, such as cleaning, painting and tidying your hair.', '', 'a paintbrush', '', ARRAY[]::TEXT[]),
('Brush', 'brush_us.mp3', 'verb', 'B1', 'to clean, polish or make something smooth with a brush', '', 'brush something, to brush your hair/teeth', '', ARRAY[]::TEXT[]),
('Brutal', 'brutal_us.mp3', 'adjective', 'B1', 'violent and cruel', '', 'a brutal attack/murder/rape/killing', '', ARRAY[]::TEXT[]),
('Bubble', 'bubble_us.mp3', 'noun', 'B1', 'a ball of air or gas in a liquid, or a ball of air inside a solid substance such as glass', '', 'champagne bubbles', '', ARRAY[]::TEXT[]),
('Buck', 'buck_us.mp3', 'noun', 'B1', 'a US, Australian or New Zealand dollar; a South African rand; an Indian rupee', '', 'They cost ten bucks.', '', ARRAY[]::TEXT[]),
('Buddy', 'buddy_us.mp3', 'noun', 'B1', 'a friend', '', 'an old college buddy of mine', '', ARRAY[]::TEXT[]),
('Budget', 'budget_us.mp3', 'noun', 'B1', 'the money that is available to a person or an organization and a plan of how it will be spent over a period of time', '', 'an annual budget of £10 million', '', ARRAY[]::TEXT[]),
('Buffer', 'buffer_us.mp3', 'noun', 'B1', 'a thing or person that reduces a shock or protects somebody/something against difficulties', '', 'buffer against something, Support from family and friends acts as a buffer against stress.', '', ARRAY[]::TEXT[]),
('Bug', 'bug_us.mp3', 'noun', 'B1', 'any small insect', '', 'There''s a bug crawling up your arm.', '', ARRAY[]::TEXT[]),
('Build', 'build_us.mp3', 'verb', 'B1', 'to make something, especially a building, by putting parts together', '', 'build (something), They have permission to build 200 new homes.', '', ARRAY[]::TEXT[]),
('Building', 'building_us.mp3', 'noun', 'B1', 'a structure such as a house or school that has a roof and walls', '', 'a tall/high-rise/ten-storey building', '', ARRAY[]::TEXT[]),
('Bulk', 'bulk_us.mp3', 'noun', 'B1', 'the main part of something; most of something', '', 'The bulk of the population lives in cities.', '', ARRAY[]::TEXT[]),
('Bullet', 'bullet_us.mp3', 'noun', 'B1', 'a small metal object that is fired from a gun', '', 'He was found to have a single bullet wound in his chest.', '', ARRAY[]::TEXT[]),
('Bunch', 'bunch_us.mp3', 'noun', 'B1', 'a number of things of the same type which are growing or fastened together', '', 'a bunch of bananas, grapes, etc.', '', ARRAY[]::TEXT[]),
('Burden', 'burden_us.mp3', 'noun', 'B1', 'a duty, responsibility, etc. that causes worry, difficulty or hard work', '', 'to bear/carry/ease/reduce/share the burden', '', ARRAY[]::TEXT[]),
('Bureaucracy', 'bureaucracy_us.mp3', 'noun', 'B1', 'the system of official rules and ways of doing things that a government or an organization has, especially when these seem to be too complicated', '', 'unnecessary/excessive bureaucracy', '', ARRAY[]::TEXT[]),
('Burial', 'burial_us.mp3', 'noun', 'B1', 'the act or ceremony of burying a dead body', '', 'a burial place/mound/site', '', ARRAY[]::TEXT[]),
('Burn', 'burn_us.mp3', 'noun', 'B1', 'an injury or a mark caused by fire, heat or acid', '', 'to have minor/severe/third-degree burns', '', ARRAY[]::TEXT[]),
('Burn', 'burn_us.mp3', 'verb', 'B1', 'to produce flames and heat', '', 'A welcoming fire was burning in the fireplace.', '', ARRAY[]::TEXT[]),
('Burst', 'burst_us.mp3', 'verb', 'B1', 'to break open or apart, especially because of pressure from inside; to make something break in this way', '', 'That balloon will burst if you blow it up any more.', '', ARRAY[]::TEXT[]),
('Bury', 'bury_us.mp3', 'verb', 'B1', 'to place a dead body in the ground', '', 'bury somebody/something, They killed her and buried her body.', '', ARRAY[]::TEXT[]),
('Bus', 'bus_us.mp3', 'noun', 'B1', 'a large road vehicle that carries passengers, especially one that travels along a fixed route and stops regularly to let people get on and off', '', 'by bus, Shall we walk or go by bus?', '', ARRAY[]::TEXT[]),
('Bush', 'bush_us.mp3', 'noun', 'B1', 'a plant that grows thickly with several hard stems coming up from the root', '', 'a rose/holly bush', '', ARRAY[]::TEXT[]),
('Business', 'business_us.mp3', 'noun', 'B1', 'the activity of making, buying, selling or supplying goods or services for money', '', 'It''s been a pleasure to do business with you.', '', ARRAY[]::TEXT[]),
('Businessman', 'businessman_us.mp3', 'noun', 'B1', 'a man who works in business, especially at a high level', '', 'a group of visiting Italian politicians and businessmen', '', ARRAY[]::TEXT[]),
('Busy', 'busy_us.mp3', 'adjective', 'B1', 'having a lot to do; perhaps not free to do something else because you are working on something', '', 'Are you busy tonight?', '', ARRAY[]::TEXT[]),
('But', 'but_us.mp3', 'conjunction', 'B1', 'used to introduce a word or phrase that contrasts with what was said before', '', 'I got it wrong. It wasn''t the red one but the blue one.', '', ARRAY[]::TEXT[]),
('But', 'but_us.mp3', 'preposition', 'B1', 'except; apart from', '', 'We''ve had nothing but trouble with this car.', '', ARRAY[]::TEXT[]),
('Butter', 'butter_us.mp3', 'noun', 'B1', 'a soft yellow food made from cream, used in cooking and for spreading on bread', '', 'Fry the onions in butter.', '', ARRAY[]::TEXT[]),
('Button', 'button_us.mp3', 'noun', 'B1', 'a small round piece of metal, plastic, etc. that is sewn onto a piece of clothing and used for fastening two parts together', '', '(British English), to do up/undo your buttons', '', ARRAY[]::TEXT[]),
('Buy', 'buy_us.mp3', 'verb', 'B1', 'to obtain something by paying money for it', '', 'buy (something), Where did you buy that dress?', '', ARRAY[]::TEXT[]),
('By', 'by_us.mp3', 'adverb', 'B1', 'past', '', 'Just drive by. Don''t stop.', '', ARRAY[]::TEXT[]),
('By', 'by_us.mp3', 'preposition', 'B1', 'used for showing how or in what way something is done', '', 'The house is heated by gas.', '', ARRAY[]::TEXT[]),
('Bye', 'bye_us.mp3', 'exclamation', 'B1', 'goodbye', '', 'Bye! See you next week.', '', ARRAY[]::TEXT[]),
('Cabin', 'cabin_us.mp3', 'noun', 'B1', 'a small room on a ship in which you live or sleep', '', 'I lay in my cabin feeling miserably seasick.', '', ARRAY[]::TEXT[]),
('Cabinet', 'cabinet_us.mp3', 'noun', 'B1', 'a group of senior members of a government that is responsible for advising and deciding on government policy', '', 'a cabinet meeting', '', ARRAY[]::TEXT[]),
('Cable', 'cable_us.mp3', 'noun', 'B1', 'a set of wires, covered in plastic or rubber, that carries electricity, phone signals, etc.', '', 'fibre-optic cable', '', ARRAY[]::TEXT[]),
('Cafe', 'cafe_us.mp3', 'noun', 'B1', 'a place where you can buy drinks and simple meals. Alcohol is not usually served in British or American cafes.', '', 'There are small shops and pavement cafes around every corner.', '', ARRAY[]::TEXT[]),
('Cake', 'cake_us.mp3', 'noun', 'B1', 'a sweet food made from a mixture of flour, eggs, butter, sugar, etc. that is baked in an oven. Cakes are made in various shapes and sizes and are often decorated, for example with cream or icing.', '', 'a piece/slice of cake', '', ARRAY[]::TEXT[]),
('Calculate', 'calculate_us.mp3', 'verb', 'B1', 'to use numbers to find out a total number, amount, distance, etc.', '', 'calculate something, An independent valuer will calculate the value of your property.', '', ARRAY[]::TEXT[]),
('Calculation', 'calculation_us.mp3', 'noun', 'B1', 'the act or process of using numbers to find out an amount', '', 'Cathy did a rough calculation.', '', ARRAY[]::TEXT[]),
('Call', 'call_us.mp3', 'noun', 'B1', 'the act of speaking to somebody on the phone', '', 'to get/receive a call from somebody', '', ARRAY[]::TEXT[]),
('Call', 'call_us.mp3', 'verb', 'B1', 'to give somebody/something a particular name; to use a particular name or title when you are talking to somebody', '', 'call somebody/something + noun, They decided to call the baby Mark.', '', ARRAY[]::TEXT[]),
('Calm', 'calm_us.mp3', 'adjective', 'B1', 'not excited, nervous or upset', '', 'It is important to keep calm in an emergency.', '', ARRAY[]::TEXT[]),
('Calm', 'calm_us.mp3', 'noun', 'B1', 'a quiet and peaceful time or situation', '', 'The police appealed for calm.', '', ARRAY[]::TEXT[]),
('Calm', 'calm_us.mp3', 'verb', 'B1', 'to make somebody/something become quiet and more relaxed, especially after strong emotion or excitement', '', 'Have some tea; it''ll calm your nerves.', '', ARRAY[]::TEXT[]),
('Camera', 'camera_us.mp3', 'noun', 'B1', 'a piece of equipment for taking photographs, moving pictures or television pictures. It can be a separate item or part of another device.', '', 'Just point the camera and press the button.', '', ARRAY[]::TEXT[]),
('Camp', 'camp_us.mp3', 'noun', 'B1', 'a place where people live temporarily in tents or temporary buildings', '', 'Let''s return to camp.', '', ARRAY[]::TEXT[]),
('Camp', 'camp_us.mp3', 'verb', 'B1', 'to put up a tent and live in it for a short time', '', 'I camped overnight in a field.', '', ARRAY[]::TEXT[]),
('Campaign', 'campaign_us.mp3', 'noun', 'B1', 'a series of planned activities that are intended to achieve a particular social, commercial or political aim', '', 'an anti-smoking campaign', '', ARRAY[]::TEXT[]),
('Campaign', 'campaign_us.mp3', 'verb', 'B1', 'to take part in or lead a campaign, for example to achieve social or political change, or in order to win an election', '', 'The party campaigned vigorously in the north of the country.', '', ARRAY[]::TEXT[]),
('Camping', 'camping_us.mp3', 'noun', 'B1', 'living in a tent, etc. on holiday', '', 'Do you go camping?', '', ARRAY[]::TEXT[]),
('Campus', 'campus_us.mp3', 'noun', 'B1', 'the buildings of a university or college and the land around them', '', 'university/college campuses', '', ARRAY[]::TEXT[]),
('Can', 'can_us.mp3', 'noun', 'B1', 'a metal container in which food and drink is sold', '', 'can of something, a can of beans/beer/soda', '', ARRAY[]::TEXT[]),
('Can', 'can_us.mp3', 'modal verb', 'B1', 'used to say that it is possible for somebody/something to do something, or for something to happen', '', 'I can run fast.', '', ARRAY[]::TEXT[]),
('Canal', 'canal_us.mp3', 'noun', 'B1', 'a long straight passage dug in the ground and filled with water for boats and ships to travel along; a smaller passage used for carrying water to fields, crops, etc.', '', 'the Panama/Suez Canal', '', ARRAY[]::TEXT[]),
('Cancel', 'cancel_us.mp3', 'verb', 'B1', 'to decide that something that has been arranged will not now take place', '', 'All flights have been cancelled because of bad weather.', '', ARRAY[]::TEXT[]),
('Cancer', 'cancer_us.mp3', 'noun', 'B1', 'a serious disease in which growths of cells, also called cancers, form in the body and kill normal body cells. The disease often causes death.', '', 'breast/lung cancer', '', ARRAY[]::TEXT[]),
('Candidate', 'candidate_us.mp3', 'noun', 'B1', 'a person who is trying to be elected or is applying for a job', '', 'a presidential candidate', '', ARRAY[]::TEXT[]),
('Candle', 'candle_us.mp3', 'noun', 'B1', 'a round stick of wax with a piece of string (called a wick) through the middle that is lit to give light as it burns', '', 'a flickering candle', '', ARRAY[]::TEXT[]),
('Cannot', 'cannot_us.mp3', 'modal verb', 'B1', 'the negative of can; can not', '', 'I cannot believe the price of the tickets!', '', ARRAY[]::TEXT[]),
('Canvas', 'canvas_us.mp3', 'noun', 'B1', 'a strong heavy rough material used for making tents, sails, etc. and by artists for painting on', '', 'tents made from heavy canvas', '', ARRAY[]::TEXT[]),
('Cap', 'cap_us.mp3', 'noun', 'B1', 'a type of soft flat hat with a peak (= a hard curved part sticking out in front). Caps are worn especially by men and boys, often as part of a uniform', '', 'to wear a cap.', '', ARRAY[]::TEXT[]),
('Capability', 'capability_us.mp3', 'noun', 'B1', 'the ability or qualities necessary to do something', '', 'Age affects the range of a person''s capabilities.', '', ARRAY[]::TEXT[]),
('Capable', 'capable_us.mp3', 'adjective', 'B1', 'having the ability or qualities necessary for doing something', '', 'capable of something, You are capable of better work than this.', '', ARRAY[]::TEXT[]),
('Capacity', 'capacity_us.mp3', 'noun', 'B1', 'the number of things or people that a container or space can hold', '', 'a fuel tank with a maximum capacity of 50 litres', '', ARRAY[]::TEXT[]),
('Capital', 'capital_us.mp3', 'adjective', 'B1', 'having the form and size used at the beginning of a sentence or a name', '', 'English is written with a capital ‘E’.', '', ARRAY[]::TEXT[]),
('Capital', 'capital_us.mp3', 'noun', 'B1', 'the most important town or city of a country or region, where the government operates from', '', 'Cairo is the capital of Egypt.', '', ARRAY[]::TEXT[]),
('Capitalism', 'capitalism_us.mp3', 'noun', 'B1', 'an economic system in which a country’s businesses and industry are controlled and run for profit by private owners rather than by the government', '', 'the growth of industrial capitalism in the West', '', ARRAY[]::TEXT[]),
('Capitalist', 'capitalist_us.mp3', 'adjective', 'B1', 'based on the principles of capitalism', '', 'a capitalist society/system/economy', '', ARRAY[]::TEXT[]),
('Captain', 'captain_us.mp3', 'noun', 'B1', 'the person in charge of a ship or commercial aircraft', '', 'Captain Cook', '', ARRAY[]::TEXT[]),
('Capture', 'capture_us.mp3', 'noun', 'B1', 'the act of capturing somebody/something or of being captured', '', 'He evaded capture for three days.', '', ARRAY[]::TEXT[]),
('Capture', 'capture_us.mp3', 'verb', 'B1', 'to catch a person or an animal and keep them as a prisoner or shut them in a space that they cannot escape from', '', 'Allied troops captured over 300 enemy soldiers.', '', ARRAY[]::TEXT[]),
('Car', 'car_us.mp3', 'noun', 'B1', 'a road vehicle with an engine and four wheels that can carry a small number of passengers', '', 'Paula got into the car and drove off.', '', ARRAY[]::TEXT[]),
('Carbon', 'carbon_us.mp3', 'noun', 'B1', 'a chemical element. Carbon is found in all living things, existing in a pure state as diamond and graphite.', '', 'carbon fibre', '', ARRAY[]::TEXT[]),
('Card', 'card_us.mp3', 'noun', 'B1', 'thick, stiff paper; a piece of this for writing on', '', 'a piece of card', '', ARRAY[]::TEXT[]),
('Care', 'care_us.mp3', 'noun', 'B1', 'the process of caring for somebody/something and providing what they need for their health or protection', '', 'Some people were badly injured and needed medical care.', '', ARRAY[]::TEXT[]),
('Care', 'care_us.mp3', 'verb', 'B1', 'to feel that something is important and worth worrying about', '', 'I don''t care (= I will not be upset) if I never see him again!', '', ARRAY[]::TEXT[]),
('Career', 'career_us.mp3', 'noun', 'B1', 'the series of jobs that a person has in a particular area of work, usually involving more responsibility as time passes', '', 'a teaching career', '', ARRAY[]::TEXT[]),
('Careful', 'careful_us.mp3', 'adjective', 'B1', 'giving attention or thought to what you are doing so that you avoid hurting yourself, damaging something or doing something wrong', '', 'Be careful!', '', ARRAY[]::TEXT[]),
('Carefully', 'carefully_us.mp3', 'adverb', 'B1', 'with a lot of attention or thought, so that you avoid hurting yourself, damaging something or doing something wrong', '', 'Drive carefully.', '', ARRAY[]::TEXT[]),
('Careless', 'careless_us.mp3', 'adjective', 'B1', 'not giving enough attention and thought to what you are doing, so that you make mistakes', '', 'careless driving', '', ARRAY[]::TEXT[]),
('Cargo', 'cargo_us.mp3', 'noun', 'B1', 'the goods carried in a ship, an aircraft or a motor vehicle', '', 'The tanker began to spill its cargo of oil.', '', ARRAY[]::TEXT[]),
('Carpet', 'carpet_us.mp3', 'noun', 'B1', 'a piece of thick woven material made of wool, etc., used to cover the floor of a room or stairs; the material used for carpets', '', 'He spent the morning laying the new carpet.', '', ARRAY[]::TEXT[]),
('Carriage', 'carriage_us.mp3', 'noun', 'B1', 'a separate section of a train for carrying passengers', '', 'a railway carriage', '', ARRAY[]::TEXT[]),
('Carrot', 'carrot_us.mp3', 'noun', 'B1', 'a long pointed orange root vegetable', '', 'grated carrot', '', ARRAY[]::TEXT[]),
('Carry', 'carry_us.mp3', 'verb', 'B1', 'to support the weight of somebody/something and take them or it from place to place; to take somebody/something from one place to another', '', 'carry somebody/something, He was carrying a large bag.', '', ARRAY[]::TEXT[]),
('Cartoon', 'cartoon_us.mp3', 'noun', 'B1', 'a humorous drawing in a newspaper or magazine, especially one about politics or events in the news', '', 'a political/satirical cartoon', '', ARRAY[]::TEXT[]),
('Carve', 'carve_us.mp3', 'verb', 'B1', 'to make objects, patterns, etc. by cutting away material from a piece of wood or stone, or another hard material', '', 'carve something, a carved doorway', '', ARRAY[]::TEXT[]),
('Case', 'case_us.mp3', 'noun', 'B1', 'a particular situation or a situation of a particular type', '', 'in… cases, In some cases people have had to wait several weeks for an appointment.', '', ARRAY[]::TEXT[]),
('Cash', 'cash_us.mp3', 'noun', 'B1', 'money in the form of coins or notes', '', 'How much cash do you have on you?', '', ARRAY[]::TEXT[]),
('Casino', 'casino_us.mp3', 'noun', 'B1', 'a public building or room where people play gambling games for money', '', 'a new hotel and casino in Las Vegas', '', ARRAY[]::TEXT[]),
('Cast', 'cast_us.mp3', 'noun', 'B1', 'all the people who act in a play or film', '', 'an all-star cast (= including many well-known actors)', '', ARRAY[]::TEXT[]),
('Cast', 'cast_us.mp3', 'verb', 'B1', 'to look, smile, etc. in a particular direction', '', 'cast something + adv./prep., She cast a welcoming smile in his direction.', '', ARRAY[]::TEXT[]),
('Castle', 'castle_us.mp3', 'noun', 'B1', 'a large strong building with thick, high walls and towers, built in the past by kings or queens, or other important people, to defend themselves against attack', '', 'a medieval castle', '', ARRAY[]::TEXT[]),
('Casual', 'casual_us.mp3', 'adjective', 'B1', 'not formal', '', 'casual clothes (= comfortable clothes that you choose to wear in your free time)', '', ARRAY[]::TEXT[]),
('Casualty', 'casualty_us.mp3', 'noun', 'B1', 'a person who is killed or injured in war or in an accident', '', 'Our primary objective is reducing road casualties.', '', ARRAY[]::TEXT[]),
('Cat', 'cat_us.mp3', 'noun', 'B1', 'a small animal with soft fur that people often keep as a pet. Cats catch and kill birds and mice.', '', 'a tin of cat food', '', ARRAY[]::TEXT[]),
('Catalogue', 'catalogue_us.mp3', 'noun', 'B1', 'a complete list of items, for example of things that people can look at or buy', '', 'a mail-order catalogue (= a book showing goods for sale to be sent to people’s homes)', '', ARRAY[]::TEXT[]),
('Catch', 'catch_us.mp3', 'noun', 'B1', 'an act of catching something, for example a ball', '', 'Roger made some brilliant catches at today''s game.', '', ARRAY[]::TEXT[]),
('Catch', 'catch_us.mp3', 'verb', 'B1', 'to stop and hold a moving object or person, especially in your hands', '', 'She managed to catch the keys as they fell.', '', ARRAY[]::TEXT[]),
('Category', 'category_us.mp3', 'noun', 'B1', 'a group of people or things with particular features in common', '', 'These are the nominees from each category.', '', ARRAY[]::TEXT[]),
('Cater', 'cater_us.mp3', 'verb', 'B1', 'to provide food and drinks for a social event', '', '(British English), cater for somebody/something, Most of our work now involves catering for weddings.', '', ARRAY[]::TEXT[]),
('Cattle', 'cattle_us.mp3', 'noun', 'B1', 'cows and bulls that are kept as farm animals for their milk or meat', '', 'a herd of cattle', '', ARRAY[]::TEXT[]),
('Cause', 'cause_us.mp3', 'noun', 'B1', 'the person or thing that makes something happen', '', 'Unemployment is a major cause of poverty.', '', ARRAY[]::TEXT[]),
('Cause', 'cause_us.mp3', 'verb', 'B1', 'to make something happen, especially something bad or unpleasant; to make somebody do something', '', 'cause something, Do they know what caused the fire?', '', ARRAY[]::TEXT[]),
('Caution', 'caution_us.mp3', 'noun', 'B1', 'care that you take in order to avoid danger or mistakes; the fact of not taking any risks', '', 'extreme/great caution', '', ARRAY[]::TEXT[]),
('Cautious', 'cautious_us.mp3', 'adjective', 'B1', 'being careful about what you say or do, especially to avoid danger or mistakes; not taking any risks', '', 'The government has been cautious in its response to the report.', '', ARRAY[]::TEXT[]),
('Cave', 'cave_us.mp3', 'noun', 'B1', 'a large hole in the side of a hill or cliff or under the ground', '', 'the mouth (= the entrance) of the cave', '', ARRAY[]::TEXT[]),
('CD', 'CD_us.mp3', 'noun', 'B1', 'a small disc on which sound or information is recorded. CDs can be played or read on various types of machines, including CD players and computers. (the abbreviation for ‘compact disc’)', '', 'on CD, His albums are available on CD and online.', '', ARRAY[]::TEXT[]),
('Cease', 'cease_us.mp3', 'verb', 'B1', 'to stop happening or existing; to stop something from happening or existing', '', 'Welfare payments cease as soon as an individual starts a job.', '', ARRAY[]::TEXT[]),
('Ceiling', 'ceiling_us.mp3', 'noun', 'B1', 'the top inside surface of a room', '', 'a large room with a high ceiling', '', ARRAY[]::TEXT[]),
('Celebrate', 'celebrate_us.mp3', 'verb', 'B1', 'to show that a day or an event is important by doing something special on it', '', 'Jake''s passed his exams. We''re going out to celebrate.', '', ARRAY[]::TEXT[]),
('Celebration', 'celebration_us.mp3', 'noun', 'B1', 'a special event that people organize in order to celebrate something', '', 'The occasion was the 40th anniversary celebrations of the orchestra.', '', ARRAY[]::TEXT[]),
('Celebrity', 'celebrity_us.mp3', 'noun', 'B1', 'a famous person', '', 'a celebrity chef', '', ARRAY[]::TEXT[]),
('Cell', 'cell_us.mp3', 'noun', 'B1', 'the smallest unit of living matter that can exist on its own. All plants and animals are made up of cells.', '', 'red and white blood cells', '', ARRAY[]::TEXT[]),
('Cemetery', 'cemetery_us.mp3', 'noun', 'B1', 'an area of land used for burying dead people, especially one that is not next to a church', '', 'He was buried in a private cemetery.', '', ARRAY[]::TEXT[]),
('Cent', 'cent_us.mp3', 'noun', 'B1', 'a coin and unit of money worth 1% of the main unit of money in many countries, for example of the US dollar or of the euro', '', 'A one-minute phone call to the UK cost 10 cents.', '', ARRAY[]::TEXT[]),
('Central', 'central_us.mp3', 'adjective', 'B1', 'in the centre of an area or object', '', 'central London', '', ARRAY[]::TEXT[]),
('Centre', 'centre_us.mp3', 'noun', 'B1', 'the middle point or part of something', '', 'He walked to the centre of the circle.', '', ARRAY[]::TEXT[]),
('Centre', 'centre_us.mp3', 'verb', 'B1', 'to be the person or thing around which most activity takes place; to make somebody/something the central person or thing', '', 'centre around/round somebody/something, State occasions always centred around the king.', '', ARRAY[]::TEXT[]),
('Century', 'century_us.mp3', 'noun', 'B1', 'a period of 100 years', '', 'A century ago, Valparaiso was the country''s main port.', '', ARRAY[]::TEXT[]),
('Ceremony', 'ceremony_us.mp3', 'noun', 'B1', 'a public or religious occasion that includes a series of formal or traditional actions', '', 'More than 1 000 people attended the ceremony.', '', ARRAY[]::TEXT[]),
('Certain', 'certain_us.mp3', 'adjective', 'B1', 'strongly believing something; having no doubts', '', 'I think it was him, but I can''t be certain.', '', ARRAY[]::TEXT[]),
('Certainly', 'certainly_us.mp3', 'adverb', 'B1', 'without doubt', '', 'Without treatment, she will almost certainly die.', '', ARRAY[]::TEXT[]),
('Certainty', 'certainty_us.mp3', 'noun', 'B1', 'the state of being certain', '', 'There is no certainty that the president''s removal would end the civil war.', '', ARRAY[]::TEXT[]),
('Certificate', 'certificate_us.mp3', 'noun', 'B1', 'an official document that may be used to prove that the facts it states are true', '', 'a birth/marriage/death certificate', '', ARRAY[]::TEXT[]),
('Chain', 'chain_us.mp3', 'noun', 'B1', 'a series of connected metal rings, used for pulling or fastening things; a length of chain used for a particular purpose', '', 'She wore a heavy gold chain around her neck.', '', ARRAY[]::TEXT[]),
('Chain', 'chain_us.mp3', 'verb', 'B1', 'to fasten something with a chain; to fasten somebody/something to another person or thing with a chain, so that they do not escape or get stolen', '', 'chain somebody/something, The doors were always locked and chained.', '', ARRAY[]::TEXT[]),
('Chair', 'chair_us.mp3', 'noun', 'B1', 'a piece of furniture for one person to sit on, with a back, a seat and four legs', '', 'a table and chairs', '', ARRAY[]::TEXT[]),
('Chair', 'chair_us.mp3', 'verb', 'B1', 'to act as the chairman or chairwoman of a meeting, discussion, etc.', '', 'to chair a committee', '', ARRAY[]::TEXT[]),
('Chairman', 'chairman_us.mp3', 'noun', 'B1', 'the person in charge of a meeting, who tells people when they can speak, etc.', '', 'Sir Herbert took it upon himself to act as chairman.', '', ARRAY[]::TEXT[]),
('Challenge', 'challenge_us.mp3', 'noun', 'B1', 'a new or difficult task that tests somebody’s ability and skill', '', 'a tough/major/significant challenge', '', ARRAY[]::TEXT[]),
('Challenge', 'challenge_us.mp3', 'verb', 'B1', 'to question whether a statement or an action is right, legal, etc.; to refuse to accept something', '', 'challenge something, His legal team immediately sought to challenge the decision.', '', ARRAY[]::TEXT[]),
('Challenging', 'challenging_us.mp3', 'adjective', 'B1', 'difficult in an interesting way that tests your ability', '', 'challenging work/questions/problems', '', ARRAY[]::TEXT[]),
('Chamber', 'chamber_us.mp3', 'noun', 'B1', 'a hall in a public building that is used for formal meetings', '', 'The members left the council chamber.', '', ARRAY[]::TEXT[]),
('Champion', 'champion_us.mp3', 'noun', 'B1', 'a person, team, etc. that has won a competition, especially in a sport', '', 'the world/European/national/Olympic champion', '', ARRAY[]::TEXT[]),
('Championship', 'championship_us.mp3', 'noun', 'B1', 'a competition to find the best player or team in a particular sport', '', 'the National Basketball Association Championship', '', ARRAY[]::TEXT[]),
('Chance', 'chance_us.mp3', 'noun', 'B1', 'a possibility of something happening, especially something that you want', '', 'chance of doing something, She only has a slim chance of passing the exam.', '', ARRAY[]::TEXT[]),
('Change', 'change_us.mp3', 'noun', 'B1', 'the act or result of something becoming different', '', 'change in something, We''re hoping for a change in the weather.', '', ARRAY[]::TEXT[]),
('Change', 'change_us.mp3', 'verb', 'B1', 'to become different', '', 'Rick hasn''t changed. He looks exactly the same as he did at school.', '', ARRAY[]::TEXT[]),
('Channel', 'channel_us.mp3', 'noun', 'B1', 'a television station', '', 'a television/TV channel', '', ARRAY[]::TEXT[]),
('Chaos', 'chaos_us.mp3', 'noun', 'B1', 'a complete lack of order', '', 'economic/political/domestic chaos', '', ARRAY[]::TEXT[]),
('Chapter', 'chapter_us.mp3', 'noun', 'B1', 'a separate section of a book, usually with a number or title', '', 'to read/write a chapter', '', ARRAY[]::TEXT[]),
('Character', 'character_us.mp3', 'noun', 'B1', 'a person or an animal in a book, play or film', '', 'the main character in the film', '', ARRAY[]::TEXT[]),
('Characteristic', 'characteristic_us.mp3', 'adjective', 'B1', 'very typical of something or of somebody’s character', '', 'characteristic of something/somebody, Community support of families is characteristic of many societies.', '', ARRAY[]::TEXT[]),
('Characteristic', 'characteristic_us.mp3', 'noun', 'B1', 'a typical feature or quality that something/somebody has', '', 'There were few similarities in the brothers'' physical characteristics.', '', ARRAY[]::TEXT[]),
('Characterize', 'characterize_us.mp3', 'verb', 'B1', 'to be typical of a person, place or thing', '', 'the rolling hills that characterize this part of England', '', ARRAY[]::TEXT[]),
('Charge', 'charge_us.mp3', 'noun', 'B1', 'the amount of money that somebody asks for goods and services', '', 'admission charges', '', ARRAY[]::TEXT[]),
('Charge', 'charge_us.mp3', 'verb', 'B1', 'to ask an amount of money for goods or a service', '', 'The fees charged by some companies are excessive.', '', ARRAY[]::TEXT[]),
('Charity', 'charity_us.mp3', 'noun', 'B1', 'an organization for helping people in need', '', 'a registered charity', '', ARRAY[]::TEXT[]),
('Charm', 'charm_us.mp3', 'noun', 'B1', 'the power of pleasing or attracting people', '', 'He was a man of great charm.', '', ARRAY[]::TEXT[]),
('Charming', 'charming_us.mp3', 'adjective', 'B1', 'very pleasant or attractive', '', 'The cottage is tiny, but it''s charming.', '', ARRAY[]::TEXT[]),
('Chart', 'chart_us.mp3', 'noun', 'B1', 'a diagram, lists of figures, etc. that shows information', '', 'Some shares have lost two-thirds of their value since being issued (see chart).', '', ARRAY[]::TEXT[]),
('Chart', 'chart_us.mp3', 'verb', 'B1', 'to record or follow the progress or development of somebody/something', '', 'The exhibition charts the history of the palace.', '', ARRAY[]::TEXT[]),
('Charter', 'charter_us.mp3', 'noun', 'B1', 'a written statement describing the rights that a particular group of people should have', '', 'the European Social Charter of workers’ rights', '', ARRAY[]::TEXT[]),
('Chase', 'chase_us.mp3', 'noun', 'B1', 'an act of running or driving after somebody/something in order to catch them or it', '', 'The thieves were caught by police after a short chase.', '', ARRAY[]::TEXT[]),
('Chase', 'chase_us.mp3', 'verb', 'B1', 'to run, drive, etc. after somebody/something in order to catch them or it', '', 'chase somebody/something, My dog likes chasing rabbits.', '', ARRAY[]::TEXT[]),
('Chat', 'chat_us.mp3', 'noun', 'B1', 'a friendly informal conversation', '', 'I just called in for a chat.', '', ARRAY[]::TEXT[]),
('Chat', 'chat_us.mp3', 'verb', 'B1', 'to talk in a friendly, informal way to somebody', '', 'I''m sorry I can''t stop to chat.', '', ARRAY[]::TEXT[]),
('Cheap', 'cheap_us.mp3', 'adjective', 'B1', 'costing little money or less money than you expected', '', 'cheap imports/flights', '', ARRAY[]::TEXT[]),
('Cheap', 'cheap_us.mp3', 'adverb', 'B1', 'for a low price', '', 'I got this dress cheap in a sale.', '', ARRAY[]::TEXT[]),
('Cheat', 'cheat_us.mp3', 'noun', 'B1', 'a person who cheats, especially in a game', '', 'You little cheat!', '', ARRAY[]::TEXT[]),
('Cheat', 'cheat_us.mp3', 'verb', 'B1', 'to trick somebody or make them believe something that is not true', '', 'cheat somebody/something, She is accused of attempting to cheat the taxman.', '', ARRAY[]::TEXT[]),
('Check', 'check_us.mp3', 'noun', 'B1', 'an act of making sure that something is safe, correct or in good condition by examining it', '', 'Could you give the tyres a check?', '', ARRAY[]::TEXT[]),
('Check', 'check_us.mp3', 'verb', 'B1', 'to examine something to see if it is correct, safe or acceptable', '', 'check something, She gave me the minutes of the meeting to read and check.', '', ARRAY[]::TEXT[]),
('Cheek', 'cheek_us.mp3', 'noun', 'B1', 'either side of the face below the eyes', '', 'chubby/rosy/pink cheeks', '', ARRAY[]::TEXT[]),
('Cheer', 'cheer_us.mp3', 'noun', 'B1', 'a shout of joy, support or praise', '', 'A great cheer went up from the crowd.', '', ARRAY[]::TEXT[]),
('Cheer', 'cheer_us.mp3', 'verb', 'B1', 'to shout loudly, in order to show support or praise for somebody, or to encourage them', '', 'We all cheered as the team came on to the field.', '', ARRAY[]::TEXT[]),
('Cheerful', 'cheerful_us.mp3', 'adjective', 'B1', 'happy, and showing it by the way that you behave', '', 'You''re not your usual cheerful self today.', '', ARRAY[]::TEXT[]),
('Cheese', 'cheese_us.mp3', 'noun', 'B1', 'a type of food made from milk that can be either soft or hard and is usually white or yellow in colour; a particular type of this food', '', 'Cheddar cheese', '', ARRAY[]::TEXT[]),
('Chef', 'chef_us.mp3', 'noun', 'B1', 'a person whose job is to cook, especially the most senior person in a restaurant, hotel, etc.', '', 'a new book by celebrity chef Jamie Oliver', '', ARRAY[]::TEXT[]),
('Chemical', 'chemical_us.mp3', 'adjective', 'B1', 'connected with chemistry', '', 'changes in the chemical composition of the atmosphere', '', ARRAY[]::TEXT[]),
('Chemical', 'chemical_us.mp3', 'noun', 'B1', 'a substance obtained by or used in a chemical process', '', 'toxic chemicals', '', ARRAY[]::TEXT[]),
('Chemistry', 'chemistry_us.mp3', 'noun', 'B1', 'the scientific study of the structure of substances, how they react when combined or in contact with one another, and how they behave under different conditions', '', 'a degree in chemistry', '', ARRAY[]::TEXT[]),
('Chest', 'chest_us.mp3', 'noun', 'B1', 'the top part of the front of the body, between the neck and the stomach', '', 'chest pains', '', ARRAY[]::TEXT[]),
('Chicken', 'chicken_us.mp3', 'noun', 'B1', 'a large bird that is often kept for its eggs or meat', '', 'They keep chickens in the back yard.', '', ARRAY[]::TEXT[]),
('Chief', 'chief_us.mp3', 'adjective', 'B1', 'most important', '', 'the chief cause/problem/reason', '', ARRAY[]::TEXT[]),
('Chief', 'chief_us.mp3', 'noun', 'B1', 'a person with a high rank or the highest rank in a company or an organization', '', 'army/police chiefs', '', ARRAY[]::TEXT[]),
('Child', 'child_us.mp3', 'noun', 'B1', 'a young human who is not yet an adult', '', 'a child of 3/a 3-year-old child', '', ARRAY[]::TEXT[]),
('Childhood', 'childhood_us.mp3', 'noun', 'B1', 'the period of somebody’s life when they are a child', '', 'childhood, adolescence, and adulthood', '', ARRAY[]::TEXT[]),
('Chip', 'chip_us.mp3', 'noun', 'B1', 'a long thin piece of potato fried in oil or fat', '', 'He was eating a burger and chips.', '', ARRAY[]::TEXT[]),
('Chocolate', 'chocolate_us.mp3', 'noun', 'B1', 'a hard brown sweet food made from cocoa beans, used in cooking to add taste to cakes, etc. or eaten as a sweet', '', 'a chocolate bar', '', ARRAY[]::TEXT[]),
('Choice', 'choice_us.mp3', 'noun', 'B1', 'an act of choosing between two or more possibilities; something that you can choose', '', 'We are faced with a difficult choice.', '', ARRAY[]::TEXT[]),
('Choir', 'choir_us.mp3', 'noun', 'B1', 'a group of people who sing together, for example in church services or public performances', '', 'She sings in the school choir.', '', ARRAY[]::TEXT[]),
('Choose', 'choose_us.mp3', 'verb', 'B1', 'to decide which thing or person you want out of the ones that are available', '', 'You choose—I can''t decide.', '', ARRAY[]::TEXT[]),
('Chop', 'chop_us.mp3', 'verb', 'B1', 'to cut something into pieces with a sharp tool such as a knife', '', 'chop something, He was chopping logs for firewood.', '', ARRAY[]::TEXT[]),
('Chronic', 'chronic_us.mp3', 'adjective', 'B1', 'lasting for a long time; difficult to cure', '', 'chronic bronchitis/arthritis/asthma', '', ARRAY[]::TEXT[]),
('Chunk', 'chunk_us.mp3', 'noun', 'B1', 'a thick, solid piece that has been cut or broken off something', '', 'a chunk of cheese/masonry', '', ARRAY[]::TEXT[]),
('Church', 'church_us.mp3', 'noun', 'B1', 'a building where Christians go to attend services, pray, etc.', '', 'The procession moved into the church.', '', ARRAY[]::TEXT[]),
('Cigarette', 'cigarette_us.mp3', 'noun', 'B1', 'a thin tube of paper filled with tobacco, for smoking', '', 'to smoke/have a cigarette', '', ARRAY[]::TEXT[]),
('Cinema', 'cinema_us.mp3', 'noun', 'B1', 'a building in which films are shown', '', 'the local cinema', '', ARRAY[]::TEXT[]),
('Circle', 'circle_us.mp3', 'noun', 'B1', 'a completely round flat shape', '', 'the centre/circumference/radius/diameter of a circle', '', ARRAY[]::TEXT[]),
('Circle', 'circle_us.mp3', 'verb', 'B1', 'to draw a circle around something', '', 'circle something, Luke circled a date on the kitchen calendar.', '', ARRAY[]::TEXT[]),
('Circuit', 'circuit_us.mp3', 'noun', 'B1', 'a line, route or journey around a place', '', 'The race ended with eight laps of a city centre circuit.', '', ARRAY[]::TEXT[]),
('Circulate', 'circulate_us.mp3', 'verb', 'B1', 'when a liquid, gas or air circulates or is circulated, it moves continuously around a place or system', '', 'The condition prevents the blood from circulating freely.', '', ARRAY[]::TEXT[]),
('Circulation', 'circulation_us.mp3', 'noun', 'B1', 'the movement of blood around the body', '', 'Regular exercise will improve blood circulation.', '', ARRAY[]::TEXT[]),
('Circumstance', 'circumstance_us.mp3', 'noun', 'B1', 'the conditions and facts that are connected with and affect a situation, an event or an action', '', 'Police said there were no suspicious circumstances surrounding the boy''s death.', '', ARRAY[]::TEXT[]),
('Cite', 'cite_us.mp3', 'verb', 'B1', 'to mention something as a reason or an example, or in order to support what you are saying', '', 'cite something, She cited examples of companies the city has helped relocate or expand.', '', ARRAY[]::TEXT[]),
('Citizen', 'citizen_us.mp3', 'noun', 'B1', 'a person who has the legal right to belong to a particular country', '', 'The defeat of the president did not change the lives of ordinary citizens for the better.', '', ARRAY[]::TEXT[]),
('Citizenship', 'citizenship_us.mp3', 'noun', 'B1', 'the legal right to belong to a particular country', '', 'They were granted full French citizenship.', '', ARRAY[]::TEXT[]),
('City', 'city_us.mp3', 'noun', 'B1', 'a large and important town', '', 'Parking is difficult in the city centre.', '', ARRAY[]::TEXT[]),
('Civic', 'civic_us.mp3', 'adjective', 'B1', 'officially connected with a town or city', '', 'civic buildings/leaders', '', ARRAY[]::TEXT[]),
('Civil', 'civil_us.mp3', 'adjective', 'B1', 'connected with the people who live in a country', '', 'civil unrest (= that is caused by groups of people within a country)', '', ARRAY[]::TEXT[]),
('Civilian', 'civilian_us.mp3', 'adjective', 'B1', 'connected with people who are not members of the armed forces or the police', '', 'He left the army and returned to civilian life.', '', ARRAY[]::TEXT[]),
('Civilian', 'civilian_us.mp3', 'noun', 'B1', 'a person who is not a member of the armed forces or the police', '', 'Two soldiers and one civilian were killed in the explosion.', '', ARRAY[]::TEXT[]),
('Civilization', 'civilization_us.mp3', 'noun', 'B1', 'a state of human society that is very developed and organized', '', 'the technology of modern civilization', '', ARRAY[]::TEXT[]),
('Claim', 'claim_us.mp3', 'noun', 'B1', 'a statement that something is true although it has not been proved and other people may not agree with or believe it', '', 'claim about somebody/something, The company had made false claims about its products.', '', ARRAY[]::TEXT[]),
('Claim', 'claim_us.mp3', 'verb', 'B1', 'to say that something is true although it has not been proved and other people may not believe it', '', 'claim (that)…, He claims (that) he was not given a fair hearing.', '', ARRAY[]::TEXT[]),
('Clarify', 'clarify_us.mp3', 'verb', 'B1', 'to make something clearer or easier to understand', '', 'clarify something, to clarify a situation/problem/issue', '', ARRAY[]::TEXT[]),
('Clarity', 'clarity_us.mp3', 'noun', 'B1', 'the quality of being expressed clearly', '', 'a lack of clarity in the law', '', ARRAY[]::TEXT[]),
('Clash', 'clash_us.mp3', 'noun', 'B1', 'a short fight between two groups of people', '', 'Clashes broke out between police and demonstrators.', '', ARRAY[]::TEXT[]),
('Class', 'class_us.mp3', 'noun', 'B1', 'a group of students who are taught together', '', 'in the/your class, We were in the same class at school.', '', ARRAY[]::TEXT[]),
('Classic', 'classic_us.mp3', 'adjective', 'B1', 'accepted or deserving to be accepted as one of the best or most important of its kind', '', 'a classic film/story/car/game', '', ARRAY[]::TEXT[]),
('Classic', 'classic_us.mp3', 'noun', 'B1', 'a book, film or song which is well known and considered to be of very high quality, setting standards for other books, etc.', '', 'The film is now a cult classic.', '', ARRAY[]::TEXT[]),
('Classical', 'classical_us.mp3', 'adjective', 'B1', 'relating to classical music', '', 'a classical composer/musician/pianist', '', ARRAY[]::TEXT[]),
('Classification', 'classification_us.mp3', 'noun', 'B1', 'the act or process of putting people or things into a group or class (= of classifying them)', '', 'a style of music that defies classification (= is like no other)', '', ARRAY[]::TEXT[]),
('Classify', 'classify_us.mp3', 'verb', 'B1', 'to arrange something in groups according to features that they have in common', '', 'The books in the library are classified according to subject.', '', ARRAY[]::TEXT[]),
('Classroom', 'classroom_us.mp3', 'noun', 'B1', 'a room where a class of children or students is taught', '', 'classroom activities', '', ARRAY[]::TEXT[]),
('Clause', 'clause_us.mp3', 'noun', 'B1', 'a group of words that includes a subject and a verb, and forms a sentence or part of a sentence', '', 'in a clause, There are languages that require the subject to come before the object in a clause.', '', ARRAY[]::TEXT[]),
('Clean', 'clean_us.mp3', 'adjective', 'B1', 'not dirty', '', 'Are your hands clean?', '', ARRAY[]::TEXT[]),
('Clean', 'clean_us.mp3', 'verb', 'B1', 'to remove the dirt or dust from something', '', 'I spent all day cooking and cleaning.', '', ARRAY[]::TEXT[]),
('Clear', 'clear_us.mp3', 'adjective', 'B1', 'easy to understand and not confusing', '', 'She gave me clear and precise directions.', '', ARRAY[]::TEXT[]),
('Clear', 'clear_us.mp3', 'verb', 'B1', 'to remove things that are not wanted or needed from something', '', 'clear something, The settlers cleared the land and planted crops.', '', ARRAY[]::TEXT[]),
('Clearly', 'clearly_us.mp3', 'adverb', 'B1', 'in a way that is easy to see or hear', '', 'Please speak clearly after the tone.', '', ARRAY[]::TEXT[]),
('Clerk', 'clerk_us.mp3', 'noun', 'B1', 'a person whose job is to serve customers in a shop', '', 'The clerk at the counter gave me too little change.', '', ARRAY[]::TEXT[]),
('Clever', 'clever_us.mp3', 'adjective', 'B1', 'quick at learning and understanding things', '', 'a clever child', '', ARRAY[]::TEXT[]),
('Click', 'click_us.mp3', 'noun', 'B1', 'the act of pressing the button on a computer mouse or touchpad', '', 'a mouse click', '', ARRAY[]::TEXT[]),
('Click', 'click_us.mp3', 'verb', 'B1', 'to choose a particular function or item on a computer screen, etc., by pressing one of the buttons on a mouse or touchpad', '', 'Click here to add your opinion to the survey.', '', ARRAY[]::TEXT[]),
('Client', 'client_us.mp3', 'noun', 'B1', 'a person who uses the services or advice of a professional person or organization', '', 'She''s a well-known lawyer with many famous clients.', '', ARRAY[]::TEXT[]),
('Cliff', 'cliff_us.mp3', 'noun', 'B1', 'a high area of rock with a very steep side, often at the edge of the sea or ocean', '', 'the cliff edge/top', '', ARRAY[]::TEXT[]),
('Climate', 'climate_us.mp3', 'noun', 'B1', 'the regular pattern of weather conditions of a particular place', '', 'a tropical/warm/mild/temperate/cold climate', '', ARRAY[]::TEXT[]),
('Climb', 'climb_us.mp3', 'noun', 'B1', 'an act of climbing up a mountain, rock or large number of steps; a period of time spent climbing', '', 'an exhausting climb', '', ARRAY[]::TEXT[]),
('Climb', 'climb_us.mp3', 'verb', 'B1', 'to go up something towards the top', '', 'climb (up) something, to climb a mountain/tree', '', ARRAY[]::TEXT[]),
('Cling', 'cling_us.mp3', 'verb', 'B1', 'to hold on tightly to somebody/something', '', 'cling to somebody/something, survivors clinging to a raft', '', ARRAY[]::TEXT[]),
('Clinic', 'clinic_us.mp3', 'noun', 'B1', 'a building or part of a hospital where people can go for special medical treatment or advice', '', 'Your local family planning clinic can give you advice about birth control.', '', ARRAY[]::TEXT[]),
('Clinical', 'clinical_us.mp3', 'adjective', 'B1', 'relating to the examination and treatment of patients and their illnesses', '', 'clinical research (= done on patients, not just considering theory)', '', ARRAY[]::TEXT[]),
('Clip', 'clip_us.mp3', 'noun', 'B1', 'a short part of a film that is shown separately', '', 'Here is a clip from her latest movie.', '', ARRAY[]::TEXT[]),
('Clock', 'clock_us.mp3', 'noun', 'B1', 'an instrument for measuring and showing time, in a room, on the wall of a building or on a computer screen (not worn or carried like a watch)', '', 'The clock struck twelve/midnight.', '', ARRAY[]::TEXT[]),
('Close', 'close_us.mp3', 'adjective', 'B1', 'near in space or time', '', 'I had no idea the beach was so close.', '', ARRAY[]::TEXT[]),
('Close', 'close_us.mp3', 'adverb', 'B1', 'near; not far away', '', '+ adv./prep., They sat close together.', '', ARRAY[]::TEXT[]),
('Close', 'close_us.mp3', 'noun', 'B1', 'the end of a period of time or an activity', '', 'at the close of the seventeenth century', '', ARRAY[]::TEXT[]),
('Close', 'close_us.mp3', 'verb', 'B1', 'to put something into a position so that it covers an opening; to get into this position', '', 'He closed the door firmly.', '', ARRAY[]::TEXT[]),
('Closed', 'closed_us.mp3', 'adjective', 'B1', 'shut', '', 'Keep the door closed.', '', ARRAY[]::TEXT[]),
('Closely', 'closely_us.mp3', 'adverb', 'B1', 'near in space or time', '', 'He walked into the room, closely followed by the rest of the family.', '', ARRAY[]::TEXT[]),
('Closure', 'closure_us.mp3', 'noun', 'B1', 'the situation when a factory, school, hospital, etc. shuts permanently', '', 'factory closures', '', ARRAY[]::TEXT[]),
('Cloth', 'cloth_us.mp3', 'noun', 'B1', 'material made by weaving or knitting cotton, wool, silk, etc.', '', 'woollen/cotton/linen cloth', '', ARRAY[]::TEXT[]),
('Clothes', 'clothes_us.mp3', 'noun', 'B1', 'the things that you wear, such as trousers, dresses and jackets', '', 'I bought some new clothes for the trip.', '', ARRAY[]::TEXT[]),
('Clothing', 'clothing_us.mp3', 'noun', 'B1', 'clothes, especially a particular type of clothes', '', 'Workers at the factory wear protective clothing.', '', ARRAY[]::TEXT[]),
('Cloud', 'cloud_us.mp3', 'noun', 'B1', 'a grey or white mass that floats in the sky, made of very small drops of water', '', 'Dark clouds were gathering in the west.', '', ARRAY[]::TEXT[]),
('Club', 'club_us.mp3', 'noun', 'B1', 'an organization for people who share an interest or do a sport or activity together', '', 'a golf/tennis/chess/film club', '', ARRAY[]::TEXT[]),
('Clue', 'clue_us.mp3', 'noun', 'B1', 'an object, a piece of evidence or some information that helps the police solve a crime', '', 'The burglar left no clues.', '', ARRAY[]::TEXT[]),
('Cluster', 'cluster_us.mp3', 'noun', 'B1', 'a group of things of the same type that grow or appear close together', '', 'The telescope is focused on a dense cluster of stars at the edge of the galaxy.', '', ARRAY[]::TEXT[]),
('Coach', 'coach_us.mp3', 'noun', 'B1', 'a person who trains a person or team in sport', '', 'the head/assistant coach', '', ARRAY[]::TEXT[]),
('Coach', 'coach_us.mp3', 'verb', 'B1', 'to train somebody to play a sport, to do a job better, or to improve a skill', '', 'coach somebody, He has coached the team for five years.', '', ARRAY[]::TEXT[]),
('Coal', 'coal_us.mp3', 'noun', 'B1', 'a hard black mineral that is found below the ground and burnt to produce heat', '', 'I put more coal on the fire.', '', ARRAY[]::TEXT[]),
('Coalition', 'coalition_us.mp3', 'noun', 'B1', 'a government formed by two or more political parties working together', '', 'The two parties have formed a coalition.', '', ARRAY[]::TEXT[]),
('Coast', 'coast_us.mp3', 'noun', 'B1', 'the land next to or near to the sea or ocean', '', 'a trip to the coast', '', ARRAY[]::TEXT[]),
('Coastal', 'coastal_us.mp3', 'adjective', 'B1', 'of or near a coast', '', 'coastal waters/resorts/scenery', '', ARRAY[]::TEXT[]),
('Coat', 'coat_us.mp3', 'noun', 'B1', 'a piece of outdoor clothing that is worn over other clothes to keep warm or dry. Coats have sleeves (= parts covering the arms) and may be long or short.', '', 'to wear a coat', '', ARRAY[]::TEXT[]),
('Cocktail', 'cocktail_us.mp3', 'noun', 'B1', 'a drink usually made from a mixture of one or more spirits (= strong alcoholic drinks) and fruit juice. It can also be made without alcohol.', '', 'a cocktail bar/cabinet/lounge/shaker', '', ARRAY[]::TEXT[]),
('Code', 'code_us.mp3', 'noun', 'B1', 'a system of words, letters, numbers or symbols that represent a message or record information secretly or in a shorter form', '', 'to break/crack a code (= to understand and read the message)', '', ARRAY[]::TEXT[]),
('Coffee', 'coffee_us.mp3', 'noun', 'B1', 'the roasted seeds (called coffee beans) of a tropical bush; a powder made from them', '', 'ground/real/instant coffee', '', ARRAY[]::TEXT[]),
('Cognitive', 'cognitive_us.mp3', 'adjective', 'B1', 'connected with mental processes of understanding', '', 'a child’s cognitive development', '', ARRAY[]::TEXT[]),
('Coin', 'coin_us.mp3', 'noun', 'B1', 'a small flat piece of metal used as money', '', 'gold coins', '', ARRAY[]::TEXT[]),
('Coincide', 'coincide_us.mp3', 'verb', 'B1', 'to take place at the same time', '', 'It''s a pity our trips to New York don''t coincide.', '', ARRAY[]::TEXT[]),
('Coincidence', 'coincidence_us.mp3', 'noun', 'B1', 'the fact of two things happening at the same time by chance, in a surprising way', '', 'a strange/an extraordinary/a remarkable coincidence', '', ARRAY[]::TEXT[]),
('Cold', 'cold_us.mp3', 'adjective', 'B1', 'having a lower than usual temperature; having a temperature lower than the human body', '', 'I''m cold. Turn the heating up.', '', ARRAY[]::TEXT[]),
('Cold', 'cold_us.mp3', 'noun', 'B1', 'a common illness that affects the nose and/or throat, making you cough, sneeze, etc.', '', 'I''ve got a cold.', '', ARRAY[]::TEXT[]),
('Collaborate', 'collaborate_us.mp3', 'verb', 'B1', 'to work together with somebody in order to produce or achieve something', '', 'Researchers around the world are collaborating to develop a new vaccine.', '', ARRAY[]::TEXT[]),
('Collaboration', 'collaboration_us.mp3', 'noun', 'B1', 'the act of working with another person or group of people to create or produce something', '', 'It was a collaboration that produced extremely useful results.', '', ARRAY[]::TEXT[]),
('Collapse', 'collapse_us.mp3', 'noun', 'B1', 'a sudden failure of something, such as an institution, a business or a course of action', '', 'the collapse of the Soviet Union', '', ARRAY[]::TEXT[]),
('Collapse', 'collapse_us.mp3', 'verb', 'B1', 'to fall down or fall in suddenly, often after breaking apart', '', 'The roof collapsed under the weight of snow.', '', ARRAY[]::TEXT[]),
('Colleague', 'colleague_us.mp3', 'noun', 'B1', 'a person that you work with, especially in a profession or a business', '', 'work/senior/male colleagues', '', ARRAY[]::TEXT[]),
('Collect', 'collect_us.mp3', 'verb', 'B1', 'to bring things together from different people or places', '', 'collect something, to collect data/evidence/information', '', ARRAY[]::TEXT[]),
('Collection', 'collection_us.mp3', 'noun', 'B1', 'a group of objects, often of the same sort, that have been collected', '', 'He wanted to share his vast art collection with the world.', '', ARRAY[]::TEXT[]),
('Collective', 'collective_us.mp3', 'adjective', 'B1', 'done or shared by all members of a group of people; involving a whole group or society', '', 'collective leadership/decision-making/responsibility', '', ARRAY[]::TEXT[]),
('Collector', 'collector_us.mp3', 'noun', 'B1', 'a person who collects things, either as a hobby or as a job', '', 'a stamp collector', '', ARRAY[]::TEXT[]),
('College', 'college_us.mp3', 'noun', 'B1', '(in the UK) a place where students go to study or to receive training after they have left school', '', 'a secretarial college', '', ARRAY[]::TEXT[]),
('Collision', 'collision_us.mp3', 'noun', 'B1', 'an accident in which two vehicles or people crash into each other', '', 'collision between A and B, a collision between two trains', '', ARRAY[]::TEXT[]),
('Colonial', 'colonial_us.mp3', 'adjective', 'B1', 'connected with or belonging to a country that controls another country', '', 'a colonial power', '', ARRAY[]::TEXT[]),
('Colony', 'colony_us.mp3', 'noun', 'B1', 'a country or an area that is governed by people from another, more powerful, country', '', 'former British colonies', '', ARRAY[]::TEXT[]),
('Colour', 'colour_us.mp3', 'noun', 'B1', 'the appearance that things have that results from the way in which they reflect light. Red, orange and green are colours.', '', 'What''s your favourite colour?', '', ARRAY[]::TEXT[]),
('Coloured', 'coloured_us.mp3', 'adjective', 'B1', 'having a particular colour or different colours', '', 'brightly coloured balloons', '', ARRAY[]::TEXT[]),
('Colourful', 'colourful_us.mp3', 'adjective', 'B1', 'full of bright colours or having a lot of different colours', '', 'colourful shop windows', '', ARRAY[]::TEXT[]),
('Column', 'column_us.mp3', 'noun', 'B1', 'one of the straight sections from top to bottom into which text on a page or screen is divided', '', 'a dictionary with two columns per page', '', ARRAY[]::TEXT[]),
('Columnist', 'columnist_us.mp3', 'noun', 'B1', 'a journalist who writes regular articles for a newspaper or magazine', '', 'a newspaper columnist', '', ARRAY[]::TEXT[]),
('Combat', 'combat_us.mp3', 'noun', 'B1', 'fighting or a fight, especially during a time of war', '', 'in combat, He was killed in combat.', '', ARRAY[]::TEXT[]),
('Combat', 'combat_us.mp3', 'verb', 'B1', 'to stop something unpleasant or harmful from happening or from getting worse', '', 'measures to combat crime/inflation/unemployment/disease', '', ARRAY[]::TEXT[]),
('Combination', 'combination_us.mp3', 'noun', 'B1', 'two or more things joined or mixed together to form a single unit', '', 'combination of something, The tragedy was due to a combination of factors.', '', ARRAY[]::TEXT[]),
('Combine', 'combine_us.mp3', 'verb', 'B1', 'to come together to form a single thing or group; to join two or more things or groups together to form a single one', '', 'combine to do something, Hydrogen and oxygen combine to form water.', '', ARRAY[]::TEXT[]),
('Come', 'come_us.mp3', 'verb', 'B1', 'to move to or towards a person or place', '', '+ adv./prep., He left and said he was never coming back.', '', ARRAY[]::TEXT[]),
('Comedy', 'comedy_us.mp3', 'noun', 'B1', 'a play, film or TV show that is intended to be funny, usually with a happy ending; plays, films and TV shows of this type', '', 'a romantic comedy', '', ARRAY[]::TEXT[]),
('Comfort', 'comfort_us.mp3', 'noun', 'B1', 'the state of being physically relaxed and free from pain; the state of having a pleasant life, with everything that you need', '', 'The hotel offers a high standard of comfort and service.', '', ARRAY[]::TEXT[]),
('Comfort', 'comfort_us.mp3', 'verb', 'B1', 'to make somebody who is worried or unhappy feel better by being kind and showing sympathy to them', '', 'comfort somebody, The victim''s widow was today being comforted by family and friends.', '', ARRAY[]::TEXT[]),
('Comfortable', 'comfortable_us.mp3', 'adjective', 'B1', 'making you feel physically relaxed; pleasant to wear, sit on, etc.', '', 'It''s such a comfortable bed.', '', ARRAY[]::TEXT[]),
('Comic', 'comic_us.mp3', 'adjective', 'B1', 'humorous and making you laugh', '', 'a comic monologue/story', '', ARRAY[]::TEXT[]),
('Comic', 'comic_us.mp3', 'noun', 'B1', 'a magazine, usually for children, that tells stories through pictures', '', 'a comic book superhero', '', ARRAY[]::TEXT[]),
('Command', 'command_us.mp3', 'noun', 'B1', 'an order given to a person or an animal', '', 'Begin when I give the command.', '', ARRAY[]::TEXT[]),
('Command', 'command_us.mp3', 'verb', 'B1', 'to tell somebody to do something', '', 'command somebody to do something, He commanded his men to retreat.', '', ARRAY[]::TEXT[]),
('Commander', 'commander_us.mp3', 'noun', 'B1', 'a person who is in charge of something, especially an officer in charge of a particular group of soldiers or a military operation', '', 'military/allied/field/flight commanders', '', ARRAY[]::TEXT[]),
('Commence', 'commence_us.mp3', 'verb', 'B1', 'to begin to happen; to begin something', '', 'The meeting is scheduled to commence at noon.', '', ARRAY[]::TEXT[]),
('Comment', 'comment_us.mp3', 'noun', 'B1', 'something that you say or write that gives an opinion on or explains somebody/something', '', 'comment on something, She made helpful comments on my work.', '', ARRAY[]::TEXT[]),
('Comment', 'comment_us.mp3', 'verb', 'B1', 'to express an opinion about something', '', 'He refused to comment until after the trial.', '', ARRAY[]::TEXT[]),
('Commentary', 'commentary_us.mp3', 'noun', 'B1', 'a spoken description of an event that is given while it is happening, especially on the radio or television', '', 'a sports commentary', '', ARRAY[]::TEXT[]),
('Commentator', 'commentator_us.mp3', 'noun', 'B1', 'a person who describes an event while it is happening, especially on television or radio', '', 'a television/sports commentator', '', ARRAY[]::TEXT[]),
('Commerce', 'commerce_us.mp3', 'noun', 'B1', 'trade, especially between countries; the buying and selling of goods and services', '', 'Leaders of industry and commerce met at the summit in Paris.', '', ARRAY[]::TEXT[]),
('Commercial', 'commercial_us.mp3', 'adjective', 'B1', 'connected with the buying and selling of goods and services', '', 'residential and commercial properties', '', ARRAY[]::TEXT[]),
('Commercial', 'commercial_us.mp3', 'noun', 'B1', 'an advertisement on television, on the radio or on a website', '', 'a TV/television commercial', '', ARRAY[]::TEXT[]),
('Commission', 'commission_us.mp3', 'noun', 'B1', 'an official group of people who have been given responsibility to control something, or to find out about something, usually for the government', '', 'The commission is expected to report its findings next month.', '', ARRAY[]::TEXT[]),
('Commission', 'commission_us.mp3', 'verb', 'B1', 'to officially ask somebody to write, make or create something or to do a task for you', '', 'commission somebody to do something, She has been commissioned to write a new national anthem.', '', ARRAY[]::TEXT[]),
('Commissioner', 'commissioner_us.mp3', 'noun', 'B1', 'a member of a commission (= an official group of people who are responsible for controlling something or finding out about something)', '', 'the Church Commissioners (= the group of people responsible for controlling the financial affairs of the Church of England)', '', ARRAY[]::TEXT[]),
('Commit', 'commit_us.mp3', 'verb', 'B1', 'to do something wrong or illegal', '', 'to commit a crime/an offence', '', ARRAY[]::TEXT[]),
('Commitment', 'commitment_us.mp3', 'noun', 'B1', 'a promise to do something or to behave in a particular way; a promise to support somebody/something; the fact of committing yourself', '', 'I''m not ready to make a long-term commitment.', '', ARRAY[]::TEXT[]),
('Committee', 'committee_us.mp3', 'noun', 'B1', 'a group of people who are chosen, usually by a larger group, to make decisions or to deal with a particular subject', '', 'an executive/advisory/organizing committee', '', ARRAY[]::TEXT[]),
('Commodity', 'commodity_us.mp3', 'noun', 'B1', 'a product or a raw material that can be bought and sold', '', 'rice, flour and other basic commodities', '', ARRAY[]::TEXT[]),
('Common', 'common_us.mp3', 'adjective', 'B1', 'happening often; existing in large numbers or in many places', '', 'a common problem/occurrence/practice', '', ARRAY[]::TEXT[]),
('Commonly', 'commonly_us.mp3', 'adverb', 'B1', 'usually; very often; by most people', '', 'Christopher is commonly known as Kit.', '', ARRAY[]::TEXT[]),
('Communicate', 'communicate_us.mp3', 'verb', 'B1', 'to share or exchange information, news, ideas, feelings, etc.', '', 'We only communicate by email.', '', ARRAY[]::TEXT[]),
('Communication', 'communication_us.mp3', 'noun', 'B1', 'the activity or process of expressing ideas and feelings or of giving people information', '', 'communication between A and B, Good communication between team leaders and members is essential.', '', ARRAY[]::TEXT[]),
('Communist', 'communist_us.mp3', 'adjective', 'B1', 'connected with communism', '', 'communist ideology', '', ARRAY[]::TEXT[]),
('Community', 'community_us.mp3', 'noun', 'B1', 'all the people who live in a particular area, country, etc. when talked about as a group', '', 'The local community supported us from the start.', '', ARRAY[]::TEXT[]),
('Companion', 'companion_us.mp3', 'noun', 'B1', 'a person or an animal that travels with you or spends a lot of time with you', '', 'travelling companions', '', ARRAY[]::TEXT[]),
('Company', 'company_us.mp3', 'noun', 'B1', 'a business organization that makes money by producing or selling goods or services', '', 'insurance/oil/tech/technology/pharmaceutical companies', '', ARRAY[]::TEXT[]),
('Comparable', 'comparable_us.mp3', 'adjective', 'B1', 'similar to somebody/something else and able to be compared', '', 'A comparable house in the south of the city would cost twice as much.', '', ARRAY[]::TEXT[]),
('Comparative', 'comparative_us.mp3', 'adjective', 'B1', 'measured or judged by how similar or different it is to something else', '', 'Then he was living in comparative comfort (= compared with others or with his own life at a previous time).', '', ARRAY[]::TEXT[]),
('Compare', 'compare_us.mp3', 'verb', 'B1', 'to examine people or things to see how they are similar and how they are different', '', 'compare A and B, It is interesting to compare their situation and ours.', '', ARRAY[]::TEXT[]),
('Comparison', 'comparison_us.mp3', 'noun', 'B1', 'the process of comparing two or more people or things', '', 'For Durkheim, comparison was the most important method of analysis in sociology.', '', ARRAY[]::TEXT[]),
('Compassion', 'compassion_us.mp3', 'noun', 'B1', 'a strong feeling of sympathy for people or animals who are suffering and a desire to help them', '', 'to feel/show compassion', '', ARRAY[]::TEXT[]),
('Compel', 'compel_us.mp3', 'verb', 'B1', 'to force somebody to do something; to make something necessary', '', 'compel somebody to do something, The law can compel fathers to make regular payments for their children.', '', ARRAY[]::TEXT[]),
('Compelling', 'compelling_us.mp3', 'adjective', 'B1', 'that makes you pay attention to it because it is so interesting and exciting', '', 'Her latest book makes compelling reading.', '', ARRAY[]::TEXT[]),
('Compensate', 'compensate_us.mp3', 'verb', 'B1', 'to provide something good to balance or reduce the bad effects of damage, loss, etc.', '', 'Nothing can compensate for the loss of a loved one.', '', ARRAY[]::TEXT[]),
('Compensation', 'compensation_us.mp3', 'noun', 'B1', 'something, especially money, that somebody gives you because they have hurt you, or damaged something that you own; the act of giving this to somebody', '', 'to claim/award/receive compensation', '', ARRAY[]::TEXT[]),
('Compete', 'compete_us.mp3', 'verb', 'B1', 'to take part in a contest or game', '', 'The games were an outstanding success, with almost 2 400 athletes competing.', '', ARRAY[]::TEXT[]),
('Competence', 'competence_us.mp3', 'noun', 'B1', 'the ability to do something well', '', 'to gain a high level of competence in English', '', ARRAY[]::TEXT[]),
('Competent', 'competent_us.mp3', 'adjective', 'B1', 'having enough skill or knowledge to do something well or to the necessary standard', '', 'He''s very competent in his work.', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
