INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Normal', 'normal_us.mp3', 'noun', 'B1', 'the usual or average state, level or standard', '', 'above/below normal, The rainfall has been above normal for the time of year.', '', ARRAY[]::TEXT[]),
('Normally', 'normally_us.mp3', 'adverb', 'B1', 'usually; in normal circumstances', '', 'I would never normally discuss this.', '', ARRAY[]::TEXT[]),
('North', 'north_us.mp3', 'adjective', 'B1', 'in or towards the north', '', 'North London', '', ARRAY[]::TEXT[]),
('North', 'north_us.mp3', 'adverb', 'B1', 'towards the north', '', 'The house faces north.', '', ARRAY[]::TEXT[]),
('North', 'north_us.mp3', 'noun', 'B1', 'the direction that is on your left when you watch the sun rise; one of the four main points of the compass', '', 'Which way is north?', '', ARRAY[]::TEXT[]),
('Northern', 'northern_us.mp3', 'adjective', 'B1', 'located in the north or facing north; connected with or typical of the north part of the world or a region', '', 'the northern slopes of the mountains', '', ARRAY[]::TEXT[]),
('Nose', 'nose_us.mp3', 'noun', 'B1', 'the part of the face that sticks out above the mouth, used for breathing and smelling things', '', 'She had dark eyes and a long narrow nose.', '', ARRAY[]::TEXT[]),
('Not', 'not_us.mp3', 'adverb', 'B1', 'used with be, do or have to form the negative of verbs; used to form the negative of modal verbs like can or must', '', 'She did not/didn’t see him.', '', ARRAY[]::TEXT[]),
('Notable', 'notable_us.mp3', 'adjective', 'B1', 'deserving to be noticed or to receive attention; important', '', 'a notable success/achievement/example', '', ARRAY[]::TEXT[]),
('Notably', 'notably_us.mp3', 'adverb', 'B1', 'used for giving a good or the most important example of something', '', 'The house had many drawbacks, most notably its price.', '', ARRAY[]::TEXT[]),
('Note', 'note_us.mp3', 'noun', 'B1', 'a short piece of writing to help you remember something', '', 'Please make a note of the dates.', '', ARRAY[]::TEXT[]),
('Note', 'note_us.mp3', 'verb', 'B1', 'to notice or pay careful attention to something', '', 'note something, Note the fine early Baroque altar inside the chapel.', '', ARRAY[]::TEXT[]),
('Notebook', 'notebook_us.mp3', 'noun', 'B1', 'a small book of plain paper for writing notes in', '', 'The police officer wrote the details down in his notebook.', '', ARRAY[]::TEXT[]),
('Nothing', 'nothing_us.mp3', 'pronoun', 'B1', 'not anything; no single thing', '', 'There was nothing in her bag.', '', ARRAY[]::TEXT[]),
('Notice', 'notice_us.mp3', 'noun', 'B1', 'a sheet of paper giving written or printed information, usually put in a public place', '', 'There was a notice on the board saying the class had been cancelled.', '', ARRAY[]::TEXT[]),
('Notice', 'notice_us.mp3', 'verb', 'B1', 'to see or hear somebody/something; to become aware of somebody/something', '', 'People were making fun of him but he didn''t seem to notice.', '', ARRAY[]::TEXT[]),
('Notify', 'notify_us.mp3', 'verb', 'B1', 'to formally or officially tell somebody about something', '', 'notify somebody, Competition winners will be notified by post.', '', ARRAY[]::TEXT[]),
('Notion', 'notion_us.mp3', 'noun', 'B1', 'an idea, a belief or an understanding of something', '', 'notion of something, a political system based on the notions of equality and liberty', '', ARRAY[]::TEXT[]),
('Notorious', 'notorious_us.mp3', 'adjective', 'B1', 'well known for being bad', '', 'a notorious criminal', '', ARRAY[]::TEXT[]),
('Novel', 'novel_us.mp3', 'adjective', 'B1', 'different from anything known before; new, interesting and often seeming slightly strange', '', 'a novel feature', '', ARRAY[]::TEXT[]),
('Novel', 'novel_us.mp3', 'noun', 'B1', 'a story long enough to fill a complete book, in which the characters and events are usually imaginary', '', 'to write/publish/read a novel', '', ARRAY[]::TEXT[]),
('Novelist', 'novelist_us.mp3', 'noun', 'B1', 'a person who writes novels', '', 'a romantic/historical novelist', '', ARRAY[]::TEXT[]),
('November', 'November_us.mp3', 'noun', 'B1', 'the 11th month of the year, between October and December', '', 'She was born in November.', '', ARRAY[]::TEXT[]),
('Now', 'now_us.mp3', 'adverb', 'B1', '(at) the present time', '', 'Where are you living now?', '', ARRAY[]::TEXT[]),
('Now', 'now_us.mp3', 'conjunction', 'B1', 'because the thing mentioned is happening or has just happened', '', 'Now that the kids have left home we''ve got a lot of extra space.', '', ARRAY[]::TEXT[]),
('Nowadays', 'nowadays_us.mp3', 'adverb', 'B1', 'at the present time, in contrast with the past', '', 'Nowadays most kids prefer going online to reading books.', '', ARRAY[]::TEXT[]),
('Nowhere', 'nowhere_us.mp3', 'adverb', 'B1', 'not in or to any place', '', 'I had nowhere to live, so I was sleeping on my sister''s couch.', '', ARRAY[]::TEXT[]),
('Nuclear', 'nuclear_us.mp3', 'adjective', 'B1', 'using, producing or resulting from nuclear energy', '', 'a nuclear power plant/station', '', ARRAY[]::TEXT[]),
('Number', 'number_us.mp3', 'noun', 'B1', 'a word or symbol that represents an amount or a quantity', '', 'Think of a number and multiply it by two.', '', ARRAY[]::TEXT[]),
('Number', 'number_us.mp3', 'verb', 'B1', 'to give a number to something as part of a series or list', '', 'number something, All the seats in the stadium are numbered.', '', ARRAY[]::TEXT[]),
('Numerous', 'numerous_us.mp3', 'adjective', 'B1', 'existing in large numbers', '', 'He has been late on numerous occasions.', '', ARRAY[]::TEXT[]),
('Nurse', 'nurse_us.mp3', 'noun', 'B1', 'a person whose job is to take care of sick or injured people, usually in a hospital', '', 'a registered nurse', '', ARRAY[]::TEXT[]),
('Nursery', 'nursery_us.mp3', 'noun', 'B1', 'a place where young children are cared for while their parents are at work; a day nursery or nursery school', '', 'at nursery, Her youngest child is at nursery now.', '', ARRAY[]::TEXT[]),
('Nursing', 'nursing_us.mp3', 'noun', 'B1', 'the job or skill of caring for people who are sick or injured', '', 'a career in nursing', '', ARRAY[]::TEXT[]),
('Nut', 'nut_us.mp3', 'noun', 'B1', 'a small hard fruit with a very hard shell that grows on some trees', '', 'to crack a nut (= open it)', '', ARRAY[]::TEXT[]),
('Nutrition', 'nutrition_us.mp3', 'noun', 'B1', 'the process by which living things receive the food necessary for them to grow and be healthy', '', 'advice on diet and nutrition', '', ARRAY[]::TEXT[]),
('O''clock', 'o''''clock_us.mp3', 'adverb', 'B1', 'used with the numbers 1 to 12 when telling the time, to mean an exact hour', '', 'He left between five and six o''clock.', '', ARRAY[]::TEXT[]),
('Obesity', 'obesity_us.mp3', 'noun', 'B1', 'the quality or fact of being very fat, in a way that is not healthy', '', 'Obesity can increase the risk of heart disease.', '', ARRAY[]::TEXT[]),
('Obey', 'obey_us.mp3', 'verb', 'B1', 'to do what you are told or expected to do', '', 'obey something, to obey a command/an order/rules/the law', '', ARRAY[]::TEXT[]),
('Object', 'object_us.mp3', 'noun', 'B1', 'a thing that can be seen and touched, but is not alive', '', 'everyday objects such as cups and saucers', '', ARRAY[]::TEXT[]),
('Object', 'object_us.mp3', 'verb', 'B1', 'to say that you disagree with or oppose something', '', 'If nobody objects, we''ll postpone the meeting till next week.', '', ARRAY[]::TEXT[]),
('Objection', 'objection_us.mp3', 'noun', 'B1', 'a reason why you do not like or are opposed to something; a statement about this', '', 'I''d like to come too, if you have no objection.', '', ARRAY[]::TEXT[]),
('Objective', 'objective_us.mp3', 'adjective', 'B1', 'not influenced by personal feelings or opinions; considering only facts', '', 'an objective assessment of the situation', '', ARRAY[]::TEXT[]),
('Objective', 'objective_us.mp3', 'noun', 'B1', 'something that you are trying to achieve', '', 'the primary/principal/key objective', '', ARRAY[]::TEXT[]),
('Obligation', 'obligation_us.mp3', 'noun', 'B1', 'the state of being forced to do something because it is your duty, or because of a law, etc.', '', 'obligation to do something, You are under no obligation to buy anything.', '', ARRAY[]::TEXT[]),
('Oblige', 'oblige_us.mp3', 'verb', 'B1', 'to force somebody to do something, by law, because it is a duty, etc.', '', 'Parents are obliged by law to send their children to school.', '', ARRAY[]::TEXT[]),
('Observation', 'observation_us.mp3', 'noun', 'B1', 'the act of watching somebody/something carefully for a period of time, especially to learn something', '', 'Most information was collected by direct observation of the animals'' behaviour.', '', ARRAY[]::TEXT[]),
('Observe', 'observe_us.mp3', 'verb', 'B1', 'to see or notice somebody/something', '', 'observe somebody/something, Have you observed any changes lately?', '', ARRAY[]::TEXT[]),
('Observer', 'observer_us.mp3', 'noun', 'B1', 'a person who watches somebody/something', '', 'According to observers, the plane exploded shortly after take-off.', '', ARRAY[]::TEXT[]),
('Obsess', 'obsess_us.mp3', 'verb', 'B1', 'to completely fill your mind so that you cannot think of anything else, in a way that is not reasonable or normal', '', 'be obsessed by somebody/something, He''s obsessed by computers.', '', ARRAY[]::TEXT[]),
('Obsession', 'obsession_us.mp3', 'noun', 'B1', 'the state in which a person’s mind is completely filled with thoughts of one particular thing or person in a way that is not reasonable or normal', '', 'Her fear of flying is bordering on obsession.', '', ARRAY[]::TEXT[]),
('Obstacle', 'obstacle_us.mp3', 'noun', 'B1', 'a situation, an event, etc. that makes it difficult for you to do or achieve something', '', 'So far, we have managed to overcome all the obstacles that have been placed in our path.', '', ARRAY[]::TEXT[]),
('Obtain', 'obtain_us.mp3', 'verb', 'B1', 'to get something, especially by making an effort', '', 'to obtain information/data/results', '', ARRAY[]::TEXT[]),
('Obvious', 'obvious_us.mp3', 'adjective', 'B1', 'easy to see or understand', '', 'I know you don''t like her but try not to make it so obvious.', '', ARRAY[]::TEXT[]),
('Obviously', 'obviously_us.mp3', 'adverb', 'B1', 'used when giving information that you expect other people to know already or agree with', '', 'Obviously, we don''t want to spend too much money.', '', ARRAY[]::TEXT[]),
('Occasion', 'occasion_us.mp3', 'noun', 'B1', 'a particular time when something happens', '', 'on an occasion, on this/that occasion', '', ARRAY[]::TEXT[]),
('Occasional', 'occasional_us.mp3', 'adjective', 'B1', 'happening or done sometimes but not often', '', 'He works for us on an occasional basis.', '', ARRAY[]::TEXT[]),
('Occasionally', 'occasionally_us.mp3', 'adverb', 'B1', 'sometimes but not often', '', 'We occasionally meet for a drink after work.', '', ARRAY[]::TEXT[]),
('Occupation', 'occupation_us.mp3', 'noun', 'B1', 'a job or profession', '', 'Please state your name, age and occupation below.', '', ARRAY[]::TEXT[]),
('Occupy', 'occupy_us.mp3', 'verb', 'B1', 'to fill or use a space, an area or an amount of time', '', 'The bed seemed to occupy most of the room.', '', ARRAY[]::TEXT[]),
('Occur', 'occur_us.mp3', 'verb', 'B1', 'to happen', '', 'When exactly did the incident occur?', '', ARRAY[]::TEXT[]),
('Occurrence', 'occurrence_us.mp3', 'noun', 'B1', 'something that happens or exists', '', 'a common/everyday/frequent/regular occurrence', '', ARRAY[]::TEXT[]),
('Ocean', 'ocean_us.mp3', 'noun', 'B1', 'the mass of salt water that covers most of the earth’s surface', '', 'The ship was dredged from the depths of the ocean.', '', ARRAY[]::TEXT[]),
('October', 'October_us.mp3', 'noun', 'B1', 'the 10th month of the year, between September and November', '', 'She was born in October.', '', ARRAY[]::TEXT[]),
('Odd', 'odd_us.mp3', 'adjective', 'B1', 'strange or unusual', '', 'They''re very odd people.', '', ARRAY[]::TEXT[]),
('Odds', 'odds_us.mp3', 'noun', 'B1', 'the degree to which something is likely to happen', '', 'The odds are very much in our favour (= we are likely to succeed).', '', ARRAY[]::TEXT[]),
('Of', 'of_us.mp3', 'preposition', 'B1', 'belonging to somebody; relating to somebody', '', 'a friend of mine', '', ARRAY[]::TEXT[]),
('Off', 'off_us.mp3', 'adverb', 'B1', 'used to say that something has been removed or become separated', '', 'He''s had his beard shaved off.', '', ARRAY[]::TEXT[]),
('Off', 'off_us.mp3', 'preposition', 'B1', 'down or away from a place or at a distance in space or time', '', 'I fell off the ladder.', '', ARRAY[]::TEXT[]),
('Offence', 'offence_us.mp3', 'noun', 'B1', 'an illegal act', '', 'a criminal/serious/minor/sexual offence', '', ARRAY[]::TEXT[]),
('Offend', 'offend_us.mp3', 'verb', 'B1', 'to make somebody feel upset because of something you say or do that is rude or embarrassing', '', 'They''ll be offended if you don''t go to their wedding.', '', ARRAY[]::TEXT[]),
('Offender', 'offender_us.mp3', 'noun', 'B1', 'a person who commits a crime', '', 'a persistent/serious/violent, etc. offender', '', ARRAY[]::TEXT[]),
('Offensive', 'offensive_us.mp3', 'adjective', 'B1', 'rude in a way that causes somebody to feel upset or annoyed because it shows a lack of respect', '', 'offensive remarks', '', ARRAY[]::TEXT[]),
('Offer', 'offer_us.mp3', 'noun', 'B1', 'an act of saying that you are willing to do something for somebody or give something to somebody', '', 'to receive a job offer', '', ARRAY[]::TEXT[]),
('Offer', 'offer_us.mp3', 'verb', 'B1', 'to say that you are willing to give something to somebody', '', 'offer (something), Josie had offered her services as a guide.', '', ARRAY[]::TEXT[]),
('Offering', 'offering_us.mp3', 'noun', 'B1', 'something that is produced for other people to use, watch, enjoy, etc.', '', 'the latest offering from the Canadian-born writer', '', ARRAY[]::TEXT[]),
('Office', 'office_us.mp3', 'noun', 'B1', 'a room, set of rooms or building where people work, usually sitting at desks', '', 'The company is moving to new offices on the other side of town.', '', ARRAY[]::TEXT[]),
('Officer', 'officer_us.mp3', 'noun', 'B1', 'a person who is in a position of authority in the armed forces', '', 'army/military/naval officers', '', ARRAY[]::TEXT[]),
('Official', 'official_us.mp3', 'adjective', 'B1', 'agreed to, said, done, etc. by somebody who is in a position of authority', '', 'an official announcement/decision/statement', '', ARRAY[]::TEXT[]),
('Official', 'official_us.mp3', 'noun', 'B1', 'a person who is in a position of authority in a large organization', '', 'She is the government official in charge of the project.', '', ARRAY[]::TEXT[]),
('Offspring', 'offspring_us.mp3', 'noun', 'B1', 'a child of a particular person or couple', '', 'the problems parents have with their teenage offspring', '', ARRAY[]::TEXT[]),
('Often', 'often_us.mp3', 'adverb', 'B1', 'many times', '', 'We often go there.', '', ARRAY[]::TEXT[]),
('Oh', 'oh_us.mp3', 'exclamation', 'B1', 'used when you are reacting to something that has been said, especially if you did not know it before', '', '‘I saw Ben yesterday.’ ‘Oh yes, how is he?’', '', ARRAY[]::TEXT[]),
('Oil', 'oil_us.mp3', 'noun', 'B1', 'a thick liquid that is found in rock underground', '', 'Several companies are drilling for oil in the region.', '', ARRAY[]::TEXT[]),
('OK', 'OK_us.mp3', 'adjective', 'B1', 'safe and well; in a calm or happy state', '', 'Are you OK?', '', ARRAY[]::TEXT[]),
('OK', 'OK_us.mp3', 'adverb', 'B1', 'safe and well; in a calm or happy state', '', 'Are you OK?', '', ARRAY[]::TEXT[]),
('OK', 'OK_us.mp3', 'exclamation', 'B1', 'yes; all right', '', '‘Shall we go for a walk?’ ‘OK.’', '', ARRAY[]::TEXT[]),
('Old', 'old_us.mp3', 'adjective', 'B1', 'of a particular age', '', 'be… years, months, etc. old, The baby was only a few hours old.', '', ARRAY[]::TEXT[]),
('Old-fashioned', 'old-fashioned_us.mp3', 'adjective', 'B1', 'not modern; no longer fashionable', '', 'old-fashioned clothes/styles/methods/equipment', '', ARRAY[]::TEXT[]),
('On', 'on_us.mp3', 'adverb', 'B1', 'on somebody’s body; being worn', '', 'Put your coat on.', '', ARRAY[]::TEXT[]),
('On', 'on_us.mp3', 'preposition', 'B1', 'in or into a position covering, touching or forming part of a surface', '', 'a picture on a wall', '', ARRAY[]::TEXT[]),
('Once', 'once_us.mp3', 'adverb', 'B1', 'on one occasion only; one time', '', 'I''ve only been there once.', '', ARRAY[]::TEXT[]),
('Once', 'once_us.mp3', 'conjunction', 'B1', 'as soon as; when', '', 'We didn''t know how we would cope once the money had gone.', '', ARRAY[]::TEXT[]),
('One', 'one_us.mp3', 'determiner', 'B1', 'the number 1', '', 'Do you want one or two?', '', ARRAY[]::TEXT[]),
('One', 'one_us.mp3', 'number', 'B1', 'the number 1', '', 'Do you want one or two?', '', ARRAY[]::TEXT[]),
('One', 'one_us.mp3', 'pronoun', 'B1', 'used to avoid repeating a noun, when you are referring to somebody/something that has already been mentioned, or that the person you are speaking to knows about', '', 'I''d like an ice cream. Are you having one, too?', '', ARRAY[]::TEXT[]),
('Ongoing', 'ongoing_us.mp3', 'adjective', 'B1', 'continuing to exist or develop', '', 'an ongoing debate/discussion/process', '', ARRAY[]::TEXT[]),
('Onion', 'onion_us.mp3', 'noun', 'B1', 'a round vegetable with many layers inside each other and a brown, red or white skin. Onions have a strong smell and taste.', '', 'Chop the onions finely.', '', ARRAY[]::TEXT[]),
('Online', 'online_us.mp3', 'adjective', 'B1', 'available on or done using the internet or other computer network', '', 'Online shopping is both cheap and convenient.', '', ARRAY[]::TEXT[]),
('Online', 'online_us.mp3', 'adverb', 'B1', 'onto the internet; using the internet or other computer network', '', 'Many children would rather go online than watch television.', '', ARRAY[]::TEXT[]),
('Only', 'only_us.mp3', 'adjective', 'B1', 'used to say that no other or others of the same group exist or are there', '', 'She''s their only daughter.', '', ARRAY[]::TEXT[]),
('Only', 'only_us.mp3', 'adverb', 'B1', 'nobody or nothing except', '', 'There are only a limited number of tickets available.', '', ARRAY[]::TEXT[]),
('Onto', 'onto_us.mp3', 'preposition', 'B1', 'used with verbs to express movement on or to a particular place or position', '', 'Move the books onto the second shelf.', '', ARRAY[]::TEXT[]),
('Open', 'open_us.mp3', 'adjective', 'B1', 'allowing things or people to go through; not closed or blocked', '', 'A wasp flew in the open window.', '', ARRAY[]::TEXT[]),
('Open', 'open_us.mp3', 'verb', 'B1', 'to move a door, window, lid, etc. into a position that is no longer closed; to get into this position', '', 'Mr Chen opened the car door for his wife.', '', ARRAY[]::TEXT[]),
('Opening', 'opening_us.mp3', 'noun', 'B1', 'a space or hole that somebody/something can pass through', '', 'We could see the stars through an opening in the roof.', '', ARRAY[]::TEXT[]),
('Openly', 'openly_us.mp3', 'adverb', 'B1', 'without hiding any feelings, opinions or information', '', 'Can you talk openly about sex with your parents?', '', ARRAY[]::TEXT[]),
('Opera', 'opera_us.mp3', 'noun', 'B1', 'a dramatic work in which all or most of the words are sung to music; works of this type as an art form or entertainment', '', 'Puccini’s operas', '', ARRAY[]::TEXT[]),
('Operate', 'operate_us.mp3', 'verb', 'B1', 'to work in a particular way', '', 'Most domestic freezers operate at below −18°C.', '', ARRAY[]::TEXT[]),
('Operation', 'operation_us.mp3', 'noun', 'B1', 'the process of cutting open a part of a person’s body in order to remove or repair a damaged part', '', 'Will I need to have an operation?', '', ARRAY[]::TEXT[]),
('Operational', 'operational_us.mp3', 'adjective', 'B1', 'connected with the way in which a business, machine, system, etc. works', '', 'operational activities/costs/difficulties', '', ARRAY[]::TEXT[]),
('Operator', 'operator_us.mp3', 'noun', 'B1', 'a person who operates equipment or a machine', '', 'a computer/machine operator', '', ARRAY[]::TEXT[]),
('Opinion', 'opinion_us.mp3', 'noun', 'B1', 'your feelings or thoughts about somebody/something, rather than a fact', '', 'He has very strong political opinions.', '', ARRAY[]::TEXT[]),
('Opponent', 'opponent_us.mp3', 'noun', 'B1', 'a person that you are playing or fighting against in a game, competition, argument, etc.', '', 'a political opponent', '', ARRAY[]::TEXT[]),
('Opportunity', 'opportunity_us.mp3', 'noun', 'B1', 'a time when a particular situation makes it possible to do or achieve something', '', 'Don''t miss this opportunity!', '', ARRAY[]::TEXT[]),
('Oppose', 'oppose_us.mp3', 'verb', 'B1', 'to disagree strongly with somebody’s plan, policy, etc. and try to change it or prevent it from succeeding', '', 'oppose somebody/something, This party would bitterly oppose the re-introduction of the death penalty.', '', ARRAY[]::TEXT[]),
('Opposed', 'opposed_us.mp3', 'adjective', 'B1', 'disagreeing strongly with something and trying to stop it', '', 'opposed to something, He was strongly opposed to modernism in art.', '', ARRAY[]::TEXT[]),
('Opposite', 'opposite_us.mp3', 'adjective', 'B1', 'on the other side of a particular area from somebody/something and usually facing them', '', 'Answers are given on the opposite page.', '', ARRAY[]::TEXT[]),
('Opposite', 'opposite_us.mp3', 'adverb', 'B1', 'on the other side of a particular area from somebody/something and usually facing them', '', 'There''s a newly married couple living opposite (= on the other side of the road).', '', ARRAY[]::TEXT[]),
('Opposite', 'opposite_us.mp3', 'noun', 'B1', 'a person or thing that is as different as possible from somebody/something else', '', 'Hot and cold are opposites.', '', ARRAY[]::TEXT[]),
('Opposite', 'opposite_us.mp3', 'preposition', 'B1', 'on the other side of a particular area from somebody/something, and usually facing them', '', 'I sat opposite him during the meal (= on the other side of the table).', '', ARRAY[]::TEXT[]),
('Opposition', 'opposition_us.mp3', 'noun', 'B1', 'the act of strongly disagreeing with somebody/something, especially with the aim of preventing something from happening', '', 'Opposition came primarily from students.', '', ARRAY[]::TEXT[]),
('Opt', 'opt_us.mp3', 'verb', 'B1', 'to choose to take or not to take a particular course of action', '', 'opt for/against something, After graduating she opted for a career in music.', '', ARRAY[]::TEXT[]),
('Optical', 'optical_us.mp3', 'adjective', 'B1', 'connected with the sense of sight or the relationship between light and sight', '', 'optical effects', '', ARRAY[]::TEXT[]),
('Optimism', 'optimism_us.mp3', 'noun', 'B1', 'a feeling that good things will happen and that something will be successful', '', 'a mood of cautious optimism', '', ARRAY[]::TEXT[]),
('Optimistic', 'optimistic_us.mp3', 'adjective', 'B1', 'expecting good things to happen or something to be successful; showing this feeling', '', 'We are now taking a more optimistic view.', '', ARRAY[]::TEXT[]),
('Option', 'option_us.mp3', 'noun', 'B1', 'something that you can choose to have or do; the freedom to choose what you do', '', 'As I see it, we have two options…', '', ARRAY[]::TEXT[]),
('Or', 'or_us.mp3', 'conjunction', 'B1', 'used to introduce another possibility', '', 'Is your sister older or younger than you?', '', ARRAY[]::TEXT[]),
('Oral', 'oral_us.mp3', 'adjective', 'B1', 'spoken rather than written', '', 'a test of both oral and written French', '', ARRAY[]::TEXT[]),
('Orange', 'orange_us.mp3', 'adjective', 'B1', 'between red and yellow in colour', '', 'yellow and orange flames', '', ARRAY[]::TEXT[]),
('Orange', 'orange_us.mp3', 'noun', 'B1', 'a round citrus fruit with thick skin of a colour between red and yellow and a lot of sweet juice', '', 'orange peel/zest/rind', '', ARRAY[]::TEXT[]),
('Orchestra', 'orchestra_us.mp3', 'noun', 'B1', 'a large group of people who play various musical instruments together, led by a conductor', '', 'She plays the flute in the school orchestra.', '', ARRAY[]::TEXT[]),
('Order', 'order_us.mp3', 'noun', 'B1', 'the way in which people or things are placed or arranged in relation to each other', '', 'in… order, The names are listed in alphabetical order.', '', ARRAY[]::TEXT[]),
('Order', 'order_us.mp3', 'verb', 'B1', 'to ask for something to eat or drink in a restaurant, bar, etc.', '', 'order (something), I ordered a coffee and a sandwich.', '', ARRAY[]::TEXT[]),
('Ordinary', 'ordinary_us.mp3', 'adjective', 'B1', 'not unusual or different in any way', '', 'an ordinary sort of day', '', ARRAY[]::TEXT[]),
('Organ', 'organ_us.mp3', 'noun', 'B1', 'a part of the body that has a particular purpose, such as the heart or the brain; part of a plant with a particular purpose', '', 'the internal organs', '', ARRAY[]::TEXT[]),
('Organic', 'organic_us.mp3', 'adjective', 'B1', 'produced or practised without using artificial chemicals', '', 'organic cheese/vegetables/wine, etc.', '', ARRAY[]::TEXT[]),
('Organization', 'organization_us.mp3', 'noun', 'B1', 'a group of people who form a business, club, etc. together in order to achieve a particular aim', '', 'He''s the president of a large international organization.', '', ARRAY[]::TEXT[]),
('Organizational', 'organizational_us.mp3', 'adjective', 'B1', 'connected with the way in which the different parts of something are arranged; connected with an organization', '', 'organizational changes within the party', '', ARRAY[]::TEXT[]),
('Organize', 'organize_us.mp3', 'verb', 'B1', 'to make all the arrangements for something to happen or be provided', '', 'He helped to organize various events.', '', ARRAY[]::TEXT[]),
('Organized', 'organized_us.mp3', 'adjective', 'B1', 'involving large numbers of people who work together to do something in a way that has been carefully planned', '', 'an organized body of workers', '', ARRAY[]::TEXT[]),
('Organizer', 'organizer_us.mp3', 'noun', 'B1', 'a person who makes the arrangements for something', '', 'the organizers of the festival', '', ARRAY[]::TEXT[]),
('Orientation', 'orientation_us.mp3', 'noun', 'B1', 'a person’s basic beliefs or feelings about a particular subject', '', 'religious/political orientation', '', ARRAY[]::TEXT[]),
('Origin', 'origin_us.mp3', 'noun', 'B1', 'the point from which something starts; the cause of something', '', 'origin of something, the origins of life on earth', '', ARRAY[]::TEXT[]),
('Original', 'original_us.mp3', 'adjective', 'B1', 'existing at the beginning of a particular period, process or activity', '', 'The room still has many of its original features.', '', ARRAY[]::TEXT[]),
('Original', 'original_us.mp3', 'noun', 'B1', 'a document, work of art, etc. produced for the first time, from which copies are later made', '', 'This painting is a copy; the original is in Madrid.', '', ARRAY[]::TEXT[]),
('Originally', 'originally_us.mp3', 'adverb', 'B1', 'used to describe the situation that existed at the beginning of a particular period or activity, especially before something was changed', '', 'The school was originally very small.', '', ARRAY[]::TEXT[]),
('Originate', 'originate_us.mp3', 'verb', 'B1', 'to happen or appear for the first time in a particular place or situation', '', 'The disease is thought to have originated in the tropics.', '', ARRAY[]::TEXT[]),
('Other', 'other_us.mp3', 'adjective', 'B1', 'used to refer to people or things that are additional or different to people or things that have been mentioned or are known about', '', 'Mr Harris and Mrs Bate and three other teachers were there.', '', ARRAY[]::TEXT[]),
('Other', 'other_us.mp3', 'pronoun', 'B1', 'used to refer to people or things that are additional or different to people or things that have been mentioned or are known about', '', 'Mr Harris and Mrs Bate and three other teachers were there.', '', ARRAY[]::TEXT[]),
('Otherwise', 'otherwise_us.mp3', 'adverb', 'B1', 'used to state what the result would be if something did not happen or if the situation were different', '', 'My parents lent me the money. Otherwise, I couldn''t have afforded the trip.', '', ARRAY[]::TEXT[]),
('Ought', 'ought_us.mp3', 'modal verb', 'B1', 'used to say what is the right thing to do', '', 'They ought to apologize.', '', ARRAY[]::TEXT[]),
('Our', 'our_us.mp3', 'determiner', 'B1', 'belonging to us; connected with us', '', 'our daughter/dog/house', '', ARRAY[]::TEXT[]),
('Ours', 'ours_us.mp3', 'pronoun', 'B1', 'the one or ones that belong to us', '', 'Their house is very similar to ours, but ours is bigger.', '', ARRAY[]::TEXT[]),
('Ourselves', 'ourselves_us.mp3', 'pronoun', 'B1', 'the reflexive form of we; used when you and another person or other people together cause and are affected by an action', '', 'We shouldn''t blame ourselves for what happened.', '', ARRAY[]::TEXT[]),
('Out', 'out_us.mp3', 'adverb', 'B1', 'away from the inside of a place or thing', '', 'She ran out into the corridor.', '', ARRAY[]::TEXT[]),
('Out', 'out_us.mp3', 'preposition', 'B1', 'away from the inside of a place or thing', '', 'She ran out into the corridor.', '', ARRAY[]::TEXT[]),
('Outbreak', 'outbreak_us.mp3', 'noun', 'B1', 'the sudden start of something unpleasant, especially violence or a disease', '', 'the outbreak of war', '', ARRAY[]::TEXT[]),
('Outcome', 'outcome_us.mp3', 'noun', 'B1', 'the result or effect of an action or event', '', 'The likely outcome is a compromise.', '', ARRAY[]::TEXT[]),
('Outdoor', 'outdoor_us.mp3', 'adjective', 'B1', 'used, happening or located outside rather than in a building', '', 'outdoor pursuits/recreation/activities', '', ARRAY[]::TEXT[]),
('Outdoors', 'outdoors_us.mp3', 'adverb', 'B1', 'outside, rather than in a building', '', 'The rain prevented them from eating outdoors.', '', ARRAY[]::TEXT[]),
('Outer', 'outer_us.mp3', 'adjective', 'B1', 'on the outside of something', '', 'the outer layers of the skin', '', ARRAY[]::TEXT[]),
('Outfit', 'outfit_us.mp3', 'noun', 'B1', 'a set of clothes that you wear together, especially for a particular occasion or purpose', '', 'She was wearing an expensive new outfit.', '', ARRAY[]::TEXT[]),
('Outing', 'outing_us.mp3', 'noun', 'B1', 'a trip that you go on for pleasure or education, usually with a group of people and lasting no more than one day', '', 'a family outing', '', ARRAY[]::TEXT[]),
('Outlet', 'outlet_us.mp3', 'noun', 'B1', 'a shop or an organization that sells goods made by a particular company or of a particular type', '', 'The business has 34 retail outlets in this state alone.', '', ARRAY[]::TEXT[]),
('Outline', 'outline_us.mp3', 'noun', 'B1', 'a description of the main facts or points involved in something', '', 'outline of something, This is a brief outline of the events.', '', ARRAY[]::TEXT[]),
('Outline', 'outline_us.mp3', 'verb', 'B1', 'to give a description of the main facts or points involved in something', '', 'outline something, He outlined his plan to leave St. Petersburg.', '', ARRAY[]::TEXT[]),
('Outlook', 'outlook_us.mp3', 'noun', 'B1', 'the attitude to life and the world of a particular person, group or culture', '', 'Travel broadens your outlook.', '', ARRAY[]::TEXT[]),
('Output', 'output_us.mp3', 'noun', 'B1', 'the amount of something that a person, a machine or an organization produces', '', 'Manufacturing output has increased by 8 per cent.', '', ARRAY[]::TEXT[]),
('Outrage', 'outrage_us.mp3', 'noun', 'B1', 'a strong feeling of shock and anger', '', 'The judge''s remarks caused public outrage.', '', ARRAY[]::TEXT[]),
('Outrage', 'outrage_us.mp3', 'verb', 'B1', 'to make somebody very shocked and angry', '', 'He was outraged at the way he had been treated.', '', ARRAY[]::TEXT[]),
('Outside', 'outside_us.mp3', 'adjective', 'B1', 'of, on or facing the outer side', '', 'The outside walls are damp.', '', ARRAY[]::TEXT[]),
('Outside', 'outside_us.mp3', 'adverb', 'B1', 'not in a room, building or container but on or to the outside of it', '', 'I''m seeing a patient—please wait outside.', '', ARRAY[]::TEXT[]),
('Outside', 'outside_us.mp3', 'noun', 'B1', 'the outer side or surface of something', '', 'The outside of the house needs painting.', '', ARRAY[]::TEXT[]),
('Outside', 'outside_us.mp3', 'preposition', 'B1', 'on or to a place on the outside of something', '', 'You can park your car outside our house.', '', ARRAY[]::TEXT[]),
('Outsider', 'outsider_us.mp3', 'noun', 'B1', 'a person who is not accepted as a member of a society, group, etc.', '', 'Here she felt she would always be an outsider.', '', ARRAY[]::TEXT[]),
('Outstanding', 'outstanding_us.mp3', 'adjective', 'B1', 'extremely good; excellent', '', 'an outstanding player/achievement/success', '', ARRAY[]::TEXT[]),
('Oven', 'oven_us.mp3', 'noun', 'B1', 'the part of a cooker that is like a box with a door on the front, in which food is cooked or heated', '', 'Take the cake out of the oven.', '', ARRAY[]::TEXT[]),
('Over', 'over_us.mp3', 'adverb', 'B1', 'across a street, an open space, etc.', '', 'I stopped and crossed over.', '', ARRAY[]::TEXT[]),
('Over', 'over_us.mp3', 'preposition', 'B1', 'resting on the surface of somebody/something and partly or completely covering them/it', '', 'She put a blanket over the sleeping child.', '', ARRAY[]::TEXT[]),
('Overall', 'overall_us.mp3', 'adjective', 'B1', 'including all the things or people that are involved in a particular situation; general', '', 'There will be winners in each of three age groups, and one overall winner.', '', ARRAY[]::TEXT[]),
('Overall', 'overall_us.mp3', 'adverb', 'B1', 'including everything or everyone; in total', '', 'The company will invest $1.6m overall in new equipment.', '', ARRAY[]::TEXT[]),
('Overcome', 'overcome_us.mp3', 'verb', 'B1', 'to succeed in dealing with or controlling a problem that has been preventing you from achieving something', '', 'She overcame injury to win the Olympic gold medal.', '', ARRAY[]::TEXT[]),
('Overlook', 'overlook_us.mp3', 'verb', 'B1', 'to fail to see or notice something', '', 'He seems to have overlooked one important fact.', '', ARRAY[]::TEXT[]),
('Overly', 'overly_us.mp3', 'adverb', 'B1', 'too; very', '', 'I''m not overly fond of pasta.', '', ARRAY[]::TEXT[]),
('Overnight', 'overnight_us.mp3', 'adverb', 'B1', 'during or for the night', '', 'We stayed overnight in London after the theatre.', '', ARRAY[]::TEXT[]),
('Overseas', 'overseas_us.mp3', 'adjective', 'B1', 'connected with foreign countries, especially those separated from your country by the sea or ocean', '', 'The firm is expanding into overseas markets.', '', ARRAY[]::TEXT[]),
('Overseas', 'overseas_us.mp3', 'adverb', 'B1', 'to or in a foreign country, especially those separated from your country by the sea or ocean', '', 'to live/work/go overseas', '', ARRAY[]::TEXT[]),
('Oversee', 'oversee_us.mp3', 'verb', 'B1', 'to watch somebody/something and make sure that a job or an activity is done correctly', '', 'United Nations observers oversaw the elections.', '', ARRAY[]::TEXT[]),
('Overturn', 'overturn_us.mp3', 'verb', 'B1', 'if something overturns, or if somebody overturns it, it turns into a position in which the top of it is where the bottom of it normally is or on its side', '', 'The car skidded and overturned.', '', ARRAY[]::TEXT[]),
('Overwhelm', 'overwhelm_us.mp3', 'verb', 'B1', 'to have such a strong emotional effect on somebody that it is difficult for them to resist or know how to react', '', 'She was overwhelmed by feelings of guilt.', '', ARRAY[]::TEXT[]),
('Overwhelming', 'overwhelming_us.mp3', 'adjective', 'B1', 'very great or very strong; so powerful that you cannot resist it or decide how to react', '', 'The evidence against him was overwhelming.', '', ARRAY[]::TEXT[]),
('Owe', 'owe_us.mp3', 'verb', 'B1', 'to have to pay somebody for something that you have already received or return money that you have borrowed', '', 'owe somebody something, She still owes her father £3 000.', '', ARRAY[]::TEXT[]),
('Own', 'own_us.mp3', 'adjective', 'B1', 'used to emphasize that something belongs to or is connected with somebody', '', 'It was her own idea.', '', ARRAY[]::TEXT[]),
('Own', 'own_us.mp3', 'pronoun', 'B1', 'used to emphasize that something belongs to or is connected with somebody', '', 'It was her own idea.', '', ARRAY[]::TEXT[]),
('Own', 'own_us.mp3', 'verb', 'B1', 'to have something that belongs to you, especially because you have bought it', '', 'Do you own your house or do you rent it?', '', ARRAY[]::TEXT[]),
('Owner', 'owner_us.mp3', 'noun', 'B1', 'a person who owns something', '', 'a dog/pet/gun owner', '', ARRAY[]::TEXT[]),
('Ownership', 'ownership_us.mp3', 'noun', 'B1', 'the fact of owning something', '', 'a growth in home ownership', '', ARRAY[]::TEXT[]),
('Oxygen', 'oxygen_us.mp3', 'noun', 'B1', 'a chemical element. Oxygen is a gas that is present in air and water and is necessary for people, animals and plants to live.', '', 'The patient didn''t seem to be getting enough oxygen.', '', ARRAY[]::TEXT[]),
('Pace', 'pace_us.mp3', 'noun', 'B1', 'the speed at which somebody/something walks, runs or moves', '', 'at a… pace, to set off at a steady/gentle/leisurely pace', '', ARRAY[]::TEXT[]),
('Pace', 'pace_us.mp3', 'verb', 'B1', 'to walk up and down in a small area many times, especially because you are feeling nervous or angry', '', '+ adv./prep., She paced up and down outside the room.', '', ARRAY[]::TEXT[]),
('Pack', 'pack_us.mp3', 'noun', 'B1', 'a container, usually made of paper, that holds a number of the same thing or an amount of something, ready to be sold', '', 'pack of something, a pack of cigarettes/gum', '', ARRAY[]::TEXT[]),
('Pack', 'pack_us.mp3', 'verb', 'B1', 'to put clothes, etc. into a bag in preparation for a trip away from home', '', 'I haven''t packed yet.', '', ARRAY[]::TEXT[]),
('Package', 'package_us.mp3', 'noun', 'B1', 'something that is wrapped in paper or put into a thick envelope so that it can be sent by mail, carried easily, or given as a present', '', 'A large package has arrived for you.', '', ARRAY[]::TEXT[]),
('Package', 'package_us.mp3', 'verb', 'B1', 'to put something into a box, bag, etc. to be sold or transported', '', 'package something, packaged food/goods', '', ARRAY[]::TEXT[]),
('Packet', 'packet_us.mp3', 'noun', 'B1', 'a small container made of paper or card in which goods are packed for selling', '', 'a packet of biscuits/cigarettes/crisps', '', ARRAY[]::TEXT[]),
('Pad', 'pad_us.mp3', 'noun', 'B1', 'a thick piece of soft material that is used, for example, for cleaning or protecting something or for holding liquid', '', 'medicated cleansing pads for sensitive skin', '', ARRAY[]::TEXT[]),
('Page', 'page_us.mp3', 'noun', 'B1', 'one side or both sides of a sheet of paper in a book, magazine, etc.', '', 'Turn to page 64.', '', ARRAY[]::TEXT[]),
('Pain', 'pain_us.mp3', 'noun', 'B1', 'the feelings that you have in your body when you have been hurt or when you are ill', '', 'a cry of pain', '', ARRAY[]::TEXT[]),
('Painful', 'painful_us.mp3', 'adjective', 'B1', 'causing you pain', '', 'Is your back still painful?', '', ARRAY[]::TEXT[]),
('Paint', 'paint_us.mp3', 'noun', 'B1', 'a liquid that is put on surfaces to give them a particular colour; a layer of this liquid when it has dried on a surface', '', 'white paint', '', ARRAY[]::TEXT[]),
('Paint', 'paint_us.mp3', 'verb', 'B1', 'to cover a surface or object with paint', '', 'paint something with something, Paint the shed with weather-resistant paint.', '', ARRAY[]::TEXT[]),
('Painter', 'painter_us.mp3', 'noun', 'B1', 'a person whose job is painting buildings, walls, etc.', '', 'He works as a painter and decorator.', '', ARRAY[]::TEXT[]),
('Painting', 'painting_us.mp3', 'noun', 'B1', 'a picture that has been painted', '', 'a watercolour/crylic painting', '', ARRAY[]::TEXT[]),
('Pair', 'pair_us.mp3', 'noun', 'B1', 'two things of the same type, especially when they are used or worn together', '', 'a pair of shoes/boots', '', ARRAY[]::TEXT[]),
('Palace', 'palace_us.mp3', 'noun', 'B1', 'the official home of a king, queen, president, etc.', '', 'Buckingham Palace', '', ARRAY[]::TEXT[]),
('Pale', 'pale_us.mp3', 'adjective', 'B1', 'having skin that is very light in colour; having skin that has less colour than usual because of illness, a strong emotion, etc.', '', 'a pale complexion', '', ARRAY[]::TEXT[]),
('Palm', 'palm_us.mp3', 'noun', 'B1', 'a straight tree with a mass of long leaves at the top, growing in tropical countries. There are several types of palm tree, some of which produce fruit.', '', 'a date palm', '', ARRAY[]::TEXT[]),
('Panel', 'panel_us.mp3', 'noun', 'B1', 'a square or rectangular piece of wood, glass or metal that forms part of a larger surface such as a door or wall', '', 'One of the glass panels in the front door was cracked.', '', ARRAY[]::TEXT[]),
('Panic', 'panic_us.mp3', 'noun', 'B1', 'a sudden feeling of great fear that cannot be controlled and prevents you from thinking clearly', '', 'a moment of panic', '', ARRAY[]::TEXT[]),
('Pants', 'pants_us.mp3', 'noun', 'B1', 'underpants or knickers', '', 'a pair of pants', '', ARRAY[]::TEXT[]),
('Paper', 'paper_us.mp3', 'noun', 'B1', 'the thin material that you write and draw on and that is also used for wrapping and packing things', '', 'a piece/sheet of paper', '', ARRAY[]::TEXT[]),
('Parade', 'parade_us.mp3', 'noun', 'B1', 'a public celebration of a special day or event, usually with bands in the streets and decorated vehicles', '', 'the Lord Mayor’s parade', '', ARRAY[]::TEXT[]),
('Paragraph', 'paragraph_us.mp3', 'noun', 'B1', 'a section of a piece of writing, usually consisting of several sentences dealing with a single subject. The first sentence of a paragraph starts on a new line.', '', 'an opening/introductory paragraph', '', ARRAY[]::TEXT[]),
('Parallel', 'parallel_us.mp3', 'adjective', 'B1', 'two or more lines that are parallel to each other are the same distance apart at every point', '', 'parallel lines', '', ARRAY[]::TEXT[]),
('Parallel', 'parallel_us.mp3', 'noun', 'B1', 'a person, a situation, an event, etc. that is very similar to another, especially one in a different place or time', '', 'These ideas have parallels in Freud''s thought too.', '', ARRAY[]::TEXT[]),
('Parameter', 'parameter_us.mp3', 'noun', 'B1', 'something that decides or limits the way in which something can be done', '', 'to set/define the parameters', '', ARRAY[]::TEXT[]),
('Parent', 'parent_us.mp3', 'noun', 'B1', 'a person’s father or mother', '', 'He''s still living with his parents.', '', ARRAY[]::TEXT[]),
('Parental', 'parental_us.mp3', 'adjective', 'B1', 'connected with a parent or parents', '', 'parental responsibility/rights', '', ARRAY[]::TEXT[]),
('Parish', 'parish_us.mp3', 'noun', 'B1', 'an area that has its own church and that a priest is responsible for', '', 'a parish church/priest', '', ARRAY[]::TEXT[]),
('Park', 'park_us.mp3', 'noun', 'B1', 'an area of public land in a town or a city where people go to walk, play and relax', '', 'Hyde Park', '', ARRAY[]::TEXT[]),
('Park', 'park_us.mp3', 'verb', 'B1', 'to leave a vehicle that you are driving in a particular place for a period of time', '', 'He parked and went inside.', '', ARRAY[]::TEXT[]),
('Parking', 'parking_us.mp3', 'noun', 'B1', 'the act of stopping a vehicle at a place and leaving it there for a period of time', '', 'There is no parking here between 9 a.m. and 6 p.m.', '', ARRAY[]::TEXT[]),
('Parliament', 'parliament_us.mp3', 'noun', 'B1', 'the group of people who are elected to make and change the laws of a country', '', 'The German parliament is called the ‘Bundestag’.', '', ARRAY[]::TEXT[]),
('Parliamentary', 'parliamentary_us.mp3', 'adjective', 'B1', 'connected with a parliament; having a parliament', '', 'parliamentary elections', '', ARRAY[]::TEXT[]),
('Part', 'part_us.mp3', 'noun', 'B1', 'some but not all of a thing', '', 'We spent part of the time in the museum.', '', ARRAY[]::TEXT[]),
('Part-time', 'part-time_us.mp3', 'adjective', 'B1', 'for part of the day or week in which people work', '', 'She''s looking for a part-time job.', '', ARRAY[]::TEXT[]),
('Partial', 'partial_us.mp3', 'adjective', 'B1', 'not complete or whole', '', 'It was only a partial solution to the problem.', '', ARRAY[]::TEXT[]),
('Partially', 'partially_us.mp3', 'adverb', 'B1', 'partly; not completely', '', 'The road was partially blocked by a fallen tree.', '', ARRAY[]::TEXT[]),
('Participant', 'participant_us.mp3', 'noun', 'B1', 'a person who is taking part in an activity or event', '', 'The average age of study participants was 48 years.', '', ARRAY[]::TEXT[]),
('Participate', 'participate_us.mp3', 'verb', 'B1', 'to take part in or become involved in an activity', '', 'Anyone who wishes to participate is welcome.', '', ARRAY[]::TEXT[]),
('Participation', 'participation_us.mp3', 'noun', 'B1', 'the act of taking part in an activity or event', '', 'a show with lots of audience participation', '', ARRAY[]::TEXT[]),
('Particular', 'particular_us.mp3', 'adjective', 'B1', 'used to emphasize that you are referring to one individual person, thing or type of thing and not others', '', 'There is one particular patient I''d like you to see.', '', ARRAY[]::TEXT[]),
('Particularly', 'particularly_us.mp3', 'adverb', 'B1', 'especially; more than usual or more than others', '', 'particularly useful/important/interesting', '', ARRAY[]::TEXT[]),
('Partly', 'partly_us.mp3', 'adverb', 'B1', 'to some extent; not completely', '', 'Some people are unwilling to attend the classes partly because of the cost involved.', '', ARRAY[]::TEXT[]),
('Partner', 'partner_us.mp3', 'noun', 'B1', 'a person that you are doing an activity with, such as dancing or playing a game', '', 'a dance/tennis partner', '', ARRAY[]::TEXT[]),
('Partnership', 'partnership_us.mp3', 'noun', 'B1', 'the state of being a partner in business', '', 'to be in/to go into partnership', '', ARRAY[]::TEXT[]),
('Party', 'party_us.mp3', 'noun', 'B1', 'a social occasion, often in a person’s home, at which people eat, drink, talk, dance and enjoy themselves', '', 'a dinner/tea/cocktail party', '', ARRAY[]::TEXT[]),
('Pass', 'pass_us.mp3', 'noun', 'B1', 'an official document or ticket that shows that you have the right to enter or leave a place, to travel on a bus or train, etc.', '', 'a boarding pass (= for a plane)', '', ARRAY[]::TEXT[]),
('Pass', 'pass_us.mp3', 'verb', 'B1', 'to achieve the required standard in an exam, a test, etc.', '', 'I''m not really expecting to pass first time.', '', ARRAY[]::TEXT[]),
('Passage', 'passage_us.mp3', 'noun', 'B1', 'a long narrow area with walls on either side that connects one room or place with another', '', 'A dark narrow passage led to the main hall.', '', ARRAY[]::TEXT[]),
('Passenger', 'passenger_us.mp3', 'noun', 'B1', 'a person who is travelling in a car, bus, train, plane or ship and who is not driving it or working on it', '', 'airline/cruise/rail/bus passengers', '', ARRAY[]::TEXT[]),
('Passing', 'passing_us.mp3', 'noun', 'B1', 'the process of time going by', '', 'The colour of the wood darkens with the passing of time.', '', ARRAY[]::TEXT[]),
('Passion', 'passion_us.mp3', 'noun', 'B1', 'a very strong feeling of love, hate, anger, enthusiasm, etc.', '', 'I admire the passion and commitment shown by the players.', '', ARRAY[]::TEXT[]),
('Passionate', 'passionate_us.mp3', 'adjective', 'B1', 'having or showing strong feelings of sexual love or of anger, etc.', '', 'to have a passionate nature', '', ARRAY[]::TEXT[]),
('Passive', 'passive_us.mp3', 'adjective', 'B1', 'accepting what happens or what people do without trying to change anything or oppose them', '', 'He played a passive role in the relationship.', '', ARRAY[]::TEXT[]),
('Passport', 'passport_us.mp3', 'noun', 'B1', 'an official document that identifies you as a citizen of a particular country, and that you may have to show when you enter or leave a country', '', 'a valid passport', '', ARRAY[]::TEXT[]),
('Password', 'password_us.mp3', 'noun', 'B1', 'a series of letters, numbers, etc. that you must type into a computer or computer system in order to be able to use it', '', 'Enter a username and password to get into the system.', '', ARRAY[]::TEXT[]),
('Past', 'past_us.mp3', 'adjective', 'B1', 'gone by in time', '', 'in past years/centuries', '', ARRAY[]::TEXT[]),
('Past', 'past_us.mp3', 'adverb', 'B1', 'from one side of something to the other', '', 'She smiled at me as she walked past.', '', ARRAY[]::TEXT[]),
('Past', 'past_us.mp3', 'noun', 'B1', 'the time that has gone by; things that happened in an earlier time', '', 'in the past, I used to go there often in the past.', '', ARRAY[]::TEXT[]),
('Past', 'past_us.mp3', 'preposition', 'B1', 'later than something', '', 'half past two', '', ARRAY[]::TEXT[]),
('Pastor', 'pastor_us.mp3', 'noun', 'B1', 'a minister in charge of a Christian church or group, especially in some Nonconformist churches', '', 'He was ordained a pastor in the Lutheran Church.', '', ARRAY[]::TEXT[]),
('Patch', 'patch_us.mp3', 'noun', 'B1', 'a small area of something, especially one which is different from the area around it', '', 'a black dog with a white patch on its back', '', ARRAY[]::TEXT[]),
('Patent', 'patent_us.mp3', 'noun', 'B1', 'an official right to be the only person to make, use or sell a product or an invention; a document that proves this', '', 'patent on something, to apply for/obtain/take out a patent on an invention', '', ARRAY[]::TEXT[]),
('Path', 'path_us.mp3', 'noun', 'B1', 'a way or track that is built or is made by the action of people walking', '', 'a dirt/gravel/concrete path', '', ARRAY[]::TEXT[]),
('Pathway', 'pathway_us.mp3', 'noun', 'B1', 'a track that serves as a path', '', 'They came out of the woods and onto a pathway.', '', ARRAY[]::TEXT[]),
('Patience', 'patience_us.mp3', 'noun', 'B1', 'the ability to stay calm and accept a delay or something annoying without complaining', '', 'She has little patience with (= will not accept or consider) such views.', '', ARRAY[]::TEXT[]),
('Patient', 'patient_us.mp3', 'adjective', 'B1', 'able to wait for a long time or accept annoying behaviour or difficulties without becoming angry', '', 'You''ll just have to be patient and wait till I''m finished.', '', ARRAY[]::TEXT[]),
('Patient', 'patient_us.mp3', 'noun', 'B1', 'a person who is receiving medical treatment, especially in a hospital', '', 'cancer/AIDS/heart patients', '', ARRAY[]::TEXT[]),
('Patrol', 'patrol_us.mp3', 'noun', 'B1', 'the act of going to different parts of a building, an area, etc. to make sure that there is no trouble or crime', '', 'Security guards make regular patrols at night.', '', ARRAY[]::TEXT[]),
('Patrol', 'patrol_us.mp3', 'verb', 'B1', 'to go around an area or a building at regular times to check that it is safe and that there is no trouble', '', 'Troops patrolled the border day and night.', '', ARRAY[]::TEXT[]),
('Patron', 'patron_us.mp3', 'noun', 'B1', 'a person who gives money and support to artists and writers', '', 'Frederick the Great was the patron of many artists.', '', ARRAY[]::TEXT[]),
('Pattern', 'pattern_us.mp3', 'noun', 'B1', 'the regular way in which something happens or is done', '', 'changing patterns of urban life', '', ARRAY[]::TEXT[]),
('Pause', 'pause_us.mp3', 'noun', 'B1', 'a period of time during which somebody stops talking or stops what they are doing', '', 'There was a long pause before she answered.', '', ARRAY[]::TEXT[]),
('Pause', 'pause_us.mp3', 'verb', 'B1', 'to stop talking or doing something for a short time before continuing', '', 'Anita paused for a moment, then said: ‘All right’.', '', ARRAY[]::TEXT[]),
('Pay', 'pay_us.mp3', 'noun', 'B1', 'the money that somebody gets for doing regular work', '', 'Her job is hard work, but the pay is good.', '', ARRAY[]::TEXT[]),
('Pay', 'pay_us.mp3', 'verb', 'B1', 'to give somebody money for work, goods, services, etc.', '', 'Who''s paying?', '', ARRAY[]::TEXT[]),
('Payment', 'payment_us.mp3', 'noun', 'B1', 'the act of paying somebody/something or of being paid', '', 'What method of payment do you prefer?', '', ARRAY[]::TEXT[]),
('Peace', 'peace_us.mp3', 'noun', 'B1', 'a situation or a period of time in which there is no war or violence in a country or an area', '', 'world peace', '', ARRAY[]::TEXT[]),
('Peaceful', 'peaceful_us.mp3', 'adjective', 'B1', 'not involving a war, violence or argument', '', 'a peaceful protest/demonstration', '', ARRAY[]::TEXT[]),
('Peak', 'peak_us.mp3', 'noun', 'B1', 'the point when somebody/something is best, most successful, strongest, etc.', '', 'Traffic reaches its peak between 8 and 9 in the morning.', '', ARRAY[]::TEXT[]),
('Peasant', 'peasant_us.mp3', 'noun', 'B1', '(especially in the past, or in poorer countries) a farmer who owns or rents a small piece of land', '', 'peasant farmers', '', ARRAY[]::TEXT[]),
('Peculiar', 'peculiar_us.mp3', 'adjective', 'B1', 'strange or unusual, especially in a way that is unpleasant or makes you worried', '', 'a peculiar smell/taste', '', ARRAY[]::TEXT[]),
('Peer', 'peer_us.mp3', 'noun', 'B1', 'a person who is the same age or who has the same social status as you', '', 'She enjoys the respect of her peers.', '', ARRAY[]::TEXT[]),
('Pen', 'pen_us.mp3', 'noun', 'B1', 'an instrument made of plastic or metal used for writing with ink (= coloured liquid for writing, etc.)', '', 'an ink pen', '', ARRAY[]::TEXT[]),
('Penalty', 'penalty_us.mp3', 'noun', 'B1', 'a punishment for breaking a law, rule or contract', '', 'to impose a penalty', '', ARRAY[]::TEXT[]),
('Pencil', 'pencil_us.mp3', 'noun', 'B1', 'a narrow piece of wood, or a metal or plastic case, containing a black or coloured substance, used for drawing or writing', '', 'I''ll get a pencil and paper.', '', ARRAY[]::TEXT[]),
('Penny', 'penny_us.mp3', 'noun', 'B1', 'a small British coin and unit of money. There are 100 pence in one pound (£1).', '', 'He had a few pennies in his pocket.', '', ARRAY[]::TEXT[]),
('People', 'people_us.mp3', 'noun', 'B1', 'human beings; men, women and children', '', 'At least ten people were killed in the crash.', '', ARRAY[]::TEXT[]),
('Pepper', 'pepper_us.mp3', 'noun', 'B1', 'a powder made from dried berries (called peppercorns), used to give a hot, spicy taste to food', '', 'Season with salt and pepper', '', ARRAY[]::TEXT[]),
('Per', 'per_us.mp3', 'preposition', 'B1', 'used to express the cost or amount of something for each person, number used, distance travelled, etc.', '', 'Rooms cost £50 per person, per night.', '', ARRAY[]::TEXT[]),
('Per cent', 'per cent_us.mp3', 'adjective', 'B1', 'by, in or for every hundred', '', 'a 15 per cent rise in price', '', ARRAY[]::TEXT[]),
('Per cent', 'per cent_us.mp3', 'adverb', 'B1', 'by, in or for every hundred', '', 'a 15 per cent rise in price', '', ARRAY[]::TEXT[]),
('Per cent', 'per cent_us.mp3', 'noun', 'B1', 'one part in every hundred', '', 'per cent of something/somebody, Poor families spend about 80 to 90 per cent of their income on food.', '', ARRAY[]::TEXT[]),
('Perceive', 'perceive_us.mp3', 'verb', 'B1', 'to understand or think of somebody/something in a particular way', '', 'perceive somebody/something/yourself (as something), This discovery was perceived as a major breakthrough.', '', ARRAY[]::TEXT[]),
('Percentage', 'percentage_us.mp3', 'noun', 'B1', 'the number, amount or rate of something, expressed as if it is part of a total that is 100; a part or share of a whole', '', 'percentage of something/somebody, What percentage of the population is/are overweight?', '', ARRAY[]::TEXT[]),
('Perception', 'perception_us.mp3', 'noun', 'B1', 'an idea, a belief or an image you have as a result of how you see or understand something', '', 'a campaign to change public perception of the police', '', ARRAY[]::TEXT[]),
('Perfect', 'perfect_us.mp3', 'adjective', 'B1', 'having everything that is necessary; complete and without faults or weaknesses', '', 'in perfect condition', '', ARRAY[]::TEXT[]),
('Perfectly', 'perfectly_us.mp3', 'adverb', 'B1', 'completely', '', 'It''s perfectly normal to feel like this.', '', ARRAY[]::TEXT[]),
('Perform', 'perform_us.mp3', 'verb', 'B1', 'to entertain an audience by playing a piece of music, acting in a play, etc.', '', 'to perform a song/dance/play', '', ARRAY[]::TEXT[]),
('Performance', 'performance_us.mp3', 'noun', 'B1', 'the act of performing a play, concert or some other form of entertainment', '', 'The performance starts at seven.', '', ARRAY[]::TEXT[]),
('Perhaps', 'perhaps_us.mp3', 'adverb', 'B1', 'possibly', '', '‘Are you going to come?’ ‘Perhaps. I''ll see how I feel.’', '', ARRAY[]::TEXT[]),
('Period', 'period_us.mp3', 'noun', 'B1', 'a particular length of time', '', 'a long/an extended period', '', ARRAY[]::TEXT[]),
('Permanent', 'permanent_us.mp3', 'adjective', 'B1', 'lasting for a long time or for all time in the future; existing all the time', '', 'She was unable to find a permanent job.', '', ARRAY[]::TEXT[]),
('Permanently', 'permanently_us.mp3', 'adverb', 'B1', 'in a way that lasts for a long time or for all time in the future; in a way that exists all the time', '', 'The stroke left his right side permanently damaged.', '', ARRAY[]::TEXT[]),
('Permission', 'permission_us.mp3', 'noun', 'B1', 'the act of allowing somebody to do something, especially when this is done by somebody in a position of authority', '', 'permission for something, You must ask permission for all major expenditure.', '', ARRAY[]::TEXT[]),
('Permit', 'permit_us.mp3', 'noun', 'B1', 'an official document that gives somebody the right to do something, especially for a limited period of time', '', 'a parking/building permit', '', ARRAY[]::TEXT[]),
('Permit', 'permit_us.mp3', 'verb', 'B1', 'to allow somebody to do something or to allow something to happen', '', 'be permitted, Mobile phones are not permitted in the examination room.', '', ARRAY[]::TEXT[]),
('Persist', 'persist_us.mp3', 'verb', 'B1', 'to continue to do something despite difficulties or opposition, in a way that can seem unreasonable', '', 'persist in doing something, Why do you persist in blaming yourself for what happened?', '', ARRAY[]::TEXT[]),
('Persistent', 'persistent_us.mp3', 'adjective', 'B1', 'determined to do something despite difficulties, especially when other people are against you and think that you are being annoying or unreasonable', '', 'How do you deal with persistent salesmen who won''t take no for an answer?', '', ARRAY[]::TEXT[]),
('Person', 'person_us.mp3', 'noun', 'B1', 'a human as an individual', '', 'What sort of person would do a thing like that?', '', ARRAY[]::TEXT[]),
('Personal', 'personal_us.mp3', 'adjective', 'B1', 'your own; not belonging to or connected with anyone else', '', 'The novel is written from personal experience.', '', ARRAY[]::TEXT[]),
('Personality', 'personality_us.mp3', 'noun', 'B1', 'the various aspects of a person’s character that combine to make them different from other people', '', 'His wife has a strong personality.', '', ARRAY[]::TEXT[]),
('Personally', 'personally_us.mp3', 'adverb', 'B1', 'used to show that you are giving your own opinion about something', '', 'Personally, I prefer the second option.', '', ARRAY[]::TEXT[]),
('Personnel', 'personnel_us.mp3', 'noun', 'B1', 'the people who work for an organization or one of the armed forces', '', 'There is a severe shortage of skilled personnel.', '', ARRAY[]::TEXT[]),
('Perspective', 'perspective_us.mp3', 'noun', 'B1', 'a particular attitude towards something; a way of thinking about something', '', 'a global perspective', '', ARRAY[]::TEXT[]),
('Persuade', 'persuade_us.mp3', 'verb', 'B1', 'to make somebody do something by giving them good reasons for doing it', '', 'persuade somebody to do something, Try to persuade him to come.', '', ARRAY[]::TEXT[]),
('Pet', 'pet_us.mp3', 'noun', 'B1', 'an animal, a bird, etc. that you have at home for pleasure, rather than one that is kept for work or food', '', 'Do you have any pets?', '', ARRAY[]::TEXT[]),
('Petition', 'petition_us.mp3', 'noun', 'B1', 'a written document signed by a large number of people that asks somebody in a position of authority to do or change something', '', 'petition against something, Would you like to sign our petition against experiments on animals?', '', ARRAY[]::TEXT[]),
('Petrol', 'petrol_us.mp3', 'noun', 'B1', 'a liquid obtained from petroleum, used as fuel in car engines, etc.', '', 'to fill a car up with petrol', '', ARRAY[]::TEXT[]),
('Phase', 'phase_us.mp3', 'noun', 'B1', 'a stage in a process of change or development', '', 'during the initial/final phase', '', ARRAY[]::TEXT[]),
('Phenomenon', 'phenomenon_us.mp3', 'noun', 'B1', 'a fact or an event in nature or society, especially one that is not fully understood', '', 'cultural/natural phenomena', '', ARRAY[]::TEXT[]),
('Philosopher', 'philosopher_us.mp3', 'noun', 'B1', 'a person who studies or writes about philosophy', '', 'We studied the writings of the Greek philosopher Aristotle.', '', ARRAY[]::TEXT[]),
('Philosophical', 'philosophical_us.mp3', 'adjective', 'B1', 'connected with philosophy', '', 'the philosophical writings of Kant', '', ARRAY[]::TEXT[]),
('Philosophy', 'philosophy_us.mp3', 'noun', 'B1', 'the study of the nature and meaning of the universe and of human life', '', 'philosophy of something, the philosophy of science', '', ARRAY[]::TEXT[]),
('Phone', 'phone_us.mp3', 'noun', 'B1', 'a piece of equipment for talking to people who are not in the same place as you', '', 'I have to make a phone call.', '', ARRAY[]::TEXT[]),
('Phone', 'phone_us.mp3', 'verb', 'B1', 'to make a phone call to somebody', '', 'I was just phoning up for a chat.', '', ARRAY[]::TEXT[]),
('Photo', 'photo_us.mp3', 'noun', 'B1', 'a picture that is made by using a camera that stores images in digital form or that has a film sensitive to light inside it', '', 'a colour/black-and-white photo', '', ARRAY[]::TEXT[]),
('Photograph', 'photograph_us.mp3', 'noun', 'B1', 'a picture that is made by using a camera that stores images in digital form or that has a film sensitive to light inside it', '', 'aerial photographs of the crash site', '', ARRAY[]::TEXT[]),
('Photograph', 'photograph_us.mp3', 'verb', 'B1', 'to take a photograph of somebody/something', '', 'photograph somebody/something, a workshop on photographing wildlife', '', ARRAY[]::TEXT[]),
('Photographer', 'photographer_us.mp3', 'noun', 'B1', 'a person who takes photographs, especially as a job', '', 'a wedding/wildlife/fashion photographer', '', ARRAY[]::TEXT[]),
('Photography', 'photography_us.mp3', 'noun', 'B1', 'the art, process or job of taking photographs or filming something', '', 'Her hobbies include hiking and photography.', '', ARRAY[]::TEXT[]),
('Phrase', 'phrase_us.mp3', 'noun', 'B1', 'a group of words that have a particular meaning when used together', '', 'a memorable/catchy phrase', '', ARRAY[]::TEXT[]),
('Physical', 'physical_us.mp3', 'adjective', 'B1', 'connected with a person’s body rather than their mind', '', 'physical activity/fitness', '', ARRAY[]::TEXT[]),
('Physician', 'physician_us.mp3', 'noun', 'B1', 'a doctor, especially one who is a specialist in general medicine and not surgery', '', 'Dr Dennett is a practicing family physician in Atlanta.', '', ARRAY[]::TEXT[]),
('Physics', 'physics_us.mp3', 'noun', 'B1', 'the scientific study of matter and energy and the relationships between them, including the study of forces, heat, light, sound, electricity and the structure of atoms', '', 'a degree in physics', '', ARRAY[]::TEXT[]),
('Piano', 'piano_us.mp3', 'noun', 'B1', 'a large musical instrument played by pressing the black and white keys on the keyboard. The sound is produced by small hammers hitting the metal strings inside the piano.', '', 'to play the piano', '', ARRAY[]::TEXT[]),
('Pick', 'pick_us.mp3', 'noun', 'B1', 'an act of choosing something', '', 'Take your pick (= choose).', '', ARRAY[]::TEXT[]),
('Pick', 'pick_us.mp3', 'verb', 'B1', 'to choose somebody/something from a group of people or things', '', 'pick somebody/something, Pick a number from one to twenty.', '', ARRAY[]::TEXT[]),
('Picture', 'picture_us.mp3', 'noun', 'B1', 'a painting or drawing, etc. that shows a scene, a person or thing', '', 'He likes books with lots of pictures in them.', '', ARRAY[]::TEXT[]),
('Picture', 'picture_us.mp3', 'verb', 'B1', 'to imagine somebody/something; to create an image of somebody/something in your mind', '', 'picture somebody/something, I could picture the scene clearly.', '', ARRAY[]::TEXT[]),
('Piece', 'piece_us.mp3', 'noun', 'B1', 'an amount of something that has been cut or separated from the rest of it; a standard amount of something', '', 'piece of something, She wrote something on a small piece of paper.', '', ARRAY[]::TEXT[]),
('Pig', 'pig_us.mp3', 'noun', 'B1', 'an animal with pink, black or brown skin, short legs, a broad nose and a short curly tail. Pigs are kept on farms for their meat (called pork) or live in the wild.', '', 'a pig farmer', '', ARRAY[]::TEXT[]),
('Pile', 'pile_us.mp3', 'noun', 'B1', 'a number of things that have been placed on top of each other', '', 'pile of something, a pile of clothes/paper', '', ARRAY[]::TEXT[]),
('Pile', 'pile_us.mp3', 'verb', 'B1', 'to put things one on top of another; to form a pile', '', 'pile something, She piled the boxes one on top of the other.', '', ARRAY[]::TEXT[]),
('Pill', 'pill_us.mp3', 'noun', 'B1', 'a small flat round piece of medicine that you swallow whole, without biting it', '', 'a vitamin pill', '', ARRAY[]::TEXT[]),
('Pilot', 'pilot_us.mp3', 'noun', 'B1', 'a person who operates the controls of an aircraft, especially as a job', '', 'an airline pilot', '', ARRAY[]::TEXT[]),
('Pin', 'pin_us.mp3', 'noun', 'B1', 'a short thin piece of stiff wire with a sharp point at one end and a round head at the other, used especially for fastening together pieces of cloth when sewing', '', 'Use pins to keep the patch in place while you sew it on.', '', ARRAY[]::TEXT[]),
('Pin', 'pin_us.mp3', 'verb', 'B1', 'to attach something onto another thing or fasten things together with a pin, etc.', '', 'She pinned the badge onto her jacket.', '', ARRAY[]::TEXT[]),
('Pink', 'pink_us.mp3', 'adjective', 'B1', 'pale red in colour', '', 'pale pink roses', '', ARRAY[]::TEXT[]),
('Pink', 'pink_us.mp3', 'noun', 'B1', 'the colour that is produced when you mix red and white together', '', 'She was dressed in pink.', '', ARRAY[]::TEXT[]),
('Pioneer', 'pioneer_us.mp3', 'noun', 'B1', 'a person who is the first to study and develop a particular area of knowledge, culture, etc. that other people then continue to develop', '', 'a pioneer in the field of microsurgery', '', ARRAY[]::TEXT[]),
('Pioneer', 'pioneer_us.mp3', 'verb', 'B1', 'when somebody pioneers something, they are one of the first people to do, discover or use something new', '', 'a new technique pioneered by surgeons in a London hospital', '', ARRAY[]::TEXT[]),
('Pipe', 'pipe_us.mp3', 'noun', 'B1', 'a tube through which liquids and gases can flow', '', 'Both hot and cold water pipes should be properly insulated.', '', ARRAY[]::TEXT[]),
('Pipeline', 'pipeline_us.mp3', 'noun', 'B1', 'a series of pipes that are usually underground and are used for carrying oil, gas, etc. over long distances', '', 'There are plans to lay a gas pipeline through the region.', '', ARRAY[]::TEXT[]),
('Pirate', 'pirate_us.mp3', 'noun', 'B1', '(especially in the past) a person on a ship who attacks other ships at sea in order to steal from them', '', 'There were reports that a pirate ship had come looking for treasure in the cove.', '', ARRAY[]::TEXT[]),
('Pit', 'pit_us.mp3', 'noun', 'B1', 'a large deep hole in the ground', '', 'We dug a deep pit in the yard.', '', ARRAY[]::TEXT[]),
('Pitch', 'pitch_us.mp3', 'noun', 'B1', 'an area of ground specially prepared and marked for playing a sports game', '', 'a football pitch', '', ARRAY[]::TEXT[]),
('Pity', 'pity_us.mp3', 'noun', 'B1', 'used to show that you are disappointed about something', '', 'a pity (that…), It''s a pity that you can''t stay longer.', '', ARRAY[]::TEXT[]),
('Place', 'place_us.mp3', 'noun', 'B1', 'a particular position, point or area', '', 'in a place, Keep your purse in a safe place.', '', ARRAY[]::TEXT[]),
('Place', 'place_us.mp3', 'verb', 'B1', 'to put something in a particular place, especially when you do it carefully or deliberately', '', 'He placed his hand on her shoulder.', '', ARRAY[]::TEXT[]),
('Placement', 'placement_us.mp3', 'noun', 'B1', 'the act of finding somebody a suitable job or place to live', '', 'a job placement service', '', ARRAY[]::TEXT[]),
('Plain', 'plain_us.mp3', 'adjective', 'B1', 'not decorated or complicated; simple', '', 'a plain but elegant dress', '', ARRAY[]::TEXT[]),
('Plan', 'plan_us.mp3', 'noun', 'B1', 'something that you intend to do or achieve', '', 'plan for something, Do you have any plans for the summer?', '', ARRAY[]::TEXT[]),
('Plan', 'plan_us.mp3', 'verb', 'B1', 'to make detailed arrangements for something you want to do in the future', '', 'plan something, to plan a trip', '', ARRAY[]::TEXT[]),
('Plane', 'plane_us.mp3', 'noun', 'B1', 'a flying vehicle with wings and one or more engines', '', 'a passenger/fighter/military/private plane', '', ARRAY[]::TEXT[]),
('Planet', 'planet_us.mp3', 'noun', 'B1', 'a large round object in space that moves around a star (such as the sun) and receives light from it', '', 'the planets of our solar system', '', ARRAY[]::TEXT[]),
('Planning', 'planning_us.mp3', 'noun', 'B1', 'the act or process of making plans for something', '', 'The department is responsible for all financial planning.', '', ARRAY[]::TEXT[]),
('Plant', 'plant_us.mp3', 'noun', 'B1', 'a living thing that grows in the earth and usually has a stem, leaves and roots, especially one that is smaller than a tree or bush', '', 'All plants need light and water.', '', ARRAY[]::TEXT[]),
('Plant', 'plant_us.mp3', 'verb', 'B1', 'to put plants, seeds, etc. in the ground to grow', '', 'to plant a tree/seed/crop', '', ARRAY[]::TEXT[]),
('Plastic', 'plastic_us.mp3', 'adjective', 'B1', 'made of plastic', '', 'a plastic bag/bottle/cup', '', ARRAY[]::TEXT[]),
('Plastic', 'plastic_us.mp3', 'noun', 'B1', 'a light strong material that is produced by chemical processes and can be formed into shapes when heated. There are many different types of plastic, used to make different objects and fabrics.', '', 'The pipes should be made of plastic.', '', ARRAY[]::TEXT[]),
('Plate', 'plate_us.mp3', 'noun', 'B1', 'a flat, usually round, dish that you put food on', '', 'sandwiches on a plate', '', ARRAY[]::TEXT[]),
('Platform', 'platform_us.mp3', 'noun', 'B1', 'the raised flat area next to the track at a train station where you get on or off the train', '', '(British English), What platform does it go from?', '', ARRAY[]::TEXT[]),
('Play', 'play_us.mp3', 'noun', 'B1', 'a piece of writing performed by actors in a theatre or on television or radio', '', 'a stage/radio play', '', ARRAY[]::TEXT[]),
('Play', 'play_us.mp3', 'verb', 'B1', 'to do things for pleasure, as children do; to enjoy yourself, rather than work', '', 'You''ll have to play inside today.', '', ARRAY[]::TEXT[]),
('Player', 'player_us.mp3', 'noun', 'B1', 'a person who takes part in a game or sport', '', 'a football/tennis/chess player', '', ARRAY[]::TEXT[]),
('Plea', 'plea_us.mp3', 'noun', 'B1', 'a serious emotional request, especially for something needing action now', '', 'plea for something, She made an impassioned plea for help.', '', ARRAY[]::TEXT[]),
('Plead', 'plead_us.mp3', 'verb', 'B1', 'to ask somebody for something in a very strong and serious way', '', 'plead (with somebody) (to do something), She pleaded with him not to go.', '', ARRAY[]::TEXT[]),
('Pleasant', 'pleasant_us.mp3', 'adjective', 'B1', 'fun, attractive, or giving pleasure', '', 'a pleasant evening/atmosphere/walk', '', ARRAY[]::TEXT[]),
('Please', 'please_us.mp3', 'exclamation', 'B1', 'used as a polite way of asking for something or telling somebody to do something', '', 'Please sit down.', '', ARRAY[]::TEXT[]),
('Please', 'please_us.mp3', 'verb', 'B1', 'to make somebody happy', '', 'please somebody, You can''t please everybody.', '', ARRAY[]::TEXT[]),
('Pleased', 'pleased_us.mp3', 'adjective', 'B1', 'feeling happy about something', '', 'You''re coming? I''m so pleased.', '', ARRAY[]::TEXT[]),
('Pleasure', 'pleasure_us.mp3', 'noun', 'B1', 'a state of feeling or being happy or satisfied', '', 'His eyes lit up with pleasure.', '', ARRAY[]::TEXT[]),
('Pledge', 'pledge_us.mp3', 'noun', 'B1', 'a serious promise', '', 'pledge (of something), a pledge of support', '', ARRAY[]::TEXT[]),
('Pledge', 'pledge_us.mp3', 'verb', 'B1', 'to formally promise to give or do something', '', 'pledge something, Japan has pledged $100 million in humanitarian aid.', '', ARRAY[]::TEXT[]),
('Plenty', 'plenty_us.mp3', 'pronoun', 'B1', 'a large amount; as much or as many as you need', '', 'plenty of eggs/money/time', '', ARRAY[]::TEXT[]),
('Plot', 'plot_us.mp3', 'noun', 'B1', 'the series of events that form the story of a novel, play, film, etc.', '', 'It''s hard to follow the plot of the film.', '', ARRAY[]::TEXT[]),
('Plot', 'plot_us.mp3', 'verb', 'B1', 'to make a secret plan to harm somebody, especially a government or its leader', '', 'plot with somebody, It is claimed he plotted with the country''s enemies.', '', ARRAY[]::TEXT[]),
('Plug', 'plug_us.mp3', 'noun', 'B1', 'a small plastic object with two or three metal pins that connects a piece of electrical equipment to the main supply of electricity', '', 'The iron is fitted with a three-pin plug.', '', ARRAY[]::TEXT[]),
('Plug', 'plug_us.mp3', 'verb', 'B1', 'to fill a hole with a substance or piece of material that fits tightly into it', '', 'He plugged the hole in the pipe with an old rag.', '', ARRAY[]::TEXT[]),
('Plunge', 'plunge_us.mp3', 'verb', 'B1', 'to move or make somebody/something move suddenly forwards and/or downwards', '', '+ adv./prep., She lost her balance and plunged 100 feet to her death.', '', ARRAY[]::TEXT[]),
('Plus', 'plus_us.mp3', 'adjective', 'B1', 'used after a number to show that the real number or amount is more than the one mentioned', '', 'The work will cost £10 000 plus.', '', ARRAY[]::TEXT[]),
('Plus', 'plus_us.mp3', 'conjunction', 'B1', 'used to add more information', '', 'I''ve got too much on at work. Plus my father is not well.', '', ARRAY[]::TEXT[]),
('Plus', 'plus_us.mp3', 'noun', 'B1', 'an advantage; a good thing', '', 'Knowledge of French is a plus in her job.', '', ARRAY[]::TEXT[]),
('Plus', 'plus_us.mp3', 'preposition', 'B1', 'used when the two numbers or amounts mentioned are being added together', '', 'Two plus five is seven.', '', ARRAY[]::TEXT[]),
('Pocket', 'pocket_us.mp3', 'noun', 'B1', 'a small piece of material like a small bag sewn into or onto a piece of clothing so that you can carry things in it', '', 'a jacket/coat/shirt/trouser pocket', '', ARRAY[]::TEXT[]),
('Poem', 'poem_us.mp3', 'noun', 'B1', 'a piece of writing in which the words are chosen for their sound and the images they suggest, not just for their obvious meanings. The words are arranged in separate lines, usually with a repeated rhythm, and often the lines rhyme at the end.', '', 'His collected poems were published after the war.', '', ARRAY[]::TEXT[]),
('Poet', 'poet_us.mp3', 'noun', 'B1', 'a person who writes poems', '', 'an internationally renowned poet', '', ARRAY[]::TEXT[]),
('Poetry', 'poetry_us.mp3', 'noun', 'B1', 'poems in general; poems as a genre of literature', '', 'lyric/epic poetry', '', ARRAY[]::TEXT[]),
('Point', 'point_us.mp3', 'noun', 'B1', 'a thing that somebody says or writes giving their opinion or stating a fact', '', 'She made several interesting points in the article.', '', ARRAY[]::TEXT[]),
('Point', 'point_us.mp3', 'verb', 'B1', 'to stretch out your finger or something held in your hand towards somebody/something in order to show somebody where a person or thing is', '', 'point at somebody/something, ‘What''s your name?’ he asked, pointing at the child with his pen.', '', ARRAY[]::TEXT[]),
('Pointed', 'pointed_us.mp3', 'adjective', 'B1', 'having a sharp end', '', 'a pointed chin', '', ARRAY[]::TEXT[]),
('Poison', 'poison_us.mp3', 'noun', 'B1', 'a substance that causes death or harm if it gets into the body', '', 'Some mushrooms contain a deadly poison.', '', ARRAY[]::TEXT[]),
('Poison', 'poison_us.mp3', 'verb', 'B1', 'to harm or kill a person or an animal by giving them poison', '', 'poison somebody/yourself, He was believed to poison his enemies.', '', ARRAY[]::TEXT[]),
('Poisonous', 'poisonous_us.mp3', 'adjective', 'B1', 'causing death or illness if swallowed or taken into the body', '', 'poisonous chemicals/fumes/plants', '', ARRAY[]::TEXT[]),
('Pole', 'pole_us.mp3', 'noun', 'B1', 'a long thin straight piece of wood or metal, especially one with the end placed in the ground, used as a support', '', 'a tent pole', '', ARRAY[]::TEXT[]),
('Police', 'police_us.mp3', 'noun', 'B1', 'an official organization whose job is to make people obey the law and to prevent and solve crime; the people who work for this organization', '', 'Get out of the house or I''ll call the police.', '', ARRAY[]::TEXT[]),
('Policeman', 'policeman_us.mp3', 'noun', 'B1', 'a male police officer', '', 'a plain-clothes/uniformed policeman', '', ARRAY[]::TEXT[]),
('Policy', 'policy_us.mp3', 'noun', 'B1', 'a plan of action agreed or chosen by a political party, a business, etc.', '', 'policy on something, the present government’s policy on education', '', ARRAY[]::TEXT[]),
('Polite', 'polite_us.mp3', 'adjective', 'B1', 'having or showing good manners and respect for the feelings of others', '', 'polite to somebody, Please be polite to our guests.', '', ARRAY[]::TEXT[]),
('Political', 'political_us.mp3', 'adjective', 'B1', 'connected with the state, government or public affairs', '', 'a monarch without political power', '', ARRAY[]::TEXT[]),
('Politician', 'politician_us.mp3', 'noun', 'B1', 'a person whose job involves politics, especially as an elected member of parliament, etc.', '', 'democratically elected politicians', '', ARRAY[]::TEXT[]),
('Politics', 'politics_us.mp3', 'noun', 'B1', 'the activities involved in getting and using power in public life, and being able to influence decisions that affect a country or a society', '', 'world/international politics', '', ARRAY[]::TEXT[]),
('Poll', 'poll_us.mp3', 'noun', 'B1', 'the process of questioning people who are representative of a larger group in order to get information about the general opinion', '', 'to carry out/conduct a poll', '', ARRAY[]::TEXT[]),
('Pollution', 'pollution_us.mp3', 'noun', 'B1', 'the process of making air, water, soil, etc. dirty; the state of being dirty', '', 'air/water pollution', '', ARRAY[]::TEXT[]),
('Pond', 'pond_us.mp3', 'noun', 'B1', 'a small area of still water, especially one that is artificial', '', 'a fish pond', '', ARRAY[]::TEXT[]),
('Pool', 'pool_us.mp3', 'noun', 'B1', 'an area of water that has been created for people to swim in', '', 'an indoor/outdoor pool', '', ARRAY[]::TEXT[]),
('Poor', 'poor_us.mp3', 'adjective', 'B1', 'having very little money; not having enough money for basic needs', '', 'They were too poor to buy shoes for the kids.', '', ARRAY[]::TEXT[]),
('Pop', 'pop_us.mp3', 'adjective', 'B1', 'connected with modern popular music', '', 'a pop song', '', ARRAY[]::TEXT[]),
('Pop', 'pop_us.mp3', 'noun', 'B1', 'popular music of the sort that has been popular since the 1950s, usually with a strong rhythm and simple tunes, often contrasted with rock, soul and other forms of popular music', '', 'rock, pop and soul', '', ARRAY[]::TEXT[]),
('Pop', 'pop_us.mp3', 'verb', 'B1', 'to make a short explosive sound; to cause something to make this sound', '', 'the sound of corks popping', '', ARRAY[]::TEXT[]),
('Popular', 'popular_us.mp3', 'adjective', 'B1', 'liked or enjoyed by a large number of people', '', 'Andalucia is a popular tourist destination.', '', ARRAY[]::TEXT[]),
('Popularity', 'popularity_us.mp3', 'noun', 'B1', 'the state of being liked, enjoyed or supported by a large number of people', '', 'the increasing popularity of cycling', '', ARRAY[]::TEXT[]),
('Population', 'population_us.mp3', 'noun', 'B1', 'all the people who live in a particular area, city or country; the total number of people who live there', '', 'One third of the world’s population consumes/consume two thirds of the world’s resources.', '', ARRAY[]::TEXT[]),
('Port', 'port_us.mp3', 'noun', 'B1', 'a town or city with a harbour, especially one where ships load and unload goods', '', 'a container/fishing ports', '', ARRAY[]::TEXT[]),
('Portfolio', 'portfolio_us.mp3', 'noun', 'B1', 'a thin flat case used for carrying documents, drawings, etc.', '', 'I left my portfolio on the train.', '', ARRAY[]::TEXT[]),
('Portion', 'portion_us.mp3', 'noun', 'B1', 'one part of something larger', '', 'a substantial/significant portion of the population', '', ARRAY[]::TEXT[]),
('Portrait', 'portrait_us.mp3', 'noun', 'B1', 'a painting, drawing or photograph of a person, especially of the head and shoulders', '', 'portrait of somebody, a portrait of his wife', '', ARRAY[]::TEXT[]),
('Portray', 'portray_us.mp3', 'verb', 'B1', 'to show somebody/something in a picture; to describe somebody/something in a piece of writing', '', 'The painting portrays the duke’s third wife.', '', ARRAY[]::TEXT[]),
('Pose', 'pose_us.mp3', 'verb', 'B1', 'to create a threat, problem, etc. that has to be dealt with', '', 'to pose a threat/risk/challenge/danger', '', ARRAY[]::TEXT[]),
('Position', 'position_us.mp3', 'noun', 'B1', 'the place where somebody/something is located', '', 'Where would be the best position for the lights?', '', ARRAY[]::TEXT[]),
('Position', 'position_us.mp3', 'verb', 'B1', 'to put somebody/something in a particular position', '', 'position somebody/something/yourself + adv./prep., She quickly positioned herself behind the desk.', '', ARRAY[]::TEXT[]),
('Positive', 'positive_us.mp3', 'adjective', 'B1', 'good or useful', '', 'The tests have so far yielded positive results.', '', ARRAY[]::TEXT[]),
('Positive', 'positive_us.mp3', 'noun', 'B1', 'a good or useful quality or aspect', '', 'What are the positives and negatives of going this route?', '', ARRAY[]::TEXT[]),
('Possess', 'possess_us.mp3', 'verb', 'B1', 'to have or own something', '', 'He was charged with possessing a shotgun without a licence.', '', ARRAY[]::TEXT[]),
('Possession', 'possession_us.mp3', 'noun', 'B1', 'something that you own or have with you at a particular time', '', 'Prisoners were allowed no personal possessions.', '', ARRAY[]::TEXT[]),
('Possibility', 'possibility_us.mp3', 'noun', 'B1', 'a thing that may happen or be true; the fact that something might happen or be true, but is not certain', '', 'Bankruptcy is a real possibility if sales don''t improve.', '', ARRAY[]::TEXT[]),
('Possible', 'possible_us.mp3', 'adjective', 'B1', 'that can be done or achieved', '', 'possible to do something, New technology has made it possible to communicate more easily.', '', ARRAY[]::TEXT[]),
('Possibly', 'possibly_us.mp3', 'adverb', 'B1', 'used to say that something might exist, happen or be true, but you are not certain', '', 'It was possibly their worst performance ever.', '', ARRAY[]::TEXT[]),
('Post', 'post_us.mp3', 'noun', 'B1', 'the official system used for sending and delivering letters, packages, etc.', '', 'by post, I''ll send the original to you by post.', '', ARRAY[]::TEXT[]),
('Post', 'post_us.mp3', 'verb', 'B1', 'to send a letter, etc. to somebody by post', '', 'post something, The cost of posting a letter has gone up again.', '', ARRAY[]::TEXT[]),
('Post-war', 'post-war_us.mp3', 'adjective', 'B1', 'existing, happening or made in the period after a war, especially the Second World War', '', 'the post-war years', '', ARRAY[]::TEXT[]),
('Poster', 'poster_us.mp3', 'noun', 'B1', 'a large notice, often with a picture on it, that is put in a public place to advertise something', '', 'campaign/election posters', '', ARRAY[]::TEXT[]),
('Postpone', 'postpone_us.mp3', 'verb', 'B1', 'to arrange for an event, etc. to take place at a later time or date than originally planned', '', 'postpone something, The game has already been postponed three times.', '', ARRAY[]::TEXT[]),
('Pot', 'pot_us.mp3', 'noun', 'B1', 'a deep round container used for cooking things in', '', 'pots and pans', '', ARRAY[]::TEXT[]),
('Potato', 'potato_us.mp3', 'noun', 'B1', 'a round white vegetable with a brown or red skin that grows underground as part of a plant also called a potato', '', 'Will you peel the potatoes for me?', '', ARRAY[]::TEXT[]),
('Potential', 'potential_us.mp3', 'adjective', 'B1', 'that can develop into something or be developed in the future', '', 'potential customers/buyers/investors/clients', '', ARRAY[]::TEXT[]),
('Potential', 'potential_us.mp3', 'noun', 'B1', 'the possibility of something happening or being developed or used', '', 'potential for something, the potential for change', '', ARRAY[]::TEXT[]),
('Potentially', 'potentially_us.mp3', 'adverb', 'B1', 'used to say that something may develop into something', '', 'a potentially dangerous situation', '', ARRAY[]::TEXT[]),
('Pound', 'pound_us.mp3', 'noun', 'B1', 'the unit of money in the UK, worth 100 pence', '', 'a ten-pound note', '', ARRAY[]::TEXT[]),
('Pour', 'pour_us.mp3', 'verb', 'B1', 'to make a liquid or other substance flow from a container in a continuous stream, especially by holding the container at an angle', '', 'pour something + adv./prep., Pour the sauce over the pasta.', '', ARRAY[]::TEXT[]),
('Poverty', 'poverty_us.mp3', 'noun', 'B1', 'the state of being poor', '', 'conditions of extreme/abject poverty', '', ARRAY[]::TEXT[]),
('Powder', 'powder_us.mp3', 'noun', 'B1', 'a dry mass of very small fine pieces or grains', '', 'milk/chilli/cocoa powder', '', ARRAY[]::TEXT[]),
('Power', 'power_us.mp3', 'noun', 'B1', 'the ability to control people or things', '', 'power to do something, He has the power to make things very unpleasant for us.', '', ARRAY[]::TEXT[]),
('Power', 'power_us.mp3', 'verb', 'B1', 'to supply a machine or vehicle with the energy that makes it work', '', 'be powered (by something), The aircraft is powered by a jet engine.', '', ARRAY[]::TEXT[]),
('Powerful', 'powerful_us.mp3', 'adjective', 'B1', 'being able to control and influence people and events', '', 'an incredibly powerful organization', '', ARRAY[]::TEXT[]),
('Practical', 'practical_us.mp3', 'adjective', 'B1', 'connected with real situations rather than with ideas or theories', '', 'to have gained practical experience of the work', '', ARRAY[]::TEXT[]),
('Practice', 'practice_us.mp3', 'noun', 'B1', 'doing an activity or training regularly so that you can improve your skill; the time you spend doing this', '', 'conversation practice', '', ARRAY[]::TEXT[]),
('Practise', 'practise_us.mp3', 'verb', 'B1', 'to do an activity or train regularly so that you can improve your skill', '', 'You need to practise every day.', '', ARRAY[]::TEXT[]),
('Practitioner', 'practitioner_us.mp3', 'noun', 'B1', 'a person who works in a profession, especially medicine or law', '', 'dental practitioners', '', ARRAY[]::TEXT[]),
('Praise', 'praise_us.mp3', 'noun', 'B1', 'words that show that you approve of and admire somebody/something', '', 'The team coach singled out two players for special praise.', '', ARRAY[]::TEXT[]),
('Praise', 'praise_us.mp3', 'verb', 'B1', 'to say that you approve of and admire somebody/something', '', 'praise somebody/something, She praised his cooking.', '', ARRAY[]::TEXT[]),
('Pray', 'pray_us.mp3', 'verb', 'B1', 'to speak to God, especially to give thanks or ask for help', '', 'They knelt down and prayed.', '', ARRAY[]::TEXT[]),
('Prayer', 'prayer_us.mp3', 'noun', 'B1', 'words that you say to God giving thanks or asking for help', '', 'to say your prayers', '', ARRAY[]::TEXT[]),
('Preach', 'preach_us.mp3', 'verb', 'B1', 'to give a religious talk in a public place, especially in a church during a service', '', 'She preached to the congregation about forgiveness.', '', ARRAY[]::TEXT[]),
('Precede', 'precede_us.mp3', 'verb', 'B1', 'to happen before something or come before something/somebody in order', '', 'the years preceding the war', '', ARRAY[]::TEXT[]),
('Precedent', 'precedent_us.mp3', 'noun', 'B1', 'an official action or decision that has happened in the past and that is seen as an example or a rule to be followed in a similar situation later', '', 'The ruling set a precedent for future libel cases.', '', ARRAY[]::TEXT[]),
('Precious', 'precious_us.mp3', 'adjective', 'B1', 'rare and worth a lot of money', '', 'a precious vase', '', ARRAY[]::TEXT[]),
('Precise', 'precise_us.mp3', 'adjective', 'B1', 'clear and accurate', '', 'precise details/instructions/measurements', '', ARRAY[]::TEXT[]),
('Precisely', 'precisely_us.mp3', 'adverb', 'B1', 'exactly', '', 'They look precisely the same to me.', '', ARRAY[]::TEXT[]),
('Precision', 'precision_us.mp3', 'noun', 'B1', 'the quality of being exact, accurate and careful', '', 'Her writing is imaginative but lacks precision.', '', ARRAY[]::TEXT[]),
('Predator', 'predator_us.mp3', 'noun', 'B1', 'an animal that kills and eats other animals', '', 'Some animals have no natural predators.', '', ARRAY[]::TEXT[]),
('Predecessor', 'predecessor_us.mp3', 'noun', 'B1', 'a person who did a job before somebody else', '', 'The new president reversed many of the policies of his predecessor.', '', ARRAY[]::TEXT[]),
('Predict', 'predict_us.mp3', 'verb', 'B1', 'to say that something will happen in the future', '', 'predict something, a reliable method of predicting earthquakes', '', ARRAY[]::TEXT[]),
('Predictable', 'predictable_us.mp3', 'adjective', 'B1', 'if something is predictable, you know in advance that it will happen or what it will be like', '', 'a predictable result', '', ARRAY[]::TEXT[]),
('Prediction', 'prediction_us.mp3', 'noun', 'B1', 'a statement that says what you think will happen; the act of making such a statement', '', 'The results of the experiment confirmed our predictions.', '', ARRAY[]::TEXT[]),
('Predominantly', 'predominantly_us.mp3', 'adverb', 'B1', 'mostly; mainly', '', 'She works in a predominantly male environment.', '', ARRAY[]::TEXT[]),
('Prefer', 'prefer_us.mp3', 'verb', 'B1', 'to like one thing or person better than another; to choose one thing rather than something else because you like it better', '', 'prefer something, ‘Coffee or tea?’ ‘I''d prefer tea, thanks.’', '', ARRAY[]::TEXT[]),
('Preference', 'preference_us.mp3', 'noun', 'B1', 'a greater interest in or desire for somebody/something than somebody/something else', '', 'It''s a matter of personal preference.', '', ARRAY[]::TEXT[]),
('Pregnancy', 'pregnancy_us.mp3', 'noun', 'B1', 'the state of being pregnant', '', 'a pregnancy test', '', ARRAY[]::TEXT[]),
('Pregnant', 'pregnant_us.mp3', 'adjective', 'B1', 'having a baby or young animal developing inside her/its body', '', 'My wife is pregnant.', '', ARRAY[]::TEXT[]),
('Prejudice', 'prejudice_us.mp3', 'noun', 'B1', 'an unreasonable dislike of or preference for a person, group, custom, etc., especially when it is based on their race, religion, sex, etc.', '', 'a victim of racial prejudice', '', ARRAY[]::TEXT[]),
('Preliminary', 'preliminary_us.mp3', 'adjective', 'B1', 'happening before a more important action or event', '', 'After a few preliminary remarks he announced the winners.', '', ARRAY[]::TEXT[]),
('Premier', 'premier_us.mp3', 'adjective', 'B1', 'most important, famous or successful', '', 'one of the country’s premier chefs', '', ARRAY[]::TEXT[]),
('Premise', 'premise_us.mp3', 'noun', 'B1', 'a statement or an idea that forms the basis for a reasonable line of argument', '', 'the basic premise of her argument', '', ARRAY[]::TEXT[]),
('Premium', 'premium_us.mp3', 'noun', 'B1', 'an amount of money that you pay once or regularly for an insurance policy', '', 'a monthly premium of £6.25', '', ARRAY[]::TEXT[]),
('Preparation', 'preparation_us.mp3', 'noun', 'B1', 'the act or process of getting ready for something or making something ready', '', 'food preparation', '', ARRAY[]::TEXT[]),
('Prepare', 'prepare_us.mp3', 'verb', 'B1', 'to make something or somebody ready to be used or to do something', '', 'prepare something/somebody, to prepare a report', '', ARRAY[]::TEXT[]),
('Prepared', 'prepared_us.mp3', 'adjective', 'B1', 'ready and able to deal with something', '', 'We''ll be better prepared next time.', '', ARRAY[]::TEXT[]),
('Prescribe', 'prescribe_us.mp3', 'verb', 'B1', 'to tell somebody to take a particular medicine or have a particular treatment; to write a prescription for a particular medicine, etc.', '', 'prescribe something, Valium is usually prescribed to treat anxiety.', '', ARRAY[]::TEXT[]),
('Prescription', 'prescription_us.mp3', 'noun', 'B1', 'an official piece of paper on which a doctor writes the type of medicine you should have, and which enables you to get it from a chemist''s', '', 'prescription for something, The doctor gave me a prescription for antibiotics.', '', ARRAY[]::TEXT[]),
('Presence', 'presence_us.mp3', 'noun', 'B1', 'the fact of being in a particular place', '', 'He hardly seemed to notice my presence.', '', ARRAY[]::TEXT[]),
('Present', 'present_us.mp3', 'adjective', 'B1', 'existing or happening now', '', 'I am not satisfied with the present situation.', '', ARRAY[]::TEXT[]),
('Present', 'present_us.mp3', 'noun', 'B1', 'a thing that you give to somebody as a gift', '', 'What can I get him for a birthday present?', '', ARRAY[]::TEXT[]),
('Present', 'present_us.mp3', 'verb', 'B1', 'to show or offer something for other people to look at or consider', '', 'present something, Are you presenting a paper at the conference?', '', ARRAY[]::TEXT[]),
('Presentation', 'presentation_us.mp3', 'noun', 'B1', 'a meeting at which something, especially a new product or idea, or piece of work, is shown to a group of people', '', 'presentation on/about somebody/something, The sales manager will give a presentation on the new products.', '', ARRAY[]::TEXT[]),
('Presently', 'presently_us.mp3', 'adverb', 'B1', 'at the time you are speaking or writing; now', '', 'The crime is presently being investigated by the police.', '', ARRAY[]::TEXT[]),
('Preservation', 'preservation_us.mp3', 'noun', 'B1', 'the act of keeping something in its original state or in good condition', '', 'building/environmental/food preservation', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
