INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Director', 'director_us.mp3', 'noun', 'B1', 'one of a group of senior managers who run a company', '', 'a non-executive director', '', ARRAY[]::TEXT[]),
('Directory', 'directory_us.mp3', 'noun', 'B1', 'a book or electronic resource containing lists of information, usually in alphabetical order, for example people’s phone numbers or the names and addresses of businesses in a particular area', '', 'a telephone/trade directory', '', ARRAY[]::TEXT[]),
('Dirt', 'dirt_us.mp3', 'noun', 'B1', 'any substance that makes something dirty, for example dust, soil or mud', '', 'His clothes were covered in dirt.', '', ARRAY[]::TEXT[]),
('Dirty', 'dirty_us.mp3', 'adjective', 'B1', 'not clean', '', 'dirty hands/clothes/dishes', '', ARRAY[]::TEXT[]),
('Disability', 'disability_us.mp3', 'noun', 'B1', 'a physical or mental condition that makes it difficult for somebody to do some things that most other people can do', '', 'a physical/developmental/intellectual disability', '', ARRAY[]::TEXT[]),
('Disabled', 'disabled_us.mp3', 'adjective', 'B1', 'having a condition that makes it difficult for you to do some things that most other people can do', '', 'physically/developmentally/intellectually disabled', '', ARRAY[]::TEXT[]),
('Disadvantage', 'disadvantage_us.mp3', 'noun', 'B1', 'something that causes problems and tends to stop somebody/something from succeeding or making progress', '', 'a serious/severe/significant disadvantage', '', ARRAY[]::TEXT[]),
('Disagree', 'disagree_us.mp3', 'verb', 'B1', 'if two people disagree or one person disagrees with another about something, they have a different opinion about it', '', 'Even friends disagree sometimes.', '', ARRAY[]::TEXT[]),
('Disagreement', 'disagreement_us.mp3', 'noun', 'B1', 'a situation where people have different opinions about something and often argue', '', 'disagreement (about/on/over/as to something), Disagreement arose about exactly how to plan the show.', '', ARRAY[]::TEXT[]),
('Disappear', 'disappear_us.mp3', 'verb', 'B1', 'to become impossible to see', '', 'With that, Matt promptly disappeared.', '', ARRAY[]::TEXT[]),
('Disappoint', 'disappoint_us.mp3', 'verb', 'B1', 'to make somebody feel sad because something that they hope for or expect to happen does not happen or is not as good as they hoped', '', 'disappoint (somebody), Her decision to cancel the concert is bound to disappoint her fans.', '', ARRAY[]::TEXT[]),
('Disappointed', 'disappointed_us.mp3', 'adjective', 'B1', 'upset because something you hoped for has not happened or been as good, successful, etc. as you expected', '', 'The singer has promised to refund any disappointed fans.', '', ARRAY[]::TEXT[]),
('Disappointing', 'disappointing_us.mp3', 'adjective', 'B1', 'not as good, successful, etc. as you had hoped; making you feel disappointed', '', 'a disappointing result/performance/defeat', '', ARRAY[]::TEXT[]),
('Disappointment', 'disappointment_us.mp3', 'noun', 'B1', 'the feeling of being sad because something has not happened or been as good, successful, etc. as you expected or hoped', '', 'Book early for the show to avoid disappointment.', '', ARRAY[]::TEXT[]),
('Disaster', 'disaster_us.mp3', 'noun', 'B1', 'an unexpected event, such as a very bad accident, a flood or a fire, that kills a lot of people or causes a lot of damage', '', 'the world''s worst humanitarian disaster', '', ARRAY[]::TEXT[]),
('Disastrous', 'disastrous_us.mp3', 'adjective', 'B1', 'very bad, harmful or unsuccessful', '', 'a disastrous harvest/fire/result', '', ARRAY[]::TEXT[]),
('Disc', 'disc_us.mp3', 'noun', 'B1', 'a thin flat round object', '', 'He wears an identity disc around his neck.', '', ARRAY[]::TEXT[]),
('Discard', 'discard_us.mp3', 'verb', 'B1', 'to get rid of something that you no longer want or need', '', 'discard somebody/something, The room was littered with discarded newspapers.', '', ARRAY[]::TEXT[]),
('Discharge', 'discharge_us.mp3', 'verb', 'B1', 'to give somebody official permission to leave the police or the armed forces; to make somebody leave the police or the armed forces', '', 'be discharged from something, He was discharged from the army following his injury.', '', ARRAY[]::TEXT[]),
('Discipline', 'discipline_us.mp3', 'noun', 'B1', 'the practice of training people to obey rules and orders and punishing them if they do not; the controlled behaviour or situation that is the result of this training', '', 'The school has a reputation for high standards of discipline.', '', ARRAY[]::TEXT[]),
('Disclose', 'disclose_us.mp3', 'verb', 'B1', 'to give somebody information about something, especially something that was previously secret', '', 'disclose something (to somebody), The spokesman refused to disclose details of the takeover to the press.', '', ARRAY[]::TEXT[]),
('Disclosure', 'disclosure_us.mp3', 'noun', 'B1', 'the act of making something known or public that was previously secret or private', '', 'the newspaper’s disclosure of defence secrets', '', ARRAY[]::TEXT[]),
('Discount', 'discount_us.mp3', 'noun', 'B1', 'an amount of money that is taken off the usual cost of something', '', 'to get/offer a discount', '', ARRAY[]::TEXT[]),
('Discount', 'discount_us.mp3', 'verb', 'B1', 'to take an amount of money off the usual cost of something; to sell something at a discount', '', 'be discounted by something, Most of our stock has been discounted by up to 40 per cent.', '', ARRAY[]::TEXT[]),
('Discourage', 'discourage_us.mp3', 'verb', 'B1', 'to try to prevent something or to prevent somebody from doing something, especially by making it difficult to do or by showing that you do not approve of it', '', 'discourage (doing) something, a campaign to discourage smoking among teenagers', '', ARRAY[]::TEXT[]),
('Discourse', 'discourse_us.mp3', 'noun', 'B1', 'a long and serious treatment or discussion of a subject in speech or writing', '', 'discourse on something, a discourse on issues of gender and sexuality', '', ARRAY[]::TEXT[]),
('Discover', 'discover_us.mp3', 'verb', 'B1', 'to be the first person to become aware that a particular place or thing exists', '', 'Cook is credited with discovering Hawaii.', '', ARRAY[]::TEXT[]),
('Discovery', 'discovery_us.mp3', 'noun', 'B1', 'an act or the process of finding somebody/something, or learning about something that was not known about before', '', 'Researchers in this field have made some important new discoveries.', '', ARRAY[]::TEXT[]),
('Discretion', 'discretion_us.mp3', 'noun', 'B1', 'the freedom or power to decide what should be done in a particular situation', '', 'I''ll leave it up to you to use your discretion.', '', ARRAY[]::TEXT[]),
('Discrimination', 'discrimination_us.mp3', 'noun', 'B1', 'the practice of treating somebody or a particular group in society less fairly than others', '', 'age/racial/gender/sex discrimination (= because of somebody’s age, race or sex)', '', ARRAY[]::TEXT[]),
('Discuss', 'discuss_us.mp3', 'verb', 'B1', 'to talk about something with somebody, especially in order to decide something', '', 'discuss something with somebody, Have you discussed the problem with anyone?', '', ARRAY[]::TEXT[]),
('Discussion', 'discussion_us.mp3', 'noun', 'B1', 'a conversation about somebody/something; the process of discussing somebody/something', '', 'I discovered something interesting during a family discussion.', '', ARRAY[]::TEXT[]),
('Disease', 'disease_us.mp3', 'noun', 'B1', 'an illness affecting humans, animals or plants, often caused by infection', '', 'heart/lung/liver disease', '', ARRAY[]::TEXT[]),
('Dish', 'dish_us.mp3', 'noun', 'B1', 'a flat shallow container for cooking food in or serving it from', '', 'a baking/serving dish', '', ARRAY[]::TEXT[]),
('Dishonest', 'dishonest_us.mp3', 'adjective', 'B1', 'not honest; intending to trick people', '', 'Beware of dishonest traders in the tourist areas.', '', ARRAY[]::TEXT[]),
('Disk', 'disk_us.mp3', 'noun', 'B1', 'a thin flat round object', '', 'Red blood cells are roughly the shape of a disk.', '', ARRAY[]::TEXT[]),
('Dislike', 'dislike_us.mp3', 'noun', 'B1', 'a feeling of not liking somebody/something', '', 'dislike of somebody/something, He did not try to hide his dislike of his boss.', '', ARRAY[]::TEXT[]),
('Dislike', 'dislike_us.mp3', 'verb', 'B1', 'to not like somebody/something', '', 'dislike somebody/something, Why do you dislike him so much?', '', ARRAY[]::TEXT[]),
('Dismiss', 'dismiss_us.mp3', 'verb', 'B1', 'to decide that somebody/something is not important and not worth thinking or talking about', '', 'dismiss somebody/something, to dismiss a suggestion/a claim/an idea', '', ARRAY[]::TEXT[]),
('Dismissal', 'dismissal_us.mp3', 'noun', 'B1', 'the act of dismissing somebody from their job; an example of this', '', 'He still hopes to win his claim against unfair dismissal.', '', ARRAY[]::TEXT[]),
('Disorder', 'disorder_us.mp3', 'noun', 'B1', 'a condition or illness that causes problems with the way part of the body or brain works', '', 'a blood/bowel disorder', '', ARRAY[]::TEXT[]),
('Displace', 'displace_us.mp3', 'verb', 'B1', 'to take the place of somebody/something', '', 'be displaced (by somebody/something), Gradually factory workers have been displaced by machines.', '', ARRAY[]::TEXT[]),
('Display', 'display_us.mp3', 'noun', 'B1', 'an arrangement of things in a public place to inform or entertain people or advertise something for sale', '', 'a beautiful floral display', '', ARRAY[]::TEXT[]),
('Display', 'display_us.mp3', 'verb', 'B1', 'to put something in a place where people can see it easily; to show something to people', '', 'display something, The exhibition gives local artists an opportunity to display their work.', '', ARRAY[]::TEXT[]),
('Disposal', 'disposal_us.mp3', 'noun', 'B1', 'the act of getting rid of something', '', 'The council is responsible for waste disposal and street cleaning.', '', ARRAY[]::TEXT[]),
('Dispose', 'dispose_us.mp3', 'verb', 'B1', 'to arrange things or people in a particular way or position', '', 'The visitors disposed themselves in a circle round the statue.', '', ARRAY[]::TEXT[]),
('Dispute', 'dispute_us.mp3', 'noun', 'B1', 'an argument between two people, groups or countries; discussion about a subject on which people disagree', '', 'industrial/pay disputes', '', ARRAY[]::TEXT[]),
('Dispute', 'dispute_us.mp3', 'verb', 'B1', 'to question whether something is true or legally or officially acceptable', '', 'dispute something, These figures have been disputed.', '', ARRAY[]::TEXT[]),
('Disrupt', 'disrupt_us.mp3', 'verb', 'B1', 'to make it difficult for something to continue in the normal way', '', 'Demonstrators succeeded in disrupting the meeting.', '', ARRAY[]::TEXT[]),
('Disruption', 'disruption_us.mp3', 'noun', 'B1', 'a situation in which it is difficult for something to continue in the normal way; the act of stopping something from continuing in the normal way', '', 'We aim to help you move house with minimum disruption to yourself.', '', ARRAY[]::TEXT[]),
('Dissolve', 'dissolve_us.mp3', 'verb', 'B1', 'to mix with a liquid and become part of it', '', 'Salt dissolves in water.', '', ARRAY[]::TEXT[]),
('Distance', 'distance_us.mp3', 'noun', 'B1', 'the amount of space between two places or things', '', 'a short/long distance', '', ARRAY[]::TEXT[]),
('Distant', 'distant_us.mp3', 'adjective', 'B1', 'far away in space or time', '', 'the distant sound of music', '', ARRAY[]::TEXT[]),
('Distinct', 'distinct_us.mp3', 'adjective', 'B1', 'easily or clearly heard, seen, felt, etc.', '', 'There was a distinct smell of gas.', '', ARRAY[]::TEXT[]),
('Distinction', 'distinction_us.mp3', 'noun', 'B1', 'a clear difference or contrast especially between people or things that are similar or related', '', 'distinctions between traditional and modern societies', '', ARRAY[]::TEXT[]),
('Distinctive', 'distinctive_us.mp3', 'adjective', 'B1', 'having a quality or characteristic that makes something different and easily noticed', '', 'clothes with a distinctive style', '', ARRAY[]::TEXT[]),
('Distinguish', 'distinguish_us.mp3', 'verb', 'B1', 'to recognize the difference between two people or things', '', 'distinguish between A and B, At what age are children able to distinguish between right and wrong?', '', ARRAY[]::TEXT[]),
('Distort', 'distort_us.mp3', 'verb', 'B1', 'to change the shape, appearance or sound of something so that it is strange or not clear', '', 'a fairground mirror that distorts your shape', '', ARRAY[]::TEXT[]),
('Distract', 'distract_us.mp3', 'verb', 'B1', 'to take somebody’s attention away from what they are trying to do', '', 'You''re distracting me from my work.', '', ARRAY[]::TEXT[]),
('Distress', 'distress_us.mp3', 'noun', 'B1', 'a feeling of great worry or unhappiness; great mental pain', '', 'The newspaper article caused the actor considerable distress.', '', ARRAY[]::TEXT[]),
('Distress', 'distress_us.mp3', 'verb', 'B1', 'to make somebody feel very worried or unhappy', '', 'distress somebody, It was clear that the letter had deeply distressed her.', '', ARRAY[]::TEXT[]),
('Distribute', 'distribute_us.mp3', 'verb', 'B1', 'to give things to a large number of people; to share something between a number of people', '', 'distribute something, The leaflets have been widely distributed.', '', ARRAY[]::TEXT[]),
('Distribution', 'distribution_us.mp3', 'noun', 'B1', 'the way that something is spread or exists over a particular area or among a particular group of people', '', 'distribution of something, They studied the geographical distribution of the disease.', '', ARRAY[]::TEXT[]),
('District', 'district_us.mp3', 'noun', 'B1', 'an area of a country or town, especially one that has particular features', '', 'the City of London’s financial district', '', ARRAY[]::TEXT[]),
('Disturb', 'disturb_us.mp3', 'verb', 'B1', 'to interrupt somebody when they are trying to work, sleep, etc.', '', 'I''m sorry to disturb you, but can I talk to you for a moment?', '', ARRAY[]::TEXT[]),
('Disturbing', 'disturbing_us.mp3', 'adjective', 'B1', 'making you feel anxious and upset or shocked', '', 'a disturbing piece of news', '', ARRAY[]::TEXT[]),
('Dive', 'dive_us.mp3', 'noun', 'B1', 'a jump into deep water with your head first and your arms in front of you', '', 'a spectacular high dive (= from high above the water)', '', ARRAY[]::TEXT[]),
('Dive', 'dive_us.mp3', 'verb', 'B1', 'to jump into water with your head and arms going in first', '', 'dive (from/off something) (into something), We dived into the river to cool off.', '', ARRAY[]::TEXT[]),
('Diverse', 'diverse_us.mp3', 'adjective', 'B1', 'very different from each other and of various kinds', '', 'People from diverse cultures were invited to the event.', '', ARRAY[]::TEXT[]),
('Diversity', 'diversity_us.mp3', 'noun', 'B1', 'a range of many people or things that are very different from each other', '', 'the biological diversity of the rainforests', '', ARRAY[]::TEXT[]),
('Divert', 'divert_us.mp3', 'verb', 'B1', 'to make somebody/something change direction', '', 'be diverted, The course of the stream has now been diverted.', '', ARRAY[]::TEXT[]),
('Divide', 'divide_us.mp3', 'noun', 'B1', 'a difference between two groups of people or two things that separates them from each other', '', 'He offered advice on bridging cultural divides.', '', ARRAY[]::TEXT[]),
('Divide', 'divide_us.mp3', 'verb', 'B1', 'to separate into parts; to make something separate into parts', '', 'The cells began to divide rapidly.', '', ARRAY[]::TEXT[]),
('Divine', 'divine_us.mp3', 'adjective', 'B1', 'coming from or connected with God or a god', '', 'divine law/love/will', '', ARRAY[]::TEXT[]),
('Division', 'division_us.mp3', 'noun', 'B1', 'the process or result of dividing into separate parts; the process or result of dividing something or sharing it out', '', 'The organism begins as a single cell and grows by cell division.', '', ARRAY[]::TEXT[]),
('Divorce', 'divorce_us.mp3', 'noun', 'B1', 'the legal ending of a marriage', '', 'The marriage ended in divorce in 1996.', '', ARRAY[]::TEXT[]),
('Divorce', 'divorce_us.mp3', 'verb', 'B1', 'to end your marriage to somebody legally', '', 'They''re getting divorced.', '', ARRAY[]::TEXT[]),
('Divorced', 'divorced_us.mp3', 'adjective', 'B1', 'no longer married because your marriage has been legally ended', '', 'My parents are divorced.', '', ARRAY[]::TEXT[]),
('Do', 'do_us.mp3', 'verb', 'B1', 'used to refer to actions that you do not mention by name or do not know about', '', 'What are you doing this evening?', '', ARRAY[]::TEXT[]),
('Do', 'do_us.mp3', 'auxiliary verb', 'B1', 'used before a full verb to form negative sentences and questions', '', 'I don''t like fish.', '', ARRAY[]::TEXT[]),
('Doctor', 'doctor_us.mp3', 'noun', 'B1', 'a person who has been trained in medical science, whose job is to treat people who are ill or injured', '', 'You''d better see a doctor about that cough.', '', ARRAY[]::TEXT[]),
('Doctrine', 'doctrine_us.mp3', 'noun', 'B1', 'a belief or set of beliefs held and taught by a Church, a political party, etc.', '', 'the doctrine of parliamentary sovereignty', '', ARRAY[]::TEXT[]),
('Document', 'document_us.mp3', 'noun', 'B1', 'an official paper, book or electronic file that gives information about something, or that can be used as evidence or proof of something', '', 'Please read and sign the attached document.', '', ARRAY[]::TEXT[]),
('Document', 'document_us.mp3', 'verb', 'B1', 'to record something in the form of a written document, photograph, film, etc.', '', 'Urban life in the nineteenth century is well documented.', '', ARRAY[]::TEXT[]),
('Documentary', 'documentary_us.mp3', 'noun', 'B1', 'a film or a radio or television programme giving facts about something', '', 'There were some interesting interviews in the documentary.', '', ARRAY[]::TEXT[]),
('Documentation', 'documentation_us.mp3', 'noun', 'B1', 'the documents that are required for something, or that give evidence or proof of something', '', 'I couldn''t enter the country because I didn''t have all the necessary documentation.', '', ARRAY[]::TEXT[]),
('Dog', 'dog_us.mp3', 'noun', 'B1', 'an animal with four legs and a tail, often kept as a pet or trained for work, for example hunting or guarding buildings. There are many types of dog, some of which are wild.', '', 'I took the dog for a walk.', '', ARRAY[]::TEXT[]),
('Dollar', 'dollar_us.mp3', 'noun', 'B1', 'the unit of money in the US, Canada, Australia and several other countries', '', 'You will be paid in American dollars.', '', ARRAY[]::TEXT[]),
('Domain', 'domain_us.mp3', 'noun', 'B1', 'an area of knowledge or activity; especially one that somebody is responsible for', '', 'Financial matters are her domain.', '', ARRAY[]::TEXT[]),
('Domestic', 'domestic_us.mp3', 'adjective', 'B1', 'of or inside a particular country; not foreign or international', '', 'domestic affairs/politics', '', ARRAY[]::TEXT[]),
('Dominance', 'dominance_us.mp3', 'noun', 'B1', 'the fact of being more important, powerful or easy to notice than somebody/something else', '', 'political/economic dominance', '', ARRAY[]::TEXT[]),
('Dominant', 'dominant_us.mp3', 'adjective', 'B1', 'more important, powerful or easy to notice than other things', '', 'The firm has achieved a dominant position in the world market.', '', ARRAY[]::TEXT[]),
('Dominate', 'dominate_us.mp3', 'verb', 'B1', 'to control or have a lot of influence over somebody/something, especially in an unpleasant way', '', 'She always says a lot in meetings, but she doesn''t dominate.', '', ARRAY[]::TEXT[]),
('Donate', 'donate_us.mp3', 'verb', 'B1', 'to give money, food, clothes, etc. to somebody/something, especially a charity', '', 'donate something to somebody/something, He donated thousands of pounds to charity.', '', ARRAY[]::TEXT[]),
('Donation', 'donation_us.mp3', 'noun', 'B1', 'something that is given to a person or an organization such as a charity, in order to help them; the act of giving something in this way', '', 'a generous/large/small donation', '', ARRAY[]::TEXT[]),
('Donor', 'donor_us.mp3', 'noun', 'B1', 'a person or an organization that makes a gift of money, clothes, food, etc. to a charity, etc.', '', 'international aid donors (= countries that give money, etc. to help other countries)', '', ARRAY[]::TEXT[]),
('Door', 'door_us.mp3', 'noun', 'B1', 'a piece of wood, glass, etc. that is opened and closed so that people can get in and out of a room, building, car, etc.; a similar thing in a cupboard', '', 'Open the door!', '', ARRAY[]::TEXT[]),
('Dose', 'dose_us.mp3', 'noun', 'B1', 'an amount of a medicine or a drug that is taken once, or regularly over a period of time', '', 'a high/low/lethal dose', '', ARRAY[]::TEXT[]),
('Dot', 'dot_us.mp3', 'noun', 'B1', 'a small round mark, especially one that is printed', '', 'There are dots above the letters i and j.', '', ARRAY[]::TEXT[]),
('Double', 'double_us.mp3', 'adjective', 'B1', 'twice as much or as many as usual', '', 'a double helping', '', ARRAY[]::TEXT[]),
('Double', 'double_us.mp3', 'adverb', 'B1', 'in twos or in two parts', '', 'I thought I was seeing double (= seeing two of something).', '', ARRAY[]::TEXT[]),
('Double', 'double_us.mp3', 'determiner', 'B1', 'twice as much or as many as', '', 'His income is double hers.', '', ARRAY[]::TEXT[]),
('Double', 'double_us.mp3', 'pronoun', 'B1', 'a number or amount that is twice as much or as many as another number or amount', '', 'He gets paid double for doing the same job I do.', '', ARRAY[]::TEXT[]),
('Double', 'double_us.mp3', 'verb', 'B1', 'to become, or make something become, twice as much or as many', '', 'Membership almost doubled in two years.', '', ARRAY[]::TEXT[]),
('Doubt', 'doubt_us.mp3', 'noun', 'B1', 'a feeling of being uncertain about something or not believing something', '', 'a feeling of doubt and uncertainty', '', ARRAY[]::TEXT[]),
('Doubt', 'doubt_us.mp3', 'verb', 'B1', 'to feel uncertain about something; to feel that something is not true, will probably not happen, etc.', '', 'doubt something, There seems no reason to doubt her story.', '', ARRAY[]::TEXT[]),
('Down', 'down_us.mp3', 'adverb', 'B1', 'to or at a lower place or position', '', 'She jumped down off the chair.', '', ARRAY[]::TEXT[]),
('Down', 'down_us.mp3', 'preposition', 'B1', 'from a high or higher point on something to a lower one', '', 'The stone rolled down the hill.', '', ARRAY[]::TEXT[]),
('Download', 'download_us.mp3', 'noun', 'B1', 'data that is downloaded from another computer system', '', 'A staggering 99.8 % of digital music downloads are to mobile handsets.', '', ARRAY[]::TEXT[]),
('Download', 'download_us.mp3', 'verb', 'B1', 'to get data from another computer, usually using the internet', '', 'download something, to download files/music/software', '', ARRAY[]::TEXT[]),
('Downstairs', 'downstairs_us.mp3', 'adjective', 'B1', 'on a floor of a house or building lower than the one you are on, especially the one at ground level', '', 'a downstairs bathroom', '', ARRAY[]::TEXT[]),
('Downstairs', 'downstairs_us.mp3', 'adverb', 'B1', 'down the stairs; on or to a floor of a house or building lower than the one you are on, especially the one at ground level', '', 'I couldn''t sleep so I went downstairs and watched TV.', '', ARRAY[]::TEXT[]),
('Downtown', 'downtown_us.mp3', 'adjective', 'B1', 'in, towards or typical of the centre of a city, especially its main business area', '', 'a downtown store', '', ARRAY[]::TEXT[]),
('Downtown', 'downtown_us.mp3', 'adverb', 'B1', 'in or towards the centre of a city, especially its main business area', '', 'to go/work downtown', '', ARRAY[]::TEXT[]),
('Downtown', 'downtown_us.mp3', 'noun', 'B1', 'the centre of a city, especially its main business area', '', 'a hotel in the heart of downtown', '', ARRAY[]::TEXT[]),
('Downwards', 'downwards_us.mp3', 'adverb', 'B1', 'towards the ground; towards a lower place or position', '', 'She was lying face downwards on the grass.', '', ARRAY[]::TEXT[]),
('Dozen', 'dozen_us.mp3', 'determiner', 'B1', 'a group of twelve of the same thing', '', 'Give me a dozen, please.', '', ARRAY[]::TEXT[]),
('Dozen', 'dozen_us.mp3', 'noun', 'B1', 'a group of twelve of the same thing', '', 'Give me a dozen, please.', '', ARRAY[]::TEXT[]),
('Draft', 'draft_us.mp3', 'noun', 'B1', 'a rough written version of something that is not yet in its final form', '', 'This is only the first draft of my speech.', '', ARRAY[]::TEXT[]),
('Draft', 'draft_us.mp3', 'verb', 'B1', 'to write the first rough version of something such as a letter, speech, book or law', '', 'I''ll draft a letter for you.', '', ARRAY[]::TEXT[]),
('Drag', 'drag_us.mp3', 'verb', 'B1', 'to pull somebody/something along with effort and difficulty', '', 'drag somebody/something, The sack is too heavy to lift—you’ll have to drag it.', '', ARRAY[]::TEXT[]),
('Drain', 'drain_us.mp3', 'verb', 'B1', 'to make something empty or dry by removing the liquid from it; to become empty or dry in this way', '', 'Drain and rinse the pasta.', '', ARRAY[]::TEXT[]),
('Drama', 'drama_us.mp3', 'noun', 'B1', 'a play for the theatre, television or radio', '', 'a costume/period/courtroom/crime drama', '', ARRAY[]::TEXT[]),
('Dramatic', 'dramatic_us.mp3', 'adjective', 'B1', 'sudden, very great and often surprising', '', 'a dramatic increase/change/improvement/shift', '', ARRAY[]::TEXT[]),
('Dramatically', 'dramatically_us.mp3', 'adverb', 'B1', 'very suddenly and to a very great and often surprising degree', '', 'Prices have fallen dramatically.', '', ARRAY[]::TEXT[]),
('Draw', 'draw_us.mp3', 'verb', 'B1', 'to make pictures, or a picture of something, with a pencil, pen or chalk (but not paint)', '', 'You draw beautifully.', '', ARRAY[]::TEXT[]),
('Drawing', 'drawing_us.mp3', 'noun', 'B1', 'a picture made using a pencil or pen rather than paint', '', 'a pencil/pen-and-ink/charcoal drawing', '', ARRAY[]::TEXT[]),
('Dream', 'dream_us.mp3', 'noun', 'B1', 'a series of images, events and feelings that happen in your mind while you are asleep', '', 'I had a really weird dream last night.', '', ARRAY[]::TEXT[]),
('Dream', 'dream_us.mp3', 'verb', 'B1', 'to experience a series of images, events and feelings in your mind while you are asleep', '', 'Did I talk in my sleep? I must have been dreaming.', '', ARRAY[]::TEXT[]),
('Dress', 'dress_us.mp3', 'noun', 'B1', 'a piece of clothing that is made in one piece and hangs down to cover the body as far as the legs, sometimes reaching to below the knees, or to the ankles', '', 'a long white dress', '', ARRAY[]::TEXT[]),
('Dress', 'dress_us.mp3', 'verb', 'B1', 'to put clothes on yourself/somebody', '', 'I dressed quickly.', '', ARRAY[]::TEXT[]),
('Dressed', 'dressed_us.mp3', 'adjective', 'B1', 'wearing clothes and not naked or wearing clothes for sleeping', '', 'Hurry up and get dressed.', '', ARRAY[]::TEXT[]),
('Drift', 'drift_us.mp3', 'verb', 'B1', 'to move along smoothly and slowly in water or air', '', 'Clouds drifted across the sky.', '', ARRAY[]::TEXT[]),
('Drink', 'drink_us.mp3', 'noun', 'B1', 'a liquid for drinking; an amount of a liquid that you drink', '', 'Can I have a drink?', '', ARRAY[]::TEXT[]),
('Drink', 'drink_us.mp3', 'verb', 'B1', 'to take liquid into your mouth and then down your throat into your stomach', '', 'drink something, I don''t drink coffee.', '', ARRAY[]::TEXT[]),
('Drive', 'drive_us.mp3', 'noun', 'B1', 'a journey in a car or other vehicle', '', 'Let''s go for a drive.', '', ARRAY[]::TEXT[]),
('Drive', 'drive_us.mp3', 'verb', 'B1', 'to operate a vehicle so that it goes in a particular direction', '', 'Can you drive?', '', ARRAY[]::TEXT[]),
('Driver', 'driver_us.mp3', 'noun', 'B1', 'a person who drives a vehicle', '', 'a bus/train/taxi driver', '', ARRAY[]::TEXT[]),
('Driving', 'driving_us.mp3', 'adjective', 'B1', 'strong and powerful; having a strong influence in making something happen', '', 'Who was the driving force (= the person with the strongest influence) in the band?', '', ARRAY[]::TEXT[]),
('Driving', 'driving_us.mp3', 'noun', 'B1', 'the way that somebody drives a vehicle; the act of driving', '', 'She was convicted of dangerous driving.', '', ARRAY[]::TEXT[]),
('Drop', 'drop_us.mp3', 'noun', 'B1', 'a very small amount of liquid that forms a round shape', '', 'The first drops of rain fell.', '', ARRAY[]::TEXT[]),
('Drop', 'drop_us.mp3', 'verb', 'B1', 'to allow something to fall by accident; to fall by accident', '', 'drop something, Be careful not to drop that plate.', '', ARRAY[]::TEXT[]),
('Drought', 'drought_us.mp3', 'noun', 'B1', 'a long period of time when there is little or no rain', '', 'Farmers are facing ruin after two years of severe drought.', '', ARRAY[]::TEXT[]),
('Drown', 'drown_us.mp3', 'verb', 'B1', 'to die because you have been underwater too long and you cannot breathe; to kill somebody by holding them underwater', '', 'Two children drowned after falling into the river.', '', ARRAY[]::TEXT[]),
('Drug', 'drug_us.mp3', 'noun', 'B1', 'an illegal substance that some people smoke, inject, etc. for the physical and mental effects it has', '', 'He does not smoke or take drugs.', '', ARRAY[]::TEXT[]),
('Drum', 'drum_us.mp3', 'noun', 'B1', 'a musical instrument made of a hollow round frame with plastic or skin stretched tightly across one or both ends. You play it by hitting it with sticks or with your hands.', '', 'to play the drum', '', ARRAY[]::TEXT[]),
('Drunk', 'drunk_us.mp3', 'adjective', 'B1', 'having drunk so much alcohol that it is impossible to think or speak clearly', '', 'They were clearly too drunk to drive.', '', ARRAY[]::TEXT[]),
('Dry', 'dry_us.mp3', 'adjective', 'B1', 'not wet or sticky; without water or moisture', '', 'Is my shirt dry yet?', '', ARRAY[]::TEXT[]),
('Dry', 'dry_us.mp3', 'verb', 'B1', 'to become dry; to make something dry', '', 'He did the laundry and hung it out to dry.', '', ARRAY[]::TEXT[]),
('Dual', 'dual_us.mp3', 'adjective', 'B1', 'having two parts or aspects', '', 'his dual role as composer and conductor', '', ARRAY[]::TEXT[]),
('Dub', 'dub_us.mp3', 'verb', 'B1', 'to give somebody/something a particular name, often in a humorous or critical way', '', 'The media dubbed anorexia ‘the slimming disease’.', '', ARRAY[]::TEXT[]),
('Due', 'due_us.mp3', 'adjective', 'B1', 'caused by somebody/something; because of somebody/something', '', 'The team''s success was largely due to her efforts.', '', ARRAY[]::TEXT[]),
('Dull', 'dull_us.mp3', 'adjective', 'B1', 'not interesting or exciting', '', 'Life in a small town could be deadly dull.', '', ARRAY[]::TEXT[]),
('Dumb', 'dumb_us.mp3', 'adjective', 'B1', 'stupid', '', 'That was a pretty dumb thing to do.', '', ARRAY[]::TEXT[]),
('Dump', 'dump_us.mp3', 'verb', 'B1', 'to get rid of something you do not want, especially in a place that is not suitable', '', 'Too much toxic waste is being dumped at sea.', '', ARRAY[]::TEXT[]),
('Duo', 'duo_us.mp3', 'noun', 'B1', 'two people who perform together or are often seen or thought of together', '', 'the comedy duo Laurel and Hardy', '', ARRAY[]::TEXT[]),
('Duration', 'duration_us.mp3', 'noun', 'B1', 'the length of time that something lasts or continues', '', 'The school was used as a hospital for the duration of the war.', '', ARRAY[]::TEXT[]),
('During', 'during_us.mp3', 'preposition', 'B1', 'all through a period of time', '', 'during the 1990s', '', ARRAY[]::TEXT[]),
('Dust', 'dust_us.mp3', 'noun', 'B1', 'a fine powder that consists of very small pieces of sand, earth, etc.', '', 'A cloud of dust rose as the truck drove off.', '', ARRAY[]::TEXT[]),
('Duty', 'duty_us.mp3', 'noun', 'B1', 'something that you feel you have to do because it is your moral or legal responsibility', '', 'duty to do something, It is my duty to report it to the police.', '', ARRAY[]::TEXT[]),
('DVD', 'DVD_us.mp3', 'noun', 'B1', 'a disk on which large amounts of information, especially films, photographs and video, can be stored, for use on a DVD player or computer (the abbreviation for ‘digital versatile disc’ or ‘digital videodisc’)', '', 'Let''s just stay in and watch a DVD.', '', ARRAY[]::TEXT[]),
('Dynamic', 'dynamic_us.mp3', 'adjective', 'B1', 'having a lot of energy and a strong personality', '', 'a dynamic leader', '', ARRAY[]::TEXT[]),
('Dynamic', 'dynamic_us.mp3', 'noun', 'B1', 'the way in which people or things behave and react to each other in a particular situation', '', 'the dynamics of political change', '', ARRAY[]::TEXT[]),
('Each', 'each_us.mp3', 'adverb', 'B1', 'used to refer to every one of two or more people or things, when you are thinking about them separately', '', 'Each answer is worth 20 points.', '', ARRAY[]::TEXT[]),
('Each', 'each_us.mp3', 'determiner', 'B1', 'used to refer to every one of two or more people or things, when you are thinking about them separately', '', 'Each answer is worth 20 points.', '', ARRAY[]::TEXT[]),
('Each', 'each_us.mp3', 'pronoun', 'B1', 'used to refer to every one of two or more people or things, when you are thinking about them separately', '', 'Each answer is worth 20 points.', '', ARRAY[]::TEXT[]),
('Eager', 'eager_us.mp3', 'adjective', 'B1', 'very interested and excited by something that is going to happen or about something that you want to do; showing this', '', 'eager crowds outside the stadium', '', ARRAY[]::TEXT[]),
('Ear', 'ear_us.mp3', 'noun', 'B1', 'either of the organs on the sides of the head that you hear with', '', 'the left/right ear', '', ARRAY[]::TEXT[]),
('Early', 'early_us.mp3', 'adjective', 'B1', 'near the beginning of a period of time, an event etc.', '', 'the early morning', '', ARRAY[]::TEXT[]),
('Early', 'early_us.mp3', 'adverb', 'B1', 'near the beginning of a period of time, an event, a piece of work, etc.', '', 'We arrived early the next day.', '', ARRAY[]::TEXT[]),
('Earn', 'earn_us.mp3', 'verb', 'B1', 'to get money for work that you do', '', 'earn (something), He earns about $40 000 a year.', '', ARRAY[]::TEXT[]),
('Earnings', 'earnings_us.mp3', 'noun', 'B1', 'the money that you earn for the work that you do', '', 'a rise in average earnings', '', ARRAY[]::TEXT[]),
('Earth', 'earth_us.mp3', 'noun', 'B1', 'the world; the planet that we live on', '', 'the planet Earth', '', ARRAY[]::TEXT[]),
('Earthquake', 'earthquake_us.mp3', 'noun', 'B1', 'a sudden, violent shaking of the earth’s surface', '', 'a devastating/massive/powerful earthquake', '', ARRAY[]::TEXT[]),
('Ease', 'ease_us.mp3', 'noun', 'B1', 'lack of difficulty', '', 'with ease, He passed the exam with ease.', '', ARRAY[]::TEXT[]),
('Ease', 'ease_us.mp3', 'verb', 'B1', 'to become less unpleasant, painful or severe; to make something less unpleasant, etc.', '', 'The pain immediately eased.', '', ARRAY[]::TEXT[]),
('Easily', 'easily_us.mp3', 'adverb', 'B1', 'without problems or difficulty', '', 'The museum is easily accessible by car.', '', ARRAY[]::TEXT[]),
('East', 'east_us.mp3', 'adjective', 'B1', 'in or towards the east', '', 'East Africa', '', ARRAY[]::TEXT[]),
('East', 'east_us.mp3', 'adverb', 'B1', 'towards the east', '', 'The house faces east.', '', ARRAY[]::TEXT[]),
('East', 'east_us.mp3', 'noun', 'B1', 'the direction that you look towards to see the sun rise; one of the four main points of the compass', '', 'Which way is east?', '', ARRAY[]::TEXT[]),
('Eastern', 'eastern_us.mp3', 'adjective', 'B1', 'located in the east or facing east', '', 'eastern Spain', '', ARRAY[]::TEXT[]),
('Easy', 'easy_us.mp3', 'adjective', 'B1', 'not difficult; done or obtained without a lot of effort or problems', '', 'an easy way to make bread', '', ARRAY[]::TEXT[]),
('Eat', 'eat_us.mp3', 'verb', 'B1', 'to put food in your mouth, bite it and swallow it', '', 'I was too nervous to eat.', '', ARRAY[]::TEXT[]),
('Echo', 'echo_us.mp3', 'noun', 'B1', 'the reflecting of sound off a wall or inside a particular space so that a noise appears to be repeated; a sound that is reflected back in this way', '', 'There was an echo on the phone and I couldn''t hear clearly.', '', ARRAY[]::TEXT[]),
('Echo', 'echo_us.mp3', 'verb', 'B1', 'if a sound echoes, it is reflected off a wall, the side of a mountain, etc. so that you can hear it again', '', 'Her footsteps echoed in the empty room.', '', ARRAY[]::TEXT[]),
('Ecological', 'ecological_us.mp3', 'adjective', 'B1', 'connected with the relation of plants and living creatures to each other and to their environment', '', 'We risk upsetting the ecological balance of the area.', '', ARRAY[]::TEXT[]),
('Economic', 'economic_us.mp3', 'adjective', 'B1', 'connected with the trade, industry and development of wealth of a country, an area or a society', '', 'They discussed social, economic and political issues.', '', ARRAY[]::TEXT[]),
('Economics', 'economics_us.mp3', 'noun', 'B1', 'the study of how a society organizes its money, trade and industry', '', 'He studied politics and economics at Yale.', '', ARRAY[]::TEXT[]),
('Economist', 'economist_us.mp3', 'noun', 'B1', 'a person who studies or writes about economics', '', 'the World Bank''s chief economist', '', ARRAY[]::TEXT[]),
('Economy', 'economy_us.mp3', 'noun', 'B1', 'the relationship between production, trade and the supply of money in a particular country or region', '', 'The economy is in recession.', '', ARRAY[]::TEXT[]),
('Edge', 'edge_us.mp3', 'noun', 'B1', 'the outside limit of an object, a surface or an area; the part furthest from the centre', '', 'I gripped the edge of my desk to steady myself.', '', ARRAY[]::TEXT[]),
('Edit', 'edit_us.mp3', 'verb', 'B1', 'to prepare a piece of writing, a book, etc. to be published by correcting the mistakes, making improvements to it, etc.', '', 'edit (something), This draft text will need to be edited.', '', ARRAY[]::TEXT[]),
('Edition', 'edition_us.mp3', 'noun', 'B1', 'the form in which a book, newspaper, etc. is published', '', 'a paperback/hardback edition', '', ARRAY[]::TEXT[]),
('Editor', 'editor_us.mp3', 'noun', 'B1', 'a person who is in charge of a newspaper, magazine, etc., or part of one, and who decides what should be included', '', 'the editor of the Washington Post', '', ARRAY[]::TEXT[]),
('Editorial', 'editorial_us.mp3', 'adjective', 'B1', 'connected with the task of preparing something such as a newspaper, a book or a television or radio programme, to be published or broadcast', '', 'the magazine’s editorial staff', '', ARRAY[]::TEXT[]),
('Educate', 'educate_us.mp3', 'verb', 'B1', 'to teach somebody over a period of time at a school, university, etc.', '', 'be educated, She was educated in the US.', '', ARRAY[]::TEXT[]),
('Educated', 'educated_us.mp3', 'adjective', 'B1', 'having had the kind of education mentioned; having been to the school, college or university mentioned', '', 'privately educated children', '', ARRAY[]::TEXT[]),
('Education', 'education_us.mp3', 'noun', 'B1', 'a process of teaching, training and learning, especially in schools, colleges or universities, to improve knowledge and develop skills', '', 'primary/elementary education', '', ARRAY[]::TEXT[]),
('Educational', 'educational_us.mp3', 'adjective', 'B1', 'connected with education', '', 'children with special educational needs', '', ARRAY[]::TEXT[]),
('Educator', 'educator_us.mp3', 'noun', 'B1', 'a person whose job is to teach or educate people', '', 'adult educators (= who teach adults)', '', ARRAY[]::TEXT[]),
('Effect', 'effect_us.mp3', 'noun', 'B1', 'a change that somebody/something causes in somebody/something else; a result', '', 'the beneficial effects of exercise', '', ARRAY[]::TEXT[]),
('Effective', 'effective_us.mp3', 'adjective', 'B1', 'producing the result that is wanted or intended; producing a successful result', '', 'Aspirin is a simple but highly effective treatment.', '', ARRAY[]::TEXT[]),
('Effectively', 'effectively_us.mp3', 'adverb', 'B1', 'in a way that produces the intended result or a successful result', '', 'The company must reduce costs to compete effectively.', '', ARRAY[]::TEXT[]),
('Effectiveness', 'effectiveness_us.mp3', 'noun', 'B1', 'the fact of producing the result that is wanted or intended; the fact of producing a successful result', '', 'to check the effectiveness of the security system', '', ARRAY[]::TEXT[]),
('Efficiency', 'efficiency_us.mp3', 'noun', 'B1', 'the quality of doing something well with no waste of time or money', '', 'improvements in efficiency at the factory', '', ARRAY[]::TEXT[]),
('Efficient', 'efficient_us.mp3', 'adjective', 'B1', 'doing something in a good, careful and complete way with no waste of time, money or energy', '', 'a highly efficient worker', '', ARRAY[]::TEXT[]),
('Efficiently', 'efficiently_us.mp3', 'adverb', 'B1', 'in a good and careful way, with no waste of time, money or energy', '', 'a very efficiently organized event', '', ARRAY[]::TEXT[]),
('Effort', 'effort_us.mp3', 'noun', 'B1', 'an attempt to do something especially when it is difficult to do', '', 'The project was a team effort.', '', ARRAY[]::TEXT[]),
('Egg', 'egg_us.mp3', 'noun', 'B1', 'a small oval object with a thin hard shell produced by a female bird and containing a young bird; a similar object (without a hard shell) produced by a female fish, insect, etc.', '', 'The female sits on the eggs until they hatch.', '', ARRAY[]::TEXT[]),
('Ego', 'ego_us.mp3', 'noun', 'B1', 'your sense of your own value and importance', '', 'He has the biggest ego of anyone I''ve ever met.', '', ARRAY[]::TEXT[]),
('Either', 'either_us.mp3', 'adverb', 'B1', 'used after negative phrases to state that a feeling or situation is similar to one already mentioned', '', 'Pete can''t go and I can''t either.', '', ARRAY[]::TEXT[]),
('Either', 'either_us.mp3', 'determiner', 'B1', 'one or the other of two; it does not matter which', '', 'You can park on either side of the street.', '', ARRAY[]::TEXT[]),
('Either', 'either_us.mp3', 'pronoun', 'B1', 'one or the other of two; it does not matter which', '', 'You can park on either side of the street.', '', ARRAY[]::TEXT[]),
('Elaborate', 'elaborate_us.mp3', 'adjective', 'B1', 'very complicated and detailed; carefully prepared and organized', '', 'elaborate designs', '', ARRAY[]::TEXT[]),
('Elbow', 'elbow_us.mp3', 'noun', 'B1', 'the joint between the upper and lower parts of the arm where it bends in the middle', '', 'She jabbed him with her elbow.', '', ARRAY[]::TEXT[]),
('Elderly', 'elderly_us.mp3', 'adjective', 'B1', 'used as a polite word for ‘old’', '', 'an elderly man/woman/lady', '', ARRAY[]::TEXT[]),
('Elect', 'elect_us.mp3', 'verb', 'B1', 'to choose somebody to do a particular job by voting for them', '', 'elect somebody/something, Voters will elect a new president on 30 March next year.', '', ARRAY[]::TEXT[]),
('Election', 'election_us.mp3', 'noun', 'B1', 'the process of choosing a person or a group of people for a position, especially a political position, by voting', '', 'presidential/parliamentary/local elections', '', ARRAY[]::TEXT[]),
('Electoral', 'electoral_us.mp3', 'adjective', 'B1', 'connected with elections', '', 'electoral systems/reforms', '', ARRAY[]::TEXT[]),
('Electric', 'electric_us.mp3', 'adjective', 'B1', 'connected with electricity; using, produced by or producing electricity', '', 'an electric car/vehicle', '', ARRAY[]::TEXT[]),
('Electrical', 'electrical_us.mp3', 'adjective', 'B1', 'connected with electricity; using or producing electricity', '', 'an electrical fault in the engine', '', ARRAY[]::TEXT[]),
('Electricity', 'electricity_us.mp3', 'noun', 'B1', 'a form of energy from charged elementary particles, usually supplied as electric current through cables, wires, etc. for lighting, heating, driving machines, etc.', '', 'materials that conduct electricity', '', ARRAY[]::TEXT[]),
('Electronic', 'electronic_us.mp3', 'adjective', 'B1', 'having or using many small parts, such as microchips, that control and direct a small electric current', '', 'Airline passengers no longer have to turn off all electronic devices while on the plane.', '', ARRAY[]::TEXT[]),
('Electronics', 'electronics_us.mp3', 'noun', 'B1', 'the branch of science and technology that studies electric currents in electronic equipment', '', 'the electronics industry', '', ARRAY[]::TEXT[]),
('Elegant', 'elegant_us.mp3', 'adjective', 'B1', 'attractive and showing a good sense of style', '', 'She was tall and elegant.', '', ARRAY[]::TEXT[]),
('Element', 'element_us.mp3', 'noun', 'B1', 'a necessary or typical part of something; one of several parts that something contains', '', 'There are three important elements to consider.', '', ARRAY[]::TEXT[]),
('Elementary', 'elementary_us.mp3', 'adjective', 'B1', 'in or connected with the first stages of a course of study', '', 'an elementary English course', '', ARRAY[]::TEXT[]),
('Elephant', 'elephant_us.mp3', 'noun', 'B1', 'a very large animal with thick grey skin, large ears, two curved outer teeth called tusks and a long nose called a trunk. There are two types of elephant, the African and the Asian.', '', 'herds of elephants', '', ARRAY[]::TEXT[]),
('Elevate', 'elevate_us.mp3', 'verb', 'B1', 'to give somebody/something a higher position or rank, often more important than they deserve', '', 'elevate somebody/something (to something), He elevated many of his friends to powerful positions within the government.', '', ARRAY[]::TEXT[]),
('Eleven', 'eleven_us.mp3', 'number', 'B1', '11', '', 'There are only eleven of these rare animals left.', '', ARRAY[]::TEXT[]),
('Eligible', 'eligible_us.mp3', 'adjective', 'B1', 'a person who is eligible for something or to do something, is able to have or do it because they have the right qualifications, are the right age, etc.', '', 'eligible (for something), Only those over 70 are eligible for the special payment.', '', ARRAY[]::TEXT[]),
('Eliminate', 'eliminate_us.mp3', 'verb', 'B1', 'to remove or get rid of something', '', 'eliminate something, Credit cards eliminate the need to carry a lot of cash.', '', ARRAY[]::TEXT[]),
('Elite', 'elite_us.mp3', 'noun', 'B1', 'a small group of people in a society, etc. who are powerful and have a lot of influence, because they are rich, intelligent, etc.', '', 'a member of the ruling/intellectual elite', '', ARRAY[]::TEXT[]),
('Else', 'else_us.mp3', 'adverb', 'B1', 'in addition to something already mentioned', '', 'What else did he say?', '', ARRAY[]::TEXT[]),
('Elsewhere', 'elsewhere_us.mp3', 'adverb', 'B1', 'in, at or to another place or other places', '', 'Dissatisfied customers will look elsewhere.', '', ARRAY[]::TEXT[]),
('Email', 'email_us.mp3', 'noun', 'B1', 'a way of sending messages and data to other people by means of computers connected together in a network', '', 'I will be on vacation for a week in November, with no access to email.', '', ARRAY[]::TEXT[]),
('Email', 'email_us.mp3', 'verb', 'B1', 'to send a message to somebody by email', '', 'email somebody, Patrick emailed me yesterday.', '', ARRAY[]::TEXT[]),
('Embark', 'embark_us.mp3', 'verb', 'B1', 'to get onto a ship or plane; to put somebody/something onto a ship or plane', '', 'We stood on the pier and watched as they embarked.', '', ARRAY[]::TEXT[]),
('Embarrassed', 'embarrassed_us.mp3', 'adjective', 'B1', 'shy, uncomfortable or ashamed, especially in a social situation', '', 'I''ve never felt so embarrassed in my life!', '', ARRAY[]::TEXT[]),
('Embarrassing', 'embarrassing_us.mp3', 'adjective', 'B1', 'making you feel shy, uncomfortable or ashamed', '', 'an embarrassing moment/situation', '', ARRAY[]::TEXT[]),
('Embarrassment', 'embarrassment_us.mp3', 'noun', 'B1', 'shy, uncomfortable or guilty feelings; a feeling of being embarrassed', '', 'I nearly died of embarrassment when he said that.', '', ARRAY[]::TEXT[]),
('Embassy', 'embassy_us.mp3', 'noun', 'B1', 'a group of officials led by an ambassador who represent their government in a foreign country', '', 'embassy officials', '', ARRAY[]::TEXT[]),
('Embed', 'embed_us.mp3', 'verb', 'B1', 'to fix something in a substance or solid object', '', 'be embedded in something, an operation to remove glass that was embedded in his leg', '', ARRAY[]::TEXT[]),
('Embody', 'embody_us.mp3', 'verb', 'B1', 'to express or represent an idea or a quality', '', 'embody something, a politician who embodied the hopes of black youth', '', ARRAY[]::TEXT[]),
('Embrace', 'embrace_us.mp3', 'verb', 'B1', 'to put your arms around somebody as a sign of love or friendship', '', 'They embraced and promised to keep in touch.', '', ARRAY[]::TEXT[]),
('Emerge', 'emerge_us.mp3', 'verb', 'B1', 'to move out of or away from something and become possible to see', '', 'The crabs emerge at low tide to look for food.', '', ARRAY[]::TEXT[]),
('Emergence', 'emergence_us.mp3', 'noun', 'B1', 'the fact of somebody/something moving out of or away from something and becoming possible to see', '', 'the island’s emergence from the sea 3 000 years ago', '', ARRAY[]::TEXT[]),
('Emergency', 'emergency_us.mp3', 'noun', 'B1', 'a sudden serious and dangerous event or situation that needs immediate action to deal with it', '', 'This is a medical emergency needing urgent treatment with antibiotics.', '', ARRAY[]::TEXT[]),
('Emission', 'emission_us.mp3', 'noun', 'B1', 'the production or sending out of light, heat, gas, etc.', '', 'the emission of carbon dioxide into the atmosphere', '', ARRAY[]::TEXT[]),
('Emotion', 'emotion_us.mp3', 'noun', 'B1', 'a strong feeling such as love, fear or anger; the part of a person’s character that consists of feelings', '', 'to show/express your emotions', '', ARRAY[]::TEXT[]),
('Emotional', 'emotional_us.mp3', 'adjective', 'B1', 'connected with people’s feelings (= with the emotions)', '', 'emotional problems/stress', '', ARRAY[]::TEXT[]),
('Emotionally', 'emotionally_us.mp3', 'adverb', 'B1', 'in a way that is connected with people''s feelings (= with the emotions)', '', 'emotionally disturbed children', '', ARRAY[]::TEXT[]),
('Emphasis', 'emphasis_us.mp3', 'noun', 'B1', 'special importance that is given to something', '', 'emphasis on/upon something, Since the elections there has been a greater emphasis on education.', '', ARRAY[]::TEXT[]),
('Emphasize', 'emphasize_us.mp3', 'verb', 'B1', 'to give special importance to something', '', 'emphasize something, His speech emphasized the importance of attracting industry to the town.', '', ARRAY[]::TEXT[]),
('Empire', 'empire_us.mp3', 'noun', 'B1', 'a group of countries or states that are controlled by one leader or government', '', 'These invasions almost led to the collapse of the Roman Empire.', '', ARRAY[]::TEXT[]),
('Empirical', 'empirical_us.mp3', 'adjective', 'B1', 'based on experiments or experience rather than ideas or theories', '', 'empirical evidence/knowledge/research', '', ARRAY[]::TEXT[]),
('Employ', 'employ_us.mp3', 'verb', 'B1', 'to give somebody a job to do for payment', '', 'employ somebody, How many people does the company employ?', '', ARRAY[]::TEXT[]),
('Employee', 'employee_us.mp3', 'noun', 'B1', 'a person who is paid to work for somebody', '', 'The firm has over 500 employees.', '', ARRAY[]::TEXT[]),
('Employer', 'employer_us.mp3', 'noun', 'B1', 'a person or company that pays people to work for them', '', 'They''re very good employers (= they treat the people that work for them well).', '', ARRAY[]::TEXT[]),
('Employment', 'employment_us.mp3', 'noun', 'B1', 'work, especially when it is done to earn money; the state of being employed', '', 'full-time/part-time employment', '', ARRAY[]::TEXT[]),
('Empower', 'empower_us.mp3', 'verb', 'B1', 'to give somebody the power or authority to do something', '', 'be empowered (to do something), The courts were empowered to impose the death sentence for certain crimes.', '', ARRAY[]::TEXT[]),
('Empty', 'empty_us.mp3', 'adjective', 'B1', 'with no people or things inside', '', 'an empty box/glass/bottle', '', ARRAY[]::TEXT[]),
('Empty', 'empty_us.mp3', 'verb', 'B1', 'to remove everything that is in a container, etc.', '', 'empty something, She emptied the bins, washed the glasses and went to bed.', '', ARRAY[]::TEXT[]),
('Enable', 'enable_us.mp3', 'verb', 'B1', 'to make it possible for somebody/something to do something', '', 'This new programme will enable older people to study at college.', '', ARRAY[]::TEXT[]),
('Enact', 'enact_us.mp3', 'verb', 'B1', 'to pass a law', '', '(be) enacted (by somebody/something), legislation enacted by parliament', '', ARRAY[]::TEXT[]),
('Encompass', 'encompass_us.mp3', 'verb', 'B1', 'to include a large number or range of things', '', 'The job encompasses a wide range of responsibilities.', '', ARRAY[]::TEXT[]),
('Encounter', 'encounter_us.mp3', 'noun', 'B1', 'a meeting, especially one that is sudden, unexpected or violent', '', 'a chance encounter', '', ARRAY[]::TEXT[]),
('Encounter', 'encounter_us.mp3', 'verb', 'B1', 'to experience something, especially something unpleasant or difficult, while you are trying to do something else', '', 'We encountered a number of difficulties in the first week.', '', ARRAY[]::TEXT[]),
('Encourage', 'encourage_us.mp3', 'verb', 'B1', 'to give somebody support, courage or hope', '', 'encourage somebody, We were greatly encouraged by the positive response of the public.', '', ARRAY[]::TEXT[]),
('Encouragement', 'encouragement_us.mp3', 'noun', 'B1', 'the act of encouraging somebody to do something; something that encourages somebody', '', 'a few words of encouragement', '', ARRAY[]::TEXT[]),
('Encouraging', 'encouraging_us.mp3', 'adjective', 'B1', 'that gives somebody support, courage or hope', '', 'This month''s unemployment figures are not very encouraging.', '', ARRAY[]::TEXT[]),
('End', 'end_us.mp3', 'noun', 'B1', 'the final part of a period of time, an event, an activity or a story', '', 'It''s the end of an era.', '', ARRAY[]::TEXT[]),
('End', 'end_us.mp3', 'verb', 'B1', 'to finish; to reach a point and go no further; to make something finish', '', 'At last the war ended.', '', ARRAY[]::TEXT[]),
('Endeavour', 'endeavour_us.mp3', 'noun', 'B1', 'an attempt to do something, especially something new or difficult', '', 'There have been great advances in the field of scientific endeavour.', '', ARRAY[]::TEXT[]),
('Ending', 'ending_us.mp3', 'noun', 'B1', 'the last part of a story, film, etc.', '', 'His stories usually have a happy ending.', '', ARRAY[]::TEXT[]),
('Endless', 'endless_us.mp3', 'adjective', 'B1', 'very large in size or amount and seeming to have no end', '', 'endless patience', '', ARRAY[]::TEXT[]),
('Endorse', 'endorse_us.mp3', 'verb', 'B1', 'to say publicly that you support a person, statement or course of action', '', 'I wholeheartedly endorse his remarks.', '', ARRAY[]::TEXT[]),
('Endorsement', 'endorsement_us.mp3', 'noun', 'B1', 'a public statement or action showing that you support somebody/something', '', 'The election victory is a clear endorsement of their policies.', '', ARRAY[]::TEXT[]),
('Endure', 'endure_us.mp3', 'verb', 'B1', 'to experience and deal with something that is painful or unpleasant without giving up', '', 'endure something, They had to endure a long wait before the case came to trial.', '', ARRAY[]::TEXT[]),
('Enemy', 'enemy_us.mp3', 'noun', 'B1', 'a person who hates somebody or who acts or speaks against somebody/something', '', 'She didn''t have an enemy in the world.', '', ARRAY[]::TEXT[]),
('Energy', 'energy_us.mp3', 'noun', 'B1', 'the strength, effort and enthusiasm required for physical or mental activity, work, etc.', '', 'It''s a waste of time and energy.', '', ARRAY[]::TEXT[]),
('Enforce', 'enforce_us.mp3', 'verb', 'B1', 'to make sure that people obey a particular law or rule', '', 'enforce something, It''s the job of the police to enforce the law.', '', ARRAY[]::TEXT[]),
('Enforcement', 'enforcement_us.mp3', 'noun', 'B1', 'the act of making people obey a particular law or rule', '', 'strict enforcement of regulations', '', ARRAY[]::TEXT[]),
('Engage', 'engage_us.mp3', 'verb', 'B1', 'to succeed in attracting and keeping somebody’s attention and interest', '', 'It is a movie that engages both the mind and the eye.', '', ARRAY[]::TEXT[]),
('Engaged', 'engaged_us.mp3', 'adjective', 'B1', 'having agreed to marry somebody', '', 'When did you get engaged?', '', ARRAY[]::TEXT[]),
('Engagement', 'engagement_us.mp3', 'noun', 'B1', 'an agreement to marry somebody; the period during which two people are engaged', '', 'Their engagement was announced in the local paper.', '', ARRAY[]::TEXT[]),
('Engaging', 'engaging_us.mp3', 'adjective', 'B1', 'interesting or pleasant in a way that attracts your attention', '', 'an engaging smile', '', ARRAY[]::TEXT[]),
('Engine', 'engine_us.mp3', 'noun', 'B1', 'the part of a vehicle that produces power to make the vehicle move', '', 'a diesel/petrol engine', '', ARRAY[]::TEXT[]),
('Engineer', 'engineer_us.mp3', 'noun', 'B1', 'a person whose job involves designing and building engines, machines, roads, bridges, etc.', '', 'We worked with a team of scientists and engineers.', '', ARRAY[]::TEXT[]),
('Engineering', 'engineering_us.mp3', 'noun', 'B1', 'the activity of applying scientific knowledge to the design, building and control of machines, roads, bridges, electrical equipment, etc.', '', 'The bridge is a triumph of modern engineering.', '', ARRAY[]::TEXT[]),
('Enhance', 'enhance_us.mp3', 'verb', 'B1', 'to increase or further improve the good quality, value or status of somebody/something', '', 'This is an opportunity to enhance the reputation of the company.', '', ARRAY[]::TEXT[]),
('Enjoy', 'enjoy_us.mp3', 'verb', 'B1', 'to get pleasure from something', '', 'enjoy something, We thoroughly enjoyed our time in New York.', '', ARRAY[]::TEXT[]),
('Enjoyable', 'enjoyable_us.mp3', 'adjective', 'B1', 'giving pleasure', '', 'an enjoyable weekend/experience', '', ARRAY[]::TEXT[]),
('Enormous', 'enormous_us.mp3', 'adjective', 'B1', 'extremely large', '', 'an enormous house/dog', '', ARRAY[]::TEXT[]),
('Enough', 'enough_us.mp3', 'adverb', 'B1', 'to the necessary degree', '', 'I hadn''t trained enough for the game.', '', ARRAY[]::TEXT[]),
('Enough', 'enough_us.mp3', 'determiner', 'B1', 'used before plural or uncountable nouns to mean ‘as many or as much as somebody needs or wants’', '', 'Have you made enough copies?', '', ARRAY[]::TEXT[]),
('Enough', 'enough_us.mp3', 'pronoun', 'B1', 'as many or as much as somebody needs or wants', '', 'Six bottles should be enough.', '', ARRAY[]::TEXT[]),
('Enquire', 'enquire_us.mp3', 'verb', 'B1', 'to ask somebody for some information', '', 'enquire about somebody/something, I called the station to enquire about train times.', '', ARRAY[]::TEXT[]),
('Enquiry', 'enquiry_us.mp3', 'noun', 'B1', 'an official process to find out the cause of something or to find out information about something', '', 'a murder enquiry', '', ARRAY[]::TEXT[]),
('Enrich', 'enrich_us.mp3', 'verb', 'B1', 'to improve the quality of something, often by adding something to it', '', 'The study of science has enriched all our lives.', '', ARRAY[]::TEXT[]),
('Enrol', 'enrol_us.mp3', 'verb', 'B1', 'to arrange for yourself or for somebody else to officially join a course, school, etc.', '', 'You need to enrol before the end of August.', '', ARRAY[]::TEXT[]),
('Ensue', 'ensue_us.mp3', 'verb', 'B1', 'to happen after or as a result of another event', '', 'An argument ensued.', '', ARRAY[]::TEXT[]),
('Ensure', 'ensure_us.mp3', 'verb', 'B1', 'to make sure that something happens or is definite', '', 'ensure something, We are working to ensure the safety of people in the city.', '', ARRAY[]::TEXT[]),
('Enter', 'enter_us.mp3', 'verb', 'B1', 'to come or go into something', '', 'Knock before you enter.', '', ARRAY[]::TEXT[]),
('Enterprise', 'enterprise_us.mp3', 'noun', 'B1', 'a company or business', '', 'He is in charge of an enterprise with a turnover of $26 billion.', '', ARRAY[]::TEXT[]),
('Entertain', 'entertain_us.mp3', 'verb', 'B1', 'to interest somebody or make somebody laugh in order to please them', '', 'The aim of the series is both to entertain and inform.', '', ARRAY[]::TEXT[]),
('Entertaining', 'entertaining_us.mp3', 'adjective', 'B1', 'that you enjoy watching, listening to, doing or experiencing', '', 'an entertaining speech/evening', '', ARRAY[]::TEXT[]),
('Entertainment', 'entertainment_us.mp3', 'noun', 'B1', 'films, music, etc. used to entertain people; an example of this', '', 'radio, television and other forms of entertainment', '', ARRAY[]::TEXT[]),
('Enthusiasm', 'enthusiasm_us.mp3', 'noun', 'B1', 'a strong feeling of excitement and interest in something and a desire to become involved in it', '', 'Her voice was full of enthusiasm.', '', ARRAY[]::TEXT[]),
('Enthusiast', 'enthusiast_us.mp3', 'noun', 'B1', 'a person who is very interested in something and spends a lot of time doing it', '', 'a football enthusiast', '', ARRAY[]::TEXT[]),
('Enthusiastic', 'enthusiastic_us.mp3', 'adjective', 'B1', 'feeling or showing a lot of excitement and interest about somebody/something', '', 'an enthusiastic supporter', '', ARRAY[]::TEXT[]),
('Entire', 'entire_us.mp3', 'adjective', 'B1', 'including everything, everyone or every part', '', 'The entire village was destroyed.', '', ARRAY[]::TEXT[]),
('Entirely', 'entirely_us.mp3', 'adverb', 'B1', 'in every way possible; completely', '', 'The experience was entirely new to me.', '', ARRAY[]::TEXT[]),
('Entitle', 'entitle_us.mp3', 'verb', 'B1', 'to give somebody the right to have or to do something', '', 'be entitled to something, You will be entitled to your pension when you reach 65.', '', ARRAY[]::TEXT[]),
('Entity', 'entity_us.mp3', 'noun', 'B1', 'something that exists separately from other things and has its own identity', '', 'The unit has become part of a larger department and no longer exists as a separate entity.', '', ARRAY[]::TEXT[]),
('Entrance', 'entrance_us.mp3', 'noun', 'B1', 'a door, gate, passage, etc. used for entering a room, building or place', '', 'the front/back/side entrance of the house', '', ARRAY[]::TEXT[]),
('Entrepreneur', 'entrepreneur_us.mp3', 'noun', 'B1', 'a person who makes money by starting or running businesses, especially when this involves taking financial risks', '', 'A creative entrepreneur, he was continually dreaming up new projects.', '', ARRAY[]::TEXT[]),
('Entry', 'entry_us.mp3', 'noun', 'B1', 'an act of going into or getting into a place', '', 'She made her entry to the sound of thunderous applause.', '', ARRAY[]::TEXT[]),
('Envelope', 'envelope_us.mp3', 'noun', 'B1', 'a flat paper container used for sending letters in, with a part that you stick down to close it', '', 'Writing paper and envelopes are provided in your room.', '', ARRAY[]::TEXT[]),
('Environment', 'environment_us.mp3', 'noun', 'B1', 'the natural world in which people, animals and plants live', '', 'The government should do more to protect the environment.', '', ARRAY[]::TEXT[]),
('Environmental', 'environmental_us.mp3', 'adjective', 'B1', 'connected with the natural conditions in which people, animals and plants live; connected with the environment', '', 'the environmental impact of pollution', '', ARRAY[]::TEXT[]),
('Epidemic', 'epidemic_us.mp3', 'noun', 'B1', 'a large number of cases of a particular disease or medical condition happening at the same time in a particular community', '', 'the outbreak of a flu epidemic', '', ARRAY[]::TEXT[]),
('Episode', 'episode_us.mp3', 'noun', 'B1', 'one part of a story that is broadcast on television or radio in several parts', '', 'The next episode has not yet been filmed.', '', ARRAY[]::TEXT[]),
('Equal', 'equal_us.mp3', 'adjective', 'B1', 'the same in size, quantity, value, etc. as something else', '', 'There is an equal number of boys and girls in the class.', '', ARRAY[]::TEXT[]),
('Equal', 'equal_us.mp3', 'noun', 'B1', 'a person or thing of the same quality or with the same status, rights, etc. as another', '', 'She treats the people who work for her as her equals.', '', ARRAY[]::TEXT[]),
('Equal', 'equal_us.mp3', 'verb', 'B1', 'to be the same in size, quantity, value, etc. as something else', '', '2x plus y equals 7 (= 2x+y=7)', '', ARRAY[]::TEXT[]),
('Equality', 'equality_us.mp3', 'noun', 'B1', 'the fact of being equal in rights, status, advantages, etc.', '', 'racial/social/gender equality', '', ARRAY[]::TEXT[]),
('Equally', 'equally_us.mp3', 'adverb', 'B1', 'to the same degree; in the same or in a similar way', '', 'Diet and exercise are equally important.', '', ARRAY[]::TEXT[]),
('Equation', 'equation_us.mp3', 'noun', 'B1', 'a statement showing that two amounts or values are equal, for example 2x + y = 54', '', 'the numbers on the right-hand side of the equation', '', ARRAY[]::TEXT[]),
('Equip', 'equip_us.mp3', 'verb', 'B1', 'to provide yourself/somebody/something with the things that are needed for a particular purpose or activity', '', 'equip something, to be fully/poorly equipped', '', ARRAY[]::TEXT[]),
('Equipment', 'equipment_us.mp3', 'noun', 'B1', 'the things that are needed for a particular purpose or activity', '', 'a useful piece of equipment for the kitchen', '', ARRAY[]::TEXT[]),
('Equivalent', 'equivalent_us.mp3', 'adjective', 'B1', 'equal in value, amount, meaning, importance, etc.', '', '250 grams or an equivalent amount in ounces', '', ARRAY[]::TEXT[]),
('Equivalent', 'equivalent_us.mp3', 'noun', 'B1', 'a thing, amount, word, etc. that is equal in value, meaning or purpose to something else', '', 'Send €20 or the equivalent in your own currency.', '', ARRAY[]::TEXT[]),
('Era', 'era_us.mp3', 'noun', 'B1', 'a period of time, usually in history, that is different from other periods because of particular characteristics or events', '', 'the Victorian/modern/post-war era', '', ARRAY[]::TEXT[]),
('Erect', 'erect_us.mp3', 'verb', 'B1', 'to build something', '', 'The church was erected in 1582.', '', ARRAY[]::TEXT[]),
('Error', 'error_us.mp3', 'noun', 'B1', 'a mistake, especially one that causes problems or affects the result of something', '', 'spelling/typographical/grammatical errors', '', ARRAY[]::TEXT[]),
('Erupt', 'erupt_us.mp3', 'verb', 'B1', 'when a volcano erupts or burning rocks, smoke, etc. erupt or are erupted, the burning rocks, etc. are thrown out from the volcano', '', 'The volcano could erupt at any time.', '', ARRAY[]::TEXT[]),
('Escalate', 'escalate_us.mp3', 'verb', 'B1', 'to become greater, worse, more serious, etc.; to make something greater, worse, more serious, etc.', '', 'the escalating costs of healthcare', '', ARRAY[]::TEXT[]),
('Escape', 'escape_us.mp3', 'noun', 'B1', 'the act or a method of escaping from a place or an unpleasant or dangerous situation', '', 'I had a narrow escape (= I was lucky to have escaped).', '', ARRAY[]::TEXT[]),
('Escape', 'escape_us.mp3', 'verb', 'B1', 'to get away from a place where you have been kept as a prisoner or not allowed to leave', '', 'Two prisoners have escaped.', '', ARRAY[]::TEXT[]),
('Especially', 'especially_us.mp3', 'adverb', 'B1', 'more with one person, thing, etc. than with others, or more in particular circumstances than in others', '', 'Teenagers are very fashion conscious, especially girls.', '', ARRAY[]::TEXT[]),
('Essay', 'essay_us.mp3', 'noun', 'B1', 'a short piece of writing by a student as part of a course of study', '', 'I have to write an essay this weekend.', '', ARRAY[]::TEXT[]),
('Essence', 'essence_us.mp3', 'noun', 'B1', 'the most important quality or feature of something, that makes it what it is', '', 'His paintings capture the essence of France.', '', ARRAY[]::TEXT[]),
('Essential', 'essential_us.mp3', 'adjective', 'B1', 'completely necessary; extremely important in a particular situation or for a particular activity', '', 'an essential part/feature of something', '', ARRAY[]::TEXT[]),
('Essentially', 'essentially_us.mp3', 'adverb', 'B1', 'when you think about the true, important or basic nature of somebody/something', '', 'There are three essentially different ways of tackling the problem.', '', ARRAY[]::TEXT[]),
('Establish', 'establish_us.mp3', 'verb', 'B1', 'to start or create an organization, a system, etc. that is meant to last for a long time', '', 'The committee was established in 1912.', '', ARRAY[]::TEXT[]),
('Establishment', 'establishment_us.mp3', 'noun', 'B1', 'an organization, a large institution or a hotel', '', 'The visa is for foreign nationals wishing to study at a university, college or similar educational establishment.', '', ARRAY[]::TEXT[]),
('Estate', 'estate_us.mp3', 'noun', 'B1', 'an area of land with a lot of houses or factories of the same type on it', '', 'on an estate, She lives in a tower block on an estate in London.', '', ARRAY[]::TEXT[]),
('Estimate', 'estimate_us.mp3', 'noun', 'B1', 'a judgement that you make without having the exact details or figures about the size, amount, cost, etc. of something', '', 'to provide/obtain an estimate', '', ARRAY[]::TEXT[]),
('Estimate', 'estimate_us.mp3', 'verb', 'B1', 'to form an idea of the cost, size, value etc. of something, but without calculating it exactly', '', 'estimate something, to estimate the cost/value/number of something', '', ARRAY[]::TEXT[]),
('Eternal', 'eternal_us.mp3', 'adjective', 'B1', 'without an end; existing or continuing forever', '', 'the promise of eternal life in heaven', '', ARRAY[]::TEXT[]),
('Ethic', 'ethic_us.mp3', 'noun', 'B1', 'moral principles that control or influence a person’s behaviour', '', 'professional/business/medical ethics', '', ARRAY[]::TEXT[]),
('Ethical', 'ethical_us.mp3', 'adjective', 'B1', 'connected with beliefs and principles about what is right and wrong', '', 'ethical issues/standards/questions/dilemmas', '', ARRAY[]::TEXT[]),
('Ethnic', 'ethnic_us.mp3', 'adjective', 'B1', 'connected with or belonging to a group of people that share a cultural tradition', '', 'ethnic background/origin', '', ARRAY[]::TEXT[]),
('Euro', 'euro_us.mp3', 'noun', 'B1', 'the unit of money of some countries of the European Union', '', 'I paid five euros for it.', '', ARRAY[]::TEXT[]),
('Evacuate', 'evacuate_us.mp3', 'verb', 'B1', 'to move people from a place of danger to a safer place', '', 'evacuate something, Police evacuated nearby buildings.', '', ARRAY[]::TEXT[]),
('Evaluate', 'evaluate_us.mp3', 'verb', 'B1', 'to form an opinion of the amount, value or quality of something after thinking about it carefully', '', 'evaluate something, The trial will evaluate the effectiveness of the different drugs.', '', ARRAY[]::TEXT[]),
('Evaluation', 'evaluation_us.mp3', 'noun', 'B1', 'the act of forming an opinion of the amount, value or quality of something after thinking about it carefully', '', 'an evaluation of the healthcare system', '', ARRAY[]::TEXT[]),
('Even', 'even_us.mp3', 'adjective', 'B1', 'that can be divided exactly by two', '', '4, 6, 8 and 10 are all even numbers.', '', ARRAY[]::TEXT[]),
('Even', 'even_us.mp3', 'adverb', 'B1', 'used to emphasize something unexpected or surprising', '', 'She didn''t even call to say she wasn''t coming.', '', ARRAY[]::TEXT[]),
('Evening', 'evening_us.mp3', 'noun', 'B1', 'the part of the day between the afternoon and the time you go to bed', '', 'Remember to call me this evening.', '', ARRAY[]::TEXT[]),
('Event', 'event_us.mp3', 'noun', 'B1', 'a thing that happens, especially something important', '', 'recent/current/world events', '', ARRAY[]::TEXT[]),
('Eventually', 'eventually_us.mp3', 'adverb', 'B1', 'at the end of a period of time or a series of events', '', 'Our flight eventually left five hours late.', '', ARRAY[]::TEXT[]),
('Ever', 'ever_us.mp3', 'adverb', 'B1', 'used in negative sentences and questions, or sentences with if to mean ‘at any time’', '', 'Nothing ever happens here.', '', ARRAY[]::TEXT[]),
('Every', 'every_us.mp3', 'determiner', 'B1', 'used with singular nouns to refer to all the members of a group of things or people', '', 'She knows every student in the school.', '', ARRAY[]::TEXT[]),
('Everybody', 'everybody_us.mp3', 'pronoun', 'B1', 'every person; all people', '', 'Everybody knows Tom.', '', ARRAY[]::TEXT[]),
('Everyday', 'everyday_us.mp3', 'adjective', 'B1', 'used or happening every day or regularly; ordinary', '', 'Change is a part of everyday life in business.', '', ARRAY[]::TEXT[]),
('Everyone', 'everyone_us.mp3', 'pronoun', 'B1', 'every person; all people', '', 'Everyone cheered and clapped.', '', ARRAY[]::TEXT[]),
('Everything', 'everything_us.mp3', 'pronoun', 'B1', 'all things', '', 'Everything had gone.', '', ARRAY[]::TEXT[]),
('Everywhere', 'everywhere_us.mp3', 'adverb', 'B1', 'in, to or at every place; all places', '', 'I''ve looked everywhere.', '', ARRAY[]::TEXT[]),
('Evidence', 'evidence_us.mp3', 'noun', 'B1', 'the facts, signs or objects that make you believe that something is true', '', 'evidence (of something), Researchers have found clear scientific evidence of a link between exposure to sun and skin cancer.', '', ARRAY[]::TEXT[]),
('Evident', 'evident_us.mp3', 'adjective', 'B1', 'clear; easily seen', '', 'The orchestra played with evident enjoyment.', '', ARRAY[]::TEXT[]),
('Evil', 'evil_us.mp3', 'adjective', 'B1', 'enjoying harming others; morally bad and cruel', '', 'Police described the killer as ‘a desperate and evil man’.', '', ARRAY[]::TEXT[]),
('Evil', 'evil_us.mp3', 'noun', 'B1', 'a force that causes bad things to happen; morally bad behaviour', '', 'the eternal struggle between good and evil', '', ARRAY[]::TEXT[]),
('Evoke', 'evoke_us.mp3', 'verb', 'B1', 'to bring a feeling, a memory or an image into your mind', '', 'The music evoked memories of her youth.', '', ARRAY[]::TEXT[]),
('Evolution', 'evolution_us.mp3', 'noun', 'B1', 'the slow steady development of plants, animals, etc. during the history of the earth, as they adapt to changes in their environment', '', 'the evolution of the human species', '', ARRAY[]::TEXT[]),
('Evolutionary', 'evolutionary_us.mp3', 'adjective', 'B1', 'connected with evolution; connected with slow steady development and change', '', 'evolutionary theory', '', ARRAY[]::TEXT[]),
('Evolve', 'evolve_us.mp3', 'verb', 'B1', 'to develop gradually, especially from a simple to a more complicated form; to develop something in this way', '', 'evolve (from something) (into something), The idea evolved from a drawing I discovered in the attic.', '', ARRAY[]::TEXT[]),
('Exact', 'exact_us.mp3', 'adjective', 'B1', 'correct in every detail', '', 'The new palace is an exact replica of the original building.', '', ARRAY[]::TEXT[]),
('Exactly', 'exactly_us.mp3', 'adverb', 'B1', 'used to emphasize that something is correct in every way or in every detail', '', 'It''s exactly nine o''clock.', '', ARRAY[]::TEXT[]),
('Exaggerate', 'exaggerate_us.mp3', 'verb', 'B1', 'to make something seem larger, better, worse or more important than it really is', '', 'The hotel was really filthy and I''m not exaggerating.', '', ARRAY[]::TEXT[]),
('Exam', 'exam_us.mp3', 'noun', 'B1', 'a formal written, spoken or practical test, especially at school or college, to see how much you know about a subject, or what you can do', '', 'to take an exam', '', ARRAY[]::TEXT[]),
('Examination', 'examination_us.mp3', 'noun', 'B1', 'a formal written, spoken or practical test, especially at school or college, to see how much you know about a subject, or what you can do', '', 'successful candidates in GCSE examinations', '', ARRAY[]::TEXT[]),
('Examine', 'examine_us.mp3', 'verb', 'B1', 'to consider or study an idea, a subject, etc. very carefully', '', 'examine something, This study sets out to examine in detail the possible effects of climate change.', '', ARRAY[]::TEXT[]),
('Example', 'example_us.mp3', 'noun', 'B1', 'something such as an object, a fact or a situation that shows, explains or supports what you say', '', 'Let me give you an example.', '', ARRAY[]::TEXT[]),
('Exceed', 'exceed_us.mp3', 'verb', 'B1', 'to be greater than a particular number or amount', '', 'The price will not exceed £100.', '', ARRAY[]::TEXT[]),
('Excellence', 'excellence_us.mp3', 'noun', 'B1', 'the quality of being extremely good', '', 'a reputation for academic excellence', '', ARRAY[]::TEXT[]),
('Excellent', 'excellent_us.mp3', 'adjective', 'B1', 'extremely good', '', 'an excellent book/article', '', ARRAY[]::TEXT[]),
('Except', 'except_us.mp3', 'conjunction', 'B1', 'used before you mention something that makes a statement not completely true', '', 'I didn''t tell him anything except that I needed the money.', '', ARRAY[]::TEXT[]),
('Except', 'except_us.mp3', 'preposition', 'B1', 'used before you mention the only thing or person about which a statement is not true', '', 'We work every day except Sunday.', '', ARRAY[]::TEXT[]),
('Exception', 'exception_us.mp3', 'noun', 'B1', 'a person or thing that is not included in a general statement', '', 'Most of the buildings in the town are modern, but the church is an exception.', '', ARRAY[]::TEXT[]),
('Exceptional', 'exceptional_us.mp3', 'adjective', 'B1', 'unusually good', '', 'At the age of five he showed exceptional talent as a musician.', '', ARRAY[]::TEXT[]),
('Excess', 'excess_us.mp3', 'adjective', 'B1', 'in addition to an amount that is necessary, usual or legal', '', 'Excess food is stored as fat.', '', ARRAY[]::TEXT[]),
('Excess', 'excess_us.mp3', 'noun', 'B1', 'more than is necessary, reasonable or acceptable', '', 'You can throw away any excess.', '', ARRAY[]::TEXT[]),
('Excessive', 'excessive_us.mp3', 'adjective', 'B1', 'greater than what seems reasonable or appropriate', '', 'They complained about the excessive noise coming from the upstairs flat.', '', ARRAY[]::TEXT[]),
('Exchange', 'exchange_us.mp3', 'noun', 'B1', 'an act of giving something to somebody or doing something for somebody and receiving something in return', '', 'The exchange of prisoners took place this morning.', '', ARRAY[]::TEXT[]),
('Exchange', 'exchange_us.mp3', 'verb', 'B1', 'to give something to somebody and at the same time receive the same type of thing from them', '', 'exchange something, to exchange news/information', '', ARRAY[]::TEXT[]),
('Excited', 'excited_us.mp3', 'adjective', 'B1', 'feeling or showing happiness and enthusiasm', '', 'Staff got excited when they heard they were getting a bonus.', '', ARRAY[]::TEXT[]),
('Excitement', 'excitement_us.mp3', 'noun', 'B1', 'the state of feeling or showing happiness and enthusiasm', '', 'The news caused great excitement among her friends.', '', ARRAY[]::TEXT[]),
('Exciting', 'exciting_us.mp3', 'adjective', 'B1', 'causing great interest or excitement', '', 'This is an exciting opportunity for me.', '', ARRAY[]::TEXT[]),
('Exclude', 'exclude_us.mp3', 'verb', 'B1', 'to deliberately not include something in what you are doing or considering', '', 'The cost of borrowing has been excluded from the inflation figures.', '', ARRAY[]::TEXT[]),
('Exclusion', 'exclusion_us.mp3', 'noun', 'B1', 'the act of preventing somebody/something from entering a place or taking part in something', '', 'exclusion (of somebody/something) (from something), He was disappointed with his exclusion from the England squad.', '', ARRAY[]::TEXT[]),
('Exclusive', 'exclusive_us.mp3', 'adjective', 'B1', 'only to be used by one particular person or group; only given to one particular person or group', '', 'The hotel has exclusive access to the beach.', '', ARRAY[]::TEXT[]),
('Exclusively', 'exclusively_us.mp3', 'adverb', 'B1', 'for only one particular person, group or use', '', 'The resort caters almost exclusively for a high-society public.', '', ARRAY[]::TEXT[]),
('Excuse', 'excuse_us.mp3', 'noun', 'B1', 'a reason, either true or invented, that you give to explain or defend your behaviour', '', 'Late again! What''s your excuse this time?', '', ARRAY[]::TEXT[]),
('Excuse', 'excuse_us.mp3', 'verb', 'B1', 'to forgive somebody for something that they have done, for example not being polite or making a small mistake', '', 'excuse something, Please excuse the mess.', '', ARRAY[]::TEXT[]),
('Execute', 'execute_us.mp3', 'verb', 'B1', 'to kill somebody, especially as a legal punishment', '', 'be executed (for something), He was executed for treason.', '', ARRAY[]::TEXT[]),
('Execution', 'execution_us.mp3', 'noun', 'B1', 'the act of killing somebody, especially as a legal punishment', '', 'He faced execution by hanging for murder.', '', ARRAY[]::TEXT[]),
('Executive', 'executive_us.mp3', 'adjective', 'B1', 'connected with managing a business or an organization, and with making plans and decisions', '', 'She has an executive position in a finance company.', '', ARRAY[]::TEXT[]),
('Executive', 'executive_us.mp3', 'noun', 'B1', 'a person who has an important job as a manager of a company or an organization', '', 'company/corporate/business/industry executives', '', ARRAY[]::TEXT[]),
('Exercise', 'exercise_us.mp3', 'noun', 'B1', 'physical or mental activity that you do to stay healthy or become stronger', '', 'Swimming is good exercise.', '', ARRAY[]::TEXT[]),
('Exercise', 'exercise_us.mp3', 'verb', 'B1', 'to do sports or other physical activities in order to stay healthy or become stronger; to make an animal do this', '', 'an hour’s class of exercising to music', '', ARRAY[]::TEXT[]),
('Exert', 'exert_us.mp3', 'verb', 'B1', 'to use power or influence to affect somebody/something', '', 'He exerted all his authority to make them accept the plan.', '', ARRAY[]::TEXT[]),
('Exhibit', 'exhibit_us.mp3', 'noun', 'B1', 'an object or a collection of objects put in a public place, for example a museum, so that people can see it', '', 'The museum contains some interesting exhibits on Spanish rural life.', '', ARRAY[]::TEXT[]),
('Exhibit', 'exhibit_us.mp3', 'verb', 'B1', 'to show something in a public place for people to enjoy or to give them information', '', 'exhibit something (at/in…), They will be exhibiting their new designs at the trade fairs.', '', ARRAY[]::TEXT[]),
('Exhibition', 'exhibition_us.mp3', 'noun', 'B1', 'a collection of things, for example works of art, that are shown to the public', '', 'Have you seen the Picasso exhibition?', '', ARRAY[]::TEXT[]),
('Exile', 'exile_us.mp3', 'noun', 'B1', 'the state of being sent to live in another country that is not your own, especially for political reasons or as a punishment', '', 'a place of exile', '', ARRAY[]::TEXT[]),
('Exist', 'exist_us.mp3', 'verb', 'B1', 'to be real; to be present in a place or situation', '', 'Does life exist on other planets?', '', ARRAY[]::TEXT[]),
('Existence', 'existence_us.mp3', 'noun', 'B1', 'the state or fact of being real or living or of being present', '', 'I was unaware of his existence until today.', '', ARRAY[]::TEXT[]),
('Exit', 'exit_us.mp3', 'noun', 'B1', 'a way out of a public building or vehicle', '', 'Where''s the exit?', '', ARRAY[]::TEXT[]),
('Exit', 'exit_us.mp3', 'verb', 'B1', 'to go out; to leave a building, stage, vehicle, etc.', '', '(+ adv./prep.), The bullet entered her back and exited through her chest.', '', ARRAY[]::TEXT[]),
('Exotic', 'exotic_us.mp3', 'adjective', 'B1', 'from or in another country, especially a tropical one; seeming exciting and unusual because it seems to be connected with foreign countries', '', 'brightly-coloured exotic flowers/plants/birds', '', ARRAY[]::TEXT[]),
('Expand', 'expand_us.mp3', 'verb', 'B1', 'to become greater in size, number or importance; to make something greater in size, number or importance', '', 'Metals expand when they are heated.', '', ARRAY[]::TEXT[]),
('Expansion', 'expansion_us.mp3', 'noun', 'B1', 'an act of increasing or making something increase in size, amount or importance', '', 'a period of rapid economic expansion', '', ARRAY[]::TEXT[]),
('Expect', 'expect_us.mp3', 'verb', 'B1', 'to think or believe that something will happen or that somebody will do something', '', 'expect something, The company is expecting record sales this year.', '', ARRAY[]::TEXT[]),
('Expectation', 'expectation_us.mp3', 'noun', 'B1', 'a belief that something will happen because it is likely', '', 'expectation of something, We are confident in our expectation of a full recovery.', '', ARRAY[]::TEXT[]),
('Expected', 'expected_us.mp3', 'adjective', 'B1', 'that you think will happen', '', 'Double the expected number of people came to the meeting.', '', ARRAY[]::TEXT[]),
('Expedition', 'expedition_us.mp3', 'noun', 'B1', 'an organized journey with a particular purpose, especially to find out about a place that is not well known', '', 'to plan/lead/go on an expedition', '', ARRAY[]::TEXT[]),
('Expenditure', 'expenditure_us.mp3', 'noun', 'B1', 'the act of spending or using money; an amount of money spent', '', 'a reduction in public/government/military expenditure', '', ARRAY[]::TEXT[]),
('Expense', 'expense_us.mp3', 'noun', 'B1', 'the money that you spend on something', '', 'The garden was transformed at great expense.', '', ARRAY[]::TEXT[]),
('Expensive', 'expensive_us.mp3', 'adjective', 'B1', 'costing a lot of money', '', 'an expensive car/restaurant/holiday', '', ARRAY[]::TEXT[]),
('Experience', 'experience_us.mp3', 'noun', 'B1', 'the knowledge and skill that you have gained through doing something for a period of time; the process of gaining this', '', 'My lack of practical experience was a disadvantage.', '', ARRAY[]::TEXT[]),
('Experience', 'experience_us.mp3', 'verb', 'B1', 'to have a particular situation affect you or happen to you', '', 'Many people have never experienced these difficulties first-hand.', '', ARRAY[]::TEXT[]),
('Experienced', 'experienced_us.mp3', 'adjective', 'B1', 'having knowledge or skill in a particular job or activity', '', 'an experienced player/teacher', '', ARRAY[]::TEXT[]),
('Experiment', 'experiment_us.mp3', 'noun', 'B1', 'a scientific test that is done in order to study what happens and to gain new knowledge', '', 'to do/perform/conduct an experiment', '', ARRAY[]::TEXT[]),
('Experiment', 'experiment_us.mp3', 'verb', 'B1', 'to do a scientific experiment or experiments', '', 'After experimenting at Columbia University, he realized that fission was the key to releasing nuclear energy.', '', ARRAY[]::TEXT[]),
('Experimental', 'experimental_us.mp3', 'adjective', 'B1', 'based on new ideas, forms or methods that are used to find out what effect they have', '', 'The school''s experimental teaching methods include letting the children decide what to study.', '', ARRAY[]::TEXT[]),
('Expert', 'expert_us.mp3', 'adjective', 'B1', 'done with, having or involving great knowledge or skill', '', 'to seek expert advice', '', ARRAY[]::TEXT[]),
('Expert', 'expert_us.mp3', 'noun', 'B1', 'a person with special knowledge, skill or training in something', '', 'a legal/security/medical/computer expert', '', ARRAY[]::TEXT[]),
('Expertise', 'expertise_us.mp3', 'noun', 'B1', 'expert knowledge or skill in a particular subject, activity or job', '', 'professional/scientific/technical, etc. expertise', '', ARRAY[]::TEXT[]),
('Expire', 'expire_us.mp3', 'verb', 'B1', 'to be no longer legally acceptable because the period of time for which it could be used has ended', '', 'When does your driving licence expire?', '', ARRAY[]::TEXT[]),
('Explain', 'explain_us.mp3', 'verb', 'B1', 'to tell somebody about something in a way that makes it easy to understand', '', 'explain (something), He was trying to explain the difference between hip hop and rap.', '', ARRAY[]::TEXT[]),
('Explanation', 'explanation_us.mp3', 'noun', 'B1', 'a statement, fact, or situation that tells you why something happened; a reason given for something', '', 'The most likely explanation is that his plane was delayed.', '', ARRAY[]::TEXT[]),
('Explicit', 'explicit_us.mp3', 'adjective', 'B1', 'clear and easy to understand, so that you have no doubt what is meant', '', 'He gave me very explicit directions on how to get there.', '', ARRAY[]::TEXT[]),
('Explicitly', 'explicitly_us.mp3', 'adverb', 'B1', 'clearly or directly, so that the meaning is easy to understand', '', 'The report states explicitly that the system was to blame.', '', ARRAY[]::TEXT[]),
('Explode', 'explode_us.mp3', 'verb', 'B1', 'to burst (= break apart) or make something burst loudly and violently, causing damage', '', 'A second bomb exploded in a crowded market.', '', ARRAY[]::TEXT[]),
('Exploit', 'exploit_us.mp3', 'verb', 'B1', 'to treat a person or situation as an opportunity to gain an advantage for yourself', '', 'He exploited his father''s name to get himself a job.', '', ARRAY[]::TEXT[]),
('Exploitation', 'exploitation_us.mp3', 'noun', 'B1', 'a situation in which somebody treats somebody else in an unfair way, especially in order to make money from their work', '', 'the exploitation of children', '', ARRAY[]::TEXT[]),
('Exploration', 'exploration_us.mp3', 'noun', 'B1', 'the act of travelling through a place in order to find out about it or look for something in it', '', 'Budgets for space exploration have been cut back.', '', ARRAY[]::TEXT[]),
('Explore', 'explore_us.mp3', 'verb', 'B1', 'to travel to or around an area or a country in order to learn about it', '', 'As soon as we arrived on the island we were eager to explore.', '', ARRAY[]::TEXT[]),
('Explosion', 'explosion_us.mp3', 'noun', 'B1', 'the sudden violent bursting and loud noise of something such as a bomb exploding; the act of deliberately causing something to explode', '', 'a bomb/nuclear/gas explosion', '', ARRAY[]::TEXT[]),
('Explosive', 'explosive_us.mp3', 'adjective', 'B1', 'easily able or likely to explode', '', 'an explosive device (= a bomb)', '', ARRAY[]::TEXT[]),
('Explosive', 'explosive_us.mp3', 'noun', 'B1', 'a substance that is able or likely to cause an explosion', '', 'plastic explosives', '', ARRAY[]::TEXT[]),
('Export', 'export_us.mp3', 'noun', 'B1', 'the selling and transporting of goods to another country', '', 'a ban on the export of live cattle', '', ARRAY[]::TEXT[]),
('Export', 'export_us.mp3', 'verb', 'B1', 'to sell and send goods to another country', '', 'export (something), The islands export sugar and fruit.', '', ARRAY[]::TEXT[]),
('Expose', 'expose_us.mp3', 'verb', 'B1', 'to show something that is usually hidden', '', 'expose something, He smiled suddenly, exposing a set of amazingly white teeth.', '', ARRAY[]::TEXT[]),
('Exposure', 'exposure_us.mp3', 'noun', 'B1', 'the state of being in a place or situation where there is no protection from something harmful or unpleasant', '', 'prolonged exposure to harmful radiation', '', ARRAY[]::TEXT[]),
('Express', 'express_us.mp3', 'verb', 'B1', 'to show or make known a feeling, an opinion, etc. by words, looks or actions', '', 'express something, Teachers have expressed concern about the changes.', '', ARRAY[]::TEXT[]),
('Expression', 'expression_us.mp3', 'noun', 'B1', 'a word or phrase', '', 'What''s the meaning of the expression ‘on cloud nine’?', '', ARRAY[]::TEXT[]),
('Extend', 'extend_us.mp3', 'verb', 'B1', 'to make something longer or larger', '', 'to extend a fence/road/house', '', ARRAY[]::TEXT[]),
('Extension', 'extension_us.mp3', 'noun', 'B1', 'the act of increasing the area of activity, group of people, etc. that is affected by something', '', 'the extension of new technology into developing countries', '', ARRAY[]::TEXT[]),
('Extensive', 'extensive_us.mp3', 'adjective', 'B1', 'covering a large area; great in amount', '', 'The house has extensive grounds.', '', ARRAY[]::TEXT[]),
('Extensively', 'extensively_us.mp3', 'adverb', 'B1', 'in a way that covers a large area', '', 'She has travelled extensively.', '', ARRAY[]::TEXT[]),
('Extent', 'extent_us.mp3', 'noun', 'B1', 'how large, important, serious, etc. something is', '', 'It is difficult to assess the full extent of the damage.', '', ARRAY[]::TEXT[]),
('External', 'external_us.mp3', 'adjective', 'B1', 'connected with or located on the outside of something/somebody', '', 'the external walls of the building', '', ARRAY[]::TEXT[]),
('Extra', 'extra_us.mp3', 'adjective', 'B1', 'more than is usual, expected, or than exists already', '', 'extra money/cash/funding', '', ARRAY[]::TEXT[]),
('Extra', 'extra_us.mp3', 'adverb', 'B1', 'in addition; more than is usual, expected or exists already', '', 'to pay/cost extra', '', ARRAY[]::TEXT[]),
('Extra', 'extra_us.mp3', 'noun', 'B1', 'a thing that is added to something that is not usual, standard or necessary and that costs more', '', 'The monthly fee is fixed and there are no hidden extras (= unexpected costs).', '', ARRAY[]::TEXT[]),
('Extract', 'extract_us.mp3', 'noun', 'B1', 'a short passage from a book, piece of music, etc. that gives you an idea of what the whole thing is like', '', 'The following extract is taken from her new novel.', '', ARRAY[]::TEXT[]),
('Extract', 'extract_us.mp3', 'verb', 'B1', 'to remove or obtain a substance from something, for example by using an industrial or a chemical process', '', 'a machine that extracts excess moisture from the air', '', ARRAY[]::TEXT[]),
('Extraordinary', 'extraordinary_us.mp3', 'adjective', 'B1', 'unexpected, surprising or strange', '', 'What an extraordinary thing to say!', '', ARRAY[]::TEXT[]),
('Extreme', 'extreme_us.mp3', 'adjective', 'B1', 'very great in degree', '', 'We are working under extreme pressure at the moment.', '', ARRAY[]::TEXT[]),
('Extreme', 'extreme_us.mp3', 'noun', 'B1', 'a feeling, situation, way of behaving, etc. that is as different as possible from another or is opposite to it', '', 'extremes of love and hate', '', ARRAY[]::TEXT[]),
('Extremely', 'extremely_us.mp3', 'adverb', 'B1', 'to a very high degree', '', 'It is extremely important to follow the directions exactly.', '', ARRAY[]::TEXT[]),
('Extremist', 'extremist_us.mp3', 'noun', 'B1', 'a person whose opinions, especially about religion or politics, are extreme, and who may do things that are violent or illegal for what they believe', '', 'left-wing/right-wing/political/religious extremists', '', ARRAY[]::TEXT[]),
('Eye', 'eye_us.mp3', 'noun', 'B1', 'either of the two organs on the face that you see with', '', 'The suspect has dark hair and green eyes.', '', ARRAY[]::TEXT[]),
('Fabric', 'fabric_us.mp3', 'noun', 'B1', 'material made by weaving wool, cotton, silk, etc., used for making clothes, curtains, etc. and for covering furniture', '', 'They sell a wide variety of printed cotton fabric.', '', ARRAY[]::TEXT[]),
('Fabulous', 'fabulous_us.mp3', 'adjective', 'B1', 'extremely good', '', 'They put on a fabulous performance.', '', ARRAY[]::TEXT[]),
('Face', 'face_us.mp3', 'noun', 'B1', 'the front part of the head, where the eyes, nose and mouth are', '', 'a pretty/pale/round face', '', ARRAY[]::TEXT[]),
('Face', 'face_us.mp3', 'verb', 'B1', 'to be opposite somebody/something; to have your face or front pointing towards somebody/something or in a particular direction', '', 'face somebody/something, She turned and faced him.', '', ARRAY[]::TEXT[]),
('Facilitate', 'facilitate_us.mp3', 'verb', 'B1', 'to make an action or a process possible or easier', '', 'The new trade agreement should facilitate more rapid economic growth.', '', ARRAY[]::TEXT[]),
('Facility', 'facility_us.mp3', 'noun', 'B1', 'buildings, services, equipment, etc. that are provided for a particular purpose', '', 'leisure/sports facilities', '', ARRAY[]::TEXT[]),
('Fact', 'fact_us.mp3', 'noun', 'B1', 'a thing that is known to be true, especially when it can be proved', '', 'fact about something, First, some basic facts about healthy eating.', '', ARRAY[]::TEXT[]),
('Faction', 'faction_us.mp3', 'noun', 'B1', 'a small group of people within a larger one, whose members have some different aims and beliefs to those of the larger group', '', 'There are rival factions within the administration.', '', ARRAY[]::TEXT[]),
('Factor', 'factor_us.mp3', 'noun', 'B1', 'one of several things that cause or influence something', '', 'Obesity is a major risk factor for heart disease.', '', ARRAY[]::TEXT[]),
('Factory', 'factory_us.mp3', 'noun', 'B1', 'a building or group of buildings where goods are made, mainly by machine', '', 'a car factory', '', ARRAY[]::TEXT[]),
('Faculty', 'faculty_us.mp3', 'noun', 'B1', 'a department or group of related departments in a college or university', '', 'the Faculty of Law', '', ARRAY[]::TEXT[]),
('Fade', 'fade_us.mp3', 'verb', 'B1', 'to become or to make something become paler or less bright', '', 'The curtains had faded in the sun.', '', ARRAY[]::TEXT[]),
('Fail', 'fail_us.mp3', 'verb', 'B1', 'to not be successful in achieving something', '', 'Many diets fail because they are boring.', '', ARRAY[]::TEXT[]),
('Failed', 'failed_us.mp3', 'adjective', 'B1', 'not successful', '', 'a failed writer', '', ARRAY[]::TEXT[]),
('Failure', 'failure_us.mp3', 'noun', 'B1', 'lack of success in doing or achieving something', '', 'The success or failure of the plan depends on you.', '', ARRAY[]::TEXT[]),
('Fair', 'fair_us.mp3', 'adjective', 'B1', 'acceptable and appropriate in a particular situation', '', 'a fair deal/wage/price', '', ARRAY[]::TEXT[]),
('Fairly', 'fairly_us.mp3', 'adverb', 'B1', 'to some extent but not very', '', 'fairly simple/easy/straightforward', '', ARRAY[]::TEXT[]),
('Fairness', 'fairness_us.mp3', 'noun', 'B1', 'the quality of treating people equally or in a way that is reasonable', '', 'The fairness of the judicial system is being questioned.', '', ARRAY[]::TEXT[]),
('Faith', 'faith_us.mp3', 'noun', 'B1', 'trust in somebody’s ability or knowledge; trust that somebody/something will do what has been promised', '', 'If the company can retain its customers'' faith, it could become the market leader.', '', ARRAY[]::TEXT[]),
('Fake', 'fake_us.mp3', 'adjective', 'B1', 'not what somebody claims it is; appearing to be something it is not', '', 'There were a few stalls selling fake designer clothing.', '', ARRAY[]::TEXT[]),
('Fall', 'fall_us.mp3', 'noun', 'B1', 'an act of falling', '', 'I had a bad fall and broke my arm.', '', ARRAY[]::TEXT[]),
('Fall', 'fall_us.mp3', 'verb', 'B1', 'to drop down from a higher level to a lower level', '', 'The rain was falling steadily.', '', ARRAY[]::TEXT[]),
('False', 'false_us.mp3', 'adjective', 'B1', 'wrong; not correct or true', '', 'A whale is a fish. True or false?', '', ARRAY[]::TEXT[]),
('Fame', 'fame_us.mp3', 'noun', 'B1', 'the state of being known and talked about by many people', '', 'to achieve/win instant fame', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
