INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Truth', 'truth_us.mp3', 'noun', 'B1', 'the true facts about something, rather than the things that have been invented or guessed', '', 'Do you think she''s telling the truth?', '', ARRAY[]::TEXT[]),
('Try', 'try_us.mp3', 'noun', 'B1', 'an act of trying to do something', '', 'I doubt they''ll be able to help but it''s worth a try (= worth asking them).', '', ARRAY[]::TEXT[]),
('Try', 'try_us.mp3', 'verb', 'B1', 'to make an attempt or effort to do or get something', '', 'I don''t know if I can come but I''ll try.', '', ARRAY[]::TEXT[]),
('Tsunami', 'tsunami_us.mp3', 'noun', 'B1', 'an extremely large wave in the sea caused, for example, by an earthquake', '', 'A tsunami early warning system was set up in Hawaii.', '', ARRAY[]::TEXT[]),
('Tube', 'tube_us.mp3', 'noun', 'B1', 'a long, hollow pipe made of metal, plastic, rubber, etc., through which liquids or gases move from one place to another', '', 'He had to be fed through a feeding tube for several months.', '', ARRAY[]::TEXT[]),
('Tuesday', 'Tuesday_us.mp3', 'noun', 'B1', 'the day of the week after Monday and before Wednesday', '', 'It''s Tuesday today, isn''t it?', '', ARRAY[]::TEXT[]),
('Tuition', 'tuition_us.mp3', 'noun', 'B1', 'the act of teaching something, especially to one person or to people in small groups', '', 'She received private tuition in French.', '', ARRAY[]::TEXT[]),
('Tune', 'tune_us.mp3', 'noun', 'B1', 'a series of musical notes that are sung or played in a particular order to form a piece of music', '', 'to sing/whistle a tune', '', ARRAY[]::TEXT[]),
('Tunnel', 'tunnel_us.mp3', 'noun', 'B1', 'a passage built underground, for example to allow a road or railway to go through a hill, under a river, etc.', '', 'a railway/railroad tunnel', '', ARRAY[]::TEXT[]),
('Turn', 'turn_us.mp3', 'noun', 'B1', 'the time when somebody in a group of people should or is allowed to do something', '', 'When it''s your turn, take another card.', '', ARRAY[]::TEXT[]),
('Turn', 'turn_us.mp3', 'verb', 'B1', 'to move or make something move around a central point', '', 'The wheels of the car began to turn.', '', ARRAY[]::TEXT[]),
('Turnout', 'turnout_us.mp3', 'noun', 'B1', 'the number of people who attend a particular event', '', 'This year''s festival attracted a record turnout.', '', ARRAY[]::TEXT[]),
('Turnover', 'turnover_us.mp3', 'noun', 'B1', 'the total amount of goods or services sold by a company during a particular period of time', '', 'an annual turnover of $75 million', '', ARRAY[]::TEXT[]),
('TV', 'TV_us.mp3', 'noun', 'B1', 'television', '', 'We spent the evening watching TV.', '', ARRAY[]::TEXT[]),
('Twelve', 'twelve_us.mp3', 'number', 'B1', '12', '', 'There are only twelve of these rare animals left.', '', ARRAY[]::TEXT[]),
('Twice', 'twice_us.mp3', 'adverb', 'B1', 'two times; on two occasions', '', 'I don''t know him well; I''ve only met him twice.', '', ARRAY[]::TEXT[]),
('Twin', 'twin_us.mp3', 'adjective', 'B1', 'used to describe one of a pair of children who are twins', '', 'a twin brother/sister', '', ARRAY[]::TEXT[]),
('Twin', 'twin_us.mp3', 'noun', 'B1', 'one of two children born at the same time to the same mother', '', 'She''s expecting twins.', '', ARRAY[]::TEXT[]),
('Twist', 'twist_us.mp3', 'noun', 'B1', 'the action of turning something with your hand, or of turning a part of your body', '', 'She gave the lid another twist and it came off.', '', ARRAY[]::TEXT[]),
('Twist', 'twist_us.mp3', 'verb', 'B1', 'to bend or turn something into a particular shape', '', 'Twist the wire to form a circle.', '', ARRAY[]::TEXT[]),
('Two', 'two_us.mp3', 'number', 'B1', '2', '', 'There are only two cookies left.', '', ARRAY[]::TEXT[]),
('Type', 'type_us.mp3', 'noun', 'B1', 'a class or group of people or things that share particular qualities or features and are part of a larger group; a kind or sort', '', 'a rare blood type', '', ARRAY[]::TEXT[]),
('Type', 'type_us.mp3', 'verb', 'B1', 'to write something using a computer keyboard or typewriter', '', 'How fast can you type?', '', ARRAY[]::TEXT[]),
('Typical', 'typical_us.mp3', 'adjective', 'B1', 'having the usual qualities or features of a particular type of person, thing or group', '', 'a typical Italian cafe', '', ARRAY[]::TEXT[]),
('Typically', 'typically_us.mp3', 'adverb', 'B1', 'used to say that something usually happens in the way that you are stating', '', 'The standard chips are typically used for databases and other business software.', '', ARRAY[]::TEXT[]),
('Tyre', 'tyre_us.mp3', 'noun', 'B1', 'a thick rubber ring that fits around the edge of a wheel of a car, bicycle, etc.', '', 'a front/rear tyre', '', ARRAY[]::TEXT[]),
('Ugly', 'ugly_us.mp3', 'adjective', 'B1', 'unpleasant to look at', '', 'an ugly face', '', ARRAY[]::TEXT[]),
('Ultimate', 'ultimate_us.mp3', 'adjective', 'B1', 'happening at the end of a long process', '', 'our ultimate goal/aim/objective/target', '', ARRAY[]::TEXT[]),
('Ultimately', 'ultimately_us.mp3', 'adverb', 'B1', 'in the end; finally', '', 'A poor diet will ultimately lead to illness.', '', ARRAY[]::TEXT[]),
('Umbrella', 'umbrella_us.mp3', 'noun', 'B1', 'an object with a round folding frame of long, straight pieces of metal covered with material, that you use to protect yourself from the rain or from hot sun', '', 'to carry/hold an umbrella', '', ARRAY[]::TEXT[]),
('Unable', 'unable_us.mp3', 'adjective', 'B1', 'not having the skill, strength, time, knowledge, etc. to do something', '', 'a former soldier who has been unable to find work since the war ended', '', ARRAY[]::TEXT[]),
('Unacceptable', 'unacceptable_us.mp3', 'adjective', 'B1', 'so bad that you think it should not be allowed', '', 'Such behaviour is totally unacceptable in a civilized society.', '', ARRAY[]::TEXT[]),
('Uncertainty', 'uncertainty_us.mp3', 'noun', 'B1', 'the state of being uncertain', '', 'There is considerable uncertainty about the company''s future.', '', ARRAY[]::TEXT[]),
('Uncle', 'uncle_us.mp3', 'noun', 'B1', 'the brother of your mother or father; the husband of your aunt or uncle', '', 'Uncle Ian', '', ARRAY[]::TEXT[]),
('Uncomfortable', 'uncomfortable_us.mp3', 'adjective', 'B1', 'not letting you feel physically comfortable; unpleasant to wear, sit on, etc.', '', 'uncomfortable shoes', '', ARRAY[]::TEXT[]),
('Unconscious', 'unconscious_us.mp3', 'adjective', 'B1', 'in a state like sleep because of an injury or illness, and not able to use your senses', '', 'They found him lying unconscious on the floor.', '', ARRAY[]::TEXT[]),
('Under', 'under_us.mp3', 'adverb', 'B1', 'below something', '', 'He pulled up the covers and crawled under.', '', ARRAY[]::TEXT[]),
('Under', 'under_us.mp3', 'preposition', 'B1', 'in, to or through a position that is below something', '', 'Have you looked under the bed?', '', ARRAY[]::TEXT[]),
('Undergo', 'undergo_us.mp3', 'verb', 'B1', 'to experience something, especially a change or something unpleasant', '', 'to undergo tests/trials/repairs', '', ARRAY[]::TEXT[]),
('Undergraduate', 'undergraduate_us.mp3', 'noun', 'B1', 'a university or college student who is studying for their first degree', '', 'a first-year undergraduate', '', ARRAY[]::TEXT[]),
('Underground', 'underground_us.mp3', 'adjective', 'B1', 'under the surface of the ground', '', 'an underground bunker/tunnel', '', ARRAY[]::TEXT[]),
('Underground', 'underground_us.mp3', 'adverb', 'B1', 'under the surface of the ground', '', 'Rescuers found victims trapped several feet underground.', '', ARRAY[]::TEXT[]),
('Underlying', 'underlying_us.mp3', 'adjective', 'B1', 'important in a situation but not always easily noticed or stated clearly', '', 'The underlying assumption is that the amount of money available is limited.', '', ARRAY[]::TEXT[]),
('Undermine', 'undermine_us.mp3', 'verb', 'B1', 'to make something, especially somebody’s confidence or authority, gradually weaker or less effective', '', 'Our confidence in the team has been seriously undermined by their recent defeats.', '', ARRAY[]::TEXT[]),
('Understand', 'understand_us.mp3', 'verb', 'B1', 'to know or realize the meaning of words, a language, what somebody says, etc.', '', 'understand (something), Can you understand French?', '', ARRAY[]::TEXT[]),
('Understanding', 'understanding_us.mp3', 'noun', 'B1', 'the knowledge that somebody has about a particular subject or situation', '', 'Students will gain a broad understanding of the workings of Parliament.', '', ARRAY[]::TEXT[]),
('Undertake', 'undertake_us.mp3', 'verb', 'B1', 'to make yourself responsible for something and start doing it', '', 'to undertake a task/project', '', ARRAY[]::TEXT[]),
('Underwear', 'underwear_us.mp3', 'noun', 'B1', 'clothes that you wear under other clothes and next to the skin', '', 'I never wear underwear.', '', ARRAY[]::TEXT[]),
('Undoubtedly', 'undoubtedly_us.mp3', 'adverb', 'B1', 'used to emphasize that something exists or is definitely true', '', 'There is undoubtedly a great deal of truth in what he says.', '', ARRAY[]::TEXT[]),
('Unemployed', 'unemployed_us.mp3', 'adjective', 'B1', 'without a job although able to work', '', 'How long have you been unemployed?', '', ARRAY[]::TEXT[]),
('Unemployment', 'unemployment_us.mp3', 'noun', 'B1', 'the fact of a number of people not having a job; the number of people without a job', '', 'an area of high/low unemployment', '', ARRAY[]::TEXT[]),
('Unexpected', 'unexpected_us.mp3', 'adjective', 'B1', 'if something is unexpected, it surprises you because you were not expecting it', '', 'Things took an unexpected turn.', '', ARRAY[]::TEXT[]),
('Unfair', 'unfair_us.mp3', 'adjective', 'B1', 'not right or fair according to a set of rules or principles; not treating people equally', '', 'They had been given an unfair advantage.', '', ARRAY[]::TEXT[]),
('Unfold', 'unfold_us.mp3', 'verb', 'B1', 'to spread open or flat something that has previously been folded; to become open and flat', '', 'to unfold a map', '', ARRAY[]::TEXT[]),
('Unfortunate', 'unfortunate_us.mp3', 'adjective', 'B1', 'having bad luck; caused by bad luck', '', 'He was unfortunate to lose in the final round.', '', ARRAY[]::TEXT[]),
('Unfortunately', 'unfortunately_us.mp3', 'adverb', 'B1', 'used to say that a particular situation or fact makes you sad or disappointed, or gets you into a difficult position', '', 'Unfortunately, I won''t be able to attend the meeting.', '', ARRAY[]::TEXT[]),
('Unhappy', 'unhappy_us.mp3', 'adjective', 'B1', 'not happy; sad', '', 'to feel/look/seem/sound/become unhappy', '', ARRAY[]::TEXT[]),
('Uniform', 'uniform_us.mp3', 'noun', 'B1', 'the special set of clothes worn by all members of an organization or a group at work, or by children at school', '', 'The hat is part of the school uniform.', '', ARRAY[]::TEXT[]),
('Unify', 'unify_us.mp3', 'verb', 'B1', 'to join people, things, parts of a country, etc. together so that they form a single unit', '', 'The new leader hopes to unify the country.', '', ARRAY[]::TEXT[]),
('Union', 'union_us.mp3', 'noun', 'B1', 'an organization of workers, usually in a particular industry, that exists to protect their interests, improve conditions of work, etc.', '', 'I''ve joined the union.', '', ARRAY[]::TEXT[]),
('Unique', 'unique_us.mp3', 'adjective', 'B1', 'being the only one of its kind', '', 'Everyone''s fingerprints are unique.', '', ARRAY[]::TEXT[]),
('Unit', 'unit_us.mp3', 'noun', 'B1', 'a single thing, person or group that is complete by itself but can also form part of something larger', '', 'After 1946 the British Government treated the four territorial divisions as a single unit.', '', ARRAY[]::TEXT[]),
('Unite', 'unite_us.mp3', 'verb', 'B1', 'to join together with other people in order to do something as a group', '', 'Nationalist parties united to oppose the government''s plans.', '', ARRAY[]::TEXT[]),
('United', 'united_us.mp3', 'adjective', 'B1', 'joined together as a political unit or by shared aims', '', 'the United States of America', '', ARRAY[]::TEXT[]),
('Unity', 'unity_us.mp3', 'noun', 'B1', 'the state of being in agreement and working together; the state of being joined together to form one unit', '', 'European unity', '', ARRAY[]::TEXT[]),
('Universal', 'universal_us.mp3', 'adjective', 'B1', 'done by or involving all the people in the world or in a particular group', '', 'Such problems are a universal feature of old age.', '', ARRAY[]::TEXT[]),
('Universe', 'universe_us.mp3', 'noun', 'B1', 'the whole of space and everything in it, including the earth, the planets and the stars', '', 'in the universe, Could there be intelligent life elsewhere in the universe?', '', ARRAY[]::TEXT[]),
('University', 'university_us.mp3', 'noun', 'B1', 'an institution at the highest level of education where you can study for a degree or do research', '', 'Is there a university in this town?', '', ARRAY[]::TEXT[]),
('Unknown', 'unknown_us.mp3', 'adjective', 'B1', 'not known or identified', '', 'A previously unknown group claimed responsibility for the bombing.', '', ARRAY[]::TEXT[]),
('Unless', 'unless_us.mp3', 'conjunction', 'B1', 'used to say that something can only happen or be true in a particular situation', '', 'You won''t get paid for time off unless you have a doctor''s note.', '', ARRAY[]::TEXT[]),
('Unlike', 'unlike_us.mp3', 'preposition', 'B1', 'different from a particular person or thing', '', 'Music is quite unlike any other art form.', '', ARRAY[]::TEXT[]),
('Unlikely', 'unlikely_us.mp3', 'adjective', 'B1', 'not likely to happen; not probable', '', 'unlikely to do something, The project seemed unlikely to succeed.', '', ARRAY[]::TEXT[]),
('Unnecessary', 'unnecessary_us.mp3', 'adjective', 'B1', 'not needed; more than is needed', '', 'They were found guilty of causing unnecessary suffering to animals.', '', ARRAY[]::TEXT[]),
('Unpleasant', 'unpleasant_us.mp3', 'adjective', 'B1', 'not pleasant or comfortable', '', 'an unpleasant experience/surprise/task', '', ARRAY[]::TEXT[]),
('Unprecedented', 'unprecedented_us.mp3', 'adjective', 'B1', 'that has never happened, been done or been known before', '', 'The situation is unprecedented in modern times.', '', ARRAY[]::TEXT[]),
('Until', 'until_us.mp3', 'conjunction', 'B1', 'up to the point in time or the event mentioned', '', 'Let''s wait until the rain stops.', '', ARRAY[]::TEXT[]),
('Until', 'until_us.mp3', 'preposition', 'B1', 'up to the point in time or the event mentioned', '', 'Let''s wait until the rain stops.', '', ARRAY[]::TEXT[]),
('Unusual', 'unusual_us.mp3', 'adjective', 'B1', 'different from what is usual or normal', '', 'The case is highly unusual.', '', ARRAY[]::TEXT[]),
('Unveil', 'unveil_us.mp3', 'verb', 'B1', 'to remove a cover or curtain from a painting, statue, etc. so that it can be seen in public for the first time', '', 'The Queen unveiled a plaque to mark the official opening of the hospital.', '', ARRAY[]::TEXT[]),
('Up', 'up_us.mp3', 'adverb', 'B1', 'towards or in a higher position', '', 'He jumped up from his chair.', '', ARRAY[]::TEXT[]),
('Up', 'up_us.mp3', 'preposition', 'B1', 'to or in a higher position somewhere', '', 'She climbed up the flight of steps.', '', ARRAY[]::TEXT[]),
('Upcoming', 'upcoming_us.mp3', 'adjective', 'B1', 'going to happen soon', '', 'the upcoming presidential election', '', ARRAY[]::TEXT[]),
('Update', 'update_us.mp3', 'noun', 'B1', 'a report or broadcast that gives the most recent information about something; a new version of something containing the most recent information', '', 'They will send you regular updates by email.', '', ARRAY[]::TEXT[]),
('Update', 'update_us.mp3', 'verb', 'B1', 'to make something more modern by adding new parts, etc.', '', 'an updated version of the app', '', ARRAY[]::TEXT[]),
('Upgrade', 'upgrade_us.mp3', 'noun', 'B1', 'the act of making a machine, computer system, etc. more powerful and efficient; the more powerful and efficient machine, computer system, etc.', '', 'instructions for installing an upgrade to the existing system', '', ARRAY[]::TEXT[]),
('Upgrade', 'upgrade_us.mp3', 'verb', 'B1', 'to make a machine, computer system, etc. more powerful and efficient; to start using a new and better version of a machine, system, etc.', '', 'upgrade something, We are constantly upgrading our software to meet customers'' needs.', '', ARRAY[]::TEXT[]),
('Uphold', 'uphold_us.mp3', 'verb', 'B1', 'to support something that you think is right and make sure that it continues to exist', '', 'We have a duty to uphold the law.', '', ARRAY[]::TEXT[]),
('Upper', 'upper_us.mp3', 'adjective', 'B1', 'located above something else, especially something of the same type or the other of a pair', '', 'her upper lip', '', ARRAY[]::TEXT[]),
('Upset', 'upset_us.mp3', 'adjective', 'B1', 'unhappy or disappointed because of something unpleasant that has happened', '', 'I understand how upset you must be feeling.', '', ARRAY[]::TEXT[]),
('Upset', 'upset_us.mp3', 'verb', 'B1', 'to make somebody/yourself feel unhappy, anxious or annoyed', '', 'upset somebody/yourself, This decision is likely to upset a lot of people.', '', ARRAY[]::TEXT[]),
('Upstairs', 'upstairs_us.mp3', 'adjective', 'B1', 'on a floor of a house or other building that is higher than the one that you are on', '', 'an upstairs room/window/bathroom', '', ARRAY[]::TEXT[]),
('Upstairs', 'upstairs_us.mp3', 'adverb', 'B1', 'up the stairs; on or to a floor of a house or other building higher than the one that you are on', '', 'to run/walk/head upstairs', '', ARRAY[]::TEXT[]),
('Upwards', 'upwards_us.mp3', 'adverb', 'B1', 'towards a higher place or position', '', 'Place your hands on the table with the palms facing upwards.', '', ARRAY[]::TEXT[]),
('Urban', 'urban_us.mp3', 'adjective', 'B1', 'connected with a town or city', '', 'urban and rural communities', '', ARRAY[]::TEXT[]),
('Urge', 'urge_us.mp3', 'verb', 'B1', 'to advise or try hard to persuade somebody to do something', '', 'urge somebody to do something, If you ever get the chance to visit this place, I strongly urge you to do so.', '', ARRAY[]::TEXT[]),
('Urgent', 'urgent_us.mp3', 'adjective', 'B1', 'that needs to be dealt with or happen immediately', '', 'The police have issued an urgent appeal for information.', '', ARRAY[]::TEXT[]),
('Us', 'us_us.mp3', 'pronoun', 'B1', 'used when the speaker or writer and another or others are the object of a verb or preposition, or after the verb be', '', 'She gave us a picture as a wedding present.', '', ARRAY[]::TEXT[]),
('Usage', 'usage_us.mp3', 'noun', 'B1', 'the way in which words are used in a language', '', 'a book on current English usage', '', ARRAY[]::TEXT[]),
('Use', 'use_us.mp3', 'noun', 'B1', 'the act of using something; the state of being used', '', 'A ban was imposed on the use of chemical weapons.', '', ARRAY[]::TEXT[]),
('Use', 'use_us.mp3', 'verb', 'B1', 'to do something with a machine, a method, an object, etc. for a particular purpose', '', 'use something, Can I use the photocopier?', '', ARRAY[]::TEXT[]),
('Used', 'used_us.mp3', 'adjective', 'B1', 'familiar with something because you do it or experience it often', '', 'used to doing something, I''m not used to eating so much at lunchtime.', '', ARRAY[]::TEXT[]),
('Used to', 'used to_us.mp3', 'modal verb', 'B1', 'used to say that something happened continuously or frequently during a period in the past', '', 'I used to live in London.', '', ARRAY[]::TEXT[]),
('Useful', 'useful_us.mp3', 'adjective', 'B1', 'that can help you to do or achieve what you want', '', 'a useful tool', '', ARRAY[]::TEXT[]),
('Useless', 'useless_us.mp3', 'adjective', 'B1', 'not useful; not doing or achieving what is needed or wanted', '', 'This pen is useless.', '', ARRAY[]::TEXT[]),
('User', 'user_us.mp3', 'noun', 'B1', 'a person or thing that uses something', '', 'road users', '', ARRAY[]::TEXT[]),
('Usual', 'usual_us.mp3', 'adjective', 'B1', 'that happens or is done most of the time or in most cases', '', 'This is the usual way of doing it.', '', ARRAY[]::TEXT[]),
('Usually', 'usually_us.mp3', 'adverb', 'B1', 'in the way that is usual or normal; most often', '', 'How long does the journey usually take?', '', ARRAY[]::TEXT[]),
('Utility', 'utility_us.mp3', 'noun', 'B1', 'a service provided for the public, for example an electricity, water or gas supply', '', 'a privatized electricity utility', '', ARRAY[]::TEXT[]),
('Utilize', 'utilize_us.mp3', 'verb', 'B1', 'to use something, especially for a practical purpose', '', 'The Romans were the first to utilize concrete as a building material.', '', ARRAY[]::TEXT[]),
('Utterly', 'utterly_us.mp3', 'adverb', 'B1', 'completely', '', 'We''re so utterly different from each other.', '', ARRAY[]::TEXT[]),
('Vacation', 'vacation_us.mp3', 'noun', 'B1', 'a period of time spent travelling or resting away from home', '', 'on vacation, They''re on vacation in Hawaii right now.', '', ARRAY[]::TEXT[]),
('Vacuum', 'vacuum_us.mp3', 'noun', 'B1', 'a space that is completely empty of all substances, including all air or other gas', '', 'a vacuum pump (= one that creates a vacuum)', '', ARRAY[]::TEXT[]),
('Vague', 'vague_us.mp3', 'adjective', 'B1', 'not clear in a person’s mind', '', 'to have a vague impression/memory/recollection of something', '', ARRAY[]::TEXT[]),
('Valid', 'valid_us.mp3', 'adjective', 'B1', 'that is legally or officially acceptable', '', 'Do you have a valid passport?', '', ARRAY[]::TEXT[]),
('Validity', 'validity_us.mp3', 'noun', 'B1', 'the state of being legally or officially acceptable', '', 'The period of validity of the agreement has expired.', '', ARRAY[]::TEXT[]),
('Valley', 'valley_us.mp3', 'noun', 'B1', 'an area of low land between hills or mountains, often with a river flowing through it; the land that a river flows through', '', 'in a valley, In the valley below cows were grazing peacefully.', '', ARRAY[]::TEXT[]),
('Valuable', 'valuable_us.mp3', 'adjective', 'B1', 'worth a lot of money', '', 'My home is my most valuable asset.', '', ARRAY[]::TEXT[]),
('Value', 'value_us.mp3', 'noun', 'B1', 'how much something is worth in money or other goods for which it can be exchanged', '', 'to go up/rise/increase in value', '', ARRAY[]::TEXT[]),
('Value', 'value_us.mp3', 'verb', 'B1', 'to think that somebody/something is important', '', 'value somebody/something, He has come to value her advice and support.', '', ARRAY[]::TEXT[]),
('Van', 'van_us.mp3', 'noun', 'B1', 'a covered vehicle with no side windows in its back half, usually smaller than a lorry, used for carrying goods or people', '', 'the driver of a white van', '', ARRAY[]::TEXT[]),
('Vanish', 'vanish_us.mp3', 'verb', 'B1', 'to disappear suddenly and/or in a way that you cannot explain', '', 'He turned around and vanished into the house.', '', ARRAY[]::TEXT[]),
('Variable', 'variable_us.mp3', 'adjective', 'B1', 'often changing; likely to change', '', 'variable temperatures', '', ARRAY[]::TEXT[]),
('Variable', 'variable_us.mp3', 'noun', 'B1', 'a situation, number or quantity that can vary or be varied', '', 'With so many variables, it is difficult to calculate the cost.', '', ARRAY[]::TEXT[]),
('Variation', 'variation_us.mp3', 'noun', 'B1', 'a change, especially in the amount or level of something', '', 'The dial records very slight variations in pressure.', '', ARRAY[]::TEXT[]),
('Varied', 'varied_us.mp3', 'adjective', 'B1', 'of many different types', '', 'varied opinions', '', ARRAY[]::TEXT[]),
('Variety', 'variety_us.mp3', 'noun', 'B1', 'several different sorts of the same thing', '', 'There is a wide variety of patterns to choose from.', '', ARRAY[]::TEXT[]),
('Various', 'various_us.mp3', 'adjective', 'B1', 'several different', '', 'various types/forms/kinds of somebody/something', '', ARRAY[]::TEXT[]),
('Vary', 'vary_us.mp3', 'verb', 'B1', 'to be different from each other in size, shape, etc.', '', 'New techniques were introduced with varying degrees of success.', '', ARRAY[]::TEXT[]),
('Vast', 'vast_us.mp3', 'adjective', 'B1', 'extremely large in area, size, amount, etc.', '', 'a vast area of forest', '', ARRAY[]::TEXT[]),
('Vegetable', 'vegetable_us.mp3', 'noun', 'B1', 'a plant or part of a plant that is eaten as food. Potatoes, beans and onions are all vegetables.', '', 'The children don''t eat enough fresh vegetables.', '', ARRAY[]::TEXT[]),
('Vehicle', 'vehicle_us.mp3', 'noun', 'B1', 'a thing that is used for transporting people or goods from one place to another, such as a car or lorry', '', 'motor vehicles (= cars, buses, lorries, etc.)', '', ARRAY[]::TEXT[]),
('Vein', 'vein_us.mp3', 'noun', 'B1', 'any of the tubes that carry blood from all parts of the body towards the heart', '', 'the jugular vein', '', ARRAY[]::TEXT[]),
('Venture', 'venture_us.mp3', 'noun', 'B1', 'a business project or activity, especially one that involves taking risks', '', 'A disastrous business venture lost him thousands of dollars.', '', ARRAY[]::TEXT[]),
('Venture', 'venture_us.mp3', 'verb', 'B1', 'to go somewhere even though you know that it might be dangerous or unpleasant', '', 'They ventured nervously into the water.', '', ARRAY[]::TEXT[]),
('Venue', 'venue_us.mp3', 'noun', 'B1', 'a place where people meet for an organized event, for example a concert, sporting event or conference', '', 'The band will be playing at 20 different venues on their UK tour.', '', ARRAY[]::TEXT[]),
('Verbal', 'verbal_us.mp3', 'adjective', 'B1', 'relating to words', '', 'The job applicant must have good verbal skills.', '', ARRAY[]::TEXT[]),
('Verdict', 'verdict_us.mp3', 'noun', 'B1', 'an official judgement made in court or at an inquest (= an official investigation into somebody''s death)', '', 'Has the jury reached a verdict?', '', ARRAY[]::TEXT[]),
('Verify', 'verify_us.mp3', 'verb', 'B1', 'to check that something is true or accurate', '', 'verify something, We have no way of verifying his story.', '', ARRAY[]::TEXT[]),
('Verse', 'verse_us.mp3', 'noun', 'B1', 'writing that is arranged in lines, often with a regular rhythm or pattern of rhyme', '', 'in verse, Most of the play is written in verse, but some of it is in prose.', '', ARRAY[]::TEXT[]),
('Version', 'version_us.mp3', 'noun', 'B1', 'a form of something that is slightly different from an earlier form or from other forms of the same thing', '', 'version of something, the latest version of the software package', '', ARRAY[]::TEXT[]),
('Versus', 'versus_us.mp3', 'preposition', 'B1', 'used to show that two teams or sides are against each other', '', 'It is France versus Brazil in the final.', '', ARRAY[]::TEXT[]),
('Vertical', 'vertical_us.mp3', 'adjective', 'B1', 'going straight up or down from a level surface or from top to bottom in a picture, etc.', '', 'the vertical axis of the graph', '', ARRAY[]::TEXT[]),
('Very', 'very_us.mp3', 'adjective', 'B1', 'used to emphasize that you are talking about a particular thing or person and not about another', '', 'He might be phoning her at this very moment.', '', ARRAY[]::TEXT[]),
('Very', 'very_us.mp3', 'adverb', 'B1', 'used before adjectives, adverbs and determiners to mean ‘in a high degree’ or ‘extremely’', '', 'Very few people know that.', '', ARRAY[]::TEXT[]),
('Vessel', 'vessel_us.mp3', 'noun', 'B1', 'a tube that carries blood through the body of a person or an animal, or liquid through the parts of a plant', '', 'to burst/rupture a blood vessel', '', ARRAY[]::TEXT[]),
('Veteran', 'veteran_us.mp3', 'noun', 'B1', 'a person who has a lot of experience in a particular area or activity', '', 'the veteran American actor, Clint Eastwood', '', ARRAY[]::TEXT[]),
('Via', 'via_us.mp3', 'preposition', 'B1', 'through a place', '', 'We flew home via Dubai.', '', ARRAY[]::TEXT[]),
('Viable', 'viable_us.mp3', 'adjective', 'B1', 'that can be done; that will be successful', '', 'a viable option/proposition', '', ARRAY[]::TEXT[]),
('Vibrant', 'vibrant_us.mp3', 'adjective', 'B1', 'full of life and energy', '', 'a vibrant city', '', ARRAY[]::TEXT[]),
('Vice', 'vice_us.mp3', 'noun', 'B1', 'criminal activities that involve sex or drugs', '', 'At the door were two plain-clothes detectives from the vice squad.', '', ARRAY[]::TEXT[]),
('Vicious', 'vicious_us.mp3', 'adjective', 'B1', 'violent and cruel', '', 'a vicious attack', '', ARRAY[]::TEXT[]),
('Victim', 'victim_us.mp3', 'noun', 'B1', 'a person who has been attacked, injured or killed as the result of a crime, a disease, an accident, etc.', '', 'shooting/murder victims', '', ARRAY[]::TEXT[]),
('Victory', 'victory_us.mp3', 'noun', 'B1', 'success in a game, an election, a war, etc.', '', 'to win a narrow victory', '', ARRAY[]::TEXT[]),
('Video', 'video_us.mp3', 'noun', 'B1', 'a system of recording moving pictures and sound, either using a digital method of storing data or (in the past) using videotape', '', 'A wedding is the perfect subject for video.', '', ARRAY[]::TEXT[]),
('View', 'view_us.mp3', 'noun', 'B1', 'what you can see from a particular place or position, especially beautiful countryside', '', 'view of something, There were magnificent views of the surrounding countryside.', '', ARRAY[]::TEXT[]),
('View', 'view_us.mp3', 'verb', 'B1', 'to think about somebody/something in a particular way', '', 'view somebody/something + adv./prep., How do you view your position within the company?', '', ARRAY[]::TEXT[]),
('Viewer', 'viewer_us.mp3', 'noun', 'B1', 'a person watching television or a video on the internet', '', 'The programme attracted millions of viewers.', '', ARRAY[]::TEXT[]),
('Viewpoint', 'viewpoint_us.mp3', 'noun', 'B1', 'a way of thinking about a subject', '', 'from a… viewpoint, Try looking at things from a different viewpoint.', '', ARRAY[]::TEXT[]),
('Village', 'village_us.mp3', 'noun', 'B1', 'a very small town located in a country area', '', 'We visited towns and villages all over Spain.', '', ARRAY[]::TEXT[]),
('Villager', 'villager_us.mp3', 'noun', 'B1', 'a person who lives in a village', '', 'Some of the villagers have lived here all their lives.', '', ARRAY[]::TEXT[]),
('Violate', 'violate_us.mp3', 'verb', 'B1', 'to go against or refuse to obey a law, an agreement, etc.', '', 'to violate international law', '', ARRAY[]::TEXT[]),
('Violation', 'violation_us.mp3', 'noun', 'B1', 'the act of going against or refusing to obey a law, an agreement, etc.', '', 'They were in open violation of the treaty.', '', ARRAY[]::TEXT[]),
('Violence', 'violence_us.mp3', 'noun', 'B1', 'violent behaviour that is intended to hurt or kill somebody', '', 'Police do not think this killing was a random act of violence.', '', ARRAY[]::TEXT[]),
('Violent', 'violent_us.mp3', 'adjective', 'B1', 'involving or caused by physical force that is intended to hurt or kill somebody', '', 'violent crime/criminals', '', ARRAY[]::TEXT[]),
('Virtual', 'virtual_us.mp3', 'adjective', 'B1', 'made to appear to exist by the use of computer software, for example on the internet', '', 'a system to help programmers create virtual environments', '', ARRAY[]::TEXT[]),
('Virtue', 'virtue_us.mp3', 'noun', 'B1', 'behaviour or attitudes that show high moral standards', '', 'He led a life of virtue.', '', ARRAY[]::TEXT[]),
('Virus', 'virus_us.mp3', 'noun', 'B1', 'a living thing, too small to be seen without a microscope, that causes disease in people, animals and plants', '', 'the flu/influenza virus', '', ARRAY[]::TEXT[]),
('Visa', 'visa_us.mp3', 'noun', 'B1', 'a stamp or mark put in your passport by officials of a foreign country that gives you permission to enter, pass through or leave their country', '', 'to apply for a visa', '', ARRAY[]::TEXT[]),
('Visible', 'visible_us.mp3', 'adjective', 'B1', 'that can be seen', '', 'The house is clearly visible from the beach.', '', ARRAY[]::TEXT[]),
('Vision', 'vision_us.mp3', 'noun', 'B1', 'the ability to see; the area that you can see from a particular position', '', 'to have good/perfect/poor/blurred/normal vision', '', ARRAY[]::TEXT[]),
('Visit', 'visit_us.mp3', 'noun', 'B1', 'an occasion or a period of time when somebody goes to see a place or person and spends time there', '', 'a two-day/three-day visit', '', ARRAY[]::TEXT[]),
('Visit', 'visit_us.mp3', 'verb', 'B1', 'to go to see a person or a place for a period of time', '', 'My parents are coming to visit me next week.', '', ARRAY[]::TEXT[]),
('Visitor', 'visitor_us.mp3', 'noun', 'B1', 'a person who visits a person or place', '', 'We''ve got visitors coming this weekend.', '', ARRAY[]::TEXT[]),
('Visual', 'visual_us.mp3', 'adjective', 'B1', 'of or connected with seeing or sight', '', 'the visual arts', '', ARRAY[]::TEXT[]),
('Vital', 'vital_us.mp3', 'adjective', 'B1', 'necessary or essential in order for something to succeed or exist', '', 'vital for somebody/something, the vitamins that are vital for health', '', ARRAY[]::TEXT[]),
('Vitamin', 'vitamin_us.mp3', 'noun', 'B1', 'a natural substance found in food that is an essential part of what humans and animals need to help them grow and stay healthy. There are many different vitamins.', '', 'vitamin A/B/D/E', '', ARRAY[]::TEXT[]),
('Vocal', 'vocal_us.mp3', 'adjective', 'B1', 'connected with the voice', '', 'vocal music', '', ARRAY[]::TEXT[]),
('Voice', 'voice_us.mp3', 'noun', 'B1', 'the sound or sounds produced through the mouth by a person speaking or singing', '', 'I could hear voices in the next room.', '', ARRAY[]::TEXT[]),
('Volume', 'volume_us.mp3', 'noun', 'B1', 'the amount of space that an object or a substance fills; the amount of space that a container has', '', 'volume of something, How do you measure the volume of a gas?', '', ARRAY[]::TEXT[]),
('Voluntary', 'voluntary_us.mp3', 'adjective', 'B1', 'done willingly, not because you are forced', '', 'a voluntary agreement', '', ARRAY[]::TEXT[]),
('Volunteer', 'volunteer_us.mp3', 'noun', 'B1', 'a person who does a job without being paid for it', '', 'Schools need volunteers to help children to read.', '', ARRAY[]::TEXT[]),
('Volunteer', 'volunteer_us.mp3', 'verb', 'B1', 'to offer to do something without being forced to do it or without getting paid for it', '', 'He has been volunteering for 11 years now.', '', ARRAY[]::TEXT[]),
('Vote', 'vote_us.mp3', 'noun', 'B1', 'a formal choice that you make in an election or at a meeting in order to choose somebody or decide something', '', 'to win/lose votes', '', ARRAY[]::TEXT[]),
('Vote', 'vote_us.mp3', 'verb', 'B1', 'to show formally by marking a paper, raising your hand, using a voting machine, etc. which person you want to win an election, or which plan or idea you support', '', 'How did you vote at the last election?', '', ARRAY[]::TEXT[]),
('Voting', 'voting_us.mp3', 'noun', 'B1', 'the action of choosing somebody/something in an election or at a meeting', '', 'He was eliminated in the first round of voting.', '', ARRAY[]::TEXT[]),
('Vow', 'vow_us.mp3', 'verb', 'B1', 'to make a formal and serious promise to do something or a formal statement that is true', '', 'vow to do something, She vowed never to speak to him again.', '', ARRAY[]::TEXT[]),
('Vulnerability', 'vulnerability_us.mp3', 'noun', 'B1', 'the fact of being weak and easily hurt physically or emotionally', '', 'the vulnerability of newborn babies to disease', '', ARRAY[]::TEXT[]),
('Vulnerable', 'vulnerable_us.mp3', 'adjective', 'B1', 'weak and easily hurt physically or emotionally', '', 'These offices are highly vulnerable to terrorist attack.', '', ARRAY[]::TEXT[]),
('Wage', 'wage_us.mp3', 'noun', 'B1', 'a regular amount of money that you earn, usually every week or every month, for work or services', '', 'wage/wages of something, wages of £300 a week', '', ARRAY[]::TEXT[]),
('Wait', 'wait_us.mp3', 'noun', 'B1', 'an act of waiting; an amount of time waited', '', 'The wait seemed interminable.', '', ARRAY[]::TEXT[]),
('Wait', 'wait_us.mp3', 'verb', 'B1', 'to stay where you are or delay doing something until somebody/something comes or something happens', '', 'She rang the bell and waited.', '', ARRAY[]::TEXT[]),
('Waiter', 'waiter_us.mp3', 'noun', 'B1', 'a man whose job is to serve customers at their tables in a restaurant, etc.', '', 'I''ll ask the waiter for the bill.', '', ARRAY[]::TEXT[]),
('Wake', 'wake_us.mp3', 'verb', 'B1', 'to stop sleeping; to make somebody stop sleeping', '', 'I always wake early in the summer.', '', ARRAY[]::TEXT[]),
('Walk', 'walk_us.mp3', 'noun', 'B1', 'a journey on foot, usually for pleasure or exercise', '', 'Let''s go for a walk.', '', ARRAY[]::TEXT[]),
('Walk', 'walk_us.mp3', 'verb', 'B1', 'to move or go somewhere by putting one foot in front of the other on the ground, but without running', '', 'The baby is just learning to walk.', '', ARRAY[]::TEXT[]),
('Wall', 'wall_us.mp3', 'noun', 'B1', 'a long, solid structure that rises straight up from the ground, made of stone, brick or concrete, that surrounds, divides or protects an area of land', '', 'to build a wall', '', ARRAY[]::TEXT[]),
('Wander', 'wander_us.mp3', 'verb', 'B1', 'to walk slowly around or to a place, often without any particular sense of purpose or direction', '', '+ adv./prep., She wandered aimlessly around the streets.', '', ARRAY[]::TEXT[]),
('Want', 'want_us.mp3', 'verb', 'B1', 'to have a desire or a wish for something/somebody', '', 'want somebody/something, Do you want some more tea?', '', ARRAY[]::TEXT[]),
('War', 'war_us.mp3', 'noun', 'B1', 'a situation in which two or more countries or groups of people fight against each other over a period of time', '', 'the Second World War', '', ARRAY[]::TEXT[]),
('Ward', 'ward_us.mp3', 'noun', 'B1', 'a separate room or area in a hospital for people with the same type of medical condition', '', 'a maternity/surgical/psychiatric/children’s ward', '', ARRAY[]::TEXT[]),
('Warehouse', 'warehouse_us.mp3', 'noun', 'B1', 'a building where large quantities of goods are stored, especially before they are sent to shops to be sold', '', 'Police are investigating a fire at a furniture warehouse.', '', ARRAY[]::TEXT[]),
('Warfare', 'warfare_us.mp3', 'noun', 'B1', 'the activity of fighting a war, especially using particular weapons or methods', '', 'air/naval/guerrilla warfare', '', ARRAY[]::TEXT[]),
('Warm', 'warm_us.mp3', 'adjective', 'B1', 'at a fairly high temperature in a way that is pleasant, rather than being hot or cold', '', 'warm weather/temperatures/air', '', ARRAY[]::TEXT[]),
('Warm', 'warm_us.mp3', 'verb', 'B1', 'to make something/somebody warm or warmer; to become warm or warmer', '', 'warm something/somebody/yourself, Come in and warm yourself by the fire.', '', ARRAY[]::TEXT[]),
('Warming', 'warming_us.mp3', 'noun', 'B1', 'the process of making something, or of becoming, warm or warmer', '', 'atmospheric warming', '', ARRAY[]::TEXT[]),
('Warn', 'warn_us.mp3', 'verb', 'B1', 'to tell somebody about something, especially something dangerous or unpleasant that is likely to happen, so that they can avoid it', '', 'warn somebody, I tried to warn him, but he wouldn''t listen.', '', ARRAY[]::TEXT[]),
('Warning', 'warning_us.mp3', 'noun', 'B1', 'a statement, an event, etc. telling somebody that something bad or unpleasant may happen in the future so that they can try to avoid it', '', 'I had absolutely no warning.', '', ARRAY[]::TEXT[]),
('Warrant', 'warrant_us.mp3', 'noun', 'B1', 'a legal document that is signed by a judge and gives the police authority to do something', '', 'an arrest warrant', '', ARRAY[]::TEXT[]),
('Warrant', 'warrant_us.mp3', 'verb', 'B1', 'to make something necessary or appropriate in a particular situation', '', 'warrant something, Further investigation is clearly warranted.', '', ARRAY[]::TEXT[]),
('Warrior', 'warrior_us.mp3', 'noun', 'B1', '(especially in the past) a person who fights in a battle or war', '', 'a warrior nation (= whose people are skilled in fighting)', '', ARRAY[]::TEXT[]),
('Wash', 'wash_us.mp3', 'noun', 'B1', 'an act of cleaning somebody/something using water and usually soap', '', 'These towels are ready for a wash.', '', ARRAY[]::TEXT[]),
('Wash', 'wash_us.mp3', 'verb', 'B1', 'to make something/somebody clean using water and usually soap', '', 'wash something/somebody, These jeans need washing.', '', ARRAY[]::TEXT[]),
('Washing', 'washing_us.mp3', 'noun', 'B1', 'the act of cleaning something using water and usually soap', '', 'a gentle shampoo for frequent washing', '', ARRAY[]::TEXT[]),
('Waste', 'waste_us.mp3', 'adjective', 'B1', 'no longer needed for a particular process and therefore thrown away', '', 'the disposal of waste material', '', ARRAY[]::TEXT[]),
('Waste', 'waste_us.mp3', 'noun', 'B1', 'the act of using something in a careless or unnecessary way, causing it to be lost or destroyed', '', 'I hate unnecessary waste.', '', ARRAY[]::TEXT[]),
('Waste', 'waste_us.mp3', 'verb', 'B1', 'to use more of something than is necessary or useful', '', 'waste something, Stop wasting time and just get on with it!', '', ARRAY[]::TEXT[]),
('Watch', 'watch_us.mp3', 'noun', 'B1', 'a type of small clock that you wear on your wrist, or (in the past) carried in your pocket', '', 'She kept looking anxiously at her watch.', '', ARRAY[]::TEXT[]),
('Watch', 'watch_us.mp3', 'verb', 'B1', 'to look at somebody/something for a time, paying attention to what happens', '', 'watch somebody/something, I was in the living room, watching TV.', '', ARRAY[]::TEXT[]),
('Water', 'water_us.mp3', 'noun', 'B1', 'a liquid without colour, smell or taste that falls as rain, is in lakes, rivers and seas, and is used for drinking, washing, etc.', '', 'a glass of water', '', ARRAY[]::TEXT[]),
('Water', 'water_us.mp3', 'verb', 'B1', 'to pour water on plants, etc.', '', 'to water the plants/garden', '', ARRAY[]::TEXT[]),
('Wave', 'wave_us.mp3', 'noun', 'B1', 'a raised line of water that moves across the surface of the sea, ocean, etc.', '', 'Huge waves were breaking on the shore.', '', ARRAY[]::TEXT[]),
('Wave', 'wave_us.mp3', 'verb', 'B1', 'to move your hand or arm from side to side in the air in order to attract attention, say hello, etc.', '', 'The people on the bus waved and we waved back.', '', ARRAY[]::TEXT[]),
('Way', 'way_us.mp3', 'adverb', 'B1', 'very far; by a large amount', '', 'She finished the race way ahead of the other runners.', '', ARRAY[]::TEXT[]),
('Way', 'way_us.mp3', 'noun', 'B1', 'a method, style or manner of doing something', '', 'I prefer to do things the easy way.', '', ARRAY[]::TEXT[]),
('We', 'we_us.mp3', 'pronoun', 'B1', 'I and another person or other people; I and you', '', 'We''ve moved to Atlanta.', '', ARRAY[]::TEXT[]),
('Weak', 'weak_us.mp3', 'adjective', 'B1', 'not physically strong', '', 'She is still weak after her illness.', '', ARRAY[]::TEXT[]),
('Weaken', 'weaken_us.mp3', 'verb', 'B1', 'to make somebody/something less strong or powerful; to become less strong or powerful', '', 'The team has been weakened by injury.', '', ARRAY[]::TEXT[]),
('Weakness', 'weakness_us.mp3', 'noun', 'B1', 'lack of physical strength', '', 'The disease causes progressive muscle weakness.', '', ARRAY[]::TEXT[]),
('Wealth', 'wealth_us.mp3', 'noun', 'B1', 'a large amount of money, property, etc. that a person or country owns', '', 'the desire to gain wealth and power', '', ARRAY[]::TEXT[]),
('Wealthy', 'wealthy_us.mp3', 'adjective', 'B1', 'having a lot of money, possessions, etc.', '', 'a wealthy businessman/individual/family', '', ARRAY[]::TEXT[]),
('Weapon', 'weapon_us.mp3', 'noun', 'B1', 'an object such as a knife, gun, bomb, etc. that is used for fighting or attacking somebody', '', 'Modern nuclear weapons are much more destructive than either biological or chemical weapons.', '', ARRAY[]::TEXT[]),
('Wear', 'wear_us.mp3', 'verb', 'B1', 'to have something on your body as a piece of clothing, a decoration, etc.', '', 'He was wearing a new suit.', '', ARRAY[]::TEXT[]),
('Weather', 'weather_us.mp3', 'noun', 'B1', 'the condition of the atmosphere at a particular place and time, such as the temperature, and if there is wind, rain, sun, etc.', '', 'cold/hot/warm/wet/dry weather', '', ARRAY[]::TEXT[]),
('Weave', 'weave_us.mp3', 'verb', 'B1', 'to make cloth, a carpet, a basket, etc. by crossing threads or narrow pieces of material across, over and under each other by hand or on a machine called a loom', '', 'weave A from B, The baskets are woven from strips of willow.', '', ARRAY[]::TEXT[]),
('Web', 'web_us.mp3', 'noun', 'B1', 'a system for finding information on the internet, in which documents are connected to other documents', '', 'to surf/browse/search the web', '', ARRAY[]::TEXT[]),
('Website', 'website_us.mp3', 'noun', 'B1', 'a set of pages on the internet, where a company or an organization, or an individual person, puts information', '', 'For current prices please visit our website.', '', ARRAY[]::TEXT[]),
('Wedding', 'wedding_us.mp3', 'noun', 'B1', 'a marriage ceremony, and the meal or party that usually follows it', '', 'I dreamed of having a big wedding, with all my family and friends.', '', ARRAY[]::TEXT[]),
('Wednesday', 'Wednesday_us.mp3', 'noun', 'B1', 'the day of the week after Tuesday and before Thursday', '', 'It''s Wednesday today, isn''t it?', '', ARRAY[]::TEXT[]),
('Weed', 'weed_us.mp3', 'noun', 'B1', 'a wild plant growing where it is not wanted, especially among crops or garden plants', '', 'The yard was overgrown with weeds.', '', ARRAY[]::TEXT[]),
('Week', 'week_us.mp3', 'noun', 'B1', 'a period of seven days, either from Monday to Sunday or from Sunday to Saturday', '', 'last/this/next week', '', ARRAY[]::TEXT[]),
('Weekend', 'weekend_us.mp3', 'noun', 'B1', 'Saturday and Sunday', '', 'this/next/last weekend', '', ARRAY[]::TEXT[]),
('Weekly', 'weekly_us.mp3', 'adjective', 'B1', 'happening, done or published once a week or every week', '', 'weekly meetings', '', ARRAY[]::TEXT[]),
('Weigh', 'weigh_us.mp3', 'verb', 'B1', 'to have a particular weight', '', 'How much do you weigh (= how heavy are you)?', '', ARRAY[]::TEXT[]),
('Weight', 'weight_us.mp3', 'noun', 'B1', 'how heavy somebody/something is, which can be measured in, for example, kilograms or pounds', '', 'in weight, It is about 76 kilos in weight.', '', ARRAY[]::TEXT[]),
('Weird', 'weird_us.mp3', 'adjective', 'B1', 'very strange or unusual and difficult to explain', '', 'I had a really weird dream last night.', '', ARRAY[]::TEXT[]),
('Welcome', 'welcome_us.mp3', 'adjective', 'B1', 'accepted or wanted somewhere', '', 'I''ll go, then. I know when I''m not welcome.', '', ARRAY[]::TEXT[]),
('Welcome', 'welcome_us.mp3', 'exclamation', 'B1', 'used as a greeting to tell somebody that you are pleased that they are there', '', 'Welcome home!', '', ARRAY[]::TEXT[]),
('Welcome', 'welcome_us.mp3', 'noun', 'B1', 'something that you do or say to somebody when they arrive, especially something that makes them feel you are happy to see them', '', 'to get/receive a welcome', '', ARRAY[]::TEXT[]),
('Welcome', 'welcome_us.mp3', 'verb', 'B1', 'to say hello to somebody in a friendly way when they arrive somewhere', '', 'welcome somebody, They were at the door to welcome us.', '', ARRAY[]::TEXT[]),
('Welfare', 'welfare_us.mp3', 'noun', 'B1', 'the general health, happiness and safety of a person, an animal or a group', '', 'We are concerned about the child''s welfare.', '', ARRAY[]::TEXT[]),
('Well', 'well_us.mp3', 'adjective', 'B1', 'in good health', '', 'I don''t feel very well.', '', ARRAY[]::TEXT[]),
('Well', 'well_us.mp3', 'adverb', 'B1', 'in a good, right or acceptable way', '', 'They played well in the tournament.', '', ARRAY[]::TEXT[]),
('Well', 'well_us.mp3', 'exclamation', 'B1', 'used to express surprise, anger or relief', '', 'Well, well—I would never have guessed it!', '', ARRAY[]::TEXT[]),
('Well', 'well_us.mp3', 'noun', 'B1', 'a deep hole in the ground from which people obtain water. The sides of wells are usually covered with brick or stone and there is usually a cover or a small wall at the top of the well.', '', 'to dig/sink a well', '', ARRAY[]::TEXT[]),
('Well-being', 'well-being_us.mp3', 'noun', 'B1', 'general health and happiness', '', 'emotional/physical/psychological well-being', '', ARRAY[]::TEXT[]),
('West', 'west_us.mp3', 'adjective', 'B1', 'in or towards the west', '', 'West Africa', '', ARRAY[]::TEXT[]),
('West', 'west_us.mp3', 'adverb', 'B1', 'towards the west', '', 'This room faces west.', '', ARRAY[]::TEXT[]),
('West', 'west_us.mp3', 'noun', 'B1', 'the direction that you look towards to see the sun go down; one of the four main points of the compass', '', 'Which way is west?', '', ARRAY[]::TEXT[]),
('Western', 'western_us.mp3', 'adjective', 'B1', 'located in the west or facing west', '', 'western Spain', '', ARRAY[]::TEXT[]),
('Wet', 'wet_us.mp3', 'adjective', 'B1', 'covered with or containing liquid, especially water', '', 'wet clothes/hair/grass', '', ARRAY[]::TEXT[]),
('What', 'what_us.mp3', 'determiner', 'B1', 'used in questions to ask for particular information about somebody/something', '', 'What is your name?', '', ARRAY[]::TEXT[]),
('What', 'what_us.mp3', 'pronoun', 'B1', 'used in questions to ask for particular information about somebody/something', '', 'What is your name?', '', ARRAY[]::TEXT[]),
('Whatever', 'whatever_us.mp3', 'adverb', 'B1', 'not at all; not of any kind', '', 'They received no help whatever.', '', ARRAY[]::TEXT[]),
('Whatever', 'whatever_us.mp3', 'determiner', 'B1', 'any or every; anything or everything', '', 'Take whatever action is needed.', '', ARRAY[]::TEXT[]),
('Whatever', 'whatever_us.mp3', 'pronoun', 'B1', 'any or every; anything or everything', '', 'Take whatever action is needed.', '', ARRAY[]::TEXT[]),
('Whatsoever', 'whatsoever_us.mp3', 'adverb', 'B1', 'not at all; not of any kind', '', 'They received no help whatsoever.', '', ARRAY[]::TEXT[]),
('Wheat', 'wheat_us.mp3', 'noun', 'B1', 'a plant grown for its grain that is used to produce the flour for bread, cakes, pasta, etc.; the grain of this plant', '', 'wheat flour', '', ARRAY[]::TEXT[]),
('Wheel', 'wheel_us.mp3', 'noun', 'B1', 'one of the round objects under a car, bicycle, bus, etc. that turns when it moves', '', 'He braked suddenly, causing the front wheels to skid.', '', ARRAY[]::TEXT[]),
('When', 'when_us.mp3', 'adverb', 'B1', 'at what time; on what occasion', '', 'When did you last see him?', '', ARRAY[]::TEXT[]),
('When', 'when_us.mp3', 'conjunction', 'B1', 'at or during the time that', '', 'I loved history when I was at school.', '', ARRAY[]::TEXT[]),
('When', 'when_us.mp3', 'pronoun', 'B1', 'what/which time', '', 'Until when can you stay?', '', ARRAY[]::TEXT[]),
('Whenever', 'whenever_us.mp3', 'conjunction', 'B1', 'at any time that; on any occasion that', '', 'You can ask for help whenever you need it.', '', ARRAY[]::TEXT[]),
('Where', 'where_us.mp3', 'adverb', 'B1', 'in or to what place or situation', '', 'Where do you live?', '', ARRAY[]::TEXT[]),
('Where', 'where_us.mp3', 'conjunction', 'B1', '(in) the place or situation in which', '', 'This is where I live.', '', ARRAY[]::TEXT[]),
('Whereas', 'whereas_us.mp3', 'conjunction', 'B1', 'used to compare or contrast two facts', '', 'Some of the studies show positive results, whereas others do not.', '', ARRAY[]::TEXT[]),
('Whereby', 'whereby_us.mp3', 'adverb', 'B1', 'by which; because of which', '', 'They have introduced a new system whereby all employees must undergo regular training.', '', ARRAY[]::TEXT[]),
('Wherever', 'wherever_us.mp3', 'conjunction', 'B1', 'in any place', '', 'Sit wherever you like.', '', ARRAY[]::TEXT[]),
('Whether', 'whether_us.mp3', 'conjunction', 'B1', 'used to express a doubt or choice between two possibilities', '', 'He seemed undecided whether to go or stay.', '', ARRAY[]::TEXT[]),
('Which', 'which_us.mp3', 'determiner', 'B1', 'used in questions to ask somebody to be exact about one or more people or things from a limited number', '', 'Which is better exercise—swimming or tennis?', '', ARRAY[]::TEXT[]),
('Which', 'which_us.mp3', 'pronoun', 'B1', 'used in questions to ask somebody to be exact about one or more people or things from a limited number', '', 'Which is better exercise—swimming or tennis?', '', ARRAY[]::TEXT[]),
('While', 'while_us.mp3', 'conjunction', 'B1', 'during the time that something is happening; at the same time as something else is happening', '', 'We must have been burgled while we were asleep.', '', ARRAY[]::TEXT[]),
('While', 'while_us.mp3', 'noun', 'B1', 'a period of time', '', 'for a while, I only stayed for a short while.', '', ARRAY[]::TEXT[]),
('Whilst', 'whilst_us.mp3', 'conjunction', 'B1', 'during the time that something is happening; at the same time as something else is happening', '', 'In the UK it is illegal to drive whilst holding a mobile phone.', '', ARRAY[]::TEXT[]),
('Whip', 'whip_us.mp3', 'verb', 'B1', 'to hit a person or an animal hard with a whip, as a punishment or to make them go faster or work harder', '', 'He was taken back to the jail and soundly whipped.', '', ARRAY[]::TEXT[]),
('Whisper', 'whisper_us.mp3', 'noun', 'B1', 'a low, quiet voice or the sound it makes', '', 'in a whisper, ‘I love you,’ he said in a whisper.', '', ARRAY[]::TEXT[]),
('Whisper', 'whisper_us.mp3', 'verb', 'B1', 'to speak very quietly to somebody so that other people cannot hear what you are saying', '', 'Don''t you know it''s rude to whisper?', '', ARRAY[]::TEXT[]),
('White', 'white_us.mp3', 'adjective', 'B1', 'having the colour of fresh snow or of milk', '', 'a crisp white shirt', '', ARRAY[]::TEXT[]),
('White', 'white_us.mp3', 'noun', 'B1', 'the colour of fresh snow or of milk', '', 'various shades of white', '', ARRAY[]::TEXT[]),
('Who', 'who_us.mp3', 'pronoun', 'B1', 'used in questions to ask about the name, identity or function of one or more people', '', 'Who is that woman?', '', ARRAY[]::TEXT[]),
('Whoever', 'whoever_us.mp3', 'pronoun', 'B1', 'the person or people who; any person who', '', 'Whoever says that is a liar.', '', ARRAY[]::TEXT[]),
('Whole', 'whole_us.mp3', 'adjective', 'B1', 'full; complete', '', 'Let''s forget the whole thing.', '', ARRAY[]::TEXT[]),
('Whole', 'whole_us.mp3', 'noun', 'B1', 'all that there is of something', '', 'The scheme would cover the whole of the UK.', '', ARRAY[]::TEXT[]),
('Wholly', 'wholly_us.mp3', 'adverb', 'B1', 'completely', '', 'wholly inappropriate behaviour', '', ARRAY[]::TEXT[]),
('Whom', 'whom_us.mp3', 'pronoun', 'B1', 'used instead of ‘who’ as the object of a verb or preposition', '', 'Whom did they invite?', '', ARRAY[]::TEXT[]),
('Whose', 'whose_us.mp3', 'determiner', 'B1', 'used in questions to ask who something belongs to', '', 'Whose house is that?', '', ARRAY[]::TEXT[]),
('Whose', 'whose_us.mp3', 'pronoun', 'B1', 'used in questions to ask who something belongs to', '', 'Whose house is that?', '', ARRAY[]::TEXT[]),
('Why', 'why_us.mp3', 'adverb', 'B1', 'used in questions to ask the reason for or purpose of something', '', 'Why were you late?', '', ARRAY[]::TEXT[]),
('Wide', 'wide_us.mp3', 'adjective', 'B1', 'measuring a large distance from one side to the other', '', 'It''s a wide, fast-flowing river.', '', ARRAY[]::TEXT[]),
('Widely', 'widely_us.mp3', 'adverb', 'B1', 'by a lot of people; in or to many places', '', 'The term is widely used in everyday speech.', '', ARRAY[]::TEXT[]),
('Widen', 'widen_us.mp3', 'verb', 'B1', 'to become wider; to make something wider', '', 'Her eyes widened in surprise.', '', ARRAY[]::TEXT[]),
('Widespread', 'widespread_us.mp3', 'adjective', 'B1', 'existing or happening over a large area or among many people', '', 'The storm caused widespread damage.', '', ARRAY[]::TEXT[]),
('Widow', 'widow_us.mp3', 'noun', 'B1', 'a woman whose husband or wife has died and who has not married again', '', 'She gets a widow’s pension.', '', ARRAY[]::TEXT[]),
('Width', 'width_us.mp3', 'noun', 'B1', 'the measurement from one side of something to the other; how wide something is', '', 'The terrace runs the full width of the house.', '', ARRAY[]::TEXT[]),
('Wife', 'wife_us.mp3', 'noun', 'B1', 'the woman that somebody is married to; a married woman', '', 'I met my wife at university.', '', ARRAY[]::TEXT[]),
('Wild', 'wild_us.mp3', 'adjective', 'B1', 'living or growing in natural conditions; not kept in a house or on a farm', '', 'wild animals/birds/flowers', '', ARRAY[]::TEXT[]),
('Wildlife', 'wildlife_us.mp3', 'noun', 'B1', 'animals, birds, insects, etc. that are wild and live in a natural environment', '', 'policies designed to protect wildlife', '', ARRAY[]::TEXT[]),
('Will', 'will_us.mp3', 'noun', 'B1', 'the ability to control your thoughts and actions in order to achieve what you want to do; a strong and determined desire to do something that you want to do', '', 'to have a strong will', '', ARRAY[]::TEXT[]),
('Will', 'will_us.mp3', 'modal verb', 'B1', 'used for talking about or predicting the future', '', 'You''ll be in time if you hurry.', '', ARRAY[]::TEXT[]),
('Willing', 'willing_us.mp3', 'adjective', 'B1', 'not objecting to doing something; having no reason for not doing something', '', 'Many consumers are willing to pay more for organic food', '', ARRAY[]::TEXT[]),
('Willingness', 'willingness_us.mp3', 'noun', 'B1', 'the quality of being happy and ready to do something', '', 'Success in studying depends on a willingness to learn.', '', ARRAY[]::TEXT[]),
('Win', 'win_us.mp3', 'noun', 'B1', 'a victory in a game, contest, etc.', '', 'two wins and three defeats', '', ARRAY[]::TEXT[]),
('Win', 'win_us.mp3', 'verb', 'B1', 'to be the most successful in a competition, race, battle, etc.', '', 'Which team won?', '', ARRAY[]::TEXT[]),
('Wind', 'wind_us.mp3', 'verb', 'B1', 'to have many bends and twists', '', 'wind + adv./prep., The path wound down to the beach.', '', ARRAY[]::TEXT[]),
('Window', 'window_us.mp3', 'noun', 'B1', 'an opening in the wall or roof of a building, car, etc., usually covered with glass, that allows light and air to come in and people to see out; the glass in a window', '', 'out of the window, She looked out of the window.', '', ARRAY[]::TEXT[]),
('Wine', 'wine_us.mp3', 'noun', 'B1', 'an alcoholic drink made from the juice of grapes that has been left to ferment. There are many different kinds of wine.', '', 'sparkling wine', '', ARRAY[]::TEXT[]),
('Wing', 'wing_us.mp3', 'noun', 'B1', 'one of the parts of the body of a bird, insect or bat that it uses for flying', '', 'The swan flapped its wings noisily.', '', ARRAY[]::TEXT[]),
('Winner', 'winner_us.mp3', 'noun', 'B1', 'a person, a team, an animal, etc. that wins something', '', 'The lucky winner gets an all-expenses-paid trip to Sydney.', '', ARRAY[]::TEXT[]),
('Winter', 'winter_us.mp3', 'noun', 'B1', 'the coldest season of the year, between autumn and spring', '', 'a cold/mild/harsh winter', '', ARRAY[]::TEXT[]),
('Wipe', 'wipe_us.mp3', 'verb', 'B1', 'to rub something against a surface, in order to remove dirt or liquid from it; to rub a surface with a cloth, etc. in order to clean it', '', 'wipe something (on something), Please wipe your feet on the mat.', '', ARRAY[]::TEXT[]),
('Wire', 'wire_us.mp3', 'noun', 'B1', 'metal in the form of thin thread; a piece of this', '', 'a coil of copper wire', '', ARRAY[]::TEXT[]),
('Wisdom', 'wisdom_us.mp3', 'noun', 'B1', 'the ability to make sensible decisions and give good advice because of the experience and knowledge that you have', '', 'She was known to be a woman of great wisdom.', '', ARRAY[]::TEXT[]),
('Wise', 'wise_us.mp3', 'adjective', 'B1', 'able to make sensible decisions and give good advice because of the experience and knowledge that you have', '', 'a wise man', '', ARRAY[]::TEXT[]),
('Wish', 'wish_us.mp3', 'noun', 'B1', 'used especially in a letter, email or card to say that you hope that somebody will be happy, well or successful', '', 'Give my good wishes to the family.', '', ARRAY[]::TEXT[]),
('Wish', 'wish_us.mp3', 'verb', 'B1', 'to want something to happen or to be true even though it is unlikely or impossible', '', 'wish (that)…, I wish I were taller.', '', ARRAY[]::TEXT[]),
('Wit', 'wit_us.mp3', 'noun', 'B1', 'the ability to say or write things that are both clever and humorous', '', 'to have a quick/sharp/dry/ready wit', '', ARRAY[]::TEXT[]),
('With', 'with_us.mp3', 'preposition', 'B1', 'in the company or presence of somebody/something', '', 'She lives with her parents.', '', ARRAY[]::TEXT[]),
('Withdraw', 'withdraw_us.mp3', 'verb', 'B1', 'to take money out of a bank account', '', 'withdraw something, With this account, you can withdraw up to £300 a day.', '', ARRAY[]::TEXT[]),
('Withdrawal', 'withdrawal_us.mp3', 'noun', 'B1', 'the act of taking an amount of money out of your bank account', '', 'You can make withdrawals of up to $250 a day.', '', ARRAY[]::TEXT[]),
('Within', 'within_us.mp3', 'preposition', 'B1', 'before a particular period of time has passed; during a particular period of time', '', 'You should receive a reply within seven days.', '', ARRAY[]::TEXT[]),
('Without', 'without_us.mp3', 'preposition', 'B1', 'not having, experiencing or showing something', '', 'They had gone two days without food.', '', ARRAY[]::TEXT[]),
('Witness', 'witness_us.mp3', 'noun', 'B1', 'a person who sees something happen and is able to describe it to other people', '', 'He failed to interview a key witness.', '', ARRAY[]::TEXT[]),
('Witness', 'witness_us.mp3', 'verb', 'B1', 'to see something happen (typically a crime or an accident)', '', 'to witness an accident/a murder/an attack', '', ARRAY[]::TEXT[]),
('Woman', 'woman_us.mp3', 'noun', 'B1', 'an adult female human', '', 'a 54-year-old woman', '', ARRAY[]::TEXT[]),
('Wonder', 'wonder_us.mp3', 'noun', 'B1', 'a feeling of surprise and pleasure that you have when you see or experience something beautiful, unusual or unexpected', '', 'He retained a childlike sense of wonder.', '', ARRAY[]::TEXT[]),
('Wonder', 'wonder_us.mp3', 'verb', 'B1', 'to think about something and try to decide what is true, what will happen, what you should do, etc.', '', '‘Why do you want to know?’ ‘No particular reason. I was just wondering.’', '', ARRAY[]::TEXT[]),
('Wonderful', 'wonderful_us.mp3', 'adjective', 'B1', 'very good, pleasant or a lot of fun', '', 'This is a wonderful opportunity to invest in new markets.', '', ARRAY[]::TEXT[]),
('Wood', 'wood_us.mp3', 'noun', 'B1', 'the hard material that the trunk and branches of a tree are made of; this material when it is used to build or make things with, or as a fuel', '', 'He chopped some wood for the fire.', '', ARRAY[]::TEXT[]),
('Wooden', 'wooden_us.mp3', 'adjective', 'B1', 'made of wood', '', 'a wooden box/door/floor', '', ARRAY[]::TEXT[]),
('Wool', 'wool_us.mp3', 'noun', 'B1', 'the soft hair that covers the body of sheep and some other animals', '', 'Sheep were kept for their wool and meat.', '', ARRAY[]::TEXT[]),
('Word', 'word_us.mp3', 'noun', 'B1', 'a single unit of language that means something and can be spoken or written', '', 'Do not write more than 200 words.', '', ARRAY[]::TEXT[]),
('Work', 'work_us.mp3', 'noun', 'B1', 'the job that a person does especially in order to earn money', '', 'He started work as a security guard.', '', ARRAY[]::TEXT[]),
('Work', 'work_us.mp3', 'verb', 'B1', 'to do something that involves physical or mental effort, especially as part of a job', '', 'I can''t work if I''m cold.', '', ARRAY[]::TEXT[]),
('Worker', 'worker_us.mp3', 'noun', 'B1', 'a person who works, especially one who does a particular kind of work', '', 'farm/factory/office workers', '', ARRAY[]::TEXT[]),
('Workforce', 'workforce_us.mp3', 'noun', 'B1', 'all the people who work for a particular company, organization, etc.', '', 'The factory has a 1 000-strong workforce.', '', ARRAY[]::TEXT[]),
('Working', 'working_us.mp3', 'adjective', 'B1', 'having a job for which you are paid', '', 'the working population', '', ARRAY[]::TEXT[]),
('Workout', 'workout_us.mp3', 'noun', 'B1', 'a period of physical exercise that you do to keep fit', '', 'She does a 20-minute workout every morning.', '', ARRAY[]::TEXT[]),
('Workplace', 'workplace_us.mp3', 'noun', 'B1', 'the office, factory, etc. where people work', '', 'the introduction of new technology into the workplace', '', ARRAY[]::TEXT[]),
('Workshop', 'workshop_us.mp3', 'noun', 'B1', 'a period of discussion and practical work on a particular subject, in which a group of people share their knowledge and experience', '', 'There will be the opportunity for practical theatre work in drama workshops.', '', ARRAY[]::TEXT[]),
('World', 'world_us.mp3', 'noun', 'B1', 'the earth, with all its countries, peoples and natural features', '', 'a map of the world', '', ARRAY[]::TEXT[]),
('Worldwide', 'worldwide_us.mp3', 'adjective', 'B1', 'affecting all parts of the world', '', 'an increase in worldwide sales', '', ARRAY[]::TEXT[]),
('Worldwide', 'worldwide_us.mp3', 'adverb', 'B1', 'affecting all parts of the world', '', 'an increase in worldwide sales', '', ARRAY[]::TEXT[]),
('Worm', 'worm_us.mp3', 'noun', 'B1', 'a long, thin creature with a soft body and no bones or legs', '', 'birds looking for worms', '', ARRAY[]::TEXT[]),
('Worried', 'worried_us.mp3', 'adjective', 'B1', 'thinking about unpleasant things that have happened or that might happen and therefore feeling unhappy and afraid', '', 'Don''t look so worried!', '', ARRAY[]::TEXT[]),
('Worry', 'worry_us.mp3', 'noun', 'B1', 'the state of worrying about something', '', 'The threat of losing their jobs is a constant source of worry to them.', '', ARRAY[]::TEXT[]),
('Worry', 'worry_us.mp3', 'verb', 'B1', 'to keep thinking about unpleasant things that might happen or about problems that you have', '', 'Don''t worry. We have plenty of time.', '', ARRAY[]::TEXT[]),
('Worse', 'worse_us.mp3', 'adjective', 'B1', 'of poorer quality or lower standard; more unpleasant', '', 'The rooms were awful and the food was worse.', '', ARRAY[]::TEXT[]),
('Worse', 'worse_us.mp3', 'adverb', 'B1', 'less well', '', 'Working-class children fared rather worse.', '', ARRAY[]::TEXT[]),
('Worse', 'worse_us.mp3', 'noun', 'B1', 'more problems or bad news', '', 'I''m afraid there is worse to come.', '', ARRAY[]::TEXT[]),
('Worship', 'worship_us.mp3', 'noun', 'B1', 'the practice of showing respect for God or a god, by saying prayers, singing with others, etc.; a ceremony for this', '', 'an act/a place of worship', '', ARRAY[]::TEXT[]),
('Worship', 'worship_us.mp3', 'verb', 'B1', 'to show respect for God or a god, especially by saying prayers, singing, etc. with other people in a religious building', '', 'The Mayans built jungle pyramids to worship their gods.', '', ARRAY[]::TEXT[]),
('Worst', 'worst_us.mp3', 'adjective', 'B1', 'of the poorest quality or lowest standard; worse than any other person or thing of a similar kind', '', 'It was by far the worst speech he had ever made.', '', ARRAY[]::TEXT[]),
('Worst', 'worst_us.mp3', 'adverb', 'B1', 'most badly or seriously', '', 'He was voted the worst dressed celebrity.', '', ARRAY[]::TEXT[]),
('Worst', 'worst_us.mp3', 'noun', 'B1', 'the most serious or unpleasant thing that could happen; the part, situation, possibility, etc. that is worse than any other', '', 'When they did not hear from her, they feared the worst.', '', ARRAY[]::TEXT[]),
('Worth', 'worth_us.mp3', 'adjective', 'B1', 'having a value in money, etc.', '', 'Our house is worth about £100 000.', '', ARRAY[]::TEXT[]),
('Worth', 'worth_us.mp3', 'noun', 'B1', 'an amount of something that has the value mentioned', '', 'The winner will receive fifty pounds'' worth of books.', '', ARRAY[]::TEXT[]),
('Worthwhile', 'worthwhile_us.mp3', 'adjective', 'B1', 'important, pleasant, interesting, etc.; worth spending time, money or effort on', '', 'It was in aid of a worthwhile cause (= a charity, etc.).', '', ARRAY[]::TEXT[]),
('Worthy', 'worthy_us.mp3', 'adjective', 'B1', 'having the qualities that deserve somebody/something', '', 'Very few of his ideas are worthy of further attention.', '', ARRAY[]::TEXT[]),
('Would', 'would_us.mp3', 'modal verb', 'B1', 'used in polite offers or invitations', '', 'Would you like a sandwich?', '', ARRAY[]::TEXT[]),
('Wound', 'wound_us.mp3', 'noun', 'B1', 'an injury to part of the body, especially one in which a hole is made in the skin using a weapon', '', 'a gunshot/stab wound', '', ARRAY[]::TEXT[]),
('Wound', 'wound_us.mp3', 'verb', 'B1', 'to injure part of the body, especially by making a hole in the skin using a weapon', '', 'He had been wounded in the arm.', '', ARRAY[]::TEXT[]),
('Wow', 'wow_us.mp3', 'exclamation', 'B1', 'used to show that you are very surprised or impressed by somebody/something', '', 'Wow! You look terrific!', '', ARRAY[]::TEXT[]),
('Wrap', 'wrap_us.mp3', 'verb', 'B1', 'to cover something completely in paper or other material, for example when you are giving it as a present', '', 'wrap something up, He spent the evening wrapping up the Christmas presents.', '', ARRAY[]::TEXT[]),
('Wrist', 'wrist_us.mp3', 'noun', 'B1', 'the joint between the hand and the arm', '', 'She''s broken her wrist.', '', ARRAY[]::TEXT[]),
('Write', 'write_us.mp3', 'verb', 'B1', 'to make letters or numbers on a surface, especially using a pen or a pencil', '', 'In some countries children don''t start learning to read and write until they are six.', '', ARRAY[]::TEXT[]),
('Writer', 'writer_us.mp3', 'noun', 'B1', 'a person whose job is writing books, stories, articles, etc.', '', 'Who''s your favourite writer?', '', ARRAY[]::TEXT[]),
('Writing', 'writing_us.mp3', 'noun', 'B1', 'the activity of writing, in contrast to reading, speaking, etc.', '', 'Our son’s having problems with his reading and writing (= at school)', '', ARRAY[]::TEXT[]),
('Written', 'written_us.mp3', 'adjective', 'B1', 'expressed in writing rather than in speech', '', 'Having a written record of what I''ve done is very valuable.', '', ARRAY[]::TEXT[]),
('Wrong', 'wrong_us.mp3', 'adjective', 'B1', 'not right or correct', '', 'I got all the answers wrong.', '', ARRAY[]::TEXT[]),
('Wrong', 'wrong_us.mp3', 'adverb', 'B1', 'in a way that produces a result that is not correct or that you do not want', '', 'My name is spelt wrong.', '', ARRAY[]::TEXT[]),
('Wrong', 'wrong_us.mp3', 'noun', 'B1', 'behaviour that is not honest or morally acceptable', '', 'Children must be taught the difference between right and wrong.', '', ARRAY[]::TEXT[]),
('Yard', 'yard_us.mp3', 'noun', 'B1', 'a piece of land next to or around your house where you can grow flowers, fruit, vegetables, etc., usually with a lawn (= an area of grass)', '', 'They have a gorgeous old oak tree in their front yard.', '', ARRAY[]::TEXT[]),
('Year', 'year_us.mp3', 'noun', 'B1', 'the period from 1 January to 31 December, that is 365 or 366 days, divided into 12 months', '', 'Elections take place every year.', '', ARRAY[]::TEXT[]),
('Yell', 'yell_us.mp3', 'verb', 'B1', 'to shout loudly, for example because you are angry, excited, frightened or in pain', '', 'yell (at somebody/something), He yelled at the other driver.', '', ARRAY[]::TEXT[]),
('Yellow', 'yellow_us.mp3', 'adjective', 'B1', 'having the colour of lemons or butter', '', 'pale yellow flowers', '', ARRAY[]::TEXT[]),
('Yellow', 'yellow_us.mp3', 'noun', 'B1', 'the colour of lemons or butter', '', 'She was dressed in yellow.', '', ARRAY[]::TEXT[]),
('Yes', 'yes_us.mp3', 'exclamation', 'B1', 'used to answer a question and say that something is correct or true', '', '‘Is this your car?’ ‘Yes, it is.’', '', ARRAY[]::TEXT[]),
('Yesterday', 'yesterday_us.mp3', 'adverb', 'B1', 'on the day before today', '', 'A company spokeswoman said yesterday that no final decision had been made yet.', '', ARRAY[]::TEXT[]),
('Yesterday', 'yesterday_us.mp3', 'noun', 'B1', 'the day before today', '', 'Yesterday was Sunday.', '', ARRAY[]::TEXT[]),
('Yet', 'yet_us.mp3', 'adverb', 'B1', 'used in negative sentences and questions to talk about something that has not happened but that you expect to happen', '', '(British English), I haven''t received a letter from him yet.', '', ARRAY[]::TEXT[]),
('Yet', 'yet_us.mp3', 'conjunction', 'B1', 'despite what has just been said', '', 'It''s a small car, yet it''s surprisingly spacious.', '', ARRAY[]::TEXT[]),
('Yield', 'yield_us.mp3', 'noun', 'B1', 'the total amount of crops, profits, etc. that are produced', '', 'a high crop yield', '', ARRAY[]::TEXT[]),
('Yield', 'yield_us.mp3', 'verb', 'B1', 'the total amount of crops, profits, etc. that are produced', '', 'a high crop yield', '', ARRAY[]::TEXT[]),
('You', 'you_us.mp3', 'pronoun', 'B1', 'used as the subject or object of a verb or after a preposition to refer to the person or people being spoken or written to', '', 'You said you knew the way.', '', ARRAY[]::TEXT[]),
('Young', 'young_us.mp3', 'adjective', 'B1', 'having lived or existed for only a short time; not fully developed', '', 'Young babies need to be wrapped up warmly.', '', ARRAY[]::TEXT[]),
('Young', 'young_us.mp3', 'noun', 'B1', 'young people considered as a group', '', 'It''s a movie that will appeal to the young.', '', ARRAY[]::TEXT[]),
('Youngster', 'youngster_us.mp3', 'noun', 'B1', 'a young person or a child', '', 'The camp is for youngsters aged 8 to 14.', '', ARRAY[]::TEXT[]),
('Your', 'your_us.mp3', 'determiner', 'B1', 'of or belonging to the person or people being spoken or written to', '', 'I like your dress.', '', ARRAY[]::TEXT[]),
('Yours', 'yours_us.mp3', 'pronoun', 'B1', 'of or belonging to you', '', 'Is that book yours?', '', ARRAY[]::TEXT[]),
('Yourself', 'yourself_us.mp3', 'pronoun', 'B1', 'used when the person or people being spoken to both cause and are affected by an action', '', 'Have you hurt yourself?', '', ARRAY[]::TEXT[]),
('Youth', 'youth_us.mp3', 'noun', 'B1', 'the time of life when a person is young, especially the time before a child becomes an adult', '', 'in somebody''s youth, He had been a talented musician in his youth.', '', ARRAY[]::TEXT[]),
('Zero', 'zero_us.mp3', 'number', 'B1', '0', '', 'Five, four, three, two, one, zero… We have lift-off.', '', ARRAY[]::TEXT[]),
('Zone', 'zone_us.mp3', 'noun', 'B1', 'an area or a region with a particular feature or use', '', 'a war/combat/demilitarized/exclusion zone', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
