INSERT INTO words (word, phonetic, pos, level, def_en, ex_en, synonyms) VALUES
('Aboveboard', '', 'adjective', 'C1', 'In open sight; without trick, concealment, or deception.', 'Fair and aboveboard.', ARRAY[]::TEXT[]),
('Abysmal', '/əˈbɪz.məl/', 'adjective', 'C1', 'Pertaining to, or resembling an abyss.', '', ARRAY['fathomless','immeasurable','profound','unending','fathomless']::TEXT[]),
('Acme', '/ˈæk.mi/', 'noun', 'C1', 'The top or highest point; pinnacle; culmination.', '', ARRAY[]::TEXT[]),
('Affable', '/ˈæf.ə.bəl/', 'adjective', 'C1', 'Receiving others kindly and conversing with them in a free and friendly manner; friendly, courteous, sociable.', '', ARRAY['accessible','civil','complaisant','courteous','friendly']::TEXT[]),
('Affluent', '/ˈæf.lu.ənt/', 'adjective', 'C1', 'Abundant; copious; plenteous.', 'They were affluent, but aspired to true wealth.', ARRAY[]::TEXT[]),
('Altruism', '', 'noun', 'C1', 'Regard for others, both natural and moral without regard for oneself; devotion to the interests of others; brotherly kindness.', '', ARRAY['philanthropy','philanthropy','selflessness','philanthropy','selflessness']::TEXT[]),
('Amiable', '/ˈeɪ.mi.ə.bəl/', 'adjective', 'C1', 'Friendly; kind; sweet; gracious', 'amiable ideas', ARRAY['likable']::TEXT[]),
('Amply', '/ˈæmp.li/', 'adverb', 'C1', 'In an ample manner.', '', ARRAY[]::TEXT[]),
('Analogous', '/əˈnæl.ə.ɡəs/', 'adjective', 'C1', 'Having analogy; corresponding to something else; bearing some resemblance or proportion (often followed by "to".)', '', ARRAY['comparable','correspondent','like','parallel','similar']::TEXT[]),
('Animosity', '/æn.əˈmɑs.ɪ.ti/', 'noun', 'C1', 'Violent hatred leading to active opposition; active enmity; energetic dislike.', '', ARRAY['acrimony','enmity','hatred','opposition']::TEXT[]),
('Antedate', '/ˈæntiˌdeɪt/', 'verb', 'C1', 'To occur before an event or time; to exist further back in time.', '', ARRAY['backdate','foredate','predate']::TEXT[]),
('Antiquated', '/ˈæntɪˌkweɪtɪd/', 'adjective', 'C1', 'Old-fashioned, out of date', '', ARRAY['backward','disused','outdated']::TEXT[]),
('Apex', '/ˈeɪˌpɛks/', 'noun', 'C1', 'Conical priest cap', 'the apex of the building', ARRAY['peak','summit','top','acme','culmination']::TEXT[]),
('Aphorism', '/ˈæ.fə.ɹɪzm̩/', 'verb', 'C1', 'To speak or write aphorisms.', '', ARRAY[]::TEXT[]),
('Appreciable', '/əˈpɹiːʃəbl/', 'adjective', 'C1', 'Large enough to be estimated; perceptible; considerable.', '', ARRAY[]::TEXT[]),
('Apprehension', '/æp.ɹɪˈhɛn.ʃən/', 'noun', 'C1', 'The physical act of seizing or taking hold of (something); seizing.', '', ARRAY['awareness','sense','alarm']::TEXT[]),
('Archaic', '/ɑː.ˈkeɪ.ɪk/', 'adjective', 'C1', 'Of or characterized by antiquity; old-fashioned, quaint, antiquated.', '', ARRAY['dated','obsolete','old fashioned']::TEXT[]),
('Ascendancy', '', 'noun', 'C1', 'The process or period of one''''s ascent', 'This was a key moment in Caesar''''s ascendancy.', ARRAY['superiority','superiority']::TEXT[]),
('Ascribe', '/əˈskɹaɪb/', 'verb', 'C1', 'To attribute a cause or characteristic to someone or something.', 'One may ascribe these problems to the federal government; however, at this stage it is unclear what caused them.', ARRAY['attribute','impute']::TEXT[]),
('Assail', '/əˈseɪl/', 'verb', 'C1', 'To attack with harsh words or violent force (also figuratively).', 'Muggers assailed them as they entered an alley.', ARRAY[]::TEXT[]),
('Assuage', '/əˈsweɪdʒ/', 'verb', 'C1', 'To lessen the intensity of, to mitigate or relieve (hunger, emotion, pain etc.).', '', ARRAY[]::TEXT[]),
('Augment', '/ɔːɡˈmɛnt/', 'verb', 'C1', 'To increase; to make larger or supplement.', 'The money from renting out a spare room can augment a salary.', ARRAY[]::TEXT[]),
('Autonomously', '', 'adverb', 'C1', 'In an autonomous or self-governing manner.', '', ARRAY['independently']::TEXT[]),
('Avarice', '/ˈævəɹəs/', 'noun', 'C1', 'Excessive or inordinate desire of gain; greed for wealth', '', ARRAY['avariciousness','covetousness','cupidity','covetousness','cupidity']::TEXT[]),
('Avert', '/əˈvɜːt/', 'verb', 'C1', 'To turn aside or away.', 'To avert the eyes from an object.', ARRAY['forestall']::TEXT[]),
('Avid', '/ævəd/', 'adjective', 'C1', 'Enthusiastic; keen; eager; showing great interest in something or desire to do something', 'I''''m an avid reader.', ARRAY[]::TEXT[]),
('Badger', '/ˈbædʒə/', 'verb', 'C1', 'To pester, to annoy persistently; press.', 'He kept badgering her about her bad habits.', ARRAY['flatulate']::TEXT[]),
('Balk', '/bɔːk/', 'verb', 'C1', 'To pass over or by.', 'The horse balked.', ARRAY['avoid','refuse','shirk','shun','baffle']::TEXT[]),
('Banish', '/ˈbænɪʃ/', 'verb', 'C1', '(heading) To send someone away and forbid that person from returning.', 'banish fear, qualm.', ARRAY[]::TEXT[]),
('Beatific', '/bɪəˈtɪfɪk/', 'adjective', 'C1', 'Blessed, blissful, heavenly', '', ARRAY[]::TEXT[]),
('Becoming', '/bɪˈkʊmɪŋɡ/', 'adjective', 'C1', 'Pleasingly suitable; fit; congruous; beautiful', '', ARRAY[]::TEXT[]),
('Begrudge', '/bɪˈɡɹʌdʒ/', 'verb', 'C1', 'To grudge about or over; be envious or covetous.', '', ARRAY[]::TEXT[]),
('Behoove', '/bɪˈhuːv/', 'verb', 'C1', 'To befit, to suit.', '', ARRAY[]::TEXT[]),
('Belittle', '/bɨˈlɪt.əl/', 'verb', 'C1', 'To knowingly say that something is smaller or less important than it actually is, especially as a way of showing contempt or deprecation.', 'Don''''t belittle your colleagues.', ARRAY['bagatellize','degrade','denigrate','deprecate','disparage']::TEXT[]),
('Bellicose', '/ˈbɛləkoʊs/', 'adjective', 'C1', 'Warlike in nature; aggressive; hostile.', '', ARRAY[]::TEXT[]),
('Benign', '/bɪˈnaɪn/', 'adjective', 'C1', 'Kind; gentle; mild.', 'an ozone-benign refrigerant', ARRAY['non-malignant']::TEXT[]),
('Besiege', '/bəˈsiːd͡ʒ/', 'verb', 'C1', 'To beset or surround with armed forces for the purpose of compelling to surrender, to lay siege to, beleaguer.', '', ARRAY[]::TEXT[]),
('Besmirch', '/bɪˈsmɜːtʃ/', 'verb', 'C1', 'To make dirty.', 'The newspaper was on a campaign to besmirch the actor.', ARRAY['debase','slander','smear','soil','soil']::TEXT[]),
('Bleak', '/bliːk/', 'adjective', 'C1', 'Without color; pale; pallid.', 'A bleak and bare rock.', ARRAY[]::TEXT[]),
('Boon', '/buːn/', 'noun', 'C1', 'A prayer; petition.', 'Anaesthetics are a great boon to modern surgery.', ARRAY['benefit','blessing','favor','gift']::TEXT[]),
('Boorish', '/ˈbʊəɹɪʃ/', 'adjective', 'C1', 'Behaving as a boor; rough in manners.', '', ARRAY['rude','uncultured','rude','uncultured']::TEXT[]),
('Buttress', '/ˈbʌtɹəs/', 'verb', 'C1', 'To support something physically with, or as if with, a prop or buttress.', '', ARRAY[]::TEXT[]),
('Cadaverous', '', 'adjective', 'C1', 'Corpselike; hinting of death; imitating a cadaver.', '', ARRAY[]::TEXT[]),
('Candid', '/ˈkæn.dɪd/', 'adjective', 'C1', 'Impartial and free from prejudice.', '', ARRAY['frank','open','parrhesiastic','sincere','unreserved']::TEXT[]),
('Cardinal', '/ˈkɑː.dɪ.nəl/', 'adjective', 'C1', 'Of fundamental importance; crucial, pivotal.', 'a cardinal rule', ARRAY[]::TEXT[]),
('Carping', '', 'adjective', 'C1', 'Complaining excessively.', '', ARRAY[]::TEXT[]),
('Catalyst', '/ˈkæt.əl.ɪst/', 'noun', 'C1', 'A substance that increases the rate of a chemical reaction without being consumed in the process.', 'Economic development and integration are working as a catalyst for peace.', ARRAY['stimulus','straw that stirs the drink']::TEXT[]),
('Cavalier', '/ˌkævəˈlɪəɹ/', 'adjective', 'C1', 'Not caring enough about something important.', '', ARRAY['brusque','curt','disdainful','haughty','brusque']::TEXT[]),
('Censor', '/ˈsɛnsə/', 'verb', 'C1', 'To review for, and if necessary to remove or suppress, content from books, films, correspondence, and other media which is regarded as objectionable (for example, obscene, likely to incite violence, or sensitive).', 'Occupying powers typically censor anything reeking of resistance', ARRAY['bowdlerize','expunge','expurgate','redact','bowdlerize']::TEXT[]),
('Cerebral', '/səˈɹiː.bɹəl/', 'adjective', 'C1', 'Of, or relating to the brain, cerebrum, or cerebral cortex.', '', ARRAY[]::TEXT[]),
('Chauvinist', '', 'adjective', 'C1', 'Pertaining to chauvinism.', '', ARRAY[]::TEXT[]),
('Checkered', '', 'adjective', 'C1', 'Divided into squares, or into light and dark patches.', 'That is a checkered tablecloth.', ARRAY[]::TEXT[]),
('Chivalrous', '/ˈʃɪv.əl.ɹʌs/', 'adjective', 'C1', '(of a man) Honourable, especially to women; gallant.', '', ARRAY[]::TEXT[]),
('Clemency', '/ˈklɛ.mən.si/', 'noun', 'C1', 'The gentle or kind exercise of power; leniency, mercy; compassion in judging or punishing.', '', ARRAY[]::TEXT[]),
('Coalesce', '/kəʊ.əˈlɛs/', 'verb', 'C1', '(of separate elements) To join into a single mass or whole.', 'The droplets coalesced into a puddle.', ARRAY['amalgamate','combine','fuse','join','merge']::TEXT[]),
('Cogent', '/ˈkə͡ʊd͡ʒn̩t/', 'adjective', 'C1', 'Reasonable and convincing; based on evidence.', 'The prosecution presented a cogent argument, convincing the jury of the defendant''''s guilt.', ARRAY[]::TEXT[]),
('Cohesive', '/ˈkəʊ.hiː.sɪv/', 'adjective', 'C1', 'Having cohesion.', '', ARRAY[]::TEXT[]),
('Collusion', '/kəˈluːʒən/', 'noun', 'C1', 'A secret agreement for an illegal purpose; conspiracy.', '', ARRAY[]::TEXT[]),
('Colossal', '/kəˈlɒsəl/', 'adjective', 'C1', 'Extremely large or on a great scale.', 'A single puppy can make a colossal mess.', ARRAY['enormous','giant','gigantic','immense','prodigious']::TEXT[]),
('Commendable', '/kəˈmɛndəbəl/', 'adjective', 'C1', 'Worthy of commendation; deserving praise; admirable, creditable, or meritorious.', '', ARRAY[]::TEXT[]),
('Complacent', '/kəmˈpleɪsənt/', 'adjective', 'C1', 'Uncritically satisfied with oneself or one''''s achievements; smug.', '', ARRAY['self-satisfied','smug']::TEXT[]),
('Complementary', '/ˌkɒmplɪ̈ˈmɛnt(ə)ɹi/', 'adjective', 'C1', 'Acting as a complement; making up a whole with something else.', '', ARRAY[]::TEXT[]),
('Conducive', '/kənˈdjuːsɪv/', 'adjective', 'C1', 'Tending to contribute to, encourage, or bring about some result.', 'A small, dark kitchen is not conducive to elaborate cooking.', ARRAY['favorable','helpful','instrumental','favorable','helpful']::TEXT[]),
('Conniving', '/kəˈnaɪvɪŋ/', 'adjective', 'C1', 'That connives; conspiratorial.', '', ARRAY[]::TEXT[]),
('Consecrate', '/ˈkɒnsəkɹeɪt/', 'adjective', 'C1', 'Consecrated; devoted; dedicated; sacred.', '', ARRAY[]::TEXT[]),
('Consummate', '', 'adjective', 'C1', 'Complete in every detail, perfect, absolute.', 'a consummate sergeant', ARRAY['absolute','complete','perfect','sheer','total']::TEXT[]),
('Contemptuous', '/kənˈtɛm(p).tju.əs/', 'adjective', 'C1', 'Showing contempt; expressing disdain; showing a lack of respect.', 'I don''''t know that guy, but he just gave me a contemptuous look.', ARRAY['disdainful']::TEXT[]),
('Contrite', '/kənˈtɹaɪt/', 'adjective', 'C1', 'Sincerely penitent or feeling regret or sorrow, especially for one’s own actions; apologetic.', '', ARRAY['apologetic']::TEXT[]),
('Conundrum', '/kəˈnʌn.dɹəm/', 'noun', 'C1', 'A difficult question or riddle, especially one using a play on words in the answer.', '', ARRAY['brain-teaser','enigma','puzzle','riddle','dilemma']::TEXT[]),
('Convivial', '/kənˈvɪv.i.əl/', 'adjective', 'C1', 'Having elements of a feast or of entertainment, especially when it comes to eating and drinking, with accompanying festivity', '', ARRAY['festive','gay','jovial','merry','social']::TEXT[]),
('Convoluted', '/-vəʊ-/', 'adjective', 'C1', 'Having numerous overlapping coils or folds; convolute.', 'He gave a convoluted explanation that amounted to little more than a weak excuse for his absence.', ARRAY['meandrine','obvolute','torquated','tortuous','meandrine']::TEXT[]),
('Cornucopia', '/ˌkɔː.nəˈkəʊ.pi.ə/', 'noun', 'C1', 'A goat''''s horn endlessly overflowing with fruit, flowers and grain; or full of whatever its owner wanted.', 'The store provided a veritable cornucopia of modern gadgets.', ARRAY['horn of plenty']::TEXT[]),
('Corroborate', '/kəˈɹɒbəɹeɪ̯t/', 'verb', 'C1', 'To confirm or support something with additional evidence; to attest or vouch for.', '', ARRAY[]::TEXT[]),
('Cosmopolitan', '/ˌkɒz.məˈpɒl.ɪ.tən/', 'adjective', 'C1', 'Inclusive; affecting the whole world.', '', ARRAY[]::TEXT[]),
('Credence', '/ˈkɹiː.dəns/', 'verb', 'C1', 'To give credence to; to believe.', '', ARRAY[]::TEXT[]),
('Creditable', '/ˈkɹɛdɪtəbəl/', 'adjective', 'C1', 'Credible or believable.', '', ARRAY['believable','credible','commendable','respectable','assignable']::TEXT[]),
('Credulity', '/kɹɪˈdjuːlɪti/', 'noun', 'C1', 'A willingness to believe in someone or something in the absence of reasonable proof; credulousness.', '', ARRAY['gullibility']::TEXT[]),
('Cumbersome', '/ˈkʌmbɚsəm/', 'adjective', 'C1', 'Burdensome or hindering, as a weight or drag; vexatious', 'Cumbersome machines can endanger operators and slow down production.', ARRAY['cumbrous','unwieldy']::TEXT[]),
('Dearth', '/dɜːθ/', 'noun', 'C1', 'A period or condition when food is rare and hence expensive; famine.', '', ARRAY['famine','shortage','lack','paucity','scarcity']::TEXT[]),
('Debase', '/dɪˈbeɪs/', 'verb', 'C1', 'To lower in character, quality, or value; to degrade.', '', ARRAY['abase','adulterate','degrade','demean']::TEXT[]),
('Debunk', '/diːˈbʊŋk/', 'verb', 'C1', 'To discredit, or expose to ridicule the falsehood or the exaggerated claims of something.', 'The explosion story was thoroughly debunked on National Public Radio in November 1999.', ARRAY[]::TEXT[]),
('Decimation', '/ˌdɛsɪˈmeɪʃən/', 'noun', 'C1', '(strictly) The killing or punishment of every tenth person, usually by lot.', '', ARRAY['tithing','tithe']::TEXT[]),
('Degrade', '/diˈɡɹeɪd/', 'verb', 'C1', 'To lower in value or social position.', 'Fred degrades himself by his behaviour.', ARRAY[]::TEXT[]),
('Demean', '/dɪˈmiːn/', 'verb', 'C1', 'To debase; to lower; to degrade.', '', ARRAY[]::TEXT[]),
('Demure', '/dɪˈmjʊə(ɹ)/', 'adjective', 'C1', '(usually of women) Quiet, modest, reserved, sober, or serious.', 'She is a demure young lady.', ARRAY[]::TEXT[]),
('Deride', '/dɪˈɹaɪd/', 'verb', 'C1', 'To harshly mock; ridicule.', '', ARRAY[]::TEXT[]),
('Derisive', '/dɪˈɹaɪ.sɪv/', 'adjective', 'C1', 'Expressing or characterized by derision; mocking; ridiculing.', 'The critic''''s review of the film was derisive.', ARRAY['ridiculous','disdainful','mocking','ridiculing','scornful']::TEXT[]),
('Desecrate', '/ˈdɛs.ə.kɹeɪ̯t/', 'adjective', 'C1', 'Desecrated.', '', ARRAY[]::TEXT[]),
('Destitute', '/ˈdɛstɪtjuːt/', 'adjective', 'C1', '(followed by the preposition "of") Lacking something; devoid', '', ARRAY[]::TEXT[]),
('Deter', '/dɪˈtɜː(ɹ)/', 'verb', 'C1', 'To prevent something from happening.', '', ARRAY['dissuade']::TEXT[]),
('Detrimental', '/ˌdɛtɹɪˈmɛntəl/', 'adjective', 'C1', 'Causing damage or harm.', 'Smoking tobacco can be detrimental to your health.', ARRAY['harmful','injurious']::TEXT[]),
('Devolve', '/dɪˈvɒɫv/', 'verb', 'C1', 'To roll (something) down; to unroll.', 'A discussion about politics may devolve into a shouting match.', ARRAY[]::TEXT[]),
('Diabolical', '[ˌdaɪəˈbɒlɪkəɫ]', 'adjective', 'C1', 'Extremely wicked or cruel.', '', ARRAY[]::TEXT[]),
('Dilapidated', '/dɪˈlæpɪdeɪtəd/', 'adjective', 'C1', 'Having fallen into a state of disrepair or deterioration, especially through neglect.', '', ARRAY[]::TEXT[]),
('Diligent', '/ˈdɪlɪdʒənt/', 'adjective', 'C1', 'Performing with industrious concentration; hard-working and focused.', 'Scientists are very diligent in their work.', ARRAY[]::TEXT[]),
('Discord', '/ˈdɪskɔːd/', 'verb', 'C1', 'To disagree; to fail to agree or harmonize; clash.', '', ARRAY[]::TEXT[]),
('Discreet', '/dɪˈskɹiːt/', 'adjective', 'C1', 'Respectful of privacy or secrecy; exercising caution in order to avoid causing embarrassment; quiet; diplomatic.', 'John just doesn''''t understand that laughing at Mary all day is not very discreet.', ARRAY[]::TEXT[]),
('Discriminate', '/dɪsˈkɹɪmɪneɪt/', 'adjective', 'C1', 'Having the difference marked; distinguished by certain tokens.', '', ARRAY[]::TEXT[]),
('Disenfranchise', '/ˌdɪs.ɪnˈfɹæn.tʃaɪz/', 'verb', 'C1', 'To deprive someone of a franchise, generally their right to vote', '', ARRAY['disfranchise']::TEXT[]),
('Disheartened', '', 'adjective', 'C1', 'Discouraged, despairing.', '', ARRAY['dejected','dispirited','down in the dumps','down in the mouth','sad']::TEXT[]),
('Disparate', '/ˈdɪsp(ə)ɹət/', 'adjective', 'C1', 'Composed of inherently different or distinct elements; incongruous.', 'The board of the company was decidedly disparate, with no two members from the same social or economic background.', ARRAY['incongruous','mismatched','uncoordinated','incommensurable','different']::TEXT[]),
('Dispatch', '/dəˈspætʃ/', 'verb', 'C1', 'To send (a shipment) with promptness.', '', ARRAY['destroy','kill','make haste','send']::TEXT[]),
('Docile', '/ˈdəʊ.saɪl/', 'adjective', 'C1', 'Ready to accept instruction or direction; obedient; subservient.', '', ARRAY['amenable','compliant','teachable','compliant','malleable']::TEXT[]),
('Dupe', '/djuːp/', 'verb', 'C1', 'To swindle, deceive, or trick.', '', ARRAY[]::TEXT[]),
('Eccentric', '/ɪkˈsɛntɹɪk/', 'adjective', 'C1', 'Not at or in the centre; away from the centre.', 'As of 2008, Margaret had the most eccentric orbit of any moon in the solar system, though Nereid''''s mean eccentricity is greater.', ARRAY['abnormal','eccentrical','excentrical','odd','eccentrical']::TEXT[]),
('Egotist', '', 'noun', 'C1', 'A person who talks excessively about himself or herself.', '', ARRAY[]::TEXT[]),
('Eke', '/iːk/', 'verb', 'C1', 'Chiefly in the form eke out: to add to, to augment; to increase; to lengthen.', '', ARRAY[]::TEXT[]),
('Elude', '/ɪˈluːd/', 'verb', 'C1', 'To evade, or escape from someone or something, especially by using cunning or skill', '', ARRAY[]::TEXT[]),
('Elusive', '/iˈluːsɪv/', 'adjective', 'C1', 'Evading capture, comprehension or remembrance.', 'The elusive criminal was arrested', ARRAY[]::TEXT[]),
('Embellish', '/ɛm-/', 'verb', 'C1', 'To make more beautiful and attractive; to decorate.', 'The old book cover was embellished with golden letters', ARRAY['adorn','beautify','deck','decorate','grace']::TEXT[]),
('Embroiled', '', 'verb', 'C1', 'To draw into a situation; to cause to be involved.', 'Avoid him. He will embroil you in his fights.', ARRAY[]::TEXT[]),
('Empathetic', '', 'adjective', 'C1', 'Showing empathy for others, and recognizing their feelings; empathic', '', ARRAY[]::TEXT[]),
('Emulate', '/ˈɛm.jə.leɪt/', 'adjective', 'C1', 'Striving to excel; ambitious; emulous.', '', ARRAY[]::TEXT[]),
('Endemic', '/ɛnˈdɛm.ɪk/', 'adjective', 'C1', 'Native to a particular area or culture; originating where it occurs.', 'The endemic religion of Easter Island arrived with the Polynesian settlers.', ARRAY['native','indigenous']::TEXT[]),
('Enmity', '/ˈɛn.mɪ.tɪ/', 'noun', 'C1', 'The quality of being an enemy; hostile or unfriendly disposition.', '', ARRAY[]::TEXT[]),
('Entice', '', 'verb', 'C1', 'To lure; to attract by arousing desire or hope.', 'I enticed the little bear into the trap with a pot of honey.', ARRAY[]::TEXT[]),
('Enumerate', '/ɪˈnjuː.məˌɹeɪt/', 'verb', 'C1', 'To specify each member of a sequence individually in incrementing order.', '', ARRAY['number','tally']::TEXT[]),
('Err', '/ɛə(ɹ)/', 'verb', 'C1', 'To make a mistake.', 'He erred in his calculations, and made many mistakes.', ARRAY[]::TEXT[]),
('Errant', '/ˈɛɹənt/', 'adjective', 'C1', 'Straying from the proper course or standard, or outside established limits.', 'We ran down the street in pursuit of the errant dog.', ARRAY['arrant']::TEXT[]),
('Erratic', '/ɪˈɹætɪk/', 'adjective', 'C1', 'Unsteady, random; prone to unexpected changes; not consistent', 'Henry has been getting erratic scores on his tests: 40% last week, but 98% this week.', ARRAY[]::TEXT[]),
('Euphoria', '/juːˈfɔːɹi.ə/', 'noun', 'C1', 'An excited state of joy; a feeling of intense happiness.', 'The runner was in absolute euphoria after winning his first marathon.', ARRAY[]::TEXT[]),
('Evasive', '/ɪˈveɪsɪv/', 'adjective', 'C1', 'Tending to avoid speaking openly or making revelations about oneself.', '', ARRAY['ambiguous','equivocal','unclear','vague','cagey']::TEXT[]),
('Evenhanded', '', 'adjective', 'C1', 'Fair and having no partiality; unbiased; just.', '', ARRAY[]::TEXT[]),
('Exasperate', '/ɪɡˈzæsp(ə)ɹeɪt/', 'adjective', 'C1', 'Exasperated; embittered.', '', ARRAY[]::TEXT[]),
('Excruciating', '/ɛkˈskɹuːʃiːeɪtɪŋ/', 'adjective', 'C1', 'Causing great pain or anguish, agonizing', '', ARRAY[]::TEXT[]),
('Exemplify', '/ɛɡˈzɛmplɪfaɪ/', 'verb', 'C1', 'To show or illustrate by example.', '', ARRAY[]::TEXT[]),
('Exhort', '/ɛɡˈzɔːt/', 'verb', 'C1', 'To urge; to advise earnestly.', '', ARRAY['counsel','implore','counsel','implore']::TEXT[]),
('Extenuating', '', 'adjective', 'C1', 'That lessens the seriousness of something by providing an excuse.', '', ARRAY[]::TEXT[]),
('Facetious', '/fəˈsiːʃəs/', 'adjective', 'C1', 'Treating serious issues with (often deliberately) inappropriate humour; flippant.', 'Robbie''''s joke about Heather''''s appearance was just him being facetious.', ARRAY[]::TEXT[]),
('Fawn', '/fɔːn/', 'adjective', 'C1', 'Of the fawn colour.', '', ARRAY[]::TEXT[]),
('Ferret', '/ˈfɛɹɪt/', 'verb', 'C1', 'To hunt game with ferrets.', '', ARRAY[]::TEXT[]),
('Fete', '/feɪt/', 'verb', 'C1', '(usually in the passive) To celebrate (a person).', '', ARRAY['celebrate','celebrate']::TEXT[]),
('Fickle', '/ˈfɪk.əl/', 'adjective', 'C1', 'Quick to change one’s opinion or allegiance; insincere; not loyal or reliable.', '', ARRAY[]::TEXT[]),
('Finagle', '/fɪˈneɪ.ɡəl/', 'verb', 'C1', 'To obtain, arrange, or achieve by indirect, complicated and/or intensive efforts.', 'finagle a day off work', ARRAY[]::TEXT[]),
('Inadvertent', '/ˌɪnədˈvɜːtn̩t/', 'adjective', 'C1', 'Not intentional; not on purpose; not conscious.', 'We check everything because an inadvertent error could be disastrous.', ARRAY['absent-minded','distracted','accidental','designless','unintended']::TEXT[]),
('Inarticulate', '/ɪn.ɑːˈtɪk.jʊ.lət/', 'adjective', 'C1', '(of speech) not articulated in normal words', '', ARRAY[]::TEXT[]),
('Incense', '/ɪnˈsɛns/', 'verb', 'C1', 'To anger or infuriate.', 'I think it would incense him to learn the truth.', ARRAY[]::TEXT[]),
('Incessant', '/ɪnˈsɛs.ənt/', 'adjective', 'C1', 'Without pause or stop; not ending, especially to the point of annoyance.', 'The dog''''s incessant barking kept the girl awake all night.', ARRAY['continuous','unceasing','unremitting']::TEXT[]),
('Inclement', '/ɪnˈklɛm.ənt/', 'adjective', 'C1', 'Stormy, of rough weather', 'inclement weather', ARRAY[]::TEXT[]),
('Incumbent', '/ɪnˈkʌmbənt/', 'adjective', 'C1', 'Imposed on someone as an obligation, especially due to one''''s office.', 'Proper behavior is incumbent on all holders of positions of trust.', ARRAY[]::TEXT[]),
('Indict', '/ˌɪnˈdaɪt/', 'verb', 'C1', 'To accuse of wrongdoing; charge.', 'a book that indicts modern values', ARRAY[]::TEXT[]),
('Indignant', '/ɪnˈdɪɡ.nənt/', 'adjective', 'C1', 'Showing anger or indignation, especially at something unjust or wrong.', '', ARRAY['angry','infuriated','mad','resentful']::TEXT[]),
('Industrious', '/ɪnˈdʌstɹi.əs/', 'adjective', 'C1', 'Hard-working and persistent.', 'I was very industrious in my effort to learn unicycle riding.', ARRAY[]::TEXT[]),
('Inflammable', '/ɪnˈflæməbəl/', 'adjective', 'C1', 'Capable of burning; easily set on fire.', '', ARRAY['combustible','flammable','hot-headed','quick to anger','combustible']::TEXT[]),
('Ingenuity', '/ˌɪndʒəˈn(j)uːəti/', 'noun', 'C1', 'The ability to solve difficult problems, often in original, clever, and inventive ways.', 'Ingenuity is one of the characteristics of a beaver.', ARRAY[]::TEXT[]),
('Inkling', '/ˈɪŋklɪŋ/', 'noun', 'C1', 'Usually preceded by forms of to give: a slight hint, implication, or suggestion given.', '', ARRAY['intimation','intimation']::TEXT[]),
('Insipid', '/ɪnˈsɪp.ɪd/', 'adjective', 'C1', 'Unappetizingly flavorless.', 'The diners were disappointed with the plain, insipid soup they were served.', ARRAY['bland','boring','characterless','colourless','dull']::TEXT[]),
('Insolvent', '', 'adjective', 'C1', 'Unable to pay one''''s bills as they fall due.', 'an insolvent debtor', ARRAY[]::TEXT[]),
('Intermittent', '/ˌɪntəˈmɪtn̩t/', 'adjective', 'C1', 'Stopping and starting, occuring, or presenting at intervals; coming after a particular time span.', 'Intermittent bugs are most difficult to reproduce.', ARRAY['patchy','periodic','periodical','spasmodic','patchy']::TEXT[]),
('Inundate', '/ˈɪn.ən.deɪt/', 'verb', 'C1', 'To cover with large amounts of water; to flood.', 'The Dutch would sometimes inundate the land to hinder the Spanish army.', ARRAY['beflood','deluge','flood','beflood','deluge']::TEXT[]),
('Irascible', '/ɪˈɹæs.ə.bəl/', 'adjective', 'C1', 'Easily provoked to outbursts of anger; irritable.', '', ARRAY['cantankerous','choleric','cranky','hot-tempered','ill-tempered']::TEXT[]),
('Irk', '/ɜːk/', 'verb', 'C1', 'To irritate; annoy; bother', '', ARRAY[]::TEXT[]),
('Irresolute', '', 'adjective', 'C1', 'Undecided or unsure how to act', '', ARRAY[]::TEXT[]),
('Jargon', '/ˈdʒɑː.ɡən/', 'verb', 'C1', 'To utter jargon; to emit confused or unintelligible sounds.', '', ARRAY[]::TEXT[]),
('Jocular', '/ˈdʒɒkjʊlə/', 'adjective', 'C1', 'Humorous, amusing or joking.', 'All we had was a short and jocular conversation.', ARRAY['joculous','jokey','silly']::TEXT[]),
('Junta', '/ˈdʒʊntə/', 'noun', 'C1', 'A council, convention, tribunal or assembly; especially, the grand council of state in Spain.', '', ARRAY[]::TEXT[]),
('Laborious', '/ləˈbɔːɹiəs/', 'adjective', 'C1', 'Requiring much physical effort; toilsome.', '', ARRAY['painstaking','toilsome','worksome']::TEXT[]),
('Leery', '/ˈlɪə.ɹi/', 'adjective', 'C1', 'Cautious, suspicious, wary, hesitant, or nervous about something; having reservations or concerns.', 'Since he was bitten by a dog when he was young, he has always been leery of animals.', ARRAY[]::TEXT[]),
('Lethargic', '/ləˈθɑɹdʒɪk/', 'adjective', 'C1', 'Sluggish, slow', '', ARRAY['lazy','torpid','unmoving']::TEXT[]),
('Lucid', '/ˈl(j)uːsɪd/', 'adjective', 'C1', 'Clear; easily understood', '', ARRAY['brilliant','light','clear','perspicuous','straightforward']::TEXT[]),
('Macabre', '/məˈkɑːbə(ɹ)/', 'adjective', 'C1', 'Representing or personifying death.', '', ARRAY['ghastly','horrifying','shocking','terrifying','ghastly']::TEXT[]),
('Malady', '/ˈmæl.ə.di/', 'noun', 'C1', 'Any ailment or disease of the body; especially, a lingering or deep-seated disorder.', '', ARRAY['ailment','disease','disorder','distemper','illness']::TEXT[]),
('Malevolent', '/məˈlɛvələnt/', 'adjective', 'C1', 'Having or displaying ill will; wishing harm on others', '', ARRAY[]::TEXT[]),
('Malleable', '/ˈmæli.əbəl/', 'adjective', 'C1', 'Able to be hammered into thin sheets; capable of being extended or shaped by beating with a hammer, or by the pressure of rollers.', 'My opinion on the subject is malleable.', ARRAY[]::TEXT[]),
('Malodorous', '/ˌmælˈəʊ.də.ɹəs/', 'adjective', 'C1', 'Having a bad odor.', 'There were tons of malodorous garbage bags outside her house.', ARRAY['fetid','foul','foul-smelling','funky','mephitic']::TEXT[]),
('Maxim', '/ˈmæk.sɪm/', 'noun', 'C1', 'A self-evident axiom or premise; a pithy expression of a general principle or rule.', '', ARRAY['aphorism','cliche','enthymeme','proverb','saying']::TEXT[]),
('Meander', '/miˈændə(ɹ)/', 'verb', 'C1', 'To wind or turn in a course or passage; to be intricate.', 'The stream meandered through the valley.', ARRAY[]::TEXT[]),
('Melancholy', '/ˈmelənkəli/', 'adjective', 'C1', 'Affected with great sadness or depression.', 'Melancholy people don''''t talk much.', ARRAY['melancholic']::TEXT[]),
('Melee', '/ˈmɛ.li/', 'verb', 'C1', 'To physically hit in close quarters, as opposed to shooting, blowing up, or other ranged means of damage. Often refers to the usage of a hand-to-hand weapon.', '', ARRAY[]::TEXT[]),
('Mesmerize', '/ˈmɛzməɹaɪz/', 'verb', 'C1', 'To exercise mesmerism on; to affect another person, such as to heal or soothe, through the use of animal magnetism.', 'She mesmerized the audience with her tricks', ARRAY['enthrall','fascinate','hypnotize','spellbind']::TEXT[]),
('Misanthrope', '/ˈmɪs.ənˌθɹoʊp/', 'noun', 'C1', 'One who hates all mankind; one who hates the human race.', '', ARRAY['misanthropist']::TEXT[]),
('Miscreant', '/ˈmɪs.kɹi.ənt/', 'adjective', 'C1', 'Lacking in conscience or moral principles; unscrupulous.', '', ARRAY[]::TEXT[]),
('Miser', '/ˈmaɪzə(ɹ)/', 'noun', 'C1', 'A person who hoards money rather than spending it; one who is cheap or extremely parsimonious.', '', ARRAY[]::TEXT[]),
('Misogynist', '/mɪˈsɒdʒ.ən.ɪst/', 'adjective', 'C1', 'Misogynistic: relating to or exhibiting misogyny.', '', ARRAY[]::TEXT[]),
('Moot', '/muːt/', 'adjective', 'C1', 'Subject to discussion (originally at a moot); arguable, debatable, unsolved or impossible to solve.', '1903, Walter Crane and Lewis F. Day, Moot Points: Friendly Disputes on Art and Industry Between Walter Crane and Lewis F. Day', ARRAY['irrelevant','obsolete']::TEXT[]),
('Morose', '/məˈɹəʊs/', 'adjective', 'C1', 'Sullen, gloomy; showing a brooding ill humour.', '', ARRAY['crabby','glum','grouchy','gruff','melancholy']::TEXT[]),
('Morph', '/mɔː(ɹ)f/', 'noun', 'C1', '(grammar) A physical form representing some morpheme in language. It is a recurrent distinctive sound or sequence of sounds.', '', ARRAY[]::TEXT[]),
('Muted', '', 'adjective', 'C1', 'Not expressed strongly or openly.', '', ARRAY[]::TEXT[]),
('Obdurate', '/-ət/', 'adjective', 'C1', 'Stubbornly persistent, generally in wrongdoing; refusing to reform or repent.', '', ARRAY['hard-hearted','hardened','impertinent','intractable','recalcitrant']::TEXT[]),
('Obliging', '/əˈblaɪd͡ʒɪŋ/', 'adjective', 'C1', 'Happy and ready to do favours for others.', '', ARRAY['accommodating','willing']::TEXT[]),
('Obstinate', '/ˈɒb.stɪ.nət/', 'adjective', 'C1', 'Stubbornly adhering to an opinion, purpose, or course, usually with implied unreasonableness; persistent.', '', ARRAY['inexorable','persistent','unrelenting','bloody-minded','persistent']::TEXT[]),
('Ornate', '/ɔɹˈneɪt/', 'adjective', 'C1', 'Elaborately ornamented, often to excess.', '', ARRAY[]::TEXT[]),
('Paradoxical', '/ˌpæɹəˈdɒksɪkəl/', 'adjective', 'C1', 'Having self-contradictory properties.', '', ARRAY['oxymoronic','self-contradictory']::TEXT[]),
('Pastoral', '/ˈpæs.tə.ɹəl/', 'adjective', 'C1', 'Of or pertaining to shepherds or herders of other livestock', 'We were living a pastoral life.', ARRAY[]::TEXT[]),
('Patronize', '/ˈpeɪt(ʃ)ɹənaɪz/', 'verb', 'C1', 'To act as a patron of; to defend, protect, or support.', '', ARRAY['condescend','infantilize','enpatron','patrocinate','enpatron']::TEXT[]),
('Paucity', '/ˈpɑsɪti/', 'noun', 'C1', 'Fewness in number; too few.', '', ARRAY['dearth','scantiness','scarcity']::TEXT[]),
('Peevish', '/ˈpiːvɪʃ/', 'adjective', 'C1', 'Characterized by or exhibiting petty bad temper, bad-tempered, moody, cross.', 'I would rather figure things out on my own than ask that peevish librarian for help.', ARRAY[]::TEXT[]),
('Perennial', '/pəˈɹɛni.əl/', 'adjective', 'C1', 'Lasting or remaining active throughout the year, or all the time.', 'a perennial stream', ARRAY['everlasting','perpetual','timeless','permanent','perpetual']::TEXT[]),
('Perpetuate', '', 'adjective', 'C1', 'Made perpetual; continued for an indefinite time.', '', ARRAY[]::TEXT[]),
('Pertinent', '/ˈpəːtɪnənt/', 'adjective', 'C1', 'Important with regard to (a subject or matter); relevant', '', ARRAY[]::TEXT[]),
('Perturb', '/pɚˈtɝb/', 'verb', 'C1', 'To disturb; to bother or unsettle.', '', ARRAY[]::TEXT[]),
('Peruse', '/pəˈɹuːz/', 'verb', 'C1', 'To examine or consider with care.', '', ARRAY[]::TEXT[]),
('Pine', '/paɪn/', 'noun', 'C1', 'Any coniferous tree of the genus Pinus.', 'The northern slopes were covered mainly in pine.', ARRAY['pine tree','pinewood','pine tree','pinewood']::TEXT[]),
('Pinnacle', '/ˈpɪnəkəl/', 'verb', 'C1', 'To put something on a pinnacle.', '', ARRAY[]::TEXT[]),
('Piquant', '/piːˈkɑːnt/', 'adjective', 'C1', 'Causing hurt feelings; scathing, severe.', '', ARRAY[]::TEXT[]),
('Pithy', '/ˈpɪθi/', 'adjective', 'C1', 'Concise and meaningful.', '', ARRAY['concise','laconic','succinct','terse']::TEXT[]),
('Pittance', '/ˈpɪtəns/', 'noun', 'C1', 'A small allowance of food and drink; a scanty meal.', '', ARRAY[]::TEXT[]),
('Placid', '/ˈplæs.ɪd/', 'adjective', 'C1', 'Calm and quiet; peaceful; tranquil', 'a placid disposition', ARRAY[]::TEXT[]),
('Plodding', '', 'adjective', 'C1', 'Progressing slowly and laboriously.', '', ARRAY[]::TEXT[]),
('Ploy', '/plɔɪ/', 'noun', 'C1', 'A tactic, strategy, or gimmick.', 'The free T-shirt is really a ploy to get you inside to see their sales pitch.', ARRAY[]::TEXT[]),
('Powwow', '', 'verb', 'C1', '(of Native Americans) To hold a meeting; to gather together in council.', '', ARRAY[]::TEXT[]),
('Precarious', '/pɹəˈkɛəɹi.əs/', 'adjective', 'C1', 'Dangerously insecure or unstable; perilous.', '', ARRAY['rickety','shaky','tottering','unsafe','unstable']::TEXT[]),
('Preempt', '', 'verb', 'C1', 'To appropriate something (before someone else does).', '', ARRAY['ninja']::TEXT[]),
('Preemptive', '/pɹiːˈɛmp.tɪv/', 'adjective', 'C1', 'Of or relating to preemption.', '', ARRAY[]::TEXT[]),
('Presumption', '', 'noun', 'C1', 'The act of presuming, or something presumed', 'The presumption is that an event has taken place.', ARRAY['overhope']::TEXT[]),
('Presumptuous', '/pɹəˈzʌmp.tjuː.əs/', 'adjective', 'C1', 'Going beyond what is right, proper, or appropriate because of an excess of self-confidence or arrogance.', '', ARRAY['arrogant','conceited','foolhardy','forward','insolent']::TEXT[]),
('Pristine', '/pɹɪsˈtaɪn/', 'adjective', 'C1', 'Unspoiled; still with its original purity; uncorrupted or unsullied.', '', ARRAY[]::TEXT[]),
('Profuse', '/pɹəˈfjuːs/', 'adjective', 'C1', 'In great quantity or abundance; liberal or generous to the point of excess.', 'She grew profuse amounts of zucchini and pumpkins.', ARRAY[]::TEXT[]),
('Profusion', '/pɹə(ʊ)ˈfjuːʒən/', 'noun', 'C1', 'Abundance; the state of being profuse; a cornucopia', 'His hair, in great profusion, streamed down over his shoulders.', ARRAY[]::TEXT[]),
('Proponent', '/pɹəˈpəʊnənt/', 'adjective', 'C1', 'Making proposals; proposing.', '', ARRAY[]::TEXT[]),
('Provisional', '/pɹəˈvɪʒənəl/', 'adjective', 'C1', 'Temporary, but with the intention of eventually becoming permanent or being replaced by a permanent equivalent.', '', ARRAY['provisionary']::TEXT[]),
('Pugnacious', '/pʌɡˈneɪ.ʃəs/', 'adjective', 'C1', 'Naturally aggressive or hostile; combative; belligerent; bellicose.', '', ARRAY[]::TEXT[]),
('Qualm', '/kwɑːm/', 'verb', 'C1', 'To have a sickly feeling.', '', ARRAY[]::TEXT[]),
('Quandary', '/ˈkwɔn.də.ɹi/', 'noun', 'C1', 'A state of not knowing what to decide; a state of difficulty or perplexity; a state of uncertainty, hesitation or puzzlement.', '', ARRAY['dilemma','perplexity','pickle','predicament','uncertainty']::TEXT[]),
('Quip', '/kwɪp/', 'verb', 'C1', 'To make a quip.', '', ARRAY[]::TEXT[]),
('Raffish', '', 'adjective', 'C1', 'Characterized by careless unconventionality; rakish.', '', ARRAY[]::TEXT[]),
('Raft', '/ɹɑːft/', 'verb', 'C1', 'To convey on a raft.', '', ARRAY[]::TEXT[]),
('Rakish', '/ˈɹeɪkɪʃ/', 'adjective', 'C1', 'Dashingly, carelessly, or sportingly unconventional or stylish; jaunty; characterized by a devil-may-care unconventionality; having a somewhat disreputable quality or appearance.', '', ARRAY[]::TEXT[]),
('Rankle', '/ˈɹæŋ.kəl/', 'verb', 'C1', 'To cause irritation or deep bitterness.', 'a splinter rankles in the flesh', ARRAY['embitter','irritate','fester']::TEXT[]),
('Rash', '/ɹæʃ/', 'adjective', 'C1', 'Acting too quickly without considering the risks and consequences; not careful; hasty.', 'rash words spoken in the heat of debate', ARRAY['brash','heady','hotheaded','impulsive','inconsiderate']::TEXT[]),
('Redress', '/ɹɪˈdɹɛs/', 'verb', 'C1', 'To put in order again; to set right; to revise.', '', ARRAY[]::TEXT[]),
('Relegate', '/ˈɹɛlɪɡeɪt/', 'verb', 'C1', 'Exile, banish, remove, or send away.', '', ARRAY[]::TEXT[]),
('Remiss', '/ɹəˈmɪs/', 'adjective', 'C1', 'At fault; failing to fulfill responsibility, duty, or obligations.', 'I would certainly be remiss if I did not give credit where credit was due.', ARRAY['at fault','blameworthy','lash','lax','negligent']::TEXT[]),
('Renege', '/ɹɪˈneɪɡ/', 'verb', 'C1', 'To break a promise or commitment; to go back on one''''s word.', '', ARRAY[]::TEXT[]),
('Replete', '/ɹɪˈpliːt/', 'adjective', 'C1', 'Gorged, filled to near the point of bursting, especially with food or drink.', '', ARRAY['abundant','plentiful','stuffed']::TEXT[]),
('Reprobate', '/ˈɹɛpɹəbət/', 'adjective', 'C1', 'Rejected; cast off as worthless.', 'The reprobate criminal sneered at me.', ARRAY[]::TEXT[]),
('Respite', '/ˈɹɛspɪt/', 'verb', 'C1', 'To delay or postpone (an event).', '', ARRAY[]::TEXT[]),
('Retiring', '/ɹəˈtaɪ(ə)ɹɪŋ/', 'adjective', 'C1', 'Introverted, liking privacy and seclusion.', 'I don''''t really know him well, since he''''s so shy and retiring.', ARRAY[]::TEXT[]),
('Retract', '/ɹəˈtɹækt/', 'verb', 'C1', 'To pull back inside.', 'An airplane retracts its wheels for flight.', ARRAY['take back','withcall','withdraw']::TEXT[]),
('Rile', '', 'verb', 'C1', 'To make angry', 'It riles me that she never closes the door after she leaves.', ARRAY['aggravate','anger','annoy','irritate','vex']::TEXT[]),
('Sanctimonious', '/ˌsæŋk.təˈməʊ.ni.əs/', 'adjective', 'C1', 'Making a show of being morally better than others, especially hypocritically pious.', '', ARRAY[]::TEXT[]),
('Sanguine', '/ˈsæŋ.ɡwɪn/', 'adjective', 'C1', 'Having the colour of blood; blood red.', 'a sanguine bodily temperament', ARRAY['animated','assured','bright','bullish','buoyant']::TEXT[]),
('Savvy', '/ˈsæ.vi/', 'adjective', 'C1', 'Shrewd, well-informed and perceptive.', '', ARRAY['canny']::TEXT[]),
('Scintillating', '/ˌsɪntɪˈleɪtɪŋ/', 'adjective', 'C1', 'That scintillates with brief flashes of light; sparkling.', '', ARRAY[]::TEXT[]),
('Screed', '/skɹiːd/', 'noun', 'C1', 'A piece or narrow strip cut or torn off from a larger whole; a shred.', '', ARRAY['cut','rip','polemic','rant','tirade']::TEXT[]),
('Sentimental', '/ˌsɛntiˈmɛntl̩/', 'adjective', 'C1', 'Characterized by sentiment, sentimentality or excess emotion.', '', ARRAY[]::TEXT[]),
('Serendipity', '/ˌsɛ.ɹən.ˈdɪ.pɪ.ti/', 'noun', 'C1', 'A combination of events which have come together by chance to make a surprisingly good or wonderful outcome.', '', ARRAY['chance','luck','chance','luck']::TEXT[]),
('Serene', '/səˈɹiːn/', 'adjective', 'C1', 'Peaceful, calm, unruffled.', 'She looked at her students with joviality and a serene mentality.', ARRAY[]::TEXT[]),
('Slapdash', '/ˈslæpdæʃ/', 'adjective', 'C1', 'Produced or carried out hastily; haphazard; careless.', '', ARRAY[]::TEXT[]),
('Smattering', '/ˈsmæ.təɹ.ɪŋ/', 'noun', 'C1', 'A superficial or shallow knowledge of a subject.', 'She knows a smattering of Greek, but not enough to carry on a conversation.', ARRAY[]::TEXT[]),
('Smug', '/smʌɡ/', 'adjective', 'C1', 'Irritatingly pleased with oneself, offensively self-complacent, self-satisfied.', 'Kate looked extremely smug this morning.', ARRAY['complacent','gloaty','self-satisfied']::TEXT[]),
('Snide', '/snaɪd/', 'adjective', 'C1', 'Disparaging or derisive in an insinuative way.', 'Don''''t make snide remarks to me.', ARRAY[]::TEXT[]),
('Snub', '/snʌb/', 'adjective', 'C1', 'Conspicuously short.', 'a snub-nosed revolver', ARRAY[]::TEXT[]),
('Sordid', '/ˈsɔː.dɪd/', 'adjective', 'C1', 'Distasteful, ignoble, vile, or contemptible.', '', ARRAY[]::TEXT[]),
('Spendthrift', '/ˈspɛn(d)θɹɪft/', 'adjective', 'C1', 'Improvident, profligate, or wasteful.', '', ARRAY[]::TEXT[]),
('Spurn', '/spɜːn/', 'verb', 'C1', 'To reject disdainfully; contemn; scorn.', '', ARRAY[]::TEXT[]),
('Squander', '/ˈskwɒnd.ə/', 'verb', 'C1', 'To waste, lavish, splurge; to spend lavishly or profusely; to dissipate.', '', ARRAY['ducks and drakes','splurge','waste','throw away']::TEXT[]),
('Staid', '/sted/', 'adjective', 'C1', 'Not capricious or impulsive; sedate, serious, sober.', '', ARRAY['composed','dignified','regular','steady','composed']::TEXT[]),
('Steadfast', '/ˈstɛdfæst/', 'adjective', 'C1', 'Fixed or unchanging; steady.', '', ARRAY[]::TEXT[]),
('Stipend', '/-pn̩d/', 'verb', 'C1', 'To provide (someone) with a stipend.', '', ARRAY[]::TEXT[]),
('Stolid', '/ˈstɒl.ɪd/', 'adjective', 'C1', 'Having or revealing little emotion or sensibility; dully or heavily stupid.', '', ARRAY[]::TEXT[]),
('Stymie', '/ˈstaɪmi/', 'verb', 'C1', 'To thwart or stump; to cause to fail or to leave hopelessly puzzled, confused, or stuck.', 'If writing dates has you stymied at times, it is probably for one of two reasons. https//www.grammarly.com/blog/how-to-write-dates/', ARRAY['block','thwart','block','thwart']::TEXT[]),
('Surly', '/ˈsɜːli/', 'adjective', 'C1', 'Irritated, bad-tempered, unfriendly.', 'The surly weather put us all in a bad mood.', ARRAY[]::TEXT[]),
('Tact', '/tækt/', 'verb', 'C1', 'To use a tact (a kind of verbal operant; see noun sense).', '', ARRAY[]::TEXT[]),
('Tarnish', '/ˈtɑɹnɪʃ/', 'verb', 'C1', 'To oxidize or discolor due to oxidation.', 'Careful storage of silver will prevent it from tarnishing.', ARRAY[]::TEXT[]),
('Tawdry', '/ˈtɔːdɹi/', 'adjective', 'C1', '(of clothing, appearance, etc.) Cheap and gaudy; showy.', '', ARRAY['sordid']::TEXT[]),
('Taxing', '', 'adjective', 'C1', 'With respect to an experience: exhausting; draining.', 'a taxing problem', ARRAY[]::TEXT[]),
('Telling', '/ˈtɛlɪŋ/', 'adjective', 'C1', 'Having force, or having a marked effect; weighty, effective.', 'a telling blow', ARRAY[]::TEXT[]),
('Telltale', '/ˈtɛlteɪl/', 'adjective', 'C1', 'Revealing something, especially something not intended to be known.', 'He blushed when he approached, a telltale sign that he was happy to see him.', ARRAY[]::TEXT[]),
('Thoroughgoing', '', 'adjective', 'C1', 'Complete; thorough; with great attention to detail.', 'He did a thoroughgoing job of cleaning up the broken glass.', ARRAY[]::TEXT[]),
('Thrifty', '/ˈθɹɪfti/', 'adjective', 'C1', 'Evincing thrift; characterized by economy and good management of property; frugal.', 'a thrifty person', ARRAY[]::TEXT[]),
('Thwart', '/θwɔːt/', 'adjective', 'C1', 'Placed or situated across something else; cross, oblique, transverse.', '', ARRAY['cross-grained','froward','unpropitious','untoward','cross-grained']::TEXT[]),
('Tirade', '/ˈtaɪɹeɪd/', 'verb', 'C1', 'To make a long, angry or violent speech, a tirade.', '', ARRAY[]::TEXT[]),
('Tout', '/taʊt/', 'verb', 'C1', 'To flaunt, to publicize/publicise; to boast or brag; to promote.', 'Mary has been touted as a potential succesor to the current COE.', ARRAY['pimp','pitch','promote','spruik']::TEXT[]),
('Transitory', '/ˈtɹæn.sɪ.t(ə)ɹɪ/', 'adjective', 'C1', 'Lasting only a short time; temporary.', '', ARRAY[]::TEXT[]),
('Travail', '/tɹəˈveɪl/', 'noun', 'C1', 'Arduous or painful exertion; excessive labor, suffering, hardship.', '', ARRAY[]::TEXT[]),
('Tribulation', '/ˌtɹɪbjʊˈleɪ̯ʃən/', 'noun', 'C1', 'Any adversity; a trying period or event.', '', ARRAY[]::TEXT[]),
('Tumult', '/ˈtjuː.mʌlt/', 'verb', 'C1', 'To make a tumult; to be in great commotion.', '', ARRAY[]::TEXT[]),
('Uncanny', '/ʌnˈkæni/', 'adjective', 'C1', 'Strange, and mysteriously unsettling (as if supernatural); weird.', 'He bore an uncanny resemblance to the dead sailor.', ARRAY[]::TEXT[]),
('Uncompromising', '', 'adjective', 'C1', 'Inflexible and unwilling to negotiate or make concessions.', '', ARRAY[]::TEXT[]),
('Unconscionable', '/ənˈkɔn.ʃən.ə.bəl/', 'adjective', 'C1', 'Not conscionable; unscrupulous and lacking principles or conscience.', 'The effective rate of interest was unconscionable, but not legally usurious.', ARRAY[]::TEXT[]),
('Underwrite', '/ʌndəˈɹaɪt/', 'verb', 'C1', 'To write below or under; subscribe.', '', ARRAY[]::TEXT[]),
('Unnerve', '', 'verb', 'C1', 'To deprive of nerve, force, or strength; to weaken; to enfeeble.', 'to unnerve the arm', ARRAY[]::TEXT[]),
('Unruly', '/ʌnˈɹuːli/', 'adjective', 'C1', 'Wild; uncontrolled.', 'The police gathered to contain the unruly mob.', ARRAY[]::TEXT[]),
('Unseemly', '', 'adjective', 'C1', 'Inconsistent with established standards of good form or taste.', 'He was drunk and made some very unseemly comments.', ARRAY[]::TEXT[]),
('Urbane', '/ɜːˈbeɪn/', 'adjective', 'C1', '(of a man) Courteous, polite, refined, and suave.', '1949: George Orwell, Nineteen Eighty-Four, p12', ARRAY[]::TEXT[]),
('Vacuous', '/ˈvækju.əs/', 'adjective', 'C1', 'Empty; void; lacking meaningful content.', '', ARRAY[]::TEXT[]),
('Vanquish', '/ˈvæŋkwɪʃ/', 'verb', 'C1', 'To defeat, to overcome.', '', ARRAY[]::TEXT[]),
('Variance', '/ˈvɛːɹi.əns/', 'noun', 'C1', 'The act of varying or the state of being variable.', 'Depending on the variance of the type constructor, the subtyping relation of the simple types may be either preserved, reversed, or ignored for the respective complex types.', ARRAY[]::TEXT[]),
('Veneer', '/vəˈniə(ɹ)/', 'verb', 'C1', 'To apply veneer to.', 'to veneer a piece of furniture with mahogany', ARRAY[]::TEXT[]),
('Vicarious', '/vɪˈkɛəɹi.əs/', 'adjective', 'C1', 'Experienced or gained by taking in another person’s experience, rather than through first-hand experience, such as through watching or reading.', 'People experience vicarious pleasures through watching television.', ARRAY[]::TEXT[]),
('Vie', '/vaɪ/', 'verb', 'C1', 'To fight for superiority; to contend; to compete eagerly so as to gain something.', 'Her suitors were all vying for her attention.', ARRAY['battle','compete','oppose']::TEXT[]),
('Vindictive', '/vɪnˈdɪk.tɪv/', 'adjective', 'C1', 'Having a tendency to seek revenge when wronged, vengeful.', '', ARRAY['nasty','revengeful','vengeful']::TEXT[]),
('Virago', '/vɪˈɹɑːɡəʊ/', 'noun', 'C1', 'A woman given to undue belligerence or ill manner at the slightest provocation.', '', ARRAY['shrew','shrew','termagant','shrew','termagant']::TEXT[]),
('Voracious', '/vɔːˈɹeɪ.ʃəs/', 'adjective', 'C1', 'Wanting or devouring great quantities of food.', '', ARRAY[]::TEXT[]),
('Wanton', '/ˈwɒntɒn/', 'adjective', 'C1', 'Undisciplined, unruly; not able to be controlled.', '', ARRAY['callous','inhumane','merciless','lewd','lustful']::TEXT[]),
('Wax', '/wæks/', 'adjective', 'C1', 'Made of wax.', '', ARRAY['waxen']::TEXT[]),
('Whimsical', '/ˈwɪmzɪkəl/', 'adjective', 'C1', 'Given to whimsy.', '', ARRAY['idiosyncratic','outlandish','peculiar','pixilated','playful']::TEXT[]),
('Zenith', '/ˈzɛn.ɪθ/', 'noun', 'C1', 'The point in the sky vertically above a given position or observer; the point in the celestial sphere opposite the nadir.', 'Winning the continental championship was the zenith of my career.', ARRAY['acme','apogee','culmination','pinnacle','acme']::TEXT[]),
('Aberrant', '/əˈbɛɹ.n̩t/', 'adjective', 'C1', 'Differing from the norm.', '', ARRAY['abnormal','exceptional','unusual','devious','errant']::TEXT[]),
('Aberration', '/ˌæb.əˈɹeɪ.ʃn̩/', 'noun', 'C1', 'The act of wandering; deviation from truth, moral rectitude; abnormal; divergence from the straight, correct, proper, normal, or from the natural state.', 'aberration of character', ARRAY[]::TEXT[]),
('Abstain', '/əbˈsteɪn/', 'verb', 'C1', 'Keep or withhold oneself.', 'In order to improve his health, Rob decided to abstain from smoking.', ARRAY['deny','forbear','forgo','give up','refrain']::TEXT[]),
('Abstruse', '/əbˈstɹuːs/', 'adjective', 'C1', 'Difficult to comprehend or understand.', '', ARRAY['clandestine','secret','surreptitious','esoteric','obscure']::TEXT[]),
('Accolade', '/ˈæk.ə.ˌleɪd/', 'verb', 'C1', 'To embrace or kiss in salutation.', 'an accoladed novel', ARRAY[]::TEXT[]),
('Acerbic', '/əˈsɜː(ɹ)bɪk/', 'adjective', 'C1', 'Tasting sour or bitter.', '', ARRAY['acrid','acrimonious','scathing','acerb','acrid']::TEXT[]),
('Acrimony', '', 'noun', 'C1', 'A sharp and bitter hatred.', 'Her acrimony for her neighbors manifests itself with shouting and stomping.', ARRAY['animosity','bitterness','enmity','hatred','opposition']::TEXT[]),
('Adamant', '/ˈæ.də.mænt/', 'adjective', 'C1', '(said of people and their conviction) Firm; unshakeable; unyielding; determined.', '', ARRAY[]::TEXT[]),
('Admonish', '/ədˈmɒn.ɪʃ/', 'verb', 'C1', 'To warn or notify of a fault; to reprove gently or kindly, but seriously; to exhort.', '', ARRAY['chide','reprimand']::TEXT[]),
('Admonitory', '', 'adjective', 'C1', 'Of or pertaining to an admonition; serving to reprove, warn or advise.', 'He wagged an admonitory finger at the culprit.', ARRAY[]::TEXT[]),
('Aesthete', '/ˈɛs.θiːt/', 'noun', 'C1', 'Someone who cultivates an unusually high sensitivity to beauty, as in art or nature.', '', ARRAY[]::TEXT[]),
('Amalgam', '/əˈmæl.ɡəm/', 'verb', 'C1', 'To amalgamate.', '', ARRAY[]::TEXT[]),
('Ambiguous', '/æmˈbɪɡjuəs/', 'adjective', 'C1', 'Open to multiple interpretations.', 'The politician was criticized for his ambiguous statements and lack of precision.', ARRAY['equivocal','equivocal']::TEXT[]),
('Ambivalent', '/æmˈbɪv.ə.lənt/', 'adjective', 'C1', 'Simultaneously experiencing or expressing opposing or contradictory feelings, beliefs, or motivations.', 'He has an ambivalent relationship towards his parents.', ARRAY['fluctuating','vacillating','wavering','conflicted','uncertain']::TEXT[]),
('Ameliorate', '/əˈmiːli.əɹeɪt/', 'verb', 'C1', 'To make better, or improve, something perceived to be in a negative condition.', 'They offered some compromises in an effort to ameliorate the situation.', ARRAY[]::TEXT[]),
('Amenable', '/əˈmɛn.ə.bəl/', 'adjective', 'C1', 'Willing to respond to persuasion or suggestions.', '', ARRAY[]::TEXT[]),
('Amorphous', '/əˈmɔɹfəs/', 'adjective', 'C1', 'Lacking a definite form or clear shape.', 'The enormous pile of spaghetti landed on the floor in an amorphous heap.', ARRAY['formless','shapeless','formless','shapeless']::TEXT[]),
('Anomalous', '', 'adjective', 'C1', 'Deviating from the normal; marked by incongruity or contradiction; aberrant or abnormal.', '', ARRAY[]::TEXT[]),
('Anomaly', '/əˈnɒməlɪ/', 'noun', 'C1', 'A deviation from a rule or from what is regarded as normal; an outlier.', 'He is an anomaly among his friends in that he''''s the only one who''''s unmarried.', ARRAY['abnormality','deviance','deviation','exception','inconsistency']::TEXT[]),
('Antipathy', '/ænˈtɪpəθi/', 'noun', 'C1', 'A feeling of dislike (normally towards someone, less often towards something); repugnance or distaste.', 'oil and water have antipathy', ARRAY['aversion','contrariety','disgust','dislike','distaste']::TEXT[]),
('Antithetical', '', 'adjective', 'C1', 'Pertaining to antithesis, or opposition of words and sentiments; containing, or of the nature of, antithesis; contrasted.', 'His wrong-headed beliefs are antithetical to everything we stand for as a community.', ARRAY[]::TEXT[]),
('Apathetic', '/æp.əˈθɛt.ɪk/', 'adjective', 'C1', 'Void of feeling; not susceptible of deep emotion', '', ARRAY['impassive','incurious','indifferent','indifferent','passionless']::TEXT[]),
('Apathy', '/ˈæ.pə.θi/', 'noun', 'C1', 'Lack of emotion or motivation; lack of interest or enthusiasm towards something; disinterest (in something).', '', ARRAY['indifference','neutrality','indifference','neutrality']::TEXT[]),
('Apocryphal', '/əˈpɒkɹəfəl/', 'adjective', 'C1', 'Of, or pertaining to, the Apocrypha.', 'Many scholars consider the stories of the monk Teilo to be apocryphal.', ARRAY['allonymous','spurious','anecdotal','allonymous','spurious']::TEXT[]),
('Appease', '/əˈpiːz/', 'verb', 'C1', 'To make quiet; to calm; to reduce to a state of peace; to dispel (anger or hatred).', 'to appease the tumult of the ocean', ARRAY['calm','lull','pacify','placate','quell']::TEXT[]),
('Arcane', '/ɑɹˈkeɪn/', 'adjective', 'C1', 'Understood by only a few.', 'arcane rituals', ARRAY['clandestine','enigmatic','esoteric','recondite','esoteric']::TEXT[]),
('Arduous', '/ˈɑːdjuːəs/', 'adjective', 'C1', 'Needing or using up much energy; testing powers of endurance.', 'The movement towards a peaceful settlement has been a long and arduous political struggle.', ARRAY['burdensome','demanding','exhausting','fatiguing','laborious']::TEXT[]),
('Artful', '/ˈɑːɹt.fəl/', 'adjective', 'C1', 'Cunning; tending toward indirect dealings; crafty.', '', ARRAY[]::TEXT[]),
('Ascetic', '/əˈsɛ.tɪk/', 'adjective', 'C1', 'Of or relating to ascetics', '', ARRAY['abstinent','ascetical','ascetical']::TEXT[]),
('Askance', '/əˈskæns/', 'adjective', 'C1', 'Turned to the side, especially of the eyes.', '', ARRAY['askew','oblique','sideways']::TEXT[]),
('Audacious', '/ɔːˈdeɪʃəs/', 'adjective', 'C1', 'Showing willingness to take bold risks; recklessly daring.', '', ARRAY['bold','daring','temerarious','temeritous']::TEXT[]),
('Audacity', '/ɔːˈdæsɪti/', 'noun', 'C1', 'Insolent boldness, especially when imprudent or unconventional.', 'Somebody never pays his loans, yet he has the audacity to ask the bank for money.', ARRAY['audaciousness','outdaciousness','temerity']::TEXT[]),
('Auspicious', '/ɔːˈspɪʃəs/', 'adjective', 'C1', 'Of good omen; indicating future success.', 'This is an auspicious day.', ARRAY['favorable','favourable','fortunate','lucky','promising']::TEXT[]),
('Austere', '/ɒstɪə(ɹ)/', 'adjective', 'C1', 'Grim or severe in manner or appearance', 'The headmistress was an austere old woman.', ARRAY['forbidding','stern','strict','plain','simple']::TEXT[]),
('Avaricious', '/ˌævəˈɹɪʃəs/', 'adjective', 'C1', 'Actuated by avarice; extremely greedy for wealth or material gain; immoderately desirous of accumulating property.', '', ARRAY[]::TEXT[]),
('Banal', '/bəˈnæl/', 'adjective', 'C1', 'Common in a boring way, to the point of being predictable; containing nothing new or fresh.', '', ARRAY['everyday','prosaic','everyday','prosaic']::TEXT[]),
('Banality', '/beɪˈnælɨti/', 'noun', 'C1', 'The quality of being banal.', '', ARRAY['bathos','bathos']::TEXT[]),
('Belie', '/bɪˈlʌɪ/', 'verb', 'C1', 'To lie around; encompass.', '', ARRAY[]::TEXT[]),
('Belligerent', '/bəˈlɪdʒ.(ə).ɹənt/', 'adjective', 'C1', 'Engaged in warfare, warring.', '', ARRAY['aggressive','antagonistic','bellicose','combative','contentious']::TEXT[]),
('Blatant', '/ˈbleɪtənt/', 'adjective', 'C1', 'Bellowing; disagreeably clamorous; sounding loudly and harshly.', '', ARRAY[]::TEXT[]),
('Bolster', '/ˈbəʊlstə/', 'verb', 'C1', 'To brace, reinforce, secure, or support.', '', ARRAY[]::TEXT[]),
('Brazen', '/ˈbɹeɪzən/', 'adjective', 'C1', 'Pertaining to, made of, or resembling brass (in color or strength).', 'She was brazen enough to deny stealing the handbag even though she was caught on closed-circuit television doing so.', ARRAY[]::TEXT[]),
('Bucolic', '/bjuːˈkɒlɪk/', 'adjective', 'C1', 'Rustic, pastoral, country-styled.', '', ARRAY[]::TEXT[]),
('Bumbling', '', 'adjective', 'C1', 'Acting in a confused or ineffectual way; incompetent; showing little or no skill.', 'a bumbling fool', ARRAY[]::TEXT[]),
('Burgeon', '/ˈbɜː.d͡ʒən/', 'verb', 'C1', 'To grow or expand.', 'Gradually, the town burgeoned into a thriving city.', ARRAY['blossom','bud','green','sprout','blossom']::TEXT[]),
('Calumny', '/kəˈlʌmni/', 'verb', 'C1', 'To make false accusations or levy false charges against a person with the intent to tarnish that person''''s reputation or standing; to calumniate.', '', ARRAY[]::TEXT[]),
('Capricious', '/kəˈpɹɪʃəs/', 'adjective', 'C1', 'Impulsive and unpredictable; determined by chance, impulse, or whim', 'I almost died in a capricious winter storm.', ARRAY['arbitrary','whimsical']::TEXT[]),
('Castigate', '/ˈkæs.tə.ɡeɪt/', 'verb', 'C1', 'To punish or reprimand someone severely.', '', ARRAY['condemn','lambaste','chastise','punish','rebuke']::TEXT[]),
('Censure', '/ˈsɛn.sjə/', 'verb', 'C1', 'To criticize harshly.', '', ARRAY[]::TEXT[]),
('Chastise', '/tʃæˈstaɪz/', 'verb', 'C1', 'To punish (someone), especially by corporal punishment.', '', ARRAY[]::TEXT[]),
('Chortle', '/ˈt͡ʃɔɹtəl/', 'verb', 'C1', 'To laugh with a chortle or chortles.', 'The old fellow chortled as he recalled his youthful adventures.', ARRAY['chuckle']::TEXT[]),
('Circumscribe', '/ˈsɜː.kəm.skɹaɪb/', 'verb', 'C1', 'To draw a line around; to encircle.', '', ARRAY[]::TEXT[]),
('Circumvent', '', 'verb', 'C1', 'To avoid or get around something; to bypass', '', ARRAY[]::TEXT[]),
('Commensurate', '/kəˈmɛnʃəɹət/', 'adjective', 'C1', 'Of a proportionate or similar measurable standard.', '', ARRAY[]::TEXT[]),
('Confound', '/kənˈfaʊnd/', 'verb', 'C1', 'To perplex or puzzle.', 'Don''''t confound the situation by yelling.', ARRAY['confuse','mix up','puzzle','puzzle','confuse']::TEXT[]),
('Duress', '/djʊˈɹɛs/', 'verb', 'C1', 'To put under duress; to pressure.', 'Someone was duressing her.', ARRAY[]::TEXT[]),
('Eclectic', '/ɛkˈlɛk.tɪk/', 'adjective', 'C1', 'Selecting a mixture of what appears to be best of various doctrines, methods or styles.', '', ARRAY['heterogeneous']::TEXT[]),
('Economical', '/ˌɛkəˈnɒmɪkəl/', 'adjective', 'C1', 'Careful with money so as not to spend too much; prudent; thrifty.', 'He was an economical person by nature.', ARRAY[]::TEXT[]),
('Edifying', '/ˈɛdɪfaɪɪŋ/', 'adjective', 'C1', 'That educates, informs, illuminates or instructs.', '', ARRAY[]::TEXT[]),
('Efficacious', '/ɛf.ɪ.ˈkeɪ.ʃəs/', 'adjective', 'C1', 'Effective; possessing efficacy.', 'This medicine is efficacious.', ARRAY['effective','effective']::TEXT[]),
('Egregious', '/əˈɡɹiː.dʒi.əs/', 'adjective', 'C1', 'Usually in a negative sense: conspicuous, exceptional, outstanding.', 'The student has made egregious errors on the examination.', ARRAY[]::TEXT[]),
('Elicit', '/ɪˈlɪsɪt/', 'adjective', 'C1', 'Elicited; drawn out; made real; open; evident.', '', ARRAY[]::TEXT[]),
('Elucidate', '/əˈluː.sɪ.de͡ɪt/', 'verb', 'C1', 'To make clear; to clarify; to shed light upon.', '', ARRAY['explicate','illuminate','explicate','illuminate']::TEXT[]),
('Eminent', '/ˈɛmɪnənt/', 'adjective', 'C1', 'High, lofty.', 'His eminent good sense has been a godsend to this project.', ARRAY['distinguished','noteworthy','outstanding','remarkable','prominent']::TEXT[]),
('Enervate', '', 'adjective', 'C1', 'Made feeble; weakened.', '', ARRAY[]::TEXT[]),
('Engender', '/ɛnˈdʒɛn.də/', 'verb', 'C1', 'To beget (of a man); to bear or conceive (of a woman).', '', ARRAY['assemble','beget','conjure','craft','create']::TEXT[]),
('Entrenched', '', 'verb', 'C1', 'To dig or excavate a trench; to trench.', 'The army entrenched its camp, or entrenched itself.', ARRAY['trench','consolidate','dig in']::TEXT[]),
('Ephemeral', '/əˈfɛ.mə.ɹəl/', 'adjective', 'C1', 'Lasting for a short period of time.', '', ARRAY['evanescent','fleeting','momentary','short','short-lived']::TEXT[]),
('Equivocal', '/əˈkwɪvəkəl/', 'adjective', 'C1', 'Having two or more equally applicable meanings; capable of double or multiple interpretation.', 'an equivocal sentence', ARRAY['ambiguous','indeterminate','doubtful','incongruous','uncertain']::TEXT[]),
('Eradicate', '/ɪˈɹæd.ɪ.keɪt/', 'verb', 'C1', 'To pull up by the roots; to uproot.', 'Smallpox was globally eradicated in 1980.', ARRAY['annihilate','exterminate','extirpate','root up','uproot']::TEXT[]),
('Erudite', '/ˈɛɹ.ʊ.daɪt/', 'adjective', 'C1', 'Learned, scholarly, with emphasis on knowledge gained from books.', '', ARRAY[]::TEXT[]),
('Eschew', '/ɛsˈtʃuː/', 'verb', 'C1', 'To avoid; to shun, to shy away from.', '', ARRAY[]::TEXT[]),
('Esoteric', '/ˌɛs.əʊˈtɛɹ.ɪk/', 'adjective', 'C1', 'Intended for or likely to be understood by only a small number of people with a specialized knowledge or interest, or an enlightened inner circle.', 'The writing in this manual is very esoteric; I’d need a degree in engineering just to understand it!', ARRAY['secretive','cerebral','arcane','recondite']::TEXT[]),
('Espouse', '/ɪˈspaʊz/', 'verb', 'C1', 'To become/get married to.', '', ARRAY[]::TEXT[]),
('Exacerbate', '/ɪkˈsæs-/', 'verb', 'C1', 'To make worse (a problem, bad situation, negative feeling, etc.); aggravate; exasperate.', 'The proposed shutdown would exacerbate unemployment problems.', ARRAY[]::TEXT[]),
('Exacting', '', 'adjective', 'C1', 'Making excessive demands; difficult to satisfy.', '', ARRAY['acquisitive','extortionate','grasping','money-grubbing','rapacious']::TEXT[]),
('Exalt', '/ɪɡˈzɔːlt/', 'verb', 'C1', 'To honor; to hold in high esteem.', 'They exalted their queen.', ARRAY['upgrade']::TEXT[]),
('Exonerate', '/ɛɡ-/', 'adjective', 'C1', 'Freed from an obligation; freed from accusation or blame; acquitted, exonerated.', '', ARRAY[]::TEXT[]),
('Expound', '/ɪkˈspaʊnd/', 'verb', 'C1', 'To set out the meaning of; to explain or discuss at length', 'He expounded often on the dangers of the imperial presidency.', ARRAY['spell out','spell out']::TEXT[]),
('Extant', '/ɛkˈstænt/', 'adjective', 'C1', 'Still in existence.', '', ARRAY['alive and kicking','living','vital','existent','existing']::TEXT[]),
('Fallacious', '/fə.ˈleɪ.ʃəs/', 'adjective', 'C1', 'Characterized by fallacy; false or mistaken.', '', ARRAY[]::TEXT[]),
('Fastidious', '/fæˈstɪdi.əs/', 'adjective', 'C1', 'Excessively particular, demanding, or fussy about details, especially about tidiness and cleanliness.', '', ARRAY['exacting','fussy','meticulous','niggly','pernickety']::TEXT[]),
('Flux', '/flʌks/', 'adjective', 'C1', 'Flowing; unstable; inconstant; variable.', '', ARRAY[]::TEXT[]),
('Foment', '/fəʊˈmɛnt/', 'verb', 'C1', 'To incite or cause troublesome acts; to encourage; to instigate.', 'Foreign governments have tried to foment unrest.', ARRAY['beath','beath']::TEXT[]),
('Forlorn', '/fɔː-/', 'adjective', 'C1', 'Abandoned, deserted, left behind.', '', ARRAY['forsaken','forsaken']::TEXT[]),
('Fortuitous', '/fɔːˈtjuːɪtəs/', 'adjective', 'C1', 'Happening by chance; coincidental, accidental.', '', ARRAY['by accident','causeless','incidental','happy','providential']::TEXT[]),
('Frivolous', '/ˈfɹɪv.əl.əs/', 'adjective', 'C1', 'Silly, especially at an inappropriate time or in an inappropriate manner.', '', ARRAY[]::TEXT[]),
('Frugal', '/ˈfɹuːɡəl/', 'adjective', 'C1', 'Avoiding unnecessary expenditure either of money or of anything else which is to be used or consumed; avoiding waste.', '', ARRAY['cheap','economical','thrifty']::TEXT[]),
('Frustrate', '/fɹəˈstɹeɪt/', 'adjective', 'C1', 'Ineffectual; useless; fruitless.', '', ARRAY[]::TEXT[]),
('Furtive', '[ˈfɜːɾɪv]', 'adjective', 'C1', 'Exhibiting guilty or evasive secrecy.', '', ARRAY['surreptitious']::TEXT[]),
('Gainsay', '/ˈɡeɪnˌseɪ/', 'verb', 'C1', 'To say something in contradiction to.', '', ARRAY['controvert','deny','dispute','refute','withsay']::TEXT[]),
('Gall', '/ɡɑl/', 'verb', 'C1', 'To bother or trouble.', 'Improper cooling and a dull milling blade on titanium can gall the surface.', ARRAY[]::TEXT[]),
('Galvanize', '/ˈɡælvənaɪ̯z/', 'verb', 'C1', 'To coat with a thin layer of metal by electrochemical means.', 'to galvanize steel', ARRAY['animate','startle','urge','electroplate','zinc']::TEXT[]),
('Garrulous', '/ˈɡæɹ.jʊ.ləs/', 'adjective', 'C1', 'Excessively or tiresomely talkative.', '', ARRAY['bombastic','rambling','wordy','chatty','long-winded']::TEXT[]),
('Gauche', '/ɡəʊʃ/', 'adjective', 'C1', 'Awkward or lacking in social graces; bumbling.', '', ARRAY['gawky','graceless','tactless','unpolished','unsophisticated']::TEXT[]),
('Germane', '/dʒɜː(ɹ)ˈmeɪn/', 'adjective', 'C1', 'Related to the topic being discussed or considered.', '', ARRAY['apt','on-topic','pertinent','relevant','apt']::TEXT[]),
('Glut', '/ɡlʌt/', 'verb', 'C1', 'To fill to capacity; to satisfy all demand or requirement; to sate.', 'to glut one''''s appetite', ARRAY[]::TEXT[]),
('Ingratiate', '/ɪnˈɡɹeɪ.ʃi.eɪt/', 'verb', 'C1', 'To bring oneself into favour with someone by flattering or trying to please him or her.', '', ARRAY[]::TEXT[]),
('Inimical', '/ɪˈnɪmɪkəl/', 'adjective', 'C1', 'Harmful in effect.', '', ARRAY['antagonistic','inimic','inimicable']::TEXT[]),
('Innocuous', '/ɪˈnɒkjuəs/', 'adjective', 'C1', 'Harmless; producing no ill effect.', '', ARRAY['harmless','innoxious','nonpoisonous','nontoxic','undamaging']::TEXT[]),
('Inscrutable', '/ˌɪnˈskɹuːtəbl/', 'adjective', 'C1', 'Difficult or impossible to comprehend, fathom or interpret.', 'His inscrutable theories would years later become the foundation of a whole new science.', ARRAY['ineffable','ineffable']::TEXT[]),
('Insidious', '/ɪnˈsɪdi.əs/', 'adjective', 'C1', 'Producing harm in a stealthy, often gradual, manner.', 'Hansel and Gretel were lured by the witch’s insidious gingerbread house.', ARRAY[]::TEXT[]),
('Insolent', '/ˈɪnsə.lənt/', 'adjective', 'C1', 'Insulting in manner or words.', '', ARRAY['arrogant','bold','cocky','impudent','disrespectful']::TEXT[]),
('Intransigent', '/ɪnˈtɹæn.sə.d͡ʒənt/', 'adjective', 'C1', 'Unwilling to compromise or moderate a position; unreasonable', 'Don''''t waste your time trying to change his mind: he''''s completely intransigent.', ARRAY[]::TEXT[]),
('Intrepid', '/ɪnˈtɹɛpɪd/', 'adjective', 'C1', 'Fearless; bold; brave.', '', ARRAY['courageous','fearless','unafraid','courageous','fearless']::TEXT[]),
('Inveterate', '/ɪnˈvɛtəɹɪt/', 'adjective', 'C1', 'Firmly established from having been around for a long time; of long standing', 'an inveterate disease', ARRAY['chronic','deep-rooted','hardened','ineradicable','ingrained']::TEXT[]),
('Irrevocable', '/ɪˈɹɛvəkəb(ə)l/', 'adjective', 'C1', 'Unable to be retracted or reversed; final.', '', ARRAY[]::TEXT[]),
('Itinerant', '/aɪˈtɪnɚənt/', 'adjective', 'C1', 'Habitually travelling from place to place.', 'an itinerant preacher or peddler', ARRAY[]::TEXT[]),
('Jingoism', '/ˈdʒɪŋɡəʊɪz(ə)m/', 'noun', 'C1', 'Excessive patriotism or aggressive nationalism, especially with regards to foreign policy.', '', ARRAY['chauvinism','flagwaving']::TEXT[]),
('Jovial', '/ˈdʒəʊ.vɪ.əl/', 'adjective', 'C1', 'Cheerful and good-humoured; jolly, merry.', '', ARRAY[]::TEXT[]),
('Jubilant', '/ˈdʒu.bə.lənt/', 'adjective', 'C1', 'In a state of elation.', '', ARRAY['delighted','elated','joyful','thrilled']::TEXT[]),
('Juxtapose', '/ˈd͡ʒʌkstəpəʊz/', 'verb', 'C1', 'To place side by side, especially for contrast or comparison.', '', ARRAY[]::TEXT[]),
('Laconic', '/ləˈkɒnɪk/', 'adjective', 'C1', 'Using as few words as possible; pithy and concise.', '', ARRAY['concise','pithy','terse']::TEXT[]),
('Lambast', '', 'verb', 'C1', 'To scold, reprimand or criticize harshly.', 'Her first novel was well and truly lambasted by the critics.', ARRAY['beat','hit','thrash','berate','scold']::TEXT[]),
('Languid', '/ˈlæŋ.ɡwɪd/', 'adjective', 'C1', 'Lacking enthusiasm, energy, or strength; drooping or flagging from weakness, fatigue, or lack of energy', 'languid breathing', ARRAY['exhausted','faint','listless','swear','sweer']::TEXT[]),
('Largess', '/lɑːˈdʒɛs/', 'noun', 'C1', 'Generosity in the giving of gifts or money.', '', ARRAY['benevolence','generosity','graciousness','boon']::TEXT[]),
('Laudable', '/lɔːdəbl/', 'adjective', 'C1', 'Worthy of being lauded; praiseworthy; commendable', 'laudable actions', ARRAY['commendable','praiseworthy']::TEXT[]),
('Lionize', '/ˈlaɪənaɪz/', 'verb', 'C1', 'To treat (a person) as if they were important, or a celebrity.', '', ARRAY[]::TEXT[]),
('Magnanimous', '/mæɡˈnæn.ɪ.məs/', 'adjective', 'C1', 'Noble and generous in spirit.', 'He thinks himself ardent, impulsive, passionate, magnanimous — capable of boundless enthusiasm for an idea or a sentiment.', ARRAY['big-hearted','generous','great-hearted','large-hearted','unselfish']::TEXT[]),
('Maladroit', '/ˌmæl.ə.ˈdɹɔɪt/', 'adjective', 'C1', 'Not adroit; awkward, clumsy, inept.', '', ARRAY[]::TEXT[]),
('Maverick', '/ˈmævəɹɪk/', 'adjective', 'C1', 'Of cattle: unbranded.', 'He made a maverick decision. She is such a maverick person.', ARRAY[]::TEXT[]),
('Mawkish', '/ˈmɑːkɪʃ/', 'adjective', 'C1', 'Feeling sick, queasy.', '', ARRAY['cutesy','schmaltzy']::TEXT[]),
('Mendacity', '/mɛnˈdæsəti/', 'noun', 'C1', 'The fact or condition of being untruthful; dishonesty.', '', ARRAY[]::TEXT[]),
('Mercurial', '/məːˈkjʊə.ɹɪ.əl/', 'adjective', 'C1', 'Having a lively or volatile character; animated, changeable, quick-witted.', 'his mercurial temperament', ARRAY['fickle','unpredictable','fickle','unpredictable']::TEXT[]),
('Meticulous', '/mɨˈtɪkjuləs/', 'adjective', 'C1', 'Characterized by very precise, conscientious attention to details.', '', ARRAY['careful','painstaking','precise','rigorous','scrupulous']::TEXT[]),
('Misconstrue', '/mɪskənˈstɹuː/', 'verb', 'C1', 'To interpret erroneously, to understand incorrectly; to misunderstand.', '', ARRAY['misinterpret','misunderstand']::TEXT[]),
('Mitigate', '/ˈmɪt.ɪ.ɡeɪt/', 'verb', 'C1', 'To reduce, lessen, or decrease; to make less severe or easier to bear.', '', ARRAY['alleviate','check','diminish','ease','lighten']::TEXT[]),
('Mollify', '/ˈmɒlɪfaɪ/', 'verb', 'C1', 'To ease a burden, particularly worry; make less painful; to comfort.', '', ARRAY['appease','conciliate','pacify','placate','propitiate']::TEXT[]),
('Mundane', '/mʌnˈdeɪn/', 'adjective', 'C1', 'Worldly, earthly, profane, vulgar as opposed to heavenly.', '', ARRAY['banal','boring','commonplace','everyday','jejune']::TEXT[]),
('Munificent', '/mjuˈnɪfɨsn̩t/', 'adjective', 'C1', '(of a person or group) Very liberal in giving or bestowing.', '', ARRAY['bounteous','generous','liberal']::TEXT[]),
('Myopic', '/maɪˈɒpɪk/', 'adjective', 'C1', 'Near-sighted; unable to see distant objects unaided', 'A stronger prescription for myopic night drivers is often needed.', ARRAY['near-sighted','short-sighted']::TEXT[]),
('Myriad', '/ˈmɪɹi.æd/', 'adjective', 'C1', '(modifying a singular noun) Multifaceted, having innumerable elements', 'Earth hosts myriad animals.', ARRAY[]::TEXT[]),
('Negligible', '/ˈnɛɡlɪdʒɪbəl/', 'adjective', 'C1', 'Able to be neglected, ignored or excluded from consideration; too small or unimportant to be of concern.', 'We found errors, but their effects were negligible.', ARRAY['ignorable','neglectable','slight','trivial']::TEXT[]),
('Nonplussed', '/nɒnˈplʌst/', 'adjective', 'C1', 'Bewildered; unsure how to respond or act.', '', ARRAY['confounded','foiled','frustrated','perplexed','thwarted']::TEXT[]),
('Nuance', '/ˈnjuː.ɑːns/', 'verb', 'C1', 'To apply a nuance to; to change or redefine in a subtle way.', '', ARRAY[]::TEXT[]),
('Obscure', '/əbˈskjɔː(ɹ)/', 'adjective', 'C1', 'Dark, faint or indistinct.', 'an obscure passage or inscription; The speaker made obscure references to little-known literary works.', ARRAY['cimmerian','dingy','fathomless','inscrutable','fuzzy']::TEXT[]),
('Obsequious', '/əbˈsiːkwi.əs/', 'adjective', 'C1', 'Obedient; compliant with someone else''''s orders or wishes.', '', ARRAY['asskissing','fawning','ingratiating','servile','slavish']::TEXT[]),
('Opaque', '/əʊˈpeɪk/', 'adjective', 'C1', 'Neither reflecting nor emitting light.', '', ARRAY[]::TEXT[]),
('Opulence', '', 'noun', 'C1', 'Abundance, bounty, profusion', '', ARRAY[]::TEXT[]),
('Ostentatious', '/ˌɒs.tənˈteɪ.ʃəs/', 'adjective', 'C1', 'Of ostentation.', '', ARRAY[]::TEXT[]),
('Ostracize', '/ˈɒstɹəsaɪz/', 'verb', 'C1', 'To ban a person from a city for five or ten years through the procedure of ostracism.', '', ARRAY['blackball','cut someone dead','give someone the cold shoulder','send to Coventry','blackball']::TEXT[]),
('Panache', '/pəˈnæʃ/', 'noun', 'C1', 'An ornamental plume on a helmet.', '', ARRAY['dash','flamboyance','swagger','verve','hackle']::TEXT[]),
('Parochial', '/pəˈɹəʊkɪəl/', 'adjective', 'C1', 'Pertaining to a parish.', 'Some people in the United States have been accused of taking a parochial view, of not being interested in international matters.', ARRAY[]::TEXT[]),
('Parsimonious', '/pɑɹ.sɪˈmo͡ʊn.i.əs/', 'adjective', 'C1', 'Exhibiting parsimony; sparing in the expenditure of money; frugal to excess.', '', ARRAY['niggardly','penurious','stingy','tight-fisted','niggardly']::TEXT[]),
('Pedantic', '/pəˈdæn.tɪk/', 'adjective', 'C1', 'Like a pedant, overly concerned with formal rules and trivial points of learning.', '', ARRAY['fussy','inkhorn','nit-picky','anal-retentive','fussy']::TEXT[]),
('Pedestrian', '/pəˈdɛst.ɹi.ən/', 'adjective', 'C1', 'Of or intended for those who are walking.', 'pedestrian crossing', ARRAY[]::TEXT[]),
('Pejorative', '/pɪˈdʒɒɹətɪv/', 'adjective', 'C1', 'Disparaging, belittling or derogatory.', '', ARRAY['derogatory','dyslogistic']::TEXT[]),
('Perfidy', '/ˈpɜː.fɪ.di/', 'noun', 'C1', 'A state or act of violating faith or allegiance; violation of a promise or vow, or of trust', '', ARRAY['betrayal','treachery','perfidiousness','betrayal','treachery']::TEXT[]),
('Pernicious', '/pəˈnɪʃəs/', 'adjective', 'C1', 'Causing much harm in a subtle way.', '', ARRAY['attery','deleterious','deleterious','attery']::TEXT[]),
('Petulant', '/ˈpɛtjələnt/', 'adjective', 'C1', 'Childishly irritable', 'Lack of sleep is causing Dave''''s recent petulant behavior.', ARRAY['brazen','flippant','impertinent','bad-tempered','crabby']::TEXT[]),
('Placate', '/pleɪˈkeɪt/', 'verb', 'C1', 'To calm; to bring peace to; to influence someone who was furious to the point that they become content or at least no longer irate.', '', ARRAY['appease','conciliate','mollify','propitiate','satisfy']::TEXT[]),
('Platitude', '/ˈplatɪtjuːd/', 'noun', 'C1', 'An often-quoted saying that is supposed to be meaningful but has become unoriginal or hackneyed through overuse; a cliché.', '', ARRAY['cliché']::TEXT[]),
('Poignant', '/ˈpɔɪn.jənt/', 'adjective', 'C1', 'Of a weapon, etc.: sharp-pointed; keen.', 'A poignant reply will garner more credence than hours of blown smoke.', ARRAY['distressing','moving','distressing','moving']::TEXT[]),
('Polemic', '/pəˈlɛmɪk/', 'adjective', 'C1', 'Having the characteristics of a polemic.', '', ARRAY['polemical']::TEXT[]),
('Posit', '/ˈpɒzɪt/', 'verb', 'C1', 'Assume the existence of; to postulate.', '', ARRAY[]::TEXT[]),
('Pragmatic', '/pɹæɡˈmætɪk/', 'adjective', 'C1', 'Practical, concerned with making decisions and actions that are useful in practice, not just theory.', 'The sturdy furniture in the student lounge was pragmatic, but unattractive.', ARRAY['down-to-earth','functional','practical','realistic','utilitarian']::TEXT[]),
('Precipitous', '/pɹɪˈsɪpɪtəs/', 'adjective', 'C1', 'Steep, like a precipice', 'a precipitous cliff', ARRAY['heedless','hotheaded','impetuous','headlong','precipitant']::TEXT[]),
('Preclude', '/pɹiːˈkluːd/', 'verb', 'C1', 'Remove the possibility of; rule out; prevent or exclude; to make impossible.', 'It has been raining for days, but that doesn’t preclude the possibility that the skies will clear by this afternoon!', ARRAY[]::TEXT[]),
('Precocious', '/pɹəˈkəʊʃəs/', 'adjective', 'C1', 'Characterized by exceptionally early development or maturity.', 'The precocious plant was already blooming flowers by day 4.', ARRAY['tranty']::TEXT[]),
('Predilection', '/ˌpɹiː.dəˈlɛk.ʃn̩/', 'noun', 'C1', 'Condition of favoring or liking; tendency towards; proclivity; predisposition.', '', ARRAY[]::TEXT[]),
('Prescience', '/ˈpɹɛsɪ.əns/', 'noun', 'C1', 'Knowledge of events before they take place; foresight; foreknowledge.', '', ARRAY[]::TEXT[]),
('Prevaricate', '/pɹɪˈvaɹɪkeɪt/', 'verb', 'C1', 'To deviate, transgress; to go astray (from).', 'The people saw the politician prevaricate every day.', ARRAY['beat around the bush','tergiversate']::TEXT[]),
('Subsume', '/səbˈsuːm/', 'verb', 'C1', 'To place (any one cognition) under another as belonging to it; to include or contain something else.', '', ARRAY[]::TEXT[]),
('Subversive', '/səbˈvɜɹsɪv/', 'adjective', 'C1', 'Intending to subvert, overturn or undermine a government or authority.', '', ARRAY['insurgent','seditious']::TEXT[]),
('Subvert', '/səbˈvɜːt/', 'verb', 'C1', 'To overturn from the foundation; to overthrow; to ruin utterly.', 'A dictator stays in power only as long as he manages to subvert the will of his people.', ARRAY[]::TEXT[]),
('Sullen', '/ˈsʌlən/', 'adjective', 'C1', 'Having a brooding ill temper; sulky.', '', ARRAY['morose','sulky']::TEXT[]),
('Superfluous', '/sjʊˈpɜːflu.əs/', 'adjective', 'C1', 'In excess of what is required or sufficient.', 'With a full rain suit, carrying an umbrella may be superfluous.', ARRAY['excessive','extra','extraneous','extravagant','pleonastic']::TEXT[]),
('Supplant', '/səˈplænt/', 'verb', 'C1', 'To take the place of; to replace, to supersede.', 'Will online dictionaries ever supplant paper dictionaries?', ARRAY['uproot','wrench','dethrone','oust','replace']::TEXT[]),
('Sycophant', '/ˈsɪkəfænt/', 'verb', 'C1', 'To inform against; hence, to calumniate.', '', ARRAY[]::TEXT[]),
('Taciturn', '/ˈtæsɪtɜːn/', 'adjective', 'C1', 'Silent; temperamentally untalkative; disinclined to speak.', 'The two sisters could hardly have been more different, one so boisterous and expressive, the other so taciturn and calm.', ARRAY['reticent','untalkative']::TEXT[]),
('Tantamount', '/ˈtæntəˌmaʊnt/', 'adjective', 'C1', 'Equivalent in meaning or effect; amounting to the same thing in practical terms, even if being technically distinct.', 'In this view, disagreement and treason are tantamount.', ARRAY[]::TEXT[]),
('Temperance', '', 'noun', 'C1', 'Habitual moderation in regard to the indulgence of the natural appetites and passions; restrained or moderate indulgence', 'temperance in eating and drinking', ARRAY['calmness','patience','sedateness','calmness','patience']::TEXT[]),
('Tempered', '', 'adjective', 'C1', '(in combination) Having a specified disposition or temper.', '', ARRAY[]::TEXT[]),
('Tenacious', '/təˈneɪʃəs/', 'adjective', 'C1', 'Clinging to an object or surface; adhesive.', '', ARRAY['clingsome','sticky','elephantlike','memorious','coherent']::TEXT[]),
('Timorous', '/ˈtɪməɹəs/', 'adjective', 'C1', 'Fearful; afraid; timid', '', ARRAY['fearful','shy','timid']::TEXT[]),
('Torpor', '/ˈtɔːpə(ɹ)/', 'noun', 'C1', 'A state of being inactive or stuporous.', '', ARRAY['languor','lethargy','sluggishness','torpidity','languor']::TEXT[]),
('Tortuous', '/ˈtɔːt͡ʃuːəs/', 'adjective', 'C1', 'Twisted; having many turns; convoluted.', '', ARRAY[]::TEXT[]),
('Tractable', '/ˈtɹæk.tə.bəl/', 'adjective', 'C1', '(of people) Capable of being easily led, taught, or managed.', '', ARRAY['docile','governable','manageable','feasible','palpable']::TEXT[]),
('Transient', '', 'adjective', 'C1', 'Passing or disappearing with time; transitory.', 'a transient pleasure', ARRAY['brief','ephemeral','fleeting','flighty','fugacious']::TEXT[]),
('Travesty', '/ˈtɹæv.əs.ti/', 'verb', 'C1', 'To make a travesty of; to parody.', '', ARRAY[]::TEXT[]),
('Treacherous', '/ˈtɹɛtʃəɹəs/', 'adjective', 'C1', 'Exhibiting treachery.', 'a treacherous mountain trail', ARRAY[]::TEXT[]),
('Trite', '/tɹaɪt/', 'adjective', 'C1', 'Often in reference to a word or phrase: used so many times that it is commonplace, or no longer interesting or effective; worn out, hackneyed.', '', ARRAY[]::TEXT[]),
('Truncate', '/tɹʌŋˈkeɪt/', 'adjective', 'C1', 'Having an abrupt termination.', '', ARRAY[]::TEXT[]),
('Underscore', '/ˈʌn.də(ɹ)ˌskɔː(ɹ)/', 'verb', 'C1', 'To underline; to mark a line beneath text.', 'I wish to underscore the importance of proper formatting.', ARRAY[]::TEXT[]),
('Unequivocal', '/ʌnɨˈkwɪvəkəl/', 'adjective', 'C1', 'Unambiguous; without equivocation or ambiguity; singularly clear, unmistakable, or unquestionable', 'I want you to give me an unequivocal guarantee on that.', ARRAY['definite','unambiguous','univocal']::TEXT[]),
('Unscrupulous', '/ˌʌnˈskɹuːpjʊləs/', 'adjective', 'C1', 'Without scruples; immoral.', '', ARRAY[]::TEXT[]),
('Upbraid', '/ˌʌpˈbɹeɪd/', 'verb', 'C1', 'To criticize severely.', '', ARRAY['cast up','cast up']::TEXT[]),
('Vacillate', '/ˈvæ.sə.leɪt/', 'verb', 'C1', 'To sway unsteadily from one side to the other; oscillate.', '', ARRAY['stagger','blow hot and cold','waffle']::TEXT[]),
('Vehement', '/ˈviː.ə.mənt/', 'adjective', 'C1', 'Showing strong feelings; passionate; forceful or intense.', '', ARRAY['full-throated','swith']::TEXT[]),
('Venerate', '/ˈvɛnəɹeɪt/', 'verb', 'C1', 'To treat with great respect and deference.', '', ARRAY[]::TEXT[]),
('Veracious', '/vɛ.ˈɹeɪ.ʃəs/', 'adjective', 'C1', 'Truthful; speaking the truth.', 'The politician''''s statement was eventually proven to be veracious.', ARRAY[]::TEXT[]),
('Vilify', '/ˈvɪl.ɪ.faɪ/', 'verb', 'C1', 'To say defamatory things about someone or something; to speak ill of.', '', ARRAY['abuse','assail','criticize','decry','demonize']::TEXT[]),
('Vindicate', '', 'verb', 'C1', 'To clear of an accusation, suspicion or criticism.', 'to vindicate someone''''s honor', ARRAY[]::TEXT[]),
('Vociferous', '', 'adjective', 'C1', 'Making or characterized by a noisy outcry; clamorous.', '', ARRAY['noisy']::TEXT[]),
('Volubility', '', 'noun', 'C1', 'The state of being voluble', '', ARRAY[]::TEXT[]),
('Wanting', '/ˈwɒntɪŋ/', 'adjective', 'C1', 'That wants or desires.', '', ARRAY[]::TEXT[]),
('Winsome', '/ˈwɪn.s(ə)m/', 'adjective', 'C1', 'Charming, engaging, winning; inspiring approval and trust, especially if in an innocent manner.', '', ARRAY[]::TEXT[]),
('Abase', '/əˈbeɪs/', 'verb', 'C1', 'To lower, as in condition in life, office, rank, etc., so as to cause pain or hurt feelings; to degrade, to depress, to humble, to humiliate.', 'to abase the eye', ARRAY['downgrade','bring down','lower','reduce','degrade']::TEXT[]),
('Abash', '/əˈbæʃ/', 'verb', 'C1', 'To make ashamed; to embarrass; to destroy the self-possession of, as by exciting suddenly a consciousness of guilt, mistake, or inferiority; to disconcert; to discomfit.', '', ARRAY['bewilder','confound','confuse','daunt','discompose']::TEXT[]),
('Abate', '/əˈbeɪt/', 'verb', 'C1', '(obsolete outside law) To put an end to; to cause to cease.', 'to abate a nuisance', ARRAY['contract','cut short','decrease','diminish','lessen']::TEXT[]),
('Abbreviate', '/ə.ˈbɹiː.vi.eɪt/', 'verb', 'C1', 'To shorten by omitting parts or details.', '', ARRAY['abridge','compress','condense','contract','curtail']::TEXT[]),
('Abdicate', '/ˈæb.dɪˌkeɪt/', 'verb', 'C1', 'To disclaim and expel from the family, as a father his child; to disown; to disinherit.', 'Note: The word abdicate was held to mean, in the case of James II, to abandon without a formal surrender.', ARRAY['abandon','abjure','cast aside','cast off','cede']::TEXT[]),
('Abet', '/əˈbɛt/', 'verb', 'C1', 'To urge on, stimulate (a person to do) something desirable.', '', ARRAY['advocate','aid','assist','back','connive']::TEXT[]),
('Adjunct', '/ˈædʒ.ʌŋkt/', 'adjective', 'C1', 'Connected in a subordinate function.', '', ARRAY[]::TEXT[]),
('Ad-lib', '', 'verb', 'C1', 'To improvise all or part of a speech or other performance, especially in comedy.', '', ARRAY[]::TEXT[]),
('Adore', '/əˈdɔː/', 'verb', 'C1', 'To worship.', 'It is obvious to everyone that Gerry adores Heather.', ARRAY[]::TEXT[]),
('Adulate', '', 'verb', 'C1', 'To flatter effusively.', '', ARRAY[]::TEXT[]),
('Adulterate', '', 'adjective', 'C1', 'Tending to commit adultery.', '', ARRAY[]::TEXT[]),
('Adumbrate', '/ˈædʌmˌbɹeɪt/', 'verb', 'C1', 'To foreshadow vaguely.', '', ARRAY[]::TEXT[]),
('Adventitious', '/ˌæd.vənˈtɪʃ.əs/', 'adjective', 'C1', 'From an external source; not innate or inherent, foreign.', '', ARRAY['accidental','spontaneous','sporadic','extrinsic','acquired']::TEXT[]),
('Adversary', '/ædˈvɜː.sə.ɹi/', 'noun', 'C1', 'An opponent or rival.', 'He prepared to fight his adversary.', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
