INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Competition', 'competition_us.mp3', 'noun', 'B1', 'an event in which people compete with each other to find out who is the best at something', '', 'a design/an art/a talent competition', '', ARRAY[]::TEXT[]),
('Competitive', 'competitive_us.mp3', 'adjective', 'B1', 'used to describe a situation in which people or organizations compete against each other', '', 'competitive games/sports', '', ARRAY[]::TEXT[]),
('Competitor', 'competitor_us.mp3', 'noun', 'B1', 'a person who takes part in a competition', '', 'Over 200 competitors entered the race.', '', ARRAY[]::TEXT[]),
('Compile', 'compile_us.mp3', 'verb', 'B1', 'to produce a book, list, report, etc. by bringing together different items, articles, songs, etc.; to collect information in order to produce a book, list, etc.', '', 'We are trying to compile a list of suitable people for the job.', '', ARRAY[]::TEXT[]),
('Complain', 'complain_us.mp3', 'verb', 'B1', 'to say that you are annoyed, unhappy or not satisfied about somebody/something', '', 'She never complains, but she''s obviously exhausted.', '', ARRAY[]::TEXT[]),
('Complaint', 'complaint_us.mp3', 'noun', 'B1', 'a reason for not being satisfied; a statement that somebody makes saying that they are not satisfied', '', 'a formal complaint', '', ARRAY[]::TEXT[]),
('Complement', 'complement_us.mp3', 'verb', 'B1', 'to add to something in a way that improves it or makes it more attractive', '', 'The excellent menu is complemented by a good wine list.', '', ARRAY[]::TEXT[]),
('Complete', 'complete_us.mp3', 'adjective', 'B1', 'including all the parts, etc. that are necessary; whole', '', 'a complete list/sequence/picture/profile', '', ARRAY[]::TEXT[]),
('Complete', 'complete_us.mp3', 'verb', 'B1', 'to finish making or doing something', '', 'to complete a course/project', '', ARRAY[]::TEXT[]),
('Completely', 'completely_us.mp3', 'adverb', 'B1', 'in every way possible; in every part', '', 'It was completely different from how I had imagined it.', '', ARRAY[]::TEXT[]),
('Completion', 'completion_us.mp3', 'noun', 'B1', 'the act or process of finishing something; the state of being finished and complete', '', 'the completion of the new hospital building', '', ARRAY[]::TEXT[]),
('Complex', 'complex_us.mp3', 'adjective', 'B1', 'made of many different things or parts that are connected; difficult to understand', '', 'a complex problem/issue/process/system', '', ARRAY[]::TEXT[]),
('Complex', 'complex_us.mp3', 'noun', 'B1', 'a group of buildings of a similar type together in one place', '', 'a sports/leisure/shopping complex', '', ARRAY[]::TEXT[]),
('Complexity', 'complexity_us.mp3', 'noun', 'B1', 'the state of being formed of many parts; the state of being difficult to understand', '', 'the increasing complexity of modern telecommunication systems', '', ARRAY[]::TEXT[]),
('Compliance', 'compliance_us.mp3', 'noun', 'B1', 'the practice of obeying rules or requests made by people in authority', '', 'compliance (with something), procedures that must be followed to ensure full compliance with the law', '', ARRAY[]::TEXT[]),
('Complicated', 'complicated_us.mp3', 'adjective', 'B1', 'made of many different things or parts that are connected; difficult to understand', '', 'a complicated issue/process/system', '', ARRAY[]::TEXT[]),
('Complication', 'complication_us.mp3', 'noun', 'B1', 'a thing that makes a situation more complicated or difficult', '', 'The bad weather added a further complication to our journey.', '', ARRAY[]::TEXT[]),
('Comply', 'comply_us.mp3', 'verb', 'B1', 'to obey a rule, an order, etc.; to meet particular standards', '', 'They refused to comply with the UN resolution.', '', ARRAY[]::TEXT[]),
('Component', 'component_us.mp3', 'noun', 'B1', 'one of several parts of which something is made', '', 'the different organizations involved in the design of the various components', '', ARRAY[]::TEXT[]),
('Compose', 'compose_us.mp3', 'verb', 'B1', 'to write music', '', 'Mozart composed his last opera shortly before he died.', '', ARRAY[]::TEXT[]),
('Composer', 'composer_us.mp3', 'noun', 'B1', 'a person who writes music, especially classical music', '', 'Verdi was a prolific composer of operas.', '', ARRAY[]::TEXT[]),
('Composition', 'composition_us.mp3', 'noun', 'B1', 'the different parts that something is made of; the way in which the different parts are organized', '', 'the chemical composition of the soil', '', ARRAY[]::TEXT[]),
('Compound', 'compound_us.mp3', 'noun', 'B1', 'a thing consisting of two or more separate things combined together', '', 'compounds derived from rainforest plants', '', ARRAY[]::TEXT[]),
('Comprehensive', 'comprehensive_us.mp3', 'adjective', 'B1', 'including all, or almost all, the items, details, facts, information, etc., that may be involved', '', 'a comprehensive list of addresses', '', ARRAY[]::TEXT[]),
('Comprise', 'comprise_us.mp3', 'verb', 'B1', 'to have somebody/something as parts or members', '', 'comprise something, The collection comprises 327 paintings.', '', ARRAY[]::TEXT[]),
('Compromise', 'compromise_us.mp3', 'noun', 'B1', 'an agreement made between two people or groups in which each side gives up some of the things they want so that both sides are happy at the end', '', 'After lengthy talks the two sides finally reached a compromise.', '', ARRAY[]::TEXT[]),
('Compromise', 'compromise_us.mp3', 'verb', 'B1', 'to give up some of your demands in order to reach an agreement after disagreeing with somebody', '', 'Neither side is prepared to compromise.', '', ARRAY[]::TEXT[]),
('Compulsory', 'compulsory_us.mp3', 'adjective', 'B1', 'that must be done because of a law or a rule', '', 'English is a compulsory subject at this level.', '', ARRAY[]::TEXT[]),
('Compute', 'compute_us.mp3', 'verb', 'B1', 'to calculate something', '', 'The losses were computed at £5 million.', '', ARRAY[]::TEXT[]),
('Computer', 'computer_us.mp3', 'noun', 'B1', 'an electronic machine that can store, organize and find information, do processes with numbers and other data, and control other machines', '', 'a home computer', '', ARRAY[]::TEXT[]),
('Conceal', 'conceal_us.mp3', 'verb', 'B1', 'to hide somebody/something', '', 'conceal somebody/something, The paintings were concealed beneath a thick layer of plaster.', '', ARRAY[]::TEXT[]),
('Concede', 'concede_us.mp3', 'verb', 'B1', 'to admit that something is true, logical, etc. after first denying it or resisting it', '', '+ speech, ‘Not bad,’ she conceded grudgingly.', '', ARRAY[]::TEXT[]),
('Conceive', 'conceive_us.mp3', 'verb', 'B1', 'to form an idea, a plan, etc. in your mind', '', 'He conceived the idea of transforming the old power station into an arts centre.', '', ARRAY[]::TEXT[]),
('Concentrate', 'concentrate_us.mp3', 'verb', 'B1', 'to give all your attention to something and not think about anything else', '', 'I can''t concentrate with all that noise going on.', '', ARRAY[]::TEXT[]),
('Concentration', 'concentration_us.mp3', 'noun', 'B1', 'the ability to direct all your effort and attention on one thing, without thinking of other things', '', 'This book requires a great deal of concentration.', '', ARRAY[]::TEXT[]),
('Concept', 'concept_us.mp3', 'noun', 'B1', 'an idea or a principle that is connected with something abstract', '', 'concept of something, the concept of social class', '', ARRAY[]::TEXT[]),
('Conception', 'conception_us.mp3', 'noun', 'B1', 'an understanding or a belief of what something/somebody is or what something/somebody should be', '', 'conception of something, Marx’s conception of social justice', '', ARRAY[]::TEXT[]),
('Concern', 'concern_us.mp3', 'noun', 'B1', 'a feeling of worry, especially one that is shared by many people', '', 'concern about something/somebody, Villagers expressed concern about the level of traffic.', '', ARRAY[]::TEXT[]),
('Concern', 'concern_us.mp3', 'verb', 'B1', 'to affect somebody/something; to involve somebody/something', '', 'Don''t interfere in what doesn''t concern you.', '', ARRAY[]::TEXT[]),
('Concerned', 'concerned_us.mp3', 'adjective', 'B1', 'worried and feeling concern about something/somebody', '', 'Concerned citizens can have a huge impact.', '', ARRAY[]::TEXT[]),
('Concert', 'concert_us.mp3', 'noun', 'B1', 'a public performance of music', '', 'to attend/go to a concert', '', ARRAY[]::TEXT[]),
('Concession', 'concession_us.mp3', 'noun', 'B1', 'something that you allow or do, or allow somebody to have, in order to end an argument or to make a situation less difficult', '', 'The firm will be forced to make concessions if it wants to avoid a strike.', '', ARRAY[]::TEXT[]),
('Conclude', 'conclude_us.mp3', 'verb', 'B1', 'to decide or believe something as a result of what you have heard or seen', '', 'conclude something, It is too early for us to conclude anything.', '', ARRAY[]::TEXT[]),
('Conclusion', 'conclusion_us.mp3', 'noun', 'B1', 'something that you decide when you have thought about all the information connected with the situation', '', 'We can safely draw some conclusions from our discussion.', '', ARRAY[]::TEXT[]),
('Concrete', 'concrete_us.mp3', 'adjective', 'B1', 'made of concrete', '', 'a concrete floor', '', ARRAY[]::TEXT[]),
('Concrete', 'concrete_us.mp3', 'noun', 'B1', 'building material that is made by mixing together cement, sand, small stones and water', '', 'a slab of concrete', '', ARRAY[]::TEXT[]),
('Condemn', 'condemn_us.mp3', 'verb', 'B1', 'to say very strongly that you think something is bad, usually for moral reasons', '', 'condemn somebody/something, The government issued a statement condemning the killings.', '', ARRAY[]::TEXT[]),
('Condition', 'condition_us.mp3', 'noun', 'B1', 'the state that something is in', '', 'in… condition, to be in pristine/excellent/perfect condition', '', ARRAY[]::TEXT[]),
('Conduct', 'conduct_us.mp3', 'noun', 'B1', 'a person’s behaviour in a particular place or in a particular situation', '', 'The sport has a strict code of conduct.', '', ARRAY[]::TEXT[]),
('Conduct', 'conduct_us.mp3', 'verb', 'B1', 'to organize and/or do a particular activity', '', 'to conduct an experiment/inquiry/investigation/interview', '', ARRAY[]::TEXT[]),
('Confer', 'confer_us.mp3', 'verb', 'B1', 'to discuss something with somebody, in order to exchange opinions or get advice', '', 'He wanted to confer with his colleagues before reaching a decision.', '', ARRAY[]::TEXT[]),
('Conference', 'conference_us.mp3', 'noun', 'B1', 'a large official meeting, usually lasting for a few days, at which people with the same work or interests come together to discuss their views', '', 'The hotel is used for exhibitions, conferences and social events.', '', ARRAY[]::TEXT[]),
('Confess', 'confess_us.mp3', 'verb', 'B1', 'to admit, especially formally or to the police, that you have done something wrong or illegal', '', 'After hours of questioning, the suspect confessed.', '', ARRAY[]::TEXT[]),
('Confession', 'confession_us.mp3', 'noun', 'B1', 'a statement that a person makes, admitting that they are guilty of a crime; the act of making such a statement', '', 'After hours of questioning by police, she made a full confession.', '', ARRAY[]::TEXT[]),
('Confidence', 'confidence_us.mp3', 'noun', 'B1', 'the feeling that you can trust, believe in and be sure about the abilities or good qualities of somebody/something', '', 'The president''s actions hardly inspire confidence.', '', ARRAY[]::TEXT[]),
('Confident', 'confident_us.mp3', 'adjective', 'B1', 'feeling sure about your own ability to do things and be successful', '', 'She was in a relaxed, confident mood.', '', ARRAY[]::TEXT[]),
('Configuration', 'configuration_us.mp3', 'noun', 'B1', 'an arrangement of the parts of something or a group of things; the form or shape that this arrangement produces', '', 'configuration of something, The design is based on four configurations of squares.', '', ARRAY[]::TEXT[]),
('Confine', 'confine_us.mp3', 'verb', 'B1', 'to keep somebody/something inside the limits of a particular activity, subject, area, etc.', '', 'be confined to (doing) something, The work will not be confined to the Glasgow area.', '', ARRAY[]::TEXT[]),
('Confirm', 'confirm_us.mp3', 'verb', 'B1', 'to state or show that something is definitely true or correct, especially by providing evidence', '', 'confirm something, His guilty expression confirmed my suspicions.', '', ARRAY[]::TEXT[]),
('Confirmation', 'confirmation_us.mp3', 'noun', 'B1', 'a statement, letter, etc. that shows that something is true, correct or definite', '', 'I''m still waiting for confirmation of the test results.', '', ARRAY[]::TEXT[]),
('Conflict', 'conflict_us.mp3', 'noun', 'B1', 'a situation in which people, groups or countries disagree strongly or are involved in a serious argument', '', 'The violence was the result of political conflicts.', '', ARRAY[]::TEXT[]),
('Conflict', 'conflict_us.mp3', 'verb', 'B1', 'if two ideas, beliefs, stories, etc. conflict, it is not possible for them to exist together or for them both to be true', '', 'Reports conflicted on how much of the aid was reaching the famine victims.', '', ARRAY[]::TEXT[]),
('Confront', 'confront_us.mp3', 'verb', 'B1', 'to appear and need to be dealt with by somebody', '', 'What is to be done about the economic problems confronting the country?', '', ARRAY[]::TEXT[]),
('Confrontation', 'confrontation_us.mp3', 'noun', 'B1', 'a situation in which there is anger between people or groups who disagree because they have different opinions', '', 'confrontation (with somebody), She wanted to avoid another confrontation with her father.', '', ARRAY[]::TEXT[]),
('Confuse', 'confuse_us.mp3', 'verb', 'B1', 'to make somebody unable to think clearly or understand something', '', 'confuse somebody, These two sets of statistics are guaranteed to confuse the public.', '', ARRAY[]::TEXT[]),
('Confused', 'confused_us.mp3', 'adjective', 'B1', 'unable to think clearly or to understand what is happening or what somebody is saying', '', 'I''m confused—say all that again.', '', ARRAY[]::TEXT[]),
('Confusing', 'confusing_us.mp3', 'adjective', 'B1', 'difficult to understand; not clear', '', 'The instructions on the box are very confusing.', '', ARRAY[]::TEXT[]),
('Confusion', 'confusion_us.mp3', 'noun', 'B1', 'a state of not being certain about what is happening, what you should do, what something means, etc.', '', 'The announcement caused a lot of confusion.', '', ARRAY[]::TEXT[]),
('Congratulate', 'congratulate_us.mp3', 'verb', 'B1', 'to tell somebody that you are pleased about their success or achievements', '', 'I congratulated them all on their results.', '', ARRAY[]::TEXT[]),
('Congregation', 'congregation_us.mp3', 'noun', 'B1', 'a group of people who are gathered together in a church for a religious service, not including the priest and choir', '', 'The congregation stood to sing the hymn.', '', ARRAY[]::TEXT[]),
('Congressional', 'congressional_us.mp3', 'adjective', 'B1', 'related to or belonging to a congress or the Congress in the US', '', 'a congressional committee/bill', '', ARRAY[]::TEXT[]),
('Connect', 'connect_us.mp3', 'verb', 'B1', 'to join together two or more things; to be joined together', '', 'connect A and B, The towns are connected by train and bus services.', '', ARRAY[]::TEXT[]),
('Connected', 'connected_us.mp3', 'adjective', 'B1', '(of two or more things or people) having a link between them', '', 'We do not believe that the incidents are connected.', '', ARRAY[]::TEXT[]),
('Connection', 'connection_us.mp3', 'noun', 'B1', 'something that connects two facts, ideas, etc.', '', 'connection between A and B, Scientists have established a connection between cholesterol levels and heart disease.', '', ARRAY[]::TEXT[]),
('Conquer', 'conquer_us.mp3', 'verb', 'B1', 'to take control of a country or city and its people by force', '', 'The Normans conquered England in 1066.', '', ARRAY[]::TEXT[]),
('Conscience', 'conscience_us.mp3', 'noun', 'B1', 'the part of your mind that tells you whether your actions are right or wrong', '', 'to have a clear/guilty conscience (= to feel that you have done right/wrong)', '', ARRAY[]::TEXT[]),
('Conscious', 'conscious_us.mp3', 'adjective', 'B1', 'aware of something; noticing something', '', 'conscious of something, She''s very conscious of the problems involved.', '', ARRAY[]::TEXT[]),
('Consciousness', 'consciousness_us.mp3', 'noun', 'B1', 'the state of being able to use your senses and mental powers to understand what is happening', '', 'I can''t remember any more—I must have lost consciousness.', '', ARRAY[]::TEXT[]),
('Consecutive', 'consecutive_us.mp3', 'adjective', 'B1', 'following one after another in a continuous series', '', 'She was absent for nine consecutive days.', '', ARRAY[]::TEXT[]),
('Consensus', 'consensus_us.mp3', 'noun', 'B1', 'an opinion that all members of a group agree with', '', 'consensus (about/on something), She is skilled at achieving consensus on sensitive issues.', '', ARRAY[]::TEXT[]),
('Consent', 'consent_us.mp3', 'noun', 'B1', 'permission to do something, especially given by somebody in authority', '', 'The written consent of a parent is required.', '', ARRAY[]::TEXT[]),
('Consent', 'consent_us.mp3', 'verb', 'B1', 'to agree to something or give your permission for something', '', 'When she told them what she intended, they readily consented.', '', ARRAY[]::TEXT[]),
('Consequence', 'consequence_us.mp3', 'noun', 'B1', 'a result of something that has happened, especially an unpleasant result', '', 'Remember that actions have consequences.', '', ARRAY[]::TEXT[]),
('Consequently', 'consequently_us.mp3', 'adverb', 'B1', 'as a result; therefore', '', 'This poses a threat to agriculture and the food chain, and consequently to human health.', '', ARRAY[]::TEXT[]),
('Conservation', 'conservation_us.mp3', 'noun', 'B1', 'the protection of the natural environment', '', 'to be interested in wildlife conservation', '', ARRAY[]::TEXT[]),
('Conservative', 'conservative_us.mp3', 'adjective', 'B1', 'opposed to great or sudden social change; showing that you prefer traditional styles and values', '', 'the conservative views of his parents', '', ARRAY[]::TEXT[]),
('Conservative', 'conservative_us.mp3', 'noun', 'B1', 'a conservative person', '', 'social/religious conservatives', '', ARRAY[]::TEXT[]),
('Conserve', 'conserve_us.mp3', 'verb', 'B1', 'to protect something and prevent it from being changed or destroyed', '', 'new laws to conserve wildlife in the area', '', ARRAY[]::TEXT[]),
('Consider', 'consider_us.mp3', 'verb', 'B1', 'to think about something carefully, especially in order to make a decision', '', 'I''d like some time to consider.', '', ARRAY[]::TEXT[]),
('Considerable', 'considerable_us.mp3', 'adjective', 'B1', 'great in amount, size, importance, etc.', '', 'The project wasted a considerable amount of time and money.', '', ARRAY[]::TEXT[]),
('Considerably', 'considerably_us.mp3', 'adverb', 'B1', 'much; a lot', '', 'The need for sleep varies considerably from person to person.', '', ARRAY[]::TEXT[]),
('Consideration', 'consideration_us.mp3', 'noun', 'B1', 'the act of thinking carefully about something', '', 'An employer is legally bound to give due consideration to the request.', '', ARRAY[]::TEXT[]),
('Consistency', 'consistency_us.mp3', 'noun', 'B1', 'the quality of always behaving in the same way or of having the same opinions, standard, etc.; the quality of being consistent', '', 'She has played with great consistency all season.', '', ARRAY[]::TEXT[]),
('Consistent', 'consistent_us.mp3', 'adjective', 'B1', 'always behaving in the same way, or having the same opinions, standards, etc.', '', 'a consistent approach to the problem', '', ARRAY[]::TEXT[]),
('Consistently', 'consistently_us.mp3', 'adverb', 'B1', 'always the same', '', 'Her work has been of a consistently high standard.', '', ARRAY[]::TEXT[]),
('Consolidate', 'consolidate_us.mp3', 'verb', 'B1', 'to make a position of power or success stronger so that it is more likely to continue', '', 'With this new movie he has consolidated his position as the country''s leading director.', '', ARRAY[]::TEXT[]),
('Conspiracy', 'conspiracy_us.mp3', 'noun', 'B1', 'a secret plan by a group of people to do something harmful or illegal', '', 'conspiracy (to do something), a conspiracy to overthrow the government', '', ARRAY[]::TEXT[]),
('Constant', 'constant_us.mp3', 'adjective', 'B1', 'happening all the time or repeatedly', '', 'There were constant interruptions.', '', ARRAY[]::TEXT[]),
('Constantly', 'constantly_us.mp3', 'adverb', 'B1', 'all the time; repeatedly', '', 'Fashion is constantly changing.', '', ARRAY[]::TEXT[]),
('Constituency', 'constituency_us.mp3', 'noun', 'B1', 'a district that elects its own representative to parliament', '', 'Unemployment is high in her constituency.', '', ARRAY[]::TEXT[]),
('Constitute', 'constitute_us.mp3', 'verb', 'B1', 'to be considered to be something', '', 'Does such an activity constitute a criminal offence?', '', ARRAY[]::TEXT[]),
('Constitution', 'constitution_us.mp3', 'noun', 'B1', 'the system of laws and basic principles that a state, a country or an organization is governed by', '', 'your right to vote under the constitution', '', ARRAY[]::TEXT[]),
('Constraint', 'constraint_us.mp3', 'noun', 'B1', 'a thing that limits something, or limits your freedom to do something', '', 'constraints of time/money/space', '', ARRAY[]::TEXT[]),
('Construct', 'construct_us.mp3', 'verb', 'B1', 'to build or make something such as a road, building or machine', '', 'construct something, The building was constructed in 1993.', '', ARRAY[]::TEXT[]),
('Construction', 'construction_us.mp3', 'noun', 'B1', 'the process or method of building or making something, especially roads, buildings, bridges, etc.', '', 'Construction began this year and will take approximately 18 months.', '', ARRAY[]::TEXT[]),
('Consult', 'consult_us.mp3', 'verb', 'B1', 'to go to somebody for information or advice', '', 'consult somebody, If the pain continues, consult your doctor.', '', ARRAY[]::TEXT[]),
('Consultant', 'consultant_us.mp3', 'noun', 'B1', 'a person who knows a lot about a particular subject and is employed to give advice about it to other people', '', 'a technology/design consultant', '', ARRAY[]::TEXT[]),
('Consultation', 'consultation_us.mp3', 'noun', 'B1', 'the act of discussing something with somebody or with a group of people before making a decision about it', '', 'a consultation document/paper/period/process', '', ARRAY[]::TEXT[]),
('Consume', 'consume_us.mp3', 'verb', 'B1', 'to use something, especially fuel, energy or time', '', 'The electricity industry consumes large amounts of fossil fuels.', '', ARRAY[]::TEXT[]),
('Consumer', 'consumer_us.mp3', 'noun', 'B1', 'a person who buys goods or uses services', '', 'consumer spending/demand', '', ARRAY[]::TEXT[]),
('Consumption', 'consumption_us.mp3', 'noun', 'B1', 'the act of using energy, food or materials; the amount used', '', 'the production of fuel for domestic consumption (= to be used in the country where it is produced)', '', ARRAY[]::TEXT[]),
('Contact', 'contact_us.mp3', 'noun', 'B1', 'the act of communicating with somebody, especially regularly', '', 'contact with somebody, I don''t have much contact with my uncle.', '', ARRAY[]::TEXT[]),
('Contact', 'contact_us.mp3', 'verb', 'B1', 'to communicate with somebody, for example by phone, letter or email', '', 'I''ve been trying to contact you all day.', '', ARRAY[]::TEXT[]),
('Contain', 'contain_us.mp3', 'verb', 'B1', 'if something contains something else, it has that thing inside it or as part of it', '', 'This drink doesn''t contain any alcohol.', '', ARRAY[]::TEXT[]),
('Container', 'container_us.mp3', 'noun', 'B1', 'a box, bottle, etc. in which something can be stored or transported', '', 'a plastic container', '', ARRAY[]::TEXT[]),
('Contemplate', 'contemplate_us.mp3', 'verb', 'B1', 'to think about whether you should do something, or how you should do something', '', 'contemplate something, You''re too young to be contemplating retirement.', '', ARRAY[]::TEXT[]),
('Contemporary', 'contemporary_us.mp3', 'adjective', 'B1', 'belonging to the same time', '', 'We have no contemporary account of the battle (= written near the time that it happened).', '', ARRAY[]::TEXT[]),
('Contempt', 'contempt_us.mp3', 'noun', 'B1', 'the feeling that somebody/something is without value and deserves no respect at all', '', 'with contempt, She looked at him with contempt.', '', ARRAY[]::TEXT[]),
('Contend', 'contend_us.mp3', 'verb', 'B1', 'to say that something is true, especially in an argument', '', 'I would contend that the minister''s thinking is flawed on this point.', '', ARRAY[]::TEXT[]),
('Contender', 'contender_us.mp3', 'noun', 'B1', 'a person or team with a chance of winning a competition', '', 'contender (for something), a contender for a gold medal in the Olympics', '', ARRAY[]::TEXT[]),
('Content', 'content_us.mp3', 'adjective', 'B1', 'happy and satisfied with what you have', '', 'He seemed more content, less bitter.', '', ARRAY[]::TEXT[]),
('Content', 'content_us.mp3', 'noun', 'B1', 'the things that are contained in something', '', 'He tipped the contents of the bag onto the table.', '', ARRAY[]::TEXT[]),
('Contention', 'contention_us.mp3', 'noun', 'B1', 'anger between people who disagree', '', 'One area of contention is the availability of nursery care.', '', ARRAY[]::TEXT[]),
('Contest', 'contest_us.mp3', 'noun', 'B1', 'a competition in which people try to win something', '', 'to hold a singing/talent contest', '', ARRAY[]::TEXT[]),
('Contest', 'contest_us.mp3', 'verb', 'B1', 'to take part in a competition, election, etc. and try to win it', '', 'Three candidates contested the leadership.', '', ARRAY[]::TEXT[]),
('Context', 'context_us.mp3', 'noun', 'B1', 'the situation in which something happens and that helps you to understand it', '', 'Such databases are being used in a wide range of contexts.', '', ARRAY[]::TEXT[]),
('Continent', 'continent_us.mp3', 'noun', 'B1', 'one of the large land masses of the earth such as Europe, Asia or Africa', '', 'the continent of Africa', '', ARRAY[]::TEXT[]),
('Continually', 'continually_us.mp3', 'adverb', 'B1', 'in a way that is repeated many times so that it is annoying', '', 'They argue continually about money.', '', ARRAY[]::TEXT[]),
('Continue', 'continue_us.mp3', 'verb', 'B1', 'to keep existing or happening without stopping', '', 'If the current trend continues, that number will increase 165 per cent by 2050.', '', ARRAY[]::TEXT[]),
('Continuous', 'continuous_us.mp3', 'adjective', 'B1', 'happening or existing for a period of time without being interrupted', '', 'Recovery after the accident will be a continuous process that may take several months.', '', ARRAY[]::TEXT[]),
('Contract', 'contract_us.mp3', 'noun', 'B1', 'an official written agreement', '', 'All employees have a written contract of employment.', '', ARRAY[]::TEXT[]),
('Contract', 'contract_us.mp3', 'verb', 'B1', 'to become less or smaller; to make something become less or smaller', '', 'Glass contracts as it cools.', '', ARRAY[]::TEXT[]),
('Contractor', 'contractor_us.mp3', 'noun', 'B1', 'a person or company that has a contract to do work or provide goods or services for another company', '', 'a building/roofing/electrical contractor', '', ARRAY[]::TEXT[]),
('Contradiction', 'contradiction_us.mp3', 'noun', 'B1', 'a lack of agreement between facts, opinions, actions, etc.', '', 'contradiction (between A and B), There is a contradiction between the two sets of figures.', '', ARRAY[]::TEXT[]),
('Contrary', 'contrary_us.mp3', 'noun', 'B1', 'the opposite fact, event or situation', '', 'In the end the contrary was proved true: he was innocent and she was guilty.', '', ARRAY[]::TEXT[]),
('Contrast', 'contrast_us.mp3', 'noun', 'B1', 'a difference between two or more people or things that you can see clearly when they are compared or put close together; the fact of comparing two or more things in order to show the differences between them', '', 'The two cities make an interesting contrast.', '', ARRAY[]::TEXT[]),
('Contrast', 'contrast_us.mp3', 'verb', 'B1', 'to compare two things in order to show the differences between them', '', 'contrast A and B, The poem contrasts youth and age.', '', ARRAY[]::TEXT[]),
('Contribute', 'contribute_us.mp3', 'verb', 'B1', 'to give something, especially money or goods, to help achieve or provide something', '', 'Do you wish to contribute?', '', ARRAY[]::TEXT[]),
('Contribution', 'contribution_us.mp3', 'noun', 'B1', 'a gift or payment that is made to a person or an organization in order to help pay for something', '', 'All contributions will be gratefully received.', '', ARRAY[]::TEXT[]),
('Contributor', 'contributor_us.mp3', 'noun', 'B1', 'a person who writes articles for a magazine, book or website, or who talks on a radio or television programme or at a meeting', '', 'a regular contributor to this magazine', '', ARRAY[]::TEXT[]),
('Control', 'control_us.mp3', 'noun', 'B1', 'the power to make decisions about how a country, an area, an organization, etc. is run', '', 'control of somebody/something, The party expects to gain control of the council in the next election.', '', ARRAY[]::TEXT[]),
('Control', 'control_us.mp3', 'verb', 'B1', 'to have power over a person, company, country, etc. so that you are able to decide what they must do or how it is run', '', 'By the age of 21 he controlled the company.', '', ARRAY[]::TEXT[]),
('Controversial', 'controversial_us.mp3', 'adjective', 'B1', 'causing a lot of angry public discussion and disagreement', '', 'a highly controversial topic', '', ARRAY[]::TEXT[]),
('Controversy', 'controversy_us.mp3', 'noun', 'B1', 'public discussion and argument about something that many people strongly disagree about, think is bad, or are shocked by', '', 'to arouse/cause controversy', '', ARRAY[]::TEXT[]),
('Convenience', 'convenience_us.mp3', 'noun', 'B1', 'the quality of being useful, easy or suitable for somebody', '', 'We have provided seats for the convenience of our customers.', '', ARRAY[]::TEXT[]),
('Convenient', 'convenient_us.mp3', 'adjective', 'B1', 'useful, easy or quick to do; not causing problems', '', 'Fruit is a convenient source of vitamins and energy.', '', ARRAY[]::TEXT[]),
('Convention', 'convention_us.mp3', 'noun', 'B1', 'the way in which something is done that most people in a society expect and consider to be polite or the right way to do it', '', 'the rigid social conventions of Victorian Britain', '', ARRAY[]::TEXT[]),
('Conventional', 'conventional_us.mp3', 'adjective', 'B1', 'tending to follow what is done or considered acceptable by society in general; normal and ordinary, and perhaps not very interesting', '', 'conventional behaviour/morality', '', ARRAY[]::TEXT[]),
('Conversation', 'conversation_us.mp3', 'noun', 'B1', 'an informal talk involving a small group of people or only two; the activity of talking in this way', '', 'a phone conversation', '', ARRAY[]::TEXT[]),
('Conversion', 'conversion_us.mp3', 'noun', 'B1', 'the act or process of changing something from one form, use or system to another', '', 'Their main business is the conversion of farm buildings into family homes.', '', ARRAY[]::TEXT[]),
('Convert', 'convert_us.mp3', 'verb', 'B1', 'to change or make something change from one form, purpose, system, etc. to another', '', 'convert something, They took just nine months to convert the building.', '', ARRAY[]::TEXT[]),
('Convey', 'convey_us.mp3', 'verb', 'B1', 'to make ideas, feelings, etc. known to somebody', '', 'convey something, Colours like red convey a sense of energy and strength.', '', ARRAY[]::TEXT[]),
('Convict', 'convict_us.mp3', 'verb', 'B1', 'to decide and state officially in court that somebody is guilty of a crime', '', 'be convicted (of something), He was convicted of fraud.', '', ARRAY[]::TEXT[]),
('Conviction', 'conviction_us.mp3', 'noun', 'B1', 'the act of finding somebody guilty of a crime in court; the fact of having been found guilty', '', 'He plans to appeal against his conviction.', '', ARRAY[]::TEXT[]),
('Convince', 'convince_us.mp3', 'verb', 'B1', 'to make somebody/yourself believe that something is true', '', 'convince somebody/yourself, Are the prime minister''s assurances enough to convince the public?', '', ARRAY[]::TEXT[]),
('Convinced', 'convinced_us.mp3', 'adjective', 'B1', 'completely sure about something', '', 'Sam nodded but he didn''t look convinced.', '', ARRAY[]::TEXT[]),
('Convincing', 'convincing_us.mp3', 'adjective', 'B1', 'that makes somebody believe that something is true', '', 'a convincing argument/explanation/case', '', ARRAY[]::TEXT[]),
('Cook', 'cook_us.mp3', 'noun', 'B1', 'a person who cooks food or whose job is cooking', '', 'John is a very good cook (= he cooks well).', '', ARRAY[]::TEXT[]),
('Cook', 'cook_us.mp3', 'verb', 'B1', 'to prepare food by heating it, for example by boiling, baking or frying it', '', 'Where did you learn to cook?', '', ARRAY[]::TEXT[]),
('Cooker', 'cooker_us.mp3', 'noun', 'B1', 'a large piece of equipment for cooking food, containing an oven and gas or electric rings on top', '', 'a gas cooker', '', ARRAY[]::TEXT[]),
('Cooking', 'cooking_us.mp3', 'noun', 'B1', 'the process of preparing food by heating it', '', 'My husband does all the cooking.', '', ARRAY[]::TEXT[]),
('Cool', 'cool_us.mp3', 'adjective', 'B1', 'fairly cold; not hot or warm', '', 'cool air/water', '', ARRAY[]::TEXT[]),
('Cool', 'cool_us.mp3', 'verb', 'B1', 'to become cool or cooler; to make somebody/something become cool or cooler', '', 'Glass contracts as it cools.', '', ARRAY[]::TEXT[]),
('Cooperate', 'cooperate_us.mp3', 'verb', 'B1', 'to work together with somebody else in order to achieve something', '', 'The two groups agreed to cooperate with each other.', '', ARRAY[]::TEXT[]),
('Cooperative', 'cooperative_us.mp3', 'adjective', 'B1', 'involving doing something together or working together with others towards a shared aim', '', 'Cooperative activity is essential to effective community work.', '', ARRAY[]::TEXT[]),
('Coordinate', 'coordinate_us.mp3', 'verb', 'B1', 'to organize the different parts of an activity and the people involved in it so that it works well', '', 'coordinate something, They appointed a new manager to coordinate the work of the team.', '', ARRAY[]::TEXT[]),
('Coordination', 'coordination_us.mp3', 'noun', 'B1', 'the act of making parts of something, groups of people, etc. work together in an efficient and organized way', '', 'The aim was to improve the coordination of services.', '', ARRAY[]::TEXT[]),
('Coordinator', 'coordinator_us.mp3', 'noun', 'B1', 'a person who organizes the different parts of an activity and the people involved in it so that it works well', '', 'The campaign needs an effective coordinator.', '', ARRAY[]::TEXT[]),
('Cop', 'cop_us.mp3', 'noun', 'B1', 'a police officer', '', 'Somebody call the cops!', '', ARRAY[]::TEXT[]),
('Cope', 'cope_us.mp3', 'verb', 'B1', 'to deal successfully with something difficult', '', 'I got to the stage where I wasn''t coping any more.', '', ARRAY[]::TEXT[]),
('Copper', 'copper_us.mp3', 'noun', 'B1', 'a chemical element. Copper is a soft red-brown metal used for making electric wires, pipes and coins.', '', 'a copper mine', '', ARRAY[]::TEXT[]),
('Copy', 'copy_us.mp3', 'noun', 'B1', 'a thing that is made to be the same as something else, especially a document or a work of art', '', 'The thieves replaced the original painting with a copy.', '', ARRAY[]::TEXT[]),
('Copy', 'copy_us.mp3', 'verb', 'B1', 'to make something that is exactly like something else', '', 'copy something, He taught himself by copying paintings in the Louvre.', '', ARRAY[]::TEXT[]),
('Copyright', 'copyright_us.mp3', 'noun', 'B1', 'if a person or an organization holds the copyright on a piece of writing, music, etc., they are the only people who have the legal right to publish, broadcast, perform it, etc., and other people must ask their permission to use it or any part of it', '', 'Copyright expires seventy years after the death of the author.', '', ARRAY[]::TEXT[]),
('Core', 'core_us.mp3', 'adjective', 'B1', 'most important; main or essential', '', 'core subjects (= subjects that all the students have to study) such as English and mathematics', '', ARRAY[]::TEXT[]),
('Core', 'core_us.mp3', 'noun', 'B1', 'the most important or central part of something', '', 'This report goes to the core of the argument.', '', ARRAY[]::TEXT[]),
('Corner', 'corner_us.mp3', 'noun', 'B1', 'a part of something where two or more sides, lines or edges join', '', 'the four corners of a square', '', ARRAY[]::TEXT[]),
('Corporate', 'corporate_us.mp3', 'adjective', 'B1', 'connected with a large business company', '', 'corporate finance/profits/tax', '', ARRAY[]::TEXT[]),
('Corporation', 'corporation_us.mp3', 'noun', 'B1', 'a large business company', '', 'multinational corporations', '', ARRAY[]::TEXT[]),
('Correct', 'correct_us.mp3', 'adjective', 'B1', 'accurate or true, without any mistakes', '', 'Do you have the correct time?', '', ARRAY[]::TEXT[]),
('Correct', 'correct_us.mp3', 'verb', 'B1', 'to make something right or accurate, for example by changing it or removing mistakes', '', 'correct something, to correct an error', '', ARRAY[]::TEXT[]),
('Correction', 'correction_us.mp3', 'noun', 'B1', 'a change that makes something more accurate than it was before', '', 'I''ve made a few small corrections to your report.', '', ARRAY[]::TEXT[]),
('Correctly', 'correctly_us.mp3', 'adverb', 'B1', 'in a way that is accurate or true, without any mistakes', '', 'Have you spelled it correctly?', '', ARRAY[]::TEXT[]),
('Correlate', 'correlate_us.mp3', 'verb', 'B1', 'if two or more facts, figures, etc. correlate or if a fact, figure, etc. correlates with another, the facts are closely connected and affect or depend on each other', '', 'The figures do not seem to correlate.', '', ARRAY[]::TEXT[]),
('Correlation', 'correlation_us.mp3', 'noun', 'B1', 'a connection between two things in which one thing changes as the other does', '', 'correlation between A and B, There is a direct correlation between exposure to sun and skin cancer.', '', ARRAY[]::TEXT[]),
('Correspond', 'correspond_us.mp3', 'verb', 'B1', 'to be the same as or match something', '', 'Your account and hers do not correspond.', '', ARRAY[]::TEXT[]),
('Correspondence', 'correspondence_us.mp3', 'noun', 'B1', 'the letters, emails, etc. a person sends and receives', '', 'personal/private correspondence', '', ARRAY[]::TEXT[]),
('Correspondent', 'correspondent_us.mp3', 'noun', 'B1', 'a person who reports news from a particular country or on a particular subject for a newspaper or a television or radio station', '', 'She''s the BBC''s political correspondent.', '', ARRAY[]::TEXT[]),
('Corresponding', 'corresponding_us.mp3', 'adjective', 'B1', 'matching or connected with something that you have just mentioned', '', 'A change in the money supply brings a corresponding change in expenditure.', '', ARRAY[]::TEXT[]),
('Corridor', 'corridor_us.mp3', 'noun', 'B1', 'a long narrow passage in a building, with doors that open into rooms on either side', '', 'His room is along the corridor.', '', ARRAY[]::TEXT[]),
('Corrupt', 'corrupt_us.mp3', 'adjective', 'B1', 'willing to use their power to do dishonest or illegal things in return for money or to get an advantage', '', 'It was seen as the only way to overthrow a corrupt regime.', '', ARRAY[]::TEXT[]),
('Corruption', 'corruption_us.mp3', 'noun', 'B1', 'dishonest or illegal behaviour, especially of people in authority', '', 'allegations of bribery and corruption', '', ARRAY[]::TEXT[]),
('Cost', 'cost_us.mp3', 'noun', 'B1', 'the amount of money that you need in order to buy, make or do something', '', 'cost of something, the high/low cost of housing', '', ARRAY[]::TEXT[]),
('Cost', 'cost_us.mp3', 'verb', 'B1', 'if something costs a particular amount of money, you need to pay that amount in order to buy, make or do it', '', 'cost something, How much did it cost?', '', ARRAY[]::TEXT[]),
('Costly', 'costly_us.mp3', 'adjective', 'B1', 'costing a lot of money, especially more than you want to pay', '', 'Buying new furniture may prove too costly.', '', ARRAY[]::TEXT[]),
('Costume', 'costume_us.mp3', 'noun', 'B1', 'the clothes worn by people from a particular place or during a particular historical period', '', 'an exhibition of Victorian costumes', '', ARRAY[]::TEXT[]),
('Cottage', 'cottage_us.mp3', 'noun', 'B1', 'a small house, especially in the country', '', 'a thatched cottage', '', ARRAY[]::TEXT[]),
('Cotton', 'cotton_us.mp3', 'noun', 'B1', 'a plant grown in warm countries for the soft white hairs around its seeds that are used to make cloth and thread', '', 'From the age of six she worked in the fields, picking cotton.', '', ARRAY[]::TEXT[]),
('Could', 'could_us.mp3', 'modal verb', 'B1', 'used as the past tense of ‘can’', '', 'She said that she couldn''t come.', '', ARRAY[]::TEXT[]),
('Council', 'council_us.mp3', 'noun', 'B1', 'a group of people who are elected to govern an area such as a city or county', '', 'a town council', '', ARRAY[]::TEXT[]),
('Councillor', 'councillor_us.mp3', 'noun', 'B1', 'a member of a city or county council', '', 'Councillor Ann Jones', '', ARRAY[]::TEXT[]),
('Counselling', 'counselling_us.mp3', 'noun', 'B1', 'professional advice about a problem', '', 'The couple decided to go for relationship counselling.', '', ARRAY[]::TEXT[]),
('Counsellor', 'counsellor_us.mp3', 'noun', 'B1', 'a person who has been trained to advise people with problems, especially personal problems', '', 'I went to see a debt counsellor and she agreed to come to the bank with me.', '', ARRAY[]::TEXT[]),
('Count', 'count_us.mp3', 'noun', 'B1', 'an act of counting to find the total number of somebody/something', '', 'If the election result is close, there will be a second count.', '', ARRAY[]::TEXT[]),
('Count', 'count_us.mp3', 'verb', 'B1', 'to say numbers in the correct order', '', 'Billy can''t count yet.', '', ARRAY[]::TEXT[]),
('Counter', 'counter_us.mp3', 'noun', 'B1', 'a long flat surface over which goods are sold or business is done in a shop, bank, etc.', '', 'behind the counter, I asked the woman behind the counter if they had any postcards.', '', ARRAY[]::TEXT[]),
('Counter', 'counter_us.mp3', 'verb', 'B1', 'to reply to somebody by trying to prove that what they said is not true', '', 'counter somebody/something, Such arguments are not easily countered.', '', ARRAY[]::TEXT[]),
('Counterpart', 'counterpart_us.mp3', 'noun', 'B1', 'a person or thing that has the same position or function as somebody/something else in a different place or situation', '', 'The Foreign Minister held talks with his Chinese counterpart.', '', ARRAY[]::TEXT[]),
('Countless', 'countless_us.mp3', 'adjective', 'B1', 'very many; too many to be counted or mentioned', '', 'I''ve warned her countless times.', '', ARRAY[]::TEXT[]),
('Country', 'country_us.mp3', 'noun', 'B1', 'an area of land that has or used to have its own government and laws', '', 'European countries', '', ARRAY[]::TEXT[]),
('Countryside', 'countryside_us.mp3', 'noun', 'B1', 'land outside towns and cities, with fields, woods, etc.', '', 'The surrounding countryside is windswept and rocky.', '', ARRAY[]::TEXT[]),
('County', 'county_us.mp3', 'noun', 'B1', 'one of a number of areas that some countries are divided into, each with its own local government', '', 'rural counties west of the Mississippi', '', ARRAY[]::TEXT[]),
('Coup', 'coup_us.mp3', 'noun', 'B1', 'a sudden change of government that is illegal and often violent', '', 'He seized power in a military coup in 2008.', '', ARRAY[]::TEXT[]),
('Couple', 'couple_us.mp3', 'noun', 'B1', 'two people or things', '', 'I saw a couple of men get out.', '', ARRAY[]::TEXT[]),
('Courage', 'courage_us.mp3', 'noun', 'B1', 'the ability to do something dangerous, or to face pain or opposition, without showing fear', '', 'He showed great courage and determination.', '', ARRAY[]::TEXT[]),
('Course', 'course_us.mp3', 'noun', 'B1', 'a series of lessons or lectures on a particular subject', '', 'a French/chemistry course', '', ARRAY[]::TEXT[]),
('Court', 'court_us.mp3', 'noun', 'B1', 'the place where legal trials take place and where crimes, etc. are judged', '', 'the civil/criminal courts', '', ARRAY[]::TEXT[]),
('Courtesy', 'courtesy_us.mp3', 'noun', 'B1', 'polite behaviour that shows respect for other people', '', 'I was treated with the utmost courtesy by the staff.', '', ARRAY[]::TEXT[]),
('Cousin', 'cousin_us.mp3', 'noun', 'B1', 'a child of your aunt or uncle', '', 'She''s my cousin.', '', ARRAY[]::TEXT[]),
('Cover', 'cover_us.mp3', 'noun', 'B1', 'a thing that is put over or on another thing, usually to protect it or to decorate it', '', 'Brighten up your room with some colourful cushion covers.', '', ARRAY[]::TEXT[]),
('Cover', 'cover_us.mp3', 'verb', 'B1', 'to place something over or in front of something in order to hide, protect or decorate it', '', 'cover something with something, Cover the chicken loosely with foil.', '', ARRAY[]::TEXT[]),
('Coverage', 'coverage_us.mp3', 'noun', 'B1', 'the reporting of news and sport in the media', '', 'media/newspaper/press coverage', '', ARRAY[]::TEXT[]),
('Covered', 'covered_us.mp3', 'adjective', 'B1', 'having a layer or amount of something on it', '', 'His face was covered in blood.', '', ARRAY[]::TEXT[]),
('Cow', 'cow_us.mp3', 'noun', 'B1', 'a large animal kept on farms to produce milk or beef', '', 'to milk a cow', '', ARRAY[]::TEXT[]),
('Crack', 'crack_us.mp3', 'noun', 'B1', 'a line on the surface of something where it has broken but not split into separate parts', '', 'This cup has a crack in it.', '', ARRAY[]::TEXT[]),
('Crack', 'crack_us.mp3', 'verb', 'B1', 'to break without dividing into separate parts; to break something in this way', '', 'The ice cracked as I stepped onto it.', '', ARRAY[]::TEXT[]),
('Craft', 'craft_us.mp3', 'noun', 'B1', 'an activity involving a special skill at making things with your hands', '', 'traditional crafts like basket-weaving', '', ARRAY[]::TEXT[]),
('Craft', 'craft_us.mp3', 'verb', 'B1', 'to make something using special skills, especially with your hands', '', 'be crafted (from something), All the furniture is crafted from natural materials.', '', ARRAY[]::TEXT[]),
('Crash', 'crash_us.mp3', 'noun', 'B1', 'an accident in which a vehicle hits something, for example another vehicle, usually causing damage and often injuring or killing the passengers', '', 'a car/plane crash', '', ARRAY[]::TEXT[]),
('Crash', 'crash_us.mp3', 'verb', 'B1', 'if a vehicle crashes or the driver crashes it, it hits an object or another vehicle, causing damage', '', 'I was terrified that the plane would crash.', '', ARRAY[]::TEXT[]),
('Crawl', 'crawl_us.mp3', 'verb', 'B1', 'to move forward on your hands and knees or with your body close to the ground', '', 'Our baby is just starting to crawl.', '', ARRAY[]::TEXT[]),
('Crazy', 'crazy_us.mp3', 'adjective', 'B1', 'not sensible; stupid', '', 'Are you crazy? We could get killed doing that.', '', ARRAY[]::TEXT[]),
('Cream', 'cream_us.mp3', 'adjective', 'B1', 'between yellow and white in colour', '', 'a cream linen suit', '', ARRAY[]::TEXT[]),
('Cream', 'cream_us.mp3', 'noun', 'B1', 'the thick white or pale yellow fatty liquid that rises to the top of milk, used in cooking or as a type of sauce to put on fruit, etc.', '', 'We had strawberries and cream for dessert.', '', ARRAY[]::TEXT[]),
('Create', 'create_us.mp3', 'verb', 'B1', 'to make something happen or exist', '', 'Scientists disagree about how the universe was created.', '', ARRAY[]::TEXT[]),
('Creation', 'creation_us.mp3', 'noun', 'B1', 'the act or process of making something that is new, or of causing something to exist that did not exist before', '', 'Job creation needs to be the top priority.', '', ARRAY[]::TEXT[]),
('Creative', 'creative_us.mp3', 'adjective', 'B1', 'involving the use of skill and the imagination to produce something new or a work of art', '', 'a course on creative writing (= writing stories, plays and poems)', '', ARRAY[]::TEXT[]),
('Creativity', 'creativity_us.mp3', 'noun', 'B1', 'the use of skill and imagination to produce something new or to produce art', '', 'Creativity and originality are more important than technical skill.', '', ARRAY[]::TEXT[]),
('Creator', 'creator_us.mp3', 'noun', 'B1', 'a person who has made or invented a particular thing', '', 'Walt Disney, the creator of Mickey Mouse', '', ARRAY[]::TEXT[]),
('Creature', 'creature_us.mp3', 'noun', 'B1', 'a living thing, real or imaginary, that can move around, such as an animal', '', 'respect for all living creatures', '', ARRAY[]::TEXT[]),
('Credibility', 'credibility_us.mp3', 'noun', 'B1', 'the quality that somebody/something has that makes people believe or trust them', '', 'to gain/lack/lose credibility', '', ARRAY[]::TEXT[]),
('Credible', 'credible_us.mp3', 'adjective', 'B1', 'that can be believed or trusted', '', 'a credible explanation/witness', '', ARRAY[]::TEXT[]),
('Credit', 'credit_us.mp3', 'noun', 'B1', 'an arrangement that you make, with a shop for example, to pay later for something you buy', '', 'to get credit', '', ARRAY[]::TEXT[]),
('Credit', 'credit_us.mp3', 'verb', 'B1', 'to add an amount of money to somebody’s bank account', '', 'credit something, They credited my account two days later.', '', ARRAY[]::TEXT[]),
('Creep', 'creep_us.mp3', 'verb', 'B1', 'to move slowly, quietly and carefully, because you do not want to be seen or heard', '', 'I crept up the stairs, trying not to wake my parents.', '', ARRAY[]::TEXT[]),
('Crew', 'crew_us.mp3', 'noun', 'B1', 'all the people working on a ship, plane, etc.', '', 'crew members', '', ARRAY[]::TEXT[]),
('Crime', 'crime_us.mp3', 'noun', 'B1', 'activities that involve breaking the law', '', 'This month''s figures show an increase in violent crime.', '', ARRAY[]::TEXT[]),
('Criminal', 'criminal_us.mp3', 'adjective', 'B1', 'connected with or involving crime', '', 'criminal offences/activities', '', ARRAY[]::TEXT[]),
('Criminal', 'criminal_us.mp3', 'noun', 'B1', 'a person who commits a crime', '', 'a convicted criminal', '', ARRAY[]::TEXT[]),
('Crisis', 'crisis_us.mp3', 'noun', 'B1', 'a time of great danger, difficulty or doubt when problems must be solved or important decisions must be made', '', 'an economic/a financial crisis', '', ARRAY[]::TEXT[]),
('Criterion', 'criterion_us.mp3', 'noun', 'B1', 'a standard or principle by which something is judged, or with the help of which a decision is made', '', 'The main criterion is value for money.', '', ARRAY[]::TEXT[]),
('Critic', 'critic_us.mp3', 'noun', 'B1', 'a person who expresses opinions about the good and bad qualities of books, music, etc.', '', 'a film/an art/a music critic', '', ARRAY[]::TEXT[]),
('Critical', 'critical_us.mp3', 'adjective', 'B1', 'saying what you think is bad about somebody/something', '', 'You should just ignore any critical comments.', '', ARRAY[]::TEXT[]),
('Critically', 'critically_us.mp3', 'adverb', 'B1', 'in a way that says what you think is bad about somebody/something', '', 'She spoke critically of her father.', '', ARRAY[]::TEXT[]),
('Criticism', 'criticism_us.mp3', 'noun', 'B1', 'the act of expressing disapproval of somebody/something and opinions about their faults or bad qualities; a statement showing this disapproval', '', 'to draw/face/receive criticism', '', ARRAY[]::TEXT[]),
('Criticize', 'criticize_us.mp3', 'verb', 'B1', 'to say that you think somebody/something is bad; to say what you do not like or think is wrong about somebody/something', '', 'All you ever do is criticize!', '', ARRAY[]::TEXT[]),
('Critique', 'critique_us.mp3', 'noun', 'B1', 'a piece of written criticism of a set of ideas, a work of art, etc.', '', 'She wrote a feminist critique of Freud''s theories.', '', ARRAY[]::TEXT[]),
('Crop', 'crop_us.mp3', 'noun', 'B1', 'a plant that is grown in large quantities, especially as food', '', 'Sugar is an important crop on the island.', '', ARRAY[]::TEXT[]),
('Cross', 'cross_us.mp3', 'noun', 'B1', 'a mark or an object formed by two lines crossing each other (X or +); the mark (X) is often used on paper to show something', '', 'I''ve put a cross on the map to show where the hotel is.', '', ARRAY[]::TEXT[]),
('Cross', 'cross_us.mp3', 'verb', 'B1', 'to go across; to pass or stretch from one side to the other', '', 'As soon as traffic slowed down enough to safely cross, I started walking.', '', ARRAY[]::TEXT[]),
('Crowd', 'crowd_us.mp3', 'noun', 'B1', 'a large number of people gathered together in a public place, for example in the streets or at a sports game', '', 'He pushed his way through the crowd.', '', ARRAY[]::TEXT[]),
('Crowded', 'crowded_us.mp3', 'adjective', 'B1', 'having a lot of people or too many people', '', 'We made our way through the crowded streets.', '', ARRAY[]::TEXT[]),
('Crown', 'crown_us.mp3', 'noun', 'B1', 'an object in the shape of a circle, usually made of gold and precious stones, that a king or queen wears on his or her head on official occasions', '', 'The crown was placed upon the new monarch''s head.', '', ARRAY[]::TEXT[]),
('Crucial', 'crucial_us.mp3', 'adjective', 'B1', 'extremely important, because it will affect other things', '', 'The next few weeks are going to be crucial.', '', ARRAY[]::TEXT[]),
('Crude', 'crude_us.mp3', 'adjective', 'B1', 'in its natural state, before it has been processed or refined', '', 'crude oil/metal', '', ARRAY[]::TEXT[]),
('Cruel', 'cruel_us.mp3', 'adjective', 'B1', 'having a desire to cause physical or mental pain and make somebody suffer', '', 'He was known to be a cruel dictator.', '', ARRAY[]::TEXT[]),
('Cruise', 'cruise_us.mp3', 'noun', 'B1', 'a journey by sea, visiting different places, especially as a holiday', '', 'I''d love to go on a round-the-world cruise.', '', ARRAY[]::TEXT[]),
('Cruise', 'cruise_us.mp3', 'verb', 'B1', 'to travel in a ship or boat visiting different places, especially as a holiday', '', '(+ adv./prep.), They cruised down the Nile.', '', ARRAY[]::TEXT[]),
('Crush', 'crush_us.mp3', 'verb', 'B1', 'to press something so hard that it is damaged or injured, or loses its shape', '', 'The car was completely crushed under the truck.', '', ARRAY[]::TEXT[]),
('Cry', 'cry_us.mp3', 'noun', 'B1', 'a loud sound without words that expresses a strong feeling', '', 'cry of something, to give a cry of anguish/despair/pain/joy/alarm, etc.', '', ARRAY[]::TEXT[]),
('Cry', 'cry_us.mp3', 'verb', 'B1', 'to produce tears from your eyes because you are unhappy or hurt', '', 'It''s all right. Don''t cry.', '', ARRAY[]::TEXT[]),
('Crystal', 'crystal_us.mp3', 'noun', 'B1', 'a small piece of a substance with many even sides, that is formed naturally when the substance becomes solid', '', 'ice/salt crystals', '', ARRAY[]::TEXT[]),
('Cue', 'cue_us.mp3', 'noun', 'B1', 'an action or event that is a signal for somebody to do something', '', 'cue (for something), Jon''s arrival was a cue for more champagne.', '', ARRAY[]::TEXT[]),
('Cult', 'cult_us.mp3', 'adjective', 'B1', 'very popular with a particular group of people', '', 'a cult movie/book', '', ARRAY[]::TEXT[]),
('Cult', 'cult_us.mp3', 'noun', 'B1', 'a way of life, an attitude, an idea, etc. that has become very popular', '', 'the cult of physical fitness', '', ARRAY[]::TEXT[]),
('Cultivate', 'cultivate_us.mp3', 'verb', 'B1', 'to prepare and use land for growing plants or crops', '', 'The land around here has never been cultivated.', '', ARRAY[]::TEXT[]),
('Cultural', 'cultural_us.mp3', 'adjective', 'B1', 'connected with the culture of a particular society or group, its customs, beliefs, etc.', '', 'Teachers need to be aware of cultural differences.', '', ARRAY[]::TEXT[]),
('Culture', 'culture_us.mp3', 'noun', 'B1', 'the customs and beliefs, art, way of life and social organization of a particular country or group', '', 'African/American/European/Islamic culture', '', ARRAY[]::TEXT[]),
('Cup', 'cup_us.mp3', 'noun', 'B1', 'a small container that is like a bowl in shape, usually with a handle, used for drinking tea, coffee, etc.', '', 'He filled the cup with water.', '', ARRAY[]::TEXT[]),
('Cupboard', 'cupboard_us.mp3', 'noun', 'B1', 'a piece of furniture with doors and shelves used for storing dishes, food, clothes, etc.', '', 'kitchen cupboards', '', ARRAY[]::TEXT[]),
('Cure', 'cure_us.mp3', 'noun', 'B1', 'a medicine or medical treatment that cures an illness', '', 'cure for something, the search for a cure for cancer', '', ARRAY[]::TEXT[]),
('Cure', 'cure_us.mp3', 'verb', 'B1', 'to make a person or an animal healthy again after an illness', '', 'cure somebody, Will you be able to cure him, Doctor?', '', ARRAY[]::TEXT[]),
('Curiosity', 'curiosity_us.mp3', 'noun', 'B1', 'a strong desire to know about something', '', 'Children show curiosity about everything.', '', ARRAY[]::TEXT[]),
('Curious', 'curious_us.mp3', 'adjective', 'B1', 'having a strong desire to know about something', '', 'He is such a curious boy, always asking questions.', '', ARRAY[]::TEXT[]),
('Curly', 'curly_us.mp3', 'adjective', 'B1', 'having a lot of curls or a curved shape', '', 'long curly hair', '', ARRAY[]::TEXT[]),
('Currency', 'currency_us.mp3', 'noun', 'B1', 'the system of money that a country uses', '', 'trading in foreign currencies', '', ARRAY[]::TEXT[]),
('Current', 'current_us.mp3', 'adjective', 'B1', 'happening now; of the present time', '', 'The necklace would be worth over $5 000 at current prices.', '', ARRAY[]::TEXT[]),
('Current', 'current_us.mp3', 'noun', 'B1', 'the movement of water in the sea or a river; the movement of air in a particular direction', '', 'with the current, It''s easier to go with the current.', '', ARRAY[]::TEXT[]),
('Currently', 'currently_us.mp3', 'adverb', 'B1', 'at the present time', '', 'The hourly charge is currently £35.', '', ARRAY[]::TEXT[]),
('Curriculum', 'curriculum_us.mp3', 'noun', 'B1', 'the subjects that are included in a course of study or taught in a school, college, etc.', '', 'The school curriculum should be as broad as possible.', '', ARRAY[]::TEXT[]),
('Curtain', 'curtain_us.mp3', 'noun', 'B1', 'a piece of cloth that is hung to cover a window', '', 'to draw/pull/close the curtains (= to pull them across the window so they cover it)', '', ARRAY[]::TEXT[]),
('Curve', 'curve_us.mp3', 'noun', 'B1', 'a line or surface that bends gradually; a smooth bend', '', 'curve of something, He admired the delicate curve of her ear.', '', ARRAY[]::TEXT[]),
('Curve', 'curve_us.mp3', 'verb', 'B1', 'to move or make something move in the shape of a curve; to be in the shape of a curve', '', 'a curving staircase', '', ARRAY[]::TEXT[]),
('Curved', 'curved_us.mp3', 'adjective', 'B1', 'having a round shape', '', 'a curved edge/surface', '', ARRAY[]::TEXT[]),
('Custody', 'custody_us.mp3', 'noun', 'B1', 'the legal right or duty to take care of or keep somebody/something; the act of taking care of something/somebody', '', 'Who will have custody of the children?', '', ARRAY[]::TEXT[]),
('Custom', 'custom_us.mp3', 'noun', 'B1', 'an accepted way of behaving or of doing things in a society or a community', '', 'It''s a local custom.', '', ARRAY[]::TEXT[]),
('Customer', 'customer_us.mp3', 'noun', 'B1', 'a person or an organization that buys goods or services from a shop or business', '', 'marketing strategies to target potential customers', '', ARRAY[]::TEXT[]),
('Cut', 'cut_us.mp3', 'noun', 'B1', 'a wound caused by something sharp', '', 'cuts and bruises on the face', '', ARRAY[]::TEXT[]),
('Cut', 'cut_us.mp3', 'verb', 'B1', 'to make an opening or a wound in something, especially with a sharp tool such as a knife or scissors', '', 'cut something, She cut her finger on a piece of glass.', '', ARRAY[]::TEXT[]),
('Cute', 'cute_us.mp3', 'adjective', 'B1', 'pretty and attractive', '', 'a cute little baby', '', ARRAY[]::TEXT[]),
('Cutting', 'cutting_us.mp3', 'noun', 'B1', 'an article or a story that you cut from a newspaper or magazine and keep', '', 'newspaper/press cuttings', '', ARRAY[]::TEXT[]),
('Cycle', 'cycle_us.mp3', 'noun', 'B1', 'a bicycle or motorcycle', '', 'He was riding his cycle home when he was hit by a lorry.', '', ARRAY[]::TEXT[]),
('Cycle', 'cycle_us.mp3', 'verb', 'B1', 'to ride a bicycle; to travel by bicycle', '', 'measures to encourage more people to cycle', '', ARRAY[]::TEXT[]),
('Cynical', 'cynical_us.mp3', 'adjective', 'B1', 'believing that people only do things to help themselves rather than for good or honest reasons', '', 'a cynical view/smile', '', ARRAY[]::TEXT[]),
('Dad', 'dad_us.mp3', 'noun', 'B1', 'father', '', 'That''s my dad over there.', '', ARRAY[]::TEXT[]),
('Daily', 'daily_us.mp3', 'adjective', 'B1', 'happening, done or produced every day', '', 'Many people still read a daily newspaper.', '', ARRAY[]::TEXT[]),
('Daily', 'daily_us.mp3', 'adverb', 'B1', 'every day', '', 'The machines are inspected twice daily.', '', ARRAY[]::TEXT[]),
('Dairy', 'dairy_us.mp3', 'adjective', 'B1', 'made from milk', '', 'dairy products/produce', '', ARRAY[]::TEXT[]),
('Dairy', 'dairy_us.mp3', 'noun', 'B1', 'milk, cheese and other milk products', '', 'The doctor told me to eat less red meat and dairy.', '', ARRAY[]::TEXT[]),
('Dam', 'dam_us.mp3', 'noun', 'B1', 'a barrier that is built across a river in order to stop the water from flowing, used especially to make a reservoir (= a lake for storing water) or to produce electricity', '', 'the Narmada dam in India', '', ARRAY[]::TEXT[]),
('Damage', 'damage_us.mp3', 'noun', 'B1', 'physical harm caused to something which makes it less attractive, useful or valuable', '', 'serious/severe damage', '', ARRAY[]::TEXT[]),
('Damage', 'damage_us.mp3', 'verb', 'B1', 'to have a bad or harmful effect on something/somebody', '', 'The church was badly damaged by the 1997 earthquake.', '', ARRAY[]::TEXT[]),
('Damaging', 'damaging_us.mp3', 'adjective', 'B1', 'causing damage; having a bad effect on somebody/something', '', 'damaging consequences/effects', '', ARRAY[]::TEXT[]),
('Dance', 'dance_us.mp3', 'noun', 'B1', 'a series of movements and steps that are usually performed to music; a particular example of these movements and steps', '', 'Do you know any other Latin American dances?', '', ARRAY[]::TEXT[]),
('Dance', 'dance_us.mp3', 'verb', 'B1', 'to move your body to the sound and rhythm of music', '', 'Do you want to dance?', '', ARRAY[]::TEXT[]),
('Dancer', 'dancer_us.mp3', 'noun', 'B1', 'a person who dances or whose job is dancing', '', 'She''s a fantastic dancer.', '', ARRAY[]::TEXT[]),
('Dancing', 'dancing_us.mp3', 'noun', 'B1', 'moving your body to music', '', 'There was music and dancing till two in the morning.', '', ARRAY[]::TEXT[]),
('Danger', 'danger_us.mp3', 'noun', 'B1', 'the possibility of something happening that will injure, harm or kill somebody, or damage or destroy something', '', 'Danger! Keep Out!', '', ARRAY[]::TEXT[]),
('Dangerous', 'dangerous_us.mp3', 'adjective', 'B1', 'likely to injure or harm somebody, or to damage or destroy something', '', 'The situation is extremely dangerous.', '', ARRAY[]::TEXT[]),
('Dare', 'dare_us.mp3', 'verb', 'B1', 'to be brave enough to do something', '', 'She said it as loudly as she dared.', '', ARRAY[]::TEXT[]),
('Dark', 'dark_us.mp3', 'adjective', 'B1', 'with no or very little light, especially because it is night', '', 'a dark room/street/forest/night', '', ARRAY[]::TEXT[]),
('Dark', 'dark_us.mp3', 'noun', 'B1', 'the lack of light in a place, especially because it is night', '', 'Are the children afraid of the dark?', '', ARRAY[]::TEXT[]),
('Darkness', 'darkness_us.mp3', 'noun', 'B1', 'the state of being dark, without any light', '', 'After a few minutes our eyes got used to the darkness.', '', ARRAY[]::TEXT[]),
('Data', 'data_us.mp3', 'noun', 'B1', 'facts or information, especially when examined and used to find out things or to make decisions', '', 'We collected publicly available data over a 10-day period.', '', ARRAY[]::TEXT[]),
('Database', 'database_us.mp3', 'noun', 'B1', 'an organized set of data that is stored in a computer and can be looked at and used in various ways', '', 'The database is updated monthly.', '', ARRAY[]::TEXT[]),
('Date', 'date_us.mp3', 'noun', 'B1', 'a particular day of the month, sometimes in a particular year, given in numbers and words', '', '‘What''s the date today?’ ‘The 10th.’', '', ARRAY[]::TEXT[]),
('Date', 'date_us.mp3', 'verb', 'B1', 'to write or print the date on something', '', 'Thank you for your letter dated 24th March.', '', ARRAY[]::TEXT[]),
('Daughter', 'daughter_us.mp3', 'noun', 'B1', 'a person’s female child', '', 'We have two sons and a daughter.', '', ARRAY[]::TEXT[]),
('Dawn', 'dawn_us.mp3', 'noun', 'B1', 'the time of day when light first appears', '', 'at dawn, They start work at dawn.', '', ARRAY[]::TEXT[]),
('Day', 'day_us.mp3', 'noun', 'B1', 'a period of 24 hours', '', '‘What day is it today?’ ‘Monday.’', '', ARRAY[]::TEXT[]),
('Dead', 'dead_us.mp3', 'adjective', 'B1', 'no longer alive', '', 'My mother''s dead; she died in 2017.', '', ARRAY[]::TEXT[]),
('Deadline', 'deadline_us.mp3', 'noun', 'B1', 'a point in time by which something must be done', '', 'I prefer to work to a deadline.', '', ARRAY[]::TEXT[]),
('Deadly', 'deadly_us.mp3', 'adjective', 'B1', 'causing or likely to cause death', '', 'a deadly weapon/disease', '', ARRAY[]::TEXT[]),
('Deal', 'deal_us.mp3', 'noun', 'B1', 'an agreement, especially in business, on particular conditions for buying or doing something', '', 'to sign/strike/finalize/close a deal', '', ARRAY[]::TEXT[]),
('Deal', 'deal_us.mp3', 'verb', 'B1', 'to give cards to each player in a game of cards', '', 'Whose turn is it to deal?', '', ARRAY[]::TEXT[]),
('Dealer', 'dealer_us.mp3', 'noun', 'B1', 'a person whose business is buying and selling a particular product', '', 'an art/antique dealer', '', ARRAY[]::TEXT[]),
('Dear', 'dear_us.mp3', 'adjective', 'B1', 'used at the beginning of a letter before the name or title of the person that you are writing to', '', 'Dear Sir or Madam', '', ARRAY[]::TEXT[]),
('Dear', 'dear_us.mp3', 'exclamation', 'B1', 'used in expressions that show that you are surprised, upset, annoyed or worried', '', 'Oh dear! I think I''ve lost my purse!', '', ARRAY[]::TEXT[]),
('Death', 'death_us.mp3', 'noun', 'B1', 'the fact of somebody dying or being killed', '', 'the anniversary of his wife’s death', '', ARRAY[]::TEXT[]),
('Debate', 'debate_us.mp3', 'noun', 'B1', 'a formal discussion of an issue at a public meeting or in a parliament. In a debate two or more speakers express opposite views and then there is often a vote on the issue.', '', 'the first ever televised presidential debate', '', ARRAY[]::TEXT[]),
('Debate', 'debate_us.mp3', 'verb', 'B1', 'to discuss something, especially formally, before making a decision or finding a solution', '', 'debate (something), Politicians will be debating the bill later this week.', '', ARRAY[]::TEXT[]),
('Debris', 'debris_us.mp3', 'noun', 'B1', 'pieces of wood, metal, building materials, etc. that are left after something has been destroyed', '', 'Emergency teams are still clearing the debris from the plane crash.', '', ARRAY[]::TEXT[]),
('Debt', 'debt_us.mp3', 'noun', 'B1', 'a sum of money that somebody owes', '', 'to pay/repay a debt', '', ARRAY[]::TEXT[]),
('Debut', 'debut_us.mp3', 'noun', 'B1', 'the first public appearance of a performer or sports player', '', 'He will make his debut for the first team this week.', '', ARRAY[]::TEXT[]),
('Decade', 'decade_us.mp3', 'noun', 'B1', 'a period of ten years, especially a continuous period, such as 1910–1919 or 2000–2009', '', 'the early decades of the nineteenth century', '', ARRAY[]::TEXT[]),
('December', 'December_us.mp3', 'noun', 'B1', 'the 12th and last month of the year', '', 'She was born in December.', '', ARRAY[]::TEXT[]),
('Decent', 'decent_us.mp3', 'adjective', 'B1', 'of a good enough standard or quality', '', 'a decent meal/place to live', '', ARRAY[]::TEXT[]),
('Decide', 'decide_us.mp3', 'verb', 'B1', 'to think carefully about the different possibilities that are available and choose one of them', '', 'It''s up to you to decide.', '', ARRAY[]::TEXT[]),
('Decision', 'decision_us.mp3', 'noun', 'B1', 'a choice or judgement that you make after thinking and talking about what is the best thing to do', '', 'I think I''ve made the right decision.', '', ARRAY[]::TEXT[]),
('Decision-making', 'decision-making_us.mp3', 'noun', 'B1', 'the process of deciding about something important, especially in a group of people or in an organization', '', 'responsibility for decision-making', '', ARRAY[]::TEXT[]),
('Decisive', 'decisive_us.mp3', 'adjective', 'B1', 'very important for the final result of a particular situation', '', 'a decisive factor/victory/battle', '', ARRAY[]::TEXT[]),
('Deck', 'deck_us.mp3', 'noun', 'B1', 'the top outside floor of a ship or boat', '', 'on deck, I was the only person on deck at that time of night.', '', ARRAY[]::TEXT[]),
('Declaration', 'declaration_us.mp3', 'noun', 'B1', 'an official or formal statement, especially about the plans of a government or an organization; the act of making such a statement', '', 'to issue/sign a declaration', '', ARRAY[]::TEXT[]),
('Declare', 'declare_us.mp3', 'verb', 'B1', 'to say something officially or publicly', '', 'declare something, The government has declared a state of emergency.', '', ARRAY[]::TEXT[]),
('Decline', 'decline_us.mp3', 'noun', 'B1', 'a continuous decrease in the number, value, quality, etc. of something', '', 'decline in something, There has been a 5 per cent decline in student numbers.', '', ARRAY[]::TEXT[]),
('Decline', 'decline_us.mp3', 'verb', 'B1', 'to become smaller, fewer, weaker, etc.', '', 'Support for the party continues to decline.', '', ARRAY[]::TEXT[]),
('Decorate', 'decorate_us.mp3', 'verb', 'B1', 'to make something look more attractive by putting things on it', '', 'decorate something with something, They decorated the room with flowers and balloons.', '', ARRAY[]::TEXT[]),
('Decoration', 'decoration_us.mp3', 'noun', 'B1', 'a thing that makes something look more attractive on special occasions', '', 'Christmas/festive decorations', '', ARRAY[]::TEXT[]),
('Decrease', 'decrease_us.mp3', 'noun', 'B1', 'the process of reducing something; the amount that something is reduced by', '', 'Sales for May show a decrease compared with the same month last year.', '', ARRAY[]::TEXT[]),
('Decrease', 'decrease_us.mp3', 'verb', 'B1', 'to become smaller in size, number, etc.; to make something smaller in size, number, etc.', '', 'Donations have decreased significantly over the past few years.', '', ARRAY[]::TEXT[]),
('Dedicated', 'dedicated_us.mp3', 'adjective', 'B1', 'working hard at something because it is very important to you', '', 'a dedicated teacher', '', ARRAY[]::TEXT[]),
('Dedication', 'dedication_us.mp3', 'noun', 'B1', 'the hard work and effort that somebody puts into an activity or a purpose because they think it is important', '', 'hard work and dedication', '', ARRAY[]::TEXT[]),
('Deed', 'deed_us.mp3', 'noun', 'B1', 'a thing that somebody does that is usually very good or very bad', '', 'It''s a stirring tale of heroic deeds.', '', ARRAY[]::TEXT[]),
('Deem', 'deem_us.mp3', 'verb', 'B1', 'to have a particular opinion about somebody/something', '', 'deem somebody/something + noun, The evening was deemed a great success.', '', ARRAY[]::TEXT[]),
('Deep', 'deep_us.mp3', 'adjective', 'B1', 'having a large distance from the top or surface to the bottom', '', 'a deep hole/well/river', '', ARRAY[]::TEXT[]),
('Deep', 'deep_us.mp3', 'adverb', 'B1', 'a long way below the surface of something or a long way inside or into something', '', 'Dig deeper!', '', ARRAY[]::TEXT[]),
('Deeply', 'deeply_us.mp3', 'adverb', 'B1', 'very; very much', '', 'She is deeply religious.', '', ARRAY[]::TEXT[]),
('Default', 'default_us.mp3', 'noun', 'B1', 'what happens or appears if you do not make any other choice or change, especially in a computer program', '', 'The default is fifty lines.', '', ARRAY[]::TEXT[]),
('Defeat', 'defeat_us.mp3', 'noun', 'B1', 'failure to win or to be successful', '', 'The party faces defeat in the election.', '', ARRAY[]::TEXT[]),
('Defeat', 'defeat_us.mp3', 'verb', 'B1', 'to win against somebody in a war, competition, sports game, etc.', '', 'defeat somebody/something, He defeated the champion in three sets.', '', ARRAY[]::TEXT[]),
('Defect', 'defect_us.mp3', 'noun', 'B1', 'a fault in something or in the way it has been made that means that it is not perfect', '', 'a defect in the glass', '', ARRAY[]::TEXT[]),
('Defence', 'defence_us.mp3', 'noun', 'B1', 'the act of protecting somebody/something from attack, criticism, etc.', '', 'in defence of somebody/something, soldiers who died in defence of their country', '', ARRAY[]::TEXT[]),
('Defend', 'defend_us.mp3', 'verb', 'B1', 'to protect somebody/something from attack', '', 'defend somebody/something, The role of the military is to defend the country.', '', ARRAY[]::TEXT[]),
('Defender', 'defender_us.mp3', 'noun', 'B1', 'a player who must stop the other team from scoring in games such as football (soccer), hockey, etc.', '', 'a passionate defender of human rights', '', ARRAY[]::TEXT[]),
('Defensive', 'defensive_us.mp3', 'adjective', 'B1', 'protecting somebody/something against attack', '', 'As a defensive measure he built a series of coastal forts and watchtowers.', '', ARRAY[]::TEXT[]),
('Deficiency', 'deficiency_us.mp3', 'noun', 'B1', 'the state of not having, or not having enough of, something that is essential', '', 'deficiency (in something), Vitamin deficiency in the diet can cause illness.', '', ARRAY[]::TEXT[]),
('Deficit', 'deficit_us.mp3', 'noun', 'B1', 'the amount by which money spent or owed is greater than money earned in a particular period of time', '', 'a budget/trade deficit', '', ARRAY[]::TEXT[]),
('Define', 'define_us.mp3', 'verb', 'B1', 'to say or explain what the meaning of a word or phrase is', '', 'define something, The term ‘normal’ is difficult to define.', '', ARRAY[]::TEXT[]),
('Definite', 'definite_us.mp3', 'adjective', 'B1', 'sure or certain; unlikely to change', '', 'Can you give me a definite answer by tomorrow?', '', ARRAY[]::TEXT[]),
('Definitely', 'definitely_us.mp3', 'adverb', 'B1', 'a way of emphasizing that something is true and that there is no doubt about it', '', 'I definitely remember sending the letter.', '', ARRAY[]::TEXT[]),
('Definition', 'definition_us.mp3', 'noun', 'B1', 'an explanation of the meaning of a word or phrase, especially in a dictionary', '', 'The dictionary provides clear, simple definitions.', '', ARRAY[]::TEXT[]),
('Defy', 'defy_us.mp3', 'verb', 'B1', 'to refuse to obey or show respect for somebody in authority, a law, a rule, etc.', '', 'I wouldn''t have dared to defy my teachers.', '', ARRAY[]::TEXT[]),
('Degree', 'degree_us.mp3', 'noun', 'B1', 'a unit for measuring temperature', '', 'at… degrees, Water freezes at 32 degrees Fahrenheit (32°F) or zero/nought degrees Celsius (0°C).', '', ARRAY[]::TEXT[]),
('Delay', 'delay_us.mp3', 'noun', 'B1', 'a period of time when somebody/something has to wait because of a problem that makes something slow or late', '', 'Commuters will face long delays on the roads today.', '', ARRAY[]::TEXT[]),
('Delay', 'delay_us.mp3', 'verb', 'B1', 'to make somebody/something late or force them to do something more slowly', '', 'My flight was delayed.', '', ARRAY[]::TEXT[]),
('Delegate', 'delegate_us.mp3', 'noun', 'B1', 'a person who is chosen or elected to represent the views of a group of people and vote and make decisions for them', '', 'Congress delegates rejected the proposals.', '', ARRAY[]::TEXT[]),
('Delegation', 'delegation_us.mp3', 'noun', 'B1', 'a group of people who represent the views of an organization, a country, etc.', '', 'the Dutch delegation to the United Nations', '', ARRAY[]::TEXT[]),
('Delete', 'delete_us.mp3', 'verb', 'B1', 'to remove something that has been written or printed, or that has been stored on a computer', '', 'Your name has been deleted from the list.', '', ARRAY[]::TEXT[]),
('Deliberate', 'deliberate_us.mp3', 'adjective', 'B1', 'done on purpose rather than by accident', '', 'a deliberate act of vandalism', '', ARRAY[]::TEXT[]),
('Deliberately', 'deliberately_us.mp3', 'adverb', 'B1', 'done in a way that was planned, not by chance', '', 'She''s been deliberately ignoring him all day.', '', ARRAY[]::TEXT[]),
('Delicate', 'delicate_us.mp3', 'adjective', 'B1', 'easily damaged or broken', '', 'delicate china teacups', '', ARRAY[]::TEXT[]),
('Delicious', 'delicious_us.mp3', 'adjective', 'B1', 'having a very pleasant taste or smell', '', 'Who cooked this? It''s absolutely delicious.', '', ARRAY[]::TEXT[]),
('Delight', 'delight_us.mp3', 'noun', 'B1', 'a feeling of great pleasure', '', 'a feeling of sheer/pure delight', '', ARRAY[]::TEXT[]),
('Delight', 'delight_us.mp3', 'verb', 'B1', 'to give somebody a lot of pleasure and joy', '', 'This news will delight his fans all over the world.', '', ARRAY[]::TEXT[]),
('Delighted', 'delighted_us.mp3', 'adjective', 'B1', 'very pleased', '', 'a delighted smile', '', ARRAY[]::TEXT[]),
('Deliver', 'deliver_us.mp3', 'verb', 'B1', 'to take goods, letters, etc. to the person or people they have been sent to', '', 'deliver something, I get my food delivered from the supermarket to save time.', '', ARRAY[]::TEXT[]),
('Delivery', 'delivery_us.mp3', 'noun', 'B1', 'the act of taking goods, letters, etc. to the people they have been sent to', '', 'Allow 28 days for delivery.', '', ARRAY[]::TEXT[]),
('Demand', 'demand_us.mp3', 'noun', 'B1', 'a very strong request for something; something that somebody needs', '', 'demand for something, a demand for higher pay', '', ARRAY[]::TEXT[]),
('Demand', 'demand_us.mp3', 'verb', 'B1', 'to make a very strong request for something', '', 'demand something, They are demanding the release of all political prisoners.', '', ARRAY[]::TEXT[]),
('Democracy', 'democracy_us.mp3', 'noun', 'B1', 'a system of government in which the people of a country can vote to elect their representatives', '', 'parliamentary democracy', '', ARRAY[]::TEXT[]),
('Democratic', 'democratic_us.mp3', 'adjective', 'B1', 'controlled by representatives who are elected by the people of a country; connected with this system', '', 'a democratic country', '', ARRAY[]::TEXT[]),
('Demon', 'demon_us.mp3', 'noun', 'B1', 'an evil spirit', '', 'The people believed the girl was possessed by demons.', '', ARRAY[]::TEXT[]),
('Demonstrate', 'demonstrate_us.mp3', 'verb', 'B1', 'to show something clearly by giving proof or evidence', '', 'demonstrate that…, New research convincingly demonstrates that age-related memory loss is not inevitable.', '', ARRAY[]::TEXT[]),
('Demonstration', 'demonstration_us.mp3', 'noun', 'B1', 'a public meeting or a march (= an organized walk by many people) at which people show that they are protesting against or supporting somebody/something', '', 'to take part in/go on a demonstration', '', ARRAY[]::TEXT[]),
('Denial', 'denial_us.mp3', 'noun', 'B1', 'a statement that something is not true or does not exist; the action of denying something', '', 'denial (of something), the prisoner’s repeated denials of the charges against him', '', ARRAY[]::TEXT[]),
('Denounce', 'denounce_us.mp3', 'verb', 'B1', 'to strongly criticize somebody/something that you think is wrong, illegal, etc.', '', 'denounce somebody/something, She publicly denounced the government''s handling of the crisis.', '', ARRAY[]::TEXT[]),
('Dense', 'dense_us.mp3', 'adjective', 'B1', 'containing a lot of people, things, plants, etc. with little space between them', '', 'a dense crowd/forest', '', ARRAY[]::TEXT[]),
('Density', 'density_us.mp3', 'noun', 'B1', 'the quality of being dense; the degree to which something is dense', '', 'The population density in this city is very high.', '', ARRAY[]::TEXT[]),
('Dentist', 'dentist_us.mp3', 'noun', 'B1', 'a person whose job is to take care of people’s teeth', '', 'to see/visit/consult your dentist', '', ARRAY[]::TEXT[]),
('Deny', 'deny_us.mp3', 'verb', 'B1', 'to say that something is not true', '', 'deny something, to deny an allegation/a charge/an accusation', '', ARRAY[]::TEXT[]),
('Depart', 'depart_us.mp3', 'verb', 'B1', 'to leave a place, especially to start a trip', '', 'depart (for…) (from…), Flights for Rome depart from Terminal 3.', '', ARRAY[]::TEXT[]),
('Department', 'department_us.mp3', 'noun', 'B1', 'a section of a large organization such as a government, business, university, etc.', '', 'department of something, the Department of Health', '', ARRAY[]::TEXT[]),
('Departure', 'departure_us.mp3', 'noun', 'B1', 'an act of leaving a place', '', 'His sudden departure threw the office into chaos.', '', ARRAY[]::TEXT[]),
('Depend', 'depend_us.mp3', 'verb', 'B1', 'according to', '', 'Starting salary varies from £26 000 to £30 500, depending on experience.', '', ARRAY[]::TEXT[]),
('Dependence', 'dependence_us.mp3', 'noun', 'B1', 'the state of needing the help and support of somebody/something in order to survive or be successful', '', 'Our relationship was based on mutual dependence.', '', ARRAY[]::TEXT[]),
('Dependent', 'dependent_us.mp3', 'adjective', 'B1', 'needing somebody/something in order to survive or be successful', '', 'a woman with several dependent children', '', ARRAY[]::TEXT[]),
('Depict', 'depict_us.mp3', 'verb', 'B1', 'to show an image of somebody/something in a picture', '', 'depict somebody/something (as somebody/something), a painting depicting the Virgin and Child', '', ARRAY[]::TEXT[]),
('Deploy', 'deploy_us.mp3', 'verb', 'B1', 'to move soldiers or weapons into a position where they are ready for military action', '', '2 000 troops were deployed in the area.', '', ARRAY[]::TEXT[]),
('Deployment', 'deployment_us.mp3', 'noun', 'B1', 'the act of moving soldiers or weapons into a position where they are ready for military action', '', 'the deployment of peacekeeping forces', '', ARRAY[]::TEXT[]),
('Deposit', 'deposit_us.mp3', 'noun', 'B1', 'a sum of money that is given as the first part of a larger payment', '', 'They normally ask you to pay $100 (as a) deposit.', '', ARRAY[]::TEXT[]),
('Deposit', 'deposit_us.mp3', 'verb', 'B1', 'to put money into a bank account', '', 'Millions were deposited in Swiss bank accounts.', '', ARRAY[]::TEXT[]),
('Depressed', 'depressed_us.mp3', 'adjective', 'B1', 'very sad and without hope', '', 'You mustn''t let yourself get depressed.', '', ARRAY[]::TEXT[]),
('Depressing', 'depressing_us.mp3', 'adjective', 'B1', 'making you feel very sad and without enthusiasm', '', 'a depressing sight/thought/experience', '', ARRAY[]::TEXT[]),
('Depression', 'depression_us.mp3', 'noun', 'B1', 'a medical condition in which a person feels very sad, anxious and without hope and often has physical symptoms such as being unable to sleep, etc.', '', 'She was diagnosed as having clinical depression.', '', ARRAY[]::TEXT[]),
('Depth', 'depth_us.mp3', 'noun', 'B1', 'the distance from the top or surface to the bottom of something; a particular distance down from the surface of something', '', 'depth of something, What''s the depth of the water here?', '', ARRAY[]::TEXT[]),
('Deputy', 'deputy_us.mp3', 'noun', 'B1', 'a person who is the next most important person below a business manager, a head of a school, a political leader, etc. and who does that person’s job when they are away', '', 'I''m acting as deputy till the manager returns.', '', ARRAY[]::TEXT[]),
('Descend', 'descend_us.mp3', 'verb', 'B1', 'to come or go down from a higher to a lower level', '', 'The plane began to descend.', '', ARRAY[]::TEXT[]),
('Descent', 'descent_us.mp3', 'noun', 'B1', 'an action of coming or going down', '', 'The plane began its descent to Heathrow.', '', ARRAY[]::TEXT[]),
('Describe', 'describe_us.mp3', 'verb', 'B1', 'to say what somebody/something is like', '', 'describe somebody/something, The next section describes our findings in detail.', '', ARRAY[]::TEXT[]),
('Description', 'description_us.mp3', 'noun', 'B1', 'a piece of writing or speech that says what somebody/something is like; the act of writing or saying in words what somebody/something is like', '', 'Follow the link below for a more detailed description.', '', ARRAY[]::TEXT[]),
('Desert', 'desert_us.mp3', 'noun', 'B1', 'a large area of land that has very little water and very few plants growing on it. Many deserts are covered by sand.', '', 'the Sahara Desert', '', ARRAY[]::TEXT[]),
('Desert', 'desert_us.mp3', 'verb', 'B1', 'to leave somebody without help or support', '', 'She was deserted by her husband.', '', ARRAY[]::TEXT[]),
('Deserve', 'deserve_us.mp3', 'verb', 'B1', 'to do something or show qualities that mean a particular reaction, reward or punishment is appropriate', '', 'deserve something, You deserve a rest after all that hard work.', '', ARRAY[]::TEXT[]),
('Design', 'design_us.mp3', 'noun', 'B1', 'the general arrangement of the different parts of something that is made, such as a building, book, machine, etc.', '', 'The basic design of the car is very similar to that of earlier models.', '', ARRAY[]::TEXT[]),
('Design', 'design_us.mp3', 'verb', 'B1', 'to decide how something will look, work, etc., by drawing plans, making computer models, etc.', '', 'design something, He designed and built his own house.', '', ARRAY[]::TEXT[]),
('Designate', 'designate_us.mp3', 'verb', 'B1', 'to say officially that somebody/something has a particular character or name; to describe somebody/something in a particular way', '', 'be designated (as) something, This area has been designated (as) a National Park.', '', ARRAY[]::TEXT[]),
('Designer', 'designer_us.mp3', 'noun', 'B1', 'a person whose job is to decide how things such as clothes, furniture, tools, etc. will look or work by making drawings, plans or patterns', '', 'one of the country''s top fashion designers', '', ARRAY[]::TEXT[]),
('Desirable', 'desirable_us.mp3', 'adjective', 'B1', 'that you would like to have or do; worth having or doing', '', 'She chatted for a few minutes about the qualities she considered desirable in a secretary.', '', ARRAY[]::TEXT[]),
('Desire', 'desire_us.mp3', 'noun', 'B1', 'a strong wish to have or do something', '', 'He now had enough money to satisfy all his desires.', '', ARRAY[]::TEXT[]),
('Desire', 'desire_us.mp3', 'verb', 'B1', 'to want something; to wish for something', '', 'desire something, We all desire health and happiness.', '', ARRAY[]::TEXT[]),
('Desk', 'desk_us.mp3', 'noun', 'B1', 'a piece of furniture like a table, often with drawers (= parts like boxes in it with handles on the front for pulling them open), that you sit at to read, write, work, etc.', '', 'at a desk, I spend all day sitting at a desk.', '', ARRAY[]::TEXT[]),
('Desktop', 'desktop_us.mp3', 'noun', 'B1', 'a screen on a computer that shows the icons of programs and files that can be used', '', 'desktop icons', '', ARRAY[]::TEXT[]),
('Desperate', 'desperate_us.mp3', 'adjective', 'B1', 'feeling or showing that you have little hope and are ready to do anything without worrying about danger to yourself or others', '', 'The prisoners grew increasingly desperate.', '', ARRAY[]::TEXT[]),
('Desperately', 'desperately_us.mp3', 'adverb', 'B1', 'in a way that shows you have little hope and are ready to do anything without worrying about danger to yourself or others', '', 'She looked desperately around for a weapon.', '', ARRAY[]::TEXT[]),
('Despite', 'despite_us.mp3', 'preposition', 'B1', 'used to show that something happened or is true although something else might have happened to prevent it', '', 'Her voice was shaking despite all her efforts to control it.', '', ARRAY[]::TEXT[]),
('Destination', 'destination_us.mp3', 'noun', 'B1', 'a place to which somebody/something is going or being sent', '', 'popular tourist/holiday destinations like the Bahamas', '', ARRAY[]::TEXT[]),
('Destroy', 'destroy_us.mp3', 'verb', 'B1', 'to damage something so badly that it no longer exists, works, etc.', '', 'The building was completely destroyed by fire.', '', ARRAY[]::TEXT[]),
('Destruction', 'destruction_us.mp3', 'noun', 'B1', 'the act of destroying something; the process of being destroyed', '', 'the destruction of the rainforests', '', ARRAY[]::TEXT[]),
('Destructive', 'destructive_us.mp3', 'adjective', 'B1', 'causing destruction or damage', '', 'The war demonstrated the destructive power of modern weapons.', '', ARRAY[]::TEXT[]),
('Detail', 'detail_us.mp3', 'noun', 'B1', 'a small individual fact or item; a less important fact or item', '', 'an expedition planned down to the last detail', '', ARRAY[]::TEXT[]),
('Detail', 'detail_us.mp3', 'verb', 'B1', 'to give a list of facts or all the available information about something', '', 'The brochure details all the hotels in the area and their facilities.', '', ARRAY[]::TEXT[]),
('Detailed', 'detailed_us.mp3', 'adjective', 'B1', 'giving many details and a lot of information; paying great attention to details', '', 'a detailed description of the events', '', ARRAY[]::TEXT[]),
('Detain', 'detain_us.mp3', 'verb', 'B1', 'to keep somebody in an official place, such as a police station, a prison or a hospital, and prevent them from leaving', '', 'One man has been detained for questioning.', '', ARRAY[]::TEXT[]),
('Detect', 'detect_us.mp3', 'verb', 'B1', 'to discover or notice something, especially something that is not easy to see, hear, etc.', '', 'The tests are designed to detect the disease early.', '', ARRAY[]::TEXT[]),
('Detection', 'detection_us.mp3', 'noun', 'B1', 'the process of discovering or noticing something, especially something that is not easy to see, hear, etc.; the fact of being discovered or noticed', '', 'crime prevention and detection', '', ARRAY[]::TEXT[]),
('Detective', 'detective_us.mp3', 'noun', 'B1', 'a person, especially a police officer, whose job is to investigate crimes and catch criminals', '', 'a police/homicide/undercover detective', '', ARRAY[]::TEXT[]),
('Detention', 'detention_us.mp3', 'noun', 'B1', 'the state of being kept in a place, especially a prison, and prevented from leaving', '', 'They were sentenced to 12 months'' detention in a young offender institution.', '', ARRAY[]::TEXT[]),
('Deteriorate', 'deteriorate_us.mp3', 'verb', 'B1', 'to become worse', '', 'Her health deteriorated rapidly, and she died shortly afterwards.', '', ARRAY[]::TEXT[]),
('Determination', 'determination_us.mp3', 'noun', 'B1', 'the quality that makes you continue trying to do something even when this is difficult', '', 'fierce/grim/dogged determination', '', ARRAY[]::TEXT[]),
('Determine', 'determine_us.mp3', 'verb', 'B1', 'to discover the facts about something; to calculate something exactly', '', 'determine something, An inquiry was set up to determine the cause of the accident.', '', ARRAY[]::TEXT[]),
('Determined', 'determined_us.mp3', 'adjective', 'B1', 'having made a definite decision to do something and not letting anyone prevent you', '', 'The opposition to her plan made her more determined than ever.', '', ARRAY[]::TEXT[]),
('Devastate', 'devastate_us.mp3', 'verb', 'B1', 'to completely destroy a place or an area', '', 'The bomb devastated much of the old part of the city.', '', ARRAY[]::TEXT[]),
('Develop', 'develop_us.mp3', 'verb', 'B1', 'to gradually grow or become bigger, more advanced, stronger, etc.; to make something do this', '', 'From birth to age 5, a child''s brain develops rapidly.', '', ARRAY[]::TEXT[]),
('Development', 'development_us.mp3', 'noun', 'B1', 'the steady growth of something so that it becomes more advanced, stronger, etc.', '', 'a baby’s development in the womb', '', ARRAY[]::TEXT[]),
('Device', 'device_us.mp3', 'noun', 'B1', 'an object or a piece of equipment that has been designed to do a particular job', '', 'a tracking/recording/listening device', '', ARRAY[]::TEXT[]),
('Devil', 'devil_us.mp3', 'noun', 'B1', 'the most powerful evil being', '', 'belief in the Devil', '', ARRAY[]::TEXT[]),
('Devise', 'devise_us.mp3', 'verb', 'B1', 'to invent something new or a new way of doing something', '', 'A new system has been devised to control traffic in the city.', '', ARRAY[]::TEXT[]),
('Diagnose', 'diagnose_us.mp3', 'verb', 'B1', 'to say exactly what an illness or the cause of a problem is', '', 'diagnose something, The test is used to diagnose a variety of diseases.', '', ARRAY[]::TEXT[]),
('Diagnosis', 'diagnosis_us.mp3', 'noun', 'B1', 'the act of discovering or identifying the exact cause of an illness or a problem', '', 'a diagnosis of lung cancer', '', ARRAY[]::TEXT[]),
('Diagram', 'diagram_us.mp3', 'noun', 'B1', 'a simple drawing using lines to explain where something is, how something works, etc.', '', 'The results are shown in diagram 2.', '', ARRAY[]::TEXT[]),
('Dialogue', 'dialogue_us.mp3', 'noun', 'B1', 'a conversation in a book, play or film or in language teaching materials', '', 'Learners are asked to listen to three short dialogues.', '', ARRAY[]::TEXT[]),
('Diamond', 'diamond_us.mp3', 'noun', 'B1', 'a clear precious stone of pure carbon, the hardest substance known. Diamonds are used in jewellery and also in industry, especially for cutting glass.', '', 'a diamond ring/necklace', '', ARRAY[]::TEXT[]),
('Diary', 'diary_us.mp3', 'noun', 'B1', 'a book in which you can write down the experiences you have each day, your private thoughts, etc.', '', 'Do you keep a diary (= write one regularly)?', '', ARRAY[]::TEXT[]),
('Dictate', 'dictate_us.mp3', 'verb', 'B1', 'to tell somebody what to do, especially in an annoying way', '', 'dictate something (to somebody), They are in no position to dictate terms (= tell other people what to do).', '', ARRAY[]::TEXT[]),
('Dictator', 'dictator_us.mp3', 'noun', 'B1', 'a political leader who has complete power over a country, especially one who has gained it using military force', '', 'The country suffered at the hands of a series of military dictators.', '', ARRAY[]::TEXT[]),
('Dictionary', 'dictionary_us.mp3', 'noun', 'B1', 'a book or electronic resource that gives a list of the words of a language in alphabetical order and explains what they mean, or gives a word for them in a foreign language', '', 'a Spanish-English dictionary', '', ARRAY[]::TEXT[]),
('Die', 'die_us.mp3', 'verb', 'B1', 'to stop living', '', 'My father died suddenly at the age of 48.', '', ARRAY[]::TEXT[]),
('Diet', 'diet_us.mp3', 'noun', 'B1', 'the food and drink that you eat and drink regularly', '', 'to eat a healthy, balanced diet', '', ARRAY[]::TEXT[]),
('Differ', 'differ_us.mp3', 'verb', 'B1', 'to be different from somebody/something', '', 'They hold differing views.', '', ARRAY[]::TEXT[]),
('Difference', 'difference_us.mp3', 'noun', 'B1', 'the way in which two people or things are not like each other; the way in which somebody/something has changed', '', 'Americans and Brits speak the same language, but there are big cultural differences.', '', ARRAY[]::TEXT[]),
('Different', 'different_us.mp3', 'adjective', 'B1', 'not the same as somebody/something; not like somebody/something else', '', 'different from somebody/something, American English is significantly different from British English.', '', ARRAY[]::TEXT[]),
('Differentiate', 'differentiate_us.mp3', 'verb', 'B1', 'to recognize or show that two things are not the same', '', 'differentiate (between) A and B, It''s difficult to differentiate between the two varieties.', '', ARRAY[]::TEXT[]),
('Differently', 'differently_us.mp3', 'adverb', 'B1', 'in a different way from somebody/something', '', 'Boys and girls may behave differently.', '', ARRAY[]::TEXT[]),
('Difficult', 'difficult_us.mp3', 'adjective', 'B1', 'not easy; needing effort or skill to do or to understand', '', 'The competition judges were given a very difficult task.', '', ARRAY[]::TEXT[]),
('Difficulty', 'difficulty_us.mp3', 'noun', 'B1', 'a problem; a thing or situation that causes problems', '', 'the difficulties of English syntax', '', ARRAY[]::TEXT[]),
('Dig', 'dig_us.mp3', 'verb', 'B1', 'to make a hole in the ground or to move soil from one place to another using your hands, a tool or a machine', '', 'I think I''ll do some digging in the garden.', '', ARRAY[]::TEXT[]),
('Digital', 'digital_us.mp3', 'adjective', 'B1', 'using a system of receiving and sending information as a series of the numbers one and zero, showing that an electronic signal is there or is not there', '', 'a digital camera', '', ARRAY[]::TEXT[]),
('Dignity', 'dignity_us.mp3', 'noun', 'B1', 'a calm and serious manner that deserves respect', '', 'She accepted the criticism with quiet dignity.', '', ARRAY[]::TEXT[]),
('Dilemma', 'dilemma_us.mp3', 'noun', 'B1', 'a situation that makes problems, often one in which you have to make a very difficult choice between things of equal importance', '', 'I could see no way of resolving this moral dilemma.', '', ARRAY[]::TEXT[]),
('Dimension', 'dimension_us.mp3', 'noun', 'B1', 'a measurement in space, for example how high, wide or long something is', '', 'We measured the dimensions of the kitchen.', '', ARRAY[]::TEXT[]),
('Diminish', 'diminish_us.mp3', 'verb', 'B1', 'to become smaller, weaker, etc.; to make something become smaller, weaker, etc.', '', 'The world''s resources are rapidly diminishing.', '', ARRAY[]::TEXT[]),
('Dinner', 'dinner_us.mp3', 'noun', 'B1', 'the main meal of the day, eaten either in the middle of the day or in the evening', '', 'It''s time for dinner.', '', ARRAY[]::TEXT[]),
('Dip', 'dip_us.mp3', 'verb', 'B1', 'to put something quickly into a liquid and take it out again', '', 'dip something (into something), He dipped the brush into the paint.', '', ARRAY[]::TEXT[]),
('Diplomat', 'diplomat_us.mp3', 'noun', 'B1', 'a person whose job is to represent his or her country in a foreign country, for example, in an embassy', '', 'Washington''s top diplomat in Havana', '', ARRAY[]::TEXT[]),
('Diplomatic', 'diplomatic_us.mp3', 'adjective', 'B1', 'connected with managing relations between countries (= diplomacy)', '', 'a diplomatic crisis', '', ARRAY[]::TEXT[]),
('Direct', 'direct_us.mp3', 'adjective', 'B1', 'going in the straightest line between two places without stopping or changing direction', '', 'the most direct route', '', ARRAY[]::TEXT[]),
('Direct', 'direct_us.mp3', 'adverb', 'B1', 'without stopping or changing direction or vehicle', '', 'direct to something, We flew direct to Hong Kong.', '', ARRAY[]::TEXT[]),
('Direct', 'direct_us.mp3', 'verb', 'B1', 'to control or be in charge of somebody/something', '', 'He was asked to take command and direct operations.', '', ARRAY[]::TEXT[]),
('Direction', 'direction_us.mp3', 'noun', 'B1', 'the general position a person or thing moves or points towards', '', 'in the direction of something, They headed in the direction of the village.', '', ARRAY[]::TEXT[]),
('Directly', 'directly_us.mp3', 'adverb', 'B1', 'without stopping or changing direction', '', 'The path leads directly to the river.', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
