INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Less', 'less_us.mp3', 'determiner', 'B1', 'used with uncountable nouns to mean ‘a smaller amount of’', '', 'less something, less butter/time/importance', '', ARRAY[]::TEXT[]),
('Less', 'less_us.mp3', 'pronoun', 'B1', 'used with uncountable nouns to mean ‘a smaller amount of’', '', 'less something, less butter/time/importance', '', ARRAY[]::TEXT[]),
('Lesser', 'lesser_us.mp3', 'adjective', 'B1', 'not as great in size, amount or importance as something/somebody else', '', 'people of lesser importance', '', ARRAY[]::TEXT[]),
('Lesson', 'lesson_us.mp3', 'noun', 'B1', 'a period of time in which somebody is taught something', '', 'She gives piano lessons.', '', ARRAY[]::TEXT[]),
('Let', 'let_us.mp3', 'verb', 'B1', 'used for making suggestions or as a polite way of telling people what you want them to do', '', '‘Shall we check it again?’ ‘Yes, let''s.’', '', ARRAY[]::TEXT[]),
('Lethal', 'lethal_us.mp3', 'adjective', 'B1', 'causing or able to cause death', '', 'She had been given a lethal dose of poison.', '', ARRAY[]::TEXT[]),
('Letter', 'letter_us.mp3', 'noun', 'B1', 'a written, typed or printed message that is put in an envelope or attached to an email and sent to somebody', '', 'to write/send (somebody) a letter', '', ARRAY[]::TEXT[]),
('Level', 'level_us.mp3', 'adjective', 'B1', 'having a flat surface that does not slope', '', 'Pitch the tent on level ground.', '', ARRAY[]::TEXT[]),
('Level', 'level_us.mp3', 'noun', 'B1', 'the height of something in relation to the ground or to what it used to be', '', 'The cables are buried one metre below ground level.', '', ARRAY[]::TEXT[]),
('Level', 'level_us.mp3', 'verb', 'B1', 'to make something flat or smooth', '', 'level something out, The first coat of plaster levels out the surface of the wall.', '', ARRAY[]::TEXT[]),
('Liable', 'liable_us.mp3', 'adjective', 'B1', 'legally responsible for paying the cost of something', '', 'You will be liable for any damage caused.', '', ARRAY[]::TEXT[]),
('Liberal', 'liberal_us.mp3', 'adjective', 'B1', 'willing to understand and respect other people’s behaviour, opinions, etc., especially when they are different from your own; believing people should be able to choose how they behave', '', 'liberal attitudes/views/opinions', '', ARRAY[]::TEXT[]),
('Liberal', 'liberal_us.mp3', 'noun', 'B1', 'a person who understands and respects other people’s opinions and behaviour, especially when they are different from their own', '', 'He liked to think of himself as a liberal.', '', ARRAY[]::TEXT[]),
('Liberation', 'liberation_us.mp3', 'noun', 'B1', 'the act or process of freeing a country or a person from the control of somebody else', '', 'a war of liberation', '', ARRAY[]::TEXT[]),
('Liberty', 'liberty_us.mp3', 'noun', 'B1', 'freedom to live as you choose without too many limits from government or authority', '', 'the fight for justice and liberty', '', ARRAY[]::TEXT[]),
('Library', 'library_us.mp3', 'noun', 'B1', 'a building in which collections of books, newspapers, etc. and sometimes films and recorded music are kept for people to read, study or borrow', '', 'a public/university/school library', '', ARRAY[]::TEXT[]),
('Licence', 'licence_us.mp3', 'noun', 'B1', 'an official document that shows that permission has been given to do, own or use something', '', 'Applicants must hold a valid driving licence.', '', ARRAY[]::TEXT[]),
('License', 'license_us.mp3', 'verb', 'B1', 'to give somebody official permission to do, own, or use something', '', 'license something, The new drug has not yet been licensed in the US.', '', ARRAY[]::TEXT[]),
('Lie', 'lie_us.mp3', 'noun', 'B1', 'a statement made by somebody knowing that it is not true', '', 'to tell a lie', '', ARRAY[]::TEXT[]),
('Lie', 'lie_us.mp3', 'verb', 'B1', 'to be or put yourself in a flat position so that you are not standing or sitting', '', 'lie + adv./prep., to lie on your back/side/front', '', ARRAY[]::TEXT[]),
('Lie', 'lie_us.mp3', 'verb', 'B1', 'to say or write something that you know is not true', '', 'You could see from his face that he was lying.', '', ARRAY[]::TEXT[]),
('Life', 'life_us.mp3', 'noun', 'B1', 'the ability to breathe, grow, produce young, etc. that people, animals and plants have before they die and that objects do not have', '', 'This could mean the difference between life and death.', '', ARRAY[]::TEXT[]),
('Lifelong', 'lifelong_us.mp3', 'adjective', 'B1', 'lasting or existing all through your life', '', 'Paul became his lifelong friend.', '', ARRAY[]::TEXT[]),
('Lifestyle', 'lifestyle_us.mp3', 'noun', 'B1', 'the way in which a person or a group of people lives and works', '', 'Many people are trying to adopt a healthy lifestyle these days.', '', ARRAY[]::TEXT[]),
('Lifetime', 'lifetime_us.mp3', 'noun', 'B1', 'the length of time that somebody lives or that something lasts', '', 'a lifetime of experience', '', ARRAY[]::TEXT[]),
('Lift', 'lift_us.mp3', 'noun', 'B1', 'a machine that carries people or goods up and down to different levels in a building or a mine', '', 'It''s on the sixth floor—let''s take the lift.', '', ARRAY[]::TEXT[]),
('Lift', 'lift_us.mp3', 'verb', 'B1', 'to raise somebody/something or be raised to a higher position or level', '', 'lift somebody/something, I lifted the lid of the box and peered in.', '', ARRAY[]::TEXT[]),
('Light', 'light_us.mp3', 'adjective', 'B1', 'pale in colour', '', 'He''s got light blue eyes.', '', ARRAY[]::TEXT[]),
('Light', 'light_us.mp3', 'noun', 'B1', 'the energy from the sun, a lamp, etc. that makes it possible to see things', '', 'bright/dim light', '', ARRAY[]::TEXT[]),
('Light', 'light_us.mp3', 'verb', 'B1', 'to make something start to burn', '', 'She lit a candle.', '', ARRAY[]::TEXT[]),
('Lighting', 'lighting_us.mp3', 'noun', 'B1', 'the arrangement or type of light in a place', '', 'electric/natural lighting', '', ARRAY[]::TEXT[]),
('Like', 'like_us.mp3', 'noun', 'B1', 'the things that you like', '', 'We all have different likes and dislikes.', '', ARRAY[]::TEXT[]),
('Like', 'like_us.mp3', 'preposition', 'B1', 'similar to somebody/something', '', 'She''s wearing a dress like mine.', '', ARRAY[]::TEXT[]),
('Like', 'like_us.mp3', 'verb', 'B1', 'to find somebody/something pleasant, attractive or of a good enough standard; to enjoy something', '', 'like somebody/something, She''s nice. I like her.', '', ARRAY[]::TEXT[]),
('Likelihood', 'likelihood_us.mp3', 'noun', 'B1', 'the chance of something happening; how likely something is to happen', '', 'There is very little likelihood of that happening.', '', ARRAY[]::TEXT[]),
('Likely', 'likely_us.mp3', 'adjective', 'B1', 'having a good chance of happening or being something; probable or expected', '', 'the most likely explanation/outcome/scenario', '', ARRAY[]::TEXT[]),
('Likewise', 'likewise_us.mp3', 'adverb', 'B1', 'the same; in a similar way', '', 'He voted for the change and he expected his colleagues to do likewise.', '', ARRAY[]::TEXT[]),
('Limb', 'limb_us.mp3', 'noun', 'B1', 'an arm or a leg; a similar part of an animal, such as a wing', '', 'an artificial limb', '', ARRAY[]::TEXT[]),
('Limit', 'limit_us.mp3', 'noun', 'B1', 'the greatest or smallest amount of something that is allowed', '', 'They imposed a strict spending limit.', '', ARRAY[]::TEXT[]),
('Limit', 'limit_us.mp3', 'verb', 'B1', 'to stop something from increasing beyond a particular amount or level', '', 'measures to limit carbon dioxide emissions', '', ARRAY[]::TEXT[]),
('Limitation', 'limitation_us.mp3', 'noun', 'B1', 'the act or process of limiting or controlling somebody/something', '', 'They would resist any limitation of their powers.', '', ARRAY[]::TEXT[]),
('Limited', 'limited_us.mp3', 'adjective', 'B1', 'not very great in amount or extent', '', 'We are doing our best with the limited resources available.', '', ARRAY[]::TEXT[]),
('Line', 'line_us.mp3', 'noun', 'B1', 'a long, thin mark on a surface', '', 'a straight/solid/dotted/dashed line', '', ARRAY[]::TEXT[]),
('Line', 'line_us.mp3', 'verb', 'B1', 'to cover the inside of something with a layer of another material, especially to keep it clean or make it stronger', '', 'Butter and line a 25 cm cake tin.', '', ARRAY[]::TEXT[]),
('Line-up', 'line-up_us.mp3', 'noun', 'B1', 'the people who are going to take part in a particular event', '', 'an impressive line-up of speakers', '', ARRAY[]::TEXT[]),
('Linear', 'linear_us.mp3', 'adjective', 'B1', 'of or in lines', '', 'In his art he broke the laws of scientific linear perspective.', '', ARRAY[]::TEXT[]),
('Linger', 'linger_us.mp3', 'verb', 'B1', 'to continue to exist for longer than expected', '', 'The faint smell of her perfume lingered in the room.', '', ARRAY[]::TEXT[]),
('Link', 'link_us.mp3', 'noun', 'B1', 'a connection between two or more people or things', '', 'link between A and B, Police suspect there may be a link between the two murders.', '', ARRAY[]::TEXT[]),
('Link', 'link_us.mp3', 'verb', 'B1', 'to make a physical or electronic connection between one object, machine, place, etc. and another', '', 'link A to B, The video cameras are linked to a powerful computer.', '', ARRAY[]::TEXT[]),
('Lion', 'lion_us.mp3', 'noun', 'B1', 'a large, powerful animal of the cat family that hunts in groups and lives in parts of Africa and southern Asia. Lions have yellow-brown fur and the male has a mane (= long, thick hair round its neck).', '', 'The lion shook its mane and roared.', '', ARRAY[]::TEXT[]),
('Lip', 'lip_us.mp3', 'noun', 'B1', 'either of the two soft edges at the opening to the mouth', '', 'The assistant pursed her lips.', '', ARRAY[]::TEXT[]),
('Liquid', 'liquid_us.mp3', 'adjective', 'B1', 'in the form of a liquid; not a solid or a gas', '', 'liquid nitrogen', '', ARRAY[]::TEXT[]),
('Liquid', 'liquid_us.mp3', 'noun', 'B1', 'a substance that flows freely and is not a solid or a gas, for example water or oil', '', 'She poured the dark brown liquid down the sink.', '', ARRAY[]::TEXT[]),
('List', 'list_us.mp3', 'noun', 'B1', 'a series of names, items, figures, etc., especially when they are written or printed', '', 'The guest list includes numerous celebrities.', '', ARRAY[]::TEXT[]),
('List', 'list_us.mp3', 'verb', 'B1', 'to write a list of things in a particular order', '', 'We were asked to list our ten favourite songs.', '', ARRAY[]::TEXT[]),
('Listen', 'listen_us.mp3', 'verb', 'B1', 'to pay attention to somebody/something that you can hear', '', 'Listen! What''s that noise? Can you hear it?', '', ARRAY[]::TEXT[]),
('Listener', 'listener_us.mp3', 'noun', 'B1', 'a person who listens', '', 'a good listener (= somebody who you can rely on to listen with attention or sympathy)', '', ARRAY[]::TEXT[]),
('Listing', 'listing_us.mp3', 'noun', 'B1', 'a list, especially an official or published list of people or things, often arranged in alphabetical order', '', 'a comprehensive listing of all airlines', '', ARRAY[]::TEXT[]),
('Literacy', 'literacy_us.mp3', 'noun', 'B1', 'the ability to read and write', '', 'a campaign to promote adult literacy', '', ARRAY[]::TEXT[]),
('Literally', 'literally_us.mp3', 'adverb', 'B1', 'in a literal way', '', 'The word ‘planet’ literally means ‘wandering body’.', '', ARRAY[]::TEXT[]),
('Literary', 'literary_us.mp3', 'adjective', 'B1', 'connected with literature', '', 'literary criticism/theory', '', ARRAY[]::TEXT[]),
('Literature', 'literature_us.mp3', 'noun', 'B1', 'pieces of writing that are valued as works of art, especially novels, plays and poems (in contrast to technical books and newspapers, magazines, etc.)', '', 'English/American/French literature', '', ARRAY[]::TEXT[]),
('Litre', 'litre_us.mp3', 'noun', 'B1', 'a unit for measuring volume, equal to 1.76 British pints or 2.11 American pints', '', '3 litres of water', '', ARRAY[]::TEXT[]),
('Litter', 'litter_us.mp3', 'noun', 'B1', 'small pieces of rubbish such as paper, cans and bottles, that people have left lying in a public place', '', 'There will be fines for people who drop litter.', '', ARRAY[]::TEXT[]),
('Little', 'little_us.mp3', 'adjective', 'B1', 'not big; small; smaller than others', '', 'a little house', '', ARRAY[]::TEXT[]),
('Little', 'little_us.mp3', 'adverb', 'B1', 'to a small degree', '', 'She seemed a little afraid of going inside.', '', ARRAY[]::TEXT[]),
('Little', 'little_us.mp3', 'determiner', 'B1', 'used with uncountable nouns to mean ‘a small amount’, ‘some’', '', 'a little milk/sugar/tea', '', ARRAY[]::TEXT[]),
('Little', 'little_us.mp3', 'pronoun', 'B1', 'used with uncountable nouns to mean ‘a small amount’, ‘some’', '', 'a little milk/sugar/tea', '', ARRAY[]::TEXT[]),
('Live', 'live_us.mp3', 'adjective', 'B1', 'living; not dead', '', 'live animals', '', ARRAY[]::TEXT[]),
('Live', 'live_us.mp3', 'adverb', 'B1', 'broadcast at the time of an actual event; played or recorded at an actual performance', '', 'The show is going out live.', '', ARRAY[]::TEXT[]),
('Live', 'live_us.mp3', 'verb', 'B1', 'to have your home in a particular place', '', 'to live in a house/a flat/an apartment', '', ARRAY[]::TEXT[]),
('Lively', 'lively_us.mp3', 'adjective', 'B1', 'full of life and energy; active and enthusiastic', '', 'an intelligent and lively young woman', '', ARRAY[]::TEXT[]),
('Liver', 'liver_us.mp3', 'noun', 'B1', 'a large organ in the body that cleans the blood and produces bile', '', 'liver disease', '', ARRAY[]::TEXT[]),
('Living', 'living_us.mp3', 'adjective', 'B1', 'alive now', '', 'all living things', '', ARRAY[]::TEXT[]),
('Living', 'living_us.mp3', 'noun', 'B1', 'money to buy the things that you need in life', '', 'She earns her living as a freelance journalist.', '', ARRAY[]::TEXT[]),
('Load', 'load_us.mp3', 'noun', 'B1', 'something that is being carried (usually in large amounts) by a person, vehicle, etc.', '', 'The trucks waited at the warehouse to pick up their loads.', '', ARRAY[]::TEXT[]),
('Load', 'load_us.mp3', 'verb', 'B1', 'to put a large quantity of things or people onto or into something', '', 'load something, We loaded the car in ten minutes.', '', ARRAY[]::TEXT[]),
('Loan', 'loan_us.mp3', 'noun', 'B1', 'money that an organization such as a bank lends and somebody borrows', '', 'to take out/repay a loan (= to borrow money/pay it back)', '', ARRAY[]::TEXT[]),
('Lobby', 'lobby_us.mp3', 'noun', 'B1', 'a large area inside the entrance of a public building where people can meet and wait', '', 'a hotel lobby', '', ARRAY[]::TEXT[]),
('Lobby', 'lobby_us.mp3', 'verb', 'B1', 'to try to influence a politician or the government and, for example, persuade them to support or oppose a change in the law', '', 'Farmers will lobby Congress for higher subsidies.', '', ARRAY[]::TEXT[]),
('Local', 'local_us.mp3', 'adjective', 'B1', 'belonging to or connected with the particular place or area that you are talking about or with the place where you live', '', 'local people/residents/businesses', '', ARRAY[]::TEXT[]),
('Local', 'local_us.mp3', 'noun', 'B1', 'a person who lives in a particular place or district', '', 'The locals are very friendly.', '', ARRAY[]::TEXT[]),
('Locate', 'locate_us.mp3', 'verb', 'B1', 'to find the exact position of somebody/something', '', 'The mechanic located the fault immediately.', '', ARRAY[]::TEXT[]),
('Located', 'located_us.mp3', 'adjective', 'B1', 'if something is located in a particular place, it exists there or has been put there', '', 'a small town located 30 miles south of Chicago', '', ARRAY[]::TEXT[]),
('Location', 'location_us.mp3', 'noun', 'B1', 'a place where something happens or exists; the position of something', '', 'a honeymoon in a secret location', '', ARRAY[]::TEXT[]),
('Lock', 'lock_us.mp3', 'noun', 'B1', 'a device that keeps a door, window, box, etc. shut, usually needing a key to open it', '', 'She turned the key in the lock.', '', ARRAY[]::TEXT[]),
('Lock', 'lock_us.mp3', 'verb', 'B1', 'to fasten something with a lock; to be fastened with a lock', '', 'Did you lock the door?', '', ARRAY[]::TEXT[]),
('Log', 'log_us.mp3', 'noun', 'B1', 'a thick piece of wood that is cut from or has fallen from a tree', '', 'logs for the fire', '', ARRAY[]::TEXT[]),
('Log', 'log_us.mp3', 'verb', 'B1', 'to put information in an official record or write a record of events', '', 'The police log all phone calls.', '', ARRAY[]::TEXT[]),
('Logic', 'logic_us.mp3', 'noun', 'B1', 'a way of thinking or explaining something', '', 'I fail to see the logic behind his argument.', '', ARRAY[]::TEXT[]),
('Logical', 'logical_us.mp3', 'adjective', 'B1', 'seeming natural, reasonable or sensible', '', 'It was a logical conclusion from the child''s point of view.', '', ARRAY[]::TEXT[]),
('Logo', 'logo_us.mp3', 'noun', 'B1', 'a printed design or symbol that a company or an organization uses as its special sign', '', 'All over the world there are red and white paper cups bearing the company logo.', '', ARRAY[]::TEXT[]),
('Lonely', 'lonely_us.mp3', 'adjective', 'B1', 'unhappy because you have no friends or people to talk to', '', 'She lives alone and often feels lonely.', '', ARRAY[]::TEXT[]),
('Long', 'long_us.mp3', 'adjective', 'B1', 'measuring or covering a great length or distance, or a greater length or distance than usual', '', 'She had long dark hair.', '', ARRAY[]::TEXT[]),
('Long', 'long_us.mp3', 'adverb', 'B1', 'for a long time', '', 'Have you been here long?', '', ARRAY[]::TEXT[]),
('Long-standing', 'long-standing_us.mp3', 'adjective', 'B1', 'that has existed or lasted for a long time', '', 'a long-standing relationship', '', ARRAY[]::TEXT[]),
('Long-term', 'long-term_us.mp3', 'adjective', 'B1', 'lasting or having an effect over a long period of time', '', 'Our long-term goal is to lower operating costs by 10 per cent.', '', ARRAY[]::TEXT[]),
('Long-term', 'long-term_us.mp3', 'adverb', 'B1', 'over a long period of time', '', 'to benefit/affect somebody long-term', '', ARRAY[]::TEXT[]),
('Long-time', 'long-time_us.mp3', 'adjective', 'B1', 'having been the particular thing mentioned for a long time', '', 'his long-time colleague', '', ARRAY[]::TEXT[]),
('Look', 'look_us.mp3', 'noun', 'B1', 'an act of looking at somebody/something', '', 'look at somebody/something, Here, have a look at this.', '', ARRAY[]::TEXT[]),
('Look', 'look_us.mp3', 'verb', 'B1', 'to turn your eyes in a particular direction', '', 'Look closely and tell me what you see.', '', ARRAY[]::TEXT[]),
('Loom', 'loom_us.mp3', 'verb', 'B1', 'to appear as a large shape that is not clear, especially in a frightening way', '', 'A dark shape loomed up ahead of us.', '', ARRAY[]::TEXT[]),
('Loop', 'loop_us.mp3', 'noun', 'B1', 'a shape like a curve or circle made by a line curving right round', '', 'The road went in a huge loop around the lake.', '', ARRAY[]::TEXT[]),
('Loose', 'loose_us.mp3', 'adjective', 'B1', 'not securely fixed where it should be; able to become separated from something', '', 'a loose button/tooth', '', ARRAY[]::TEXT[]),
('Lord', 'lord_us.mp3', 'noun', 'B1', '(in the UK) a man of high rank in the nobility (= people of high social class), or somebody who has been given the title ‘lord’ as an honour', '', 'She''s married to a lord.', '', ARRAY[]::TEXT[]),
('Lorry', 'lorry_us.mp3', 'noun', 'B1', 'a large vehicle for carrying heavy loads by road', '', 'a lorry driver', '', ARRAY[]::TEXT[]),
('Lose', 'lose_us.mp3', 'verb', 'B1', 'to be unable to find something/somebody', '', 'I''ve lost my keys.', '', ARRAY[]::TEXT[]),
('Loss', 'loss_us.mp3', 'noun', 'B1', 'the state of no longer having something or as much of something; the process that leads to this', '', 'I want to report the loss of a package.', '', ARRAY[]::TEXT[]),
('Lost', 'lost_us.mp3', 'adjective', 'B1', 'unable to find your way; not knowing where you are', '', 'We always get lost in London.', '', ARRAY[]::TEXT[]),
('Lot', 'lot_us.mp3', 'adverb', 'B1', 'used with verbs to mean ‘a great amount’', '', 'I care a lot about you.', '', ARRAY[]::TEXT[]),
('Lot', 'lot_us.mp3', 'determiner', 'B1', 'a large number or amount of somebody/something', '', 'What a lot of presents!', '', ARRAY[]::TEXT[]),
('Lot', 'lot_us.mp3', 'pronoun', 'B1', 'a large number or amount', '', '‘How many do you need?’ ‘A lot.’', '', ARRAY[]::TEXT[]),
('Lottery', 'lottery_us.mp3', 'noun', 'B1', 'a way of raising money for a government, charity, etc. by selling tickets that have different numbers on them that people have chosen. Numbers are then chosen by chance and the people who have those numbers on their tickets win prizes.', '', 'the national/state lottery', '', ARRAY[]::TEXT[]),
('Loud', 'loud_us.mp3', 'adjective', 'B1', 'making a lot of noise', '', 'loud laughter', '', ARRAY[]::TEXT[]),
('Loud', 'loud_us.mp3', 'adverb', 'B1', 'in a way that makes a lot of noise or can be easily heard', '', 'Do you have to play that music so loud?', '', ARRAY[]::TEXT[]),
('Loudly', 'loudly_us.mp3', 'adverb', 'B1', 'in a way that makes a lot of noise', '', 'She screamed as loudly as she could.', '', ARRAY[]::TEXT[]),
('Love', 'love_us.mp3', 'noun', 'B1', 'a very strong feeling of liking and caring for somebody/something, especially a member of your family or a friend', '', 'She has earned the love and respect of many people.', '', ARRAY[]::TEXT[]),
('Love', 'love_us.mp3', 'verb', 'B1', 'to have very strong feelings of liking and caring for somebody', '', 'I love you.', '', ARRAY[]::TEXT[]),
('Lovely', 'lovely_us.mp3', 'adjective', 'B1', 'beautiful; attractive', '', 'She looked particularly lovely that night.', '', ARRAY[]::TEXT[]),
('Low', 'low_us.mp3', 'adjective', 'B1', 'not high or tall; not far above the ground', '', 'a low wall/building/table', '', ARRAY[]::TEXT[]),
('Low', 'low_us.mp3', 'adverb', 'B1', 'in or into a low position, not far above the ground', '', 'to crouch/bend low', '', ARRAY[]::TEXT[]),
('Low', 'low_us.mp3', 'noun', 'B1', 'a low level or point; a low figure', '', 'The temperature reached a record low in London last night.', '', ARRAY[]::TEXT[]),
('Lower', 'lower_us.mp3', 'verb', 'B1', 'to reduce something or to become less in value, quality, etc.', '', 'lower something, He lowered his voice to a whisper.', '', ARRAY[]::TEXT[]),
('Loyal', 'loyal_us.mp3', 'adjective', 'B1', 'remaining constant in your support of somebody/something', '', 'a loyal friend/supporter', '', ARRAY[]::TEXT[]),
('Loyalty', 'loyalty_us.mp3', 'noun', 'B1', 'the quality of being constant in your support of somebody/something', '', 'Can I count on your loyalty?', '', ARRAY[]::TEXT[]),
('Luck', 'luck_us.mp3', 'noun', 'B1', 'good things that happen to you by chance, not because of your own efforts or abilities', '', 'with (any) luck, With any luck, we''ll be home before dark.', '', ARRAY[]::TEXT[]),
('Lucky', 'lucky_us.mp3', 'adjective', 'B1', 'having good luck', '', 'lucky to do something, His friend was killed and he knows he is lucky to be alive.', '', ARRAY[]::TEXT[]),
('Lunch', 'lunch_us.mp3', 'noun', 'B1', 'a meal eaten in the middle of the day', '', 'She''s gone to lunch.', '', ARRAY[]::TEXT[]),
('Lung', 'lung_us.mp3', 'noun', 'B1', 'either of the two organs in the chest that you use for breathing', '', 'Her father died of lung cancer.', '', ARRAY[]::TEXT[]),
('Luxury', 'luxury_us.mp3', 'adjective', 'B1', 'expensive and of very high quality', '', 'a luxury hotel/car/apartment', '', ARRAY[]::TEXT[]),
('Luxury', 'luxury_us.mp3', 'noun', 'B1', 'the fact of enjoying special and expensive things, particularly food and drink, clothes and places', '', 'a life of unimaginable luxury', '', ARRAY[]::TEXT[]),
('Lyric', 'lyric_us.mp3', 'noun', 'B1', 'the words of a popular song', '', 'music and lyrics by Rodgers and Hart', '', ARRAY[]::TEXT[]),
('Machine', 'machine_us.mp3', 'noun', 'B1', 'a piece of equipment with many parts that work together to do a particular task. The power used to work a machine may be electricity, steam, gas, etc. or human power.', '', 'Machines have replaced human labour in many industries.', '', ARRAY[]::TEXT[]),
('Machinery', 'machinery_us.mp3', 'noun', 'B1', 'machines as a group, especially large ones', '', 'agricultural/industrial machinery', '', ARRAY[]::TEXT[]),
('Mad', 'mad_us.mp3', 'adjective', 'B1', 'very stupid; not at all sensible', '', 'You must be mad to risk it.', '', ARRAY[]::TEXT[]),
('Magazine', 'magazine_us.mp3', 'noun', 'B1', 'a type of large thin book with a paper cover that you can buy every week or month, containing articles, photographs, etc., often on a particular topic; a similar collection of articles, etc. that appears regularly online', '', 'a weekly/monthly magazine', '', ARRAY[]::TEXT[]),
('Magic', 'magic_us.mp3', 'adjective', 'B1', 'having or using special powers to make impossible things happen or seem to happen', '', 'a magic spell/charm/potion', '', ARRAY[]::TEXT[]),
('Magic', 'magic_us.mp3', 'noun', 'B1', 'the secret power of appearing to make impossible things happen by saying special words or doing special things', '', 'Do you believe in magic?', '', ARRAY[]::TEXT[]),
('Magical', 'magical_us.mp3', 'adjective', 'B1', 'containing magic; used in magic', '', 'magical powers', '', ARRAY[]::TEXT[]),
('Magistrate', 'magistrate_us.mp3', 'noun', 'B1', 'an official who acts as a judge in the lowest courts of law', '', 'to come up before the magistrates', '', ARRAY[]::TEXT[]),
('Magnetic', 'magnetic_us.mp3', 'adjective', 'B1', 'behaving like a magnet; that can be attracted by a magnet', '', 'magnetic materials', '', ARRAY[]::TEXT[]),
('Magnificent', 'magnificent_us.mp3', 'adjective', 'B1', 'extremely attractive and impressive; deserving praise', '', 'The Taj Mahal is a magnificent building.', '', ARRAY[]::TEXT[]),
('Magnitude', 'magnitude_us.mp3', 'noun', 'B1', 'the great size or importance of something; the degree to which something is large or important', '', 'We did not realize the magnitude of the problem.', '', ARRAY[]::TEXT[]),
('Mail', 'mail_us.mp3', 'noun', 'B1', 'the official system used for sending and delivering letters, packages, etc.', '', 'a mail service/train/van', '', ARRAY[]::TEXT[]),
('Mail', 'mail_us.mp3', 'verb', 'B1', 'to send something to somebody using the postal system', '', 'mail something (to somebody/something), Don''t forget to mail that letter to your mother.', '', ARRAY[]::TEXT[]),
('Main', 'main_us.mp3', 'adjective', 'B1', 'being the largest or most important of its kind', '', 'Be careful crossing the main road.', '', ARRAY[]::TEXT[]),
('Mainland', 'mainland_us.mp3', 'noun', 'B1', 'the main area of land of a country or region, not including any islands near to it', '', 'to/from the mainland, a boat to/from the mainland', '', ARRAY[]::TEXT[]),
('Mainly', 'mainly_us.mp3', 'adverb', 'B1', 'more than anything else; also used to talk about the most important reason for something', '', 'They eat mainly fruit and nuts.', '', ARRAY[]::TEXT[]),
('Mainstream', 'mainstream_us.mp3', 'adjective', 'B1', 'considered normal because it reflects what is done or accepted by most people', '', 'mainstream culture/politics', '', ARRAY[]::TEXT[]),
('Mainstream', 'mainstream_us.mp3', 'noun', 'B1', 'the ideas and opinions that are thought to be normal because they are shared by most people; the people whose ideas and opinions are most accepted', '', 'His radical views place him outside the mainstream of American politics.', '', ARRAY[]::TEXT[]),
('Maintain', 'maintain_us.mp3', 'verb', 'B1', 'to make something continue at the same level, standard, etc.', '', 'to maintain law and order/standards/a balance/control', '', ARRAY[]::TEXT[]),
('Maintenance', 'maintenance_us.mp3', 'noun', 'B1', 'the act of keeping something in good condition by checking or repairing it regularly', '', 'The school pays for heating and the maintenance of the buildings.', '', ARRAY[]::TEXT[]),
('Major', 'major_us.mp3', 'adjective', 'B1', 'very large or important', '', 'a major road', '', ARRAY[]::TEXT[]),
('Majority', 'majority_us.mp3', 'noun', 'B1', 'the largest part of a group of people or things', '', 'majority (of somebody/something), The majority of people interviewed prefer TV to radio.', '', ARRAY[]::TEXT[]),
('Make', 'make_us.mp3', 'noun', 'B1', 'the name or type of a machine, piece of equipment, etc. that is made by a particular company', '', 'make of something, What make of car does he drive?', '', ARRAY[]::TEXT[]),
('Make', 'make_us.mp3', 'verb', 'B1', 'to create or prepare something by combining materials or putting parts together', '', 'make something, to make a table/dress/cake', '', ARRAY[]::TEXT[]),
('Make-up', 'make-up_us.mp3', 'noun', 'B1', 'coloured substances used on the skin to make yourself look more attractive or to change your appearance', '', 'eye make-up', '', ARRAY[]::TEXT[]),
('Making', 'making_us.mp3', 'noun', 'B1', 'the act or process of making or producing something', '', 'strategic decision-making', '', ARRAY[]::TEXT[]),
('Male', 'male_us.mp3', 'adjective', 'B1', 'being a man or boy', '', 'a male friend/colleague/partner', '', ARRAY[]::TEXT[]),
('Male', 'male_us.mp3', 'noun', 'B1', 'a male person, animal or plant', '', 'The male of the species has a white tail.', '', ARRAY[]::TEXT[]),
('Mall', 'mall_us.mp3', 'noun', 'B1', 'a large building or covered area that has many shops, restaurants, etc. inside it', '', 'Let''s go to the mall.', '', ARRAY[]::TEXT[]),
('Man', 'man_us.mp3', 'noun', 'B1', 'an adult male human', '', 'a good-looking young man', '', ARRAY[]::TEXT[]),
('Manage', 'manage_us.mp3', 'verb', 'B1', 'to control or be in charge of a business, a team, an organization, land, etc.', '', 'to manage a business/factory/bank/hotel/soccer team', '', ARRAY[]::TEXT[]),
('Management', 'management_us.mp3', 'noun', 'B1', 'the activity of running and controlling a business or similar organization', '', 'a career in management', '', ARRAY[]::TEXT[]),
('Manager', 'manager_us.mp3', 'noun', 'B1', 'a person who is in charge of running a business, a shop or a similar organization or part of one', '', 'a bank/hotel manager', '', ARRAY[]::TEXT[]),
('Mandate', 'mandate_us.mp3', 'noun', 'B1', 'the authority to do something, given to a government or other organization by the people who vote for it in an election', '', 'It is undemocratic to govern an area without an electoral mandate.', '', ARRAY[]::TEXT[]),
('Mandatory', 'mandatory_us.mp3', 'adjective', 'B1', 'required by law', '', 'The offence carries a mandatory life sentence.', '', ARRAY[]::TEXT[]),
('Manifest', 'manifest_us.mp3', 'verb', 'B1', 'to show something clearly, especially a feeling, an attitude or a quality', '', 'Social tensions were manifested in the recent political crisis.', '', ARRAY[]::TEXT[]),
('Manipulate', 'manipulate_us.mp3', 'verb', 'B1', 'to control or influence somebody/something, often in a dishonest way so that they do not realize it', '', 'manipulate somebody/something, She uses her charm to manipulate people.', '', ARRAY[]::TEXT[]),
('Manipulation', 'manipulation_us.mp3', 'noun', 'B1', 'behaviour that controls or influences somebody/something, often in a dishonest way so that they do not realize it', '', 'Advertising like this is a cynical manipulation of the elderly.', '', ARRAY[]::TEXT[]),
('Manner', 'manner_us.mp3', 'noun', 'B1', 'behaviour that is considered to be polite in a particular society or culture', '', 'to have good/bad manners', '', ARRAY[]::TEXT[]),
('Manufacture', 'manufacture_us.mp3', 'verb', 'B1', 'to make goods in large quantities, using machines', '', 'manufactured goods', '', ARRAY[]::TEXT[]),
('Manufacturing', 'manufacturing_us.mp3', 'noun', 'B1', 'the business or industry of producing goods in large quantities in factories, etc.', '', 'Many jobs in manufacturing were lost during the recession.', '', ARRAY[]::TEXT[]),
('Manuscript', 'manuscript_us.mp3', 'noun', 'B1', 'a copy of a book, piece of music, etc. before it has been printed', '', 'an unpublished/original manuscript', '', ARRAY[]::TEXT[]),
('Many', 'many_us.mp3', 'determiner', 'B1', 'used with plural nouns and verbs, especially in negative sentences or in more formal English, to mean ‘a large number of’. Also used in questions to ask about the size of a number, and with ‘as’, ‘so’ and ‘too’.', '', 'We don''t have very many copies left.', '', ARRAY[]::TEXT[]),
('Many', 'many_us.mp3', 'pronoun', 'B1', 'used with plural nouns and verbs, especially in negative sentences or in more formal English, to mean ‘a large number of’. Also used in questions to ask about the size of a number, and with ‘as’, ‘so’ and ‘too’.', '', 'We don''t have very many copies left.', '', ARRAY[]::TEXT[]),
('Map', 'map_us.mp3', 'noun', 'B1', 'a drawing or plan of the earth’s surface or part of it, showing countries, towns, rivers, etc.', '', 'a map of France', '', ARRAY[]::TEXT[]),
('Map', 'map_us.mp3', 'verb', 'B1', 'to make a map of an area', '', 'an unexplored region that has not yet been mapped', '', ARRAY[]::TEXT[]),
('Marathon', 'marathon_us.mp3', 'noun', 'B1', 'a long running race of about 42 kilometres or 26 miles', '', 'the London marathon', '', ARRAY[]::TEXT[]),
('March', 'March_us.mp3', 'noun', 'B1', 'the 3rd month of the year, between February and April', '', 'She was born in March.', '', ARRAY[]::TEXT[]),
('March', 'march_us.mp3', 'noun', 'B1', 'an organized walk by many people from one place to another, in order to protest about something, or to express their opinions', '', 'protest marches', '', ARRAY[]::TEXT[]),
('March', 'march_us.mp3', 'verb', 'B1', 'to walk with stiff regular steps like a soldier', '', 'Quick march! (= the order to start marching)', '', ARRAY[]::TEXT[]),
('Margin', 'margin_us.mp3', 'noun', 'B1', 'the empty space at the side of a written or printed page', '', 'the left-hand/right-hand margin', '', ARRAY[]::TEXT[]),
('Marginal', 'marginal_us.mp3', 'adjective', 'B1', 'small and not important', '', 'a marginal improvement in weather conditions', '', ARRAY[]::TEXT[]),
('Marine', 'marine_us.mp3', 'adjective', 'B1', 'connected with the sea and the creatures and plants that live there', '', 'marine life', '', ARRAY[]::TEXT[]),
('Mark', 'mark_us.mp3', 'noun', 'B1', 'a written or printed symbol that is used as a sign of something, for example the quality of something or who made or owns it', '', 'punctuation marks', '', ARRAY[]::TEXT[]),
('Mark', 'mark_us.mp3', 'verb', 'B1', 'to write or draw a symbol, line, etc. on something in order to give information about it', '', 'mark something, The flood level is marked by a white line on the wall.', '', ARRAY[]::TEXT[]),
('Marker', 'marker_us.mp3', 'noun', 'B1', 'an object or a sign that shows the position of something', '', 'a boundary marker', '', ARRAY[]::TEXT[]),
('Market', 'market_us.mp3', 'noun', 'B1', 'an occasion when people buy and sell goods; the open area or building where they meet to do this', '', 'a fruit/flower/fish market', '', ARRAY[]::TEXT[]),
('Market', 'market_us.mp3', 'verb', 'B1', 'to advertise a product in a particular way in order to make people want it', '', 'market something, The company utilizes every media tool available to market its products.', '', ARRAY[]::TEXT[]),
('Marketing', 'marketing_us.mp3', 'noun', 'B1', 'the activity of presenting, advertising and selling a company’s products or services in the best possible way', '', 'a marketing campaign/strategy', '', ARRAY[]::TEXT[]),
('Marketplace', 'marketplace_us.mp3', 'noun', 'B1', 'the activity of competing with other companies to buy and sell goods, services, etc.', '', 'Companies must be able to survive in the marketplace.', '', ARRAY[]::TEXT[]),
('Marriage', 'marriage_us.mp3', 'noun', 'B1', 'the legal relationship between two people who are married to each other', '', 'a happy/an unhappy marriage', '', ARRAY[]::TEXT[]),
('Married', 'married_us.mp3', 'adjective', 'B1', 'having a husband or wife', '', 'a married man/woman', '', ARRAY[]::TEXT[]),
('Marry', 'marry_us.mp3', 'verb', 'B1', 'to become the husband or wife of somebody; to get married to somebody', '', 'marry (somebody), She married a German.', '', ARRAY[]::TEXT[]),
('Mask', 'mask_us.mp3', 'noun', 'B1', 'something that you wear over your face to hide it, or to frighten or entertain other people', '', 'The robbers wore stocking masks.', '', ARRAY[]::TEXT[]),
('Mass', 'mass_us.mp3', 'adjective', 'B1', 'affecting or involving a large number of people or things', '', 'The world faces the tremendous problem of mass unemployment.', '', ARRAY[]::TEXT[]),
('Mass', 'mass_us.mp3', 'noun', 'B1', 'a large amount of a substance that does not have a definite shape or form', '', 'She saw a large dark mass in the water.', '', ARRAY[]::TEXT[]),
('Massacre', 'massacre_us.mp3', 'noun', 'B1', 'the killing of a large number of people especially in a cruel way', '', 'the bloody massacre of innocent civilians', '', ARRAY[]::TEXT[]),
('Massive', 'massive_us.mp3', 'adjective', 'B1', 'very large, heavy and solid', '', 'a massive rock', '', ARRAY[]::TEXT[]),
('Master', 'master_us.mp3', 'noun', 'B1', 'a man who has people working for him, often as servants in his home', '', 'They lived in fear of their master.', '', ARRAY[]::TEXT[]),
('Master', 'master_us.mp3', 'verb', 'B1', 'to learn or understand something completely', '', 'She never completely mastered the art of lip-reading.', '', ARRAY[]::TEXT[]),
('Match', 'match_us.mp3', 'noun', 'B1', 'a sports event where people or teams compete against each other', '', '(British English), a football match', '', ARRAY[]::TEXT[]),
('Match', 'match_us.mp3', 'verb', 'B1', 'to find somebody/something that goes together with or is connected with another person or thing', '', 'match A and B, Match the words and pictures.', '', ARRAY[]::TEXT[]),
('Matching', 'matching_us.mp3', 'adjective', 'B1', 'having the same colour, pattern, style, etc. and therefore looking attractive together', '', 'The two sisters wore matching outfits.', '', ARRAY[]::TEXT[]),
('Mate', 'mate_us.mp3', 'noun', 'B1', 'a friend', '', 'They''ve been best mates since school.', '', ARRAY[]::TEXT[]),
('Mate', 'mate_us.mp3', 'verb', 'B1', 'to have sex in order to produce young', '', 'Do foxes ever mate with dogs?', '', ARRAY[]::TEXT[]),
('Material', 'material_us.mp3', 'adjective', 'B1', 'connected with money, possessions, etc. rather than with the needs of the mind or spirit', '', 'material possessions/wealth', '', ARRAY[]::TEXT[]),
('Material', 'material_us.mp3', 'noun', 'B1', 'a substance that things can be made from', '', 'building materials (= bricks, sand, glass, etc.)', '', ARRAY[]::TEXT[]),
('Mathematical', 'mathematical_us.mp3', 'adjective', 'B1', 'connected with or involving mathematics', '', 'mathematical calculations/problems/models', '', ARRAY[]::TEXT[]),
('Mathematics', 'mathematics_us.mp3', 'noun', 'B1', 'the science of numbers and shapes. Branches of mathematics include arithmetic, algebra, geometry and trigonometry.', '', 'the school mathematics curriculum', '', ARRAY[]::TEXT[]),
('Maths', 'maths_us.mp3', 'noun', 'B1', 'mathematics, especially as a subject in school', '', 'The core subjects are English, maths and science.', '', ARRAY[]::TEXT[]),
('Matter', 'matter_us.mp3', 'noun', 'B1', 'used (to ask) if somebody is upset, unhappy, etc. or if there is a problem', '', 'What''s the matter? Is there something wrong?', '', ARRAY[]::TEXT[]),
('Matter', 'matter_us.mp3', 'verb', 'B1', 'to be important or have an important effect on somebody/something', '', '‘I''m afraid I forgot that book again.’ ‘It doesn''t matter (= it is not important enough to worry about).’', '', ARRAY[]::TEXT[]),
('Mature', 'mature_us.mp3', 'adjective', 'B1', 'behaving in a sensible way, like an adult', '', 'Jane is very mature for her age.', '', ARRAY[]::TEXT[]),
('Mature', 'mature_us.mp3', 'verb', 'B1', 'to become fully grown or developed', '', 'This particular breed of cattle matures early.', '', ARRAY[]::TEXT[]),
('Maximize', 'maximize_us.mp3', 'verb', 'B1', 'to increase something as much as possible', '', 'to maximize efficiency/fitness/profits', '', ARRAY[]::TEXT[]),
('Maximum', 'maximum_us.mp3', 'adjective', 'B1', 'as large, fast, etc. as is possible, or the most that is possible or allowed', '', 'the maximum amount/number of something', '', ARRAY[]::TEXT[]),
('Maximum', 'maximum_us.mp3', 'noun', 'B1', 'the greatest amount, size, speed, etc. that is possible, recorded or allowed', '', 'a maximum of 30 children in a class', '', ARRAY[]::TEXT[]),
('May', 'May_us.mp3', 'noun', 'B1', 'the fifth month of the year, between April and June', '', 'She was born in May.', '', ARRAY[]::TEXT[]),
('May', 'may_us.mp3', 'modal verb', 'B1', 'used to say that something is possible', '', 'That may or may not be true.', '', ARRAY[]::TEXT[]),
('Maybe', 'maybe_us.mp3', 'adverb', 'B1', 'used when you are not certain that something will happen or that something is true or is a correct number', '', 'Maybe he''ll come, maybe he won''t.', '', ARRAY[]::TEXT[]),
('Mayor', 'mayor_us.mp3', 'noun', 'B1', 'the head of the government of a town or city, etc., elected by the public', '', 'the Mayor of New York', '', ARRAY[]::TEXT[]),
('Me', 'me_us.mp3', 'pronoun', 'B1', 'the form of I that is used when the speaker or writer is the object of a verb or preposition, or after the verb be', '', 'Don''t hit me.', '', ARRAY[]::TEXT[]),
('Meal', 'meal_us.mp3', 'noun', 'B1', 'an occasion when people eat food, especially breakfast, lunch or dinner', '', 'Try not to eat between meals.', '', ARRAY[]::TEXT[]),
('Mean', 'mean_us.mp3', 'verb', 'B1', 'to have something as a meaning in the same or another language', '', 'mean something, What does this sentence mean?', '', ARRAY[]::TEXT[]),
('Meaning', 'meaning_us.mp3', 'noun', 'B1', 'the thing or idea that a sound, word, sign, etc. represents', '', 'What''s the meaning of this word?', '', ARRAY[]::TEXT[]),
('Meaningful', 'meaningful_us.mp3', 'adjective', 'B1', 'serious and important', '', 'a meaningful relationship/discussion/experience', '', ARRAY[]::TEXT[]),
('Means', 'means_us.mp3', 'noun', 'B1', 'an action, an object or a system by which a result is achieved; a way of achieving or doing something', '', 'means of something, Email is a highly effective means of communication.', '', ARRAY[]::TEXT[]),
('Meantime', 'meantime_us.mp3', 'noun', 'B1', 'for a short period of time but not permanently', '', 'I''m changing my email address but for the meantime you can use the old one.', '', ARRAY[]::TEXT[]),
('Meanwhile', 'meanwhile_us.mp3', 'adverb', 'B1', 'while something else is happening', '', 'Leave the cake to cool completely. Meanwhile, make the topping.', '', ARRAY[]::TEXT[]),
('Measure', 'measure_us.mp3', 'noun', 'B1', 'an official action that is done in order to achieve a particular aim', '', 'safety/austerity measures', '', ARRAY[]::TEXT[]),
('Measure', 'measure_us.mp3', 'verb', 'B1', 'to find the size, quantity, etc. of something in standard units', '', 'measure something/somebody, a device that measures the level of radiation in the atmosphere', '', ARRAY[]::TEXT[]),
('Measurement', 'measurement_us.mp3', 'noun', 'B1', 'the act or the process of finding the size, quantity or degree of something', '', 'the metric system of measurement', '', ARRAY[]::TEXT[]),
('Meat', 'meat_us.mp3', 'noun', 'B1', 'the soft part of an animal or a bird that can be eaten as food; a particular type of this', '', 'a piece/slice of meat', '', ARRAY[]::TEXT[]),
('Mechanic', 'mechanic_us.mp3', 'noun', 'B1', 'a person whose job is repairing machines, especially the engines of vehicles', '', 'a car/motor mechanic', '', ARRAY[]::TEXT[]),
('Mechanical', 'mechanical_us.mp3', 'adjective', 'B1', 'operated by power from an engine', '', 'a mechanical device/toy/clock', '', ARRAY[]::TEXT[]),
('Mechanism', 'mechanism_us.mp3', 'noun', 'B1', 'a set of moving parts in a machine that performs a task', '', 'a delicate watch mechanism', '', ARRAY[]::TEXT[]),
('Medal', 'medal_us.mp3', 'noun', 'B1', 'a flat piece of metal, usually like a coin in shape, that is given to the winner of a competition or to somebody who has been brave, for example in war', '', 'to win a gold medal in the Olympics', '', ARRAY[]::TEXT[]),
('Media', 'media_us.mp3', 'noun', 'B1', 'the main ways that large numbers of people receive information and entertainment, that is television, radio, newspapers and the internet', '', 'the national/international media', '', ARRAY[]::TEXT[]),
('Medical', 'medical_us.mp3', 'adjective', 'B1', 'connected with illness and injury and their treatment', '', 'medical care/treatment', '', ARRAY[]::TEXT[]),
('Medication', 'medication_us.mp3', 'noun', 'B1', 'a drug or another form of medicine that you take to prevent or to treat an illness; treatment involving drugs', '', 'Are you currently taking any medication?', '', ARRAY[]::TEXT[]),
('Medicine', 'medicine_us.mp3', 'noun', 'B1', 'the study and treatment of diseases and injuries', '', 'advances in modern medicine', '', ARRAY[]::TEXT[]),
('Medieval', 'medieval_us.mp3', 'adjective', 'B1', 'connected with the Middle Ages (about AD 1000 to AD 1450)', '', 'medieval architecture/castles/manuscripts', '', ARRAY[]::TEXT[]),
('Meditation', 'meditation_us.mp3', 'noun', 'B1', 'the practice of focusing your mind in silence, especially for religious reasons or in order to make your mind calm', '', 'She found peace through yoga and meditation.', '', ARRAY[]::TEXT[]),
('Medium', 'medium_us.mp3', 'adjective', 'B1', 'in the middle between a larger and smaller size, amount, length, temperature, etc.', '', 'There are three sizes—small, medium and large.', '', ARRAY[]::TEXT[]),
('Medium', 'medium_us.mp3', 'noun', 'B1', 'a way of communicating information, etc. to people', '', 'the medium of radio/television', '', ARRAY[]::TEXT[]),
('Meet', 'meet_us.mp3', 'verb', 'B1', 'to be in the same place as somebody by chance and talk to them', '', 'Maybe we''ll meet again some time.', '', ARRAY[]::TEXT[]),
('Meeting', 'meeting_us.mp3', 'noun', 'B1', 'an occasion when people come together to discuss or decide something', '', 'A hundred people attended the public meeting.', '', ARRAY[]::TEXT[]),
('Melody', 'melody_us.mp3', 'noun', 'B1', 'a tune, especially the main tune in a piece of music written for several instruments or voices', '', 'a haunting melody', '', ARRAY[]::TEXT[]),
('Melt', 'melt_us.mp3', 'verb', 'B1', 'to become or make something become liquid as a result of heating', '', 'The snow showed no sign of melting.', '', ARRAY[]::TEXT[]),
('Member', 'member_us.mp3', 'noun', 'B1', 'a person, an animal or a plant that belongs to a particular group', '', 'member of something, a member of the family/community', '', ARRAY[]::TEXT[]),
('Membership', 'membership_us.mp3', 'noun', 'B1', 'the state of being a member of a group, a club, an organization, etc.', '', 'membership of something, (British English), Who is eligible to apply for membership of the association?', '', ARRAY[]::TEXT[]),
('Memo', 'memo_us.mp3', 'noun', 'B1', 'an official note from one person to another in the same organization', '', 'to write/send a memo', '', ARRAY[]::TEXT[]),
('Memoir', 'memoir_us.mp3', 'noun', 'B1', 'an account written by somebody, especially somebody famous, about their life and experiences', '', 'O''Connor published a childhood memoir.', '', ARRAY[]::TEXT[]),
('Memorable', 'memorable_us.mp3', 'adjective', 'B1', 'worth remembering or easy to remember, especially because of being special or unusual', '', 'The holiday provided many memorable moments.', '', ARRAY[]::TEXT[]),
('Memorial', 'memorial_us.mp3', 'noun', 'B1', 'a statue, stone, etc. that is built in order to remind people of an important past event or of a famous person who has died', '', 'a war memorial (= in memory of soldiers who died in a war)', '', ARRAY[]::TEXT[]),
('Memory', 'memory_us.mp3', 'noun', 'B1', 'your ability to remember things', '', 'memory for something, I have a bad memory for names.', '', ARRAY[]::TEXT[]),
('Mental', 'mental_us.mp3', 'adjective', 'B1', 'connected with or happening in the mind; involving the process of thinking', '', 'the mental process of remembering', '', ARRAY[]::TEXT[]),
('Mention', 'mention_us.mp3', 'noun', 'B1', 'an act of referring to somebody/something in speech or writing', '', 'He made no mention of her work.', '', ARRAY[]::TEXT[]),
('Mention', 'mention_us.mp3', 'verb', 'B1', 'to write or speak about something/somebody, especially without giving much information', '', 'mention something/somebody, Sorry, I won''t mention it again.', '', ARRAY[]::TEXT[]),
('Mentor', 'mentor_us.mp3', 'noun', 'B1', 'an experienced person who advises and helps somebody with less experience over a period of time', '', 'She was a friend and mentor to many young actors.', '', ARRAY[]::TEXT[]),
('Menu', 'menu_us.mp3', 'noun', 'B1', 'a list of the food that is available at a restaurant or to be served at a meal', '', 'May we have the menu?', '', ARRAY[]::TEXT[]),
('Merchant', 'merchant_us.mp3', 'noun', 'B1', 'a person who buys and sells goods in large quantities, especially one who imports and exports goods', '', 'a coal/wine merchant', '', ARRAY[]::TEXT[]),
('Mercy', 'mercy_us.mp3', 'noun', 'B1', 'a kind or forgiving attitude towards somebody that you have the power to harm or right to punish', '', 'to ask/beg/plead for mercy', '', ARRAY[]::TEXT[]),
('Mere', 'mere_us.mp3', 'adjective', 'B1', 'used when you want to emphasize how small, unimportant, etc. somebody/something is', '', 'It took her a mere 20 minutes to win.', '', ARRAY[]::TEXT[]),
('Merely', 'merely_us.mp3', 'adverb', 'B1', 'used meaning ‘only’ or ‘simply’ to emphasize a fact or something that you are saying', '', 'It is not merely a job, but a way of life.', '', ARRAY[]::TEXT[]),
('Merge', 'merge_us.mp3', 'verb', 'B1', 'to combine or make two or more things combine to form a single thing', '', 'The banks are set to merge next year.', '', ARRAY[]::TEXT[]),
('Merger', 'merger_us.mp3', 'noun', 'B1', 'the act of joining two or more organizations or businesses into one', '', 'If the merger goes through, thousands of jobs will be lost.', '', ARRAY[]::TEXT[]),
('Merit', 'merit_us.mp3', 'noun', 'B1', 'the quality of being good and of deserving praise or reward', '', 'a work of outstanding artistic merit', '', ARRAY[]::TEXT[]),
('Mess', 'mess_us.mp3', 'noun', 'B1', 'a dirty or untidy state', '', 'in a mess, The room was in a mess.', '', ARRAY[]::TEXT[]),
('Message', 'message_us.mp3', 'noun', 'B1', 'a written or spoken piece of information, etc. that you send to somebody or leave for somebody when you cannot speak to them yourself', '', 'There were no messages for me at the hotel.', '', ARRAY[]::TEXT[]),
('Metal', 'metal_us.mp3', 'noun', 'B1', 'a type of solid mineral substance that is usually hard and shiny and that heat and electricity can travel through, for example tin, iron and gold', '', 'a piece/sheet of metal', '', ARRAY[]::TEXT[]),
('Metaphor', 'metaphor_us.mp3', 'noun', 'B1', 'a word or phrase used to describe somebody/something else, in a way that is different from its normal use, in order to show that the two things have the same qualities and to make the description more powerful, for example She has a heart of stone; the use of such words and phrases', '', 'a game of football used as a metaphor for the competitive struggle of life', '', ARRAY[]::TEXT[]),
('Method', 'method_us.mp3', 'noun', 'B1', 'a particular way of doing something', '', 'Which method is the most effective?', '', ARRAY[]::TEXT[]),
('Methodology', 'methodology_us.mp3', 'noun', 'B1', 'a set of methods and principles used to perform a particular activity', '', 'recent changes in the methodology of language teaching', '', ARRAY[]::TEXT[]),
('Metre', 'metre_us.mp3', 'noun', 'B1', 'a unit for measuring length; a hundred centimetres', '', 'a 50-metre swimming pool', '', ARRAY[]::TEXT[]),
('Middle', 'middle_us.mp3', 'adjective', 'B1', 'in a position in the middle of an object, group of objects, people, etc.; between the beginning and the end of something', '', 'Pens are kept in the middle drawer.', '', ARRAY[]::TEXT[]),
('Middle', 'middle_us.mp3', 'noun', 'B1', 'the part of something that is at an equal distance from all its edges or sides; a point or a period of time between the beginning and the end of something', '', 'in the middle, a lake with an island in the middle', '', ARRAY[]::TEXT[]),
('Midnight', 'midnight_us.mp3', 'noun', 'B1', '12 o’clock at night', '', 'She heard the clock strike midnight.', '', ARRAY[]::TEXT[]),
('Midst', 'midst_us.mp3', 'noun', 'B1', 'the middle part of something', '', 'in the midst of something, Such beauty was unexpected in the midst of the city.', '', ARRAY[]::TEXT[]),
('Might', 'might_us.mp3', 'modal verb', 'B1', 'used when showing that something is or was possible', '', 'He might get there in time, but I can''t be sure.', '', ARRAY[]::TEXT[]),
('Migration', 'migration_us.mp3', 'noun', 'B1', 'the movement every year of large numbers of birds or animals from one place to another', '', 'the seasonal migration of blue whales', '', ARRAY[]::TEXT[]),
('Mild', 'mild_us.mp3', 'adjective', 'B1', 'not severe or strong', '', 'a mild form of the disease', '', ARRAY[]::TEXT[]),
('Mile', 'mile_us.mp3', 'noun', 'B1', 'a unit for measuring distance equal to 1 609 metres or 1 760 yards', '', 'a 20-mile drive to work', '', ARRAY[]::TEXT[]),
('Militant', 'militant_us.mp3', 'adjective', 'B1', 'using, or willing to use, force or strong pressure to achieve your aims, especially to achieve social or political change', '', 'militant groups/leaders', '', ARRAY[]::TEXT[]),
('Militant', 'militant_us.mp3', 'noun', 'B1', 'a person who uses, or is willing to use, force or strong pressure to achieve their aims, especially to achieve social or political change', '', 'Student militants were fighting with the police.', '', ARRAY[]::TEXT[]),
('Military', 'military_us.mp3', 'adjective', 'B1', 'connected with soldiers or the armed forces', '', 'We may have to take military action.', '', ARRAY[]::TEXT[]),
('Military', 'military_us.mp3', 'noun', 'B1', 'soldiers; the armed forces', '', 'The military was/were called in to deal with the riot.', '', ARRAY[]::TEXT[]),
('Militia', 'militia_us.mp3', 'noun', 'B1', 'a group of people who are not professional soldiers but who have had military training and can act as an army', '', 'He said he would call out the state militia if the rebels did not surrender.', '', ARRAY[]::TEXT[]),
('Milk', 'milk_us.mp3', 'noun', 'B1', 'the white liquid produced by cows, goats and some other animals as food for their young and used as a drink by humans', '', 'a pint/litre of milk', '', ARRAY[]::TEXT[]),
('Mill', 'mill_us.mp3', 'noun', 'B1', 'a building fitted with equipment for grinding grain into flour; a machine for grinding grain', '', 'The old mill has been converted into apartments.', '', ARRAY[]::TEXT[]),
('Million', 'million_us.mp3', 'number', 'B1', '1 000 000', '', 'a population of half a million', '', ARRAY[]::TEXT[]),
('Mind', 'mind_us.mp3', 'noun', 'B1', 'the part of a person that makes them able to be aware of things, to think and to feel', '', 'the conscious/subconscious mind', '', ARRAY[]::TEXT[]),
('Mind', 'mind_us.mp3', 'verb', 'B1', 'to be upset, annoyed or worried by something', '', 'mind (something), I don''t mind the cold—it''s the rain I don''t like.', '', ARRAY[]::TEXT[]),
('Mine', 'mine_us.mp3', 'noun', 'B1', 'a deep hole or holes under the ground where minerals such as coal, gold, etc. are dug', '', 'a copper/diamond mine', '', ARRAY[]::TEXT[]),
('Mine', 'mine_us.mp3', 'pronoun', 'B1', 'of or belonging to the person writing or speaking', '', 'That''s mine.', '', ARRAY[]::TEXT[]),
('Miner', 'miner_us.mp3', 'noun', 'B1', 'a person who works in a mine taking out coal, gold, diamonds, etc.', '', 'Rescuers are trying to save miners trapped underground after a gas explosion.', '', ARRAY[]::TEXT[]),
('Mineral', 'mineral_us.mp3', 'noun', 'B1', 'a substance that is naturally present in the earth and is not formed from animal or vegetable matter, for example gold and salt. Some minerals are also present in food and drink and in the human body and are essential for good health.', '', 'a country rich in mineral resources', '', ARRAY[]::TEXT[]),
('Minimal', 'minimal_us.mp3', 'adjective', 'B1', 'very small in size or amount; as small as possible', '', 'The work was carried out at minimal cost.', '', ARRAY[]::TEXT[]),
('Minimize', 'minimize_us.mp3', 'verb', 'B1', 'to reduce something, especially something bad, to the lowest possible level', '', 'Good hygiene helps to minimize the risk of infection.', '', ARRAY[]::TEXT[]),
('Minimum', 'minimum_us.mp3', 'adjective', 'B1', 'the smallest that is possible or allowed; extremely small', '', 'a minimum charge/price', '', ARRAY[]::TEXT[]),
('Minimum', 'minimum_us.mp3', 'noun', 'B1', 'the smallest or lowest amount that is possible, required or recorded', '', 'The class needs a minimum of six students to continue.', '', ARRAY[]::TEXT[]),
('Mining', 'mining_us.mp3', 'noun', 'B1', 'the process of getting coal and other minerals from under the ground; the industry involved in this', '', 'coal/diamond/gold/tin mining', '', ARRAY[]::TEXT[]),
('Minister', 'minister_us.mp3', 'noun', 'B1', 'a senior member of the government who is in charge of a government department or a branch of one', '', 'the Minister of Education', '', ARRAY[]::TEXT[]),
('Ministry', 'ministry_us.mp3', 'noun', 'B1', 'a government department that has a particular area of responsibility', '', 'The Ministry of Defence has issued the following statement.', '', ARRAY[]::TEXT[]),
('Minor', 'minor_us.mp3', 'adjective', 'B1', 'not very large, important or serious', '', 'The new plan involves widening a minor road through the valley.', '', ARRAY[]::TEXT[]),
('Minority', 'minority_us.mp3', 'noun', 'B1', 'the smaller part of a group; less than half of the people or things in a large group', '', 'Only a small minority of students is/are interested in politics these days.', '', ARRAY[]::TEXT[]),
('Minute', 'minute_us.mp3', 'adjective', 'B1', 'extremely small', '', 'minute amounts of chemicals in the water', '', ARRAY[]::TEXT[]),
('Minute', 'minute_us.mp3', 'noun', 'B1', 'each of the 60 parts of an hour, that are equal to 60 seconds', '', 'minutes to…, It''s four minutes to six.', '', ARRAY[]::TEXT[]),
('Miracle', 'miracle_us.mp3', 'noun', 'B1', 'an act or event that does not follow the laws of nature and is believed to be caused by God', '', 'the miracle of rising from the grave', '', ARRAY[]::TEXT[]),
('Mirror', 'mirror_us.mp3', 'noun', 'B1', 'a piece of special flat glass that reflects images, so that you can see yourself when you look in it', '', 'in the mirror, He looked at himself in the mirror.', '', ARRAY[]::TEXT[]),
('Miserable', 'miserable_us.mp3', 'adjective', 'B1', 'very unhappy or uncomfortable', '', 'We were cold, wet and thoroughly miserable.', '', ARRAY[]::TEXT[]),
('Misery', 'misery_us.mp3', 'noun', 'B1', 'great physical or mental pain', '', 'Fame brought her nothing but misery.', '', ARRAY[]::TEXT[]),
('Misleading', 'misleading_us.mp3', 'adjective', 'B1', 'giving the wrong idea or impression and making you believe something that is not true', '', 'misleading information/advertisements', '', ARRAY[]::TEXT[]),
('Miss', 'miss_us.mp3', 'verb', 'B1', 'to be or arrive too late for something', '', 'If I don''t leave now I''ll miss my plane.', '', ARRAY[]::TEXT[]),
('Missile', 'missile_us.mp3', 'noun', 'B1', 'a weapon that is sent through the air and that explodes when it hits the thing that it is aimed at', '', 'nuclear missiles', '', ARRAY[]::TEXT[]),
('Missing', 'missing_us.mp3', 'adjective', 'B1', 'that cannot be found or that is not in its usual place; that has been removed, lost or destroyed', '', 'I never found the missing piece.', '', ARRAY[]::TEXT[]),
('Mission', 'mission_us.mp3', 'noun', 'B1', 'that cannot exist or be done; not possible', '', 'almost/virtually/nearly impossible', '', ARRAY[]::TEXT[]),
('Mistake', 'mistake_us.mp3', 'noun', 'B1', 'an action or an opinion that is not correct, or that produces a result that you did not want', '', 'It''s easy to make a mistake.', '', ARRAY[]::TEXT[]),
('Mistake', 'mistake_us.mp3', 'verb', 'B1', 'to not understand or judge somebody/something correctly', '', 'mistake somebody/something, I admit that I mistook his intentions.', '', ARRAY[]::TEXT[]),
('Mix', 'mix_us.mp3', 'noun', 'B1', 'a combination of different people or things', '', 'It''s a school with a good social and ethnic mix of children.', '', ARRAY[]::TEXT[]),
('Mix', 'mix_us.mp3', 'verb', 'B1', 'if two or more substances or things mix or you mix them, they combine, usually in a way that means they cannot easily be separated', '', 'Oil and water do not mix.', '', ARRAY[]::TEXT[]),
('Mixed', 'mixed_us.mp3', 'adjective', 'B1', 'consisting of different qualities or elements', '', 'a mixed diet', '', ARRAY[]::TEXT[]),
('Mixture', 'mixture_us.mp3', 'noun', 'B1', 'a combination of different things', '', 'She was a curious mixture, part grand lady, part wild child.', '', ARRAY[]::TEXT[]),
('Mob', 'mob_us.mp3', 'noun', 'B1', 'a large crowd of people, especially one that may become violent or cause trouble', '', 'an angry/unruly mob', '', ARRAY[]::TEXT[]),
('Mobile', 'mobile_us.mp3', 'adjective', 'B1', 'connected with mobile phones, tablets, etc.', '', 'What''s your mobile number?', '', ARRAY[]::TEXT[]),
('Mobile', 'mobile_us.mp3', 'noun', 'B1', 'a mobile phone', '', 'Call me on my mobile.', '', ARRAY[]::TEXT[]),
('Mobility', 'mobility_us.mp3', 'noun', 'B1', 'the ability to move easily from one place, social class or job to another', '', 'social/geographical/career mobility', '', ARRAY[]::TEXT[]),
('Mobilize', 'mobilize_us.mp3', 'verb', 'B1', 'to work together in order to achieve a particular aim; to organize a group of people to do this', '', 'The unions mobilized thousands of workers in a protest against the cuts.', '', ARRAY[]::TEXT[]),
('Mode', 'mode_us.mp3', 'noun', 'B1', 'a particular way of doing something; a particular type of something', '', 'a mode of communication', '', ARRAY[]::TEXT[]),
('Model', 'model_us.mp3', 'noun', 'B1', 'a copy of something, usually smaller than the original object', '', 'a working model (= one in which the parts move) of a fire engine', '', ARRAY[]::TEXT[]),
('Model', 'model_us.mp3', 'verb', 'B1', 'to create a copy or description of an activity, a situation, etc. so that you can study it before dealing with the real thing', '', 'The program can model a typical home page for you.', '', ARRAY[]::TEXT[]),
('Moderate', 'moderate_us.mp3', 'adjective', 'B1', 'that is neither very good, large, hot, etc. nor very bad, small, cold, etc.', '', 'students of moderate ability', '', ARRAY[]::TEXT[]),
('Modern', 'modern_us.mp3', 'adjective', 'B1', 'of the present time or recent times', '', 'the modern industrial world', '', ARRAY[]::TEXT[]),
('Modest', 'modest_us.mp3', 'adjective', 'B1', 'not very large, expensive, important, etc.', '', 'modest improvements/reforms', '', ARRAY[]::TEXT[]),
('Modification', 'modification_us.mp3', 'noun', 'B1', 'the act or process of changing something in order to improve it or make it more acceptable; a change that is made', '', 'Considerable modification of the existing system is needed.', '', ARRAY[]::TEXT[]),
('Modify', 'modify_us.mp3', 'verb', 'B1', 'to change something slightly, especially in order to make it more suitable for a particular purpose', '', 'Patients are taught how to modify their diet.', '', ARRAY[]::TEXT[]),
('Moment', 'moment_us.mp3', 'noun', 'B1', 'a very short period of time', '', 'Could you wait a moment, please?', '', ARRAY[]::TEXT[]),
('Momentum', 'momentum_us.mp3', 'noun', 'B1', 'the ability to keep increasing or developing', '', 'The fight for his release gathers momentum each day.', '', ARRAY[]::TEXT[]),
('Monday', 'Monday_us.mp3', 'noun', 'B1', 'the day of the week after Sunday and before Tuesday, the first day of the working week', '', 'It''s Monday today, isn''t it?', '', ARRAY[]::TEXT[]),
('Money', 'money_us.mp3', 'noun', 'B1', 'what you earn by working or selling things, and use to buy things', '', 'to borrow/save/spend/earn money', '', ARRAY[]::TEXT[]),
('Monitor', 'monitor_us.mp3', 'noun', 'B1', 'a screen that shows information from a computer; a television screen used to show particular kinds of information', '', 'The details of today''s flights are displayed on the monitor.', '', ARRAY[]::TEXT[]),
('Monitor', 'monitor_us.mp3', 'verb', 'B1', 'to watch and check something over a period of time in order to see how it develops, so that you can make any necessary changes', '', 'monitor something, Each student''s progress is closely monitored.', '', ARRAY[]::TEXT[]),
('Monk', 'monk_us.mp3', 'noun', 'B1', 'a member of a religious group of men who often live apart from other people in a monastery and who do not marry or have personal possessions', '', 'Benedictine/Buddhist monks', '', ARRAY[]::TEXT[]),
('Monkey', 'monkey_us.mp3', 'noun', 'B1', 'an animal with a long tail, that climbs trees and lives in hot countries. There are several types of monkey and they are related to apes and humans.', '', 'Like humans, apes and monkeys live in complex social groupings.', '', ARRAY[]::TEXT[]),
('Monopoly', 'monopoly_us.mp3', 'noun', 'B1', 'the complete control of trade in particular goods or the supply of a particular service; a type of goods or a service that is controlled in this way', '', 'In the past central government had a monopoly on television broadcasting.', '', ARRAY[]::TEXT[]),
('Monster', 'monster_us.mp3', 'noun', 'B1', '(in stories) an imaginary creature that is very large, ugly and frightening', '', 'a monster with three heads', '', ARRAY[]::TEXT[]),
('Month', 'month_us.mp3', 'noun', 'B1', 'any of the twelve periods of time into which the year is divided, for example May or June', '', 'The months of July and August are the hottest.', '', ARRAY[]::TEXT[]),
('Monthly', 'monthly_us.mp3', 'adjective', 'B1', 'happening once a month or every month', '', 'a monthly meeting/visit/magazine', '', ARRAY[]::TEXT[]),
('Monument', 'monument_us.mp3', 'noun', 'B1', 'a building, column, statue, etc. built to remind people of a famous person or event', '', 'A monument to him was erected in St Paul''s Cathedral.', '', ARRAY[]::TEXT[]),
('Mood', 'mood_us.mp3', 'noun', 'B1', 'the way you are feeling at a particular time', '', 'in a … mood, She''s in a good mood today (= happy and friendly).', '', ARRAY[]::TEXT[]),
('Moon', 'moon_us.mp3', 'noun', 'B1', 'the round object that moves around the earth once every 27½ days and shines at night by light reflected from the sun', '', 'the surface of the moon', '', ARRAY[]::TEXT[]),
('Moral', 'moral_us.mp3', 'adjective', 'B1', 'connected with principles of right and wrong behaviour', '', 'a moral issue/dilemma', '', ARRAY[]::TEXT[]),
('Moral', 'moral_us.mp3', 'noun', 'B1', 'standards or principles of good behaviour, especially in matters of sexual relationships', '', 'Young people these days have no morals.', '', ARRAY[]::TEXT[]),
('Morality', 'morality_us.mp3', 'noun', 'B1', 'principles relating to right and wrong or good and bad behaviour', '', 'matters of public/private morality', '', ARRAY[]::TEXT[]),
('More', 'more_us.mp3', 'adverb', 'B1', 'used to form the comparative of most adjectives and adverbs with two or more syllables', '', 'She was far more intelligent than her sister.', '', ARRAY[]::TEXT[]),
('More', 'more_us.mp3', 'determiner', 'B1', 'a larger number or amount of', '', 'I want some more!', '', ARRAY[]::TEXT[]),
('More', 'more_us.mp3', 'pronoun', 'B1', 'used with plural nouns and verbs, especially in negative sentences or in more formal English, to mean ‘a large number of’. Also used in questions to ask about the size of a number, and with ‘as’, ‘so’ and ‘too’.', '', 'We don''t have very many copies left.', '', ARRAY[]::TEXT[]),
('Moreover', 'moreover_us.mp3', 'adverb', 'B1', 'used to introduce some new information that adds to or supports what you have said previously', '', 'A talented artist, he was, moreover, a writer of some note.', '', ARRAY[]::TEXT[]),
('Morning', 'morning_us.mp3', 'noun', 'B1', 'the early part of the day from the time when people wake up until 12 o''clock in the middle of the day or before lunch', '', 'They left for Spain early this morning.', '', ARRAY[]::TEXT[]),
('Mortgage', 'mortgage_us.mp3', 'noun', 'B1', 'a legal agreement by which a bank or similar organization lends you money to buy a house, etc., and you pay the money back over a particular number of years; the sum of money that you borrow', '', 'to apply for/take out/pay off a mortgage', '', ARRAY[]::TEXT[]),
('Mosque', 'mosque_us.mp3', 'noun', 'B1', 'a building where Muslims go to worship (= praise God)', '', 'I used to pray at the local mosque with my father and grandfather.', '', ARRAY[]::TEXT[]),
('Most', 'most_us.mp3', 'adverb', 'B1', 'used to form the superlative of most adjectives and adverbs of two or more syllables', '', 'the most boring/beautiful part', '', ARRAY[]::TEXT[]),
('Most', 'most_us.mp3', 'determiner', 'B1', 'the largest in number or amount', '', 'Who do you think will get (the) most votes?', '', ARRAY[]::TEXT[]),
('Most', 'most_us.mp3', 'pronoun', 'B1', 'used with plural nouns and verbs, especially in negative sentences or in more formal English, to mean ‘a large number of’. Also used in questions to ask about the size of a number, and with ‘as’, ‘so’ and ‘too’.', '', 'We don''t have very many copies left.', '', ARRAY[]::TEXT[]),
('Mostly', 'mostly_us.mp3', 'adverb', 'B1', 'mainly; generally', '', 'The sauce is mostly cream.', '', ARRAY[]::TEXT[]),
('Mother', 'mother_us.mp3', 'noun', 'B1', 'a female parent of a child or animal; a person who is acting as a mother to a child', '', 'I want to buy a present for my mother and father.', '', ARRAY[]::TEXT[]),
('Motion', 'motion_us.mp3', 'noun', 'B1', 'the act or process of moving or the way something moves', '', 'What was Newton''s first law of motion?', '', ARRAY[]::TEXT[]),
('Motivate', 'motivate_us.mp3', 'verb', 'B1', 'to be the reason why somebody does something or behaves in a particular way', '', 'motivate somebody (to do something), What motivates people to carry out such attacks?', '', ARRAY[]::TEXT[]),
('Motivation', 'motivation_us.mp3', 'noun', 'B1', 'the reason why somebody does something or behaves in a particular way', '', 'motivation (behind something), What is the motivation behind this sudden change?', '', ARRAY[]::TEXT[]),
('Motive', 'motive_us.mp3', 'noun', 'B1', 'a reason for doing something', '', 'There seemed to be no motive for the murder.', '', ARRAY[]::TEXT[]),
('Motor', 'motor_us.mp3', 'adjective', 'B1', 'having an engine; using the power of an engine', '', 'The street is closed to motor vehicles.', '', ARRAY[]::TEXT[]),
('Motor', 'motor_us.mp3', 'noun', 'B1', 'a device that uses electricity, petrol, etc. to produce movement and makes a machine, a vehicle, a boat, etc. work', '', 'An electric motor is used to pump the water.', '', ARRAY[]::TEXT[]),
('Motorcycle', 'motorcycle_us.mp3', 'noun', 'B1', 'a road vehicle with two wheels, driven by an engine, with one seat for the driver and often a seat for a passenger behind the driver', '', 'He never learned to ride a motorcycle or to drive a car.', '', ARRAY[]::TEXT[]),
('Motorist', 'motorist_us.mp3', 'noun', 'B1', 'a person driving a car', '', 'The accident was reported by a passing motorist.', '', ARRAY[]::TEXT[]),
('Mount', 'mount_us.mp3', 'verb', 'B1', 'to organize and begin something', '', 'Residents mounted a campaign to fight the plans.', '', ARRAY[]::TEXT[]),
('Mountain', 'mountain_us.mp3', 'noun', 'B1', 'a very high hill, often with rocks near the top', '', 'the mountains of Andalusia', '', ARRAY[]::TEXT[]),
('Mouse', 'mouse_us.mp3', 'noun', 'B1', 'a small animal that is covered in fur and has a long thin tail. Mice live in fields, in people’s houses or where food is stored.', '', 'a house mouse', '', ARRAY[]::TEXT[]),
('Mouth', 'mouth_us.mp3', 'noun', 'B1', 'the opening in the face used for speaking, eating, etc.; the area inside the head behind this opening', '', 'She opened her mouth to say something.', '', ARRAY[]::TEXT[]),
('Move', 'move_us.mp3', 'noun', 'B1', 'a change of place or position', '', 'Don''t make a move!', '', ARRAY[]::TEXT[]),
('Move', 'move_us.mp3', 'verb', 'B1', 'to change position or make somebody/something change position in a way that can be seen, heard or felt', '', 'Don''t move—stay perfectly still.', '', ARRAY[]::TEXT[]),
('Movement', 'movement_us.mp3', 'noun', 'B1', 'an act of moving the body or part of the body', '', 'hand/eye movements', '', ARRAY[]::TEXT[]),
('Movie', 'movie_us.mp3', 'noun', 'B1', 'a series of moving pictures recorded with sound that tells a story, watched at a movie theater or on a television or other device', '', 'You''ll love this movie.', '', ARRAY[]::TEXT[]),
('Moving', 'moving_us.mp3', 'adjective', 'B1', 'causing strong, often sad, feelings about somebody/something', '', 'a deeply moving experience', '', ARRAY[]::TEXT[]),
('Much', 'much_us.mp3', 'adverb', 'B1', 'to a great degree', '', 'Thank you very much for the flowers.', '', ARRAY[]::TEXT[]),
('Much', 'much_us.mp3', 'determiner', 'B1', 'used with uncountable nouns, especially in negative sentences to mean ‘a large amount of something’, or after ‘how’ to ask about the amount of something. It is also used with ‘as’, ‘so’ and ‘too’.', '', 'I don''t have much money with me.', '', ARRAY[]::TEXT[]),
('Much', 'much_us.mp3', 'pronoun', 'B1', 'used with plural nouns and verbs, especially in negative sentences or in more formal English, to mean ‘a large number of’. Also used in questions to ask about the size of a number, and with ‘as’, ‘so’ and ‘too’.', '', 'We don''t have very many copies left.', '', ARRAY[]::TEXT[]),
('Mud', 'mud_us.mp3', 'noun', 'B1', 'wet earth that is soft and sticky', '', 'The car wheels got stuck in the mud.', '', ARRAY[]::TEXT[]),
('Multiple', 'multiple_us.mp3', 'adjective', 'B1', 'many in number; involving many different people or things', '', 'The shape appears multiple times within each painting.', '', ARRAY[]::TEXT[]),
('Multiply', 'multiply_us.mp3', 'verb', 'B1', 'to add a number to itself a particular number of times', '', 'The children are already learning to multiply and divide.', '', ARRAY[]::TEXT[]),
('Mum', 'mum_us.mp3', 'noun', 'B1', 'a mother', '', 'Call your mum.', '', ARRAY[]::TEXT[]),
('Municipal', 'municipal_us.mp3', 'adjective', 'B1', 'connected with or belonging to a town, city or district that has its own local government', '', 'municipal elections/councils', '', ARRAY[]::TEXT[]),
('Murder', 'murder_us.mp3', 'noun', 'B1', 'the crime of killing somebody deliberately', '', 'He was found guilty of murder.', '', ARRAY[]::TEXT[]),
('Murder', 'murder_us.mp3', 'verb', 'B1', 'to kill somebody deliberately and illegally', '', 'He denies murdering his wife''s lover.', '', ARRAY[]::TEXT[]),
('Muscle', 'muscle_us.mp3', 'noun', 'B1', 'a piece of body tissue that you make tight and relax in order to move a particular part of the body; the tissue that forms the muscles of the body', '', 'a calf/neck/thigh muscle', '', ARRAY[]::TEXT[]),
('Museum', 'museum_us.mp3', 'noun', 'B1', 'a building in which objects of artistic, cultural, historical or scientific interest are kept and shown to the public', '', 'a museum of modern art', '', ARRAY[]::TEXT[]),
('Music', 'music_us.mp3', 'noun', 'B1', 'sounds that are arranged in a way that is pleasant or exciting to listen to. People sing music or play it on instruments.', '', 'I like any kind of pop or dance music.', '', ARRAY[]::TEXT[]),
('Musical', 'musical_us.mp3', 'adjective', 'B1', 'connected with music; containing music', '', 'musical styles/tastes', '', ARRAY[]::TEXT[]),
('Musical', 'musical_us.mp3', 'noun', 'B1', 'a play or film in which part or all of the story is told using songs and often dancing', '', 'a Broadway/Hollywood musical', '', ARRAY[]::TEXT[]),
('Musician', 'musician_us.mp3', 'noun', 'B1', 'a person who plays a musical instrument or writes music, especially as a job', '', 'a jazz/rock/classical musician', '', ARRAY[]::TEXT[]),
('Must', 'must_us.mp3', 'modal verb', 'B1', 'used to say that something is necessary or very important (sometimes involving a rule or a law)', '', 'All visitors must report to reception.', '', ARRAY[]::TEXT[]),
('Mutual', 'mutual_us.mp3', 'adjective', 'B1', 'used to describe feelings that two or more people have for each other equally, or actions that affect two or more people equally', '', 'mutual respect/understanding', '', ARRAY[]::TEXT[]),
('My', 'my_us.mp3', 'determiner', 'B1', 'of or belonging to the speaker or writer', '', 'Where''s my passport?', '', ARRAY[]::TEXT[]),
('Myself', 'myself_us.mp3', 'pronoun', 'B1', 'used when the speaker or writer is also the person affected by an action', '', 'I cut myself on a knife.', '', ARRAY[]::TEXT[]),
('Mysterious', 'mysterious_us.mp3', 'adjective', 'B1', 'difficult to understand or explain; strange', '', 'He died in mysterious circumstances.', '', ARRAY[]::TEXT[]),
('Mystery', 'mystery_us.mp3', 'noun', 'B1', 'something that is difficult to understand or to explain', '', 'It is one of the great unsolved mysteries of this century.', '', ARRAY[]::TEXT[]),
('Myth', 'myth_us.mp3', 'noun', 'B1', 'a story from ancient times, especially one that was told to explain natural events or to describe the early history of a people; this type of story', '', 'ancient Greek myths', '', ARRAY[]::TEXT[]),
('Nail', 'nail_us.mp3', 'noun', 'B1', 'the thin hard layer covering the outer tip of the fingers or toes', '', 'Stop biting your nails!', '', ARRAY[]::TEXT[]),
('Naked', 'naked_us.mp3', 'adjective', 'B1', 'not wearing any clothes', '', 'She was clutching the sheet around her naked body.', '', ARRAY[]::TEXT[]),
('Name', 'name_us.mp3', 'noun', 'B1', 'a word or words that a particular person, animal, place or thing is known by', '', 'What''s your name?', '', ARRAY[]::TEXT[]),
('Name', 'name_us.mp3', 'verb', 'B1', 'to give a name to somebody/something', '', 'name somebody/something (after somebody), He was named after his father (= given his father''s first name).', '', ARRAY[]::TEXT[]),
('Namely', 'namely_us.mp3', 'adverb', 'B1', 'used to introduce more exact and detailed information about something that you have just mentioned', '', 'We need to concentrate on our target audience, namely women aged between 20 and 30.', '', ARRAY[]::TEXT[]),
('Narrative', 'narrative_us.mp3', 'adjective', 'B1', 'describing events or telling a story', '', 'narrative fiction', '', ARRAY[]::TEXT[]),
('Narrative', 'narrative_us.mp3', 'noun', 'B1', 'a description of events', '', 'a gripping narrative of their journey up the Amazon', '', ARRAY[]::TEXT[]),
('Narrow', 'narrow_us.mp3', 'adjective', 'B1', 'measuring a short distance from one side to the other, especially in relation to length', '', 'Stray dogs wander the steep narrow lanes of the old town.', '', ARRAY[]::TEXT[]),
('Narrow', 'narrow_us.mp3', 'verb', 'B1', 'to become or make something less wide', '', 'This is where the river narrows.', '', ARRAY[]::TEXT[]),
('Nasty', 'nasty_us.mp3', 'adjective', 'B1', 'very bad or unpleasant', '', 'He had a nasty accident.', '', ARRAY[]::TEXT[]),
('Nation', 'nation_us.mp3', 'noun', 'B1', 'a country considered as a group of people with the same language, culture and history, who live in a particular area under one government', '', 'European/Arab/Asian nations', '', ARRAY[]::TEXT[]),
('National', 'national_us.mp3', 'adjective', 'B1', 'connected with a particular nation; shared by a whole nation', '', 'Decide whether it would be better to advertise in a national or a local newspaper.', '', ARRAY[]::TEXT[]),
('National', 'national_us.mp3', 'noun', 'B1', 'a citizen of a particular country', '', 'Polish nationals living in Germany', '', ARRAY[]::TEXT[]),
('Nationwide', 'nationwide_us.mp3', 'adjective', 'B1', 'happening or existing in all parts of a particular country', '', 'a nationwide campaign', '', ARRAY[]::TEXT[]),
('Native', 'native_us.mp3', 'adjective', 'B1', 'connected with the place where you were born and lived for the first years of your life', '', 'your native land/country/city', '', ARRAY[]::TEXT[]),
('Native', 'native_us.mp3', 'noun', 'B1', 'a person who was born in a particular country or area', '', 'a native of New York', '', ARRAY[]::TEXT[]),
('Natural', 'natural_us.mp3', 'adjective', 'B1', 'existing in nature; not made or caused by humans', '', 'the natural world (= of trees, rivers, animals and birds)', '', ARRAY[]::TEXT[]),
('Naturally', 'naturally_us.mp3', 'adverb', 'B1', 'in a way that you would expect', '', 'Naturally, I get upset when things go wrong.', '', ARRAY[]::TEXT[]),
('Nature', 'nature_us.mp3', 'noun', 'B1', 'all the plants, animals and things that exist in the universe that are not made by people', '', 'Take time to appreciate the beauties of nature.', '', ARRAY[]::TEXT[]),
('Naval', 'naval_us.mp3', 'adjective', 'B1', 'connected with the navy of a country', '', 'a naval base/officer/battle', '', ARRAY[]::TEXT[]),
('Navigation', 'navigation_us.mp3', 'noun', 'B1', 'the skill or the process of planning a route for a ship or other vehicle and taking it there', '', 'a maker of in-car navigation systems', '', ARRAY[]::TEXT[]),
('Near', 'near_us.mp3', 'adjective', 'B1', 'a short distance away', '', 'His house is very near.', '', ARRAY[]::TEXT[]),
('Near', 'near_us.mp3', 'adverb', 'B1', 'at a short distance away', '', 'A bomb exploded somewhere near.', '', ARRAY[]::TEXT[]),
('Near', 'near_us.mp3', 'preposition', 'B1', 'at a short distance away from somebody/something', '', 'Do you live near here?', '', ARRAY[]::TEXT[]),
('Nearby', 'nearby_us.mp3', 'adjective', 'B1', 'near in position; not far away', '', 'Her mother lived in a nearby town.', '', ARRAY[]::TEXT[]),
('Nearby', 'nearby_us.mp3', 'adverb', 'B1', 'a short distance from somebody/something; not far away', '', 'They live nearby.', '', ARRAY[]::TEXT[]),
('Nearly', 'nearly_us.mp3', 'adverb', 'B1', 'almost; not quite; not completely', '', 'The bottle''s nearly empty.', '', ARRAY[]::TEXT[]),
('Neat', 'neat_us.mp3', 'adjective', 'B1', 'tidy and in order; carefully done or arranged', '', 'She kept her desk extremely neat.', '', ARRAY[]::TEXT[]),
('Necessarily', 'necessarily_us.mp3', 'adverb', 'B1', 'used to say that something cannot be avoided', '', 'The number of places available is necessarily limited.', '', ARRAY[]::TEXT[]),
('Necessary', 'necessary_us.mp3', 'adjective', 'B1', 'that is needed for a purpose or a reason', '', 'necessary to do something, It may be necessary to buy a new one.', '', ARRAY[]::TEXT[]),
('Necessity', 'necessity_us.mp3', 'noun', 'B1', 'the fact that something must happen or be done; the need for something', '', 'necessity for something, We recognize the necessity for a written agreement.', '', ARRAY[]::TEXT[]),
('Neck', 'neck_us.mp3', 'noun', 'B1', 'the part of the body between the head and the shoulders', '', 'He tied a scarf around his neck.', '', ARRAY[]::TEXT[]),
('Need', 'need_us.mp3', 'noun', 'B1', 'a situation when something is necessary or must be done', '', 'to satisfy/meet/fulfil a need', '', ARRAY[]::TEXT[]),
('Need', 'need_us.mp3', 'verb', 'B1', 'to require something/somebody because they are essential or very important, not just because you would like to have them', '', 'need something/somebody, Do you need any help?', '', ARRAY[]::TEXT[]),
('Need', 'need_us.mp3', 'modal verb', 'B1', 'used to state that something is/was not necessary or that only very little is/was necessary; used to ask if something is/was necessary', '', 'need (not) do something, You needn''t bother asking Rick—I know he''s too busy.', '', ARRAY[]::TEXT[]),
('Needle', 'needle_us.mp3', 'noun', 'B1', 'a small thin piece of steel that you use for sewing, with a point at one end and a hole for the thread at the other', '', 'a needle and thread', '', ARRAY[]::TEXT[]),
('Negative', 'negative_us.mp3', 'adjective', 'B1', 'bad or harmful', '', 'The crisis had a negative effect on trade.', '', ARRAY[]::TEXT[]),
('Negative', 'negative_us.mp3', 'noun', 'B1', 'a word or statement that means ‘no’; an act of refusing to do something or of denying something', '', 'in the negative, She answered in the negative (= said ‘no’).', '', ARRAY[]::TEXT[]),
('Neglect', 'neglect_us.mp3', 'noun', 'B1', 'the fact of not giving enough care or attention to something/somebody; the state of not receiving enough care or attention', '', 'The buildings are crumbling from years of neglect.', '', ARRAY[]::TEXT[]),
('Neglect', 'neglect_us.mp3', 'verb', 'B1', 'to fail to take care of somebody/something', '', 'She denies neglecting her baby.', '', ARRAY[]::TEXT[]),
('Negotiate', 'negotiate_us.mp3', 'verb', 'B1', 'to try to reach an agreement by formal discussion', '', 'negotiate (with somebody) (for something), The government will not negotiate with terrorists.', '', ARRAY[]::TEXT[]),
('Negotiation', 'negotiation_us.mp3', 'noun', 'B1', 'formal discussion between people who are trying to reach an agreement', '', 'peace/trade/contract negotiations', '', ARRAY[]::TEXT[]),
('Neighbour', 'neighbour_us.mp3', 'noun', 'B1', 'a person who lives next to you or near you', '', 'We''ve had a lot of support from all our friends and neighbours.', '', ARRAY[]::TEXT[]),
('Neighbourhood', 'neighbourhood_us.mp3', 'noun', 'B1', 'a district or an area of a town; the people who live there', '', 'We grew up in the same neighbourhood.', '', ARRAY[]::TEXT[]),
('Neighbouring', 'neighbouring_us.mp3', 'adjective', 'B1', 'located or living near or next to a place or person', '', 'a neighbouring house', '', ARRAY[]::TEXT[]),
('Neither', 'neither_us.mp3', 'adverb', 'B1', 'used to show that a negative statement is also true of somebody/something else', '', 'He didn''t remember and neither did I.', '', ARRAY[]::TEXT[]),
('Neither', 'neither_us.mp3', 'determiner', 'B1', 'not one nor the other of two things or people', '', 'Neither answer is correct.', '', ARRAY[]::TEXT[]),
('Neither', 'neither_us.mp3', 'pronoun', 'B1', 'not one nor the other of two things or people', '', 'Neither answer is correct.', '', ARRAY[]::TEXT[]),
('Nerve', 'nerve_us.mp3', 'noun', 'B1', 'any of the long fibres that carry messages between the brain and parts of the body, enabling you to move, feel pain, etc.', '', 'the optic nerve', '', ARRAY[]::TEXT[]),
('Nervous', 'nervous_us.mp3', 'adjective', 'B1', 'anxious about something or afraid of something', '', 'I felt really nervous before the interview.', '', ARRAY[]::TEXT[]),
('Nest', 'nest_us.mp3', 'noun', 'B1', 'a hollow place or structure that a bird makes or chooses for laying its eggs in and sheltering its young', '', 'sparrows building a nest of twigs and dry grass', '', ARRAY[]::TEXT[]),
('Net', 'net_us.mp3', 'adjective', 'B1', 'a net amount of money is the amount that remains when nothing more is to be taken away', '', 'a net profit of £500', '', ARRAY[]::TEXT[]),
('Net', 'net_us.mp3', 'noun', 'B1', 'material that is made of string, thread or wire twisted or tied together, with small spaces in between; a piece of this material used for a particular purpose', '', 'Unfortunately the animals are often caught in fishing nets.', '', ARRAY[]::TEXT[]),
('Network', 'network_us.mp3', 'noun', 'B1', 'a complicated system of roads, lines, tubes, nerves, etc. that are connected to each other and operate together', '', 'a rail/road/canal network', '', ARRAY[]::TEXT[]),
('Neutral', 'neutral_us.mp3', 'adjective', 'B1', 'not supporting or helping either side in a disagreement, competition, etc.', '', 'Journalists are supposed to be politically neutral.', '', ARRAY[]::TEXT[]),
('Never', 'never_us.mp3', 'adverb', 'B1', 'not at any time; not on any occasion', '', 'You never help me.', '', ARRAY[]::TEXT[]),
('Nevertheless', 'nevertheless_us.mp3', 'adverb', 'B1', 'despite something that you have just mentioned', '', 'There is little chance that we will succeed in changing the law. Nevertheless, it is important that we try.', '', ARRAY[]::TEXT[]),
('New', 'new_us.mp3', 'adjective', 'B1', 'not existing before; recently made, invented, introduced, etc.', '', 'Have you read her new novel?', '', ARRAY[]::TEXT[]),
('Newly', 'newly_us.mp3', 'adverb', 'B1', 'recently', '', 'a newly qualified doctor', '', ARRAY[]::TEXT[]),
('News', 'news_us.mp3', 'noun', 'B1', 'new information about something that has happened recently', '', 'What''s the latest news?', '', ARRAY[]::TEXT[]),
('Newsletter', 'newsletter_us.mp3', 'noun', 'B1', 'a report containing news of the activities of a club or organization that is sent regularly to all its members', '', 'Our sailing club produces a monthly newsletter.', '', ARRAY[]::TEXT[]),
('Newspaper', 'newspaper_us.mp3', 'noun', 'B1', 'a set of large printed sheets of paper, or a website, containing news, articles, advertisements, etc. and published every day or every week; the organization responsible for producing this', '', 'a daily/weekly newspaper', '', ARRAY[]::TEXT[]),
('Next', 'next_us.mp3', 'adjective', 'B1', 'coming straight after somebody/something in time, order or space', '', 'The next train to Baltimore is at ten.', '', ARRAY[]::TEXT[]),
('Next', 'next_us.mp3', 'adverb', 'B1', 'after something else; then; afterwards', '', 'What happened next?', '', ARRAY[]::TEXT[]),
('Next', 'next_us.mp3', 'noun', 'B1', 'a person or thing that is next', '', 'One moment he wasn''t there, the next he was.', '', ARRAY[]::TEXT[]),
('Next to', 'next to_us.mp3', 'preposition', 'B1', 'in or into a position right by somebody/something', '', 'We sat next to each other.', '', ARRAY[]::TEXT[]),
('Nice', 'nice_us.mp3', 'adjective', 'B1', 'pleasant or attractive', '', 'a nice day/smile/place', '', ARRAY[]::TEXT[]),
('Niche', 'niche_us.mp3', 'noun', 'B1', 'a comfortable or suitable role, job, way of life, etc.', '', 'He eventually found his niche in sports journalism.', '', ARRAY[]::TEXT[]),
('Night', 'night_us.mp3', 'noun', 'B1', 'the time between one day and the next when it is dark, when people usually sleep', '', 'at night, These animals only come out at night.', '', ARRAY[]::TEXT[]),
('Nightmare', 'nightmare_us.mp3', 'noun', 'B1', 'a dream that is very frightening or unpleasant', '', 'He still has nightmares about the accident.', '', ARRAY[]::TEXT[]),
('Nine', 'nine_us.mp3', 'number', 'B1', '9', '', 'There are only nine of these rare animals left.', '', ARRAY[]::TEXT[]),
('Ninety', 'ninety_us.mp3', 'number', 'B1', '90', '', 'The temperature must be in the nineties today.', '', ARRAY[]::TEXT[]),
('No', 'no_us.mp3', 'determiner', 'B1', 'not one; not any; not a', '', 'No student is to leave the room.', '', ARRAY[]::TEXT[]),
('No', 'no_us.mp3', 'exclamation', 'B1', 'used to give a negative reply or statement', '', 'Just say yes or no.', '', ARRAY[]::TEXT[]),
('No one', 'no one_us.mp3', 'pronoun', 'B1', 'not anyone; no person', '', 'No one was at home.', '', ARRAY[]::TEXT[]),
('Noble', 'noble_us.mp3', 'adjective', 'B1', 'having or showing fine personal qualities that people admire, such as courage, honesty and care for others', '', 'a noble leader', '', ARRAY[]::TEXT[]),
('Nobody', 'nobody_us.mp3', 'pronoun', 'B1', 'not anyone; no person', '', 'Nobody knew what to say.', '', ARRAY[]::TEXT[]),
('Nod', 'nod_us.mp3', 'verb', 'B1', 'if you nod, nod your head or your head nods, you move your head up and down to show agreement, understanding, etc.', '', 'I asked him if he would help me and he nodded.', '', ARRAY[]::TEXT[]),
('Noise', 'noise_us.mp3', 'noun', 'B1', 'a sound, especially when it is loud, unpleasant or frightening', '', 'There was a rattling noise coming from the back of the car.', '', ARRAY[]::TEXT[]),
('Noisy', 'noisy_us.mp3', 'adjective', 'B1', 'making a lot of noise', '', 'noisy children/traffic/crowds', '', ARRAY[]::TEXT[]),
('Nominate', 'nominate_us.mp3', 'verb', 'B1', 'to formally suggest that somebody/something should be chosen for an important role, prize, position, etc.', '', 'nominate somebody/something (for something), She has been nominated for the presidency.', '', ARRAY[]::TEXT[]),
('Nomination', 'nomination_us.mp3', 'noun', 'B1', 'the act of suggesting or choosing somebody as a candidate in an election, or for a job or an award; the fact of being suggested for this', '', 'Membership of the club is by nomination only.', '', ARRAY[]::TEXT[]),
('Nominee', 'nominee_us.mp3', 'noun', 'B1', 'a person who has been formally suggested for a job, a prize, etc.', '', 'He was chosen as the party''s presidential nominee.', '', ARRAY[]::TEXT[]),
('Non-profit', 'non-profit_us.mp3', 'adjective', 'B1', 'without the aim of making a profit', '', 'an independent non-profit organization', '', ARRAY[]::TEXT[]),
('None', 'none_us.mp3', 'pronoun', 'B1', 'not one of a group of people or things; not any', '', 'None of these pens works/work.', '', ARRAY[]::TEXT[]),
('Nonetheless', 'nonetheless_us.mp3', 'adverb', 'B1', 'despite this fact', '', 'The book is too long but, nonetheless, informative and entertaining.', '', ARRAY[]::TEXT[]),
('Nonsense', 'nonsense_us.mp3', 'noun', 'B1', 'ideas, statements or beliefs that you think are silly or not true', '', 'Reports that he has resigned are nonsense.', '', ARRAY[]::TEXT[]),
('Noon', 'noon_us.mp3', 'noun', 'B1', '12 o’clock in the middle of the day', '', 'We should be there by noon.', '', ARRAY[]::TEXT[]),
('Nor', 'nor_us.mp3', 'adverb', 'B1', 'and not', '', 'She seemed neither surprised nor worried.', '', ARRAY[]::TEXT[]),
('Nor', 'nor_us.mp3', 'conjunction', 'B1', 'and not', '', 'She seemed neither surprised nor worried.', '', ARRAY[]::TEXT[]),
('Norm', 'norm_us.mp3', 'noun', 'B1', 'a situation or a pattern of behaviour that is usual or expected', '', 'The new design is a departure from the norm.', '', ARRAY[]::TEXT[]),
('Normal', 'normal_us.mp3', 'adjective', 'B1', 'typical, usual or ordinary; what you would expect', '', 'quite/perfectly (= completely) normal', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
