INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Familiar', 'familiar_us.mp3', 'adjective', 'B1', 'well known to you; often seen or heard and therefore easy to recognize', '', 'to look/sound/seem familiar', '', ARRAY[]::TEXT[]),
('Family', 'family_us.mp3', 'adjective', 'B1', 'connected with the family or a particular family', '', 'family life', '', ARRAY[]::TEXT[]),
('Family', 'family_us.mp3', 'noun', 'B1', 'a group consisting of one or two parents and their children', '', 'I introduced Neil to the other members of my family.', '', ARRAY[]::TEXT[]),
('Famous', 'famous_us.mp3', 'adjective', 'B1', 'known about by many people', '', 'a famous artist/actor', '', ARRAY[]::TEXT[]),
('Fan', 'fan_us.mp3', 'noun', 'B1', 'a person who admires somebody/something or enjoys watching or listening to somebody/something very much', '', 'sports/music fans', '', ARRAY[]::TEXT[]),
('Fancy', 'fancy_us.mp3', 'adjective', 'B1', 'unusually complicated, often in an unnecessary way; intended to impress other people', '', 'a kitchen full of fancy gadgets', '', ARRAY[]::TEXT[]),
('Fancy', 'fancy_us.mp3', 'verb', 'B1', 'to want something or want to do something', '', 'fancy something, Fancy a drink?', '', ARRAY[]::TEXT[]),
('Fantastic', 'fantastic_us.mp3', 'adjective', 'B1', 'extremely good; excellent', '', 'He''s done a fantastic job.', '', ARRAY[]::TEXT[]),
('Fantasy', 'fantasy_us.mp3', 'noun', 'B1', 'a pleasant situation that you imagine but that is unlikely to happen', '', 'He spoke of his childhood fantasies about becoming a famous football player.', '', ARRAY[]::TEXT[]),
('Far', 'far_us.mp3', 'adjective', 'B1', 'at a greater distance away from you', '', 'I saw her on the far side of the road.', '', ARRAY[]::TEXT[]),
('Far', 'far_us.mp3', 'adverb', 'B1', 'a long distance away', '', 'We didn''t go far.', '', ARRAY[]::TEXT[]),
('Fare', 'fare_us.mp3', 'noun', 'B1', 'the money that you pay to travel by bus, plane, taxi, etc.', '', 'bus/taxi fares', '', ARRAY[]::TEXT[]),
('Farm', 'farm_us.mp3', 'noun', 'B1', 'an area of land, and the buildings on it, used for growing crops and/or keeping animals', '', 'a 200-hectare farm', '', ARRAY[]::TEXT[]),
('Farm', 'farm_us.mp3', 'verb', 'B1', 'to use land for growing crops and/or keeping animals', '', 'The family has farmed in Kent for over two hundred years.', '', ARRAY[]::TEXT[]),
('Farmer', 'farmer_us.mp3', 'noun', 'B1', 'a person who owns or manages a farm', '', 'My parents are dairy farmers.', '', ARRAY[]::TEXT[]),
('Farming', 'farming_us.mp3', 'noun', 'B1', 'the business of managing or working on a farm', '', 'to take up farming', '', ARRAY[]::TEXT[]),
('Fascinating', 'fascinating_us.mp3', 'adjective', 'B1', 'extremely interesting and attractive', '', 'a fascinating story', '', ARRAY[]::TEXT[]),
('Fashion', 'fashion_us.mp3', 'noun', 'B1', 'a popular style of clothes, hair, etc. at a particular time or place; the state of being popular', '', 'the latest fashion trends', '', ARRAY[]::TEXT[]),
('Fashionable', 'fashionable_us.mp3', 'adjective', 'B1', 'following a style that is popular at a particular time', '', 'fashionable clothes/ideas/styles', '', ARRAY[]::TEXT[]),
('Fast', 'fast_us.mp3', 'adjective', 'B1', 'moving or able to move quickly', '', 'a fast car/horse', '', ARRAY[]::TEXT[]),
('Fast', 'fast_us.mp3', 'adverb', 'B1', 'quickly', '', 'Don''t drive so fast!', '', ARRAY[]::TEXT[]),
('Fasten', 'fasten_us.mp3', 'verb', 'B1', 'to close or join together the two parts of something; to become closed or joined together', '', 'fasten something, Fasten your seat belts, please.', '', ARRAY[]::TEXT[]),
('Fat', 'fat_us.mp3', 'adjective', 'B1', 'having too much flesh on it and weighing too much', '', 'a big fat man/woman', '', ARRAY[]::TEXT[]),
('Fat', 'fat_us.mp3', 'noun', 'B1', 'a white or yellow substance in the bodies of animals and humans, stored under the skin', '', 'excess body fat', '', ARRAY[]::TEXT[]),
('Fatal', 'fatal_us.mp3', 'adjective', 'B1', 'causing or ending in death', '', 'a fatal accident/blow/illness', '', ARRAY[]::TEXT[]),
('Fate', 'fate_us.mp3', 'noun', 'B1', 'the things, especially bad things, that will happen or have happened to somebody/something', '', 'The fate of the three men is unknown.', '', ARRAY[]::TEXT[]),
('Father', 'father_us.mp3', 'noun', 'B1', 'a male parent of a child or an animal; a person who is acting as the father to a child', '', 'My father died in 2017.', '', ARRAY[]::TEXT[]),
('Fault', 'fault_us.mp3', 'noun', 'B1', 'the responsibility for something wrong that has happened or been done', '', 'Why should I say sorry when it''s not my fault?', '', ARRAY[]::TEXT[]),
('Favour', 'favour_us.mp3', 'noun', 'B1', 'a thing that you do to help somebody', '', 'Could you do me a favour and pick up Sam from school today?', '', ARRAY[]::TEXT[]),
('Favour', 'favour_us.mp3', 'verb', 'B1', 'to prefer one system, plan, way of doing something, etc. to another', '', 'favour something, Many countries favour a presidential system of government.', '', ARRAY[]::TEXT[]),
('Favourable', 'favourable_us.mp3', 'adjective', 'B1', 'making people have a good opinion of somebody/something', '', 'She made a favourable impression on his parents.', '', ARRAY[]::TEXT[]),
('Favourite', 'favourite_us.mp3', 'adjective', 'B1', 'liked more than others of the same kind', '', 'It''s one of my favourite movies.', '', ARRAY[]::TEXT[]),
('Favourite', 'favourite_us.mp3', 'noun', 'B1', 'a person or thing that you like more than the others of the same type', '', 'Which one''s your favourite?', '', ARRAY[]::TEXT[]),
('Fear', 'fear_us.mp3', 'noun', 'B1', 'the bad feeling that you have when you are in danger or when a particular thing frightens you', '', 'Her eyes showed no fear.', '', ARRAY[]::TEXT[]),
('Fear', 'fear_us.mp3', 'verb', 'B1', 'to be frightened of somebody/something or frightened of doing something', '', 'fear somebody/something, All his employees fear him.', '', ARRAY[]::TEXT[]),
('Feat', 'feat_us.mp3', 'noun', 'B1', 'an action or a piece of work that needs skill, strength or courage', '', 'The tunnel is a remarkable feat of engineering.', '', ARRAY[]::TEXT[]),
('Feather', 'feather_us.mp3', 'noun', 'B1', 'one of the many soft light parts covering a bird’s body', '', 'a peacock feather', '', ARRAY[]::TEXT[]),
('Feature', 'feature_us.mp3', 'noun', 'B1', 'something important, interesting or typical of a place or thing', '', 'An interesting feature of the city is the old market.', '', ARRAY[]::TEXT[]),
('Feature', 'feature_us.mp3', 'verb', 'B1', 'to include a particular person or thing as a special feature', '', 'feature somebody/something as somebody/something, The film features Cary Grant as a professor.', '', ARRAY[]::TEXT[]),
('February', 'February_us.mp3', 'noun', 'B1', 'the 2nd month of the year, between January and March', '', 'She was born in February.', '', ARRAY[]::TEXT[]),
('Federal', 'federal_us.mp3', 'adjective', 'B1', 'having a system of government in which the individual states of a country have control over their own affairs, but are controlled by a central government for national decisions, etc.', '', 'a federal republic', '', ARRAY[]::TEXT[]),
('Fee', 'fee_us.mp3', 'noun', 'B1', 'an amount of money that you pay for professional advice or services', '', 'Employees are reimbursed for any legal fees incurred when they relocate.', '', ARRAY[]::TEXT[]),
('Feed', 'feed_us.mp3', 'noun', 'B1', 'a meal of milk for a young baby; a meal for an animal', '', 'her morning feed', '', ARRAY[]::TEXT[]),
('Feed', 'feed_us.mp3', 'verb', 'B1', 'to give food to a person or an animal', '', 'feed somebody/something/yourself, Have you fed the cat yet?', '', ARRAY[]::TEXT[]),
('Feedback', 'feedback_us.mp3', 'noun', 'B1', 'advice, criticism or information about how good or useful something or somebody’s work is', '', 'customer/user feedback', '', ARRAY[]::TEXT[]),
('Feel', 'feel_us.mp3', 'noun', 'B1', 'the feeling you get when you touch something or are touched', '', 'You can tell it''s silk by the feel.', '', ARRAY[]::TEXT[]),
('Feel', 'feel_us.mp3', 'verb', 'B1', 'to experience a particular feeling or emotion', '', '+ adj., The bus ride made me feel sick.', '', ARRAY[]::TEXT[]),
('Feeling', 'feeling_us.mp3', 'noun', 'B1', 'something that you feel through the mind or through the senses', '', 'a feeling of something, a feeling of guilt/helplessness/anger/sadness', '', ARRAY[]::TEXT[]),
('Fellow', 'fellow_us.mp3', 'adjective', 'B1', 'used to describe somebody who is the same as you in some way, or in the same situation', '', 'fellow citizens/students', '', ARRAY[]::TEXT[]),
('Female', 'female_us.mp3', 'adjective', 'B1', 'being a woman or a girl', '', 'a female student/employee/artist/athlete', '', ARRAY[]::TEXT[]),
('Female', 'female_us.mp3', 'noun', 'B1', 'an animal that can lay eggs or give birth to babies; a plant that can produce fruit', '', 'One adult female can lay 400 to 500 eggs.', '', ARRAY[]::TEXT[]),
('Feminist', 'feminist_us.mp3', 'adjective', 'B1', 'having or based on the belief that women should have the same rights and opportunities as men', '', 'feminist demands/ideas/theories', '', ARRAY[]::TEXT[]),
('Feminist', 'feminist_us.mp3', 'noun', 'B1', 'a person who supports the belief that women should have the same rights and opportunities as men', '', 'Nineteenth-century feminists demanded equal education and employment opportunities for single women.', '', ARRAY[]::TEXT[]),
('Fence', 'fence_us.mp3', 'noun', 'B1', 'a structure made of wood or wire supported with posts that is put between two areas of land as a boundary, or around a garden, field, etc. to keep animals in, or to keep people and animals out', '', 'The two women chatted over the garden fence.', '', ARRAY[]::TEXT[]),
('Festival', 'festival_us.mp3', 'noun', 'B1', 'a series of performances of music, plays, films, etc., usually organized in the same place once a year; a series of public events connected with a particular activity or idea', '', 'a film/music festival', '', ARRAY[]::TEXT[]),
('Fever', 'fever_us.mp3', 'noun', 'B1', 'a medical condition in which a person has a temperature that is higher than normal', '', 'He has a high fever.', '', ARRAY[]::TEXT[]),
('Few', 'few_us.mp3', 'adjective', 'B1', 'used with plural nouns and a plural verb to mean ‘a small number’, ‘some’', '', 'We''ve had a few replies.', '', ARRAY[]::TEXT[]),
('Few', 'few_us.mp3', 'determiner', 'B1', 'used with plural nouns and a plural verb to mean ‘a small number’, ‘some’', '', 'We''ve had a few replies.', '', ARRAY[]::TEXT[]),
('Few', 'few_us.mp3', 'pronoun', 'B1', 'a small number of people, things or places; some', '', 'I recognized a few of the other people.', '', ARRAY[]::TEXT[]),
('Fibre', 'fibre_us.mp3', 'noun', 'B1', 'the part of food that helps to keep a person healthy by keeping the bowels working and moving other food quickly through the body', '', 'dietary fibre', '', ARRAY[]::TEXT[]),
('Fiction', 'fiction_us.mp3', 'noun', 'B1', 'a type of literature that describes imaginary people and events, not real ones', '', 'a work of popular fiction', '', ARRAY[]::TEXT[]),
('Field', 'field_us.mp3', 'noun', 'B1', 'an area of land in the country used for growing crops or keeping animals in, usually surrounded by a fence, etc.', '', 'We had to walk across a ploughed field.', '', ARRAY[]::TEXT[]),
('Fierce', 'fierce_us.mp3', 'adjective', 'B1', 'angry and aggressive in a way that is frightening', '', 'a fierce dog', '', ARRAY[]::TEXT[]),
('Fifteen', 'fifteen_us.mp3', 'number', 'B1', '15', '', 'He''s in the first fifteen.', '', ARRAY[]::TEXT[]),
('Fifth', 'fifth_us.mp3', 'ordinal number', 'B1', '5th', '', 'Today is the fifth (of May).', '', ARRAY[]::TEXT[]),
('Fifty', 'fifty_us.mp3', 'number', 'B1', '50', '', 'She was born in the fifties.', '', ARRAY[]::TEXT[]),
('Fight', 'fight_us.mp3', 'noun', 'B1', 'a struggle against somebody/something using physical force', '', 'a street/gang fight', '', ARRAY[]::TEXT[]),
('Fight', 'fight_us.mp3', 'verb', 'B1', 'to take part in a war or battle against an enemy', '', 'soldiers trained to fight', '', ARRAY[]::TEXT[]),
('Fighting', 'fighting_us.mp3', 'noun', 'B1', 'the activity of being involved in a battle against an enemy', '', 'Fighting broke out in three districts of the city last night.', '', ARRAY[]::TEXT[]),
('Figure', 'figure_us.mp3', 'noun', 'B1', 'a number representing a particular amount, especially one given in official information', '', 'the latest sales/crime/unemployment figures', '', ARRAY[]::TEXT[]),
('Figure', 'figure_us.mp3', 'verb', 'B1', 'to be part of a process, situation, etc. especially an important part', '', 'My feelings about the matter didn''t seem to figure at all.', '', ARRAY[]::TEXT[]),
('File', 'file_us.mp3', 'noun', 'B1', 'a box or folded piece of card for keeping loose papers together and in order', '', 'a box file', '', ARRAY[]::TEXT[]),
('File', 'file_us.mp3', 'verb', 'B1', 'to put and keep paper documents in a particular place and in a particular order so that you can find them easily; to put a paper document in a box, file, etc.', '', 'file something (+ adv./prep.), The forms should be filed alphabetically.', '', ARRAY[]::TEXT[]),
('Fill', 'fill_us.mp3', 'verb', 'B1', 'to make something full of something; to become full of something', '', 'fill something, Please fill this glass for me.', '', ARRAY[]::TEXT[]),
('Film', 'film_us.mp3', 'noun', 'B1', 'a series of moving pictures recorded with sound that tells a story, watched at a cinema or on a television or other device', '', 'Let''s stay in and watch a film.', '', ARRAY[]::TEXT[]),
('Film', 'film_us.mp3', 'verb', 'B1', 'to make a film of a story or a real event; to record somebody/something on film', '', 'They are filming in Moscow right now.', '', ARRAY[]::TEXT[]),
('Filter', 'filter_us.mp3', 'noun', 'B1', 'a device containing paper, sand, chemicals, etc. that a liquid or gas is passed through in order to remove any materials that are not wanted', '', 'an air/oil filter', '', ARRAY[]::TEXT[]),
('Filter', 'filter_us.mp3', 'verb', 'B1', 'to pass liquid, light, etc. through a special device, especially to remove something that is not wanted', '', 'All drinking water must be filtered.', '', ARRAY[]::TEXT[]),
('Final', 'final_us.mp3', 'adjective', 'B1', 'being or happening at the end of a series of events, actions, statements, etc.', '', 'his final act as party leader', '', ARRAY[]::TEXT[]),
('Final', 'final_us.mp3', 'noun', 'B1', 'the last of a series of games or competitions, in which the winner is decided', '', 'She reached the final of the 100m hurdles.', '', ARRAY[]::TEXT[]),
('Finally', 'finally_us.mp3', 'adverb', 'B1', 'after a long time, especially when there has been some difficulty or delay', '', 'The performance finally started half an hour late.', '', ARRAY[]::TEXT[]),
('Finance', 'finance_us.mp3', 'noun', 'B1', 'money used to run a business, an activity or a project', '', 'The project will only go ahead if they can raise the necessary finance.', '', ARRAY[]::TEXT[]),
('Finance', 'finance_us.mp3', 'verb', 'B1', 'to provide money for a project', '', 'finance something, He took a job to finance his stay in Germany.', '', ARRAY[]::TEXT[]),
('Financial', 'financial_us.mp3', 'adjective', 'B1', 'connected with money and finance', '', 'the world''s major financial markets/institutions', '', ARRAY[]::TEXT[]),
('Find', 'find_us.mp3', 'verb', 'B1', 'to discover somebody/something unexpectedly or by chance', '', 'find somebody/something, Look what I''ve found!', '', ARRAY[]::TEXT[]),
('Finding', 'finding_us.mp3', 'noun', 'B1', 'information that is discovered as the result of research into something', '', 'Our research findings indicate that pregnant women benefit from this treatment.', '', ARRAY[]::TEXT[]),
('Fine', 'fine_us.mp3', 'adjective', 'B1', 'in good health', '', '‘How are you?’ ‘Fine, thanks.’', '', ARRAY[]::TEXT[]),
('Fine', 'fine_us.mp3', 'noun', 'B1', 'a sum of money that must be paid as punishment for breaking a law or rule', '', 'I got a parking fine for parking on double yellow lines.', '', ARRAY[]::TEXT[]),
('Fine', 'fine_us.mp3', 'verb', 'B1', 'to make somebody pay money as an official punishment', '', 'fine somebody (something), The magistrate fined him $400.', '', ARRAY[]::TEXT[]),
('Finger', 'finger_us.mp3', 'noun', 'B1', 'one of the four long thin parts that stick out from the hand (or five, if the thumb is included)', '', 'She ran her fingers through her hair.', '', ARRAY[]::TEXT[]),
('Finish', 'finish_us.mp3', 'noun', 'B1', 'the last part or the end of something', '', 'It was a close finish as they had predicted.', '', ARRAY[]::TEXT[]),
('Finish', 'finish_us.mp3', 'verb', 'B1', 'to stop doing something or making something because it is complete', '', 'finish (something), Haven''t you finished your homework yet?', '', ARRAY[]::TEXT[]),
('Fire', 'fire_us.mp3', 'noun', 'B1', 'the flames, light and heat, and often smoke, that are produced when something burns', '', 'Most animals are afraid of fire.', '', ARRAY[]::TEXT[]),
('Fire', 'fire_us.mp3', 'verb', 'B1', 'to shoot bullets, etc. from a gun or other weapon', '', 'The officer ordered his men to fire.', '', ARRAY[]::TEXT[]),
('Firearm', 'firearm_us.mp3', 'noun', 'B1', 'a gun that can be carried', '', 'The police were issued with firearms.', '', ARRAY[]::TEXT[]),
('Firefighter', 'firefighter_us.mp3', 'noun', 'B1', 'a person whose job is to put out fires', '', 'Firefighters were called to a house in Summertown.', '', ARRAY[]::TEXT[]),
('Firework', 'firework_us.mp3', 'noun', 'B1', 'a small device containing powder that burns or explodes and produces bright coloured lights and loud noises, used especially at celebrations', '', '(British English), to let off a few fireworks', '', ARRAY[]::TEXT[]),
('Firm', 'firm_us.mp3', 'adjective', 'B1', 'fairly hard; not easy to press into a different shape', '', 'a firm bed/mattress', '', ARRAY[]::TEXT[]),
('Firm', 'firm_us.mp3', 'noun', 'B1', 'a business or company', '', 'a law/consulting/research firm', '', ARRAY[]::TEXT[]),
('Firmly', 'firmly_us.mp3', 'adverb', 'B1', 'in a strong or definite way', '', '‘I can manage,’ she said firmly.', '', ARRAY[]::TEXT[]),
('First', 'first_us.mp3', 'adverb', 'B1', 'before anyone or anything else; at the beginning', '', '‘Do you want a drink?’ ‘I''ll finish my work first.’', '', ARRAY[]::TEXT[]),
('First', 'first_us.mp3', 'determiner', 'B1', 'happening or coming before all other similar things or people; 1st', '', 'her first husband', '', ARRAY[]::TEXT[]),
('First', 'first_us.mp3', 'noun', 'B1', 'the person or thing that comes or happens before all other similar people or things', '', 'I was the first in my family to go to college.', '', ARRAY[]::TEXT[]),
('First', 'first_us.mp3', 'ordinal number', 'B1', 'happening or coming before all other similar things or people; 1st', '', 'her first husband', '', ARRAY[]::TEXT[]),
('Firstly', 'firstly_us.mp3', 'adverb', 'B1', 'used to introduce the first of a list of points you want to make in a speech or piece of writing', '', 'There are two reasons for this decision: firstly…', '', ARRAY[]::TEXT[]),
('Fish', 'fish_us.mp3', 'noun', 'B1', 'a creature that lives in water, breathes through gills, and uses fins and a tail for swimming', '', 'They caught several fish.', '', ARRAY[]::TEXT[]),
('Fish', 'fish_us.mp3', 'verb', 'B1', 'to try to catch fish with nets, a fishing line, etc.', '', 'The trawler was fishing off the coast of Iceland.', '', ARRAY[]::TEXT[]),
('Fishing', 'fishing_us.mp3', 'noun', 'B1', 'the sport or business of catching fish', '', 'They often go fishing.', '', ARRAY[]::TEXT[]),
('Fit', 'fit_us.mp3', 'adjective', 'B1', 'healthy and strong, especially because you do regular physical exercise', '', 'Top athletes have to be very fit.', '', ARRAY[]::TEXT[]),
('Fit', 'fit_us.mp3', 'noun', 'B1', 'a sudden attack of an illness, such as epilepsy, in which somebody becomes unconscious and their body may make violent movements', '', 'to have an epileptic fit', '', ARRAY[]::TEXT[]),
('Fit', 'fit_us.mp3', 'verb', 'B1', 'to be the right shape and size for somebody/something', '', 'I tried the dress on but it didn''t fit.', '', ARRAY[]::TEXT[]),
('Fitness', 'fitness_us.mp3', 'noun', 'B1', 'the state of being physically healthy and strong', '', 'a magazine on health and fitness', '', ARRAY[]::TEXT[]),
('Five', 'five_us.mp3', 'number', 'B1', '5', '', 'There are only five cookies left.', '', ARRAY[]::TEXT[]),
('Fix', 'fix_us.mp3', 'noun', 'B1', 'a solution to a problem, especially an easy or temporary one', '', 'Luckily there is an easy fix.', '', ARRAY[]::TEXT[]),
('Fix', 'fix_us.mp3', 'verb', 'B1', 'to repair or correct something', '', 'The car won''t start—can you fix it?', '', ARRAY[]::TEXT[]),
('Fixed', 'fixed_us.mp3', 'adjective', 'B1', 'staying the same; not changing or able to be changed', '', 'These fixed prices give farmers a degree of financial security.', '', ARRAY[]::TEXT[]),
('Fixture', 'fixture_us.mp3', 'noun', 'B1', 'a sports event that has been arranged to take place on a particular date and at a particular place', '', 'There are plans to make the race an annual fixture.', '', ARRAY[]::TEXT[]),
('Flag', 'flag_us.mp3', 'noun', 'B1', 'a piece of cloth with a special coloured design on it that may be the symbol of a particular country or organization, may be used to give a signal or may have a particular meaning. A flag can be attached to a pole (= a long thin straight piece of wood or metal) or held in the hand.', '', 'the Italian flag', '', ARRAY[]::TEXT[]),
('Flame', 'flame_us.mp3', 'noun', 'B1', 'a hot bright stream of burning gas that comes from something that is on fire', '', 'the tiny yellow flame of a match', '', ARRAY[]::TEXT[]),
('Flash', 'flash_us.mp3', 'noun', 'B1', 'a sudden bright light that shines for a moment and then disappears', '', 'a flash of lightning', '', ARRAY[]::TEXT[]),
('Flash', 'flash_us.mp3', 'verb', 'B1', 'to shine very brightly for a short time; to make something shine in this way', '', 'Lightning flashed in the distance.', '', ARRAY[]::TEXT[]),
('Flat', 'flat_us.mp3', 'adjective', 'B1', 'having a level surface, not curved or sloping, and without holes or any bits sticking out', '', 'low buildings with flat roofs', '', ARRAY[]::TEXT[]),
('Flat', 'flat_us.mp3', 'noun', 'B1', 'a set of rooms for living in, usually on one floor of a building', '', 'They''re renting a furnished flat on the third floor.', '', ARRAY[]::TEXT[]),
('Flavour', 'flavour_us.mp3', 'noun', 'B1', 'how food or drink tastes', '', 'The tomatoes give extra flavour to the sauce.', '', ARRAY[]::TEXT[]),
('Flaw', 'flaw_us.mp3', 'noun', 'B1', 'a mistake in something that means that it is not correct or does not work correctly', '', 'The argument is full of fundamental flaws.', '', ARRAY[]::TEXT[]),
('Flawed', 'flawed_us.mp3', 'adjective', 'B1', 'having a flaw; not perfect or correct', '', 'seriously/fundamentally/fatally flawed', '', ARRAY[]::TEXT[]),
('Flee', 'flee_us.mp3', 'verb', 'B1', 'to leave a person or place very quickly, especially because you are afraid of possible danger', '', 'She burst into tears and fled.', '', ARRAY[]::TEXT[]),
('Fleet', 'fleet_us.mp3', 'noun', 'B1', 'a group of military ships commanded by the same person', '', 'a fleet of destroyers', '', ARRAY[]::TEXT[]),
('Flesh', 'flesh_us.mp3', 'noun', 'B1', 'the soft substance between the skin and bones of animal or human bodies', '', 'The trap had cut deeply into the rabbit''s flesh.', '', ARRAY[]::TEXT[]),
('Flexibility', 'flexibility_us.mp3', 'noun', 'B1', 'the ability to change to suit new conditions or situations', '', 'The new system offers a much greater degree of flexibility in the way work is organized.', '', ARRAY[]::TEXT[]),
('Flexible', 'flexible_us.mp3', 'adjective', 'B1', 'able to change to suit new conditions or situations', '', 'a more flexible approach', '', ARRAY[]::TEXT[]),
('Flight', 'flight_us.mp3', 'noun', 'B1', 'a journey made by air, especially in a plane', '', 'a smooth/comfortable/bumpy flight', '', ARRAY[]::TEXT[]),
('Float', 'float_us.mp3', 'verb', 'B1', 'to move slowly on water or in the air', '', 'A group of swans floated by.', '', ARRAY[]::TEXT[]),
('Flood', 'flood_us.mp3', 'noun', 'B1', 'a large amount of water covering an area that is usually dry', '', 'The heavy rain has caused floods in many parts of the country.', '', ARRAY[]::TEXT[]),
('Flood', 'flood_us.mp3', 'verb', 'B1', 'if a place floods or something floods it, it becomes filled or covered with water', '', 'The cellar floods whenever it rains heavily.', '', ARRAY[]::TEXT[]),
('Floor', 'floor_us.mp3', 'noun', 'B1', 'the surface of a room that you walk on', '', 'a wooden/concrete/tiled floor', '', ARRAY[]::TEXT[]),
('Flour', 'flour_us.mp3', 'noun', 'B1', 'a fine white or brown powder made from grain, especially wheat, and used in cooking for making bread, cakes, etc.', '', 'Sift the flour and salt into a bowl.', '', ARRAY[]::TEXT[]),
('Flourish', 'flourish_us.mp3', 'verb', 'B1', 'to develop quickly and become successful or common', '', 'Few businesses are flourishing in the present economic climate.', '', ARRAY[]::TEXT[]),
('Flow', 'flow_us.mp3', 'noun', 'B1', 'the steady and continuous movement of something/somebody in one direction', '', 'the flow of an electric current', '', ARRAY[]::TEXT[]),
('Flow', 'flow_us.mp3', 'verb', 'B1', 'to move steadily and continuously in one direction', '', 'She lost control and the tears began to flow.', '', ARRAY[]::TEXT[]),
('Flower', 'flower_us.mp3', 'noun', 'B1', 'the coloured part of a plant from which the seed or fruit develops. Flowers usually grow at the end of a stem and last only a short time.', '', 'The plant has a beautiful bright red flower.', '', ARRAY[]::TEXT[]),
('Flu', 'flu_us.mp3', 'noun', 'B1', 'a serious disease caused by a virus, that causes a high temperature, severe pains and weakness', '', 'The whole family has the flu.', '', ARRAY[]::TEXT[]),
('Fluid', 'fluid_us.mp3', 'noun', 'B1', 'a liquid; a substance that can flow', '', 'body fluids (= for example, blood)', '', ARRAY[]::TEXT[]),
('Fly', 'fly_us.mp3', 'noun', 'B1', 'a small flying insect with two wings. There are many different types of fly and many of them spread disease.', '', 'A fly was buzzing against the window.', '', ARRAY[]::TEXT[]),
('Fly', 'fly_us.mp3', 'verb', 'B1', 'to move through the air, using wings', '', 'Penguins can''t fly.', '', ARRAY[]::TEXT[]),
('Flying', 'flying_us.mp3', 'adjective', 'B1', 'able to fly', '', 'flying insects', '', ARRAY[]::TEXT[]),
('Flying', 'flying_us.mp3', 'noun', 'B1', 'travelling in an aircraft', '', 'I''m terrified of flying.', '', ARRAY[]::TEXT[]),
('Focus', 'focus_us.mp3', 'noun', 'B1', 'the thing or person that people are most interested in; the act of paying special attention to something and making people interested in it', '', 'focus of something, It was the main focus of attention at the meeting.', '', ARRAY[]::TEXT[]),
('Focus', 'focus_us.mp3', 'verb', 'B1', 'to give attention, effort, etc. to one particular subject, situation or person rather than another', '', 'She was distracted and finding it hard to focus.', '', ARRAY[]::TEXT[]),
('Fold', 'fold_us.mp3', 'noun', 'B1', 'a part of something, especially cloth, that is folded or hangs as if it had been folded', '', 'the folds of her dress', '', ARRAY[]::TEXT[]),
('Fold', 'fold_us.mp3', 'verb', 'B1', 'to bend something, especially paper or cloth, so that one part lies on top of another part', '', 'fold something, First, fold the paper in half/in two.', '', ARRAY[]::TEXT[]),
('Folding', 'folding_us.mp3', 'adjective', 'B1', 'that can be folded, so that it can be carried or stored in a small space', '', 'a folding chair/bike/knife', '', ARRAY[]::TEXT[]),
('Folk', 'folk_us.mp3', 'adjective', 'B1', 'traditional and typical of the ordinary people of a country or community', '', 'We visited an exhibition of folk art.', '', ARRAY[]::TEXT[]),
('Folk', 'folk_us.mp3', 'noun', 'B1', 'people in general', '', 'ordinary working-class folk', '', ARRAY[]::TEXT[]),
('Follow', 'follow_us.mp3', 'verb', 'B1', 'to come or go after or behind somebody/something', '', 'follow somebody/something, Follow me please.', '', ARRAY[]::TEXT[]),
('Following', 'following_us.mp3', 'adjective', 'B1', 'that is/are going to be mentioned next', '', 'Answer the following questions.', '', ARRAY[]::TEXT[]),
('Following', 'following_us.mp3', 'noun', 'B1', 'the thing or things that you will mention next; the person or people that you will mention next', '', 'The following is a summary of events.', '', ARRAY[]::TEXT[]),
('Following', 'following_us.mp3', 'preposition', 'B1', 'after or as a result of a particular event', '', 'He took charge of the family business following his father''s death.', '', ARRAY[]::TEXT[]),
('Fond', 'fond_us.mp3', 'adjective', 'B1', 'having warm or loving feelings for somebody, especially somebody you have known for a long time', '', 'Over the years, I have grown quite fond of her.', '', ARRAY[]::TEXT[]),
('Food', 'food_us.mp3', 'noun', 'B1', 'things that people or animals eat', '', 'Pat had prepared food and drink for the work party.', '', ARRAY[]::TEXT[]),
('Fool', 'fool_us.mp3', 'noun', 'B1', 'a person who you think behaves or speaks in a way that lacks intelligence or good judgement', '', 'Don''t be such a fool!', '', ARRAY[]::TEXT[]),
('Foot', 'foot_us.mp3', 'noun', 'B1', 'the lowest part of the leg, below the ankle, on which a person or an animal stands', '', 'My feet are aching.', '', ARRAY[]::TEXT[]),
('Footage', 'footage_us.mp3', 'noun', 'B1', 'part of a film showing a particular event', '', 'old film footage of the moon landing', '', ARRAY[]::TEXT[]),
('Football', 'football_us.mp3', 'noun', 'B1', 'a game played by two teams of 11 players, using a round ball that players kick up and down the playing field. Teams try to kick the ball into the other team’s goal.', '', 'The kids were outside playing football.', '', ARRAY[]::TEXT[]),
('For', 'for_us.mp3', 'preposition', 'B1', 'used to show who is intended to have or use something or where something is intended to be put', '', 'There''s a letter for you.', '', ARRAY[]::TEXT[]),
('Forbid', 'forbid_us.mp3', 'verb', 'B1', 'to order somebody not to do something; to order that something must not be done', '', 'forbid somebody (from doing something), He forbade them from mentioning the subject again.', '', ARRAY[]::TEXT[]),
('Force', 'force_us.mp3', 'noun', 'B1', 'violent physical action used to obtain or achieve something', '', 'The release of the hostages could not be achieved without the use of force.', '', ARRAY[]::TEXT[]),
('Force', 'force_us.mp3', 'verb', 'B1', 'to make somebody do something that they do not want to do', '', 'be forced into doing something, The President was forced into resigning.', '', ARRAY[]::TEXT[]),
('Forecast', 'forecast_us.mp3', 'noun', 'B1', 'a statement about what will happen in the future, based on information that is available now', '', 'The sales forecasts are encouraging.', '', ARRAY[]::TEXT[]),
('Forecast', 'forecast_us.mp3', 'verb', 'B1', 'to say what you think will happen in the future based on information that you have now', '', 'forecast something, Experts are forecasting a recovery in the economy.', '', ARRAY[]::TEXT[]),
('Foreign', 'foreign_us.mp3', 'adjective', 'B1', 'in or from a country that is not your own', '', 'What foreign languages do you speak?', '', ARRAY[]::TEXT[]),
('Foreigner', 'foreigner_us.mp3', 'noun', 'B1', 'a person who comes from a different country', '', 'The fact that I was a foreigner was a big disadvantage.', '', ARRAY[]::TEXT[]),
('Forest', 'forest_us.mp3', 'noun', 'B1', 'a large area of land that is thickly covered with trees', '', 'a tropical/pine forest', '', ARRAY[]::TEXT[]),
('Forever', 'forever_us.mp3', 'adverb', 'B1', 'used to say that a particular situation or state will always exist', '', 'I''ll love you forever!', '', ARRAY[]::TEXT[]),
('Forge', 'forge_us.mp3', 'verb', 'B1', 'to put a lot of effort into making something successful or strong so that it will last', '', 'a move to forge new links between management and workers', '', ARRAY[]::TEXT[]),
('Forget', 'forget_us.mp3', 'verb', 'B1', 'to not remember to do something that you ought to do, or to bring or buy something that you ought to bring or buy', '', '‘Why weren''t you at the meeting?’ ‘Sorry—I forgot.’', '', ARRAY[]::TEXT[]),
('Forgive', 'forgive_us.mp3', 'verb', 'B1', 'to stop feeling angry with somebody who has done something to harm, annoy or upset you; to stop feeling angry with yourself', '', 'forgive somebody, Can you ever forgive me?', '', ARRAY[]::TEXT[]),
('Fork', 'fork_us.mp3', 'noun', 'B1', 'a tool with a handle and three or four sharp points (called prongs), used for picking up and eating food', '', 'to eat with a knife and fork', '', ARRAY[]::TEXT[]),
('Form', 'form_us.mp3', 'noun', 'B1', 'a type or variety of something', '', 'all the millions of different life forms on the planet today', '', ARRAY[]::TEXT[]),
('Form', 'form_us.mp3', 'verb', 'B1', 'to produce something in a particular way or make it have a particular shape', '', 'form something, Bend the wire so that it forms a ‘V’.', '', ARRAY[]::TEXT[]),
('Formal', 'formal_us.mp3', 'adjective', 'B1', 'very correct and suitable for official or important occasions', '', 'ladies in formal evening wear', '', ARRAY[]::TEXT[]),
('Format', 'format_us.mp3', 'noun', 'B1', 'the general arrangement, plan, design, etc. of something', '', 'The format of the new quiz show has proved popular.', '', ARRAY[]::TEXT[]),
('Formation', 'formation_us.mp3', 'noun', 'B1', 'the action of forming something; the process of being formed', '', 'the formation of a new government', '', ARRAY[]::TEXT[]),
('Former', 'former_us.mp3', 'adjective', 'B1', 'that existed in earlier times', '', 'This fine ruin was, in former times, a royal castle.', '', ARRAY[]::TEXT[]),
('Formerly', 'formerly_us.mp3', 'adverb', 'B1', 'in the past', '', 'Namibia, formerly known as South West Africa', '', ARRAY[]::TEXT[]),
('Formula', 'formula_us.mp3', 'noun', 'B1', 'a series of letters, numbers or symbols that represent a rule or law', '', 'This formula is used to calculate the area of a circle.', '', ARRAY[]::TEXT[]),
('Formulate', 'formulate_us.mp3', 'verb', 'B1', 'to create or prepare something carefully, giving particular attention to the details', '', 'formulate something, to formulate a policy/theory/plan/proposal', '', ARRAY[]::TEXT[]),
('Forth', 'forth_us.mp3', 'adverb', 'B1', 'away from a place; out', '', 'They set forth at dawn.', '', ARRAY[]::TEXT[]),
('Forthcoming', 'forthcoming_us.mp3', 'adjective', 'B1', 'going to happen, be published, etc. very soon', '', 'the forthcoming elections', '', ARRAY[]::TEXT[]),
('Fortunate', 'fortunate_us.mp3', 'adjective', 'B1', 'having or bringing an advantage, an opportunity, a piece of good luck, etc.', '', 'Remember those less fortunate than yourselves.', '', ARRAY[]::TEXT[]),
('Fortunately', 'fortunately_us.mp3', 'adverb', 'B1', 'by good luck', '', 'I was late, but fortunately the meeting hadn''t started.', '', ARRAY[]::TEXT[]),
('Fortune', 'fortune_us.mp3', 'noun', 'B1', 'a large amount of money', '', 'He made a fortune in real estate.', '', ARRAY[]::TEXT[]),
('Forum', 'forum_us.mp3', 'noun', 'B1', 'an event or medium where people can exchange opinions and ideas on a particular issue; a meeting organized for this purpose', '', 'forum (on something), to hold an international forum on drug abuse', '', ARRAY[]::TEXT[]),
('Forward', 'forward_us.mp3', 'adjective', 'B1', 'directed or moving towards the front', '', 'The door opened, blocking his forward movement.', '', ARRAY[]::TEXT[]),
('Forward', 'forward_us.mp3', 'adverb', 'B1', 'towards a place or position that is in front', '', 'She leaned forward and kissed him on the cheek.', '', ARRAY[]::TEXT[]),
('Fossil', 'fossil_us.mp3', 'noun', 'B1', 'the parts of a dead animal or a plant that have become hard and turned into rock', '', 'fossils over two million years old', '', ARRAY[]::TEXT[]),
('Foster', 'foster_us.mp3', 'verb', 'B1', 'to encourage something to develop', '', 'The club''s aim is to foster better relations within the community.', '', ARRAY[]::TEXT[]),
('Found', 'found_us.mp3', 'verb', 'B1', 'to start something, such as an organization or an institution, especially by providing money', '', 'to found a club/company/school', '', ARRAY[]::TEXT[]),
('Foundation', 'foundation_us.mp3', 'noun', 'B1', 'a principle, an idea or a fact that something is based on and that it grows from', '', 'Respect and friendship provide a solid foundation for marriage.', '', ARRAY[]::TEXT[]),
('Founder', 'founder_us.mp3', 'noun', 'B1', 'a person who starts an organization, institution, etc. or causes something to be built', '', 'the founder and president of the company', '', ARRAY[]::TEXT[]),
('Fourth', 'fourth_us.mp3', 'ordinal number', 'B1', '4th', '', 'Today is the fourth (of May).', '', ARRAY[]::TEXT[]),
('Fraction', 'fraction_us.mp3', 'noun', 'B1', 'a small part or amount of something', '', 'Only a small fraction of a bank''s total deposits will be withdrawn at any one time.', '', ARRAY[]::TEXT[]),
('Fragile', 'fragile_us.mp3', 'adjective', 'B1', 'easily broken or damaged', '', 'fragile china/glass/bones', '', ARRAY[]::TEXT[]),
('Fragment', 'fragment_us.mp3', 'noun', 'B1', 'a small part of something that has broken off or comes from something larger', '', 'fragment (of something), Police found fragments of glass near the scene.', '', ARRAY[]::TEXT[]),
('Frame', 'frame_us.mp3', 'noun', 'B1', 'a strong border or structure of wood, metal, etc. that holds a picture, door, piece of glass, etc. in position', '', 'a picture/photo frame', '', ARRAY[]::TEXT[]),
('Frame', 'frame_us.mp3', 'verb', 'B1', 'to put or make a frame or border around something', '', 'be framed, The photograph had been framed.', '', ARRAY[]::TEXT[]),
('Framework', 'framework_us.mp3', 'noun', 'B1', 'the parts of a building or an object that support its weight and give it shape', '', 'built on a wooden framework', '', ARRAY[]::TEXT[]),
('Franchise', 'franchise_us.mp3', 'noun', 'B1', 'formal permission given by a company to somebody who wants to sell its goods or services in a particular area; formal permission given by a government to somebody who wants to operate a public service as a business', '', 'a franchise agreement/company', '', ARRAY[]::TEXT[]),
('Frankly', 'frankly_us.mp3', 'adverb', 'B1', 'in an honest and direct way that people might not like', '', 'He spoke frankly about the ordeal.', '', ARRAY[]::TEXT[]),
('Fraud', 'fraud_us.mp3', 'noun', 'B1', 'the crime of cheating somebody in order to get money or goods illegally', '', 'She was charged with credit card fraud.', '', ARRAY[]::TEXT[]),
('Free', 'free_us.mp3', 'adjective', 'B1', 'without particular plans or arrangements; not busy', '', 'Are you free on Saturday? We''re having a barbecue.', '', ARRAY[]::TEXT[]),
('Free', 'free_us.mp3', 'adverb', 'B1', 'without payment', '', 'Children under five travel free.', '', ARRAY[]::TEXT[]),
('Free', 'free_us.mp3', 'verb', 'B1', 'to allow somebody to leave prison or somewhere they have been kept against their will', '', 'free somebody, The hijackers agreed to free a further ten hostages.', '', ARRAY[]::TEXT[]),
('Freedom', 'freedom_us.mp3', 'noun', 'B1', 'the power or right to do or say what you want without anyone stopping you', '', 'to defend/protect academic freedom', '', ARRAY[]::TEXT[]),
('Freely', 'freely_us.mp3', 'adverb', 'B1', 'without anyone trying to prevent or control something', '', 'the country’s first freely elected president', '', ARRAY[]::TEXT[]),
('Freeze', 'freeze_us.mp3', 'verb', 'B1', 'to become hard, and often turn to ice, as a result of extreme cold; to make something do this', '', 'Water freezes at 0°C.', '', ARRAY[]::TEXT[]),
('Frequency', 'frequency_us.mp3', 'noun', 'B1', 'the rate at which something happens or is repeated', '', 'Fatal road accidents have decreased in frequency over recent years.', '', ARRAY[]::TEXT[]),
('Frequent', 'frequent_us.mp3', 'adjective', 'B1', 'happening or doing something often', '', 'He is a frequent visitor to this country.', '', ARRAY[]::TEXT[]),
('Frequently', 'frequently_us.mp3', 'adverb', 'B1', 'often', '', 'Buses run frequently between the city and the airport.', '', ARRAY[]::TEXT[]),
('Fresh', 'fresh_us.mp3', 'adjective', 'B1', 'recently produced or picked and not frozen, dried or preserved in tins or cans', '', 'Is this milk fresh?', '', ARRAY[]::TEXT[]),
('Friday', 'Friday_us.mp3', 'noun', 'B1', 'the day of the week after Thursday and before Saturday', '', 'It''s Friday today, isn''t it?', '', ARRAY[]::TEXT[]),
('Fridge', 'fridge_us.mp3', 'noun', 'B1', 'a piece of electrical equipment in which food is kept cold so that it stays fresh', '', 'The kids tend to raid the fridge when they get home from school.', '', ARRAY[]::TEXT[]),
('Friend', 'friend_us.mp3', 'noun', 'B1', 'a person you know well and like, and who is not usually a member of your family', '', 'This is my friend Tom.', '', ARRAY[]::TEXT[]),
('Friendly', 'friendly_us.mp3', 'adjective', 'B1', 'behaving in a kind and pleasant way because you like somebody or want to help them', '', 'a warm and friendly person', '', ARRAY[]::TEXT[]),
('Friendship', 'friendship_us.mp3', 'noun', 'B1', 'a relationship between friends', '', 'They formed a close friendship at college.', '', ARRAY[]::TEXT[]),
('Frighten', 'frighten_us.mp3', 'verb', 'B1', 'to make somebody suddenly feel afraid', '', 'frighten (somebody), Sorry, I didn''t mean to frighten you.', '', ARRAY[]::TEXT[]),
('Frightened', 'frightened_us.mp3', 'adjective', 'B1', 'afraid; feeling fear', '', 'a frightened child', '', ARRAY[]::TEXT[]),
('Frightening', 'frightening_us.mp3', 'adjective', 'B1', 'making you feel afraid', '', 'a frightening experience/prospect/thought', '', ARRAY[]::TEXT[]),
('Frog', 'frog_us.mp3', 'noun', 'B1', 'a small animal with smooth skin, that lives both on land and in water (= is an amphibian). Frogs have very long back legs for jumping, and no tail.', '', 'the croaking of frogs', '', ARRAY[]::TEXT[]),
('From', 'from_us.mp3', 'preposition', 'B1', 'used to show where somebody/something starts', '', 'She began to walk away from him.', '', ARRAY[]::TEXT[]),
('Front', 'front_us.mp3', 'adjective', 'B1', 'on or at the front of something', '', '(British English), the front garden', '', ARRAY[]::TEXT[]),
('Front', 'front_us.mp3', 'noun', 'B1', 'the part or side of something that faces forward; the side of something that you look at first', '', 'The front of the building was covered with ivy.', '', ARRAY[]::TEXT[]),
('Frozen', 'frozen_us.mp3', 'adjective', 'B1', 'kept at a very low temperature in order to preserve it', '', 'frozen peas/fish/pizza', '', ARRAY[]::TEXT[]),
('Fruit', 'fruit_us.mp3', 'noun', 'B1', 'the part of a plant that consists of one or more seeds and a soft inner part, can be eaten as food and usually tastes sweet', '', 'tropical fruits, such as bananas and pineapples', '', ARRAY[]::TEXT[]),
('Frustrated', 'frustrated_us.mp3', 'adjective', 'B1', 'feeling annoyed and impatient because you cannot do or achieve what you want', '', 'It''s very easy to get frustrated in this job.', '', ARRAY[]::TEXT[]),
('Frustrating', 'frustrating_us.mp3', 'adjective', 'B1', 'causing you to feel annoyed and impatient because you cannot do or achieve what you want', '', 'It''s frustrating to have to wait so long.', '', ARRAY[]::TEXT[]),
('Frustration', 'frustration_us.mp3', 'noun', 'B1', 'the feeling of being frustrated', '', 'in frustration, Dave thumped the table in frustration.', '', ARRAY[]::TEXT[]),
('Fry', 'fry_us.mp3', 'verb', 'B1', 'to cook something in hot fat or oil; to be cooked in hot fat or oil', '', 'fry (something), fried fish', '', ARRAY[]::TEXT[]),
('Fuel', 'fuel_us.mp3', 'noun', 'B1', 'any material that produces heat or power, usually when it is burnt', '', 'diesel/jet/rocket fuel', '', ARRAY[]::TEXT[]),
('Fuel', 'fuel_us.mp3', 'verb', 'B1', 'to supply something with material that can be burnt to produce heat or power', '', 'Uranium is used to fuel nuclear plants.', '', ARRAY[]::TEXT[]),
('Fulfil', 'fulfil_us.mp3', 'verb', 'B1', 'to do or achieve what was hoped for or expected', '', 'to fulfil your dream/ambition/potential', '', ARRAY[]::TEXT[]),
('Full', 'full_us.mp3', 'adjective', 'B1', 'containing or holding as much or as many as possible; having no empty space', '', 'a full bottle of wine', '', ARRAY[]::TEXT[]),
('Full-time', 'full-time_us.mp3', 'adjective', 'B1', 'for all the hours of a week during which people normally work or study, rather than just for a part of it', '', 'students in full-time education', '', ARRAY[]::TEXT[]),
('Full-time', 'full-time_us.mp3', 'adverb', 'B1', 'for all the hours of a week during which people normally work or study, rather than just for a part of it', '', 'students in full-time education', '', ARRAY[]::TEXT[]),
('Fully', 'fully_us.mp3', 'adverb', 'B1', 'completely', '', 'I fully understand your motives.', '', ARRAY[]::TEXT[]),
('Fun', 'fun_us.mp3', 'adjective', 'B1', 'that you enjoy', '', 'She''s really fun to be with.', '', ARRAY[]::TEXT[]),
('Fun', 'fun_us.mp3', 'noun', 'B1', 'the feeling of enjoying yourself; activities that you enjoy', '', 'We had a lot of fun at Sarah''s party.', '', ARRAY[]::TEXT[]),
('Function', 'function_us.mp3', 'noun', 'B1', 'a special activity or purpose of a person or thing', '', 'The club serves a useful function as a meeting place.', '', ARRAY[]::TEXT[]),
('Function', 'function_us.mp3', 'verb', 'B1', 'to work in the correct way', '', 'We now have a functioning shower.', '', ARRAY[]::TEXT[]),
('Functional', 'functional_us.mp3', 'adjective', 'B1', 'practical and useful; with little or no decoration', '', 'Bathrooms don''t have to be purely functional.', '', ARRAY[]::TEXT[]),
('Fund', 'fund_us.mp3', 'noun', 'B1', 'an amount of money that has been saved or has been made available for a particular purpose', '', 'a disaster relief fund', '', ARRAY[]::TEXT[]),
('Fund', 'fund_us.mp3', 'verb', 'B1', 'to provide money for something, usually something official', '', 'Who is funding this research?', '', ARRAY[]::TEXT[]),
('Fundamental', 'fundamental_us.mp3', 'adjective', 'B1', 'serious and very important; affecting the most central and important parts of something', '', 'the fundamental principles of scientific method', '', ARRAY[]::TEXT[]),
('Fundamentally', 'fundamentally_us.mp3', 'adverb', 'B1', 'in every way that is important; completely', '', 'The two approaches are fundamentally different.', '', ARRAY[]::TEXT[]),
('Funding', 'funding_us.mp3', 'noun', 'B1', 'money for a particular purpose; the act of providing money for such a purpose', '', 'federal/state funding', '', ARRAY[]::TEXT[]),
('Fundraising', 'fundraising_us.mp3', 'noun', 'B1', 'the activity of collecting money for a charity or organization, often by organizing social events or entertainments', '', 'The hospice is planning a major fundraising event for June.', '', ARRAY[]::TEXT[]),
('Funeral', 'funeral_us.mp3', 'noun', 'B1', 'a ceremony, often a religious one, for burying or cremating (= burning) a dead person', '', 'Hundreds of people attended the funeral.', '', ARRAY[]::TEXT[]),
('Funny', 'funny_us.mp3', 'adjective', 'B1', 'making you laugh', '', 'a funny story/joke', '', ARRAY[]::TEXT[]),
('Fur', 'fur_us.mp3', 'noun', 'B1', 'the soft thick mass of hair that grows on the body of some animals', '', 'The cat carefully licked its fur.', '', ARRAY[]::TEXT[]),
('Furious', 'furious_us.mp3', 'adjective', 'B1', 'very angry', '', 'Their incompetence made me furious.', '', ARRAY[]::TEXT[]),
('Furniture', 'furniture_us.mp3', 'noun', 'B1', 'objects that can be moved, such as tables, chairs and beds, that are put into a house or an office to make it suitable for living or working in', '', 'garden/office furniture', '', ARRAY[]::TEXT[]),
('Further', 'further_us.mp3', 'adjective', 'B1', 'more; additional', '', 'Cook for a further 2 minutes.', '', ARRAY[]::TEXT[]),
('Further', 'further_us.mp3', 'adverb', 'B1', 'at or to a greater distance', '', 'We had walked a bit further than I had realized.', '', ARRAY[]::TEXT[]),
('Furthermore', 'furthermore_us.mp3', 'adverb', 'B1', 'in addition to what has just been stated. Furthermore is used especially to add a point to an argument.', '', 'He said he had not discussed the matter with her. Furthermore, he had not even contacted her.', '', ARRAY[]::TEXT[]),
('Future', 'future_us.mp3', 'adjective', 'B1', 'taking place or existing at a time after the present', '', 'The land will remain untouched for future generations to enjoy.', '', ARRAY[]::TEXT[]),
('Future', 'future_us.mp3', 'noun', 'B1', 'the time that will come after the present or the events that will happen then', '', 'We need to plan for the future.', '', ARRAY[]::TEXT[]),
('Gain', 'gain_us.mp3', 'noun', 'B1', 'an increase in the amount of something, especially in wealth or weight', '', 'The opposition made unexpected gains in the last election.', '', ARRAY[]::TEXT[]),
('Gain', 'gain_us.mp3', 'verb', 'B1', 'to obtain or win something, especially something that you need or want', '', 'gain something, They managed to gain access to secret files.', '', ARRAY[]::TEXT[]),
('Gallery', 'gallery_us.mp3', 'noun', 'B1', 'a room or building for showing works of art, especially to the public', '', 'a picture gallery', '', ARRAY[]::TEXT[]),
('Gallon', 'gallon_us.mp3', 'noun', 'B1', 'a unit for measuring liquid. In the UK, Canada and other countries it is equal to about 4.5 litres; in the US it is equal to about 3.8 litres. There are four quarts in a gallon.', '', 'The tankers carried 130 000 gallons of fuel.', '', ARRAY[]::TEXT[]),
('Gambling', 'gambling_us.mp3', 'noun', 'B1', 'the activity of playing games of chance for money and of betting on horses, etc.', '', 'online/internet gambling', '', ARRAY[]::TEXT[]),
('Game', 'game_us.mp3', 'noun', 'B1', 'an activity that you do to have fun, often one that has rules and that you can win or lose; the equipment for a game', '', 'The kids were playing a game with their balloons.', '', ARRAY[]::TEXT[]),
('Gaming', 'gaming_us.mp3', 'noun', 'B1', 'playing computer games', '', 'online/mobile/console gaming', '', ARRAY[]::TEXT[]),
('Gang', 'gang_us.mp3', 'noun', 'B1', 'an organized group of criminals', '', 'criminal gangs', '', ARRAY[]::TEXT[]),
('Gap', 'gap_us.mp3', 'noun', 'B1', 'a space where something is missing', '', 'Extra funding is needed to plug the gap.', '', ARRAY[]::TEXT[]),
('Garage', 'garage_us.mp3', 'noun', 'B1', 'a building for keeping one or more cars or other vehicles in', '', 'a double garage (= one for two cars)', '', ARRAY[]::TEXT[]),
('Garden', 'garden_us.mp3', 'noun', 'B1', 'a piece of land next to or around your house where you can grow flowers, fruit, vegetables, etc., usually with a lawn (= an area of grass)', '', 'a front/back/rear garden', '', ARRAY[]::TEXT[]),
('Gas', 'gas_us.mp3', 'noun', 'B1', 'any substance like air that is neither a solid nor a liquid, for example hydrogen or oxygen', '', 'Air is a mixture of gases.', '', ARRAY[]::TEXT[]),
('Gate', 'gate_us.mp3', 'noun', 'B1', 'a barrier like a door that is used to close an opening in a fence or a wall outside a building', '', 'the front/main gate', '', ARRAY[]::TEXT[]),
('Gather', 'gather_us.mp3', 'verb', 'B1', 'to come together, or bring people together, in one place to form a group', '', 'A crowd soon gathered.', '', ARRAY[]::TEXT[]),
('Gathering', 'gathering_us.mp3', 'noun', 'B1', 'a meeting of people for a particular purpose', '', 'a social/family gathering', '', ARRAY[]::TEXT[]),
('Gay', 'gay_us.mp3', 'adjective', 'B1', 'sexually attracted to people of the same sex', '', 'gay men', '', ARRAY[]::TEXT[]),
('Gaze', 'gaze_us.mp3', 'noun', 'B1', 'a long, steady look at somebody/something', '', 'He met her gaze (= looked at her while she looked at him).', '', ARRAY[]::TEXT[]),
('Gaze', 'gaze_us.mp3', 'verb', 'B1', 'to look steadily at somebody/something for a long time, either because you are very interested or surprised, or because you are thinking of something else', '', 'She gazed at him in amazement.', '', ARRAY[]::TEXT[]),
('Gear', 'gear_us.mp3', 'noun', 'B1', 'equipment in a vehicle that changes the relation between engine speed (or pedal speed on a bicycle) and the speed of the wheels moving forwards or backwards', '', 'Careless use of the clutch may damage the gears.', '', ARRAY[]::TEXT[]),
('Gender', 'gender_us.mp3', 'noun', 'B1', 'the fact of being male or female, especially when considered with reference to social and cultural differences, rather than differences in biology; members of a particular gender as a group', '', 'issues of class, race and gender', '', ARRAY[]::TEXT[]),
('Gene', 'gene_us.mp3', 'noun', 'B1', 'a unit inside a cell that controls a particular quality in a living thing that has been passed on from its parents', '', 'a dominant/recessive gene', '', ARRAY[]::TEXT[]),
('General', 'general_us.mp3', 'adjective', 'B1', 'affecting all or most people, places or things', '', 'books of general interest (= of interest to most people)', '', ARRAY[]::TEXT[]),
('Generally', 'generally_us.mp3', 'adverb', 'B1', 'by or to most people', '', 'The initiative was generally considered a success.', '', ARRAY[]::TEXT[]),
('Generate', 'generate_us.mp3', 'verb', 'B1', 'to produce energy, especially electricity', '', 'The wind turbines are used to generate electricity.', '', ARRAY[]::TEXT[]),
('Generation', 'generation_us.mp3', 'noun', 'B1', 'all the people who were born at about the same time', '', 'the younger/older generation', '', ARRAY[]::TEXT[]),
('Generic', 'generic_us.mp3', 'adjective', 'B1', 'shared by, including or typical of a whole group of things; not specific', '', '‘Vine fruit’ is the generic term for currants and raisins.', '', ARRAY[]::TEXT[]),
('Generous', 'generous_us.mp3', 'adjective', 'B1', 'giving or willing to give freely; given freely', '', 'The gallery was named after its most generous benefactor.', '', ARRAY[]::TEXT[]),
('Genetic', 'genetic_us.mp3', 'adjective', 'B1', 'connected with genes (= the units in the cells of a living thing that control its physical characteristics) or genetics (= the study of genes)', '', 'genetic and environmental factors', '', ARRAY[]::TEXT[]),
('Genius', 'genius_us.mp3', 'noun', 'B1', 'unusually great intelligence, skill or artistic ability', '', 'the genius of Shakespeare', '', ARRAY[]::TEXT[]),
('Genocide', 'genocide_us.mp3', 'noun', 'B1', 'the murder of a large number of people from a particular nation or ethnic group, with the aim of destroying that nation or group', '', 'Refugees gave accounts of the mass genocide.', '', ARRAY[]::TEXT[]),
('Genre', 'genre_us.mp3', 'noun', 'B1', 'a particular type or style of literature, art, film or music that you can recognize because of its special features', '', 'literary/musical genres', '', ARRAY[]::TEXT[]),
('Gentle', 'gentle_us.mp3', 'adjective', 'B1', 'calm and kind; doing things in a quiet and careful way', '', 'a kind and gentle man', '', ARRAY[]::TEXT[]),
('Gentleman', 'gentleman_us.mp3', 'noun', 'B1', 'a man who is polite and well educated, who has excellent manners and always behaves well', '', 'You acted like a true gentleman.', '', ARRAY[]::TEXT[]),
('Genuine', 'genuine_us.mp3', 'adjective', 'B1', 'real; exactly what it appears to be; not artificial', '', 'Is the painting a genuine Picasso?', '', ARRAY[]::TEXT[]),
('Genuinely', 'genuinely_us.mp3', 'adverb', 'B1', 'truly; in a way that is exactly what it appears to be and is not artificial', '', 'There are some genuinely funny moments in the film.', '', ARRAY[]::TEXT[]),
('Geography', 'geography_us.mp3', 'noun', 'B1', 'the scientific study of the earth’s surface, physical features, divisions, products, population, etc.', '', 'recent work in economic geography', '', ARRAY[]::TEXT[]),
('Gesture', 'gesture_us.mp3', 'noun', 'B1', 'a movement that you make with your hands, your head or your face to show a particular meaning', '', 'He made a rude gesture at the driver of the other car.', '', ARRAY[]::TEXT[]),
('Get', 'get_us.mp3', 'verb', 'B1', 'to receive something', '', 'I got a call from Dave this morning.', '', ARRAY[]::TEXT[]),
('Ghost', 'ghost_us.mp3', 'noun', 'B1', 'the spirit of a dead person that a living person believes they can see or hear', '', 'Do you believe in ghosts (= believe that they exist)?', '', ARRAY[]::TEXT[]),
('Giant', 'giant_us.mp3', 'adjective', 'B1', 'very large; much larger or more important than similar things usually are', '', 'The match was shown on a giant screen outside the town hall.', '', ARRAY[]::TEXT[]),
('Giant', 'giant_us.mp3', 'noun', 'B1', '(in stories) a very large strong person who is often cruel and stupid', '', 'tales of giants and ogres', '', ARRAY[]::TEXT[]),
('Gift', 'gift_us.mp3', 'noun', 'B1', 'a thing that you give to somebody, especially on a special occasion or to say thank you', '', 'to give/receive a gift', '', ARRAY[]::TEXT[]),
('Gig', 'gig_us.mp3', 'noun', 'B1', 'a performance by musicians playing popular music or jazz in front of an audience; a similar performance by a comedian', '', 'They''re doing a gig in Boston tonight.', '', ARRAY[]::TEXT[]),
('Girl', 'girl_us.mp3', 'noun', 'B1', 'a female child', '', 'a little girl of six', '', ARRAY[]::TEXT[]),
('Girlfriend', 'girlfriend_us.mp3', 'noun', 'B1', 'a girl or a woman that somebody is having a romantic relationship with', '', 'He’s got a new girlfriend.', '', ARRAY[]::TEXT[]),
('Give', 'give_us.mp3', 'verb', 'B1', 'to hand something to somebody so that they can look at it, use it or keep it for a time', '', 'give something to somebody, Give the letter to your mother when you''ve read it.', '', ARRAY[]::TEXT[]),
('Glad', 'glad_us.mp3', 'adjective', 'B1', 'pleased; happy', '', '‘I passed the test!’ ‘I’m so glad.’', '', ARRAY[]::TEXT[]),
('Glance', 'glance_us.mp3', 'noun', 'B1', 'a quick look', '', 'to take/have a glance at the newspaper headlines', '', ARRAY[]::TEXT[]),
('Glance', 'glance_us.mp3', 'verb', 'B1', 'to look quickly at something/somebody', '', 'She glanced at her watch.', '', ARRAY[]::TEXT[]),
('Glass', 'glass_us.mp3', 'noun', 'B1', 'a hard, usually clear, substance used, for example, for making windows and bottles', '', 'a sheet/pane of glass', '', ARRAY[]::TEXT[]),
('Glimpse', 'glimpse_us.mp3', 'noun', 'B1', 'a sight of somebody/something for a very short time, when you do not see the person or thing completely', '', 'glimpse (of somebody/something), He caught a glimpse of her in the crowd.', '', ARRAY[]::TEXT[]),
('Global', 'global_us.mp3', 'adjective', 'B1', 'covering or affecting the whole world', '', 'This year the global economy will grow by about 4 per cent.', '', ARRAY[]::TEXT[]),
('Globe', 'globe_us.mp3', 'noun', 'B1', 'the world (used especially to emphasize its size)', '', 'tourists from every corner of the globe', '', ARRAY[]::TEXT[]),
('Glorious', 'glorious_us.mp3', 'adjective', 'B1', 'deserving or bringing great success and making somebody/something famous', '', 'We congratulate you on this glorious victory.', '', ARRAY[]::TEXT[]),
('Glory', 'glory_us.mp3', 'noun', 'B1', 'great success that brings somebody praise and honour and makes them famous', '', 'Olympic glory in the 100 metres', '', ARRAY[]::TEXT[]),
('Glove', 'glove_us.mp3', 'noun', 'B1', 'a piece of clothing for the hand, made of wool, leather, etc. with separate parts for each finger and the thumb', '', 'a pair of gloves', '', ARRAY[]::TEXT[]),
('Go', 'go_us.mp3', 'noun', 'B1', 'a person’s turn to move or play in a game or an activity', '', 'Whose go is it?', '', ARRAY[]::TEXT[]),
('Go', 'go_us.mp3', 'verb', 'B1', 'to move or travel from one place to another', '', '+ adv./prep., She went into her room and shut the door behind her.', '', ARRAY[]::TEXT[]),
('Goal', 'goal_us.mp3', 'noun', 'B1', 'a frame with a net into which players must kick or hit the ball in order to score a point', '', 'He headed the ball into an open goal (= one that had nobody defending it).', '', ARRAY[]::TEXT[]),
('God', 'god_us.mp3', 'noun', 'B1', 'the being or spirit that is worshipped and is believed to have created the universe', '', 'Do you believe in God?', '', ARRAY[]::TEXT[]),
('Gold', 'gold_us.mp3', 'adjective', 'B1', 'bright yellow in colour, like gold', '', 'The company name was spelled out in gold letters.', '', ARRAY[]::TEXT[]),
('Gold', 'gold_us.mp3', 'noun', 'B1', 'a chemical element. Gold is a yellow precious metal used for making coins, jewellery, beautiful objects, etc.', '', 'gold coins/jewellery', '', ARRAY[]::TEXT[]),
('Golden', 'golden_us.mp3', 'adjective', 'B1', 'made of gold', '', 'a golden crown', '', ARRAY[]::TEXT[]),
('Golf', 'golf_us.mp3', 'noun', 'B1', 'a game played over a large area of ground using sticks with a special shape to hit a small hard ball (a golf ball) into a series of 9 or 18 holes, using as few shots as possible', '', 'I play golf every weekend.', '', ARRAY[]::TEXT[]),
('Good', 'good_us.mp3', 'adjective', 'B1', 'of high quality or an acceptable standard', '', 'a good book', '', ARRAY[]::TEXT[]),
('Good', 'good_us.mp3', 'noun', 'B1', 'behaviour that is morally right or acceptable', '', 'Do they even know the difference between good and evil?', '', ARRAY[]::TEXT[]),
('Goodbye', 'goodbye_us.mp3', 'exclamation', 'B1', 'used when you are leaving somebody or when somebody else is leaving', '', 'Goodbye! It was great to meet you.', '', ARRAY[]::TEXT[]),
('Goodbye', 'goodbye_us.mp3', 'noun', 'B1', 'used when you are leaving somebody or when somebody else is leaving', '', 'Goodbye! It was great to meet you.', '', ARRAY[]::TEXT[]),
('Goodness', 'goodness_us.mp3', 'noun', 'B1', 'the quality of being good', '', 'the essential goodness of human nature', '', ARRAY[]::TEXT[]),
('Goods', 'goods_us.mp3', 'noun', 'B1', 'things that are produced to be sold', '', 'to produce/buy/sell goods', '', ARRAY[]::TEXT[]),
('Gorgeous', 'gorgeous_us.mp3', 'adjective', 'B1', 'very beautiful and attractive; giving great pleasure', '', 'a gorgeous girl/man', '', ARRAY[]::TEXT[]),
('Govern', 'govern_us.mp3', 'verb', 'B1', 'to legally control a country or its people and be responsible for introducing new laws, organizing public services, etc.', '', 'The country is governed by elected representatives of the people.', '', ARRAY[]::TEXT[]),
('Governance', 'governance_us.mp3', 'noun', 'B1', 'the activity of governing a country or controlling a company or an organization; the way in which a country is governed or a company or institution is controlled', '', 'He emphasized the company''s commitment to high standards of corporate governance.', '', ARRAY[]::TEXT[]),
('Government', 'government_us.mp3', 'noun', 'B1', 'the group of people who are responsible for controlling a country or a state', '', 'to lead/form a government', '', ARRAY[]::TEXT[]),
('Governor', 'governor_us.mp3', 'noun', 'B1', 'a person who is the official head of a country or region that is governed by another country', '', 'the former governor of the colony', '', ARRAY[]::TEXT[]),
('Grab', 'grab_us.mp3', 'verb', 'B1', 'to take or hold somebody/something with your hand suddenly or roughly', '', 'grab somebody/something, She grabbed his arm as he got up to leave.', '', ARRAY[]::TEXT[]),
('Grace', 'grace_us.mp3', 'noun', 'B1', 'an attractive quality of movement that is smooth and done with control; a simple and beautiful quality', '', 'She moves with the natural grace of a ballerina.', '', ARRAY[]::TEXT[]),
('Grade', 'grade_us.mp3', 'noun', 'B1', 'a mark given in an exam or for a piece of school work', '', '(British English), She got good grades in her exams.', '', ARRAY[]::TEXT[]),
('Grade', 'grade_us.mp3', 'verb', 'B1', 'to give a grade to a student or to a piece of their written work', '', 'grade somebody/something, I spent all weekend grading papers.', '', ARRAY[]::TEXT[]),
('Gradually', 'gradually_us.mp3', 'adverb', 'B1', 'slowly, over a long period of time', '', 'to gradually increase/decrease', '', ARRAY[]::TEXT[]),
('Graduate', 'graduate_us.mp3', 'noun', 'B1', 'a person who has a university degree', '', 'job prospects for graduates', '', ARRAY[]::TEXT[]),
('Graduate', 'graduate_us.mp3', 'verb', 'B1', 'to get a degree, especially your first degree, from a university or college', '', 'She taught in France after she graduated.', '', ARRAY[]::TEXT[]),
('Grain', 'grain_us.mp3', 'noun', 'B1', 'the small hard seeds of food plants such as wheat, rice, etc.; a single seed of such a plant', '', 'Russia sold 12 million tons of grain abroad last year.', '', ARRAY[]::TEXT[]),
('Grand', 'grand_us.mp3', 'adjective', 'B1', 'impressive and large or important', '', 'It''s not a very grand house.', '', ARRAY[]::TEXT[]),
('Grandfather', 'grandfather_us.mp3', 'noun', 'B1', 'the father of your father or mother', '', 'The firm had been founded by his grandfather.', '', ARRAY[]::TEXT[]),
('Grandmother', 'grandmother_us.mp3', 'noun', 'B1', 'the mother of your father or mother', '', 'I always loved going to visit my grandmother.', '', ARRAY[]::TEXT[]),
('Grandparent', 'grandparent_us.mp3', 'noun', 'B1', 'the father or mother of your father or mother', '', 'The children are staying with their grandparents.', '', ARRAY[]::TEXT[]),
('Grant', 'grant_us.mp3', 'noun', 'B1', 'a sum of money that is given by the government or by another organization to be used for a particular purpose', '', 'government/federal grants', '', ARRAY[]::TEXT[]),
('Grant', 'grant_us.mp3', 'verb', 'B1', 'to agree to give somebody what they ask for, especially formal or legal permission to do something', '', 'grant something, My request was granted.', '', ARRAY[]::TEXT[]),
('Graphic', 'graphic_us.mp3', 'adjective', 'B1', 'connected with drawings and design, especially in the production of books, magazines, websites, etc.', '', 'graphic design', '', ARRAY[]::TEXT[]),
('Graphics', 'graphics_us.mp3', 'noun', 'B1', 'designs, drawings or pictures that are used especially in the production of books, magazines, websites, etc.', '', 'Text and graphics are prepared separately and then combined.', '', ARRAY[]::TEXT[]),
('Grasp', 'grasp_us.mp3', 'noun', 'B1', 'a strong hold of somebody/something or control over somebody/something', '', 'I grabbed him, but he slipped from my grasp.', '', ARRAY[]::TEXT[]),
('Grasp', 'grasp_us.mp3', 'verb', 'B1', 'to take a strong hold of somebody/something', '', 'He grasped my hand and shook it warmly.', '', ARRAY[]::TEXT[]),
('Grass', 'grass_us.mp3', 'noun', 'B1', 'a common wild plant with narrow green leaves and stems that are eaten by cows, horses, sheep, etc.', '', 'a blade of grass', '', ARRAY[]::TEXT[]),
('Grateful', 'grateful_us.mp3', 'adjective', 'B1', 'feeling or showing thanks because somebody has done something kind for you or has done as you asked', '', 'Thank you for doing this. I really am so grateful.', '', ARRAY[]::TEXT[]),
('Grave', 'grave_us.mp3', 'adjective', 'B1', 'very serious and important; giving you a reason to feel worried', '', 'The police have expressed grave concern about the missing child''s safety.', '', ARRAY[]::TEXT[]),
('Grave', 'grave_us.mp3', 'noun', 'B1', 'a place in the ground where a dead person is buried', '', 'We visited Grandma''s grave.', '', ARRAY[]::TEXT[]),
('Gravity', 'gravity_us.mp3', 'noun', 'B1', 'the force that attracts objects in space towards each other, and that on the earth pulls them towards the centre of the planet, so that things fall to the ground when they are dropped', '', 'Newton’s law of gravity', '', ARRAY[]::TEXT[]),
('Great', 'great_us.mp3', 'adjective', 'B1', 'very good or pleasant', '', 'He''s a great bloke.', '', ARRAY[]::TEXT[]),
('Greatly', 'greatly_us.mp3', 'adverb', 'B1', 'very much', '', 'People''s reaction to the film has varied greatly.', '', ARRAY[]::TEXT[]),
('Green', 'green_us.mp3', 'adjective', 'B1', 'having the colour of grass or the leaves of most plants and trees', '', 'green grass/leaves/vegetables', '', ARRAY[]::TEXT[]),
('Green', 'green_us.mp3', 'noun', 'B1', 'the colour of grass and the leaves of most plants and trees', '', 'light/pale green', '', ARRAY[]::TEXT[]),
('Greet', 'greet_us.mp3', 'verb', 'B1', 'to say hello to somebody or to welcome them', '', 'greet somebody, He greeted all the guests warmly as they arrived.', '', ARRAY[]::TEXT[]),
('Grey', 'grey_us.mp3', 'adjective', 'B1', 'having the colour of smoke or ashes', '', 'grey eyes/hair', '', ARRAY[]::TEXT[]),
('Grey', 'grey_us.mp3', 'noun', 'B1', 'the colour of smoke or ashes', '', 'the dull grey of the sky', '', ARRAY[]::TEXT[]),
('Grid', 'grid_us.mp3', 'noun', 'B1', 'a pattern of straight lines, usually crossing each other to form squares', '', 'New York’s grid of streets', '', ARRAY[]::TEXT[]),
('Grief', 'grief_us.mp3', 'noun', 'B1', 'a very sad feeling, especially when somebody dies', '', 'She was overcome with grief when her husband died.', '', ARRAY[]::TEXT[]),
('Grin', 'grin_us.mp3', 'noun', 'B1', 'a wide smile', '', 'She gave a broad grin.', '', ARRAY[]::TEXT[]),
('Grin', 'grin_us.mp3', 'verb', 'B1', 'to smile widely', '', 'They grinned with delight when they heard our news.', '', ARRAY[]::TEXT[]),
('Grind', 'grind_us.mp3', 'verb', 'B1', 'to break or press something into very small pieces between two hard surfaces or using a special machine', '', 'to grind coffee/corn', '', ARRAY[]::TEXT[]),
('Grip', 'grip_us.mp3', 'noun', 'B1', 'an act of holding somebody/something tightly; a particular way of doing this', '', 'Keep a tight grip on the rope.', '', ARRAY[]::TEXT[]),
('Grip', 'grip_us.mp3', 'verb', 'B1', 'to hold something tightly', '', 'grip something, ‘Please don''t go,’ he said, gripping her arm.', '', ARRAY[]::TEXT[]),
('Grocery', 'grocery_us.mp3', 'noun', 'B1', 'a shop that sells food and other things used in the home. In American English ‘grocery store’ is often used to mean ‘supermarket’.', '', 'the corner grocery store', '', ARRAY[]::TEXT[]),
('Gross', 'gross_us.mp3', 'adjective', 'B1', 'being the total amount of something before anything is taken away', '', 'gross weight (= including the container or wrapping)', '', ARRAY[]::TEXT[]),
('Ground', 'ground_us.mp3', 'noun', 'B1', 'the solid surface of the earth', '', 'on the ground, I found her lying on the ground.', '', ARRAY[]::TEXT[]),
('Group', 'group_us.mp3', 'noun', 'B1', 'a number of people or things that are together in the same place or that are connected in some way', '', 'group of somebody/something, a group of people/students/friends', '', ARRAY[]::TEXT[]),
('Grow', 'grow_us.mp3', 'verb', 'B1', 'to increase in size, number, strength or quality', '', 'The sector is growing at a phenomenal rate.', '', ARRAY[]::TEXT[]),
('Growth', 'growth_us.mp3', 'noun', 'B1', 'the process in people, animals or plants of growing physically, mentally or emotionally', '', 'Lack of water will stunt the plant''s growth.', '', ARRAY[]::TEXT[]),
('Guarantee', 'guarantee_us.mp3', 'noun', 'B1', 'a formal promise that you will do something or that something will happen', '', 'They are demanding certain guarantees before they sign the treaty.', '', ARRAY[]::TEXT[]),
('Guarantee', 'guarantee_us.mp3', 'verb', 'B1', 'to promise to do something; to promise something will happen', '', 'guarantee something, Basic human rights, including freedom of speech, are now guaranteed.', '', ARRAY[]::TEXT[]),
('Guard', 'guard_us.mp3', 'noun', 'B1', 'a person, such as a soldier, a police officer or a prison officer, who protects a place or people, or prevents prisoners from escaping', '', 'prison/border guards', '', ARRAY[]::TEXT[]),
('Guard', 'guard_us.mp3', 'verb', 'B1', 'to protect property, places or people from attack or danger', '', 'Armed officers guarded the entrance.', '', ARRAY[]::TEXT[]),
('Guerrilla', 'guerrilla_us.mp3', 'noun', 'B1', 'a member of a small group of soldiers who are not part of an official army and who fight against official soldiers, usually to try to change the government', '', 'urban guerrillas (= those who fight in towns)', '', ARRAY[]::TEXT[]),
('Guess', 'guess_us.mp3', 'noun', 'B1', 'an attempt to give an answer or an opinion when you cannot be certain if you are right', '', '(British English), to have/make a guess', '', ARRAY[]::TEXT[]),
('Guess', 'guess_us.mp3', 'verb', 'B1', 'to try and give an answer or make a judgement about something without being sure of all the facts', '', 'I don''t really know. I''m just guessing.', '', ARRAY[]::TEXT[]),
('Guest', 'guest_us.mp3', 'noun', 'B1', 'a person that you have invited to your house or to a particular event that you are paying for', '', 'They only use the dining room when they have guests.', '', ARRAY[]::TEXT[]),
('Guidance', 'guidance_us.mp3', 'noun', 'B1', 'help or advice that is given to somebody, especially by somebody older or with more experience', '', 'guidance for teachers on how to use video in the classroom', '', ARRAY[]::TEXT[]),
('Guide', 'guide_us.mp3', 'noun', 'B1', 'a person who shows other people the way to a place, especially somebody employed to show tourists around interesting places', '', 'Our tour guide showed us around the old town.', '', ARRAY[]::TEXT[]),
('Guide', 'guide_us.mp3', 'verb', 'B1', 'to show somebody the way to a place, often by going with them; to show somebody a place that you know well', '', 'guide somebody, It''s a dangerous route—you''ll need someone to guide you.', '', ARRAY[]::TEXT[]),
('Guideline', 'guideline_us.mp3', 'noun', 'B1', 'a set of rules or instructions that are given by an official organization telling you how to do something, especially something difficult', '', 'The government has drawn up guidelines for schools during the pandemic.', '', ARRAY[]::TEXT[]),
('Guilt', 'guilt_us.mp3', 'noun', 'B1', 'the unhappy feelings caused by knowing or thinking that you have done something wrong', '', 'She had feelings of guilt about leaving her children and going to work.', '', ARRAY[]::TEXT[]),
('Guilty', 'guilty_us.mp3', 'adjective', 'B1', 'feeling ashamed because you have done something that you know is wrong or have not done something that you should have done', '', 'Matt and Chrissy both looked equally guilty.', '', ARRAY[]::TEXT[]),
('Guitar', 'guitar_us.mp3', 'noun', 'B1', 'a musical instrument that usually has six strings and that you play with your fingers or with a plectrum', '', 'an acoustic/electric guitar', '', ARRAY[]::TEXT[]),
('Gun', 'gun_us.mp3', 'noun', 'B1', 'a weapon that is used for firing bullets or shells', '', 'I have never fired a gun in my life.', '', ARRAY[]::TEXT[]),
('Gut', 'gut_us.mp3', 'noun', 'B1', 'the tube in the body through which food passes when it leaves the stomach', '', 'It can take up to 72 hours for food to pass through the gut.', '', ARRAY[]::TEXT[]),
('Guy', 'guy_us.mp3', 'noun', 'B1', 'a man', '', 'a big/little guy', '', ARRAY[]::TEXT[]),
('Gym', 'gym_us.mp3', 'noun', 'B1', 'a room or hall with equipment for doing physical exercise, for example in a school', '', 'The school has recently built a new gym.', '', ARRAY[]::TEXT[]),
('Habit', 'habit_us.mp3', 'noun', 'B1', 'a thing that you do often and almost without thinking, especially something that is hard to stop doing', '', 'You need to change your eating habits.', '', ARRAY[]::TEXT[]),
('Habitat', 'habitat_us.mp3', 'noun', 'B1', 'the place where a particular type of animal or plant is normally found', '', 'The panda''s natural habitat is the bamboo forest.', '', ARRAY[]::TEXT[]),
('Hail', 'hail_us.mp3', 'verb', 'B1', 'to describe somebody/something as being very good or special, especially in newspapers, etc.', '', 'be hailed (as) something, The conference was hailed as a great success.', '', ARRAY[]::TEXT[]),
('Hair', 'hair_us.mp3', 'noun', 'B1', 'the substance that looks like a mass of fine threads growing on a person''s head', '', 'She has long dark hair.', '', ARRAY[]::TEXT[]),
('Half', 'half_us.mp3', 'adverb', 'B1', 'to the extent of half', '', 'The glass was half full.', '', ARRAY[]::TEXT[]),
('Half', 'half_us.mp3', 'determiner', 'B1', 'an amount equal to half of something/somebody', '', 'I''ll see you in half an hour.', '', ARRAY[]::TEXT[]),
('Half', 'half_us.mp3', 'noun', 'B1', 'either of two equal parts into which something is or can be divided', '', 'two and a half kilos (= 2½)', '', ARRAY[]::TEXT[]),
('Half', 'half_us.mp3', 'pronoun', 'B1', 'an amount equal to half of something/somebody', '', 'I''ll see you in half an hour.', '', ARRAY[]::TEXT[]),
('Halfway', 'halfway_us.mp3', 'adverb', 'B1', 'at an equal distance between two points; in the middle of a period of time', '', 'It''s about halfway between London and Bristol.', '', ARRAY[]::TEXT[]),
('Hall', 'hall_us.mp3', 'noun', 'B1', 'a space or passage inside the entrance or front door of a building', '', 'in a hall, Her brother was standing in the front hall.', '', ARRAY[]::TEXT[]),
('Halt', 'halt_us.mp3', 'noun', 'B1', 'an act of stopping the movement or progress of somebody/something', '', 'Work came to a halt when the machine broke down.', '', ARRAY[]::TEXT[]),
('Halt', 'halt_us.mp3', 'verb', 'B1', 'to stop; to make somebody/something stop', '', 'She walked towards him and then halted.', '', ARRAY[]::TEXT[]),
('Hand', 'hand_us.mp3', 'noun', 'B1', 'the part of the body at the end of the arm, including the fingers and thumb', '', 'Ian placed a hand on her shoulder.', '', ARRAY[]::TEXT[]),
('Hand', 'hand_us.mp3', 'verb', 'B1', 'to pass or give something to somebody', '', 'hand something to somebody, She handed the letter to me.', '', ARRAY[]::TEXT[]),
('Handful', 'handful_us.mp3', 'noun', 'B1', 'the amount of something that can be held in one hand', '', 'a handful of rice', '', ARRAY[]::TEXT[]),
('Handle', 'handle_us.mp3', 'noun', 'B1', 'the part of a door, window, etc. that you use to open it', '', 'She turned the handle and opened the door.', '', ARRAY[]::TEXT[]),
('Handle', 'handle_us.mp3', 'verb', 'B1', 'to deal with a situation, a person, an area of work or a strong emotion', '', 'handle something/somebody, A new man was appointed to handle the crisis.', '', ARRAY[]::TEXT[]),
('Handling', 'handling_us.mp3', 'noun', 'B1', 'the way that somebody deals with or treats a situation, a person, an animal, etc.', '', 'I was impressed by his handling of the affair.', '', ARRAY[]::TEXT[]),
('Handy', 'handy_us.mp3', 'adjective', 'B1', 'easy to use or to do', '', 'a handy little tool', '', ARRAY[]::TEXT[]),
('Hang', 'hang_us.mp3', 'verb', 'B1', 'to attach something, or to be attached, at the top so that the lower part is free or loose', '', 'hang something + adv./prep., Hang your coat on the hook.', '', ARRAY[]::TEXT[]),
('Happen', 'happen_us.mp3', 'verb', 'B1', 'to take place, especially without being planned', '', 'You''ll never guess what''s happened!', '', ARRAY[]::TEXT[]),
('Happily', 'happily_us.mp3', 'adverb', 'B1', 'in a cheerful way; with feelings of pleasure', '', 'children playing happily on the beach', '', ARRAY[]::TEXT[]),
('Happiness', 'happiness_us.mp3', 'noun', 'B1', 'the state of feeling or showing pleasure', '', 'to find true happiness', '', ARRAY[]::TEXT[]),
('Happy', 'happy_us.mp3', 'adjective', 'B1', 'feeling or showing pleasure; pleased', '', 'a happy family', '', ARRAY[]::TEXT[]),
('Harassment', 'harassment_us.mp3', 'noun', 'B1', 'the act of annoying or worrying somebody by putting pressure on them or saying or doing unpleasant things to them', '', 'sexual/racial harassment', '', ARRAY[]::TEXT[]),
('Harbour', 'harbour_us.mp3', 'noun', 'B1', 'an area of water on the coast, protected from the open sea by strong walls, where ships can shelter', '', 'Several boats lay at anchor in the harbour.', '', ARRAY[]::TEXT[]),
('Hard', 'hard_us.mp3', 'adjective', 'B1', 'difficult to do, understand or answer', '', 'a hard choice/decision/question', '', ARRAY[]::TEXT[]),
('Hard', 'hard_us.mp3', 'adverb', 'B1', 'with great effort; with difficulty', '', 'to work hard', '', ARRAY[]::TEXT[]),
('Hardly', 'hardly_us.mp3', 'adverb', 'B1', 'almost no; almost not; almost none', '', 'There''s hardly any tea left.', '', ARRAY[]::TEXT[]),
('Hardware', 'hardware_us.mp3', 'noun', 'B1', 'the machines and electronic parts in a computer or other electronic system', '', 'We supply computer hardware to businesses.', '', ARRAY[]::TEXT[]),
('Harm', 'harm_us.mp3', 'noun', 'B1', 'damage or injury that is caused by a person or an event', '', 'He would never frighten anyone or cause them any harm.', '', ARRAY[]::TEXT[]),
('Harm', 'harm_us.mp3', 'verb', 'B1', 'to hurt or injure somebody or to damage something', '', 'He would never harm anyone.', '', ARRAY[]::TEXT[]),
('Harmful', 'harmful_us.mp3', 'adjective', 'B1', 'causing damage or injury to somebody/something, especially to a person’s health or to the environment', '', 'the harmful effects of alcohol', '', ARRAY[]::TEXT[]),
('Harmony', 'harmony_us.mp3', 'noun', 'B1', 'a state of peaceful existence and agreement', '', 'social/racial harmony', '', ARRAY[]::TEXT[]),
('Harsh', 'harsh_us.mp3', 'adjective', 'B1', 'cruel, severe and unkind', '', 'The punishment was harsh and unfair.', '', ARRAY[]::TEXT[]),
('Harvest', 'harvest_us.mp3', 'noun', 'B1', 'the time of year when the crops are gathered in on a farm, etc.; the act of cutting and gathering crops', '', 'harvest time', '', ARRAY[]::TEXT[]),
('Harvest', 'harvest_us.mp3', 'verb', 'B1', 'to cut and gather a crop; to catch a number of animals or fish to eat', '', 'The nuts are ready to harvest in September.', '', ARRAY[]::TEXT[]),
('Hat', 'hat_us.mp3', 'noun', 'B1', 'a piece of clothing made to fit the head, often with a brim (= a flat edge that sticks out), usually worn out of doors', '', 'a straw/woolly hat', '', ARRAY[]::TEXT[]),
('Hate', 'hate_us.mp3', 'noun', 'B1', 'a very strong feeling of dislike for somebody', '', 'She gave him a look of real hate.', '', ARRAY[]::TEXT[]),
('Hate', 'hate_us.mp3', 'verb', 'B1', 'to dislike somebody/something very much', '', 'hate somebody/yourself, The two boys hated each other.', '', ARRAY[]::TEXT[]),
('Hatred', 'hatred_us.mp3', 'noun', 'B1', 'a very strong feeling of dislike for somebody/something', '', 'He looked at me with intense hatred.', '', ARRAY[]::TEXT[]),
('Haunt', 'haunt_us.mp3', 'verb', 'B1', 'if the ghost of a dead person haunts a place, people say that they have seen it there', '', 'A headless rider haunts the country lanes.', '', ARRAY[]::TEXT[]),
('Have', 'have_us.mp3', 'verb', 'B1', 'to own, hold or possess something', '', 'He had a new car and a boat.', '', ARRAY[]::TEXT[]),
('Have', 'have_us.mp3', 'auxiliary verb', 'B1', 'used with the past participle to form perfect tenses', '', 'I''ve finished my work.', '', ARRAY[]::TEXT[]),
('Have to', 'have to_us.mp3', 'modal verb', 'B1', 'used to show that you must do something', '', 'Sorry, I''ve got to go.', '', ARRAY[]::TEXT[]),
('Hazard', 'hazard_us.mp3', 'noun', 'B1', 'something that can be dangerous or cause damage', '', 'a fire/safety hazard', '', ARRAY[]::TEXT[]),
('He', 'he_us.mp3', 'pronoun', 'B1', 'a male person or animal that has already been mentioned or is easily identified', '', 'Everyone liked my father—he was the perfect gentleman.', '', ARRAY[]::TEXT[]),
('Head', 'head_us.mp3', 'noun', 'B1', 'the part of the body on top of the neck containing the eyes, nose, mouth and brain', '', 'She nodded her head in agreement.', '', ARRAY[]::TEXT[]),
('Head', 'head_us.mp3', 'verb', 'B1', 'to move in a particular direction', '', 'Where are we heading?', '', ARRAY[]::TEXT[]),
('Headache', 'headache_us.mp3', 'noun', 'B1', 'a continuous pain in the head', '', 'He had a terrible headache.', '', ARRAY[]::TEXT[]),
('Headline', 'headline_us.mp3', 'noun', 'B1', 'the title of a news article printed in large letters, especially at the top of the front page on a newspaper or the home page on a news website', '', 'a newspaper headline', '', ARRAY[]::TEXT[]),
('Headquarters', 'headquarters_us.mp3', 'noun', 'B1', 'a place from which an organization or a military operation is controlled; the people who work there', '', 'The firm’s headquarters is/are in London.', '', ARRAY[]::TEXT[]),
('Heal', 'heal_us.mp3', 'verb', 'B1', 'to become healthy again; to make something healthy again', '', 'It took a long time for the wounds to heal.', '', ARRAY[]::TEXT[]),
('Health', 'health_us.mp3', 'noun', 'B1', 'the condition of a person’s body or mind', '', 'to be good/bad for your health', '', ARRAY[]::TEXT[]),
('Healthcare', 'healthcare_us.mp3', 'noun', 'B1', 'the service of providing medical care', '', 'the costs of healthcare for the elderly', '', ARRAY[]::TEXT[]),
('Healthy', 'healthy_us.mp3', 'adjective', 'B1', 'having good health and not likely to become ill', '', 'a healthy child/baby/adult', '', ARRAY[]::TEXT[]),
('Hear', 'hear_us.mp3', 'verb', 'B1', 'to be aware of sounds with your ears', '', 'I can''t hear very well.', '', ARRAY[]::TEXT[]),
('Hearing', 'hearing_us.mp3', 'noun', 'B1', 'the ability to hear', '', 'Her hearing is poor.', '', ARRAY[]::TEXT[]),
('Heart', 'heart_us.mp3', 'noun', 'B1', 'the organ in the chest that sends blood around the body, usually on the left in humans', '', 'The patient''s heart stopped beating for a few seconds.', '', ARRAY[]::TEXT[]),
('Heat', 'heat_us.mp3', 'noun', 'B1', 'the quality of being hot', '', 'Heat rises.', '', ARRAY[]::TEXT[]),
('Heat', 'heat_us.mp3', 'verb', 'B1', 'to make something hot or warm; to become hot or warm', '', 'heat (something), Heat the oil and add the onions.', '', ARRAY[]::TEXT[]),
('Heating', 'heating_us.mp3', 'noun', 'B1', 'the process of supplying heat to a room or building; a system used to do this', '', 'to put/turn the heating on', '', ARRAY[]::TEXT[]),
('Heaven', 'heaven_us.mp3', 'noun', 'B1', 'the place believed to be the home of God where good people go when they die, sometimes imagined to be in the sky', '', 'the kingdom of heaven', '', ARRAY[]::TEXT[]),
('Heavily', 'heavily_us.mp3', 'adverb', 'B1', 'to a great degree; in large amounts', '', 'It was raining heavily.', '', ARRAY[]::TEXT[]),
('Heavy', 'heavy_us.mp3', 'adjective', 'B1', 'weighing a lot; difficult to lift or move', '', 'a heavy weight/load', '', ARRAY[]::TEXT[]),
('Heel', 'heel_us.mp3', 'noun', 'B1', 'the back part of the foot below the ankle', '', 'Apply the cream to dry, cracked heels before bed.', '', ARRAY[]::TEXT[]),
('Height', 'height_us.mp3', 'noun', 'B1', 'the measurement of how tall a person or thing is', '', 'Height: 210 mm. Width: 57 mm. Length: 170 mm.', '', ARRAY[]::TEXT[]),
('Heighten', 'heighten_us.mp3', 'verb', 'B1', 'if a feeling or an effect heightens, or something heightens it, it becomes stronger or increases', '', 'Tension has heightened after the recent bomb attack.', '', ARRAY[]::TEXT[]),
('Helicopter', 'helicopter_us.mp3', 'noun', 'B1', 'an aircraft without wings that has large blades (= long flat parts) on top that go round. It can fly straight up from the ground and can also stay in one position in the air.', '', 'a police/rescue helicopter', '', ARRAY[]::TEXT[]),
('Hell', 'hell_us.mp3', 'noun', 'B1', 'the place believed to be the home of devils and where bad people go after death', '', 'He was terrified of going to hell when he died.', '', ARRAY[]::TEXT[]),
('Hello', 'hello_us.mp3', 'exclamation', 'B1', 'used as a greeting when you meet somebody, in an email, when you answer the phone or when you want to attract somebody’s attention', '', 'Hello John, how are you?', '', ARRAY[]::TEXT[]),
('Hello', 'hello_us.mp3', 'noun', 'B1', 'used as a greeting when you meet somebody, in an email, when you answer the phone or when you want to attract somebody’s attention', '', 'Hello John, how are you?', '', ARRAY[]::TEXT[]),
('Helmet', 'helmet_us.mp3', 'noun', 'B1', 'a type of hard hat that protects the head, worn, for example, by a police officer, a soldier or a person riding a bike or motorbike or playing some sports', '', 'Police in riot helmets lined the streets.', '', ARRAY[]::TEXT[]),
('Help', 'help_us.mp3', 'noun', 'B1', 'the act of helping somebody to do something', '', 'Thank you for all your help.', '', ARRAY[]::TEXT[]),
('Help', 'help_us.mp3', 'verb', 'B1', 'to make it easier or possible for somebody to do something by doing something for them or by giving them something that they need', '', 'What can I do to help?', '', ARRAY[]::TEXT[]),
('Helpful', 'helpful_us.mp3', 'adjective', 'B1', 'able to improve a particular situation', '', 'helpful advice/information', '', ARRAY[]::TEXT[]),
('Hence', 'hence_us.mp3', 'adverb', 'B1', 'for this reason', '', 'We suspect they are trying to hide something, hence the need for an independent inquiry.', '', ARRAY[]::TEXT[]),
('Her', 'her_us.mp3', 'determiner', 'B1', 'of or belonging to a woman or girl who has already been mentioned or is easily identified', '', 'Meg loves her job.', '', ARRAY[]::TEXT[]),
('Her', 'her_us.mp3', 'pronoun', 'B1', 'used as the object of a verb, after the verb be or after a preposition to refer to a woman or girl who has already been mentioned or is easily identified', '', 'We''re going to call her Sophie.', '', ARRAY[]::TEXT[]),
('Herb', 'herb_us.mp3', 'noun', 'B1', 'a plant whose leaves, flowers or seeds are used to add taste to food, in medicines or for their pleasant smell. parsley, mint and oregano are all herbs.', '', 'a herb garden', '', ARRAY[]::TEXT[]),
('Here', 'here_us.mp3', 'adverb', 'B1', 'used after a verb or preposition to mean ‘in, at or to this position or place’', '', 'I live here.', '', ARRAY[]::TEXT[]),
('Heritage', 'heritage_us.mp3', 'noun', 'B1', 'the history, traditions, buildings and objects that a country or society has had for many years and that are considered an important part of its character', '', 'Spain’s rich cultural heritage', '', ARRAY[]::TEXT[]),
('Hero', 'hero_us.mp3', 'noun', 'B1', 'a person who is admired by many people for doing something brave or good', '', 'a war hero (= somebody who was very brave during a war)', '', ARRAY[]::TEXT[]),
('Hers', 'hers_us.mp3', 'pronoun', 'B1', 'of or belonging to her', '', 'His eyes met hers.', '', ARRAY[]::TEXT[]),
('Herself', 'herself_us.mp3', 'pronoun', 'B1', 'used when the woman or girl who performs an action is also affected by it', '', 'She hurt herself.', '', ARRAY[]::TEXT[]),
('Hesitate', 'hesitate_us.mp3', 'verb', 'B1', 'to be slow to speak or act because you feel uncertain or nervous', '', 'She hesitated before replying.', '', ARRAY[]::TEXT[]),
('Hey', 'hey_us.mp3', 'exclamation', 'B1', 'used to attract somebody’s attention or to express interest, surprise or anger', '', 'Hey, can I just ask you something?', '', ARRAY[]::TEXT[]),
('Hi', 'hi_us.mp3', 'exclamation', 'B1', 'used to say hello', '', 'Hi guys!', '', ARRAY[]::TEXT[]),
('Hidden', 'hidden_us.mp3', 'adjective', 'B1', 'something that is hidden is kept or located in a place where it cannot be seen', '', 'Hidden dangers lurk in the ocean depths.', '', ARRAY[]::TEXT[]),
('Hide', 'hide_us.mp3', 'verb', 'B1', 'to put or keep somebody/something in a place where they/it cannot be seen or found', '', 'hide somebody/something + adv./prep., He hid the letter in a drawer.', '', ARRAY[]::TEXT[]),
('Hierarchy', 'hierarchy_us.mp3', 'noun', 'B1', 'a system, especially in a society or an organization, in which people are organized into different levels of importance from highest to lowest', '', 'the social/political hierarchy', '', ARRAY[]::TEXT[]),
('High', 'high_us.mp3', 'adjective', 'B1', 'measuring a long distance from the bottom to the top', '', 'What''s the highest mountain in the US?', '', ARRAY[]::TEXT[]),
('High', 'high_us.mp3', 'adverb', 'B1', 'at or to a position or level that is a long way up from the ground or from the bottom', '', 'to climb/jump/leap high', '', ARRAY[]::TEXT[]),
('High', 'high_us.mp3', 'noun', 'B1', 'the highest level or number', '', 'to hit/reach a high', '', ARRAY[]::TEXT[]),
('High-profile', 'high-profile_us.mp3', 'adjective', 'B1', 'receiving or involving a lot of attention and discussion in the media', '', 'a high-profile campaign', '', ARRAY[]::TEXT[]),
('Highlight', 'highlight_us.mp3', 'noun', 'B1', 'the best, most interesting or most exciting part of something', '', 'One of the highlights of the trip was seeing the Taj Mahal.', '', ARRAY[]::TEXT[]),
('Highlight', 'highlight_us.mp3', 'verb', 'B1', 'to emphasize something, especially so that people give it more attention', '', 'The report highlighted the importance of exercise to maintain a healthy body.', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
