INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('A', 'a_us.mp3', 'indefinite article', 'B1', 'used before countable or singular nouns referring to people or things that have not already been mentioned', '', 'a man/horse/unit', '', ARRAY[]::TEXT[]),
('Abandon', 'abandon_us.mp3', 'verb', 'B1', 'to leave somebody, especially somebody you are responsible for, with no intention of returning', '', 'abandon somebody, The baby had been abandoned by its mother.', '', ARRAY[]::TEXT[]),
('Ability', 'ability_us.mp3', 'noun', 'B1', 'the fact that somebody/something is able to do something', '', 'People with the disease may lose their ability to communicate.', '', ARRAY[]::TEXT[]),
('Able', 'able_us.mp3', 'adjective', 'B1', 'to have the skill, intelligence, opportunity, etc. needed to do something', '', 'You must be able to speak French for this job.', '', ARRAY[]::TEXT[]),
('Abolish', 'abolish_us.mp3', 'verb', 'B1', 'to officially end a law, a system or an institution', '', 'This tax should be abolished.', '', ARRAY[]::TEXT[]),
('Abortion', 'abortion_us.mp3', 'noun', 'B1', 'the deliberate ending of a pregnancy at an early stage', '', 'to support/oppose abortion', '', ARRAY[]::TEXT[]),
('About', 'about_us.mp3', 'adverb', 'B1', 'a little more or less than; a little before or after', '', 'It costs about $10.', '', ARRAY[]::TEXT[]),
('About', 'about_us.mp3', 'preposition', 'B1', 'on the subject of somebody/something; in connection with somebody/something', '', 'a book about flowers', '', ARRAY[]::TEXT[]),
('Above', 'above_us.mp3', 'adverb', 'B1', 'at or to a higher place', '', 'Put it on the shelf above.', '', ARRAY[]::TEXT[]),
('Above', 'above_us.mp3', 'preposition', 'B1', 'at or to a higher place or position than something/somebody', '', 'The water came above our knees.', '', ARRAY[]::TEXT[]),
('Abroad', 'abroad_us.mp3', 'adverb', 'B1', 'in or to a foreign country', '', 'to go/travel/live/study abroad', '', ARRAY[]::TEXT[]),
('Absence', 'absence_us.mp3', 'noun', 'B1', 'the fact of somebody being away from a place where they are usually expected to be; the occasion or period of time when somebody is away', '', 'in somebody''s absence, The decision was made in my absence (= while I was not there).', '', ARRAY[]::TEXT[]),
('Absent', 'absent_us.mp3', 'adjective', 'B1', 'not in a place because of illness, etc.', '', 'He was absent from work for two weeks.', '', ARRAY[]::TEXT[]),
('Absolute', 'absolute_us.mp3', 'adjective', 'B1', 'total and complete', '', 'I''ve joined a class for absolute beginners.', '', ARRAY[]::TEXT[]),
('Absolutely', 'absolutely_us.mp3', 'adverb', 'B1', 'used to emphasize that something is completely true', '', 'You''re absolutely right.', '', ARRAY[]::TEXT[]),
('Absorb', 'absorb_us.mp3', 'verb', 'B1', 'to take in a liquid, gas or other substance from the surface or space around', '', 'absorb something, Plants absorb carbon dioxide from the air.', '', ARRAY[]::TEXT[]),
('Abstract', 'abstract_us.mp3', 'adjective', 'B1', 'based on general ideas and not on any particular real person, thing or situation', '', 'abstract knowledge/principles', '', ARRAY[]::TEXT[]),
('Absurd', 'absurd_us.mp3', 'adjective', 'B1', 'extremely silly; not logical and sensible', '', 'That uniform makes the guards look absurd.', '', ARRAY[]::TEXT[]),
('Abundance', 'abundance_us.mp3', 'noun', 'B1', 'a large quantity that is more than enough', '', 'The brochure promised beautiful walks with an abundance of wildlife.', '', ARRAY[]::TEXT[]),
('Abuse', 'abuse_us.mp3', 'noun', 'B1', 'the use of something in a way that is wrong or harmful', '', 'alcohol/drug abuse', '', ARRAY[]::TEXT[]),
('Abuse', 'abuse_us.mp3', 'verb', 'B1', 'to make bad use of something, or to use so much of something that it harms your health', '', 'to abuse alcohol/drugs', '', ARRAY[]::TEXT[]),
('Academic', 'academic_us.mp3', 'adjective', 'B1', 'connected with education, especially studying in schools and universities', '', 'high/low academic standards', '', ARRAY[]::TEXT[]),
('Academic', 'academic_us.mp3', 'noun', 'B1', 'a person who teaches and/or does research at a university or college', '', 'a leading/distinguished/prominent academic', '', ARRAY[]::TEXT[]),
('Academy', 'academy_us.mp3', 'noun', 'B1', 'a school or college for special training', '', 'She trained at the Royal Academy of Music.', '', ARRAY[]::TEXT[]),
('Accelerate', 'accelerate_us.mp3', 'verb', 'B1', 'to happen faster or earlier; to make something happen faster or earlier', '', 'Inflation continues to accelerate.', '', ARRAY[]::TEXT[]),
('Accent', 'accent_us.mp3', 'noun', 'B1', 'a way of pronouncing the words of a language that shows which country, area or social class a person comes from; how well somebody pronounces a particular language', '', 'a northern/Dublin/Scottish accent', '', ARRAY[]::TEXT[]),
('Accept', 'accept_us.mp3', 'verb', 'B1', 'to take willingly something that is offered; to say ‘yes’ to an offer, invitation, etc.', '', 'He asked me to marry him and I accepted.', '', ARRAY[]::TEXT[]),
('Acceptable', 'acceptable_us.mp3', 'adjective', 'B1', 'agreed or approved of by most people in a society', '', 'Children must learn socially acceptable behaviour.', '', ARRAY[]::TEXT[]),
('Acceptance', 'acceptance_us.mp3', 'noun', 'B1', 'the act of accepting a gift, an invitation, an offer, etc.', '', 'Please confirm your acceptance of this offer in writing.', '', ARRAY[]::TEXT[]),
('Access', 'access_us.mp3', 'noun', 'B1', 'the opportunity or right to use something or to see somebody/something', '', 'High-speed internet access has become a necessity.', '', ARRAY[]::TEXT[]),
('Access', 'access_us.mp3', 'verb', 'B1', 'to open a computer file or use a computer system', '', 'Most people use their phones to access the internet.', '', ARRAY[]::TEXT[]),
('Accessible', 'accessible_us.mp3', 'adjective', 'B1', 'that can be reached, entered, used, seen, etc.', '', 'The remote desert area is accessible only by helicopter.', '', ARRAY[]::TEXT[]),
('Accident', 'accident_us.mp3', 'noun', 'B1', 'an unpleasant event, especially in a vehicle, that happens unexpectedly and causes injury or damage', '', 'a car/road/traffic accident', '', ARRAY[]::TEXT[]),
('Accidentally', 'accidentally_us.mp3', 'adverb', 'B1', 'by chance; in a way that was not planned', '', 'As I turned around, I accidentally hit him in the face.', '', ARRAY[]::TEXT[]),
('Accommodate', 'accommodate_us.mp3', 'verb', 'B1', 'to provide somebody with a room or place to sleep, live or sit', '', 'The hotel can accommodate up to 500 guests.', '', ARRAY[]::TEXT[]),
('Accommodation', 'accommodation_us.mp3', 'noun', 'B1', 'a place to live, work or stay in', '', 'rented/temporary accommodation', '', ARRAY[]::TEXT[]),
('Accompany', 'accompany_us.mp3', 'verb', 'B1', 'to travel or go somewhere with somebody/something', '', 'accompany somebody/something + adv./prep., His wife accompanied him on the trip.', '', ARRAY[]::TEXT[]),
('Accomplish', 'accomplish_us.mp3', 'verb', 'B1', 'to succeed in doing or completing something', '', 'The first part of the plan has been safely accomplished.', '', ARRAY[]::TEXT[]),
('Accomplishment', 'accomplishment_us.mp3', 'noun', 'B1', 'an impressive thing that is done or achieved after a lot of work', '', 'It was one of the President''s greatest accomplishments.', '', ARRAY[]::TEXT[]),
('Accordance', 'accordance_us.mp3', 'noun', 'B1', 'according to a rule or the way that somebody says that something should be done', '', 'in accordance with legal requirements', '', ARRAY[]::TEXT[]),
('According to', 'according to_us.mp3', 'preposition', 'B1', 'as stated or reported by somebody/something', '', 'According to Mick, it''s a great movie.', '', ARRAY[]::TEXT[]),
('Accordingly', 'accordingly_us.mp3', 'adverb', 'B1', 'in a way that is appropriate to what has been done or said in a particular situation', '', 'We have to discover his plans and act accordingly.', '', ARRAY[]::TEXT[]),
('Account', 'account_us.mp3', 'noun', 'B1', 'an arrangement that somebody has with a bank, etc. to keep money there, take some out, etc.', '', 'I don''t have a bank account.', '', ARRAY[]::TEXT[]),
('Account', 'account_us.mp3', 'verb', 'B1', 'to have the opinion that somebody/something is a particular thing', '', 'be accounted + adj., In English law a person is accounted innocent until they are proved guilty.', '', ARRAY[]::TEXT[]),
('Accountability', 'accountability_us.mp3', 'noun', 'B1', 'the fact of being responsible for your decisions or actions and expected to explain them when you are asked', '', 'proposals for greater police accountability', '', ARRAY[]::TEXT[]),
('Accountable', 'accountable_us.mp3', 'adjective', 'B1', 'responsible for your decisions or actions and expected to explain them when you are asked', '', 'The state spends taxpayers’ money and should be held accountable.', '', ARRAY[]::TEXT[]),
('Accountant', 'accountant_us.mp3', 'noun', 'B1', 'a person whose job is to keep or check financial accounts', '', 'We talked to the company’s chief accountant.', '', ARRAY[]::TEXT[]),
('Accumulate', 'accumulate_us.mp3', 'verb', 'B1', 'to gradually get more and more of something over a period of time', '', 'I seem to have accumulated a lot of books.', '', ARRAY[]::TEXT[]),
('Accumulation', 'accumulation_us.mp3', 'noun', 'B1', 'the process of gradually increasing or getting more and more of something over a period of time', '', 'the accumulation of wealth', '', ARRAY[]::TEXT[]),
('Accuracy', 'accuracy_us.mp3', 'noun', 'B1', 'the state of being exact or correct; the ability to do something with skill and without making mistakes', '', 'They questioned the accuracy of the information in the file.', '', ARRAY[]::TEXT[]),
('Accurate', 'accurate_us.mp3', 'adjective', 'B1', 'correct and true in every detail', '', 'an accurate description/picture of something', '', ARRAY[]::TEXT[]),
('Accurately', 'accurately_us.mp3', 'adverb', 'B1', 'in a way that is correct and true in every detail', '', 'The article accurately reflects public opinion.', '', ARRAY[]::TEXT[]),
('Accusation', 'accusation_us.mp3', 'noun', 'B1', 'a statement saying that you think a person is guilty of doing something wrong or illegal; the fact of accusing somebody', '', 'I don''t want to make an accusation until I have some proof.', '', ARRAY[]::TEXT[]),
('Accuse', 'accuse_us.mp3', 'verb', 'B1', 'to say that somebody has done something wrong or is guilty of something', '', 'accuse somebody of something, to accuse somebody of murder/a crime', '', ARRAY[]::TEXT[]),
('Accused', 'accused_us.mp3', 'noun', 'B1', 'a person who is on trial for committing a crime', '', 'The accused was found innocent.', '', ARRAY[]::TEXT[]),
('Achieve', 'achieve_us.mp3', 'verb', 'B1', 'to succeed in reaching a particular goal, status or standard, especially by making an effort for a long time', '', 'He had finally achieved success.', '', ARRAY[]::TEXT[]),
('Achievement', 'achievement_us.mp3', 'noun', 'B1', 'a thing that somebody has done successfully, especially using their own effort and skill', '', 'the greatest scientific achievement of the decade', '', ARRAY[]::TEXT[]),
('Acid', 'acid_us.mp3', 'adjective', 'B1', 'that contains acid or has the essential characteristics of an acid; that has a pH of less than seven', '', 'Rye is tolerant of poor, acid soils.', '', ARRAY[]::TEXT[]),
('Acid', 'acid_us.mp3', 'noun', 'B1', 'a chemical, usually a liquid, that contains hydrogen and has a pH of less than seven. The hydrogen can be replaced by a metal to form a salt. Acids usually have a bitter sharp taste and can often burn holes in or damage things they touch.', '', 'The acid burned a hole in her coat.', '', ARRAY[]::TEXT[]),
('Acknowledge', 'acknowledge_us.mp3', 'verb', 'B1', 'to accept that something is true', '', 'acknowledge something, She refuses to acknowledge the need for reform.', '', ARRAY[]::TEXT[]),
('Acquire', 'acquire_us.mp3', 'verb', 'B1', 'to gain something by your own efforts, ability or behaviour', '', 'She has acquired a good knowledge of English.', '', ARRAY[]::TEXT[]),
('Acquisition', 'acquisition_us.mp3', 'noun', 'B1', 'the act of getting something, especially knowledge, a skill, etc.', '', 'theories of child language acquisition', '', ARRAY[]::TEXT[]),
('Acre', 'acre_us.mp3', 'noun', 'B1', 'a unit for measuring an area of land; 4 840 square yards or about 4 050 square metres', '', '3 000 acres of parkland', '', ARRAY[]::TEXT[]),
('Across', 'across_us.mp3', 'adverb', 'B1', 'from one side to the other side', '', 'It''s too wide. We can''t swim across.', '', ARRAY[]::TEXT[]),
('Across', 'across_us.mp3', 'preposition', 'B1', 'from one side to the other side of something', '', 'He walked across the field.', '', ARRAY[]::TEXT[]),
('Act', 'act_us.mp3', 'noun', 'B1', 'a particular thing that somebody does', '', 'You have committed a serious criminal act.', '', ARRAY[]::TEXT[]),
('Act', 'act_us.mp3', 'verb', 'B1', 'to do something for a particular purpose or in order to deal with a situation', '', 'act to do something, It is vital that we act to stop the destruction of the rainforests.', '', ARRAY[]::TEXT[]),
('Action', 'action_us.mp3', 'noun', 'B1', 'the process of doing something in order to make something happen or to deal with a situation', '', 'The time has come for action if these beautiful animals are to survive.', '', ARRAY[]::TEXT[]),
('Activate', 'activate_us.mp3', 'verb', 'B1', 'to make something such as a device or chemical process start working', '', 'The burglar alarm is activated by movement.', '', ARRAY[]::TEXT[]),
('Activation', 'activation_us.mp3', 'noun', 'B1', 'the act of making something such as a device or chemical process start working', '', 'The activation of several target genes results in two major effects.', '', ARRAY[]::TEXT[]),
('Active', 'active_us.mp3', 'adjective', 'B1', 'always busy doing things, especially physical activities', '', 'Staying physically active in later years can also keep you feeling younger.', '', ARRAY[]::TEXT[]),
('Activist', 'activist_us.mp3', 'noun', 'B1', 'a person who works to achieve political or social change, especially as a member of an organization with particular aims', '', 'human/civil/animal rights activists', '', ARRAY[]::TEXT[]),
('Activity', 'activity_us.mp3', 'noun', 'B1', 'a thing that you do for interest or pleasure', '', 'leisure/outdoor/recreational activities', '', ARRAY[]::TEXT[]),
('Actor', 'actor_us.mp3', 'noun', 'B1', 'a person who performs on the stage, on television or in films, especially as a profession', '', 'Both lead actors (= the ones who play the main parts) are outstanding.', '', ARRAY[]::TEXT[]),
('Actress', 'actress_us.mp3', 'noun', 'B1', 'a woman who performs on the stage, on television or in films, especially as a profession', '', 'The Oscar-winning actress has taken a break from acting.', '', ARRAY[]::TEXT[]),
('Actual', 'actual_us.mp3', 'adjective', 'B1', 'used to emphasize something that is real or exists in fact', '', 'James looks younger than his wife but in actual fact (= really) he is five years older.', '', ARRAY[]::TEXT[]),
('Actually', 'actually_us.mp3', 'adverb', 'B1', 'used in speaking to emphasize a fact or a comment, or that something is really true', '', 'What did she actually say?', '', ARRAY[]::TEXT[]),
('Acute', 'acute_us.mp3', 'adjective', 'B1', 'very serious or severe', '', 'There is an acute shortage of water.', '', ARRAY[]::TEXT[]),
('Ad', 'ad_us.mp3', 'noun', 'B1', 'a notice, picture or film telling people about a product, job or service', '', 'The TV ads were first run last year.', '', ARRAY[]::TEXT[]),
('Adapt', 'adapt_us.mp3', 'verb', 'B1', 'to change your behaviour in order to deal more successfully with a new situation', '', 'It''s amazing how soon you adapt.', '', ARRAY[]::TEXT[]),
('Adaptation', 'adaptation_us.mp3', 'noun', 'B1', 'the action or process of changing something, or of being changed, to suit a new purpose or situation', '', 'the adaptation of buildings for military purposes', '', ARRAY[]::TEXT[]),
('Add', 'add_us.mp3', 'verb', 'B1', 'to put something together with something else so as to increase the size, number, amount, etc.', '', 'add something, Next add the flour.', '', ARRAY[]::TEXT[]),
('Addiction', 'addiction_us.mp3', 'noun', 'B1', 'the condition of being unable to stop using or doing something as a habit, especially something harmful', '', 'cocaine addiction', '', ARRAY[]::TEXT[]),
('Addition', 'addition_us.mp3', 'noun', 'B1', 'a thing that is added to something else', '', 'All of these technologies are fairly recent additions.', '', ARRAY[]::TEXT[]),
('Additional', 'additional_us.mp3', 'adjective', 'B1', 'more than was first mentioned or is usual', '', 'additional resources/funds/security/funding/costs', '', ARRAY[]::TEXT[]),
('Additionally', 'additionally_us.mp3', 'adverb', 'B1', 'in a way that is more than was first mentioned or is usual', '', 'Additionally, the bus service will run on Sundays, every two hours.', '', ARRAY[]::TEXT[]),
('Address', 'address_us.mp3', 'noun', 'B1', 'details of where somebody lives or works and where letters, etc. can be sent', '', 'What''s your name and address?', '', ARRAY[]::TEXT[]),
('Address', 'address_us.mp3', 'verb', 'B1', 'to think about a problem or a situation and decide how you are going to deal with it', '', 'address something, Your essay does not address the real issues.', '', ARRAY[]::TEXT[]),
('Adequate', 'adequate_us.mp3', 'adjective', 'B1', 'enough in quantity, or good enough in quality, for a particular purpose or need', '', 'They''ll need an adequate supply of hot water.', '', ARRAY[]::TEXT[]),
('Adequately', 'adequately_us.mp3', 'adverb', 'B1', 'in a way that is enough in quantity, or good enough in quality, for a particular purpose or need', '', 'Are you adequately insured?', '', ARRAY[]::TEXT[]),
('Adhere', 'adhere_us.mp3', 'verb', 'B1', 'to stick to something', '', 'Once in the bloodstream, the bacteria adhere to the surface of the red cells.', '', ARRAY[]::TEXT[]),
('Adjacent', 'adjacent_us.mp3', 'adjective', 'B1', 'next to something', '', 'The planes landed on adjacent runways.', '', ARRAY[]::TEXT[]),
('Adjust', 'adjust_us.mp3', 'verb', 'B1', 'to change something slightly to make it more suitable for a new set of conditions or to make it work better', '', 'adjust something, Watch out for sharp bends and adjust your speed accordingly.', '', ARRAY[]::TEXT[]),
('Adjustment', 'adjustment_us.mp3', 'noun', 'B1', 'a small change made to something in order to correct or improve it', '', 'I''ve made a few adjustments to the design.', '', ARRAY[]::TEXT[]),
('Administer', 'administer_us.mp3', 'verb', 'B1', 'to manage and organize the affairs of a company, an organization, a country, etc.', '', 'to administer a charity/fund/school', '', ARRAY[]::TEXT[]),
('Administration', 'administration_us.mp3', 'noun', 'B1', 'the activities that are done in order to plan, organize and run a business, school or other institution', '', 'Administration costs are passed on to the customer.', '', ARRAY[]::TEXT[]),
('Administrative', 'administrative_us.mp3', 'adjective', 'B1', 'connected with organizing the work of a business or an institution', '', 'an administrative job/assistant/error', '', ARRAY[]::TEXT[]),
('Administrator', 'administrator_us.mp3', 'noun', 'B1', 'a person whose job is to manage and organize the public or business affairs of a company or an institution, or a person who works in an office dealing with records, accounts, etc.', '', 'Such organizational decisions are made by the hospital administrators.', '', ARRAY[]::TEXT[]),
('Admire', 'admire_us.mp3', 'verb', 'B1', 'to respect somebody for what they have done or to respect their qualities', '', 'admire somebody/something, I really admire your enthusiasm.', '', ARRAY[]::TEXT[]),
('Admission', 'admission_us.mp3', 'noun', 'B1', 'the act of accepting somebody into an institution, organization, etc.; the right to enter a place or to join an institution or organization', '', 'Hospital admission is not necessary in most cases.', '', ARRAY[]::TEXT[]),
('Admit', 'admit_us.mp3', 'verb', 'B1', 'to agree, often unwillingly, that something is true', '', 'It was a stupid thing to do, I admit.', '', ARRAY[]::TEXT[]),
('Adolescent', 'adolescent_us.mp3', 'noun', 'B1', 'a young person who is developing from a child into an adult', '', 'adolescents between the ages of 13 and 18 and the problems they face', '', ARRAY[]::TEXT[]),
('Adopt', 'adopt_us.mp3', 'verb', 'B1', 'to take somebody else’s child into your family and become its legal parent(s)', '', 'a campaign to encourage childless couples to adopt', '', ARRAY[]::TEXT[]),
('Adoption', 'adoption_us.mp3', 'noun', 'B1', 'the act of adopting a child; the fact of being adopted', '', 'She put the baby up for adoption.', '', ARRAY[]::TEXT[]),
('Adult', 'adult_us.mp3', 'adjective', 'B1', 'fully grown or developed', '', 'preparing young people for adult life', '', ARRAY[]::TEXT[]),
('Adult', 'adult_us.mp3', 'noun', 'B1', 'a fully grown person who is legally responsible for their actions', '', 'Children must be accompanied by an adult.', '', ARRAY[]::TEXT[]),
('Advance', 'advance_us.mp3', 'adjective', 'B1', 'done or given before something is going to happen', '', 'Please give us advance warning of any changes.', '', ARRAY[]::TEXT[]),
('Advance', 'advance_us.mp3', 'noun', 'B1', 'progress or a development in a particular activity or area of understanding', '', 'We live in an age of rapid technological advance.', '', ARRAY[]::TEXT[]),
('Advance', 'advance_us.mp3', 'verb', 'B1', 'if knowledge, technology, etc. advances, it develops and improves', '', 'Technology is advancing at an incredibly rapid pace.', '', ARRAY[]::TEXT[]),
('Advanced', 'advanced_us.mp3', 'adjective', 'B1', 'having the most modern and recently developed ideas, methods, etc.', '', 'Scientists are working on highly advanced technology to replace fossil fuels.', '', ARRAY[]::TEXT[]),
('Advantage', 'advantage_us.mp3', 'noun', 'B1', 'a thing that helps you to be better or more successful than other people', '', 'a distinct/significant/huge advantage', '', ARRAY[]::TEXT[]),
('Adventure', 'adventure_us.mp3', 'noun', 'B1', 'an unusual, exciting or dangerous experience, journey or series of events', '', 'her adventures travelling in Africa', '', ARRAY[]::TEXT[]),
('Adverse', 'adverse_us.mp3', 'adjective', 'B1', 'negative and unpleasant; not likely to produce a good result', '', 'adverse change/circumstances/weather conditions', '', ARRAY[]::TEXT[]),
('Advertise', 'advertise_us.mp3', 'verb', 'B1', 'to tell the public about a product or a service in order to encourage people to buy or to use it', '', 'If you want to attract customers you need to advertise.', '', ARRAY[]::TEXT[]),
('Advertisement', 'advertisement_us.mp3', 'noun', 'B1', 'a notice, picture or film telling people about a product, job or service', '', 'a newspaper/television advertisement', '', ARRAY[]::TEXT[]),
('Advertising', 'advertising_us.mp3', 'noun', 'B1', 'the activity and industry of advertising things to people on television, in newspapers, on the internet, etc.', '', 'Cigarette advertising has been banned.', '', ARRAY[]::TEXT[]),
('Advice', 'advice_us.mp3', 'noun', 'B1', 'an opinion or a suggestion about what somebody should do in a particular situation', '', 'expert/practical/professional/medical advice', '', ARRAY[]::TEXT[]),
('Advise', 'advise_us.mp3', 'verb', 'B1', 'to tell somebody what you think they should do in a particular situation', '', 'advise against doing something, I would strongly advise against going out on your own.', '', ARRAY[]::TEXT[]),
('Advocate', 'advocate_us.mp3', 'noun', 'B1', 'a person who supports or speaks in favour of somebody or of a public plan or action', '', 'advocate for something/somebody, an advocate for hospital workers', '', ARRAY[]::TEXT[]),
('Advocate', 'advocate_us.mp3', 'verb', 'B1', 'to support something publicly', '', 'advocate something, The group does not advocate the use of violence.', '', ARRAY[]::TEXT[]),
('Aesthetic', 'aesthetic_us.mp3', 'adjective', 'B1', 'connected with beauty and art and the understanding of beautiful things', '', 'the aesthetic appeal of the songs', '', ARRAY[]::TEXT[]),
('Affair', 'affair_us.mp3', 'noun', 'B1', 'events that are of public interest or political importance', '', 'world/international affairs', '', ARRAY[]::TEXT[]),
('Affect', 'affect_us.mp3', 'verb', 'B1', 'to produce a change in somebody/something', '', 'How will these changes affect us?', '', ARRAY[]::TEXT[]),
('Affection', 'affection_us.mp3', 'noun', 'B1', 'the feeling of liking or loving somebody/something very much and caring about them', '', 'Children need lots of love and affection.', '', ARRAY[]::TEXT[]),
('Afford', 'afford_us.mp3', 'verb', 'B1', 'to have enough money to be able to buy or do something', '', 'afford something, Can we afford a new car?', '', ARRAY[]::TEXT[]),
('Affordable', 'affordable_us.mp3', 'adjective', 'B1', 'cheap enough that people can afford to pay it or buy it', '', 'We offer quality products at affordable prices.', '', ARRAY[]::TEXT[]),
('Afraid', 'afraid_us.mp3', 'adjective', 'B1', 'feeling fear; frightened because you think that you might be hurt or suffer', '', 'Don''t be afraid.', '', ARRAY[]::TEXT[]),
('After', 'after_us.mp3', 'adverb', 'B1', 'later in time; afterwards', '', 'That was in 1996. Soon after, I heard that he''d died.', '', ARRAY[]::TEXT[]),
('After', 'after_us.mp3', 'conjunction', 'B1', 'at a time later than something; when something has finished', '', 'I''ll call you after I''ve spoken to them.', '', ARRAY[]::TEXT[]),
('After', 'after_us.mp3', 'preposition', 'B1', 'later than something; following something in time', '', 'We''ll leave after lunch.', '', ARRAY[]::TEXT[]),
('Aftermath', 'aftermath_us.mp3', 'noun', 'B1', 'the situation that exists as a result of an important (and usually unpleasant) event, especially a war, an accident, etc.', '', 'in the aftermath of something, A lot of rebuilding took place in the aftermath of the war.', '', ARRAY[]::TEXT[]),
('Afternoon', 'afternoon_us.mp3', 'noun', 'B1', 'the period of time from 12 o''clock in the middle of the day until about 6 o’clock in the evening', '', 'this/yesterday/tomorrow afternoon', '', ARRAY[]::TEXT[]),
('Afterwards', 'afterwards_us.mp3', 'adverb', 'B1', 'at a later time; after an event that has already been mentioned', '', 'Afterwards she was sorry for what she''d said.', '', ARRAY[]::TEXT[]),
('Again', 'again_us.mp3', 'adverb', 'B1', 'one more time; on another occasion', '', 'This must never happen again.', '', ARRAY[]::TEXT[]),
('Against', 'against_us.mp3', 'preposition', 'B1', 'opposing or disagreeing with somebody/something', '', 'the fight against terrorism', '', ARRAY[]::TEXT[]),
('Age', 'age_us.mp3', 'noun', 'B1', 'the number of years that a person has lived or a thing has existed', '', 'You''re the same age as my brother.', '', ARRAY[]::TEXT[]),
('Age', 'age_us.mp3', 'verb', 'B1', 'to become older', '', 'As he aged, his memory got worse.', '', ARRAY[]::TEXT[]),
('Aged', 'aged_us.mp3', 'adjective', 'B1', 'of the age of', '', 'They have two children aged six and nine.', '', ARRAY[]::TEXT[]),
('Agency', 'agency_us.mp3', 'noun', 'B1', 'a business or an organization that provides a particular service especially when representing other businesses or organizations', '', 'She works for an advertising agency.', '', ARRAY[]::TEXT[]),
('Agenda', 'agenda_us.mp3', 'noun', 'B1', 'a list of items to be discussed at a meeting', '', 'We have a very full agenda of issues to discuss.', '', ARRAY[]::TEXT[]),
('Agent', 'agent_us.mp3', 'noun', 'B1', 'a person whose job is to act for, or manage the affairs of, other people in business, politics, etc.', '', 'Our agent in New York deals with all US sales.', '', ARRAY[]::TEXT[]),
('Aggression', 'aggression_us.mp3', 'noun', 'B1', 'feelings of anger and hate that may result in threatening or violent behaviour', '', 'The research shows that computer games may cause aggression.', '', ARRAY[]::TEXT[]),
('Aggressive', 'aggressive_us.mp3', 'adjective', 'B1', 'angry, and behaving in a threatening way; ready to attack', '', 'Seals have been known to exhibit aggressive behaviour towards swimmers.', '', ARRAY[]::TEXT[]),
('Ago', 'ago_us.mp3', 'adverb', 'B1', 'used in expressions of time with the simple past tense to show how far in the past something happened', '', 'two weeks/months/years ago', '', ARRAY[]::TEXT[]),
('Agree', 'agree_us.mp3', 'verb', 'B1', 'to have the same opinion as somebody; to say that you have the same opinion', '', 'When he said that, I had to agree.', '', ARRAY[]::TEXT[]),
('Agreement', 'agreement_us.mp3', 'noun', 'B1', 'an arrangement, a promise or a contract made with somebody', '', 'an international peace agreement', '', ARRAY[]::TEXT[]),
('Agricultural', 'agricultural_us.mp3', 'adjective', 'B1', 'connected with the science or practice of farming', '', 'agricultural policy/land/production/development', '', ARRAY[]::TEXT[]),
('Agriculture', 'agriculture_us.mp3', 'noun', 'B1', 'the science or practice of farming', '', 'The number of people employed in agriculture has fallen in the last decade.', '', ARRAY[]::TEXT[]),
('Ah', 'ah_us.mp3', 'exclamation', 'B1', 'used to express surprise, pleasure or sympathy, or when you disagree with somebody', '', 'Ah, there you are!', '', ARRAY[]::TEXT[]),
('Ahead', 'ahead_us.mp3', 'adverb', 'B1', 'further forward in space or time; in front', '', 'I''ll run ahead and warn them.', '', ARRAY[]::TEXT[]),
('Aid', 'aid_us.mp3', 'noun', 'B1', 'money, food, etc. that is sent to help countries in difficult situations', '', 'humanitarian/food/medical aid', '', ARRAY[]::TEXT[]),
('Aid', 'aid_us.mp3', 'verb', 'B1', 'to help somebody/something to do something, especially by making it easier', '', 'aid in something, The test is designed to aid in the diagnosis of various diseases.', '', ARRAY[]::TEXT[]),
('Aide', 'aide_us.mp3', 'noun', 'B1', 'a person who helps another person, especially a politician, in their job', '', 'White House aides', '', ARRAY[]::TEXT[]),
('AIDS', 'AIDS_us.mp3', 'noun', 'B1', 'a serious illness caused by a virus called HIV that attacks the body’s ability to resist infection (the abbreviation for ‘Acquired Immune Deficiency Syndrome’)', '', 'the AIDS epidemic', '', ARRAY[]::TEXT[]),
('Aim', 'aim_us.mp3', 'noun', 'B1', 'the purpose of doing something; what somebody is trying to achieve', '', 'the stated aims of the study', '', ARRAY[]::TEXT[]),
('Aim', 'aim_us.mp3', 'verb', 'B1', 'to try or plan to achieve something', '', 'He has always aimed high (= tried to achieve a lot).', '', ARRAY[]::TEXT[]),
('Air', 'air_us.mp3', 'noun', 'B1', 'the mixture of gases that surrounds the earth and that we breathe', '', 'Let''s go out for some fresh air.', '', ARRAY[]::TEXT[]),
('Aircraft', 'aircraft_us.mp3', 'noun', 'B1', 'any vehicle that can fly and carry goods or passengers', '', 'fighter/transport/military aircraft', '', ARRAY[]::TEXT[]),
('Airline', 'airline_us.mp3', 'noun', 'B1', 'a company that provides regular flights to take passengers and goods to different places', '', 'an airline pilot/passenger', '', ARRAY[]::TEXT[]),
('Airport', 'airport_us.mp3', 'noun', 'B1', 'a place where planes land and take off and that has buildings for passengers to wait in', '', 'Gatwick Airport', '', ARRAY[]::TEXT[]),
('Alarm', 'alarm_us.mp3', 'noun', 'B1', 'a loud noise or a signal that warns people of danger or of a problem', '', 'She decided to sound the alarm (= warn people that the situation was dangerous).', '', ARRAY[]::TEXT[]),
('Alarm', 'alarm_us.mp3', 'verb', 'B1', 'to make somebody anxious or afraid', '', 'I can only guess that they don''t want to alarm the public yet.', '', ARRAY[]::TEXT[]),
('Albeit', 'albeit_us.mp3', 'conjunction', 'B1', 'although', '', 'He finally agreed, albeit reluctantly, to help us.', '', ARRAY[]::TEXT[]),
('Album', 'album_us.mp3', 'noun', 'B1', 'a book in which you keep photographs, stamps, etc.', '', 'a photo album', '', ARRAY[]::TEXT[]),
('Alcohol', 'alcohol_us.mp3', 'noun', 'B1', 'drinks such as beer, wine, etc. that can make people drunk', '', 'He never drinks alcohol.', '', ARRAY[]::TEXT[]),
('Alcoholic', 'alcoholic_us.mp3', 'adjective', 'B1', 'connected with or containing alcohol', '', 'alcoholic drinks/beverages', '', ARRAY[]::TEXT[]),
('Alert', 'alert_us.mp3', 'adjective', 'B1', 'able to think quickly; quick to notice things', '', 'Suddenly he found himself awake and fully alert.', '', ARRAY[]::TEXT[]),
('Alert', 'alert_us.mp3', 'noun', 'B1', 'a situation in which people are watching for danger and ready to deal with it', '', 'on the alert (for something), Police are warning the public to be on the alert for suspicious packages.', '', ARRAY[]::TEXT[]),
('Alert', 'alert_us.mp3', 'verb', 'B1', 'to warn somebody about a dangerous situation or one that requires immediate action', '', 'alert somebody, Neighbours quickly alerted the emergency services.', '', ARRAY[]::TEXT[]),
('Alien', 'alien_us.mp3', 'adjective', 'B1', 'strange and frightening; different from what you are used to', '', 'an alien environment', '', ARRAY[]::TEXT[]),
('Alien', 'alien_us.mp3', 'noun', 'B1', 'a person who is not a citizen of the country in which they live or work', '', 'an illegal alien', '', ARRAY[]::TEXT[]),
('Align', 'align_us.mp3', 'verb', 'B1', 'to arrange something in the correct position, or to be in the correct position, in relation to something else, especially in a straight line', '', 'Make sure the shelf is aligned with the top of the cupboard.', '', ARRAY[]::TEXT[]),
('Alignment', 'alignment_us.mp3', 'noun', 'B1', 'arrangement in a straight line', '', 'the alignment of the sun, moon and earth at a particular time', '', ARRAY[]::TEXT[]),
('Alike', 'alike_us.mp3', 'adjective', 'B1', 'very similar', '', 'My sister and I do not look alike.', '', ARRAY[]::TEXT[]),
('Alike', 'alike_us.mp3', 'adverb', 'B1', 'in a very similar way', '', 'They tried to treat all their children alike.', '', ARRAY[]::TEXT[]),
('Alive', 'alive_us.mp3', 'adjective', 'B1', 'living; not dead', '', 'Is your mother still alive?', '', ARRAY[]::TEXT[]),
('All', 'all_us.mp3', 'adverb', 'B1', 'completely', '', 'She was dressed all in white.', '', ARRAY[]::TEXT[]),
('All', 'all_us.mp3', 'determiner', 'B1', 'the whole number of', '', 'All horses are animals, but not all animals are horses.', '', ARRAY[]::TEXT[]),
('All', 'all_us.mp3', 'pronoun', 'B1', 'the whole number or amount', '', 'All of the food has gone.', '', ARRAY[]::TEXT[]),
('All right', 'all right_us.mp3', 'adjective', 'B1', 'acceptable; in an acceptable manner', '', 'Is the coffee all right?', '', ARRAY[]::TEXT[]),
('All right', 'all right_us.mp3', 'adverb', 'B1', 'acceptable; in an acceptable manner', '', 'Is the coffee all right?', '', ARRAY[]::TEXT[]),
('All right', 'all right_us.mp3', 'exclamation', 'B1', 'used to check that somebody agrees or understands', '', 'We''ve got to get up early, all right?', '', ARRAY[]::TEXT[]),
('Allegation', 'allegation_us.mp3', 'noun', 'B1', 'a public statement that is made without giving proof, accusing somebody of doing something that is wrong or illegal', '', 'to investigate/deny/withdraw an allegation', '', ARRAY[]::TEXT[]),
('Allege', 'allege_us.mp3', 'verb', 'B1', 'to state something as a fact but without giving proof', '', 'allege (that)…, The prosecution alleges (that) she was driving carelessly.', '', ARRAY[]::TEXT[]),
('Allegedly', 'allegedly_us.mp3', 'adverb', 'B1', 'expressed as though something is a fact but without giving any proof', '', 'crimes allegedly committed during the war', '', ARRAY[]::TEXT[]),
('Alliance', 'alliance_us.mp3', 'noun', 'B1', 'an agreement between countries, political parties, etc. to work together in order to achieve something that they all want', '', 'to form/make an alliance', '', ARRAY[]::TEXT[]),
('Allocate', 'allocate_us.mp3', 'verb', 'B1', 'to give something officially to somebody/something for a particular purpose', '', 'allocate something (for something), A large sum has been allocated for buying new books for the library.', '', ARRAY[]::TEXT[]),
('Allocation', 'allocation_us.mp3', 'noun', 'B1', 'an amount of money, space, etc. that is given to somebody for a particular purpose', '', 'We have spent our entire allocation for the year.', '', ARRAY[]::TEXT[]),
('Allow', 'allow_us.mp3', 'verb', 'B1', 'to let somebody/something do something; to let something happen or be done', '', 'allow somebody/something to do something, His parents won''t allow him to stay out late.', '', ARRAY[]::TEXT[]),
('Allowance', 'allowance_us.mp3', 'noun', 'B1', 'an amount of money that is given to somebody regularly or for a particular purpose', '', 'an allowance of $20 a day', '', ARRAY[]::TEXT[]),
('Ally', 'ally_us.mp3', 'noun', 'B1', 'a country that has agreed to help and support another country, especially in case of a war', '', 'our European/NATO allies', '', ARRAY[]::TEXT[]),
('Almost', 'almost_us.mp3', 'adverb', 'B1', 'not quite', '', 'I like almost all of them.', '', ARRAY[]::TEXT[]),
('Alone', 'alone_us.mp3', 'adjective', 'B1', 'without any other people', '', 'not alone in, Tom is not alone in finding Rick hard to work with.', '', ARRAY[]::TEXT[]),
('Alone', 'alone_us.mp3', 'adverb', 'B1', 'without any other people', '', 'not alone in, Tom is not alone in finding Rick hard to work with.', '', ARRAY[]::TEXT[]),
('Along', 'along_us.mp3', 'adverb', 'B1', 'forward', '', 'I was just walking along singing to myself.', '', ARRAY[]::TEXT[]),
('Along', 'along_us.mp3', 'preposition', 'B1', 'from one end to or towards the other end of something', '', 'They walked slowly along the road.', '', ARRAY[]::TEXT[]),
('Alongside', 'alongside_us.mp3', 'preposition', 'B1', 'next to or at the side of something', '', 'A police car pulled up alongside us.', '', ARRAY[]::TEXT[]),
('Already', 'already_us.mp3', 'adverb', 'B1', 'before now or before a particular time in the past', '', '‘Lunch?’ ‘No thanks, I''ve already eaten.’', '', ARRAY[]::TEXT[]),
('Also', 'also_us.mp3', 'adverb', 'B1', 'in addition; too', '', 'She''s fluent in French and German. She also speaks a little Italian.', '', ARRAY[]::TEXT[]),
('Alter', 'alter_us.mp3', 'verb', 'B1', 'to become different; to make somebody/something different', '', 'Prices did not alter significantly during 2019.', '', ARRAY[]::TEXT[]),
('Alternative', 'alternative_us.mp3', 'adjective', 'B1', 'that can be used instead of something else', '', 'The road was closed so we had to find an alternative route.', '', ARRAY[]::TEXT[]),
('Alternative', 'alternative_us.mp3', 'noun', 'B1', 'a thing that you can choose to do or have out of two or more possibilities', '', 'The car is too expensive so we''re trying to find a cheaper alternative.', '', ARRAY[]::TEXT[]),
('Although', 'although_us.mp3', 'conjunction', 'B1', 'used for introducing a statement that makes the main statement in a sentence seem surprising', '', 'Although the sun was shining, it wasn''t very warm.', '', ARRAY[]::TEXT[]),
('Altogether', 'altogether_us.mp3', 'adverb', 'B1', '(used to emphasize something) completely; in every way', '', 'The train went slower and slower until it stopped altogether.', '', ARRAY[]::TEXT[]),
('Aluminium', 'aluminium_us.mp3', 'noun', 'B1', 'a chemical element. Aluminium is a light, silver-grey metal used for making pans, etc.', '', 'aluminium saucepans/window frames', '', ARRAY[]::TEXT[]),
('Always', 'always_us.mp3', 'adverb', 'B1', 'at all times; on every occasion', '', 'There''s almost always somebody at home in the evenings.', '', ARRAY[]::TEXT[]),
('Amateur', 'amateur_us.mp3', 'adjective', 'B1', 'doing something for pleasure or interest, not as a job', '', 'an amateur photographer', '', ARRAY[]::TEXT[]),
('Amateur', 'amateur_us.mp3', 'noun', 'B1', 'a person who takes part in a sport or other activity for pleasure, not as a job', '', 'The tournament is open to both amateurs and professionals.', '', ARRAY[]::TEXT[]),
('Amazed', 'amazed_us.mp3', 'adjective', 'B1', 'very surprised', '', 'an amazed look', '', ARRAY[]::TEXT[]),
('Amazing', 'amazing_us.mp3', 'adjective', 'B1', 'very surprising, especially in a way that you like or admire', '', 'an amazing feat/story/experience', '', ARRAY[]::TEXT[]),
('Ambassador', 'ambassador_us.mp3', 'noun', 'B1', 'an official who lives in a foreign country as the senior representative there of their own country', '', 'the British Ambassador to Italy/in Rome', '', ARRAY[]::TEXT[]),
('Ambition', 'ambition_us.mp3', 'noun', 'B1', 'something that you want to do or achieve very much', '', 'She had fulfilled her lifelong ambition.', '', ARRAY[]::TEXT[]),
('Ambitious', 'ambitious_us.mp3', 'adjective', 'B1', 'determined to be successful, rich, powerful, etc.', '', 'a fiercely ambitious young manager', '', ARRAY[]::TEXT[]),
('Ambulance', 'ambulance_us.mp3', 'noun', 'B1', 'a vehicle with special equipment, used for taking sick or injured people to a hospital', '', 'Call an ambulance!', '', ARRAY[]::TEXT[]),
('Amend', 'amend_us.mp3', 'verb', 'B1', 'to change a law, document, statement, etc. slightly in order to correct a mistake or to improve it', '', 'He asked to see the amended version.', '', ARRAY[]::TEXT[]),
('Amendment', 'amendment_us.mp3', 'noun', 'B1', 'a small change or improvement that is made to a document or proposed new law; the process of changing a document or proposed new law', '', 'to introduce/propose/table an amendment (= to suggest it)', '', ARRAY[]::TEXT[]),
('Amid', 'amid_us.mp3', 'preposition', 'B1', 'in the middle of or during something, especially something that causes excitement or fear', '', 'He finished his speech amid tremendous applause.', '', ARRAY[]::TEXT[]),
('Among', 'among_us.mp3', 'preposition', 'B1', 'surrounded by somebody/something; in the middle of somebody/something', '', 'a house among the trees', '', ARRAY[]::TEXT[]),
('Amount', 'amount_us.mp3', 'noun', 'B1', 'a quantity of something', '', 'I was amazed at the amount he could eat.', '', ARRAY[]::TEXT[]),
('Amusing', 'amusing_us.mp3', 'adjective', 'B1', 'funny and giving pleasure', '', 'an amusing story/game/incident', '', ARRAY[]::TEXT[]),
('Analogy', 'analogy_us.mp3', 'noun', 'B1', 'a comparison of one thing with another thing that has similar features; a feature that is similar', '', 'analogy (between A and B), The teacher drew an analogy between the human heart and a pump.', '', ARRAY[]::TEXT[]),
('Analyse', 'analyse_us.mp3', 'verb', 'B1', 'to examine the nature or structure of something, especially by separating it into its parts, in order to understand or explain it', '', 'analyse something, The job involves collecting and analysing data.', '', ARRAY[]::TEXT[]),
('Analysis', 'analysis_us.mp3', 'noun', 'B1', 'the detailed study or examination of something in order to understand more about it; the result of the study', '', 'statistical/data analysis', '', ARRAY[]::TEXT[]),
('Analyst', 'analyst_us.mp3', 'noun', 'B1', 'a person whose job involves examining facts or materials in order to give an opinion on them', '', 'a political/financial analyst', '', ARRAY[]::TEXT[]),
('Ancestor', 'ancestor_us.mp3', 'noun', 'B1', 'a person in your family who lived a long time ago', '', 'His ancestors had come to America from Ireland.', '', ARRAY[]::TEXT[]),
('Anchor', 'anchor_us.mp3', 'noun', 'B1', 'a heavy metal object that is attached to a rope or chain and dropped over the side of a ship or boat to keep it in one place', '', 'to drop anchor', '', ARRAY[]::TEXT[]),
('Ancient', 'ancient_us.mp3', 'adjective', 'B1', 'belonging to a period of history that is thousands of years in the past', '', 'Archaeologists are excavating the ruined temples of this ancient civilization.', '', ARRAY[]::TEXT[]),
('And', 'and_us.mp3', 'conjunction', 'B1', 'also; in addition to', '', 'bread and butter', '', ARRAY[]::TEXT[]),
('Angel', 'angel_us.mp3', 'noun', 'B1', 'a spirit who is believed to be a servant of God, and is sent by God to deliver a message or perform a task. Angels are often shown dressed in white, with wings.', '', 'a host of angels', '', ARRAY[]::TEXT[]),
('Anger', 'anger_us.mp3', 'noun', 'B1', 'the strong feeling that you have when something has happened that you think is bad and unfair', '', 'She had to find a way to express her pent-up anger.', '', ARRAY[]::TEXT[]),
('Angle', 'angle_us.mp3', 'noun', 'B1', 'the space between two lines or surfaces that join, measured in degrees', '', 'a 45° angle', '', ARRAY[]::TEXT[]),
('Angry', 'angry_us.mp3', 'adjective', 'B1', 'having strong feelings about something that you dislike very much or about an unfair situation', '', 'Her behaviour really made me angry.', '', ARRAY[]::TEXT[]),
('Animal', 'animal_us.mp3', 'noun', 'B1', 'a creature that is not a bird, a fish, a reptile, an insect or a human', '', 'the animals and birds of South America', '', ARRAY[]::TEXT[]),
('Animation', 'animation_us.mp3', 'noun', 'B1', 'the process of making films, videos and computer games in which drawings, models or images of people and animals seem to move', '', 'computer/cartoon animation', '', ARRAY[]::TEXT[]),
('Ankle', 'ankle_us.mp3', 'noun', 'B1', 'the joint connecting the foot to the leg; the narrow part of the leg just above the ankle joint', '', 'to sprain/break/twist your ankle', '', ARRAY[]::TEXT[]),
('Anniversary', 'anniversary_us.mp3', 'noun', 'B1', 'a date that is an exact number of years after the date of an important or special event', '', 'on the anniversary of his wife’s death', '', ARRAY[]::TEXT[]),
('Announce', 'announce_us.mp3', 'verb', 'B1', 'to tell people something officially, especially about a decision, plans, etc.', '', 'announce something, He officially announced his intention to resign at today''s press conference.', '', ARRAY[]::TEXT[]),
('Announcement', 'announcement_us.mp3', 'noun', 'B1', 'a spoken or written statement that informs people about something', '', 'to make an announcement', '', ARRAY[]::TEXT[]),
('Annoy', 'annoy_us.mp3', 'verb', 'B1', 'to make somebody slightly angry', '', 'annoy somebody, His constant joking was beginning to annoy her.', '', ARRAY[]::TEXT[]),
('Annoyed', 'annoyed_us.mp3', 'adjective', 'B1', 'slightly angry', '', 'annoyed with somebody at/about something, He was beginning to get very annoyed with me about my carelessness.', '', ARRAY[]::TEXT[]),
('Annoying', 'annoying_us.mp3', 'adjective', 'B1', 'making somebody feel slightly angry', '', 'This interruption is very annoying.', '', ARRAY[]::TEXT[]),
('Annual', 'annual_us.mp3', 'adjective', 'B1', 'happening or done once every year', '', 'an annual meeting/event/report/conference', '', ARRAY[]::TEXT[]),
('Annually', 'annually_us.mp3', 'adverb', 'B1', 'once a year', '', 'The exhibition is held annually.', '', ARRAY[]::TEXT[]),
('Anonymous', 'anonymous_us.mp3', 'adjective', 'B1', 'with a name that is not known or that is not made public', '', 'an anonymous donor', '', ARRAY[]::TEXT[]),
('Another', 'another_us.mp3', 'determiner', 'B1', 'one more; an extra thing or person', '', 'Would you like another drink?', '', ARRAY[]::TEXT[]),
('Another', 'another_us.mp3', 'pronoun', 'B1', 'one more; an extra thing or person', '', 'Would you like another drink?', '', ARRAY[]::TEXT[]),
('Answer', 'answer_us.mp3', 'noun', 'B1', 'something that you say, write or do to react to a question or situation', '', 'I rang the bell, but there was no answer.', '', ARRAY[]::TEXT[]),
('Answer', 'answer_us.mp3', 'verb', 'B1', 'to say, write or do something as a reaction to a question or situation', '', 'I repeated the question, but she didn''t answer.', '', ARRAY[]::TEXT[]),
('Anticipate', 'anticipate_us.mp3', 'verb', 'B1', 'to expect something', '', 'anticipate something, We don''t anticipate any major problems.', '', ARRAY[]::TEXT[]),
('Anxiety', 'anxiety_us.mp3', 'noun', 'B1', 'the state of feeling nervous or worried that something bad is going to happen', '', 'acute/intense/deep anxiety', '', ARRAY[]::TEXT[]),
('Anxious', 'anxious_us.mp3', 'adjective', 'B1', 'feeling worried or nervous', '', 'The bus was late and Sue began to get anxious.', '', ARRAY[]::TEXT[]),
('Any', 'any_us.mp3', 'adverb', 'B1', 'used to emphasize an adjective or adverb in negative sentences or questions, meaning ‘at all’', '', 'He wasn''t any good at French.', '', ARRAY[]::TEXT[]),
('Any', 'any_us.mp3', 'determiner', 'B1', 'used with uncountable or plural nouns in negative sentences and questions, after if or whether, and after some verbs such as prevent, ban, forbid, etc. to refer to an amount or a number of something, however large or small', '', 'I didn''t eat any meat.', '', ARRAY[]::TEXT[]),
('Any', 'any_us.mp3', 'pronoun', 'B1', 'used in negative sentences and in questions and after if or whether to refer to an amount or a number, however large or small', '', 'We need some more paint; there isn''t any left.', '', ARRAY[]::TEXT[]),
('Any more', 'any more_us.mp3', 'adverb', 'B1', 'often used at the end of negative sentences and at the end of questions, to mean ‘any longer’', '', 'She doesn''t live here any more.', '', ARRAY[]::TEXT[]),
('Anybody', 'anybody_us.mp3', 'pronoun', 'B1', 'used instead of somebody in negative sentences and in questions after if/whether, and after verbs such as prevent, forbid, avoid, etc.', '', 'Is there anybody who can help me?', '', ARRAY[]::TEXT[]),
('Anyone', 'anyone_us.mp3', 'pronoun', 'B1', 'used instead of someone in negative sentences and in questions after if/whether, and after verbs such as prevent, forbid, avoid, etc.', '', 'Is anyone there?', '', ARRAY[]::TEXT[]),
('Anything', 'anything_us.mp3', 'pronoun', 'B1', 'used instead of something in negative sentences and in questions; after if/whether; and after verbs such as prevent, ban, avoid, etc.', '', 'Would you like anything else?', '', ARRAY[]::TEXT[]),
('Anyway', 'anyway_us.mp3', 'adverb', 'B1', 'used when adding something to support an idea or argument', '', 'It''s too expensive and anyway the colour doesn''t suit you.', '', ARRAY[]::TEXT[]),
('Anywhere', 'anywhere_us.mp3', 'adverb', 'B1', 'used in negative sentences and in questions instead of somewhere', '', 'I can''t see it anywhere.', '', ARRAY[]::TEXT[]),
('Anywhere', 'anywhere_us.mp3', 'pronoun', 'B1', 'used in negative sentences and in questions instead of somewhere', '', 'I don''t have anywhere to stay.', '', ARRAY[]::TEXT[]),
('Apart', 'apart_us.mp3', 'adverb', 'B1', 'separated by a distance, of space or time', '', 'The two houses stood 500 metres apart.', '', ARRAY[]::TEXT[]),
('Apartment', 'apartment_us.mp3', 'noun', 'B1', 'a set of rooms for living in, usually on one floor of a building', '', 'an apartment building', '', ARRAY[]::TEXT[]),
('Apologize', 'apologize_us.mp3', 'verb', 'B1', 'to say that you are sorry for doing something wrong or causing a problem', '', 'Why should I apologize?', '', ARRAY[]::TEXT[]),
('Apology', 'apology_us.mp3', 'noun', 'B1', 'a word or statement saying sorry for something that has been done wrong or that causes a problem', '', 'to offer/make/demand/accept an apology', '', ARRAY[]::TEXT[]),
('App', 'app_us.mp3', 'noun', 'B1', 'a piece of software that you can download to a device such as a smartphone or tablet, for example to look up information or to play a game', '', 'You first need to install the app on your device.', '', ARRAY[]::TEXT[]),
('Apparatus', 'apparatus_us.mp3', 'noun', 'B1', 'the tools or other pieces of equipment that are needed for a particular activity or task', '', 'a piece of laboratory apparatus', '', ARRAY[]::TEXT[]),
('Apparent', 'apparent_us.mp3', 'adjective', 'B1', 'easy to see or understand', '', 'Their devotion was apparent.', '', ARRAY[]::TEXT[]),
('Apparently', 'apparently_us.mp3', 'adverb', 'B1', 'according to what you have heard or read; according to the way something appears', '', 'Apparently they are getting divorced soon.', '', ARRAY[]::TEXT[]),
('Appeal', 'appeal_us.mp3', 'noun', 'B1', 'a deeply felt request for money, help or information that is needed immediately, especially one made by a charity or by the police', '', 'appeal for something, to launch a TV appeal for donations to the charity', '', ARRAY[]::TEXT[]),
('Appeal', 'appeal_us.mp3', 'verb', 'B1', 'to make a deeply felt request, especially for something that is needed immediately', '', 'I am appealing (= asking for money) on behalf of the famine victims.', '', ARRAY[]::TEXT[]),
('Appealing', 'appealing_us.mp3', 'adjective', 'B1', 'attractive or interesting', '', 'Spending the holidays in Britain wasn''t a prospect that I found particularly appealing.', '', ARRAY[]::TEXT[]),
('Appear', 'appear_us.mp3', 'verb', 'B1', 'to start to be seen', '', 'Three days later a rash appeared.', '', ARRAY[]::TEXT[]),
('Appearance', 'appearance_us.mp3', 'noun', 'B1', 'the way that somebody/something looks on the outside; what somebody/something seems to be', '', 'the physical/outward/external appearance of something', '', ARRAY[]::TEXT[]),
('Appetite', 'appetite_us.mp3', 'noun', 'B1', 'physical desire for food', '', 'He suffered from headaches and loss of appetite.', '', ARRAY[]::TEXT[]),
('Applaud', 'applaud_us.mp3', 'verb', 'B1', 'to show your approval of somebody/something by clapping your hands (= hitting your open hands together several times)', '', 'He started to applaud and the others joined in.', '', ARRAY[]::TEXT[]),
('Apple', 'apple_us.mp3', 'noun', 'B1', 'a round fruit with shiny red or green skin that is fairly hard and white inside', '', 'Peel and core the apples.', '', ARRAY[]::TEXT[]),
('Applicable', 'applicable_us.mp3', 'adjective', 'B1', 'that can be said to be true in the case of somebody/something', '', 'Give details of children where applicable (= if you have any).', '', ARRAY[]::TEXT[]),
('Applicant', 'applicant_us.mp3', 'noun', 'B1', 'a person who makes a formal request for something (= applies for it), especially for a job, a place at a college or university, etc.', '', 'There were over 500 applicants for the job.', '', ARRAY[]::TEXT[]),
('Application', 'application_us.mp3', 'noun', 'B1', 'a formal (often written) request for something, such as a job, permission to do something or a place at a college or university', '', 'a planning/patent/visa application', '', ARRAY[]::TEXT[]),
('Apply', 'apply_us.mp3', 'verb', 'B1', 'to make a formal request, usually in writing, for something such as a job, a loan, permission for something, a place at a university, etc.', '', 'You should apply in person/by letter.', '', ARRAY[]::TEXT[]),
('Appoint', 'appoint_us.mp3', 'verb', 'B1', 'to choose somebody for a job or position of responsibility', '', 'appoint somebody, They have appointed a new head teacher at my son''s school.', '', ARRAY[]::TEXT[]),
('Appointment', 'appointment_us.mp3', 'noun', 'B1', 'a formal arrangement to meet or visit somebody at a particular time, especially for a reason connected with their work', '', 'I''ve got a dental appointment at 3 o''clock.', '', ARRAY[]::TEXT[]),
('Appreciate', 'appreciate_us.mp3', 'verb', 'B1', 'to recognize the good qualities of somebody/something', '', 'Over the years he came to appreciate the beauty and tranquillity of the river.', '', ARRAY[]::TEXT[]),
('Appreciation', 'appreciation_us.mp3', 'noun', 'B1', 'pleasure that you have when you recognize and enjoy the good qualities of somebody/something', '', 'She shows little appreciation of good music.', '', ARRAY[]::TEXT[]),
('Approach', 'approach_us.mp3', 'noun', 'B1', 'a way of dealing with somebody/something; a way of doing or thinking about something such as a problem or a task', '', 'She took the wrong approach in her dealings with them.', '', ARRAY[]::TEXT[]),
('Approach', 'approach_us.mp3', 'verb', 'B1', 'to come near to somebody/something in distance or time', '', 'We could hear the train approaching.', '', ARRAY[]::TEXT[]),
('Appropriate', 'appropriate_us.mp3', 'adjective', 'B1', 'suitable, acceptable or correct for the particular circumstances', '', 'an appropriate response/measure/method', '', ARRAY[]::TEXT[]),
('Appropriately', 'appropriately_us.mp3', 'adverb', 'B1', 'in a way that is suitable, acceptable or correct for the particular circumstances', '', 'The government has been accused of not responding appropriately to the needs of the homeless.', '', ARRAY[]::TEXT[]),
('Approval', 'approval_us.mp3', 'noun', 'B1', 'the feeling that somebody/something is good or acceptable; a positive opinion of somebody/something', '', 'She desperately wanted to win her father''s approval.', '', ARRAY[]::TEXT[]),
('Approve', 'approve_us.mp3', 'verb', 'B1', 'to think that somebody/something is good, acceptable or suitable', '', 'I told my mother I wanted to leave school but she didn''t approve.', '', ARRAY[]::TEXT[]),
('Approximately', 'approximately_us.mp3', 'adverb', 'B1', 'used to show that something is almost, but not completely, accurate or correct', '', 'The journey took approximately seven hours.', '', ARRAY[]::TEXT[]),
('April', 'April_us.mp3', 'noun', 'B1', 'the fourth month of the year, between March and May', '', 'in April, She was born in April.', '', ARRAY[]::TEXT[]),
('Arbitrary', 'arbitrary_us.mp3', 'adjective', 'B1', 'not seeming to be based on a reason, system or plan and sometimes seeming unfair', '', 'The choice of players for the team seemed completely arbitrary.', '', ARRAY[]::TEXT[]),
('Architect', 'architect_us.mp3', 'noun', 'B1', 'a person whose job is designing buildings', '', 'The house was designed by architect Louis Kahn.', '', ARRAY[]::TEXT[]),
('Architectural', 'architectural_us.mp3', 'adjective', 'B1', 'relating to architecture and buildings', '', 'architectural features', '', ARRAY[]::TEXT[]),
('Architecture', 'architecture_us.mp3', 'noun', 'B1', 'the art and study of designing buildings', '', 'to study architecture', '', ARRAY[]::TEXT[]),
('Archive', 'archive_us.mp3', 'noun', 'B1', 'a collection of historical documents or records of a government, a family, a place or an organization; the place where these records are stored', '', 'the National Sound Archive', '', ARRAY[]::TEXT[]),
('Area', 'area_us.mp3', 'noun', 'B1', 'part of a place, town, etc., or a region of a country or the world', '', 'to improve access to services in rural areas', '', ARRAY[]::TEXT[]),
('Arena', 'arena_us.mp3', 'noun', 'B1', 'a place with a flat open area in the middle and seats around it where people can watch sports and entertainment', '', 'a concert at Wembley Arena', '', ARRAY[]::TEXT[]),
('Arguably', 'arguably_us.mp3', 'adverb', 'B1', 'used (often before a comparative or superlative adjective) when you are stating an opinion that you believe you could give reasons to support', '', 'He is arguably the best actor of his generation.', '', ARRAY[]::TEXT[]),
('Argue', 'argue_us.mp3', 'verb', 'B1', 'to speak angrily to somebody because you disagree with them', '', 'My brothers are always arguing.', '', ARRAY[]::TEXT[]),
('Argument', 'argument_us.mp3', 'noun', 'B1', 'a conversation or discussion in which two or more people disagree, often angrily', '', 'to win/lose an argument', '', ARRAY[]::TEXT[]),
('Arise', 'arise_us.mp3', 'verb', 'B1', 'to happen; to start to exist', '', 'An opportunity arose to work in the United States.', '', ARRAY[]::TEXT[]),
('Arm', 'arm_us.mp3', 'noun', 'B1', 'either of the two long parts that stick out from the top of the body and connect the shoulders to the hands', '', 'He escaped with only a broken arm.', '', ARRAY[]::TEXT[]),
('Arm', 'arm_us.mp3', 'verb', 'B1', 'to provide weapons for yourself/somebody in order to fight a battle or a war', '', 'The country was arming against the enemy.', '', ARRAY[]::TEXT[]),
('Armed', 'armed_us.mp3', 'adjective', 'B1', 'involving the use of weapons', '', 'an armed robbery', '', ARRAY[]::TEXT[]),
('Arms', 'arms_us.mp3', 'noun', 'B1', 'weapons, especially as used by the army, navy, etc.', '', 'arms and ammunition', '', ARRAY[]::TEXT[]),
('Army', 'army_us.mp3', 'noun', 'B1', 'a large organized group of soldiers who are trained to fight on land', '', 'The two opposing armies faced each other across the battlefield.', '', ARRAY[]::TEXT[]),
('Around', 'around_us.mp3', 'adverb', 'B1', 'approximately', '', 'He arrived around five o''clock.', '', ARRAY[]::TEXT[]),
('Around', 'around_us.mp3', 'preposition', 'B1', 'surrounding somebody/something; on each side of something', '', 'The house is built around a central courtyard.', '', ARRAY[]::TEXT[]),
('Arrange', 'arrange_us.mp3', 'verb', 'B1', 'to plan or organize something in advance', '', 'arrange something, The party was arranged quickly.', '', ARRAY[]::TEXT[]),
('Arrangement', 'arrangement_us.mp3', 'noun', 'B1', 'a plan or preparation that you make so that something can happen', '', 'Travel and accommodation arrangements have been finalized.', '', ARRAY[]::TEXT[]),
('Array', 'array_us.mp3', 'noun', 'B1', 'a group or collection of things or people, often one that is large or impressive', '', 'a vast array of bottles of different shapes and sizes', '', ARRAY[]::TEXT[]),
('Arrest', 'arrest_us.mp3', 'noun', 'B1', 'the act of arresting somebody', '', 'The police made several arrests.', '', ARRAY[]::TEXT[]),
('Arrest', 'arrest_us.mp3', 'verb', 'B1', 'if the police arrest somebody, the person is taken to a police station and kept there because the police believe they may be guilty of a crime', '', 'arrest somebody, A man has been arrested in connection with the robbery.', '', ARRAY[]::TEXT[]),
('Arrival', 'arrival_us.mp3', 'noun', 'B1', 'an act of coming or being brought to a place', '', 'We apologize for the late arrival of the train.', '', ARRAY[]::TEXT[]),
('Arrive', 'arrive_us.mp3', 'verb', 'B1', 'to get to a place, especially at the end of a journey', '', 'I''ll wait until they arrive.', '', ARRAY[]::TEXT[]),
('Arrow', 'arrow_us.mp3', 'noun', 'B1', 'a thin stick with a sharp point at one end, which is shot from a bow', '', 'a bow and arrow', '', ARRAY[]::TEXT[]),
('Art', 'art_us.mp3', 'noun', 'B1', 'the use of the imagination to express ideas or feelings, particularly in painting, drawing or sculpture', '', 'modern/contemporary art', '', ARRAY[]::TEXT[]),
('Article', 'article_us.mp3', 'noun', 'B1', 'a piece of writing about a particular subject in a newspaper or magazine, on a website, etc.', '', 'to read/write/publish an article', '', ARRAY[]::TEXT[]),
('Articulate', 'articulate_us.mp3', 'verb', 'B1', 'to express or explain your thoughts or feelings clearly in words', '', 'She struggled to articulate her thoughts.', '', ARRAY[]::TEXT[]),
('Artificial', 'artificial_us.mp3', 'adjective', 'B1', 'made or produced to copy something natural; not real', '', 'an artificial limb/flower/sweetener/fertilizer', '', ARRAY[]::TEXT[]),
('Artist', 'artist_us.mp3', 'noun', 'B1', 'a person who creates works of art, especially paintings or drawings', '', 'an exhibition of work by contemporary British artists', '', ARRAY[]::TEXT[]),
('Artistic', 'artistic_us.mp3', 'adjective', 'B1', 'connected with art or artists', '', 'the artistic works of the period', '', ARRAY[]::TEXT[]),
('Artwork', 'artwork_us.mp3', 'noun', 'B1', 'pictures and photographs prepared for books, magazines, etc.', '', 'Can you let me have the finished artwork for the poster by Friday?', '', ARRAY[]::TEXT[]),
('As', 'as_us.mp3', 'adverb', 'B1', 'used when you are comparing two people or things, or two situations', '', 'You''re as tall as your father.', '', ARRAY[]::TEXT[]),
('As', 'as_us.mp3', 'conjunction', 'B1', 'while something else is happening', '', 'He sat watching her as she got ready.', '', ARRAY[]::TEXT[]),
('As', 'as_us.mp3', 'preposition', 'B1', 'used to describe somebody/something appearing to be somebody/something else', '', 'They were all dressed as clowns.', '', ARRAY[]::TEXT[]),
('Ash', 'ash_us.mp3', 'noun', 'B1', 'the grey or black powder that is left after something, especially tobacco, wood or coal, has burnt', '', 'cigarette ash', '', ARRAY[]::TEXT[]),
('Ashamed', 'ashamed_us.mp3', 'adjective', 'B1', 'feeling shame or feeling embarrassed about somebody/something or because of something you have done', '', 'ashamed of something, She was deeply ashamed of her behaviour at the party.', '', ARRAY[]::TEXT[]),
('Aside', 'aside_us.mp3', 'adverb', 'B1', 'to one side; out of the way', '', 'She pulled the curtain aside.', '', ARRAY[]::TEXT[]),
('Ask', 'ask_us.mp3', 'verb', 'B1', 'to say or write something in the form of a question, in order to get information', '', 'How old are you—if you don’t mind me/my asking?', '', ARRAY[]::TEXT[]),
('Asleep', 'asleep_us.mp3', 'adjective', 'B1', 'sleeping', '', 'I waited until they were all fast asleep (= sleeping deeply).', '', ARRAY[]::TEXT[]),
('Aspect', 'aspect_us.mp3', 'noun', 'B1', 'a particular part or feature of a situation, an idea, a problem, etc.; a way in which it may be considered', '', 'aspect of something, The book aims to cover all aspects of city life.', '', ARRAY[]::TEXT[]),
('Aspiration', 'aspiration_us.mp3', 'noun', 'B1', 'a strong desire to have or do something', '', 'I didn''t realize you had political aspirations.', '', ARRAY[]::TEXT[]),
('Aspire', 'aspire_us.mp3', 'verb', 'B1', 'to have a strong desire to achieve or to become something', '', 'aspire (to something), She aspired to a scientific career.', '', ARRAY[]::TEXT[]),
('Assassination', 'assassination_us.mp3', 'noun', 'B1', 'the murder of an important or famous person, especially for political reasons', '', 'The president survived a number of assassination attempts.', '', ARRAY[]::TEXT[]),
('Assault', 'assault_us.mp3', 'noun', 'B1', 'the crime of attacking somebody physically', '', 'Both men were charged with assault.', '', ARRAY[]::TEXT[]),
('Assault', 'assault_us.mp3', 'verb', 'B1', 'to attack somebody violently, especially when this is a crime', '', 'He has been charged with assaulting a police officer.', '', ARRAY[]::TEXT[]),
('Assemble', 'assemble_us.mp3', 'verb', 'B1', 'to come together as a group; to bring people or things together as a group', '', 'All the students were asked to assemble in the main hall.', '', ARRAY[]::TEXT[]),
('Assembly', 'assembly_us.mp3', 'noun', 'B1', 'a group of people who have been elected to meet together regularly and make decisions or laws for a particular region or country', '', 'state/legislative/federal/local assemblies', '', ARRAY[]::TEXT[]),
('Assert', 'assert_us.mp3', 'verb', 'B1', 'to state clearly and definitely that something is true', '', 'assert that…, She continued to assert that she was innocent.', '', ARRAY[]::TEXT[]),
('Assertion', 'assertion_us.mp3', 'noun', 'B1', 'a statement saying that you strongly believe something to be true', '', 'He was correct in his assertion that the minister had been lying.', '', ARRAY[]::TEXT[]),
('Assess', 'assess_us.mp3', 'verb', 'B1', 'to make a judgement about the nature or quality of somebody/something', '', 'assess somebody/something, Accurately assessing environmental impacts is very complex.', '', ARRAY[]::TEXT[]),
('Assessment', 'assessment_us.mp3', 'noun', 'B1', 'an opinion or a judgement about somebody/something that has been thought about very carefully', '', 'a detailed assessment of the risks involved', '', ARRAY[]::TEXT[]),
('Asset', 'asset_us.mp3', 'noun', 'B1', 'a person or thing that is valuable or useful to somebody/something', '', 'In his job, patience is an invaluable asset.', '', ARRAY[]::TEXT[]),
('Assign', 'assign_us.mp3', 'verb', 'B1', 'to give somebody something that they can use, or some work or responsibility', '', 'assign something (to somebody), The teacher assigned a different task to each of the children.', '', ARRAY[]::TEXT[]),
('Assignment', 'assignment_us.mp3', 'noun', 'B1', 'a task or piece of work that somebody is given to do, usually as part of their job or studies', '', 'Students are required to complete all homework assignments.', '', ARRAY[]::TEXT[]),
('Assist', 'assist_us.mp3', 'verb', 'B1', 'to help somebody to do something', '', 'Anyone willing to assist can contact this number.', '', ARRAY[]::TEXT[]),
('Assistance', 'assistance_us.mp3', 'noun', 'B1', 'help or support', '', 'technical/economic/military assistance', '', ARRAY[]::TEXT[]),
('Assistant', 'assistant_us.mp3', 'adjective', 'B1', 'having a rank below that of a senior person and helping them in their work', '', 'the assistant manager/director/commissioner', '', ARRAY[]::TEXT[]),
('Assistant', 'assistant_us.mp3', 'noun', 'B1', 'a person who helps or supports somebody, usually in their job', '', 'My assistant will now demonstrate the machine in action.', '', ARRAY[]::TEXT[]),
('Associate', 'associate_us.mp3', 'verb', 'B1', 'to make a connection between people or things in your mind', '', 'associate somebody/something with somebody/something, I always associate the smell of baking with my childhood.', '', ARRAY[]::TEXT[]),
('Associated', 'associated_us.mp3', 'adjective', 'B1', 'if one thing is associated with another, the two things are connected because they happen together or one thing causes the other', '', 'associated with doing something, the risks associated with taking drugs', '', ARRAY[]::TEXT[]),
('Association', 'association_us.mp3', 'noun', 'B1', 'an official group of people who have joined together for a particular purpose', '', 'Do you belong to any professional or trade associations?', '', ARRAY[]::TEXT[]),
('Assume', 'assume_us.mp3', 'verb', 'B1', 'to think or accept that something is true but without having proof of it', '', 'assume (that)…, It is reasonable to assume (that) the economy will continue to improve.', '', ARRAY[]::TEXT[]),
('Assumption', 'assumption_us.mp3', 'noun', 'B1', 'a belief or feeling that something is true or that something will happen, although there is no proof', '', 'an underlying/implicit assumption', '', ARRAY[]::TEXT[]),
('Assurance', 'assurance_us.mp3', 'noun', 'B1', 'a statement that something will certainly be true or will certainly happen, particularly when there has been doubt about it', '', 'They called for assurances that the government is committed to its education policy.', '', ARRAY[]::TEXT[]),
('Assure', 'assure_us.mp3', 'verb', 'B1', 'to tell somebody that something is definitely true or is definitely going to happen, especially when they have doubts about it', '', 'assure somebody (that)…, You think I did it deliberately, but I assure you (that) I did not.', '', ARRAY[]::TEXT[]),
('Astonishing', 'astonishing_us.mp3', 'adjective', 'B1', 'very surprising; difficult to believe', '', 'She ran 100m in an astonishing 10.6 seconds.', '', ARRAY[]::TEXT[]),
('Asylum', 'asylum_us.mp3', 'noun', 'B1', 'protection that a government gives to people who have left their own country, usually because they were in danger for political reasons', '', 'to seek/apply for/be granted asylum', '', ARRAY[]::TEXT[]),
('At', 'at_us.mp3', 'preposition', 'B1', 'used to say where something/somebody is or where something happens', '', 'at the corner of the street', '', ARRAY[]::TEXT[]),
('Athlete', 'athlete_us.mp3', 'noun', 'B1', 'a person who competes in sports', '', 'Olympic athletes', '', ARRAY[]::TEXT[]),
('Atmosphere', 'atmosphere_us.mp3', 'noun', 'B1', 'the mixture of gases that surrounds the earth', '', 'Wind power doesn''t release carbon dioxide into the atmosphere.', '', ARRAY[]::TEXT[]),
('Atrocity', 'atrocity_us.mp3', 'noun', 'B1', 'a cruel and violent act, especially in a war', '', 'In the war, both sides committed atrocities.', '', ARRAY[]::TEXT[]),
('Attach', 'attach_us.mp3', 'verb', 'B1', 'to fasten or join one thing to another', '', 'attach something, I attach a copy of my notes for your information.', '', ARRAY[]::TEXT[]),
('Attachment', 'attachment_us.mp3', 'noun', 'B1', 'a document that you send to somebody using email', '', 'No attachment was included.', '', ARRAY[]::TEXT[]),
('Attack', 'attack_us.mp3', 'noun', 'B1', 'an act of using violence to try to hurt or kill somebody', '', 'Five people were killed in the attacks that took place last night.', '', ARRAY[]::TEXT[]),
('Attack', 'attack_us.mp3', 'verb', 'B1', 'to use violence to try to hurt or kill somebody', '', 'Most dogs will not attack unless provoked.', '', ARRAY[]::TEXT[]),
('Attain', 'attain_us.mp3', 'verb', 'B1', 'to succeed in getting something, usually after a lot of effort', '', 'Most of our students attained five ‘A’ grades in their exams.', '', ARRAY[]::TEXT[]),
('Attempt', 'attempt_us.mp3', 'noun', 'B1', 'an act of trying to do something, especially something difficult, often with no success', '', 'I passed my driving test at the first attempt.', '', ARRAY[]::TEXT[]),
('Attempt', 'attempt_us.mp3', 'verb', 'B1', 'to make an effort or try to do something, especially something difficult', '', 'attempt to do something, I will attempt to answer all your questions.', '', ARRAY[]::TEXT[]),
('Attend', 'attend_us.mp3', 'verb', 'B1', 'to be present at an event', '', 'We''d like as many people as possible to attend.', '', ARRAY[]::TEXT[]),
('Attendance', 'attendance_us.mp3', 'noun', 'B1', 'the act of being present at a place, for example at school', '', 'Attendance at these lectures is not compulsory.', '', ARRAY[]::TEXT[]),
('Attention', 'attention_us.mp3', 'exclamation', 'B1', 'used for asking people to listen to something that is being announced', '', 'Attention, please! Passengers for flight KL412 are requested to go to gate 21 immediately.', '', ARRAY[]::TEXT[]),
('Attention', 'attention_us.mp3', 'noun', 'B1', 'the act of listening to, looking at or thinking about something/somebody carefully; interest that people show in somebody/something', '', 'the report’s attention to detail', '', ARRAY[]::TEXT[]),
('Attitude', 'attitude_us.mp3', 'noun', 'B1', 'the way that you think and feel about somebody/something; the way that you behave towards somebody/something that shows how you think and feel', '', 'attitude towards somebody/something, These societies have to change their attitudes towards women.', '', ARRAY[]::TEXT[]),
('Attorney', 'attorney_us.mp3', 'noun', 'B1', 'a lawyer, especially one who can act for somebody in court', '', 'The prosecuting attorney began with a short opening statement.', '', ARRAY[]::TEXT[]),
('Attract', 'attract_us.mp3', 'verb', 'B1', 'if you are attracted by something, it interests you and makes you want it; if you are attracted by somebody, you like or admire them', '', 'be attracted by somebody/something, I had always been attracted by the idea of working abroad.', '', ARRAY[]::TEXT[]),
('Attraction', 'attraction_us.mp3', 'noun', 'B1', 'an interesting or lively place to go or thing to do', '', 'Buckingham Palace is a major tourist attraction.', '', ARRAY[]::TEXT[]),
('Attractive', 'attractive_us.mp3', 'adjective', 'B1', 'pleasant to look at, especially in a sexual way', '', 'an attractive woman', '', ARRAY[]::TEXT[]),
('Attribute', 'attribute_us.mp3', 'noun', 'B1', 'a quality or feature of somebody/something', '', 'Patience is one of the most important attributes in a teacher.', '', ARRAY[]::TEXT[]),
('Attribute', 'attribute_us.mp3', 'verb', 'B1', 'to say or believe that something is the result of a particular thing', '', 'She attributes her success to hard work and a little luck.', '', ARRAY[]::TEXT[]),
('Auction', 'auction_us.mp3', 'noun', 'B1', 'a public sale in which things are sold to the person who offers the most money for them', '', 'an auction of paintings', '', ARRAY[]::TEXT[]),
('Audience', 'audience_us.mp3', 'noun', 'B1', 'the group of people who have gathered to watch or listen to something (a play, concert, somebody speaking, etc.)', '', 'The audience was/were clapping for 10 minutes.', '', ARRAY[]::TEXT[]),
('Audio', 'audio_us.mp3', 'adjective', 'B1', 'connected with sound that is recorded', '', 'audio and video recordings/files/clips', '', ARRAY[]::TEXT[]),
('Audit', 'audit_us.mp3', 'noun', 'B1', 'an official examination of business and financial records to see that they are true and correct', '', 'an annual audit', '', ARRAY[]::TEXT[]),
('August', 'August_us.mp3', 'noun', 'B1', 'the 8th month of the year, between July and September', '', 'She was born in August.', '', ARRAY[]::TEXT[]),
('Aunt', 'aunt_us.mp3', 'noun', 'B1', 'the sister of your father or mother; the wife of your uncle or aunt', '', 'Aunt Alice', '', ARRAY[]::TEXT[]),
('Authentic', 'authentic_us.mp3', 'adjective', 'B1', 'known to be real and what somebody claims it is and not a copy', '', 'I don''t know if the painting is authentic.', '', ARRAY[]::TEXT[]),
('Author', 'author_us.mp3', 'noun', 'B1', 'a person who writes books or the person who wrote a particular book', '', 'Who is your favourite author?', '', ARRAY[]::TEXT[]),
('Authority', 'authority_us.mp3', 'noun', 'B1', 'the power to give orders to people', '', 'in a position of authority', '', ARRAY[]::TEXT[]),
('Authorize', 'authorize_us.mp3', 'verb', 'B1', 'to give official permission for something, or for somebody to do something', '', 'authorize something, I can authorize payments up to £5 000.', '', ARRAY[]::TEXT[]),
('Auto', 'auto_us.mp3', 'noun', 'B1', 'a car', '', 'the auto industry', '', ARRAY[]::TEXT[]),
('Automatic', 'automatic_us.mp3', 'adjective', 'B1', 'having controls that work without needing a person to operate them', '', 'automatic doors', '', ARRAY[]::TEXT[]),
('Automatically', 'automatically_us.mp3', 'adverb', 'B1', 'without needing a person to operate controls', '', 'The heating switches off automatically.', '', ARRAY[]::TEXT[]),
('Autonomy', 'autonomy_us.mp3', 'noun', 'B1', 'the freedom for a country, a region or an organization to govern itself independently', '', 'a campaign in Wales for greater autonomy', '', ARRAY[]::TEXT[]),
('Autumn', 'autumn_us.mp3', 'noun', 'B1', 'the season of the year between summer and winter, when leaves change colour and the weather becomes colder', '', 'in the autumn of something, in the autumn of 2010', '', ARRAY[]::TEXT[]),
('Availability', 'availability_us.mp3', 'noun', 'B1', 'the fact that something is possible to get, buy or find', '', 'the availability of cheap flights', '', ARRAY[]::TEXT[]),
('Available', 'available_us.mp3', 'adjective', 'B1', 'that you can get, buy or find', '', 'available resources/data', '', ARRAY[]::TEXT[]),
('Average', 'average_us.mp3', 'adjective', 'B1', 'calculated by adding several amounts together, finding a total, and dividing the total by the number of amounts', '', 'The average age of participants was 52 years.', '', ARRAY[]::TEXT[]),
('Average', 'average_us.mp3', 'noun', 'B1', 'the result of adding several amounts together, finding a total, and dividing the total by the number of amounts', '', 'The average of 4, 5 and 9 is 6.', '', ARRAY[]::TEXT[]),
('Average', 'average_us.mp3', 'verb', 'B1', 'to be equal to a particular amount as an average', '', 'Economic growth is expected to average 2% next year.', '', ARRAY[]::TEXT[]),
('Avoid', 'avoid_us.mp3', 'verb', 'B1', 'to prevent something bad from happening', '', 'avoid something, to avoid conflict/confrontation', '', ARRAY[]::TEXT[]),
('Await', 'await_us.mp3', 'verb', 'B1', 'to wait for somebody/something', '', 'He is in custody awaiting trial.', '', ARRAY[]::TEXT[]),
('Award', 'award_us.mp3', 'noun', 'B1', 'a prize such as money, etc. for something that somebody has done', '', 'He was nominated for the best actor award.', '', ARRAY[]::TEXT[]),
('Award', 'award_us.mp3', 'verb', 'B1', 'to make an official decision to give something to somebody as a payment, prize, contract, etc.', '', 'award something, Knowing why and how corporations award contracts is vitally important.', '', ARRAY[]::TEXT[]),
('Aware', 'aware_us.mp3', 'adjective', 'B1', 'knowing or realizing something', '', 'As you''re aware, this is not a new problem.', '', ARRAY[]::TEXT[]),
('Awareness', 'awareness_us.mp3', 'noun', 'B1', 'knowing something; knowing that something exists and is important', '', 'awareness of something, an awareness of the importance of eating a healthy diet', '', ARRAY[]::TEXT[]),
('Away', 'away_us.mp3', 'adverb', 'B1', 'to or at a distance from somebody/something in space or time', '', 'The beach is a mile away.', '', ARRAY[]::TEXT[]),
('Awful', 'awful_us.mp3', 'adjective', 'B1', 'very bad or unpleasant', '', 'That''s an awful colour.', '', ARRAY[]::TEXT[]),
('Awkward', 'awkward_us.mp3', 'adjective', 'B1', 'making you feel embarrassed', '', 'There was an awkward silence.', '', ARRAY[]::TEXT[]),
('Baby', 'baby_us.mp3', 'noun', 'B1', 'a very young child or animal', '', 'The baby''s crying!', '', ARRAY[]::TEXT[]),
('Back', 'back_us.mp3', 'adjective', 'B1', 'located behind or at the back of something', '', 'We were sitting in the back row', '', ARRAY[]::TEXT[]),
('Back', 'back_us.mp3', 'adverb', 'B1', 'to or into the place, condition, situation or activity where somebody/something was before', '', 'When is he coming back to work?', '', ARRAY[]::TEXT[]),
('Back', 'back_us.mp3', 'noun', 'B1', 'the part of the human body that is on the opposite side to the chest, between the neck and the tops of the legs; the part of an animal’s body that corresponds to this', '', 'on your back, He was lying on his back on the sofa.', '', ARRAY[]::TEXT[]),
('Back', 'back_us.mp3', 'verb', 'B1', 'to encourage somebody or give them help; to give financial support to somebody/something', '', 'Her parents backed her in her choice of career.', '', ARRAY[]::TEXT[]),
('Backdrop', 'backdrop_us.mp3', 'noun', 'B1', 'everything that can be seen around an event or scene', '', 'The mountains provided a dramatic backdrop for our picnic.', '', ARRAY[]::TEXT[]),
('Background', 'background_us.mp3', 'noun', 'B1', 'the details of a person’s family, education, experience, etc.', '', 'somebody''s ethnic/genetic/cultural background', '', ARRAY[]::TEXT[]),
('Backing', 'backing_us.mp3', 'noun', 'B1', 'help and support from somebody to do something; financial support for something', '', 'The police gave the proposals their full backing.', '', ARRAY[]::TEXT[]),
('Backup', 'backup_us.mp3', 'noun', 'B1', 'extra help or support that you can get if necessary', '', 'The police had backup from the army.', '', ARRAY[]::TEXT[]),
('Backwards', 'backwards_us.mp3', 'adverb', 'B1', 'towards a place or position that is behind', '', 'I lost my balance and fell backwards.', '', ARRAY[]::TEXT[]),
('Bacteria', 'bacteria_us.mp3', 'noun', 'B1', 'the simplest and smallest forms of life. Bacteria exist in large numbers in air, water and soil, and also in living and dead creatures and plants, and are often a cause of disease.', '', 'Neither chilling nor freezing kills all bacteria.', '', ARRAY[]::TEXT[]),
('Bad', 'bad_us.mp3', 'adjective', 'B1', 'unpleasant; full of problems', '', 'I have some bad news for you, I''m afraid.', '', ARRAY[]::TEXT[]),
('Badge', 'badge_us.mp3', 'noun', 'B1', 'a small piece of metal or plastic, with a design or words on it, that a person wears or carries to show that they belong to an organization, support something, have achieved something, have a particular rank, etc.', '', 'She wore a badge saying ‘Vote for Coates’.', '', ARRAY[]::TEXT[]),
('Badly', 'badly_us.mp3', 'adverb', 'B1', 'without skill or care', '', 'to play/sing badly', '', ARRAY[]::TEXT[]),
('Bag', 'bag_us.mp3', 'noun', 'B1', 'a container made of cloth, leather, plastic or paper, used to carry things in, especially when shopping or travelling', '', 'He was carrying a heavy bag of groceries.', '', ARRAY[]::TEXT[]),
('Bail', 'bail_us.mp3', 'noun', 'B1', 'money that somebody agrees to pay if a person accused of a crime does not appear at their trial. When bail has been arranged, the accused person is allowed to go free until the trial.', '', 'Can anyone put up bail for you?', '', ARRAY[]::TEXT[]),
('Bake', 'bake_us.mp3', 'verb', 'B1', 'to cook food in an oven without extra fat or liquid; to be cooked in this way', '', 'bake (something), to bake bread/biscuits/cookies', '', ARRAY[]::TEXT[]),
('Balance', 'balance_us.mp3', 'noun', 'B1', 'a situation in which different things exist in equal, correct or good amounts', '', 'This newspaper maintains a good balance in its presentation of different opinions.', '', ARRAY[]::TEXT[]),
('Balance', 'balance_us.mp3', 'verb', 'B1', 'to put your body or something else into a position where it is steady and does not fall', '', 'balance on something, How long can you balance on one leg?', '', ARRAY[]::TEXT[]),
('Balanced', 'balanced_us.mp3', 'adjective', 'B1', 'keeping or showing a balance so that different things or different parts of something exist in equal or correct amounts', '', 'The programme presented a balanced view of the two sides of the conflict.', '', ARRAY[]::TEXT[]),
('Ball', 'ball_us.mp3', 'noun', 'B1', 'a round object used for throwing, hitting or kicking in games and sports', '', 'a golf/tennis/bowling/soccer ball', '', ARRAY[]::TEXT[]),
('Ballet', 'ballet_us.mp3', 'noun', 'B1', 'a style of dancing that tells a dramatic story with music but no talking or singing', '', 'She wants to be a ballet dancer.', '', ARRAY[]::TEXT[]),
('Balloon', 'balloon_us.mp3', 'noun', 'B1', 'a small bag made of very thin rubber that becomes larger and rounder when you fill it with air or gas. Balloons are brightly coloured and used as decorations or toys.', '', 'to blow up/burst/pop a balloon', '', ARRAY[]::TEXT[]),
('Ballot', 'ballot_us.mp3', 'noun', 'B1', 'the system of voting in writing and usually in secret; an occasion on which a vote is held', '', 'The chairperson is chosen by secret ballot.', '', ARRAY[]::TEXT[]),
('Ban', 'ban_us.mp3', 'noun', 'B1', 'an official rule that says that something is not allowed', '', 'a smoking ban', '', ARRAY[]::TEXT[]),
('Ban', 'ban_us.mp3', 'verb', 'B1', 'to decide or say officially that something is not allowed', '', 'ban something, The law effectively bans smoking in all public places.', '', ARRAY[]::TEXT[]),
('Banana', 'banana_us.mp3', 'noun', 'B1', 'a long curved fruit with a thick yellow skin and that is soft inside, which grows on trees in hot countries', '', 'a bunch of bananas', '', ARRAY[]::TEXT[]),
('Band', 'band_us.mp3', 'noun', 'B1', 'a small group of musicians who play popular music together, often with a singer or singers', '', 'a rock/punk/jazz band', '', ARRAY[]::TEXT[]),
('Bank', 'bank_us.mp3', 'noun', 'B1', 'an organization that provides various financial services, for example keeping or lending money', '', 'I don''t have much money in the bank at the end of the month.', '', ARRAY[]::TEXT[]),
('Banner', 'banner_us.mp3', 'noun', 'B1', 'a long piece of cloth with a message on it that is carried between two poles or hung in a public place to show support for something', '', 'A huge banner over the street said ‘Welcome home’.', '', ARRAY[]::TEXT[]),
('Bar', 'bar_us.mp3', 'noun', 'B1', 'a place where you can buy and drink alcoholic and other drinks', '', 'We arranged to meet in a bar called the Flamingo.', '', ARRAY[]::TEXT[]),
('Bar', 'bar_us.mp3', 'verb', 'B1', 'to ban or prevent somebody from doing something', '', 'bar somebody from doing something, Prisoners are barred by law from voting in general elections.', '', ARRAY[]::TEXT[]),
('Bare', 'bare_us.mp3', 'adjective', 'B1', 'not covered by any clothes', '', 'She likes to walk around in bare feet.', '', ARRAY[]::TEXT[]),
('Barely', 'barely_us.mp3', 'adverb', 'B1', 'in a way that is just possible but only with difficulty', '', 'He could barely read and write.', '', ARRAY[]::TEXT[]),
('Bargain', 'bargain_us.mp3', 'noun', 'B1', 'a thing bought for less than the usual price', '', 'I picked up a few good bargains in the sale.', '', ARRAY[]::TEXT[]),
('Barrel', 'barrel_us.mp3', 'noun', 'B1', 'a large round container, usually made of wood or metal, with flat ends and, usually, curved sides', '', 'a beer/wine barrel', '', ARRAY[]::TEXT[]),
('Barrier', 'barrier_us.mp3', 'noun', 'B1', 'an object like a fence that prevents people from moving forward from one place to another', '', 'The crowd had to stand behind barriers.', '', ARRAY[]::TEXT[]),
('Base', 'base_us.mp3', 'noun', 'B1', 'the lowest part of something, especially the part or surface on which it rests or stands', '', 'The lamp has a heavy base.', '', ARRAY[]::TEXT[]),
('Base', 'base_us.mp3', 'verb', 'B1', 'to use a particular city, town, etc. as the main place for a business, holiday, etc.', '', 'be based in… , The organization is now based in Geneva.', '', ARRAY[]::TEXT[]),
('Baseball', 'baseball_us.mp3', 'noun', 'B1', 'a game played especially in the US by two teams of nine players, using a bat and ball. Each player tries to hit the ball and then run around four bases before the other team can return the ball.', '', 'a baseball bat/team/cap/fan/player/game', '', ARRAY[]::TEXT[]),
('Based', 'based_us.mp3', 'adjective', 'B1', 'if one thing is based on another, it uses it or is developed from it', '', 'The movie is based on a real-life incident.', '', ARRAY[]::TEXT[]),
('Basement', 'basement_us.mp3', 'noun', 'B1', 'a room or rooms in a building, partly or completely below the level of the ground', '', 'Kitchen goods are sold in the basement.', '', ARRAY[]::TEXT[]),
('Basic', 'basic_us.mp3', 'adjective', 'B1', 'forming the part of something that is most necessary and from which other things develop', '', 'basic information/facts/ideas', '', ARRAY[]::TEXT[]),
('Basically', 'basically_us.mp3', 'adverb', 'B1', 'in the most important ways, without considering things that are less important', '', 'I think we are basically saying the same thing.', '', ARRAY[]::TEXT[]),
('Basis', 'basis_us.mp3', 'noun', 'B1', 'the way things are organized or arranged; how often something happens', '', 'We are in contact on a regular basis.', '', ARRAY[]::TEXT[]),
('Basket', 'basket_us.mp3', 'noun', 'B1', 'a container for holding or carrying things. Baskets are made of long thin pieces of material that bends and twists easily, for example plastic, wire or wicker.', '', 'a shopping basket', '', ARRAY[]::TEXT[]),
('Basketball', 'basketball_us.mp3', 'noun', 'B1', 'a game played by two teams of five players, using a large ball which players try to throw into a high net hanging from a ring', '', 'a basketball game/coach/team/player', '', ARRAY[]::TEXT[]),
('Bass', 'bass_us.mp3', 'noun', 'B1', 'the lowest tone or part in music, for instruments or voices', '', 'He always plays his stereo with the bass turned right up.', '', ARRAY[]::TEXT[]),
('Bat', 'bat_us.mp3', 'noun', 'B1', 'a piece of wood with a handle, made in various shapes and sizes, and used for hitting the ball in games such as baseball, cricket and table tennis', '', 'a baseball/cricket bat', '', ARRAY[]::TEXT[]),
('Bat', 'bat_us.mp3', 'verb', 'B1', 'to hit a ball with a bat, especially in a game of baseball or cricket', '', 'He bats very well.', '', ARRAY[]::TEXT[]),
('Bath', 'bath_us.mp3', 'noun', 'B1', 'a large, long container that you put water in and then get into to wash your whole body', '', 'I''m in the bath!', '', ARRAY[]::TEXT[]),
('Bathroom', 'bathroom_us.mp3', 'noun', 'B1', 'a room in which there is a bath, a washbasin and often a toilet', '', 'Go and wash your hands in the bathroom.', '', ARRAY[]::TEXT[]),
('Battery', 'battery_us.mp3', 'noun', 'B1', 'a device that is placed inside a car engine, clock, radio, etc. and that produces the electricity that makes it work', '', 'to replace the batteries', '', ARRAY[]::TEXT[]),
('Battle', 'battle_us.mp3', 'noun', 'B1', 'a fight between armies, ships or planes, especially during a war; a violent fight between groups of people', '', 'Napoleon was defeated at the Battle of Waterloo.', '', ARRAY[]::TEXT[]),
('Battle', 'battle_us.mp3', 'verb', 'B1', 'to try very hard to achieve something difficult or to deal with something unpleasant or dangerous', '', 'Both teams battled hard.', '', ARRAY[]::TEXT[]),
('Battlefield', 'battlefield_us.mp3', 'noun', 'B1', 'a place where a battle is being fought or has been fought', '', 'heavy casualties on the battlefield', '', ARRAY[]::TEXT[]),
('Bay', 'bay_us.mp3', 'noun', 'B1', 'a part of the sea, or of a large lake, partly surrounded by a wide curve of the land', '', 'the Bay of Bengal', '', ARRAY[]::TEXT[]),
('Be', 'be_us.mp3', 'verb', 'B1', 'used when you are naming people or things, describing them or giving more information about them', '', '+ noun, Today is Monday.', '', ARRAY[]::TEXT[]),
('Be', 'be_us.mp3', 'auxiliary verb', 'B1', 'used with a present participle to form progressive tenses', '', 'I am studying Chinese.', '', ARRAY[]::TEXT[]),
('Beach', 'beach_us.mp3', 'noun', 'B1', 'an area of sand or small stones (called shingle), next to the sea or a lake', '', 'on the beach, tourists sunbathing on the beach', '', ARRAY[]::TEXT[]),
('Beam', 'beam_us.mp3', 'noun', 'B1', 'a line of light, electromagnetic waves or particles', '', 'narrow beams of light/sunlight', '', ARRAY[]::TEXT[]),
('Bean', 'bean_us.mp3', 'noun', 'B1', 'a seed, or pod containing seeds, of a climbing plant, eaten as a vegetable. There are several types of bean and the plants that they grow on are also called beans.', '', 'green beans', '', ARRAY[]::TEXT[]),
('Bear', 'bear_us.mp3', 'noun', 'B1', 'a heavy wild animal with thick fur and sharp claws (= pointed parts on the ends of its feet). There are many types of bear.', '', 'a black bear', '', ARRAY[]::TEXT[]),
('Bear', 'bear_us.mp3', 'verb', 'B1', 'to be able to accept and deal with something unpleasant', '', 'bear something, The pain was almost more than he could bear.', '', ARRAY[]::TEXT[]),
('Beast', 'beast_us.mp3', 'noun', 'B1', 'an animal, especially one that is large or dangerous, or one that is unusual', '', 'wild/savage/ferocious beasts', '', ARRAY[]::TEXT[]),
('Beat', 'beat_us.mp3', 'noun', 'B1', 'a single hit to something, such as a drum, or a movement of something, such as your heart; the sound that this makes', '', 'several loud beats on the drum', '', ARRAY[]::TEXT[]),
('Beat', 'beat_us.mp3', 'verb', 'B1', 'to defeat somebody in a game or competition', '', 'beat somebody at something, He beat me at chess.', '', ARRAY[]::TEXT[]),
('Beautiful', 'beautiful_us.mp3', 'adjective', 'B1', 'having beauty; giving pleasure to the senses or to the mind', '', 'a beautiful woman/girl', '', ARRAY[]::TEXT[]),
('Beauty', 'beauty_us.mp3', 'noun', 'B1', 'the quality of giving pleasure to the senses or to the mind', '', 'beauty of something, the beauty of the sunset/of poetry/of his singing', '', ARRAY[]::TEXT[]),
('Because', 'because_us.mp3', 'conjunction', 'B1', 'for the reason that', '', 'I did it because he told me to.', '', ARRAY[]::TEXT[]),
('Become', 'become_us.mp3', 'verb', 'B1', 'to start to be something', '', '+ adj., It soon became apparent that no one was going to come.', '', ARRAY[]::TEXT[]),
('Bed', 'bed_us.mp3', 'noun', 'B1', 'a piece of furniture for sleeping on', '', 'a single/double bed', '', ARRAY[]::TEXT[]),
('Bedroom', 'bedroom_us.mp3', 'noun', 'B1', 'a room for sleeping in', '', 'the spare/guest bedroom', '', ARRAY[]::TEXT[]),
('Bee', 'bee_us.mp3', 'noun', 'B1', 'a black and yellow flying insect that can sting (= touch your skin and make you feel a sharp pain).Bees live in large groups and make honey (= a sweet sticky substance that is good to eat).', '', 'Bees were buzzing in the clover.', '', ARRAY[]::TEXT[]),
('Beef', 'beef_us.mp3', 'noun', 'B1', 'meat that comes from a cow', '', 'roast beef', '', ARRAY[]::TEXT[]),
('Beer', 'beer_us.mp3', 'noun', 'B1', 'an alcoholic drink made from malt with hops added to give it taste. There are many types of beer.', '', 'a pint/can/bottle of beer', '', ARRAY[]::TEXT[]),
('Before', 'before_us.mp3', 'adverb', 'B1', 'at an earlier time; in the past; already', '', 'You should have told me so before.', '', ARRAY[]::TEXT[]),
('Before', 'before_us.mp3', 'conjunction', 'B1', 'earlier than the time when', '', 'Do it before you forget.', '', ARRAY[]::TEXT[]),
('Before', 'before_us.mp3', 'preposition', 'B1', 'earlier than somebody/something', '', 'before lunch', '', ARRAY[]::TEXT[]),
('Beg', 'beg_us.mp3', 'verb', 'B1', 'to ask somebody for something especially in an anxious way because you want or need it very much', '', 'Now you have to beg and plead.', '', ARRAY[]::TEXT[]),
('Begin', 'begin_us.mp3', 'verb', 'B1', 'to start doing something; to do the first part of something', '', 'Shall I begin?', '', ARRAY[]::TEXT[]),
('Beginning', 'beginning_us.mp3', 'noun', 'B1', 'the time when something starts; the first part of an event, a story, etc.', '', 'A story has to have a beginning, middle, and end.', '', ARRAY[]::TEXT[]),
('Behalf', 'behalf_us.mp3', 'noun', 'B1', 'in order to help somebody', '', 'He began a petition in behalf of the farmers.', '', ARRAY[]::TEXT[]),
('Behave', 'behave_us.mp3', 'verb', 'B1', 'to do things in a particular way', '', 'The doctor behaved very unprofessionally.', '', ARRAY[]::TEXT[]),
('Behaviour', 'behaviour_us.mp3', 'noun', 'B1', 'the way that somebody behaves, especially towards other people', '', 'good/bad behaviour', '', ARRAY[]::TEXT[]),
('Behind', 'behind_us.mp3', 'adverb', 'B1', 'at or towards the back of somebody/something; further back', '', 'She rode off down the road with the dog running behind.', '', ARRAY[]::TEXT[]),
('Behind', 'behind_us.mp3', 'preposition', 'B1', 'at or towards the back of somebody/something, and often hidden by it or them', '', 'Who''s the girl standing behind Jan?', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
