INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Preserve', 'preserve_us.mp3', 'verb', 'B1', 'to keep a particular quality, feature, etc.; to make sure that something is kept', '', 'He was anxious to preserve his reputation.', '', ARRAY[]::TEXT[]),
('Preside', 'preside_us.mp3', 'verb', 'B1', 'to lead or be in charge of a meeting, ceremony, etc.', '', 'the presiding judge', '', ARRAY[]::TEXT[]),
('Presidency', 'presidency_us.mp3', 'noun', 'B1', 'the job of being president of a country or an organization; the period of time somebody holds this job', '', 'the current holder of the EU presidency', '', ARRAY[]::TEXT[]),
('President', 'president_us.mp3', 'noun', 'B1', 'the leader of a republic, for example the US', '', 'Several presidents attended the funeral.', '', ARRAY[]::TEXT[]),
('Presidential', 'presidential_us.mp3', 'adjective', 'B1', 'connected with the position or activities of a president', '', 'a presidential campaign/candidate/election', '', ARRAY[]::TEXT[]),
('Press', 'press_us.mp3', 'noun', 'B1', 'newspapers and magazines', '', 'the local/national/foreign press', '', ARRAY[]::TEXT[]),
('Press', 'press_us.mp3', 'verb', 'B1', 'to push part of a device, etc. in order to make it work', '', 'press something, to press a button/key', '', ARRAY[]::TEXT[]),
('Pressure', 'pressure_us.mp3', 'noun', 'B1', 'the act of trying to persuade or to force somebody to do something', '', 'pressure for something, The pressure for change continued to mount.', '', ARRAY[]::TEXT[]),
('Prestigious', 'prestigious_us.mp3', 'adjective', 'B1', 'respected and admired as very important or of very high quality', '', 'a prestigious award', '', ARRAY[]::TEXT[]),
('Presumably', 'presumably_us.mp3', 'adverb', 'B1', 'used to say that you think that something is probably true', '', 'Presumably this is where the accident happened.', '', ARRAY[]::TEXT[]),
('Presume', 'presume_us.mp3', 'verb', 'B1', 'to suppose that something is true, although you do not have actual proof', '', 'They are very expensive, I presume?', '', ARRAY[]::TEXT[]),
('Pretend', 'pretend_us.mp3', 'verb', 'B1', 'to behave in a particular way, in order to make other people believe something that is not true', '', 'I''m tired of having to pretend all the time.', '', ARRAY[]::TEXT[]),
('Pretty', 'pretty_us.mp3', 'adjective', 'B1', 'attractive without being very beautiful', '', 'a pretty face', '', ARRAY[]::TEXT[]),
('Pretty', 'pretty_us.mp3', 'adverb', 'B1', 'to some extent; fairly', '', 'The game was pretty good.', '', ARRAY[]::TEXT[]),
('Prevail', 'prevail_us.mp3', 'verb', 'B1', 'to exist or be very common at a particular time or in a particular place', '', 'prevail in something, We were horrified at the conditions prevailing in local prisons.', '', ARRAY[]::TEXT[]),
('Prevalence', 'prevalence_us.mp3', 'noun', 'B1', 'the fact of existing or being very common at a particular time or in a particular place', '', 'an increase in the prevalence of smoking among young people', '', ARRAY[]::TEXT[]),
('Prevent', 'prevent_us.mp3', 'verb', 'B1', 'to stop somebody from doing something; to stop something from happening', '', 'prevent something/somebody, The accident could have been prevented.', '', ARRAY[]::TEXT[]),
('Prevention', 'prevention_us.mp3', 'noun', 'B1', 'the act of stopping something bad from happening', '', 'accident/crime prevention', '', ARRAY[]::TEXT[]),
('Previous', 'previous_us.mp3', 'adjective', 'B1', 'happening or existing before the event or object that you are talking about', '', 'No previous experience is necessary for this job.', '', ARRAY[]::TEXT[]),
('Previously', 'previously_us.mp3', 'adverb', 'B1', 'at a time before the time that you are talking about', '', 'The building had previously been used as a hotel.', '', ARRAY[]::TEXT[]),
('Prey', 'prey_us.mp3', 'noun', 'B1', 'an animal, a bird, etc. that is hunted, killed and eaten by another', '', 'The lion will often stalk its prey for hours.', '', ARRAY[]::TEXT[]),
('Price', 'price_us.mp3', 'noun', 'B1', 'the amount of money that you have to pay for something', '', 'Boat for sale, price £8 000', '', ARRAY[]::TEXT[]),
('Price', 'price_us.mp3', 'verb', 'B1', 'to fix the price of something at a particular level', '', 'be priced + adv./prep., The main courses are all reasonably priced.', '', ARRAY[]::TEXT[]),
('Pride', 'pride_us.mp3', 'noun', 'B1', 'a feeling of being pleased or satisfied that you get when you or people who are connected with you have done something well or own something that other people admire', '', 'The sight of her son graduating filled her with pride.', '', ARRAY[]::TEXT[]),
('Priest', 'priest_us.mp3', 'noun', 'B1', 'a person who is qualified to perform religious duties and ceremonies in the Roman Catholic, Anglican and Orthodox Churches', '', 'a parish priest', '', ARRAY[]::TEXT[]),
('Primarily', 'primarily_us.mp3', 'adverb', 'B1', 'mainly', '', 'a course designed primarily for specialists', '', ARRAY[]::TEXT[]),
('Primary', 'primary_us.mp3', 'adjective', 'B1', 'connected with the education of children between the ages of about five and eleven', '', 'primary teachers', '', ARRAY[]::TEXT[]),
('Prime', 'prime_us.mp3', 'adjective', 'B1', 'main; most important; basic', '', 'My prime concern is to protect my property.', '', ARRAY[]::TEXT[]),
('Prince', 'prince_us.mp3', 'noun', 'B1', 'a male member of a royal family who is not king, especially the son or grandson of the king or queen', '', 'the royal princes', '', ARRAY[]::TEXT[]),
('Princess', 'princess_us.mp3', 'noun', 'B1', 'a female member of a royal family who is not a queen, especially the daughter or granddaughter of the king or queen', '', 'the royal princesses', '', ARRAY[]::TEXT[]),
('Principal', 'principal_us.mp3', 'adjective', 'B1', 'most important; main', '', 'The principal reason for this omission is lack of time.', '', ARRAY[]::TEXT[]),
('Principal', 'principal_us.mp3', 'noun', 'B1', 'the person who is in charge of a college or (in Scotland and Canada) a university', '', 'Peter Brown, principal of St John’s College', '', ARRAY[]::TEXT[]),
('Principle', 'principle_us.mp3', 'noun', 'B1', 'a moral rule or a strong belief that influences your actions', '', 'He has high moral principles.', '', ARRAY[]::TEXT[]),
('Print', 'print_us.mp3', 'noun', 'B1', 'letters, words, numbers, etc. that have been printed onto paper', '', 'The tiny print was hard to read without my glasses.', '', ARRAY[]::TEXT[]),
('Print', 'print_us.mp3', 'verb', 'B1', 'to produce letters, pictures, etc. on paper using a machine that puts ink (= coloured liquid) on the surface', '', 'print (something), I''m printing a copy of the document for you.', '', ARRAY[]::TEXT[]),
('Printer', 'printer_us.mp3', 'noun', 'B1', 'a machine for printing text on paper, especially one connected to a computer', '', 'a colour printer', '', ARRAY[]::TEXT[]),
('Printing', 'printing_us.mp3', 'noun', 'B1', 'the act of producing letters, pictures, patterns, etc. on something by pressing a surface covered with ink (= coloured liquid for printing, drawing, etc.) against it', '', 'the invention of printing', '', ARRAY[]::TEXT[]),
('Prior', 'prior_us.mp3', 'adjective', 'B1', 'happening or existing before something else or before a particular time', '', 'Although not essential, some prior knowledge of statistics is desirable.', '', ARRAY[]::TEXT[]),
('Priority', 'priority_us.mp3', 'noun', 'B1', 'something that you think is more important than other things and should be dealt with first', '', 'a high/low priority', '', ARRAY[]::TEXT[]),
('Prison', 'prison_us.mp3', 'noun', 'B1', 'a building where people are kept as a punishment for a crime they have committed, or while they are waiting for trial', '', 'She went to prison for tax evasion.', '', ARRAY[]::TEXT[]),
('Prisoner', 'prisoner_us.mp3', 'noun', 'B1', 'a person who is kept in prison as a punishment, or while they are waiting for trial', '', 'The number of prisoners serving life sentences has fallen.', '', ARRAY[]::TEXT[]),
('Privacy', 'privacy_us.mp3', 'noun', 'B1', 'the state of being alone and not watched or interrupted by other people', '', 'She was longing for some peace and privacy.', '', ARRAY[]::TEXT[]),
('Private', 'private_us.mp3', 'adjective', 'B1', 'belonging to or for the use of a particular person or group; not for public use', '', 'The sign said, ‘Private property. Keep out.’', '', ARRAY[]::TEXT[]),
('Privatization', 'privatization_us.mp3', 'noun', 'B1', 'the act of selling a business or an industry so that it is no longer owned by the government', '', 'There were fears that privatization would lead to job losses.', '', ARRAY[]::TEXT[]),
('Privilege', 'privilege_us.mp3', 'noun', 'B1', 'a special right or advantage that a particular person or group of people has', '', 'Education should be a universal right and not a privilege.', '', ARRAY[]::TEXT[]),
('Prize', 'prize_us.mp3', 'noun', 'B1', 'an award that is given to a person who wins a competition, race, etc. or who does very good work', '', 'She was awarded the Nobel Peace Prize.', '', ARRAY[]::TEXT[]),
('Probability', 'probability_us.mp3', 'noun', 'B1', 'how likely something is to happen', '', 'The probability is that prices will rise rapidly.', '', ARRAY[]::TEXT[]),
('Probable', 'probable_us.mp3', 'adjective', 'B1', 'likely to happen, to exist or to be true', '', 'the probable cause/explanation/outcome', '', ARRAY[]::TEXT[]),
('Probably', 'probably_us.mp3', 'adverb', 'B1', 'used to say that something is likely to happen or to be true', '', 'You''re probably right.', '', ARRAY[]::TEXT[]),
('Probe', 'probe_us.mp3', 'noun', 'B1', 'a complete and careful investigation of something', '', 'a police probe into the financial affairs of the company', '', ARRAY[]::TEXT[]),
('Probe', 'probe_us.mp3', 'verb', 'B1', 'to ask questions in order to find out secret or hidden information about somebody/something', '', 'probe (into something), He didn''t like the media probing into his past.', '', ARRAY[]::TEXT[]),
('Problem', 'problem_us.mp3', 'noun', 'B1', 'a thing that is difficult to deal with or to understand', '', 'big/serious/major problems', '', ARRAY[]::TEXT[]),
('Problematic', 'problematic_us.mp3', 'adjective', 'B1', 'difficult to deal with or to understand; full of problems; not certain to be successful', '', 'The situation is more problematic than we first thought.', '', ARRAY[]::TEXT[]),
('Procedure', 'procedure_us.mp3', 'noun', 'B1', 'a way of doing something, especially the usual or correct way', '', 'emergency/safety/disciplinary procedures', '', ARRAY[]::TEXT[]),
('Proceed', 'proceed_us.mp3', 'verb', 'B1', 'to continue doing something that has already been started; to continue being done', '', 'We''re not sure whether we still want to proceed with the sale.', '', ARRAY[]::TEXT[]),
('Proceeding', 'proceeding_us.mp3', 'noun', 'B1', 'the process of using a court to settle an argument or to deal with a complaint', '', 'court/legal/judicial proceedings', '', ARRAY[]::TEXT[]),
('Proceeds', 'proceeds_us.mp3', 'noun', 'B1', 'the money that you receive when you sell something or organize a performance, etc.; profits', '', 'She sold her car and bought a piano with the proceeds.', '', ARRAY[]::TEXT[]),
('Process', 'process_us.mp3', 'noun', 'B1', 'a series of things that are done in order to achieve a particular result', '', 'the consultation/planning process', '', ARRAY[]::TEXT[]),
('Processing', 'processing_us.mp3', 'noun', 'B1', 'the treatment of raw material, food, etc. in order to change it, preserve it, etc.', '', 'the food processing industry', '', ARRAY[]::TEXT[]),
('Processor', 'processor_us.mp3', 'noun', 'B1', 'a machine, person or company that processes things', '', 'The company is Ireland''s largest dairy processor.', '', ARRAY[]::TEXT[]),
('Proclaim', 'proclaim_us.mp3', 'verb', 'B1', 'to publicly and officially tell people about something important', '', 'proclaim something, The president proclaimed a state of emergency.', '', ARRAY[]::TEXT[]),
('Produce', 'produce_us.mp3', 'noun', 'B1', 'things that have been made or grown, especially things connected with farming', '', 'The market is full of farm produce.', '', ARRAY[]::TEXT[]),
('Produce', 'produce_us.mp3', 'verb', 'B1', 'to make things to be sold, especially in large quantities', '', 'Our company mainly produces goods for export.', '', ARRAY[]::TEXT[]),
('Producer', 'producer_us.mp3', 'noun', 'B1', 'a person, a company or a country that grows or makes food, goods or materials', '', 'French wine producers', '', ARRAY[]::TEXT[]),
('Product', 'product_us.mp3', 'noun', 'B1', 'a thing that is grown, produced or created, usually for sale', '', 'food/agricultural/software products', '', ARRAY[]::TEXT[]),
('Production', 'production_us.mp3', 'noun', 'B1', 'the process of growing or making food, goods or materials, especially large quantities', '', 'food/oil production', '', ARRAY[]::TEXT[]),
('Productive', 'productive_us.mp3', 'adjective', 'B1', 'making goods or growing crops, especially in large quantities', '', 'highly productive farming land', '', ARRAY[]::TEXT[]),
('Productivity', 'productivity_us.mp3', 'noun', 'B1', 'the rate at which a worker, a company or a country produces goods, and the amount produced, compared with how much time, work and money is needed to produce them', '', 'high/improved/increased productivity', '', ARRAY[]::TEXT[]),
('Profession', 'profession_us.mp3', 'noun', 'B1', 'a type of job that needs special training or skill, especially one that needs a high level of education', '', 'the medical/legal/teaching profession', '', ARRAY[]::TEXT[]),
('Professional', 'professional_us.mp3', 'adjective', 'B1', 'doing something as a paid job rather than as a hobby', '', 'professional athletes/players', '', ARRAY[]::TEXT[]),
('Professional', 'professional_us.mp3', 'noun', 'B1', 'a person who does a job that needs special training and a high level of education', '', 'You need a professional to sort out your finances.', '', ARRAY[]::TEXT[]),
('Professor', 'professor_us.mp3', 'noun', 'B1', 'a university teacher of the highest rank', '', 'Professor (Ann) Williams', '', ARRAY[]::TEXT[]),
('Profile', 'profile_us.mp3', 'noun', 'B1', 'a description of somebody/something that gives useful information', '', 'We first build up a detailed profile of our customers and their requirements.', '', ARRAY[]::TEXT[]),
('Profit', 'profit_us.mp3', 'noun', 'B1', 'the money that you make in business or by selling things, especially after paying the costs involved', '', 'annual/pre-tax/corporate profits', '', ARRAY[]::TEXT[]),
('Profitable', 'profitable_us.mp3', 'adjective', 'B1', 'that makes or is likely to make money', '', 'a highly profitable business', '', ARRAY[]::TEXT[]),
('Profound', 'profound_us.mp3', 'adjective', 'B1', 'very great; felt or experienced very strongly', '', 'profound changes in the earth’s climate', '', ARRAY[]::TEXT[]),
('Program', 'program_us.mp3', 'noun', 'B1', 'a set of instructions in code that control the operations or functions of a computer', '', 'You''ll need to download and install the program on your computer.', '', ARRAY[]::TEXT[]),
('Program', 'program_us.mp3', 'verb', 'B1', 'to give a computer, etc. a set of instructions to make it perform a particular task', '', 'In this class, students will learn how to program.', '', ARRAY[]::TEXT[]),
('Programme', 'programme_us.mp3', 'noun', 'B1', 'something that people watch on television or listen to on the radio', '', 'a news programme', '', ARRAY[]::TEXT[]),
('Programming', 'programming_us.mp3', 'noun', 'B1', 'the process of writing and testing computer programs', '', 'programming languages', '', ARRAY[]::TEXT[]),
('Progress', 'progress_us.mp3', 'noun', 'B1', 'the process of improving or developing, or of getting nearer to achieving or completing something', '', 'I think we''re making progress.', '', ARRAY[]::TEXT[]),
('Progress', 'progress_us.mp3', 'verb', 'B1', 'to improve or develop over a period of time; to make progress', '', 'The course allows students to progress at their own speed.', '', ARRAY[]::TEXT[]),
('Progressive', 'progressive_us.mp3', 'adjective', 'B1', 'in favour of new ideas, modern methods and change', '', 'progressive schools', '', ARRAY[]::TEXT[]),
('Prohibit', 'prohibit_us.mp3', 'verb', 'B1', 'to stop something from being done or used especially by law', '', 'prohibit something, a law prohibiting the sale of alcohol', '', ARRAY[]::TEXT[]),
('Project', 'project_us.mp3', 'noun', 'B1', 'a piece of work involving careful study of a subject over a period of time, done by school or college students', '', 'a history project', '', ARRAY[]::TEXT[]),
('Project', 'project_us.mp3', 'verb', 'B1', 'to estimate what the size, cost or amount of something will be in the future based on what is happening now', '', 'be projected, A growth rate of 4 per cent is projected for next year.', '', ARRAY[]::TEXT[]),
('Projection', 'projection_us.mp3', 'noun', 'B1', 'an estimate or a statement of what figures, amounts, or events will be in the future, or what they were in the past, based on what is happening now', '', 'to make forward/backward projections of population figures', '', ARRAY[]::TEXT[]),
('Prominent', 'prominent_us.mp3', 'adjective', 'B1', 'important or well known', '', 'a prominent politician', '', ARRAY[]::TEXT[]),
('Promise', 'promise_us.mp3', 'noun', 'B1', 'a statement that tells somebody that you will definitely do or not do something', '', 'to make/keep/fulfil/break a promise', '', ARRAY[]::TEXT[]),
('Promise', 'promise_us.mp3', 'verb', 'B1', 'to tell somebody that you will definitely do or not do something, or that something will definitely happen', '', '‘We haven''t got time to go to the park.’ ‘But you promised!’', '', ARRAY[]::TEXT[]),
('Promising', 'promising_us.mp3', 'adjective', 'B1', 'showing signs of being good or successful', '', 'He was voted the most promising new actor for his part in the movie.', '', ARRAY[]::TEXT[]),
('Promote', 'promote_us.mp3', 'verb', 'B1', 'to help sell a product, service, etc. or make it more popular by advertising it or offering it at a special price', '', 'promote something, The band has gone on tour to promote their new album.', '', ARRAY[]::TEXT[]),
('Promotion', 'promotion_us.mp3', 'noun', 'B1', 'a move to a more important job or rank in a company or an organization', '', 'The new job is a promotion for him.', '', ARRAY[]::TEXT[]),
('Prompt', 'prompt_us.mp3', 'verb', 'B1', 'to make somebody decide to do something; to cause something to happen', '', 'prompt something, The discovery of the bomb prompted an increase in security.', '', ARRAY[]::TEXT[]),
('Pronounce', 'pronounce_us.mp3', 'verb', 'B1', 'to make the sound of a word or letter in a particular way', '', 'to pronounce a word/syllable/vowel/consonant', '', ARRAY[]::TEXT[]),
('Pronounced', 'pronounced_us.mp3', 'adjective', 'B1', 'very obvious, easy to notice or strongly expressed', '', 'He walked with a pronounced limp.', '', ARRAY[]::TEXT[]),
('Proof', 'proof_us.mp3', 'noun', 'B1', 'information, documents, etc. that show that something is true', '', 'conclusive/definitive/scientific proof', '', ARRAY[]::TEXT[]),
('Propaganda', 'propaganda_us.mp3', 'noun', 'B1', 'ideas or statements that may be false or present only one side of an argument that are used in order to gain support for a political leader, party, etc.', '', 'enemy propaganda', '', ARRAY[]::TEXT[]),
('Proper', 'proper_us.mp3', 'adjective', 'B1', 'right, appropriate or correct; according to the rules', '', 'We should have had a proper discussion before voting.', '', ARRAY[]::TEXT[]),
('Properly', 'properly_us.mp3', 'adverb', 'B1', 'in a way that is correct and/or appropriate', '', 'How much money do we need to do the job properly?', '', ARRAY[]::TEXT[]),
('Property', 'property_us.mp3', 'noun', 'B1', 'a thing or things that are owned by somebody; a possession or possessions', '', 'personal/stolen property', '', ARRAY[]::TEXT[]),
('Proportion', 'proportion_us.mp3', 'noun', 'B1', 'a part or share of a whole', '', 'Water covers a large proportion of the earth''s surface.', '', ARRAY[]::TEXT[]),
('Proposal', 'proposal_us.mp3', 'noun', 'B1', 'a formal suggestion or plan; the act of making a suggestion', '', 'to submit/present/put forward a proposal', '', ARRAY[]::TEXT[]),
('Propose', 'propose_us.mp3', 'verb', 'B1', 'to suggest a plan, an idea, etc. for people to think about and decide on', '', 'propose something, The government proposed changes to the voting system.', '', ARRAY[]::TEXT[]),
('Proposition', 'proposition_us.mp3', 'noun', 'B1', 'an idea or a plan of action that is suggested, especially in business', '', 'I''d like to put a business proposition to you.', '', ARRAY[]::TEXT[]),
('Prosecute', 'prosecute_us.mp3', 'verb', 'B1', 'to officially charge somebody with a crime in court', '', 'The police decided not to prosecute.', '', ARRAY[]::TEXT[]),
('Prosecution', 'prosecution_us.mp3', 'noun', 'B1', 'the process of trying to prove in court that somebody is guilty of a crime (= of prosecuting them); the process of being officially charged with a crime in court', '', 'Prosecution for a first minor offence rarely leads to imprisonment.', '', ARRAY[]::TEXT[]),
('Prosecutor', 'prosecutor_us.mp3', 'noun', 'B1', 'a public official who charges somebody officially with a crime and prosecutes them in court', '', 'the public/state prosecutor', '', ARRAY[]::TEXT[]),
('Prospect', 'prospect_us.mp3', 'noun', 'B1', 'the possibility that something will happen', '', 'prospect of something, There is no immediate prospect of peace.', '', ARRAY[]::TEXT[]),
('Prospective', 'prospective_us.mp3', 'adjective', 'B1', 'expected to do something or to become something', '', 'a prospective buyer', '', ARRAY[]::TEXT[]),
('Prosperity', 'prosperity_us.mp3', 'noun', 'B1', 'the state of being successful, especially in making money', '', 'Our future prosperity depends on economic growth.', '', ARRAY[]::TEXT[]),
('Protect', 'protect_us.mp3', 'verb', 'B1', 'to make sure that somebody/something is not harmed, injured, damaged, etc.', '', 'protect somebody/something/yourself, to protect children/citizens/civilians/consumers/workers', '', ARRAY[]::TEXT[]),
('Protection', 'protection_us.mp3', 'noun', 'B1', 'the act of protecting somebody/something; the state of being protected', '', 'protection against something, Wear clothes that provide adequate protection against the wind and rain.', '', ARRAY[]::TEXT[]),
('Protective', 'protective_us.mp3', 'adjective', 'B1', 'providing or intended to provide protection', '', 'Workers should wear full protective clothing.', '', ARRAY[]::TEXT[]),
('Protein', 'protein_us.mp3', 'noun', 'B1', 'a substance, found within all living things, that forms the structure of muscles, organs, etc. There are many different proteins and they are an essential part of what humans and animals eat to help them grow and stay healthy.', '', 'essential proteins and vitamins', '', ARRAY[]::TEXT[]),
('Protest', 'protest_us.mp3', 'noun', 'B1', 'the expression of strong dislike of or opposition to something; a statement or an action that shows this', '', 'to hold/organize/join a protest', '', ARRAY[]::TEXT[]),
('Protest', 'protest_us.mp3', 'verb', 'B1', 'to say or do something to show that you disagree with something or think it is bad, especially publicly', '', 'There''s no use protesting, I won''t change my mind.', '', ARRAY[]::TEXT[]),
('Protester', 'protester_us.mp3', 'noun', 'B1', 'a person who makes a public protest', '', 'Thousands of protesters marched through the city.', '', ARRAY[]::TEXT[]),
('Protocol', 'protocol_us.mp3', 'noun', 'B1', 'a system of fixed rules and formal behaviour used at official meetings, usually between governments', '', 'a breach of protocol', '', ARRAY[]::TEXT[]),
('Proud', 'proud_us.mp3', 'adjective', 'B1', 'feeling pleased and satisfied about something that you own or have done, or are connected with', '', 'proud parents', '', ARRAY[]::TEXT[]),
('Prove', 'prove_us.mp3', 'verb', 'B1', 'to use facts, evidence, etc. to show that something is true', '', 'prove something, They hope this new evidence will prove her innocence.', '', ARRAY[]::TEXT[]),
('Provide', 'provide_us.mp3', 'verb', 'B1', 'to give something to somebody or make it available for them to use', '', 'provide something, Please provide the following information.', '', ARRAY[]::TEXT[]),
('Province', 'province_us.mp3', 'noun', 'B1', 'one of the areas that some countries are divided into with its own local government', '', 'the provinces of Canada', '', ARRAY[]::TEXT[]),
('Provincial', 'provincial_us.mp3', 'adjective', 'B1', 'connected with one of the large areas that some countries are divided into, with its own local government', '', 'provincial assemblies/elections', '', ARRAY[]::TEXT[]),
('Provision', 'provision_us.mp3', 'noun', 'B1', 'the act of supplying somebody with something that they need or want; something that is supplied', '', 'housing provision', '', ARRAY[]::TEXT[]),
('Provoke', 'provoke_us.mp3', 'verb', 'B1', 'to cause a particular reaction or have a particular effect', '', 'The announcement provoked a storm of protest.', '', ARRAY[]::TEXT[]),
('Psychiatric', 'psychiatric_us.mp3', 'adjective', 'B1', 'relating to psychiatry or to mental illnesses', '', 'psychiatric disorders', '', ARRAY[]::TEXT[]),
('Psychological', 'psychological_us.mp3', 'adjective', 'B1', 'connected with a person’s mind and the way in which it works', '', 'the psychological development of children', '', ARRAY[]::TEXT[]),
('Psychologist', 'psychologist_us.mp3', 'noun', 'B1', 'a scientist who studies and is trained in psychology', '', 'to see a psychologist', '', ARRAY[]::TEXT[]),
('Psychology', 'psychology_us.mp3', 'noun', 'B1', 'the scientific study of the mind and how it influences behaviour', '', 'clinical/educational/child/sport psychology', '', ARRAY[]::TEXT[]),
('Pub', 'pub_us.mp3', 'noun', 'B1', 'a building where people go to drink and meet their friends. Pubs serve alcoholic and other drinks, and often also food.', '', 'We''re all going to the pub after work.', '', ARRAY[]::TEXT[]),
('Public', 'public_us.mp3', 'adjective', 'B1', 'connected with ordinary people in society in general', '', 'The campaign is designed to increase public awareness of the issues.', '', ARRAY[]::TEXT[]),
('Public', 'public_us.mp3', 'noun', 'B1', 'ordinary people in society in general', '', 'The palace is now open to the public.', '', ARRAY[]::TEXT[]),
('Publication', 'publication_us.mp3', 'noun', 'B1', 'the act of printing a book, a magazine, etc. and making it available to the public; a book, a magazine, etc. that has been published', '', 'specialist publications', '', ARRAY[]::TEXT[]),
('Publicity', 'publicity_us.mp3', 'noun', 'B1', 'the attention that is given to somebody/something by newspapers, television, etc.', '', 'good/bad/adverse publicity', '', ARRAY[]::TEXT[]),
('Publish', 'publish_us.mp3', 'verb', 'B1', 'to produce a book, magazine, CD-ROM, etc. and sell it to the public', '', 'to publish a book/novel/magazine/paper', '', ARRAY[]::TEXT[]),
('Publishing', 'publishing_us.mp3', 'noun', 'B1', 'the profession or business of preparing and printing books, magazines, CD-ROMs, etc. and selling or making them available to the public', '', 'a job in publishing', '', ARRAY[]::TEXT[]),
('Pull', 'pull_us.mp3', 'noun', 'B1', 'an act of trying to make something move by taking hold of it and using force to bring it towards you', '', 'I gave the door a sharp pull and it opened.', '', ARRAY[]::TEXT[]),
('Pull', 'pull_us.mp3', 'verb', 'B1', 'to take hold of something and use force in order to move it or try to move it towards yourself', '', 'You push and I''ll pull.', '', ARRAY[]::TEXT[]),
('Pulse', 'pulse_us.mp3', 'noun', 'B1', 'the regular beat of the heart as it sends blood around the body, that can be felt in different places, especially on the inside part of the wrist; the number of times the heart beats in a minute', '', 'a strong/weak pulse', '', ARRAY[]::TEXT[]),
('Pump', 'pump_us.mp3', 'noun', 'B1', 'a machine that is used to force liquid, gas or air into or out of something', '', '(British English), a petrol pump', '', ARRAY[]::TEXT[]),
('Pump', 'pump_us.mp3', 'verb', 'B1', 'to make water, air, gas, etc. flow in a particular direction by using a pump or something that works like a pump', '', 'pump something (+ adv./prep.), The engine is used for pumping water out of the mine.', '', ARRAY[]::TEXT[]),
('Punch', 'punch_us.mp3', 'noun', 'B1', 'a hard hit made with the fist (= closed hand)', '', 'a punch in the face', '', ARRAY[]::TEXT[]),
('Punch', 'punch_us.mp3', 'verb', 'B1', 'to hit somebody/something hard with your fist (= closed hand)', '', 'punch somebody/something, He was kicked and punched as he lay on the ground.', '', ARRAY[]::TEXT[]),
('Punish', 'punish_us.mp3', 'verb', 'B1', 'to make somebody suffer because they have broken the law or done something wrong', '', 'punish somebody, Those responsible for this crime will be severely punished.', '', ARRAY[]::TEXT[]),
('Punishment', 'punishment_us.mp3', 'noun', 'B1', 'an act or a way of punishing somebody', '', 'to inflict/impose/mete out punishment', '', ARRAY[]::TEXT[]),
('Punk', 'punk_us.mp3', 'noun', 'B1', 'a type of loud and aggressive rock music popular in the late 1970s and early 1980s', '', 'a punk band', '', ARRAY[]::TEXT[]),
('Pupil', 'pupil_us.mp3', 'noun', 'B1', 'a person who is being taught, especially a child in a school', '', 'school pupils', '', ARRAY[]::TEXT[]),
('Purchase', 'purchase_us.mp3', 'noun', 'B1', 'the act or process of buying something', '', 'to make a purchase (= buy something)', '', ARRAY[]::TEXT[]),
('Purchase', 'purchase_us.mp3', 'verb', 'B1', 'to buy something', '', 'purchase something, Please ensure that you purchase your ticket in advance.', '', ARRAY[]::TEXT[]),
('Pure', 'pure_us.mp3', 'adjective', 'B1', 'not mixed with anything else; with nothing added', '', 'pure gold', '', ARRAY[]::TEXT[]),
('Purely', 'purely_us.mp3', 'adverb', 'B1', 'only; completely', '', 'I saw the letter purely by chance.', '', ARRAY[]::TEXT[]),
('Purple', 'purple_us.mp3', 'adjective', 'B1', 'having the colour of blue and red mixed together', '', 'a purple flower/dress', '', ARRAY[]::TEXT[]),
('Purple', 'purple_us.mp3', 'noun', 'B1', 'the colour of blue and red mixed together', '', 'Her hair was dyed a bright shade of purple.', '', ARRAY[]::TEXT[]),
('Purpose', 'purpose_us.mp3', 'noun', 'B1', 'the intention, aim or function of something; the thing that something is supposed to achieve', '', 'Our campaign''s main purpose is to raise money.', '', ARRAY[]::TEXT[]),
('Pursue', 'pursue_us.mp3', 'verb', 'B1', 'to do something or try to achieve something over a period of time', '', 'to pursue a goal', '', ARRAY[]::TEXT[]),
('Pursuit', 'pursuit_us.mp3', 'noun', 'B1', 'the act of looking for or trying to get something', '', 'pursuit of something, the pursuit of happiness/knowledge/profit', '', ARRAY[]::TEXT[]),
('Push', 'push_us.mp3', 'noun', 'B1', 'an act of pushing something/somebody', '', 'She gave him a gentle push.', '', ARRAY[]::TEXT[]),
('Push', 'push_us.mp3', 'verb', 'B1', 'to use your hands, arms or body in order to make somebody/something move forward or away from you; to move part of your body into a particular position', '', 'We pushed and pushed but the piano wouldn''t move.', '', ARRAY[]::TEXT[]),
('Put', 'put_us.mp3', 'verb', 'B1', 'to move something into a particular place or position', '', 'Put the cases down there, please.', '', ARRAY[]::TEXT[]),
('Puzzle', 'puzzle_us.mp3', 'noun', 'B1', 'a game, etc. that you have to think about carefully in order to answer it or do it', '', 'a crossword puzzle', '', ARRAY[]::TEXT[]),
('Qualification', 'qualification_us.mp3', 'noun', 'B1', 'an exam that you have passed or a course of study that you have successfully completed', '', 'academic/educational/professional/vocational qualifications', '', ARRAY[]::TEXT[]),
('Qualified', 'qualified_us.mp3', 'adjective', 'B1', 'having passed the exams or completed the training that are necessary in order to do a particular job; having the experience to do a particular job', '', 'a qualified teacher', '', ARRAY[]::TEXT[]),
('Qualify', 'qualify_us.mp3', 'verb', 'B1', 'to reach the standard of ability or knowledge needed to do a particular job, for example by completing a course of study or passing exams', '', 'How long does it take to qualify?', '', ARRAY[]::TEXT[]),
('Quality', 'quality_us.mp3', 'noun', 'B1', 'the standard of something when it is compared to other things like it; how good or bad something is', '', 'Improving the quality of care for nursing home residents is a priority.', '', ARRAY[]::TEXT[]),
('Quantity', 'quantity_us.mp3', 'noun', 'B1', 'an amount or a number of something', '', 'quantity of something, a large/small quantity of something', '', ARRAY[]::TEXT[]),
('Quarter', 'quarter_us.mp3', 'noun', 'B1', 'one of four equal parts of something', '', 'quarter of something, a quarter of an hour/a century', '', ARRAY[]::TEXT[]),
('Queen', 'queen_us.mp3', 'noun', 'B1', 'the female ruler of an independent state that has a royal family', '', 'She was crowned queen at the age of fifteen.', '', ARRAY[]::TEXT[]),
('Query', 'query_us.mp3', 'noun', 'B1', 'a question, especially one asking for information or expressing a doubt about something', '', 'Our assistants will be happy to answer your queries.', '', ARRAY[]::TEXT[]),
('Quest', 'quest_us.mp3', 'noun', 'B1', 'a long search for something, especially for some quality such as happiness', '', 'quest for something, the quest for happiness/knowledge/truth', '', ARRAY[]::TEXT[]),
('Question', 'question_us.mp3', 'noun', 'B1', 'a sentence, phrase or word that asks for information', '', 'You didn''t answer my question.', '', ARRAY[]::TEXT[]),
('Question', 'question_us.mp3', 'verb', 'B1', 'to ask somebody questions about something, especially officially', '', 'question somebody, Police are keen to question any witnesses.', '', ARRAY[]::TEXT[]),
('Questionnaire', 'questionnaire_us.mp3', 'noun', 'B1', 'a written list of questions that are answered by a number of people so that information can be collected from the answers', '', '(British English), to fill in a questionnaire', '', ARRAY[]::TEXT[]),
('Queue', 'queue_us.mp3', 'noun', 'B1', 'a line of people, cars, etc. waiting for something or to do something', '', 'There were long queues at polling stations.', '', ARRAY[]::TEXT[]),
('Queue', 'queue_us.mp3', 'verb', 'B1', 'to wait in a line of people, vehicles, etc. in order to do something, get something or go somewhere', '', 'queue (up), People queued up outside.', '', ARRAY[]::TEXT[]),
('Quick', 'quick_us.mp3', 'adjective', 'B1', 'done with speed; taking or lasting a short time', '', 'a quick look/check/search', '', ARRAY[]::TEXT[]),
('Quickly', 'quickly_us.mp3', 'adverb', 'B1', 'fast', '', 'She walked quickly away.', '', ARRAY[]::TEXT[]),
('Quiet', 'quiet_us.mp3', 'adjective', 'B1', 'making very little noise', '', 'her quiet voice', '', ARRAY[]::TEXT[]),
('Quietly', 'quietly_us.mp3', 'adverb', 'B1', 'in a way that makes very little noise', '', 'to ask/speak/talk quietly', '', ARRAY[]::TEXT[]),
('Quit', 'quit_us.mp3', 'verb', 'B1', 'to leave your job, school, etc.', '', 'If I don''t get more money I''ll quit.', '', ARRAY[]::TEXT[]),
('Quite', 'quite_us.mp3', 'adverb', 'B1', 'to some degree', '', 'quite good/interesting/common/difficult', '', ARRAY[]::TEXT[]),
('Quota', 'quota_us.mp3', 'noun', 'B1', 'a limited number or amount of people or things that is officially allowed', '', 'to introduce a strict import quota on grain', '', ARRAY[]::TEXT[]),
('Quotation', 'quotation_us.mp3', 'noun', 'B1', 'a group of words or a short piece of writing taken from a book, play, speech, etc. and repeated because it is interesting or useful', '', 'a dictionary of quotations', '', ARRAY[]::TEXT[]),
('Quote', 'quote_us.mp3', 'noun', 'B1', 'a group of words or a short piece of writing taken from a book, play, speech, etc. and repeated because it is interesting or useful', '', 'The essay was full of quotes.', '', ARRAY[]::TEXT[]),
('Quote', 'quote_us.mp3', 'verb', 'B1', 'to repeat the exact words that another person has said or written', '', 'quote something, to quote Shakespeare', '', ARRAY[]::TEXT[]),
('Race', 'race_us.mp3', 'noun', 'B1', 'a competition between people, animals, vehicles, etc. to see which one is the faster or fastest', '', 'a boat/horse race', '', ARRAY[]::TEXT[]),
('Race', 'race_us.mp3', 'verb', 'B1', 'to compete against somebody/something to see who can go faster or the fastest, do something first, etc.; to take part in a race or races', '', 'They raced to a thrilling victory in the relay.', '', ARRAY[]::TEXT[]),
('Racial', 'racial_us.mp3', 'adjective', 'B1', 'happening or existing between people of different races', '', 'racial hatred/prejudice/tension/violence', '', ARRAY[]::TEXT[]),
('Racing', 'racing_us.mp3', 'noun', 'B1', 'the sport of racing horses', '', 'He used to watch the racing on TV in the afternoons.', '', ARRAY[]::TEXT[]),
('Racism', 'racism_us.mp3', 'noun', 'B1', 'the unfair treatment of people who belong to a different race; violent behaviour towards them', '', 'a victim of racism', '', ARRAY[]::TEXT[]),
('Racist', 'racist_us.mp3', 'adjective', 'B1', 'having the belief that some races of people are better than others or having general beliefs about other people based only on their race; showing this through violent or unfair treatment of people of other races', '', 'racist attitudes/remarks', '', ARRAY[]::TEXT[]),
('Racist', 'racist_us.mp3', 'noun', 'B1', 'a person who believes that some races of people are better than others or who has general beliefs about other people based only on their race, and may show this in violent or unfair treatment of people of other races', '', 'He''s a racist.', '', ARRAY[]::TEXT[]),
('Radar', 'radar_us.mp3', 'noun', 'B1', 'a system that uses radio waves to find the position and movement of objects, for example planes and ships, when they cannot be seen', '', 'They located the ship by radar.', '', ARRAY[]::TEXT[]),
('Radiation', 'radiation_us.mp3', 'noun', 'B1', 'powerful and very dangerous rays that are sent out from radioactive substances', '', 'high levels/doses of radiation that damage cells', '', ARRAY[]::TEXT[]),
('Radical', 'radical_us.mp3', 'adjective', 'B1', 'relating to the most basic and important parts of something; complete and detailed', '', 'the need for radical changes in education', '', ARRAY[]::TEXT[]),
('Radio', 'radio_us.mp3', 'noun', 'B1', 'the activity of broadcasting programmes for people to listen to; the programmes that are broadcast', '', 'The play was written specially for radio.', '', ARRAY[]::TEXT[]),
('Rage', 'rage_us.mp3', 'noun', 'B1', 'a feeling of violent anger that is difficult to control', '', 'His face was dark with rage.', '', ARRAY[]::TEXT[]),
('Raid', 'raid_us.mp3', 'noun', 'B1', 'a short surprise attack on an enemy by soldiers, ships or aircraft', '', 'to conduct/launch a raid', '', ARRAY[]::TEXT[]),
('Raid', 'raid_us.mp3', 'verb', 'B1', 'to visit a person or place without warning to look for criminals, illegal goods, drugs, etc.', '', 'The house was raided in the early hours.', '', ARRAY[]::TEXT[]),
('Rail', 'rail_us.mp3', 'noun', 'B1', 'a wooden or metal bar placed around something as a barrier or to provide support', '', 'She leaned on the ship''s rail and gazed out to sea.', '', ARRAY[]::TEXT[]),
('Railway', 'railway_us.mp3', 'noun', 'B1', 'a track with rails on which trains run', '', 'The railway is still under construction.', '', ARRAY[]::TEXT[]),
('Rain', 'rain_us.mp3', 'noun', 'B1', 'water that falls from the sky in separate drops', '', 'There will be rain in all parts tomorrow.', '', ARRAY[]::TEXT[]),
('Rain', 'rain_us.mp3', 'verb', 'B1', 'when it rains, water falls from the sky in drops', '', 'Is it raining?', '', ARRAY[]::TEXT[]),
('Raise', 'raise_us.mp3', 'verb', 'B1', 'to lift or move something to a higher level', '', 'She raised the gun and fired.', '', ARRAY[]::TEXT[]),
('Rally', 'rally_us.mp3', 'noun', 'B1', 'a large public meeting, especially one held to support a particular idea or political party', '', 'to attend/hold a rally', '', ARRAY[]::TEXT[]),
('Rally', 'rally_us.mp3', 'verb', 'B1', 'to come together or bring people together in order to help or support somebody/something', '', 'rally around/behind somebody/something, The cabinet rallied behind the Prime Minister.', '', ARRAY[]::TEXT[]),
('Random', 'random_us.mp3', 'adjective', 'B1', 'done, chosen, etc. without somebody deciding in advance what is going to happen, or without any regular pattern', '', 'the random killing of innocent people', '', ARRAY[]::TEXT[]),
('Range', 'range_us.mp3', 'noun', 'B1', 'a variety of things of a particular type', '', 'range of something, The hotel offers a wide range of facilities.', '', ARRAY[]::TEXT[]),
('Range', 'range_us.mp3', 'verb', 'B1', 'to vary between two particular amounts, sizes, etc., including others between them', '', 'range from A to B, Accommodation ranges from tourist class to luxury hotels.', '', ARRAY[]::TEXT[]),
('Rank', 'rank_us.mp3', 'noun', 'B1', 'the position, especially a high position, that somebody has in a particular organization, society, etc.', '', 'She was not used to mixing with people of high social rank.', '', ARRAY[]::TEXT[]),
('Rank', 'rank_us.mp3', 'verb', 'B1', 'to give somebody/something a particular position on a scale according to quality, importance, success, etc.; to have a position of this kind', '', 'rank somebody/something, In most Australian elections, electors are required to rank all candidates.', '', ARRAY[]::TEXT[]),
('Ranking', 'ranking_us.mp3', 'noun', 'B1', 'the position of somebody/something on a scale that shows how good or important they are in relation to other similar people or things, especially in sport', '', 'He has improved his ranking this season from 67th to 30th.', '', ARRAY[]::TEXT[]),
('Rape', 'rape_us.mp3', 'noun', 'B1', 'the crime of forcing somebody to have sex when they do not want it or are not able to agree to it', '', 'He was charged with rape.', '', ARRAY[]::TEXT[]),
('Rape', 'rape_us.mp3', 'verb', 'B1', 'to force somebody to have sex when they do not want it or are not able to agree to it', '', 'She was attacked and raped.', '', ARRAY[]::TEXT[]),
('Rapid', 'rapid_us.mp3', 'adjective', 'B1', 'happening quickly or in a short period of time', '', 'rapid change/expansion/growth/development', '', ARRAY[]::TEXT[]),
('Rapidly', 'rapidly_us.mp3', 'adverb', 'B1', 'very quickly; at a great rate', '', 'to increase/spread/expand rapidly', '', ARRAY[]::TEXT[]),
('Rare', 'rare_us.mp3', 'adjective', 'B1', 'not done, seen, happening, etc. very often', '', 'a rare disease/occurrence/event', '', ARRAY[]::TEXT[]),
('Rarely', 'rarely_us.mp3', 'adverb', 'B1', 'not very often', '', 'She is rarely seen in public nowadays.', '', ARRAY[]::TEXT[]),
('Rat', 'rat_us.mp3', 'noun', 'B1', 'a small animal with a long tail, that looks like a large mouse, usually considered a pest (= an animal which is disliked because it destroys food or spreads disease)', '', 'rat poison', '', ARRAY[]::TEXT[]),
('Rate', 'rate_us.mp3', 'noun', 'B1', 'a measurement of the speed at which something happens', '', 'rate (of something), Figures published today show another fall in the rate of inflation.', '', ARRAY[]::TEXT[]),
('Rate', 'rate_us.mp3', 'verb', 'B1', 'to have or think that somebody/something has a particular level of quality, value, etc.', '', 'rate somebody/something + adv./prep., The university is highly rated for its research.', '', ARRAY[]::TEXT[]),
('Rather', 'rather_us.mp3', 'adverb', 'B1', 'used to mean ‘fairly’ or ‘to some degree’, often when you are disappointed, surprised or expressing slight criticism', '', 'rather odd/strange/unusual', '', ARRAY[]::TEXT[]),
('Rating', 'rating_us.mp3', 'noun', 'B1', 'a measurement of how good, popular, important, etc. somebody/something is, especially in relation to other people or things', '', 'The poll gave an approval rating of 39 per cent for the president.', '', ARRAY[]::TEXT[]),
('Ratio', 'ratio_us.mp3', 'noun', 'B1', 'the relationship between two groups of people or things that is represented by two numbers showing how much larger one group is than the other', '', 'The school has a very high teacher-student ratio.', '', ARRAY[]::TEXT[]),
('Rational', 'rational_us.mp3', 'adjective', 'B1', 'based on reason rather than emotions', '', 'a rational argument/choice/decision', '', ARRAY[]::TEXT[]),
('Raw', 'raw_us.mp3', 'adjective', 'B1', 'not cooked', '', 'raw meat', '', ARRAY[]::TEXT[]),
('Ray', 'ray_us.mp3', 'noun', 'B1', 'a narrow line of light, heat or other energy', '', 'The last of the sun''s rays shone on the grass.', '', ARRAY[]::TEXT[]),
('Reach', 'reach_us.mp3', 'noun', 'B1', 'the distance over which you can stretch your arms to touch something; the distance over which a particular object can be used to touch something else', '', 'beyond somebody''s reach, The shot was well beyond the reach of the goalkeeper.', '', ARRAY[]::TEXT[]),
('Reach', 'reach_us.mp3', 'verb', 'B1', 'to arrive at the place that you have been travelling to', '', 'They didn''t reach the border until after dark.', '', ARRAY[]::TEXT[]),
('React', 'react_us.mp3', 'verb', 'B1', 'to change or behave in a particular way as a result of or in response to something', '', 'I nudged her but she didn''t react.', '', ARRAY[]::TEXT[]),
('Reaction', 'reaction_us.mp3', 'noun', 'B1', 'what you do, say or think as a result of something that has happened', '', 'to provoke/cause/get a reaction', '', ARRAY[]::TEXT[]),
('Read', 'read_us.mp3', 'verb', 'B1', 'to look at and understand the meaning of written or printed words or symbols', '', 'She''s still learning to read.', '', ARRAY[]::TEXT[]),
('Reader', 'reader_us.mp3', 'noun', 'B1', 'a person who reads, especially one who reads a lot or in a particular way', '', 'an avid reader of science fiction', '', ARRAY[]::TEXT[]),
('Readily', 'readily_us.mp3', 'adverb', 'B1', 'quickly and without difficulty', '', 'All ingredients are readily available from your local store.', '', ARRAY[]::TEXT[]),
('Reading', 'reading_us.mp3', 'noun', 'B1', 'the activity of somebody who reads', '', 'My hobbies include reading and painting.', '', ARRAY[]::TEXT[]),
('Ready', 'ready_us.mp3', 'adjective', 'B1', 'fully prepared for what you are going to do and able to start it immediately', '', 'Just a minute—I''m almost ready.', '', ARRAY[]::TEXT[]),
('Real', 'real_us.mp3', 'adjective', 'B1', 'actually existing or happening and not imagined or pretended', '', 'a real danger/risk/threat/concern', '', ARRAY[]::TEXT[]),
('Realistic', 'realistic_us.mp3', 'adjective', 'B1', 'accepting in a sensible way what it is actually possible to do or achieve in a particular situation', '', 'a realistic assessment/approach/view', '', ARRAY[]::TEXT[]),
('Reality', 'reality_us.mp3', 'noun', 'B1', 'the true situation and the problems that actually exist in life, in contrast to how you would like life to be', '', 'She refuses to face reality.', '', ARRAY[]::TEXT[]),
('Realization', 'realization_us.mp3', 'noun', 'B1', 'the process of becoming aware of something', '', 'As realization dawned, he went pale.', '', ARRAY[]::TEXT[]),
('Realize', 'realize_us.mp3', 'verb', 'B1', 'to understand or become aware of a particular fact or situation', '', 'realize (that)…, I didn’t realize (that) you were so unhappy.', '', ARRAY[]::TEXT[]),
('Really', 'really_us.mp3', 'adverb', 'B1', 'used to emphasize an adjective or adverb', '', 'That''s a really good idea.', '', ARRAY[]::TEXT[]),
('Realm', 'realm_us.mp3', 'noun', 'B1', 'an area of activity, interest or knowledge', '', 'in the realm of something, in the realm of literature', '', ARRAY[]::TEXT[]),
('Rear', 'rear_us.mp3', 'adjective', 'B1', 'at or near the back of something', '', 'front and rear windows', '', ARRAY[]::TEXT[]),
('Rear', 'rear_us.mp3', 'noun', 'B1', 'the back part of something', '', 'A trailer was attached to the rear of the truck.', '', ARRAY[]::TEXT[]),
('Reason', 'reason_us.mp3', 'noun', 'B1', 'a cause or an explanation for something that has happened or that somebody has done', '', 'He said no but he didn''t give a reason.', '', ARRAY[]::TEXT[]),
('Reasonable', 'reasonable_us.mp3', 'adjective', 'B1', 'fair, practical, and sensible', '', 'it is reasonable to do something, It is reasonable to assume that he knew beforehand that this would happen.', '', ARRAY[]::TEXT[]),
('Reasonably', 'reasonably_us.mp3', 'adverb', 'B1', 'to a degree that is fairly good but not very good', '', 'The instructions are reasonably straightforward.', '', ARRAY[]::TEXT[]),
('Reasoning', 'reasoning_us.mp3', 'noun', 'B1', 'the process of thinking about things in a logical way; opinions and ideas that are based on logical thinking', '', 'What is the reasoning behind this decision?', '', ARRAY[]::TEXT[]),
('Reassure', 'reassure_us.mp3', 'verb', 'B1', 'to say or do something that makes somebody less frightened or worried', '', 'reassure somebody (about something), They tried to reassure her, but she still felt anxious.', '', ARRAY[]::TEXT[]),
('Rebel', 'rebel_us.mp3', 'noun', 'B1', 'a person who fights against the government of their country', '', 'rebel forces', '', ARRAY[]::TEXT[]),
('Rebellion', 'rebellion_us.mp3', 'noun', 'B1', 'an attempt by some of the people in a country to change their government, using violence', '', 'in rebellion (against somebody/something), The north of the country rose in rebellion against the government.', '', ARRAY[]::TEXT[]),
('Rebuild', 'rebuild_us.mp3', 'verb', 'B1', 'to build or put something together again', '', 'After the earthquake, the people set about rebuilding their homes.', '', ARRAY[]::TEXT[]),
('Recall', 'recall_us.mp3', 'verb', 'B1', 'to remember something', '', 'recall something, She could not recall his name.', '', ARRAY[]::TEXT[]),
('Receipt', 'receipt_us.mp3', 'noun', 'B1', 'a piece of paper or an electronic document that shows that goods or services have been paid for', '', 'Can I have a receipt, please?', '', ARRAY[]::TEXT[]),
('Receive', 'receive_us.mp3', 'verb', 'B1', 'to get or accept something that is sent or given to you', '', 'receive something', '', ARRAY[]::TEXT[]),
('Receiver', 'receiver_us.mp3', 'noun', 'B1', 'the part of a phone that you hold close to your mouth and ear', '', 'to pick up/lift/put down/replace the receiver', '', ARRAY[]::TEXT[]),
('Recent', 'recent_us.mp3', 'adjective', 'B1', 'that happened or began only a short time ago', '', 'a recent study/report/survey', '', ARRAY[]::TEXT[]),
('Recently', 'recently_us.mp3', 'adverb', 'B1', 'not long ago', '', 'a recently published book', '', ARRAY[]::TEXT[]),
('Reception', 'reception_us.mp3', 'noun', 'B1', 'the area inside the entrance of a hotel, an office building, etc. where guests or visitors go first when they arrive', '', 'Please report to reception on arrival.', '', ARRAY[]::TEXT[]),
('Recession', 'recession_us.mp3', 'noun', 'B1', 'a difficult time for the economy of a country, when there is less trade and industrial activity than usual and more people are unemployed', '', 'How do you assess the impact of the current recession on manufacturing?', '', ARRAY[]::TEXT[]),
('Recipe', 'recipe_us.mp3', 'noun', 'B1', 'a set of instructions that tells you how to cook something and the ingredients (= items of food) you need for it', '', 'recipe for something, a recipe for chicken soup', '', ARRAY[]::TEXT[]),
('Recipient', 'recipient_us.mp3', 'noun', 'B1', 'a person who receives something', '', 'recipients of awards', '', ARRAY[]::TEXT[]),
('Reckon', 'reckon_us.mp3', 'verb', 'B1', 'to think something or have an opinion about something', '', 'I reckon (that) I’m going to get that job.', '', ARRAY[]::TEXT[]),
('Recognition', 'recognition_us.mp3', 'noun', 'B1', 'the act of remembering who somebody is when you see them, or of identifying what something is', '', 'He glanced briefly towards her but there was no sign of recognition.', '', ARRAY[]::TEXT[]),
('Recognize', 'recognize_us.mp3', 'verb', 'B1', 'to know who somebody is or what something is when you see or hear them or it, because you have seen or heard them or it before', '', 'recognize somebody/something, I recognized him as soon as he came in the room.', '', ARRAY[]::TEXT[]),
('Recommend', 'recommend_us.mp3', 'verb', 'B1', 'to tell somebody that something is good or useful, or that somebody would be suitable for a particular job, etc.', '', 'recommend somebody/something, The hotel''s new restaurant comes highly recommended (= a lot of people have praised it).', '', ARRAY[]::TEXT[]),
('Recommendation', 'recommendation_us.mp3', 'noun', 'B1', 'an official suggestion about the best thing to do', '', 'to accept/reject a recommendation', '', ARRAY[]::TEXT[]),
('Reconstruction', 'reconstruction_us.mp3', 'noun', 'B1', 'the process of changing or improving the condition of something or the way it works; the process of putting something back into the state it was in before', '', 'the reconstruction of the educational system', '', ARRAY[]::TEXT[]),
('Record', 'record_us.mp3', 'noun', 'B1', 'a written account of something that is kept so that it can be looked at and used in the future', '', 'You should keep a record of your expenses.', '', ARRAY[]::TEXT[]),
('Record', 'record_us.mp3', 'verb', 'B1', 'to keep a permanent account of facts or events by writing them down, filming them, storing them in a computer, etc.', '', 'record something, Her childhood is recorded in the diaries of those years.', '', ARRAY[]::TEXT[]),
('Recording', 'recording_us.mp3', 'noun', 'B1', 'sound or pictures that have been recorded on computer files or on CD, DVD, video, etc.', '', 'an audio recording', '', ARRAY[]::TEXT[]),
('Recount', 'recount_us.mp3', 'verb', 'B1', 'sound or pictures that have been recorded on computer files or on CD, DVD, video, etc.', '', 'an audio recording', '', ARRAY[]::TEXT[]),
('Recover', 'recover_us.mp3', 'verb', 'B1', 'to get well again after being ill, hurt, etc.', '', 'recover from something, He''s still recovering from his operation.', '', ARRAY[]::TEXT[]),
('Recovery', 'recovery_us.mp3', 'noun', 'B1', 'the process of becoming well again after an illness or injury', '', 'My father has made a full recovery from the operation.', '', ARRAY[]::TEXT[]),
('Recruit', 'recruit_us.mp3', 'noun', 'B1', 'a person who has recently joined the armed forces or the police', '', 'the training of new recruits', '', ARRAY[]::TEXT[]),
('Recruit', 'recruit_us.mp3', 'verb', 'B1', 'to find new people to join a company, an organization, the armed forces, etc.', '', 'recruit (somebody), We are trying to recruit officers from more diverse backgrounds.', '', ARRAY[]::TEXT[]),
('Recruitment', 'recruitment_us.mp3', 'noun', 'B1', 'the act or process of finding new people to join a company, an organization, the armed forces, etc.', '', 'the recruitment of new members', '', ARRAY[]::TEXT[]),
('Recycle', 'recycle_us.mp3', 'verb', 'B1', 'to treat things that have already been used so that they can be used again', '', 'to recycle waste/rubbish', '', ARRAY[]::TEXT[]),
('Red', 'red_us.mp3', 'adjective', 'B1', 'having the colour of blood or fire', '', 'bright/light/dark red lipstick', '', ARRAY[]::TEXT[]),
('Red', 'red_us.mp3', 'noun', 'B1', 'the colour of blood or fire', '', 'She often wears red.', '', ARRAY[]::TEXT[]),
('Reduce', 'reduce_us.mp3', 'verb', 'B1', 'to make something less or smaller in size, quantity, price, etc.; to become less or smaller in size, quantity, etc.', '', 'reduce something, Reduce speed now (= on a sign).', '', ARRAY[]::TEXT[]),
('Reduction', 'reduction_us.mp3', 'noun', 'B1', 'an act of making something less or smaller; the state of being made less or smaller', '', 'Some staff received wage rises, while others experienced a reduction.', '', ARRAY[]::TEXT[]),
('Refer', 'refer_us.mp3', 'verb', 'B1', 'to send somebody/something to somebody/something for help, advice or a decision', '', 'refer somebody/something to somebody/something, My doctor referred me to a specialist.', '', ARRAY[]::TEXT[]),
('Referee', 'referee_us.mp3', 'noun', 'B1', 'the official who controls the game in some sports', '', 'He was sent off for arguing with the referee.', '', ARRAY[]::TEXT[]),
('Reference', 'reference_us.mp3', 'noun', 'B1', 'a thing you say or write that mentions somebody/something else; the act of mentioning somebody/something', '', 'reference to somebody/something, She made no reference to her illness but only to her future plans.', '', ARRAY[]::TEXT[]),
('Referendum', 'referendum_us.mp3', 'noun', 'B1', 'an occasion when all the people of a country can vote on an important issue', '', 'referendum on something, Switzerland decided to hold a referendum on joining the EU.', '', ARRAY[]::TEXT[]),
('Reflect', 'reflect_us.mp3', 'verb', 'B1', 'to show the image of somebody/something on the surface of something such as a mirror, water or glass', '', 'be reflected (in something), His face was reflected in the mirror.', '', ARRAY[]::TEXT[]),
('Reflection', 'reflection_us.mp3', 'noun', 'B1', 'an image in a mirror, on a shiny surface, on water, etc.', '', 'He admired his reflection in the mirror.', '', ARRAY[]::TEXT[]),
('Reform', 'reform_us.mp3', 'noun', 'B1', 'change that is made to a social system, an organization, etc. in order to improve or correct it', '', 'a government committed to reform', '', ARRAY[]::TEXT[]),
('Reform', 'reform_us.mp3', 'verb', 'B1', 'to improve a system, an organization, a law, etc. by making changes to it', '', 'proposals to reform the social security system', '', ARRAY[]::TEXT[]),
('Refuge', 'refuge_us.mp3', 'noun', 'B1', 'shelter or protection from danger, trouble, etc.', '', 'A further 300 people have taken refuge in the US embassy.', '', ARRAY[]::TEXT[]),
('Refugee', 'refugee_us.mp3', 'noun', 'B1', 'a person who has been forced to leave their country or home, because there is a war or for political, religious or social reasons', '', 'There has been a steady flow of refugees from the war zone.', '', ARRAY[]::TEXT[]),
('Refusal', 'refusal_us.mp3', 'noun', 'B1', 'an act of saying or showing that you will not do, give or accept something', '', 'the refusal of a request/an invitation/an offer', '', ARRAY[]::TEXT[]),
('Refuse', 'refuse_us.mp3', 'verb', 'B1', 'to say or show that you will not do something that somebody has asked you to do', '', 'Go on, ask her; she can hardly refuse.', '', ARRAY[]::TEXT[]),
('Regain', 'regain_us.mp3', 'verb', 'B1', 'to get back something you no longer have, especially an ability or a quality', '', 'I struggled to regain some dignity.', '', ARRAY[]::TEXT[]),
('Regard', 'regard_us.mp3', 'noun', 'B1', 'attention to or thought and care for somebody/something', '', 'regard for somebody/something, to have scant/little/no regard for somebody/something', '', ARRAY[]::TEXT[]),
('Regard', 'regard_us.mp3', 'verb', 'B1', 'to think about somebody/something in a particular way', '', 'regard somebody/something + adv./prep., They regarded people outside their own town with suspicion.', '', ARRAY[]::TEXT[]),
('Regardless', 'regardless_us.mp3', 'adverb', 'B1', 'paying no attention, even if the situation is bad or there are difficulties', '', 'The weather was terrible but we carried on regardless.', '', ARRAY[]::TEXT[]),
('Regime', 'regime_us.mp3', 'noun', 'B1', 'a method or system of government, especially one that has not been elected in a fair way', '', 'a fascist/totalitarian/military, etc. regime', '', ARRAY[]::TEXT[]),
('Region', 'region_us.mp3', 'noun', 'B1', 'a large area of land, usually without exact limits or borders', '', 'mountainous/coastal regions', '', ARRAY[]::TEXT[]),
('Regional', 'regional_us.mp3', 'adjective', 'B1', 'of or relating to a region', '', 'services available at a local and regional level', '', ARRAY[]::TEXT[]),
('Register', 'register_us.mp3', 'noun', 'B1', 'an official list or record of names, items, etc.; a book that contains such a list', '', 'The bride and groom signed the register.', '', ARRAY[]::TEXT[]),
('Register', 'register_us.mp3', 'verb', 'B1', 'to record your/somebody’s/something’s name on an official list', '', 'You can also register online.', '', ARRAY[]::TEXT[]),
('Registration', 'registration_us.mp3', 'noun', 'B1', 'the act of making an official record of something/somebody', '', 'the registration of letters and parcels', '', ARRAY[]::TEXT[]),
('Regret', 'regret_us.mp3', 'noun', 'B1', 'a sad feeling because of something that has happened or something that you have done or not done', '', 'a feeling/pang/twinge of regret', '', ARRAY[]::TEXT[]),
('Regret', 'regret_us.mp3', 'verb', 'B1', 'to feel sorry about something you have done or about something that you have not been able to do', '', 'regret something, If you don''t do it now, you''ll only regret it.', '', ARRAY[]::TEXT[]),
('Regular', 'regular_us.mp3', 'adjective', 'B1', 'following a pattern, especially with the same time or space in between each thing and the next', '', 'regular breathing', '', ARRAY[]::TEXT[]),
('Regularly', 'regularly_us.mp3', 'adverb', 'B1', 'at regular intervals or times', '', 'We meet regularly to discuss the progress of the project.', '', ARRAY[]::TEXT[]),
('Regulate', 'regulate_us.mp3', 'verb', 'B1', 'to control something by means of rules', '', 'The department is responsible for regulating the insurance industry.', '', ARRAY[]::TEXT[]),
('Regulation', 'regulation_us.mp3', 'noun', 'B1', 'an official rule made by a government or some other authority', '', 'too many rules and regulations', '', ARRAY[]::TEXT[]),
('Regulator', 'regulator_us.mp3', 'noun', 'B1', 'a person or an organization that officially controls an area of business or industry and makes sure that it is operating fairly', '', 'Ofgas, the gas industry regulator', '', ARRAY[]::TEXT[]),
('Regulatory', 'regulatory_us.mp3', 'adjective', 'B1', 'having the power to control an area of business or industry and make sure that it is operating fairly', '', 'regulatory bodies/authorities/agencies', '', ARRAY[]::TEXT[]),
('Rehabilitation', 'rehabilitation_us.mp3', 'noun', 'B1', 'the process of helping somebody to return to a normal, healthy life after they have been in prison or very ill', '', 'a drug rehabilitation centre', '', ARRAY[]::TEXT[]),
('Reign', 'reign_us.mp3', 'noun', 'B1', 'the period during which a king, queen, emperor, etc. rules', '', 'By the end of his reign, the vast empire was in decline.', '', ARRAY[]::TEXT[]),
('Reign', 'reign_us.mp3', 'verb', 'B1', 'to rule as king, queen, emperor, etc.', '', 'It was the first visit by a British reigning monarch to Russia.', '', ARRAY[]::TEXT[]),
('Reinforce', 'reinforce_us.mp3', 'verb', 'B1', 'to make a feeling, an idea, etc. stronger', '', 'The experience reinforced my sense of loss.', '', ARRAY[]::TEXT[]),
('Reject', 'reject_us.mp3', 'verb', 'B1', 'to refuse to accept or consider something', '', 'to reject an argument/a hypothesis/a notion/a plan', '', ARRAY[]::TEXT[]),
('Rejection', 'rejection_us.mp3', 'noun', 'B1', 'the act of refusing to accept or consider something', '', 'Her proposal met with unanimous rejection.', '', ARRAY[]::TEXT[]),
('Relate', 'relate_us.mp3', 'verb', 'B1', 'show or make a connection between two or more things', '', 'relate something, I found it difficult to relate the two ideas in my mind.', '', ARRAY[]::TEXT[]),
('Related', 'related_us.mp3', 'adjective', 'B1', 'connected with something/somebody in some way', '', 'related to something/somebody, The amount of protein you need is directly related to your lifestyle.', '', ARRAY[]::TEXT[]),
('Relation', 'relation_us.mp3', 'noun', 'B1', 'the way in which two people, groups or countries behave towards each other or deal with each other', '', 'diplomatic/international/foreign relations', '', ARRAY[]::TEXT[]),
('Relationship', 'relationship_us.mp3', 'noun', 'B1', 'the way in which two people, groups or countries behave towards each other or deal with each other', '', 'a personal/working relationship', '', ARRAY[]::TEXT[]),
('Relative', 'relative_us.mp3', 'adjective', 'B1', 'considered and judged by being compared with something else', '', 'You must consider the relative merits of the two plans.', '', ARRAY[]::TEXT[]),
('Relative', 'relative_us.mp3', 'noun', 'B1', 'a person who is in the same family as somebody else', '', 'a close/distant relative', '', ARRAY[]::TEXT[]),
('Relatively', 'relatively_us.mp3', 'adverb', 'B1', 'to a fairly large degree, especially in comparison to something else', '', 'relatively large/small/high/low', '', ARRAY[]::TEXT[]),
('Relax', 'relax_us.mp3', 'verb', 'B1', 'to rest while you are doing something that you enjoy, especially after work or effort', '', 'Just relax and enjoy the movie.', '', ARRAY[]::TEXT[]),
('Relaxed', 'relaxed_us.mp3', 'adjective', 'B1', 'calm and not anxious or worried', '', 'He appeared relaxed and confident before the match.', '', ARRAY[]::TEXT[]),
('Relaxing', 'relaxing_us.mp3', 'adjective', 'B1', 'helping you to rest and become less anxious', '', 'a relaxing evening with friends', '', ARRAY[]::TEXT[]),
('Release', 'release_us.mp3', 'noun', 'B1', 'the act of setting a person or an animal free; the state of being set free', '', 'release of somebody/something, The government has been working to secure the release of the hostages.', '', ARRAY[]::TEXT[]),
('Release', 'release_us.mp3', 'verb', 'B1', 'to let somebody come out of a place where they have been kept or stuck and unable to leave or move', '', 'release somebody, to release a prisoner', '', ARRAY[]::TEXT[]),
('Relevance', 'relevance_us.mp3', 'noun', 'B1', 'a close connection with the subject you are discussing or the situation you are in', '', 'I don''t see the relevance of your question.', '', ARRAY[]::TEXT[]),
('Relevant', 'relevant_us.mp3', 'adjective', 'B1', 'closely connected with the subject you are discussing or the situation you are in', '', 'relevant information/facts/documents/factors', '', ARRAY[]::TEXT[]),
('Reliability', 'reliability_us.mp3', 'noun', 'B1', 'the quality of being able to be trusted to do what somebody wants or needs', '', 'The incident cast doubt on her motives and reliability.', '', ARRAY[]::TEXT[]),
('Reliable', 'reliable_us.mp3', 'adjective', 'B1', 'that can be trusted to do something well; that you can rely on', '', 'We are looking for someone who is reliable and hard-working.', '', ARRAY[]::TEXT[]),
('Relief', 'relief_us.mp3', 'noun', 'B1', 'the feeling of happiness that you have when something unpleasant stops or does not happen', '', 'I felt a huge sense of relief when I heard they were all OK.', '', ARRAY[]::TEXT[]),
('Relieve', 'relieve_us.mp3', 'verb', 'B1', 'to remove or reduce an unpleasant feeling or pain', '', 'to relieve the symptoms of a cold', '', ARRAY[]::TEXT[]),
('Relieved', 'relieved_us.mp3', 'adjective', 'B1', 'feeling happy because something unpleasant has stopped or has not happened; showing this', '', 'She sounded relieved.', '', ARRAY[]::TEXT[]),
('Religion', 'religion_us.mp3', 'noun', 'B1', 'the belief in the existence of a god or gods, and the activities that are connected with the worship of them, or in the teachings of a spiritual leader', '', 'Is there always a conflict between science and religion?', '', ARRAY[]::TEXT[]),
('Religious', 'religious_us.mp3', 'adjective', 'B1', 'connected with religion or with a particular religion', '', 'religious beliefs/convictions/faith', '', ARRAY[]::TEXT[]),
('Reluctant', 'reluctant_us.mp3', 'adjective', 'B1', 'hesitating before doing something because you do not want to do it or because you are not sure that it is the right thing to do', '', 'He finally gave a reluctant smile.', '', ARRAY[]::TEXT[]),
('Remain', 'remain_us.mp3', 'verb', 'B1', 'to continue to be something; to be still in the same state or condition', '', 'remain + adj., to remain silent', '', ARRAY[]::TEXT[]),
('Remainder', 'remainder_us.mp3', 'noun', 'B1', 'the people, things or time that remain', '', 'I kept some of his books and gave away the remainder.', '', ARRAY[]::TEXT[]),
('Remains', 'remains_us.mp3', 'noun', 'B1', 'the parts of something that are left after the other parts have been used, eaten, removed, etc.', '', 'She fed the remains of her lunch to the dog.', '', ARRAY[]::TEXT[]),
('Remark', 'remark_us.mp3', 'noun', 'B1', 'something that you say or write which expresses an opinion, a thought, etc. about somebody/something', '', 'to make a remark', '', ARRAY[]::TEXT[]),
('Remark', 'remark_us.mp3', 'verb', 'B1', 'to say or write a comment about something/somebody', '', 'Sport, George Orwell once remarked, is like war.', '', ARRAY[]::TEXT[]),
('Remarkable', 'remarkable_us.mp3', 'adjective', 'B1', 'unusual or surprising in a way that causes people to take notice', '', 'a remarkable achievement/career/talent', '', ARRAY[]::TEXT[]),
('Remarkably', 'remarkably_us.mp3', 'adverb', 'B1', 'in a way that is unusual or surprising and causes people to take notice', '', 'The car is in remarkably good condition for its age.', '', ARRAY[]::TEXT[]),
('Remedy', 'remedy_us.mp3', 'noun', 'B1', 'a way of dealing with or improving an unpleasant or difficult situation', '', 'When the reservoir becomes blocked, the only remedy lies in cleaning the entire system.', '', ARRAY[]::TEXT[]),
('Remember', 'remember_us.mp3', 'verb', 'B1', 'to have or keep an image in your memory of an event, a person, a place, etc. from the past', '', 'remember somebody/something, This is Carla. Do you remember her?', '', ARRAY[]::TEXT[]),
('Remind', 'remind_us.mp3', 'verb', 'B1', 'to help somebody remember something, especially something important that they must do', '', 'remind somebody/yourself, I''m sorry, I''ve forgotten your name. Can you remind me?', '', ARRAY[]::TEXT[]),
('Reminder', 'reminder_us.mp3', 'noun', 'B1', 'something that makes you think about or remember somebody/something, that you have forgotten or would like to forget', '', 'reminder of something, The sheer size of the cathedral is a constant reminder of the power of religion.', '', ARRAY[]::TEXT[]),
('Remote', 'remote_us.mp3', 'adjective', 'B1', 'far away from places where other people live', '', 'a remote village/island/location/region', '', ARRAY[]::TEXT[]),
('Removal', 'removal_us.mp3', 'noun', 'B1', 'the act of taking somebody/something away from a particular place', '', 'Clearance of the site required the removal of a number of trees.', '', ARRAY[]::TEXT[]),
('Remove', 'remove_us.mp3', 'verb', 'B1', 'to take somebody/something away from a place', '', 'remove somebody/something, Illegally parked vehicles will be removed.', '', ARRAY[]::TEXT[]),
('Render', 'render_us.mp3', 'verb', 'B1', 'to cause somebody/something to be in a particular state or condition', '', 'to render something harmless/useless/ineffective', '', ARRAY[]::TEXT[]),
('Renew', 'renew_us.mp3', 'verb', 'B1', 'to begin something again after it stopped or was interrupted', '', 'The army renewed its assault on the capital.', '', ARRAY[]::TEXT[]),
('Renowned', 'renowned_us.mp3', 'adjective', 'B1', 'famous and respected', '', 'a renowned author', '', ARRAY[]::TEXT[]),
('Rent', 'rent_us.mp3', 'noun', 'B1', 'an amount of money that you regularly pay so that you can use a house, room, etc.', '', 'I earn just about enough to pay the rent.', '', ARRAY[]::TEXT[]),
('Rent', 'rent_us.mp3', 'verb', 'B1', 'to regularly pay money to somebody so that you can use something that they own, such as a house, a room, some land, etc.', '', 'Are you looking to buy or rent?', '', ARRAY[]::TEXT[]),
('Rental', 'rental_us.mp3', 'noun', 'B1', 'the amount of money that you pay to use something for a particular period of time', '', 'Telephone charges include line rental.', '', ARRAY[]::TEXT[]),
('Repair', 'repair_us.mp3', 'noun', 'B1', 'an act of repairing something', '', 'They agreed to pay the costs of any repairs.', '', ARRAY[]::TEXT[]),
('Repair', 'repair_us.mp3', 'verb', 'B1', 'to fix something that is broken, damaged or torn', '', 'to repair a car/television', '', ARRAY[]::TEXT[]),
('Repeat', 'repeat_us.mp3', 'noun', 'B1', 'an event that is very similar to something that happened before', '', 'repeat of something, She didn''t want a repeat performance of what had happened the night before.', '', ARRAY[]::TEXT[]),
('Repeat', 'repeat_us.mp3', 'verb', 'B1', 'to say or write something again or more than once', '', 'repeat something, to repeat a question/a claim/an assertion/a warning', '', ARRAY[]::TEXT[]),
('Repeated', 'repeated_us.mp3', 'adjective', 'B1', 'happening, said or done many times', '', 'repeated absences from work', '', ARRAY[]::TEXT[]),
('Replace', 'replace_us.mp3', 'verb', 'B1', 'to be used instead of somebody/something else; to do something instead of somebody/something else', '', 'The new design will eventually replace all existing models.', '', ARRAY[]::TEXT[]),
('Replacement', 'replacement_us.mp3', 'noun', 'B1', 'the act of replacing one thing with another, especially something that is newer or better', '', 'the replacement of worn car parts', '', ARRAY[]::TEXT[]),
('Reply', 'reply_us.mp3', 'noun', 'B1', 'an act of replying to something/somebody in speech, writing or by some action', '', 'I asked her what her name was but she made no reply.', '', ARRAY[]::TEXT[]),
('Reply', 'reply_us.mp3', 'verb', 'B1', 'to say or write something as an answer to somebody/something', '', 'She didn''t even bother to reply.', '', ARRAY[]::TEXT[]),
('Report', 'report_us.mp3', 'noun', 'B1', 'a written or spoken account of an event, especially one that is published or broadcast', '', 'Are these news reports true?', '', ARRAY[]::TEXT[]),
('Report', 'report_us.mp3', 'verb', 'B1', 'to give people information about something that you have heard, seen, done, etc.', '', 'report something, The crash happened seconds after the pilot reported engine trouble.', '', ARRAY[]::TEXT[]),
('Reportedly', 'reportedly_us.mp3', 'adverb', 'B1', 'according to what some people say', '', 'The band have reportedly decided to split up.', '', ARRAY[]::TEXT[]),
('Reporter', 'reporter_us.mp3', 'noun', 'B1', 'a person who collects and reports news for newspapers, radio or television', '', 'He leaked the story to a news reporter.', '', ARRAY[]::TEXT[]),
('Reporting', 'reporting_us.mp3', 'noun', 'B1', 'the presenting of and writing about news on television and radio, and in newspapers', '', 'accurate/balanced/objective reporting', '', ARRAY[]::TEXT[]),
('Represent', 'represent_us.mp3', 'verb', 'B1', 'to be a member of a group of people and act or speak for them at an event, a meeting, etc.', '', 'The competition attracted over 500 contestants representing eight different countries.', '', ARRAY[]::TEXT[]),
('Representation', 'representation_us.mp3', 'noun', 'B1', 'the act of presenting somebody/something in a particular way; something that shows or describes something', '', 'the negative representation of single mothers in the media', '', ARRAY[]::TEXT[]),
('Representative', 'representative_us.mp3', 'adjective', 'B1', 'typical of a particular group of people; that is a typical example of something', '', 'Is a questionnaire answered by 500 people truly representative of the population as a whole?', '', ARRAY[]::TEXT[]),
('Representative', 'representative_us.mp3', 'noun', 'B1', 'a person who has been chosen to speak or vote for somebody else or for a group of people, or to take the place of somebody else', '', 'Our elected representatives in government should be doing something about this.', '', ARRAY[]::TEXT[]),
('Reproduce', 'reproduce_us.mp3', 'verb', 'B1', 'to make a copy of a picture, piece of text, etc.', '', 'It is illegal to reproduce these worksheets without permission from the publisher.', '', ARRAY[]::TEXT[]),
('Reproduction', 'reproduction_us.mp3', 'noun', 'B1', 'the act or process of producing babies, young animals or plants', '', 'sexual reproduction', '', ARRAY[]::TEXT[]),
('Republic', 'republic_us.mp3', 'noun', 'B1', 'a country that is governed by a president and politicians elected by the people and where there is no king or queen', '', 'newly independent republics', '', ARRAY[]::TEXT[]),
('Reputation', 'reputation_us.mp3', 'noun', 'B1', 'the opinion that people have about what somebody/something is like, based on what has happened in the past', '', 'to have a good/bad reputation', '', ARRAY[]::TEXT[]),
('Request', 'request_us.mp3', 'noun', 'B1', 'the action of asking for something formally and politely; a thing that you formally ask for', '', 'request for something, a request for information', '', ARRAY[]::TEXT[]),
('Request', 'request_us.mp3', 'verb', 'B1', 'to ask for something or ask somebody to do something in a polite or formal way', '', 'request something, She requested permission to film at the White House.', '', ARRAY[]::TEXT[]),
('Require', 'require_us.mp3', 'verb', 'B1', 'to need something; to depend on somebody/something', '', 'require something, These pets require a lot of care and attention.', '', ARRAY[]::TEXT[]),
('Requirement', 'requirement_us.mp3', 'noun', 'B1', 'something that you need or want', '', 'the basic requirements of life', '', ARRAY[]::TEXT[]),
('Rescue', 'rescue_us.mp3', 'noun', 'B1', 'the act of saving somebody/something from a dangerous or difficult situation; the fact of being saved', '', 'We had given up hope of rescue.', '', ARRAY[]::TEXT[]),
('Rescue', 'rescue_us.mp3', 'verb', 'B1', 'to save somebody/something from a dangerous or harmful situation', '', 'rescue somebody/something from something/somebody, The coastguard rescued six people from the sinking boat.', '', ARRAY[]::TEXT[]),
('Research', 'research_us.mp3', 'noun', 'B1', 'a careful study of a subject, especially in order to discover new facts or information about it', '', 'scientific/medical/academic research', '', ARRAY[]::TEXT[]),
('Research', 'research_us.mp3', 'verb', 'B1', 'to study something carefully and try to discover new facts about it', '', 'research (something), to research a topic/subject', '', ARRAY[]::TEXT[]),
('Researcher', 'researcher_us.mp3', 'noun', 'B1', 'a person who studies something carefully and tries to discover new facts about it', '', 'European researchers say olive oil could help prevent cancer.', '', ARRAY[]::TEXT[]),
('Resemble', 'resemble_us.mp3', 'verb', 'B1', 'to look like or be similar to another person or thing', '', 'She closely resembles her sister.', '', ARRAY[]::TEXT[]),
('Reservation', 'reservation_us.mp3', 'noun', 'B1', 'an arrangement for a seat on a plane or train, a room in a hotel, etc. to be kept for you', '', 'I''ll call the restaurant and make a reservation.', '', ARRAY[]::TEXT[]),
('Reserve', 'reserve_us.mp3', 'noun', 'B1', 'a supply of something that is available to be used in the future or when it is needed', '', 'cash/foreign currency reserves', '', ARRAY[]::TEXT[]),
('Reserve', 'reserve_us.mp3', 'verb', 'B1', 'to ask for a seat, table, room, etc. to be available for you or somebody else at a future time', '', 'reserve something for somebody/something, I''d like to reserve a table for three for eight o''clock.', '', ARRAY[]::TEXT[]),
('Reside', 'reside_us.mp3', 'verb', 'B1', 'to live in a particular place', '', 'He returned to Britain in 1939, having resided abroad for many years.', '', ARRAY[]::TEXT[]),
('Residence', 'residence_us.mp3', 'noun', 'B1', 'a house, especially a large or impressive one', '', 'a desirable family residence for sale (= for example, in an advertisement)', '', ARRAY[]::TEXT[]),
('Resident', 'resident_us.mp3', 'adjective', 'B1', 'living in a particular place', '', 'the town’s resident population (= not tourists or visitors)', '', ARRAY[]::TEXT[]),
('Resident', 'resident_us.mp3', 'noun', 'B1', 'a person who lives in a particular place or who has their home there', '', 'a resident of the United States', '', ARRAY[]::TEXT[]),
('Residential', 'residential_us.mp3', 'adjective', 'B1', 'suitable for living in; consisting of houses rather than factories or offices', '', 'a quiet residential area', '', ARRAY[]::TEXT[]),
('Residue', 'residue_us.mp3', 'noun', 'B1', 'a small amount of something that remains at the end of a process', '', 'pesticide residues in fruit and vegetables', '', ARRAY[]::TEXT[]),
('Resign', 'resign_us.mp3', 'verb', 'B1', 'to officially tell somebody that you are leaving your job, an organization, etc.', '', 'She was forced to resign due to ill health.', '', ARRAY[]::TEXT[]),
('Resignation', 'resignation_us.mp3', 'noun', 'B1', 'the act of giving up your job or position; the occasion when you do this', '', 'a letter of resignation', '', ARRAY[]::TEXT[]),
('Resist', 'resist_us.mp3', 'verb', 'B1', 'to refuse to accept something and try to stop it from happening', '', 'resist something, They are determined to resist pressure to change the law.', '', ARRAY[]::TEXT[]),
('Resistance', 'resistance_us.mp3', 'noun', 'B1', 'dislike of or opposition to a plan, an idea, etc.; the act of refusing to obey', '', 'As with all new ideas it met with resistance.', '', ARRAY[]::TEXT[]),
('Resolution', 'resolution_us.mp3', 'noun', 'B1', 'a definite decision to do or not to do something', '', 'Have you made any New Year''s resolutions (= for example, to give up smoking from 1 January)?', '', ARRAY[]::TEXT[]),
('Resolve', 'resolve_us.mp3', 'verb', 'B1', 'to find an acceptable solution to a problem or difficulty', '', 'resolve something, to resolve an issue/a dispute/a conflict/a crisis', '', ARRAY[]::TEXT[]),
('Resort', 'resort_us.mp3', 'noun', 'B1', 'a place where a lot of people go on holiday', '', 'seaside/mountain resorts', '', ARRAY[]::TEXT[]),
('Resource', 'resource_us.mp3', 'noun', 'B1', 'a supply of something that a country, an organization or a person has and can use, especially to increase their wealth', '', 'the exploitation of minerals and other natural resources', '', ARRAY[]::TEXT[]),
('Respect', 'respect_us.mp3', 'noun', 'B1', 'a strong feeling of approval of somebody/something because of their good qualities or achievements', '', 'I have the utmost respect for her and her work.', '', ARRAY[]::TEXT[]),
('Respect', 'respect_us.mp3', 'verb', 'B1', 'to have a very good opinion of somebody/something; to admire somebody/something', '', 'I respect Jack''s opinion on most subjects.', '', ARRAY[]::TEXT[]),
('Respective', 'respective_us.mp3', 'adjective', 'B1', 'belonging or relating separately to each of the people or things already mentioned', '', 'They are each recognized specialists in their respective fields.', '', ARRAY[]::TEXT[]),
('Respectively', 'respectively_us.mp3', 'adverb', 'B1', 'in the same order as the people or things already mentioned', '', 'Julie and Mark, aged 17 and 19 respectively', '', ARRAY[]::TEXT[]),
('Respond', 'respond_us.mp3', 'verb', 'B1', 'to give a spoken or written answer to somebody/something', '', 'I asked him his name, but he didn''t respond.', '', ARRAY[]::TEXT[]),
('Response', 'response_us.mp3', 'noun', 'B1', 'a spoken or written answer', '', 'She made no response.', '', ARRAY[]::TEXT[]),
('Responsibility', 'responsibility_us.mp3', 'noun', 'B1', 'a duty to deal with or take care of somebody/something, so that you may be blamed if something goes wrong', '', 'to be in a position of responsibility', '', ARRAY[]::TEXT[]),
('Responsible', 'responsible_us.mp3', 'adjective', 'B1', 'having the job or duty of doing something or taking care of somebody/something, so that you may be blamed if something goes wrong', '', 'responsible for doing something, Mike is responsible for designing the entire project.', '', ARRAY[]::TEXT[]),
('Rest', 'rest_us.mp3', 'noun', 'B1', 'the part of something that remains', '', 'Take what you want and throw the rest away.', '', ARRAY[]::TEXT[]),
('Rest', 'rest_us.mp3', 'verb', 'B1', 'to relax, sleep or do nothing after a period of activity or illness; to not use a part of your body for some time', '', 'The doctor told me to rest.', '', ARRAY[]::TEXT[]),
('Restaurant', 'restaurant_us.mp3', 'noun', 'B1', 'a place where you can buy and eat a meal', '', 'We''re going to try this Italian restaurant that just opened.', '', ARRAY[]::TEXT[]),
('Restoration', 'restoration_us.mp3', 'noun', 'B1', 'the work of repairing and cleaning an old building, a painting, etc. so that its condition is as good as it originally was', '', 'restoration work', '', ARRAY[]::TEXT[]),
('Restore', 'restore_us.mp3', 'verb', 'B1', 'to bring back a situation or feeling that existed before', '', 'restore something, The measures are intended to restore public confidence in the economy.', '', ARRAY[]::TEXT[]),
('Restraint', 'restraint_us.mp3', 'noun', 'B1', 'a rule, a fact, an idea, etc. that limits or controls what people can do', '', 'The government has imposed export restraints on some products.', '', ARRAY[]::TEXT[]),
('Restrict', 'restrict_us.mp3', 'verb', 'B1', 'to limit the size, amount or range of something', '', 'restrict something to something, Speed is restricted to 30 mph in towns.', '', ARRAY[]::TEXT[]),
('Restriction', 'restriction_us.mp3', 'noun', 'B1', 'a rule or law that limits what you can do or what can happen', '', 'import/speed/travel restrictions', '', ARRAY[]::TEXT[]),
('Result', 'result_us.mp3', 'noun', 'B1', 'a thing that is caused or produced because of something else', '', 'And did your intervention produce the desired result?', '', ARRAY[]::TEXT[]),
('Result', 'result_us.mp3', 'verb', 'B1', 'to make something happen', '', 'A heavy frost could result in loss of the crop.', '', ARRAY[]::TEXT[]),
('Resume', 'resume_us.mp3', 'verb', 'B1', 'if you resume an activity, or if it resumes, it begins again or continues after being interrupted', '', 'resume (something), to resume talks/negotiations', '', ARRAY[]::TEXT[]),
('Retail', 'retail_us.mp3', 'noun', 'B1', 'the selling of goods to the public, usually through shops', '', 'The recommended retail price is £9.99.', '', ARRAY[]::TEXT[]),
('Retain', 'retain_us.mp3', 'verb', 'B1', 'to keep something; to continue to have something', '', 'to retain your independence', '', ARRAY[]::TEXT[]),
('Retire', 'retire_us.mp3', 'verb', 'B1', 'to leave your job and stop working, especially because you have reached a particular age or because you are ill; to tell somebody they must stop doing their job', '', 'He is retiring next year after 30 years with the company.', '', ARRAY[]::TEXT[]),
('Retired', 'retired_us.mp3', 'adjective', 'B1', 'having retired from work', '', 'a retired doctor/teacher/officer/general', '', ARRAY[]::TEXT[]),
('Retirement', 'retirement_us.mp3', 'noun', 'B1', 'the fact of leaving your job and stopping work, usually because you have reached a particular age; the time when you do this', '', 'At 60, he was now approaching retirement.', '', ARRAY[]::TEXT[]),
('Retreat', 'retreat_us.mp3', 'noun', 'B1', 'a movement away from a place or an enemy because of danger or defeat', '', 'Napoleon’s retreat from Moscow', '', ARRAY[]::TEXT[]),
('Retreat', 'retreat_us.mp3', 'verb', 'B1', 'to move away from a place or an enemy because you are in danger or because you have been defeated', '', 'The army was forced to retreat after suffering heavy losses.', '', ARRAY[]::TEXT[]),
('Retrieve', 'retrieve_us.mp3', 'verb', 'B1', 'to bring or get something back, especially from a place where it should not be', '', 'retrieve something from somebody/something, She bent to retrieve her comb from the floor.', '', ARRAY[]::TEXT[]),
('Return', 'return_us.mp3', 'noun', 'B1', 'the action of arriving in or coming back to a place that you were in before', '', 'return of somebody to…, A week had passed since their return to Geneva.', '', ARRAY[]::TEXT[]),
('Return', 'return_us.mp3', 'verb', 'B1', 'to come or go back from one place to another', '', 'I waited a long time for him to return.', '', ARRAY[]::TEXT[]),
('Reveal', 'reveal_us.mp3', 'verb', 'B1', 'to make something known to somebody', '', 'reveal something, to reveal a secret', '', ARRAY[]::TEXT[]),
('Revelation', 'revelation_us.mp3', 'noun', 'B1', 'a fact that people are made aware of, especially one that has been secret and is surprising', '', 'revelation about/concerning something, startling/sensational revelations about her private life', '', ARRAY[]::TEXT[]),
('Revenge', 'revenge_us.mp3', 'noun', 'B1', 'something that you do in order to make somebody suffer because they have made you suffer', '', 'revenge for something, She is seeking revenge for the murder of her husband.', '', ARRAY[]::TEXT[]),
('Revenue', 'revenue_us.mp3', 'noun', 'B1', 'the money that a government receives from taxes or that an organization, etc. receives from its business', '', 'The government is currently facing a shortfall in tax revenue.', '', ARRAY[]::TEXT[]),
('Reverse', 'reverse_us.mp3', 'adjective', 'B1', 'opposite to what has been mentioned', '', 'to travel in the reverse direction', '', ARRAY[]::TEXT[]),
('Reverse', 'reverse_us.mp3', 'noun', 'B1', 'the opposite of what has just been mentioned', '', 'This problem is the reverse of the previous one.', '', ARRAY[]::TEXT[]),
('Reverse', 'reverse_us.mp3', 'verb', 'B1', 'to change something completely so that it is the opposite of what it was before', '', 'Falling birth rates may reverse the trend towards early retirement.', '', ARRAY[]::TEXT[]),
('Review', 'review_us.mp3', 'noun', 'B1', 'a report in a newspaper or magazine, or on the internet, television or radio, in which somebody gives their opinion of a book, play, film, product, etc.; the act of writing this kind of report', '', 'a book review', '', ARRAY[]::TEXT[]),
('Review', 'review_us.mp3', 'verb', 'B1', 'to write a report of a book, play, film, product, etc. in which you give your opinion of it', '', 'Please rate and review your purchase on our website.', '', ARRAY[]::TEXT[]),
('Revise', 'revise_us.mp3', 'verb', 'B1', 'to change your opinions or plans, for example because of something you have learned', '', 'I can see I will have to revise my opinions of his abilities now.', '', ARRAY[]::TEXT[]),
('Revision', 'revision_us.mp3', 'noun', 'B1', 'a change or set of changes to something', '', 'He made some minor revisions to the report before printing it out.', '', ARRAY[]::TEXT[]),
('Revival', 'revival_us.mp3', 'noun', 'B1', 'an improvement in the condition or strength of something', '', 'the revival of trade', '', ARRAY[]::TEXT[]),
('Revive', 'revive_us.mp3', 'verb', 'B1', 'to become, or to make somebody/something become, conscious or healthy and strong again', '', 'The flowers soon revived in water.', '', ARRAY[]::TEXT[]),
('Revolution', 'revolution_us.mp3', 'noun', 'B1', 'an attempt, by a large number of people, to change the government of a country, especially by violent action', '', 'a socialist revolution', '', ARRAY[]::TEXT[]),
('Revolutionary', 'revolutionary_us.mp3', 'adjective', 'B1', 'connected with political revolution', '', 'a revolutionary leader', '', ARRAY[]::TEXT[]),
('Reward', 'reward_us.mp3', 'noun', 'B1', 'a thing that you are given because you have done something good, worked hard, etc.', '', 'a financial reward', '', ARRAY[]::TEXT[]),
('Reward', 'reward_us.mp3', 'verb', 'B1', 'to give something to somebody because they have done something good, worked hard, etc.', '', 'reward somebody for something, She was rewarded for her efforts with a cash bonus.', '', ARRAY[]::TEXT[]),
('Rhetoric', 'rhetoric_us.mp3', 'noun', 'B1', 'speech or writing that is intended to influence people, but that is not completely honest or sincere', '', 'the rhetoric of political slogans', '', ARRAY[]::TEXT[]),
('Rhythm', 'rhythm_us.mp3', 'noun', 'B1', 'a strong regular repeated pattern of sounds or movements', '', 'to dance to the rhythm of the music', '', ARRAY[]::TEXT[]),
('Rice', 'rice_us.mp3', 'noun', 'B1', 'short, narrow white or brown grain grown on wet land in hot countries as food; the plant that produces this grain', '', 'a grain of rice', '', ARRAY[]::TEXT[]),
('Rich', 'rich_us.mp3', 'adjective', 'B1', 'having a lot of money or property', '', 'She''s one of the richest women in the world.', '', ARRAY[]::TEXT[]),
('Rid', 'rid_us.mp3', 'verb', 'B1', 'to be free of somebody/something that has been annoying you or that you do not want', '', 'She wanted to be rid of her parents and their authority.', '', ARRAY[]::TEXT[]),
('Ride', 'ride_us.mp3', 'noun', 'B1', 'a short journey in a vehicle, on a bicycle, etc.', '', 'a train ride through beautiful countryside', '', ARRAY[]::TEXT[]),
('Ride', 'ride_us.mp3', 'verb', 'B1', 'to sit on an animal, especially a horse, and control it as it moves', '', 'I learnt to ride as a child.', '', ARRAY[]::TEXT[]),
('Ridiculous', 'ridiculous_us.mp3', 'adjective', 'B1', 'very silly or unreasonable', '', 'I look ridiculous in this hat.', '', ARRAY[]::TEXT[]),
('Rifle', 'rifle_us.mp3', 'noun', 'B1', 'a gun with a long barrel which you hold to your shoulder to fire', '', 'a hunting rifle', '', ARRAY[]::TEXT[]),
('Right', 'right_us.mp3', 'adjective', 'B1', 'true or correct as a fact', '', 'Did you get the answer right?', '', ARRAY[]::TEXT[]),
('Right', 'right_us.mp3', 'adverb', 'B1', 'on or to the right side', '', 'Turn right at the end of the street.', '', ARRAY[]::TEXT[]),
('Right', 'right_us.mp3', 'noun', 'B1', 'the right side or direction', '', 'on the right, Take the first street on the right.', '', ARRAY[]::TEXT[]),
('Ring', 'ring_us.mp3', 'noun', 'B1', 'a piece of jewellery that you wear on your finger, consisting of a round band of gold, silver, etc., sometimes decorated with precious stones', '', 'a gold ring', '', ARRAY[]::TEXT[]),
('Ring', 'ring_us.mp3', 'verb', 'B1', 'to surround somebody/something', '', 'Thousands of demonstrators ringed the building.', '', ARRAY[]::TEXT[]),
('Riot', 'riot_us.mp3', 'noun', 'B1', 'a situation in which a group of people behave in a violent way in a public place, often as a protest', '', 'One prison guard was killed when a riot broke out in the jail.', '', ARRAY[]::TEXT[]),
('Rip', 'rip_us.mp3', 'verb', 'B1', 'to tear something or to become torn, often suddenly or violently', '', 'rip (something), I ripped my jeans on the fence.', '', ARRAY[]::TEXT[]),
('Rise', 'rise_us.mp3', 'noun', 'B1', 'an increase in an amount, a number or a level', '', 'The industry is feeling the effects of recent price rises.', '', ARRAY[]::TEXT[]),
('Rise', 'rise_us.mp3', 'verb', 'B1', 'to come or go upwards; to reach a higher level or position', '', 'The curtain rose to reveal an empty stage.', '', ARRAY[]::TEXT[]),
('Risk', 'risk_us.mp3', 'noun', 'B1', 'the possibility of something bad happening at some time in the future; a situation that could be dangerous or have a bad result', '', 'The health risks are very low.', '', ARRAY[]::TEXT[]),
('Risk', 'risk_us.mp3', 'verb', 'B1', 'to put something valuable or important in a dangerous situation, in which it could be lost or damaged', '', 'He risked his life to save her.', '', ARRAY[]::TEXT[]),
('Risky', 'risky_us.mp3', 'adjective', 'B1', 'involving the possibility of something bad happening', '', 'Life as an aid worker can be a risky business (= dangerous).', '', ARRAY[]::TEXT[]),
('Ritual', 'ritual_us.mp3', 'noun', 'B1', 'a series of actions that are always performed in the same way, especially as part of a religious ceremony', '', 'religious rituals', '', ARRAY[]::TEXT[]),
('Rival', 'rival_us.mp3', 'adjective', 'B1', 'competing with another person, company, thing, etc.', '', 'a rival bid/claim/offer', '', ARRAY[]::TEXT[]),
('Rival', 'rival_us.mp3', 'noun', 'B1', 'a person, company or thing that competes with another in sport, business, etc.', '', 'The two teams have always been rivals.', '', ARRAY[]::TEXT[]),
('River', 'river_us.mp3', 'noun', 'B1', 'a natural flow of water that continues in a long line across land to the sea', '', 'Eventually we came to the mouth of the River Thames.', '', ARRAY[]::TEXT[]),
('Road', 'road_us.mp3', 'noun', 'B1', 'a hard surface built for vehicles to travel on', '', 'a main/major/minor road', '', ARRAY[]::TEXT[]),
('Rob', 'rob_us.mp3', 'verb', 'B1', 'to steal money or property from a person or place', '', 'to rob a bank', '', ARRAY[]::TEXT[]),
('Robbery', 'robbery_us.mp3', 'noun', 'B1', 'the crime of stealing money or goods from a bank, shop, person, etc., especially using violence or threats', '', 'armed robbery (= using a gun, knife, etc.)', '', ARRAY[]::TEXT[]),
('Robot', 'robot_us.mp3', 'noun', 'B1', 'a machine that can perform a complicated series of tasks by itself', '', 'These cars are built by robots.', '', ARRAY[]::TEXT[]),
('Robust', 'robust_us.mp3', 'adjective', 'B1', 'strong and healthy', '', 'She was almost 90, but still very robust.', '', ARRAY[]::TEXT[]),
('Rock', 'rock_us.mp3', 'noun', 'B1', 'the hard solid material that forms part of the surface of the earth and some other planets', '', 'They drilled through several layers of rock to reach the oil.', '', ARRAY[]::TEXT[]),
('Rock', 'rock_us.mp3', 'verb', 'B1', 'to move gently backwards and forwards or from side to side; to make somebody/something move in this way', '', '(+ adv./prep.), The boat rocked from side to side in the waves.', '', ARRAY[]::TEXT[]),
('Rocket', 'rocket_us.mp3', 'noun', 'B1', 'a spacecraft in the shape of a tube that is driven by a stream of gases let out behind it when fuel is burned inside', '', 'a space rocket', '', ARRAY[]::TEXT[]),
('Rod', 'rod_us.mp3', 'noun', 'B1', 'a long straight piece of wood, metal or glass', '', 'The concrete is reinforced with steel rods.', '', ARRAY[]::TEXT[]),
('Role', 'role_us.mp3', 'noun', 'B1', 'an actor’s part in a play, film, etc.', '', 'She has landed the lead role (= the most important one) in a new play.', '', ARRAY[]::TEXT[]),
('Roll', 'roll_us.mp3', 'noun', 'B1', 'a small loaf of bread for one person', '', 'Soup and a roll: £3.50', '', ARRAY[]::TEXT[]),
('Roll', 'roll_us.mp3', 'verb', 'B1', 'to turn over and over and move in a particular direction; to make a round object do this', '', '+ adv./prep., The ball rolled down the hill.', '', ARRAY[]::TEXT[]),
('Romance', 'romance_us.mp3', 'noun', 'B1', 'an exciting, usually short, relationship between two people who are in love with each other', '', 'a holiday romance', '', ARRAY[]::TEXT[]),
('Romantic', 'romantic_us.mp3', 'adjective', 'B1', 'connected with or about love or a sexual relationship', '', 'a romantic candlelit dinner', '', ARRAY[]::TEXT[]),
('Roof', 'roof_us.mp3', 'noun', 'B1', 'the structure that covers or forms the top of a building or vehicle', '', 'a flat/sloping/pitched roof', '', ARRAY[]::TEXT[]),
('Room', 'room_us.mp3', 'noun', 'B1', 'a part of a building that has its own walls, floor and ceiling and is usually used for a particular purpose', '', 'I heard him enter the room.', '', ARRAY[]::TEXT[]),
('Root', 'root_us.mp3', 'noun', 'B1', 'the part of a plant that grows under the ground and takes in water and minerals that it sends to the rest of the plant', '', 'deep spreading roots', '', ARRAY[]::TEXT[]),
('Rope', 'rope_us.mp3', 'noun', 'B1', 'very strong thick string made by twisting thinner strings, wires, etc. together', '', 'The rope broke and she fell 50 metres onto the rocks.', '', ARRAY[]::TEXT[]),
('Rose', 'rose_us.mp3', 'noun', 'B1', 'a flower with a sweet smell that grows on a bush with thorns (= sharp points) on its stems', '', 'a bunch of red roses', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
