INSERT INTO words (word, phonetic, pos, level, def_en, def_vi, ex_en, ex_vi, synonyms) VALUES
('Rotate', 'rotate_us.mp3', 'verb', 'B1', 'to move or turn around a central fixed point; to make something do this', '', 'Stay well away from the helicopter when its blades start to rotate.', '', ARRAY[]::TEXT[]),
('Rotation', 'rotation_us.mp3', 'noun', 'B1', 'the action of an object moving in a circle around a central fixed point', '', 'the daily rotation of the earth on its axis', '', ARRAY[]::TEXT[]),
('Rough', 'rough_us.mp3', 'adjective', 'B1', 'having a surface that is not even or regular', '', 'rough ground', '', ARRAY[]::TEXT[]),
('Roughly', 'roughly_us.mp3', 'adverb', 'B1', 'approximately but not exactly', '', 'Sales are up by roughly 10 per cent.', '', ARRAY[]::TEXT[]),
('Round', 'round_us.mp3', 'adjective', 'B1', 'having a shape like a circle or a ball', '', 'a round plate', '', ARRAY[]::TEXT[]),
('Round', 'round_us.mp3', 'adverb', 'B1', 'moving in a circle', '', 'Everybody joins hands and dances round.', '', ARRAY[]::TEXT[]),
('Round', 'round_us.mp3', 'noun', 'B1', 'a stage in a competition or sports event', '', 'the qualifying rounds of the National Championships', '', ARRAY[]::TEXT[]),
('Round', 'round_us.mp3', 'preposition', 'B1', 'in a circle', '', 'the first woman to sail round the world', '', ARRAY[]::TEXT[]),
('Route', 'route_us.mp3', 'noun', 'B1', 'a way that you follow to get from one place to another', '', 'Which is the best route to take?', '', ARRAY[]::TEXT[]),
('Routine', 'routine_us.mp3', 'adjective', 'B1', 'done or happening as a normal part of a particular job, situation or process', '', 'routine enquiries/questions/tests/screening', '', ARRAY[]::TEXT[]),
('Routine', 'routine_us.mp3', 'noun', 'B1', 'the normal order and way in which you regularly do things', '', 'to settle/get/fall into a routine', '', ARRAY[]::TEXT[]),
('Royal', 'royal_us.mp3', 'adjective', 'B1', 'connected with or belonging to the king or queen of a country', '', 'the royal family', '', ARRAY[]::TEXT[]),
('Rub', 'rub_us.mp3', 'verb', 'B1', 'to move your hand, a cloth, etc., backwards and forwards over a surface while pressing it', '', 'rub something, He sat up on the hard bunk and rubbed his eyes.', '', ARRAY[]::TEXT[]),
('Rubber', 'rubber_us.mp3', 'adjective', 'B1', 'made of rubber', '', 'a rubber ball', '', ARRAY[]::TEXT[]),
('Rubber', 'rubber_us.mp3', 'noun', 'B1', 'a strong substance that can be stretched and does not allow liquids to pass through it, used for making tyres, boots, etc. It is made from the liquid (= sap) inside a tropical plant or is produced using chemicals.', '', 'a ball made of rubber', '', ARRAY[]::TEXT[]),
('Rubbish', 'rubbish_us.mp3', 'noun', 'B1', 'things that you throw away because you no longer want or need them', '', 'a rubbish bag/bin', '', ARRAY[]::TEXT[]),
('Rude', 'rude_us.mp3', 'adjective', 'B1', 'having or showing a lack of respect for other people and their feelings', '', 'a rude comment/remark', '', ARRAY[]::TEXT[]),
('Rugby', 'rugby_us.mp3', 'noun', 'B1', 'a game played by two teams of 13 or 15 players, using an oval ball which may be kicked or carried. Teams try to put the ball over the other team’s line.', '', 'to play a game of rugby', '', ARRAY[]::TEXT[]),
('Ruin', 'ruin_us.mp3', 'noun', 'B1', 'the state or process of being destroyed or severely damaged', '', 'A large number of churches fell into ruin after the revolution.', '', ARRAY[]::TEXT[]),
('Ruin', 'ruin_us.mp3', 'verb', 'B1', 'to damage something so badly that it loses all its value, pleasure, etc.', '', 'The bad weather ruined our trip.', '', ARRAY[]::TEXT[]),
('Rule', 'rule_us.mp3', 'noun', 'B1', 'a statement of what may, must or must not be done in a particular situation or when playing a game', '', 'She laid down strict rules for her tenants, including prompt payment of rent.', '', ARRAY[]::TEXT[]),
('Rule', 'rule_us.mp3', 'verb', 'B1', 'to control and have authority over a country, a group of people, etc.', '', 'rule (something), At that time, King John ruled England.', '', ARRAY[]::TEXT[]),
('Ruling', 'ruling_us.mp3', 'noun', 'B1', 'an official decision made by somebody in a position of authority, especially a judge', '', 'The court will make its ruling on the case next week.', '', ARRAY[]::TEXT[]),
('Rumour', 'rumour_us.mp3', 'noun', 'B1', 'a piece of information, or a story, that people talk about, but that may not be true', '', 'to start/spread a rumour', '', ARRAY[]::TEXT[]),
('Run', 'run_us.mp3', 'noun', 'B1', 'an act of running; a period of time spent running or the distance that somebody runs', '', 'I go for a run every morning.', '', ARRAY[]::TEXT[]),
('Run', 'run_us.mp3', 'verb', 'B1', 'to move using your legs, going faster than when you walk', '', 'Can you run as fast as Mike?', '', ARRAY[]::TEXT[]),
('Runner', 'runner_us.mp3', 'noun', 'B1', 'a person or an animal that runs, especially one taking part in a race', '', 'a long-distance/cross-country/marathon runner', '', ARRAY[]::TEXT[]),
('Running', 'running_us.mp3', 'noun', 'B1', 'the action or sport of running', '', 'to go running', '', ARRAY[]::TEXT[]),
('Rural', 'rural_us.mp3', 'adjective', 'B1', 'connected with or like the countryside', '', 'rural areas', '', ARRAY[]::TEXT[]),
('Rush', 'rush_us.mp3', 'noun', 'B1', 'a sudden strong movement or action', '', 'rush for something, Shoppers made a rush for the exits.', '', ARRAY[]::TEXT[]),
('Rush', 'rush_us.mp3', 'verb', 'B1', 'to move or to do something with great speed, often too fast', '', 'We''ve got plenty of time; there''s no need to rush.', '', ARRAY[]::TEXT[]),
('Sack', 'sack_us.mp3', 'verb', 'B1', 'to dismiss somebody from a job', '', 'She was sacked for refusing to work on Sundays.', '', ARRAY[]::TEXT[]),
('Sacred', 'sacred_us.mp3', 'adjective', 'B1', 'connected with God or a god; considered to be holy', '', 'a sacred image/shrine/temple', '', ARRAY[]::TEXT[]),
('Sacrifice', 'sacrifice_us.mp3', 'noun', 'B1', 'the fact of giving up something important or valuable to you in order to get or do something that seems more important; something that you give up in this way', '', 'The makers of the product assured us that there had been no sacrifice of quality.', '', ARRAY[]::TEXT[]),
('Sacrifice', 'sacrifice_us.mp3', 'verb', 'B1', 'to give up something that is important or valuable to you in order to get or do something that seems more important for yourself or for another person', '', 'sacrifice something for somebody/something, She sacrificed everything for her children.', '', ARRAY[]::TEXT[]),
('Sad', 'sad_us.mp3', 'adjective', 'B1', 'unhappy or showing unhappiness', '', 'sad to do something, We are very sad to hear that you are leaving.', '', ARRAY[]::TEXT[]),
('Sadly', 'sadly_us.mp3', 'adverb', 'B1', 'in a sad way', '', '‘I''m so sorry,’ she said sadly.', '', ARRAY[]::TEXT[]),
('Safe', 'safe_us.mp3', 'adjective', 'B1', 'protected from any danger, harm or loss', '', 'The children are quite safe here.', '', ARRAY[]::TEXT[]),
('Safety', 'safety_us.mp3', 'noun', 'B1', 'the state of being safe and protected from danger or harm', '', 'in safety, a place where children can play in safety', '', ARRAY[]::TEXT[]),
('Sail', 'sail_us.mp3', 'noun', 'B1', 'a sheet of strong cloth which the wind blows against to make a boat or ship travel through the water', '', 'As the boat moved down the river the wind began to fill the sails.', '', ARRAY[]::TEXT[]),
('Sail', 'sail_us.mp3', 'verb', 'B1', 'to travel on water using sails or an engine', '', '+ adv./prep., to sail into harbour', '', ARRAY[]::TEXT[]),
('Sailing', 'sailing_us.mp3', 'noun', 'B1', 'the sport or activity of travelling in a boat with sails', '', 'to go sailing', '', ARRAY[]::TEXT[]),
('Sailor', 'sailor_us.mp3', 'noun', 'B1', 'a person who works on a ship as a member of the crew', '', 'a crew of two officers and 13 sailors', '', ARRAY[]::TEXT[]),
('Saint', 'saint_us.mp3', 'noun', 'B1', 'a person that the Christian Church recognizes as being very holy, because of the way they have lived or died', '', 'St John', '', ARRAY[]::TEXT[]),
('Salad', 'salad_us.mp3', 'noun', 'B1', 'a mixture of raw vegetables such as lettuce, tomato and cucumber, usually served with other food as part of a meal', '', 'All main courses come with salad or vegetables.', '', ARRAY[]::TEXT[]),
('Salary', 'salary_us.mp3', 'noun', 'B1', 'money that employees receive for doing their job, especially professional employees or people working in an office, usually paid every month', '', 'an annual salary of $40 000', '', ARRAY[]::TEXT[]),
('Sale', 'sale_us.mp3', 'noun', 'B1', 'an act or the process of selling something', '', 'regulations governing the sale of alcoholic beverages', '', ARRAY[]::TEXT[]),
('Salt', 'salt_us.mp3', 'noun', 'B1', 'a white substance that is added to food to make it taste better or to preserve it. Salt is obtained from mines and is also found in seawater. It is sometimes called common salt to show that it is different from other chemical salts. Its chemical name is sodium chloride.', '', 'Pass the salt, please.', '', ARRAY[]::TEXT[]),
('Same', 'same_us.mp3', 'adjective', 'B1', 'exactly the one or ones referred to or mentioned; not different', '', 'We have lived in the same house for twenty years.', '', ARRAY[]::TEXT[]),
('Same', 'same_us.mp3', 'adverb', 'B1', 'in the same way', '', 'We treat boys exactly the same as girls.', '', ARRAY[]::TEXT[]),
('Same', 'same_us.mp3', 'pronoun', 'B1', 'the same thing or things', '', 'I would do the same again.', '', ARRAY[]::TEXT[]),
('Sample', 'sample_us.mp3', 'noun', 'B1', 'a number of people or things taken from a larger group and used in tests to provide information about the group', '', 'The interviews were given to a random sample of students.', '', ARRAY[]::TEXT[]),
('Sample', 'sample_us.mp3', 'verb', 'B1', 'to try a small amount of a particular food to see what it is like; to experience something for a short time to see what it is like', '', 'I sampled the delights of Greek cooking for the first time.', '', ARRAY[]::TEXT[]),
('Sanction', 'sanction_us.mp3', 'noun', 'B1', 'an official order that limits trade, contact, etc. with a particular country, in order to make it do something, such as obeying international law', '', 'Trade sanctions were imposed against any country that refused to sign the agreement.', '', ARRAY[]::TEXT[]),
('Sand', 'sand_us.mp3', 'noun', 'B1', 'a substance that consists of very small fine grains of rock. Sand is found on beaches, in deserts, etc.', '', 'a grain of sand', '', ARRAY[]::TEXT[]),
('Sandwich', 'sandwich_us.mp3', 'noun', 'B1', 'two slices of bread, often spread with butter, with a layer of meat, cheese, etc. between them', '', 'a ham/tuna/egg sandwich', '', ARRAY[]::TEXT[]),
('Satellite', 'satellite_us.mp3', 'noun', 'B1', 'an electronic device that is sent into space and moves around the earth or another planet. It is used for communicating by radio, television, etc. and for gathering information.', '', 'a weather/communications/spy satellite', '', ARRAY[]::TEXT[]),
('Satisfaction', 'satisfaction_us.mp3', 'noun', 'B1', 'the good feeling that you have when you have achieved something or when something that you wanted to happen does happen; something that gives you this feeling', '', 'to gain/get/derive satisfaction from something', '', ARRAY[]::TEXT[]),
('Satisfied', 'satisfied_us.mp3', 'adjective', 'B1', 'pleased because you have achieved something or because something that you wanted to happen has happened', '', 'a satisfied customer', '', ARRAY[]::TEXT[]),
('Satisfy', 'satisfy_us.mp3', 'verb', 'B1', 'to make somebody pleased by doing or giving them what they want', '', 'Nothing satisfies him—he''s always complaining.', '', ARRAY[]::TEXT[]),
('Saturday', 'Saturday_us.mp3', 'noun', 'B1', 'the day of the week after Friday and before Sunday', '', 'It''s Saturday today, isn''t it?', '', ARRAY[]::TEXT[]),
('Sauce', 'sauce_us.mp3', 'noun', 'B1', 'a thick liquid that is eaten with food to add taste to it', '', 'tomato/cranberry/chilli sauce', '', ARRAY[]::TEXT[]),
('Save', 'save_us.mp3', 'verb', 'B1', 'to keep somebody/something safe from death, harm, loss, etc.', '', 'save somebody/something, to save somebody’s life', '', ARRAY[]::TEXT[]),
('Saving', 'saving_us.mp3', 'noun', 'B1', 'an amount of something such as time or money that you do not need to use or spend', '', 'saving of something, Buy three and make a saving of 55p.', '', ARRAY[]::TEXT[]),
('Say', 'say_us.mp3', 'noun', 'B1', 'the right to influence something by giving your opinion before a decision is made', '', 'say (in something), We had no say in the decision to sell the company.', '', ARRAY[]::TEXT[]),
('Say', 'say_us.mp3', 'verb', 'B1', 'to speak or tell somebody something, using words', '', '+ speech, ‘Hello!’ she said.', '', ARRAY[]::TEXT[]),
('Scale', 'scale_us.mp3', 'noun', 'B1', 'the size or extent of something, especially when compared with something else', '', 'on a … scale, They entertain on a large scale (= they hold expensive parties with a lot of guests).', '', ARRAY[]::TEXT[]),
('Scan', 'scan_us.mp3', 'verb', 'B1', 'to look quickly but not very carefully at a document, etc.', '', 'scan something for something, I scanned the list quickly for my name.', '', ARRAY[]::TEXT[]),
('Scandal', 'scandal_us.mp3', 'noun', 'B1', 'behaviour or an event that people think is morally or legally wrong and causes public feelings of shock or anger', '', 'a series of sex scandals', '', ARRAY[]::TEXT[]),
('Scare', 'scare_us.mp3', 'noun', 'B1', 'a situation in which a lot of people are anxious or frightened about something', '', 'a health scare', '', ARRAY[]::TEXT[]),
('Scare', 'scare_us.mp3', 'verb', 'B1', 'to frighten somebody', '', 'scare somebody, You scared me.', '', ARRAY[]::TEXT[]),
('Scared', 'scared_us.mp3', 'adjective', 'B1', 'frightened of something or afraid that something bad might happen', '', 'The thieves got scared and ran away.', '', ARRAY[]::TEXT[]),
('Scary', 'scary_us.mp3', 'adjective', 'B1', 'frightening', '', 'It was a really scary moment.', '', ARRAY[]::TEXT[]),
('Scattered', 'scattered_us.mp3', 'adjective', 'B1', 'spread far apart over a wide area or over a long period of time', '', 'a few scattered settlements', '', ARRAY[]::TEXT[]),
('Scenario', 'scenario_us.mp3', 'noun', 'B1', 'a description of how things might happen in the future', '', 'Let me suggest a possible scenario.', '', ARRAY[]::TEXT[]),
('Scene', 'scene_us.mp3', 'noun', 'B1', 'the place where something happens, especially something unpleasant', '', 'the scene of the accident/crime/crash', '', ARRAY[]::TEXT[]),
('Sceptical', 'sceptical_us.mp3', 'adjective', 'B1', 'having doubts that a claim or statement is true or that something will happen', '', 'She looked highly sceptical.', '', ARRAY[]::TEXT[]),
('Schedule', 'schedule_us.mp3', 'noun', 'B1', 'a plan that lists all the work that you have to do and when you must do each thing', '', 'I have a hectic schedule for the next few days.', '', ARRAY[]::TEXT[]),
('Schedule', 'schedule_us.mp3', 'verb', 'B1', 'to arrange for something to happen at a particular time', '', 'schedule something for something, The meeting is scheduled for Friday afternoon.', '', ARRAY[]::TEXT[]),
('Scheme', 'scheme_us.mp3', 'noun', 'B1', 'a plan or system for doing or organizing something', '', 'a training scheme', '', ARRAY[]::TEXT[]),
('Scholar', 'scholar_us.mp3', 'noun', 'B1', 'a person who knows a lot about a particular subject because they have studied it in detail', '', 'a classical scholar', '', ARRAY[]::TEXT[]),
('Scholarship', 'scholarship_us.mp3', 'noun', 'B1', 'an amount of money given to somebody by an organization to help pay for their education', '', 'She won a scholarship to study at Stanford.', '', ARRAY[]::TEXT[]),
('School', 'school_us.mp3', 'noun', 'B1', 'a place where children go to be educated', '', 'My brother and I went to the same school.', '', ARRAY[]::TEXT[]),
('Science', 'science_us.mp3', 'noun', 'B1', 'knowledge about the structure and behaviour of the natural and physical world, based on facts that you can prove, for example by experiments', '', 'new developments in science and technology', '', ARRAY[]::TEXT[]),
('Scientific', 'scientific_us.mp3', 'adjective', 'B1', 'involving science; connected with science', '', 'a scientific discovery/theory/fact', '', ARRAY[]::TEXT[]),
('Scientist', 'scientist_us.mp3', 'noun', 'B1', 'a person who studies one or more of the natural sciences (= for example, physics, chemistry or biology)', '', 'a research scientist', '', ARRAY[]::TEXT[]),
('Scope', 'scope_us.mp3', 'noun', 'B1', 'the opportunity or ability to do or achieve something', '', 'scope for something, There''s still plenty of scope for improvement.', '', ARRAY[]::TEXT[]),
('Score', 'score_us.mp3', 'noun', 'B1', 'the number of points, goals, etc. scored by each player or team in a game or competition', '', 'a high/low score', '', ARRAY[]::TEXT[]),
('Score', 'score_us.mp3', 'verb', 'B1', 'to win points, goals, etc. in a game or competition', '', 'Fraser scored again in the second half.', '', ARRAY[]::TEXT[]),
('Scratch', 'scratch_us.mp3', 'noun', 'B1', 'a mark, a cut or an injury made by scratching somebody’s skin or the surface of something', '', 'Her hands were covered in scratches from the brambles.', '', ARRAY[]::TEXT[]),
('Scratch', 'scratch_us.mp3', 'verb', 'B1', 'to rub your skin with your nails, usually because it is itching', '', 'scratch something, John yawned and scratched his chin.', '', ARRAY[]::TEXT[]),
('Scream', 'scream_us.mp3', 'noun', 'B1', 'a loud high shout made by somebody who is hurt, frightened, excited, etc.; a loud high noise', '', 'scream of something, She let out a scream of pain.', '', ARRAY[]::TEXT[]),
('Scream', 'scream_us.mp3', 'verb', 'B1', 'to give a loud, high shout, because you are hurt, frightened, excited, etc.', '', 'There was a bang and I heard someone scream.', '', ARRAY[]::TEXT[]),
('Screen', 'screen_us.mp3', 'noun', 'B1', 'the flat surface at the front of a television, computer, or other electronic device, on which you see pictures or information', '', 'a computer screen', '', ARRAY[]::TEXT[]),
('Screen', 'screen_us.mp3', 'verb', 'B1', 'to show a film, etc. in a cinema or on television', '', 'a list of films to be screened as part of the festival', '', ARRAY[]::TEXT[]),
('Screening', 'screening_us.mp3', 'noun', 'B1', 'the act of showing a film or television programme', '', 'This will be the movie''s first screening in this country.', '', ARRAY[]::TEXT[]),
('Screw', 'screw_us.mp3', 'noun', 'B1', 'a thin pointed piece of metal like a nail with a raised spiral line (called a thread) along it and a line or cross cut into its head. Screws are turned and pressed into wood, metal, etc. with a screwdriver in order to fasten two things together.', '', 'One of the screws is loose.', '', ARRAY[]::TEXT[]),
('Screw', 'screw_us.mp3', 'verb', 'B1', 'to fasten one thing to another or make something tight with a screw or screws', '', 'The bookcase is screwed to the wall.', '', ARRAY[]::TEXT[]),
('Script', 'script_us.mp3', 'noun', 'B1', 'a written text of a play, film, broadcast, talk, etc.', '', 'That line isn''t in the original script.', '', ARRAY[]::TEXT[]),
('Scrutiny', 'scrutiny_us.mp3', 'noun', 'B1', 'careful and complete examination', '', 'Her argument doesn''t really stand up to scrutiny.', '', ARRAY[]::TEXT[]),
('Sculpture', 'sculpture_us.mp3', 'noun', 'B1', 'a work of art that is a solid figure or object made by carving or shaping wood, stone, clay, metal, etc.', '', 'a marble sculpture of Venus', '', ARRAY[]::TEXT[]),
('Sea', 'sea_us.mp3', 'noun', 'B1', 'the salt water that covers most of the earth’s surface and surrounds its continents and islands', '', 'The waste was dumped in the sea.', '', ARRAY[]::TEXT[]),
('Seal', 'seal_us.mp3', 'noun', 'B1', 'an official design or mark, stamped on a document to show that it is real and carries the authority of a particular person or organization', '', 'The letter bore the president''s seal.', '', ARRAY[]::TEXT[]),
('Seal', 'seal_us.mp3', 'verb', 'B1', 'to close an envelope, etc. by sticking the edges of the opening together', '', 'Make sure you''ve signed the cheque before sealing the envelope.', '', ARRAY[]::TEXT[]),
('Search', 'search_us.mp3', 'noun', 'B1', 'an attempt to find somebody/something, especially by looking carefully for them/it', '', 'search for somebody/something, a long search for the murder weapon', '', ARRAY[]::TEXT[]),
('Search', 'search_us.mp3', 'verb', 'B1', 'to look carefully for something/somebody; to examine a particular place when looking for something/somebody', '', 'search for something/somebody, She searched in vain for her passport.', '', ARRAY[]::TEXT[]),
('Season', 'season_us.mp3', 'noun', 'B1', 'any of the four main periods of the year: spring, summer, autumn and winter', '', 'the changing seasons', '', ARRAY[]::TEXT[]),
('Seat', 'seat_us.mp3', 'noun', 'B1', 'a place where you can sit, for example a chair', '', 'She sat back in her seat.', '', ARRAY[]::TEXT[]),
('Seat', 'seat_us.mp3', 'verb', 'B1', 'to give somebody a place to sit; to sit down in a place', '', 'Please wait to be seated (= in a restaurant, etc.).', '', ARRAY[]::TEXT[]),
('Second', 'second_us.mp3', 'adverb', 'B1', 'after one other person or thing in order or importance', '', 'She came second in the marathon.', '', ARRAY[]::TEXT[]),
('Second', 'second_us.mp3', 'determiner', 'B1', 'happening or coming next after the first in a series of similar things or people; 2nd', '', 'This is the second time it''s happened.', '', ARRAY[]::TEXT[]),
('Second', 'second_us.mp3', 'noun', 'B1', 'a unit for measuring time. There are 60 seconds in one minute.', '', 'in… seconds, She can run 100 metres in just over 11 seconds.', '', ARRAY[]::TEXT[]),
('Second', 'second_us.mp3', 'ordinal number', 'B1', 'happening or coming next after the first in a series of similar things or people; 2nd', '', 'This is the second time it''s happened.', '', ARRAY[]::TEXT[]),
('Secondary', 'secondary_us.mp3', 'adjective', 'B1', 'connected with teaching children of 11–18 years', '', 'secondary teachers', '', ARRAY[]::TEXT[]),
('Secondly', 'secondly_us.mp3', 'adverb', 'B1', 'used to introduce the second of a list of points you want to make in a speech or piece of writing', '', 'Firstly, it''s expensive, and secondly, it''s too slow.', '', ARRAY[]::TEXT[]),
('Secret', 'secret_us.mp3', 'adjective', 'B1', 'known about by only a few people; kept hidden from others', '', 'secret information/meetings/talks', '', ARRAY[]::TEXT[]),
('Secret', 'secret_us.mp3', 'noun', 'B1', 'something that is known about by only a few people and not told to others', '', 'Can you keep a secret?', '', ARRAY[]::TEXT[]),
('Secretary', 'secretary_us.mp3', 'noun', 'B1', 'a person who works in an office, working for another person, dealing with mail and phone calls, keeping records, arranging meetings with people, etc.', '', 'a legal/medical secretary', '', ARRAY[]::TEXT[]),
('Section', 'section_us.mp3', 'noun', 'B1', 'any of the parts into which something is divided', '', 'section of something, That section of the road is still closed.', '', ARRAY[]::TEXT[]),
('Sector', 'sector_us.mp3', 'noun', 'B1', 'a part of an area of activity, especially of a country’s economy', '', 'the service/banking/manufacturing/financial sector', '', ARRAY[]::TEXT[]),
('Secular', 'secular_us.mp3', 'adjective', 'B1', 'not connected with spiritual or religious matters', '', 'secular music', '', ARRAY[]::TEXT[]),
('Secure', 'secure_us.mp3', 'adjective', 'B1', 'likely to continue or be successful for a long time', '', 'a secure job/income', '', ARRAY[]::TEXT[]),
('Secure', 'secure_us.mp3', 'verb', 'B1', 'to obtain or achieve something, especially when this means using a lot of effort', '', 'secure something, to secure a contract/deal/funding', '', ARRAY[]::TEXT[]),
('Security', 'security_us.mp3', 'noun', 'B1', 'the activities involved in protecting a country, building or person against attack, danger, etc.', '', 'national/homeland security (= the defence of a country)', '', ARRAY[]::TEXT[]),
('See', 'see_us.mp3', 'verb', 'B1', 'to become aware of somebody/something by using your eyes', '', 'see somebody/something, She looked for him but couldn''t see him in the crowd.', '', ARRAY[]::TEXT[]),
('Seed', 'seed_us.mp3', 'noun', 'B1', 'the small hard part produced by a plant, from which a new plant can grow', '', 'a packet of wild flower seeds', '', ARRAY[]::TEXT[]),
('Seek', 'seek_us.mp3', 'verb', 'B1', 'to look for something/somebody', '', 'seek something/somebody, Drivers are advised to seek alternative routes.', '', ARRAY[]::TEXT[]),
('Seeker', 'seeker_us.mp3', 'noun', 'B1', 'a person who is trying to find or get the thing mentioned', '', 'an attention/a publicity seeker', '', ARRAY[]::TEXT[]),
('Seem', 'seem_us.mp3', 'linking verb', 'B1', 'to give the impression of being or doing something', '', '+ adj., You seem happy.', '', ARRAY[]::TEXT[]),
('Seemingly', 'seemingly_us.mp3', 'adverb', 'B1', 'in a way that appears to be true but may in fact not be', '', 'a seemingly stupid question', '', ARRAY[]::TEXT[]),
('Segment', 'segment_us.mp3', 'noun', 'B1', 'a part of something that is separate from the other parts or can be considered separately', '', 'She cleaned a small segment of the painting.', '', ARRAY[]::TEXT[]),
('Seize', 'seize_us.mp3', 'verb', 'B1', 'to take somebody/something in your hand suddenly and using force', '', 'seize something from somebody, She tried to seize the gun from him.', '', ARRAY[]::TEXT[]),
('Seldom', 'seldom_us.mp3', 'adverb', 'B1', 'not often', '', 'He had seldom seen a child with so much talent.', '', ARRAY[]::TEXT[]),
('Select', 'select_us.mp3', 'verb', 'B1', 'to choose somebody/something from a group of people or things, usually according to a system', '', 'select somebody/something for something, He hasn''t been selected for the team.', '', ARRAY[]::TEXT[]),
('Selection', 'selection_us.mp3', 'noun', 'B1', 'the process of choosing somebody/something from a group of people or things, usually according to a system', '', 'She took a long time to make her selection.', '', ARRAY[]::TEXT[]),
('Selective', 'selective_us.mp3', 'adjective', 'B1', 'affecting or involving only a small number of people or things from a larger group', '', 'the selective breeding of cattle', '', ARRAY[]::TEXT[]),
('Self', 'self_us.mp3', 'noun', 'B1', 'the type of person you are, especially the way you normally behave, look or feel', '', 'You''ll soon be feeling your old self again (= feeling well or happy again).', '', ARRAY[]::TEXT[]),
('Sell', 'sell_us.mp3', 'verb', 'B1', 'to give something to somebody in exchange for money', '', 'sell (something), I recently sold my bike.', '', ARRAY[]::TEXT[]),
('Seminar', 'seminar_us.mp3', 'noun', 'B1', 'a class at a university or college when a small group of students and a teacher discuss or study a particular topic', '', 'Teaching is by lectures and seminars.', '', ARRAY[]::TEXT[]),
('Senator', 'senator_us.mp3', 'noun', 'B1', 'a member of a senate', '', 'Senator McCarthy', '', ARRAY[]::TEXT[]),
('Send', 'send_us.mp3', 'verb', 'B1', 'to make something go or be taken to a place, especially by post, email, radio, etc.', '', 'send something, She sent a letter of support.', '', ARRAY[]::TEXT[]),
('Senior', 'senior_us.mp3', 'adjective', 'B1', 'high in rank or status; higher in rank or status than others', '', 'a senior official/officer/manager/executive', '', ARRAY[]::TEXT[]),
('Sensation', 'sensation_us.mp3', 'noun', 'B1', 'a feeling that you get when something affects your body', '', 'a tingling/burning sensation', '', ARRAY[]::TEXT[]),
('Sense', 'sense_us.mp3', 'noun', 'B1', 'an understanding about something; an ability to judge something', '', 'One of the most important things in a partner is a sense of humour (= the ability to find things funny or make people laugh).', '', ARRAY[]::TEXT[]),
('Sense', 'sense_us.mp3', 'verb', 'B1', 'to become aware of something even though you cannot see it, hear it, etc.', '', 'sense something, Sensing danger, they started to run.', '', ARRAY[]::TEXT[]),
('Sensible', 'sensible_us.mp3', 'adjective', 'B1', 'able to make good judgements based on reason and experience rather than emotion; practical', '', 'She''s a sensible sort of person.', '', ARRAY[]::TEXT[]),
('Sensitive', 'sensitive_us.mp3', 'adjective', 'B1', 'aware of and able to understand other people and their feelings', '', 'a sensitive and caring man', '', ARRAY[]::TEXT[]),
('Sensitivity', 'sensitivity_us.mp3', 'noun', 'B1', 'the ability to understand other people’s feelings', '', 'sensitivity to the needs of children', '', ARRAY[]::TEXT[]),
('Sentence', 'sentence_us.mp3', 'noun', 'B1', 'a set of words expressing a statement, a question or an order, usually containing a subject and a verb. In written English sentences begin with a capital letter and end with a full stop/period (.), a question mark (?) or an exclamation mark (!).', '', 'Does the sentence contain an adverb?', '', ARRAY[]::TEXT[]),
('Sentence', 'sentence_us.mp3', 'verb', 'B1', 'to say officially in court that somebody is to receive a particular punishment', '', 'sentence somebody to something, He sentenced the defendant to life in prison.', '', ARRAY[]::TEXT[]),
('Sentiment', 'sentiment_us.mp3', 'noun', 'B1', 'a feeling or an opinion, especially one based on emotions', '', 'the spread of nationalist sentiments', '', ARRAY[]::TEXT[]),
('Separate', 'separate_us.mp3', 'adjective', 'B1', 'forming a unit by itself; not joined to something else', '', 'They have begun to sleep in separate rooms.', '', ARRAY[]::TEXT[]),
('Separate', 'separate_us.mp3', 'verb', 'B1', 'to divide into different parts or groups; to divide things into different parts or groups', '', 'Stir the sauce constantly so that it does not separate.', '', ARRAY[]::TEXT[]),
('Separation', 'separation_us.mp3', 'noun', 'B1', 'the act of separating people or things; the state of being separate', '', 'separation from somebody/something, the state’s eventual separation from the federation', '', ARRAY[]::TEXT[]),
('September', 'September_us.mp3', 'noun', 'B1', 'the 9th month of the year, between August and October', '', 'She was born in September.', '', ARRAY[]::TEXT[]),
('Sequence', 'sequence_us.mp3', 'noun', 'B1', 'a set of events, actions, numbers, etc. which have a particular order and which lead to a particular result', '', 'He described the sequence of events leading up to the robbery.', '', ARRAY[]::TEXT[]),
('Serial', 'serial_us.mp3', 'adjective', 'B1', 'doing the same thing in the same way several times; done in the same way several times', '', 'a serial rapist', '', ARRAY[]::TEXT[]),
('Series', 'series_us.mp3', 'noun', 'B1', 'a set of television or radio programmes or podcasts that deal with the same subject or that have the same characters', '', 'The first episode of the new series is on Saturday.', '', ARRAY[]::TEXT[]),
('Serious', 'serious_us.mp3', 'adjective', 'B1', 'bad or dangerous', '', 'a serious illness/offence/crime', '', ARRAY[]::TEXT[]),
('Seriously', 'seriously_us.mp3', 'adverb', 'B1', 'in a serious way', '', 'to be seriously ill/injured/wounded/hurt', '', ARRAY[]::TEXT[]),
('Servant', 'servant_us.mp3', 'noun', 'B1', 'a person who works in another person’s house, and cooks, cleans, etc. for them', '', 'a domestic servant', '', ARRAY[]::TEXT[]),
('Serve', 'serve_us.mp3', 'verb', 'B1', 'to give somebody food or drink, for example at a restaurant or during a meal', '', 'serve (something), Breakfast is served between 7 and 10 a.m.', '', ARRAY[]::TEXT[]),
('Service', 'service_us.mp3', 'noun', 'B1', 'a system that provides something that the public needs, organized by the government or a private company', '', 'the ambulance/bus/postal service', '', ARRAY[]::TEXT[]),
('Session', 'session_us.mp3', 'noun', 'B1', 'a period of time that is spent doing a particular activity', '', 'a training/practice session', '', ARRAY[]::TEXT[]),
('Set', 'set_us.mp3', 'noun', 'B1', 'a group of similar things that belong together in some way', '', 'a set of six chairs', '', ARRAY[]::TEXT[]),
('Set', 'set_us.mp3', 'verb', 'B1', 'to prepare or arrange something so that it is ready for use or in position', '', 'set something, Have you set the alarm clock?', '', ARRAY[]::TEXT[]),
('Set-up', 'set-up_us.mp3', 'noun', 'B1', 'a way of organizing something; a system', '', 'I''ve only been here a couple of weeks and I don''t really know the set-up.', '', ARRAY[]::TEXT[]),
('Setting', 'setting_us.mp3', 'noun', 'B1', 'an environment where something is located; the place at which something happens', '', 'a rural/an ideal/a beautiful/an idyllic setting', '', ARRAY[]::TEXT[]),
('Settle', 'settle_us.mp3', 'verb', 'B1', 'to put an end to an argument or a disagreement', '', 'settle something, to settle a dispute/a matter/an issue', '', ARRAY[]::TEXT[]),
('Settlement', 'settlement_us.mp3', 'noun', 'B1', 'an official agreement that ends an argument between two people or groups', '', 'to negotiate a peace settlement', '', ARRAY[]::TEXT[]),
('Settler', 'settler_us.mp3', 'noun', 'B1', 'a person who goes to live in a new country or region', '', 'Most of the settlers came from England.', '', ARRAY[]::TEXT[]),
('Seven', 'seven_us.mp3', 'number', 'B1', '7', '', 'There are seven cookies left.', '', ARRAY[]::TEXT[]),
('Several', 'several_us.mp3', 'determiner', 'B1', 'more than two but not very many', '', 'Several letters arrived this morning.', '', ARRAY[]::TEXT[]),
('Several', 'several_us.mp3', 'pronoun', 'B1', 'more than two but not very many', '', 'Several letters arrived this morning.', '', ARRAY[]::TEXT[]),
('Severe', 'severe_us.mp3', 'adjective', 'B1', 'extremely bad or serious', '', 'His injuries are severe.', '', ARRAY[]::TEXT[]),
('Severely', 'severely_us.mp3', 'adverb', 'B1', 'very badly or seriously', '', 'severely injured', '', ARRAY[]::TEXT[]),
('Sex', 'sex_us.mp3', 'noun', 'B1', 'the state of being male or female', '', 'How can you tell what sex a fish is?', '', ARRAY[]::TEXT[]),
('Sexual', 'sexual_us.mp3', 'adjective', 'B1', 'connected with the physical activity of sex', '', 'sexual behaviour/activity/desire', '', ARRAY[]::TEXT[]),
('Sexuality', 'sexuality_us.mp3', 'noun', 'B1', 'the feelings and activities connected with a person’s sexual desires', '', 'He was confused about his sexuality.', '', ARRAY[]::TEXT[]),
('Sexy', 'sexy_us.mp3', 'adjective', 'B1', 'sexually attractive', '', 'the sexy lead singer', '', ARRAY[]::TEXT[]),
('Shade', 'shade_us.mp3', 'noun', 'B1', 'an area that is dark and cool under or behind something, for example a tree or building, because the sun’s light does not get to it', '', 'shade of something, The shade of the pine tree provided some protection from the sun.', '', ARRAY[]::TEXT[]),
('Shadow', 'shadow_us.mp3', 'noun', 'B1', 'the dark shape that somebody/something’s form makes on a surface, for example on the ground, when they are between the light and the surface', '', 'The children were having fun, chasing each other''s shadows.', '', ARRAY[]::TEXT[]),
('Shake', 'shake_us.mp3', 'noun', 'B1', 'an act of shaking somebody/something', '', 'She gave him a shake to wake him.', '', ARRAY[]::TEXT[]),
('Shake', 'shake_us.mp3', 'verb', 'B1', 'to move or make somebody/something move with short quick movements from side to side or up and down', '', 'The whole house shakes when a train goes past.', '', ARRAY[]::TEXT[]),
('Shall', 'shall_us.mp3', 'modal verb', 'B1', 'used with I and we for talking about or predicting the future', '', 'This time next week I shall be in Scotland.', '', ARRAY[]::TEXT[]),
('Shallow', 'shallow_us.mp3', 'adjective', 'B1', 'not having much distance between the top or surface and the bottom', '', 'a shallow dish/pan/bowl', '', ARRAY[]::TEXT[]),
('Shame', 'shame_us.mp3', 'noun', 'B1', 'used to say that something is a cause for feeling sad or disappointed', '', 'She''s retiring because of ill health, which is a great shame.', '', ARRAY[]::TEXT[]),
('Shape', 'shape_us.mp3', 'noun', 'B1', 'the form of the outer edges or surfaces of something; an example of something that has a particular form', '', 'a rectangular/spherical/cylindrical shape', '', ARRAY[]::TEXT[]),
('Shape', 'shape_us.mp3', 'verb', 'B1', 'to make something into a particular shape', '', 'shape A into B, Shape the dough into a ball.', '', ARRAY[]::TEXT[]),
('Shaped', 'shaped_us.mp3', 'adjective', 'B1', 'having the type of shape mentioned', '', 'a huge balloon shaped like a giant cow', '', ARRAY[]::TEXT[]),
('Share', 'share_us.mp3', 'noun', 'B1', 'one part of something that is divided between two or more people', '', 'share of something, Next year we hope to have a greater share of the market.', '', ARRAY[]::TEXT[]),
('Share', 'share_us.mp3', 'verb', 'B1', 'to have, use or experience something at the same time as somebody else', '', 'There isn''t an empty table. Would you mind sharing?', '', ARRAY[]::TEXT[]),
('Shareholder', 'shareholder_us.mp3', 'noun', 'B1', 'an owner of shares in a company or business', '', 'the major shareholders in the company', '', ARRAY[]::TEXT[]),
('Sharp', 'sharp_us.mp3', 'adjective', 'B1', 'having a fine edge or point, especially of something that can cut or make a hole in something', '', 'a sharp knife', '', ARRAY[]::TEXT[]),
('Shatter', 'shatter_us.mp3', 'verb', 'B1', 'to suddenly break into small pieces; to make something suddenly break into small pieces', '', 'shatter (into something), He dropped the vase and it shattered into pieces on the floor.', '', ARRAY[]::TEXT[]),
('She', 'she_us.mp3', 'pronoun', 'B1', 'a female person or animal that has already been mentioned or is easily identified', '', '‘What does your sister do?’ ‘She''s a dentist.’', '', ARRAY[]::TEXT[]),
('Shed', 'shed_us.mp3', 'verb', 'B1', 'to get rid of something that is no longer wanted', '', 'The factory is shedding a large number of jobs.', '', ARRAY[]::TEXT[]),
('Sheep', 'sheep_us.mp3', 'noun', 'B1', 'an animal with a thick coat, kept on farms for its meat (called mutton or lamb) or its wool', '', 'a flock of sheep', '', ARRAY[]::TEXT[]),
('Sheer', 'sheer_us.mp3', 'adjective', 'B1', 'used to emphasize the size, degree or amount of something', '', 'The area is under threat from the sheer number of tourists using it.', '', ARRAY[]::TEXT[]),
('Sheet', 'sheet_us.mp3', 'noun', 'B1', 'a large piece of thin cloth used on a bed to lie on or lie under', '', 'Have you changed the sheets (= put clean sheets on the bed)?', '', ARRAY[]::TEXT[]),
('Shelf', 'shelf_us.mp3', 'noun', 'B1', 'a flat board, made of wood, metal, glass, etc., fixed to the wall or forming part of a cupboard, bookcase, etc., for things to be placed on', '', 'I helped him put up some shelves in his bedroom.', '', ARRAY[]::TEXT[]),
('Shell', 'shell_us.mp3', 'noun', 'B1', 'the hard outer part of eggs, nuts, some seeds, and some animals', '', 'We collected shells on the beach.', '', ARRAY[]::TEXT[]),
('Shelter', 'shelter_us.mp3', 'noun', 'B1', 'the fact of having a place to live or stay, considered as a basic human need', '', 'Human beings need food, clothing and shelter.', '', ARRAY[]::TEXT[]),
('Shelter', 'shelter_us.mp3', 'verb', 'B1', 'to give somebody/something a place where they are protected from the weather or from danger; to protect somebody/something', '', 'shelter somebody/something from somebody/something, Trees shelter the house from the wind.', '', ARRAY[]::TEXT[]),
('Shift', 'shift_us.mp3', 'noun', 'B1', 'a period of time worked by a group of workers who start work as another group finishes', '', 'to work a shift', '', ARRAY[]::TEXT[]),
('Shift', 'shift_us.mp3', 'verb', 'B1', 'to move, or move something, from one position or place to another', '', 'Lydia shifted uncomfortably in her chair.', '', ARRAY[]::TEXT[]),
('Shine', 'shine_us.mp3', 'verb', 'B1', 'to produce or reflect light; to be bright', '', 'The sun shone brightly in a cloudless sky.', '', ARRAY[]::TEXT[]),
('Shiny', 'shiny_us.mp3', 'adjective', 'B1', 'smooth and bright; reflecting the light', '', 'shiny black hair', '', ARRAY[]::TEXT[]),
('Ship', 'ship_us.mp3', 'noun', 'B1', 'a large boat that carries people or goods by sea', '', 'The yard builds ships for the Navy.', '', ARRAY[]::TEXT[]),
('Ship', 'ship_us.mp3', 'verb', 'B1', 'to send or transport somebody/something by ship or by another means of transport', '', 'The company ships its goods all over the world.', '', ARRAY[]::TEXT[]),
('Shipping', 'shipping_us.mp3', 'noun', 'B1', 'ships in general or considered as a group', '', 'The canal is open to shipping.', '', ARRAY[]::TEXT[]),
('Shirt', 'shirt_us.mp3', 'noun', 'B1', 'a piece of clothing worn on the upper part of the body, made of light cloth, with sleeves and usually with a collar and buttons down the front', '', 'to wear a shirt', '', ARRAY[]::TEXT[]),
('Shock', 'shock_us.mp3', 'noun', 'B1', 'a strong feeling of surprise as a result of something happening, especially something unpleasant; the event that causes this feeling', '', 'I got a terrible shock the other day.', '', ARRAY[]::TEXT[]),
('Shock', 'shock_us.mp3', 'verb', 'B1', 'to surprise and upset somebody', '', 'shock somebody, President Kennedy''s assassination in Dallas on November 22, 1963, shocked the world.', '', ARRAY[]::TEXT[]),
('Shocked', 'shocked_us.mp3', 'adjective', 'B1', 'surprised and upset; showing that somebody feels surprised and upset', '', 'I was quite shocked when I found out what he''d done.', '', ARRAY[]::TEXT[]),
('Shocking', 'shocking_us.mp3', 'adjective', 'B1', 'that offends or upsets people; that is morally wrong', '', 'shocking behaviour', '', ARRAY[]::TEXT[]),
('Shoe', 'shoe_us.mp3', 'noun', 'B1', 'one of a pair of objects usually made of leather or plastic that you wear on your feet', '', 'a pair of shoes', '', ARRAY[]::TEXT[]),
('Shoot', 'shoot_us.mp3', 'noun', 'B1', 'the part that grows up from the ground when a plant starts to grow; a new part that grows on plants or trees', '', 'new green shoots', '', ARRAY[]::TEXT[]),
('Shoot', 'shoot_us.mp3', 'verb', 'B1', 'to fire a gun or other weapon; to fire something from a weapon', '', 'Don''t shoot—I surrender.', '', ARRAY[]::TEXT[]),
('Shooting', 'shooting_us.mp3', 'noun', 'B1', 'a situation in which a person is shot with a gun', '', 'Terrorist groups claimed responsibility for the shootings and bomb attacks.', '', ARRAY[]::TEXT[]),
('Shop', 'shop_us.mp3', 'noun', 'B1', 'a building or part of a building where you can buy goods or services', '', 'to open/close/run a shop', '', ARRAY[]::TEXT[]),
('Shop', 'shop_us.mp3', 'verb', 'B1', 'to buy things in shops', '', 'I shop there from time to time.', '', ARRAY[]::TEXT[]),
('Shopping', 'shopping_us.mp3', 'noun', 'B1', 'the activity of going to shops and buying things or ordering them online', '', 'to go shopping', '', ARRAY[]::TEXT[]),
('Shore', 'shore_us.mp3', 'noun', 'B1', 'the land along the edge of the sea, the ocean or a lake', '', 'a rocky/sandy shore', '', ARRAY[]::TEXT[]),
('Short', 'short_us.mp3', 'adjective', 'B1', 'measuring or covering a small length or distance, or a smaller length or distance than usual', '', 'He had short curly hair.', '', ARRAY[]::TEXT[]),
('Short-term', 'short-term_us.mp3', 'adjective', 'B1', 'lasting a short time; designed only for a short period of time in the future', '', 'a short-term loan', '', ARRAY[]::TEXT[]),
('Shortage', 'shortage_us.mp3', 'noun', 'B1', 'a situation when there is not enough of the people or things that are needed', '', 'food/housing/water shortages', '', ARRAY[]::TEXT[]),
('Shortly', 'shortly_us.mp3', 'adverb', 'B1', 'a short time; not long', '', 'She arrived shortly after us.', '', ARRAY[]::TEXT[]),
('Shot', 'shot_us.mp3', 'noun', 'B1', 'the act of firing a gun; the sound this makes', '', 'We heard some shots in the distance.', '', ARRAY[]::TEXT[]),
('Should', 'should_us.mp3', 'modal verb', 'B1', 'used to show what is right, appropriate, etc., especially when criticizing somebody’s actions', '', 'You shouldn''t drink and drive.', '', ARRAY[]::TEXT[]),
('Shoulder', 'shoulder_us.mp3', 'noun', 'B1', 'either of the two parts of the body between the top of each arm and the neck', '', 'your left/right shoulder', '', ARRAY[]::TEXT[]),
('Shout', 'shout_us.mp3', 'noun', 'B1', 'a loud cry of anger, fear, excitement, etc.', '', 'angry shouts', '', ARRAY[]::TEXT[]),
('Shout', 'shout_us.mp3', 'verb', 'B1', 'to say something in a loud voice; to speak loudly/angrily to somebody', '', 'Stop shouting and listen!', '', ARRAY[]::TEXT[]),
('Show', 'show_us.mp3', 'noun', 'B1', 'a programme on television or the radio', '', 'Millions of people watch the show.', '', ARRAY[]::TEXT[]),
('Show', 'show_us.mp3', 'verb', 'B1', 'to make something clear; to prove something', '', 'show (that)…, The figures clearly show that her claims are false.', '', ARRAY[]::TEXT[]),
('Shower', 'shower_us.mp3', 'noun', 'B1', 'a piece of equipment producing a flow of water that you stand under to wash yourself; the small room or part of a room that contains a shower', '', 'in the shower, He''s in the shower.', '', ARRAY[]::TEXT[]),
('Shrink', 'shrink_us.mp3', 'verb', 'B1', 'to become smaller, especially when washed in water that is too hot; to make clothes, cloth, etc. smaller in this way', '', 'My sweater shrank in the wash.', '', ARRAY[]::TEXT[]),
('Shrug', 'shrug_us.mp3', 'verb', 'B1', 'to raise your shoulders and then drop them to show that you do not know or care about something', '', 'Sam shrugged and said nothing.', '', ARRAY[]::TEXT[]),
('Shut', 'shut_us.mp3', 'adjective', 'B1', 'not open', '', 'The door was shut.', '', ARRAY[]::TEXT[]),
('Shut', 'shut_us.mp3', 'verb', 'B1', 'to close something; to become closed', '', 'The window won''t shut.', '', ARRAY[]::TEXT[]),
('Shy', 'shy_us.mp3', 'adjective', 'B1', 'nervous or embarrassed about meeting and speaking to other people', '', 'He is not exactly the shy and retiring type.', '', ARRAY[]::TEXT[]),
('Sibling', 'sibling_us.mp3', 'noun', 'B1', 'a brother or sister', '', 'squabbles between siblings', '', ARRAY[]::TEXT[]),
('Sick', 'sick_us.mp3', 'adjective', 'B1', 'physically or mentally ill', '', 'a sick child', '', ARRAY[]::TEXT[]),
('Side', 'side_us.mp3', 'noun', 'B1', 'either of the two halves of a surface, an object or an area that is divided by an imaginary central line', '', 'the right side of the brain', '', ARRAY[]::TEXT[]),
('Sigh', 'sigh_us.mp3', 'noun', 'B1', 'an act or the sound of sighing', '', 'to give/heave/let out a sigh', '', ARRAY[]::TEXT[]),
('Sigh', 'sigh_us.mp3', 'verb', 'B1', 'to take and then let out a long deep breath that can be heard, to show that you are disappointed, sad, tired, etc.', '', 'He sighed deeply at the thought.', '', ARRAY[]::TEXT[]),
('Sight', 'sight_us.mp3', 'noun', 'B1', 'the ability to see', '', 'to lose your sight (= to become blind)', '', ARRAY[]::TEXT[]),
('Sign', 'sign_us.mp3', 'noun', 'B1', 'an event, an action, a fact, etc. that shows that something exists, is happening or may happen in the future', '', 'Looking back, I should have seen the signs.', '', ARRAY[]::TEXT[]),
('Sign', 'sign_us.mp3', 'verb', 'B1', 'to write your name on a document, letter, etc. to show that you have written it, that you agree with what it says, or that it is real', '', 'Sign here, please.', '', ARRAY[]::TEXT[]),
('Signal', 'signal_us.mp3', 'noun', 'B1', 'a movement or sound that you make to give somebody information, instructions, a warning, etc.', '', 'a danger/warning/distress signal', '', ARRAY[]::TEXT[]),
('Signal', 'signal_us.mp3', 'verb', 'B1', 'to make a movement or sound to give somebody a message, an order, etc.', '', 'Don''t fire until I signal.', '', ARRAY[]::TEXT[]),
('Signature', 'signature_us.mp3', 'noun', 'B1', 'your name as you usually write it, for example at the end of a letter', '', 'Someone had forged her signature on the cheque.', '', ARRAY[]::TEXT[]),
('Significance', 'significance_us.mp3', 'noun', 'B1', 'the importance of something, especially when this has an effect on what happens in the future', '', 'a decision of major political significance', '', ARRAY[]::TEXT[]),
('Significant', 'significant_us.mp3', 'adjective', 'B1', 'large or important enough to have an effect or to be noticed', '', 'There are no significant differences between the two groups of students.', '', ARRAY[]::TEXT[]),
('Significantly', 'significantly_us.mp3', 'adverb', 'B1', 'in a way that is large or important enough to have an effect on something or to be noticed', '', 'significantly higher/lower/larger/smaller', '', ARRAY[]::TEXT[]),
('Silence', 'silence_us.mp3', 'noun', 'B1', 'a complete lack of noise or sound', '', 'Their footsteps echoed in the silence.', '', ARRAY[]::TEXT[]),
('Silent', 'silent_us.mp3', 'adjective', 'B1', 'where there is little or no sound; making little or no sound', '', 'At last the traffic fell silent.', '', ARRAY[]::TEXT[]),
('Silk', 'silk_us.mp3', 'noun', 'B1', 'fine soft thread produced by silkworms', '', 'The caterpillar spins the silk around its entire body.', '', ARRAY[]::TEXT[]),
('Silly', 'silly_us.mp3', 'adjective', 'B1', 'showing a lack of thought, understanding, or judgement', '', 'a silly idea/question/name', '', ARRAY[]::TEXT[]),
('Silver', 'silver_us.mp3', 'adjective', 'B1', 'shiny grey-white in colour', '', 'a silver car', '', ARRAY[]::TEXT[]),
('Silver', 'silver_us.mp3', 'noun', 'B1', 'a chemical element. Silver is a shiny, grey-white precious metal used for making coins, jewellery, beautiful objects, etc.', '', 'a silver ring/chain', '', ARRAY[]::TEXT[]),
('Similar', 'similar_us.mp3', 'adjective', 'B1', 'like somebody/something but not exactly the same', '', 'We have very similar interests.', '', ARRAY[]::TEXT[]),
('Similarity', 'similarity_us.mp3', 'noun', 'B1', 'the state of being similar to somebody/something but not exactly the same', '', 'similarity between A and B, The report highlights the similarity between the two groups.', '', ARRAY[]::TEXT[]),
('Similarly', 'similarly_us.mp3', 'adverb', 'B1', 'in almost the same way', '', 'It is a little cheaper than other similarly sized cars.', '', ARRAY[]::TEXT[]),
('Simple', 'simple_us.mp3', 'adjective', 'B1', 'not complicated; easy to understand or do', '', 'a simple solution/explanation/question/task/example', '', ARRAY[]::TEXT[]),
('Simply', 'simply_us.mp3', 'adverb', 'B1', 'used to emphasize how easy or basic something is', '', 'To order, simply click here.', '', ARRAY[]::TEXT[]),
('Simulate', 'simulate_us.mp3', 'verb', 'B1', 'to create particular conditions that exist in real life using computers, models, etc., usually for study or training purposes', '', 'Computer software can be used to simulate conditions on the seabed.', '', ARRAY[]::TEXT[]),
('Simulation', 'simulation_us.mp3', 'noun', 'B1', 'a situation in which a particular set of conditions is created artificially in order to study or experience something that could exist in reality', '', 'a computer simulation of how the planet functions', '', ARRAY[]::TEXT[]),
('Simultaneously', 'simultaneously_us.mp3', 'adverb', 'B1', 'at the same time as something else', '', 'The game will be broadcast simultaneously on TV and radio.', '', ARRAY[]::TEXT[]),
('Sin', 'sin_us.mp3', 'noun', 'B1', 'an offence against God or against a religious or moral law', '', 'to commit a sin', '', ARRAY[]::TEXT[]),
('Since', 'since_us.mp3', 'adverb', 'B1', 'from a time in the past until a later past time, or until now', '', 'She went for a run on Monday and has not been seen since.', '', ARRAY[]::TEXT[]),
('Since', 'since_us.mp3', 'conjunction', 'B1', 'from an event in the past until a later past event, or until now', '', 'Cath hasn''t phoned since she went to Berlin.', '', ARRAY[]::TEXT[]),
('Since', 'since_us.mp3', 'preposition', 'B1', 'from a time in the past until a later past time, or until now', '', 'She''s been off work since Tuesday.', '', ARRAY[]::TEXT[]),
('Sincere', 'sincere_us.mp3', 'adjective', 'B1', 'showing what you really think or feel', '', 'a sincere apology', '', ARRAY[]::TEXT[]),
('Sing', 'sing_us.mp3', 'verb', 'B1', 'to make musical sounds with your voice in the form of a song or tune', '', 'I just can''t sing in tune!', '', ARRAY[]::TEXT[]),
('Singer', 'singer_us.mp3', 'noun', 'B1', 'a person who sings, or whose job is singing, especially in public', '', 'She''s a wonderful singer.', '', ARRAY[]::TEXT[]),
('Singing', 'singing_us.mp3', 'noun', 'B1', 'the activity of making musical sounds with your voice', '', 'the beautiful singing of birds', '', ARRAY[]::TEXT[]),
('Single', 'single_us.mp3', 'adjective', 'B1', 'only one', '', 'He sent her a single red rose.', '', ARRAY[]::TEXT[]),
('Single', 'single_us.mp3', 'noun', 'B1', 'a ticket that allows you to travel to a place but not back again', '', 'How much is a single to York?', '', ARRAY[]::TEXT[]),
('Sink', 'sink_us.mp3', 'verb', 'B1', 'to go down below the surface or towards the bottom of a liquid or soft substance', '', 'The ship sank to the bottom of the sea.', '', ARRAY[]::TEXT[]),
('Sir', 'sir_us.mp3', 'noun', 'B1', 'used as a polite way of addressing a man whose name you do not know, for example in a shop or restaurant', '', 'Good morning, sir. Can I help you?', '', ARRAY[]::TEXT[]),
('Sister', 'sister_us.mp3', 'noun', 'B1', 'a girl or woman who has the same mother and father as another person', '', 'She''s my sister.', '', ARRAY[]::TEXT[]),
('Sit', 'sit_us.mp3', 'verb', 'B1', 'to rest your weight on your bottom with your back straight, for example on/in a chair', '', 'She sat and stared at the letter in front of her.', '', ARRAY[]::TEXT[]),
('Site', 'site_us.mp3', 'noun', 'B1', 'a place where a building, town, etc. was, is or will be located', '', 'the site of a sixteenth-century abbey', '', ARRAY[]::TEXT[]),
('Situated', 'situated_us.mp3', 'adjective', 'B1', 'in a particular place or position', '', 'My bedroom was situated on the top floor of the house.', '', ARRAY[]::TEXT[]),
('Situation', 'situation_us.mp3', 'noun', 'B1', 'all the circumstances and things that are happening at a particular time and in a particular place', '', 'the present economic/financial/political situation', '', ARRAY[]::TEXT[]),
('Six', 'six_us.mp3', 'number', 'B1', '6', '', 'There are six cookies left.', '', ARRAY[]::TEXT[]),
('Size', 'size_us.mp3', 'noun', 'B1', 'how large or small a person or thing is', '', 'population/sample/group/class size', '', ARRAY[]::TEXT[]),
('Sketch', 'sketch_us.mp3', 'noun', 'B1', 'a simple picture that is drawn quickly and does not have many details', '', 'The artist is making sketches for his next painting.', '', ARRAY[]::TEXT[]),
('Ski', 'ski_us.mp3', 'adjective', 'B1', 'connected with the sport of skiing', '', 'a ski resort', '', ARRAY[]::TEXT[]),
('Ski', 'ski_us.mp3', 'noun', 'B1', 'one of a pair of long narrow pieces of wood, metal or plastic that you attach to boots so that you can move smoothly over snow', '', 'a pair of skis', '', ARRAY[]::TEXT[]),
('Ski', 'ski_us.mp3', 'verb', 'B1', 'to move over snow on skis, especially as a sport', '', 'Our children want to learn to ski.', '', ARRAY[]::TEXT[]),
('Skiing', 'skiing_us.mp3', 'noun', 'B1', 'the sport or activity of moving over snow on skis', '', 'He also enjoys skiing and mountain biking.', '', ARRAY[]::TEXT[]),
('Skill', 'skill_us.mp3', 'noun', 'B1', 'the ability to do something well', '', 'The job requires skill and an eye for detail.', '', ARRAY[]::TEXT[]),
('Skilled', 'skilled_us.mp3', 'adjective', 'B1', 'having enough ability, experience and knowledge to be able to do something well', '', 'a skilled engineer/negotiator/craftsman', '', ARRAY[]::TEXT[]),
('Skin', 'skin_us.mp3', 'noun', 'B1', 'the layer of tissue that covers the body', '', 'to have dark/pale skin', '', ARRAY[]::TEXT[]),
('Skip', 'skip_us.mp3', 'verb', 'B1', 'to move forwards lightly and quickly making a little jump with each step', '', 'She skipped happily along beside me.', '', ARRAY[]::TEXT[]),
('Skirt', 'skirt_us.mp3', 'noun', 'B1', 'a piece of clothing that hangs from the middle part of the body', '', 'a short/long/pleated/denim skirt', '', ARRAY[]::TEXT[]),
('Skull', 'skull_us.mp3', 'noun', 'B1', 'the bone structure that forms the head and surrounds and protects the brain', '', 'a fractured skull', '', ARRAY[]::TEXT[]),
('Sky', 'sky_us.mp3', 'noun', 'B1', 'the space above the earth that you can see when you look up, where clouds and the sun, moon and stars appear', '', 'The sky suddenly went dark and it started to rain.', '', ARRAY[]::TEXT[]),
('Slam', 'slam_us.mp3', 'verb', 'B1', 'to shut, or to make something shut, with a lot of force, making a loud noise', '', 'I heard the door slam behind him.', '', ARRAY[]::TEXT[]),
('Slap', 'slap_us.mp3', 'verb', 'B1', 'to hit somebody/something with the flat part of your hand', '', 'She slapped his face hard.', '', ARRAY[]::TEXT[]),
('Slash', 'slash_us.mp3', 'verb', 'B1', 'to make a long cut with a sharp object, especially in a violent way', '', 'slash something, Someone had slashed the tyres on my car.', '', ARRAY[]::TEXT[]),
('Slave', 'slave_us.mp3', 'noun', 'B1', 'a person who is owned by another person and is forced to work for and obey them', '', 'A former slave, he graduated from Clafflin University in South Carolina.', '', ARRAY[]::TEXT[]),
('Slavery', 'slavery_us.mp3', 'noun', 'B1', 'the state of being forced to work as a slave', '', 'to be sold into slavery', '', ARRAY[]::TEXT[]),
('Sleep', 'sleep_us.mp3', 'noun', 'B1', 'the natural state of rest in which your eyes are closed, your body is not active, and your mind is not conscious', '', 'I need to get some sleep.', '', ARRAY[]::TEXT[]),
('Sleep', 'sleep_us.mp3', 'verb', 'B1', 'to rest with your eyes closed and your mind and body not active', '', 'Let her sleep—it''ll do her good.', '', ARRAY[]::TEXT[]),
('Slice', 'slice_us.mp3', 'noun', 'B1', 'a thin flat piece of bread, meat, cheese, etc. that has been cut off a larger piece; a piece of cake that has been cut from a larger cake', '', 'Cut the meat into thin slices.', '', ARRAY[]::TEXT[]),
('Slice', 'slice_us.mp3', 'verb', 'B1', 'to cut something into slices', '', 'to slice (up) onions', '', ARRAY[]::TEXT[]),
('Slide', 'slide_us.mp3', 'noun', 'B1', 'one page of an electronic presentation, that may contain text and images, that is usually viewed on a computer screen or projected onto a larger screen', '', 'Here''s a slide showing target markets.', '', ARRAY[]::TEXT[]),
('Slide', 'slide_us.mp3', 'verb', 'B1', 'to move easily over a smooth or wet surface; to make something move in this way', '', 'As I turned left on a bend, my car started to slide.', '', ARRAY[]::TEXT[]),
('Slight', 'slight_us.mp3', 'adjective', 'B1', 'very small in degree', '', 'a slight increase/change/difference', '', ARRAY[]::TEXT[]),
('Slightly', 'slightly_us.mp3', 'adverb', 'B1', 'a little', '', 'a slightly different version', '', ARRAY[]::TEXT[]),
('Slip', 'slip_us.mp3', 'verb', 'B1', 'to slide a short distance by accident so that you fall or nearly fall', '', 'She slipped and landed flat on her back.', '', ARRAY[]::TEXT[]),
('Slogan', 'slogan_us.mp3', 'noun', 'B1', 'a word or phrase that is easy to remember, used for example by a political party or in advertising to attract people’s attention or to suggest an idea quickly', '', 'an advertising slogan', '', ARRAY[]::TEXT[]),
('Slope', 'slope_us.mp3', 'noun', 'B1', 'a surface or piece of land that slopes (= is higher at one end than the other)', '', 'on a slope, The town is built on a slope.', '', ARRAY[]::TEXT[]),
('Slope', 'slope_us.mp3', 'verb', 'B1', 'to be at an angle so that it is higher at one end than the other', '', 'a sloping roof', '', ARRAY[]::TEXT[]),
('Slot', 'slot_us.mp3', 'noun', 'B1', 'a long, narrow opening, into which you put or fit something', '', 'to put some coins in the slot', '', ARRAY[]::TEXT[]),
('Slow', 'slow_us.mp3', 'adjective', 'B1', 'not moving, acting or done quickly; taking a long time; not fast', '', 'a slow pace/speed', '', ARRAY[]::TEXT[]),
('Slow', 'slow_us.mp3', 'verb', 'B1', 'to go or to make something/somebody go at a slower speed or be less active', '', 'Economic growth has slowed a little.', '', ARRAY[]::TEXT[]),
('Slowly', 'slowly_us.mp3', 'adverb', 'B1', 'at a slow speed; not quickly', '', 'to move/walk/turn slowly', '', ARRAY[]::TEXT[]),
('Small', 'small_us.mp3', 'adjective', 'B1', 'not large in size, number, degree, amount, etc.', '', 'a small town/village/community', '', ARRAY[]::TEXT[]),
('Smart', 'smart_us.mp3', 'adjective', 'B1', 'looking clean and neat; well dressed in fashionable and/or formal clothes', '', 'I have to be smart for work.', '', ARRAY[]::TEXT[]),
('Smartphone', 'smartphone_us.mp3', 'noun', 'B1', 'a mobile phone that also has some of the functions of a computer, for example the facility to use apps and the internet', '', 'You can use your smartphone to access the internet.', '', ARRAY[]::TEXT[]),
('Smash', 'smash_us.mp3', 'verb', 'B1', 'to break something, or to be broken, violently and noisily into many pieces', '', 'Several windows had been smashed.', '', ARRAY[]::TEXT[]),
('Smell', 'smell_us.mp3', 'noun', 'B1', 'the quality of something that people and animals sense through their noses', '', 'a sweet/pleasant smell', '', ARRAY[]::TEXT[]),
('Smell', 'smell_us.mp3', 'verb', 'B1', 'to have a particular smell', '', '+ adj., The room smelt damp.', '', ARRAY[]::TEXT[]),
('Smile', 'smile_us.mp3', 'noun', 'B1', 'the expression that you have on your face when you are happy or you think something is funny, in which the corners of your mouth turn upwards', '', 'a broad/warm/bright/slight smile', '', ARRAY[]::TEXT[]),
('Smile', 'smile_us.mp3', 'verb', 'B1', 'to make a smile appear on your face', '', 'to smile slightly/broadly', '', ARRAY[]::TEXT[]),
('Smoke', 'smoke_us.mp3', 'noun', 'B1', 'the grey, white or black gas that is produced by something burning', '', 'cigarette/tobacco smoke', '', ARRAY[]::TEXT[]),
('Smoke', 'smoke_us.mp3', 'verb', 'B1', 'to take smoke from a cigarette, pipe, etc. into your mouth and let it out again', '', 'Do you mind if I smoke?', '', ARRAY[]::TEXT[]),
('Smoking', 'smoking_us.mp3', 'noun', 'B1', 'the activity or habit of smoking cigarettes, etc.', '', 'No Smoking (= for example, on a notice)', '', ARRAY[]::TEXT[]),
('Smooth', 'smooth_us.mp3', 'adjective', 'B1', 'completely flat and even, without any rough areas or holes', '', 'the smooth surface of the metal', '', ARRAY[]::TEXT[]),
('Snake', 'snake_us.mp3', 'noun', 'B1', 'a reptile with a very long thin body and no legs. There are many types of snake, some of which are poisonous.', '', 'a snake coiled up in the grass', '', ARRAY[]::TEXT[]),
('Snap', 'snap_us.mp3', 'verb', 'B1', 'to break something suddenly with a sharp noise; to be broken in this way', '', 'snap something, The wind had snapped the tree in two.', '', ARRAY[]::TEXT[]),
('Snow', 'snow_us.mp3', 'noun', 'B1', 'small soft white pieces (called flakes) of frozen water that fall from the sky in cold weather; this substance when it is lying on the ground', '', 'Snow was falling heavily.', '', ARRAY[]::TEXT[]),
('Snow', 'snow_us.mp3', 'verb', 'B1', 'when it snows, snow falls from the sky', '', 'It''s been snowing heavily all day.', '', ARRAY[]::TEXT[]),
('So', 'so_us.mp3', 'adverb', 'B1', 'to such a great degree', '', 'Don''t look so angry.', '', ARRAY[]::TEXT[]),
('So', 'so_us.mp3', 'conjunction', 'B1', 'used to show the reason for something', '', 'It was still painful, so I went to see a doctor.', '', ARRAY[]::TEXT[]),
('So-called', 'so-called_us.mp3', 'adjective', 'B1', 'used to show that you do not think that the word or phrase that is being used to describe somebody/something is appropriate', '', 'the opinion of a so-called ‘expert’', '', ARRAY[]::TEXT[]),
('Soak', 'soak_us.mp3', 'verb', 'B1', 'to put something in liquid for a time so that it becomes completely wet; to become completely wet in this way', '', 'soak something (in something), I usually soak the beans overnight.', '', ARRAY[]::TEXT[]),
('Soap', 'soap_us.mp3', 'noun', 'B1', 'a substance that you use with water for washing your body', '', 'Wash the affected area with soap and water.', '', ARRAY[]::TEXT[]),
('Soar', 'soar_us.mp3', 'verb', 'B1', 'if the value, amount or level of something soars, it rises very quickly', '', 'soaring costs/prices/temperatures', '', ARRAY[]::TEXT[]),
('Soccer', 'soccer_us.mp3', 'noun', 'B1', 'a game played by two teams of 11 players, using a round ball which players kick up and down the playing field. Teams try to kick the ball into the other team’s goal.', '', 'I played soccer when I was younger.', '', ARRAY[]::TEXT[]),
('Social', 'social_us.mp3', 'adjective', 'B1', 'connected with activities in which people meet each other for pleasure', '', 'She has a busy social life.', '', ARRAY[]::TEXT[]),
('Socialist', 'socialist_us.mp3', 'adjective', 'B1', 'connected with socialism', '', 'socialist beliefs', '', ARRAY[]::TEXT[]),
('Society', 'society_us.mp3', 'noun', 'B1', 'people in general, living together in communities', '', 'She believes that the arts benefit society as a whole.', '', ARRAY[]::TEXT[]),
('Sock', 'sock_us.mp3', 'noun', 'B1', 'a piece of clothing that is worn over the foot, ankle and lower part of the leg, especially inside a shoe', '', 'a pair of socks', '', ARRAY[]::TEXT[]),
('Soft', 'soft_us.mp3', 'adjective', 'B1', 'changing shape easily when pressed; not stiff or hard', '', 'soft margarine', '', ARRAY[]::TEXT[]),
('Software', 'software_us.mp3', 'noun', 'B1', 'the programs used by a computer for doing particular jobs', '', 'management/editing software', '', ARRAY[]::TEXT[]),
('Soil', 'soil_us.mp3', 'noun', 'B1', 'the top layer of the earth in which plants, trees, etc. grow', '', 'instruments for measuring soil moisture', '', ARRAY[]::TEXT[]),
('Solar', 'solar_us.mp3', 'adjective', 'B1', 'of or connected with the sun', '', 'solar radiation', '', ARRAY[]::TEXT[]),
('Soldier', 'soldier_us.mp3', 'noun', 'B1', 'a member of an army, especially one who is not an officer', '', 'They visited the graves of US soldiers killed in the First World War.', '', ARRAY[]::TEXT[]),
('Sole', 'sole_us.mp3', 'adjective', 'B1', 'only; single', '', 'the sole surviving member of the family', '', ARRAY[]::TEXT[]),
('Solely', 'solely_us.mp3', 'adverb', 'B1', 'only; not involving somebody/something else', '', 'She was motivated solely by self-interest.', '', ARRAY[]::TEXT[]),
('Solicitor', 'solicitor_us.mp3', 'noun', 'B1', 'a lawyer who prepares legal documents, for example for the sale of land or buildings, advises people on legal matters, and can speak for them in some courts of law', '', 'Her first step was to contact a solicitor for advice.', '', ARRAY[]::TEXT[]),
('Solid', 'solid_us.mp3', 'adjective', 'B1', 'hard; not in the form of a liquid or gas', '', 'The planet Jupiter may have no solid surface at all.', '', ARRAY[]::TEXT[]),
('Solid', 'solid_us.mp3', 'noun', 'B1', 'a substance or an object that is solid, not a liquid or a gas', '', 'liquids and solids', '', ARRAY[]::TEXT[]),
('Solidarity', 'solidarity_us.mp3', 'noun', 'B1', 'support by one person or group of people for another because they share feelings, opinions, aims, etc.', '', 'community solidarity', '', ARRAY[]::TEXT[]),
('Solo', 'solo_us.mp3', 'adjective', 'B1', 'done by one person alone, without anyone helping them', '', 'his first solo flight', '', ARRAY[]::TEXT[]),
('Solo', 'solo_us.mp3', 'noun', 'B1', 'a piece of music, dance or entertainment performed by only one person', '', 'The song features an extended guitar solo.', '', ARRAY[]::TEXT[]),
('Solution', 'solution_us.mp3', 'noun', 'B1', 'a way of solving a problem or dealing with a difficult situation', '', 'Attempts to find a solution have failed.', '', ARRAY[]::TEXT[]),
('Solve', 'solve_us.mp3', 'verb', 'B1', 'to find a way of dealing with a problem or difficult situation', '', 'Attempts are being made to solve the problem of waste disposal.', '', ARRAY[]::TEXT[]),
('Some', 'some_us.mp3', 'determiner', 'B1', 'used with uncountable nouns or plural countable nouns to mean ‘an amount of’ or ‘a number of’, when the amount or number is not given', '', 'There''s some milk in the fridge.', '', ARRAY[]::TEXT[]),
('Some', 'some_us.mp3', 'pronoun', 'B1', 'used to refer to an amount of something or a number of people or things when the amount or number is not given', '', 'Some disapprove of the idea.', '', ARRAY[]::TEXT[]),
('Somebody', 'somebody_us.mp3', 'pronoun', 'B1', 'a person who is not known or mentioned by name', '', 'Somebody should have told me.', '', ARRAY[]::TEXT[]),
('Somehow', 'somehow_us.mp3', 'adverb', 'B1', 'in a way that is not known or certain', '', 'We must stop him from seeing her somehow.', '', ARRAY[]::TEXT[]),
('Someone', 'someone_us.mp3', 'pronoun', 'B1', 'a person who is not known or mentioned by name', '', 'There''s someone at the door.', '', ARRAY[]::TEXT[]),
('Something', 'something_us.mp3', 'pronoun', 'B1', 'a thing that is not known or mentioned by name', '', 'We stopped for something to eat.', '', ARRAY[]::TEXT[]),
('Sometime', 'sometime_us.mp3', 'adverb', 'B1', 'at a time that you do not know exactly or has not yet been decided', '', 'I saw him sometime last summer.', '', ARRAY[]::TEXT[]),
('Sometimes', 'sometimes_us.mp3', 'adverb', 'B1', 'occasionally rather than all of the time', '', 'Sometimes I go by car.', '', ARRAY[]::TEXT[]),
('Somewhat', 'somewhat_us.mp3', 'adverb', 'B1', 'to some degree', '', 'somewhat different/similar', '', ARRAY[]::TEXT[]),
('Somewhere', 'somewhere_us.mp3', 'adverb', 'B1', 'in, at or to a place that you do not know or do not mention by name', '', 'I read somewhere that she refuses to do interviews.', '', ARRAY[]::TEXT[]),
('Somewhere', 'somewhere_us.mp3', 'pronoun', 'B1', 'a place that you do not know or do not mention by name', '', 'We need to find somewhere to live.', '', ARRAY[]::TEXT[]),
('Son', 'son_us.mp3', 'noun', 'B1', 'a person’s male child', '', 'their four-year-old son', '', ARRAY[]::TEXT[]),
('Song', 'song_us.mp3', 'noun', 'B1', 'a short piece of music with words that you sing', '', 'a love/pop/rock song', '', ARRAY[]::TEXT[]),
('Soon', 'soon_us.mp3', 'adverb', 'B1', 'in a short time from now; a short time after something else has happened', '', 'She sold the house soon after her husband died.', '', ARRAY[]::TEXT[]),
('Sophisticated', 'sophisticated_us.mp3', 'adjective', 'B1', 'clever and complicated in the way that it works or is presented', '', 'highly sophisticated computer systems', '', ARRAY[]::TEXT[]),
('Sorry', 'sorry_us.mp3', 'adjective', 'B1', 'feeling sad and ashamed about something that has been done', '', 'sorry about something, We''re very sorry about the damage to your car.', '', ARRAY[]::TEXT[]),
('Sorry', 'sorry_us.mp3', 'exclamation', 'B1', 'used when you are apologizing for something', '', 'Sorry I''m late!', '', ARRAY[]::TEXT[]),
('Sort', 'sort_us.mp3', 'noun', 'B1', 'a group or type of people or things that are similar in a particular way', '', 'sort of somebody/something, ‘What sort of music do you like?’ ‘Oh, all sorts.’', '', ARRAY[]::TEXT[]),
('Sort', 'sort_us.mp3', 'verb', 'B1', 'to arrange things in groups or in a particular order according to their type, etc.; to separate things of one type from others', '', 'sort something, I started at the bottom, answering phones and sorting the mail.', '', ARRAY[]::TEXT[]),
('Soul', 'soul_us.mp3', 'noun', 'B1', 'the spiritual part of a person, believed to exist after death', '', 'He believed his immortal soul was in peril.', '', ARRAY[]::TEXT[]),
('Sound', 'sound_us.mp3', 'adjective', 'B1', 'sensible; that you can rely on and that will probably give good results', '', 'He''s a person of very sound judgement.', '', ARRAY[]::TEXT[]),
('Sound', 'sound_us.mp3', 'noun', 'B1', 'something that you can hear', '', 'a loud/soft/faint sound', '', ARRAY[]::TEXT[]),
('Sound', 'sound_us.mp3', 'verb', 'B1', 'to give a particular impression when heard or read about', '', '+ adj., to sound good/great/right/interesting', '', ARRAY[]::TEXT[]),
('Soup', 'soup_us.mp3', 'noun', 'B1', 'a liquid food made by boiling meat, vegetables, etc. in water, often eaten as the first course of a meal', '', 'a bowl/cup of soup', '', ARRAY[]::TEXT[]),
('Source', 'source_us.mp3', 'noun', 'B1', 'a place, person or thing that you get something from', '', 'renewable energy sources', '', ARRAY[]::TEXT[]),
('South', 'south_us.mp3', 'adjective', 'B1', 'in or towards the south', '', 'South Wales', '', ARRAY[]::TEXT[]),
('South', 'south_us.mp3', 'adverb', 'B1', 'towards the south', '', 'This room faces south.', '', ARRAY[]::TEXT[]),
('South', 'south_us.mp3', 'noun', 'B1', 'the direction that is on your right when you watch the sun rise; one of the four main points of the compass', '', 'Which way is south?', '', ARRAY[]::TEXT[]),
('Southern', 'southern_us.mp3', 'adjective', 'B1', 'located in the south or facing south; connected with or typical of the south part of the world or a region', '', 'the southern slopes of the mountains', '', ARRAY[]::TEXT[]),
('Sovereignty', 'sovereignty_us.mp3', 'noun', 'B1', 'complete power to govern a country', '', 'The country claimed sovereignty over the island.', '', ARRAY[]::TEXT[]),
('Space', 'space_us.mp3', 'noun', 'B1', 'the area outside the earth’s atmosphere where all the other planets and stars are', '', 'in space, Valentina Tereshkova was the first woman in space.', '', ARRAY[]::TEXT[]),
('Spam', 'spam_us.mp3', 'noun', 'B1', 'advertising material sent by email to people who have not asked for it; advertising material on the internet that is not wanted', '', 'to send/block spam', '', ARRAY[]::TEXT[]),
('Span', 'span_us.mp3', 'noun', 'B1', 'the length of time that something lasts or is able to continue', '', 'I worked with him over a span of six years.', '', ARRAY[]::TEXT[]),
('Span', 'span_us.mp3', 'verb', 'B1', 'to last all through a period of time or to cover the whole of it', '', 'His acting career spanned 55 years.', '', ARRAY[]::TEXT[]),
('Spare', 'spare_us.mp3', 'adjective', 'B1', 'available to do what you want with rather than work', '', 'He''s studying music in his spare time.', '', ARRAY[]::TEXT[]),
('Spare', 'spare_us.mp3', 'verb', 'B1', 'to make something such as time or money available to somebody or for something, especially when it requires an effort for you to do this', '', 'spare something/somebody, I''d love to have a break, but I can''t spare the time just now.', '', ARRAY[]::TEXT[]),
('Spark', 'spark_us.mp3', 'verb', 'B1', 'to cause something to start or develop, especially suddenly', '', 'spark something, The proposal would spark a storm of protest around the country.', '', ARRAY[]::TEXT[]),
('Speak', 'speak_us.mp3', 'verb', 'B1', 'to talk to somebody about something; to have a conversation with somebody', '', 'speak to somebody, The President refused to speak to reporters.', '', ARRAY[]::TEXT[]),
('Speaker', 'speaker_us.mp3', 'noun', 'B1', 'a person who gives a talk or makes a speech', '', 'He was a guest speaker at the conference.', '', ARRAY[]::TEXT[]),
('Special', 'special_us.mp3', 'adjective', 'B1', 'not ordinary or usual; different from what is normal', '', 'The school will only allow this in special circumstances.', '', ARRAY[]::TEXT[]),
('Specialist', 'specialist_us.mp3', 'adjective', 'B1', 'having or involving expert knowledge of a particular area of work, study or medicine', '', 'specialist knowledge/training/skills', '', ARRAY[]::TEXT[]),
('Specialist', 'specialist_us.mp3', 'noun', 'B1', 'a person who is an expert in a particular area of work or study', '', 'specialist in something, a specialist in Japanese history', '', ARRAY[]::TEXT[]),
('Specialize', 'specialize_us.mp3', 'verb', 'B1', 'to become an expert in a particular area of work, study or business; to spend more time on one area of work, etc. than on others', '', 'Many students prefer not to specialize too soon.', '', ARRAY[]::TEXT[]),
('Specialized', 'specialized_us.mp3', 'adjective', 'B1', 'designed or developed for a particular purpose or area of knowledge', '', 'specialized equipment', '', ARRAY[]::TEXT[]),
('Species', 'species_us.mp3', 'noun', 'B1', 'a group into which animals, plants, etc. that are able to have sex with each other and produce healthy young are divided, smaller than a genus and identified by a Latin name', '', 'a conservation area for endangered species', '', ARRAY[]::TEXT[]),
('Specific', 'specific_us.mp3', 'adjective', 'B1', 'connected with one particular thing only', '', 'specific needs/requirements', '', ARRAY[]::TEXT[]),
('Specifically', 'specifically_us.mp3', 'adverb', 'B1', 'connected with or intended for one particular thing only', '', 'liquid vitamins specifically designed for children', '', ARRAY[]::TEXT[]),
('Specification', 'specification_us.mp3', 'noun', 'B1', 'a detailed description of how something is, or should be, designed or made', '', 'the technical specifications of the new model (= of car)', '', ARRAY[]::TEXT[]),
('Specify', 'specify_us.mp3', 'verb', 'B1', 'to state something, especially by giving an exact measurement, time, exact instructions, etc.', '', 'specify something, Remember to specify your size when ordering clothes.', '', ARRAY[]::TEXT[]),
('Specimen', 'specimen_us.mp3', 'noun', 'B1', 'a small amount of something that shows what the rest of it is like', '', 'Astronauts have brought back specimens of rock from the moon.', '', ARRAY[]::TEXT[]),
('Spectacle', 'spectacle_us.mp3', 'noun', 'B1', 'two lenses in a frame that rests on the nose and ears. People wear spectacles in order to be able to see better or to protect their eyes from bright light.', '', 'a pair of spectacles', '', ARRAY[]::TEXT[]),
('Spectacular', 'spectacular_us.mp3', 'adjective', 'B1', 'very impressive', '', 'The coastal road has spectacular scenery.', '', ARRAY[]::TEXT[]),
('Spectator', 'spectator_us.mp3', 'noun', 'B1', 'a person who is watching an event, especially a sports event', '', 'The new football stadium will hold 75 000 spectators.', '', ARRAY[]::TEXT[]),
('Spectrum', 'spectrum_us.mp3', 'noun', 'B1', 'a band of coloured lights in order of their wavelengths, as seen in a rainbow and into which light may be separated', '', 'A spectrum is formed by a ray of light passing through a prism.', '', ARRAY[]::TEXT[]),
('Speculate', 'speculate_us.mp3', 'verb', 'B1', 'to form an opinion about something without knowing all the details or facts', '', 'speculate (about/on/as to something), We all speculated about the reasons for her resignation.', '', ARRAY[]::TEXT[]),
('Speculation', 'speculation_us.mp3', 'noun', 'B1', 'the act of forming opinions about what has happened or what might happen without knowing all the facts', '', 'His private life is the subject of much speculation.', '', ARRAY[]::TEXT[]),
('Speech', 'speech_us.mp3', 'noun', 'B1', 'a formal talk that a person gives to an audience', '', 'Several people made speeches at the wedding.', '', ARRAY[]::TEXT[]),
('Speed', 'speed_us.mp3', 'noun', 'B1', 'the rate at which somebody/something moves or travels', '', 'at … speed, at high/low/full/top speed', '', ARRAY[]::TEXT[]),
('Speed', 'speed_us.mp3', 'verb', 'B1', 'to move along quickly', '', 'They sped off to get help.', '', ARRAY[]::TEXT[]),
('Spell', 'spell_us.mp3', 'noun', 'B1', 'a short period of time during which something lasts', '', 'We had a spell of warm weather in April.', '', ARRAY[]::TEXT[]),
('Spell', 'spell_us.mp3', 'verb', 'B1', 'to say or write the letters of a word in the correct order', '', 'How do you spell your surname?', '', ARRAY[]::TEXT[]),
('Spelling', 'spelling_us.mp3', 'noun', 'B1', 'the act of forming words correctly from individual letters; the ability to do this', '', 'the differences between British and American spelling', '', ARRAY[]::TEXT[]),
('Spend', 'spend_us.mp3', 'verb', 'B1', 'to give money to pay for goods, services, etc.', '', 'spend something, I''ve spent all my money already.', '', ARRAY[]::TEXT[]),
('Spending', 'spending_us.mp3', 'noun', 'B1', 'the amount of money that is spent by a government, an organization or a person', '', 'to increase/cut/reduce spending', '', ARRAY[]::TEXT[]),
('Sphere', 'sphere_us.mp3', 'noun', 'B1', 'a solid figure that is completely round, with every point on its surface at an equal distance from the centre', '', 'The Earth is not a perfect sphere.', '', ARRAY[]::TEXT[]),
('Spice', 'spice_us.mp3', 'noun', 'B1', 'one of the various types of powder or seed that come from plants and are used in cooking. Spices have a strong taste and smell.', '', 'common spices such as ginger and cinnamon', '', ARRAY[]::TEXT[]),
('Spicy', 'spicy_us.mp3', 'adjective', 'B1', 'having a strong taste because spices have been added to it', '', 'I don''t like spicy food.', '', ARRAY[]::TEXT[]),
('Spider', 'spider_us.mp3', 'noun', 'B1', 'a small creature with eight thin legs. Many spiders spin webs to catch insects for food.', '', 'a poisonous spider', '', ARRAY[]::TEXT[]),
('Spill', 'spill_us.mp3', 'verb', 'B1', 'to flow over the edge of a container by accident; to make liquid do this', '', 'Water had spilled out of the bucket onto the floor.', '', ARRAY[]::TEXT[]),
('Spin', 'spin_us.mp3', 'noun', 'B1', 'a very fast turning movement', '', 'Only in the last 50 years have we had clocks accurate enough to measure changes in the earth''s spin.', '', ARRAY[]::TEXT[]),
('Spin', 'spin_us.mp3', 'verb', 'B1', 'to turn round and round quickly; to make something do this', '', '(+ adv./prep.), The plane was spinning out of control.', '', ARRAY[]::TEXT[]),
('Spine', 'spine_us.mp3', 'noun', 'B1', 'the row of small bones that are connected together down the middle of the back', '', 'A shiver went down my spine.', '', ARRAY[]::TEXT[]),
('Spirit', 'spirit_us.mp3', 'noun', 'B1', 'the part of a person that includes their mind, feelings and character rather than their body', '', 'You are underestimating the power of the human spirit to overcome difficulties.', '', ARRAY[]::TEXT[]),
('Spiritual', 'spiritual_us.mp3', 'adjective', 'B1', 'connected with the human spirit, rather than the body or physical things', '', 'a spiritual experience', '', ARRAY[]::TEXT[]),
('Spite', 'spite_us.mp3', 'noun', 'B1', 'a feeling of wanting to hurt or upset somebody', '', 'out of spite, I''m sure he only said it out of spite.', '', ARRAY[]::TEXT[]),
('Split', 'split_us.mp3', 'noun', 'B1', 'an argument or disagreement that divides a group of people or makes somebody separate from somebody else', '', 'Ten years after their acrimonious split, the band has reformed.', '', ARRAY[]::TEXT[]),
('Split', 'split_us.mp3', 'verb', 'B1', 'to divide, or to make something divide, into two or more parts', '', 'split something, He was a member of the team that split the atom in 1932.', '', ARRAY[]::TEXT[]),
('Spoil', 'spoil_us.mp3', 'verb', 'B1', 'to change something good into something bad, unpleasant, etc.', '', 'Our camping trip was spoilt by bad weather.', '', ARRAY[]::TEXT[]),
('Spoken', 'spoken_us.mp3', 'adjective', 'B1', 'involving speaking rather than writing; expressed in speech rather than in writing', '', 'spoken English', '', ARRAY[]::TEXT[]),
('Spokesman', 'spokesman_us.mp3', 'noun', 'B1', 'a person who speaks for a group or an organization', '', 'a police spokesman', '', ARRAY[]::TEXT[]),
('Spokesperson', 'spokesperson_us.mp3', 'noun', 'B1', 'a person who speaks for a group or an organization', '', 'a council spokesperson', '', ARRAY[]::TEXT[]),
('Spokeswoman', 'spokeswoman_us.mp3', 'noun', 'B1', 'a woman who speaks for a group or an organization', '', 'a government spokeswoman', '', ARRAY[]::TEXT[]),
('Sponsor', 'sponsor_us.mp3', 'noun', 'B1', 'a person or company that pays for a radio or television programme, or for a concert or sporting event, usually in return for advertising', '', 'The programme is funded by a number of corporate sponsors.', '', ARRAY[]::TEXT[]),
('Sponsor', 'sponsor_us.mp3', 'verb', 'B1', 'to pay the costs of a particular event, programme, etc. as a way of advertising', '', 'Sports events are no longer sponsored by the tobacco industry.', '', ARRAY[]::TEXT[]),
('Sponsorship', 'sponsorship_us.mp3', 'noun', 'B1', 'financial support from a sponsor', '', 'a $50 million sponsorship deal', '', ARRAY[]::TEXT[]),
('Spoon', 'spoon_us.mp3', 'noun', 'B1', 'a tool that has a handle with a shallow bowl at the end, used for mixing, serving and eating food', '', 'a plastic/metal spoon', '', ARRAY[]::TEXT[]),
('Sport', 'sport_us.mp3', 'noun', 'B1', 'activity that you do for pleasure and that needs physical effort or skill, usually done in a special area and according to fixed rules', '', 'There are excellent facilities for sport and recreation.', '', ARRAY[]::TEXT[]),
('Sporting', 'sporting_us.mp3', 'adjective', 'B1', 'connected with sports', '', 'a major sporting event', '', ARRAY[]::TEXT[]),
('Spot', 'spot_us.mp3', 'noun', 'B1', 'a small round area that has a different colour or feels different from the surface it is on', '', 'Which has spots, the leopard or the tiger?', '', ARRAY[]::TEXT[]),
('Spot', 'spot_us.mp3', 'verb', 'B1', 'to see or notice a person or thing, especially suddenly or when it is not easy to do so', '', 'spot somebody/something, Can you spot the difference between these two pictures?', '', ARRAY[]::TEXT[]),
('Spotlight', 'spotlight_us.mp3', 'noun', 'B1', 'a light with a single, very bright beam that can be directed at a particular place or person, especially a performer on the stage', '', 'The room was lit by spotlights.', '', ARRAY[]::TEXT[]),
('Spouse', 'spouse_us.mp3', 'noun', 'B1', 'a husband or wife', '', 'Fill in your spouse’s name here.', '', ARRAY[]::TEXT[]),
('Spread', 'spread_us.mp3', 'noun', 'B1', 'an increase in the amount or number of something that there is, or in the area that is affected by something', '', 'measures to halt the spread of the disease', '', ARRAY[]::TEXT[]),
('Spread', 'spread_us.mp3', 'verb', 'B1', 'to affect or make something affect, be known by, or be used by more and more people', '', 'The news had spread and was causing great excitement.', '', ARRAY[]::TEXT[]),
('Spring', 'spring_us.mp3', 'noun', 'B1', 'the season between winter and summer when plants begin to grow', '', 'The following spring, the three artists travelled to California.', '', ARRAY[]::TEXT[]),
('Spring', 'spring_us.mp3', 'verb', 'B1', 'to move suddenly and with one quick movement in a particular direction', '', 'The cat crouched ready to spring.', '', ARRAY[]::TEXT[]),
('Spy', 'spy_us.mp3', 'noun', 'B1', 'a person who tries to get secret information about another country, organization or person, especially somebody who is employed by a government or the police', '', 'He was denounced as a foreign spy.', '', ARRAY[]::TEXT[]),
('Spy', 'spy_us.mp3', 'verb', 'B1', 'to collect secret information about another country, organization or person', '', 'He spied for his government for more than ten years.', '', ARRAY[]::TEXT[]),
('Squad', 'squad_us.mp3', 'noun', 'B1', 'a section of a police force that deals with a particular type of crime', '', 'the drugs/fraud/bomb/riot squad', '', ARRAY[]::TEXT[]),
('Square', 'square_us.mp3', 'adjective', 'B1', 'having four straight equal sides and four angles of 90°', '', 'a square room', '', ARRAY[]::TEXT[]),
('Square', 'square_us.mp3', 'noun', 'B1', 'a shape with four straight sides of equal length and four angles of 90°; a piece of something that has this shape', '', 'First break the chocolate into squares.', '', ARRAY[]::TEXT[]),
('Squeeze', 'squeeze_us.mp3', 'verb', 'B1', 'to press something, especially with your fingers', '', 'to squeeze a tube of toothpaste', '', ARRAY[]::TEXT[]),
('Stab', 'stab_us.mp3', 'verb', 'B1', 'to push a sharp, pointed object, especially a knife, into somebody, killing or injuring them', '', 'He was stabbed to death in a racist attack.', '', ARRAY[]::TEXT[]),
('Stability', 'stability_us.mp3', 'noun', 'B1', 'the quality or state of being steady and not changing or being upset in any way (= the quality of being stable)', '', 'political/economic/social stability', '', ARRAY[]::TEXT[]),
('Stabilize', 'stabilize_us.mp3', 'verb', 'B1', 'to become or to make something become steady and unlikely to change; to make something stable', '', 'The patient''s condition stabilized.', '', ARRAY[]::TEXT[]),
('Stable', 'stable_us.mp3', 'adjective', 'B1', 'fixed or steady; not likely to move, change or fail', '', 'The patient''s condition is stable (= it is not getting worse).', '', ARRAY[]::TEXT[]),
('Stadium', 'stadium_us.mp3', 'noun', 'B1', 'a large sports ground surrounded by rows of seats and usually other buildings', '', 'a football/sports stadium', '', ARRAY[]::TEXT[]),
('Staff', 'staff_us.mp3', 'noun', 'B1', 'all the workers employed in an organization considered as a group', '', 'medical/nursing/teaching/coaching staff', '', ARRAY[]::TEXT[]),
('Stage', 'stage_us.mp3', 'noun', 'B1', 'a period or state that something/somebody passes through while developing or making progress', '', 'at… stage, I can''t make a decision at this stage.', '', ARRAY[]::TEXT[]),
('Stage', 'stage_us.mp3', 'verb', 'B1', 'to organize and present a play or an event for people to see', '', 'to stage a play/an event/an exhibition', '', ARRAY[]::TEXT[]),
('Stair', 'stair_us.mp3', 'noun', 'B1', 'a set of steps built between two floors inside a building', '', 'We had to carry the piano up three flights of stairs.', '', ARRAY[]::TEXT[]),
('Stake', 'stake_us.mp3', 'noun', 'B1', 'money that somebody invests in a company', '', 'a 20 per cent stake in the business', '', ARRAY[]::TEXT[]),
('Stall', 'stall_us.mp3', 'noun', 'B1', 'a table or small shop with an open front that people sell things from, especially at a market', '', 'He works on a market stall in the Square.', '', ARRAY[]::TEXT[]),
('Stamp', 'stamp_us.mp3', 'noun', 'B1', 'a small piece of paper with a design on it that you buy and stick on an envelope or a package before you post it', '', 'a 67p stamp', '', ARRAY[]::TEXT[]),
('Stance', 'stance_us.mp3', 'noun', 'B1', 'the opinions that somebody has about something and expresses publicly', '', 'What is the newspaper''s stance on the war?', '', ARRAY[]::TEXT[]),
('Stand', 'stand_us.mp3', 'noun', 'B1', 'an attitude towards something or an opinion that you make clear to people', '', 'He has avoided taking a firm stand.', '', ARRAY[]::TEXT[]),
('Stand', 'stand_us.mp3', 'verb', 'B1', 'to be on your feet; to be in a vertical position', '', 'She was too weak to stand.', '', ARRAY[]::TEXT[]),
('Standard', 'standard_us.mp3', 'adjective', 'B1', 'average or normal rather than having special or unusual features', '', 'the standard rate of tax (= paid by everyone)', '', ARRAY[]::TEXT[]),
('Standard', 'standard_us.mp3', 'noun', 'B1', 'a level of quality, especially one that people think is acceptable', '', 'There has been a fall in living standards.', '', ARRAY[]::TEXT[]),
('Standing', 'standing_us.mp3', 'adjective', 'B1', 'done from a position in which you are standing rather than sitting or running', '', 'a standing jump/start', '', ARRAY[]::TEXT[]),
('Star', 'star_us.mp3', 'noun', 'B1', 'a large ball of burning gas in space that we see as a point of light in the sky at night', '', 'There was a big moon and hundreds of stars were shining overhead.', '', ARRAY[]::TEXT[]),
('Star', 'star_us.mp3', 'verb', 'B1', 'to have one of the main parts in a film, play, etc.', '', 'star in something, He starred in that movie about the crazy professor.', '', ARRAY[]::TEXT[]),
('Stare', 'stare_us.mp3', 'verb', 'B1', 'to look at somebody/something for a long time', '', 'I screamed and everyone stared.', '', ARRAY[]::TEXT[]),
('Stark', 'stark_us.mp3', 'adjective', 'B1', 'unpleasant; real, and impossible to avoid', '', 'The author paints a stark picture of life in a prison camp.', '', ARRAY[]::TEXT[]),
('Start', 'start_us.mp3', 'noun', 'B1', 'the point at which something begins', '', 'If we don''t hurry, we''ll miss the start.', '', ARRAY[]::TEXT[]),
('Start', 'start_us.mp3', 'verb', 'B1', 'to begin doing or using something', '', 'start (something), I start work at nine.', '', ARRAY[]::TEXT[]),
('Starve', 'starve_us.mp3', 'verb', 'B1', 'to suffer or die because you do not have enough food to eat; to make somebody suffer or die in this way', '', 'The animals were left to starve to death.', '', ARRAY[]::TEXT[]),
('State', 'state_us.mp3', 'adjective', 'B1', 'provided or controlled by the government of a country', '', 'state officials/agencies', '', ARRAY[]::TEXT[]),
('State', 'state_us.mp3', 'noun', 'B1', 'a country considered as an organized political community controlled by one government', '', 'the Baltic States', '', ARRAY[]::TEXT[]),
('State', 'state_us.mp3', 'verb', 'B1', 'to formally write or say something, especially in a careful and clear way', '', 'state something, He has already stated his intention to run for election.', '', ARRAY[]::TEXT[]),
('Statement', 'statement_us.mp3', 'noun', 'B1', 'something that you say or write that gives information or an opinion', '', 'Are the following statements true or false?', '', ARRAY[]::TEXT[]),
('Station', 'station_us.mp3', 'noun', 'B1', 'a place where trains stop so that passengers can get on and off; the buildings connected with this', '', 'the main station', '', ARRAY[]::TEXT[]),
('Statistic', 'statistic_us.mp3', 'noun', 'B1', 'a collection of information shown in numbers', '', 'Analysis of crime statistics showed high levels of violent crime within the area.', '', ARRAY[]::TEXT[]),
('Statistical', 'statistical_us.mp3', 'adjective', 'B1', 'connected with or based on statistics', '', 'statistical analysis', '', ARRAY[]::TEXT[]),
('Statue', 'statue_us.mp3', 'noun', 'B1', 'a figure of a person or an animal in stone, metal, etc., usually the same size as in real life or larger', '', 'a bronze/marble statue', '', ARRAY[]::TEXT[]),
('Status', 'status_us.mp3', 'noun', 'B1', 'the legal position of a person, group or country', '', 'They were granted refugee status.', '', ARRAY[]::TEXT[]),
('Stay', 'stay_us.mp3', 'noun', 'B1', 'a period of staying; a visit', '', 'I enjoyed my stay in Prague.', '', ARRAY[]::TEXT[])
ON CONFLICT (word) DO NOTHING;
